### ISSUE TITLE
A minor fix in docs

### ISSUE THREAD

**Issue by nikoTM** [transistorsoft/cordova-background-geolocation-lt#10]
```Your callbackFn will be executed each time the device has changed-state between MOVING or STATIONARY. The callbackFn will be provided with a Location object as the 1st param, with the usual params (latitude, longitude, accuracy, speed, bearing, altitude), in addition to a taskId used to signal that your callback is finished.```

It says **Location object as the 1st param**, but as we see in the code below isMoving is the first param.

```
bgGeo.onMotionChange(function(isMoving, location, taskId) {
    if (isMoving) {
        console.log('Device has just started MOVING', location);
    } else {
        console.log('Device has just STOPPED', location);
    }
    bgGeo.finish(taskId);
})
```

**Comment by christocracy** [comment]
Thanks

On Wednesday, September 30, 2015, Garnik <notifications@github.com> wrote:

> Your callbackFn will be executed each time the device has changed-state
> between MOVING or STATIONARY. The callbackFn will be provided with a
> Location object as the 1st param, with the usual params (latitude,
> longitude, accuracy, speed, bearing, altitude), in addition to a taskId
> used to signal that your callback is finished.
>
> It says *Location object as the 1st param*, but as we see in the code
> below isMoving is the first param.
>
> bgGeo.onMotionChange(function(isMoving, location, taskId) {
>     if (isMoving) {
>         console.log('Device has just started MOVING', location);
>     } else {
>         console.log('Device has just STOPPED', location);
>     }
>     bgGeo.finish(taskId);
> })
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/10>
> .
>


-- 
Snet form Gmail Mobile

**Comment by phamminhvu** [comment]
I tried to run the SampleApp in Xcode 6.1
and got an issue when I try to build the app:

duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationManager.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationManager.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
ld: 12 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by christocracy** [comment]
Oh right, you're using XCode 6.1.  You **must** upgrade to `7.x`.  Problem will be solved.

**Comment by christocracy** [comment]
Fixed docs wrt `isMoving` flag at 1st position.
