### ISSUE TITLE
Geofence triggers late/not

### ISSUE THREAD

**Issue by tafh** [transistorsoft/cordova-background-geolocation-lt#1000]
## Your Environment
* Plugin version: 3.2.0
* Platform: Android
* OS version: 7,8,9
* Device manufacturer / model: Nexus 5, Honeywell CT 50, Samsung S9,
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
            debug: true,
            reset: true,
            distanceFilter = 5;
            foregroundService = true;
            fastestLocationUpdateInterval = 5;
            desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_HIGH;
            startOnBoot = true;
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            geofenceModeHighAccuracy = true;
```

## Expected Behavior
Geofences enter/exit events should trigger immediately. 

## Actual Behavior
Sometimes when the app is in foreground enter and exit events trigger late or not at all. 
I.e. an enter events triggers but the exit event will trigger late (i.e. 5 min after the actual physical exit).  

## Steps to Reproduce
We set geofences with 200m radius. It happens sometimes so there are no clear steps to reproduce...

## Debug logs
I have no debug logs because it happens only in the field. (using simulators and mocking in the office works perfectly)

**Comment by christocracy** [comment]
See wiki “Debugging”

**Comment by tafh** [comment]
But what use is a debug log if the geofence did trigger late or not at all. What would you expect to see, errors? 
Anyway, I'd like to know if there is something wrong with my config or something that I could improve. It just doesn't make sense why it only happens _sometimes_. And yes I've seen https://dontkillmyapp.com

**Comment by christocracy** [comment]
>But what use is a debug log if the geofence did trigger late or not at all

Logs are the *first* thing you look at when you have a problem.  I'm testing on 11 devices almost every day and geofences are remarkably consistent (except for the Huawei, of course, which never works):

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 9.0.0
- Google Pixel 3a @ Q
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 8.0.0
