### ISSUE TITLE
Not calling onActivityChange ios Simulator after change location

### ISSUE THREAD

**Issue by jvcjunior** [transistorsoft/cordova-background-geolocation-lt#1001]
## Your Environment
* Plugin version: ˆ3.2.0
* Platform: iOS or Android
* OS version: macOS Mojave 10.14.6
* Device manufacturer / model: iOS Emulator Iphone XS
* Cordova version (`cordova -v`):    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`):
```
You have been opted out of telemetry. To change this, run: cordova telemetry on.
Installed platforms:
  android 8.0.0
  ios 5.0.1
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      reset: false,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100, // Record a location every 100 meters.
      httpTimeout: 20000,
      disableElasticity: true,
      stopOnTerminate: false, // Don't stop tracking when app is terminated.
      foregroundService: true, // Prevent Android from terminating service due to memory pressure from other apps.
      startOnBoot: true, // <-- Auto start tr acking when device is powered-up.
      locationAuthorizationRequest: "Always",
      locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>, "data": "<%= timestamp %>"}',
      //debug: true,
    }).then(() => {
      console.log('BackgroundGeolocation Ready!');
    }).catch(e => console.error(e));
```

## Expected Behavior
Should call onActivityChange callback

## Actual Behavior
Not calling onActivityChange callback

## Steps to Reproduce

1.
2.
3.
4.

## Context
I'm trying to do some work when receive the callback of onActivityChange

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
That’s correct.  Simulators don’t have motion sensors (accelerometer, gyroscope, magnetometer).
