### ISSUE TITLE
E TSLocationManager:   ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by deepanjali11** [transistorsoft/cordova-background-geolocation-lt#1005]
## Your Environment
* Plugin version: 3.2.2
* Platform: Android
* OS version: 8.1
* Device manufacturer / model: Nexus6p
* Cordova version (`cordova -v`): 9
* Cordova platform version (`cordova platform ls`):Installed platforms:
  android 7.1.1
  ios 4.5.5
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

The application shouldn't crash
## Actual Behavior

App crash
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
10-07 16:01:33.365  8239  8239 E TSLocationManager: [c.t.l.a.BackgroundGeolocation$e uncaughtException]
10-07 16:01:33.365  8239  8239 E TSLocationManager:   ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground()
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
10-07 16:01:33.204  8239  8239 W TSLocationManager:   ⚠️  Failed to find SingleLocationRequest: 576
10-07 16:01:33.233  8239 10524 I TSLocationManager: [c.t.l.data.sqlite.b persist]
10-07 16:01:33.233  8239 10524 I TSLocationManager:   ✅  INSERT: 8dead539-c1aa-4187-b146-50a18d135308
10-07 16:01:33.239  8239  8239 I TSLocationManager: [c.t.l.s.LocationRequestService b]
10-07 16:01:33.239  8239  8239 I TSLocationManager:   ℹ️  Location availability: true
10-07 16:01:33.267  8239  8239 I TSLocationManager: [c.t.l.s.LocationRequestService b]
10-07 16:01:33.267  8239  8239 I TSLocationManager:   ℹ️  Location availability: true
10-07 16:01:33.309  8239  8239 I TSLocationManager: [c.t.l.s.LocationRequestService b]
10-07 16:01:33.309  8239  8239 I TSLocationManager:   ℹ️  Location availability: true
10-07 16:01:33.325  8239  8239 I TSLocationManager: [c.t.l.s.ActivityRecognitionService a]
10-07 16:01:33.325  8239  8239 I TSLocationManager:   🎾  Start motion-activity updates
10-07 16:01:33.336  8239  8239 D TSLocationManager: [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion]
10-07 16:01:33.336  8239  8239 D TSLocationManager:   🎾  Start monitoring stationary region (radius: 150.0 meters)
10-07 16:01:33.365  8239  8239 E TSLocationManager: [c.t.l.a.BackgroundGeolocation$e uncaughtException]
10-07 16:01:33.365  8239  8239 E TSLocationManager:   ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground()
10-07 16:01:33.365  8239  8239 E TSLocationManager: {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"autoSync":true,"autoSyncThreshold":5,"batchSync":true,"debug":true,"deferTime":0,"desiredAccuracy":0,"desiredOdometerAccuracy":100,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableStopDetection":false,"distanceFilter":100,"elasticityMultiplier":1,"enableHeadless":true,"enableTimestampMeta":false,"extras":{"userID":"1633","device":{"model":"Nexus 6P","platform":"Android","uuid":"aa26b047b7a8cff7","version":"8.1.0","manufacturer":"Huawei"}},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{"Authorize":"fa901361ae744240b3098d2386aa07db","X-DeviceID":"aa26b047b7a8cff7"},"headlessJobService":"com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask","heartbeatInterval":900,"httpRootProperty":"locations","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":100,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"https:\/\/loadtracking-api-qa.truckstop.com\/pings","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":29809488,"isFirstBoot":true,"didLaunchInBackground":false}
10-07 16:01:33.365  8239  8239 E TSLocationManager: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
10-07 16:01:33.365  8239  8239 E TSLocationManager:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
10-07 16:01:33.365  8239  8239 E TSLocationManager:     at android.os.Handler.dispatchMessage(Handler.java:106)
10-07 16:01:33.365  8239  8239 E TSLocationManager:     at android.os.Looper.loop(Looper.java:164)
10-07 16:01:33.365  8239  8239 E TSLocationManager:     at android.app.ActivityThread.main(ActivityThread.java:6494)
10-07 16:01:33.365  8239  8239 E TSLocationManager:     at java.lang.reflect.Method.invoke(Native Method)
10-07 16:01:33.365  8239  8239 E TSLocationManager:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-07 16:01:33.365  8239  8239 E TSLocationManager:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-07 16:01:33.933  8239  8906 I TSLocationManager: [c.t.l.http.HttpService$b onResponse]
10-07 16:01:33.933  8239  8906 I TSLocationManager:   🔵  Response: 200
10-07 16:01:33.967  8239  8906 D TSLocationManager: [c.t.l.data.sqlite.b destroyAll]
10-07 16:01:33.967  8239  8906 D TSLocationManager:   ✅  DELETED: (3)
10-07 16:01:34.010  8239  8906 D TSLocationManager: [c.t.l.data.sqlite.b allWithLocking]
10-07 16:01:34.010  8239  8906 D TSLocationManager:   ✅  Locked 1 records
10-07 16:01:34.024  8239  8906 I TSLocationManager: [c.t.l.http.HttpService a]
10-07 16:01:34.024  8239  8906 I TSLocationManager:   🔵  HTTP POST batch (1)
10-07 16:01:34.373  8239  8863 I TSLocationManager: [c.t.l.http.HttpService$b onRe
</details>
 @christocracy `

**Comment by christocracy** [comment]
Are you a customer?

**Comment by deepanjali11** [comment]
yes

**Comment by christocracy** [comment]
Install latest from master in the [private repo](https://github.com/transistorsoft/cordova-background-geolocation).  If that link is 404, talk to your project manager to add you as a member via the Product Dashboard.
