### ISSUE TITLE
http url params..

### ISSUE THREAD

**Issue by Muralilive** [transistorsoft/cordova-background-geolocation-lt#1008]
startBackgroundGeolocation() {
this.device = (window).device;
console.log("device information",this.device);
BackgroundGeolocation.onLocation(this.onLocation.bind(this));
BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
BackgroundGeolocation.onHeartbeat(this.onHeartbeat.bind(this));
BackgroundGeolocation.onGeofence(this.onGeofence);
BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
BackgroundGeolocation.onProviderChange(this.onProviderChange.bind(this));
BackgroundGeolocation.onGeofencesChange(this.onGeofencesChange);
BackgroundGeolocation.onSchedule(this.onSchedule);
BackgroundGeolocation.onPowerSaveChange(this.onPowerSaveChange.bind(this));
BackgroundGeolocation.onConnectivityChange(this.onConnectivityChange.bind(this));
BackgroundGeolocation.onNotificationAction(this.onNotificationAction);
BackgroundGeolocation.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this))
let location:any;
BackgroundGeolocation.ready({
// Geolocation config
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, // <-- highest possible accuracy
distanceFilter: this.distanceFilter,
// ActivityRecognition config
stopTimeout: this.stopTimeout,
// Application config
foregroundService: true,
stopOnTerminate: this.stopOnTerminate,
enableHeadless: true,
heartbeatInterval: 60,
// HTTP / Persistence config
url: config.SERVICE_API + config.UPD_LOC,
headers: {
'authorization': 'Bearer ' + this.user.access_token,
},
httpTimeout : 10000,
method : 'POST',
httpRootProperty: '.',
locationTemplate: '{"u_lat":<%= latitude %>,"u_lng":<%= longitude %>}',
params: {
'u_id':this.user.userid,
'u_radius':this.radius
},
autoSync: this.autoSync,
batchSync : true,
forceReloadOnGeofence: true,
geofenceModeHighAccuracy: true,
geofenceProximityRadius: 500,
autoSyncThreshold: 0,
notification: {
title: 'cordova-background-geolocation',
text: 'Tracking engaged'
},
// Logging / Debug config
debug: this.debug,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
schedule: [this.scheduleTime],
scheduleUseAlarmManager: true
}, (state) => {
console.log('- BackgroundGeolocation ready: ', state);
// Set current plugin state upon our view.
BackgroundGeolocation.startGeofences().then(() => {
BackgroundGeolocation.startSchedule();
});
BackgroundGeolocation.getLog((log) => {
console.log('[log] success: ', log);
});
this._ngZone.run(() => {
this.enabled = state.enabled;
this.isMoving = state.isMoving;
this.autoSync = state.autoSync;
this.distanceFilter = state.distanceFilter;
this.stopTimeout = state.stopTimeout;
this.stopOnTerminate = state.stopOnTerminate;
this.startOnBoot = state.startOnBoot;
this.debug = state.debug;

  });
})
}

Invalid request Error
How to include this format ?
{
'u_id' : 1
'u_radius':200,
'u_lat':12.234,
'u_lng':50.23423
}
Please advice..

**Comment by christocracy** [comment]
No, the issue template is **not** optional.  Did you read the top of it before just deleting it?

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
