### ISSUE TITLE
error: cannot find symbol   File dbfile = new File(CommonPathUtil.getDatabaseDirectoryPath(packageName), DB_FILENAME); 

### ISSUE THREAD

**Issue by shajeermhmmd** [transistorsoft/cordova-background-geolocation-lt#1012]
## Your Environment
* Plugin version: 3.3.0
* Platform: Android
* OS version:
* Device manufacturer / model: 
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Successful build

## Actual Behavior
Build error

## Steps to Reproduce

1. Install the plugin
2. configure the functions
3. Take build
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

![image](https://user-images.githubusercontent.com/12708552/67210607-0adf9100-f422-11e9-822d-f185b8ae827c.png)

**Comment by christocracy** [comment]
Not my plugin.

![](https://dl.dropbox.com/s/2odn3jfbdheta6m/Screenshot%202019-10-21%2010.09.44.png?dl=1)

**Comment by christocracy** [comment]
If you're using `cordova-background-geolocation`, remove that other plugin.
