### ISSUE TITLE
Issue related to License Key

### ISSUE THREAD

**Issue by rouheet** [transistorsoft/cordova-background-geolocation-lt#1013]
## Your Environment
* Plugin version: 3.2
* Platform: Android
* OS version: 
* Device manufacturer / model:
* Cordova version (`cordova -v`): 
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:

## Context
We purchased 5 Key license of Cordova Geolocation Plugin last year. We are right now using 2 keys. Recently the 2nd key that we generated started giving problems. The application has started showing this message - "License Validation Failure - Failed to find license key in AndroidManifest. Ensure...". Could you please check at your end why is it so? For your reference - INV Order #2958 

Please let me know ASAP

**Comment by christocracy** [comment]
Have you read the [Setup Instructions](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)?  The may have changed since you last installed the plugin.

**Comment by rouheet** [comment]
Okay, will check and implement.

Thanks
