### ISSUE TITLE
cordova-background-geolocation-lt, actually nothing happening / not working and no error, installed successfully (IONIC 4)

### ISSUE THREAD

**Issue by shajeermhmmd** [transistorsoft/cordova-background-geolocation-lt#1014]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:

```javascript
import BackgroundGeolocation, {
  Location,
  MotionChangeEvent,
  MotionActivityEvent,
  GeofenceEvent,
  Geofence,
  HttpEvent,
  ConnectivityChangeEvent
} from 'cordova-background-geolocation-lt';

 constructor() {
    this.menuCtrl.enable(false);
    this.onBuildForm();
    this.getToken();
    this.platform.ready().then(this.configureBackgroundGeolocation.bind(this));
  }

 configureBackgroundGeolocation() {
    BackgroundGeolocation.onLocation(this.onLocation.bind(this));
    BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
    BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
    BackgroundGeolocation.onGeofence(this.onGeofence.bind(this));
    BackgroundGeolocation.onHttp(this.onHttp.bind(this));
    BackgroundGeolocation.onEnabledChange(this.onEnabledChange.bind(this));
    BackgroundGeolocation.onConnectivityChange(this.onConnectivityChange.bind(this));
    // 2. Configure the plugin
    BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      url: 'http://your.server.com/locations',
      autoSync: true,
      params: {
        foo: 'bar'
      }
    }, (state) => {
      console.log('state=', state);
    });
    // 1. Listen to events (see the docs a list of all available events)
  }


 onLocation(location: Location) {
    console.log('[location] -', location);
  }
  onMotionChange(event: MotionChangeEvent) {
    console.log('[motionchange] -', event.isMoving, event.location);
  }
  onActivityChange(event: MotionActivityEvent) {
    console.log('[activitychange] -', event.activity, event.confidence);
  }
  onGeofence(event: GeofenceEvent) {
    console.log('[geofence] -', event.action, event.identifier, event.location);
  }
  onHttp(event: HttpEvent) {
    console.log('[http] -', event.success, event.status, event.responseText);
  }
  onEnabledChange(enabled: boolean) {
    console.log('[enabledchange] - enabled? ', enabled);
  }
  onConnectivityChange(event: ConnectivityChangeEvent) {
    console.log('[connectivitychange] - connected?', event.connected);
  }

startLoging() {
    console.log('start clicked')
    BackgroundGeolocation.start((state) => {
      console.log('- Start success: ', state);
    });
  }

  stopLogging() {
    BackgroundGeolocation.stop();
  }

Above given is my code,

this is "project.properties"
# Project target.
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=com-sarriaroman-photoviewer/app-photoviewer.gradle
cordova.gradle.include.2=cordova-plugin-background-fetch/app-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:10.+
cordova.system.library.2=com.android.support:appcompat-v7:28.+
cordova.system.library.3=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.4=org.greenrobot:eventbus:3.0.0
cordova.system.library.5=com.intentfilter:android-permissions:0.1.8
cordova.system.library.6=org.slf4j:slf4j-api:1.7.25
cordova.system.library.7=com.github.tony19:logback-android:2.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/app-build.gradle
cordova.system.library.8=com.android.support:support-v4:27.+
cordova.system.library.9=com.google.firebase:firebase-core:10.+
cordova.system.library.10=com.google.firebase:firebase-messaging:10.+
cordova.gradle.include.4=cordova-plugin-fcm-with-dependecy-updated/app-FCMPlugin.gradle
cordova.system.library.11=com.android.support:support-annotations:27.+
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
Insufficient version of play-services:
```
com.google.android.gms:play-services-location:10.+
```
The latest version available for non-AndroidX apps is `16.0.0`.

Use `16.0.0`

**Comment by christocracy** [comment]
In addition, all `com.android.support` libraries' major version must correspond to your `target=android-28`.

These two must be upgraded to `28.+`
```
cordova.system.library.8=com.android.support:support-v4:27.+
cordova.system.library.11=com.android.support:support-annotations:27.+
```

**Comment by shajeermhmmd** [comment]
Updated the project.properties as like above
Location tracking is working fine on Foreground, but if we close / Exit the application it will not send the location. I will share my code here. Any solution for this

import BackgroundGeolocation, {
  Location,
  MotionChangeEvent,
  ConnectivityChangeEvent,
} from 'cordova-background-geolocation-lt';


this.platform.ready().then(() => {
      this.configureBackgroundGeolocation();
});

configureBackgroundGeolocation() {
    BackgroundGeolocation.onLocation(this.onLocation.bind(this));
    BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
    BackgroundGeolocation.onConnectivityChange(this.onConnectivityChange.bind(this));
    BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      autoSync: true,
    }, (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start();
      }
    });
  }

  onLocation(location: Location) {
    this.getLocationTrackInfo(location.coords.latitude, location.coords.longitude, location.coords.speed);
  }

  onMotionChange(event: MotionChangeEvent) {
    this.getLocationTrackInfo(event.location.coords.latitude, event.location.coords.longitude, event.location.coords.speed);
  }

  onConnectivityChange(event: ConnectivityChangeEvent) {
    console.log('[connectivitychange] - connected?', event.connected);
  }

  getLocationTrackInfo(lat, lng, speed) {  // for sure this function will work on foreground, tested all the way 
    this.storage.get('loginInfo').then((loginInfo) => {
      if (loginInfo != null) {
        let post = {
          userID: loginInfo.UserID,
          latitude: lat,
          longitude: lng,
          currentSpeed: speed
        };
        this.applicationServicesProvider.updatePhleboCurrentLocation(post)
          .subscribe(result => {
          });
      }
    });
  }

**Comment by christocracy** [comment]
- See wiki Debugging.  Fetch logs.
- You ignored Device info in issue template.  See http://dontkillmyapp.com
