### ISSUE TITLE
Hello Chris, can you help me?

### ISSUE THREAD

**Issue by Didox** [transistorsoft/cordova-background-geolocation-lt#1015]
I buyed the licence of cordova-background-geolocation-lt a few years and a had to update my app, but when I reinstall all npm packege the cordova-background-geolocation-lt is inform my licence is invalid. I put the same licence in the last time.

Do you have any ideas ?

**Comment by Didox** [comment]
Obs: this mode of installation 
ionic cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git
Don't works anymore

**Comment by christocracy** [comment]
Have you read the [CHANGELOG](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#warning-breaking-changes-1) and README lately?

**Comment by Didox** [comment]
Thanks Chris.
My Ionic version is v1
And my current licence start with:
c7b746563793112f...

I try the keys below and doesn't works to me
6da948b0a8e4eebd2af03d2defe363bc3d5ca380b4bb846cb8342c6446c69975
439403e62649bd4dddf88f95f591e2c55e2b5586997e9393e3aa23a8b17b9cf5

I put the key in:
platforms/android/app/src/main/AndroidManifest.xml

<meta-data android:name="com.transistorsoft.locationmanager.license" android:value="6da948b0a8e4eebd2af03d2defe363bc3d5ca380b4bb846cb8342c6446c69975" />

Corvova version: 9.0.0 (cordova-lib@9.0.1)

**Comment by christocracy** [comment]
Why are you posting your keys to the public?

**Comment by christocracy** [comment]
Follow the installation instructions.  You cannot manually edit `AndroidManifest.xml` with Cordova

**Comment by Didox** [comment]
ok I put the configuration on config.xml too and not works.
So, thanks for your help 
bye
