### ISSUE TITLE
Problem with license

### ISSUE THREAD

**Issue by scc4** [transistorsoft/cordova-background-geolocation-lt#1019]
Hello, 
I'm having a problem with the license when building the project.
When i execute npm install, a rights error appears
The site also shows that the license has expired, but the package I bought said that the license is for life,
follow de error that appears in git:
ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/transistorsoft/cordova-background-geolocation.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128.

OBS.: git login where the license is registered: fernando@scc4.com.br

**Comment by christocracy** [comment]
This has nothing to do with the license.  
https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
