### ISSUE TITLE
Feature Request: AutoSync only when on WiFi

### ISSUE THREAD

**Issue by bryanrideshark** [transistorsoft/cordova-background-geolocation-lt#1022]
It would be excellent if there was an option which only allowed AutoSync to happen when the user is using a WiFi connection.

**Comment by christocracy** [comment]
This has been requested in the React Native version.  It will be done.  No idea when.

**Comment by christocracy** [comment]
I've decided to take a crack at this while refactoring the iOS HTTP Service.

The new option is `Config.disableAutoSyncOnCellular (default `false`)`:

```javascript
BackgroundGeolocation.ready({
  autoSync: true,
  disableAutoSyncOnCellular: true
});
```
Install the `#dev` branch from private repo:

```
cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git#dev
```
