### ISSUE TITLE
Russia blocking/not sending any api calls.

### ISSUE THREAD

**Issue by novaknole** [transistorsoft/cordova-background-geolocation-lt#1023]
I know that If I ignore the template here, My issue might be ignored too, but my issue is something specific that it's not about versions or anything related to it.

I will say it quickly.

Your plugin works pretty well. but If the driver is in Russia, it doesn't send anything to my API. looks like Russia is blocking something. Anyone knows anything about this ? What do you think Chris? 

I really need your advice on this.

Thank you.

**Comment by christocracy** [comment]
Your problem cannot have anything to do with the plugin.  Here's a counter point of a recent Russian user posting to [tracker.transistorsoft.com](http://tracker.transistorsoft.com/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80
) today.

I also have a contractor @Sigura from Russia currently refactoring `tracker.transistorsoft.com`.  The Heroku-based server seems to have no trouble receiving his locations either.

**Comment by novaknole** [comment]
So, you have no idea why it's working everywhere except for russia?

**Comment by christocracy** [comment]
No.  This is between your users and your server.
