### ISSUE TITLE
iPadOS 13.3.1, Issue with security. Background location option "always" requested but not chooseable

### ISSUE THREAD

**Issue by MattiHay** [transistorsoft/cordova-background-geolocation-lt#1024]
## Your Environment
* Plugin version: 3,3,1
* Platform: iOS 
* OS version: iPad OS 13.3.1
* Device manufacturer / model: Apple, iPad (6th Generation)
* Cordova version (`cordova -v`): 8
* Cordova platform version (`cordova platform ls`): using phonegap
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

The app shoud use Background location for Geofencing

## Actual Behavior

The app is requesting for background permission "always" by an popup, but this option is no longer available in the security-settings of the app

## Steps to Reproduce

1. update to iPad OS 13.3.1
2.
3.
4.

## Context

The users updated from iOS 12.x to iPad OS 13.3.1 Since then the app always ask for background location setting "alwasy". But this is not available in the security-settings.
What to do now? Does Geofencing work with security setting "only when using app"?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Welcome to iOS 13.  Read [this blog](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24)
