### ISSUE TITLE
Debug sound not working in release mode

### ISSUE THREAD

**Issue by LarsBocons** [transistorsoft/cordova-background-geolocation-lt#1028]
## Your Environment
* Plugin version: 3.2.1
* Platform: Android
* OS version: 9.1.0
* Device manufacturer / model: Huawei P20 Lite
* Cordova version (`cordova -v`): Android: 8.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```
{
    "activityRecognitionInterval": 500,
    "allowIdenticalLocations": true,
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": true,
    "deferTime": 0,
    "desiredAccuracy": -1,
    "desiredOdometerAccuracy": 10,
    "disableElasticity": true,
    "disableLocationAuthorizationAlert": false,
    "disableStopDetection": true,
    "distanceFilter": 0,
    "elasticityMultiplier": 1,
    "enableHeadless": false,
    "enableTimestampMeta": false,
    "extras": {},
    "fastestLocationUpdateInterval": 900,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceModeHighAccuracy": false,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {},
    "headlessJobService": "com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask",
    "heartbeatInterval": 30,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": true,
    "locationAuthorizationRequest": "Always",
    "locationTemplate": "",
    "locationTimeout": 60,
    "locationUpdateInterval": 900,
    "locationsOrderDirection": "ASC",
    "logLevel": 5,
    "logMaxDays": 1,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": -1,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 20,
    "notification": {
        "layout": "",
        "title": "",
        "text": "Location Service activated",
        "color": "",
        "channelName": "TSLocationManager",
        "smallIcon": "",
        "largeIcon": "",
        "priority": 0,
        "strings": {},
        "actions": []
    },
    "params": {},
    "persist": true,
    "persistMode": 2,
    "schedule": [],
    "scheduleUseAlarmManager": false,
    "speedJumpFilter": 300,
    "startOnBoot": false,
    "stationaryRadius": 1,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": false,
    "stopTimeout": 60,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "",
    "useSignificantChangesOnly": false,
    "enabled": true,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 0,
    "isFirstBoot": false,
    "didLaunchInBackground": false
}

## Expected Behavior

With debug=true it should play debug sounds.

## Actual Behavior

Sound is only playing in "no certificat" version of app (build with no certificat)

## Steps to Reproduce

1. 
2.
3.
4.

## Context

Trying to play debug sounds in release mode. In the log it says Unknown sound key when it tries to play sound.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
[background-geolocation.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3810908/background-geolocation.log.gz)

</details>

**Comment by christocracy** [comment]
Yes, that’s on purpose.  These sound-files add an extra ~1.5M to bundle/apk size.

See [here](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/src/android/build-extras.gradle) to learn how I prevent debug sounds being stripped in the SampleApp release.

**Comment by LarsBocons** [comment]
This worked last year. The sounds are just as usefull in the release version. 
How can I get them back using Phonegap Build?

**Comment by christocracy** [comment]
I have no idea about Phonegap Build, I've never used it.

You need to provide a [build-extras](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/config.xml#L30) gradle file as a `<resource-file>`.  The content of the `build-extras` is linked previously.

**Comment by christocracy** [comment]
>This worked last year.

v2 used Android system sounds.  v3 custom custom `.wav` / `.mp3` files that I purchased.

**Comment by christocracy** [comment]
[build-extras](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#extending-buildgradle) is a mechanism built into Cordova.

**Comment by LarsBocons** [comment]
The problem with removing them from the release is that relase- and debug app version will behave diffently. With the "debug" version I can prevent an incoming call from killing the app by playing sounds (playing sounds via the WebView will not work) on the most agressive phones.

**Comment by christocracy** [comment]
If you want them, add a build-extras.gradle.

> version I can prevent an incoming call from killing the app by playing sounds (playing sounds

Sounds like voodoo to me.

**Comment by LarsBocons** [comment]
> Sounds like voodoo to me.
Yes :-) Voodoo that works. The system will mute the sounds during the call, so they won't bother the callers. Even with the app in the foreground and sleep turned off, the incoming call works just like setting the app in the background, and it will be killed if the call is more than 5-7 minutes.

Unfortunately I only have a config.xml - no gradle files.
