### ISSUE TITLE
Question about distanceFilter

### ISSUE THREAD

**Issue by chemerisuk** [transistorsoft/cordova-background-geolocation-lt#103]
Hi @christocracy . I'm working with a GPS tracking on some project, read your docs about parameter `distanceFilter`. Does the formula `(round(speed, 5))^2 + distanceFilter` have a math background, or it's just your observation? Thanks anyway.

**Comment by christocracy** [comment]
The docs need to be updated.  The elasticity is linesr now.

This formula is arbitrary

On Saturday, April 16, 2016, Maksim Chemerisuk <notifications@github.com>
wrote:

> Hi @christocracy <https://github.com/christocracy> . I'm working with a
> GPS tracking on some project, read your docs about parameter
> distanceFilter. Does the formula (round(speed, 5))^2 + distanceFilter
> have a math background, or it's just your observation? Thanks anyway.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/103>
>


-- 
Snet form Gmail Mobile

**Comment by chemerisuk** [comment]
Okay got it. What I'm thinking about is filtering based in value of `heading`. If an object angle hasn't changed, the track has a straightforward line, so intermediate points on that can be safely skipped. Have you investigated this idea in the past as well?

**Comment by christocracy** [comment]
I have thought of this, yes.  But on the server.

On Saturday, April 16, 2016, Maksim Chemerisuk <notifications@github.com>
wrote:

> Okay got it. What I'm thinking about is filtering based in value of
> heading. If an object angle hasn't changed, the track has a
> straightforward line, so intermediate points on that can be safely skipped.
> Have you investigated this idea in the past as well?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/103#issuecomment-210821772>
>


-- 
Snet form Gmail Mobile

**Comment by chemerisuk** [comment]
Totally agree, thanks!
