### ISSUE TITLE
Ionic Application is closing it self in background after some time.

### ISSUE THREAD

**Issue by Venkatesh-Veersoftsolutions** [transistorsoft/cordova-background-geolocation-lt#1031]
Application is closing in background after some time in one plus 7 mobile . Thank you.
-->
## Your Environment
Plugin version:3.2.2
Platform: Android
OS version:8.0 and above
Device manufacturer / model: One plus
Cordova version (cordova -v): 9.0.0
Cordova platform version (cordova platform ls):android 8.1.0
Plugin config provided to #ready:
  BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 0,
      locationUpdateInterval: 300000,
      startOnBoot: true,
      foregroundService: true,
      enableHeadless: true,
      stopOnTerminate: false,
      url: url,
      autoSync: true,
      params: {
        tenantId: tenantId,
        branchId: branchId,
        vsLoginToken: vsLoginToken,
      },
      allowIdenticalLocations: true,
      heartbeatInterval: 300,
      stopOnStationary: false,
      reset: true
    }, (state) => {
      console.log('- Configure success: ', state);
      this.zone.run(() => {
      });
    });

    this.start = true;
    BackgroundGeolocation.start().then((state) => {
      BackgroundGeolocation.changePace(true);
    });
  }

  // Clear the list of events from ion-list
  onClickClear() {
    this.events = [];
  }

  /*
  *
  * @event location
  */
  onLocation(location: Location) {
    console.log('[event] location : ', location);
    const event = location.event || 'location';

    this.zone.run(() => {
      if (event === 'location') {
        this.addEvent(event, new Date(location.timestamp), location);
      }
    });
  }

  onHeartBeat(heartBeatEvent: HeartbeatEvent) {
    console.log('[event] heartBeat: ', heartBeatEvent, new Date());
    this.zone.run(() => {
      this.addEvent('heartBeat', new Date(), heartBeatEvent);
    });

    BackgroundGeolocation.getCurrentPosition({}, (location) => {
      console.log('- getCurrentPosition: ', location);
      console.log(`latitude: ${location.coords.latitude}`);
      console.log(`longitude: ${location.coords.longitude}`);
      this.jobService.updateUserLocation(this.tenantId, this.branchId, this.vsLoginToken,
        location.coords.latitude, location.coords.longitude).
        subscribe((res) => {
          console.log(res);
        }, (error) => {
          console.log(`updateUserLocation error: ${error}`);
        });

    }, (error) => {
      console.warn(`- Location error: ${error}`);
    });
  }

  /*
  *
  * @event http
  */
  onHttpSuccess(response: HttpEvent) {
    console.log('[event] http: ', response);
    this.zone.run(() => {
      this.addEvent('http', new Date(), response);
    });
  }
  onHttpFailure(response: HttpEvent) {
    console.warn('[event] http failure: ', response);
    this.zone.run(() => {
      this.addEvent('http failure', new Date(), response);
    });
  }

  /*
  *
  * Add a record to ion-list
  * @param {String} event name
  * @param {Date} date
  * @param {Object} event object, eg: {location}, {provider}, {activity}
  */
  private addEvent(name, date, event) {
    if (this.events.length >= 50) {
      this.events = [];
    }
    const timestamp = date.toLocaleDateString() + ' ' + date.toLocaleTimeString();

    this.events.unshift({
      name: name,
      timestamp: timestamp,
      object: event,
      content: JSON.stringify(event, null, 2)
    });
  }

  public stopTracking() {
    BackgroundGeolocation.stop();
    this.start = false;
    this.events = [];
  }

}

## Expected Behavior
App should not close in the background.

## Actual Behavior
application is closing  in background after some time.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> App should not close in the background

The operating system **can and will** terminate your app’s MainActivity (where the webview that your Cordova app exists) when resources are required for the current foreground-activity.  

You should *except* that your app will be terminated at some point.
