### ISSUE TITLE
Issue related to logger.

### ISSUE THREAD

**Issue by yugandharyadav** [transistorsoft/cordova-background-geolocation-lt#1036]
## Your Environment
* Plugin version: 3.3.1
* Platform:  Android
* OS version: 8.1.0
* Device manufacturer / model: Redmi 6A
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 8.1.0
* Plugin config provided to `#ready`:
BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
      distanceFilter: 0,
      locationUpdateInterval: 300000,
      startOnBoot: true,
      foregroundService: true,
      enableHeadless: true,
      stopOnTerminate: true,
      url: url,
      autoSync: true,
      params: {
        tenantId: tenantId,
        branchId: branchId,
        vsLoginToken: vsLoginToken,
      },
      allowIdenticalLocations: true,
      heartbeatInterval: 300,
      stopOnStationary: false,
      reset: true
    }, (state) => {
      console.log('- Configure success: ', state);
      this.zone.run(() => {
      });
    });

```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE

BackgroundGeolocation.logger.getLog().then((log) => {
      console.log('[log] success: ', log);
    });
```

## Expected Behavior

It should display logs in the adb logcat

## Actual Behavior

"ERROR Error: Uncaught (in promise): TypeError: _cordova_background_geolocation__WEBPACK_IMPORTED_MODULE_1__.default.logger.getLog is not a function

-->
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
"ERROR Error: Uncaught (in promise): TypeError: _cordova_background_geolocation__WEBPACK_IMPORTED_MODULE_1__.default.logger.getLog is not a function

</details>

**Comment by yugandharyadav** [comment]
We have paid version,  we urgently want it to be implemented.

**Comment by christocracy** [comment]
Customers should post issues (and use) the private repo.
