### ISSUE TITLE
Not able to get geo location callbacks in javascript file after application terminated 'Android Headless Mode'.

### ISSUE THREAD

**Issue by dotsquaresjaipur** [transistorsoft/cordova-background-geolocation-lt#1038]
Is there any way to get onLocation callback in javascript file?

I am getting following message when registering registerHeadlessTask : 
"[BackgroundGeolocation registerHeadlessTask] -- Cordova has no Javascript mechanism for registering Headless-tasks."

## Environment
* Plugin version: 3.3.1
* Platform: Android
* Cordova version (`cordova -v`):9.0.0
* Android platform version (`cordova platform ls`):8.1.0
* Plugin config provided to `#ready`:
```
stopTimeout: 5,
stopOnTerminate: false,
startOnBoot: true,
enableHeadless: true,
debug: true,
fastestLocationUpdateInterval: 5000,
distanceFilter: 10,
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
heartbeatInterval: 10,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE

```

## Expected Behavior
Background geo location plugin callback should call in javascript file when application terminated.

## Actual Behavior
Not getting background geo location plugin callback in javascript file.

## Debug logs

- Android: $ adb logcat

```
D/SystemWebChromeClient: http://localhost/plugins/cordova-background-geolocation-lt/www/BackgroundGeolocation.js: Line 403 : [BackgroundGeolocation registerHeadlessTask] -- Cordova has no Javascript mechanism for registering Headless-tasks.  See Wiki https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode
I/chromium: [INFO:CONSOLE(403)] "[BackgroundGeolocation registerHeadlessTask] -- Cordova has no Javascript mechanism for registering Headless-tasks.  See Wiki https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode", source: http://localhost/plugins/cordova-background-geolocation-lt/www/BackgroundGeolocation.js (403)
```

**Comment by christocracy** [comment]
That's correct.  That method is for React Native (Cordova and React Native share the same Typescript API).

For Cordova, see Wiki [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode).

**Comment by dotsquaresjaipur** [comment]
Does this mean i would have to implement native code for Android just for getting the location callback from this plugin.

**Comment by christocracy** [comment]
> Does this mean i would have to implement native code for Android just for getting the location callback from this plugin.

For the case where your Android app is terminated, yes.  If you've configured the plugin with a `Config.url`, the plugin will automatically continue uploading recorded locations to your server without the need for a custom headless task.
