### ISSUE TITLE
Plugin stops tracking after initialisation

### ISSUE THREAD

**Issue by 4ty711** [transistorsoft/cordova-background-geolocation-lt#1040]
## Your Environment
* Plugin version: 3.3.1
* Platform: Android
* OS version: 8.0
* Device manufacturer / model: Huawai
* Cordova version (`cordova -v`): 9-0-0
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```javascript 
var bgGeo = window.BackgroundGeolocation;
              
            bgGeo.onLocation(function(location) {
              console.log('[location] -', location);
            });
          
            bgGeo.onMotionChange(function(event) {
              console.log('[motionchange] -', event);
            });
          
            bgGeo.onProviderChange(function(event) {
              console.log('[providerchange] -', event);
            });

            bgGeo.onGeofence(function(geofence) {
                console.log("geofence")
                console.log(geofence);
             
                var temp = {
                    "identifier": geofence.identifier,
                    "action": geofence.action,
                    "latitude": geofence.location.coords.latitude,
                    "longitude": geofence.location.coords.longitude,
                    "registrationToken": global.firebaseToken,
                    "extras": {}
                }

                console.log('onGeoFence temp', temp)

                Services.geofencing.onGeoFence.post(temp, function(data, status) {

                })
            });
            
            // 2. Execute #ready method:
            bgGeo.ready({
              reset: true,
              debug: true,
              logLevel: bgGeo.LOG_LEVEL_VERBOSE,
              desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
              stopOnTerminate: false,
              startOnBoot: true
            }, function(state) {    // <-- Current state provided to #configure callback
              // 3.  Start tracking
              console.log('BackgroundGeolocation is configured and ready to use');

              console.log(state)
              
              if (!state.enabled) {
                bgGeo.start().then(function() {
                  console.log('- BackgroundGeolocation tracking started');

                     navigator.geolocation.getCurrentPosition(function(position) { 
                        self.getGeoFences(position, true) // Another function that adds some fences
                    }, function(err) {
                        console.log('location err', err)
                    }) 

                });
              }
            });
```

## Expected Behavior
Motionchange and Location Events should be fired

## Actual Behavior
After the first start(), one location and motionchange event ist fired, then it seems to stop tracking the location.

## Debug logs

There are no errors or warnings...

**Comment by christocracy** [comment]
Sounds normal to me.  Read the wiki “Philosophy of Operation” then go outside for a nice 1km walk.

**Comment by christocracy** [comment]
Btw, you don’t need Cordova-plugin-geolocation.  This plugin has its own #getCurrentPosition method.

**Comment by hboelling4711** [comment]
We have read the Wiki '' Philosophy of Operation ''. But it does not work anyway. We only get the first event when we are in a geofence region. Then we drove several times with the car and the running debugger. But we get neither the Exit Event and no further Motion Events. It just does not happen anymore. When we restart the app it is that we only ever get an event and nothing else. The creation of geofences works. We have already exchanged the GetCurrentlocation. Also without change.

**Comment by christocracy** [comment]
Huawei devices are the worst devices on earth for background operation.  The OS is like a “nanny state”.

See http://dontkillmyapp.com.

One of my 11 test devices is a Huawei P20 Lite.  I got it to work by following the directions on the link above.

**Comment by hboelling4711** [comment]
Hello, thank you for your very fast answer. But so we can´t use your nice plug in for all mobile phones ? 
We have test on huawei tablet media pad 5 and on a ulefone node 7.
thx for your help.

**Comment by christocracy** [comment]
You can use it for any phone, the user must follow the instructions at http://dontkillmyapp.com.  As you can see there:  “*No Developer Solution*”.

The fault is *entirely* with the device manufacturer violating the Android API and how the docs say things are supposed to work.

I regularly field test using the following devices:
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 10
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 8.0.0

**Comment by hboelling4711** [comment]
We only get one motion event and then the service stops. If we start with driving the motion event don´t change to driving state. Now we have test with 4 mobile phones. thx for your help.

**Comment by christocracy** [comment]
>If we start with driving the motion event don't change to driving state

Yes, that's what Huawei's device do until you modify the device's settings according to http://dontkillmyapp.com.  The OS swallows events from the Motion API and refuses to pass them on to the app.  You'll find that those events actually do come through later when you next unlock the device.  Of course by then, those events are useless.

Follow the directions for you device in http://dontkillmyapp.com and you *can* make it work.

**Comment by hboelling4711** [comment]
You think we should implement this Api in our app or we must change manually the settings in the settions section of android ?


Von: Chris Scott <notifications@github.com>
Gesendet: Montag, 2. Dezember 2019 14:42
An: transistorsoft/cordova-background-geolocation-lt <cordova-background-geolocation-lt@noreply.github.com>
Cc: Heinz Bölling <heinz.boelling@spoo-group.com>; Comment <comment@noreply.github.com>
Betreff: Re: [transistorsoft/cordova-background-geolocation-lt] Plugin stops tracking after initialisation (#1040)


If we start with driving the motion event don't change to driving state

Yes, that's what Huawei's device do until you modify the device's settings according to http://dontkillmyapp.com. The OS swallows events from the Motion API and refuses to pass them on to the app. You'll find that those events actually do come through later when you next unlock the device. Of course by then, those events are useless.

Follow the directions for you device in http://dontkillmyapp.com and you can make it work.

**Comment by christocracy** [comment]
The directions at http://dontkillmyapp.com are very clear.  The *user* much perform those actions in the settings of the device.  Huawei devices are *the worst*.  They break Android background services.  [Google is full of other developers having the same problem](https://www.google.com/search?safe=off&rlz=1C5CHFA_enCA816CA816&sxsrf=ACYBGNRpttecMHS7kSkVS99m55ElcvbXzA%3A1575295664674&ei=sBrlXaLDKMu7ggfss7WgAg&q=huawei+background+service&oq=huawei+background+service&gs_l=psy-ab.3..0i22i30.4278.6651..6820...4.2..0.109.1116.9j3....2..0....1..gws-wiz.......0i71j35i39j0j33i160j0i13i30.O2WqM_NQNRQ&ved=0ahUKEwii24jUkZfmAhXLneAKHexZDSQQ4dUDCAs&uact=5)

**Comment by hboelling4711** [comment]
Now we have tested and we have detect the following. If we starts Google Maps in the  background and we see the android location icon on the top bar the app works fine and we get motion events !?

**Comment by christocracy** [comment]
My Huawei P20 works perfectly after following the directions in http://dontkillmyapp.com.  I don't run any other apps and I don't even use the device.  I simply place it in my backpack, along with my other 10 test-devices and go.  The plugin does not require have some other app running for it to work.

**Comment by hboelling4711** [comment]
Hello Chris, first of all thank you for your quick answers. We have implemented your note and removed the current location from the API. Also, we have changed the settings as described in http://dontkillmyapp.com. But only if Google Maps is open will we receive motion events. Can you please look again in our code if there is something wrong from your point of view?
We have a big project and we want to start soon. thx

**Comment by christocracy** [comment]
There's nothing wrong with your code.
