### ISSUE TITLE
"locationTemplate" not being applied

### ISSUE THREAD

**Issue by cuddlemeister** [transistorsoft/cordova-background-geolocation-lt#1042]
## Your Environment
* Plugin version: ^3.4.1
* Platform: iOS and Android
* OS version: tested on Android emulator Pixel 2 API 28
* Capacitor version: 1.3.0
* Plugin config provided to `#ready`:

```javascript <!-- syntax-highlighting:  paste your code below -->

BackgroundGeolocation.ready({
      reset: true,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      method: 'POST',
      url: 'htpps://mock',
      headers: {
        Authorization: 'Bearer mock',
      },
      locationTemplate: '{"Lat": <%= latitude %>, "Lng": <%= longitude %>}',
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true
    }, (state) => {
      console.log('[ready] BackgroundGeolocation is ready to use');
      if (!state.enabled) {
        // 3.  Start tracking.
        BackgroundGeolocation.start();
      }
    });
```
Please note, that actual endpoint and authorization are being removed from an example. When tested, I used real endpoint.

## Expected Behavior

Location template should be applied within a configuration.

## Actual Behavior

I am providing location template in a configuration as follows: `locationTemplate: '{"Lat": <%= latitude %>, "Lng": <%= longitude %>}',`

Using android profilier I've checked the payload that is being sent and it's as follows:
``` json
{
  "location": {
    "latitude": 37.2785317,
    "longitude": -122.2003717
  }
}
```

## Steps to Reproduce
Created a blank ionic capacitor application to reproduce. Please, take a look https://github.com/cuddlemeister/bug-reproduction-cordova-background-geolocation-lt

**Comment by christocracy** [comment]
`BackgroundGeolocation.destroyLocation()`

The plugin has queued records encoded with previous or default template.  It keeps attempting to upload those old records and your server keeps returning non-200 response.  The plugin is going to keep trying until you either:
1.  Delete records in the plugin's queue with `destroyLocations`
2.  Your server return http `200`

**Comment by cuddlemeister** [comment]
I've did what you said and now the payload looks like this: 
```
{
  "location": {
    "Lat": 37.2600333,
    "Lng": -122.1017383
  }
}
```
Is it possible to make `Lat`\`Lng` properties in the root of the object?

**Comment by christocracy** [comment]
The answer is in the api docs.  Search for “rootProperty”

**Comment by himanshu849** [comment]
### you can use this property ( httpRootProperty: '.' ) to get data in root. thanks

**Comment by cuddlemeister** [comment]
> ### you can use this property ( httpRootProperty: '.' ) to get data in root. thanks

yes, I've already used this and it did the trick. thanks

**Comment by ptv1p3r** [comment]
How can i check the format the payload is beeing sent in android studio ?

**Comment by christocracy** [comment]
You can’t.  Make sure the plugin database doesn’t have old locations rendered with default template via #destroyLocations

**Comment by ptv1p3r** [comment]
i'm doing :
BackgroundGeolocation.start();
BackgroundGeolocation.destroyLocations();

Should this be enough ?

**Comment by christocracy** [comment]
You should not always be using #destroyLocations each time the app starts.

**Comment by ptv1p3r** [comment]
These are the configs i'm using:

httpRootProperty: '.',
        url: appSettings.getString("API_URL") + ":" + appSettings.getString("API_PORT") + "/v1/user/location",
        locationTemplate: '{ "latitude":<%= latitude %>, "longitude":<%= longitude %> }',
        autoSync: true,
        autoSyncThreshold: 5,
        batchSync: true,
        maxBatchSize: 50,
        method: 'POST',
        headers: {
          "content-type" : "application/json",
          "Authorization": widget.currentUser.token,
        },
        locationsOrderDirection: "DESC",
        maxDaysToPersist: 14,

I would expect the payload to be : { "latitude" : 12.546, "longitude": 64654.323} would it be a correct assumption ?

**Comment by christocracy** [comment]
Yes

**Comment by cuddlemeister** [comment]
> How can i check the format the payload is beeing sent in android studio ?

You can see it in android studio's profiler in network section

**Comment by christocracy** [comment]
You can’t.  View your http logs for the incoming data.

**Comment by christocracy** [comment]
> You can see it in android studio's profiler in network section

Oops, sorry.  Misunderstood your post.  You *can*?  Show me a screenshot of that.

**Comment by ptv1p3r** [comment]
> > You can see it in android studio's profiler in network section
> 
> Oops, sorry. Misunderstood your post. You _can_? Show me a screenshot of that.

same.. how can i see it? it would solve a lot of problems here eheh...

**Comment by ptv1p3r** [comment]
Just found out how :-) TY
![image](https://user-images.githubusercontent.com/10048793/72569714-f0974100-38b2-11ea-88a5-df73df867159.png)

**Comment by christocracy** [comment]
Oh, that’s neat!

**Comment by ptv1p3r** [comment]
And i just found out one the problems, it's that not all keys are always present, for instance event ... i thought from the documentation that it would always be present, but it could be empty, that's not the case, if it's empty, the key does not exist...

**Comment by christocracy** [comment]
Correct.  No point inflating the data with an empty-string.

**Comment by ptv1p3r** [comment]
Yes, but it's not explicit in the documentation and it should.. now the question rises, what other keys have the same behavior ?

**Comment by ptv1p3r** [comment]
> > @ptv1p3r How can i check the format the payload is beeing sent in android studio ?
> 
> You can see it in android studio's profiler in network section

Thank You !!!!!! You are a life saver !!!!

**Comment by christocracy** [comment]
See Wiki [Location Data Schema](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema)

**Comment by ptv1p3r** [comment]
> See Wiki [Location Data Schema](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema)

So those keys will always be present, and all others may or may not be present depending on content ? is that correct ?

**Comment by christocracy** [comment]
yes
