### ISSUE TITLE
API Level 26 support for v2.9.1

### ISSUE THREAD

**Issue by readyresponders** [transistorsoft/cordova-background-geolocation-lt#1043]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):
  android 6.4.0
  ios 4.5.5
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
      httpRootProperty: 'location',
      locationTemplate: '{"latitude": <%= latitude %>, "longitude": <%= longitude %>}',
      desiredAccuracy: 0,
      distanceFilter: 10,
      stationaryRadius: 25,
      activityRecognitionInterval: 5000,
      stopTimeout: 5,
      stopOnTerminate: false,
      startOnBoot: true,
      autosync: true,
      maxRecordsToPersist: 1,
      foregroundService: true,
      notificationColor: '#9c000d',
      notificationSmallIcon: 'drawable/push',
      notificationLargeIcon: 'drawable/push'
    };
```

## Expected Behavior
When targeting API level 26+, I expect the geolocation service to work normally. 
## Actual Behavior
I get an error related to requirement of `android.permission.FOREGROUND_SERVICE`. I realize that updating to a newer version of the plugin would probably help, but we don't have time to sort through breaking changes at the moment and testing everything via QA.

I'm wondering the recommended best course of action from transistorsoft. I'm currently going to try the suggestion here: https://ionicframework.com/docs/native/foreground-service
## Steps to Reproduce

1. Use 2.9.1 of plugin
2. Add `<preference name="android-targetSdkVersion" value="28" />` to config.xml
3. Build
4. Run on device

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
https://kceb.d.pr/BvPitc
```

</details>

**Comment by christocracy** [comment]
Why are you not on 3.x yet?  2.x doesn’t support iOS 13 or Android 10.

**Comment by readyresponders** [comment]
@christocracy Do you think that upgrading to 3.x resolve this issue? I locked the version of the app a year+ ago, and haven't had the chance to update it to 3.x

**Comment by christocracy** [comment]
You're free to add any required permissions to your own app's AndroidManifest.xml using `<config-file>` block in your `config.xml`.
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

**Comment by christocracy** [comment]
and the latest in 2.x is [2.14.2](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/2.14.2) has the permission.

In the future, customers please post support requests in the private repo.
