### ISSUE TITLE
How can i achieve custom JSON format using locationTemplate.

### ISSUE THREAD

**Issue by himanshu849** [transistorsoft/cordova-background-geolocation-lt#1044]
## Your Environment
* Plugin version:
* Platform:  Android
* OS version: Pie
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
 BackgroundGeolocation.ready(
      {
        reset: true,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        url: this.gps_update_link,
        autoSync: true,
        httpRootProperty: '.',

        locationTemplate: '[{"latitude":<%= latitude %>, "longitude":<%= longitude %>, "time":<%= this.timeStamp %>,"userId":"this.userId", "deviceId":"this.deviceID"}]',
      },

      state => {
        if (!state.enabled) {
          BackgroundGeolocation.start();
        } else {
        }
      }
    );
  }

  onLocation(location: Location) {
    console.log('[location] -', location);
    this.zone.run(() => {
      this.lat = location.coords.latitude;
      this.lng = location.coords.longitude;
      this.timeStamp = new Date(location.timestamp);
      //this.sendData(this.lat, this.lng, this.timeStamp)
    });

```

## Expected Behavior
``` [{"latitude":"12.3243","longitude":"7.3533","userId":"hello@gmail.com","deviceId":"samsung","time":12345678}]```
## Actual Behavior
```
{"location":{"event":"providerchange","provider":{"network":true,"gps":true,"enabled":true,"status":3},"is_moving":false,"uuid":"d15cdfdd-88ad-44ff-96d1-0206cb986622","timestamp":"2019-12-05T08:09:41.534Z","odometer":0,"coords":{"latitude":12.8198034,"longitude":77.6831387,"accuracy":600,"speed":0,"heading":90,"altitude":-1},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":0.66},"extras":{}},"deviceId":"Redmi 6A (4043d6f8adacefe4)","userId":"himan@gmail.com"}
```

**Comment by christocracy** [comment]
You have old records in the plugin's SQLite database *before* you added your template.  The plugin is likely trying to send those records to your server and your server is returning an error.

When you are playing with `locationTemplate`, be sure to `BackgroundGeolocation.destroyLocations` to ensure old records are destroyed.

**Comment by christocracy** [comment]
and this is an error:
```
"time":<%= this.timeStamp %>,
```
it's:
```
"time": "<%= timestamp %>"
```

**Comment by himanshu849** [comment]
my problem is that i am not able to bind global variable with locationTemplate.
please check the following code.

locationTemplate: '[{"latitude":<%= latitude %>, "longitude":<%= longitude %>, "time":<%= this.timeStamp %>,"userId":"this.userId", "deviceId":"this.deviceID"}]

i want to send the data from client to server in following format.
[{"latitude":"22","longitude":"32423","userId":"hello@gmail.com","deviceId":"samsung","dt":23234234}]

**Comment by christocracy** [comment]
**SYNTAX HIGHLIGHTING**

**Comment by himanshu849** [comment]
## my problem is that i am not able to bind global variable with locationTemplate.
please check the following code.

```locationTemplate: '[{"latitude":<%= latitude %>, "longitude":<%= longitude %>, "time":<%= this.timeStamp %>,"userId":"this.userId", "deviceId":"this.deviceID"}]```

## i want to send the data from client to server in following format.
```[{"latitude":"22","longitude":"32423","userId":"hello@gmail.com","deviceId":"samsung","dt":23234234}]```

**Comment by christocracy** [comment]
**EDIT YOUR PREVIOUS POST**.
![](https://dl.dropboxusercontent.com/s/l244vdoyl9qf3zr/Screenshot%202019-12-05%2012.19.07.png?dl=1)

**Comment by christocracy** [comment]
There is no *binding* of your Javascript.  the rendering occurs in native code (Obj-c / Java).

You can't do this:
```
"time":<%= this.timeStamp %>
```
The timestamp is available via `"time": "<%= timestamp %>"` (you have no control over the format; it's *String*, not a number).

See `Config.extras`

```
BackgroundGeolocation.ready({
  extras: {
    userId: this.userId,
    deviceId: this.deviceId
  },
  locationTemplate: "<your location template">
});
```
You will still have no control over the `timetamp` format.  Your server must accept the format as provided by the plugin ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format)

**Comment by himanshu849** [comment]
Thanks i got it !
