### ISSUE TITLE
Update to server only under certain conditions

### ISSUE THREAD

**Issue by Marcophono2** [transistorsoft/cordova-background-geolocation-lt#1045]
## Your Environment
* Plugin version: 3.3.1
* Platform: iOS
* OS version: 13.2
* Device manufacturer / model: Apple iPhone 6s
* Cordova version (`cordova -v`): 5.0.0
* Cordova platform version (`cordova platform ls`): 9.0.0

## Expected Behavior
There should be an option to tell the plugin under which circumstanzas it shall make a server request ('url')

## Actual Behavior
There is not such an option / I did not find one

## Context
The app I am building shall trigger when the user is arriving a country outside the EU. My app's users will originally only be located in Germany. As far as I understand there is no direct way to trigger if the roaming state changes or to trigger the present location country code or the local cell provider (not the home provider) without sending the lat,lng to my server first. To save battery I would like to make location requests very seldom and updating the result to my server not before being (rather) sure that the user arrived another country outside the EU.
Due to the fact that all countries outside the EU have another timezone than Germany (I know, there are some countries in Africa which also have the same timezone but that isn't important in my case) my idea is to compare the timestamp coming from the location api with the device's timestamp. If there is a difference more than the difference between german time and Greenwich Mean Time, I would like to let the plugin upload the location results to my server. But I think there is no option to let the server access depend on one or more conditions.
By the way: If you have any other ideas which can solve my problem in a less indirect way I would be very thankful.

Best regards
Marc

**Comment by christocracy** [comment]
The plugin cannot possibly be involved with this highly specific use-case you require.

It's up to you to figure this out and set `autoSync` and perhaps `maxRecordsToPersist` as desired.  if you set `maxRecordsToPersist: 0`, no location will be persisted to the plugin's internal SQLite database.  Since the HTTP Service operates by selecting records from the SQLite database, `maxRecordsToPersist: 0` will "starve" the HTTP Service thus no records exist to upload to the server.

Search the API docs for "HTTP Guide"

**Comment by Marcophono2** [comment]
Damn, that was fast! Not the answer I hoped to get but really fast! Thank you! :-)

Marc

**Comment by Marcophono2** [comment]
Hi Chris!
Sorry for bothering again. May be you can help me in a logical question. To find out if a user is abroad I now try another approach. I now want to trigger an event which

1.) happens not too often and
2.) COULD point to a re-connection to a foreign mobile network

In such a case I would let send the current lat,lng data to my server to let it find out in which country the user is (or near the border)

So, if for example an "onConnectivityChange" event happens this COULD mean that the user is now registered into another mobile network for roaming in another country. Sure, that event happens 100 to 1000 times more often without re-connecting to another country mobile network but all together this event would not happen more than, may be, 10 to 20 times a day. 
As far as I understand your plugin's docs the event listeners are active in the background all the time without using (much) battery. If so, in my case I just would make a location request when the onConnectivityChange event happens. But that is not working with the default/example JS code after a device reboot. Only if I add the heartbeatInterval parameter it works in that way. But this seems not to be the way the big brain behind all this (you) imagined. Can you give me one or two advices, Chris?

Best regards
Marc

**Comment by christocracy** [comment]
See Wiki “Android Headless Mode” for the reboot case.

**Comment by Marcophono2** [comment]
Not bad. ;) I made my tests on an Android device because it is easier and faster (on my computer), yes. But actually I ask for iOS. Or does it work on iOS in the way I tried it on Android?

**Comment by christocracy** [comment]
No, it doesn’t work for iOS the same.  iOS has no such concept of running “headless”.

**Comment by Marcophono2** [comment]
Okay. Does it mean that for iOS the only way to reduce the amount of location service activations (to save battery) is to use the geofences? For example I could overlap 90% to 95% of the map from Germany with the 20 allowed geofences to mark that here is no need to get location data to find out if the user is (with a certain probability) outside of Germany / just being passing the german border?

May be you know someone who can set me up a good config setting for my desire for some money? I understand that you want the users completely understand the ideas and the technical relationships inside your code but I will never again change anything at that code when it is once set up.
And: Yes, I also need the Android code so I will make a license purchase by the way. ;)

Best regards
Marc

**Comment by christocracy** [comment]
Why don’t you reverse geocode the lat/lng on the server and ask “is this outside my desired border”?  If so, the plugin has an undocumented feature where if you return a JSON response:
```json
{
  “background_geolocation”: [“stop”]
}
```
The plugin *will* stop.

**Comment by christocracy** [comment]
Random googling, i might use something like this if I were doing this with Node server.

https://github.com/totemstech/country-reverse-geocoding/blob/master/README.md#how-it-works

**Comment by christocracy** [comment]
And if still want to periodically query the location to ask “is device back in DE?”, you might set up a background-fetch handler to call #getCurrentPosition.

**Comment by Marcophono2** [comment]
I already have that plugin inserted. :-) My main point is not to save battery when the user is abroad. I want to save battery when the user is not abroad. That happens in 99% of the time. But may be with a "good" setting your plugin does not use significant battery anyway. (I did not test it.) If there is no significant increase in battery usage while the plugin works in background mode (and not in heartbreak mode and not with too small radius for waking up) then I am happy without further optimations.

**Comment by christocracy** [comment]
How often, in meters, do you want to record a location while user is in home country?

**Comment by Marcophono2** [comment]
1000 would be enough.

**Comment by christocracy** [comment]
See api docs Config.useSignificantChangesOnly.

**Comment by Marcophono2** [comment]
"significantChangesOnly: true will provide significant power-saving"
Okay. I understand your hint in that way that the battery usage is absolut "acceptable" with this setting. ;)

**Comment by Marcophono2** [comment]
You are the best!!

**Comment by Marcophono2** [comment]
Hi Chris!
For optimizing my iOS app I - of course - try to reduce the battery usage to a minimum. Relating to my app intention it may be senseful to differ from the "standard" plugin script. I hope you can give me a hint for two considerations.
As decribed my app shall do something when the user passes the german border to another country. This situation is an exception and will happen seldom, may be twice a year. So I want to reduce the battery usage to the absolute minimum as far as the user/device has a safe distance to the german borders.
So I could use a geofence with one (or more) circles within Germany. The app should only do something if the user/device is outside of that cicle(s) because then it must check (always when a connectivity change event happens) in which country the user/device is per reverse geocoding. As far as the user is within this circle, no more action shall happen. Here my first question: Does is make any battery usage difference if using the geofence function compared to own scripting in the onLocation function?

```
 bgGeo.onLocation(function(location) {
lati=location.coords.latitude;
loni=location.coords.longitude;
if (lati >= 47.884938 && lati <= 54.802412 && loni >= 8.208070 && loni <= 11.946627) {
console.log('being in Germany');
germany = 1;
}
      });
```
And second point: An additional condition when my script needs the location data is when something changes in the connectivity.

```
 bgGeo.onConnectivityChange(function(event)  { 
console.log('this is the only place and situation the app needs lat and lon to get the country via reverse geocoding');
if (germany == 0) {
nativegeocoder.reverseGeocode(successRG, failureRG, lati, loni, { useLocale: true, maxResults: 1 });
}
  });
```
My question is if it is an advantage to use the one-time location request function
`bgGeo.getCurrentPosition`
within bgGeo.onConnectivityChange
or shall I use the location data from the
`bgGeo.onLocation`
listener? 
I am using useSignificantChangesOnly.

Best regards
Marc
