### ISSUE TITLE
App not sending location on the URL while device is in sleep mode.

### ISSUE THREAD

**Issue by kiranyad** [transistorsoft/cordova-background-geolocation-lt#1047]
## Your Environment
* Plugin version: 3.3.1
* Platform: Android
* OS version:
* Device manufacturer / model: 
* Cordova version (`cordova -v`): 8.1.0
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:

function background_tracking(device_id) {  
    var bgGeo = window.BackgroundGeolocation;

    bgGeo.onLocation(function(location) {
        // console.log('[location] -', location);
    });

    bgGeo.onMotionChange(function(event) {
        // console.log('[motionchange] -', event.isMoving, event.location);
    });

    bgGeo.onHttp(function(response) {
        // console.log('[http] - ', response.success, response.status, response.responseText);
    });

    bgGeo.onProviderChange(function(event) {
        // console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
    });

    // Your app must execute AT LEAST ONE call for the current position via standard Cordova geolocation,
    //  in order to prompt the user for Location permission.
    window.navigator.geolocation.getCurrentPosition(function (location) {
        // console.log('Location from Phonegap');
        latitude = location.coords.latitude;
        longitude = location.coords.longitude;
    });

    bgGeo.configure({
            activityRecognitionInterval : 5000,
            autoSync: true,
            debug: false,
            desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            enableHeadless: true, 
            logLevel: bgGeo.LOG_LEVEL_VERBOSE,
            url: 'https://keystonbros.com/mobile_api/update_location.php',
            params: {
                'device_id': device_id,
            },
            reset: true,
            stopOnTerminate: false,
            startOnBoot: true
        }, function(state) {    // <-- Current state provided to #configure callback
            // 3.  Start tracking
            // console.log('BackgroundGeolocation is configured and ready to use');
            if (!state.enabled) {
                bgGeo.start().then(function() {
                    // console.log('- BackgroundGeolocation tracking started');
                });
            }
        }
    ).catch(error => {
        // console.log('- BackgroundGeolocation error: ', error);
    });
}

## Expected Behavior
1. function is called at login time so it should start posting location on the url from then
2. and after that even my application is closed or device is in sleep mode , it should repost the location on to the url after every 10 meter.

## Actual Behavior
1. when i login it is posting the location on to the URL. but after that when my application is closed  or device is in sleep mode it is not posting the location to the url.

## Context
I am trying to save the location of device whether user is working on App or it is closed or device is in sleep mode.

## Debug logs
There are no errors or warnings.

**Comment by christocracy** [comment]
- Device OS version:
- Device manufacturer / model:

**Comment by kiranyad** [comment]
device OS version: colorOs V3.0.0i
Device manufacturer / model: oppo

**Comment by christocracy** [comment]
You need to go outside and *move.*

Also, many device manufacturers cripple Android for background operation, particularly Chinese devices.  See http://dontkillmyapp.com

**Comment by kiranyad** [comment]
yes, I am testing it from last one week. when i logout the application then at that time it is doing all the entries. it means it is getting the location but did not posting on to the url.

And yes i have checked the link that you have mentioned but what is the solution in that case?

**Comment by christocracy** [comment]
See Wiki "Debugging".  Are you observing the logs?  You have to.

**Comment by kiranyad** [comment]
If you don't mind, can you tell me how do i debug the App while app is not running or phone is in sleep mode?

**Comment by christocracy** [comment]
See Wiki "Debugging".

**Comment by sudinmondal19** [comment]
I have same problem also "App not sending location on the URL while device is in sleep mode"

**Comment by christocracy** [comment]
>App not sending location on the URL while device is in sleep mode

Why should the app record location while it's *sleeping*?  In order for the plugin to record location, the device must be *moving* (where the app is **not** not sleeping).
