### ISSUE TITLE
Heartbeat not being call after closing the app

### ISSUE THREAD

**Issue by Hiraqui** [transistorsoft/cordova-background-geolocation-lt#1049]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 8.1.0 / 8.0.0
* Device manufacturer / model: Samsung Galaxy J7 (2016) SM-J710MN / HUAWEI P20 lite
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
let config: Config = {
            reset: true,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            stopOnTerminate: false,
            startOnBoot: false,
            notificationTitle: "Magiis activado",
            notificationText:"Obteniendo ubicación",
            autoSync: true,
            batchSync: false,
            foregroundService: true,
            heartbeatInterval: 60,
            preventSuspend: true,
            stopTimeout: 1,
            url: AppSettings.Url + "drivers/"  + this.identityService.userId + "/reportNumericLocation",
            locationTemplate:'{ "latitude":<%= latitude %>, "longitude":<%= longitude %> }',
            params: undefined,
            headers: {
                Authorization: "Bearer " + this.connectionService.getToken(),
            },
        };
```

## Expected Behavior
Hearbeat calls should keep working after closing de app. It also makes a call to an API.

## Actual Behavior
The heartbeat function is not being called anymore after closing the app.

## Context
I'm trying to make a "keep alive" call. In the backend, users status is changed to OFFLINE if they haven't been sending location updates or heartbeat calls for the last 5 minutes. An endpoint is being called in each heartbeat. When the app is in foreground or background works fine, after closing it is the issue.

**Comment by christocracy** [comment]
What makes you think that heartbeat isn't being called?
- Are you observing the logs?
```
TSLocationManager: [c.t.l.s.HeartbeatService$a run] ❤️
```
- Are you *listening* for heartbeat events by setting `debug: true`?

You *do* realize that your Cordova Javascript doesn't exist when an Android app is terminated, right?  Your Javascript `onHeartbeat` callback no longer exists to execute.

**Comment by Hiraqui** [comment]
Yes, the log inside the callback is no longer being printed and the endpoint on the backend is not receiving anything.

> You do realize that your Cordova Javascript app no longer exists when an Android app is terminated, right? Your Javascript onHeartbeat callback no longer exists to execute.

So there is no way to make it work if the app is terminated?

**Comment by christocracy** [comment]
The plugin's native Android service remain running after terminate.  If you've configured the plugin with an `#url`, it will continue uploading the location it records to your server.

If you have business logic to perform in the terminated state, see Wiki ["Android Headless Mode"](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode).  You must write Java code.
