### ISSUE TITLE
( ionic Cordova plugin add cordova-background-geolocation-lt ) plugin apk build error Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by sudinmondal19** [transistorsoft/cordova-background-geolocation-lt#1050]
Hi,
I have to work on ionic 4 projects, that project needs to implement
GPS tracker.

I want to track GPS location when the user is logged into my app and
even closing the app (if the user is in the logged-in state). The
tracking needs to be stopped only when the user is logged out from
the app.

So, I found your plugin (Ionic
$ ionic Cordova plugin add cordova-background-geolocation-lt)

I have installed that plugin and change variable to the config.xml
file also which you recommended.

but when I app build then given some error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
&gt; Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[ERROR] An error occurred while running subprocess cordova.

cordova build android exited with exit code 1.

Re-running this command with the --verbose flag may provide
more
information.

and my cordova plugin list is:

cordova plugin list
cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location
Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by christocracy** [comment]
Post your platforms/android/project.properties

**Comment by sudinmondal19** [comment]
platforms/android/project.properties

# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android Studio Gradle projects

# Project target.
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/starterEFCEasyCrm-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:16.+
cordova.system.library.2=com.android.support:appcompat-v7:28.+
cordova.system.library.3=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.4=org.greenrobot:eventbus:3.0.0
cordova.system.library.5=com.intentfilter:android-permissions:0.1.8
cordova.system.library.6=org.slf4j:slf4j-api:1.7.25
cordova.system.library.7=com.github.tony19:logback-android:2.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/starterEFCEasyCrm-build.gradle
cordova.system.library.8=com.android.support:support-v4:27.1.0
cordova.system.library.9=com.android.support:support-annotations:27.+
cordova.system.library.10=com.google.android.gms:play-services-location:16.+

**Comment by christocracy** [comment]
When you see this `target=android-27`, it means all `com.android.support.*` libs' major version is supposed to correspond to `27` as well (however, you should be building with a higher sdk than 27; latest is `29`).

Manually edit `project.properties` as below then build.

```
+cordova.system.library.2=com.android.support:appcompat-v7:27.+
```

See [APP_COMPAT_VERSION](https://github.com/transistorsoft/cordova-background-geolocation-lt#variable-appcompat_version-27)

**Comment by sudinmondal19** [comment]
My build issue is resolved by using (+cordova.system.library.2=com.android.support:appcompat-v7:27.+)

but, i need server api to send latitude and longitude every 10 min interval after my app login then start tracking and app close and background and sleep mode also. But in current situation api is firing for first time but longitude and latitude is not accessible with same name and also not firing the api after 10 min interval.

I am not able to do this my code bellow :

 //================= background geo location (purches code) start ==================
  api_gps_url = API_URL+'/check_interval';

  get_global_params = this.authService.getTokenSessionMaster();

  configureBackgroundGeolocation() {
    alert('click server api  url>' + this.api_gps_url);
    alert('token >'+ this.get_global_params.token);
  
    BackgroundGeolocation.onLocation(location => {
      console.log('[location] - ', location);
    });

    BackgroundGeolocation.onMotionChange(event => {
      console.log('[motionchange] - ', event.isMoving, event.location);
    });

    BackgroundGeolocation.onHttp(response => {
      console.log('[http] - ', response.success, response.status, response.responseText);
    });

    BackgroundGeolocation.onProviderChange(event => {
      console.log('[providerchange] - ', event.enabled, event.status, event.gps);
    });

    BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 0,
      locationUpdateInterval: 600000, //(10 min interval server api call ? (also need lat and long send))
      startOnBoot: true,
      url: this.api_gps_url,
      autoSync: true,
      params: {
        'token':this.get_global_params.token,
        'session':this.get_global_params.session,
        'master':this.get_global_params.master
      },
      stopOnTerminate: false,
      reset: true
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    
      if (!state.enabled) {
      
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
  }
  
  //===background geo location (purches code ) end ===

**Comment by sudinmondal19** [comment]
And another app need to live tracking(like uber)  that is possible ? using this plugin

**Comment by christocracy** [comment]
This issue is title "plugin apk build error Execution failed for task ':app:processDebugResources'.".  If it is solved, please close the issue.

**Comment by sudinmondal19** [comment]
My build issue is resolved by using (+cordova.system.library.2=com.android.support:appcompat-v7:27.+)
