### ISSUE TITLE
Feature request: Enable "triggerActivities" config on iOS too

### ISSUE THREAD

**Issue by GroveDev** [transistorsoft/cordova-background-geolocation-lt#1051]
Sorry, if I misunderstood something but according to the documentation, the config parameter "triggerActivities" is for android only. Can I ask why? The information of stationary/walking/in vehicle/etc is available on iOS too, isn't it? I tried the "activityType" parameter but it did not work.

I'd need to config the plugin so that it only starts saving the locations when the "in vehicle" state is received.

**Comment by christocracy** [comment]
iOS cannot monitor Motion API in the background and the user may not have enabled the Physical Activity permission.

Listen to #onActivityChange event.  If there’s some particular motion-activity you’re not interested in, changePace(false) to place the plugin back into stationary state.

**Comment by GroveDev** [comment]
Oh I see. Thank you very much for your help!
