### ISSUE TITLE
How to enable the iOS #preventSuspend mode

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1052]
Is going to: Xcode => Signing and  Capabilities  => Background Modes => Check the Background processing is enough for **iOS #preventSuspend mode** to work, OR that I should also add this in code configuration object?
like this: `preventSuspend: true`

**Comment by christocracy** [comment]
You need to configure `preventSuspend: true` in addition to `[x] Background Location` capability in XCode.

**Comment by Taxi4you** [comment]
So my actual config should be looking like this:

```
BackgroundGeolocation.ready({
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    autoSync: true,
    preventSuspend: true,
    stopOnTerminate: true,
    startOnBoot: true
  })
```

BTW, this is working only if the client allowed "allways location permission" or that its just working even if the user granted only foreground permissions, but the app keep functioning on background as foreground anyway?

**Comment by christocracy** [comment]
iOS` `preventSuspend` *requires* `Always`.
