### ISSUE TITLE
 i need server api to send latitude and longitude every 10 min interval after my app login then start tracking and app close and background and sleep mode also

### ISSUE THREAD

**Issue by sudinmondal19** [transistorsoft/cordova-background-geolocation-lt#1053]
I need server api to send latitude and longitude every 10 min interval after my app login then start tracking and app close and background and sleep mode also. But in current situation api is firing for first time but longitude and latitude is not accessible with same name and also not firing the api after 10 min interval.

I am not able to do this my code bellow :

//================= background geo location (purches code) start ==================
api_gps_url = API_URL+'/check_interval';

get_global_params = this.authService.getTokenSessionMaster();

configureBackgroundGeolocation() {
alert('click server api url>' + this.api_gps_url);
alert('token >'+ this.get_global_params.token);

BackgroundGeolocation.onLocation(location => {
  console.log('[location] - ', location);
});

BackgroundGeolocation.onMotionChange(event => {
  console.log('[motionchange] - ', event.isMoving, event.location);
});

BackgroundGeolocation.onHttp(response => {
  console.log('[http] - ', response.success, response.status, response.responseText);
});

BackgroundGeolocation.onProviderChange(event => {
  console.log('[providerchange] - ', event.enabled, event.status, event.gps);
});

BackgroundGeolocation.ready({
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  distanceFilter: 0,
  locationUpdateInterval: 600000, //(10 min interval server api call ? (also need lat and long send))
  startOnBoot: true,
  url: this.api_gps_url,
  autoSync: true,
  params: {
    'token':this.get_global_params.token,
    'session':this.get_global_params.session,
    'master':this.get_global_params.master
  },
  stopOnTerminate: false,
  reset: true
}, (state) => {
  console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

  if (!state.enabled) {
  
    BackgroundGeolocation.start(function() {
      console.log("- Start success");
    });
  }
});
}

//===background geo location (purches code ) end ===

**Comment by christocracy** [comment]
Read the Wiki "Philosophy of Operation".  This plugin knows when the device is *moving* and *stationary*.

- When the device is moving, the plugin records locations according to configured `distanceFilter` / `locationUpdateInterval`.
- When the device is *stationary*, the plugin has turned off location-services and is doing *nothing*.
- If you want a location periodically when device is stationary, implement a `background-fetch` handler (plugin already included and ready for you).  Execute `#getCurrentPosition` in the callback.
