### ISSUE TITLE
Android not precise + not sending position on time

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1054]
* Plugin version: 3.4.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Note 8
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    autoSync: true,
    preventSuspend: true,
    stopOnTerminate: true,
    startOnBoot: false
  })
```

## Expected Behavior
Locations should be precise, dispatched on each 10 meters as configured in the plugin

## Actual Behavior

1. Location is not accurate, around 100 meter radius mistake.
![2019-12-18_09-57-52](https://user-images.githubusercontent.com/41004207/71067749-c6504780-217d-11ea-860f-925e58264384.png)

In the picuture above you can see where the user is (the green 30).
In the upper arrow you see where he really is.
Its 100 meter deviation.

2. Locations are not disptached after 10 meters but after 20 seconds approximately, which in this period the user actually moves like 300 meters.

## Steps to Reproduce
1. Just play the start method.
2. Listen to location event and disptach this to my server.

## Context
Reveal user's position robustly as mentioned in this plugin.
I would like to purchase only if its works as perfect.

## Debug logs
There isnt.

**Comment by Taxi4you** [comment]
Furthermore, on Android the speedometer fail to emit event when driver stops - if he goes 100kmh there is 100kmh, if he slows down to 50 you see 50kmh as excepted, but if he completeley stops, it stucks on 20kmh and only after 5 minutes it zeroing to 0 or -1. This should be happen immedtiately.

On iOS the speedometer functionality doesn't work at all.
on iOS background detection is bad - working rarely.

**Comment by christocracy** [comment]
The plugin doesn’t “create” locations, it’s only the messenger, delivering locations to you exactly as provided by the native location apis.  Depending on the device manufacturer and local environment (bridges, tunnels, tall buildings, mountains, etc) you’ll never get “perfection”.

You’ll want to read the docs for Config.distanceFilter, paying particular attention to the note about Config.disableElasticity.

> on Android the speedometer fail 

I’m not aware of a “speedometer”.

**Comment by christocracy** [comment]
I suggest you install the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp) on your device and let it operate in conjunction with your app, to test the plugin in isolation of your application code.  It will post its results to http://tracker.transistorsoft.com.

**Comment by Taxi4you** [comment]
1. The actual problem is when stop in a red light for 2 minutes or so, and then continue driving.
The plugin will throw the next position only after 1 minute of continues driving, so it's a big gap.
After continue driving there no problem - the plugin throws location events just as supposed to.

2. You know what Speedometer is. Speedometer = Location > Coords > Speed, under the Location object.
And it's not getting zeroed immediately when stop drive, maybe you know why.
I mean, it only stuck on 5km/h (after translating this from m/s) for 5 minutes and only then its getting zeroed. 
Also the **is_moving** doesn't get changed to 'still' when just stand.

3. I need background(!) geolocation and you probably know that iOS in first time only asks for foreground or one time permission at first - the apple annoying prompt, which is very unclear to understand. This is a bad prompt, maybe this plugin has a better prompt, overrides the default, which actually asks only for Always or something easier else?

4. I didn't understand what is the stopTimeout to be exact.
Correct me if I am wrong:
stopTimeout for example is set to 1.
User drives and then stop. Now the plugin counts 1 minute and if the user doesn't start moving again after this period of time, only by then the plugin changes from "driving" or etc to "still"?
So basically if I want to solve the 2. issue I have mentioned in this comment, I have to set this to **stopTimeout: 0**?
Please, if you could, try to explain it practically.

5. For about the motion sensor, is this counting the speed based on built in sensor, or, that it counts the distance from his previous point to the current one and the time been passed between them?

6. Config.disableElasticity This can lead to ratelimit overflow since when driving highway its 30m/s approximately and therefore there may be too many requests for waste. In highway there no problems - there problems (sometimes) when device moves from still to moving or from moving to still.

7.  I know the plugin can be tested on the debug build on Android, but I want to try this in production for one month. Is it possible to get one month free, or just paid for one month counted for testing purposes and if everything is good I will complete purchase?
Please be elastic in here, as you can see, I really interesting about your product, but I want to really test before I buy, with real users.

Thanks.

**Comment by christocracy** [comment]
>The actual problem is when stop in a red light for 2 minutes 

So why don't you *increase* your [`stopTimeout`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#stoptimeout) accordingly?

>You know what Speedometer is. Speedometer = Location > Coords > Speed, under the Location object.
And it's not getting zeroed immediately when stop drive, maybe you know why.

`location.coords.speed` comes from the native location api when a location is recorded.  The plugin doesn't "zero" anything.  It simply provides locations.  If you're concerned with `speed`, you should listen to the `#onActivityChange` event &mdash; when `still` event is returned, the device is obviously stationary, thus speed *must* be zero.  This is your responsibility.

>maybe this plugin has a better prompt, overrides the default, which actually asks only for Always or something easier else?

No.  This is not possible.  You cannot "override" iOS behaviour.  iOS is **very** strict when it comes to location permission (for good reason).

>I didn't understand what is the stopTimeout to be exact.
>So basically if I want to solve the 2. issue I have mentioned in this comment, I have to set this to stopTimeout: 0?

Setting `stopTimeout: 0` would make it *worse*.  It's very simple:  When the motion api says `still`, the plugin starts a timer of `stopTimeout` minutes.  If the motion API reports a moving-type activity (eg: 'in_vehicle`, `on_foot`) during that time, the `stopTimeout` timer is cancelled and tracking continues along as normal.  If the `stopTimeout` timer *does* expire, the plugin *turns off* location-services and transitions to the **stationary state**.  Stopping at a red-light with `stopTimeout: 0` would cause the plugin to enter the stationary state within seconds of stopping.  

![](https://dl.dropboxusercontent.com/s/z3lf8pcthmj8vp8/Screenshot%202019-12-19%2009.23.34.png?dl=1)

>For about the motion sensor, is this counting the speed based on built in sensor, or, that it counts the distance from his previous point to the current one and the time been passed between them?

The Android/iOS MotionAPIs have nothing to do with speed or distance.  It's a black-box API that aggregates accelerometer, gyroscope and magnetometer into a machine-learning algorithm (presumably) to spit out an answer:  `on_foot`, `still`, `in_vehicle`, etc.

>Why the plugin asks for Bluetooth permission?

It doesn't.  One of your other plugins is.

>I know the plugin can be tested on the debug build on Android, but I want to try this in production for one month

Not possible.  The performance in DEBUG builds is identical to RELEASE build.

**Comment by Taxi4you** [comment]
You had written in the docs that its possible to prompt "Always" permission in iOS, see this:
https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#locationauthorizationrequest
But this is not working for me, how come?

**Comment by christocracy** [comment]
this *closed issue*, titled “Android not precise + not sending position on time”, has nothing to do with iOS.

Issues are not generic personal support thread where you get to ask any question you like.
