### ISSUE TITLE
Android phone restart then not working this plugin

### ISSUE THREAD

**Issue by sudinmondal19** [transistorsoft/cordova-background-geolocation-lt#1055]
```I have use (cordova-background-geolocation-lt) this plugin it work fine even app close then also
but when android phone restart then not geting response, how can i solve this problemI only want to stop tracking when user forcefully logged out from my app, not when phone restart because user is in logged-in state when phone restarts```

**Comment by christocracy** [comment]
**Ignored issue template**

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
