### ISSUE TITLE
android mobile user manually turn off connection there any way detect this situation

### ISSUE THREAD

**Issue by sudinmondal19** [transistorsoft/cordova-background-geolocation-lt#1057]
I have implemented (cordova-background-geolocation-lt) this plugin also work app close and running extremely well in my app but when my android mobile user manually turn off connection(mobile data or wifi) or switch off the mobile then not api not sending data to my url. so is there any way to detect this situation when user intentionally cut off his tracking. Thanks for your help in advance.

**Comment by christocracy** [comment]
Yes.  Read api docs for events #onConnectivityChange, #onProviderChange.
