### ISSUE TITLE
Class not found issue

### ISSUE THREAD

**Issue by Qulinary** [transistorsoft/cordova-background-geolocation-lt#106]
I am trying to implement it for android, and the background service is initialising properly, but getting class not found error.

license key added in preference
works for ios but not for android, any help would be appriciated

**Comment by christocracy** [comment]
You say you purchased a license so you should be using the premium repo.
This is the free version.

https://github.com/transistorsoft/cordova-background-geolocation


On Wednesday, April 20, 2016, Qulinary <notifications@github.com> wrote:

> I am trying to implement it for android, and the background service is
> initialising properly, but getting class not found error.
>
> works for ios but not for android, any help would be appriciated
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/106>
>


-- 
Snet form Gmail Mobile
