### ISSUE TITLE
Question about HTTP module

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1060]
This is the example you provided in the docs, however I got some questions I couldnt understand from reading the docs:

```
BackgroundGeolocation.ready({
  url: "https://my-server.com/locations",
  autoSync: true,
  autoSyncThreshold: 5,
  batchSync: true,
  maxBatchSize: 50,
  headers: {
    AUTHENTICATION_TOKEN: "23kasdlfkjlksjflkasdZIds"
  },
  params: {
    user_id: 1234
  },
  extras: {
    route_id: 8675309
  },
  locationsOrderDirection: "DESC",
  maxDaysToPersist: 14
}, state => {
  console.log("[ready] success: ", state);
});
```

You say that the plugin has own DB saving locations that were failed to be sent to the server, everything is not 20x and with the **maxDaysToPersis** it will eventually try to send them again in future.

If for example a location sending was failed, and a new location is found, what will be sent to the server - the new, the old, both of them using array?
Does this plugin sends arrays of locations?

If you could explain this please.

BTW I just want to send the current location each time the plugins detects a new, and if there error to catch this error and stop the plugin, I concern the plugin will hold a big array and send them later causing mismatches.

**Comment by christocracy** [comment]
Search api docs for “HTTP Guide”.  Read it.

**Comment by Taxi4you** [comment]
From your docs, as you didnt understand that the question was raised from them:

> HTTP Failures
> If your server does not return a 20x response (eg: 200, 201, 204), the SDK will UNLOCK that record. Another attempt to upload will be made in the future (until maxDaysToPersist) when:
> 
> When another location is recorded.
> Application pause / resume events.
> Application boot.
> onHeartbeat events.
> onConnectivityChange events.
> [iOS] Background fetch events.

What do you mean by: "the SDK will UNLOCK that record. Another attempt to upload will be made in the future"?

**Comment by christocracy** [comment]
What do you *think* it means?

**Comment by Taxi4you** [comment]
User is in point a, then moved to point b but there was issue sending to the server and returned with 4xx,
then the user moves to point c successfully, but the point b that now holds in the DB of the plugin will be sent and user will be back to point b, but he actually now on point c.

**Comment by christocracy** [comment]
This plugin was Originally designed for tracking emergency workers in disaster zones.  It had to record everywhere a particular device went, no matter what.

The first thing the plugin does is insert **every location** into SQLite (as documented in “Http Guide”.

Next the http service is invoked.  The http service ask “are there any locations in SQLite?”.

If “yes”, select first (timestamp ascending).  

- If error, give up.
- if success, select another location from SQLite and continue looping.

When another location is recorded, the loop begins again.

**Comment by Taxi4you** [comment]
What is the interval of moving to the next?
Is it possible to disable this so the plugin will only send the last position instead of resending all of them again?

**Comment by Taxi4you** [comment]
If for example there 50 locations in this DB and the plugin will send them all, it can reach to ratelimit of my API. Please explain.

**Comment by christocracy** [comment]
The plugin executes http requests synchronously.  When a response is received, it executes another http request until SQLite dB is empty, as documented in “Http Guide”.

> Is it possible to disable this 

No

**Comment by Taxi4you** [comment]
This can lead to what I mentioned above, isnt it?

**Comment by christocracy** [comment]
Maybe you should test it and see.

**Comment by Taxi4you** [comment]
Okay I was just about going to your website to purchase this plugin but I will test this potential issue first
