### ISSUE TITLE
 Android mobile Restart or switch off the mobile then  api not sending data to my url so this plugin  any way to detect this situation

### ISSUE THREAD

**Issue by sudinmondal19** [transistorsoft/cordova-background-geolocation-lt#1061]
I have implemented (cordova-background-geolocation-lt) this plugin also work app close and running extremely well in my app but when my android mobile  restart or switch off the mobile then  api not sending data to my url. so is there any way to detect this situation when user intentionally cut off his tracking. Thanks for your help in advance.

**Comment by christocracy** [comment]
See API docs for event `#onProviderChange`.
