### ISSUE TITLE
Android phone  restart or  switchoff not detect any status from cordova-background-geolocation-lt

### ISSUE THREAD

**Issue by sudinmondal19** [transistorsoft/cordova-background-geolocation-lt#1062]
I did not get any response  when my android phone  restart or mobile switchoff , you told me #onProviderChange function  provide  phone  restart or mobile switchoff detect status i have using 
(BackgroundGeolocation.onProviderChange) but not get any responese.

i have get  {"network":true,"gps":true,"enabled":true,"status":2} this object from #onProviderChange function .

my code :

api_gps_url = API_URL+'/check_interval_mail';

  get_global_params = this.authService.getTokenSessionMaster();

  configureBackgroundGeolocation() {
    // alert('click url>' + this.api_gps_url);
    // alert('token >'+ this.get_global_params.token);
  
    BackgroundGeolocation.onLocation(location => {
      console.log('[location] - ', location);

      // dashboard data call
      // this.getDashboardData();

    });

    BackgroundGeolocation.onMotionChange(event => {
      console.log('[motionchange] - ', event.isMoving, event.location);
    });

    BackgroundGeolocation.onHttp(response => {
      this.checkAppLoctionEnable = true;
      console.log('[http] - ', response.success, response.status, response.responseText);
    });

    BackgroundGeolocation.onProviderChange(event => {

      this.http.get('check_interval_mail?remarks='+JSON.stringify(event))
      .subscribe(
        (res:any) => {
         
        },
        errRes => {
        }
      );

      alert('onProviderChange event >'+ JSON.stringify(event));
      console.log('[providerchange] - ', event.enabled, event.status, event.network, event.gps);
      
    });

    // work for menually data change
    BackgroundGeolocation.onConnectivityChange((event) => {
       alert("[onConnectivityChange] event >" +  JSON.stringify(event));
      console.log("[onConnectivityChange] ", event);
    });

    /* BackgroundGeolocation.onPowerSaveChange((isPowerSaveMode) => {
      alert("[onPowerSaveChange: >"+ isPowerSaveMode);
      console.log("[onPowerSaveChange: ", isPowerSaveMode);
    }); */

    BackgroundGeolocation.ready({
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 0,
      locationUpdateInterval: 120000,
      //locationUpdateInterval: 600000, //(60, 000 min 1 min interval (when yow walk))
      foregroundService: true,
      url: this.api_gps_url,
      autoSync: true,
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // locationTemplate:'{ "latitude":<%= latitude %>, "longitude":<%= longitude %> }',
      //disableLocationAuthorizationAlert: true
      params: {
        'token':this.get_global_params.token,
        'session':this.get_global_params.session,
        'master':this.get_global_params.master
      },
      allowIdenticalLocations: true,
      heartbeatInterval: 120, 
      //heartbeatInterval: 600, //(60 min 1 min interval  (when yow stay same place))
      stopOnTerminate: false,
      reset: true,
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    
      if (!state.enabled) {
      
        BackgroundGeolocation.start(() => {
          console.log("- Start success");

          //  // dashboard data call
          // this.getDashboardData();

        });

        //BackgroundGeolocation.stop(); //(when logout)
      }
    });

    BackgroundGeolocation.onHeartbeat((event) => {
      console.log("[onHeartbeat] ", event);
    
      // You could request a new location if you wish.
      BackgroundGeolocation.getCurrentPosition({
        samples: 1,
        persist: true
      }).then((location) => {
        console.log("[getCurrentPosition] ", location);
      });
    })
  }

**Comment by christocracy** [comment]
Are you watching the logs with `adb logcat` when you restart the device?  **Always** watch the logs.

Do you know that your Cordova app doesn’t magically launch after a device reboot?  See Wiki “Android Headless Mode”.

**Comment by sudinmondal19** [comment]
when i restart or switch off device then i have called server api to send event data like :
BackgroundGeolocation.onProviderChange(event => {

  this.http.get('check_interval_mail?remarks='+JSON.stringify(event))
  .subscribe(
    (res:any) => {
     
    },
    errRes => {
    }
  );

  alert('onProviderChange event >'+ JSON.stringify(event));
  console.log('[providerchange] - ', event.enabled, event.status, event.network, event.gps);
  
});



but server api  not update when reboot or restart device so, i think #onProviderChange not work

**Comment by christocracy** [comment]
Your **Javascript code does not execute when device is rebooted**.

See wiki “”Android Headless Mode”.

**Comment by sudinmondal19** [comment]
so, how can i do that ?

**Comment by christocracy** [comment]
Did you read the wiki?  That **IS** the answer.

**Comment by sudinmondal19** [comment]
See wiki “”Android Headless Mode”. so , need to write java code ?

**Comment by christocracy** [comment]
> need to write java code ?

Yes, you do.

**Comment by sudinmondal19** [comment]
ok..thank you
