### ISSUE TITLE
vivo android mobile app close then not working cordova-background-geolocation-lt plugin(background mode not working)

### ISSUE THREAD

**Issue by sudinmondal19** [transistorsoft/cordova-background-geolocation-lt#1063]
hi,
 vivo android mobile  not working  cordova-background-geolocation-lt plugin when app close or terminate but other mobile(redmi) working fine even app close then also get my location.

what is problem i do't understand i have test 2 vivo android mobile two mobile not working and not getting location when close app.

**Comment by christocracy** [comment]
http://dontkillmyapp.com

**Comment by sudinmondal19** [comment]
this link http://dontkillmyapp.com not describe vivo phone work or not. please tell me what wrong my code

**Comment by sudinmondal19** [comment]
please tell me what can i do for plugin work
