### ISSUE TITLE
to start bckground location service in app is taking time after killing app from RAM

### ISSUE THREAD

**Issue by anikinitek** [transistorsoft/cordova-background-geolocation-lt#1066]
## Your Environment
* Plugin version: 3.4.1
* Platform: Android
* OS version:9.0
* Device manufacturer / model: Redmi Note5 Pro
* Cordova version (`cordova -v`): 9.1.0
* Cordova platform version (`cordova platform ls`): 
Installed platforms:
  android 7.0.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```
  this.bgGeo = window.BackgroundGeolocation;

    // 2. Listen to events
    this.bgGeo.on('location', this.onLocation.bind(this));
    this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
    this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
    this.bgGeo.on('geofence', this.onGeofence.bind(this));
    this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));
    this.bgGeo.on('heartbeat', this.onHearbeat.bind(this) );

    // 3. Configure it.
    this.bgGeo.configure({
      reset: false,
      debug: false,
      logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
      distanceFilter: 10,
      stopTimeout: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      encrypt: true,
      autoSync: true,
      // desiredOdometerAccuracy:10,
      url: "http://123.176.47.54:9013/" + "/api/v1/Driver" + "/PositionChangeJson?jsonString=",
      headers: {
        'Authorization': "Bearer " + window.localStorage.getItem('acesstoken')
      },
      maxDaysToPersist: 14,
      notification: {
        title: 'LTA Driver',
        text: 'OdoMeter'
      }
    }, (state) => {
      console.log(state);
      this.totaldistance = state.odometer;
      this.bgCurrentPosition();
      // 4. Start the plugin.
      if(!state.enabled)
      this.bgGeo.start();
    });

## Expected Behavior

   I am using this plugin. After initiating i am getting locations. After travelling sometime. I killed my android app . I did not get latitude and longitude up to 5 or 6 minutes. and also odometer starting suppose previous where i killed my app. if i kill my after travelling 1.5 km. after 5 mins. it is starting from 1.5 kms. meanwhile travel distance is missed. 
## Actual Behavior

  After killing if device is moving app should send latitudes and longitudes. it should not distance travelled in between 
## Steps to Reproduce

1. Start App. check your vehcile odometer value
2. travel some distance kill the app from RAM
3. again travel some distance
4. then again check your vehicle odometer value

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Logs please.

**Comment by anikinitek** [comment]
i do't have logs. After killing app from RAM. it is taking time to start . this is main issue. I have question. how much time plugin will take to start background service . after killing app.

**Comment by christocracy** [comment]
The tracking service is unaffected by terminating the app.  It takes *no time*.  This is why logs are required.  You *must* provide logs.  There *are* logs.  You just need to ask the plugin for them.  See wiki “Debugging”.  

There is nothing more to say until you provide logs.

**Comment by anikinitek** [comment]
How can i get logs. can you please help me to get logs

Please see attached data file. there is no location update for 3 mins

{"location":{"event":"motionchange","is_moving":true,"uuid":"2a02bba4-0ef2-48f4-9575-ad39e8d1219e","timestamp":"2020-01-05T15:38:00.453Z","odometer":1813.6,"coords":{"latitude":17.451662,"longitude":78.3947215,"accuracy":5.4,"speed":7.85,"heading":90,"altitude":494.5},"activity":{"type":"in_vehicle","confidence":100},"battery":{"is_charging":false,"level":0.73},"extras":{}}}
{"location":{"event":"motionchange","is_moving":false,"uuid":"e5dcfbea-25f1-4343-b414-9a3a64ca7c67","timestamp":"2020-01-05T15:35:36.195Z","odometer":1509.8,"coords":{"latitude":17.4520397,"longitude":78.3918621,"accuracy":10.1,"speed":0,"heading":0.16,"altitude":498.5},"activity":{"type":"still","confidence":100},"battery":{"is_charging":false,"level":0.73},"extras":{}}}


[jsondata.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/4029241/jsondata.txt)

**Comment by christocracy** [comment]
**i told you** how to get logs **above**:

>  See wiki “Debugging”
