### ISSUE TITLE
State is already enabled after reset the app

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1068]
Using latest version of Cordova and iOS 13. 
Tested on iPhone Pro X Max on the Xcode Simulator.

Process:

1. I launch the app.
2. I run `BackgroundGeolocation.start()` method.
3. I reset the app.
4. I test the state `let state = await BackgroundGeolocation.getState() // state.enabled is true`

The location event isn't getting fired - I have to use the stop method, use the start method again and only then the location event will be fired.

This is the plugin config:

```
BackgroundGeolocation.ready({
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 8,
    preventSuspend: true,
    stopOnTerminate: true,
    startOnBoot: false
  })
```

Why is the plugin auto start even when `startOnBoot` and `stopOnTerminate` are false?

**Comment by Taxi4you** [comment]
Any support?

**Comment by christocracy** [comment]
Logs please.  See Wiki "Debugging".  `state.enabled` is 100% guaranteed to be `false` in the callback to `#ready` method after terminating / re-launching the app with `stopOnTerminate: false`.

```javascript
BackgroundGeolocation.ready({
  stopOnTerminate: false
}).then((state) => {
  console.log('[ready] state.enabled? ', state.enabled);
});
```
