### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Vendelay** [transistorsoft/cordova-background-geolocation-lt#107]
Hello,

With the Background Geolocation active on a demo app, the app crashed with the following error (when I received a phone call, not sure this actually triggered it):

Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x1446cd6b0> was mutated while being enumerated.'

I initialized BackgroundGeolocation with the following options:
bgGeo.configure({
                desiredAccuracy: 0,
                stationaryRadius: 1,
                distanceFilter: 1,
                disableElasticity: true,
                minimumActivityRecognitionConfidence: 10,
                activityRecognitionInterval: 1,
                stopDetectionDelay: 1,
                stopTimeout: 1,
                activityType: 'Fitness',
                autoSync: false,
                debug: false
            });

Thank you

**Comment by christocracy** [comment]
This crash is from *my* demo app with no other 3rd party plugins other than
those specifically requested by the demo app?

Is there no more info from that stackTrace; I see nothing specific
referencing my code

On Saturday, April 23, 2016, Vendelay <notifications@github.com> wrote:

> Hello,
>
> With the Background Geolocation active on a demo app, the app crashed with
> the following error (when I received a phone call, not sure this actually
> triggered it):
>
> Terminating app due to uncaught exception 'NSGenericException', reason:
> '*** Collection <__NSArrayM: 0x1446cd6b0> was mutated while being
> enumerated.'
>
> I initialized BackgroundGeolocation with the following options:
> bgGeo.configure({
> desiredAccuracy: 0,
> stationaryRadius: 1,
> distanceFilter: 1,
> disableElasticity: true,
> minimumActivityRecognitionConfidence: 10,
> activityRecognitionInterval: 1,
> stopDetectionDelay: 1,
> stopTimeout: 1,
> activityType: 'Fitness',
> autoSync: false,
> debug: false
> });
>
> Thank you
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/107>
>


-- 
Snet form Gmail Mobile

**Comment by Vendelay** [comment]
Thanks for the quick reply.
I will try the same config with your demo app and let you know if I still get this error

**Comment by Vendelay** [comment]
Hello,

I made some changes (especially the one suggested in [Background Tasks](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Background-Tasks)  and did not see this error reappearing.

Can you please give me a hint which is not related with the above:
do you know how could I save/see the logs an app is making while the device is not connected to my computer?
I've been using Xcode > Window > Devices, or tools like iConsole, but I can only see the logs for a few hours back max.

Thank you

**Comment by christocracy** [comment]
The plugin has methods [#getLog](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getlogcallbackfn) and [#emailLog](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#emaillogemail-callbackfn).

These logs do **not** record a long duration of time.  Maybe 15min.
