### ISSUE TITLE
Advice Needed For Booting in Background with Javascript variables in URL

### ISSUE THREAD

**Issue by austincraig09** [transistorsoft/cordova-background-geolocation-lt#1072]
## Your Environment
* Plugin version: 3.2.2
* Platform: iOS or Android: iOS
* OS version: 13.3
* Device manufacturer / model: Apple iPhone XR
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.5
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

      $rootScope.setGPSConfig = function () { 
          bgGeo.setConfig({
            url: 'hardcoded URL' +
            $rootScope.$storage.getItem("dealer_id") + '?auth_token=' + UserService.auth_token,
            locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"speed":<%= speed %>,"timestamp":"<%= timestamp %>"}',
            params: {
              UserId: $rootScope.$storage.getItem("user_id"),
              DealerId: $rootScope.$storage.getItem("dealer_id"),
              LocalTimeOffset: timezoneOffset
            },
            schedule: [
              '2-6 8:00-17:00'
            ],
          }).then((state) => {
             bgGeo.requestPermission(function (status) {
              console.log('[requestPermission] SUCCESS', status);
              bgGeo.startSchedule(function () {
                console.log('schedule: ' + state.schedule)
              });
            })
          })
        }

        let timezoneOffset = new Date().getTimezoneOffset();
        let bgGeo = window.BackgroundGeolocation;
        $rootScope.gpsTracking = {};
        $rootScope.gpsTracking.distanceFilter = 4;
        $rootScope.gpsTracking.disableElasticity = false;
        $rootScope.gpsTracking.desiredAccuracy = bgGeo.DESIRED_ACCURACY_HIGH;

        bgGeo.onLocation((location) => {
          console.log('[location] -', location);
        });
        bgGeo.onHttp((response) => {
          console.log('[onHttp] ', response);
        });
        bgGeo.onMotionChange((event) => {
          console.log('[motionchange] -', event.isMoving, event.location);
        });
        bgGeo.onSchedule((state) => {
          console.log('[onSchedule] - enabled? ', state.enabled);
        });

        bgGeo.ready({
          reset: true,
          // debug: true,
          logLevel: bgGeo.LOG_LEVEL_VERBOSE,
          desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
          distanceFilter: $rootScope.gpsTracking.distanceFilter,
          stopTimeout: 3,
          url: 'hardcoded URL' +
          $rootScope.$storage.getItem("dealer_id") + '?auth_token=' + UserService.auth_token,
          locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"speed":<%= speed %>,"timestamp":"<%= timestamp %>"}',
          params: {
            UserId: $rootScope.$storage.getItem("user_id"),
            DealerId: $rootScope.$storage.getItem("dealer_id"),
            LocalTimeOffset: timezoneOffset,
            Device: bgGeo.transistorTrackerParams(window.device)
          },
          autoSync: true,
          stopOnTerminate: false,
          startOnBoot: true,
          // disableElasticity: $rootScope.gpsTracking.disableElasticity,
          heartbeatInterval: 60,
          preventSuspend: true,
          schedule: [
            '2-6 8:00-17:00'
          ],
          locationAuthorizationAlert: {
            titleWhenNotEnabled: "Location services are not enabled",
            titleWhenOff: "Location services are off",
            instructions: "To use background location, you must enable 'Always' in the Location Services settings",
            cancelButton: "Cancel",
            settingsButton: "Settings"
          }
        }).then((state) => {
          // bgGeo.requestPermission(function (status) {
            // console.log('[requestPermission] SUCCESS', status);
            // bgGeo.startSchedule(function () {
            //   console.log('schedule: ' + state.schedule)
            // });
          // })
        })


```

## Expected Behavior

I have the .ready being called every time my app is launched. Because the tracking is only for a select group of people, based on a flag on another view, I will call the .setConfig with the correct values. Then, when the app launches in the background after being closed, it will have the values set from the .setConfig and can successfully send the locations to the URL.
## Actual Behavior

With iOS only, when you swipe to terminate the app, the plugin awakens perfectly after a significant change in location, but the url is failing because the JS $rootScope.$storage.getItem() is not loading the proper values.
## Steps to Reproduce

1. Run code
2. Swipe to terminate app
3. Wait for URL to not come in
4.

## Context

I want iOS to do what Android does, and continue to track and post to the URL with the last known user that should be saved after the .setConfig in the plugin.
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
I do not have logs from when the URL is failing, because my desktop is not mobile, so I do not capture when the URL fails
```

</details>

**Comment by christocracy** [comment]
```javascript
bgGeo.ready({
          reset: false,  // <-- don't reset on ready
```

**Comment by austincraig09** [comment]
I removed the reset from ready and am still seeing same issue. Do I need to have a start of some sort inside my success of .ready to run?

**Comment by christocracy** [comment]
> Do I need to have a start of some sort inside my success 

No.  The plugin remembers its enabled state.

Are you watching the logs?  Why not set debug: true so you can *hear* the plugin?

Note that Config changes provided to #ready is ignored with reset: false.

See Wiki “Debugging”

**Comment by austincraig09** [comment]
Yes, I have enabled debug, and all of my listeners fire correctly, but my URL is not being constructed in my .ready on a background reboot. It is correct the first time, using .setConfig, but then when I close the app it does not have the correct URL when it reboots in the background.

**Comment by christocracy** [comment]
I don't know what you're trying to do.  This is an application error on your part, not a plugin issue.  If you're expecting `#ready` to construct your url with each boot, you'll **not** want to use `reset: false`.

I suggest you store your auth-token in local-storage.  Also, it's not a good idea to place the auth-token in the query-param since this is not encrypted with https.  It would be best placed into `#headers`

**Comment by austincraig09** [comment]
It was a local storage issue. Nothing to do with the plugin. Thanks for you help.
