### ISSUE TITLE
resume and pause event triggers when trying to start backgroundgeolocation

### ISSUE THREAD

**Issue by malmatalla** [transistorsoft/cordova-background-geolocation-lt#1073]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung Galaxy S7
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        this.receivedEvent('deviceready');
        setupAndRunBGGeo(); 
    },

    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};

document.addEventListener("resume", function(){
	console.log("RESUMED APPLICATION");
}, false);

document.addEventListener("pause", function(){
	console.log("PAUSED APPLICATION");
}, false);

var bgGeo;
function setupAndRunBGGeo(){
	  bgGeo = window.BackgroundGeolocation;

	  bgGeo.onLocation(function(location) {
	    console.log('[location] -', location);
	  }); 

	  bgGeo.ready({
	    reset: false,
	    debug: true,
	    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
	    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
	    distanceFilter: 10,
	    stopOnTerminate: true,
	    startOnBoot: false
	  }, function(state) {    // <-- Current state provided to #configure callback
	    // 3.  Start tracking
	    console.log('BackgroundGeolocation is configured and ready to use');
	    if (!state.enabled) {
	      bgGeo.start().then(function() {
	        console.log('- BackgroundGeolocation tracking started');
	      });
	    }
	  });
}

// Executed via a regular <button>
function startGeolocation(){
	console.log("start");
	bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking successfully started');
    });
}

// Executed via a regular <button>
function stopGeolocation(){
	console.log("stop");
	bgGeo.stop(function(){ // TODO IMPORTANT WE MIGHT NEED THIS
		console.log('- BackgroundGeolocation tracking stopped since no services are running');                
    });
}

app.initialize();
```

## Expected Behavior
I expect to be able to start and stop the plugin at any time. If the user isnt using any of our services at the moment, we dont want background-geolocation to be active because of batterydrain. Therefore, we check if there are any services active in the pause-event and stop the plugin as necessary. Therefore we also need to start background-geolocation on resume. But starting it at resume triggers the pause-event and then resume-event so we get stuck in an infinite loop where we are turning the plugin on and of. 

## Actual Behavior
The pause and resume events are triggered on bgGeo.start(); 

## Steps to Reproduce
1. Start the application and initialize bgGeo. Both resume and pause event are called twice.

## Context
We are building a service that sends coordinates to our server so that other people can see where you are at real time.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Received Event: deviceready
index.js:73 BackgroundGeolocation is configured and ready to use
index.js:52 PAUSED APPLICATION
index.js:76 - BackgroundGeolocation tracking started
index.js:48 RESUMED APPLICATION
index.js:60 [location] - Object
index.js:52 PAUSED APPLICATION
index.js:48 RESUMED APPLICATION
```

</details>

**Comment by christocracy** [comment]
See API docs `Config.disableLocationAuthorizationAlert`

**Comment by malmatalla** [comment]
I´ve tried both  Config.disableLocationAuthorizationAlert and Config.
Config.locationAuthorizationAlert. App still triggers pause and resume when
bgGeo.start() is called.

Den ons 15 jan. 2020 kl 16:14 skrev Chris Scott <notifications@github.com>:

**Comment by christocracy** [comment]
`Config.locationAuthorizationAlert` has *nothing* to do with this (that's an iOS-only option).

I see no issues at all with `disableLocationAuthorizationAlert: true` using `3.4.2`.  Your problem is **not** caused by the plugin.

It's not a bug, it's *by design* that these `pause` / `resume` events occur, since the Android plugin has implemented a feature that allows the plugin to show a single dialog to resolve settings issues when device-settings are not properly configured for the desired location-request (eg: Location-services enabled, High accuracy location enabled).  This feature requires a new Activity be launched, which happens to transparent so you don't actually *see* it.

When you configure `disableLocationAuthorizationRequest: true`, this new feature is **by-passed**.

It's **100% guaranteed** that `disableLocationAuthorizationAlert` works.
