### ISSUE TITLE
Strange locations pushing behaviour

### ISSUE THREAD

**Issue by caiusCitiriga** [transistorsoft/cordova-background-geolocation-lt#1074]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: OnePlus 5T
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```typescript
const jwt = await this.storage.get(StorageKeys.authToken);
const refToken = await this.storage.get(StorageKeys.refreshToken);
BackgroundGeolocation.ready({
    debug: true,
    startOnBoot: true,
    distanceFilter: 10,
    reset: resetConfig,
    stopOnTerminate: false,
    foregroundService: true,
    geofenceModeHighAccuracy: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    authorization: {
        strategy: 'JWT',
        accessToken: jwt,
        refreshToken: refToken,
        refreshPayload: { refreshToken: '{refreshToken}' },
        refreshUrl: `${environment.ApiEndpoint}/auth/refresh`,
    },
    url: `${environment.ApiEndpoint}tracking/position/logs`,
}, async (state) => {
    this.startBackgroundGeolocation(mode);
    resolver(state);
    this.geolocationReady$.next(true);
});
```

## Expected Behavior
Since `allowIdenticalLocations` is not specified, should default to `false`, which indeed by the logs I can confirm. I expect to find only distinct locations on the server logs.

## Actual Behavior
The strange thing is that everything works fine, and after a while in `terminated` state the plugin starts "going crazy", and it loops for a while the "whoop" & "ding!" sound. At the first time I thought at an authorization error, but is not the case since I don't have any 403 errors serverside. And the token lasts 10hrs, so it's kinda impossible. 
Watching the logs I noticed that at some point during the tracked journey the locations comes back to the starting point, following all the journey until it reaches the "breakpoint" and once reached, everything starts working back to normal. 

I've screenshotted the data on the server logs, and the weird thing is that the timestamp is **identical** , the location coordinates too, but the activity type is "still" while in that location I can ensure that I was driving. 

Also the odometer goes up, and the battery state is not the same, so... WTF 😱? Am I doing something wrong?

I assume then that the "fake" location is the "still" one, the question is... How come does it arrive to the server?

Unfortunately at the moment I don't have access to the library logs... but still I think that we have some "data" to work on..

![Screenshot 2020-01-17 at 15 22 09](https://user-images.githubusercontent.com/12595721/72619285-3b5d9b00-393d-11ea-90ea-abeb7bb962bb.png)

**Comment by christocracy** [comment]
I may have experienced something like this on my OnePlus A510 last week.  Try installing latest from private repo `3.5.0`, released yesterday.

**Comment by caiusCitiriga** [comment]
Ahahahahah it's **exactly** my phone!! Ok, I think it's time to re-buy 😝

**Comment by christocracy** [comment]
The OnePlus A510 is one of the better performers among my test devices.:
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 10
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 8.0.0

**Comment by caiusCitiriga** [comment]
I've noticed that on my side too.. Anyway I close this since the problem is known and fixed. I've sent you an email regarding the purchase in the meanwhile.

Thanks again.
