### ISSUE TITLE
Can't build project without access to private repo

### ISSUE THREAD

**Issue by bhavikmit** [transistorsoft/cordova-background-geolocation-lt#1076]
## Your Environment
* Plugin version: 2.40.5
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Motorola 
* Cordova version (`cordova -v`): 9.0
* Cordova platform version (`cordova platform ls`): 7.1.4

## Expected Behavior

Should be able to build project. 

## Actual Behavior

Npm is throwing 404 error when I do `npm install`. 

## Context

I believe this is due to the fact that in my package.json I have mentioned repo url as a dependency.  
```json
"cordova-background-geolocation": "git+https://github.com/transistorsoft/cordova-background-geolocation.git"
```
My support just ended few days back. As per what I heard keys don’t expire.  Support does. so I should be able to access the plugin and use the keys I currently have. How do I do that?

**Comment by christocracy** [comment]
Remove that plugin and follow the instructions in the readme of this repo.

**Comment by vasani-arpit** [comment]
Thanks. will do!!

**Comment by bhavikmit** [comment]
Will do. thanks !!

**Comment by bhavikmit** [comment]
@christocracy 
Didn't work. Can't add logs and information here because it has sensitive content. I have sent it over email to you.

**Comment by christocracy** [comment]
License Config changed significantly since the last time you added the plugin.  There is no more —variable LICENCE.

Read the setup docs.

**Comment by bhavikmit** [comment]
Okay. Checking. Thanks
