### ISSUE TITLE
How to vehicle start time and stop time using this package

### ISSUE THREAD

**Issue by nijesh17** [transistorsoft/cordova-background-geolocation-lt#1079]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs for event #onMotionChange and analyze location.activity.

**Comment by christocracy** [comment]
Also see event #onActivityChange and Config.trggeractivities
