### ISSUE TITLE
Limit server calls by interval

### ISSUE THREAD

**Issue by PWRM** [transistorsoft/cordova-background-geolocation-lt#1080]
This is not an issue but a question.
It all works but there are too many locations send to the server with the standard server mechanisme.
I would like the server calls to limit to ,let's say every 15 seconds. It only needs to send the last longitude and latitude.

Seems there is a setting for Android: locationUpdateInterval
What about iOS?

**Comment by christocracy** [comment]
Please do not ignore issue template.  The config you're providing the plugin **is relevant** to your question.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by PWRM** [comment]
Your Environment

Plugin version: 3.4.2
Platform: iOS
OS version: 13.3
Device manufacturer / model: Apple
Cordova version (cordova -v): 9.0.1
Cordova platform version (cordova platform ls): ios 5.1.1
Plugin config provided to #ready:
        bgGeo.ready({
            reset: true,
            desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,     // Highest possible accuracy: GPS + Wifi + Cellular
            distanceFilter: 10,     // Record a location every 10 meters.
            stopTimeout: 1,         // Change state to stationary after 1 min with device "still"
            stopOnTerminate: true, // Don't stop tracking when app is terminated.
            foregroundService: true,// Prevent Android from terminating service due to memory pressure from other apps.
            heartbeatInterval: 60,  // <-- heartbeat event every 60s
            url: app.host,
            extras: {
                    id: app.storage.getItem('id'),
                    },
            params: bgGeo.transistorTrackerParams(window.device),
            debug: false,            // Debug sounds & notifications
            autoSync: true,         // Auto sync each recorded location to #url immediately.
            sample: false,
            logLevel: bgGeo.LOG_LEVEL_OFF
        }, function(state) {
            app.setState(state);
            //console.log('- BackgroundGeolocation is configured and ready to use');
        });

Expected Behavior
Sends location updates to server

Actual Behavior
Sends location updates to server, but sometimes 3x within 1 second with the same coordinates.

Steps to Reproduce
Run demo program and store locations into database with a timestamp
See attached screenshot, look at id 1597, 1598, 1599
Context

Debug logs

Logs
![Screenshot 2020-01-28 at 15 14 00](https://user-images.githubusercontent.com/49676024/73271419-d9285400-41e0-11ea-99d5-8dc425724e46.png)

**Comment by christocracy** [comment]
Read API docs `Config.distanceFilter` and "HTTP Guide".

**Comment by PWRM** [comment]
I use the distanceFilter, but strange enough I get the 3x in one second.
Maybe I do not understand but a way to go would be: autoSyncThreshold.
But that is not a time based setting, but rather an amount. 
Are there other options?

**Comment by christocracy** [comment]
Turn on `debug: true` and learn to observe the logs.  See Wiki "Debugging".

**Comment by PWRM** [comment]
Could you help me with a bgGeo.ready setting that does what I need? Most likely I am doing the wrong settings and I don't see how the debug would solve this.

**Comment by christocracy** [comment]
There is nothing wrong with your config and it's likely working exactly as intended, you just need to learn about how the plugin works.  This is a very complex plugin and you're not going to learn how to properly use it after a couple of days.

Read the Wiki articles, turn on `debug: true`, turn on `LOG_LEVEL_VERBOSE` and start observing the logs and *listening* to the plugin.  Then go outside for a nice long field-test of 1km or more.

**Comment by PWRM** [comment]
Oh yes you are right. It is very complex, and it goes beyond my technical skills. That is the reason why my customer bought it today so we could have the functionality and, hopefully, some assistance from you. I wrote you an email who my customer is. We do not want a lot of tweaking, just using the standard mechanisms. Is that included with the purchase of the license?

**Comment by christocracy** [comment]
- You need to *learn* how to use the plugin.  
- You need to *learn* how to observe the logs.  
- You need to got *outside* and field-test yourself.
- You need to learn to use the [demo server](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.transistorauthorizationtoken.html).
