### ISSUE TITLE
Tapping on "Location Services activated" notification opens new app instance instead of resuming.

### ISSUE THREAD

**Issue by mirceah13** [transistorsoft/cordova-background-geolocation-lt#1082]
## Your Environment
* Plugin version: ^3.4.2
* Platform: Android
* OS version: 8+
* Device manufacturer / model: Samsung Galaxy S10+
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 8.1.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      isMoving: true,
      reset: true,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      url: 'http://DESKTOP-KDBE1MG:9000/locations',
      autoSync: true,
      stopOnTerminate: true,
      startOnBoot: true
    }
```

## Expected Behavior
App should resume to current state

## Actual Behavior
App is reinitialized and goes to landing page (login -> home)

## Steps to Reproduce

1. BackgroundGeolocation.start();
2. Location Tracking starts working.
3. App Notification appears on notification bar
4. Tap on Notification (new app instance is being created)

## Context
Tried adding 
```javascript <!-- syntax-highlighting:  paste your code below -->
<preference name="AndroidLaunchMode" value="singleTask" />
``` 
in config.xml which ends up in AndroidManifest.xml but with no effect.
[https://www.mobomo.com/2011/06/android-understanding-activity-launchmode/](launchmode)

I've read about [foregroundService](http://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.state.html#foregroundservice) and i know about the persistent Notification that is required by the operating-system with a foreground-service, which cannot be hidden. But inevitably the user will tap on this notification and 
the app experience will be bad because current state is lost and app starts over from login page / main page.
I have tried with a regular notification which I created from the app, and when tapping on that one the app resumes from background and works as expected.

looks like a duplicate for #819 but comments there did not help with my issue.

App is built using Ionic . here is 'ionic info'

```javascript <!-- syntax-highlighting:  paste your code below -->
Ionic:

   Ionic CLI                     : 5.4.15 (C:\Users\m\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.3.23
   @angular/cli                  : 8.3.23
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 12 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v12.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
``` 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
This is fixed in the private “paid” version.  It will be released here in the near future.

**Comment by mirceah13** [comment]
Thank you
