### ISSUE TITLE
onPowerSaveChange() is Not working in Android

### ISSUE THREAD

**Issue by paragghadge** [transistorsoft/cordova-background-geolocation-lt#1084]
## Your Environment
* Plugin version: cordova-background-geolocation-lt
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy S8 / RedMi Note 8 Pro
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
--
Available platforms:
android ^8.0.0
browser ^6.0.0
electron ^1.0.0
ios ^5.0.0
osx ^5.0.0
windows ^7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
 this.platform.ready().then(this.onDeviceReady.bind(this));
    this.state = {};
    // BackgroundGeolocation initial config.
    this.isMoving = false;
    this.enabled = false;
    this.autoSync = true;
    this.distanceFilter = 10;
    this.stopTimeout = 1; // minutes
    this.stopOnTerminate = false;
    this.startOnBoot = true;
    this.debug = true;

    // Android specific property
    this.allowIdenticalLocations = true;

    // UI members.
    this.motionActivity = 'Activity';
    this.menuActive = false;
    this.batteryObject = {};
  }

BackgroundGeolocation.ready({
      // Logging / Debug config
      debug: this.debug,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // Geolocation config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,  // <-- highest possible accuracy
      distanceFilter: 10,
      // ActivityRecognition config
      stopTimeout: 1,
      // Application config
      stopOnTerminate: false,
      startOnBoot: true,
      heartbeatInterval: 60,
      allowIdenticalLocations: true,
      // HTTP / Persistence config
      url: ENV.TRACKER_HOST + '/api/locations',
      authorization: {
        strategy: 'JWT',
        accessToken: token.accessToken,
        refreshToken: token.refreshToken,
        refreshUrl: ENV.TRACKER_HOST + '/api/refresh_token',
        refreshPayload: {
          refresh_token: '{refreshToken}'
        },
        expires: token.expires
      },
      autoSync: this.autoSync,
      autoSyncThreshold: 0
    }, (state) => {
      console.log('- BackgroundGeolocation ready: ', state);
      // Set current plugin state upon our view.
      this.zone.run(() => {
        this.enabled = state.enabled;
        this.isMoving = state.isMoving;
        this.autoSync = state.autoSync;
        this.distanceFilter = state.distanceFilter;
        this.stopTimeout = state.stopTimeout;
        this.stopOnTerminate = state.stopOnTerminate;
        this.startOnBoot = state.startOnBoot;
        this.debug = state.debug;
      });
    });
```

## Expected Behavior
onPowerSaveChange() - Fired when the state of the operating-system's "Power Saving" mode changes. It should fire onPowerSaveChange() event when the device reaches to it's power saving mode.

## Actual Behavior
onPowerSaveChange() Event is not working in android. 
Tested on Samsung Galaxy S8 / RedMi Note 8 Pro devices.

## Steps to Reproduce

onPowerSaveChange() Event is not working in android. 
Tested on Samsung Galaxy S8 / RedMi Note 8 Pro devices.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
No Logs
```

</details>

**Comment by christocracy** [comment]
Are you unplugging your device from power to test it?

I confirm it's working in the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp).  The SampleApp [draws a red border around the screen and posts a Toast message](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/src/pages/advanced/advanced.ts#L919-L924) and I *do* witness that.

**Comment by paragghadge** [comment]
I have tested the same in iOS and it's working. But in Android it's not working.
Yes. While testing I unplugged my device from power.

**Comment by christocracy** [comment]
I've confirmed working in SampleApp on following devices:
- Nexus 5 @ 6.0.1
- OnePlus A510 @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Pixel 3a @ 10.0.0


![](https://dl.dropboxusercontent.com/s/zmumfdzdqs6m4h5/Screenshot%202020-01-29%2013.19.17.png?dl=1)

*Red Border* is toggled in `onPowerSaveChange` callback.
![](https://dl.dropboxusercontent.com/s/2mc4f77f5hfwv5j/Screenshot%202020-01-29%2013.20.05.png?dl=1)

**Comment by paragghadge** [comment]
I agree with your point But Plugin says that --
onPowerSaveChange Event - Fired when the state of the operating-system's "Power Saving" mode changes. Your callback will be provided with a bool showing whether "Power Saving" is enabled or disabled.?

How you will can power saving is disabled? because to disable power saving mode automatically we need to charge the mobile with charger plugin in. 

Please explain on same.
