### ISSUE TITLE
Ionic v4 cordova - Undefined symbols for architecture x86_64 - iOS Build error

### ISSUE THREAD

**Issue by DannyCaldeira24** [transistorsoft/cordova-background-geolocation-lt#1085]
## Your Environment
* Plugin version:
* cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
* cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
* cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
* Ionic CLI: 5.4.13
* Ionic Framework: @ionic/angular 4.11.10
* Platform: iOS or Android
* OS version: MacOS Catalina v10.15.2
* Cordova version (`cordova -v`): v9.0.0
* @angular-devkit/architect": "~0.801.3,
* @angular-devkit/build-angular": "~0.801.3,
* Cordova platform version (`cordova platform ls`): ios 5.1.1
* xCode v11.1

## Expected Behavior
Build in iOS

## Actual Behavior

Getting issue on build in iOS. (In Android is OK)

## Context

I have tried to generate the application for iOS and it presents me with the following error. He tried reinstalling the node_modules folder, reinstalling the plugins and even tried installing the following plugin https://github.com/transistorsoft/cordova-plugin-cocoalumberjack. But nothing seems to work.

## Debug logs
Undefined symbols for architecture x86_64:
  "_OBJC_IVAR_$_DDLogMessage._tag", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_METACLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_METACLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_CLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_CLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._message", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDAbstractLogger._logFormatter", referenced from:
      -[TSDBLogger db_log:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._saveThreshold", referenced from:
      -[TSDBLogger initWithLogDirectory:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._timestamp", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._flag", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDLogMessage._context", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._function", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._maxAge", referenced from:
      -[TSDBLogger getLog:] in TSLocationManager(TSDBLogger.o)
      -[TSDBLogger db_delete] in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in TSLocationManager(LocationAuthorization.o)
      objc-class-ref in TSLocationManager(TSConfig.o)
      objc-class-ref in TSLocationManager(HttpResponse.o)
      objc-class-ref in TSLocationManager(TSDBLogger.o)
      objc-class-ref in TSLocationManager(TSScheduler.o)
      objc-class-ref in TSLocationManager(RPC.o)
      objc-class-ref in TSLocationManager(TSGeofenceEvent.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
        Ld build/emulator/xxx.app/xxx normal x86_64
(1 failure)
Command finished with error code 65: xcodebuild -workspace,xxx.xcworkspace,-scheme,xxx,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 11 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/adminfs/Desktop/github/xxx/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/adminfs/Desktop/github/xxx/platforms/ios/build/sharedpch,-UseModernBuildSystem=0
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/adminfs/Desktop/github/xxx/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --verbose --buildFlag=-UseModernBuildSystem=0 exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 2 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 65) +73ms

**Comment by christocracy** [comment]
The plugin no longer requires the cocoa-lumberjack plugin so get rid of that.

The plugin now [imports Cocoalumberjack via Cocoapods](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L45).

You need to open the .xcworkspace in XCode, not the .xcodeproj.

**Comment by christocracy** [comment]
And try removing / re-adding the iOS platform

**Comment by DannyCaldeira24** [comment]
It worked, thank you very much.

Steps:
* ionic cordova platform remove ios
* ionic cordova platform add ios
* ionic cordova resources ios --force
And subsequently
* ionic cordova build ios --prod
My mistake was to try directly doing the ionic cordova build
