### ISSUE TITLE
ld: library not found for -lCocoaLumberjack on IOS

### ISSUE THREAD

**Issue by ademmecit** [transistorsoft/cordova-background-geolocation-lt#1086]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS 
* OS version: macOS Catalina
* Device manufacturer / model: MacBook Pro (Retina, 13-inch, Mid 2014)
* Cordova version (`cordova -v`):  9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`):  Installed platforms:
  ios 5.1.1
Available platforms: 
  android ^8.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below --> 

Sample code @Github
```

## Expected Behavior

I got error message while i am trying to run the app on IOS simulator by using xcode  

## Actual Behavior

Here is the error  : 
ld: warning: directory not found for option '-L/Users/myuser/Library/Developer/Xcode/DerivedData/MyApp-afznxusmeelhtsdujkqfrwijuvnd/Build/Products/Debug-iphonesimulator/CocoaLumberjack'
ld: library not found for -lCocoaLumberjack

## Steps to Reproduce

1.  create an empty ionic project :   
ionic start sp_ltv2 blank --type=angular
2. install plugin 
ionic cordova plugin add cordova-background-geolocation-lt
Here is the output : 
> cordova plugin add cordova-background-geolocation-lt
Installing "cordova-background-geolocation-lt" for ios
Installing "cordova-plugin-background-fetch" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Adding cordova-background-geolocation-lt to package.json

*** There is a warning about framework 

3.  ios platform add 
ionic cordova platform add ios 

4. ios platform prepare 
ionic cordova prepare ios 

5.  Open xcode project on xcode and try to run the app on IOS simulator 

6. I got following error on xcode : 

ld: warning: directory not found for option '-L/Users/myuser/Library/Developer/Xcode/DerivedData/MyTestApp-euhlfqcrvohrtpaowlxuzwpptcdn/Build/Products/Debug-iphonesimulator/CocoaLumberjack'
ld: library not found for -lCocoaLumberjack
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Context

I am trying to run the app on IOS (got the error just after installing plugin. Next step will be modifying config.xml for ios and adding proper codes to app) 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->

ld: warning: directory not found for option '-L/Users/myuser/Library/Developer/Xcode/DerivedData/MyTestApp-euhlfqcrvohrtpaowlxuzwpptcdn/Build/Products/Debug-iphonesimulator/CocoaLumberjack'
ld: library not found for -lCocoaLumberjack
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

</details>

**Comment by christocracy** [comment]
Please search issues *before* posting.  Duplicate #1085
