### ISSUE TITLE
Missing permission on android: ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by Maikell84** [transistorsoft/cordova-background-geolocation-lt#1088]
The plugin is missing `ACCESS_BACKGROUND_LOCATION` permission on android.
This permission is required for `Android 10` if you build your app with API level 29 or higher.

Please see this Android article: [**Privacy changes in Android 10**](https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location)

## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 10
* Device manufacturer / model: all
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.1.0

## Expected Behavior
It should add the permission to run in background

## Actual Behavior
It does not add the permission to run in background

**Comment by cmpDrone** [comment]
Facing this same issue. Due to this users are not getting geofence alerts.

**Comment by mknnaren** [comment]
Facing this same issue. Due to this users are not getting geofence alerts.

**Comment by christocracy** [comment]
The plugin does contain this permission and has for a long time.  You need to provide far more information, such as
- plugin version
- stacktrace
- device model / os version
- Cordova version

**Comment by mknnaren** [comment]
> The plugin does contain this permission and has for a long time. You need to provide far more information, such as
> 
> * plugin version
> * stacktrace
> * device model / os version
> * Cordova version

- plugin version : 3.6.2
- stacktrace : sry I will post the logs later as I am working on this thing to fix the geofence alerts.
- device model / os version : Google Pixel XL / Android 10
- Cordova version: 9.0.0
- Cordova android platform version: 8.1.1

Problem: 
Users are not getting (or getting delayed) geofence alerts when they have chosen the access type option to "allow only when app is in use".
If they chose access type as "Always allow", then the geofence alerts are working fine.
This behavior was in iOS but not in Android 9 or lower.

Request:
Can you please guide me on how to check if the user has selected the option "allow only when app is in use" and force him to chose "Always allow" option.

Thank you,
Naren

**Comment by christocracy** [comment]
@mknnaren your problem has nothing to do with this *closed* issue.  Open a new issue.

**Comment by mknnaren** [comment]
> @mknnaren your problem has nothing to do with this _closed_ issue. Open a new issue.

ok will do that.
Thanks
