### ISSUE TITLE
How does getOdometer works

### ISSUE THREAD

**Issue by chandriano** [transistorsoft/cordova-background-geolocation-lt#109]
I'm not using bgGeo plugin synchronisation because I need to do it by myself in my API, but I'm not able to use getOdometer and I don't know if it's because of that. Does the bgGeo (window.BackgroundGeolocation) object use the API sync to calculate traveled distance or I'm using plugin wrongly?

**Comment by christocracy** [comment]
how are you using `#getOdometer`?

**Comment by chandriano** [comment]
bgGeo.getOdometer(function(distance) {
  console.log("Distance travelled: ", distance);
});

**Comment by christocracy** [comment]
That's fine.  What version of the plugin are you using?

**Comment by chandriano** [comment]
version 1.5.1

**Comment by christocracy** [comment]
It should work.  works here on both iOS and Android.  What's the problem?

**Comment by christocracy** [comment]
btw, are you using `stopOnTerminate: true` with Android?

**Comment by chandriano** [comment]
no, it's false, I cleaned some functions, my server structure is below. I'm able to change location right, the only problem is the calc of traveled distance that is always returning undefined.

`(function(){
  'use strict';

  angular.module('app')
  .factory('bgGeolocationService', ['$rootScope',
    function bgGeolocation($rootScope){
      return {
        initialize : function(){
          var bgGeo = window.BackgroundGeolocation;
          var lastPosition;
          
          /**
          * This callback will be executed every time a geolocation is recorded in the background.
          */
          var callbackFn = function(location, taskId) {
              dadosService.motorista.atualizaPosicao({
                latitude: location.coords.latitude,
                longitude: location.coords.longitude,
                taximetroDistancia: bgGeo.getOdometer()
              }).then(function(response) {
                lastPosition = location;
              });
            
            // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
            // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
            bgGeo.finish(taskId);
          };

          var failureFn = function(error) {
              console.log('BackgroundGeoLocation error');
          }

          bgGeo.on('location', callbackFn, failureFn);
          
          // BackgroundGeoLocation is highly configurable.
          bgGeo.configure(callbackFn, failureFn, {
            desiredAccuracy: 0,
            timeout: 1200,
            distanceFilter: 100,
            disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
            locationUpdateInterval: 1200,
            minimumActivityRecognitionConfidence: 20,   // 0-100%.  Minimum activity-confidence for a state-change 
            fastestLocationUpdateInterval: 5000,
            activityRecognitionInterval: 2000,
            stopDetectionDelay: 3,   // [iOS] delay x minutes before entering stop-detection mode
            stopTimeout: 3,  // Stop-detection timeout minutes (wait x minutes to turn off tracking)
            activityType: 'AutomotiveNavigation',

            // Application config
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user) 
            forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user) 
            forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user) 
            stopOnTerminate: false,              // <-- Don't stop tracking when user closes app.
            startOnBoot: false,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.
          });

          bgGeo.changePace(true); // Setting pace to fast to enable aggresive tracking as soon as the plugin is started
                                  // Comment it to enable default behaviour
          $rootScope.bgGeo = bgGeo;
        },
        start : function(){
          $rootScope.bgGeo.start();
        },
        stop : function(){
          $rootScope.bgGeo.stop();  
        }
      }
    }
  ]);
})();`

**Comment by christocracy** [comment]
```
taximetroDistancia: bgGeo.getOdometer()  // <--------- You're not providing a callback here
              }).then(function(response) {
                lastPosition = location;
              });

```

It should be:
```
bgGeo.getOdometer(function(distance) {
  console.log('distance: ', distance);
});
```

You're aware your Javascript callbacks don't run anymore when user closes the app with `stopOnTerminate: false`?

**Comment by chandriano** [comment]
Wasn't aware about stopOnTerminate, thanks. About the code, I'm receiving 0.
bgGeo.getOdometer(function(distance) {
  console.log('distance: ', distance); // distance: 0
});

**Comment by chandriano** [comment]
the log in console:

```
atuPos dist Object {latitude: -19.9299934, longitude: -43.9320757, taximetroValor: 47.95, taximetroDistancia: 0, taximetroTempo: 87}
dados.js:472 atuPos dist Object {latitude: -19.9299934, longitude: -43.9320757, taximetroValor: 47.95, taximetroDistancia: 0, taximetroTempo: 87}
bgGeolocation.js:46 Distance travelled:  0
dados.js:472 atuPos dist Object {latitude: -19.928796368144948, longitude: -43.92689310014248, taximetroValor: 48.45, taximetroDistancia: 0, taximetroTempo: 88}
bgGeolocation.js:46 Distance travelled:  0
dados.js:472 atuPos dist Object {latitude: -19.9274832446335, longitude: -43.93648836761713, taximetroValor: 48.45, taximetroDistancia: 0, taximetroTempo: 88}
bgGeolocation.js:46 Distance travelled:  0
```

**Comment by christocracy** [comment]
Now go for a walk.

On Tue, May 3, 2016 at 5:26 PM, Conrado Costa <notifications@github.com>
wrote:

> the log in console:
>
> atuPos dist Object {latitude: -19.9299934, longitude: -43.9320757, taximetroValor: 47.95, taximetroDistancia: 0, taximetroTempo: 87}
> dados.js:472 atuPos dist Object {latitude: -19.9299934, longitude: -43.9320757, taximetroValor: 47.95, taximetroDistancia: 0, taximetroTempo: 87}
> bgGeolocation.js:46 Distance travelled:  0
> dados.js:472 atuPos dist Object {latitude: -19.928796368144948, longitude: -43.92689310014248, taximetroValor: 48.45, taximetroDistancia: 0, taximetroTempo: 88}
> bgGeolocation.js:46 Distance travelled:  0
> dados.js:472 atuPos dist Object {latitude: -19.9274832446335, longitude: -43.93648836761713, taximetroValor: 48.45, taximetroDistancia: 0, taximetroTempo: 88}
> bgGeolocation.js:46 Distance travelled:  0
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/109#issuecomment-216669596>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chandriano** [comment]
I'm still trying to fix this problem, when I use getLocations the plugin returned me a big array with objects, so the plugin is saving the locations, but in this objects, the parameter odometer is 0 too. below have two samples of those objects. I can do a for  to walk through this array and calculate the total traveled distance but I don't want to have to do this every time I reload the position because it will be a big array...
Do you think it could be a bug in the plugin or probably I am using it wrongly?
```
0: object {
  coords: {
    accuracy: 1
    altitude: 65
    heading: 0
    latitude: -19.933094990435965
    longitude: -43.92789389938116
    speed: 0
  }
  event: "motionchange"
  is_moving: false
  odometer: 0
  timestamp: Wed May 04 2016 15:15:39 GMT-0300 (BRT)
  uuid: "a9cffaed-7437-4317-8b46-98012b845158"
}

1: object {
  coords: {
    accuracy: 1
    altitude: 65
    heading: 0
    latitude: -19.92768528859166
    longitude: -43.93236514180899
    speed: 0
  }
  event: "motionchange"
  is_moving: false
  odometer: 0
  timestamp: Wed May 04 2016 15:15:51 GMT-0300 (BRT)
  uuid: "c8e1dae2-fb27-4d72-9462-f7fb5c10ff48"
}
```

**Comment by achatsenovea** [comment]
hi,
i'm also using the odometer function and I have the same problem than chandriano. I'm coding the function on my own with the geolib plugin and the location sended by your plugin. My odometer increase but yours doesn't.

Distance travelled:  0
Distance travelled of my odometer:  255

Distance travelled:  0
Distance travelled of my odometer:  466

Distance travelled:  0
Distance travelled of my odometer:  521

**Comment by christocracy** [comment]
I'm currently refactoring odometer-calculation to keep track of median-accuracy of last 10 points.  If there's an issue with it, it's probably fixed now.

**Comment by christocracy** [comment]
I've pushed refactored odometer calculation to master.

**Comment by christocracy** [comment]
Status please.
