### ISSUE TITLE
Headless not work when close the APP. (background mode)

### ISSUE THREAD

**Issue by sistemas10info** [transistorsoft/cordova-background-geolocation-lt#1090]
Hi

We set up the translator plugin on Android.

It is working correctly when the APP is open.
In headLess = true mode (when the APP is closed), it works for a few minutes and then stops completely.

Native Android is configured with the javascript classes correctly.

We haven't bought the license yet, but our intention is to buy for 5 applications.

Please Help me.

Thank's.

Configuration Code.

        var bgGeo = window.BackgroundGeolocation;
        // console.log('Inicializando variável Back');

        // location event: Fires whenever a location is recorded.
        bgGeo.onLocation(function(location) {
            console.log('[event] location: ' + location);
            //app.setLocation(location);
            //alert('[event] location: ' + location);
        }, function(error) {
            //console.log('[event] location error: ', error);
            alert('[event] location error: ', error);
        });

        // motionchange event:  Fires when plugin changes state from Stationary->Moving and vice-versa.
        bgGeo.onMotionChange(function(location) {
            //console.log('[event] motionchange' + location);
            app.setState({
                enabled: true,
                isMoving: location.isMoving
            });
            //alert('[event] motionchange' + location);
        });

        // providerchange event:  Fires when user changes location authorization)
        bgGeo.onProviderChange(function(provider) {
            //console.log('[event] providerchange: ', provider);
            app.setProvider(provider);
            //alert('[event] providerchange: ' + provider);
        });

		bgGeo.onHeartbeat((event) => {
		  console.log("[onHeartbeat] ", event);
		
		  // You could request a new location if you wish.
		  bgGeo.getCurrentPosition({
		    samples: 1,
		    persist: true
		  }).then((location) => {
		    console.log("[getCurrentPosition] ", location);
		  });
		})
		
        bgGeo.watchPosition((location) => {
            //console.log("[watchPosition] -", location);
            app.setWatch(location);
          }, (errorCode) => {
            //console.log("[watchPosition] ERROR -", errorCode);
            alert("[watchPosition] ERROR -" + errorCode);
          }, {
            interval: 2000
        });

        // 2. Execute #ready method:
        bgGeo.ready({
          reset: true,
          debug: true,
          logLevel: bgGeo.LOG_LEVEL_VERBOSE,
          desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10,     
          url: 'http://xxxxxx.com/post-geo.php',
          extras: {
            id_key_usuario: "85dfsdf7744115544",  // SOME FIELDS
            codigo_int: "3333",
            sistema: "Dryca"
          },
          autoSync: true,
          
          stopOnTerminate: false,          
          enableHeadless: true,
          
          heartbeatInterval: 60,
          
          startOnBoot: true
        }, function(state) {    // <-- Current state provided to #configure callback
          // 3.  Start tracking
          // console.log('BackgroundGeolocation is configured and ready to use');
          //alert('BackgroundGeolocation is configured and ready to use');
          if (!state.enabled) {
            bgGeo.start().then(function() {
              // console.log('- BackgroundGeolocation tracking started');
              //alert('- BackgroundGeolocation tracking started');
            });
          }
        });
        console.log('Inicializou.......');
        //alert('Inicializou Certo');
        /**** FIM ALTERAÇÃO Geolocation ******/

**Comment by paragghadge** [comment]
Any Update on above issue please?
I am too facing same issue. Any help is appreciated.
