### ISSUE TITLE
meteor js and plugin configuration

### ISSUE THREAD

**Issue by chansdad** [transistorsoft/cordova-background-geolocation-lt#110]
So  I have the premium version and able to use the plugin in a meteor js app , great. But here is the issue

I invoke the plugin in onDeviceReady during application start. but how do i get the user id to be posted or for that mater any custom parameters to post back.  What I did is within OndeviceReady i configure the plugin and start the plugin . so now i want to pass the userid for which i am tracking the gps coordinates back to the server , so i tried updating the config upon user login using setConfig and calling the window.backgroundgeolocation ( hoping this will call the original background geo location and update its config ) . When i log in , it is now posting the userid , closed the app and went for a drive , but i see userid is not in the posted request .. Obviously At the time of OnDeviceReady , we dont have a user id , it is the first tiem user is installing the app . WHat is the suggested approach for passing the logged in user id back with the posted gps info.

**Comment by christocracy** [comment]
You must be doing it wrong.  Show me your #setConfig code

On Friday, May 6, 2016, chansdad <notifications@github.com> wrote:

> So I have the premium version and able to use the plugin in a meteor js
> app , great. But here is the issue
>
> I invoke the plugin in onDeviceReady during application start. but how do
> i get the user id to be posted or for that mater any custom parameters to
> post back. What I did is within OndeviceReady i configure the plugin and
> start the plugin . so now i want to pass the userid for which i am tracking
> the gps coordinates back to the server , so i tried updating the config
> upon user login using setConfig and calling the
> window.backgroundgeolocation ( hoping this will call the original
> background geo location and update its config ) . When i log in , it is now
> posting the userid , closed the app and went for a drive , but i see userid
> is not in the posted request .. Obviously At the time of OnDeviceReady , we
> dont have a user id , it is the first tiem user is installing the app .
> WHat is the suggested approach for passing the logged in user id back with
> the posted gps info.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/110>
>


-- 
Snet form Gmail Mobile

**Comment by chansdad** [comment]
in my startup.js  within the OndeviceReady I have this 
//BackGroundGeoLocation  stuff....
            // Get a reference to the plugin.
            var bgGeo = window.BackgroundGeolocation;

            /**
             * This callback will be executed every time a geolocation is recorded in the background.
             */
            var callbackFn = function(location, taskId) {
                var coords = location.coords;
                var lat = coords.latitude;
                var lng = coords.longitude;

                // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
                // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
                setTimeout(function() {
                    bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
                }, 1000);
            };

            var failureFn = function(error) {
                console.log('BackgroundGeoLocation error..', error);
            }

            //if (Meteor.userId()) {
            //    console.log("This is the user Id : " + Meteor.userId());
            //    //atoken = Meteor.user().services.resume.loginTokens[Meteor.user().services.resume.loginTokens.length-1].hashedToken;
            //    atoken = Meteor.userId();
            //
            //}

            // BackgroundGeoLocation is highly configurable.
            bgGeo.configure(callbackFn, failureFn, {
                // Geolocation config
                desiredAccuracy: 0,
                stationaryRadius: 1,
                distanceFilter: 1,
                disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
                locationUpdateInterval: 5000,
                minimumActivityRecognitionConfidence: 80, // 0-100%.  Minimum activity-confidence for a state-change
                fastestLocationUpdateInterval: 5000,
                activityRecognitionInterval: 10000,
                stopDetectionDelay: 1, // [iOS] delay x minutes before entering stop-detection mode
                stopTimeout: 2, // Stop-detection timeout minutes (wait x minutes to turn off tracking)
                activityType: 'AutomotiveNavigation',
                disableMotionActivityUpdates: false,

                // Application config
                debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                forceReloadOnLocationChange: false, // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
                forceReloadOnMotionChange: false, // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
                forceReloadOnGeofence: false, // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
                stopOnTerminate: false, // <-- Don't stop tracking when user closes app.
                startOnBoot: true, // <-- [Android] Auto start background-service in headless mode when device is powered-up.

                // HTTP / SQLite config
             
                url: 'http://192.168.1.111/api/geolocation',
                method: 'POST',
                batchSync: true, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
                maxDaysToPersist: 1, // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
                headers: {
                    "X-FOO": "bar"
                },
                params: {
                    "auth_token": ''
                }
            });


            // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
            bgGeo.start();


and then when the user logs in , i have a success hook  in a file accountConfig.js in which i have the following 

`var mySubmitFunc = function(error, state) {     if (!error) {                if (state === "signIn") {             // Successfully logged in             // ...             var LoggedinUserId = Meteor.userId();           // Start background geo tracking for the logged in user             var bgGeo = window.BackgroundGeolocation;             var callbackFn = function() {                                 console.log("finished setting userid  for background geo location");             };              var failureFn = function(error) {                 console.log('BackgroundGeoLocation error', error);             }             bgGeo.setConfig(callbackFn, failureFn, {                  params: {                     "authuser" : LoggedinUserId                                      }             });                     }          } }; `

**Comment by christocracy** [comment]
before you `#configure` the plugin, are you checking to see if the user is *already* logged-in?  You would need to supply the already-logged-in user's `authuser` at *that* time.  

(BTW:  I wouldn't use a simple user-id to authenticate the user.  You should generate a unique token each time the user logs in and send that `authentication_token` to the client in your auth success callback.)

```
// My imaginary success response from your user logging in.
function yourAuthenticationSuccess(response) {
  var result = JSON.parse(response.responseText);
  var user = result.user;

  // Place the authenticated user's credentials in localStorage.
  window.localStorage.setItem('authuser', user.id);
}

function configureBackgroundGeolocation() {
  var bgGeo = window.BackgroundGeolocation;

  var config = {
    desiredAccuracy: 0,
    distanceFilter: 50,
    params: {}
  };

  if (window.localStorage.hasItem('authuser') {
    // Oh look!  Our user is already logged in!  Attach their auth credentials now
    config.params.authuser = window.localStorage.getItem('authuser');
  }
  
  bgGeo.configure(config, function(state) {
    console.log('BackgroundGeolocation configured, state: ', state.enabled);
  });
}
```

Or simply don't even configure the plugin *until* the user logs in.

**Comment by chansdad** [comment]
Chris 

Yes i just over simplified the problem , I am setting hashed tokens etc ...  The issue is at the time OnDeviceReady is fired , user has not logged in . This could have fired when the user is first installing the application. So there is no way i can set  the auth tokens or user id etc as the custom parameters at the time BgGeo is being configured and initialized in OnDeviceReady

So I have a hook which fires when a user logs in , at which time i am trying to set the has tokens so that from then onwards any background geo location coordinates posted will also send login tokens so i can map the incoming request to the correct user .

As you can see i have taken code from your documentation and plugged it in my onDeviceReady .
When the app is installed , it sends the coordinates just fine 

My accountsconfig.js file in which i have the onlog in hook , i am trying to set the hash tokens , what i am seeing is these tokens are coming in as long as the app is running , but when the app is closed i dont get them any more

**Comment by christocracy** [comment]
You’re talking about iOS, right?

On Mon, May 9, 2016 at 7:11 PM, chansdad <notifications@github.com> wrote:

> Chris
>
> Yes i just over simplified the problem , I am setting hashed tokens etc
> ... The issue is at the time OnDeviceReady is fired , user has not logged
> in . This could have fired when the user is first installing the
> application. So there is no way i can set the auth tokens or user id etc as
> the custom parameters at the time BgGeo is being configured and initialized
> in OnDeviceReady
>
> So I have a hook which fires when a user logs in , at which time i am
> trying to set the has tokens so that from then onwards any background geo
> location coordinates posted will also send login tokens so i can map the
> incoming request to the correct user .
>
> As you can see i have taken code from your documentation and plugged it in
> my onDeviceReady .
> When the app is installed , it sends the coordinates just fine
>
> My accountsconfig.js file in which i have the onlog in hook , i am trying
> to set the hash tokens , what i am seeing is these tokens are coming in as
> long as the app is running , but when the app is closed i dont get them any
> more
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/110#issuecomment-218016600>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chansdad** [comment]
RIght , I am testing on iOs for the moment . And will test it on android device as well

**Comment by christocracy** [comment]
Are you storing your auth token in localStorage?

**Comment by chansdad** [comment]
No I am not  and why should i be storing it in local storage ?  I woudl assume once I reset the config to include params , those would come in on any new posted coordinates , isnt it?

**Comment by christocracy** [comment]
Of course you store your auth token in localStorage!

And no, iOS does NOT persist its config between restarts.  It doesn't need
to.

Put your authToken in localStorage.

On Tuesday, May 10, 2016, chansdad <notifications@github.com> wrote:

> No I am not and why should i be storing it in local storage ? I woudl
> assume once I reset the config to include params , those would come in on
> any new posted coordinates , isnt it?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/110#issuecomment-218033807>
>


-- 
Snet form Gmail Mobile

**Comment by chansdad** [comment]
uuh , I am still not clear on how this setConfig works , if I am passing the new custom parms thorugh setConfig , why would i need to put them in local storage ? Considering the bggeo has been configured , initiated with app install , once the user logs in i am reconfiguring the bggeo (through setConfig) by adding my custom parms . and going forawrd these custom parms should be posted by bggeo to the url along with the coordinates isnt it? 
Assuming the above is correct , why would i need to set the parms in local storage ?

**Comment by christocracy** [comment]
You do not understand how iOS works when the user closes the app.  Your
JavaScript is KILLED.  When iOS reboots your app in bg, your entire
JavaScript app is rebooted.

Just don't even #configure the plugin UNTIL you have a logged-in user.

#setConfig only changes the current run time params.

You have to provide all your desired config params EACH time the app boots,
since you have to reconnect the JavaScript callbacks anyway.

Have you never used localStorage before??

On Tuesday, May 10, 2016, chansdad <notifications@github.com> wrote:

> uuh , I am still not clear on how this setConfig works , if I am passing
> the new custom parms thorugh setConfig , why would i need to put them in
> local storage ? Considering the bggeo has been configured , initiated with
> app install , once the user logs in i am reconfiguring the bggeo (through
> setConfig) by adding my custom parms . and going forawrd these custom parms
> should be posted by bggeo to the url along with the coordinates isnt it?
> Assuming the above is correct , why would i need to set the parms in local
> storage ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/110#issuecomment-218035852>
>


-- 
Snet form Gmail Mobile

**Comment by chansdad** [comment]
Ok got it .. let me try it out . Ya i did briefly work with local storage a while back . looked through your samples , i think will be able to get it . If i have any questions will ping you.

**Comment by christocracy** [comment]
"A while back"??  Dude, this is a mobile authentication 101 problem you're
having.  Go google "Cordova

Google "cordova authentication token"

1st link:  https://devdactic.com/user-auth-angularjs-ionic/

On Tuesday, May 10, 2016, chansdad <notifications@github.com> wrote:

> Ok got it .. let me try it out . Ya i did briefly work with local storage
> a while back . looked through your samples , i think will be able to get it
> . If i have any questions will ping you.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/110#issuecomment-218037560>
>


-- 
Snet form Gmail Mobile
