### ISSUE TITLE
BackgroundGeolocation is undefined

### ISSUE THREAD

**Issue by jhad-ay** [transistorsoft/cordova-background-geolocation-lt#1107]
After converting the simple map example to Ionic 4, the import function fails, with an error

import BackgroundGeolocation, {
Location,
HttpEvent,
HeartbeatEvent,
MotionActivityEvent,
ProviderChangeEvent,
MotionChangeEvent,
ConnectivityChangeEvent
} from "cordova-background-geolocation-lt";

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'onLocation' of undefined
TypeError: Cannot read property 'onLocation' of undefined
at Function.push../node_modules/cordova-background-geolocation-lt/src/ionic/index.js.BackgroundGeolocation.onLocation (index.js:181)

how can i import the plugin without getting this issue ?

**Comment by christocracy** [comment]
I can't help you if you **ignore the issue template**.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
