### ISSUE TITLE
plugin not working in android 10

### ISSUE THREAD

**Issue by ahsan154** [transistorsoft/cordova-background-geolocation-lt#1108]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: Windows
* Device manufacturer / model: Sorry galaxy s10 plus
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
document.addEventListener("deviceready", onDeviceReady, false);
            //onDeviceReady();
            function onDeviceReady() {
                // 1.  Listen to events
                var bgGeo = window.BackgroundGeolocation;

                bgGeo.onLocation(function (location) {
                    alert('[location] -'+ JSON.stringify(location));
                    localStorage.setItem('loc',location);
                });
//
                bgGeo.onMotionChange(function (event) {
                    alert('[motionchange] -'+ event.isMoving, event.location);
                });
//
                bgGeo.onHttp(function (response) {
                    alert('[http] - '+ response.success+ response.status+ response.responseText);
                });
//
                bgGeo.onProviderChange(function (event) {
                    alert('[providerchange] -'+event.status+ event.enabled+ event.gps+ event.network);
                });
                window.navigator.geolocation.getCurrentPosition(function (location) {
                    alert('Location from Phonegap');
                    latitude = location.coords.latitude;
                   longitude = location.coords.longitude;
               });
               // 2. Execute #ready method:
               alert('86'+JSON.stringify(bgGeo.transistorTrackerParams(window.device)));
               alert('87'+JSON.stringify(location));

                bgGeo.ready({
                    reset: true,
                    debug: true,
                    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
                    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                   distanceFilter: 10,
                    url: 'URL',
                    params: localStorage.getItem('loc'),
                    extras: {
                    id: '97'
                    },
                    autoSync: true,
                    method: "POST",
                    stopOnTerminate: false,
                    startOnBoot: true
                }, function (state) {    // <-- Current state provided to #configure callback
                    // 3.  Start tracking
                    alert('BackgroundGeolocation is configured and ready to use');
                    alert(state.enabled);
                    if (!state.enabled) {
                        bgGeo.start();
                   }
                });

                // NOTE:  Do NOT execute any API methods which will access location-services
                // until the callback to #ready executes!
                //
                // For example, DO NOT do this here:
                //
                // bgGeo.getCurrentPosition();   // <-- NO!
                // bgGeo.start();                // <-- NO!
            }
```

## Expected Behavior
I expect to this plugin to hit the URL mentioned in the ready event, although it is doing on android 9 phones but not on the client's mentioned device.

## Actual Behavior
It shows alert messages that i have added along with the permission but it does not track user upon moving or on the read while driving etc. It dosn't show any notifcation in the mobile tray about tracking user.

## Steps to Reproduce

1. I sent apk file to client to test but its not tracking him. If you have android 10 device i can send apk.
2.
3.
4.

## Context
I was demoing client about the plugin features so we can buy and implement it in our upcoming app

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
No logs yet, as it is an apk.
```

</details>

**Comment by ahsan154** [comment]
![1585995829579](https://user-images.githubusercontent.com/12672971/78530288-d196b400-77fc-11ea-8136-6195be4d0684.JPEG)
![1586149919224](https://user-images.githubusercontent.com/12672971/78530512-35b97800-77fd-11ea-94ed-6b833628fe9a.JPEG)
![1585894982221](https://user-images.githubusercontent.com/12672971/78530514-36520e80-77fd-11ea-8c0b-233abedcb5e1.JPEG)
![1585894753442](https://user-images.githubusercontent.com/12672971/78530515-36eaa500-77fd-11ea-9517-d76fd32aaf08.JPEG)
![1585894739414](https://user-images.githubusercontent.com/12672971/78530517-37833b80-77fd-11ea-9943-4f6fbe1d7ecc.JPEG)

**Comment by christocracy** [comment]
Are you building for *debug*?  *release* builds don't work without a license.

It's not a good idea to use `alert` for debugging since alert is a *blocking* operation.  Use `console.log` and observe device logs:
```
$ adb logcat *:S TSLocationManager:V chromium:V
```

**Comment by ahsan154** [comment]
yes you are correct, it was a release apk. My bad sorry.

Thanks for alert correction too!

Just sending a debug apk to client for testing.
