### ISSUE TITLE
UUID of device

### ISSUE THREAD

**Issue by chansdad** [transistorsoft/cordova-background-geolocation-lt#111]
Any way we can get the uuid of the device posted back along with the gps coordinates ? 
Alternatively , when the plugin first registers , if we can get the UUID , we can register the device for tracking on the server side.
This will allow us to map out the coordinates posted for a user if we have a uuid -> user id mapping on the back-end. Also on client side we can set the userid by getting the uuid of the

**Comment by christocracy** [comment]
I simply use Cordova-plugin-device in my sample app and add the result to
the plugin's configured http #params

On Monday, May 9, 2016, chansdad <notifications@github.com> wrote:

> Any way we can get the uuid of the device posted back along with the gps
> coordinates ?
> Alternatively , when the plugin first registers , if we can get the UUID ,
> we can register the device for tracking on the server side.
> This will allow us to map out the coordinates posted for a user if we have
> a uuid -> user id mapping on the back-end. Also on client side we can set
> the userid by getting the uuid of the
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/111>
>


-- 
Snet form Gmail Mobile

**Comment by chansdad** [comment]
Chris

If you noticed  my earlier reported issue . Once the plugin is initialized in OnDeviceReady , later on i am not able to pass params that can be posted back to the server along with the coordinates.

So my flow is like this in my Meteor App 
1. Initiate Plugin in OnDeviceReady with default parameters 
2. when user logs in to the app for the first time , capture the user id and update the plugin config using setConfig 

I am not stopping the bgGeo at any point 

Now 
1.When the app is first installed , I see the app asking for permissions and the coordinates are being posted with blank http #2 
2. I log in , and i see the the coordiants now post the http parms ( user id )

I close the app , 

Now the app is posting the coordinates with no user id . Considering i updated the config to now include the userid in httpparm i should see this user id every time the device /plugin posts the coordinates even when app is closed .

Now I compared this to one of hte other plugins i am using for push notification. interestingly , the pattern is much better if the device uuid is posted with every post of coordinates to the server. 

This will allow for user to device  mapping much better , and get a handle on one user having multiple devices and which one to track at any point .

All in all I am stuck with no way to get the user id information with bgGeo at the moment ... :( 

Regards

**Comment by christocracy** [comment]
I have no problems using #setConfig to update the #params.


On Mon, May 9, 2016 at 5:44 PM, chansdad <notifications@github.com> wrote:

> Chris
>
> If you noticed my earlier reported issue . Once the plugin is initialized
> in OnDeviceReady , later on i am not able to pass params that can be posted
> back to the server along with the coordinates.
>
> So my flow is like this in my Meteor App
> 1. Initiate Plugin in OnDeviceReady with default parameters
> 2. when user logs in to the app for the first time , capture the user id
> and update the plugin config using setConfig
>
> I am not stopping the bgGeo at any point
>
> Now
> 1.When the app is first installed , I see the app asking for permissions
> and the coordinates are being posted with blank http #2
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/2>
> 2. I log in , and i see the the coordiants now post the http parms ( user
> id )
>
> I close the app ,
>
> Now the app is posting the coordinates with no user id . Considering i
> updated the config to now include the userid in httpparm i should see this
> user id every time the device /plugin posts the coordinates even when app
> is closed .
>
> Now I compared this to one of hte other plugins i am using for push
> notification. interestingly , the pattern is much better if the device uuid
> is posted with every post of coordinates to the server.
>
> This will allow for user to device mapping much better , and get a handle
> on one user having multiple devices and which one to track at any point .
>
> All in all I am stuck with no way to get the user id information with
> bgGeo at the moment ... :(
>
> Regards
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/111#issuecomment-217919630>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Nor has anyone else reported this issue in over a year.  Presumably
hundreds of others are using #params to set some sort of
authentication_token for their server.

On Mon, May 9, 2016 at 7:19 PM, Chris Scott <christocracy@gmail.com> wrote:

> I have no problems using #setConfig to update the #params.
>
>
> On Mon, May 9, 2016 at 5:44 PM, chansdad <notifications@github.com> wrote:
>
>> Chris
>>
>> If you noticed my earlier reported issue . Once the plugin is initialized
>> in OnDeviceReady , later on i am not able to pass params that can be posted
>> back to the server along with the coordinates.
>>
>> So my flow is like this in my Meteor App
>> 1. Initiate Plugin in OnDeviceReady with default parameters
>> 2. when user logs in to the app for the first time , capture the user id
>> and update the plugin config using setConfig
>>
>> I am not stopping the bgGeo at any point
>>
>> Now
>> 1.When the app is first installed , I see the app asking for permissions
>> and the coordinates are being posted with blank http #2
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/2>
>> 2. I log in , and i see the the coordiants now post the http parms ( user
>> id )
>>
>> I close the app ,
>>
>> Now the app is posting the coordinates with no user id . Considering i
>> updated the config to now include the userid in httpparm i should see this
>> user id every time the device /plugin posts the coordinates even when app
>> is closed .
>>
>> Now I compared this to one of hte other plugins i am using for push
>> notification. interestingly , the pattern is much better if the device uuid
>> is posted with every post of coordinates to the server.
>>
>> This will allow for user to device mapping much better , and get a handle
>> on one user having multiple devices and which one to track at any point .
>>
>> All in all I am stuck with no way to get the user id information with
>> bgGeo at the moment ... :(
>>
>> Regards
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/111#issuecomment-217919630>
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
