### ISSUE TITLE
PGB iOS -> build failing after 3.6.2 publish on npm

### ISSUE THREAD

**Issue by rkjamvi** [transistorsoft/cordova-background-geolocation-lt#1110]
## Your Environment
* 3.6.3 and 3.4.2:
* Platform: iOS
* OS version: 
* Device manufacturer / model:
* Cordova version (`cordova -v`): cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)
* Cordova platform version (`cordova platform ls`): cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
iOS build successful on Phonegap Build Cloud services.

## Actual Behavior
iOS build failing with Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-background-fetch

## Steps to Reproduce

1. Build app on PGB cloud account
2.
3.
4.

## Context
iOS build was successful 3 days ago and now I tried to build with some changes, iOS is giving me error. I even tried with version 3.4.2

## Debug logs
<!-- include iOS / Android logs
While building module 'TSBackgroundFetch' imported from /project/The Health Challenge/Plugins/cordova-plugin-background-fetch/CDVBackgroundFetch.m:9:
In file included from <module-includes>:1:
The Health Challenge/Plugins/cordova-plugin-background-fetch/TSBackgroundFetch.framework/Headers/TSBackgroundFetch.h:11:9: fatal error: 'BackgroundTasks/BackgroundTasks.h' file not found
#import <BackgroundTasks/BackgroundTasks.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
/project/The Health Challenge/Plugins/cordova-plugin-background-fetch/CDVBackgroundFetch.m:9:9: fatal error: could not build module 'TSBackgroundFetch'
#import <TSBackgroundFetch/TSBackgroundFetch.h>
 ~~~~~~~^
2 errors generated.

** ARCHIVE FAILED **
-->
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by mikemania** [comment]
Something similar happened with android build suddenly. But I managed to resolve by rolling back to 3.4.2

> Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: cdvbackgroundfetch.java

**Comment by rkjamvi** [comment]
> Something similar happened with android build suddenly. But I managed to resolve by rolling back to 3.4.2
> 
> > Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: cdvbackgroundfetch.java

Android was fine yesterday only had issue with iOS build, but today Android is also failing even tried 3.4.2 and 3.4.1

**Comment by christocracy** [comment]
Somebody provide an *entire* build log from PhoneGap.  iOS is likely failing because the latest background-fetch requires XCode 11.  PhoneGap is probably still building with XCode 10.  PhoneGap is always behind.  PhoneGap is crap.

**Comment by rkjamvi** [comment]
Please find attached ios log. 
[ios_log.docx](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/4457494/ios_log.docx)

**Comment by christocracy** [comment]
Don't send logs in a `.docx`.  Put it into a regular old `.txt` file.

**Comment by christocracy** [comment]
What version of XCode are you building with on PhoneGap?

**Comment by rkjamvi** [comment]
Here you see plain txt file. I am using CLI 9.0 and iOS version is 5.0.1, not sure about xcode version. 

I made build without any issue 3 days ago with same configs. and now both iOS and android are failing. 
[ios.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/4457512/ios.txt)

**Comment by christocracy** [comment]
PhoneGap is **NOT** building with latest XCode 11 (latest is `11.4`).  PhoneGap is building with XCode 10.  Only XCode 11 can build for iOS 13.

```
#import <BackgroundTasks/BackgroundTasks.h>
```
Latest version of `background-fetch` has migrated away from the deprecated iOS [background-fetch API](https://developer.apple.com/documentation/uikit/uiapplication/1623100-setminimumbackgroundfetchinterva?language=objc)
![](https://dl.dropbox.com/s/rq8rxzfycf575ku/Screenshot%202020-04-09%2012.48.34.png?dl=1)

The new iOS 13 [`BackgroundTasks`](https://developer.apple.com/documentation/backgroundtasks?language=objc) API is available only in XCode 11.
![](https://dl.dropbox.com/s/gkid20wsq4avyoe/Screenshot%202020-04-09%2012.50.23.png?dl=1)

You need to ask PhoneGap:  *"How do I build my iOS app with XCode 11?"*.

**Comment by rkjamvi** [comment]
Ok, I will now try building with Cordova CLI then, what about android, its failing for even 3.4.2. see error below and log attached:

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: CDVBackgroundFetch.java

[android_log.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/4457565/android_log.txt)

**Comment by christocracy** [comment]
>then, what about android

This is due to release of `cordova-plugin-background-fetch@6.0.5` that I published today.  Fixed in `6.0.6`.

**Comment by rkjamvi** [comment]
> > then, what about android
> 
> This is due to release of `cordova-plugin-background-fetch@6.0.5` that I published today. Fixed in `6.0.6`.

android build is now working. for iOS can't we use old version of background geolocation plugin like 3.4.2 for iOS?

**Comment by christocracy** [comment]
>For iOS can't we use old version of background geolocation plugin like 3.4.2 for iOS?

Yes.  3.4.2  is pinned to `background-fetch@5.x`.  You will be missing out on a [number of fixes and features provided by 3.6.2](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#362---2020-04-08)

**Talk to PhoneGap**.  Ask them why they don't support building for iOS 13.  iOS 13 has been out since  **September 2019**.  A remote build-service should be supporting building for latest iOS APIs *on the day of its release*.  PhoneGap is horrible.

**Comment by rkjamvi** [comment]
I just tried using 3.4.2 but once its fetching from NPM, its installing 3.6.2, see few lines of log.

Fetching plugin "cordova-background-geolocation-lt@^3.4.2" via npm
Installing "cordova-background-geolocation-lt" at "3.6.2" for ios
Fetching plugin "cordova-plugin-background-fetch@~6.0.3" via npm
Installing "cordova-plugin-background-fetch" at "6.0.5" for ios

and my config.xml  is:
<plugin name="cordova-background-geolocation-lt" spec="^3.4.2">
		<variable name="GOOGLE_API_VERSION" value="16.0.0" />
		<variable name="APPCOMPAT_VERSION" value="27.1.1" />
    </plugin>

**Comment by rkjamvi** [comment]
![2020-04-09_21-28-30](https://user-images.githubusercontent.com/6947975/78933155-1fcfdf80-7aa9-11ea-860b-17d564fbc4d9.png)

**Comment by christocracy** [comment]
I have no idea.  I don't use PhoneGap.  Seek help at PhoneGap.

**Comment by davidshieldsaz** [comment]
Hello Chris, for those of us who have been using Phonegap for builds, do you recommend transitioning to https://www.bitrise.io/ ?  I've read that WKWEBVIEW which is used by iOS 13 has been really buggy, have you experienced similar issues?  My apologies for hijacking this thread, but it could help some people who are looking for cloud based alternatives.  Thank you.

**Comment by christocracy** [comment]
I recommend dumping all cloud-based build-services and build locally instead.

**Comment by davidshieldsaz** [comment]
Thanks Chris.  I found this tutorial https://stackoverflow.com/questions/59247751/phonegap-cordova-to-ipa-file-without-phonegap-build on building locally on mac, perhaps this could be a good resource for other users of your app using cloud-based build-services.
