### ISSUE TITLE
E/TSLocationManager Exception

### ISSUE THREAD

**Issue by Osmanakdemir** [transistorsoft/cordova-background-geolocation-lt#1111]
* Plugin version: 3.4.2
* Platform: Android
* OS version: API 29
* Device manufacturer / model: Emulator Pixel XL API 29
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 8.1.0
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
 bgGeo.configure({
                        // Geolocation config
						/*
						locationTemplate : {"lat":<%= latitude %>,"lng":<%= longitude %>,"event":"<%= event %>",isMoving:<%= is_moving %>},
						geofenceTemplate : { "lat":<%= latitude %>, "lng":<%= longitude %>, "geofence":"<%= geofence.identifier %>:<%= geofence.action %>" }
						*/
                        /*locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>,"event":"<%= event %>",isMoving:<%= is_moving %>}', // newly added
						geofenceTemplate: '{ "lat":<%= latitude %>, "lng":<%= longitude %>, "geofence":"<%= geofence.identifier %>:<%= geofence.action %>" }',*/
						fastestLocationUpdateInterval: 180000, //180000,
                        stopAfterElapsedMinutes: 2880,
                        minimumActivityRecognitionConfidence: 100,
                        stopDetectionDelay: 0,
                        schedule: null,
						geofenceModeHighAccuracy: true, // newly added
                        desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH, //0, // bgGeo.DESIRED_ACCURACY_HIGH, //1000, // newly added
                        disableElasticity: false,
                        distanceFilter: 5,
                        stationaryRadius: 1,
                        stopOnStationary: false,
                        // Activity Recognition config
                        activityRecognitionInterval: 30000, //120000, //activity recognition in 1 minute
                        locationUpdateInterval: 30000, //180000, //update every 180 second...
                        stopTimeout: 1440,
                        batchSync: true,
                        maxBatchSize: 50,
                        preventSuspend: true,
                        foregroundService: true,
						notification: {
							smallIcon: "mipmap/not_icon",
							largIcon: "mipmap/not_icon"
						},
                        // Application config
                        debug: false,  // <-- Debug sounds & notifications.
                        stopOnTerminate: false,
		                enableHeadless: true,
                        startOnBoot: true,
                        heartbeatInterval: 180,
                        //deferTime: 60000, //5 minutes
                        url: v_url,
                        method: 'PUT',
                        locationAuthorizationRequest: "Always",
                        geofenceInitialTriggerEntry: true,
                        forceReloadOnLocationChange: true,
                        forceReloadOnGeofence: true,
                        forceReloadOnBoot: true,
		                locationAuthorizationAlert: {
                        		titleWhenNotEnabled: apex.lang.getMessage("GEOLOCATION_TITLEWHENNOTENABLED"), //"Location services not enabled",
                        		titleWhenOff: apex.lang.getMessage("GEOLOCATION_TITLEWHENOFF"), //"Location services are off",
                        		instructions: apex.lang.getMessage("GEOLOCATION_INSTRUCTIONS"), //"To use this app, you must enable 'Always' in the location service settings.",
                        		cancelButton: apex.lang.getMessage("GEOLOCATION_CANCEL"), //"Cancel",
                        		settingsButton: apex.lang.getMessage("GEOLOCATION_SETTINGS")//"Settings"
                        },
                        }, function(state) {
                        // This callback is executed when the plugin is ready to use.
                        //// console.log("BackgroundGeolocation ready: ", state);
                            /*if (!state.enabled) {
								bgGeo.start();
								bgGeo.changePace(true);  // <-- Location-services ON
								//bgGeo.changePace(false);
								//f_autoAcceptAssignment();
							}*/
                        });
```

## Steps to Reproduce

1.
2.
3.
4.

## Context
To use the plugin...
## Debug logs
2020-04-09 12:23:01.769 13439-13625/com.simply.dincer E/TSLocationManager:   ‼️  Value null at schedule of type org.json.JSONObject$1 cannot be converted to JSONArray
    org.json.JSONException: Value null at schedule of type org.json.JSONObject$1 cannot be converted to JSONArray
        at org.json.JSON.typeMismatch(JSON.java:101)
        at org.json.JSONObject.getJSONArray(JSONObject.java:598)
        at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.a(Unknown Source:292)
        at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.a(Unknown Source:0)
        at com.transistorsoft.locationmanager.adapter.TSConfig.updateWithJSONObject(Unknown Source:2)
        at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.configure(CDVBackgroundGeolocation.java:391)
        at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.execute(CDVBackgroundGeolocation.java:174)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
<details>
	<summary>Logs</summary>
</details>

We use your plugin in our two applications. One of them has the version of cordova-background-geolocation-lt 3.3.1 and it is working fine but the new app that we created yesterday has the version of cordova-background-geolocation-lt 3.4.2 and we get this error when the app starts. What might be the reason ? Configs are exactly the same for the two projects.

**Comment by christocracy** [comment]
Don’t set `schedule: null’.

If you’re not using the scheduler, just don’t provide that all.

If you are using the scheduler and you’re trying to clear it, give it an empty `[]`

**Comment by Osmanakdemir** [comment]
It is OK now. Thanks !
