### ISSUE TITLE
App is crashing on Android 

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1115]
I GOT CRASH ERROR:

![2020-04-17_12-49-54](https://user-images.githubusercontent.com/41004207/79556615-0252d500-80aa-11ea-90d0-8bf6b48ca6a0.png)
![2020-04-17_12-50-01](https://user-images.githubusercontent.com/41004207/79556620-04b52f00-80aa-11ea-9b3f-901d83251f7f.png)

**Comment by christocracy** [comment]
The issue template is *not* optional, it’s **required** or I don’t look at your issue.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Taxi4you** [comment]
Sure I have created another detailed issue.

**Comment by christocracy** [comment]
You *could have* edited *this* issue.
