### ISSUE TITLE
Notification on Android resets the app

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1116]
## Your Environment
* Plugin version:
```
  <plugin name="cordova-background-geolocation-lt" spec="^3.4.2">
    <variable name="GOOGLE_API_VERSION" value="16.+"/>
    <variable name="APPCOMPAT_VERSION" value="28.+"/>
    <variable name="OKHTTP_VERSION" value="3.12.+"/>
    <variable name="EVENTBUS_VERSION" value="3.0.0"/>
    <variable name="BACKGROUND_MODE_LOCATION" value="&lt;string>location&lt;/string>"/>
  </plugin>
```

* Platform: Android

* OS version: 8 and 9 and 10

* Device manufacturer / model: Any - tested on more than 20 devices

* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)

* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 8.1.0
  ios 5.1.1
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.ready({
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 8,
    preventSuspend: true,
    stopOnTerminate: true,
    startOnBoot: false,
    notification: {
      title: "my Title",
      text: "my Text",
      priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN
    }
  })
```

## Expected Behavior
I want to hide this plugin's notification at all. I am using cordova background plugin which handles background notifications - therefore this plugin's notification only adds extra notification which I don't need and therefore I want to cancel this at all.

IF IT DOESN'T POSSIBLE YET, OR SOMETHING (to completely remove this notification):
This has to:
1. Be showed only when on background.
2. Open the app when clicking on it - on the same state that was.

## Actual Behavior
1. It shows all the time - even when the app is on foreground.
2. It crashes the app and resets it and show splashscreen loader again.

## Steps to Reproduce

1. Start geolocation

## Context

Simply want 1 notification showing only when the app's state is on background,
showing that the app is running and when clicking it, it should bring the app back to foreground - not reset it.

Also, I want to change the background notification's text dynamically - so when not connected to gps to write something like: App is running in background - location services are off.
OR: App is running in background - your location is available!
... etc

Notice that I am also using the background plugin I have mentioned above that also implements its notification that I cannot remove.

## Debug logs
<!-- include iOS / Android logs
Furthermore I noticed some crashes that probably causes by this plugin (not related to the issue of the notification's behaviour) I post here some info, hope it helps!

Android logs from APPCENTER service (by Microsoft)

![2020-04-17_16-16-46](https://user-images.githubusercontent.com/41004207/79573278-0ccf9780-80c7-11ea-8df2-519ab57986d5.png)

**Comment by christocracy** [comment]
You **cannot hide the plugin's foreground-service notification**.  This notification is required by the plugin's foreground-service.  If you have the ability to provide your current notification a `notificationId`, you can share the plugin's notification, whose `notificationId` is `9942585`.

>Open the app when clicking on it - on the same state that was.

See [CHANGELOG](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#362---2020-04-08) for `3.6.2`:

>[Fixed] Android: launch-Intent for foreground-service notification was causing notification-click to re-launch the Activity rather than show existing.

>Also, I want to change the background notification's text dynamically 

Use `setConfig`.  See `Config.notification`.

**Comment by Taxi4you** [comment]
1. What do you mean by: "If you have the ability to provide your current notification a notificationId, you can share the plugin's notification, whose notificationId is 9942585"

2. You say that I need to upgrade the version from 3.4.x to 3.6.x? Is 3.6.x is the newest? It won't cause any problems upgrading in major versions?

**Comment by Taxi4you** [comment]
?
