### ISSUE TITLE
Contains unsafe cryptographic encryption patterns. v[3.4.2]

### ISSUE THREAD

**Issue by eviv3k** [transistorsoft/cordova-background-geolocation-lt#1117]
Google play give me a alert upload a release version:
**Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.
Vulnerable classes:
org.a.a.b.a
Affects APK version xxxxx**

List Plugins:
cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-background-fetch 6.0.5 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-camera-preview 0.11.1 "cordova-plugin-camera-preview"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-flashlight 3.2.0 "Flashlight"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-save-image 0.3.0 "SaveImage"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"

We're not using the plugin's encryption feature and config encryt (Default false).

What is the solution to this?

Thanks

**Comment by christocracy** [comment]
Ignore it.  This is due to a new encryption option `Config.encrypt` that you are probably *not* using.

For you, it’s a false positive.

**Comment by coffee-abremer** [comment]
While I understand that it is a false positive (and I'm definitely not using this feature), my client has access to the Google Play Console and does not like to see warning signs next to his apps. Using or no, we need to get this of this real warning for it might later become an error.

**Comment by christocracy** [comment]
Google is detecting that the plugin is implementing crypto methods and referencing a key from AndroidManifest.xml (which is unsafe).  You are not using the Config.encrypt feature.  There is absolutely no way Google will reject an app for this.  It is 100% false positive and I don’t intend to address this for at least 2 months.

**Comment by coffee-abremer** [comment]
Sounds good, just think it shouldn't be closed yet. Thanks for your help

**Comment by eviv3k** [comment]
Okay, Thanks for the update.
