### ISSUE TITLE
iOS provides onLocation event only once. afterwards only ActivityChange events appear

### ISSUE THREAD

**Issue by comalpine** [transistorsoft/cordova-background-geolocation-lt#1118]
## Your Environment
* Plugin version: 3.6.3
* Platform: iOS
* OS version: MacOSX 10.14.4
* Device manufacturer / model: iOS 13.3.1
* Cordova version (`cordova -v`): 6.6.0
* Cordova platform version (`cordova platform ls`): 5.1.1
* Plugin config provided to `#ready`:

    BackgroundGeolocation.ready(
      {
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        stopTimeout: 1,
        stopOnTerminate: false,
        startOnBoot: true,
      },
      (state) => {
        this.logService.updateLogList('[config done]');
      }
    );

## Expected Behavior
While moving the phone with location permission "always" there should appear many onLocation events. 

## Actual Behavior
When I start BackgroundLocation then I get only 1-2 onLocation events. Afterwards only ActivityChange events appear.

## Steps to Reproduce

1. Start app
2. click on start background detection
3. walk arround
4. check for logs

## Debug logs

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════
2020-04-29 17:07:08.940560+0200 MyApp[6895:2035253] 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚══════════════════════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚══════════════════════════════════\342═════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════
2020-04-29 17:07:08.940844+0200 MyApp[6895:2035251] 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════
🎾-[SOMotionDetector startDetection] 
2020-04-29 17:07:08.941674+0200 MyApp[6895:2034811] 🎾-[SOMotionDetector startDetection] 
🔵-[TSLocationManager setPace:] 0
2020-04-29 17:07:08.942097+0200 MyApp[6895:2034811] 🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
2020-04-29 17:07:08.943905+0200 MyApp[6895:2034811] 🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
ℹ️+[LocationAuthorization run:onCancel:] status: 3
2020-04-29 17:07:08.951671+0200 MyApp[6895:2034751] [location] -  [object Object]
2020-04-29 17:07:08.951987+0200 MyApp[6895:2035252] ℹ️+[LocationAuthorization run:onCancel:] status: 3
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2020-04-29 17:07:08.953420+0200 MyApp[6895:2035251] 🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
✅-[SOMotionDetector startDetection]_block_invoke Enabled M7 MotionActivity updates
2020-04-29 17:07:08.958151+0200 MyApp[6895:2035252] ✅-[SOMotionDetector startDetection]_block_invoke Enabled M7 MotionActivity updates

📍<+48.64259284,+13.39307568> +/- 88.37m (speed -1.00 mps / course -1.00) @ 29.04.20, 17:06:29 Central European Summer Time
2020-04-29 17:07:08.959105+0200 MyApp[6895:2034811] 
📍<+48.64259284,+13.39307568> +/- 88.37m (speed -1.00 mps / course -1.00) @ 29.04.20, 17:06:29 Central European Summer Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 39.9s
╚═══════════════════════════════════════════════════════════
2020-04-29 17:07:08.959224+0200 MyApp[6895:2034811] 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 39.9s
╚═══════════════════════════════════════════════════════════
ℹ️-[TSLocationManager locationManager:didUpdateLocations:] Received stale motionchange location.  Retrying...
2020-04-29 17:07:08.959401+0200 MyApp[6895:2034811] ℹ️-[TSLocationManager locationManager:didUpdateLocations:] Received stale motionchange location.  Retrying...

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2020-04-29 17:07:08.959518+0200 MyApp[6895:2035253] 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════
2020-04-29 17:07:08.960122+0200 MyApp[6895:2034751] [ActivityChange] -  [object Object]

📍<+48.64259284,+13.39307568> +/- 88.37m (speed -1.00 mps / course -1.00) @ 29.04.20, 17:07:08 Central European Summer Time
2020-04-29 17:07:08.961722+0200 MyApp[6895:2035253] 
📍<+48.64259284,+13.39307568> +/- 88.37m (speed -1.00 mps / course -1.00) @ 29.04.20, 17:07:08 Central European Summer Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 0.0s
╚═══════════════════════════════════════════════════════════
2020-04-29 17:07:08.961894+0200 MyApp[6895:2035252] 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 0.0s
╚═══════════════════════════════════════════════════════════
✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+48.64259284,+13.39307568> +/- 88.37m (speed -1.00 mps / course -1.00) @ 29.04.20, 17:07:08 Central European Summer Time
2020-04-29 17:07:08.961980+0200 MyApp[6895:2035150] ✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+48.64259284,+13.39307568> +/- 88.37m (speed -1.00 mps / course -1.00) @ 29.04.20, 17:07:08 Central European Summer Time
🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 113
2020-04-29 17:07:08.962404+0200 MyApp[6895:2035150] 🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 113
🔴-[TSLocationManager stopUpdatingLocation] 
2020-04-29 17:07:08.962978+0200 MyApp[6895:2035252] 🔴-[TSLocationManager stopUpdatingLocation] 
🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 88.4
2020-04-29 17:07:08.968050+0200 MyApp[6895:2035252] 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 88.4
🎾-[TSLocationManager startMonitoringSignificantLocationChanges] 
2020-04-29 17:07:08.968302+0200 MyApp[6895:2035150] 🎾-[TSLocationManager startMonitoringSignificantLocationChanges] 
✅-[TSLocationManager persistLocation:]_block_invoke INSERT: E39E683C-2AB4-4BFA-A619-192B45B42CA6
2020-04-29 17:07:08.969544+0200 MyApp[6895:2035251] ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: E39E683C-2AB4-4BFA-A619-192B45B42CA6

**Comment by christocracy** [comment]
Have you read the Wiki "*Philosophy of Operation*"?  On iOS, you need to move *at least* 200 meters before tracking engages.  No, there's no way around this.

**Comment by comalpine** [comment]
But when I compile/build your sample app, it works immediately.

**Comment by christocracy** [comment]
Test in the iOS Simulator with *Freeway Driver*.

**Comment by comalpine** [comment]
I've read it now - again. Took my bicycle and drove 200m plus and - yeah - then onLocation events occur!
though:
1) i'm still wondering why it seems to work different in your sample-app.
2) there are notifactions poping up "continue stationary" - these are not available as events, correct?

**Comment by christocracy** [comment]
>there are notifactions poping up "continue stationary" - these are not available as events, correct?

Those are shown merely from app `resume` / `suspend` events.

**Comment by christocracy** [comment]
>i'm still wondering why it seems to work different in your sample-app.

It's probably a first-time thing when an app is first installed due to change in iOS location permission model in iOS 13.  See [my blog](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24)

**Comment by alphagamer7** [comment]
Hey @christocracy ,  I am curious if this will get accepted by app store for submission with iOS 13 changes, I see that you don't have a sample app on app store and would like to know if there are issues in submitting to app store, do you know any example app using this plugin which have been published to app store?

**Comment by christocracy** [comment]
>I am curious if this will get accepted by app store for submission with iOS 13

Why not?  The plugin implements the same documented public iOS apis as any native app.

The only question is whether *Apple believes* your app *deserves* this checkbox enabled in XCode.
![](https://dl.dropbox.com/s/f45ak2vjtuijukv/Screenshot%202020-04-29%2014.27.14.png?dl=1)

If you're making an *Alarm Clock* app, hoping to keep location-services on to keep your app running in the background to run a timer, **of course** Apple would reject having the `[x] Location updates` background mode enabled.

**Comment by alphagamer7** [comment]
@christocracy got it, thanks for the clarification :) .
