### ISSUE TITLE
Location Services Notification Issue.

### ISSUE THREAD

**Issue by paulatrockhill** [transistorsoft/cordova-background-geolocation-lt#1119]
## Your Environment
* Plugin version: 3.4.2 
* Platform :both
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1
* Cordova platform version (`cordova platform ls`):
cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

1. Tapping on "Location Services activated" notification opens new app instance instead of resuming.
2. I think it should be there all the time while smart track is running.  Perhaps icon/message should be different if tracking is on or off.

## Actual Behavior

 "Location Services activated" notification opens new app instance

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See [CHANGELOG](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md) for `3.6.2`

>[Fixed] Android: launch-Intent for foreground-service notification was causing notification-click to re-launch the Activity rather than show existing.
