### ISSUE TITLE
Notification that the service is running or stopped

### ISSUE THREAD

**Issue by paulatrockhill** [transistorsoft/cordova-background-geolocation-lt#1120]
## Your Environment
* Plugin version: 3.4.2
* Platform: Both iOS and Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
A notification message should be displayed notifying the user that the device's location is currently being captured (while the service is ON) and the device's location is NOT being captured (while the service is OFF).

Also clicking on the notification should take the user directly into the app - inside the app and not the login screen.

Please let me know how to enable this notification? Thanks.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Please let me know how to enable this notification? Thanks.

When the device is detected to be *moving*, the notification is present.  When the device is detected to be *stationary*, the foreground-service is terminated and the notification is turned off.

This behavior is explained [at my blog](https://medium.com/@transistorsoft/background-geolocation-v3-be8665b06c7?source=linkShare-cd6de7ea2f98-1588271188)
