### ISSUE TITLE
Is there a way to auto-sych the Locations, but control if or not the SDK deletes the synch'ed records from the SDK SQL?

### ISSUE THREAD

**Issue by wardeha** [transistorsoft/cordova-background-geolocation-lt#1124]
## Your Environment
* Plugin version: 3.6.3
* Platform: iOS or Android
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): Capacitor 
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
     desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      reset: true,
      debug: true,
      stopTimeout: 5,
      stopOnTerminate: false,
      startOnBoot: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      url: this.locationUrl,
      autoSync: true,
      locationTemplate: this.locationTemplate,
      httpRootProperty: '.',
      authorization: {
        strategy: 'JWT',
        accessToken: token,
        refreshToken: refreshTokenText,
        refreshUrl: 'https://XXXX',
        refreshPayload: {
          refresh_token: refreshTokenText,
        }
      }
```

## Expected Behavior
When in autoSynch = true, the SDK Will sync the record and then delete it from the SQL. but that means i have to keep the app alive to listen and display all locations. To cater for low bandwidth and low connectivity, I prefer if the SDK Keeps the record in the SQL and I will delete them after the user completed the recording.
## Actual Behavior
SDK delete the record after a success HTTP send

## Steps to Reproduce
N/A

## Context
I want to be able to control whether or not I want the SDK to auto delete the record after it is synch'd. This way I can load the rout in the app in case the data connection is off at the location when the user stopped to check the rout. but I also want to auto sync the locations during the rout.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
No logs and no errors
```

</details>

**Comment by christocracy** [comment]
The plugin’s SQLite database is a temporary queue for its http service only.

If want these locations persisted in your app, insert them into your own SQLite database.

**Comment by wardeha** [comment]
Thank you Chris for the reply. I was trying to avoid having to keep the app alive in the background. once the Ionic app goes to the background, it will go to sleep and the app listeners will pause. And if the user stops in the middle of the rout with no data connection, it will be impossible to show the full route that was recorded: parts will be on the server and parts in the SDK SQL.
