### ISSUE TITLE
Mode Refresh Issue

### ISSUE THREAD

**Issue by paulatrockhill** [transistorsoft/cordova-background-geolocation-lt#1125]
## Your Environment
* Plugin version: 3.4.2
* Platform: both iOS and Android
* OS version: Android 10 / iOS 13
* Device manufacturer / model: Samsung Note 10+ / Apple iPhone 11
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1
* Cordova platform version (`cordova platform ls`):
cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
We get the Mode (in_vehicle, on_foot, still, on_bicycle, etc) based on the device activity. During testing, we found that Mode takes a long time to change. For example, during Driving (in_vehicle), the mode shows "in_vehicle" - after the car is parked and when the device is stationary, it takes 15-20 minutes for the mode to change to "still" from "in_vehicle". This happens across all modes. Please le me know how to check and update the modes quickly. Thanks.   

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
There is no other way.  Is this one data point you’re reporting or from consistent, long-term testing?

**Comment by christocracy** [comment]
Also, you’ve neglected the following information:

> OS version:
> Device manufacturer / model:

The plugin performance is affected by the oem version of Android as well as the quality and presence of sensors on a particular device (accelerometer, gyroscope, magnetometer).

**Comment by paulatrockhill** [comment]
Sorry, updated the OS Version and Device details.

This is based on long term testing with multiple data points. Thanks.

**Comment by christocracy** [comment]
You have not provided the `Config` you're providing to `#ready`.  That would be *highly* relevant.

**Comment by paulatrockhill** [comment]
initialiation
this.platform.ready().then(this.onDeviceReady.bind(this));

    this.state = {};
    // BackgroundGeolocation initial config.
    this.isMoving = false;
    this.enabled = false;
    this.autoSync = true;
    this.distanceFilter = Number(window.localStorage.getItem("DataCapture"));
    this.stopTimeout = 1;
    this.stopOnTerminate = true;
    this.startOnBoot = true;
    this.debug = false;

    // UI members.
    this.motionActivity = '';
    this.menuActive = false;

-----------------------------------------
BackgroundGeolocation.ready({
      // Logging / Debug config
      debug: this.debug,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // Geolocation config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,  // <-- highest possible accuracy
      distanceFilter: this.distanceFilter,
      // ActivityRecognition config
      stopTimeout: this.stopTimeout,
      // Application config
      stopOnTerminate: this.stopOnTerminate,
      startOnBoot: this.startOnBoot,
      heartbeatInterval: 60,
      // HTTP / Persistence config
      //url: ENV.TRACKER_HOST + '/api/locations',
      url: 'https://myapiapi/PhoneTrackWebService/RoMaPhoneTrackWebService.asmx/GetLocationLatest',
      extras: {
        RecordType: "15"
      },
      params: this.getParams(),
      authorization: {
        strategy: 'JWT',
        accessToken: token.accessToken,
        refreshToken: token.refreshToken,
        refreshUrl: ENV.TRACKER_HOST + '/api/refresh_token',
        refreshPayload: {
          refresh_token: '{refreshToken}'
        },
        expires: token.expires
      },
      autoSync: this.autoSync,
      batchSync: true,
      maxBatchSize: 10,
      autoSyncThreshold: 0,
      preventSuspend: true,
      notification: {
        title: "RoMa Smart Track",
        text: "Tracking service is turned Off",
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MAX
      }
    }, (state) => {
      console.log('- BackgroundGeolocation ready: ', state);
      // Set current plugin state upon our view.
      this.zone.run(() => {
        this.enabled = state.enabled;
        this.isMoving = state.isMoving;
        this.autoSync = state.autoSync;
        this.distanceFilter = state.distanceFilter;
        this.stopTimeout = state.stopTimeout;
        this.stopOnTerminate = state.stopOnTerminate;
        this.startOnBoot = state.startOnBoot;
        this.debug = state.debug;
        this.OnOFFstatusCheck();
      });
    });
  }

**Comment by christocracy** [comment]
Please *syntax-highlight* your code.
![](https://dl.dropbox.com/s/p47axsz0ze057x8/Screenshot%202020-05-08%2011.42.58.png?dl=1)

**Comment by christocracy** [comment]
And paid members should seek support by posting in the private repo:
https://github.com/transistorsoft/cordova-background-geolocation

**Comment by paulatrockhill** [comment]
Actual Our problem Explained Below

we drive a vehicle my activity type changed to "in_vehicle".
.once stop a driving wait more than 15 mins only activity changed to "still". 
we already set stopTimeout value is "1", but we except once stop a drive , another 5 mins activity need to be change 'still'
let me know what are time interval in one activity to another activity.
any config related to this?

**Comment by christocracy** [comment]
I'm not looking at your code above until you *syntax highlight* it.

**Comment by paulatrockhill** [comment]
BackgroundGeolocation.ready({
debug: false,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, // <-- highest possible accuracy
distanceFilter: 10,
**stopTimeout: 1,**
stopOnTerminate: true,
startOnBoot: true,
heartbeatInterval: 60,
url: 'https://myapiapi/PhoneTrackWebService/RoMaPhoneTrackWebService.asmx/GetLocationLatest',
extras: {
RecordType: "15"
},
params: this.getParams(),
authorization: {
strategy: 'JWT',
accessToken: token.accessToken,
refreshToken: token.refreshToken,
refreshUrl: ENV.TRACKER_HOST + '/api/refresh_token',
refreshPayload: {
refresh_token: '{refreshToken}'
},
expires: token.expires
},
autoSync: this.autoSync,
batchSync: true,
maxBatchSize: 10,
autoSyncThreshold: 0,
preventSuspend: true,
notification: {
title: "RoMa Smart Track",
text: "Tracking service is turned Off",
priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MAX
}
}, (state) => {
console.log('- BackgroundGeolocation ready: ', state);
// Set current plugin state upon our view.
this.zone.run(() => {
this.enabled = state.enabled;
this.isMoving = state.isMoving;
this.autoSync = state.autoSync;
this.distanceFilter = state.distanceFilter;
this.stopTimeout = state.stopTimeout;
this.stopOnTerminate = state.stopOnTerminate;
this.startOnBoot = state.startOnBoot;
this.debug = state.debug;
this.OnOFFstatusCheck();
});
});
}

let me know this code you are expected?

**Comment by christocracy** [comment]
**EDIT** your *previous post*
![](https://dl.dropbox.com/s/qcnaotpehmddmxl/Screenshot%202020-05-08%2013.18.09.png?dl=1)

![](https://dl.dropbox.com/s/p47axsz0ze057x8/Screenshot%202020-05-08%2011.42.58.png?dl=1)

**Comment by paulatrockhill** [comment]
Updated. Thanks.

**Comment by christocracy** [comment]
Now doesn’t that look much prettier?  Don’t forget how to do this.
