### ISSUE TITLE
Invalid License Key

### ISSUE THREAD

**Issue by scc4** [transistorsoft/cordova-background-geolocation-lt#1126]
## Your Environment
* Plugin version:3.6.3
* Platform:  Android
* OS version:
* Device manufacturer / model: Samsung a20
* Cordova version 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version   android 7.1.4
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```
  this.bgGeo = (<any>window).BackgroundGeolocation;
 this.bgGeo.ready({
      reset: true,
      logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
      distanceFilter: 10,
      stopTimeout: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      autoSync: true,
      url: ENV.COUCHDB + '/locations',
      httpRootProperty: '.',
      locationTemplate: '{ "lat":<%= latitude %>, "lng":<%= longitude %>, "timestamp": "<%= timestamp %>"}',
      params: {
        model: this.device.model,
        cnpj: localStorage.getItem('cnpj'),
        id_coletador: parseInt(localStorage.getItem('id_coletador')),
        _id:localStorage.getItem('cnpj') + this.dateUtilsProvider.getTodayYyyymmmdddAsString() + parseInt(localStorage.getItem('id_coletador')) + new Date().getTime()
      },
    }, (state) => {
      //console.log('- Configure success: ', state);
      if (!state.enabled) {
        this.bgGeo.start(function() {
          console.log('- BackgroundGeolocation tracking started');
        });
      }
      this.zone.run(() => {
        this.isMoving = state.isMoving;
      });
    });

## Expected Behavior

Start sending locations without error

## Actual Behavior

LICENSE VALIDATION FAILURE
my purchased license is shown here

## Steps to Reproduce

1. start app, login
2.toast show message license validation failure
3.locations are not sent to the server
4.

## Context
I bought the license and always validate the error

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

07 17:16:49.316  9356  9846 E TSLocationManager: ╔═════════════════════════════════════════════
05-07 17:16:49.316  9356  9846 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: br.com.scc4.newest.coletas
05-07 17:16:49.316  9356  9846 E TSLocationManager: ╠═════════════════════════════════════════════
05-07 17:16:49.316  9356  9846 E TSLocationManager: ╟─ Invalid license key:

my purchased license is shown here

05-07 17:16:49.316  9356  9846 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
05-07 17:16:49.316  9356  9846 E TSLocationManager: ╚═════════════════════════════════════════════

</details>

**Comment by christocracy** [comment]
email `chris@transistorsoft.com` the following info:
- Order #
- `config.xml`

Also, customers should use the private repo https://github.com/transistorsoft/cordova-background-geolocation

**Comment by christocracy** [comment]
Also, to enable multi-line syntax-highlighting in markdown, it's **3 backticks**, not one.

**Comment by scc4** [comment]
I have no access on https://github.com/transistorsoft/cordova-background-geolocation

**Comment by christocracy** [comment]
Did you [read this comment](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1126#issuecomment-625486945)?
