### ISSUE TITLE
Entry name 'res/color/material_on_surface_disabled.xml' collided

### ISSUE THREAD

**Issue by TomasMoskala** [transistorsoft/cordova-background-geolocation-lt#1132]
## Your Environment
* Plugin version: latest
{
  "_from": "cordova-background-geolocation-lt",
  "_id": "cordova-background-geolocation-lt@3.6.3",
  "_inBundle": false,
  "_integrity": "sha512-HPjdZE4DasLJFTLGQc4UwZ7NAFZvUZSwAyYPPNvmE3T7aAASGR81HWobardXrRnvYDyJHfqBK0U0YJQdS+G0ug==",
  "_location": "/cordova-background-geolocation-lt",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "cordova-background-geolocation-lt",
    "name": "cordova-background-geolocation-lt",
    "escapedName": "cordova-background-geolocation-lt",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/cordova-background-geolocation-lt/-/cordova-background-geolocation-lt-3.6.3.tgz",
  "_shasum": "f733596242c764c784aad69ba536bcdef33bab55",
  "_spec": "cordova-background-geolocation-lt",
  "_where": "C:\\aa\\TESTS\\bgeo",
  "author": {
    "name": "Chris Scott, Transistor Software"
  },
  "bugs": {
    "url": "https://github.com/transistorsoft/cordova-background-geolocation-lt/issues"
  },
  "bundleDependencies": false,
  "cordova": {
    "id": "cordova-background-geolocation-lt",
    "platforms": [
      "ios",
      "android"
    ]
  },
  "deprecated": false,
  "description": "Cordova Background Geolocation.  The most sophisticated, cross-platform location-tracking and geofencing plugin with battery-conscious motion-detection intelligence.",
  "devDependencies": {
    "typedoc": "^0.12.0",
    "typedoc-plugin-gitlink": "^0.0.3",
    "typedoc-plugin-mediaplayer": "^0.1.1",
    "typedoc-theme-transistor": "git+https://github.com/transistorsoft/typedoc-theme-transistor.git"
  },
  "engines": {
    "cordovaDependencies": {
      "2.12.0": {
        "cordova": ">=7.1.0",
        "cordova-android": ">=7.0.0",
        "cordova-ios": ">=4.4.0"
      },
      "2.9.0": {
        "cordova": ">=7.1.0",
        "cordova-android": ">=6.3.0",
        "cordova-ios": ">=4.4.0"
      },
      "<2.9.0": {
        "cordova": ">=6.4.0",
        "cordova-android": ">=6.0.0",
        "cordova-ios": ">=4.3.0"
      }
    }
  },
  "homepage": "https://github.com/transistorsoft/cordova-background-geolocation-lt#README",
  "keywords": [
    "gps",
    "location",
    "tracking",
    "geolocation",
    "geofencing",
    "background",
    "ecosystem:cordova",
    "cordova-android",
    "cordova-ios",
    "cordova",
    "phonegap"
  ],
  "license": "Apache-2.0",
  "main": "./src/ionic/index.js",
  "name": "cordova-background-geolocation-lt",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/transistorsoft/cordova-background-geolocation-lt.git"
  },
  "scripts": {
    "build": "tsc -p src/ionic",
    "prepublish": "npm run build"
  },
  "types": "./src/ionic/index.d.ts",
  "version": "3.6.3"
}

* Platform: Android
* OS version: Android studio
* Device manufacturer / model: N/A
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): Current working directory is not a Cordova-based project.
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
import { Component } from '@angular/core';
import { NavController, Platform } from '@ionic/angular';
import BackgroundGeolocation, {
  Location,
  MotionChangeEvent,
  MotionActivityEvent,
  GeofenceEvent,
  Geofence,
  HttpEvent,
  ConnectivityChangeEvent
} from 'cordova-background-geolocation-lt';  // <-- or "cordova-background-geolocation" for licensed customers


@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  // public myLocation: Location;
  public myLocation: number;

  constructor(public navCtrl: NavController, public platform: Platform) {
    platform.ready().then(this.configureBackgroundGeolocation.bind(this));
  }
  configureBackgroundGeolocation() {
    // 1. Listen to events (see the docs a list of all available events)
    BackgroundGeolocation.onLocation(this.onLocation.bind(this));
    BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
    BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
    BackgroundGeolocation.onGeofence(this.onGeofence.bind(this));
    BackgroundGeolocation.onHttp(this.onHttp.bind(this));
    BackgroundGeolocation.onEnabledChange(this.onEnabledChange.bind(this));
    BackgroundGeolocation.onConnectivityChange(this.onConnectivityChange.bind(this));

    // 2. Configure the plugin
    BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      url: null,
      autoSync: false,
      params: {
        foo: 'bar'
      }
    }, (state) => {
      // Note:  the SDK persists its own state -- it will auto-start itself after being terminated
      // in the enabled-state when configured with stopOnTerminate: false.
      // - The #onEnabledChange event has fired.
      // - The #onConnectivityChange event has fired.
      // - The #onProviderChange has fired (so you can learn the current state of location-services).

      if (!state.enabled) {
        // 3. Start the plugin.  In practice, you won't actually be starting the plugin in the #ready callback
        // like this.  More likely, you'll respond to some app or UI which event triggers tracking.  "Starting an order"
        // or "beginning a workout", for example.
        BackgroundGeolocation.start();
      } else {
        // If configured with stopOnTerminate: false, the plugin has already begun tracking now.
        // - The #onMotionChange location has been requested.  It will be arriving some time in the near future.
      }
    });
  }

  onLocation(location: Location) {
    this.myLocation = location.coords.latitude;
    console.log('[location] -', location);
  }
  onMotionChange(event: MotionChangeEvent) {
    console.log('[motionchange] -', event.isMoving, event.location);
  }
  onActivityChange(event: MotionActivityEvent) {
    console.log('[activitychange] -', event.activity, event.confidence);
  }
  onGeofence(event: GeofenceEvent) {
    console.log('[geofence] -', event.action, event.identifier, event.location);
  }
  onHttp(event: HttpEvent) {
    console.log('[http] -', event.success, event.status, event.responseText);
  }
  onEnabledChange(enabled: boolean) {
    console.log('[enabledchange] - enabled? ', enabled);
  }
  onConnectivityChange(event: ConnectivityChangeEvent) {
    console.log('[connectivitychange] - connected?', event.connected);
  }
}


```

## Expected Behavior
Build apk

## Actual Behavior
Build error

## Steps to Reproduce

1.npm install cordova-background-geolocation-lt
2.npx cap sync
3. ionic capacitor run android
4.Generate signed APK

## Context

Copied code from here

## Debug logs

Entry name 'res/color/material_on_surface_disabled.xml' collided

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Plugin version: latest

Enter the **exact** version.  Edit your post.

**Comment by TomasMoskala** [comment]
> > Plugin version: latest
> 
> Enter the **exact** version. Edit your post.

Hi, is there anything else I should provide?
For me it really does not work, the plugin fires a new error every time I try to use it.
Is there any proven working example and configuration that I could copy?

**Comment by christocracy** [comment]
I’ve never heard of this error and the plugin has nothing to do with “res/color”.

Sounds like mis-matched gradle dependencies, likely resulting from some other poorly-configured plugin.

Post your gradle files:
- build.gradle
- app/build.gradle

**Comment by TomasMoskala** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath 'com.google.gms:google-services:4.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by TomasMoskala** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "io.ionic.starter"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
}

apply from: 'capacitor.build.gradle'

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}

**Comment by christocracy** [comment]
Post the result of `./gradlew dependences`
```
$ cd android
$ ./gradlew dependencies
```
This will print multiple dependency trees for each product flavour.  They're all the same.  Just post any one of these trees.

**Comment by TomasMoskala** [comment]
#!/usr/bin/env bash

##############################################################################
##
##  Gradle start up script for UN*X
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn ( ) {
    echo "$*"
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
esac

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
        CHECK2=`echo "$arg"|egrep -c "^-"`                                 ### Determine if an option

        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
            eval `echo args$i`=`cygpath --path --ignore --mixed "$arg"`
        else
            eval `echo args$i`="\"$arg\""
        fi
        i=$((i+1))
    done
    case $i in
        (0) set -- ;;
        (1) set -- "$args0" ;;
        (2) set -- "$args0" "$args1" ;;
        (3) set -- "$args0" "$args1" "$args2" ;;
        (4) set -- "$args0" "$args1" "$args2" "$args3" ;;
        (5) set -- "$args0" "$args1" "$args2" "$args3" "$args4" ;;
        (6) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" ;;
        (7) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" ;;
        (8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
        (9) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" "$args8" ;;
    esac
fi

# Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell quoting and substitution rules
function splitJvmOpts() {
    JVM_OPTS=("$@")
}
eval splitJvmOpts $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS
JVM_OPTS[${#JVM_OPTS[*]}]="-Dorg.gradle.appname=$APP_BASE_NAME"

exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

**Comment by christocracy** [comment]
You’re supposed to **execute ./gradlew**, not show me the contents *of* the script.

**Comment by TomasMoskala** [comment]
PS C:\aa\TESTS\bgeo> cd android
PS C:\aa\TESTS\bgeo\android>  ./gradlew      

ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by christocracy** [comment]
Do what the error message says.

**Comment by TomasMoskala** [comment]
Welcome to Gradle 5.6.4!

Here are the highlights of this release:
 - Incremental Groovy compilation       
 - Groovy compile avoidance
 - Test fixtures for Java projects      
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6.4/release-notes.html

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :app
[cordova-background-geolocation]  Capacitor detected
[cordova-background-geolocation]  libDir: C:\aa\TESTS\bgeo\android/../node_modules/cordova-background-geolocation-lt/src/android/libs
[cordova-plugin-background-fetch] Capacitor detected
[cordova-plugin-background-fetch] libDir: C:\aa\TESTS\bgeo\android\app/../../node_modules/cordova-plugin-background-fetch/src/android/libs
google-services.json not found, google-services plugin not applied. Push Notifications won't work

> Configure project :capacitor-android
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Configure project :capacitor-cordova-android-plugins
[cordova-background-geolocation]  Capacitor detected  
[cordova-background-geolocation]  libDir: C:\aa\TESTS\bgeo\android/../node_modules/cordova-background-geolocation-lt/src/android/libs
[cordova-plugin-background-fetch] Capacitor detected
[cordova-plugin-background-fetch] libDir: C:\aa\TESTS\bgeo\android\capacitor-cordova-android-plugins/../../node_modules/cordova-plugin-background-fetch/src/android/libs

> Task :help

Welcome to Gradle 5.6.4.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 11s
1 actionable task: 1 executed

**Comment by christocracy** [comment]
I await the result of `./gradlew dependencies`

**Comment by TomasMoskala** [comment]
PS C:\aa\TESTS\bgeo\android> ./gradlew dependencies

> Configure project :app
[cordova-background-geolocation]  Capacitor detected
[cordova-background-geolocation]  libDir: C:\aa\TESTS\bgeo\android/../node_modules/cordova-background-geolocation-lt/src/android/libs
[cordova-plugin-background-fetch] Capacitor detected
[cordova-plugin-background-fetch] libDir: C:\aa\TESTS\bgeo\android\app/../../node_modules/cordova-plugin-background-fetch/src/android/libs
google-services.json not found, google-services plugin not applied. Push Notifications won't work

> Configure project :capacitor-android
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Configure project :capacitor-cordova-android-plugins
[cordova-background-geolocation]  Capacitor detected  
[cordova-background-geolocation]  libDir: C:\aa\TESTS\bgeo\android/../node_modules/cordova-background-geolocation-lt/src/android/libs
[cordova-plugin-background-fetch] Capacitor detected
[cordova-plugin-background-fetch] libDir: C:\aa\TESTS\bgeo\android\capacitor-cordova-android-plugins/../../node_modules/cordova-plugin-background-fetch/src/android/libs

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed
PS C:\aa\TESTS\bgeo\android>
