### ISSUE TITLE
setConfig doesn't exist on `BackgroundGeolocation` in Java

### ISSUE THREAD

**Issue by cwoolum** [transistorsoft/cordova-background-geolocation-lt#1133]
## Your Environment
* Plugin version: 3.6.3
* Platform: Android
* OS version: N/A (code issue)
* Device manufacturer / model: N/A (code issue)
* Cordova version (`cordova -v`): N/A (code issue)
* Cordova platform version (`cordova platform ls`): N/A (code issue)

## Expected Behavior
I'm trying to utilize the Java headless task. In Java, I should be able to fetch an instance of `BackgroundGeolocation`. According to the documentation for plugin version `2.13.2+`, I should be able to call `setConfig`.

> execute BackgroundGeolocation API methods (eg: #getCurrentPosition, #setConfig, #addGeofence, #stop, etc -- you can execute ANY method of the Javascript API) 

## Actual Behavior
 I fetch an instance of `BackgroundGeolocation` but it doesn't appear to have the `setConfig` available. 

## Steps to Reproduce

1. Follow the instructions [here](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode)
2. Fetch an instance of `BackgroundGeolocation`.
3. Try to call the `setConfig` method.

## Context
I need to be able to change the notification text on the android side if the cordova portion has been killed.

``` java
public class BackgroundGeolocationHeadlessTask  {

    @Subscribe(threadMode=ThreadMode.MAIN)
    public void onHeadlessTask(HeadlessEvent event) {
        String name = event.getName();
        TSLog.logger.debug("\uD83D\uDC80  event: " + event.getName());
        TSLog.logger.debug("- event: " + event.getEvent());

        BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(event.getContext());

        // Call setConfig(etc.) here
    }
}
```

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It's `TSConfig` which manages config, not `BackgroundGeolocation`.

Eg.  updating `distanceFilter`.  See the [native API docs](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-Android.md)

```java
TSConfig config = TSConfig.getInstance(event.getContext());
config.updateWithBuilder()
  .setDistanceFilter(10f)
  .commit();
```

**Comment by cwoolum** [comment]
Aaah, thanks for the clarification!
