### ISSUE TITLE
Autopause

### ISSUE THREAD

**Issue by jmhernandezivitalia** [transistorsoft/cordova-background-geolocation-lt#1137]
Does the plugin have any settings for auto pause?
When you stop it will pause, and when you start it will start.

Thanx

**Comment by christocracy** [comment]
See http://dontkillmyapp.com

**Comment by christocracy** [comment]
And see api docs [DeviceSettings](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.devicesettings.html)
