### ISSUE TITLE
Do not start on Android

### ISSUE THREAD

**Issue by vladimir1998** [transistorsoft/cordova-background-geolocation-lt#1138]
## Your Environment
* Plugin version: 3.7.0 
* Platform: iAndroid
* OS version: 9
* Device manufacturer / model: Redmi 7A
* Cordova version (`cordova -v`): 6.9.2
* Cordova platform version (`cordova platform ls`):
  Installed platforms:
    android 8.1.0
  Available platforms:
    browser ^6.0.0
    electron ^1.0.0
    ios ^5.0.0
    osx ^5.0.0
    windows ^7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{ 
        debug: true,

        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1,
        stationaryRadius: 1,

        autoSync: true,
        autoSyncThreshold: 2,
        batchSync: true,

        stopOnTerminate: false,
        startOnBoot: true,

        url: `${this._providerService.getHost()}/gpsTest`,
        headers: {
          'Authorization': `Bearer ${this.auth.getToken()}`,
          'Content-Type': 'application/json'
        },
        locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>, "timestamp": "<%= timestamp %>", "speed": <%= speed %>, "accuracy": <%= accuracy %>, "altitude": <%= altitude %>, "is_moving": <%= is_moving %>, "altitude": <%= altitude %>}',
        extras: {
          "userId": this.userId
        }

}
```

## Expected Behavior
The application will work in debug mode.

## Actual Behavior
The application does not work in debug mode.

## Steps to Reproduce
Installed the application by the: ionic cordova run android

## Context
Everything works fine on ios but on android it gives an error that it is necessary to add a key for the plugin

**Comment by christocracy** [comment]
>but on android it gives an error that it is necessary to add a key 

This is normal and expected.  The plugin is fully functional in DEBUG builds without a license key, regardless of the license warning.
