### ISSUE TITLE
problem with IOS - background geolocation

### ISSUE THREAD

**Issue by NavisDesenvolvimento** [transistorsoft/cordova-background-geolocation-lt#114]
Dear Christopher,
 
On January 27th, 2016, we bought your API (as you can see in the order below) but we couldn’t use it fully in our application.
 
What happens is that we are having problems/difficulties in iOS platform. We need your help in order to tell us how can we configure the API to work in a very simple way:
 
1)      Our app need to get the geolocation every minute of the day, regardless of the application condition (in background or foreground).
2)      For us, there’s no need to work with activity recognition. It means that, regardless of the fact of phone actually be stopped, we must ask the geolocation every minute.
 
We need your indication about how can we setup the API to get the desired result in the iOS platform, since our app is running perfectly when we use your API with Android platform.

**Comment by christocracy** [comment]
If you paid for a license, why are you posting on the free repo?

**Comment by Jpsankaran** [comment]
In Which function  i have to use to get geolocation for every minute (onmotionchange or onloction or etc..).

Where i have to specify my time interval?

 For my scenario,this plugin only bring geolocation at first time of installation.After that it is not getting geolocation even app is moving state.
