### ISSUE TITLE
Problems with Xiaomi celphones

### ISSUE THREAD

**Issue by pelupotter** [transistorsoft/cordova-background-geolocation-lt#1140]
## Your Environment
* Plugin version: 3.7.0
* Platform: Android
* Device manufacturer / model: Xiaomi celphones
* Capacitor version: 2.1.1
* Plugin config provided to `#ready`:
```javascript
{
        reset: false,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        distanceFilter: 100,
        stopOnTerminate: false,
        startOnBoot: true,
        allowIdenticalLocations: false
}
```

## Expected Behavior

The locations be updated when the cell phone is in the background (onLocation method)

## Actual Behavior

We are testing the geolocation plugin and we have a problem with Xiaomi phones, when the application is in the background it does not update the geolocation (onLocation method), but when it is activated it sends all the positions at the same time. Do you have any idea what might be happening?

**Comment by christocracy** [comment]
>reset: false,

Why are you using this?  Don't.

See http://dontkillmyapp.com

**Comment by pelupotter** [comment]
Yes, it is not necessary. Thanks.
