### ISSUE TITLE
How to optimize stationary to movement detection to avoid locations loss?

### ISSUE THREAD

**Issue by oaugustus** [transistorsoft/cordova-background-geolocation-lt#1147]
## Your Environment
* Plugin version: 3.6.3
* Platform: Android
* OS version: 9
* Device manufacturer / model: Moto Z 2
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": [],
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": true,
  "configUrl": "",
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 30,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": true,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableStopDetection": false,
  "distanceFilter": 5,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "enableTimestampMeta": false,
  "encrypt": false,
  "extras": [],
  "fastestLocationUpdateInterval": -1,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": [],
  "headlessJobService": "com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 300000,
  "isMoving": false,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": 200,
  "maxDaysToPersist": 30,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "Milk's Tracker",
    "text": "Serviço de rastreamento ativo",
    "color": "",
    "channelName": "TSLocationManager",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "strings": [],
    "actions": []
  },
  "params": {
    "linha_id": 2679,
    "device_id": 2788,
    "coletor_id": 1933,
    "veiculo_id": 1334,
    "rota_id": 211,
    "token": "40001.2788.200615-2140",
    "conta_id": "40001"
  },
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 50,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_foot, running, walking",
  "url": "http://xxxx.xxx.xxx",
  "useSignificantChangesOnly": false,
  "enabled": false,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 13967.571289062,
  "isFirstBoot": false,
  "didLaunchInBackground": false
}
```

## Expected Behavior
When in still for more than 5 minutes location services are turn off. But when device move, location services turn on again fast. 

## Actual Behavior
When in still for more than 5 minutes location services are turn off. But when device move, location services turn on again very slow and tracking lost many locations. 

## Context
![image](https://user-images.githubusercontent.com/424960/84779607-fce70d80-afba-11ea-8445-37d54b310789.png)
In the image, at point (1) I was in still for more than 50 minutes. After, I move at blue line path (2), but location services turn on only in (3). With this I loss more than 1 kilometer of tracking.

## Debug logs

<details>
	<summary>Logs</summary>

[40001.2788.200615-2140.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/4786834/40001.2788.200615-2140.log.gz)

</details>

**Comment by christocracy** [comment]
There is no way to “optimize” this.  It’s largely dependent upon the device model.

Most of my 11 test devices, such as Pixel3a,  take only a few meters of movement to trigger.

**Comment by oaugustus** [comment]
If I disable distanceFilter and use periodic checks, will these periodic checks check locations even at steady state?

**Comment by christocracy** [comment]
How do you intend to do “periodic checks”?

**Comment by oaugustus** [comment]
Using distanceFilter and locationUpdateInterval.

````
BackgroundGeolocation.ready({
  distanceFilter: 0,            
  locationUpdateInterval: 5000 
});
````

**Comment by christocracy** [comment]
When the plugin enters the *stationary* state, location-services are completely turned off.  There is no `locationUpdateInterval` in the *stationary* state.

**Comment by oaugustus** [comment]
In the operation that my application tracks, I have frequent stops, between 5 to 20 stops, each of which can vary from 15 to 45 minutes. If I change the stopTimeout property setting to more than 15 minutes, what impact can this have?

**Comment by christocracy** [comment]
GPS is a radio-receiver that connects to satellites in space.  When location-services is on, the GPS radio is on and consuming energy.

The longer the `stopTimeout`, the longer the GPS radio is on and consuming energy.
