### ISSUE TITLE
Issue while building android

### ISSUE THREAD

**Issue by Swapniltdatalogy** [transistorsoft/cordova-background-geolocation-lt#1148]
C:\Users\test5\.gradle\caches\transforms-1\files-1.1\tslocationmanager-3.1.5.aar
\ff1ac60535cd61c19e46c080a1129021\jars\classes.jar: D8: Type `com.google.android
.gms.location.ActivityTransitionResult` was not found, it is required for defaul
t or static interface methods desugaring of `int com.transistorsoft.locationmana
ger.service.ActivityRecognitionService.onStartCommand(android.content.Intent, in
t, int)`

encountered above issue while building android app.

**Comment by christocracy** [comment]
The issue template is not *optional*, **'it's required.**.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
