### ISSUE TITLE
Get location via Wifi/Cellular

### ISSUE THREAD

**Issue by vicmonmena** [transistorsoft/cordova-background-geolocation-lt#115]
Hi!

I've been trying to get location without GPS, it is WiFi/Celular) but my plugin shouldn't be right defined.

**What I did is set desiredAccuracy to 10**

_Could you help me to set a right configuration?_

Thank you!

**Comment by christocracy** [comment]
10 will not use GPS

On Wednesday, May 18, 2016, Vicente <notifications@github.com> wrote:

> Hi!
>
> I've been trying to get location without GPS, it is WiFi/Celular) but my
> plugin shouldn't be right defined.
>
> *What I did is set desiredAccuracy to 10*
>
> *Could you help me to set a right configuration?*
>
> Thank you!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/115>
>


-- 
Snet form Gmail Mobile

**Comment by vicmonmena** [comment]
Yeah! This is what I'm trying to achieve: get location not using GPS or get it even when GPS is disabled in the smartphone.

Thanks!

**Comment by christocracy** [comment]
0: GPS + Wifi + Cell
10: wifi + cell
100: wifi + cell (lower power)
1000: cell

On Wednesday, May 18, 2016, Vicente <notifications@github.com> wrote:

> Yeah! This is what I'm trying to achieve: get location not using GPS or
> get it even when GPS is disabled in the smartphone.
>
> Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/115#issuecomment-220051376>
>


-- 
Snet form Gmail Mobile
