### ISSUE TITLE
Apple Mobile Hotspot + cordova-background-geolocation-lt

### ISSUE THREAD

**Issue by washowasho** [transistorsoft/cordova-background-geolocation-lt#1151]
I've been getting complaints from users that cordova-background-geolocation-lt doesn't work when the phone is also serving as a mobile hotspot. The users have to turn off hotspot in order to get a location. Everything works as expected when hotspot is off. Is this a known issue with this plugin or Apple specific? Thank you.

**Comment by christocracy** [comment]
Never heard of this.  Have you tried reproducing this yourself, while observing the logs in XCode.

**Comment by washowasho** [comment]
Thanks. Actually no... I figured I'd check to see if it's a known problem first. Thanks for replying... You can close for now and I'll open with details if I find why.
