### ISSUE TITLE
How can I send location to server when app is stationary in an interval time?

### ISSUE THREAD

**Issue by Suryalg** [transistorsoft/cordova-background-geolocation-lt#1152]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See Cordova-plugin-background-fetch, already included as a dependency and waiting for you to implement it.

**Comment by Suryalg** [comment]
I need to run an ajax when in the background for both android and ios. is
it possible?
It seems background operations stops after 8-10 mins.

**Comment by christocracy** [comment]
The plugin is tracks location only when the device is detected to be *moving*.  It's not responsible for periodically requesting location while the device is *stationary*.
