### ISSUE TITLE
Sending same location to the server

### ISSUE THREAD

**Issue by Suryalg** [transistorsoft/cordova-background-geolocation-lt#1155]
## Your Environment
* Plugin version: 3.7.0
* Platform: Android
* OS version: 
* Device manufacturer / model: Samsung note 9 and Galaxy s8+
* Cordova version (`cordova -v`):9.0.0
* Cordova platform version (`cordova platform ls`):android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
var bgGeo = window.BackgroundGeolocation;
		
	bgGeo.onLocation(function(location) {
	    console.log('[location] -', location);
	  });
	
	  bgGeo.onMotionChange(function(event) {
	    console.log('[motionchange] -', event.isMoving, event.location);
	  });
	
	  bgGeo.onHttp(function(response) {
	    console.log('[http] - ', response.success, response.status, response.responseText);
	  });
	
	  bgGeo.onProviderChange(function(event) {
	    console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
	  });
	
	  // 2. Execute #ready method:
	  bgGeo.ready({
	    reset: true,
	    debug: false,
	    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
	    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
	    distanceFilter: 1,
	    url: domainUrl+'/locations',
	    autoSync: true,
	    stopOnTerminate: false,
	    allowIdenticalLocations: false,
	    startOnBoot: true,
	    params: {
	        appVersion: $('#appVersion').val(),
	        fireBaseNotification: $('#fireBaseNotification').val(),
	        deviceId: $('#deviceId').val(),
	        devicePlatform: $('#devicePlatform').val(),
	        deviceModel: $('#deviceModel').val(),
	        deviceVersion: $('#deviceVersion').val(),
	        deviceManufacturer: $('#deviceManufacturer').val(),
	        deviceIsVirtual: $('#deviceIsVirtual').val(),
	        deviceSerial: $('#deviceSerial').val(),
			userId: $('#userId').val(),
			userRole: $('#userRole').val(),
			userIsAgent: $('#userIsAgent').val(),
			userOnline: $('#userOnline').val(),
	      }
	  }, function(state) {    // <-- Current state provided to #configure callback
	    // 3.  Start tracking
	    console.log('BackgroundGeolocation is configured and ready to use');
	    if (!state.enabled) {
	      bgGeo.start().then(function() {
	        console.log('- BackgroundGeolocation tracking started');
	      });
	    }
	  });
```

## Expected Behavior
send current location to server

## Actual Behavior
The plugin is working perfectly in most of the devices and but in some devices the same location is getting updated 100s of times

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you observing the plugin logs?  The plugin can be very verbose with logging and logs absolutely everything it does, including http requests.

See Wiki *Debugging*.

**Comment by Suryalg** [comment]
I do not have the device in my place.. This is a issue with some samsung galaxy and note devices

**Comment by Suryalg** [comment]
I have checked it is not in Battery saver mode

**Comment by christocracy** [comment]
The symptom you describe sounds like your server returning an http error response.  This will cause the plugin to keep posting the same location, over and over until your server returns HTTP 200 or maxDaysToPersist causes that record to be deleted.

This symptom will be obvious in plugin logs.

I suggest you attempt to reproduce this on your devices.

**Comment by Suryalg** [comment]
can you help me how to check the plugin logs.
I use chrome console where there is noting but http 200 success

**Comment by christocracy** [comment]
See wiki Debugging to learn how to observe native logs and fetch them from the plugin’s log database using emailLog method.

**Comment by christocracy** [comment]
> The plugin is working perfectly in most of the devices and but in some devices

And the device you’re testing is *not* one of these devices which is “working perfectly”?

**Comment by Suryalg** [comment]
ok I debug the logs and I will check if there is any error in my http
request

**Comment by Suryalg** [comment]
> The symptom you describe sounds like your server returning an http error response. This will cause the plugin to keep posting the same location, over and over until your server returns HTTP 200 or maxDaysToPersist causes that record to be deleted.
> 
> This symptom will be obvious in plugin logs.
> 
> I suggest you attempt to reproduce this on your devices.

Hello I have checked from my side it is not the issue as location sends well to server when on foreground but on closed not working

**Comment by Suryalg** [comment]
> > The plugin is working perfectly in most of the devices and but in some devices
> 
> And the device you’re testing is _not_ one of these devices which is “working perfectly”?

No
