### ISSUE TITLE
Getting issue while doing ios build.

### ISSUE THREAD

**Issue by jitrani** [transistorsoft/cordova-background-geolocation-lt#1157]
Hi guys I am using razorpay in my app if i do android build it is working.If i will do ios build i am getting issue.
 'Razorpay/Razorpay-Swift.h' file not found. in main.h file.
I imported #import <Razorpay/Razorpay-Swift.h> also in my main.m file also.
Can any one help me out.

**Comment by christocracy** [comment]
The *issue template* is not optional, it's **required**.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
