### ISSUE TITLE
Difference in Kilometer Tracking and no disableElasticity option in Sample App

### ISSUE THREAD

**Issue by sktech** [transistorsoft/cordova-background-geolocation-lt#116]
I am building a kilometer tracking app in Android for car and bike riders.

I tried the Sample App. I am facingthe following issues

1 -Kilometer Reading starts after 300-400 m.
2 - There always a difference of 100-1000 m in actual reading.The kilometer reading is different for car and bike. In car it shows 100-300 m difference whereas in bike it shows 700-1000 m difference
3 - When we stop and start moving again there is a difference of more than 1 km.

i only changed distanceFilter to 50 in the Sample App.

Please help me to solve this issue as i need accurate reading

**Comment by christocracy** [comment]
iOS and Android are completely different, as an Elephant and a Zebra.  You
have to specify which platform.

iOS will always take several hundred meters to begin tracking.  This is the
nature of iOS.  You have to accept this limitation, there is no solution.

The odometer reading is not very accurate.  It is simply the summation of
the distance between the last position and current position and relies upon
accurate geolocations from the device.  You shouldn't rely on it as being
completely accurate.

I assume you're talking of iOS for #3.  This is the nature of iOS.  There
is no solution.  iOS is completely dependent upon the nature of the local
network in this situation.

On Friday, May 20, 2016, Sunil Kumbhar <notifications@Github.com> wrote:

> I am building a kilometer tracking app in Android for car and bike riders.
>
> I tried the Sample App. I am facingthe following issues
>
> 1 -Kilometer Reading starts after 300-400 m.
> 2 - There always a difference of 100-1000 m in actual reading.The
> kilometer reading is different for car and bike. In car it shows 100-300 m
> difference whereas in bike it shows 700-1000 m difference
> 3 - When we stop and start moving again there is a difference of more than
> 1 km.
>
> i only changed distanceFilter to 50 in the Sample App.
>
> Please help me to solve this issue as i need accurate reading
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/116>
>


-- 
Snet form Gmail Mobile

**Comment by sktech** [comment]
I am testing it for Android Platform only as mentioned in the issue. Please let me know for Anroid only. Also i am not seeing disableElasticity  option inthe settings.

**Comment by christocracy** [comment]
The sample app settings screen shows only the most common subset of
available settings.  You can add any overrides you wish in the source code
here:
https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/app/home/home.js#L197

config.disableElasticity = true;

On Friday, May 20, 2016, Sunil Kumbhar <notifications@github.com> wrote:

> I am testing it for Android Platform only as mentioned in the issue.
> Please let me know for Anroid only. Also i am not seeing disableElasticity
> option inthe settings.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/116#issuecomment-220563407>
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
For Android, the plugin uses an accelerometer/gyroscope based API to toggle
state between stationary/moving mode.

The polling of this API is controlled by #activityRecognitionInterval
(milliseconds, default 10000).  You can increase this rate to 1000 and it
will poll faster.

On Friday, May 20, 2016, Chris Scott <christocracy@gmail.com> wrote:

> The sample app settings screen shows only the most common subset of
> available settings.  You can add any overrides you wish in the source code
> here:
>
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/app/home/home.js#L197
>
> config.disableElasticity = true;
>
> On Friday, May 20, 2016, Sunil Kumbhar <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I am testing it for Android Platform only as mentioned in the issue.
>> Please let me know for Anroid only. Also i am not seeing disableElasticity
>> option inthe settings.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/116#issuecomment-220563407>
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile

**Comment by sktech** [comment]
In the setting page the disableElasticity option is available sometime and most of time it is not there on same device. Does it changes on same device and OS.

**Comment by christocracy** [comment]
It should be there for every device.  Show me a screenshot of the
Geolocation options of settings screen

https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/services/Settings.js#L18

On Friday, May 20, 2016, Sunil Kumbhar <notifications@github.com> wrote:

> In the setting page the disableElasticity option is available sometime and
> most of time it is not there on same device. Does it changes on same device
> and OS.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/116#issuecomment-220567474>
>


-- 
Snet form Gmail Mobile

**Comment by sktech** [comment]
Please have a look at the following settings screen shot
![screenshot_2016-05-20-10-00-23](https://cloud.githubusercontent.com/assets/8659244/15424772/14592394-1ea2-11e6-86d5-5d154fe62cd5.png)
![screenshot_2016-05-20-10-00-13](https://cloud.githubusercontent.com/assets/8659244/15424773/145ca5d2-1ea2-11e6-96d1-746c6e044627.png)

**Comment by sktech** [comment]
Same thing for activityType.
Yesterday this 2 settings were visible but after some time they were not ther

**Comment by christocracy** [comment]
What device/OS are you using?

Anyway, This has nothing to do with the plugin itself.

Simply provide overrides on the config object in home.js as noted above.

On Friday, May 20, 2016, Sunil Kumbhar <notifications@github.com> wrote:

> Same thing for activityType.
> Yesterday this 2 settings were visible but after some time they were not
> ther
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/116#issuecomment-220569683>
>


-- 
Snet form Gmail Mobile
