### ISSUE TITLE
Is it Possible to save additional data along with location information

### ISSUE THREAD

**Issue by djoyrocks** [transistorsoft/cordova-background-geolocation-lt#1160]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Context

Is it possible to save additional data along with location data? 
We are trying to develop a trip app. we need to save trip information along with location data (example trip id, user info etc)
when plugin post the data to the server is trip data will be posted to the server ?  or we need to keep our own DB structure and write our own sync logic by capturing location changed event?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs `Config.extras`
