### ISSUE TITLE
Bakcground Geolocation with Custom method

### ISSUE THREAD

**Issue by AbhilashPoshanagari** [transistorsoft/cordova-background-geolocation-lt#1161]
## Your Environment
* Plugin version:  "cordova-background-geolocation-lt": {
      "GOOGLE_API_VERSION": "16.+",
      "APPCOMPAT_VERSION": "28.+",
      "OKHTTP_VERSION": "3.12.+",
      "EVENTBUS_VERSION": "3.0.0",
      "PACKAGE_NAME": "bluetooth.watch.tgg"
    }
* Platform: iOS or Android
* OS version:  android-targetSdkVersion - 28
* Device manufacturer / model: 
* Cordova version (`cordova -v`):  9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`: 
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

1. We have added a New function name : ble.connect().  connecting  Bluetooth device and reading the data from Bluetooth device successfully on App foreground and data transferring into our database server for every 10 minutes 
2. Now, We have to call same function in background mode(On app terminate) for every 10 minutes(any Interval time) and transfer Bluetooth device data to our database server through API ( Android Headless Mode.)) 
3. Should be support Android and iOS platforms

4. Background geolocation and BLE Data Read  sample code https://github.com/AbhilashPoshanagari/ble-tgg.git

5. Plugin used for BLE connection and data reading https://github.com/don/cordova-plugin-ble-central

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>
https://github.com/AbhilashPoshanagari/ble-tgg.git
```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Sorry, I have little experience with Bluetooth.

The Android *terminated* state requires [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode).  You would have to implement the native Android bluetooth APIs with Java code, unfortunately.  React Native and Flutter are much nicer for Android headless-mode, allowing your write your headless code with *Javascript* and *dart*, respectively.

**Comment by AbhilashPoshanagari** [comment]
Thank you very much for your reply. 

Our team is new To React Native and Flutter. 

We will pay for  our requirement(Location and BLE data push to API).

Is it possible to implement in Ionic with Angular  cordova plugins and Android headless Mode(Android and iOS platforms)?
