### ISSUE TITLE
Where to find the Json Data sent to the Server ?

### ISSUE THREAD

**Issue by djoyrocks** [transistorsoft/cordova-background-geolocation-lt#1162]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Context
We are using custom template for location and need to know the JSON sent by the plugin to the server 
Where we need to look for it ?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin posts the JSON data in the "body of the HTTP request".

- With a NodeJS server, that's available at `request.body`.
- With PHP server, `$data = file_get_contents('php://input');`
- Search the API docs of your server framework to learn where to find the "body of the HTTP request"
