### ISSUE TITLE
Invalid license key

### ISSUE THREAD

**Issue by G93692** [transistorsoft/cordova-background-geolocation-lt#1165]
We has purchased the license key and the key has been added in meta-data.
In the initial phase we used cordova-background-geolocation-lt plugin version 3.6.1. It was worked without any license key error. 
Recently we have updated the plugin version to 3.8.1. In the latest Android version of app, we are getting Invalid license key.

**Comment by christocracy** [comment]
When in doubt, remove / re-add your android platform.  Cordova can get confused.

**Comment by G93692** [comment]
Thanks. We will try and let you know.

**Comment by G93692** [comment]
Issue is resolved. Thanks!
