### ISSUE TITLE
distanceFilter not working

### ISSUE THREAD

**Issue by G93692** [transistorsoft/cordova-background-geolocation-lt#1166]
In BackgroundGeolocation we have set distanceFilter as 8047 meters (Approximately 5 miles) to receive the location change event for every 5 miles distance interval.
But We have received inconsistent location change event. i.e. 30 meters, 220 meters,  970 meters etc.

Used plugin details:
Plugin name: cordova-background-geolocation-lt
Version: : 3.8.1

<img width="850" alt="Screenshot1" src="https://user-images.githubusercontent.com/58215342/89253497-72c23980-d63a-11ea-878f-78a373337108.png">

**Comment by G93692** [comment]
I would request you to help us to resolve this defect.

**Comment by christocracy** [comment]
You should not expect `distanceFilter` to return locations exactly as configured.  There are a variety of cases where the plugin will return a location, eg: motion-activity change from `in_vehicle` -> `still`.

If you want a location only periodically, you're wasting energy by only configuring a high `distanceFilter`.  The GPS radio is on and fetching locations all the time, consuming almost as much energy with `distanceFilter: 0` as `distanceFilter: `9999999999`.

You should be using `useSignificantChangesOnly: true`.  You will receive a location about every 1000 meters and consume far less energy.

Btw, issues posted here in the public repo and not granted priority attention or any guarantee of response.  Customers should post in the private repo.

**Comment by G93692** [comment]
We have upgraded the Transistorsoft plugin version to 3.9.0. Still the distanceFilter issue yet to resolved.

**Comment by christocracy** [comment]
If you want only periodic location updates, configure `useSignificantChangesOnly: true`.  iOS location-services are not designed to used with high `distanceFilter` of thousands of meters.  It's pointless to do so since it wastes nearly as much energy as `distanceFilter: 0`.

**Comment by G93692** [comment]
Please find the configuration we have used: 
BackgroundGeolocation.ready({
            locationAuthorizationRequest: "Always",
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
            distanceFilter: KEYS.distanceFilter,  //Approximately 800 meters
            disableElasticity: true,
            useSignificantChangesOnly: false, //set either useSignificantChangesOnly or distanceFilter; not both
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true,

**Comment by christocracy** [comment]
> Our requirement is that location change event would be received for every 8047 meters 

The plugin is not going to do this.  You can expect a location at least every 500-1000 meters, regardless of anything.
