### ISSUE TITLE
allowIdenticalLocations not working

### ISSUE THREAD

**Issue by G93692** [transistorsoft/cordova-background-geolocation-lt#1167]
For Android we have received duplicate location change event for twice or thrice. Issue is not resolved by allowIdenticalLocations as true as well.

Used plugin details:
Plugin name: cordova-background-geolocation-lt
Version: : 3.8.1

<img width="850" alt="Screenshot1" src="https://user-images.githubusercontent.com/58215342/89253745-19a6d580-d63b-11ea-8f4f-91c59eb150e2.png">

**Comment by G93692** [comment]
I would request you to help us to resolve this defect.

**Comment by christocracy** [comment]
You've not provided any plugin logs of this occuring.
