### ISSUE TITLE
Tracking stops after "a few minutes stopped"

### ISSUE THREAD

**Issue by victornoletosysout** [transistorsoft/cordova-background-geolocation-lt#1168]
## Your Environment
* Plugin version: "^3.8.2"
* Platform: Android
* OS version: Ubuntu 18.04 / Android 9
* Device manufacturer/model: ASUS_X00TDB
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
	reset: true,
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	distanceFilter: 1,
	foregroundService: true,
	debug: true,
	logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
	startOnBoot: false,
	stopOnTerminate: true,
	stopOnStationary: false,
}
```

## Expected Behavior
I am developing a system that will track a driver's tracking during a trip. The tracking should start as soon as the user starts (enter the tracking screen) and **stop only when it ends** (exit the screen), regardless of whether the driver stops for 10 minutes or 10 hours.

## Actual Behavior
I realized that after a few minutes, stopped somewhere, the plugin tracking dies. I stayed a few minutes inside my house (_point A at attached image_) and then left for a car drive around the city to test the plugin, but after a few kilometers I realized that the plugin was not updating in my position.

So, when I was at _point B_ (attached image) I clicked on the play button (which runs the BackgroundGeolocation.start function - this button is only for testing and will not exist in the production version) and then the service went up and started tracking again my positions normally.

An important observation is that in this test I stopped at a cafeteria, stayed a few minutes stopped again, but in this time (different from the first time) when I went back to drive the tracking was still active.

I read the plugin's configuration documentation and the only key that seemed to relate to this problem was the "**stopOnStationary**" which had already been set to false for this test.

## Steps to Reproduce

1. Set the plugin with the settings mentioned;
2. Open a tracking page and then execute BackgroundGeolocation.start;
3. Stay a few minutes stopped and then start walking/driving;

## Context
I have already explained in the _Actual Behavior section_ the problem I am dealing with and the test I did. I imagine that this problem is solved with some configuration that I left blank, but that even rereading the documentation I can't find the answer.

Thanks in advance.

![Screenshot_20200804-103232](https://user-images.githubusercontent.com/33295523/89303232-49a5a700-d642-11ea-8e55-9b98c369ae43.png)

**Comment by christocracy** [comment]
You are likely experiencing an issue specific to your device manufacturer.  See http://dontkillmyapp.com.

Perform the recommended changes to device settings and try again.

**Comment by victornoletosysout** [comment]
So do you think the configuration I set for the plugin is OK for my purpose?

**Comment by christocracy** [comment]
Yes

**Comment by victornoletosysout** [comment]
Do you think there is a problem if I happen to solve this (since I won't have access to all my users' devices) by executing the "BackgroundGeolocation.start" function in a setInterval?

**Comment by christocracy** [comment]
>by executing the "BackgroundGeolocation.start" function in a setInterval?

Won't work.

**Comment by victornoletosysout** [comment]
I asked this question because that's what I did to "wake up" the plugin, as mentioned in the body of the issue. I entered the link you sent me, my device is an Asus and does not have "Mobile Manager" informed there (but I know this is not your problem) - I only find myself somewhat limited (not to say unable) in how to solve this problem.

**Comment by Suryalg** [comment]
I am facing the same issue. when app is on foreground location service working
When on closed not working properly on Android 9+

**Comment by Suryalg** [comment]
Is that something to do with wifi and mobile internet. as when in wifi its working even after hours

**Comment by christocracy** [comment]
> Is that something to do with wifi and mobile internet

No.  More likely your Android device manufacturer is responsible.  As linked above, see http://dontkillmyapp.com.

**Comment by Suryalg** [comment]
Then there is no solution is what you want to mean? because in hundreds of devices in some of them the app won't work if my major pupose is to get user data.

**Comment by christocracy** [comment]
No developer has the power to override some particular device manufacturer’s decision to violate the Android API, requiring the user to make necessary changes to Settings.

There’s a reason the developer behind http://dontkillmyapp.com created the site:  **Frustration with device manufacturers violating the Android API and breaking apps**.

Make the necessary changes to your settings as recommended and see if it solves your issue.

**Comment by Suryalg** [comment]
What are the changes in settings? can you give a brief about it?
As I have tried so many things like
Battery saver or optimization off, app background service allow on wifi and mobile internet

**Comment by christocracy** [comment]
Read http://dontkillmyapp.com

**Comment by Suryalg** [comment]
I have understood that this can be a device manufacturer issue but Samsung Galaxy A10 I am getting the same location again and again. There is no possible chnace of any error as the same user when logs in in diff device it works fine
52.9664897,-2.0598356 --2020-08-05 23:11:49
52.9664897,-2.0598356 --2020-08-05 23:12:04
52.9664897,-2.0598356 --2020-08-05 23:12:07
52.9664897,-2.0598356 --2020-08-05 23:12:16
52.9664897,-2.0598356 --2020-08-05 23:12:59
52.9664897,-2.0598356 --2020-08-05 23:13:04
52.9664897,-2.0598356 --2020-08-05 23:17:04
52.9664897,-2.0598356 --2020-08-05 23:18:31
52.9664897,-2.0598356 --2020-08-05 23:18:37
52.9664897,-2.0598356 --2020-08-05 23:19:20
52.9664897,-2.0598356 --2020-08-05 23:19:34

**Comment by christocracy** [comment]
See wiki *Debugging*.  I have no idea under what circumstances those locations are being received by your app.  You need to observe the plugin’s logs in `adb logcat`.

**Comment by M-Chou** [comment]
Hello @christocracy 
On how many phones do we estimate this problem can appear? (percentage)
Thanks

**Comment by christocracy** [comment]
I have no idea.

**Comment by Cclown98** [comment]
@christocracy  what about keeping the service alive create a foreground bubble like the one Facebook's messenger uses, I started a project for that but it's very hard for me to finish because I'm not a very experienced android developer, neither I have enough time.

https://github.com/Cclown98/capacitor-bubble-background

**Comment by christocracy** [comment]
There is no need for a "foreground bubble" (whatever that is).  I do not experience any tracking issues with my 12 Android test-devices which I have running the Sample App for *months* at a time without even unlocking these devices.  When I move, they track.

![](https://dl.dropbox.com/s/2vn98hc3unsfv99/Screen%20Shot%202020-12-30%20at%2012.53.25%20PM.png?dl=1)
