### ISSUE TITLE
Prevent http locations when using getCurrentPosition

### ISSUE THREAD

**Issue by Sulorb** [transistorsoft/cordova-background-geolocation-lt#1174]
## Your Environment
* Plugin version: GitHub version (latest)
* Platform:  Android
* OS version: 11
* Device manufacturer / model: SM-G9500
* Cordova version (`cordova -v`): 9
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
        reset: true,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 100,
        url: 'https://XXXX.ngrok.io',
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true
      }```

## Expected Behavior
I would like to use getCurrentPosition without sending POST locations at each position found

## Actual Behavior
Every getCurrentPosition results send at the same time a POST location my server has to manage even if it's not needed in my scenario

## Steps to Reproduce
1. launch a getCurrentPosition from the plugin

## Context
I'm trying to get locally the coords of the user but I don't want every users to send to server their coords when using getCurrentPosition

**Comment by christocracy** [comment]
Have you read the API docs for `getCurrentPosition` and learned about the options available for that method?

![](https://dl.dropbox.com/s/effd9lmp8jlufuy/Screen%20Shot%202020-08-28%20at%2010.08.35%20AM.png?dl=1)

**Comment by Sulorb** [comment]
Yes but among the different options I didn't find something to prevent sending an http request. Maybe I forgot to preciser I still want to send http requests while in background with a distance of 100m BUT not during the use of getCurrentPosition.
![image](https://user-images.githubusercontent.com/29526245/91599201-372f3c80-e966-11ea-9820-7ae68a6f1370.png)

I just had a doubt on the persist option which says "Set false to disable persisting the retrieved Location in the plugin's SQLite database". I understand that it doesn't insert the data in the local database but not that it doesn't send http request.

Thanks for the quick answer

**Comment by christocracy** [comment]
The HTTP services *feeds off* the database.

If a location is not `persist`ed into the database, there’s no location for the http service to upload.

**Comment by Sulorb** [comment]
Nice, so the
`persist: false,`
resolved the problem. Thank you very much!
