### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by sandrojr** [transistorsoft/cordova-background-geolocation-lt#1175]
## Your Environment
* Plugin version: 3.8.2
* Platform: iOS or Android
* OS version: Windows 10
* Device manufacturer / model: Xaomi/ POCOPHONE F1
* Cordova version (`cordova -v`): 9.00
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onLocation = function (success, failure) {

    var bgGeo = plugin();

    bgGeo.onLocation.apply(bgGeo, arguments);

};
```

## Actual Behavior

I'd tried this code but happen a specific error

## Steps to Reproduce

1.clone this code: https://gist.github.com/christocracy/0379dd519d77f4215d5de943ed51ade9
2. run : npm install -i
3.install cordova-background-geolocation-lt
4.run : ionic cordova run android

## Context

I was try to reproduce this code: https://gist.github.com/christocracy/0379dd519d77f4215d5de943ed51ade9

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
```

</details>

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by sandrojr** [comment]
cordova-background-geolocation-lt 3.8.2 "BackgroundGeolocation"

**Comment by christocracy** [comment]
```
$ ls -al node_modules/cordova-background-geolocation-lt
```

**Comment by christocracy** [comment]
and show me the entire list:
```
$ cordova plugins
```

**Comment by sandrojr** [comment]
> ```
> $ ls -al node_modules/cordova-background-geolocation-lt
> ```

Mode                LastWriteTime         Length Name

----                -------------         ------ ----

d-----        8/20/2020   2:04 PM                .github

d-----        8/20/2020   2:04 PM                src

d-----        8/20/2020   2:04 PM                www

-a----       10/26/1985   9:15 AM          85452 CHANGELOG.md

-a----       10/26/1985   9:15 AM           9465 LICENSE.md

-a----        8/20/2020   2:04 PM           2907 package.json

-a----       10/26/1985   9:15 AM           4470 plugin.xml

-a----       10/26/1985   9:15 AM          26123 README.md

**Comment by sandrojr** [comment]
> and show me the entire list:
> 
> ```
> $ cordova plugins
> ```

call-number 1.0.4 "Cordova Call Number Plugin"

cordova-background-geolocation-lt 3.8.2 "BackgroundGeolocation"      

cordova-open-native-settings 1.5.2 "Native settings"

cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"

cordova-plugin-android-permissions 1.0.0 "Permissions"

cordova-plugin-app-version 0.1.9 "AppVersion"

cordova-plugin-background-fetch 6.1.1 "CDVBackgroundFetch"

cordova-plugin-calendar 5.1.4 "Calendar"

cordova-plugin-chooser 1.2.5 "Chooser"

cordova-plugin-datepicker 0.9.3 "DatePicker"

cordova-plugin-device 2.0.2 "Device"

cordova-plugin-dreamover-uid 1.3.0 "UID"

cordova-plugin-file-opener2 2.0.19 "File Opener2"

cordova-plugin-file-transfer 1.7.1 "File Transfer"

cordova-plugin-file 6.0.1 "File"

cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"

cordova-plugin-is-debug 1.0.0 "IsDebug"

cordova-plugin-network-information 2.0.2 "Network Information"

cordova-plugin-networkinterface 2.0.0 "NetworkInterface"

cordova-plugin-permission 0.1.0 "Permission"

cordova-plugin-qrscanner 2.6.2 "QRScanner"

cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"

cordova-plugin-splashscreen 5.0.2 "Splashscreen"

cordova-plugin-statusbar 2.4.2 "StatusBar"

cordova-plugin-whitelist 1.3.3 "Whitelist"

cordova-plugin-wifiinfo 0.0.2 "WifiInfo"

cordova-sms-plugin 0.1.13 "Cordova SMS Plugin"

cordova.plugins.diagnostic 5.0.0 "Diagnostic"

es6-promise-plugin 4.1.0 "Promise"

**Comment by christocracy** [comment]
uninstall / re-install the plugin.
```
$ cordova plugin remove cordova-background-geolocation-lt
$ ionic cordova plugin add cordova-background-geolocation-lt
```
