### ISSUE TITLE
Interacting with splashscreen?

### ISSUE THREAD

**Issue by CodeWithOz** [transistorsoft/cordova-background-geolocation-lt#1176]
I'm using the [splashscreen plugin](https://github.com/apache/cordova-plugin-splashscreen) and I noticed that on app init, the splashscreen gets removed automatically even if I disable it by setting [`AutoHideSplashScreen`](https://github.com/apache/cordova-plugin-splashscreen#configxml) to `"false"`. When I uninstall this plugin, the problem goes away.

## Your Environment
* Plugin version: 3.6.2
* Platform: Android
* OS version: Android 8 - 10
* Device manufacturer / model: Samsung, Tecno
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`): 9.0.0
* Plugin config provided to `#ready`:
```javascript 

        let geoDebugOptions = {};

        if (globals.bgGeoDebug) {
            geoDebugOptions = {
                reset: true, // to ensure our debugging and log level config changes are picked up
                debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: bgGeo.LOG_LEVEL_VERBOSE,
            };
        } else {
            geoDebugOptions = {
                reset: true,
                debug: false,
            };
        }

        const initGeoOptions = {
            // Geolocation config
            desiredAccuracy: 0,
            stationaryRadius: 50,
            distanceFilter: 50,
            disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
            locationUpdateInterval: 5000,
            minimumActivityRecognitionConfidence: 80, // 0-100%.  Minimum activity-confidence for a state-change
            fastestLocationUpdateInterval: 5000,
            activityRecognitionInterval: 10000,
            stopTimeout: 0,
            stopOnTerminate: false,
            startOnBoot: true,
            locationAuthorizationRequest: 'Any',
            // Default is "Always".  This will force a prompt and take user to device settings for iOS,
            // if the current location settings do not match.  Options: "Always", "WhenInUse", or "Any"
            // Application config
            url: [our url]
            method: 'POST',
            batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
            // Debug config
            ...geoDebugOptions,
        };

        bgGeo.ready(initGeoOptions, async function (state) { ... });
```

## Expected Behavior

Using this plugin should not interact with or hijack the functioning of the splashscreen plugin.

## Actual Behavior

Using this plugin causes the splashscreen to always be removed automatically, even when I try
to avoid that by disabling the auto-hide functionality in the splashscreen plugin.

## Steps to Reproduce

1. With this plugin installed and `<preference name="AutoHideSplashScreen" value="false" />` in the config.xml file, the splashscreen still gets removed automatically.
2. After uninstalling this plugin, the splashscreen is not removed until `navigator.splashscreen.hide()` is called

## Context

Control when my splashscreen is removed by setting `<preference name="AutoHideSplashScreen" value="false" />` and calling `navigator.splashscreen.hide()` when I want to remove the splashscreen.

## Debug logs

Sorry not sure which set of logs would be useful here, and I don't want to dump everything from app init. Let me know if a particular set of log statements would be useful.
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I have no idea.

**Comment by CodeWithOz** [comment]
@christocracy thanks for the quick response. Can you please look through [this thread](https://github.com/apache/cordova-plugin-splashscreen/issues/217), that's the sort of problem I'm dealing with.

**Comment by christocracy** [comment]
Please create a simple pure Cordova Hello world app that reproduces the problem and share that github repo here.

**Comment by avargaskun** [comment]
I'm also running into this same issue - it appears the `cordova-background-geolocation` plugin is making the splashscreen disappear immediately on application launch. The setting in config.xml for `AutoHideSplashScreen` is being ignored. 

FYI - I am trying to setup a simple repro but having trouble cloning the SimpleApp for Android. See: https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/130

**Comment by CodeWithOz** [comment]
@avargaskun if you can get a repro that would be awesome for full debugging. In case you need it, what helped for me was to not initialize the bg geo plugin (`bgGeo.ready()`) at all until I had called `navigator.splashscreen.hide()`.
