### ISSUE TITLE
Android Headless Mode capacitor close 

### ISSUE THREAD

**Issue by alphagamer7** [transistorsoft/cordova-background-geolocation-lt#1178]
## Your Environment
* Plugin version: 3.9.0
* Platform:  Android
* OS version:
* Device manufacturer / model: HTC One M8
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): android 9.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
            debug: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10, 
            stopTimeout: 300,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            disableStopDetection: true,
          }
```

For capacitor, is it possible to use Android headless mode within the app itself like done in [React Native](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode) or should we follow something similar as done for cordova and add it with java code ?

**Comment by christocracy** [comment]
You have to follow the same Cordova instructions as the Wiki here.
