### ISSUE TITLE
await BackgroundGeolocation.start() is not resolving

### ISSUE THREAD

**Issue by willemjanvankranenburg** [transistorsoft/cordova-background-geolocation-lt#1179]
## Your Environment
* Plugin version: 3.7.0
* Platform:  Android
* OS version: 10
* Device manufacturer / model: OnePlus 7pro, Samsung Galaxy S9, OnePlus 6
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`):  android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

function getConfig(userId: string): Config
       const LATEST_POSITION_INTERVAL: number = 60000;
        const ROUTE_INTERVAL: number = 20000;
        const MINIMAL_DISTANCE_MOVED_IN_METERS: number = 20;

            const params: any = {
                user: userId,
                handled: false
            };
            const config: Config = {
                debug: false,
                reset: true,
                distanceFilter: 0,
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            }
            const routeId: string = await this.storage.get(StorageKey.ROUTE_ID);
            if (environment.backgroundGeolocationLoggingLevel === BackgroundLoggingLevel.ROUTE) {
                if (routeId != null) {
                    params.route = routeId;
                    config.distanceFilter = MINIMAL_DISTANCE_MOVED_IN_METERS;
                    config.fastestLocationUpdateInterval = ROUTE_INTERVAL;
                } else {
                    config.disableStopDetection = true;
                    config.foregroundService = true;
                    config.fastestLocationUpdateInterval = LATEST_POSITION_INTERVAL;
                    config.locationUpdateInterval = LATEST_POSITION_INTERVAL;
                }
            } else {
                config.locationUpdateInterval = LATEST_POSITION_INTERVAL;
            }
            config.params = params;
            return config;
}
```

## Expected Behavior
In our app (a proof of delivery app) we have multipe stops the user has to drive to.  When we start navigation we call the following code:
```
 const config: Config = await this.getConfig(user.id);
            if (!config) {
                return;
            }
            const state: State = await BackgroundGeolocation.getState();
            if (state.enabled) {
                await BackgroundGeolocation.stop();
            }
            await BackgroundGeolocation.setConfig(config);
            await BackgroundGeolocation.start();
            // Get the current state of the background plugin
            const stateAfterStart: State = await BackgroundGeolocation.getState();
```

and when we stop / arive at the destination; we call `BackgroundGeolocation.stop();`

**I expect the `await BackgroundGeolocation.start();` to resolve when the plugin has started.**

## Actual Behavior
When the android system permission for "Physical Activity" is denied and the permission for "location" is set to "Only while app is in use", the `.start();` doesn't resolve the second time. The first time it works perfectly, it resolves and goes to the line below, but the second time it gets stuck there..

If we change it to the following it always seem to work.
```
BackgroundGeolocation.start().then(() => { console.log('started'); });
```

## Steps to Reproduce
1. Create an app with the above code
2. Revoke permissions on android for physical activity and location
3. Start the plugin twice, with an await.

**Comment by christocracy** [comment]
Observe the plugin logs in `logcat`: 
```
$ adb logcat *:S TSLocationManager:V
```

**Comment by willemjanvankranenburg** [comment]
[BackgroundGelocation logcat.pdf](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/5230289/BackgroundGelocation.logcat.pdf)

See the attached file.
