### ISSUE TITLE
Can't add geofences via addGeofence

### ISSUE THREAD

**Issue by nick2k5** [transistorsoft/cordova-background-geolocation-lt#118]
addGeofence appears as if it's working -- it fires the callbackFn. 

However, the geoFences don't actually seem to exist. They never fire notification events, and if I call getGeofences (both immediately upon adding a geofence, and after a delay) I always receive an empty array.

```javascript
bgGeo = window.BackgroundGeolocation;
bgGeo.addGeofence({
 identifier: '1', 
 latitude: 37.422396, 
 longitude: -122.171340, 
 radius: 200, 
 notifyOnEnter: true, 
 notifyOnEnter: true},  
function(){ 
 console.log('added')
}, 
function(){
 console.log('not')
})
```

> 'added'

```javascript
bgGeo.getGeofences(
 function(geofences){
  console.log(geofences)
 }, 
 function(){
  console.warn('error')
})
```
> []

**Comment by christocracy** [comment]
Does #addGeofences do the same?

On Wednesday, May 25, 2016, Nick Alexander <notifications@github.com> wrote:

> addGeofence appears as if it's working -- it fires the callbackFn.
>
> However, the geoFences don't actually seem to exist. They never fire
> notification events, and if I call getGeofences (both immediately upon
> adding a geofence, and after a delay) I always receive an empty array.
>
> bgGeo = window.BackgroundGeolocation;bgGeo.addGeofence({
>  identifier: '1',
>  latitude: 37.422396,
>  longitude: -122.171340,
>  radius: 200,
>  notifyOnEnter: true,
>  notifyOnEnter: true},  function(){
>  console.log('added')
> }, function(){
>  console.log('not')
> })
>
> 'added'
>
> bgGeo.getGeofences(
>  function(geofences){
>   console.log(geofences)
>  },
>  function(){
>   console.warn('error')
> })
>
> []
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/118>
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
I don't seem to have a problem with this.  Are you calling #configure before adding geofences?

**Comment by christocracy** [comment]
Status please.

**Comment by andpoulsen** [comment]
You have to call bgGeo.configure({}) before you register the geofences.
