### ISSUE TITLE
Unsupported Swift Version using Xcode 12

### ISSUE THREAD

**Issue by SISQUAL** [transistorsoft/cordova-background-geolocation-lt#1181]
## Your Environment
OS version: 10.15.6
XCode version: 12.0
Swift version target: 4.2
Device manufacturer / model: Apple
Cordova version (cordova -v): 9
Cordova platform version (cordova platform ls):5.1.1
Plugin config provided to #ready:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

XCode should build the app
## Actual Behavior

Unsupported Swift Version
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
Unsupported Swift Version
The target "SISQUAL Smart Clocking" contains source code developed with Swift 3.x . This version of Xcode does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4
```

</details>

**Comment by christocracy** [comment]
This plugin does not contain any *Swift* code.  I program my libraries with *pure Obj-c*.

**Comment by SISQUAL** [comment]
I will chek others cordova plugins, thanks
