### ISSUE TITLE
Licence key for capacitor

### ISSUE THREAD

**Issue by monkeydkon** [transistorsoft/cordova-background-geolocation-lt#1185]
## Your Environment
* Plugin version: 3.9.2
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Context

If i am using capacitor instead of cordova, where should i be putting the licence key? There is no config.xml as you say. 
should i be putting this code: 
```
<platform name="android">
      <!-- background-geolocation -->
      <config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
          <meta-data
            android:name="com.transistorsoft.locationmanager.license_key"
            android:value="YOUR_LICENSE_KEY_HERE" />
      </config-file>
      <!-- /background-geolocation -->
</platform>
```

straight in to the AndroidManifest.xml ? And if so, at which level exactly?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Customers, please post support requests in the [private repo](https://github.com/transistorsoft/cordova-background-geolocation).  

See the README [Capacitor Setup](https://github.com/transistorsoft/cordova-background-geolocation#large_blue_diamond-installing-the-plugin)

![](https://dl.dropbox.com/s/ym9iffa8dyp7bhd/Screen%20Shot%202020-10-19%20at%2011.45.15%20AM.png?dl=1)
