### ISSUE TITLE
Timestamp Format on Location Template

### ISSUE THREAD

**Issue by MartinNowak96** [transistorsoft/cordova-background-geolocation-lt#1186]
Is is possible to configure the format of the timestamp in the location template?

I would like to specify the time format like I do in moment.js. Example : "YYYY-MM-DD[T]HH:mm:ss.SSS[Z]"

My main goal is to include time zone.

```
locationTemplate:'{ "time":"<%= timestamp %>","lat":"<%= latitude %>" , "long":"<%= longitude %>" ,"speed":"<%= speed %>", "heading":"<%= heading %>" , "accuracy": "<%= accuracy %>"}',
```

Thank you!

**Comment by christocracy** [comment]
No, it is not possible.
