### ISSUE TITLE
Creating a steady location update interval of 1 minute, even when stationary, stops after 5 minutes

### ISSUE THREAD

**Issue by ricardodebeijer** [transistorsoft/cordova-background-geolocation-lt#1188]
Hello, I am trying to get this plugin to log location updates at a steady interval of ~1 minute, even when staying stationary (on Android with Ionic5/Cordova).
I have set both `locationUpdateInterval` and `fastestLocationUpdateInterval` to 60000ms.
Also I set `allowIdenticalLocations` and `disableStopDetection` to true.
However, after 5 minutes I no longer receive location updates.

See attached log file for more info
On 17:10 I called the `destroyLog()` and restarted the app, to have clear logs
From 17:10:59 till 17:15:05 I get location updates, after that it stops.
On 17:20:43 I hit the stop & start button again, which triggers updates again, but only till 17:25:25  (again for just 5 minutes).
On 17:30 I killed the app and restarted it again, to be able to include the logs when the app was shut down and restarted.

## Your Environment
* Plugin version: 3.9.2
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Zebra Technologies TC56
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
```javascript
   let config: Config = {
      isMoving: true,

      distanceFilter: 0,
      locationUpdateInterval: this.nonActiveRouteInterval,
      fastestLocationUpdateInterval: this.nonActiveRouteInterval,
      disableStopDetection: true,
      allowIdenticalLocations: true,
      params: {
        user: this.authenticationService.ApplicationUser.id
      },

      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      reset: true,
      foregroundService: true,
      notification: {
        title: 'DEV GPS logging',
        text: 'This app is busy logging your gps'
      },
      backgroundPermissionRationale: {
        title: 'Allow {applicationName} to access to this device\'s location in the background?',
        message: 'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission',
        positiveAction: 'Change to {backgroundPermissionOptionLabel}',
        negativeAction: 'Cancel'
      },
      transistorAuthorizationToken: token
    };


```

## Expected Behavior
I expect, due to setting `allowIdenticalLocations` and `disableStopDetection` that my location updates keep on going, at the given interval of 60000ms, even when staying stationary.

## Actual Behavior
For the first 5 minutes, I get location updates, even when stationary, as expected.
After those 5 minutes, I get no location updates anymore.

When I tap on start button (which includes the `isMoving` again), the location updates start again, but again only for 5 minutes.

## Steps to Reproduce
```javascript
    // Step 0. Wait for platform ready
    await this.platform.ready();

    // Step 1.  Listen/subscribe to events.
    BackgroundGeolocation.onLocation(location => {
      this.addLog(`[onLocation] ${new Date(location.timestamp).toLocaleTimeString()}: ${location.coords.latitude},${location.coords.longitude}. speed: ${location.coords.speed}. moving: ${location.is_moving}. activity: ${(location.activity as any).type}`);
    }, (error) => {
      this.addLog(`[onLocation] ERROR: ${error}`);
    });

    // Fetch a JSON Web Token from dev server.
    const token = await BackgroundGeolocation.findOrCreateTransistorAuthorizationToken(
      'orange-nxt',
      'rdb-zebra',
      this.url
    );

    // Step 2. Configure the plugin with #ready
    const state: State = await BackgroundGeolocation.ready({
      isMoving: true,

      distanceFilter: 0,
      locationUpdateInterval: this.nonActiveRouteInterval,
      fastestLocationUpdateInterval: this.nonActiveRouteInterval,
      disableStopDetection: true,
      allowIdenticalLocations: true,
      params: {
        user: this.authenticationService.ApplicationUser.id
      },

      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      reset: true,
      foregroundService: true,
      notification: {
        title: 'DEV GPS logging',
        text: 'Deze app is druk bezig je gps te loggen'
      },
      backgroundPermissionRationale: {
        title: 'Allow {applicationName} to access to this device\'s location in the background?',
        message: 'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission',
        positiveAction: 'Change to {backgroundPermissionOptionLabel}',
        negativeAction: 'Cancel'
      },
      transistorAuthorizationToken: token
    });

    this.addLog(`[ready] BackgroundGeolocation is ready to use`, state);

    // Start logging
    await BackgroundGeolocation.start();
```
## Context
I am trying to create an application which has two modes (or rather configs when referred to this plugin):
- One config is used to keep track of the device, which should be updated every minute, even if the device stays on the same location (eg on a table in a gradle). I am having trouble with this config, thats why I created this issue
- A second config is used when a user is actively driving a route (updated by using the `setConfig`). This config uses a faster interval (20s) to show a nice trail on a map. This config seems to work as expected, because the device stays in motion.

## Debug logs
See attached file: 
[2020-10-21T15_30_32.329Z-ricardo-zebra.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/5417041/2020-10-21T15_30_32.329Z-ricardo-zebra.log)

**Comment by christocracy** [comment]
See http://dontkillmyapp.com

**Comment by christocracy** [comment]
Also, if you're hoping for your app to continue tracking after *terminate*, see API docs `Config.stopOnTerminate`.  The default is `true`.

```
10-21 17:30:19.984 INFO [BackgroundGeolocation$k0 run] 
╔═════════════════════════════════════════════
║ MainActivity was destroyed
╠═════════════════════════════════════════════
╟─ stopOnTerminate: true
╟─ enabled: false

```

**Comment by aamirsyed110** [comment]
> Hello, I am trying to get this plugin to log location updates at a steady interval of ~1 minute, even when staying stationary (on Android with Ionic5/Cordova).
> I have set both `locationUpdateInterval` and `fastestLocationUpdateInterval` to 60000ms.
> Also I set `allowIdenticalLocations` and `disableStopDetection` to true.
> However, after 5 minutes I no longer receive location updates.
> 
> See attached log file for more info
> On 17:10 I called the `destroyLog()` and restarted the app, to have clear logs
> From 17:10:59 till 17:15:05 I get location updates, after that it stops.
> On 17:20:43 I hit the stop & start button again, which triggers updates again, but only till 17:25:25 (again for just 5 minutes).
> On 17:30 I killed the app and restarted it again, to be able to include the logs when the app was shut down and restarted.
> 
> ## Your Environment
> * Plugin version: 3.9.2
> * Platform: Android
> * OS version: 8.1.0
> * Device manufacturer / model: Zebra Technologies TC56
> * Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
> * Cordova platform version (`cordova platform ls`): android 8.1.0
> * Plugin config provided to `#ready`:
> 
> ```js
>    let config: Config = {
>       isMoving: true,
> 
>       distanceFilter: 0,
>       locationUpdateInterval: this.nonActiveRouteInterval,
>       fastestLocationUpdateInterval: this.nonActiveRouteInterval,
>       disableStopDetection: true,
>       allowIdenticalLocations: true,
>       params: {
>         user: this.authenticationService.ApplicationUser.id
>       },
> 
>       logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
>       reset: true,
>       foregroundService: true,
>       notification: {
>         title: 'DEV GPS logging',
>         text: 'This app is busy logging your gps'
>       },
>       backgroundPermissionRationale: {
>         title: 'Allow {applicationName} to access to this device\'s location in the background?',
>         message: 'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission',
>         positiveAction: 'Change to {backgroundPermissionOptionLabel}',
>         negativeAction: 'Cancel'
>       },
>       transistorAuthorizationToken: token
>     };
> ```
> 
> ## Expected Behavior
> I expect, due to setting `allowIdenticalLocations` and `disableStopDetection` that my location updates keep on going, at the given interval of 60000ms, even when staying stationary.
> 
> ## Actual Behavior
> For the first 5 minutes, I get location updates, even when stationary, as expected.
> After those 5 minutes, I get no location updates anymore.
> 
> When I tap on start button (which includes the `isMoving` again), the location updates start again, but again only for 5 minutes.
> 
> ## Steps to Reproduce
> ```js
>     // Step 0. Wait for platform ready
>     await this.platform.ready();
> 
>     // Step 1.  Listen/subscribe to events.
>     BackgroundGeolocation.onLocation(location => {
>       this.addLog(`[onLocation] ${new Date(location.timestamp).toLocaleTimeString()}: ${location.coords.latitude},${location.coords.longitude}. speed: ${location.coords.speed}. moving: ${location.is_moving}. activity: ${(location.activity as any).type}`);
>     }, (error) => {
>       this.addLog(`[onLocation] ERROR: ${error}`);
>     });
> 
>     // Fetch a JSON Web Token from dev server.
>     const token = await BackgroundGeolocation.findOrCreateTransistorAuthorizationToken(
>       'orange-nxt',
>       'rdb-zebra',
>       this.url
>     );
> 
>     // Step 2. Configure the plugin with #ready
>     const state: State = await BackgroundGeolocation.ready({
>       isMoving: true,
> 
>       distanceFilter: 0,
>       locationUpdateInterval: this.nonActiveRouteInterval,
>       fastestLocationUpdateInterval: this.nonActiveRouteInterval,
>       disableStopDetection: true,
>       allowIdenticalLocations: true,
>       params: {
>         user: this.authenticationService.ApplicationUser.id
>       },
> 
>       logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
>       reset: true,
>       foregroundService: true,
>       notification: {
>         title: 'DEV GPS logging',
>         text: 'Deze app is druk bezig je gps te loggen'
>       },
>       backgroundPermissionRationale: {
>         title: 'Allow {applicationName} to access to this device\'s location in the background?',
>         message: 'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission',
>         positiveAction: 'Change to {backgroundPermissionOptionLabel}',
>         negativeAction: 'Cancel'
>       },
>       transistorAuthorizationToken: token
>     });
> 
>     this.addLog(`[ready] BackgroundGeolocation is ready to use`, state);
> 
>     // Start logging
>     await BackgroundGeolocation.start();
> ```
> 
> ## Context
> I am trying to create an application which has two modes (or rather configs when referred to this plugin):
> 
> * One config is used to keep track of the device, which should be updated every minute, even if the device stays on the same location (eg on a table in a gradle). I am having trouble with this config, thats why I created this issue
> * A second config is used when a user is actively driving a route (updated by using the `setConfig`). This config uses a faster interval (20s) to show a nice trail on a map. This config seems to work as expected, because the device stays in motion.
> 
> ## Debug logs
> See attached file:
> [2020-10-21T15_30_32.329Z-ricardo-zebra.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/5417041/2020-10-21T15_30_32.329Z-ricardo-zebra.log)



> * r is actively dri



hey buddy can u share the code of your secound config file. and the function where u update the location

**Comment by ricardodebeijer** [comment]
We could not get this to work with our device (Zebra TC56). 
We cant find any battery optimization options that we can turn off which allows this to work.

In the future we will try again with the `onHeartbeat` event, which with allows for a `heartbeatInterval`  of 60 on Android.
So hopefully that will work, closing this issue for now
