### ISSUE TITLE
how to get plugin version in running app?

### ISSUE THREAD

**Issue by dgobaud** [transistorsoft/cordova-background-geolocation-lt#119]
Is there a way to get the version of the plugin in code?

**Comment by christocracy** [comment]
Not that I'm aware of, though it must be accessible by parsing the
plugin.xml.  I'll look into it.

On Thursday, May 26, 2016, David Gobaud <notifications@github.com> wrote:

> Is there a way to get the version of the plugin in code?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/119>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l01EOUOJcgWR1pnLOjkmQ5kKqE8Wks5qFkh2gaJpZM4IoGFk>
> .
>


-- 
Snet form Gmail Mobile
