### ISSUE TITLE
How Do I send form-data not Json Payload in the POST 

### ISSUE THREAD

**Issue by ausittechdirect** [transistorsoft/cordova-background-geolocation-lt#1190]
## Your Environment
* Plugin version: Latest
* Platform: Android
* OS version: 10
* Device manufacturer / model: Oppo Reno2 Z
* Cordova version 9.0:
* Cordova platform version Monaca:
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
  enableHeadless: true,    // <-- enable Headless mode
  stopOnTerminate: false,  // <-- required for Headless JS
  url: "https://communicate.ausittechdirect.com.au/api/save_device/",
  autoSync: true,
  debug: true,
  locationAuthorizationRequest: 'Always',
  autoSyncThreshold: 5,
  batchSync: false,
  triggerActivities: "walking, running, in_vehicle",
  httpRootProperty: '.',
  headers: {
    "Access-Token": '804f1ebb9313128c276796ef4d56e056'
  },
  locationTemplate: {
    "latitude":'<%= latitude %>',
    "longitude":'<%= longitude %>',
    "device_token": window.localStorage.getItem('deviceToken'),
    "device_type": 'android',
    },
  locationsOrderDirection: "DESC",
  maxDaysToPersist: 14  
}, state => {
  // engage geofences-only mode:
  BackgroundGeolocation.start();
});

```

## Expected Behavior
The Push Notification platform we are using requires the data to be sent as parameters or Form data but it is sending as a JSON Payload in the body can this be changed, 

## Actual Behavior
Normal Function of happening wondering if possible to change the way it sends the data to server. 

## Steps to Reproduce

1.
2.
3.
4.

## Context
Need to intergrate with our Push Notification dashdoard but the data from the APP is not in a format that the PUSH platform is looking for. 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You can't.  JSON only.

**Comment by ausittechdirect** [comment]
Hi Chris 

No need to be so rude. I haven't purchased your plugin yet and now don't think I will if reaching out for support warrants such a short response. 

Thank you for your reply

Cheers Matt
