### ISSUE TITLE
Location template timestamp after phone's time changed

### ISSUE THREAD

**Issue by MartinNowak96** [transistorsoft/cordova-background-geolocation-lt#1192]
## Your Environment
* Plugin version: 3.7.0
* Platform: iOS
* OS version:14.0.1
* Device manufacturer / model: Apple / iPhone 7
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`): 5.1.1

I am located GMT -06:00 and I set the phone's time zone to GMT -05:00. When I get a location by using the location template the time is still GMT - 06:00. I tried to reboot the phone in GMT -05:00 but they are still coming back as GMT -06:00. Can you please provide some information on how the time is being provided to the location template?

```
locationTemplate:'{ "time":"<%= timestamp %>","lat":"<%= latitude %>" , "long":"<%= longitude %>" ,"speed":"<%= speed %>", "heading":"<%= heading %>" , "accuracy": "<%= accuracy %>"}',
```

## Context
I am trying to determine the user's time zone offset with the geolocations.

Thank you for your very quick replies!

**Comment by christocracy** [comment]
The timestamp is UTC.  It doesn't care about your local timezone.  If you care about the device's timezone, you could add that information to your `Config.params`
