### ISSUE TITLE
Expose the plugin's database in a callback so that we can store our own metadata in it

### ISSUE THREAD

**Issue by shamilovtim** [transistorsoft/cordova-background-geolocation-lt#1193]
We need a database to use in the background of our Android application to store some of our business specific metadata related to the background geofencing. The problem is that we cannot get a backgrounded SQLite database to work while simultaneously using this plugin. The `window.createDatabase()` (default webSQL) object is empty while the app is in the background, and additionally, any 3rd party implementations of SQLite databases seem to all suffer from the same exact issue. I was wondering if it's possible to provide a callback from this plugin that exposes its database object so that as users we can perform operations on it? Thank you!

**Comment by christocracy** [comment]
What sort of meta-data are you providing and why can't you just use `Config.extras` or `Config.params` to store that meta-data.  That's what they're designed for.

**Comment by shamilovtim** [comment]
Hey @christocracy! It's relational data with a several tables and queries. Unfortunately it's larger in complexity than a simple keystore could support. If a simple keystore sufficed I'd typically just use localstorage.

**Comment by christocracy** [comment]
Sorry, the plugin's database is strictly designed as a simple queue for the plugin's HTTP service and its API is limited.  It is unsuitable for your use-case.
