### ISSUE TITLE
Keep the notification 'location service activated' visible during the tracking

### ISSUE THREAD

**Issue by dabaaaz** [transistorsoft/cordova-background-geolocation-lt#1194]
On Android we get 'location service activated' peristsent notification for 0,5 seconds every random seconds once the app launch BackgroundGeolocation.start().

Is it possible to not kill this notification because it's not readable ?!
And after is it possible to change the notification title ?

I tried the code below but this notification was not replacing the persitent one, another notification was showing.

notification: {
   title: "Background tracking engaged by DDDD",
   text: "My notification text yalaaa",
}

EDIT1:

I fixed the notification with notification.sticky at true.
And the title and text work !

Now I put try to change the smallIcon with mipmap-hdmi/ic_launcher as I get android/app/src/main/res/mipmap-hdpi/ic_launcher.png icon, what is wrong ?

EDIT2 : 

Now when I send a notification from another service, that last one is not showing if the notification is sticky, because the sticky one take the place. If I do not enable the sticky one I get the notification from the service.

How can cordova-background-geolocation leave the other notifications to be shown ?

**Comment by dabaaaz** [comment]
I fixed the notification with notification.sticky at true.
And the title and text work !

Now I put try to change the smallIcon with mipmap-hdmi/ic_launcher as I get android/app/src/main/res/mipmap-hdpi/ic_launcher.png icon, what is wrong ?

**Comment by dabaaaz** [comment]
Now when I send a notification from another service, that last one is not showing if the notification is sticky, because the sticky one take the place. If I do not enable the sticky one I get the notification from the service.

How can cordova-background-geolocation leave the other notifications to be shown ?!

**Comment by christocracy** [comment]
How *exactly* did you configure `notification`?  Show it to me.

**Comment by dabaaaz** [comment]
Here is the path of my icon

![smallIcon](https://user-images.githubusercontent.com/1432848/100312607-1309e880-2fb3-11eb-9445-fef8f0377583.png)

Then here is my code :

```
notification: {
	sticky: true,
	title: "Background tracking engaged by DDDD",
	text: "My notification text yalaaa",
	priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
	smallIcon: "mipmap-hdpi/ic_launcher",
},
```

**Comment by dabaaaz** [comment]
>> https://github.com/zo0r/react-native-push-notification/issues/730#issuecomment-389545259 fixed this !

**Comment by christocracy** [comment]
Please close your own issues when solved.

**Comment by dabaaaz** [comment]
```
notification: {
	sticky: true,
	title: "The title youhou",
	text: "My notification text areaaaa",
	priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
	smallIcon: "mipmap/ic_notification",
}
```

with a `ic_notification.png` file added to every `mipmap-*`
