### ISSUE TITLE
Sticky notification disappear during the day

### ISSUE THREAD

**Issue by dabaaaz** [transistorsoft/cordova-background-geolocation-lt#1195]
Hi,

I've put `notification.sticky: true` and `stopOnTerminate: false`.
This morning I leave my phone at home and the persistent notification was there.

Tonight when I arrived that one have been disapeared.
It's a good nice but how is it working ? Once stationary and the app is killed, how many time have I to wait to get the notification disapeared ?! Is it random ?

**Comment by christocracy** [comment]
Do **NOT** ignore the issue template.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by dabaaaz** [comment]
See #1196
