### ISSUE TITLE
Android headless problems using Capacitor

### ISSUE THREAD

**Issue by lbonsey1** [transistorsoft/cordova-background-geolocation-lt#1197]
## Your Environment
* Plugin version: 3.9.0
* Platform: Android
* OS version: Mac
* Device manufacturer / model: Emulated Pixel 3a
* Capacitor version: 2.2.1
* Quasar version: 2.1.8
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
debug: true,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
foregroundService: true,
geofenceInitialTriggerEntry: false,
geofenceModeHighAccuracy: true,
maxRecordsToPersist: 0,
stopTimeout: 5,
enableHeadless: true,
stopOnTerminate: false,
```

## Expected Behavior

Expected to see headless task events appearing in logcat.

## Actual Behavior

Instead got this error:
```HeadlessTask failed to find com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask.java```

## Steps to Reproduce

Followed instructions from github wiki as shown [here](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode#capacitor-setup-1).

## Context

Trying to get headless mode set up with Android/Capacitor. I am using Quasar if that's relevant. 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
E/TSLocationManager: [c.t.locationmanager.util.a a] HeadlessTask failed to find com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask.java.  If you've configured enableHeadless: true, you must provide a custom BackgroundGeolocationHeadlessTask.java.  See Wiki: https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode
E/TSLocationManager: [c.t.locationmanager.util.a a] 
      ‼️  com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask
W/TSLocationManager: [c.t.locationmanager.util.a a] 
      ⚠️  Attempted to post headless event geofenceschange but there are no listeners.
```

</details>

**Comment by christocracy** [comment]
>Plugin version: 3.9.0

See [CHANGELOG 3.9.2](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#392--2020-10-02)

![](https://dl.dropbox.com/s/7wgjkl89yj7myey/Screen%20Shot%202020-11-30%20at%2012.41.48%20PM.png?dl=1)

**Comment by christocracy** [comment]
Btw, customers  should post support requests (and install from) the [private repo](https://github.com/transistorsoft/cordova-background-geolocation)
