### ISSUE TITLE
Prominent disclosure needed before location runtime permission 

### ISSUE THREAD

**Issue by maswa** [transistorsoft/cordova-background-geolocation-lt#1198]
## Your Environment
* 3.9.4:
* Platform: Android
* OS version: 10
* Cordova version (`cordova -v`): 10.0
* Cordova platform version (`cordova platform ls`): 9.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
bgGeo.ready({
        // Geolocation config
		//desiredAccuracy: 0,
		//logLevel:bgGeo.LOG_LEVEL_VERBOSE,
		locationAuthorizationRequest: 'Always',
 		backgroundPermissionRationale: {
   	title: "Allow {applicationName} to access to this device's location in the background?",
   	message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
   	positiveAction: "Change to {backgroundPermissionOptionLabel}",
   	negativeAction: "Cancel"
 		},
	  	desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
		notificationTitle:'Tracking active',
		notificationText:'Background tracking',
		distanceFilter: 10,
	  	stationaryRadius: 25,
		stopTimeout: 5,         // Change state to stationary after 1 min with device "still"
		desiredOdometerAccuracy :40,
        //stopOnTerminate: false, // Don't stop tracking when app is terminated.
	  	foregroundService: true,

		preventSuspend : true,
        debug: false, // <-- Debug sounds & notifications.
				
```

## Expected Behavior
 Google rejected my app update because of missing a Prominent disclosure needed before location runtime permission.

i just would like to know if there is any disclosure popup provided from plugin side which i can set? I have read about the backgroundPermissionRationale and locationAuthorizationAlert but these are not serving a disclosure popup.

**Comment by christocracy** [comment]
See my latest blog:

https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353

**Comment by maswa** [comment]
Thank you that is a clear post, very helpful
