### ISSUE TITLE
Blink notification during movement

### ISSUE THREAD

**Issue by dabaaaz** [transistorsoft/cordova-background-geolocation-lt#1199]
Hi,

As we can see into the below video (in the zip), the icon of the app appear/disappear in the screen off during movement. Is it possible to always get the icon in a sticky mode ?!

[persistent-notification.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/5635275/persistent-notification.zip)

* Plugin version: 3.9.2
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung Galaxy Note 10+
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): Current working directory is not a Cordova-based project, it's Capacitor
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
	url: environment.apiUrl,
	params: {
		"testId": this.testId,
	},
	headers: {
		'Content-Type':  'application/x-www-form-urlencoded',
		'Merchant-Token': environment.merchantToken,
		'Authorization': 'Basic [TOKEN]',
	},
	logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	stopOnTerminate: false,
	startOnBoot: true,
	reset: true,
	useSignificantChangesOnly: true,
	disableMotionActivityUpdates: true,
	locationAuthorizationRequest: 'Always',
	backgroundPermissionRationale: { // for Android
		title: "Accès à votre position en arrière-plan",
		message: "Veuillez autoriser l'accès à votre position à 'Toujours autoriser' dans les réglages de l'application",
		positiveAction: 'Changer à "Toujours autoriser"',
		negativeAction: "Fermer"
	},
	locationAuthorizationAlert: { // for iOS
		titleWhenNotEnabled: "L'accès à votre position en arrière-plan n'est pas correctement activé",
		titleWhenOff       : "L'accès à votre position en arrière-plan est désactivé",
		instructions       : "Veuillez autoriser l'accès à votre position à 'Toujours' dans les réglages de l'application",
		cancelButton       : "Fermer",
		settingsButton     : "Réglages"
	},
	enableHeadless: true,
	notification: {
		sticky: true,
		title: "My title",
		text: "My text",
		priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
		smallIcon: "mipmap/ic_notification",
	},
}
```

## Steps to Reproduce
Take the car and drive it

**Comment by christocracy** [comment]
`sticky: true` relies on `disableMotionActivityUpdates: false`

**Comment by dabaaaz** [comment]
and if I want to not show the behavior like the picture below ?

![image](https://user-images.githubusercontent.com/1432848/101050830-15f17400-3585-11eb-9a16-06249c64c012.png)

**Comment by christocracy** [comment]
Physical Activity permission is required for `sticky: true`.

**Comment by dabaaaz** [comment]
Is it an Android new behavior ?! If yes if you have some doc it could be interesting please :)

Otherwise `sticky: true` for notifications is working everywhere with `disableMotionActivityUpdates: true`. With Xiaomi or other phones it is not blinked neither in the classic panel nor in the status bar.

It is only blinked on Samsung Galaxy Note 10+ when the phone is lock. Do you think it is Samsung ?!

Because if it's possible I wouldn't add the modal "Allow BG Geolocation to access your physical activity".

**Comment by dabaaaz** [comment]
EDIT : the problem is on the feature “Always on Display”.
Maybe it will help you ?

**Comment by dabaaaz** [comment]
What if I use `triggerActivities` with all but `in_vehicle` ?
