### ISSUE TITLE
post is not executing

### ISSUE THREAD

**Issue by luiz70** [transistorsoft/cordova-background-geolocation-lt#120]
im using an api rest in node, can i post directly to my api? because i configured the plugin and is not wordking, the app recives the location but is not sending it to my api

url: 'myurl',
method: 'POST',
autoSync: true,
maxDaysToPersist: 1,

**Comment by christocracy** [comment]
Are you using PHP?

On Fri, May 27, 2016 at 11:20 AM, luiz70 <notifications@github.com> wrote:

> im using an api rest in node, can i post directly to my api? because i
> configured the plugin and is not wordking, the app recives the location but
> is not sending it to my api
>
> url: 'myurl',
> method: 'POST',
> autoSync: true,
> maxDaysToPersist: 1,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/120>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lzuZz9pyRbHSR9_Hdw3ieOyBd-fKks5qFwu7gaJpZM4IommJ>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
And are you monitoring the device logs and/or listening to the onHttp
event?

On Fri, May 27, 2016 at 11:31 AM, Chris Scott <christocracy@gmail.com>
wrote:

> Are you using PHP?
>
> On Fri, May 27, 2016 at 11:20 AM, luiz70 <notifications@github.com> wrote:
>
>> im using an api rest in node, can i post directly to my api? because i
>> configured the plugin and is not wordking, the app recives the location but
>> is not sending it to my api
>>
>> url: 'myurl',
>> method: 'POST',
>> autoSync: true,
>> maxDaysToPersist: 1,
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/120>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAA6lzuZz9pyRbHSR9_Hdw3ieOyBd-fKks5qFwu7gaJpZM4IommJ>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by luiz70** [comment]
im using nodejs,

**Comment by luiz70** [comment]
im monitoring server side and i have no request

**Comment by luiz70** [comment]
let me listen the onhttp

**Comment by christocracy** [comment]
Are you monitoring the device logs?  The plugin is **very** verbose with HTTP.

**Comment by christocracy** [comment]
Status please.

**Comment by conorstrejcek** [comment]
I believe I am having a similar issue. I am getting POSTs to my server from iOS devices, but not from Android.

I have attached logging code to both the `onLocation` and `onHttp` events in order to get a better sense of what is happening. What I see is that while both iOS and Android trigger the `onLocation` event as expected, only iOS event triggers the `onHttp` event. On Android, neither the success nor the failure callbacks are called, and on the server side I see no incoming requests.

Here is what my configuration looks like (with license key omitted):
```
{
    url: Meteor.absoluteUrl() + 'api/geolocation',
    params: {
        userId: Meteor.userId()
    },
    activityType: 'CLActivityTypeOther',
    locationUpdateInterval: 60000,
    desiredAccuracy: 0,
    stationaryRadius: 1,
    distanceFilter: 1,
    debug: true,
    preventSuspend: true,
    heartbeatInterval: 60,
}
```

I could just refrain from using the POST url and implement my own requests in the `onLocation` callback, but I would prefer to use the built-in functionality. Any guidance would be greatly appreciated.

**Comment by conorstrejcek** [comment]
I can also add that I see no attempts in the Android device log to make a POST request.

**Comment by christocracy** [comment]
I see you don't have `autoSync: true`.  Are you manually executing `bgGeo.sync()`?

**Comment by kholiavko-roman** [comment]
I have the same issue, post does not execute. Also method 'heartbeat' doesn`t work. 
Tested on 
iphone 5,   ios: 10.2.1
iphone 4s, ios: 9.3
