### ISSUE TITLE
BackgroundGeoLocation error:1 occuring on iOS14.2

### ISSUE THREAD

**Issue by maswa** [transistorsoft/cordova-background-geolocation-lt#1200]
## Your Environment
* Plugin version:3.9.4
* Platform: iOS 
* OS version: 14.2
* Device manufacturer / model: iPhone XR 
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):6.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
// BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
		//desiredAccuracy: 0,
		//logLevel:bgGeo.LOG_LEVEL_VERBOSE,
	  	desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
		notificationTitle:'Tracking active',
		notificationText:'Background Tracking',
		distanceFilter: 10,
	  	stationaryRadius: 25,
		stopTimeout: 5,         // Change state to stationary after 1 min with device "still"
		desiredOdometerAccuracy :40,
        //stopOnTerminate: false, // Don't stop tracking when app is terminated.
	  	foregroundService: true,

		preventSuspend : true,
        debug: false  // <-- Debug sounds & notifications.

```

## Expected Behavior

Start app and give permissions without errors
## Actual Behavior

After a fresh installation of the app i get an error message : BackgroundGeoLocation error:1 . This error comes after the two permission popups from the OS , the first one to request for Allow once / While using app/ Don't allow and the second one to allow for 'Always' .  Right after that it shows the error message.  This occurs only on ios 14.2 , not on previous iOS versions.

Once permissons have been set i can close app and reopen and then i get no error message again.  When i reset the permissons to Ask next time , i get the error again when restarting the app.  So it looks like it has to do something with these permissions. 
Besides these error messages i notice no problems with the tracking itself. 
  
## Steps to Reproduce

1. Install app
2. Open app
3. Set permissions to While using app en then to Always
4. Error message appears. 

## Context

![image](https://user-images.githubusercontent.com/3632005/101024410-5b597580-3574-11eb-9068-50c46b76908b.png)

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
When having any kind of problem, the first step is to `logLevel:bgGeo.LOG_LEVEL_VERBOSE` and boot your app in XCode to observe the logs.

**Comment by christocracy** [comment]
I don't not experience any issue with fresh install of SampleApp on iOS 14.2, nor real *iPhone 12 Pro @ 14.2.1*.
