### ISSUE TITLE
Got too much locations as expected (every 3 sec)

### ISSUE THREAD

**Issue by klakto** [transistorsoft/cordova-background-geolocation-lt#1202]
Hello,

as you can see into my logs, there is too much 'motionchange LocationResult'.

1/ I've put `useSignificantChangesOnly: true` to try to space that but there is a location every 3s.
2/ I tried to not use in_vehicle but all my logs were during a car driving.

What's wrong with my config ?

* Plugin version: 3.9.2
* Platform: Android
* OS version: 11
* Device manufacturer / model: Pocophone
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): Current working directory is not a Cordova-based project, it's Capacitor
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
  url: myUrl,
  params: {
    "uId": this.uId,
  },
  headers: {
    'Content-Type':  'application/x-www-form-urlencoded',
    'Merchant-Token': environment.merchantToken,
    'Authorization': 'Basic [TOKEN]',
  },
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
  stopOnTerminate: false,
  startOnBoot: true,
  reset: true,
  useSignificantChangesOnly: true,
  triggerActivities: "on_foot, walking, running",
  locationAuthorizationRequest: 'Always',
  backgroundPermissionRationale: {
    title: "access into background",
    message: "please select always",
    positiveAction: 'change into always',
    negativeAction: "close"
  },
  locationAuthorizationAlert: {
    titleWhenNotEnabled: "no good",
    titleWhenOff       : "disabled",
    instructions       : "please enable",
    cancelButton       : "close",
    settingsButton     : "settings"
  },
  enableHeadless: true,
  notification: {
    sticky: true,
    title: "Background tracking test title",
    text: "Background tracking test text",
    priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
  }
}
```

## Steps to Reproduce
Take the car then get the logs after

**Comment by christocracy** [comment]
You likely have another app which is aggressively tracking location (eg: Google map route, jogging app, mock location app).  Locations recorded by another app are delivered to *all* apps on the device free of "battery blame".

See API docs `Config.fastestLocationUpdateInterval` to control the rate of incoming locations from *other* apps.

**Comment by klakto** [comment]
Aww ok !
I make my tests with Lockito.

And is it possible to use `disableMotionActivityUpdates: true` with that config ?

**Comment by christocracy** [comment]
You're free to adjust the Config however you wish, after reading the api docs.
