### ISSUE TITLE
SetConfig not working as expected

### ISSUE THREAD

**Issue by guptavip** [transistorsoft/cordova-background-geolocation-lt#1204]
## Your Environment
* Plugin version:3.9.4
* Platform: iOS 
* OS version:12.4.8
* Device manufacturer / model:IPhone SE (Simulator)
* Cordova version (`cordova -v`):9.0.0
* Cordova platform version (`cordova platform ls`):5.1.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
 BackgroundGeolocation.ready({
      // Logging / Debug config
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // Geolocation config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,  // <-- highest possible accuracy
      distanceFilter: 10,
      // ActivityRecognition config
      stopTimeout: 1,
      // Application config
      stopOnTerminate: false,
      startOnBoot: true,
      heartbeatInterval: 60,
      // [Android] backgroundPermissionRationale for Always permission.
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      **params: {               // <-- Optional HTTP params
        UserId: '0'
      
      },**
      // HTTP / Persistence config
      url: '$SERVER URL$',
     
      autoSync: true,
      autoSyncThreshold: 0
    }, (state) => {
      console.log('- BackgroundGeolocation ready: ', state);
      // Set current plugin state upon our view.
      this.zone.run(() => {
       
      });
    });
```

## Expected Behavior
On a specific event Value in param field is changed.
After App is killed updated SetConfig value should be preserved

## Actual Behavior
As soon as app is killed and plugin is restarted initial config param value is sent to server instead of updated value

## Steps to Reproduce

1. in Simple map html add another setting button as 
       <ion-item>
				<button ion-button full round color="primary" (click)="setAnotherConfig()"><ion-icon name="home"></ion-icon>&nbsp;AnotherConfig</button>
			  </ion-item>
			<ion-item>
2. Create handler in ts file for the same
setAnotherConfig()
{
  BackgroundGeolocation.setConfig(  {params: {               // <-- Optional HTTP params
    UserId: '29'  
  }}, (state) => {
    console.log(state);

})
3. run the program on IOS.
4. as soon as location tracing started param value 0 is received on server==>OK
5.  click on the newly created button to update param value
6. In next call at server param value received is 29 ==> OK
7. until and unless the program is running value at server is 29.==> OK
8. Kill app and wait plugin to reinitialize itself.
9. Plugin reinitialized and calles at server received again ==> OK
10. Now Param value at server is 0 again ==> Not Ok.
11. Stimulate same behavior in Android==> step 1 to 10 worked as expected and after killing the app new value is got at the server

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You may either:
1.  Store your `Userid` in `localStorage` and provide that to the `.ready()` method.
2. Configure the plugin with `reset: false`.  Beware of this option:  your config supplied to `.ready` will be applied **ONLY AT FIRST INSTALL OF THE APP**.  If you change config supplied to `.ready` during development, it will be ignored.  Config changed with `setConfig` will always persist.

**Comment by guptavip** [comment]
Hi @christocracy ,
Currently plugin is not behaving like this.
I have reproduce this in Your sample app it self.
SetConfig option is not preserved in case of IOS.
I have used 2 nd option you have suggested.

**Comment by christocracy** [comment]
The Sample App *Advanced App* **absolutely, 100% does** preserve the config controlled by the Settings screen.
