### ISSUE TITLE
iOS 14.3 issue with activity_type

### ISSUE THREAD

**Issue by monkeydkon** [transistorsoft/cordova-background-geolocation-lt#1206]
## Your Environment
* Plugin version: 3.9.2
* Platform: iOS or Android iOS
* OS version: 14.3
* Device manufacturer / model: apple 
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

When the user has the tracking on, locations with all the data must be returned

## Actual Behavior

The plugin acts as if the "Motion & Fitness" is off, but it's on. Almost all of the locations have: activity_type: 'unknown'. This started with the latest iOS version (14.3).

I currently don't have logs. I will be able to post logs at the night. But I'm posting this because it's really urgent.

## Steps to Reproduce

1. Use the geolocation with and older iOS version
2. Try with 14.3 version
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I upgraded to *iOS 14.3* yesterday and took a walk.  I see no issue with *activity*.

![](https://dl.dropbox.com/s/x30nuisjuomrs7k/Screen%20Shot%202020-12-18%20at%2010.26.51%20AM.png?dl=1)
![](https://dl.dropbox.com/s/mcj1zh877xtuh7f/Screen%20Shot%202020-12-18%20at%2010.28.21%20AM.png?dl=1)

**Comment by monkeydkon** [comment]
Maybe I'm wrong but I'm trying to understand what is going on. Because this is an issue i haven't had all this time. I also notice that the battery level is "-1" for all the "unknown" activity_types. Has this ever occured to you? Does it mean something?

![image](https://user-images.githubusercontent.com/32495550/102634111-0fa0f180-415a-11eb-931b-5d0a7e4df1e6.png)

**Comment by monkeydkon** [comment]
iOS Simulator?
You mean the were ran via XCode?
This is not the case, if that's what you mean.

**Comment by christocracy** [comment]
I don't know what could be the problem.  My *iPhone 12 Pro @ 14.3* shown nothing unusual with *battery* or *motion activity*.  Restart the device.

**Comment by christocracy** [comment]
Of course, *Motion Activity* requires the user enable *Health & Fitness* runtime permission.

**Comment by monkeydkon** [comment]
Do you mean "Motion & Fitness"?
Or is it the same? Because it's open on the devices with this problem..

**Comment by christocracy** [comment]
I do not know what could be the problem.

![](https://dl.dropbox.com/s/fgz3qyf3vni89yh/Screen%20Shot%202020-12-18%20at%2011.11.17%20AM.png?dl=1)

**Comment by monkeydkon** [comment]
Maybe updating via TestFlight is the problem? This is where the clients test the application.. Maybe the option doesn't really persist even if it is on...
I don't know.. Thanks for the help anyway

**Comment by monkeydkon** [comment]
I'm back at this issue. It seems that this happens when the app is in the background only. If it's in foreground everything is recorded correctly.

**Comment by christocracy** [comment]
I am not experiencing any issues with recorded `activity` while running in the background on my *iPhone 12 Pro @ iOS 14.3*.

**Comment by monkeydkon** [comment]
Is there a chance this could happen if I'm not calling `.ready()` for every time the app launches?

**Comment by christocracy** [comment]
No idea.  You *must* ensure your app calls `.ready` *each and every time your app launches*, **no matter what**.

**Comment by monkeydkon** [comment]
Okay, I'll try it and update.

**Comment by monkeydkon** [comment]
This issue happens only on iphone and only when the app is killed.
If it's just at the background it's okay.
My app is Vue.js and I'm calling the ready function at the main.js file which is the first js file that runs.

`geo.ready({
  distanceFilter: 5,
  allowIdenticalLocations: true,
  stopOnTerminate: false,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  debug: false,
  url: `${process.env.VUE_APP_BASE_URL}/traveller/geo/postLocations`,
  autoSync: true,
  httpRootProperty: 'locations',
  headers: {
    'authorization': `${axios.defaults.headers.common['Authorization']}`
  },
  startOnBoot: true,
  stationaryRadius: 25,
  locationAuthorizationRequest: "Always",
  showsBackgroundLocationIndicator: true,
  preventSuspend: true,
  locationAuthorizationAlert: {
    titleWhenNotEnabled: "Location-services not enabled",
    titleWhenOff: "Location-services OFF",
    instructions: "You must enable 'Always' in location-services.",
    cancelButton: "Cancel",
    settingsButton: "Settings"
  },
  backgroundPermissionRationale: {
    title: "Allow access to this device's location in the background?",
    message: "In order to allow X, Y and Z, please enable 'Allow all the time permission",
    positiveAction: "Change to Allow all the time"
  },
  notification: {
    title: "Moby app",
    text: "tracking is on"
  }
}, (res) => {
  console.log("THIS IS FROM THE MAIN FILE")
});`
