### ISSUE TITLE
setTimeout on BackgroundGeolocation.getCurrentPosition

### ISSUE THREAD

**Issue by natali93ale** [transistorsoft/cordova-background-geolocation-lt#1212]
## Your Environment
* Plugin version: 3.9.4
* Platform: iOS 6.1.1  Android 9.0.0
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`: timeout: 30, maximumAge: 5000, desiredAccuracy: 10 
```javascript <!-- syntax-highlighting:  paste your code below -->
document.addEventListener("deviceready", () => {
    BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
    }).then((state) => {
        console.log("[ready] success", state);
        if (!state.enabled) {
            BackgroundGeolocation.start();
            setTimeout(() => {
                sendGpsTecnico();
            }, 15 * 60 * 1000);
        }
    });
}, false);

function sendGpsTecnico() {
    BackgroundGeolocation.getCurrentPosition({
        timeout: 30,          // 30 second timeout to fetch location
        maximumAge: 5000,     // Accept the last-known-location if not older than 5000 ms
        desiredAccuracy: 10   // Try to fetch a location with an accuracy of `10` meters
    }, onBGpsSuccess, onGpsError);

    setTimeout("sendGpsTecnico()", 15 * 60 * 1000); 
    return false;
}

```

## Expected Behavior

I am trying this on iOS 13.4.1 because on platform Android the app gives error: "the program Appname was stopped" when I run it on debug and it doesn't provide any error on log... ( Can you help me on this in some way, the package doesn't have AndroidX installed )
The getCurrentPosition function should be called every 15 minutes and get the position.

## Actual Behavior

When the app is opened, the current position is called correctly. But while the app is in background it is not working anymore.

## Steps to Reproduce

1. Open the app
2. Call the BackgroundGeolocation.ready({})
3. On then callback execute setTimeout on sendGpsTecnico()
4.

## Context

I am trying to track the position of an agent going around every "n" minutes, where the "n" parameter is defined by the person in charge of the agents.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You cannot use `setTimeout` like this to execute code every 15 minutes.  It will *never ever* work.

If you want periodic wakeups to execute `getCurrentPosition`, your best option is to use [`cordova-plugin-background-fetch`](https://github.com/transistorsoft/cordova-plugin-background-fetch), already included as a dependency.

**Comment by natali93ale** [comment]
Hi, thanks for the answer.
Now I am using the cordova-plugin-background-fetch like it follows:
    var fetchCallback = function(taskId) {
        console.log(new Date() + '[js] BackgroundFetch event received: ', taskId);
        sendGpsTecnico();
        BackgroundFetch.finish(taskId);
    };
    
    var failureCallback = function(error) {
        console.log('- BackgroundFetch failed', error);
    };
    
    BackgroundFetch.configure(fetchCallback, failureCallback, {
        minimumFetchInterval: 15 // <-- default is 15
    });

It is working well on Android.
While on iOS it is not working, no console.log or console.error is returned.
But if I call BackgroundFetch.status((status)=>{console.log(status)}); it returns me 2 that means "Available" in the guide.
Do you have any suggestions?

**Comment by christocracy** [comment]
Are you *simulating* a fetch event as described in the readme?

**Comment by natali93ale** [comment]
Yes I called the function

    BackgroundFetch.configure(fetchCallback, failureCallback, {
        minimumFetchInterval: 15 // <-- default is 15
    });

Inside the document.addEventListener("deviceready", () => {});
The only thing I added is the sendGpsTecnico() inside fetchCallback function that runs the getCurrentPosition function ( as you can see in the previous message ).

**Comment by christocracy** [comment]
>Yes I called the function

I asked **are you simulating** a fetch event as described in the README?  With XCode.

**Comment by natali93ale** [comment]
I executed this from Xcode following the guide and it seems working

    e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.fetch"]
    
    2021-01-05 17:32:05.213800+0100 Assist[2871:1051986] Simulating launch for task with identifier com.transistorsoft.fetch
    2021-01-05 17:32:07.900131+0100 Assist[2871:1053472] Starting simulated task: <BGAppRefreshTask: com.transistorsoft.fetch>
    2021-01-05 17:32:07.900941+0100 Assist[2871:1053472] [TSBackgroundFetch handleBGAppRefreshTask]
    2021-01-05 17:32:07.901716+0100 Assist[2871:1053472] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
    2021-01-05 17:32:07.929328+0100 Assist[2871:1051986] [CDVBackgroundFetch event] taskId: cordova-background-fetch
    2021-01-05 17:32:07.936567+0100 Assist[2871:1051986] Tue Jan 05 2021 17:32:07 GMT+0100 (CET)[js] BackgroundFetch event received:  cordova-background-fetch
    2021-01-05 17:32:07.937575+0100 Assist[2871:1051986] sendGpsTecnico
    2021-01-05 17:32:07.938328+0100 Assist[2871:1051986] [TSBackgroundFetch finish] cordova-background-fetch (1 of 1)
    2021-01-05 17:32:07.938569+0100 Assist[2871:1051986] Marking simulated task complete: <BGAppRefreshTask: com.transistorsoft.fetch>
    2021-01-05 17:32:07.975059+0100 Assist[2871:1051986] onGpsSuccess
    2021-01-05 17:32:08.793925+0100 Assist[2871:1051986] 200

Anyway if I call start function it returns me success. It looks like configure it is not calling start itself.

**Comment by christocracy** [comment]
>It looks like configure it is not calling start itself.

Calling `#configure` *automatically* starts the plugin, by default.

**Comment by natali93ale** [comment]
Yeah I read it on the README but as I said before on Android is working fine while on iOS it is not starting alone.
Moreover I noticed that

    BackgroundFetch.start((s)=>{console.log("success: "+s)}, (e)=>{console.log(e)})

is returning "success: null", and it is not returning one of the two following

    var fetchCallback = function(taskId) {
        console.log(new Date() + '[js] BackgroundFetch event received: ', taskId);
        sendGpsTecnico();
        BackgroundFetch.finish(taskId);
    };
    var failureCallback = function(error) {
        console.log('- BackgroundFetch failed', error);
    };

that are in the 

    BackgroundFetch.configure(fetchCallback, failureCallback, {
        minimumFetchInterval: 15 // <-- default is 15
    });

Can I send you some more information to help you understand the problem?

**Comment by natali93ale** [comment]
Good morning Chris Scott,
Do you have some news for me?
