### ISSUE TITLE
iOS Background Location - when app is in background for a long time

### ISSUE THREAD

**Issue by moshikh** [transistorsoft/cordova-background-geolocation-lt#1213]
## Your Environment
* Plugin version: 3.9.4
* Platform: iOS or Android
* OS version: iOS
* Device manufacturer / model: iPhone 12 / 11 / 8
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 9.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
     reset: true,
     debug: false,
     logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
     desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
     distanceFilter: 50,
     locationAuthorizationRequest: 'Always',
     url: '------------------------',
     autoSync: true,
     stopOnTerminate: false,
     startOnBoot: true,
     preventSuspend: true,
     heartbeatInterval: 60,  // <-- every minute
     fastestLocationUpdateInterval: 30000,
     locationAuthorizationAlert: {
          titleWhenNotEnabled: '--------',
          titleWhenOff: '--------',
          instructions: '-------',
          cancelButton: '---',
          settingsButton: '----'
     },
     headers: {
          authorization: 'Bearer ' + this.accessToken
     },
     extras: {
          userName: this.currentUser.fullName,
          uid: this.currentUser.uid
     },
     params: {
          uid: this.currentUser.uid
     },
}, (state) => {
     console.log('[BACKGROUND LOCATION][INFO] - BackgroundGeolocation is ready to use');
     if (!state.enabled) {
          // 3.  Start tracking.
          BackgroundGeolocation.start();
          this.tracking = true;
     }
});
```

## Expected Behavior

the location should be fired to the server continuously, even if the app is in the background or closed and if the phone is untouched for a long time 
## Actual Behavior

after an hour or so that everything works as expected and when the phone is closed and untouched the plugin caches the location for as long as the phone closed and only when you re-open the app all the locations is fired to the server one after another.

## Steps to Reproduce

1. create new app
2. install the plugin
3.use my config
4.

## Context

* tried to use startBackgroundTask but it was crashed on Android(different issue), and it wasnt fix it anyways.
* uninstall / install the plug in
- I am not sure if i use the `url` field (built in HTTP), should it handle all the background stuff by itself?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The only thing you need to do is `stopOnTerminate: false`, `startOnBoot: true`.

I've been field-testing the iOS plugin nearly every day for over 6 years.  It never fails.

- See Wiki *Debugging*.  Enable verbose logging and fetch logs from the plugin.
- Ensure your app is **always** calling `.ready()` each time your app boots, **no matter what**.

**Comment by moshikh** [comment]
Thank you for your quickest reply.
As a rule of thumb... if i am setting stopOnTerminate: false, startOnBoot: true as i did and set the url with my api endpoint, it should work for as long as he phone is working? one doesn't need to handle startBackgroundTask?

also,  should I call ready if my app is resume back from pause? or only when it freshly loaded?

**Comment by christocracy** [comment]
>or only when it freshly loaded?

Each time the app is freshly launched.

>and set the url with my api endpoint, it should work for as long as he phone is working? 

yes.

>one doesn't need to handle startBackgroundTask?

No.

**Comment by monkeydkon** [comment]
I'm kinda having the same problem. I'm turning my "geolocation" via a button on my app. So, when the user clicks the button this happens:

1. `.ready()` is called
2. `.start()` is called

You are saying that `.ready()` should be called for every launch of the app. Should I be doing the same for `.start()` too?

**Comment by christocracy** [comment]
If the plugin were a stereo receiver:
- `.ready()` = plugging the AC cord.
- .`start()` = toggling the power switch ON.
- `.stop()` = toggling the power switch OFF.

Calling `.ready()` does not imply "start tracking", just as plugging in the power to your stereo receiver does not imply turning it on.  `.ready()` is a signal to the plugin that your Javascript app is launched and the plugin can now start emitting events to your event-listeners.

You do not call `.ready()` in a button listener when you're ready to start tracking.  You must need to call `.start()`.  

The plugin maintains its enabled state throughout app restarts / device reboots.  Once the plugin is `.start()`ed, it is *always* enabled until you call `.stop()`.
