### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by moshikh** [transistorsoft/cordova-background-geolocation-lt#1214]
## Your Environment
* Plugin version: 3.9.4
* Platform: iOS or Android
* OS version: Android
* Device manufacturer / model:  Samsung s9
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 9.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
     reset: true,
     debug: false,
     logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
     desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
     distanceFilter: 50,
     locationAuthorizationRequest: 'Always',
     url: '------------------------',
     autoSync: true,
     stopOnTerminate: false,
     startOnBoot: true,
     preventSuspend: true,
     heartbeatInterval: 60,  // <-- every minute
     fastestLocationUpdateInterval: 30000,
     locationAuthorizationAlert: {
          titleWhenNotEnabled: '--------',
          titleWhenOff: '--------',
          instructions: '-------',
          cancelButton: '---',
          settingsButton: '----'
     },
     headers: {
          authorization: 'Bearer ' + this.accessToken
     },
     extras: {
          userName: this.currentUser.fullName,
          uid: this.currentUser.uid
     },
     params: {
          uid: this.currentUser.uid
     },
}, (state) => {
     console.log('[BACKGROUND LOCATION][INFO] - BackgroundGeolocation is ready to use');
     if (!state.enabled) {
          // 3.  Start tracking.
          BackgroundGeolocation.start();
          this.tracking = true;
     }
});
```

## Expected Behavior

clean build
## Actual Behavior

when i build the app without changing the version in platforms/android i get:
Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 10.+

if i am changing play-service-location to 10+ the build was finished ok but the app crashed with: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent
these are the versions in project.properties 
```javascript <!-- syntax-highlighting:  paste your code below -->
target=android-29
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/driver-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:16.+
cordova.system.library.2=androidx.appcompat:appcompat:1.2.0
cordova.system.library.3=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.4=org.greenrobot:eventbus:3.0.0
cordova.system.library.5=com.intentfilter:android-permissions:0.1.8
cordova.system.library.6=org.slf4j:slf4j-api:1.7.25
cordova.system.library.7=com.github.tony19:logback-android:2.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/driver-build.gradle
cordova.system.library.8=androidx.legacy:legacy-support-v4:1.0.0
cordova.system.library.9=com.google.firebase:firebase-core:10.+
cordova.system.library.10=com.google.firebase:firebase-messaging:10.+
cordova.gradle.include.3=cordova-plugin-fcm-with-dependecy-updated/driver-FCMPlugin.gradle
```
## Steps to Reproduce

1. create new app
2. install the plugin
3. use FCM and firebase@latest
4.use my config

## Context

* uninstall / install the plug in
*  AndroidXEnabled added to config.xml + adapter installed

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>if i am changing play-service-location to 10+

You can't use v10.  You always want to use the latest available version of play-services-location.  That version is [17.1.0](https://maven.google.com/web/index.html#com.google.android.gms:play-services-location)

Check all your `com.google.firebase` dependencies and ensure *those* are using the latest available version.  See http://maven.google.com
