### ISSUE TITLE
Geolocation in the background stops reporting after a certain time has elapsed

### ISSUE THREAD

**Issue by DannyCaldeira24** [transistorsoft/cordova-background-geolocation-lt#1218]
## Your Environment
* Plugin version: 3.9.4
* Platform: Android
* OS version: Android 10
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):  android ^9.0.0 
* Plugin config provided to `#ready`:
*     reset: false,
      debug: debug,
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: this._translateService.Traductor('BACKGROUND_GEOLOCATION.ALLOW_ACCESS'),
        message: this._translateService.Traductor('BACKGROUND_GEOLOCATION.MESSAGE'),
        positiveAction: this._translateService.Traductor('BACKGROUND_GEOLOCATION.ACCEPT'),
        negativeAction: this._translateService.Traductor('BACKGROUND_GEOLOCATION.CANCEL')
      },
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: distance,
      stopTimeout: 20,
      stopOnTerminate: false,
      startOnBoot: true,
      stationaryRadius: 25,
      enableHeadless: true,
      encrypt: true,
      autoSync: true,
      maxDaysToPersist: 14,
* 

## Expected Behavior

Geolocation in the background should always be maintained, once the user starts the application for the first time
## Actual Behavior

Background geolocation works in the foreground and background for a limited amount of time, but at some point and without knowing why tracking stops. The application has the automatic start permission but still the problem persists

</details>

**Comment by DannyCaldeira24** [comment]
> What device model / manufacturer?
>  The problem has occurred in a Samsung Galaxy Note 9 that we have followed up, but we do not know if the problem can occur in other devices.
> > encrypt: true,
> 
> This feature is removed in the next release. Do not use it. Ok

**Comment by christocracy** [comment]
see http://dontkillmyapp.com

**Comment by Murod772** [comment]
> > What device model / manufacturer?
> > The problem has occurred in a Samsung Galaxy Note 9 that we have followed up, but we do not know if the problem can occur in other devices.
> > > encrypt: true,
> > 
> > 
> > This feature is removed in the next release. Do not use it. Ok

Have you solved this problem?
