### ISSUE TITLE
How to Change GeoFence notification message?

### ISSUE THREAD

**Issue by kartiksolanki** [transistorsoft/cordova-background-geolocation-lt#1219]
Great plugin. Planning to purchase the license for Android. Keep up the good work. So i have couple of question not the errors but general ones. First of all, I am only planning to use only GeoFence for now in my Ionic 5 Angular app. I am not sure about the flow of the methods. I tried reading the API document as well but I am confused. 

1. So basically which methods are called in sequence? 

As per my understanding  when platform is ready, we call "configureBackgroundGeolocation" method. Inside that function, I have "BackgroundGeolocation.ready" which configures my plugin state and after that configuration is done, I get the "state" in return as a promise. If the state.enabled is true, that means my plugin is up and ready and if it is false, I can start my plugin again by calling "BackgroundGeolocation.startGeofences();" ????

Secondly, after the plugin gets ready by config, I am doing "BackgroundGeolocation.addGeofence" which basically puts my geofence data into database. This step does not emit anything or any functionality.

And lastly, when we call "BackgroundGeolocation.onGeofence", thats when my app listens to the added geofence data and will initiate the notification for the GeoFence, I have added.  

Is that the correct flow of functions running for GeoFencing???? I have followed the above sequence, and I am getting notification of my added GeoFence data but I just want to make sure, I am using it correcly.

2. When I receive the geofence notification upon entry or exit, I get my notification as "(icon) ENTER Geofence: My Custom Message inside Identifier". Is there any way to customize that notification tray message? For example, I want to remove the speaker icon and ENTER Geofence prefix. 

Also, when my app is closed, I also get notification as "Background Fetched" which I understand is for development mode to make sure, the plugin is active in the background. But how do I remove those development notifications? Like "Location On","Location Off", "SPID: xxx" etc.

Once again, this is my general queries for better understanding of this plugin. This plugin is amazing btw. Keep up the good work!

**Comment by christocracy** [comment]
>So basically which methods are called in sequence?

The sequence is [here](https://github.com/transistorsoft/cordova-background-geolocation-lt#ionic-2-with-typescript) in the README.

Typically, one won't call `.start()` (or `.startGeofences()`) in the callback to `.ready()`.  That's just a simple example.  Typically one would `.start()` from a UI button or some other action.  You must *always* call `.ready()` whenever your app launches.  The plugin maintains its state internally.  Once `.start()` (or `.startGeofences()` is called, `state.enabled` will be true, regardless if app is terminated or device rebooted.  The *only* way `state.enabled` becomes `false` is via `.stop()`.

>Secondly, after the plugin gets ready by config, I am doing "BackgroundGeolocation.addGeofence

You can `addGeofence` before calling `.ready()`.  However, once a geofence is added, the plugin stores those in its own SQLite database.  You do no need to re-add them each time your app launches.  The only way a geofence stops being monitored is by calling `removeGeofence(identifier)` / `removeGeofences` or `.stop()`.

Think of the plugin as an electronic device, such as a stereo receiver:
- `.ready()` => pluggin in AC cord.
- `.start` / `.stop()` => power button
- Subscribing to events (eg: `onGeofence`, `onLocation`, etc) => wiring up speakers.

>When I receive the geofence notification upon entry or exit, I get my notification as "(icon) ENTER Geofence: My Custom Message inside Identifier". Is there any way to customize that notification tray message?

Those messages exist only for debugging purposes.  They are enabled by configuring `debug: true`.  They are not a part of the plugin's core API.  You are responsible for showing your own local-notifications to the user with your own code app code and 3rd party plugin specializing in local-notifications.

>But how do I remove those development notifications?

`debug: false`.  Those messages are there to assist you during development and field-testing only.  You will not be releasing an app with `debug: true`.
