### ISSUE TITLE
Cordova android build issue

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1221]
![image](https://user-images.githubusercontent.com/40283671/105692320-4837a600-5f24-11eb-8318-8970abef8e0a.png)

following issue occur when take android build once key added in config.xml file

**Comment by christocracy** [comment]
Do **not** ignore the issue template.


*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Ambikapathi** [comment]
![image](https://user-images.githubusercontent.com/40283671/105702574-ff86e980-5f31-11eb-9143-58c612ef2f10.png)


![image](https://user-images.githubusercontent.com/40283671/105702730-3957f000-5f32-11eb-93aa-89b59f2743d7.png)

**Comment by christocracy** [comment]
Edit your issue to provide the information requested in the issue template.

I do not waste time on reading issues where the issue template is ignored.

**Comment by christocracy** [comment]
and please don't post *screenshots* -- post *text*.

**Comment by Ambikapathi** [comment]
I had installed plugin one week ago, Initially it's worked perfectly. Once i change config debug=false for testing purpose to remove that beep sound. after i changed to that config, i worked as i expected, Today i go to show my app to manager, Suddently it stopped working. After i reviewed my code  testing key has gone in config.xml file. So i added test key in my app, i will gives build error in cordova app. error already i posted.Kindly help me to solve this error.

**Comment by christocracy** [comment]
You are not following instructions.

Do **not** ignore the issue template.


*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Ambikapathi** [comment]
Issue cleared after adding this line in confic.xml xmlns:android="http://schemas.android.com/apk/res/android"

**Comment by christocracy** [comment]
As documented in the [*Configuring the Plugin*](https://github.com/transistorsoft/cordova-background-geolocation-lt#android) section of the README.

Close your own issues when solved and **never** ignore the issue template.
