### ISSUE TITLE
Async dynamic headers

### ISSUE THREAD

**Issue by grodriguez85** [transistorsoft/cordova-background-geolocation-lt#1224]
## Your Environment
* Plugin version: 3.9.x
* Platform: Both
* OS version: Any
* Device manufacturer / model: Any
* Cordova version (`cordova -v`): Any
* Cordova platform version (`cordova platform ls`): Not relevant

## New Useful Behavior
Add support for an async function instead of an object on the header option of the configuration. I use aws-amplify for authentication and the token sent on headers when expired should be refreshed. I extend fetch requests to get the session first; getting the session on amplify (or firebase-auth for example) waits for a new token if expired, and is a good practice to get the session before each request to avoid race conditions when manually refreshing after it already expires.

Unfortunately with the actual configuration is impossible to set dynamic headers for authenticated servers. I can update the configured headers after a new token is issued but I will have a race condition. If the request fails the addon would eventually try to sync it again, so the race condition isn't that bad. But nonetheless it would be a great feature to accept async functions on the header option. But this requests are run on background, and sometimes with our app not even running, so can this function still run with the binded context of the app?

## Actual Behavior
The headers object is static and should be generated beforehand and added during initial or subsequent configurations

**Comment by christocracy** [comment]
I don't think this is going to happen.  Far too complex to have this type of communication back-and-forth from native->javascript->native, particularly in the Android *Headless* case, where your Javascript app is terminated.

**Comment by grodriguez85** [comment]
I can't imagine, thanks @christocracy for the quick response. I didn't see the authorization option, that solves my issue.

**Comment by darrensapalo** [comment]
The authorization option that @grodriguez85 is mentioning is the one that @christocracy mentions [here](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1217#issuecomment-763007332). 

# References

* API docs for [Config.transistorAuthorizationToken](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#transistorauthorizationtoken)
* API docs for [refresh token authentication](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.authorization.html)

**Comment by christocracy** [comment]
@darrensapalo Note that `Config.transistorAuthorizationToken` is for **development-use only**.  That Config is used only for authenticating with http://tracker.transistorsoft.com.
