### ISSUE TITLE
Missing $BACKGROUND_MODE_LOCATION

### ISSUE THREAD

**Issue by riderx** [transistorsoft/cordova-background-geolocation-lt#1225]
## Your Environment
* Plugin version: latest
* Platform: iOS 
* OS version: 14
* Device manufacturer / model: iphone 12
* Cordova version (`cordova -v`): capacitor 2.4.6
* Plugin config provided to `#ready`:
```
[warn] Plugin cordova-background-geolocation-lt might require you to add 
                $BACKGROUND_MODE_LOCATION
```

## Expected Behavior
No warning message

## Actual Behavior
when i do `cap sync ios` i got tis warning :
<img width="944" alt="Screenshot 2021-02-03 at 13 43 06" src="https://user-images.githubusercontent.com/4084527/106755216-25954380-662e-11eb-9df9-22bc6f464f05.png">

so tried to add as said :
<img width="595" alt="Screenshot 2021-02-03 at 13 40 42" src="https://user-images.githubusercontent.com/4084527/106755089-01396700-662e-11eb-8988-ec773bca5318.png">
But even if with this, i still get the warning when i run sync again.

Do you have any clue why ?
it look i do something wrong but not sure what !

## Context
I try to install your plugin on capacitor

**Comment by christocracy** [comment]
This message does not come from `background-geolocation`.  I must be coming from one of your *other* plugins.

Open your app in XCode and observe the *Signing & Capabilities -> Background Modes* section.  It should look like this:

![](https://dl.dropbox.com/s/fhpekriifqswzaq/Screen%20Shot%202021-02-03%20at%208.50.30%20AM.png?dl=1)

**Comment by christocracy** [comment]
Did you follow the *Capacitor Setup* instructions in the README?

![](https://dl.dropbox.com/s/rjgqf7b1jydejmp/Screen%20Shot%202021-02-03%20at%208.54.40%20AM.png?dl=1)

**Comment by riderx** [comment]
@christocracy thanks for the quick reply, i followed the doc in your module, and this is a fresh start app from blank with only your module, maybe that not working with latest capacitor `2.4.6` ?

**Comment by christocracy** [comment]
Have you opened your app in XCode to verify the Background Capabilities are set according to my screenshot above.

I'm sure the plugin works in latest Capacitor.  Have you tried it?

**Comment by riderx** [comment]
Yes i have the same :)
<img width="848" alt="Screenshot 2021-02-09 at 22 27 52" src="https://user-images.githubusercontent.com/4084527/107436904-77f2ca80-6b2e-11eb-931f-bfe5ef840de8.png">
I use your plugin since 5 years, in my old company You2you, i had many issue comming from my side, but i don't find a way to fix that one alone !

**Comment by christocracy** [comment]
Looks good to me.

**Comment by riderx** [comment]
@christocracy so i still have the issue !

**Comment by alexcroox** [comment]
I can confirm I too have the issue with Capacitor v3, having just installed everything fresh and up to date.

![image](https://user-images.githubusercontent.com/1065835/112478137-983bb900-8d6b-11eb-9702-e0bfe1875312.png)

![image](https://user-images.githubusercontent.com/1065835/112478156-9eca3080-8d6b-11eb-94e2-e0cb03f63e2d.png)

**Comment by alexcroox** [comment]
related to the encoding here maybe? https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/351bfc4986fe235868ffc6638205fb861fa03035/plugin.xml#L30

**Comment by christocracy** [comment]
Ignore.  Capacitor cannot handle these `<preference>` values and cannot automatically add the `UIBackgroundModes`.  Add ing the required `UIBackgroundModes` is detailed in the *Capacitor Setup*.
