### ISSUE TITLE
[Android] Turn off/silent notification

### ISSUE THREAD

**Issue by fgarcia5** [transistorsoft/cordova-background-geolocation-lt#1227]
## Your Environment
* Plugin version: **cordova-background-geolocation-lt 3.9.4 "BackgroundGeolocation"**
* Platform: **Android**
* Cordova version (`cordova -v`): **10.0.0**
* Cordova platform version (`cordova platform ls`): **android 9.0.0**

## Expected Behavior

I need to silence the local-notification that this plugin shows when the App runs in Background. The main reason is that I am already showing a local sticky notification "manually" with the plugin "cordova-plugin-local-notification" indicating to the user that an activity is taking place in Background.

Is there a way to do this configuration? I have read the documentation and searched the issues but couldn't find a way to do it.

A related question to this, what happens if the plugin is working in Background and a notification is not displayed? The OS kills the task?

Thank you in advance.

**Comment by christocracy** [comment]
No.  The plugin's magic on Android is achieved by use of *foreground services* -- *Android's foreground service requires a persistent notification while active.

**Comment by christocracy** [comment]
See the api docs Config.notification to learn the many ways of *configuring* the required notification.  Perhaps you can get rid of your existing custom notification instead.
