### ISSUE TITLE
ios 9.3.2

### ISSUE THREAD

**Issue by jojo69256** [transistorsoft/cordova-background-geolocation-lt#123]
Hello,
anyone having problems on ios 9.3.2?

I observe problems with getCurrentPosition or hearbeat, when app is in the background.
After it goes in the background and gps is turned off after update is obtained, it wont start again and app is put to sleep in a few minutes by iOS.

I've tried to set stopTimeout, preventSuspend, heartbeatInterval... without any luck.

Thank you for any help

**Comment by christocracy** [comment]
Have you disabled `[x] Location Updates`?  There is **certainly nothing** wrong with the plugin on 9.3.2.
![](https://www.dropbox.com/s/2m2y0pdmy4fqwdw/Screenshot%202016-05-29%2016.08.34.png?dl=1)

**Comment by jojo69256** [comment]
Thank you for your help.

The cause was I've used phonegap build with source="git" in my config.xml. This does not add required config strings. When changed to source="npm", works just fine.

Thank you for a great plugin and for your time
