### ISSUE TITLE
Is the ACTIVITY_RECOGNITION permission required for this plugin to work?

### ISSUE THREAD

**Issue by CodeWithOz** [transistorsoft/cordova-background-geolocation-lt#1230]
## Your Environment
* Plugin version: 3.6.2
* Platform: Android
* OS version: 11 (API level 30)
* Device manufacturer / model: Google Pixel 4XL emulator on Android Studio
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`): 9.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
            // Geolocation config
            desiredAccuracy: desiredAccuracy,
            stationaryRadius: 50,
            distanceFilter: distanceFilter,
            disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
            locationUpdateInterval: 5000,
            minimumActivityRecognitionConfidence: 80, // 0-100%.  Minimum activity-confidence for a state-change
            fastestLocationUpdateInterval: 5000,
            activityRecognitionInterval: 10000,
            stopTimeout: 0,
            stopOnTerminate: false,
            startOnBoot: true,
            locationAuthorizationRequest: 'Any',
            // Default is "Always".  This will force a prompt and take user to device settings for iOS,
            // if the current location settings do not match.  Options: "Always", "WhenInUse", or "Any"
            // Application config
            url: 'our-url',
            method: 'POST',
            batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        }
```

## Expected Behavior

I have 2 questions rather than a bug report.
- I would like to separate the physical activity permission request from the initialization of the plugin, how can I do this?
- If I remove the `ACTIVITY_RECOGNITION` permission entirely from my app (from the manifest), what functionalities of this plugin will be affected? As I understand it, that permission is for detecting changes in the user's motion state. I rely primarily on the `location` event. Is the `ACTIVITY_RECOGNITION` permission required for the `location` event?

## Actual Behavior

N/A, please see above.

## Steps to Reproduce

Not reporting a bug

## Context

I would like to either remove the `ACTIVITY_RECOGNITION` permission from my app, or decouple the request for this permission (i.e. the physical activity permission prompt) from the initialization of the plugin (so I can explicitly request this permission when I want to).

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It will trigger to the *moving* state much faster with *motion* permission but it uses a geofence around the stationary position as a fallback (in the same manner as iOS).

**Comment by CodeWithOz** [comment]
Thanks for explaining. Does this mean that for Android 10 and above (API level 29+), removing _both_ `ACCESS_BACKGROUND_LOCATION` and `ACTIVITY_RECOGNITION` will prevent the plugin from functioning properly? The  official Android docs say that the `ACCESS_BACKGROUND_LOCATION` perm is needed for any use of the geofencing API.

**Comment by CodeWithOz** [comment]
Also how about my question on decoupling the permission prompt for `ACTIVITY_RECOGNITION` from the initialization of the plugin? Thanks.

**Comment by christocracy** [comment]
Yes, you will likely have problems with geofences, try it.

Also see api docs Config.disableMotionActivityUpdates.
