### ISSUE TITLE
Documentation bug - inverted if statement

### ISSUE THREAD

**Issue by darrensapalo** [transistorsoft/cordova-background-geolocation-lt#1232]
The if statement in [the authorization documentation](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.authorization.html) is inverted.

## Your Environment

Irrelevant, as this is documentation.

## Expected Behavior

```
BackgroundGeolocation.onAuthorization((event) => {
  if (event.success === false) {
    console.log("[authorization] ERROR: ", event.error);
  } else {
    console.log("[authorization] SUCCESS: ", event.response);
  }
});
```

## Actual Behavior

```
BackgroundGeolocation.onAuthorization((event) => {
  if (event.success) {
    console.log("[authorization] ERROR: ", event.error);
  } else {
    console.log("[authorization] SUCCESS: ", event.response);
  }
});
```

## Steps to Reproduce

1. Visit [the authorization documentation](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.authorization.html)

## Context

Understand authentication.

I would make the pull request myself; I'm just not sure where the documentation is.

## Debug logs

Irrelevant.

**Comment by darrensapalo** [comment]
> I would make the pull request myself; I'm just not sure where the documentation is.

Nevermind; I found the document under `docs`.

**Comment by christocracy** [comment]
The docs are inside the [Typescript declarations](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/ionic/declarations/BackgroundGeolocation.d.ts#L608-L627)

I use [typedoc](https://typedoc.org/) to parse the Typescript declarations and auto-generate docs.

**Comment by darrensapalo** [comment]
I see. Thanks. I can revise.
