### ISSUE TITLE
correct access to jwt

### ISSUE THREAD

**Issue by monkeydkon** [transistorsoft/cordova-background-geolocation-lt#1234]
## Your Environment
* Plugin version: 3.9.4
* Platform: BOTH
* OS version:
* Device manufacturer / model:
* Capacitor version: 2.4.3

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
geo.ready({
  distanceFilter: 5,
  allowIdenticalLocations: true,
  stopOnTerminate: false,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  debug: false,
  url: `${process.env.VUE_APP_BASE_URL}/traveller/geo/postLocations`,
  autoSync: true,
  httpRootProperty: 'locations',
  headers: {
    'authorization': `${axios.defaults.headers.common['Authorization']}`
  },
  startOnBoot: true,
  stationaryRadius: 25,
  locationAuthorizationRequest: "Always",
  showsBackgroundLocationIndicator: true,
  preventSuspend: true,
  locationAuthorizationAlert: {
    titleWhenNotEnabled: "Location-services not enabled",
    titleWhenOff: "Location-services OFF",
    instructions: "You must enable 'Always' in location-services.",
    cancelButton: "Cancel",
    settingsButton: "Settings"
  },
  backgroundPermissionRationale: {
    title: "Allow access to this device's location in the background?",
    message: "In order to allow background geolocation, please enable 'Allow all the time permission",
    positiveAction: "Change to Allow all the time"
  },
  notification: {
    title: "Moby app",
    text: "tracking is on"
  }
}, (res) => {
  console.log("THIS IS FROM THE MAIN FILE")
});
```

## Expected Behavior

As you have told me, I should also be putting the `ready()` function, every time my app boots. In my specific situation, i call it in the main.js file, as I'm building a vue.js app. So when app is in background or killed, it should be the first thing to run and geolocation be working as expected
## Actual Behavior

What I think happens, is that when app is killed (or background), the ready() function cannot access the `axios` instance, and so all the POST location requests are not authenticated and they fail. How can I have access to that everytime? If I save it with the Storage capacitor plugin will it be ok? Do you happen to have an idea?
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Perhaps you're interested in `Config.authorization`

**Comment by monkeydkon** [comment]
I'm kinda confused to be honest.
Does the (in my case) main.js file run when app is in background? Or it only runs when the user launches the app?

I have a button, which when the user presses, the geolocation tracking starts.
Why would I need to call the ready function everytime the user launches the app? 

Can you help me a bit with the explanation?

I hope I'm clear. If I'm not please ask for further explanation. English is not my native language.

Thanks :)

**Comment by christocracy** [comment]
> Why would I need to call the ready function everytime the user launches the app?

You just do. If you don't, the plugin won't work.
