### ISSUE TITLE
Plugin runs very well with Android 11 but unfortunately crashes at irregular intervals with Android 8 & 9 

### ISSUE THREAD

**Issue by Till92921** [transistorsoft/cordova-background-geolocation-lt#1235]
## Your Environment
* Plugin version: "3.9.4"
* Platform: Android
* OS version:  8 & 9 and 11 
* Device:  Huawei P10 Lite (Android 8) &  Huawei P20 lite (Android 9) & Samsung Galaxy 20 (Android 11) 
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):
 Installed platforms: 
Available platforms:
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
```
// myConfig
BackgroundGeolocation.ready(
      {
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        disableElasticity: true,
        // disableMotionActivityUpdates: true,
        //foregroundService:  true,
        // locationAuthorizationRequest: 'Any',
        autoSyncThreshold: 0,
        stopOnTerminate: true,
        startOnBoot: false,
        url: "http://localhost:80", 
        autoSync: true,
        params: {
          foo: "bar",
        },
      },
(state) => {
        if (!state.enabled) {
          
        } else {
         
        }
      }
    );


// my start Method 
async start() {
    stopwatch.start();
    await BackgroundGeolocation.start();
    await this.startStopwatchFormatter();
  }

// my onLocation Method 
async onLocation(location: Location) {
  
      const currentPosition: GpsKordwithTime = {
        lat: location.coords.latitude,
        long: location.coords.longitude,
        time: location.timestamp,
      };

      this.gpsCoordinates.push(currentPosition);
       this.calcDistanceBetweenLastCoord();
      await this.calcTotalLengthOfDistance();
  }

```

## Expected Behavior

That the plugin runs as stable as it did with Android 11 (Galaxy 20) 

## Actual Behavior

With this code the plugin runs very well on my Galaxy S20 (Android 11). It does exactly what I expect. It records the GPS positions and stores them in an array, which I add up to get a total distance. 

------------------------------------

Issues with my Huawei test devices: 
Huawei P20 lite, Android 9
Huawei P10 Lite, Android 8

- I have to wait to get the first coordinate in the foreground before I can put the plugin in the background and it starts recording.  
- The plugin crashes irregularly when the app is running in the background. 

What do I need to do to make the plugin as stable on Android 8 and 9 as it is on my Android 11 device? 

On my Android 11 device (Galaxy 20), in addition to the GPS authorisation, I am also asked for my physical activity authorisation. 

On Android 8 and 9, I am only asked for GPS authorisation. 

I have already tested the commented out parameters in .ready({.....} without any particular success.  

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I regularly test on 11 Android devices:
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 11
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

>On my Android 11 device (Galaxy 20), in addition to the GPS authorisation, I am also asked for my physical activity authorisation.
>On Android 8 and 9, I am only asked for GPS authorisation.

[**Android 10** introduced run-time permission requirement for activity recognition](https://android-developers.googleblog.com/2019/11/privacy-protections-for-physical.html).  All versions previously get that permission free.

>What do I need to do to make the plugin as stable on Android 8 and 9 as it is on my Android 11 device?

See Wiki *Debugging*.  Gather logs.  Also see http://dontkillmyapp.com
