### ISSUE TITLE
The plugin does not work with the app completely in the background, that is, when I remove it from the running applications tab.

### ISSUE THREAD

**Issue by viniciusschneider** [transistorsoft/cordova-background-geolocation-lt#1236]
## Your Environment
* Plugin version: "^3.9.4"
* Platform: Android
* OS version: 10
* Device manufacturer / model: SM-A307GT/DS
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`):
Installed platforms: 
  android 9.0.0      
  ios 5.1.1
Available platforms: 
  browser ^6.0.0     
  electron ^1.0.0    
  windows ^7.0.0     
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

await this.platform.ready().then( async () => {
        await BackgroundGeolocation.ready({
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 50,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          locationAuthorizationRequest: 'Always',
          desiredOdometerAccuracy: 10
        }, (state) => {
          console.log('[ready] BackgroundGeolocation is ready to use');
          if (!state.enabled) {
            BackgroundGeolocation.start();
          }
        });   
});

BackgroundGeolocation.onLocation( async (location: any) => {
        
        let coords: any = localStorage.getItem('coords');

        if (coords) {
          coords = JSON.parse(coords);
          coords.push(location);
        } else {
          coords = [location];
        }

        coords = JSON.stringify(coords);

        localStorage.setItem('coords', coords);
});
```

## Expected Behavior

That the location is returned both with the app in the foreground and in the background (with the app busy or not in the task tab).

## Actual Behavior

The app works only in the foreground and in the background only when you keep it in the task tab.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Your onLocation event listener is uninteresting to me.

What's interesting is the Config you're providing to `.ready()`

**Comment by viniciusschneider** [comment]
Ok, but is this listener implementation correct?

Ready:
`await this.platform.ready().then( async () => {
        await BackgroundGeolocation.ready({
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 50,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          locationAuthorizationRequest: 'Always',
          desiredOdometerAccuracy: 10
        }, (state) => {
          console.log('[ready] BackgroundGeolocation is ready to use');
          if (!state.enabled) {
            BackgroundGeolocation.start();
          }
        });   
      });
`

**Comment by christocracy** [comment]
Event-listeners do not affect the behavior of the plugin, just as disconnecting a speaker from your stereo system doesn't affect the playing of music.

See the Wiki *Debugging*.  Gather logs from the plugin.

**Comment by christocracy** [comment]
Also, you're aware that your Cordova JavaScript app no longer exists when you terminate the App?  Your event-listeners no longer exist in the terminated state.

See wiki *Android Headless Mode*.

This is why the plugin has its own built-in HTTP service (`Config.url`), so the native code, which remains running "headless" after terminate, can continue uploading recorded locations to your server.

**Comment by christocracy** [comment]
You might be interested in the method `BackgroundGeolocation.getLocations()` (see api docs).

**Comment by viniciusschneider** [comment]
Ok, I was confusing some things but I will work on that, thank you very much for your attention!
