### ISSUE TITLE
does not show the message  backgroundPermissionRationale Android V11

### ISSUE THREAD

**Issue by mba3** [transistorsoft/cordova-background-geolocation-lt#1238]
does not show the message  backgroundPermissionRationale

 
as seen in the captures it does not show the message backgroundPermissionRationale

Video Google play Console: https://vimeo.com/519693962/085ba75a64

**cordova-background-geolocation-lt 3.10.0**

**4 times the APP is rejected**
//// COdigo /////
`

> 

 bgGeo.ready({

        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title: "Permitir el acceso a la ubicación de este dispositivo en segundo plano?",
          message: "Esta aplicación recopila datos de ubicación para permitir reportar la ubicación del usuario vendedor y calcular la distancia recorrida.",
          positiveAction: "Cambiar a Permitir todo el tiempo ",
          negativeAction: "Cancel"
        },
        reset: true,
        //  debug: true,
        logLevel: bgGeo.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        url: localStorage.ip_mba + "/mbamovil/movil_act?vSesion=" + localStorage.sesion_mba,
        method: 'POST',
        autoSync: true,
        batchSync: true,
        maxDaysToPersist: 30,
        maxRecordsToPersist: 500,
        logLevel: 0,
        extras: {
            emp_id: localStorage.id_emp_mba,
            device_id: device.uuid,
            user_id: localStorage.id_mba,
            user_name: localStorage.nombres_mba,
            model: device.model,
            fabricante: device.manufacturer,
            cod_rel: deviceName.name,
            plataforma: device.platform
        },
        stopOnTerminate: false,
        // startOnBoot: true*/
    }, function (state) {    // <-- Current state provided to #configure callback
        // 3.  Start tracking
        console.log('BackgroundGeolocation is configured and ready to use');
        if (!state.enabled) {
            bgGeo.start().then(function () {
                console.log('- BackgroundGeolocation tracking started');
            });
        }
        init();
    });`

**Comment by christocracy** [comment]
The issue-template is not *optional*, it is **required**.  **Edit your post** and provide *all* the requested information and I will re-open.
![](https://dl.dropbox.com/s/zc0t3heqzbjowht/Screen%20Shot%202021-03-04%20at%206.28.42%20PM.png?dl=1)

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
