### ISSUE TITLE
does not show the message backgroundPermissionRationale Android V11  (4 times the APP is rejected)

### ISSUE THREAD

**Issue by mba3** [transistorsoft/cordova-background-geolocation-lt#1239]
## Your Environment
* Plugin version:
* Platform:  Android 8.1.0
* OS version:
* Device manufacturer / model: Android V11
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 
cordova-background-geolocation-lt 3.10.0 "BackgroundGeolocation"
cordova-honeywell-scanner-simplified 1.0.0 "HoneywellScannerSimplified"
cordova-open 1.1.0 "Open"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-background-fetch 6.1.1 "CDVBackgroundFetch"
cordova-plugin-bluetooth-peripheral-usage-description 1.0.1 "Bluetooth Peripheral Usage Description"
cordova-plugin-bluetooth-serial 0.4.7 "Bluetooth Serial"
cordova-plugin-bluetoothle 4.4.4 "Bluetooth LE"
cordova-plugin-btprinter 0.0.1-dev "BTPrinter"
cordova-plugin-buildinfo 2.0.3 "BuildInfo"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-device-name 1.3.5 "Device-Name"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-document-scanner 4.2.5 "Scan"
cordova-plugin-extended-device-information 2.2.0 "ExtendedDeviceInformation"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 10.2.0-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ipda018-scanner 1.0.0 "Scanner"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
cordova-plugin-zebra-printer 2.0.1 "ZebraBluetoothPrinter"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 3.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
* Plugin config provided to `#ready`:

does not show the message backgroundPermissionRationale

Video Google play Console: https://vimeo.com/519693962/085ba75a64
```javascript <!-- syntax-highlighting:  paste your code below -->
 bgGeo.ready({
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title: "Permitir el acceso a la ubicación de este dispositivo en segundo plano?",
          message: "Esta aplicación recopila datos de ubicación para permitir reportar la ubicación del usuario vendedor y calcular la distancia recorrida.",
          positiveAction: "Cambiar a Permitir todo el tiempo ",
          negativeAction: "Cancel"
        },
        reset: true,
        //  debug: true,
        logLevel: bgGeo.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        url: localStorage.ip_mba + "/mbamovil/movil_act?vSesion=" + localStorage.sesion_mba,
        method: 'POST',
        autoSync: true,
        batchSync: true,
        maxDaysToPersist: 30,
        maxRecordsToPersist: 500,
        logLevel: 0,
        extras: {
            emp_id: localStorage.id_emp_mba,
            device_id: device.uuid,
            user_id: localStorage.id_mba,
            user_name: localStorage.nombres_mba,
            model: device.model,
            fabricante: device.manufacturer,
            cod_rel: deviceName.name,
            plataforma: device.platform
        },
        stopOnTerminate: false,
        // startOnBoot: true*/
    }, function (state) {    // <-- Current state provided to #configure callback
        // 3.  Start tracking
        console.log('BackgroundGeolocation is configured and ready to use');
        if (!state.enabled) {
            bgGeo.start().then(function () {
                console.log('- BackgroundGeolocation tracking started');
            });
        }
        init();
    });
```

## Expected Behavior

does not display backgroundPermissionRationale message
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Plugin version:

**Comment by mba3** [comment]
**cordova-background-geolocation-lt 3.10.0 "BackgroundGeolocation"**
cordova-honeywell-scanner-simplified 1.0.0 "HoneywellScannerSimplified"
cordova-open 1.1.0 "Open"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-background-fetch 6.1.1 "CDVBackgroundFetch"
cordova-plugin-bluetooth-peripheral-usage-description 1.0.1 "Bluetooth Peripheral Usage Description"
cordova-plugin-bluetooth-serial 0.4.7 "Bluetooth Serial"
cordova-plugin-bluetoothle 4.4.4 "Bluetooth LE"
cordova-plugin-btprinter 0.0.1-dev "BTPrinter"
cordova-plugin-buildinfo 2.0.3 "BuildInfo"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-device-name 1.3.5 "Device-Name"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-document-scanner 4.2.5 "Scan"
cordova-plugin-extended-device-information 2.2.0 "ExtendedDeviceInformation"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 10.2.0-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ipda018-scanner 1.0.0 "Scanner"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
cordova-plugin-zebra-printer 2.0.1 "ZebraBluetoothPrinter"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 3.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

**Comment by christocracy** [comment]
Post your platforms/android/project.properties
