### ISSUE TITLE
Device reboot not enabling tracking.

### ISSUE THREAD

**Issue by salman-ghauri** [transistorsoft/cordova-background-geolocation-lt#124]
Hi Chris,
I am having issues while tracking locations using your plugin. I am using version 1.6.1 from your master branch. I implemented and configured the plugin as you did in sample app as a service with some changes and updates. I start the plugin in the app boot up which starts getting the locations but it is not frequent as I have configured it to be and as we do in the sample app configuration. I am using this on android phone. 
Also, I have enabled the flag **startOnBoot** to true, but it does not track the location when I restart the phone. 

Here is my options setting:
`var $settings = {
    common: [
      {name: 'url', dgroup: 'http', inputType: 'text', dataType: 'string', defaultValue: API_ENDPOINTS.geotrack_url},
      {name: 'method', group: 'http', inputType: 'select', dataType: 'string', values: ['POST', 'PUT'], defaultValue: 'POST'},
      {name: 'autoSync', group: 'http', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'true'},
      {name: 'batchSync', group: 'http', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'false'},
      {name: 'stopOnTerminate', group: 'application', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'false'},
      {name: 'stopTimeout', group: 'activity recognition', dataType: 'integer', inputType: 'select', values: [0, 1, 2, 5, 10], defaultValue: 0},
        {name: 'startOnBoot', group: 'application', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'true'},
      {name: 'activityRecognitionInterval', group: 'activity recognition', dataType: 'integer', inputType: 'select', values: [0, 1000, 10000, 30000, 60000], defaultValue: 6000},
      {name: 'debug', group: 'application', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'false'}
    ],
    iOS: [
      {name: 'desiredAccuracy', group: 'geolocation', dataType: 'integer', inputType: 'select', values: [-1, 0, 10, 100, 1000], defaultValue: 500 },
      {name: 'distanceFilter', group: 'geolocation', dataType: 'integer', inputType: 'select', values: [0, 10, 20, 50, 100, 500], defaultValue: 50 },
      {name: 'stationaryRadius', group: 'geolocation', dataType: 'integer', inputType: 'select', values: [0, 20, 50, 100, 500], defaultValue: 100 },
      {name: 'activityType', group: 'geolocation', dataType: 'string', inputType: 'select', values: ['Other', 'AutomotiveNavigation', 'Fitness', 'OtherNavigation'], defaultValue: 'Other'},
      {name: 'disableElasticity', group: 'geolocation', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'true'},
      {name: 'stopDetectionDelay', group: 'activity recognition', dataType: 'integer', inputType: 'select', values: [0, 1, 2, 5], defaultValue: 0},
      {name: 'useSignificantChangesOnly', group: 'geolocation', dataType: 'boolean', inputType: 'select', values: ['true','false'], defaultValue: 'false'},
      {name: 'disableMotionActivityUpdates', group: 'geolocation', dataType: 'boolean', inputType: 'select', values: ['true','false'], defaultValue: 'true'}
    ],
    Android: [
      {name: 'desiredAccuracy', group: 'geolocation', dataType: 'integer', inputType: 'select', values: [0, 10, 100, 1000], defaultValue: 0 },
      {name: 'distanceFilter', group: 'geolocation', dataType: 'integer', inputType: 'select', values: [0, 10, 20, 50, 100, 500], defaultValue: 0 },
      {name: 'locationUpdateInterval', group: 'geolocation', dataType: 'integer', inputType: 'select', values: [0, 1000, 5000, 10000, 30000, 60000], defaultValue: 6000},
      {name: 'fastestLocationUpdateInterval', group: 'geolocation', dataType: 'integer', inputType: 'select', values: [0, 1000, 5000, 10000, 30000, 60000], defaultValue: 9000},
      {name: 'triggerActivities', group: 'activity recognition', dataType: 'string', inputType: 'select', values: ['in_vehicle', 'on_bicycle', 'on_foot', 'running', 'walking'], defaultValue: 'in_vehicle, on_bicycle, running, walking, on_foot'},
      {name: 'forceReloadOnMotionChange', group: 'application', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'false'},
      {name: 'forceReloadOnLocationChange', group: 'application', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'false'},
      {name: 'forceReloadOnGeofence', group: 'application', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'false'},
      {name: 'startOnBoot', group: 'application', dataType: 'boolean', inputType: 'select', values: ['true', 'false'], defaultValue: 'false'}
    ]
  };`

and this is what I am returning from my service:
`
return {
  
    setEnabled: function(willEnable, success, fail) {
      window.localStorage.setItem('bgGeo:enabled', willEnable);
      if ($plugin) {
        if (willEnable) {
          $plugin.start(success, fail);
        } else {
          $plugin.stop(success, fail);
        }
      }
    },
    /**
    * Is the plugin enabled to run in background?
    * @return {Boolean}
    */
    getEnabled: function() {
      return window.localStorage.getItem('bgGeo:enabled') === 'true';
    },
    /**
    * Toggle stationary/aggressive mode
    * @param {Boolean} willStart
    */
    setPace: function(willStart, successFn) {
      if ($plugin) {
        $plugin.changePace(willStart, successFn, function(error) {
          $log.debug('Failed to change pace: ' + error);
        });
      }
    },
    /**
    * Manually sync plugin's persisted locations to server
    */
    sync: function(success, failure) {
      if ($plugin) {
        $plugin.sync(success, failure);
      } else {
        // Fake it for browser testing.
        setTimeout(success, 1000);
      }
    },
    finish: function(taskId) {
      $log.debug('- BackgroundGeolocationService#finish, taskId: ', taskId);
      if ($plugin) {
        $plugin.finish(taskId);
      }
    },
    /**
    * Add an event-listener for location-received from $plugin
    * @param {Function} callback
    */
    onLocation: function(callback, failure) {
        if ($plugin) {
            $plugin.onLocation(callback, failure);
        }
    },
    /**
    * Add a stationary-listener
    * @param {Function} stationary event-listener
    */
    onMotionChange: function(callback, failure) {
      if ($plugin) {
        $plugin.onMotionChange(callback, failure);
      }
    },
    onGeofence: function(callback) {
      var me = this;
      if ($plugin) {
        $plugin.onGeofence(function(params, taskId) {
          $log.debug('- onGeofence:' + JSON.stringify(params));
          $log.debug('  taskId: ' + taskId);
          try {
            callback.call(me, params, taskId);
          } catch (e) {
            $log.debug('error: ' + e.message, e);  
          }
        });
      }
    },

    /**
    * Return the current BackgroundGeolocation config-state as stored in localStorage
    * @return {Object}
    */
    getConfig: function() {
      return $config;
    },

    /**
    * Get a single config value by key
    * @param {String} key A BackgroundGeolocation setting key to return a value for
    * @return {Mixed}
    */
    get: function(key) {
      return $config[key];
    },
    /**
    * Set a single config value by key,value
    * @param {String} key
    * @param {Mixed} value
    */
    set: function(key, value) {
      $ls.setItem('settings:' + key, value);
      $config[key] = value;

      if ($plugin) {
        $plugin.setConfig(function(response) {
          $log.debug('- setConfig: ', response);
        }, function(error) {
          console.warn('- setConfig error: ', error);
        }, $config);
      }
    },
    /**
    * Configure the BackgroundGeolocation Cordova $plugin
    * @param {BackgroundGeolocation} bgGeoPlugin
    */
    configurePlugin: function(bgGeoPlugin) {
      var device = ionic.Platform.device();
      $platform = device.platform;

      var me      = this;
      var config  = this.getConfig();

      config.extras = {
        "network_type": $cordovaNetwork.getNetwork() || 'unknown',
        "user_email": window.localStorage.getItem(LOCAL_STORAGE_KEY.user_email),
        "auth_token": window.localStorage.getItem(LOCAL_STORAGE_KEY.auth_token)
      };

      config.preventSuspend = true;
      config.heartbeatInterval = 60;

      config.params = config.params || {};

      // Append Cordova device-info to POST params so we can map a device-id to the location
      config.params.device = device;
        config.params.user_email = window.localStorage.getItem(LOCAL_STORAGE_KEY.user_email);
        config.params.auth_token = window.localStorage.getItem(LOCAL_STORAGE_KEY.auth_token);
        config.params.network_type = window.localStorage.getItem(LOCAL_STORAGE_KEY.network_type);
        config.params.device_token = window.localStorage.getItem(LOCAL_STORAGE_KEY.device_token);

      $plugin = bgGeoPlugin;

      // Configure BackgroundGeolocation Plugin
      $plugin.configure(config, function (state) {

          $log.debug('got the state:', state);
      }, function(error) {
        $log.debug('Location error: ' + error);
        $log.debug('BackgroundGeolocation Error: ' + error);
      });

      if (this.getEnabled()) {
        $plugin.start();
      }
    },
    setParam: function(new_param_object) {

    	if($plugin) {
    		$plugin.getState(function(state){
    			$log.debug('setParam before, BGGeo config: ');
    			$log.debug(JSON.stringify($config));
    			$log.debug('BGGEO STATE');
    			$log.debug(JSON.stringify(state));
    			$log.debug('setParam function. showing new_param_object, state.params and obj');
    			$log.debug(JSON.stringify(new_param_object));
    			$log.debug(JSON.stringify(state.params));
    			var obj = {};
    			if(ionic.Platform.isIOS())
				{
    				obj = angular.extend({}, state.params, new_param_object );
    			} else {
    				obj = angular.extend({}, state.params, new_param_object );
    			}
    			$log.debug(JSON.stringify(obj));
    			$plugin.setConfig({params: obj}, function(){
                    $log.debug('set config success');
                }, function(){
                    $log.debug('set config failed');
                });

    			$log.debug('setParam after, BGGeo config: ');
    			$log.debug(JSON.stringify($config));
    			
    		});
    		
    	}

    },
    /**
    * Return a reference to Cordova BackgroundGeolocation plugin
    * @return {BackgroundGeolocation}
    */
    getPlugin: function() {
      return $plugin;
    },
    getCurrentPosition: function(callback, failure, options) {
    	$log.debug('Starting getCurrentPosition');
      if ($plugin) {
      	$log.debug('BGGeo plugin exists');
        $plugin.getCurrentPosition(callback, failure, options);
      }
    }
  
  };`

**Waiting for you thoughts!**

**Comment by christocracy** [comment]
You should not modify `Settings` service, nor should you use `Settings` service in your own application.  `Settings` service is a construct used only in the SampleApp in support of the complex **Settings** screen, which you would **not** use in your own app.  Do **NOT USE THIS IN YOUR APP!**.

In response to too many people needlessly using this `Settings` construct, I've [greatly simplified it](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/services/Settings.js).  I don't think you're using the latest version of my SampleApp:

With that being said, I won't even look at code you've posted.  The only think I'm interested in are logs.  Show me logs.

**Comment by salman-ghauri** [comment]
Actually, what I am trying to tell you is that I am not getting the response like I set the parameters in the setting using `setConfig()` function.
I have set the
`desired accuracy to 0, 
``distance filter to 0, 
``autoSyn to true, 
``startOnBoot to true` and 
`stopOnTerminate to false`
but I am not getting the responses as frequently as I get them when I set these settings in the sample app nor the plugins run on app termination or device reboot.. I can you show you logs which I am storing in my data base which contains the locations, time stamps etc.
My question is: is this regular or is there something I am not doing right?

**Comment by christocracy** [comment]
When you kill the app with `stopOnTerminate: false` (or reboot the device with `stopOnTerminate: false`, you need to move some distance before before iOS will re-awaken the device and begin tracking again.  This can take 2-3 blocks typically but can take 1km depending on your local network environment.  The plugin **cannot** immediately keep tracking when user kills the app.  Tracking **will** be interrupted.

Are you testing in the iOS simulator?  This behaviour is easily simulated.

You can see `stopOnTerminate` behaviour in [this video](https://dl.dropboxusercontent.com/u/2319755/cordova-background-geolocaiton/SampleApp-1080.mov)

**Comment by christocracy** [comment]
Btw, you've made a typo in the `autoSync` config (you're typing `autoSyn`.  The default is `true` anyway.

**Comment by salman-ghauri** [comment]
Okay thanks for the help for `stopOnTerminate`. 
The typo you mentioned is actually not in the code but here is the comment. :)
Can you help me with the other issue of the device not tracking the location as frequently as I configure the plugin for Android. Is this usual behavior on android?

**Comment by christocracy** [comment]
>Can you help me with the other issue of the device not tracking the location as frequently as I configure the plugin for Android. Is this usual behavior on android?

Post a new issue related to that as well as logs and/or map showing this behaviour.
