### ISSUE TITLE
Plugin does not track location when internet is off

### ISSUE THREAD

**Issue by amit-rwt** [transistorsoft/cordova-background-geolocation-lt#1240]
## Your Environment
* Plugin version: 3.9.1
* Platform: Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):9.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onHttp(response => {
  console.log("[http] response: ", response.success, response.status, response.responseText);
});

BackgroundGeolocation.ready({
reset: false,
desiredAccuracy:BackgroundGeolocation.DESIRED_ACCURACY_HIGH, 
distanceFilter:30,
stopOnTerminate: true,
startOnBoot: false,
heartbeatInterval: 60,
preventSuspend: true,
}, state => {
  if(!state.enabled){
	BackgroundGeolocation.start();
  }
});
```

## Expected Behavior
Should Record location when internet is off

## Actual Behavior
it is not tracking location when internet is off

## Steps to Reproduce

1. Disable wifi and mobile network
2. Start App (I am using my app and your plugin)
3. Went out and it has not track any location for me.

When internet is on it tracks the location.

## Context

I am using non license version in android debug mode. 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Do not disable WiFi.  Both iOS and Android location apis rely on WiFi.

It's fine to disable cellular data.

**Comment by hiimagu** [comment]
Im about to buy the license and I want to know, this library works without internet? for example, I'll be able to save the locations in my phone without internet driving a truck in the middle of the road?

**Comment by christocracy** [comment]
>this library works without internet?

Yes.  This plugin was originally designed for a disaster-response app, tracking emergency workers in hurricanes and earthquakes where the **cellular network is assumed to be destroyed (ie: no network connection)**.  This is  why the plugin hosts its own SQLite database, so it can queue recorded locations and sync when a network connection becomes available.

I regularly field-test on 13 Android devices with no SIM card.  They diligently record everywhere I go and upload their data to my test-server when I arrive back on my home Wifi.
