### ISSUE TITLE
Getting error while try to run android application in mobile

### ISSUE THREAD

**Issue by vpetkar2** [transistorsoft/cordova-background-geolocation-lt#1243]
## Your Environment
* Plugin version: 4.0.0
* Platform: Android
* OS version: Android 10
* Device manufacturer / model: Mi Note 8 Pro
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): Cordova Android 9.0.0
* Plugin config provided to `#ready`:
```
  configureBackgroundGeolocation() {
    // 1. Listen to events (see the docs a list of all available events)
    BackgroundGeolocation.onLocation(this.onLocation.bind(this));
    BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
    BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
    BackgroundGeolocation.onGeofence(this.onGeofence.bind(this));
    BackgroundGeolocation.onHttp(this.onHttp.bind(this));
    BackgroundGeolocation.onEnabledChange(this.onEnabledChange.bind(this));
    BackgroundGeolocation.onConnectivityChange(this.onConnectivityChange.bind(this));

    // 2. Configure the plugin
    BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      url: 'http://your.server.com/locations',
      autoSync: true,
      params: {
        foo: 'bar'
      }
    }, (state) => {
      // Note:  the SDK persists its own state -- it will auto-start itself after being terminated
      // in the enabled-state when configured with stopOnTerminate: false.
      // - The #onEnabledChange event has fired.
      // - The #onConnectivityChange event has fired.
      // - The #onProviderChange has fired (so you can learn the current state of location-services).
      
      if (!state.enabled) {
        // 3. Start the plugin.  In practice, you won't actually be starting the plugin in the #ready callback
        // like this.  More likely, you'll respond to some app or UI which event triggers tracking.  "Starting an order"
        // or "beginning a workout", for example.
        BackgroundGeolocation.start();
      } else {        
        // If configured with stopOnTerminate: false, the plugin has already begun tracking now.        
        // - The #onMotionChange location has been requested.  It will be arriving some time in the near future.        
      }
    });
  }

  onLocation(location:Location) {
    console.log('[location] -', location);
  }
  onMotionChange(event:MotionChangeEvent) {
    console.log('[motionchange] -', event.isMoving, event.location);
  }
  onActivityChange(event:MotionActivityEvent) {
    console.log('[activitychange] -', event.activity, event.confidence);
  }
  onGeofence(event:GeofenceEvent) {
    console.log('[geofence] -', event.action, event.identifier, event.location);
  }
  onHttp(event:HttpEvent) {
    console.log('[http] -', event.success, event.status, event.responseText);
  }
  onEnabledChange(enabled:boolean) {
    console.log('[enabledchange] - enabled? ', enabled);
  }
  onConnectivityChange(event:ConnectivityChangeEvent) {
    console.log('[connectivitychange] - connected?', event.connected);
  }

```

## Expected Behavior
App should run properly 

## Actual Behavior
It was showing error

## Steps to Reproduce
1. Followed the steps for code integration
2. run command: ionic cordova run android -l
3. installed successfully 
4. while open the app, it shows error in debug console

## Context

I have installed as per the steps given, but after doing all steps, I am getting the below error.

## Debug logs
Android Logs
<details>
	<summary>Logs</summary>

``
ERROR Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 8 of the parameter list is invalid.
This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 8 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.
    at ɵɵinvalidFactoryDep (:8100/vendor.js:37925)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (ng:///AppComponent/ɵfac.js:9)
    at getNodeInjectable (:8100/vendor.js:41128)
    at instantiateRootComponent (:8100/vendor.js:44925)
    at createRootComponent (:8100/vendor.js:55474)
    at ComponentFactory$1.create (:8100/vendor.js:59290)
    at ApplicationRef.bootstrap (:8100/vendor.js:65418)
    at :8100/vendor.js:65129
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (:8100/vendor.js:65129)
defaultErrorLogger @ core.js:4197
main.ts:12 Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 8 of the parameter list is invalid.
This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 8 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.
    at ɵɵinvalidFactoryDep (:8100/vendor.js:37925)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (ng:///AppComponent/ɵfac.js:9)
    at getNodeInjectable (:8100/vendor.js:41128)
    at instantiateRootComponent (:8100/vendor.js:44925)
    at createRootComponent (:8100/vendor.js:55474)
    at ComponentFactory$1.create (:8100/vendor.js:59290)
    at ApplicationRef.bootstrap (:8100/vendor.js:65418)
    at :8100/vendor.js:65129
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (:8100/vendor.js:65129)
```

</details>

**Comment by christocracy** [comment]
I don't see any reference to background-geolocation.  Never heard of this error.

**Comment by vpetkar2** [comment]
Before the integration of this plugin, it was working fine 
Also, I search for this issue, getting the solution like I am missing constructor for some class but don't know for which class it is.
I Will check again today
Thanks for your quick response!!

**Comment by vpetkar2** [comment]
Do you also give support for integration?

**Comment by christocracy** [comment]
I suggest you create a simple *Hello world* app and first experiment with the plugin in isolation.

**Comment by vpetkar2** [comment]
ok, Thanks for the suggestion.
I will try that

**Comment by vpetkar2** [comment]
It's working for me in sample application in ionic
I want to discuss something about it and interested to purchase
can we have a call, please?

**Comment by christocracy** [comment]
my phone number is on the website.

**Comment by vpetkar2** [comment]
Can we have call on skype?

**Comment by christocracy** [comment]
Skype: 'christocracy`
