### ISSUE TITLE
Installing the plugin automatically downgrade my Gradle version in Android studio

### ISSUE THREAD

**Issue by kinson603** [transistorsoft/cordova-background-geolocation-lt#1248]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: Windows 10
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
ionic cordova plugin add cordova-background-geolocation-It
```

## Expected Behavior
It should install the plugin without changing anything.

## Actual Behavior
Cannot install the plugin. My Gradle version in the android studio has downgraded from 4.6 to 3.3, and an error pops up telling me to update the Gradle to 4.6.

## Steps to Reproduce

1. Start an Ionic app with Cordova 7.1.0
2. Add an Android platform
3. Add this plugin

## Context
I try to install the plugin in my Ionic 3 app with an Android platform.  The java and Gradle version has checked and it just can't install the plugin. Using the latest version of the plugin would also fail because the Cordova-android version is too old. Any workaround or alternatives?

## Debug logs
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
> cordova.cmd plugin add cordova-background-geolocation-lt
Installing "cordova-background-geolocation-lt" for android
Plugin dependency "cordova-plugin-background-fetch@5.3.0" already fetched, using that version.
Installing "cordova-plugin-background-fetch" for android
ANDROID_HOME=C:\Users\***\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_281
Subproject Path: CordovaLib
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

BUILD FAILED

Total time: 8.852 secs

* Where:
Build file 'C:\<myProject>\platforms\android\build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 4.6. Current version is 3.3. If using the gradle wrapper, try editing the distributionUrl in C:\Users\<myProject>\gradle\wrapper\gradle-wrapper.properties to gradle-4.6-all.zip
```

</details>

**Comment by christocracy** [comment]
The plugin does not affect Gradle version.

Are you sure you're installing the correct plugin, because this is not correct:

![](https://dl.dropbox.com/s/a86tnes2ptvaye8/Screen%20Shot%202021-04-13%20at%2010.02.34%20AM.png?dl=1)

**Comment by kinson603** [comment]
Sorry it is just a typo on the post. I am installing the correct plugin.

I solved the problem now. It is related to the gradle building in Cordova [https://stackoverflow.com/questions/49321000/minimum-supported-gradle-version-is-4-1-current-version-is-3-3](url)
Not sure why would this only occur when installing this plugin though.
