### ISSUE TITLE
Error when switching location type in the simulator

### ISSUE THREAD

**Issue by moltar** [transistorsoft/cordova-background-geolocation-lt#125]
When I use Debug -> Location menu to switch type of movement simulation, I get the following error. However, it seems not to affect functionality and the app continues to work.

```
33    865976   warn     - BackgroundGeoLocation error: , 0
```

To reproduce:

 1. Run app with ```ionic emulate ios -lc```
 1. Open an app with location set to "Freeway Drive". 
 1. Wait for a few location reports. 
 1. Switch the location type to "City Run".
 1. Watch for console errors and app notification errors.

**Comment by christocracy** [comment]
This is completely normal and expected behavior.

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Error-Codes

**Comment by moltar** [comment]
It sounds like it might be worth documenting. As clearly it was not expected nor obvious for me ;)
