### ISSUE TITLE
Plugin not installed on ios build taken 

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1251]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS
* OS version:6.1.0
* Device manufacturer / model:
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

Need background location access in ios
## Actual Behavior
Can't take build

## Steps to Reproduce

1.ng build
2.cordova platform add ios,
3.cordova build ios
4.failed to install 'cordova-background-geolocation-lt': Error: pod: Command failed with exit code 1

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```
$ pod --version
```

**Comment by Ambikapathi** [comment]
Due to download permission issue, once i cleared permission for download,issue cleared.

**Comment by Ambikapathi** [comment]
location latitude and longitude not captured on some place. How to resolve that.
