### ISSUE TITLE
Location not captured on some places during continuous tracking.

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1252]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS
* OS version:6.1.0
* Device manufacturer / model:
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Need continuous tracking without trouple

## Actual Behavior
Background geolocation working fine. But some places not return any data about location.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See Wiki *Debugging*.
