### ISSUE TITLE
Android 11 Galaxy S20 Restart Phone Problem

### ISSUE THREAD

**Issue by Till92921** [transistorsoft/cordova-background-geolocation-lt#1254]
## Your Environment
* Plugin version:   "cordova-background-geolocation-lt": "^3.9.4",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-background-fetch": "^6.1.1",
    "cordova-plugin-file": "^6.0.2",
    "cordova-sqlite-storage": "^5.1.0",
* Platform:  Android
* OS version: 11 
* Device manufacturer / model: Samsung Galaxy S20
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): Installed platforms:
Available platforms:
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
* this.stopOnTerminate = true;
    this.debug =  false;
    this.disableElasticity =   true;
    this.startOnBoot = false;
    this.autoSync =  false;
    this.distanceFilter = 50;
.....
* logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: this.distanceFilter,
        debug: this.debug,
        disableElasticity: this.disableElasticity,
        stopOnTerminate: this.stopOnTerminate,
        startOnBoot: this.startOnBoot,
        autoSync: this.autoSync,
        speedJumpFilter: 10,
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
I restart the phone while the plugin is running. 
After the restart I open the app again and the GPS tracking should continue to run

## Actual Behavior

Currently the plugin starts shortly after restarting the phone and fires a coordinate, then the plugin crashes. There are no new coordinates. 

Even if I close the app and start it again

## Steps to Reproduce

1.
2.
3.
4.

## Context
It is a hiking app. 
The goal is that when the user's phone crashes or the battery goes flat. The route of the user is not deleted and the user can continue walking with the known data before the crash. The plugin should start again

because I run BackgroundGeolocation.start()

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>After the restart I open the app again and the GPS tracking should continue to run

```
this.stopOnTerminate = true;
this.startOnBoot = false;
```

**Comment by Till92921** [comment]
![image](https://user-images.githubusercontent.com/65195261/115886553-5593fc00-a451-11eb-9624-6242262c3bf4.png)

The parameters are already set to these values

**Comment by christocracy** [comment]
ask yourself the following questions:
- *"Do I want location tracking to stop on terminate?"*
- *"Do I want location tracking to start on boot?"*
