### ISSUE TITLE
AppTrackingTransparency

### ISSUE THREAD

**Issue by hrefcl** [transistorsoft/cordova-background-geolocation-lt#1255]
Apple has sent me this email about AppTrackingTransparency and refers to the backgroundlocation modules, what can be done about this? I can not find more information.
<details>
Hello XXX,

Thank you for answering the app privacy questions in App Store Connect. You’ve indicated that your app, XXX, collects data to track users or devices. We want to make sure you're aware that starting April 26, 2021, apps on the App Store must use AppTrackingTransparency to receive user permission before collecting data used to track them or their devices.

If you're already working on implementing the framework, we appreciate your efforts to provide transparency and choice to users. If not, and your app continues to track users, your next submission must implement AppTrackingTransparency to request the user’s permission to track them. The following resources are available:

App Tracking Transparency documentation
Human Interface Guidelines: Accessing User Data
AdSupport documentation
We also understand that many developers are working towards ending tracking functionality in their app and will update their app privacy information in App Store Connect when they're finished.

For additional details on policies related to tracking, please review App Store Review Guideline 5.1.2 (i): Data Use and Sharing and the User Privacy and Data Use support page.

We look forward to reviewing your future submissions to the App Store. If you have any questions, contact us.

Best regards,

Apple Developer Relations
</details>

**Comment by christocracy** [comment]
"*App Tracking Transparency" doesn't mean *"Location Tracking"*, it means tracking as in *"Ad Tracking"*.

See [here](https://techcrunch.com/2021/04/07/apple-app-tracking-transparency-details/)

This is what [Facebook is all mad about](https://www.facebook.com/business/help/126789292407737?id=1205376682832142).
