### ISSUE TITLE
Beep Sound Issue

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1258]
## Your Environment
* Plugin version:4.0.1
* Platform: iOS
* OS version:6.1.0
* Device manufacturer / model:
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Background geolocation without beep sound

## Actual Behavior
Beep sound makes horrible use app.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs `Config.debug`.  Those *Debugging* sound FX are there to assist you during development / field-testing, so you can *hear* the plugin operating in real time.
