### ISSUE TITLE
How to remove location service activated notification

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1259]
## Your Environment
* Plugin version:4.0.1
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Vivo
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):9.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Need to remove location service activated notification

## Actual Behavior
Always showing location service activated notification

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It is required by the OS.

If the notification were not there, the plugin could not operate in the background.
