### ISSUE TITLE
App (sometimes) crashing on resuming from background (iOS)

### ISSUE THREAD

**Issue by aspin** [transistorsoft/cordova-background-geolocation-lt#126]
I suspect that my issues are from some problem from signaling completion from a callback in the success callback, but I'm not completely understanding why.  Here's the source:

```js
function success(location, taskId) {
  if (Meteor.userId()) {
    HTTP.post(`${ Meteor.absoluteUrl() }api/geolocation`, {
      data: {
        location: location.coords,
        userId: Meteor.userId()
      }
    }, (err, res) => {
      bgGeo.finish(taskId);
    });
  } else {
    bgGeo.finish(taskId);
  }
}

function error(error) {
  console.log(error);
}

bgGeo.on('location', success, error);
```
This is for a Meteor app, and `HTTP.post` is a convenience package. Is there anything wrong with signaling completion from this callback?

I have confirmed that background geo is causing this issue, as I can (oddly enough) reproduce the crash by putting the app in the background, and toggling on/off airplane mode, and attempting to resume the app (although the crash seems to happen on its own after some period of time of leaving the app in the background). Not starting background location tracking avoids this. Any tips?

**Comment by christocracy** [comment]
Logs, please

**Comment by christocracy** [comment]
Hello?  Logs?

**Comment by aspin** [comment]
Apologies sorry this got pushed to the backburner. Will follow up over the weekend.

**Comment by aspin** [comment]
Also, I misstated that it was a crash -- it's actually that it gets stuck at the app loading screen forever.

**Comment by christocracy** [comment]
What makes you suspect it's this plugin causing this issue?  Are you watching the app boot in XCode?

**Comment by christocracy** [comment]
These bg `taskId` are nothing more than labels to iOS, signalling that it should delay suspending an app in the background.  When all outstanding `bgTask` labels are `#finish`ed, iOS will suspend the app (if location-services are OFF).  

It doesn't matter where you call `#finish`.

**Comment by aspin** [comment]
Hmm, gotcha. Main reason we thought so is that the commit adding this package was the one that started us having issues with the app on resume + a teammate told me that the issues stopped happening after he took out the package locally for testing.

I'll keep you posted when I get a chance to jump back into this on the weekend.

**Comment by ddresch** [comment]
@aspin can you check you debug -> system logs when testing in simulator? I got the same issue and end up with this error in the log:

```
App startup timed out, reverting to last known good version.
```

Also a question if you use the raix:push package? Not sure right now but I'm also sticking in the dark.

**Comment by ddresch** [comment]
@christocracy I setup a simple test app with Meteor and it seams like there is a problem when the app gets started in background. Can you please check this repo?

https://github.com/ddresch/meteor-geofencing-test

I added the log output I get to the README. At the moment I'm not sure where the error happens or if it's a miss configuration by myself. It could also be a issue of Meteor itself but I wanted to check first with you. THX!

**Comment by christocracy** [comment]
Geofencing is completely handled with pure native APIs.  These APIs are
"fire and forget", handled by the OS.

On Wednesday, July 6, 2016, Dirk Dresch <notifications@github.com> wrote:

> @christocracy <https://github.com/christocracy> I setup a simple test app
> with Meteor and it seams like there is a problem when the app gets started
> in background. Can you please check this repo?
>
> https://github.com/ddresch/meteor-geofencing-test
>
> I added the log output I get to the README. At the moment I'm not sure
> where the error happens or if it's a miss configuration by myself. It could
> also be a issue of Meteor itself but I wanted to check first with you. THX!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/126#issuecomment-230746113>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l-8QuBLWLnpjBvdHFEmO3blo46QDks5qS5DCgaJpZM4IrJh1>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ddresch** [comment]
Thx. Trying to get answers in the Meteor community.

**Comment by christocracy** [comment]
The plugin has nothing to do with `App startup timed out, reverting to last known good version.`.

**Comment by lpender** [comment]
@ddresch Did you start a thread somewhere in the Meteor community that you could point to? 

My app is also hanging on startup after adding this plugin.

Thanks!
-Lee

**Comment by ddresch** [comment]
@lpender actually I can't remember where I tried to get an answer but I know I didn't get any. I switched to ReactNative which was definitely a good idea. But probably not the one you want to hear now. But at that point I was desperate.

**Comment by lpender** [comment]
I found it here: https://github.com/meteor/meteor/issues/7359

**Comment by lpender** [comment]
And here is a more detailed explanation of the issue and its fix.

https://github.com/meteor/cordova-plugin-meteor-webapp/issues/24

To avoid this issue, add the following to your meteor app:

`.meteor/cordova-plugins`

```
cordova-plugin-meteor-webapp@1.4.2
```
