### ISSUE TITLE
After the phone call background location data not fetched 

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1260]
## Your Environment
* Plugin version:4.0.1
* Platform:  Android
* OS version: Android 8
* Device manufacturer / model: Vivo
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):9.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Need background location tracking data without any trouble

## Actual Behavior
After the phone call app background location service data not fetched

## Steps to Reproduce

1. Minimize the app in background,
2.Drive in car with app in background,
3.Make the phone call in between the background tracking,
4. No data received after phone call closed.

## Debug logs

<details>
	[{"CompanyId":"416","TechId":"1135","Latitude":12.9063053,"Longitude":80.2007138,"CreatedBy":"1135","CreatedDate":"4/29/2021 02:05:53 pm"},{"CompanyId":"416","TechId":"1135","Latitude":12.9062955,"Longitude":80.2007138,"CreatedBy":"1135","CreatedDate":"4/29/2021 02:06:02 pm"},{"CompanyId":"416","TechId":"1135","Latitude":12.9062907,"Longitude":80.2007119,"CreatedBy":"1135","CreatedDate":"4/29/2021 02:06:13 pm"},{"CompanyId":"416","TechId":"1135","Latitude":12.9062969,"Longitude":80.2007144,"CreatedBy":"1135","CreatedDate":"4/29/2021 02:06:22 pm"},{"CompanyId":"416","TechId":"1135","Latitude":12.9062876,"Longitude":80.2007075,"CreatedBy":"1135","CreatedDate":"4/29/2021 02:06:32 pm"},{"CompanyId":"416","TechId":"1135","Latitude":12.9062896,"Longitude":80.2007089,"CreatedBy":"1135","CreatedDate":"4/29/2021 02:06:42 pm"}][{"CompanyId":"416","TechId":"1671","Latitude":12.9062863,"Longitude":80.2007089,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:06:52 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063226,"Longitude":80.200694,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:02 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063017,"Longitude":80.2007638,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:06 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063045,"Longitude":80.2007981,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:12 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9062599,"Longitude":80.2007416,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:21 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9062621,"Longitude":80.2007389,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:22 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9062762,"Longitude":80.2007659,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:32 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9062839,"Longitude":80.2007843,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:35 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9062966,"Longitude":80.2008037,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:42 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.906353,"Longitude":80.2007854,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:48 pm"}][{"CompanyId":"416","TechId":"1671","Latitude":12.9063606,"Longitude":80.2007743,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:52 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063042,"Longitude":80.2007703,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:56 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063508,"Longitude":80.20077,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:58 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9062968,"Longitude":80.2007693,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:07:59 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063415,"Longitude":80.2007734,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:02 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063339,"Longitude":80.2007756,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:12 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063181,"Longitude":80.2007181,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:21 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063206,"Longitude":80.2006812,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:22 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063162,"Longitude":80.2006153,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:24 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9062307,"Longitude":80.1997981,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:49 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9061784,"Longitude":80.1997804,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:51 pm"}][{"CompanyId":"416","TechId":"1671","Latitude":12.9061279,"Longitude":80.1997715,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:52 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9060876,"Longitude":80.1997635,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:53 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9059709,"Longitude":80.1997454,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:55 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9058621,"Longitude":80.1997344,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:57 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9057567,"Longitude":80.1997284,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:08:59 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9056554,"Longitude":80.1997228,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:01 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9056034,"Longitude":80.1997206,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:02 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9055549,"Longitude":80.199718,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:03 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9054554,"Longitude":80.1997061,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:05 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9053576,"Longitude":80.199693,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:07 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9052573,"Longitude":80.199679,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:09 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9051484,"Longitude":80.1996581,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:11 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9050943,"Longitude":80.19965,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:12 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9050337,"Longitude":80.199644,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:14 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9049361,"Longitude":80.1996392,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:19 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9048377,"Longitude":80.1996315,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:21 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9047926,"Longitude":80.1996271,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:22 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9047057,"Longitude":80.1996382,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:24 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9045909,"Longitude":80.1996068,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:26 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9044715,"Longitude":80.1995629,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:28 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9043499,"Longitude":80.1995087,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:30 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9042225,"Longitude":80.199423,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:32 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9041153,"Longitude":80.1993552,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:34 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9040128,"Longitude":80.1992902,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:36 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9039182,"Longitude":80.1992332,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:38 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9038184,"Longitude":80.1991774,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:40 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9037166,"Longitude":80.1991019,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:42 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9036015,"Longitude":80.1990285,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:44 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9034932,"Longitude":80.1989667,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:46 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.903396,"Longitude":80.1989065,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:48 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9033068,"Longitude":80.1988392,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:50 pm"}][{"CompanyId":"416","TechId":"1671","Latitude":12.9032106,"Longitude":80.1987792,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:52 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9031231,"Longitude":80.1987143,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:54 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9030349,"Longitude":80.1986526,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:56 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9029511,"Longitude":80.1985819,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:09:58 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9028657,"Longitude":80.1985164,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:00 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.902774,"Longitude":80.1984663,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:02 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9026807,"Longitude":80.1984178,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:04 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9025778,"Longitude":80.1983696,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:06 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9024428,"Longitude":80.1983471,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:09 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9023141,"Longitude":80.1983083,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:11 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9022547,"Longitude":80.1982889,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:12 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.902196,"Longitude":80.1982577,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:13 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.902084,"Longitude":80.1982039,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:15 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9019991,"Longitude":80.1981659,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:17 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9019087,"Longitude":80.1981278,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:19 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9018023,"Longitude":80.1980987,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:21 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9017603,"Longitude":80.1980944,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:22 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9016967,"Longitude":80.1980758,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:24 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9015976,"Longitude":80.1980228,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:27 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9015012,"Longitude":80.1979799,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:30 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9014938,"Longitude":80.1979665,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:31 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9014369,"Longitude":80.197952,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:34 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.901321,"Longitude":80.1979059,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:37 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9012249,"Longitude":80.1979256,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:41 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9011925,"Longitude":80.1979681,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:43 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9012084,"Longitude":80.1979885,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:10:52 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9012162,"Longitude":80.1979806,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:02 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9011855,"Longitude":80.1979475,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:11 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9011559,"Longitude":80.1979985,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:13 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.901115,"Longitude":80.1980904,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:15 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9011063,"Longitude":80.1981869,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:16 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9010947,"Longitude":80.1983078,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:19 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9010838,"Longitude":80.1984293,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:22 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9010542,"Longitude":80.1985439,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:26 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9010047,"Longitude":80.1986601,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:29 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9009241,"Longitude":80.1987396,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:32 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9008306,"Longitude":80.1987612,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:34 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9007342,"Longitude":80.1987594,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:36 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9006427,"Longitude":80.1987463,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:39 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9005483,"Longitude":80.1987299,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:41 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9004584,"Longitude":80.1987061,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:43 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9003547,"Longitude":80.1986813,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:45 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9002407,"Longitude":80.1986679,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:47 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9001465,"Longitude":80.198656,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:11:49 pm"}]

<------ After the phone call gps data not received between 02:11 pm to 02:24 pm------------------>

<------- Gps data was received only after relogin the app -------------------------->

<--- ----- Below given data received after relogin the app ------------------->

[{"CompanyId":"416","TechId":"1671","Latitude":12.9063021,"Longitude":80.1993192,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:24:42 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063018,"Longitude":80.1993189,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:24:44 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063019,"Longitude":80.1993195,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:24:51 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063036,"Longitude":80.1993807,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:24:57 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063172,"Longitude":80.1994492,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:24:59 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9063498,"Longitude":80.1995449,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:01 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9064042,"Longitude":80.1996276,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:04 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9064291,"Longitude":80.1996743,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:09 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9064742,"Longitude":80.1996894,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:11 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9066028,"Longitude":80.1996954,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:15 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.906695,"Longitude":80.1997065,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:17 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9068293,"Longitude":80.19972,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:20 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9068994,"Longitude":80.1997351,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:21 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9069192,"Longitude":80.19974,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:22 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9070304,"Longitude":80.1997629,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:25 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9071383,"Longitude":80.1997785,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:29 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9071734,"Longitude":80.199762,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:31 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9071759,"Longitude":80.1997505,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:32 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9071759,"Longitude":80.199698,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:35 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9071534,"Longitude":80.1996046,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:39 pm"},{"CompanyId":"416","TechId":"1671","Latitude":12.9071816,"Longitude":80.1994971,"CreatedBy":"1671","CreatedDate":"4/29/2021 02:25:41 pm"}]
</details>

**Comment by christocracy** [comment]
If the OS is under memory pressure, it *will* terminate background-services to free up memory for the currently running app in the foreground.

It is the OS's responsibility to re-launch terminated services in the future when memory is freed up.

The plugin does all it can to ensure that the OS restarts terminated services, by returning [`Service.START_REDELIVER_INTENT`](https://stackoverflow.com/questions/14054588/what-is-start-sticky-start-not-sticky-and-start-redeliver-intent-service) from its services `onStartCommand`.

>Plugin config provided to #ready:

You have not provided the config you're using with the plugin.  Are configuring the plugin with an `url` or are you managing your own HTTP uploads?
