### ISSUE TITLE
Detect permissions

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1261]
I need to show a dialog window to the user before the Android permission screen. If confirm in the window then I want to show the Android permission screen. The dialog window is ready, but first I need to know if the person has authorized. How can I check if the person has granted Android location permissions?

**Comment by fgarcia5** [comment]
I understand that you need use [cordova-plugin-dialog](https://github.com/dpa99c/cordova-diagnostic-plugin) to check the permissions status and get more control about it.

**Comment by christocracy** [comment]
See api docs BackgroundGeolocation.getProviderState
