### ISSUE TITLE
iOS Installation

### ISSUE THREAD

**Issue by luigichiappinelli** [transistorsoft/cordova-background-geolocation-lt#1262]
## Your Environment
* Plugin version: Transistorsoft Studio 4.0.1
* Platform: iOS
* OS version: 14.5
* Device manufacturer / model: Iphone 11 Pro Max
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 6.2.0

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

```

## Expected Behavior

I recently purchased the Transistorsoft Studio License and I would like to insert the plugin within my app, where it will play a fundamental role.
The Android version works fine and very well.

## Actual Behavior
Unfortunately, I was unable to compile the iOS version. I need documentation that fully explains how to install the plugin and compile the iOS version.

## Steps to Reproduce

1. Install XCode and Cordova
2. Open my project
3. Add platform iOS
4. Compile and build my app

## Context

![Inkedscreenshot_LI](https://user-images.githubusercontent.com/73893533/117029171-b13a7100-acfe-11eb-8150-18512ddcbb47.jpg)
![screenshot1](https://user-images.githubusercontent.com/73893533/117029179-b3043480-acfe-11eb-95d6-3a0fef8d3d60.png)

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Customers should post support requests to the [private repo](https://github.com/transistorsoft/cordova-background-geolocation).  Customers should also *install* the plugin from the private repo.  This public repo here is updated only about every 3 months.

Is this a *Capacitor App*?
