### ISSUE TITLE
Location service activated notification showing after app fully closed

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1263]
## Your Environment
* Plugin version:4.0.1
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Vivo
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 9.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Location service activated notification not present after app closed or killed.

## Actual Behavior
Location service activated notification showing after app fully closed

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The issue template asked you to post your Config.

**Comment by Ambikapathi** [comment]
BackgroundGeolocation.ready({
          reset: true,
          debug: false,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          distanceFilter: 5,
          stopTimeout: 1,
          stopOnTerminate: false,
          startOnBoot: true,
          url: myGlobals.ServiceUrl.WorkOrder + "WorkOrder/InsertTrackRoute",
          params: myGlobals.buildGps,
          headers: this.getRequestHeaders(),
          // [Android] backgroundPermissionRationale for Always permission.
          backgroundPermissionRationale: {
            title: "Allow Field power to access this device's location even when closed or not in use.",
            message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'
          },
          autoSync: true
        }, (state) => {
          console.log('- Configure success: ', state);
          // Update UI state (toggle switch, changePace button)
         
        });

**Comment by christocracy** [comment]
> stopOnTerminate: false,

What do you expect?

**Comment by Ambikapathi** [comment]
stopOnTerminate: true
