### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by ravanbhai** [transistorsoft/cordova-background-geolocation-lt#1265]
just i wanted to make Geofencing app in ionic , 
i implemented code but its not working.

 Geofence(){
    BackgroundGeolocation.addGeofence({
      identifier: "Home",
      radius: 10,
      latitude: this.latitude,
      longitude: this.longitude,
      notifyOnEntry: true,
      notifyOnExit: true,
      extras: {
        route_id: 1234
      }
    }).then((success) => {
      console.log("[addGeofence] success");
      this.SenNotification(this.latitude,this.longitude);
    }).catch((error) => {
      console.log("[addGeofence] FAILURE: ", error);
    });
    BackgroundGeolocation.onGeofence(geofence => {
      console.log("[geofence] ", geofence.identifier, geofence.action);
      this.SenNotification(geofence.identifier,geofence.action);
      this.SenSMS();
    });
  }
I am not getting any notification while exit or enter in radius , and also wanted to work in background please help me out

**Comment by christocracy** [comment]
The issue template is *not* optional.  It is **required**.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
