### ISSUE TITLE
backgroundPermissionRationale not being displayed on Android, live app removed from Google Play

### ISSUE THREAD

**Issue by kirkHawksworth** [transistorsoft/cordova-background-geolocation-lt#1268]
## Your Environment
* Plugin version: cordova-background-geolocation-lt 4.0.1 "BackgroundGeolocation"
* Platform: Android
* OS version: 11
* Device manufacturer / model: S20 Ultra 5G
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):   android 9.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
  var bgGeo = window.BackgroundGeolocation;

  var tempConfig = {
    autoSync: true,
    batchSync: false,
    debug: false,
    desiredAccuracy: -2,
    distanceFilter: 30,
    enableLocationTracking: true,
    fastestLocationUpdateInterval: 4000,
    geofenceInitialTriggerEntry: false,
    maxBatchSize: 20,
    notificaitonTitle: "My APP",
    notificationPriority: 0,
    notificationText: "GPS Tracking",
    preventSuspend: true,
    reset: true,
    startOnBoot: true,
    stopOnTerminate: false,
    url: "https://app.myapp.com/submit-geo",
    backgroundPermissionRationale : {
      title: "This is the TITLE of backgroundPermissionRationale",
      message: "This is the MESSAGE of backgroundPermissionRationale",
      positiveAction: "PositiveAction",
      negativeAction: "NagativeAction"
    }
  };
  
  bgGeo.ready(tempConfig, function(state) {
    if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
  });

```

## Expected Behavior

The background permission rationale should be displayed as stated in the config.

## Actual Behavior

The background permission rationale is NOT displayed, I have seen it displayed once, on one device, but after multiple uninstalls, different devices on Android 11 I haven't seen it.

## Steps to Reproduce

1. I call my ```startGeo()``` function which starts the tracking, 'backgroundPermissionRationale' is not displayed
2.
3.
4.

## Context

App has been removed from Google Play (not rejected, our live app has been removed) giving this reason:

Prominent disclosure not found
Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.

Please add a prominent disclosure before the runtime permission.

Remember, your prominent disclosure must:

- Appear before your app’s location runtime permission.
- Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”
- Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
iMac:ANDROID_202105201400 user$ adb logcat *:S TSLocationManager:V
--------- beginning of system
--------- beginning of main
05-26 12:24:44.738 23196 27686 D TSLocationManager: $ ready()
05-26 12:24:44.747 23196 27686 D TSLocationManager: $ start()
05-26 12:24:49.764 23196 27937 I TSLocationManager: - Enable: false → true, trackingMode: 1
05-26 12:24:49.863 23196 27686 D TSLocationManager: $ addGeofenceListener()
05-26 12:24:49.864 23196 27686 D TSLocationManager: $ removeGeofences()
05-26 12:24:49.895 23196 27686 D TSLocationManager: $ addGeofences()
```

</details>

I noticed in a similar issue that was raised (https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1239), you asked to post project.properties from (platforms/android/project.properties)

```
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android Studio Gradle projects

# Project target.
target=android-29
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-firebasex/tcfe-build.gradle
cordova.system.library.1=androidx.appcompat:appcompat:1.2.0
cordova.system.library.2=androidx.legacy:legacy-support-v4:1.0.0
cordova.system.library.3=androidx.legacy:legacy-support-v4:1.0.0
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:17.0.0
cordova.system.library.5=com.google.android.gms:play-services-auth:18.1.0
cordova.system.library.6=com.google.firebase:firebase-analytics:17.5.0
cordova.system.library.7=com.google.firebase:firebase-messaging:20.3.0
cordova.system.library.8=com.google.firebase:firebase-config:19.2.0
cordova.system.library.9=com.google.firebase:firebase-perf:19.0.9
cordova.system.library.10=com.google.firebase:firebase-auth:19.4.0
cordova.system.library.11=com.google.firebase:firebase-inappmessaging:19.1.1
cordova.system.library.12=com.google.firebase:firebase-inappmessaging-display:19.1.1
cordova.system.library.13=com.google.firebase:firebase-firestore:21.7.0
cordova.system.library.14=com.google.firebase:firebase-crashlytics:17.2.2
cordova.system.library.15=com.google.firebase:firebase-crashlytics-ndk:17.2.2
cordova.system.library.16=com.google.code.gson:gson:2.8.6
cordova.system.library.17=androidx.legacy:legacy-support-v4:1.+
cordova.system.library.18=androidx.appcompat:appcompat:1.+
cordova.gradle.include.2=cordova-plugin-background-fetch/tcfe-build.gradle
cordova.system.library.19=com.google.android.gms:play-services-location:16.+
cordova.system.library.20=androidx.appcompat:appcompat:1.2.0
cordova.system.library.21=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.22=org.greenrobot:eventbus:3.0.0
cordova.system.library.23=com.intentfilter:android-permissions:0.1.8
cordova.system.library.24=org.slf4j:slf4j-api:1.7.25
cordova.system.library.25=com.github.tony19:logback-android:2.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/tcfe-build.gradle
```

**Comment by christocracy** [comment]
> target=android-29

Use 30.

See my blog https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353

**Comment by kirkHawksworth** [comment]
Thank you for the quick response. Moving it to 30 did indeed solve the issue.

That blog post is incredibly helpful also, I would suggest adding it to the Android section of the Readme
