### ISSUE TITLE
Simple implementation of plugin in real world apps. (Android)

### ISSUE THREAD

**Issue by salman-ghauri** [transistorsoft/cordova-background-geolocation-lt#127]
Hi Chris,
I think the implementation of the plugin can be made simple so that everyone could easily implement it in their apps and there should be some document about some concise settings to get the plugin up and running.
You have mentioned [here](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/124) that we should use it the sample app code in real apps.
Can you please tell how should the plugin be implemented in real world apps. Can you specify the minimum requirements or settings that should be used in real apps. Should it be started in the app.run()?

What I am doing is:
I have implemented the plugin as a service similar to what you did in sample app. Then I configure the plugin in app run, start it and get the locations. But after that, the locations do not post to url as I have configured in the plugin
i.e distanceFilter: 0, desiredAccuracy: 0. (it works accurately in the sample app but in my app locations are random may be after an hour even if I have traveled a considerable amount of distance)

PS: The sample app behaves very strangely in Android but works fine on iphone.

**Comment by christocracy** [comment]
**3 Easy Steps**

```Javascript
bgGeo = window.BackgroundGeolcoation;

// 1. First attach event-listeners
bgGeo.onLocation(function(location, taskId) {
  console.log('- location: ', location);
  bgGeo.finish(taskId);
});
.
. other event-listeners
.
// 2. Compose your configuration.  DO NOT USE THE Settings SERVICE FROM SampleApp!!!!
var simpleConfig = {
  // Geolocation
  desiredAccuracy: 0,
  distanceFilter: 10,
  locationUpdateInterval: 1000,
  fastestLocationUpdateInterval: 1000,
  // Activity Recognition
  stationaryRadius: 25,
  activityRecognitionInterval: 10000,
  stopTimeout: 5
  // Http Options
  url: 'http://my.server.com/locations'
  autoSync: true
  // Application Options
  debug: true,
  stopOnTerminate: false,
  startOnBoot: true
};

// 3.  configure the plugin.
bgGeo.configure(simpleConfig, function(state) {
  // The plugin is now ready to be used.  It's important to note that the plugin *persists* its #enabled
  // between reboots:  if user closes the app and re-opens, once you #configure, the plugin will have
  // already #start-ed itself.

  if (!state.enabled) {
    bgGeo.start();
  }
});
```

**Comment by christocracy** [comment]
Can you elaborate on "PS: The sample app behaves very strangely in Android but works fine on iphone."?

**Comment by christocracy** [comment]
>Should it be started in the app.run()?

Like **every** Cordova plugin in the universe, you don't interact with the plugin until [deviceready](https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready) event fires.  It's assumed you know this.

In the Ionic universe, the Cordova `deviceready` event is abstracted as:
```Javascript
ionic.Platform.ready(function() {
  var bgGeo = window.BackgroundGeolocation;
  var simpleConfig = {...};
  bgGeo.onLocation(function() {...});
  bgGeo.configure(simpleConfig, function(state) {
    .
    .
    .
  });
});
```
