### ISSUE TITLE
TSLocationManager/TSLocationManager.h' and  Tsbackgroundfetch/tsbackgroundfetch.h'  file not found  when IOS app build in Xcode

### ISSUE THREAD

**Issue by tejashcrest** [transistorsoft/cordova-background-geolocation-lt#1270]
## Your Environment
* Plugin version:^4.0.1
* Platform: iOS
* mac OS version:11.0.1
* Device manufacturer / model: iPhone 8 (14.5)
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
**This Plugin is working perfectly in  android but in IOS app build we are getting below errors** :  
```javascript <!-- syntax-highlighting:  paste your code below -->
**When We build App in xcode we get below errors:**
In file included from /Users/apple/Desktop/testuser/projectname/ios/capacitor-cordova-ios-plugins/sourcesstatic/CordovaBackgroundGeolocationLt/CDVBackgroundGeolocation.m:6:
/Users/apple/Desktop/testuser/projectname/ios/capacitor-cordova-ios-plugins/sourcesstatic/CordovaBackgroundGeolocationLt/CDVBackgroundGeolocation.h:8:9: 
fatal error: 'TSLocationManager/TSLocationManager.h' file not found
#import <TSLocationManager/TSLocationManager.h>

Once we **fix** the error of TSLocationManager.h by **reinstalling the plugin**
we are getting the error of background-fetch.h below : 
 **Tsbackgroundfetch/tsbackgroundfetch.h'  file not found** 
```

## Actual Behavior

![image](https://user-images.githubusercontent.com/21195217/120150121-48182180-c208-11eb-9216-8764ba8361e3.png)

plugins we added  is below,
![image](https://user-images.githubusercontent.com/21195217/120204504-859b9f80-c246-11eb-8583-d5bd7593fbcc.png)
![image](https://user-images.githubusercontent.com/21195217/120152016-96c6bb00-c20a-11eb-9512-fd0c18df7020.png)

**we already install and uninstall this plugin multiple times and update xcode to 12.5**

  Once we **fix** the error of TSLocationManager.h by **reinstalling the plugin**
  we are getting the error of background-fetch.h below : 
   **Tsbackgroundfetch/tsbackgroundfetch.h'  file not found** 
   
**This Plugin is working perfectly in  android but in IOS App build we are getting errors :** 

NOTE: **_We are using capacitor in our project_**

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See the changelog:

https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md

**Comment by christocracy** [comment]
This issue with iOS has been posted multiple times.  Have you searched the issues for previous solutions?

**Comment by tejashcrest** [comment]
yes, we tried previous solutions by **uninstalling and installing plugin and update code,** which is I already mention in our issue details, still, we get an error message

**Comment by christocracy** [comment]
Did you [try this](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1247#issuecomment-819581782)?

**Comment by tejashcrest** [comment]
Yes, we try still get same error message, 
our Pod version: 1.10.1

**Comment by tejashcrest** [comment]
Yes, we try still get same error message,
our Pod version: 1.10.1

**Comment by christocracy** [comment]
> Yes, we try still get same error message,

>our Pod version: 1.10.1

I see you deleted this post.

**Comment by agrisolutionseu** [comment]
I am confirming that upgrade from 2.1.x capacitor to 2.4.7 has impact on this message. After upgrading to this version message disappears. However plugin shouldn't be broken on old capacitor.

**Comment by christocracy** [comment]
Capacitor support is now through capacitor-background-geolocation.
