### ISSUE TITLE
Handling of outlier coordinates at IOS

### ISSUE THREAD

**Issue by Till92921** [transistorsoft/cordova-background-geolocation-lt#1271]
## Your Environment
* Plugin version: "version": "3.9.4"
* Platform: iOS 
* OS version: 14
* Device manufacturer / model: Iphone X 
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:

Available platforms:
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
  locationAuthorizationRequest: 'Always',
        logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: this.distanceFilter,
        debug: this.debug,
        disableElasticity: this.disableElasticity,
        stopOnTerminate: this.stopOnTerminate,
        startOnBoot: this.startOnBoot,
        autoSync: this.autoSync,

```javascript <!-- syntax-highlighting:  paste your code below -->

```

## Expected Behavior

The outlier coordinates are to be filtered out cleanly 

## Actual Behavior

Unfortunately, large jumps are made, which falsify the distance measurement

## Steps to Reproduce
1.
2.
3.
4.

## Context

A 6km march through the Swiss mountains, measuring the distance. 

## Debug logs

![image](https://user-images.githubusercontent.com/65195261/120285135-42c8de80-c2bd-11eb-86f6-2f282ba8109a.png)

![image](https://user-images.githubusercontent.com/65195261/120287610-af44dd00-c2bf-11eb-96e9-9fc48cba5cde.png)

**Comment by christocracy** [comment]
It's your responsibility to filter locations as desired,  use location.coords.accuracy.

**Comment by Till92921** [comment]
@christocracy But as far as I understand it, we only have read access to the sqlite database.

So we have to use our own data structure and filter it?

**Comment by Till92921** [comment]
![image](https://user-images.githubusercontent.com/65195261/121011896-6dbca200-c797-11eb-97cb-01ee6224c2be.png)

Our march event is now over. For the most part, we were able to record usable routes (> 85 %). 

How are the ricochets created technically? 
Does the device switch to the mobile phone masts when determining the position or are too few satellites visible?

**Comment by Till92921** [comment]
**Here is a positive example of the over 85 per cent**

![image](https://user-images.githubusercontent.com/65195261/121012812-63e76e80-c798-11eb-81d4-92cd86eed33b.png)

**Comment by christocracy** [comment]
>How are the ricochets created technically?

It's not known that these are "ricochets".  More likely it's a problem with the user's device / settings.  You did not provide device details (OS version, device model).

>Does the device switch to the mobile phone masts when determining the position or are too few satellites visible?

iOS and Android location-services are a black box.  One configures the `desiredAccuracy` / `distanceFilter` then simply tells native API to start.  The native APIs do all the work.  The public API has no direct control over Satellites or cell towers.

**Comment by Till92921** [comment]
OK, thank you very much for the quick reply. I now close the issue
