### ISSUE TITLE
Heartbeat doesn't stable track geolocation 

### ISSUE THREAD

**Issue by Vasek18** [transistorsoft/cordova-background-geolocation-lt#1272]
## Your Environment
* Plugin version: 4.0.1
* Platform: Android
* OS version: 10+
* Device manufacturer / model: Xiaomi Mi 8, Samsung S10e
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): we are use Capacitor instead
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    autoSync: false,
    stopOnTerminate: false,
    startOnBoot: true,
    preventSuspend: true,
    stationaryRadius: 50,
    locationUpdateInterval: 120000,
    fastestLocationUpdateInterval: 120000,
    heartbeatInterval: 120,
    stopTimeout: 2,
    notification: {
        title: i18n.t('bg_geo.tracking.notification.title'),
        text: i18n.t('bg_geo.tracking.notification.text'),
        color: "#800080",
    }
}
```

## Expected Behavior
We would see a list of locations on the server with timestamps that differ by about 2 minutes

## Actual Behavior

- Sometimes locations differ by only several seconds (we use timestamps of the location from plugin not any our timestamp)
- Sometimes there are hours without any location but we can see notifications from plugin every several minutes

## Steps to Reproduce

1. Make app using config above
2. Design your own system of server pushes and synchronization
3. Start track locations (move for a while)
4. Put phone on a desk

## Context
**To avoid questions about our server pushes system here are some code samples. We are confident in this system**
```
BackgroundGeolocation.onHeartbeat(() => {
    BackgroundGeolocation.getCurrentPosition({samples: 1}).then((location: pluginLocation) => {
        this.handleNewLocation(location); // this method pushes location to server by ionic-native/http
    });
});
BackgroundGeolocation.onLocation((locationFromPlugin: pluginLocation) => {
    this.handleNewLocation(locationFromPlugin);
});
private handleNewLocation = (locationFromPlugin: pluginLocation) => {
    BackgroundGeolocation.insertLocation(locationFromPlugin).then(() => {
        this.getUnsentLocations().then(async (unsentLocations) => {
            await this.sendLocationsToServer(unsentLocations);
        })
    });
}
private async getUnsentLocations(): Promise<pluginLocation[]> {
    // @ts-ignore
    return BackgroundGeolocation.getLocations().then((notSentLocations) => {
        if (!notSentLocations.length) {
            return [];
        }
      
        return notSentLocations;
    });
}
private sendLocationsToServer = (locationsFromPlugin: pluginLocation[]) => {
    // Here we filter duplications by timestamp and change class of locations (in new class there are only uuid, timestamp, coords, accuracy)
    const locations = this.unique(this.transformPluginLocationsToMapslyLocations(locationsFromPlugin));

    return userManager.saveLocationTracking(locations)
        .then(() => {
            BackgroundGeolocation.destroyLocations().then(() => {
                this.log('Locations deleted');
            });
        })
        .catch(() => {
            this.log('Locations not sent');
        });
}
```

_We also noticed that there are more chances of missing locations when the battery is ~<21%_
Also we disable battery restrictions by instructions from https://dontkillmyapp.com/

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Heartbeat is subject to throttling by the OS based upon user activity and battery level.

You will never get a perfectly timed "every 2 minutes".

**Comment by christocracy** [comment]
When the device is detected to be moving, locations will be recorded *exactly* according to Config.distanceFilter.

But when a device is idle, you can expect the OS to throttle heartbeats to protect the user's battery.

**Comment by Vasek18** [comment]
> You will never get a perfectly timed "every 2 minutes".

Yes, we understand. 1, 2, 3, 4, ... minutes is ok. But we are facing gaps like 40 minutes and even hours

> When the device is detected to be moving, locations will be recorded exactly according to Config.distanceFilter.

You can see that instead of we use locationUpdateInterval and fastestLocationUpdateInterval. And they are also 2 minutes

Also we have stationaryRadius of 50m. So the scenario when we get location at heartbeat event, then move device and instantly get new location because of move and have two locations what differ by several seconds is not look realistic

**Comment by Vasek18** [comment]
Two frequent locations we can filter so our main problem - absence of locations for several hours

**Comment by christocracy** [comment]
>absence of locations for several hours

If the device is sitting idle (that's the only time heartbeat event fires), you can assume the device is sitting at the last known position.  What's the point wasting battery having the device say "HERE I AM", "HERE I AM, "HERE I AM", every two minutes?

**Comment by sshurygin** [comment]
Hi @christocracy 
>If the device is sitting idle (that's the only time heartbeat event fires), you can assume the device is sitting at the last known position. What's the point wasting battery having the device say "HERE I AM", "HERE I AM, "HERE I AM", every two minutes?

The idea behind getting heartbeat every 2 minutes is to make sure the phone has not moved to another location while offline. I left the app running whole night, battery level at 70%, but there hadn't been any heartbeat messages in over 7 hours, until I unlocked the phone, at which moment it came. Is it the expected behavior? We were assuming that we may expect the heartbeat at more or less predictable intervals, but if it can go dark for 1/3 of a day, that's hardly a "heartbeat")) Let me know what you think.

**Comment by sshurygin** [comment]
The second issue is that I go out and walk with my Galaxy S10e definitely more than 50 meters but updated locations don't come in (neither does heartbeat), and it doesn't matter if the screen is on or off. During one of the tests the app stopped transmitting locations or heartbeat 2 miles before an airport for 45 minutes, and resumed transmitting location approximately at the same location on the way back. Why could this be happening?

**Comment by christocracy** [comment]
See http://dontkillmyapp.com

**Comment by sshurygin** [comment]
Optimized battery off, app added to Never sleeps - didn't help.

**Comment by sshurygin** [comment]
Am I understand correctly that it is 100% the OS that's interfering with outbound connection and there's nothing more to troubleshoot in the app or the plugin?

**Comment by sshurygin** [comment]
and unless a particular user finds a way to disable this OS-level optimization, there's nothing we can do to ensure regular connections?

**Comment by sshurygin** [comment]
Also, a 3rd problem is that the plugin doesn't seem to be accumulating data when it can't send it to the server. When we get something on the server, it's always exactly 1 event that happened immediately before the connection. Is it a known issue that's also related to the OS-level optimization?

**Comment by christocracy** [comment]
>Am I understand correctly that it is 100% the OS that's interfering with outbound connection and there's nothing more to troubleshoot in the app or the plugin?

That's right.

>there's nothing we can do to ensure regular connections?

That's correct.

>also related to the OS-level optimization?

That's right

There are no known issues with location-tracking behaviour.  I regularly field-test on the following devices and they **always** work, regardless if they've been sitting idle for *days* with the app terminated or device rebooted:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 12
- Samsung Galaxy S20 FE @ 11.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/z715i5i9q4qr0lb/Screen%20Shot%202021-06-04%20at%201.43.50%20PM.png?dl=1)

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/cpjri97lwm16j3h/Screen%20Shot%202021-06-04%20at%201.44.59%20PM.png?dl=1)

**Comment by Vasek18** [comment]
Hi, Chris, we've got logs for you. Phone - Xiaomi Mi 8

* There is geolocation on server at 22:07:35, then there is a gap, and first location after the gap is only at 23:28:08
* Strings, what start with "[bg geo]", are our custom messages. Everything else is from your plugin
* We can see that through out the whole period of no locations there are events and logs from plugin. But no logs from our client code
* We can see that at the gap there are many errors like ":bangbang:  Failed to get last location: com.google.android.gms.tasks.zzu@69580c5"
* Period of errors ended when I explicitly opened the app


[Bg Geo Logs.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/6607622/Bg.Geo.Logs.txt)

**Comment by christocracy** [comment]
Remove `{samples: 1}` from call to `getCurrentPosition`:

```javascript
BackgroundGeolocation.onHeartbeat(() => {
    BackgroundGeolocation.getCurrentPosition().then((location: pluginLocation) => {
        this.handleNewLocation(location); // this method pushes location to server by ionic-native/http
    });
});
```
