### ISSUE TITLE
getCofing method

### ISSUE THREAD

**Issue by monkeydkon** [transistorsoft/cordova-background-geolocation-lt#1274]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

Why is there not a method to get the current `config` ?

## Steps to Reproduce

1.
2.
3.
4.

## Context

I want the users to be able to pick whether to let the app use Cellular network or Wifi only for autoSync.
So, I need to know what option is selected at any time. Is there a good way to do this?

**Comment by christocracy** [comment]
There is.  It's called `getState`

**Comment by monkeydkon** [comment]
And how should i be using it? Will the plugin remember its last state?
I'm asking because you have told me before, to call `ready()` in a main `javascript` file, for it to run ob background.

**Comment by christocracy** [comment]
>And how should i be using it?

See the API docs for example usage.
