### ISSUE TITLE
Where to put purchased key in ios

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1275]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS
* OS version: 6.1.0
* Device manufacturer / model:
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Need to put key for ios

## Actual Behavior
Document shows only key for android.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
iOS is free, only Android consumes keys.
