### ISSUE TITLE
How to remove Location service activated ?

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1276]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS or Android
* OS version: Android
* Device manufacturer / model: Vivo
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):  9.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Need background location tracking without showing location service activated notification.

## Actual Behavior
It showing location service activated notification.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You can't.  The Android OS requires it.
