### ISSUE TITLE
How to stop background tracking 

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1278]
## Your Environment
* Plugin version: 4.0.1
* Platform:  Android
* OS version: Android 8
* Device manufacturer / model: Vivo
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 9.1.0
* Plugin config provided to `#ready`: 
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Need to stop background tracking

## Actual Behavior
Can't able to stop background tracking

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Ambikapathi** [comment]
BackgroundGeolocation.stop(); not working

**Comment by christocracy** [comment]
Yes it does.

**Comment by Ambikapathi** [comment]
BackgroundGeolocation.onLocation(this.onLocation.bind(this));
 BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
above two functions are calling repeatedly, after i calling BackgroundGeolocation.stop();

**Comment by christocracy** [comment]
You're doing something wrong.  You *think* you're calling stop() but you are not.

See wiki *Debugging* and learn to observe the plugin logs through `$ adb logcat`
