### ISSUE TITLE
Schedule doesn't start background tracking on the next day

### ISSUE THREAD

**Issue by Vasek18** [transistorsoft/cordova-background-geolocation-lt#1279]
## Your Environment
* Plugin version: 4.0.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: Xiaomi
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): not a Cordova-based project, Capacitor
* Plugin config provided to `#ready`: 
```javascript <!-- syntax-highlighting:  paste your code below -->
{
  locationAuthorizationRequest: 'Always',
  reset: true,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  autoSync: false,
  stopOnTerminate: false,
  startOnBoot: true,
  preventSuspend: true,
  stationaryRadius: 50,
  locationUpdateInterval: 120000,
  fastestLocationUpdateInterval: 120000,
  heartbeatInterval: 120,
  stopTimeout: 2,
  notification: {
      title: i18n.t('bg_geo.tracking.notification.title'),
      text: i18n.t('bg_geo.tracking.notification.text'),
      color: "#800080",
  },
  schedule: [
"2 9:00-18:00",
"3 9:00-18:00",
"4 9:00-18:00",
"5 9:00-18:00",
"6 9:00-18:00",
"7 9:00-18:00",
"1 9:00-18:00"
]
}
```

## Expected Behavior
At 9am bg tracking starts

## Actual Behavior
Background tracking doesn't start at morning (several hours without opening app)
Even manual app opening does not help

## Steps to Reproduce

1. Use the config above for example at evening. Via ready() or setConfig()
2. Check bg tracking after day start

## Context

```
...
await BackgroundGeolocation.setConfig({schedule: schedule});
...
await BackgroundGeolocation.startSchedule();
// You can initaiate some handlers after startSchedule();
...
```

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Actually no logs after several hours of app work and no logs after day start. So no logs but it is also a clue
```

</details>

**Comment by christocracy** [comment]
See Wiki *Debugging*.  Enable *verbose* logging and learn to fetch logs from plugin using `emailLog`.

**Comment by Vasek18** [comment]
Yes, as you can see, we set logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
And in slack I've show you the gap in logs. And that is why I did't include logs here => we just has no logs until actual app opening nor errors in logs
But. okay, I'll grab logs from today's evening till ~10am for you. Will post them tomorrow

**Comment by Vasek18** [comment]
Hi,
In the evening I had used BackgroundGeolocation.logger.destroyLog() and then didn't touch app till scheduled day start plus a couple of hours
And I have no logs at all. BackgroundGeolocation.logger.getLog() returns an empty string. No logs even from TSScheduleManager

**Comment by christocracy** [comment]
Are you *moving* the device during the scheduled ON period? Go for a little walk, shake the device vigorously (to simulate moving) or unlock the device.

**Comment by Vasek18** [comment]
No, so I'll try
Thank you

**Comment by Vasek18** [comment]
So no problems on Android. Indeed you just need to start moving
However on ios schedule doesn't work
I've created new issue to show your our current config https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1287
