### ISSUE TITLE
Question: Is there a way to switch on location-services programmatically?

### ISSUE THREAD

**Issue by shyamal890** [transistorsoft/cordova-background-geolocation-lt#128]
I was wondering if there was a way to switch on location-services programmatically without user's intervention incase the location-services are switched off.

**Comment by christocracy** [comment]
Are you joking?  Hell no!  You don't own the user's device.  If the user
wants to hide from the world tracking them, there's nothing you can do to
prevent that, and I'm thankful that's the case.

The only thing you can do is detect that error code in your failure
callback and ask them "pretty please, can you turn on location services for
me?"

On Saturday, June 4, 2016, Shyamal Parikh <notifications@github.com> wrote:

> I was wondering if there was a way to switch on location-services
> programmatically without user's intervention incase the location-services
> are switched off.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l8sJuvLwO4qtB8CcQKy4yd1azkMqks5qITTvgaJpZM4IuFQb>
> .
>


-- 
Snet form Gmail Mobile

**Comment by shyamal890** [comment]
This is what I think:

What if the app has already asked "pretty please, can you turn on location services for
me?" and the answer was YES earlier?! It doesn't make sense to keep on asking right? Once the user says yes the app should then be authorized to control location-services. The user always has the option to turn it off from app settings.

**Comment by christocracy** [comment]
When the plugin request "AlwaysUsagePermission", the user has agreed to allow the plugin to engage location-services, even in the background **when they have location-services enabled**.
![]()https://www.dropbox.com/s/w496i6f0o09tqrf/Screenshot%202016-06-04%2013.56.17.png?dl=1)

Later, If the user later decides to **disable** location-services via `Settings->Privacy->Location Services`, there's nothing you can do but show an alert to the user and ask them to turn it back on.  There's no way to programmatically toggle that switch **ON**.
![](https://www.dropbox.com/s/lj25k9w98vfkdbh/Screenshot%202016-06-04%2013.59.27.png?dl=1)

**Comment by christocracy** [comment]
If the user later **revokes** `AlwaysUsagePermission`:
![](https://www.dropbox.com/s/lq284nhi7tbpme4/Screenshot%202016-06-04%2014.02.48.png?dl=1)

The plugin will once again request it:
![](https://www.dropbox.com/s/w496i6f0o09tqrf/Screenshot%202016-06-04%2013.56.17.png?dl=1)

**Comment by shyamal890** [comment]
Thanks a lot @christocracy for the detailed reply. I guess this is for IOS, is there a similar option for android too?
