### ISSUE TITLE
Android 10 device not able to send GPS pings 

### ISSUE THREAD

**Issue by G93692** [transistorsoft/cordova-background-geolocation-lt#1280]
## Your Environment
* Plugin version: 3.9.2
* Platform: Android
* OS version: Android Q onwards
* Device manufacturer / model: Samsung note 10 & 11
* Cordova version (`cordova -v`): 
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```
 BackgroundGeolocation.ready(
  {
          locationAuthorizationRequest: 'Always',
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
          distanceFilter: distanceFilter, //Approximately 800 meters
          disableElasticity: true,
          useSignificantChangesOnly: false, //set either useSignificantChangesOnly or distanceFilter; not both
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: false,
          allowIdenticalLocations: true, // Android only
          autoSync: true,
          url: locationURL,
          headers: {
            'Ocp-Apim-Subscription-Key': KEYS.SUBSCRIPTION_KEY,
            Authorization: 'Bearer ' + vault
          },
          extras: {
                messageType: MESSAGE_TYPE.GEO_POSITION,
                activity: _activity,
                shipmentId: _shipmentID,
                carrierScac: _carrierScac,
                userId: _userId,
                sourceSystem: _sourceTMS,
                carrierId: _carrierId,
                stopId,
                sequenceNo,
                locationId
          }
    })

## Expected Behavior

GPS pings would be fuccessfully sent to Backend
## Actual Behavior

400 Bad Request response status code is received
## Steps to Reproduce

1.  BackgroundGeolocation.start()
2. non of the GPS ping will be received by Backend
## Context

This issue only reproduce in Android 10 devices. This is an intermittent issue. Once the issue is replicated non of the GPS ping is sent to Backend. BAD REQUEST always received by device. 24 hrs later if user kill the app and start the BackgroundGeolocation, it is working as expected.
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki Debugging.  Learn to observe logcat logs from the plugin.

Use targetSdkVersion 30

**Comment by G93692** [comment]
Okay, Thanks Chris Scott

**Comment by G93692** [comment]
Hi Chris,
We have received "bad request" as an error, Would you please suggest to resolve this issue?

**Comment by christocracy** [comment]
Consult with your server as to why it thinks it's a "Bad Request".
