### ISSUE TITLE
sometimes the plugin stops sending the locations

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1282]
## Your Environment
* Plugin version: 4.1.2
* Platform: Android
* OS version:  Generally all OS
* Device manufacturer / model: Xiaomi Redmi Note 8
* Cordova version (`cordova -v`): latest
* Cordova platform version (`cordova platform ls`): latest
* Plugin config provided to `#ready`: 
```javascript 
var bgGeo = window.BackgroundGeolocation;
			bgGeo.ready({
			reset: true,
			debug: false,
			notification: {
				title: "",
				text: ""
			  },
			logLevel: bgGeo.LOG_LEVEL_VERBOSE,
			desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
			distanceFilter: 100,
			locationAuthorizationRequest: 'Always',
				backgroundPermissionRationale: {
				title: "Lütfen, {applicationName} 'ın lokasyon erişimine izin verin.",
				message: ".",
				positiveAction: "İzin verin '{backgroundPermissionOptionLabel}'",
				negativeAction: "İptal"
				},
			url: '',
			autoSync: true,
			stopOnTerminate: false,
			extras: {
				
			  },
			startOnBoot: true
			}, function(state) {    // <-- Current state provided to #configure callback
			// 3.  Start tracking
			console.log('BackgroundGeolocation is configured and ready to use');
			if (!state.enabled) {
			  bgGeo.start().then(function() {
				console.log('- BackgroundGeolocation tracking started');
			  });
			}
		  });
```

## Expected Behavior

Hi @christocracy , sometimes the plugin stops sending the location and starts sending again after 5-6 hours, what could be the reason? Could this be related to (https://dontkillmyapp.com)? I think the device interrupts my transactions because I send too many locations. Do I need extra permission from the user for this, what can I do?  Is there a plugin I can use for this?

## Steps to Reproduce

1. 
2.
3.
4.

## Debug logs

<details>
<summary>Logs</summary>
```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
</details>

**Comment by christocracy** [comment]
The plugin requests all required permissions.

See wiki *Debugging*

**Comment by Vasek18** [comment]
I bet the problem is related to https://dontkillmyapp.com
