### ISSUE TITLE
Issue installing cordova-background-geolocation-lt 

### ISSUE THREAD

**Issue by webtegy** [transistorsoft/cordova-background-geolocation-lt#1283]
## Your Environment
* Plugin version: cordova-background-geolocation-lt 4.1.2 
* Platform: iOS 
* OS version: macOS BigSur 11.4
* Device manufacturer / model: Apple MacPro M1
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):  Installed platforms:
  ios 6.2.0
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0

## Expected Behavior
Installing cordova-background-geolocation-lt
## Actual Behavior
Failed to install 'cordova-background-geolocation-lt': Error: pod: Command failed with exit code 1 Error output:
Searching for inspections failed: undefined method `map' for nil:NilClass
    at ChildProcess.whenDone (/Users/webapptegy/DEV/EcoRyd/EcoRyd/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
pod: Command failed with exit code 1 Error output:
Searching for inspections failed: undefined method `map' for nil:NilClass

## Steps to Reproduce

1. ionic cordova plugin add  cordova-background-geolocation-lt

## Context
Adding platform iOS. 

## Debug logs

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```
$ pod --version
```

**Comment by webtegy** [comment]
$ pod --version.   1.10.1

**Comment by christocracy** [comment]
Have you [googled your error](https://www.google.com/search?q=Searching+for+inspections+failed%3A+undefined+method+map%27+for+nil%3ANilClass+at+ChildProcess.whenDone&rlz=1C5CHFA_enCA816CA816&oq=Searching+for+inspections+failed%3A+undefined+method+map%27+for+nil%3ANilClass+at+ChildProcess.whenDone&aqs=chrome..69i57.437j0j7&sourceid=chrome&ie=UTF-8)?

**Comment by christocracy** [comment]
What version of Ionic are you using?

**Comment by webtegy** [comment]
sudo arch -x86_64 gem install ffi. fixed the issue. 
ionic -v 6.16.3
Thanks
