### ISSUE TITLE
Android error: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by mikepaterson** [transistorsoft/cordova-background-geolocation-lt#1284]
## Your Environment
* Plugin version: latest
* Platform: Android
* OS version: 7 & 11
* Device manufacturer / model: Acer tablet (older model) & Samsung A51
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`): 9.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
        BackgroundGeolocation.ready({
          reset: true,
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          stationaryRadius: 25,
        }, (state) => {
          if (!state.enabled) {
            BackgroundGeolocation.start();
          }
        });

```

## Expected Behavior
Plugin should initialize and function correctly. 

## Actual Behavior
Plugin does not initialize. When any method on BackgroundGeolocation is called there is no error, and no callbacks fire (either success or failure).   Looking in the device log there is a java error included below.

## Steps to Reproduce

1. Any method call

## Context

Just start location tracking

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
07-14 11:43:03.412 6587-6678/com.firestitch.dev.tasteadvisor W/System.err:     at com.transistorsoft.locationmanager.b.b.T(SourceFile)
        at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.P(SourceFile:116)
        at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(SourceFile:110)
        at org.apache.cordova.CordovaPlugin.privateInitialize(SourceFile:58)
        at org.apache.cordova.PluginManager.getPlugin(SourceFile:178)
        at org.apache.cordova.PluginManager.exec(SourceFile:129)
        at org.apache.cordova.CordovaBridge.jsExec(SourceFile:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SourceFile:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.transistorsoft.tslocationmanager.a.d(SourceFile)
        at com.transistorsoft.locationmanager.b.b.<clinit>(SourceFile)
    	... 12 more
```

</details>

**Comment by christocracy** [comment]
Show me your package.json

**Comment by mikepaterson** [comment]
{
  "name": "tasteadvisor",
  "license": "MIT",
  "config": {
    "env": "local",
    "platform": "web",
    "brand": "tasteadvisor"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "^9.0.6",
    "@angular/cdk": "^9.1.2",
    "@angular/common": "^9.0.6",
    "@angular/compiler": "^9.0.6",
    "@angular/core": "^9.0.6",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.0.6",
    "@angular/http": "^7.2.9",
    "@angular/material": "^9.1.2",
    "@angular/platform-browser": "^9.0.6",
    "@angular/platform-browser-dynamic": "^9.0.6",
    "@angular/platform-server": "^9.0.6",
    "@angular/router": "^9.0.6",
    "@auth0/angular-jwt": "^2.1.0",
    "@firestitch/account-picker": "^8.0.0",
    "@firestitch/account-status": "^8.0.0",
    "@firestitch/address": "^8.4.4",
    "@firestitch/admin": "^8.3.18",
    "@firestitch/api": "^8.1.9",
    "@firestitch/attribute": "^9.1.4",
    "@firestitch/autocomplete": "^8.8.5",
    "@firestitch/autocomplete-chips": "^8.3.3",
    "@firestitch/badge": "^8.0.0",
    "@firestitch/body": "^7.1.0",
    "@firestitch/build": "^9.2.1",
    "@firestitch/checkboxgroup": "^8.1.1",
    "@firestitch/chip": "^8.0.0",
    "@firestitch/clear": "^8.0.0",
    "@firestitch/colorpicker": "^8.1.3",
    "@firestitch/common": "^8.0.1",
    "@firestitch/connection": "^7.0.1",
    "@firestitch/core": "^7.2.1",
    "@firestitch/date": "^8.0.2",
    "@firestitch/datepicker": "8.2.3",
    "@firestitch/dialog": "^8.1.1",
    "@firestitch/drawer": "^8.3.7",
    "@firestitch/duration": "^8.0.0",
    "@firestitch/editor": "^8.1.1",
    "@firestitch/exif-js": "^2.3.0",
    "@firestitch/field-editor": "^8.1.5",
    "@firestitch/file": "^8.5.1",
    "@firestitch/file-manager": "^9.0.0",
    "@firestitch/filter": "^8.7.2",
    "@firestitch/froala": "^1.0.1",
    "@firestitch/form": "^9.2.3",
    "@firestitch/gallery": "^8.2.5",
    "@firestitch/html-editor": "9.3.4",
    "@firestitch/icon-picker": "^8.1.1",
    "@firestitch/import": "^8.0.2",
    "@firestitch/jsplumb": "^2.12.0",
    "@firestitch/label": "^8.2.5",
    "@firestitch/link": "^8.0.4",
    "@firestitch/list": "^9.0.0",
    "@firestitch/mask": "^8.3.0",
    "@firestitch/menu": "^9.1.3",
    "@firestitch/message": "^8.1.0",
    "@firestitch/model": "^7.3.5",
    "@firestitch/pane": "^7.0.3",
    "@firestitch/password": "^8.1.0",
    "@firestitch/phone": "^8.1.0",
    "@firestitch/progress": "^8.0.0",
    "@firestitch/prompt": "^8.4.1",
    "@firestitch/radiogroup": "^8.1.1",
    "@firestitch/rating": "^7.0.12",
    "@firestitch/schematics": "^7.3.10",
    "@firestitch/scroll": "^8.0.0",
    "@firestitch/scroll-picker": "^8.0.0",
    "@firestitch/scrollbar": "^7.0.4",
    "@firestitch/select": "^7.0.0",
    "@firestitch/selectbutton": "^8.0.0",
    "@firestitch/selection": "^8.1.0",
    "@firestitch/share": "^9.0.2",
    "@firestitch/sidenav": "^8.1.2",
    "@firestitch/signin-security": "^8.2.0",
    "@firestitch/skeleton": "^8.1.4",
    "@firestitch/store": "^8.0.0",
    "@firestitch/style": "^8.1.2",
    "@firestitch/system": "^8.3.1",
    "@firestitch/tab": "^7.0.3",
    "@firestitch/toggle": "^8.0.0",
    "@firestitch/transfer": "^8.0.0",
    "@firestitch/tree": "^9.1.0",
    "@firestitch/truncate": "^9.0.2",
    "@firestitch/upload": "^8.0.1",
    "@firestitch/wizard": "^7.0.5",
    "@firestitch/zoom-pan": "^7.0.3",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.15",
    "@fortawesome/free-brands-svg-icons": "^5.7.2",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "@ionic-native/core": "^5.7.0",
    "@ionic-native/deeplinks": "^5.10.0",
    "@ionic-native/splash-screen": "^5.8.0",
    "@ionic-native/status-bar": "^5.7.0",
    "@ionic/angular": "^5.1.1",
    "cordova-background-geolocation-lt": "^4.1.2",
    "@ngx-loading-bar/http": "^2.1.2",
    "@ngx-loading-bar/http-client": "^2.1.2",
    "@ngx-share/button": "^7.1.2",
    "@ngx-share/buttons": "^7.1.2",
    "@ngx-share/core": "^7.1.2",
    "@types/googlemaps": "^3.30.18",
    "agm-overlays": "^2.0.0",
    "anchorme": "^1.1.2",
    "angulartics2": "^7.5.2",
    "angularx-social-login": "^2.2.1",
    "autolinker": "^1.6.2",
    "camelcase-keys": "^6.2.1",
    "color": "^3.1.1",
    "core-js": "^2.6.5",
    "date-fns": "^2.5.0",
    "date-fns-tz": "^1.0.8",
    "fileapi": "2.0.27",
    "imask": "^5.2.1",
    "iscroll": "^5.2.0",
    "jsplumb": "^2.9.0",
    "lodash-es": "^4.17.11",
    "ng-intercom": "^8.0.2",
    "ng2-dragula": "^2.1.1",
    "ng2-social-share": "0.0.10",
    "ngx-clipboard": "12.1.2",
    "ngx-device-detector": "^1.3.6",
    "ngx-take-until-destroy": "^5.4.0",
    "ngx-toastr": "^12.0.0",
    "node-sass": "^4.12.0",
    "offline-js": "^0.7.19",
    "tributejs": "^5.1.3",
    "quill": "^1.3.6",
    "quill-delta-to-html": "^0.10.7",
    "rxjs": "6.5.4",
    "snakecase-keys": "^3.1.2",
    "tslib": "^1.10.0",
    "tsmodels": "^0.4.6",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.6",
    "@angular/cli": "^9.0.6",
    "@angular/compiler-cli": "^9.0.6",
    "@firestitch/codegenerator": "^7.3.5",
    "@firestitch/nav": "^8.0.7",
    "@firestitch/npm-cross-var": "^0.1.0",
    "@types/jasmine": "3.3.9",
    "@types/node": "^12.11.1",
    "@types/quill": "^2.0.2",
    "bestzip": "^2.1.2",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "move-cli": "^1.2.1",
    "npm-run-all": "^4.1.5",
    "protractor": "^5.4.2",
    "ts-node": "~8.0.3",
    "tslint": "^5.14.0",
    "typescript": "3.8.3",
    "xmldom": "^0.1.27",
    "xpath": "^0.0.27",
    "prompts": "^2.3.2"
  }
}

**Comment by ShaunEngel** [comment]
Is this due to a setting parameter issue?

**Comment by christocracy** [comment]
No.  Are you getting this only on release build?

**Comment by mikepaterson** [comment]
No, this is during a debug build.

**Comment by christocracy** [comment]
Create a simple *Hello World* app and test the plugin in isolation.

**Comment by mikepaterson** [comment]
Seems it was some kinda conflict with either cordova-plugin-enable-multidex or cordova-plugin-proguard

**Comment by Farmin1** [comment]
> No. Are you getting this only on release build?

I am getting this error only on release builds. Debug builds works fine. Do u have an idea of what could be causing it?

**Comment by christocracy** [comment]
You have minifyEnabled in your gradle and are not including the plugin's required proguard-rules, thus re-minifyIng the already minified TSLocationManager.aar.
