### ISSUE TITLE
Question: Is timestamp in location data schema UTC time?

### ISSUE THREAD

**Issue by shyamal890** [transistorsoft/cordova-background-geolocation-lt#129]

**Comment by christocracy** [comment]
The wiki is full of great info, such as the Location Data Schema:

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema#http-post-schema

On Saturday, June 4, 2016, Shyamal Parikh <notifications@github.com> wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/129>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l2Ha8_ZH51bH3_uKz53lNKAE-OMJks5qITXlgaJpZM4IuFTb>
> .
>


-- 
Snet form Gmail Mobile
