### ISSUE TITLE
Not every device returns all data.

### ISSUE THREAD

**Issue by willemjanvankranenburg** [transistorsoft/cordova-background-geolocation-lt#1297]
## Your Environment
* Plugin version: 4.0.1
* Platform: Android
* OS version: Android 10
* Device manufacturer / model: Samsung
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): Android 8.1.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
const config: Config = {
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    reset: true,
    foregroundService: true,
    notification: {
        title: this.appName,
        text: 'This app is using your GPS'
    },
    backgroundPermissionRationale: {
        title: `${this.appName} Background GPS`,
        message: 'In order to track your device in the background, please enable {backgroundPermissionOptionLabel} location permission',
        positiveAction: 'Go to {backgroundPermissionOptionLabel}',
        negativeAction: 'Cancel'
    },
    distanceFilter: 20,
    locationUpdateInterval: 20000,
    fastestLocationUpdateInterval: 20000,
    disableStopDetection: false,
    allowIdenticalLocations: false,
    params: {
        user: this.userId,
        handled: false,
        route: this.routeId
    },
    isMoving: true
};
```

## Expected Behavior
All device returning the correct and same data.

## Actual Behavior
Almost all devices returning the correct data, with coords and activity. But some devices only return 'location'.

An example of correct data:
![image](https://user-images.githubusercontent.com/31033654/130766445-94c6d1d5-b5c4-4980-b9c1-473ad1ab235f.png)
An example of a device missing data:
![image](https://user-images.githubusercontent.com/31033654/130766551-3b43f101-b203-459a-80c4-e77d6424cf16.png)

The device that sends the incorrect data has internet, and our app has access to the GPS of the device:
![image](https://user-images.githubusercontent.com/31033654/130766804-8024b560-09ec-4431-b816-a656d984653d.png)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
What is the specific device model and OS version having problems?

**Comment by willemjanvankranenburg** [comment]
The device in the example is a Samsung A10 with Android 9.

**Comment by christocracy** [comment]
See Wiki *Debugging* and use `emailLog` to provide log file while reproducing this.
