### ISSUE TITLE
It is possible to customize the data sent pro server via Method PUT?

### ISSUE THREAD

**Issue by ivanssa** [transistorsoft/cordova-background-geolocation-lt#130]
Hello I'm trying work  my server in data entry that requires the use of the PUT method but I need to post a data structure specifies so I would know:

1- How is it possible to disable sending all standard location information, and customize sending only the items defined in params?

2 How is it possible to add the lat and lng coords in node called cords and latitude e longitude in child?

Example:

{ "Coords":
{ "Latitude": "- 12.12345", "longitude": "- 38.12345"},
"Timestamp": 1465044290
, "Type": "BgGeo"}

I tried this way but the error

HTTP / SQLite config
url: 'http://myserverexample.com/'
method, 'PUT'
AutoSync: true,
maxDaysToPersist: 1,
headers: {
"X-FOO", "bar"
},
params: {
coords ":
        "Latitude": "coords.latirude", "longitude": coords.longitude}
"Timestamp": 1465044290
, "Type": "BgGeo"
}

**Comment by christocracy** [comment]
In the HTTP Config section of the docs, is a param called #method
https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#http--persistence-options

As for the location Schema, you cannot change it, it's inflexible.  You
must change your server to accept this schema.

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema#http-post-schema

On Saturday, June 4, 2016, Navis <notifications@github.com> wrote:

> Hello I'm trying work my server in data entry that requires the use of the
> PUT method but I need to post a data structure specifies so I would know:
>
> 1- How is it possible to disable sending all standard location
> information, and customize sending only the items defined in params?
>
> 2 How is it possible to add the lat and lng coords in node called cords
> and latitude e longitude in child?
>
> Example:
>
> { "Coords":
> { "Latitude": "- 12.12345", "longitude": "- 38.12345"},
> "Timestamp": 1465044290
> , "Type": "BgGeo"}
>
> I tried this way but the error
>
> HTTP / SQLite config
> url: 'http://myserverexample.com/'
> method, 'PUT'
> AutoSync: true,
> maxDaysToPersist: 1,
> headers: {
> "X-FOO", "bar"
> },
> params: {
> coords ":
>         "Latitude": "coords.latirude", "longitude": coords.longitude}
> "Timestamp": 1465044290
> , "Type": "BgGeo"
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/130>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l2af5FNTZd0_betm7bxJN1x302Cxks5qIYZXgaJpZM4IuIuK>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ivent** [comment]
Thank you again, it worked, their work is amazing ....

**Comment by ivanssa** [comment]
Thank you again, it worked, their work is amazing ....
