### ISSUE TITLE
is this plugin doesn't works on Huawei phones (HMS)?

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1300]
* Plugin version: 4.1.2
* Platform: Huawei
* OS version: Android 10
* Device manufacturer / model: JNY-LX1
* Cordova version (`cordova -v`): latest
* Cordova platform version (`cordova platform ls`): latest
* Plugin config provided to `#ready`:

is this plugin doesn't works on Huawei phones (HMS)? I asked Huawei technical support and they said the map is not compatible with HMS. Their answer : https://ibb.co/X5C7fnV

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
No.  Huawei HMS is not supported.

**Comment by christocracy** [comment]
I've been playing with the [Huawei Convertor](https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/convertor-0000001050147221):  Huawei support is coming soon.

**Comment by mehmetkaynak** [comment]
> I've been playing with the [Huawei Convertor](https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/convertor-0000001050147221): Huawei support is coming soon.

Nice to see this.

**Comment by christocracy** [comment]
It’s going to require a separate license key for $99.

**Comment by christocracy** [comment]
Who wants to be *the first* to test it?  Installed the plugin from this repo (branch `#hms`)

(*insert* `ionic` if using that).
```bash
$ [ionic] cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git#hms
```

Unfortunately, I discovered *after purchase* that my __`$650`__ *Nova 9 SE* does not have a *Gyroscope* and HMS `ActivityRecognition` API doesn't work when *Gyroscope* is missing.  *Google Play Services'* `ActivityRecognition` API will still work with at least an *accelerometer*.

```
TSLocationManager: ╔═════════════════════════════════════════════
TSLocationManager: ║ DEVICE SENSORS
TSLocationManager: ╠═════════════════════════════════════════════
TSLocationManager: ╟─ ✅  ACCELEROMETER: {Sensor name="acc_s004_002 Accelerometer Non-wakeup", vendor="Kionix", version=132096, type=1, maxRange=78.45318, resolution=0.0023928226, power=0.145, minDelay=2500}
TSLocationManager: ╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
TSLocationManager: ╟─ ✅  MAGNETOMETER: {Sensor name="mag_s004_001 Magnetometer Non-wakeup", vendor="QST", version=258, type=2, maxRange=4912.0, resolution=0.1, power=1.1, minDelay=10000}
TSLocationManager: ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="sns_smd  Wakeup", vendor="qualcomm", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.025, minDelay=-1}
TSLocationManager: ╚═════════════════════════════════════════════
```
