### ISSUE TITLE
iOS app failed to generate while updating the plugin from 3.7.0 to 4.1.3

### ISSUE THREAD

**Issue by CreetionMotia** [transistorsoft/cordova-background-geolocation-lt#1305]
## Your Environment
* Plugin version: 4.1.3 (The latest)
* Platform: iOS 
* OS version: -
* MABS version (7.1 (latest from Outsystems)
* Cordova iOS engine 6.1.1 for iOS apps
* Cordova Android engine 9.0.0 for Android apps
* Cordova Command Line Tool (CLI) 10.0.0.
* CocoaPods version 1.10.0.

## Expected Behavior
Build the app in iOS. After the plugin has been updated from 3.7.0 to 4.1.3.

## Actual Behavior
Getting an issue while building in iOS. (In android it is correctly building). 

## Context
I have tried to update the plugin from version 3.7.0 to 4.1.3. The version 3.7.0 works and builds correctly for Android and iOS. However the plugin version 4.1.3. somehow fails to build for iOS, but successfully builds for Android.  It seems that this issue might be related to the fact that the plugin is using an architecture that isn't supported (arm64). 

## Debug logs
```<!-- Syntax highlighting:  DO NOT REMOVE -->
[2021-09-08T08:37:14.045Z] [VERBOSE] [Build] Undefined symbols for architecture arm64:
[2021-09-08T08:37:14.047Z] [VERBOSE] [Build] "_OBJC_CLASS_$_DDOSLogger", referenced from:
[2021-09-08T08:37:14.047Z] [VERBOSE] [Build] objc-class-ref in TSLocationManager(TSLog.o)
[2021-09-08T08:37:14.056Z] [VERBOSE] [Build] ld: symbol(s) not found for architecture arm64
```
</details>

**Comment by christocracy** [comment]
What version XCode?

**Comment by CreetionMotia** [comment]
Hi Christocracy,

We are using Xcode version 12.2
https://success.outsystems.com/Support/Release_Notes/Mobile_Apps_Build_Service_Versions

If additional information is required, please let me know!

**Comment by christocracy** [comment]
You need to upgrade XCode

**Comment by christocracy** [comment]
Btw, I see your support subscription has expired.

**Comment by CreetionMotia** [comment]
I will contact the party responsible to see if Xcode can be updated.
I was not aware of any support subscription, my apologies. Thank you for your input.

**Comment by christocracy** [comment]
> I was not aware of any support subscription, 

Login to the customer dashboard at https://www.transistorsoft.com (see Customer Login)
