### ISSUE TITLE
Ios logs gaps during movement

### ISSUE THREAD

**Issue by Vasek18** [transistorsoft/cordova-background-geolocation-lt#1306]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS or Android: ios
* OS version: 14.7.1
* Device manufacturer / model: iPhone XR
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`): not a Cordova-based project, Capacitor
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization = {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 1;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 0;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 100;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 1;
    extras = {
        platform = ios;
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers = {
        Authorization = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MzE3MDI0MDMsImV4cCI6MTYzMjMwNzIwMywicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpZCI6MTE3NSwiYWNjb3VudElkIjo1OTcsInNzb1Byb3ZpZGVyIjpudWxsfQ.KNKa7WghJd5_BnF_mAPSOzxu7-172X33U4LysSlpN01aK_-qv0aLlSrFn_dRaetWRBRZIx7nh5wimxBoNG2VzjZ6IbncMg09vAY6vCi9K0kwYf6MHkgVVVpdGmh2oVY1gIXSDGjVhToqzn94vyjV-ou1psJB_G1pga4shSuRJZ5t7VJJpNaLdLgu7YtbppE9U5wAUrdzJwDt-cPiULMdz8TWMLkvFFdbs8eUY91ytfiXDCUP_2aYbv5YWl2S0_0yHhiM8C3MyGsBPh-rcjwtScpUdG__IO556rrDifmVy4_ztiAh1khHEW92e9P978E15E8fV2M8tBdghxD1kVg9qbnLyI-6hpJK7sl2nWUA1HKoYacufNx39lw-TeVNE8WodnlmBSUGLG3ol_P-GkK21XrI_dwkyEaNMc6Ubf5UVolgYPUdYvGSKwdHVIO-MQZ8HWREpUgzPcWQT7T-JBeKOjZg8gw4f74JPxxQnDFjOzg6-eWcjJS-yGphnyNMBU5OAXH2U2c1frzhM0fhP20fOq7CZCPMpPGBPXoB0dW0y46G6_4iHYouqejcWtpdRNzRYyq4VBCayqjeM__UnCngh3SUd4WA9q0F5-KtwBeTUVA_eWVjf63QwYb5uCZOL6JzX-a5nviPMksuBUr3-ye4yxXxGQtcv-smnfXGOhQFkfY";
    };
    heartbeatInterval = 120;
    httpRootProperty = locations;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert = {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = 20;
    maxDaysToPersist = 3;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "4832.175934938634";
    params = {
    };
    pausesLocationUpdatesAutomatically = 1;
    persistMode = 2;
    preventSuspend = 1;
    schedule = (
        "2 9:00-23:00",
        "6 11:15-11:35",
        "3 21:40-22:00",
        "5 9:00-18:00",
        "4 8:30-17:41"
    );
    schedulerEnabled = 1;
    showsBackgroundLocationIndicator = 1;
    startOnBoot = 1;
    stationaryRadius = 50;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 2;
    trackingMode = 1;
    url = "https://api.mapsly.com/location_tracking/save";
    useSignificantChangesOnly = 0;
}
```

## Expected Behavior
2 walks further 500 meters: 14.09.2021 12:40-22:00 and 15.09.2021 10:55-11:35 should be tracked

## Actual Behavior
As you can see there are no logs during this periods. Also we've got no locations on a server. It worth to mention that device had no internet connection during the periods

## Steps to Reproduce

1. Turn tracking on or trigger it by schedule
2. Turn off internet connection
3. Go on a walk for ~1km 

## Context
We remember about your advice to increase stopTimeout parameter (it is being tested now). But could the stopTimeout be the only reason for this silence?
Or does the plugin requires internet connection to work?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
I've attached them as a file due to maximum characters constrain
```

</details>
[background-geolocation (10).log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/7170119/background-geolocation.10.log.gz)

**Comment by christocracy** [comment]
>not a Cordova-based project, Capacitor

Why are you not using [`capacitor-background-geolocation`](https://github.com/transistorsoft/capacitor-background-geolocation) instead?  It is the same native libraries "under the hood" and is not a cause of tracking issues but you should use the Capacitor version with Capacitor projects.

**Comment by christocracy** [comment]
>Turn off internet connection

How *exactly* are you "turning off internet connection".  If you're turning off Wifi, that is your problem, since both iOS and Android use Wifi signals to fire geofences.  The plugin uses a geofence around the last known position in order to determine that the device is moving when the *EXIT* event fires (typically after ~200 meters of movement).

**Comment by Vasek18** [comment]
> Why are you not using capacitor-background-geolocation instead? It is the same native libraries "under the hood" and is not a cause of tracking issues but you should use the Capacitor version with Capacitor projects.

We've started to use current library at May. It was before you've created separate one for Capacitor. Now it looks like a big risk to replace it

> How exactly are you "turning off internet connection". If you're turning off Wifi, that is your problem, since both iOS and Android use Wifi signals to fire geofences.

So should wi-fi always be turned on? Wouldn't it cause battery drains?

> The plugin uses a geofence around the last known position in order to determine that the device is moving when the EXIT event fires (typically after ~200 meters of movement).

Doesn't physical activity monitor help to determine that the device is moving?

**Comment by christocracy** [comment]
>Now it looks like a big risk to replace it

What sort of "risk" do you think there is?  Is is the exact same native iOS / Android libraries used in all versions of the plugin for *Cordova*, *Capacitor*, *React Native* and *Flutter*.  There is no difference in plugin behaviour.

>So should wi-fi always be turned on?

Yes.

>Wouldn't it cause battery drains?

No.

>Doesn't physical activity monitor help to determine that the device is moving?

iOS disallows the MotionAPI to operate in the background unless location is currently being monitored in the background.  Location API is not turned on until the plugin's stationary geofence EXIT event fires.  Geofences won't fire in the typical 200 meters unless Wifi is ON.  If Wifi is OFF, the device will have to travel at least 1000 meters before the geofence exit fires.

**DO NOT TURN OFF WIFI**.

**Comment by Vasek18** [comment]
> What sort of "risk" do you think there is? Is is the exact same native iOS / Android libraries used in all versions of the plugin for Cordova, Capacitor, React Native and Flutter. There is no difference in plugin behaviour.

If there is no difference what is the point for us to change plugin?

> DO NOT TURN OFF WIFI.

Ok, thanks, we've heard you

**Comment by christocracy** [comment]
>If there is no difference what is the point for us to change plugin?

You will eventually encounter build issues (eg: when new iOS / Android versions are released).  I'm no longer interested in supporting the Cordova version with Capacitor apps.

The next time you have a build issue with the Cordova version, I'm simply going to say "Sorry, I suggest you migrate to the Capacitor version".

**Comment by Vasek18** [comment]
Hi,

Do we need to generate a new license key if we migrate to capacitor's plugin?

**Comment by christocracy** [comment]
**Cordova** Background Geolocation keys do not work with **Capacitor** Background Geolocation.

**Comment by Vasek18** [comment]
Does this mean that we should purchase new license or we can just generate new key at Customer Dashboard?

**Comment by christocracy** [comment]
It means you need to purchase a *Capacitor* license.
