### ISSUE TITLE
Build error rising when using cordova-plugin-fcm-with-dependecy-updated

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1307]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS or Android : IOS
* OS version: 5.1.1
* Device manufacturer / model:
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
No Build issue

## Actual Behavior
Can't able to take build using both cordova geolocation lt and cordova-plugin-fcm-with-dependecy-updated gives build error

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You're not going to provide any specific details about this "build issue"?

**Comment by Ambikapathi** [comment]
'FirMessaging' has different definitions in different modules
