### ISSUE TITLE
heartbeat not working

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1309]
## Your Environment
* Plugin version: 4.1.2
* Platform: iOS or Android
* OS version: ios 14.7
* Device manufacturer / model: iPhone 11
* Cordova version (`cordova -v`): latest
* Cordova platform version (`cordova platform ls`): latest
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
var bgGeo = window.BackgroundGeolocation;
			bgGeo.ready({
			reset: true,
			debug: false,
			notification: {
				title: "",
				text: ""
			  },
			logLevel: bgGeo.LOG_LEVEL_VERBOSE,
			desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
			distanceFilter: 100,
			locationAuthorizationRequest: 'Always',
				backgroundPermissionRationale: {
				title: "Lütfen, {applicationName} 'ın lokasyon erişimine izin verin.",
				message: ".",
				positiveAction: "İzin verin '{backgroundPermissionOptionLabel}'",
				negativeAction: "İptal"
				},
			url: '',
			autoSync: true,
			stopOnTerminate: false,
			extras: {
				
			  },
			startOnBoot: true,
			heartbeatInterval:60,
			preventSuspend:true,
			foregroundService:true
			}, function(state) {    // <-- Current state provided to #configure callback
			// 3.  Start tracking
			console.log('BackgroundGeolocation is configured and ready to use');
			if (!state.enabled) {
			  bgGeo.start().then(function() {
				console.log('- BackgroundGeolocation tracking started');
			  });
			}
		  });
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Vasek18** [comment]
heartbeatInterval looks very small
Plus heartbeat starts on stop after move, so you need to move first
Also on ios heartbeat works only when the screen is on or the phone is charging

**Comment by christocracy** [comment]
>heartbeatInterval looks very small

I have no idea what this means.

>Plus heartbeat starts on stop after move, so you need to move first

Heartbeat events fire only when the device is in the *stationary* state.  When the device is detected to be moving and the plugin changes to *moving* state to begin recording locations, **heartbeat events no longer fire**.

>Also on ios heartbeat works only when the screen is on or the phone is charging

Or when the device is being physically moved / shaken.  Yes, this is correct and API docs in `Config.preventSuspend` (which iOS requires for heartbeat) warn about this.  No, there is no way around this.  It is the nature of iOS.

![](https://dl.dropbox.com/s/mtvporrj1ovopa9/Screen%20Shot%202021-09-22%20at%209.43.55%20AM.png?dl=1)

**Comment by mehmetkaynak** [comment]
> > heartbeatInterval looks very small
> 
> I have no idea what this means.
> 
> > Plus heartbeat starts on stop after move, so you need to move first
> 
> Heartbeat events fire only when the device is in the _stationary_ state. When the device is detected to be moving and the plugin changes to _moving_ state to begin recording locations, **heartbeat events no longer fire**.
> 
> > Also on ios heartbeat works only when the screen is on or the phone is charging
> 
> Or when the device is being physically moved / shaken. Yes, this is correct and API docs in `Config.preventSuspend` (which iOS requires for heartbeat) warn about this. No, there is no way around this. It is the nature of iOS.
> 
> ![](https://camo.githubusercontent.com/c81230f73116fa84ac194ee891f036bab825d9e3a5deeee659a065ae2a151020/68747470733a2f2f646c2e64726f70626f782e636f6d2f732f6d7476706f72726a316f766f7061392f53637265656e25323053686f74253230323032312d30392d32322532306174253230392e34332e3535253230414d2e706e673f646c3d31)

so what is my problem i didn't get any heartbeat event data? is my config wrong?

**Comment by christocracy** [comment]
The only thing required for iOS `onHeartbeat` event to fire is `heartbeatInterval` >= 0 and `preventSuspend: true`.
