### ISSUE TITLE
When I call getCurrentPosition() the failure function is called with error code of 408 even though the onLocation success callback function was called with a location.

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [transistorsoft/cordova-background-geolocation-lt#131]
Any help would be greatly appreciated.

Logs:

```
2016-06-06 15:53:45.910 Lineman-App[1314:1350879] got coords: 33.17002477195813/-96.64575958245628 : 65m. at Mon Jun 06 2016 15:53:45 GMT-0500 (CDT)
2016-06-06 15:53:46.078 Lineman-App[1314:1350879] got coords: 33.17002248664593/-96.64575958245628 : 65m. at Mon Jun 06 2016 15:53:46 GMT-0500 (CDT)
2016-06-06 15:53:48.794 Lineman-App[1314:1350879]  - onLocationManagerError: Error Domain=location Code=408 "(null)"
2016-06-06 15:53:48.875 Lineman-App[1314:1350879] BackgroundGeoLocation error=408 at Mon Jun 06 2016 15:53:48 GMT-0500 (CDT)
2016-06-06 15:53:48.875 Lineman-App[1314:1350879] BackgroundGeoLocation error at Mon Jun 06 2016 15:53:48 GMT-0500 (CDT)
2016-06-06 15:53:48.875 Lineman-App[1314:1350879] Failure submitting GPS. Code=408
```
Code:

```
var bgGeo = null;

g_gpsOnReady = function() {
	loadDeviceToken();
    deviceInfo();
    load();
    console.log('*****gpsOnReady()');
    if (localStorage.getItem('ims_url') == "null" || localStorage.getItem('ims_url') == null || localStorage.getItem('ims_url').length == 0) {
        localStorage.setItem('ckbx_AlertPoints', "true");
        localStorage.setItem('ckbx_ConsumerOutages', "true");
        localStorage.setItem('ckbx_DevicesOut', "true");
        localStorage.setItem('ckbx_MyItems', "true");
        localStorage.setItem('ckbx_Predictions', "true");
        localStorage.setItem('ckbx_PrimaryLines', "true");
        localStorage.setItem('ckbx_Substations', "true");
        localStorage.setItem('ckbx_Vehicles', "true");
        localStorage.setItem('ckbx_Weather', "true");
        needsSetup=true;
        $.mobile.changePage( "#settings_page" );
    }else if (localStorage.getItem('gpsActive') == 'on'){
        startGps();
    }else if (collectionStarted) {
        stopGps();
    }
}
var bgGeoCallbackFn = function(location, taskId) {
	try{
		//console.log('[js] BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);
		//if (location.accuracy < defaultAccu ) {
		console.log("got coords: "+location.coords.latitude+"/"+location.coords.longitude+ " : "+location.coords.accuracy+"m. at "+new Date().toString());		
		bgGeo.finish(taskId);
	}catch(e){
		alert("STACK:\n", e.stack);
		console.error(e);  

		// And finally, here's our raison d'etre:  catching the error in order to ensure background-task is completed.
		bgGeo.finish(taskId);
	}
};
var bgGeoFailureFn = function(error) {
	console.log('BackgroundGeoLocation error at '+new Date().toString());
	if (error==0) {
		console.log("Unable to retrieve GPS Location is unkown.");
	}else if (error == 1 ) {
		console.log("Please allow Geolocation Permissions in Settings");
	}else if (error == 2 ) {
		console.log("Network failure submitting GPS.");
	}else if (error == 3) {
		console.log("Network failure submitting GPS.");
	}else {
		console.log("Failure submitting GPS. Code="+error);
	}
	//bgGeo.stop();
	//bgGeo.start();
};
/*----------------------------------------------------------------------------*/
var startGps  = function() {
    bgGeo = window.BackgroundGeolocation;
    // BackgroundGeoLocation is highly configurable.
    var unitid='Fixed unit id';
    if (localStorage.devicetoken != undefined && localStorage.devicetoken != null) {
    	unitid=localStorage.devicetoken;
    }
    bgGeo.configure( 
    				 {
						locationUpdateInterval: localStorage.getItem('location_update_interval'),
						fastestLocationUpdateInterval: localStorage.getItem('location_update_interval'),
						desiredAccuracy: localStorage.getItem('desired_accuracy'),
						stationaryRadius: localStorage.getItem('stationary_radius'),
						distanceFilter: localStorage.getItem('distance_filter'),
						disableElasticity : localStorage.getItem('disable_elasticity') == 'on',                    
						autoSync: true,
						batchSync: localStorage.getItem('batch_sync') == 'on',
						debug: localStorage.getItem('debug_mode') == 'on',
						preventSuspend: localStorage.max_time_btwn_stationary_collections != 0,
						heartbeatInterval: localStorage.max_time_btwn_stationary_collections,
						url: localStorage.getItem('ims_url')+'/webSrvRequests/AVL/avlMobilePush.php',
						params: {rcdid:new Date().getTime(), unitid:unitid, network_state:navigator.connection.type.toString(), platform:platform, version:device.version, uuid:device.uuid, device_name:device.name, collection_type:appname},
						method: 'POST',
						maxDaysToPersist: localStorage.getItem('days_to_persist'),
						activityType: "AutomotiveNavigation"
    				}
   );
   bgGeo.start(function(taskId){ bgGeo.finish(taskId); console.log("Started GPS successfully");},
    				 function(error){console.log("Failed to start GPS:" + error)});
	if (collectionStarted) {
		console.log("Already Collecting GPS");
		return;
	}
    console.log("starting gps");
	collectionStarted=true;
	bgGeo.onLocation(bgGeoCallbackFn,bgGeoFailureFn);
};
/*----------------------------------------------------------------------------*/
var stopGps = function() {
	console.log("stopping gps");
	if(bgGeo == null) {
		bgGeo = window.BackgroundGeolocation;
	}
	collectionStarted=false;
	bgGeo.stop(function(taskId){ bgGeo.finish(taskId); console.log("Successfully stopped GPS");},
    				 function(error){console.log("Failed to stop GPS:"+error);});
};
/*********************Lineman App Uses This*****************/
var getBgGps= function() {
	$("#waiting").show();
	bgGeo.getCurrentPosition(gotBgGps,errorBgGps,{timeout:parseInt(localStorage.max_wait)/1000,minimumAccuracy:parseInt(localStorage.desired_accuracy),maximumAge:parseInt(localStorage.max_wait), persist:false});
};
var gotBgGps = function (position, taskId) {
	$("#waiting").hide();
	bgGeo.finish(taskId);
	search_value=position;
    searchlat=search_value.coords.latitude;
    searchlon=search_value.coords.longitude;
    searchaccuracy=search_value.coords.accuracy;
    $("#accuracy_acceptance_accuracy").html(searchaccuracy+"<br>Latitude/Longitude:"+searchlat +"/"+searchlon);
    $("#accuracy_acceptance_dialog").popup('open');
    
};
var errorBgGps= function(err) {
	console.log('BackgroundGeoLocation error="+JSON.stringify(err)+" at '+new Date().toString());
	$("#accuracy_acceptance_accuracy").html(JSON.stringify(err));
    $("#accuracy_acceptance_dialog").popup('open');
};
```

**Comment by christocracy** [comment]
What version of plugin?

**Comment by KimberleeDArmstrong** [comment]
1.5.1 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144 

----- Original Message -----

**Comment by christocracy** [comment]
For one thing, you should never interact with the plugin until the `#configure` method's callback has fired:
**WRONG**
```
bgGeo.configure(config);
bgGeo.start();
```
**CORRECT**
```
bgGeo.configure(config, function(state) {
  // Plugin is ready to use.
  if (!state.enabled) {
    bgGeo.start();
  }
});
```

**Comment by KimberleeDArmstrong** [comment]
Ah. Thank you. I will make that change. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144 

----- Original Message -----

**Comment by KimberleeDArmstrong** [comment]
I made the change to the configure call, but I am still seeing the error.  It will work 1 in 25 times.  The rest of the time, I get the 408.  The one time it works the both success callback functions (gotBgGps and bgGeoCallbackFn) are called back to back and the location is retrieved quickly.  The rest of the time the bgGeoCallbackFn is called quickly but the gotBgGps function is never called then after the max wait time expires the errorBgGps function is called with error code 408.  Thank you for your help.

as a part of device ready this code....

var startGps  = function() {
    bgGeo = window.BackgroundGeolocation;
    // BackgroundGeoLocation is highly configurable.
    var unitid='Fixed unit id';
    if (localStorage.devicetoken != undefined && localStorage.devicetoken != null) {
    	unitid=localStorage.devicetoken;
    }
    bgGeo.configure( 
    				 {
						locationUpdateInterval: localStorage.getItem('location_update_interval'),
						fastestLocationUpdateInterval: localStorage.getItem('location_update_interval'),
						desiredAccuracy: localStorage.getItem('desired_accuracy'),
						stationaryRadius: localStorage.getItem('stationary_radius'),
						distanceFilter: localStorage.getItem('distance_filter'),
						disableElasticity : localStorage.getItem('disable_elasticity') == 'on',                    
						autoSync: true,
						batchSync: localStorage.getItem('batch_sync') == 'on',
						debug: localStorage.getItem('debug_mode') == 'on',
						preventSuspend: localStorage.max_time_btwn_stationary_collections != 0,
						heartbeatInterval: localStorage.max_time_btwn_stationary_collections,
						url: localStorage.getItem('ims_url')+'/webSrvRequests/AVL/avlMobilePush.php',
						params: {rcdid:new Date().getTime(), unitid:unitid, network_state:navigator.connection.type.toString(), platform:platform, version:device.version, uuid:device.uuid, device_name:device.name, collection_type:appname},
						method: 'POST',
						maxDaysToPersist: localStorage.getItem('days_to_persist'),
						activityType: "AutomotiveNavigation"
    				}, function(state) {
    					if (state.enabled) {
    						console.log("starting gps");
							collectionStarted=true;
    						bgGeo.start(function(taskId){ bgGeo.finish(taskId); console.log("Started GPS successfully");},
    				 			function(error){console.log("Failed to start GPS:" + error)});
							bgGeo.onLocation(bgGeoCallbackFn,bgGeoFailureFn);
    					}else{
    						console.log("Failed to configure dbGeo");
    					}
    				}
   );
};

Gives these logs.....

2016-06-07 09:23:25.602 Lineman-App[1360:1453270] *****gpsOnReady()
2016-06-07 09:23:25.603 Lineman-App[1360:1453270] ╔═════════════════════════════════════════════════
2016-06-07 09:23:25.603 Lineman-App[1360:1453270] ║TSLocationManager ► SQLite init
2016-06-07 09:23:25.604 Lineman-App[1360:1453270] ╠═════════════════════════════════════════════════
2016-06-07 09:23:25.608 Lineman-App[1360:1453270] ✓ Opened database
2016-06-07 09:23:25.610 Lineman-App[1360:1453270] ✓ Unlocked all records
2016-06-07 09:23:25.678 Lineman-App[1360:1453270] THREAD WARNING: ['BackgroundGeolocation'] took '58.099854' ms. Plugin should use a background thread.
2016-06-07 09:23:25.722 Lineman-App[1360:1453270] starting gps
2016-06-07 09:23:25.748 Lineman-App[1360:1453270] Started GPS successfully
2016-06-07 09:23:25.950 Lineman-App[1360:1453270] got coords: 33.17002269320049/-96.64575958245628 : 65m. at Tue Jun 07 2016 09:23:25 GMT-0500 (CDT)

At a later point this code is called...

var getBgGps= function() {
	$("#waiting").show();
	bgGeo.getCurrentPosition(gotBgGps,errorBgGps,{timeout:parseInt(localStorage.max_wait)/1000,minimumAccuracy:parseInt(localStorage.desired_accuracy),maximumAge:parseInt(localStorage.max_wait), persist:false});
};
var gotBgGps = function (position, taskId) {
	$("#waiting").hide();
	bgGeo.finish(taskId);
	search_value=position;
    searchlat=search_value.coords.latitude;
    searchlon=search_value.coords.longitude;
    searchaccuracy=search_value.coords.accuracy;
    $("#accuracy_acceptance_accuracy").html(searchaccuracy+"<br>Latitude/Longitude:"+searchlat +"/"+searchlon);
    $("#accuracy_acceptance_dialog").popup('open');
    
};
var errorBgGps= function(err) {
	console.log('BackgroundGeoLocation error='+JSON.stringify(err)+' at '+new Date().toString());
	$("#accuracy_acceptance_accuracy").html(JSON.stringify(err));
    $("#accuracy_acceptance_dialog").popup('open');
};
var bgGeoCallbackFn = function(location, taskId) {
	try{
		//console.log('[js] BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);
		//if (location.accuracy < defaultAccu ) {
		console.log("got coords: "+location.coords.latitude+"/"+location.coords.longitude+ " : "+location.coords.accuracy+"m. at "+new Date().toString());		
		bgGeo.finish(taskId);
	}catch(e){
		alert("STACK:\n", e.stack);
		console.error(e);  

		// And finally, here's our raison d'etre:  catching the error in order to ensure background-task is completed.
		bgGeo.finish(taskId);
	}
};
var bgGeoFailureFn = function(error) {
	console.log('BackgroundGeoLocation error at '+new Date().toString());
	if (error==0) {
		console.log("Unable to retrieve GPS Location is unkown.");
	}else if (error == 1 ) {
		console.log("Please allow Geolocation Permissions in Settings");
	}else if (error == 2 ) {
		console.log("Network failure submitting GPS.");
	}else if (error == 3) {
		console.log("Network failure submitting GPS.");
	}else {
		console.log("Failure submitting GPS. Code="+error);
	}
};

Yields these logs....

2016-06-07 09:49:53.674 Lineman-App[1360:1453270] got coords: 33.17003248228949/-96.64575958245628 : 65m. at Tue Jun 07 2016 09:49:53 GMT-0500 (CDT)
2016-06-07 09:49:53.904 Lineman-App[1360:1453270] got coords: 33.17002857593634/-96.64575958245628 : 65m. at Tue Jun 07 2016 09:49:53 GMT-0500 (CDT)
2016-06-07 09:49:56.652 Lineman-App[1360:1453270]  - onLocationManagerError: Error Domain=location Code=408 "(null)"
2016-06-07 09:49:56.751 Lineman-App[1360:1453270] BackgroundGeoLocation error=408 at Tue Jun 07 2016 09:49:56 GMT-0500 (CDT)
2016-06-07 09:49:56.752 Lineman-App[1360:1453270] BackgroundGeoLocation error at Tue Jun 07 2016 09:49:56 GMT-0500 (CDT)
2016-06-07 09:49:56.752 Lineman-App[1360:1453270] Failure submitting GPS. Code=408

**Comment by KimberleeDArmstrong** [comment]
Changing...
bgGeo.getCurrentPosition(gotBgGps,errorBgGps,{timeout:parseInt(localStorage.max_wait)/1000,minimumAccuracy:parseInt(localStorage.desired_accuracy),maximumAge:parseInt(localStorage.max_wait), persist:false});

To ...
bgGeo.getCurrentPosition(gotBgGps,errorBgGps);

Made the issue go away.

**Comment by christocracy** [comment]
See the docs for [getCurrentPosition](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getcurrentpositionsuccessfn-failurefn-options).  

There's no such `option` as `minimumAccuracy`.  It's `desiredAccuracy`.

If I were you, I'd check the value being returned by `timeout:parseInt(localStorage.max_wait)/1000` is sane.  It's probably not returning the value you suspect.
