### ISSUE TITLE
Location updates not firing unless movement started while app is in foreground

### ISSUE THREAD

**Issue by mikepaterson** [transistorsoft/cordova-background-geolocation-lt#1312]
## Your Environment
* Plugin version:4.3.0
* Platform: iOS or Android: ios
* OS version: 14
* Device manufacturer / model:  iphone 8/12
* Cordova version (`cordova -v`): latest
* Cordova platform version (`cordova platform ls`):  ios 6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Movement should cause location updates to fire regardless of wether app was in background or foreground when it started.

## Actual Behavior
Location updates only fire if movement was started while app is in foreground.  If app is in background no location updates are recieved even though permission is "always".  Bringing the app back to foreground while continuing to move seems to fix it, as once the events are firing it the foreground the app can be sent to the background and will continue to fire.

## Steps to Reproduce
1. start app
2. once fully loaded send app to background
3. go for a walk
4. open app and see that no location update recieved

vs

1. start app
2. keep in foreground
3. go for walk
4. when location events start firing send app to background
5. keep walking
6. re-open app and see that events continued to fire.

## Context
when a location update is recieved we make a custom api call to lookup nearby locations, and possibly log a visit to the closest location if certain conditions are met (duration/etc). 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Plugin config provided to #ready:

**Comment by mikepaterson** [comment]
BackgroundGeolocation.ready({
          reset: true,
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          stationaryRadius: 25,
          locationAuthorizationRequest: 'Always',
          backgroundPermissionRationale: {
            title: 'Allow {applicationName} to access to this device\'s location in the background?',
            message: 'Your location is used to show your position on the map, discover nearby organizations and update your Places I\'ve Visited history.',
            positiveAction: 'Change to {backgroundPermissionOptionLabel}',
            negativeAction: 'Cancel'
          }
        }, (state) => {
          if (!state.enabled) {
            BackgroundGeolocation.start();
          }
        });

**Comment by christocracy** [comment]
- are you traveling at least 200 meters?
- is WiFi **not disabled**?
- you've authorized *Always* authorization when dialog requested it?
- see wiki *Debugging*.

You're doing something wrong.  I've been field testing almost daily for over 7 years and ios triggering never fails.

**Comment by mikepaterson** [comment]
- are you traveling at least 200 meters?   Yes
- is WiFi not disabled?   Correct
- you've authorized Always authorization when dialog requested it?  Yes
- see wiki Debugging.  Have looked and didnt find a solution, hence this ticket. 

> You're doing something wrong. I've been field testing almost daily for over 7 years and ios triggering never fails.

Yes, I assume so.  Was hoping for more support than "You're doing something wrong".   Any suggestions about what that could be, what might cause the behaviour I'm seeing, or what things I should be looking at?

**Comment by Vasek18** [comment]
Maybe you should try to set "preventSuspend" to true?

**Comment by hanatharesh2712** [comment]
> * are you traveling at least 200 meters?
> * is WiFi **not disabled**?
> * you've authorized _Always_ authorization when dialog requested it?
> * see wiki _Debugging_.
> 
> You're doing something wrong. I've been field testing almost daily for over 7 years and ios triggering never fails.

Facing the same issues in Android 10 Emulators. Have followed all these thins mentioned.

**Comment by christocracy** [comment]
> Platform: iOS or Android: ios

This is an iOS issue.

Android has trouble in emulators because the motion api doesn't work in emulators.

See wiki *Debugging*.  You have to manually engage location-services with .changePace(true).

It's best to test on a real device  with real movement.  Go outside for a 1km trip.

**Comment by hanatharesh2712** [comment]
I am going to do these tests:
Start the App (It will start the plugin)
Walk for 100 meters
Terminates the App from recent apps(Fully Closed)
Seat ideal for 10 minutes
Start driving for ~1-2km trip (It should send positions)

In the above case, the plugin should work properly. right?

**Comment by christocracy** [comment]
If you experience issues during your field-test, post a new issue.  This issue is related to *iOS Only*.

**Comment by hanatharesh2712** [comment]
> If you experience issues during your field-test, post a new issue. This issue is related to _iOS Only_.
Just asking, should these steps work or not?

**Comment by christocracy** [comment]
See the wiki *Philosophy of Operation*.  When the device is detected to be physically moving, the plugin turns on location-services and begins recording location according to your configured `distanceFilter`.

When the device is detected to be stationary, the plugin initiated the `stopTimeout` timer, the expiration of which will cause the plugin to turn off location-services and enter the *stationary* state to conserve energy,
