### ISSUE TITLE
sometimes plugin send wrong location generally "motion change event"

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1313]
## Your Environment
* Plugin version: 4.1.2
* Platform: iOS or Android
* OS version: ios 15
* Device manufacturer / model: iPhone 11
* Cordova version (`cordova -v`): latest
* Cordova platform version (`cordova platform ls`): latest
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
var bgGeo = window.BackgroundGeolocation;
			bgGeo.ready({
			reset: true,
			debug: false,
			notification: {
				title: "",
				text: ""
			  },
			logLevel: bgGeo.LOG_LEVEL_VERBOSE,
			desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
			distanceFilter: 100,
			locationAuthorizationRequest: 'Always',
				backgroundPermissionRationale: {
				title: "Lütfen, {applicationName} 'ın lokasyon erişimine izin verin.",
				message: ".",
				positiveAction: "İzin verin '{backgroundPermissionOptionLabel}'",
				negativeAction: "İptal"
				},
			url: '',
			autoSync: true,
			stopOnTerminate: false,
			extras: {
				
			  },
			startOnBoot: true,
			heartbeatInterval:60,
			preventSuspend:true,
			foregroundService:true
			}, function(state) {    // <-- Current state provided to #configure callback
			// 3.  Start tracking
			console.log('BackgroundGeolocation is configured and ready to use');
			if (!state.enabled) {
			  bgGeo.start().then(function() {
				console.log('- BackgroundGeolocation tracking started');
			  });
			}
		  });
```

## Expected Behavior

sometimes the plugin sends wrong locations. usually at the "motion change" event. The locations with "(M)" appearing in the picture are the locations from the "motion change" event. It shows people in places they've never been.
Map Url : https://ibb.co/HpLG9bv
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by mehmetkaynak** [comment]
My Log

[log.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/7244291/log.txt)

**Comment by christocracy** [comment]
>sometimes the plugin sends wrong locations

The plugin receives location directly from the device's native location API.  It does not *manufacture* locations.  It delivers them to you exactly as received.  Location APIs can take time to "warm up" (eg: connecting to GPS satellites).

See `Location.coords.accuracy`.
