### ISSUE TITLE
How to licence validation failure message from appearing?

### ISSUE THREAD

**Issue by ohtanzcom** [transistorsoft/cordova-background-geolocation-lt#1319]
We are using ionic.
The platform is developed for IOS and Android, but I would like to use this plugin only on iOS.
In this case, is there any way to prevent the "Activation Failed" message from appearing on Android?

**Comment by christocracy** [comment]
>is there any way to prevent the "Activation Failed" message from appearing on Android?

No.

**Comment by christocracy** [comment]
Well, you can [buy a license](https://www.transistorsoft.com/shop/products/cordova-background-geolocation).  That'll shut it up.
