### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by LessorMatt** [transistorsoft/cordova-background-geolocation-lt#132]
Hi,

I have Basic Authentication on our Web API but I can't seem to figure out how to add it to the header of the POST that the plugin sends. 

I see there is _header_ and _params_ attributes in the configuration but I can't get it to work.

The authentication in the header is **username:password**, and then base64 encrypted. I add it to the $http headers like this for other requests:

$http.defaults.headers.common['Authorization'] = 'Basic ' + userDetails;

How would I accomplish this for the plugin? I'm not sure if I'm on the right path.

I have tried:

**headers: {
"Authorization": 'Basic' + userDetails
}**

and 

**params: {
"Authorization": 'Basic' + userDetails
}**

Is this correct?

**Comment by christocracy** [comment]
Are you analyzing the request in the logs arriving at your server?

On Tuesday, June 14, 2016, LessorMatt <notifications@github.com> wrote:

> Hi,
>
> I have Basic Authentication on our Web API but I can't seem to figure out
> how to add it to the header of the post that the plugin sends.
>
> I see there is *header* and *params* attributes in the configuration but
> I can't get it to work.
>
> The authentication in the header is *username:password*, and then base64
> encrypted. I add it to the $http headers like this for other requests:
>
> $http.defaults.headers.common['Authorization'] = 'Basic ' + userDetails;
>
> How would I accomplish this for the plugin? I'm not sure if I'm on the
> right path.
>
> I have tried:
>
>
>
> *headers: { "Authorization": 'Basic' + userDetails }*
>
> and
>
>
>
> *params: { "Authorization": 'Basic' + userDetails }*
>
> Is this correct?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/132>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lwphnVKmDiIEZ1TzxMwaSvZ9tAouks5qLr0FgaJpZM4I1ZQh>
> .
>


-- 
Snet form Gmail Mobile

**Comment by LessorMatt** [comment]
I'm still developing the app and is not on any sort of live server atm. I have Visual Studio running on my PC and have configured it to run the WebAPI on my PC's hostname. Both devices (PC and Phone) are connected to the same network so the mobile app can hit the Web API while I'm debugging on VS. 

It doesn't seem like the request comes through though. I put a breakpoint on my basic auth module (which gets hit every request, confirmed working) and it's as if the request doesn't even hit the "web server" that my VS is hosting in debug.

I ran a test where I took basic auth off the API call and the POST from the plugin comes through perfectly.

Are my attributes on the configuration object correct? If you can confirm that this is how you add basic auth to the headers of the POST for the plugin then I will trawl through log files and troubleshoot why it's not hitting the server. Have you dealt with basic auth on the plugin before?

**Comment by christocracy** [comment]
Is this still an issue?

**Comment by LessorMatt** [comment]
Hi,

You can close it, I'm going to change to token based auth soon so if I have an issue Ill log another.
