### ISSUE TITLE
[CHANGEME] This app collects location data for FEATURE X and FEATURE Y .

### ISSUE THREAD

**Issue by Nikhath-1211** [transistorsoft/cordova-background-geolocation-lt#1320]
I have been using the license version of cordova-background-geolocation-lt in my cordova app, Because of these context text [CHANGEME] This app collects location data for FEATURE X and FEATURE Y . Google play console rejected due to policies violation , aren't able to customize the text explaining why it should be tracked . so mainly need to change the text/message in Alert permissions.

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version: cordova-background-geolocation-lt 3.10.0 "BackgroundGeolocation"
* Platform: iOS or Android
* OS version:Android 10 
* Device manufacturer / model:
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):
  android 9.1.0
  browser 
  ios 6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

The Alert for location tracking permission should be given a custom message /proper message to user why it's being asked for?
## Actual Behavior

The Alert for location tracking permission displays message as [CHANGEME] This app collects location data for FEATURE X and FEATURE Y .
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
![Permission](https://user-images.githubusercontent.com/94528297/142371687-867f06f4-649d-410e-9ee2-b7c20471bbb3.png)

**Comment by phil294** [comment]
Check https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353 for explanation. It just seems to not have really been documented yet in the readme
