### ISSUE TITLE
Disable url through setConfig

### ISSUE THREAD

**Issue by QP-JoBi** [transistorsoft/cordova-background-geolocation-lt#1321]
## Your Environment
* Plugin version: 4.4.0
* Platform: Android
* OS version: Android 9
* Device manufacturer / model: Samsung Galaxy S8
* Cordova version (`cordova -v`): Capacitor Project
* Cordova platform version (`cordova platform ls`): Capacitor Project
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
config = {
            debug: false,
            distanceFilter: 0,
            stationaryRadius: 25,
            startOnBoot: false,
            stopOnTerminate: true,
            heartbeatInterval: 60,
            locationUpdateInterval: this.interval,
            fastestLocationUpdateInterval: this.interval,
            maxDaysToPersist: 1,

            httpTimeout: 5_000,
            method: "POST",
            httpRootProperty: ".",
            locationTemplate: "{ \"latitude\":<%= latitude %>, \"longitude\":<%= longitude %>, \"accuracy\": <%= accuracy %>, " +
                                "\"altitude\": <%= altitude %>, \"bearing\": <%= heading %>, \"speed\": <%= speed %>, " +
                                "\"time\": \"<%= timestamp %>\" }",
            autoSyncThreshold: 1,
            autoSync: true,
            batchSync: true,

            backgroundPermissionRationale: {
                title: this.translateService.instant("gps-always-request-title"),
                message: this.translateService.instant("gps-always-request-message"),
                positiveAction: "Change to {backgroundPermissionOptionLabel}",
                negativeAction: "Cancel"
            },
        }
```

## Expected Behavior
After `#ready` a server url is set to the according backend. However, in our usage there are repeated phases where the gps coordinates have to be sent over to the backend and others where this should not happen. Since the docs tell you the default value of "url" is undefined, our approaches were to use ```` .setConfig({ url: undefined }) ```` or ```` .setConfig({ url: null }) ```` in order to disable the transmission.

## Actual Behavior
```` .setConfig({ url: undefined }) ```` led to no changes at all - the url in the config remained to be the backend url previously provided.

```` .setConfig({ url: null }) ```` led to the url being set to "null" (type string)

Transmission was still ongoing in both cases after using ```` .setConfig({ url: ... }) ````

## Question
How can you stop the transfer to the server once a valid URL has been provided?

**Comment by christocracy** [comment]
Set it empty string `""`
