### ISSUE TITLE
fail to install cordova-background-geolocation plugin

### ISSUE THREAD

**Issue by ryaa** [transistorsoft/cordova-background-geolocation-lt#1325]
## Your Environment
```
   NodeJS : v14.18.0 (/Users/alexryltsov/.nvm/versions/node/v14.18.0/bin/node)
   npm    : 6.14.15
   OS     : macOS Monterey
   Xcode  : Xcode 13.2 Build version 13C90
```

## Expected Behavior
Before today the plugin successfully installed

## Actual Behavior
Getting the below error when trying to run 'npm install' on my machine. The problem started today
```
40978 error remote: Repository not found.
```

My package.json contain the below line for this plugin package
```
"cordova-background-geolocation": "git+https://XXXXXXXXX@github.com/transistorsoft/cordova-background-geolocation.git#3.9.4",
```

## Steps to Reproduce
1. run 'npm install' command

## Context
install all the application npm packages

## Debug logs
N/A

**Comment by ryaa** [comment]
@christocracy thank you for quick response. yes, you are right. the problem is on my side and has been resolved.

**Comment by phil294** [comment]
> Perhaps your support subscription expired and you were removed from the private repo? What is your Order #?

How can the subscription expire? [The shop](https://www.transistorsoft.com/shop/products/cordova-background-geolocation) says
- Perpetual license
- Support via Github issues
- 1 year access to latest updates.

As I understand this, there should be no way to ever be removed from the private repo. Am I misunderstanding something here?

Sorry for hijacking this thread

**Comment by christocracy** [comment]
You get one year access to the private repo for access to latest updates / priority support.

**Comment by christocracy** [comment]
License keys continue to unlock the plugin forever.

One doesn’t get to dance free forever on my private property (that I pay GitHub for).

**Comment by ryaa** [comment]
> You get one year access to the private repo for access to latest updates / priority support.

The problem for me was that I could not install even an older (not the latest) version to do the development. As I understand, once the subscription is expired, you can not even install the older versions (which were available at the time of the purchase).

**Comment by christocracy** [comment]
This public repo here where we’re talking is mirrored from the private repo about every 3 months, then published to npm.
