### ISSUE TITLE
Timestamps of ( transmission delayed (?) ) locations is wrong

### ISSUE THREAD

**Issue by QP-JoBi** [transistorsoft/cordova-background-geolocation-lt#1327]
## Your Environment
* Plugin version: 4.4.0
* Platform: Android
* OS version: Android 9
* Device manufacturer / model: Samsung Galaxy S8
* Cordova version (`cordova -v`): Capacitor Project
* Cordova platform version (`cordova platform ls`): Capacitor Project
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
config = {
            debug: false,
            distanceFilter: 0,
            stationaryRadius: 25,
            startOnBoot: false,
            stopOnTerminate: true,
            heartbeatInterval: 60,
            locationUpdateInterval: this.interval,
            fastestLocationUpdateInterval: this.interval,
            maxDaysToPersist: 1,

            httpTimeout: 5_000,
            method: "POST",
            httpRootProperty: ".",
            locationTemplate: "{ \"latitude\":<%= latitude %>, \"longitude\":<%= longitude %>, \"accuracy\": <%= accuracy %>, " +
                                "\"altitude\": <%= altitude %>, \"bearing\": <%= heading %>, \"speed\": <%= speed %>, " +
                                "\"time\": \"<%= timestamp %>\" }",
            autoSyncThreshold: 1,
            autoSync: true,
            batchSync: true,

            backgroundPermissionRationale: {
                title: this.translateService.instant("gps-always-request-title"),
                message: this.translateService.instant("gps-always-request-message"),
                positiveAction: "Change to {backgroundPermissionOptionLabel}",
                negativeAction: "Cancel"
            },
        }
```

## Expected Behavior
Each location caught by `BackgroundGelocation.onLocation` has a timestamp that is referring to the time it was tracked. 

This timestamp still refers to the time of recording when it is sent to the server using the plugin's own Http service. This also applies if a significantly delayed transmission occurs due to lack of Internet or other reasons

## Actual Behavior
![image](https://user-images.githubusercontent.com/83657458/146807897-3473e06c-3bc9-4e12-9395-30b007b36098.png)

In the picture you can see a polyline drawn of a car drive recorded by the plugin on android with a set interval of 10 seconds. The blue arrows show the direction in which the car was driving.

The polyline connects each location with the nearest one in terms of time (ordered by the timestamp).

However, as you can see there is a weird "jump" on the line. The point in the lower left corner occurs earlier on the drive, yet somehow has a timestamp in between the two top right points.

We checked with the backend logs and there is no transmission delay with any timestamp  [ e.g Location_1 with timestamp "20.12.2021 14:31:17" arrives in the backend at "20.12.2021 14:31:20" ] and the bottom-left location in fact got a timestamp between the two top-right locations. Also it cannot just be a "highly inaccurate" location, since it in fact lies on the earlier drive path.

Another important observation is that the wrong record was transmitted outside the regular 10-second interval.
So somehow, the bottom-left location was transmitted outside of the 10-seconds time interval with a wrong timestamp. 

My only explanation is that the location used to be recorded, but for some reason it was not sent to the backend via HTTP request. This then happened at a later time, with the timestamp referring to when it was sent rather than when it was tracked.

## Question
When using the plugin's own Http service, does the timestamp refer to the sending time or the recording time?

**Comment by christocracy** [comment]
> does the timestamp refer to the sending time or the recording time?

The timestamp comes from the time it was reported.  The plugin doesn’t care about the time it was sent.

the data is exactly as reported by the native location api.  The plugin doesn’t manufacture data.  It is only the messenger, delivering data exactly as received by the native api.
