### ISSUE TITLE
Plugin doesn't trigger onGeofence when app was killed, but it initializes i

### ISSUE THREAD

**Issue by MarkusPfundstein** [transistorsoft/cordova-background-geolocation-lt#133]
CAN BE CLOSED: had a bug

Hoi, 

I have a question regarding the plugin's behaviour.

I initialize it as follows;

    console.log('[GEO] init geofencing');
	this._bgGeo = window.BackgroundGeolocation;
	if (!this._bgGeo) {
		console.error('error getting geolocation plugin');
		return;
	}
	console.log('[GEO] here');
	// https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs
	var that = this;
	this._bgGeo.configure({
		startOnBoot: true,
		stopOnTerminate: false,		// doesn't change much 
		pausesLocationUpdatesAutomatically : false,		// doesn't change much
		desiredAccuracy: 0,
		distanceFilter: 50,
		stationaryRadius: 25,
		locationUpdateInterval: 1000
	}, function(state) {
		console.log("[GEO] Background Geolocation started up.  Current state: ", state.enabled);
		that._bgGeo.start(function() {
			console.log("[GEO] started");

			that.addGeofenceEntry('leiduinstraat', 45.519219, -73.616786, 150, function (error) {
				if (error) {
					return console.log('[GEO] error: ' + error.message);
				}
				console.log('[GEO] leiduinstraat added');
			});

			that._bgGeo.onGeofence(function(params, taskId) {
				console.log("[GEO] ----- ENTERED GEOFENCE");
				// re add
				that.addGeofenceEntry('leiduinstraat', 45.519219, -73.616786, 150, function (error) {
					if (error) {
						return console.log('[GEO] error: ' + error.message);
					}
					console.log('[GEO] leiduinstraat added');
				});

				that._bgGeo.finish(taskId);

			});
		}, function (error) {
			console.log("[GEO] failed starting: " + error);
		});
	}, function(error) {
		console.warn("[GEO] Background Geolocation failed to configure");
	});

When I run the app in the simulator, everything works great and I receive the update.

	Jun 17 15:33:10 MBP Project[8085]: [GEO] init geofencing
	Jun 17 15:33:10 MBP Project[8085]: [GEO] here
	Jun 17 15:33:10 MBP Project[8085]: [GEO] Background Geolocation started up.  Current state:  true
	Jun 17 15:33:13 MBP Project[8085]: [GEO] started
	Jun 17 15:33:13 MBP Project[8085]: [GEO] add geofence: leiduinstraat
	Jun 17 15:33:13 MBP Project[8085]: [GEO] leiduinstraat added
	Jun 17 15:33:29 MBP Project[8085]: [GEO] ----- ENTERED GEOFENCE

	
However, when I kill the app (swipe it out of task manager). And I re-enter the geofence then the callback isn't called. However I see that
it restarts the app:

	Jun 17 15:33:41 MBP Project[8089]: [GEO] init geofencing
	Jun 17 15:33:41 MBP Project[8089]: [GEO] here
	Jun 17 15:33:41 MBP Project[8089]: [GEO] Background Geolocation started up.  Current state:  true
	Jun 17 15:33:41 MBP Project[8089]: [GEO] started
	Jun 17 15:33:41 MBP Project[8089]: [GEO] add geofence: leiduinstraat
	
So the app was started. But the callback isn't executed.

Any ideas? Is this possible in the first place? 

Thanks a lot for your answer!

Markus

**Comment by christocracy** [comment]
May be missing this case.  I'll have a look when I return from vacation in
about 10 days

On Friday, June 17, 2016, Markus Pfundstein <notifications@github.com>
wrote:

> Hoi,
>
> I have a question regarding the plugin's behaviour.
>
> I initialize it as follows;
>
> console.log('[GEO] init geofencing');
> this._bgGeo = window.BackgroundGeolocation;
> if (!this._bgGeo) {
>     console.error('error getting geolocation plugin');
>     return;
> }
> console.log('[GEO] here');
> // https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs
> var that = this;
> this._bgGeo.configure({
>     startOnBoot: true,
>     stopOnTerminate: false,     // doesn't change much
>     pausesLocationUpdatesAutomatically : false,     // doesn't change much
>     desiredAccuracy: 0,
>     distanceFilter: 50,
>     stationaryRadius: 25,
>     locationUpdateInterval: 1000
> }, function(state) {
>     console.log("[GEO] Background Geolocation started up.  Current state: ", state.enabled);
>     that._bgGeo.start(function() {
>         console.log("[GEO] started");
>
>         that.addGeofenceEntry('leiduinstraat', 45.519219, -73.616786, 150, function (error) {
>             if (error) {
>                 return console.log('[GEO] error: ' + error.message);
>             }
>             console.log('[GEO] leiduinstraat added');
>         });
>
>         that._bgGeo.onGeofence(function(params, taskId) {
>             console.log("[GEO] ----- ENTERED GEOFENCE");
>             // re add
>             that.addGeofenceEntry('leiduinstraat', 45.519219, -73.616786, 150, function (error) {
>                 if (error) {
>                     return console.log('[GEO] error: ' + error.message);
>                 }
>                 console.log('[GEO] leiduinstraat added');
>             });
>
>             that._bgGeo.finish(taskId);
>
>         });
>     }, function (error) {
>         console.log("[GEO] failed starting: " + error);
>     });
> }, function(error) {
>     console.warn("[GEO] Background Geolocation failed to configure");
> });
>
> When I run the app in the simulator, everything works great and I receive
> the update.
>
> Jun 17 15:33:10 MBP Project[8085]: [GEO] init geofencing
> Jun 17 15:33:10 MBP Project[8085]: [GEO] here
> Jun 17 15:33:10 MBP Project[8085]: [GEO] Background Geolocation started up.  Current state:  true
> Jun 17 15:33:13 MBP Project[8085]: [GEO] started
> Jun 17 15:33:13 MBP Project[8085]: [GEO] add geofence: leiduinstraat
> Jun 17 15:33:13 MBP Project[8085]: [GEO] leiduinstraat added
> Jun 17 15:33:29 MBP Project[8085]: [GEO] ----- ENTERED GEOFENCE
>
> However, when I kill the app (swipe it out of task manager). And I
> re-enter the geofence then the callback isn't called. However I see that
> it restarts the app:
>
> Jun 17 15:33:41 MBP Project[8089]: [GEO] init geofencing
> Jun 17 15:33:41 MBP Project[8089]: [GEO] here
> Jun 17 15:33:41 MBP Project[8089]: [GEO] Background Geolocation started up.  Current state:  true
> Jun 17 15:33:41 MBP Project[8089]: [GEO] started
> Jun 17 15:33:41 MBP Project[8089]: [GEO] add geofence: leiduinstraat
>
> So the app was started. But the callback isn't executed.
>
> Any ideas? Is this possible in the first place?
>
> Thanks a lot for your answer!
>
> Markus
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/133>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lxvRpOerow3z3LxqHUJwUesH31eFks5qMqQFgaJpZM4I4XkL>
> .
>


-- 
Snet form Gmail Mobile
