### ISSUE TITLE
[how-to] is there a way to stop and start the plugin without triggering the devicepause and deviceresume events?

### ISSUE THREAD

**Issue by CodeWithOz** [transistorsoft/cordova-background-geolocation-lt#1337]
## Your Environment
* Plugin version: 3.6.2
* Platform: iOS or Android (both)
* OS version: Android 8.1 - 12.1, ios 12 - 15
* Device manufacturer / model: iPhone 6, Tekno Pop 2 Plus, samsung galaxy s21 note ultra
* Cordova version (`cordova -v`): 11
* Cordova platform version (`cordova platform ls`): ios platform v6, android platform v10
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
        const initGeoOptions = {
            desiredAccuracy: 50,
            stationaryRadius: 50,
            distanceFilter: 50,
            disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
            locationUpdateInterval: 5000,
            minimumActivityRecognitionConfidence: 80, // 0-100%.  Minimum activity-confidence for a state-change
            fastestLocationUpdateInterval: 5000,
            activityRecognitionInterval: 10000,
            showsBackgroundLocationIndicator: true,
            stopTimeout: 0,
            startOnBoot: true,
            locationAuthorizationRequest: 'Any',
            url: 'my-server.com'
            method: 'POST',
            batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
            reset: true,
        };

```

## Expected Behavior

Starting and stopping the plugin shouldn't trigger the `devicepause` followed by `deviceresume` events. The context is that I want to pause the plugin when my app is put in the background, rather than having it potentially remain active if the user keeps moving while my app is in the background. I can use `stop()` and `.start()` but `.start()` triggers my `devicepause` and `deviceresume` handlers, which is redundant in my app because those funds are already invoked by the device.  Of course "background" is in the name of the plugin, but is there a way/config to disable background tracking i.e. make the plugin only function while my app is in the foreground?

## Actual Behavior

`.start()` triggers my `devicepause` and `deviceresume` handlers, which I want to avoid.

## Steps to Reproduce

1. after starting the plugin, invoke `bgGeo.stop().then(() => bgGeo.start())`
2.
3.
4.

## Context

I want to pause the plugin when my app is put in the background, rather than having it potentially remain active if the user keeps moving while my app is in the background

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
130|TECNO-BA2:/ $ logcat *:S TSLocationManager:V           
--------- beginning of crash
--------- beginning of main
--------- beginning of system
03-08 01:09:49.140  8934  9753 D TSLocationManager: $ stop()
03-08 01:09:53.836  8934  9753 D TSLocationManager: $ stop()
03-08 01:10:04.822  8934  9753 D TSLocationManager: $ stop()
03-08 01:10:07.641  8934  9753 D TSLocationManager: $ start()
03-08 01:10:07.654  8934  1287 I TSLocationManager: - Enable: false → true, trackingMode: 1
```

</details>

**Comment by christocracy** [comment]
Read the api docs Config.disableLocationAuthorizationAlert.

this is a special mechanism of the Android location api that can detect when the user has not configured settings properly to allow geolocation (Eg location-services disabled), where the OS will present the user a dialog to automatically fix the problem.  This requires a hidden activity to be presented, which is responsible for this pause/resume phenomenon.

If you set disableLocationAuthorizationAlert: true, it will prevent that phenomenon at the expense of losing that automatic feature.

**Comment by CodeWithOz** [comment]
@christocracy thanks for that. That's a valuable feature so I'd rather not disable it. Are there any other considerations/pitfalls I should be aware of if I'm `.stop()`ing the plugin when the app is in the background and `.start()`ing it when the app is returned to the foreground? Do you know if that's a common way the plugin is used?

**Comment by CodeWithOz** [comment]
Also, one of the implications of the pause/resume phenomenon should be that `myCallback` in
```js
bgGeo.start().then(myCallback);
```
will always execute before `onDeviceResume` in
```js
document.addEventListener('resume', onDeviceResume, false);
```
Is that right? To state it differently, can I be certain that the callback I supply to `.start().then(...)` will always execute before the handler for the `deviceresume` event? It seems so based on what you explained, the hidden activity can only be shown after `.start()` is invoked, so the callback to `start().then(...)` would fire before the hidden activity triggers `devicepause` and `deviceresume`. I just want to be sure that's correct.

**Comment by christocracy** [comment]
I have no idea.

**Comment by CodeWithOz** [comment]
Thanks for the response. Is that an answer to my first question about potential pitfalls and other considerations, or the second question about order of execution?

**Comment by christocracy** [comment]
Both
