### ISSUE TITLE
execute function when stopTimeout limit is reached

### ISSUE THREAD

**Issue by tanjentman** [transistorsoft/cordova-background-geolocation-lt#134]
Hi everyone, is there any way to execute a function when the stopTimeout limit occurs?

**Comment by christocracy** [comment]
The motionchange event fires when stopTimeout expires

On Tuesday, June 21, 2016, tanjentman <notifications@github.com> wrote:

> Hi everyone, is there any way to execute a function when the stopTimeout
> limit occurs?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/134>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l8i3TjEDanKofNcNWFXPM86FG1ujks5qODFNgaJpZM4I7DRt>
> .
>


-- 
Snet form Gmail Mobile

**Comment by tanjentman** [comment]
Will it fire any time before the stopTimeout?  I am trying to use it to determine when a driving trip has ended, which I've set to 10 minutes.

**Comment by christocracy** [comment]
`motionchange` event fires *as soon as* `stopTimeout` expires.
