### ISSUE TITLE
this plugin is not working cordova-plugin-wkwebview-engine

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1344]
## Your Environment
* Plugin version: 4.1.1
* Platform: iOS
* OS version: 5.1.1
* Device manufacturer / model: 13
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 9.1.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Need to work with cordova wkwebview engine plugin

## Actual Behavior
Ios app store not allowed apps without wkwebview. So background plugin not work with wkwebview plugin. It give app crash.

## Steps to Reproduce

1. Install both cordova wkwebview engine and cordova background geolocation lt plugin
2.Then make ios build 
3.Then install ios apk in ios mobile
4.Open the apk in ios mobile. 
5.It will crash when app open

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>It will crash when app open

What makes you think the plugin is responsible?  You haven't posted a stacktrace referencing the plugin.

**Comment by Ambikapathi** [comment]
Once i installed cordova background lt plugin. then wkwebview plugin gives error like this  -- > int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");

Once i removed background lt plugin app working fine.

**Comment by christocracy** [comment]
I have no idea what your problem is.  There is no reference to anything from the plugin in ` int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");`.

**Comment by christocracy** [comment]
>Cordova version (cordova -v): 10.0.0

Btw, the latest Cordova CLI is `11.0.0`

https://www.npmjs.com/package/cordova

**Comment by Ambikapathi** [comment]
There is no problem in your plugin. Only the plugin is not works with wkwebview plugin. Above issue is returned by wkwebview plugin once i merge with background lt plugin . without wkwebview app store not accepting ipa in app store.

**Comment by christocracy** [comment]
Customers have been using the plugin with *WkWebView* since at least 2017.  This isn't new.


https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/548

**Comment by christocracy** [comment]
You can search the issues here for "WkWebView".

I suggest you start by uninstalling **deprecated plugins**.

**Comment by Ambikapathi** [comment]
I have searched in issues. But nothing is related to me. Can you suggest which wkwebview plugin is working with background lt plugin.

**Comment by christocracy** [comment]
I don't know anything about WkWebView.

**Comment by christocracy** [comment]
I suggest you migrate your app to Capacitor, which uses WkWebView by default.

**Comment by christocracy** [comment]
Did you read the [deprecation notice](https://github.com/apache/cordova-plugin-wkwebview-engine#deprecation-notice) at `cordova-plugin-wkwebview'??

<img width="909" alt="Screen Shot 2022-04-14 at 1 38 27 PM" src="https://user-images.githubusercontent.com/14999/163443679-7fe38ea8-68b0-4429-b589-c660b21f5789.png">
