### ISSUE TITLE
How can i send connectted bluetooth  device list with extras? Is this possible?

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1345]
* Plugin version: latest
* Platform: iOS or Android 
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```JavaScript
BackgroundGeolocation.setConfig({
  extras:  {
    deviceList:  yourDeviceList
  }
})
```

**Comment by mehmetkaynak** [comment]
> ```js
> BackgroundGeolocation.setConfig({
>   extras:  {
>     deviceList:  yourDeviceList
>   }
> })
> ```

i think this but active bluetooth device list live thing. how can i get active devicelist with your plugin? https://github.com/transistorsoft/cordova-plugin-background-fetch is this works?

**Comment by christocracy** [comment]
None of my plugin have anything to do with Bluetooth.

It's your own responsibility to collect a list of BT devices using some plugin specializing in BT.
