### ISSUE TITLE
Background fetch failing on Android 

### ISSUE THREAD

**Issue by nanshaki** [transistorsoft/cordova-background-geolocation-lt#1347]
## Your Environment
* Plugin version: 4.4.2
* Platform: Android
* OS version: 11
* Device manufacturer / model: Galaxy (Also tested on Android 10 LG Nexus)
* Cordova version (`cordova -v`):  10
* Cordova platform version (`cordova platform ls`): 10.1.1
* Plugin config provided to `#ready`:
```

```

## Expected Behavior
App tracks in the background

## Actual Behavior
App stoops tracking and log shows that the url for background tracking is not found 

## Steps to Reproduce
1. Allow background (Always) on location to the app2. 
2. Shutdown the app 
3.  Move at least 200 Meters

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
This is what your server said to the plugin:

[HttpService$i onResponse] 
  ⚠️  Response: 401,

**Comment by christocracy** [comment]
The only reason your server would return 401 is that it's not satisfied with the provided auth credentials.

You should debug this at your server and log the provided credentials.

**Comment by christocracy** [comment]
You are placing your auth token in the http headers.  Both iOS and Android operate identically.

Presumably, your server is not happy with that token associated with that particular device.

Query your server logs to find out why.

**Comment by nanshaki** [comment]
Hello again 
We think that we understand the issue on Android now better. 
We are using Access tokens and Refresh Tokens when the Access tokens expire within a set amount of time.
However the onHTTP is not triggering and I see why that is from this post.
https://github.com/transistorsoft/react-native-background-geolocation/issues/710

Is this accurate and relevant and is the documentation for Headless Mode for Cordova as well?
https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode
