### ISSUE TITLE
All geofences get removed, when app is started by geofence event from terminated state

### ISSUE THREAD

**Issue by andpoulsen** [transistorsoft/cordova-background-geolocation-lt#135]
Hi. 

We would like to create an app, which can do some quick bluetooth communication every time the user enters a monitored region. 
This should work regardless of wether the app is in the foreground, background or terminated state. 

We have the following problem: if the app gets woken in the background from terminated state because the user entered a geofenced area, then all geofences get deleted. If the app is in the foreground or background, none of the geofences get deleted. 
We would like for the app to behave the same way in both cases, which means that no geofences should get deleted automatically.

This is reproducable in the iOS debugger with the sample app (BG Geo) through the following steps:
1. In home.js remove the section of onGeofence which removes a geofence after it has been hit. E.g. everything between "$scope.showAlert('Geofence '..." and the last call to "bgGeo.finish(taskId);".
2. Rebuild BG Geo.
3. Remove BG Geo if it is already installed in the simulator. Stop all other apps in the simulator.
4. Start BG Geo (don't start background geolocation tracking with the toggle button in upper right corner). We do NOT want the app to get started in the background simply because of movement. 
5. In simulator menu go to Debug => Location => Apple.
6. Press the arrow in lower left corner to center app on current location.
7. Move a bit the the west and set a geofence, where Junipero Serra FW meets N Stelling Rd. This gets hit in a moment.
8. Move south a bit and set another geofence on where N Stelling Rd meets Stevens Creek Blvd. This geofence will not get hit. 
9. Set the app in the background by pressing cmd+shift+h.
10. Go to Debug => location => Freeway Drive. 
11. Wait until the debug toast tells you that the geofence has been entered. 
12. Switch back to the app and notice that both geofences are present on the map. 
13. Terminate and restart the app. Press the arrow in lower left corner to center map on current location. Zoom out to verify that both geofences really do still exist. 
14. Terminate the app. 
15. Notice that the iOS location indicator shows you that geofences are being monitored in the background (the arrow next to the battery is outlined instead of filled)
16. Restart the Freeway drive as in step 8.
17. Wait unit the debug toast tells you that the geofence has been entered. 
18. Wait a bit more and then notice that the iOS location indicator disappeared, telling you that now NO geofences are being monitored in the background anymore. 
19. Restart the app. Center on current location and verify that both of our geofences have now been deleted!

The geofences were not supposed to be deleted.

It is possible to avoid this issue by setting the setting stopOnTerminate to 'false'. 
The problem with that solution is, that the app changes from using a geofence to actively using the position in the background after the geofence has been hit (the indicator next to battery indicator becomes filled instead of outlined after the geofence has been hit).

**Comment by christocracy** [comment]
Sorry, I was on vacation the past 2 weeks.  I'll look into this.

**Comment by christocracy** [comment]
This issue is probably obsolete since the Geofence System has been completely refactored in latest version.
