### ISSUE TITLE
Runaway http Updates

### ISSUE THREAD

**Issue by TARJr** [transistorsoft/cordova-background-geolocation-lt#1354]
## Your Environment
* Plugin version: 4.4.2
* Platform: iOS or Android Android
* OS version: 12
* Device manufacturer / model: Pixel 4a
* Cordova version (`cordova -v`): 10.1.2
* Cordova platform version (`cordova platform ls`):
* Installed platforms:
  android 9.1.0
  browser 6.0.0
Available platforms:
  electron ^3.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
import { Injectable } from '@angular/core';
import BackgroundGeolocation, { ProviderChangeEvent } from 'cordova-background-geolocation-lt';
import { Platform, ToastController } from 'ionic-angular';
import { get } from 'lodash-es';
import { ReplaySubject, Subject } from 'rxjs';
import { UtilsService } from '../services/utils.service';
import { API_INFO } from './api';
import { Logger } from './logger';
import { Settings } from './settings';

type TProviderStatus = 'on' | 'off' | null;

type TProviderState = {
    status: TProviderStatus,
    changeEvent: ProviderChangeEvent,
    phoneMac: string,
};

@Injectable()
export class BackgroundGeolocationProvider {
    public $providerState: ReplaySubject<TProviderState | null> = new ReplaySubject(1);
    public $providerChanged: Subject<ProviderChangeEvent> = new Subject();
    private _providerState: TProviderState | null;
    private phoneMac: string;


    private set providerState(value: Partial<TProviderState> | null) {
        this._providerState = {
            ...this._providerState,
            ...value,
        };

        this.$providerState.next(this._providerState);
    }

    get hasBEAccess() {
        return;
    }


    constructor(
        private utilsProvider: UtilsService,
        private platform: Platform,
        private toastCtrl: ToastController,
        private logger: Logger,
        private settingsProvider: Settings,
    ) {
        if (!this.platform.is('cordova')) {
            console.log('skip BackgroundGeolocation');

            return;
        }


        this.utilsProvider.phoneMac().then((mac) => {
            this.phoneMac = mac;

            if (!BackgroundGeolocation || !mac) return;

            BackgroundGeolocation.onActivityChange((event) => {
                console.error('[onActivityChange] ', event);
            });

            BackgroundGeolocation.onMotionChange((event) => {
                if (event.isMoving) {
                    console.error('[onMotionChange] Device has just started MOVING ', event.location);
                    this.logger.info(`BackgroundGeolocationProvider:: MOVING`);
                    BackgroundGeolocation.getCurrentPosition({
                        samples: 1,
                        persist: true
                    }).then((location) => {
                        console.log('[getCurrentPosition] ', location);
                    });

                } else {
                   console.log('[onMotionChange] Device has just STOPPED:  ', event.location);
                }
            });

            const subscription = BackgroundGeolocation.onHeartbeat((event) => {
                console.log('[onHeartbeat] ', event);
            });


            BackgroundGeolocation.onProviderChange(async (event) => {
                this.$providerChanged.next(event);

                try {
                    const state = await BackgroundGeolocation.getState();
                    const status = this.getStatus(state.enabled, event);

                    this.providerState = {
                        status,
                        changeEvent: event,
                        phoneMac: this.phoneMac,
                    };
                } catch (error) {
                    this.settingsProvider.updateSettings({
                        trackThisPhone: false
                    });

                    this.providerState = {
                        status: null,
                        changeEvent: event,
                        phoneMac: this.phoneMac,
                    }
                }
            });

            BackgroundGeolocation.ready({
                reset: true,
                debug: false,
                locationAuthorizationRequest: 'Always',
                backgroundPermissionRationale: {
                    title: "Allow access to this device's location in the background?",
                    message: "Please enable 'Allow all the time permission",
                    positiveAction: "Change to Allow all the time"
                },
                /* iOS only */
                locationAuthorizationAlert: {
                    titleWhenNotEnabled: 'Yo, location-services not enabled',
                    titleWhenOff: 'Location-services are OFF',
                    instructions: "You must enable 'Always' in location-services",
                    cancelButton: 'Cancel',
                    settingsButton: 'Settings'
                },
                stationaryRadius: 50,
                /* Common */
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: this.platform.is('ios') ? 300 : 0,
                desiredOdometerAccuracy: 10,
                /* android only */
                foregroundService: true,
                locationUpdateInterval: 15 * 1000,
                fastestLocationUpdateInterval: 120000,
                allowIdenticalLocations: false,
                /* **** */
                stopOnTerminate: false,
                startOnBoot: true,
                url: `${API_INFO.DEVICE_API}/v1/devices/tracks`,
                method: 'PUT',
                autoSync: true,
                httpRootProperty: 'PHS_LOCATION'
            });
        });
    }

    public sendLogs() {
        console.log('sending log');
        const Logger = BackgroundGeolocation.logger;
        Logger.emailLog('support@email.com').then((success) => {
            this.logger.info(`[emailLog] SUCCESS`);
          }).catch((error) => {
            this.logger.info(`[emailLog] FAILURE: ${error}`);
          });

    }

    public start() {
        BackgroundGeolocation.getState((state) => {
            this.logger.info(`BackgroundGeolocationProvider::start: enabled? ${state.enabled}`);
            this.providerState = {
                status: this.getStatus(state.enabled, get(this._providerState, 'changeEvent', false)),
                phoneMac: this.phoneMac
            };

            if (!state.enabled) {
                BackgroundGeolocation.start(() => {
                    console.log(`BackgroundGeolocationProvider::start: OK`);

                    this.providerState = {
                        status: this.getStatus(true, get(this._providerState, 'changeEvent', false)),
                        phoneMac: this.phoneMac
                    };

                }, (err) => {
                    this.logger.error(`BackgroundGeolocationProvider::start: error ${err}`);
                });
            }
        });
    }

    public stop() {
        BackgroundGeolocation.getState((state) => {
            this.logger.info(`BackgroundGeolocationProvider::stop: enabled? ${state.enabled}`);
            this.providerState = {
                status: this.getStatus(state.enabled, get(this._providerState, 'changeEvent', false)),
                phoneMac: this.phoneMac
            };

            if (state.enabled) {
                BackgroundGeolocation.removeListeners();
                BackgroundGeolocation.stop(() => {
                    console.log(`BackgroundGeolocationProvider::stop: OK`);

                    this.providerState = {
                        status: this.getStatus(false, get(this._providerState, 'changeEvent', false)),
                        phoneMac: this.phoneMac
                    };
                }, (err) => {
                    this.logger.error(`BackgroundGeolocationProvider::stop: error ${err}`);
                });
            }
        });
    }

    private getStatus(BGEnabled: boolean, event: ProviderChangeEvent | false): TProviderStatus {
        let status: 'on' | 'off' | null = null;

        if (this.phoneMac) {
            if (BGEnabled) { 
                status = 'on';
            } else {
                status = 'off';
            }
        }

        return status;
    }

}

```

## Expected Behavior

plugin posting updates continuously

## Actual Behavior

I'm seeing non-stop updates on my phone and a customer's phone:

my phone showed is_moving: 1   (wasn't moving all night) (Pixel 4a, my
verbose logs attached)
cust phone showed is_movng: 0  (his geo never changed) (Galaxy A51,
unable to get logs)

(both phones stuck on opposite moving states, yet plugin continued to
send updates)

## Steps to Reproduce

1.
Pixel 4a attached verbose BG Log significant times:

05-31 22:21:25.857 ->  our http service was fixed to return 201 and
accept all records

...http updates every 2 minutes, non-stop, phone never moved

06-01 04:47:25.153 ->  I stopped BG service (in the app)

06-01 05:17:23.325 ->  I restarted BG service (in the app)

...updates and tracking returned to normal

2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
[background-geolocation (4).log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/8814765/background-geolocation.4.log)

**Comment by TARJr** [comment]
Not sure what a Mock location app would be.

**Comment by TARJr** [comment]
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android
Studio Gradle projects

# Project target.
target=android-29
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/txxxx-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:18.+
cordova.system.library.2=androidx.appcompat:appcompat:1.2.0
cordova.system.library.3=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.4=org.greenrobot:eventbus:3.2.0
cordova.system.library.5=io.github.nishkarsh:android-permissions:0.1.8
cordova.system.library.6=org.slf4j:slf4j-api:1.7.25
cordova.system.library.7=com.github.tony19:logback-android:2.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/xxxxx-build.gradle
cordova.system.library.8=com.google.android.play:core:1.8.0
cordova.gradle.include.3=cordova-support-google-services/xxxxx-build.gradle
cordova.gradle.include.4=phonegap-plugin-multidex/xxxxx-multidex.gradle
cordova.system.library.9=androidx.legacy:legacy-support-v13:1.0.0
***@***.***
cordova.system.library.11=com.google.firebase:firebase-messaging:17.0.+

**Comment by TARJr** [comment]
I'm going to take that out, it was put in for testing.

**Comment by TARJr** [comment]
Thanks. I'll wait for the updated fix.

**Comment by TARJr** [comment]
Not sure this is related, but location was not updating for several hours, should have (same phone), had to reset BG:
last update was 17:11:32

╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🎾  ENTER: still
╚═════════════════════════════════════════════
06-06 17:11:32.273 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
06-06 17:11:32.339 INFO [HttpService$i onResponse] 
  🔵  Response: 201
06-06 17:11:32.340 DEBUG [b destroy] 
  ✅  DESTROY: 534f7811-e9d7-42ab-b34a-61ddec5d5222
06-06 17:11:32.344 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 181
06-06 17:11:32.345 DEBUG [AbstractService a] ⚙️︎  finish BackgroundTaskService [eventCount: 0, sticky: false]
06-06 17:11:32.346 DEBUG [AbstractService onDestroy] 
  🔴  BackgroundTaskService destroyed
06-06 17:11:32.435 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService destroyed
06-06 17:11:32.531 DEBUG [AbstractService onDestroy] 
  🔴  ActivityRecognitionService destroyed
06-06 17:11:39.691 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-06 17:11:49.916 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-06 17:11:49.920 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-06 17:24:52.310 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-06 17:25:10.873 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-06 17:25:10.875 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-06 17:40:31.340 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-06 17:40:46.308 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-06 17:40:46.312 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-06 17:49:12.338 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-06 17:49:30.876 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-06 17:49:30.879 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-06 18:12:54.582 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-06 18:18:54.323 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════
06-06 22:35:10.597 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-06 22:42:45.053 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-06 22:43:02.580 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-06 22:43:02.583 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).

**Comment by christocracy** [comment]
Are you doing something in the app `pause` / `resume` events?

**Comment by TARJr** [comment]
Just logging events, nothing else being done:

    this.resumeSubscription = this.platform.resume.subscribe(async () => {
      logger.info('App:onResume');
