### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found in Android

### ISSUE THREAD

**Issue by narenderreddych** [transistorsoft/cordova-background-geolocation-lt#1356]
## Your Environment
* Plugin version: 4.8.0
* Platform: iOS or Android
* OS version:12
* Device manufacturer / model: Honor 20
* Cordova version (`cordova -v`): 11.0.0
* Cordova platform version (`cordova platform ls`): android 9.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```
Installed the plugin and compile it 

## Expected Behavior

should run the code and give the apk
## Actual Behavior

Getting error  AAPT: error: resource android:attr/lStar not found in Android
I got the following after installing your plugin:
AAPT: error: resource android:attr/lStar not found.

Several alternatives, such as removing the diagnostics plugin or removing and re-adding the platform, did not work

Currently I am using Cordova 9.1 for Android 
## Steps to Reproduce

1. cordova plugin add cordova-background-geolocation-lt
2. cordova prepare
3. cordova compile
4. AAPT: error: resource android:attr/lStar not found.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Currently I am using Cordova 9.1 for Android

1. You need to use latest.

```
$ cordova -v
11.0.0

$ cordova platform
Installed platforms:
  android 10.1.2
  ios 6.2.0
```

2. You need to use `compileSdkVersion 31`

Here's how I use `compileSdkVersion 31` in the *SampleApp*.
1.  [config.xml](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/config.xml#L36)
2. [create file `src/android/build-extras.gradle`](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/src/android/build-extras.gradle#L9)

You only need this one line:
```gradle
ext.cdvSdkVersion="31"
```

**Comment by narenderreddych** [comment]
it does not support cordova android@9.1.0?

android 10.1.2 having issues in build-tools so am unable to upgrade it
I am using Cordova/javascript

**Comment by christocracy** [comment]
>it does not support cordova android@9.1.0?

I doubt it.

>android 10.1.2 having issues in build-tools

Likely because you're not using `compileSdkVersion 31`

You need to upgrade to latest cordova/cordova-android.

**Comment by christocracy** [comment]
>I've added a geofence with exit notification but have not been prompted when leaving the geofence.

On a *real* device or emulator?   Geofences hardly ever fire in the emulator.

- Configure the plugin with `debug: true` and `LOG_LEVEL_VERBOSE` (see Wiki [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging))
- Create a geofence around your current position.
- Go for a walk of at least 200 meters.  With `debug: true`, you will hear the Geofence EXIT event.

```javascript
BackgroundGeolocation.onGeofence((event) => {
  console.log('[onGeofence] ', event);
});

const state = await BackgroundGeolocation.ready({
  debug: true,
  BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: false,
  locationAuthorizationRequest: 'Always'
});

const location = await BackgroundGeolocation.getCurrentPosition();

BackgroundGeolocation.addGeofence({
  latitude: location.coords.latitude,
  longitude: location.coords.longitude,
  radius: 200,
  identifier: 'HOME'
  notifyOnEntry: true,
  notifyOnExit: true  
});
```
