### ISSUE TITLE
iOS- duplicate symbols for architecture arm64 - linker command failed

### ISSUE THREAD

**Issue by narenderreddych** [transistorsoft/cordova-background-geolocation-lt#1357]
![test2](https://user-images.githubusercontent.com/7994498/176900902-6eabe32d-d187-4014-bc86-af7bf4b62558.png)

Installed in iOS environment to check the background location.
installtion done without error
prepared well
but while building got an error.
 
## Your Environment
* Plugin version:4.8.0
* Platform: iOS
* OS version: 12.4
* Device manufacturer / model: Mac 12.4/iPhone 6s 15.x
* Cordova version (`cordova -v`):11.0.0
* Cordova platform version (`cordova platform ls`):iOS 6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

Should build with out linker errors
## Actual Behavior

Getting error as duplicate symbols and linker command failed
## Steps to Reproduce

1. install plugin
2.cordova prepare
3.cordova build
4.got an error

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by narenderreddych** [comment]
here are the plugins we using

com-badrit-contactpicker 0.3.0 "ContactPicker"
com.googlemaps.ios 3.9.0 "Google Maps SDK for iOS"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-background-geolocation-lt 4.8.0 "BackgroundGeolocation"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-android-fingerprint-auth 1.5.0 "FingerprintAuth"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-apprate 1.5.0 "AppRate"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-background-fetch 7.1.1 "CDVBackgroundFetch"
cordova-plugin-background-geolocation 3.1.0 "CDVBackgroundGeolocation"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-battery-status 2.0.3 "Battery"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 4.0.0 "BuildInfo"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-camera 5.0.2 "Camera"
cordova-plugin-cocoapod-support 1.6.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-customurlscheme 5.0.0 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file-transfer 2.0.0-dev "File Transfer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-fingerprint-aio 3.0.1 "FingerprintAllInOne"
cordova-plugin-firebase-analytics 6.1.0 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-ios-contacts-permissions 1.2.0 "iOS Permissions"
cordova-plugin-ios-location-permissions 1.2.0 "iOS Permissions"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.5 "Whitelist"
cordova-plugin-wkwebview-file-xhr 3.0.0 "Cordova WKWebView File XHR Plugin"
cordova-plugin-x-socialsharing 5.6.3 "SocialSharing"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"

**Comment by christocracy** [comment]
>cordova-plugin-background-geolocation 3.1.0 "CDVBackgroundGeolocation"

This is your problem.  This is a fork of my original open-source project, which happens to share similar "*symbols*".  Remove it.

### Unrelated

>cordova-plugin-background-mode 0.7.3 "BackgroundMode"

If you don't want *Apple* to [reject your app](https://github.com/katzer/cordova-plugin-background-mode/issues?q=rejected), you should remove this.

>android 10.1.2 having issues in build-tools so am unable to upgrade it

No wonder you have issues (as noted at #1356) .  You have a giant amount of plugins, many of which are abandoned.

- [`cordova-plugin-cocoapods-support`](https://github.com/blakgeek/cordova-plugin-cocoapods-support):  No update in 3 years.
- [`cordova-plugin-browsertab`](https://www.npmjs.com/package/cordova-plugin-browsertab):  No update in 5 years
- [`cordova-universal-links-plugin`](https://github.com/nordnet/cordova-universal-links-plugin):  Publicly stated __"DEPRECATED"__

You need to audit *each* of your plugins and check upon their current state.  Remove deprecated / stale plugins and/or update to latest version.
