### ISSUE TITLE
Incompatibility with Intercom (Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1)

### ISSUE THREAD

**Issue by crazybaud** [transistorsoft/cordova-background-geolocation-lt#136]
Hello,

We have an incompatibility between `cordova-background-geolocation-lt@1.6.2` and `cordova-plugin-intercom@1.1.7` : `Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;`. If we remove one of the two, everything works. We use Meteor framework.

Intercom suggest to update dependency of the concerned package https://github.com/intercom/intercom-cordova#android-dex-errors (a similar comment here https://github.com/jeduan/cordova-plugin-facebook4/issues/11#issuecomment-127066535 )

In https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/122, @christocracy you suggest to update `meteor add cordova:cordova-plugin-android-support-v4@21.0.1` but no result on our side, the error seems different.

Do you have a suggestion ?

Thanks for this plugin

Possible duplicate : https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/122
Error detail : http://pastebin.com/mxKVyyAP
Related plugin : https://github.com/intercom/intercom-cordova
Version : java 1.8.0_92, Meteor 1.3.2.4 (https://guide.meteor.com/mobile.html)

**Comment by christocracy** [comment]
There's nothing wrong with my Gradle dependencies.

I don't do anything stupid.

On Friday, June 24, 2016, Crazy <notifications@github.com> wrote:

> Hello,
>
> We have an incompatibility between cordova-background-geolocation-lt@1.6.2
> and cordova-plugin-intercom@1.1.7 : Multiple dex files define
> Lcom/google/android/gms/iid/MessengerCompat$1;. If we remove one of the
> two, everything works. We use Meteor framework.
>
> Intercom suggest to update dependency of the concerned package
> https://github.com/intercom/intercom-cordova#android-dex-errors (a
> similar comment here jeduan/cordova-plugin-facebook4#11 (comment)
> <https://github.com/jeduan/cordova-plugin-facebook4/issues/11#issuecomment-127066535>
> )
>
> In #122
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/122>,
> @christocracy <https://github.com/christocracy> you suggest to update meteor
> add cordova:cordova-plugin-android-support-v4@21.0.1 but no result on our
> side, the error seems different.
>
> Do you have a suggestion ?
>
> Thanks for this plugin
>
> Possible duplicate : #122
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/122>
> Error detail : http://pastebin.com/mxKVyyAP
> Related plugin : https://github.com/intercom/intercom-cordova
> Meteor : https://guide.meteor.com/mobile.html
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/136>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l6VDCHUZnjCR_VX4KLBzdpqn61Nvks5qPBGMgaJpZM4I99WK>
> .
>


-- 
Snet form Gmail Mobile

**Comment by crazybaud** [comment]
> I don't do anything stupid.
Of course, I tried to help to localize the issue, as much as I can. 

Do you have any idea of the origin ? Should I investigate something in particular ?

**Comment by christocracy** [comment]
Here's Android build.gradle.
https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/build.gradle


On Friday, June 24, 2016, Crazy <notifications@github.com> wrote:

> I don't do anything stupid.
> Of course, I tried to help to localize the issue, as much as I can.
>
> Do you have any idea of the origin ? Should I investigate something in
> particular ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/136#issuecomment-228419515>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lz56zi60n876jPL2TKitECDm6rmLks5qPB4cgaJpZM4I99WK>
> .
>


-- 
Snet form Gmail Mobile

**Comment by crazybaud** [comment]
Thanks for having shown the way.

So based on this https://github.com/intercom/intercom-cordova/issues/54 and on this fork commit https://github.com/37d/intercom-cordova/commit/cccf24a00c80724ae9473f35bf4feff2a1ca4ace , it seems to be on Intercom side.

**Comment by christocracy** [comment]
Yes, it was a mistake on their side to **pin** play-services at `8`.  Many other devices might still use `7`.

**Comment by christocracy** [comment]
I've come up with a new plugin for solving Google API dependency issues.  See #453
