### ISSUE TITLE
Build Failed in Android

### ISSUE THREAD

**Issue by javico-dev11** [transistorsoft/cordova-background-geolocation-lt#1364]
## Your Environment
* Plugin version: 4.8.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: MAR-LX3A
* Cordova version (`cordova -v`): 11.0.0
* Cordova platform version (`cordova platform ls`): 
* Installed platforms:
  android 10.1.2
Available platforms: 
  browser ^6.0.0
  electron ^3.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

After the plugin installation, it should allow you to compile the app
## Actual Behavior

Before installing the plugin, the app compiles correctly, after installing the plugin, when trying to compile, it generates an error: The minCompileSdk (31) specified in a
      dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
      is greater than this module's compileSdkVersion (android-30).
## Steps to Reproduce

1. 
2.
3.
4.

## Context

I am trying to get the location of the device even if the app closes completely.
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
adb
</details>

**Comment by christocracy** [comment]
That's right.  `compileSdkVersion 31` is now required.

See the *SampleApp* to learn how to define a custom [build-extras.gradle](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/config.xml#L36).  Within that custom `build-extras.gradle`, add the following one line:

```gradle
ext.cdvSdkVersion="31"
```

**Comment by javico-dev11** [comment]
Oh I understand, thank you very much for the information, I will try with your recommendation.
