### ISSUE TITLE
black screen when launching th app in my device and then exit

### ISSUE THREAD

**Issue by need4android-com** [transistorsoft/cordova-background-geolocation-lt#1367]
**cordova platform ls**
Installed platforms:
  android 10.1.2
Available platforms:
  browser ^6.0.0
  electron ^3.0.0
  windows ^7.0.0

**cordova plugins**
cordova-background-geolocation-lt 4.8.1 "BackgroundGeolocation"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-background-fetch 7.1.1 "CDVBackgroundFetch"

**framework**
ExtJs 7.6.0 modern

**Comment by christocracy** [comment]
Launching what app?  Your app or my demo app?

see wiki *Debugging* and learn to observe logs

**Comment by need4android-com** [comment]
>I'm trying the demo app(cordova-background-geolocation-lt) , so I've just built it with cordova cli and when launching the app-debug.apk in my device it shows black screen and then exit!

**Comment by christocracy** [comment]
The answer is in `adb logcat`.

see wiki *Debugging* and learn to observe logs.
