### ISSUE TITLE
The application starts tracking without calling start() method

### ISSUE THREAD

**Issue by idanperlmutter** [transistorsoft/cordova-background-geolocation-lt#137]

**Comment by christocracy** [comment]
The plugin persists it's "started" state between app restarts.  If you
close the app while it was started, it will automatically start itself when
rebooted.

On Tue, Jun 28, 2016 at 6:57 AM, idanperlmutter <notifications@github.com>
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/137>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lyk6DyS2So8aL6iAgWmmj89j4I8Dks5qQP4dgaJpZM4I_-tx>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by mathias-falkenberg** [comment]
Actually, if you set a geofence while the app is in the *stopped* state, it seems to start in the *started* state, when the geofence is hit...

**Comment by christocracy** [comment]
Yes, if you add a geofence **while the plugin is in the "stopped" state**, it **will** in fact begin monitoring that geofence immediately.

The plugin shouldn't do this.  This is a bug.

**Comment by andpoulsen** [comment]
Actually, we'd like to be able to use geofences, while the location tracking is off. 
Or in other words: we'd like for our app to only have the outlined "location arrow" next to the battery indicator instead of the filled one. 
The reason for this is that we want our app to consume no battery or cpu in the background expect when a geofence is hit. 
As we understand it, when the plugin is on (the arrow is filled), then the app or at least the plugin is in fact continuously receiving location updates, which must consume some battery.

**Comment by christocracy** [comment]
Your use-case is not currently supported.  I'm working on a new *geofence-only* tracking mode but it's not ready yet.

**Comment by andpoulsen** [comment]
Is there an ETA on this? Like approx how many months might we have to wait if we wait for it?
We were considering to workaround-it by: Stop the plugin. Set a geofence. If the app gets started by a geofence-event, then we'll read out all geofences, delete them, stop the plugin and set them again. 
But if course we'd rather be using a plugin that is actually designed to do what we need.

**Comment by christocracy** [comment]
Might be a month.  I have a beta working in Android currently.

**Comment by christocracy** [comment]
A Geofence-only mode for both iOS & Android is currently being field-tested.

**Comment by christocracy** [comment]
Geofence-only mode is now available.
