### ISSUE TITLE
Installation of plugin fails

### ISSUE THREAD

**Issue by kevinmcody** [transistorsoft/cordova-background-geolocation-lt#1374]
## Your Environment
* Plugin version: [latest]
* Platform: Android
* OS version: Windows 11
* Device manufacturer / model: [N/A]
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): android 9.1.0 , ios 6.1.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
cordova plugin add cordova-background-geolocation-lt```

## Expected Behavior
<!--- Tell us what should happen -->
the plugin should install
## Actual Behavior
<!--- Tell us what happens instead -->
The following error is thrown:

Running command: pod install --verbose
Searching for inspections failed: undefined method `map' for nil:NilClass

      report.issues = results['items'].map { |item| Issue.new(item) }
                                      ^^^^

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1. open PowerShell
2. cd to project directory
3. cordova plugin add cordova-background-geolocation-lt
4. 

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat
-->
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Plugin version: [latest]

this is meaningless.  Post the **Exact** version

**Comment by christocracy** [comment]
> Installation of plugin fails

What is the evidence of failure?

**Comment by kevinmcody** [comment]
> > Plugin version: [latest]
> 
> this is meaningless. Post the **Exact** version

4.92

**Comment by kevinmcody** [comment]
> > Installation of plugin fails
> 
> What is the evidence of failure?

this error is thrown during the installation:

Running command: pod install --verbose
Searching for inspections failed: undefined method `map' for nil:NilClass

      report.issues = results['items'].map { |item| Issue.new(item) }
                                      ^^^^

**Comment by christocracy** [comment]
**edit** your initial post to add required information.

**Comment by kevinmcody** [comment]
done

**Comment by christocracy** [comment]
Have you googled your error “* undefined method `map' for nil:NilClass*”?

**Comment by kevinmcody** [comment]
> Have you googled your error “_Cordova undefined method `map' for nil:NilClass_”?

Yes.  It leads me down Ruby rabbit holes.  I was hoping to avoid having to learn Ruby to use a Cordova plugin.
