### ISSUE TITLE
LocationTemplate is not updating via .setConfig or .configure methods. the location template set at the beginning is coming to server always.

### ISSUE THREAD

**Issue by qwicksoftteam** [transistorsoft/cordova-background-geolocation-lt#1379]
## Your Environment
* Plugin version: 4.3.0 
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: Samsung / M21
* Cordova version (`cordova -v`):  
* Cordova platform version (`cordova platform ls`): cordova-android 8.1.0
* Plugin config provided to `#ready`:
* let postTemplate = {
      u_latitude: "<%= latitude %>",
      u_longitude: "<%= longitude %>",
      u_direction: "<%= heading %>",
      u_flag: null,
      u_driverid: null,
      u_mastercartypeid: null,
      u_cityid: null,
      u_companyid: null,
      u_orgid: ORG_ID,
      u_bookingid: null,
    };
* 
* {
        reset: true,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        method: "POST",
       
        url: "http://192.168.0.115:7893/location",
        
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        locationUpdateInterval: 10000,
        locationTemplate: JSON.stringify(postTemplate),
        params: param,
      },
```
async resetBGL(reqBy: string) {
    this.storage.get("driverparam").then(async (driverparam) => {
      if (driverparam != null || driverparam != undefined) {
        const param = {
          u_flag: driverparam.u_flag,
          u_driverid: driverparam.u_driverid,
          u_mastercartypeid: driverparam.u_mastercartypeid,
          u_cityid: driverparam.u_cityid,
          u_companyid: driverparam.u_companyid,
          u_orgid: ORG_ID,
          u_bookingid: driverparam.u_bookingid,
        };

        console.debug("template while reset", param);
        BackgroundGeolocation.reset({
          reset: true,
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10,
          method: "POST",
          url: "http://192.168.0.115:7893/location",
          // url: UPDATE_LOCATION_URL,
          autoSync: true,
          stopOnTerminate: false,
          startOnBoot: true,
          locationUpdateInterval: 10000,
          locationTemplate: JSON.stringify(param),
        }).then(
          (s) => {
            console.debug("configure success", s);
          },
          (e) => {
            console.debug("configure failed", e);
          }
        );
        const a = await this.checkStatus();
        console.debug("reset called by", reqBy, a);
      }
    });
  }
```

## Expected Behavior

the data should be updated after the reset method because the driver flag will change
## Actual Behavior

the template set with null values in the beginning is hitting the server always.
I have tried reset, configure and setconfig methods inside the reset method.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You likely have existing locations in the plugins database.  Locations in db are not re-rendered.

see api docs .getLocations(), .destroyLocations()
