### ISSUE TITLE
My server doesn't get the POST params 

### ISSUE THREAD

**Issue by idanperlmutter** [transistorsoft/cordova-background-geolocation-lt#138]
I use the sync() method in order to save the data on my server and the server receives only empty array.
Thanks.

**Comment by christocracy** [comment]
Are you setting autoSync: false?

Are you using php?

On Tuesday, June 28, 2016, idanperlmutter <notifications@github.com> wrote:

> I use the sync() method in order to save the data on my server and the
> server receives only empty array.
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/138>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l5BF1HaQVrfrABz3KWT_y2YXK8hDks5qQRJagaJpZM4JACuz>
> .
>


-- 
Snet form Gmail Mobile

**Comment by idanperlmutter** [comment]
yes

**Comment by idanperlmutter** [comment]
Is there any problem with php? I cannot use it?

**Comment by christocracy** [comment]
php [is dumb](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/2)

**Comment by christocracy** [comment]
Duplicate #2
