### ISSUE TITLE
How to stop showing message saying that this application is using background location?

### ISSUE THREAD

**Issue by bassam-basamad-bupa** [transistorsoft/cordova-background-geolocation-lt#1382]
## Your Environment
* Plugin version: Latest version
* Platform: iOS or Android : Android
* OS version: 13.0
* Device manufacturer / model: Galaxy 10
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```
There is always an icon showing at the top of the screen of the app indicating that is fetching the location, how I can stop this notification, and also by the time, using the application, the Android OS, showing that this application is collecting your location while it is in the background. however, other applications, like "Maps", it's not showing this message.

Is there a way to hide this messages and icons?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The persistent notification is required by the OS for foreground services.  You cannot hide it.

The other notification is shown by the os for apps with “Always” location authorization.  See api docs Config.locationAuthorizationRequest.
