### ISSUE TITLE
motion detection

### ISSUE THREAD

**Issue by tanjentman** [transistorsoft/cordova-background-geolocation-lt#139]
Hey Chris, I cannot get the app to go into STATIONARY once it starts moving.  I will drive around for a about 5 minutes then pull into a parking lot and sit there for 3 minutes and the app never goes into STATIONARY.  I even see notifications saying it's moving even though I'm sitting there.  Here is my configuration:

bgGeo.configure({
            desiredAccuracy: 10, //meters
            stationaryRadius: 100, //meters
            stopTimeout: 2, //minutes
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle. 
            stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates 
            });

**Comment by christocracy** [comment]
Try desiredAccuracy: 0.

You're probably getting poor accuracy locations coming in and the
stopDetector timer keeps getting reset because it thinks you're moving.
There is only wifi/cell tower triangulation with desiredAccuracy != 0 (no
GPS)

On Thursday, June 30, 2016, tanjentman <notifications@github.com> wrote:

> Hey Chris, I cannot get the app to go into STATIONARY once it starts
> moving. I will drive around for a about 5 minutes then pull into a parking
> lot and sit there for 3 minutes and the app never goes into STATIONARY. I
> even see notifications saying it's moving even though I'm sitting there.
> Here is my configuration:
>
> bgGeo.configure({
> desiredAccuracy: 10, //meters
> stationaryRadius: 100, //meters
> stopTimeout: 2, //minutes
> debug: true, // <-- enable this hear sounds for background-geolocation
> life-cycle.
> stopOnTerminate: false, // <-- enable this to clear background location
> settings when the app terminates
> });
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l0yHZYHQQ6CM40yPgB2m8B-wWHW7ks5qRAM1gaJpZM4JCayI>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Also, set a distanceFilter of something like 50

On Thursday, June 30, 2016, tanjentman <notifications@github.com> wrote:

> Hey Chris, I cannot get the app to go into STATIONARY once it starts
> moving. I will drive around for a about 5 minutes then pull into a parking
> lot and sit there for 3 minutes and the app never goes into STATIONARY. I
> even see notifications saying it's moving even though I'm sitting there.
> Here is my configuration:
>
> bgGeo.configure({
> desiredAccuracy: 10, //meters
> stationaryRadius: 100, //meters
> stopTimeout: 2, //minutes
> debug: true, // <-- enable this hear sounds for background-geolocation
> life-cycle.
> stopOnTerminate: false, // <-- enable this to clear background location
> settings when the app terminates
> });
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l0yHZYHQQ6CM40yPgB2m8B-wWHW7ks5qRAM1gaJpZM4JCayI>
> .
>


-- 
Snet form Gmail Mobile

**Comment by tanjentman** [comment]
Ok, I'll try it right now.  Thanks for the quick response!

**Comment by tanjentman** [comment]
Just tried it and it's still not going into STATIONARY mode, nor is it triggering the onMotionChange event.  However, when I look at the location data there is a 4 minute gap at the time when I was just sitting there.

**Comment by tanjentman** [comment]
Hey Chris, any update on this one?  Thanks.

**Comment by christocracy** [comment]
Is this still an issue?  

Since you're a customer, you should post issues to the private repo.

**Comment by tanjentman** [comment]
Yes it's still an issue an I have reported it on the private repo.
