### ISSUE TITLE
iPhones randomly have 2-5 mile accuracy when wifi is on; instantly works when wifi turned off

### ISSUE THREAD

**Issue by caleb87** [transistorsoft/cordova-background-geolocation-lt#1393]
## Your Environment
* Plugin version: **3.8.0**
* Platform: **iOS** 
* OS version: **16.3.1**
* Device manufacturer / model: **iPhone** 
* Cordova version (`cordova -v`): 9.0

## Expected Behavior
The app has worked great for years using this plugin. In the past year, a few random iPhone users have reported that their GPS had 3-5 mile accuracy. More recently one user has found that **disabling** WiFi instantly provides an accurate coordinate (15-30 feet). Customers claim their other mapping apps work fine.

What are the odds that a bug like this could be caused by this plugin? Has anyone else had any problems like this?

**Comment by christocracy** [comment]
> What are the odds that a bug like this could be caused by this plugin?

0%

The plug-in uses the same iOS location api as any native app (`CLocationManager`).

**Comment by christocracy** [comment]
I’m field-testing this plug-in daily for about the last 9 years.  With many thousands of users over those years, nobody has ever reported anything like that.

**Comment by caleb87** [comment]
That's what I had figured, but it's such a weird bug, I'm exploring all possibilities. I will close this issue, but given your expertise, if you have any ideas what I could have my users test for, please let me know. I suspect either security software on the phone as these are corporate users, or very specific iOS versions and settings. I'm sure you're super busy, so no worries if you don't have 

Thanks!
