### ISSUE TITLE
Need to know some functionality

### ISSUE THREAD

**Issue by amarhtn** [transistorsoft/cordova-background-geolocation-lt#1395]
Hi,

We have purchased  your plugin for offline location fetching requirement. But we don't want to track the location all the time.

Only, we are using this plugin to get location in offline mode when user click on the get location button. Otherwise, there is no need to track /use the users location in background.

Due to this problem, we are not able to get approval by google play store. 

Please help us, Is there any option available to sleep the offline location tracking in background and only use it when needed.

**Comment by christocracy** [comment]
Ignored issue template:


*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
