### ISSUE TITLE
INVALID LICENSE ERROR

### ISSUE THREAD

**Issue by Microzone** [transistorsoft/cordova-background-geolocation-lt#140]
Hi

Getting the following error message when we try and implement the background geolocation plugin.

INVALID LICENSE

We added the bundle-id in the config.xml file.

`<widget xmlns="http://www.w3.org/ns/widgets" version="2.0.0" id="*************">`

And the code

```
var bgGeo = window.BackgroundGeolocation;

    // 1. First attach event-listeners
    bgGeo.onLocation(function(location, taskId) {
        console.log('- location: ', location);
        bgGeo.finish(taskId);
    }, function(errorCode) {
        console.error('- location error: ', errorCode);
    });
      //  .
    //. other event-listeners
    // 2. Compose your configuration.  DO NOT USE THE Settings SERVICE FROM SampleApp!!!!
    var simpleConfig = {
        // Geolocation Options
        desiredAccuracy: 0,
        distanceFilter: 10,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 1000,
        // Activity Recognition Options
        stationaryRadius: 25,
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        // Http Options
        //url: 'http://my.server.com/locations',
        //autoSync: true,
        // Application Options
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true,
        license: '*********************************************************************************'
    };

    // 3.  Configure the plugin.
    bgGeo.configure(simpleConfig, function(state) {
        // The plugin is now ready to be used.  It's important to note that the plugin *persists* its #enabled
        // between reboots:  if user closes the app and re-opens, once you #configure, the plugin will have
        // already #start-ed itself.

        if (!state.enabled) {
            bgGeo.start();
        }
    });
```

The above code is run on deviceready.

**Comment by christocracy** [comment]
Have you purchased a license?

On Monday, July 4, 2016, microzonesolutions <notifications@github.com>
wrote:

> Hi
>
> Getting the following error message when we try and implement the
> background geolocation plugin.
>
> INVALID LICENSE
>
> We added the bundle-id in the config.xml file.
>
> <widget xmlns="http://www.w3.org/ns/widgets" version="2.0.0"
> id="*************">
>
> And the code
>
> var bgGeo = window.BackgroundGeolocation;
>
>     // 1. First attach event-listeners
>     bgGeo.onLocation(function(location, taskId) {
>         console.log('- location: ', location);
>         bgGeo.finish(taskId);
>     }, function(errorCode) {
>         console.error('- location error: ', errorCode);
>     });
>       //  .
>     //. other event-listeners
>     // 2. Compose your configuration.  DO NOT USE THE Settings SERVICE FROM SampleApp!!!!
>     var simpleConfig = {
>         // Geolocation Options
>         desiredAccuracy: 0,
>         distanceFilter: 10,
>         locationUpdateInterval: 1000,
>         fastestLocationUpdateInterval: 1000,
>         // Activity Recognition Options
>         stationaryRadius: 25,
>         activityRecognitionInterval: 10000,
>         stopTimeout: 5,
>         // Http Options
>         //url: 'http://my.server.com/locations',
>         //autoSync: true,
>         // Application Options
>         debug: true,
>         stopOnTerminate: false,
>         startOnBoot: true,
>         license: '*********************************************************************************'
>     };
>
>     // 3.  Configure the plugin.
>     bgGeo.configure(simpleConfig, function(state) {
>         // The plugin is now ready to be used.  It's important to note that the plugin *persists* its #enabled
>         // between reboots:  if user closes the app and re-opens, once you #configure, the plugin will have
>         // already #start-ed itself.
>
>         if (!state.enabled) {
>             bgGeo.start();
>         }
>     });
>
> The above code is run on deviceready.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/140>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lzS9cA12EY5mFZvKXtgtIFOXl7_oks5qSPWZgaJpZM4JEToJ>
> .
>


-- 
Snet form Gmail Mobile

**Comment by Microzone** [comment]
Yes we have

**Comment by Microzone** [comment]
Hi, yes we have. We bought the Pro edition and we are using our first licence generated under product manager page.

**Comment by diegoqlima** [comment]
@Microzone @christocracy 
Hi, i'm getting the same error.
My guess: Google Reposity revision 31.
At other machine with the same package at version 25/26 there's no problem.

I'm sorry for my poor english.

**Comment by christocracy** [comment]
Are you a customer?

**Comment by diegoqlima** [comment]
Yes, how can i confirm ?

**Comment by christocracy** [comment]
If you're a customer, you should not use the free repo.  Use the private [Premium repo](https://github.com/transistorsoft/cordova-background-geolocation)

**Comment by diegoqlima** [comment]
ok, thanks
