### ISSUE TITLE
App doesn't send location data in background since iOS 16.4.

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1402]
## Your Environment
* Plugin version: 
"cordova-background-geolocation-lt": "4.10.0",
"cordova-plugin-background-fetch": "7.1.2",
"cordova-plugin-background-mode": "0.7.3",

* Platform: iOS
* OS version: 16.4
* Device manufacturer / model: Any
* Cordova version (`cordova -v`): 9
* Cordova platform version (`cordova platform ls`): ios 5
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 70,
    preventSuspend: true,
    stopOnTerminate: true,
    maxRecordsToPersist: 0,
    startOnBoot: false,
    notification: {
      text: "Touch to open",
      priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN
    },
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: {
      title: "Our app needs access to your location even when the app is closed or in the background, for the following reasons"
      message: "Send you nearby work from fleet the management",
      positiveAction: "Allow"
    }
```

## Expected Behavior
The app should work in background, as worked in earlier version to 16.4.

## Actual Behavior
No geolocation outgoing HTTP requests are sent to remote.

## Debug logs
I don't know how I can find debug logs for an app already in the AppStore.

**Comment by christocracy** [comment]
iOS 16.4 made changes to CoreLocation.

upgrade to latest version.  See CHANGELOG.
