### ISSUE TITLE
SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger

### ISSUE THREAD

**Issue by Magiis** [transistorsoft/cordova-background-geolocation-lt#1403]
## Your Environment
* Plugin version: 4.11.3
* Platform: Android
* OS version: Android 9
* Cordova version (`cordova -v`): 11.0.0
* Cordova platform version (`cordova platform ls`):  android 10.1.2
* Plugin config provided to `#ready`: config = {
        isMoving: true,
        reset: true,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
        logMaxDays: 1,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 15,
        stopOnTerminate: true,
        startOnBoot: false,
        notification: {
          title: this.translateService.instant(
            "notifications.geolocation_active.title"
          ),
          text: this.translateService.instant(
            "notifications.geolocation_active.text"
          ),
        },
        foregroundService: true,
        heartbeatInterval: 60,
        preventSuspend: true,
        disableElasticity: true,
        autoSync: true,
        url: this.getUrl(driverId),
        locationTemplate:'{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "accuracy":<%= accuracy %>, "timestamp": "<%= timestamp %>" }',
        geofenceTemplate:'{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "accuracy":<%= accuracy %>, "timestamp": "<%= timestamp %>" }',
        headers: { Authorization: "Bearer " + this.connectionService.getToken() },
        maxRecordsToPersist: 1,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title: this.translateService.instant("notifications.geolocation_allow.title"),
          message: this.translateService.instant("notifications.geolocation_allow.message"),
          positiveAction: this.translateService.instant("notifications.geolocation_allow.accept"),
          negativeAction: this.translateService.instant("notifications.geolocation_allow.cancel")
        },
        stopTimeout: 999999999999999
      };
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
The expected behavior is that the application does not close.

## Actual Behavior
The actual behavior is that the application closes unexpectedly.

## Steps to Reproduce

1.Open the application.
2.Grant location permissions to the Transistor plugin.
3.After granting permissions, the application closes unexpectedly.

## Context
I am trying to use the application, but it keeps closing unexpectedly, which hinders my ability to perform tasks efficiently.

## Debug logs

<details>
	<summary>    Process: com.magiis.app.uat.driver, PID: 5719
    java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
        at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:11)
        at com.transistorsoft.locationmanager.logger.TSLog.getDatabaseAppender(Unknown Source:0)
        at com.transistorsoft.locationmanager.logger.TSLog$c.run(Unknown Source:0)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
		at com.transistorsoft.locationmanager.logger.TSLog$c.run(Unknown Source:0)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
I/Process: Sending signal. PID: 5719 SIG: 9</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Duplicate #1401
