### ISSUE TITLE
Cannot archive iOS app - Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1404]
## Your Environment
* Plugin version: 4.12.0
* Platform: iOS 
* OS version: Xcode Archive (Xcode's version 13.2.1)
* Cordova version (`cordova -v`): 11.1.0
* Cordova platform version (`cordova platform ls`):  ios 6.3.0

## Expected Behavior
Should proceed with Archive the app for sending it to the appstore.

## Actual Behavior
I got these kind of errors when trying to Archive it from Xcode:

Ld /Users/user/Library/Developer/Xcode/DerivedData/App_Name-bivwjoqyjlzbmnbqobqpzedovcnu/Build/Intermediates.noindex/ArchiveIntermediates/App\ Name/InstallationBuildProductsLocation/Applications/App\ Name.app/App\ Name normal (in target 'App Name' from project 'App Name')
    cd /Users/PATH/cordova/platforms/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -L/user/userName/Library/Developer/Xcode/DerivedData/App_Name-bivwjoqyjlzbmnbqobqpzedovcnu/Build/Intermediates.noindex/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos -L/Users/user/Library/Developer/Xcode/DerivedData/App_Name-bivwjoqyjlzbmnbqobqpzedovcnu/Build/Intermediates.noindex/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos/CocoaLumberjack -

...
...
and more and more really long kind of stuff.

More logs are attached next in this issue.

## Steps to Reproduce

1. I build the app successfully both from the Terminal using Cordova and manually in Xcode.
2. Then I select the Any iOS Device
3. Then I go to Product -> Archive in order to push the new version to the appstore.
4. Then I got the above mentioned error.

## Context
Send new version of the app to the store.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Undefined symbols for architecture arm64:
  "_objc_msgSend$jsonKey", referenced from:
      -[TSHttpService parseResponse:] in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$run:", referenced from:
      -[TSHttpService parseResponse:] in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$setCallback:", referenced from:
      ___30-[TSHttpService finish:error:]_block_invoke.158 in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$fireAuthorizationEvent:", referenced from:
      ___33-[TSHttpService doPost:callback:]_block_invoke_2 in TSLocationManager(TSHttpService.o)
      ___33-[TSHttpService doPost:callback:]_block_invoke.151 in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$syncedRecords", referenced from:
      ___33-[TSHttpService doPost:callback:]_block_invoke in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$resolve:success:failure:", referenced from:
      ___33-[TSHttpService doPost:callback:]_block_invoke in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$httpResponseBlock", referenced from:
      ___33-[TSHttpService doPost:callback:]_block_invoke in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$parseResponse:", referenced from:
      ___33-[TSHttpService doPost:callback:]_block_invoke in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$execute:callback:", referenced from:
      -[TSHttpService doPost:callback:] in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$first", referenced from:
      -[TSHttpService schedulePost] in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$maxBatchSize", referenced from:
      -[TSHttpService scheduleBatchPost] in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$postBatch:", referenced from:
      -[TSHttpService scheduleBatchPost] in TSLocationManager(TSHttpService.o)
  "_objc_msgSend$scheduleBatchPost", referenced from:
      ___23-[TSHttpService flush:]_block_invoke in TSLocationManager(TSHttpService.o)
```

</details>

**Comment by christocracy** [comment]
The latest version of the plugin was built with *XCode 14.3*.

I suggest you upgrade your XCode.
