### ISSUE TITLE
best settings for indoor tracking?

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1405]
## Your Environment
* Plugin version: latest
* Platform: iOS or Android
* OS version: 
* Device manufacturer / model:
* Cordova version (`cordova -v`): latest
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

is there a best settings for indoor tracking?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by mehmetkaynak** [comment]
for details : i want to track people inside a building entering and leaving a certain area. I have defined geofences for this. What is the optimal config for indoor? Can you help me?

**Comment by christocracy** [comment]
What sort of indoor tracking equipment do you have installed at the particular location where you're doing indoor tracking?

Indoor tracking is a **BIG TOPIC**, requiring the purchase of specialized equipment installed at the particular (eg: museum, shopping mall).

Without the installation of specialized equipment, using only an Android / iOS device, indoor tracking is *impossible*.  The best accuracy indoors is 40-60 meters.  Geofences (with a minimum radius of 200 meters) will not work indoors.

**Comment by christocracy** [comment]
Here's an example of how a large airport (London's Gatwick) does indoor tracking (with Bluetooth beacons):  
https://techcrunch.com/2017/05/25/gatwick-airport-now-has-2000-beacons-for-indoor-navigation/

**Comment by christocracy** [comment]
Wikipedia:  [Indoor Positioning System](https://en.wikipedia.org/wiki/Indoor_positioning_system)

**Comment by mehmetkaynak** [comment]
I want to keep track of the sales person's entrances and exits to stores that are usually 30+ meters in diameter. I tried today, but I didn't get a very good result. I probably need to do this with another device instead of the phone, right?

**Comment by mehmetkaynak** [comment]
> I want to keep track of the sales person's entrances and exits to stores that are usually 30+ meters in diameter. I tried today, but I didn't get a very good result. I probably need to do this with another device instead of the phone, right?

store locations are very different, some on the road and some in the mall.

**Comment by christocracy** [comment]
The minimum geofence radius, without specialized equipment installed at the location, is 200 meters.

you cannot do indoor tracking / geofencing without installing specialized equipment, which is beyond the scope of this plug-in.

Indoor tracking is *not* easy.  It is expensive and complex.
