### ISSUE TITLE
Plugin Installation fails with cordova-ios 7.0.0

### ISSUE THREAD

**Issue by erkenberg** [transistorsoft/cordova-background-geolocation-lt#1407]
## Your Environment
* Plugin version: 4.12.0
* Platform: iOS
* OS version: install time failure, not on device
* Device manufacturer / model:  install time failure, not on device
* Cordova version (`cordova -v`): 12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (`cordova platform ls`):  ios 7.0.0
* Plugin config provided to `#ready`:  install time failure, not on device (so not relevant)

## Expected Behavior
`cordova prepare ios`  successfully prepares the build and inlcudes the plugin without error

## Actual Behavior
`cordova prepare ios`  results in an error:

```
Error during processing of action! Attempting to revert...
Failed to install 'cordova-background-geolocation-lt': Error [ERR_UNHANDLED_ERROR]: Uh oh!
Unhandled error. ('"framework" tag with type "podspec" is no longer supported. Please use the "podspec" tag.')
    at new NodeError (node:internal/errors:371:5)
    at CordovaEventEmitter.emit (node:events:379:17)
    at CordovaEventEmitter.emit (.../node_modules/cordova-common/src/events.js:69:22)
    at install (.../node_modules/cordova-ios/lib/plugman/pluginHandlers.js:100:32)
    at ActionStack.process (.../node_modules/cordova-common/src/ActionStack.js:55:25)
    at PluginManager.doOperation (.../node_modules/cordova-common/src/PluginManager.js:111:24)
    at PluginManager.addPlugin (.../node_modules/cordova-common/src/PluginManager.js:141:21)
    at Api.addPlugin (.../node_modules/cordova-ios/lib/Api.js:258:14)
    at handleInstall (.../node_modules/cordova-lib/src/plugman/install.js:561:10)
    at .../node_modules/cordova-lib/src/plugman/install.js:344:28
Failed to restore platform "ios". You might need to try adding it again. Error: Error [ERR_UNHANDLED_ERROR]: Uh oh!
Unhandled error. ('"framework" tag with type "podspec" is no longer supported. Please use the "podspec" tag.')
Uh oh!
Unhandled error. ('"framework" tag with type "podspec" is no longer supported. Please use the "podspec" tag.')
```

## Steps to Reproduce
1. Create a cordova Project using `cordova-ios` 7.0.0
2. Add the plugin
3. Run `cordova prepare ios`

## Context
`cordova-ios` [7.0.0 was released a few days ago](https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md) and we wanted to update to it.
The relevant breaking change seems to be : 

> [GH-1340](https://github.com/apache/cordova-ios/pull/1340) chore!: Remove podspec support from framework tag

From what I see, the issue is likely in the [plugin.xml](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L45), where `<framework type="podspec">` is no longer supported.

**Comment by christocracy** [comment]
Fixed and released to `4.13.0`

**Comment by christocracy** [comment]
Thanks.  it will be done in `v4.13.1`.

It goes like this?
```xml
<podspec>
            <config>
                <source url="https://cdn.cocoapods.org/"/>  // <----------------------
            </config>
            .
            .
            .
</podspec>
```

**Comment by erkenberg** [comment]
Thanks again fort the quick response, yes, this is exactly how i tested IT locally 👍

**Comment by christocracy** [comment]
`v4.13.1` is released.  Thanks.

**Comment by erkenberg** [comment]
Thank you very much, works perfectly 👍
