### ISSUE TITLE
I get "Invalid Action" when I attempt to start schedule or to get onHeartbeat event

### ISSUE THREAD

**Issue by idanperlmutter** [transistorsoft/cordova-background-geolocation-lt#141]

**Comment by christocracy** [comment]
Android?

On Monday, July 4, 2016, idanperlmutter <notifications@github.com> wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/141>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lxtzYu53YGZnsO5sqOi4yvy6EOvjks5qSPwPgaJpZM4JEU1p>
> .
>


-- 
Snet form Gmail Mobile

**Comment by idanperlmutter** [comment]
yes

**Comment by relbraun** [comment]
There is any solution?

**Comment by christocracy** [comment]
You're probably using a version of the plugin before "schedule" or "heartbeat" were implemented.

Update your plugin to latest version.
