### ISSUE TITLE
HMS license validation failure toast

### ISSUE THREAD

**Issue by VardanTitan** [transistorsoft/cordova-background-geolocation-lt#1412]
## Your Environment
* Plugin version: 4.13.1
* Platform: Android
* OS version: 13
* Device manufacturer / model: Pixel 3a
* Cordova version (`cordova -v`): 12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (`cordova platform ls`):  android 12.0.0
* Plugin config provided to `#ready`:
```
  const commonOptions = {
                // Application config
                debug: false,
                stopOnTerminate: true,
                startOnBoot: false
            };
```

## Expected Behavior
We already purchased a license and we expect to run app without any toasts regarding license validation.

## Actual Behavior
App runs and shows a HMS license validation error on first screen.

## Steps to Reproduce

1. Add `com.transistorsoft.locationmanager.license_key` to config file.
2. Run app
3. HMS validation error is shown.

## Context
I have couple of questions:

1. How to disable HMS check if it's not needed?2. 
2. Would regular license check work if HMS license check failed? 

## Debug logs

<details>
	<summary>Logs</summary>

```
╔═════════════════════════════════════════════
║ LICENSE VALIDATION FAILURE: ****
╠═════════════════════════════════════════════
╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.hms.license" android:value="<YOUR LICENSE KEY>" />
╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
╚═════════════════════════════════════════════
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.4.0 (420)
╠═════════════════════════════════════════════
╟─ unknown Android SDK built for arm64 @ 10 (cordova)
╟─ HMS: true

```

</details>

**Comment by christocracy** [comment]
You seem to be running that app on an emulator with neither Google Play Services or Huawei Mobile Services installed.

Ensure Google Play Services installed.

**Comment by VardanTitan** [comment]
Thanks!!!

Didn't notice I run on emulator without Play services.
