### ISSUE TITLE
Information Required - What is the minimum plugin version I should install inorder to support API level 31(Android 12). 

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [transistorsoft/cordova-background-geolocation-lt#1414]
I'm seeing crash reports which points to this plugin( I will update here once I have the logs). But however we are using 3.10.0, which is next version I can upgrade to stay compatible to Android 31. I'm not able to gather any info from your change logs as well. Is there a compatibility table I can refer to?

**Comment by christocracy** [comment]
I have no idea.  

Use latest version or you’ll have problems with devices running latest iOS and Android versions

**Comment by Tejas-ChandraShekarRaju** [comment]
Hi @christocracy 

We use the below versions

**Target SDK -> 31
"cordova-background-geolocation-lt": "3.10.0",
"cordova-plugin-background-fetch": “6.1.1”
  "cordova-background-geolocation-lt": {
        "OKHTTP_VERSION": "3.12.+",
        "APPCOMPAT_VERSION": "28.+",
        "GOOGLE_API_VERSION": "16.0.0",
        "EVENTBUS_VERSION": "3.0.0"
      },**
    "cordova": "10.0.0",
    "cordova-android": "^9.1.0",

With the above versions we are facing the below issue for android 12 and 13. Can you please assist us here? 
<img width="1691" alt="image" src="https://github.com/transistorsoft/cordova-background-geolocation-lt/assets/41864599/34345adc-4f7c-401a-ad58-ed9525e42d1f">

<img width="1691" alt="image" src="https://github.com/transistorsoft/cordova-background-geolocation-lt/assets/41864599/f12256ce-6d3d-4e1d-8f06-d341c39fe318">

**Comment by christocracy** [comment]
You **need** to upgrade to the latest version.

**Comment by Tejas-ChandraShekarRaju** [comment]
This got resolved after upgrading to 4.9.4.

**Comment by christocracy** [comment]
4.9.4 will **not work** on devices running Android 13+

**Comment by Tejas-ChandraShekarRaju** [comment]
Noted. Will upgrade to latest when releasing for SDK 33. We can close this issue

**Comment by christocracy** [comment]
In the meantime, your Android 13+ users will find that your app won't work.

**Comment by Tejas-ChandraShekarRaju** [comment]
This is only my App targets Andoird SDK 34 correct? As long as the run time is targeting only Android SDK 33 then checks that are enforced for Android 34 shouldn't be a problem.
