### ISSUE TITLE
Too many wake ups after new update

### ISSUE THREAD

**Issue by mehmetkaynak** [transistorsoft/cordova-background-geolocation-lt#1419]
## Your Environment
* Plugin version:4.14.2
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
cordova-ios 6.3.0
cordova-android 12.0

The app started waking up a lot by itself and consuming a lot of battery.  IMG: https://pasteboard.co/oNfCDzbKASYg.png

**Comment by christocracy** [comment]
I see no such issue reported in the *Play Store Console* for the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp) published to Play Store with `4.14.3` for more than a month.  There are no issues reported for *React Native* or *Flutter* demo app, either.

<img width="1141" alt="Screenshot 2023-09-21 at 9 36 42 AM" src="https://github.com/transistorsoft/cordova-background-geolocation-lt/assets/14999/098f9bd7-2097-492b-88fb-913091222236">

**Comment by christocracy** [comment]
Also, your own application code and config will affect your performance, which you've not even provided.
