### ISSUE TITLE
Can I get some event before "stopAfterElapsedMinutes" occurs?

### ISSUE THREAD

**Issue by idanperlmutter** [transistorsoft/cordova-background-geolocation-lt#142]

**Comment by christocracy** [comment]
no.

**Comment by relbraun** [comment]
Maybe in future?

**Comment by christocracy** [comment]
Probably not.  What is the use-case?

**Comment by relbraun** [comment]
I use the parameter autoSync:false and want to send the whole data on before stop tracking

**Comment by christocracy** [comment]
what's wrong with the `motionchange` event?

**Comment by relbraun** [comment]
This event also doesnt work correctly.
I want to track one's driving and after 2 hours to turn it off automatically and send the data to server

**Comment by christocracy** [comment]
Hmm...I see.  It seems there *is* a need for an event here.

I will name it `stop`.  It might be ready in a couple of weeks.

**Comment by relbraun** [comment]
Thanks

**Comment by christocracy** [comment]
This is really old.  `enabledchange` has been implemented since this.
