### ISSUE TITLE
[Android] - App Crash in Android 13 because HMS

### ISSUE THREAD

**Issue by fgarciaand** [transistorsoft/cordova-background-geolocation-lt#1420]
## Your Environment
* Plugin version: 4.14.3
* Platform: Android
* OS version: Android 13
* Device manufacturer / model: Samsung Galaxy Note 20 or any Android 13 emulator
* Cordova version (`cordova -v`): 12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (`cordova platform ls`): android 12.0.1
* Cordova plugin list:
```
cordova-background-geolocation-lt 4.14.3 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 7.2.1 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.9 "Badge"
cordova-plugin-camera 7.0.0-dev "Camera"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-exit 1.0.3 "Exit"
cordova-plugin-file 8.0.0 "File"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 7.0.0-dev "Media"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-sms-plugin 1.0.3 "Cordova SMS Plugin"
cordova.plugins.diagnostic 7.1.2 "Diagnostic"
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

// After deviceReady, initial configuration
BackgroundGeolocation.ready({
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  //Parámetros relacionados con la distancia y la localización
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 20,
  elasticityMultiplier: 1,
  stopOnTerminate: true, 
  startOnBoot: false,
  url: ENDPOINT + 'tracking/trackUserLocation',
  extras: {
    id: userProfile.getId()
  },
  preventSuspend: true, //Para IOS
  heartInterval: 60,
  notification: {
    title: 'MyApp',
    text: 'Verificando su seguridad',
    smallIcon: "mipmap/icon_notification", // <-- defaults to app icon
    color: '#122a36'
  },
  //Permisos Android 11+
  locationAuthorizationRequest: 'Always',
  backgroundPermissionRationale: {
    title: "¿Permitir que MyApp acceda a la ubicación de este dispositivo en segundo plano?",
    message: "Para realizar un seguimiento de su actividad en una situación de Emergencia, habilite el permiso de ubicación a permitir siempre",
    positiveAction: "Cambiar a permitir siempre",
    negativeAction: "Cancelar"
  },
  locationAuthorizationAlert: {
    titleWhenNotEnabled: "Permisos para acceder a la ubicación desactivados",
    titleWhenOff: "Servicios de ubicación desactivados",
    instructions: "Para el correcto funcionamiento de MyApp debe habilitar 'Siempre' los servicios de ubicación",
    cancelButton: "Cancelar",
    settingsButton: "Configuración"
  }
}).then((state) => {
  console.log("[ready] BackgroundGeolocation is configured and ready to use", state); 
}).catch(error => {
  console.log("[ready]  BackgroundGeolocation.ready error: ", error);
});

// When an event occurs and App is running in background
BackgroundGeolocation.setConfig({
  autoSync: true,
  maxRecordsToPersist: 1,
  stopAfterElapsedMinutes: 10,
  stopOnTerminate: false
}).then(() => {
  //Inicio Trackeo en Background
  BackgroundGeolocation.start(function() {
    console.log("- Start success");
  });
});
```

## Expected Behavior
Prior to the cordova and plugins update I am performing, the application behaved correctly and did not crash.
## Actual Behavior
After the update the App crashes and the only errors I see in the LoCat are related to this plugin and HMS. This happens only on Android 13, I have tested on later versions of Android and the App does not crash.
Crashes are random but the App almost always crashes.

## Steps to Reproduce

1. Run the App in Android 13
2. When the App starts, BackgroundGeolocation.ready
3. While App is in Background, BackgroundGeolocation.setConfiguration
4. After BackgroundGeolocation.start, App crashes
5. The only errors I see in LogCat are related to this plugin and HMS:
<img width="1426" alt="image_2023_09_25T12_00_36_371Z" src="https://github.com/transistorsoft/cordova-background-geolocation-lt/assets/92478839/0810cd1b-8de6-4fcb-9f3a-6e0a05434e84">

## Context
I have to put the application in tracking mode and keep it in background, for this last one I use cordova-plugin-background-mode. HMS support are not needed.

## Debug logs (AndroidStudio - LogCat)
[myApp.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/12728314/myApp.log)

**Comment by christocracy** [comment]
The HMS log messages are harmless and expected your app is first launched as the plugin executes methods to discover if the device is running on a device with GMS or HMS installed.  They have nothing do do with your app crashing.
