### ISSUE TITLE
Missing $BACKGROUND_MODE_LOCATION in UIBackgroundModes

### ISSUE THREAD

**Issue by stib** [transistorsoft/cordova-background-geolocation-lt#1422]
This is similar to the issue listed here https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1225
except this is from the cordova plugin and not the capacitor plugin. I get the same warning that $BACKGROUND_MODE_LOCATION needs to be added to UIBackgroundModes in Info.plist

## Your Environment
* Plugin version: cordova-background-geolocation-lt@4.15.0
* Platform: iOS
* OS version: 13.5.2
* Device manufacturer / model: Mac
* Cordova version (`cordova -v`): 12.0.0
* Cordova platform version (`cordova platform ls`):
  android 9.1.0
  browser 6.0.0
  ios 6.2.0

## Expected Behavior
Shouldn't get the warning in "ionic cap ios sync".

## Actual Behavior
Getting this warning

[capacitor] [warn] Configuration might be missing for cordova-background-geolocation-lt.
[capacitor]        Add the following to the existing UIBackgroundModes entry of Info.plist:
[capacitor]        
[capacitor]        $BACKGROUND_MODE_LOCATION

The Xcode has the right flags checked as shown in the screenshot below.

<img width="478" alt="image" src="https://github.com/transistorsoft/cordova-background-geolocation-lt/assets/310258/d46e7746-9235-48a4-b76e-1ef437c5b037">

The only mention I see in the documentation is when installing the plugin pass an empty string to BACKGROUND_MODE_LOCATION when configuring for useSignficantChangesOnly which doesn't apply here.

I have been looking around but not sure what I need to do to address this. Perhaps I am missing some documentation on this somewhere as rest of the documentation is pretty thorough.

Thank you for your help.
-Sanjay

**Comment by christocracy** [comment]
Why are you using the Cordova version in a Capacitor app?  There’s a Capacitor version of this plug-in.

**Comment by stib** [comment]
It's a very old app that I haven't worked on for years and am trying to do the minimum upgrades so it is functional again. So I am trying to minimize the changes I have to make. As I understand it cordova plugins should work fine in a capacitor app.

**Comment by christocracy** [comment]
Have you followed the specific “Capacitor Installation” instructions in the readme?

I no longer provide support for Cordova plug-in used in Capacitor.

Use the Capacitor version for Capacitor apps.

**Comment by stib** [comment]
Thank you for clarifying the drop in support.
