### ISSUE TITLE
Not sending data along with the URL

### ISSUE THREAD

**Issue by KhanBalty** [transistorsoft/cordova-background-geolocation-lt#1423]
App is hitting the server, but attaching no data with it.
My Environment
* Plugin version: 4.15.1
* Platform: Android
* OS version: 12
* Device manufacturer / model: Xiaomi
* Cordova version (`cordova -v`): 12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (`cordova platform ls`):  android 12.0.1
* Plugin config provided to `#ready`:
```
 bgGeo.ready({
    reset: true,
    debug: true,
    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    url: 'http://IP/domain/controller/testMethod',
	params: {
    "latitudee": 12.3
  },
   httpTimeout: 30000,
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true
  }, function(state) {    
    console.log('BackgroundGeolocation is configured and ready to use');
    if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
  });
```

## Expected Behavior:
The plugin should send/attach data along with the URL.

## Actual Behavior
The plugin is hitting the server with no data attached with the URL. 

## Steps to Reproduce
1. Create a Cordova project.
2. Install the Plugin.
3. Configure it and define the desired URL.
4. Build the app and test in debug mode.

## Context
 I was trying to track the current location of a test user and send the locations to the server.

## Debug logs
	<summary>In the logs, the URL shows no data attached with it.</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
199.188.1.199 POST /abc.com/Controller/Test - 80 - 195.143.5.22 okhttp/3.12.13 - 200 0 11 12321
199.188.1.199 POST /abc.com/Controller/Test  - 80 - 195.143.5.22 okhttp/3.12.13 - 200 0 11 12321
199.188.1.199 POST /abc.com/Controller/Test  - 80 - 195.143.5.22 okhttp/3.12.13 - 200 0 11 12321
```

</details>

**Comment by KhanBalty** [comment]
Like this, when I tried it with Postman:

 199.188.1.199 POST /abc.com/Controller/Test  param=[12,13] 80 - 192.168.5.171 PostmanRuntime/7.33.0 - 200 0 0 1530

**Comment by christocracy** [comment]
**Where are you expecting the data in the HTTP request?**

**Comment by KhanBalty** [comment]
I'm expecting the plugin to attach the data after the ~/Test, just like it does when I test it with Postman.

199.188.1.199 POST /abc.com/Controller/Test  "Here" - 80 - 195.143.5.22 okhttp/3.12.13 - 200 0 11 12321

**Comment by KhanBalty** [comment]
How do we get that data on server side? I mean how can we catch that data to insert in the DB?
I'm using .NET on server side.

**Comment by christocracy** [comment]
I don't know.  I've never used .NET.  Search the .NET docs "retrieve raw json body of http request"

**Comment by KhanBalty** [comment]
Thank you for the time and help.
