### ISSUE TITLE
API calls to backend server calling pending in the background mode after 5 minutes

### ISSUE THREAD

**Issue by vgirik** [transistorsoft/cordova-background-geolocation-lt#1424]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.watchPosition(
      (location) => {
        console.log("[watchPosition] -", location);
        localStorage.setItem('locations', JSON.stringify(location.coords));
        this.lat = location.coords.latitude;
        this.lan = location.coords.longitude;
        this.saveLocation(this.lat, this.lan);
        if ((localStorage.getItem('StopInterval') === 'false' && localStorage.getItem('StopInterval'))) {
          this.store_getCurrentPosition();
        }
      },
      (errorCode) => {
        console.log('[watchPosition] ERROR -', errorCode);
      },
      {
        interval: 8000, // location capture interval
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        persist: true,
        timeout: 60000,
      }
    );

    // BackgroundGeolocation Plugin configuration
    BackgroundGeolocation.ready(
      {
        reset: true,
        // debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        autoSync: true,
        stopOnTerminate: false,
        distanceFilter: 0,
        locationUpdateInterval: 8000,
        allowIdenticalLocations: false
      },
      (state) => {
        console.log('[ready] BackgroundGeolocation is ready to use');
        if (!state.enabled) {
          BackgroundGeolocation.start();
        }
      }
    );
```

## Expected Behavior
We are using the cordova plug-in , to capture geo location when the app is locked or minimized. 
## Actual Behavior

 the geolocation are posting until 5 min after that every call to backend server is falling under pending , even though server is normally responding. After bring the app to foreground, all the pending calls are submitted and getting response immediately from sever. This issue is only happening in Android, iOS it is working fine.
## Steps to Reproduce
Cordova  - 11.0.0
Android platform  10.1.2
Android API version - 33
Ionic - 6.1.7
cordova-background-geolocation-lt - 4.13.1

</details>

**Comment by christocracy** [comment]
Why are you using .watchPosition?  That method is designed to be used for short periods while your app is in the foreground.  It is not to be used for long periods in the background.

The plug-in does not require you to use that method at all.

See wiki "Philosophy of Operation".

**Comment by christocracy** [comment]
.setConfig is for changing the Config *After* you've called .ready.  .ready accepts the same Config options as .ready.

You must call .ready once, each time your app is launched.

Using .setConfig is optional and only required when you wish to *change* the Config provided to .ready.
