### ISSUE TITLE
[documentation] Missing wiki page "Solving Build Failures" when following a link in the REAME

### ISSUE THREAD

**Issue by sc0ttdav3y** [transistorsoft/cordova-background-geolocation-lt#1425]
## Your Environment

Web browser, viewing [your README at this location](https://github.com/transistorsoft/cordova-background-geolocation-lt#android-gradle-dependency-configuration) on your `master` branch.

## Expected Behavior

Your README has a link to "Solving Build Failures" but it goes to a 404. I'd expect to click the link to view the page.

## Actual Behavior

Clicking the link goes to a 404.

## Steps to Reproduce

1. Visit [your README here](https://github.com/transistorsoft/cordova-background-geolocation-lt#android-gradle-dependency-configuration)
2. Click "Solving Build Failures"

## Context

I've got a build failure and I'm trying to self-help.

## Debug logs

N/A.

**Comment by christocracy** [comment]
If you've got a build failure, why are you not posting the error message?

**Comment by sc0ttdav3y** [comment]
No worries, I worked it out but wanted to let you know about the 404 so you can help others.

FYI my build problem was a crash in `test-build.gradle` on line 123 due to `playServicesLocationVersion` being null. It was `null` because I hadn't specified `GOOGLE_API_VERSION` anywhere.  You might want to test that it's a string before splitting it, and advise the user to set the config var if it's null.

I hunted through code to work out how to fix that. I worked out that I could put it into my Cordova project's `package.json` under `cordova.plugins.cordova-background-geolocation` and set `GOOGLE_API_VERSION` to `21.+`.  

I'm not an Android expert through and this is a dependency of a dependency for me, so that involved a bit of guesswork to work out what value to insert.

I think perhaps the README should explicitly state that `GOOGLE_API_VERSION` needs to be set to something, and mention what the latest version is, for Android-bunnies like myself that doesn't even know what this setting really does. 

Perhaps all that info is in the missing wiki page ;-)

Anyway, the build is working now. Thanks for the quick response.

Cheers, Scott
