### ISSUE TITLE
Distance is not coming as per actual distance travelled.

### ISSUE THREAD

**Issue by vgirik** [transistorsoft/cordova-background-geolocation-lt#1426]
## Your Environment
* Plugin version: 4.15.2
* Platform: iOS or Android : Android
* OS version: 13
* Device manufacturer / model: Vivo 75
* Cordova version (`cordova -v`): 11.0.0
* Cordova platform version (`cordova platform ls`): Android 10.1,2
* Plugin config provided to `#ready`: Ready
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```
 BackgroundGeolocation.watchPosition(
      (location) => {
        console.log("[watchPosition] -", location);
        localStorage.setItem('locations', JSON.stringify(location.coords));
        this.lat = location.coords.latitude;
        this.lan = location.coords.longitude;
        this.odometer = location.odometer
        console.log('odometer',this.odometer)
        this.data = this.data + this.odometer
        console.log('data',this.data)
// localStorage.setItem('odometer',this.data.toString());
        this.saveLocation(this.lat, this.lan);
        // if ((localStorage.getItem('StopInterval') === 'false' && localStorage.getItem('StopInterval'))) {
        //   this.store_getCurrentPosition();
        // }
      },
      (errorCode) => {
        console.log('[watchPosition] ERROR -', errorCode);
      },
      {
        interval: 7000, // location capture interval
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        persist: true,
        timeout: 60000,
      }
    );
 
// BackgroundGeolocation Plugin configuration
    BackgroundGeolocation.ready(
      {
        reset: true,
        // debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        //autoSync: true,
        stopOnTerminate: false,
        allowIdenticalLocations: false,
        persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
      },
      (state) => {
        console.log('[ready] BackgroundGeolocation is ready to use');
        if (!state.enabled) {
          BackgroundGeolocation.start();
        }
      }
    );
  }

## Expected Behavior
Actual KMS : 5 KM
## Actual Behavior
In one trip it came 58 kms
In another trip it came 20 Kms

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Please learn to [Syntax highlight codeblocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks).
