### ISSUE TITLE
Location seems to stop updating.

### ISSUE THREAD

**Issue by delusive** [transistorsoft/cordova-background-geolocation-lt#143]
Hi Chris,

As requested I am posting the issue here.

We notice that after running our app we stop getting the location data. Not sure where or why the app is failing, but it runs for awhile then stops. If there is a way to turn additional logging on to determine the cause let me know. As of right now, it just silently fails.

The plugin version we are using is **1.6.3**. 
We have seen this behaviour on a few devices but the one i have access to is a OnePlus One (Model A0001) running Android 6.0.1.
The config we have for the plug is:
```
config_options = {
  desiredAccuracy: 0,
  stationaryRadius: 20,
  distanceFilter: 50,
  disableElasticity: false,
  locationUpdateInterval: 10000,
  minimumActivityRecognitionConfidence: 80,
  fastestLocationUpdateInterval: 5000,
  activityRecognitionInterval: 20000,
  stopDetectionDelay: 1,
  stopTimeout: 2,
  activityType: 'AutomotiveNavigation',
  debug: false,
  forceReloadOnLocationChange: false,
  forceReloadOnMotionChange: false,
  forceReloadOnGeofence: false,
  stopOnTerminate: false,
  startOnBoot: true,
  url: this.POST_URL,
  method: "POST",
  batchSync: false,
  autoSync: true,
  maxDaysToPersist: 1,
  extras: {
    transmissionId: this.deviceId,
    phone_number: this.phoneNumber,
    device_platform: this.platformName,
    version: this._config.version
  },
  headers: {
    transmissionId: this.deviceId
  }
};
```

**Comment by christocracy** [comment]
Since you're a paying customer, you should be posting issues to the private repo.  This is the free, iOS-only version

https://github.com/transistorsoft/cordova-background-geolocation
