### ISSUE TITLE
Persistent display in iOS dynamic island

### ISSUE THREAD

**Issue by jfm-so** [transistorsoft/cordova-background-geolocation-lt#1430]
## Your Environment
* Plugin version: cordova-background-geolocation-lt 4.15.4
* Platform: iOS
* OS version: 17.1.1
* Device manufacturer / model: Apple
* Cordova version (`cordova -v`): 12.0.0
* Cordova platform version (`cordova platform ls`): ios 7.0.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

    if (localStorage.getItem('geoloc_confirmed') == 'true') {

    var notifPref = localStorage.getItem('notifPref');

    if (notifPref) {
      decodedArray = JSON.parse(notifPref);
      geolocationOn = decodedArray.find(element => element[0] === "geolocation_on")[1];
      if (geolocationOn) {
        var bgGeo = window.BackgroundGeolocation;

        // 2. Execute #ready method:
        bgGeo.ready({
          reset: true,
          //  debug: true,
          //  logLevel: bgGeo.LOG_LEVEL_VERBOSE,
          backgroundPermissionRationale: {
            title: "Allow LAIT911 to access to this device's location when closed or not in use?",
            message:
              "This app collects location data to to notify you of incidents near your location even when the app is closed or not in use.",
            positiveAction: 'Change to {backgroundPermissionOptionLabel}',
            negativeAction: 'Cancel',
          },
          desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
          distanceFilter: 150,
          url: `{geoloc_url}`,
          autoSync: true,
          stopOnTerminate: false,
          startOnBoot: true
        }, function (state) {    // <-- Current state provided to #configure callback
          // 3.  Start tracking
          debug_log('BackgroundGeolocation is configured and ready to use');
          if (!state.enabled) {
            bgGeo.start().then(function () {
              debug_log('- BackgroundGeolocation tracking started');
            });
          }
        });

      BackgroundGeolocation.ready({
        reset: true,  // <-- true to always apply the supplied config
      }, function (state) {
        debug_log('- BackgroundGeolocation is ready: ', state);
      });
    }
  }
```

## Expected Behavior

User prompted to enable location if not enabled. Users location updated in background. User is not notified of these changes. 
## Actual Behavior
iPhone 15 Pro (and newer models with Dynamic Island) display a persistent blue border and icon if location is enabled even when the app is in background.

This is regardless of whether the user has the location privacy settings set to Always or Only when in use. Both have been tried in testing. 

**Settings -> Privacy & Security -> Location Services -> (all the way at the bottom) System Services -> Status Bar Icon**
^ Toggled off

**Privacy -> Location Services -> My App**
^ Set to precise and always

If the user clicks the dynamic island, the app opens. 

The dynamic island is persistent but can sometimes disappear after 5-10 minutes but will return within another few minutes regardless of location changes. 

This has been reproduced on devices only with the dynamic island. Devices without the dynamic island function as expected.

## Steps to Reproduce

1. Download the app on a device that has dynamic island
2. Enable Geolocation functionality within the app

## Context

As with other models, a persistent icon or notification should not be displayed to the user while the app is in the background. 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> a persistent icon or notification should not be displayed to the user while the app is in the background.

Why not?  I expect to see this.

![image](https://github.com/transistorsoft/cordova-background-geolocation-lt/assets/14999/52f00d88-844e-4214-b78b-94db71ab3f5f)

**Comment by jfm-so** [comment]
Is there any solution for a user who doesn't want to see that? Will changing the level of accuracy or distance have an impact?

**Comment by christocracy** [comment]
iOS 16 made changes that require the icon to be shown.

**Comment by jfm-so** [comment]
Is there a way I can subscribe to significant location updates only and have the bar only show when it is updating due to a significant location change?

No need for fleet-level tracking accuracy which I know is closer to the purpose of the plugin, but unfortunately it's the best one that's available for iOS background location updates.

**Comment by BGHDDevelopment** [comment]
> iOS 16 made changes that require the icon to be shown.

I don't see any mention of this in the developer documentation. Could you link it to me?
There is a requirement for the Location Services status icon, but that is not within the dynamic island. [As seen here](https://support.apple.com/en-us/HT207354#:~:text=An%20app%20or%20website%20is,you%E2%80%99re%20using%20requests%20your%20location) That is typically shown as a tiny blue dot or under the control center, even on newer devices with the dynamic island.

The Dynamic Island is mainly cosmetic and typically requires a live activity to be set by the framework or the app.
[Dev Docs](https://developer.apple.com/documentation/widgetkit/dynamicisland)

I am going to do more research later today, but if you could link me to the section in the repo that handles this function I will see what else I can do.

**Comment by christocracy** [comment]
>I don't see any mention of this in the developer documentation

It's not documented.
