### ISSUE TITLE
Odometer remains 0 on one phone (Redmi 9T) out of 500 users

### ISSUE THREAD

**Issue by peterbodo** [transistorsoft/cordova-background-geolocation-lt#1431]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.9.4",
* Platform: Android
* Device manufacturer / model: Redmi 9T
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
    locationAuthorizationRequest: "Always",
    backgroundPermissionRationale: {
        title: "Engedélyezed, hogy a {applicationName} hozzáférjen a helyadatokhoz a háttérben?",
        message:
            "Azért, hogy a háttérben is rögzíthessük az utazásaidat, kérlek engedélyezd a helyadatokat {backgroundPermissionOptionLabel} formában",
        positiveAction: "Váltás {backgroundPermissionOptionLabel}-re",
        negativeAction: "Mégsem",
    },
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 2,
    desiredOdometerAccuracy: 100,
    allowIdenticalLocations: true,
    stopTimeout: 60,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    stopOnTerminate: false,
    startOnBoot: true,
    url: `${BASE_URL}telemetry`,
    batchSync: true,
    maxBatchSize: 200,
    autoSync: false,
    //autoSyncThreshold: 200,
    extras: { session: sessionId, telemetryEvent: "COLLECT" },
    locationTemplate,
    headers: {
        "x-carbontracker-authtoken": accessToken,
        "x-carbontracker-userid": userId,
    },
}
```

## Expected Behavior

Odometer should update. It does for more than 500 users, but remains 0 for just this one user 

## Actual Behavior

Odometer remains 0 for this user

![image](https://github.com/transistorsoft/cordova-background-geolocation-lt/assets/14811093/e8b9b3b4-0692-4bd3-9a74-8ffa6fa095d4)

## Steps to Reproduce

Well, that's the problem. Are there any reason for odometer not updating? While having absolutely correct location with the desired accuracy?
Thanks Chris, in advance.

## Context

Well, this is a production app with more than 500 users in the first test month and I am trying to debug a user's complain.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Sorry I have no access.
```

</details>

Thanks a million!

**Comment by christocracy** [comment]
It's impossible to explain one particular device without detailed logs from the plug-in.  See wiki "Debugging" and learn to fetch logs from the plug-in.

> "^4.9.4",

See the CHANGELOG and update to latest version

**Comment by peterbodo** [comment]
And I just realised I posted for the cordova version instead of react :/

Thanks, I will look into it

**Comment by peterbodo** [comment]
Well, I will check the update possibilities.

Debugging is still not feasible as I meantioned it is a production appand I do not have access to the user's device. Any suggestions?
