### ISSUE TITLE
autosync not merging data after device is back on wifi

### ISSUE THREAD

**Issue by sridhar-rachamshetty** [transistorsoft/cordova-background-geolocation-lt#1434]
## Your Environment
* Plugin version:  4.14.2
* Platform: Android 
* OS version:  13
* Device manufacturer / model: Redmi 12 C Samsung
* Cordova version (`cordova -v`): 11.1.0
* Cordova platform version (`cordova platform ls`): android
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      reset: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      backgroundPermissionRationale: {
        //title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        title: "{applicationName} ",
        message: "collects location data to enable recording of your location tracing during your shift in any site location or patrolling even when closed or not in use.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: this.global.getDistanceFilter(),
      stationaryRadius:this.global.getStationaryRadius(),
      url: this.global.getServerURL() + '/set_live_location',
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true
    }, (state:any) => {
      console.log('%c[ready] BackgroundGeolocation is ready to use','color: green;');
      if (!state.enabled) {
        // 3.  wait till user login in to Start tracking.
        //BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior

Device is online its sending lat lng to server, device is disconnected, moved around for 5 kms and its connected back to wifi after coming back, it should send the saved lat lng in local sql database to server.
## Actual Behavior

Its sending data when connected to wifi / mobile app i.e when its online, once its offiline and comes back on wifi it does not send the saved data in local sql database. 
## Steps to Reproduce

1. Configure ready as given
2. install the app
3. disconnect from wifi / mobile connection
4. travel for 5 kms to generate location data, come back and connect wifi 

## Context

- track security patrol teams who work in night shifts 
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki "Debugging".  Learn to fetch plug-in native logs using .emailLog method.
