### ISSUE TITLE
Build failing with plugin

### ISSUE THREAD

**Issue by anikethhippo** [transistorsoft/cordova-background-geolocation-lt#1436]
Command failed: cordova build android --debug -- --keystore=/home/aniketh/MyProjects/storehippo/storehippo-code/app/servers/mobile_apps/mobileapp/data/storehippo.keystore.p12 --storePassword="manusis123" --alias="release" --password="manusis123" --keystoreType=pkcs12 --packageType=bundle FAILURE: Build completed with 2 failures. 1: Task failed with an exception. ----------- * Where: Script '/tmp/tmp-118607-ZijbAtbX4w8v/techcart/platforms/android/cordova-background-geolocation-lt/techcart-build.gradle' line: 72 * What went wrong: A problem occurred evaluating script. > Cannot get property 'plugins' on null object * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. ============================================================================== 2: Task failed with an exception. ----------- * What went wrong: A problem occurred configuring project ':app'. > compileSdkVersion is not specified. Please add it to build.gradle * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. ============================================================================== * Get more help at https://help.gradle.org BUILD FAILED in 4s Command failed with exit code 1: /tmp/tmp-118607-ZijbAtbX4w8v/techcart/platforms/android/gradlew :app:bundleDebug -b /tmp/tmp-118607-ZijbAtbX4w8v/techcart/platforms/android/build.gradle

getting the following error when i try to build with the plugin

**Comment by christocracy** [comment]
Ignored issue template.
