### ISSUE TITLE
Plugin crashing during app build

### ISSUE THREAD

**Issue by anikethhippo** [transistorsoft/cordova-background-geolocation-lt#1437]
## Your Environment
* Plugin version:4.16.0
* Platform: Android 
* OS version: 5.11.0-49-generic #55-Ubuntu
* Device manufacturer / model:Linux Thinkpad
* Cordova version (`cordova -v`): 11.1.0 
* Cordova platform version (`cordova platform ls`):android 11.0.0
* Plugin config provided to `#ready`:
plugin is added with the command ``` cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git```

## Expected Behavior
App should build after adding the plugin  and running cordova build.

## Actual Behavior
Getting the following error:
 stderr: '\n' +
    'FAILURE: Build completed with 2 failures.\n' +
    '\n' +
    '1: Task failed with an exception.\n' +
    '-----------\n' +
    '* Where:\n' +
    "Script '/tmp/tmp-32166-17oooeEwx2zk/techcart/platforms/android/cordova-background-geolocation-lt/techcart-build.gradle' line: 72\n" +
    '\n' +
    '* What went wrong:\n' +
    'A problem occurred evaluating script.\n' +
    "> Cannot get property 'plugins' on null object\n" +
    '\n' +
    '* Try:\n' +
    '> Run with --stacktrace option to get the stack trace.\n' +
    '> Run with --info or --debug option to get more log output.\n' +
    '> Run with --scan to get full insights.\n' +
    '==============================================================================\n' +
    '\n' +
    '2: Task failed with an exception.\n' +
    '-----------\n' +
    '* What went wrong:\n' +
    "A problem occurred configuring project ':app'.\n" +
    '> compileSdkVersion is not specified. Please add it to build.gradle\n' +
    '\n' +
    '* Try:\n' +
    '> Run with --stacktrace option to get the stack trace.\n' +
    '> Run with --info or --debug option to get more log output.\n' +
    '> Run with --scan to get full insights.\n' +
    '==============================================================================\n' +
    '\n' +
    '* Get more help at https://help.gradle.org\n' +
    '\n' +
    'BUILD FAILED in 4s\n' +
    'Command failed with exit code 1: /tmp/tmp-32166-17oooeEwx2zk/techcart/platforms/android/gradlew :app:bundleDebug -b /tmp/tmp-32166-17oooeEwx2zk/techcart/platforms/android/build.gradle\n'

## Steps to Reproduce
1.Use the configuration mentioned above 
2.run cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git --fetch
3.run cordova build

## Context
I am trying to build the app using the plugin, But crashes with the error mentioned in actual behaviour

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
 '\n' +
    'FAILURE: Build completed with 2 failures.\n' +
    '\n' +
    '1: Task failed with an exception.\n' +
    '-----------\n' +
    '* Where:\n' +
    "Script '/tmp/tmp-32166-17oooeEwx2zk/techcart/platforms/android/cordova-background-geolocation-lt/techcart-build.gradle' line: 72\n" +
    '\n' +
    '* What went wrong:\n' +
    'A problem occurred evaluating script.\n' +
    "> Cannot get property 'plugins' on null object\n" +
    '\n' +
    '* Try:\n' +
    '> Run with --stacktrace option to get the stack trace.\n' +
    '> Run with --info or --debug option to get more log output.\n' +
    '> Run with --scan to get full insights.\n' +
    '==============================================================================\n' +
    '\n' +
    '2: Task failed with an exception.\n' +
    '-----------\n' +
    '* What went wrong:\n' +
    "A problem occurred configuring project ':app'.\n" +
    '> compileSdkVersion is not specified. Please add it to build.gradle\n' +
    '\n' +
    '* Try:\n' +
    '> Run with --stacktrace option to get the stack trace.\n' +
    '> Run with --info or --debug option to get more log output.\n' +
    '> Run with --scan to get full insights.\n' +
    '==============================================================================\n' +
    '\n' +
    '* Get more help at https://help.gradle.org\n' +
    '\n' +
    'BUILD FAILED in 4s\n' +
    'Command failed with exit code 1: /tmp/tmp-32166-17oooeEwx2zk/techcart/platforms/android/gradlew :app:bundleDebug -b /tmp/tmp-32166-17oooeEwx2zk/techcart/platforms/android/build.gradle\n'
```

</details>

**Comment by christocracy** [comment]
show me your `package.json`

**Comment by anikethhippo** [comment]
[tc-package.json](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/14509093/tc-package.json)
Hi @christocracy,
Thank you for responding,
PFA my package.json

**Comment by christocracy** [comment]
That's a package.json.lock

Show me your package.json
