### ISSUE TITLE
Location is not recording while in background mode

### ISSUE THREAD

**Issue by madhavny** [transistorsoft/cordova-background-geolocation-lt#1444]
Plugin version:^4.14.3
Platform: Android
OS version: Android 11 and above
Device manufacturer / model: All
Cordova version (cordova -v): 12.0.0
Cordova platform version (cordova platform ls):
Installed platforms:
android 10.1.0
ios 6.2.0
Available platforms:
browser
electron
Plugin config provided to #ready:
    configureBackgroundGeolocation() {

        BackgroundGeolocation.onHttp(response => {
            console.log("[http] full response: ", response);
            console.log("[http] response: ", response.success, response.status, response.responseText);
        });
        BackgroundGeolocation.onHeartbeat((event) => {
            console.log("[onHeartbeat] ", event);
        });
        BackgroundGeolocation.onLocation(location => {
            console.log('[get OnLocation]', location);
        });
        const headers = {
            'Authorization': 'Bearer ' + this.Authtoken,
            'Content-Type': 'application/json'
        };
        BackgroundGeolocation.ready({
            reset: true,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 100,
            url: this.constant.backgroundLocationUrl,
            headers: headers,
            extras: {
                user_id: this.user_id,
                location_status: this.AuthorizationStatus,
            },

            autoSync: true,
            batchSync: false,
            stopOnTerminate: false,
            startOnBoot: true,
            disableElasticity: true,
            preventSuspend: true,
            heartbeatInterval: 60,
            backgroundPermissionRationale: {
                title: "Allow Advance Laminates to access this device's location all the time ?",
                message: "To show tracked activities on map, Advance Laminates App collects location data even when closed or not in use.",
                positiveAction: "Change to 'Allow all the time'",
                negativeAction: "Cancel"
            }

        }, (state) => {
            console.warn('[ready] BackgroundGeolocation is ready to use', state);
            if (!state.enabled) {
                console.log(!state.enabled, "inside the background geolocation")
                BackgroundGeolocation.start();
            } else {
                console.log('BackgroundGeolocation is running')

            }

        });
    }

## Expected Behavior
Track the GPS Location when app is not in recent apps , it should track location in background

## Actual Behavior
Its Not tracking in background 

## Steps to Reproduce

1.
2.
3.
4.

## Context
App which is running in foreground or background or sleep we have to track the live location even in stationery position.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> debug: false,

See wiki “Debugging”.  Learn how to fetch plug-in logs using .emailLog

**Comment by madhavny** [comment]
Actually I made an app for background location tracking for a company and around 500-800 users are using it so mostly devices were used. Is there anything, so I can get there background location even after location settings were configured in there devices.

**Comment by christocracy** [comment]
Are you reproducing this problem yourself?

**Comment by madhavny** [comment]
No i dont , can you guide me what should i do so i can get location of users in  some interval , because in any how i want there location , as company pay them one behalf of they travelled .

**Comment by christocracy** [comment]
Implement background-fetch, already imported as a dependency.  See its readme.

**Comment by madhavny** [comment]
How can i use cordova-plugin-background-fetch with cordova-background-geolocation-lt ,with my code
