### ISSUE TITLE
Cannot import the plugin in cordova 12.0.0

### ISSUE THREAD

**Issue by ViniciusBenetti** [transistorsoft/cordova-background-geolocation-lt#1448]
Plugin version: from github
Platform: Android
OS version 13.0
Device manufacturer / model: XIAOMI POCO F3
Cordova version (`cordova -v`)  android 12.0.0
Cordova platform version (`cordova platform ls`): 12.0.0

plugin provided for ready:

<platform name="android">
    <preference name="AndroidXEnabled" value="true"/>
    <config-file parent="/manifest" target="app/src/main/AndroidManifest.xml">
      <uses-permission android:minSdkVersion="34" android:name="android.permission.USE_EXACT_ALARM"/>
    </config-file>
</platform>

code:

    var bgGeo = window.BackgroundGeolocation;
    bgGeo.ready({
            allowIdenticalLocations:true

        }, function(state) {    // <-- Current state provided to #configure callback
    // 3.  Start tracking
    console.log('BackgroundGeolocation is configured and ready to use');
    if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started')
      });
    }
    })

Expected Behavior

console.log('BackgroundGeolocation is configured and ready to use');

Actual Behavior
uncaught TypeError: Cannot read properties of undefined(reading'ready')

Steps to Reproduce
1. cordova plugin add "https://github.cpm/transistorsoft/cordova-background-geolocation-lt.git"
2. in config.xml  i put exact alarm and androidX enabled only
3. in <script> tag in index.html i put exactly the specified code
4. run the code in monaca debugger for android specified version

Context
I just wanna use geolocation with screen off on android devices, i tried everything in config.xml  even an old unused functionality
like android.permission.PERSISTENT_ACTIVITY

Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
uncaught TypeError: Cannot read properties of undefined(reading'ready')
```

</details>

**Comment by christocracy** [comment]
Why would you install from GitHub instead of the standard, much simpler way, from npm?

**Comment by christocracy** [comment]
> even an old unused functionality
like android.permission.PERSISTENT_ACTIVITY

I have no idea what that is or why you’d do that.

**Comment by ViniciusBenetti** [comment]
> Why would you install from GitHub instead of the standard, much simpler way, from npm?

cause firstly, i used to add the plugin via interface on monaca. But i just checked the plugin is on my package.json v 4.16.5 i don't know how to import in my project

**Comment by ViniciusBenetti** [comment]
> he plugin is on my package.json v 4.16.5 i don't know how to import in my project

persistent activity is a manifest.permission on android that forces application run in background, but my problem is just the  geolocation in background, not application

**Comment by christocracy** [comment]
> plugin via interface on monaca(add from url

I have no idea what a “monaca” is.  Install from npm

**Comment by ViniciusBenetti** [comment]
> > plugin via interface on monaca(add from url
> 
> I have no idea what a “monaca” is. Install from npm

Ok, i'll try it

**Comment by ViniciusBenetti** [comment]
> > plugin via interface on monaca(add from url
> 
> I have no idea what a “monaca” is. Install from npm

i did it and the error stills the same

**Comment by christocracy** [comment]
I idea.
