### ISSUE TITLE
Location not tracking

### ISSUE THREAD

**Issue by Rajam0310** [transistorsoft/cordova-background-geolocation-lt#1449]
## Your Environment
* Plugin version:7.2.0
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):12.0.0
* Cordova platform version (`cordova platform ls`):android 10.1.2  ios 6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
async backgroundgps2()
  {
    // In configureBackgroundGeolocation() method
BackgroundGeolocation.ready({
  reset: true,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  stopOnTerminate: false,
  startOnBoot: true,
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  foregroundService: true, // Enable foreground service
  notification: {
    title: 'Background tracking',
    text: 'Your location is being tracked in the background',
    channelName: 'Background Geolocation',
    priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH
  }
}, (state) => {
  console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
  this.sendgps();
  if (!state.enabled) {
    BackgroundGeolocation.start(() => {
      console.log("- Start success");
      this.sendgps();
    });
  }
});
  }


  async bgfetch()
{let status = await BackgroundFetch.configure({
  minimumFetchInterval: 1
}, (taskId) => {  // <-- Event callback.
  console.log("[BackgroundFetch] taskId: ", taskId);
  this.backgroundgps2();
  // Finish, providing received taskId.
  BackgroundFetch.finish(taskId);
}, (taskId) => {  // <-- Task timeout callback.
  // This task has exceeded its allowed running-time.
  // You must stop what you're doing and immediately .finish(taskId)
  console.log('[BackgroundFetch] TIMEOUT taskId: ', taskId);
  BackgroundFetch.finish(taskId);
});
}
```
## Expected Behavior
1.We need to track the user location when the app is running in foreground or background.
2.update the location when the device is on or lock or sleep.
## Actual Behavior
1.Location is tracked only when the app is running in foreground.
2.once the device is locked and app is running in the background location is not tracked after 5minutes.
## Steps to Reproduce

1.
2.
3.
4.
## Debug logs

<details>
<summary>Logs</summary>
```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
</details>

**Comment by christocracy** [comment]
>Plugin version:7.2.0

There [no such version](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#changelog) as `7.2.0`.

>Platform: iOS or Android
>OS version:
>Device manufacturer / model:

You did not provide all the required information.

>2.once the device is locked and app is running in the background location is not tracked after 5minutes.

Do you know that you need to move at least 200 meters beyond the last known location before tracking engages?

See Wiki ["Debugging"](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging) and ["Philosophy of Operation"](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

**Comment by Rajam0310** [comment]
Platform: iOS or Android(Both)

Device manufacturer / model:All Device
plugin version : 4.10.0
we tested above 200mters also but did not captured location after 5minutes when device went sleep

**Comment by christocracy** [comment]
Duplicate #1450 

Why are you posting multiple issues about the same thing?!

**Comment by christocracy** [comment]
Oops, my bad.  That wasn't you.

**Comment by christocracy** [comment]
Or is it?  Are you and @kmanikandan8122 on the same team?

**Comment by christocracy** [comment]
Duplicate #1450
