### ISSUE TITLE
SampleApp doesn't trigger onGeoFence

### ISSUE THREAD

**Issue by luposlip** [transistorsoft/cordova-background-geolocation-lt#145]
Hi there!

Seems like great work you're doing here.

I'm considering migrating from https://github.com/mauron85/cordova-plugin-background-geolocation to your premium plugin for an app I'm working on requiring region monitoring even when app is killed.

1. This is one of the use cases where my life will be easier with your plugin, right?
2. I tried your SampleApp (downloaded from Google Play). I created a geofence, enabled background location and killed the app. I walked the couple of hundred meters into the geofence, but nothing happened. If this doesn't work I won't pay a premium for your plugin - can you please explain me how to demo this?

Thanks!

Best,
Henrik

**Comment by christocracy** [comment]
Mauron85's a fork of my original open-source project.  He likes to copy
what I do.  If you want the original and best, this is it.

1. Yes
2. I have no problem at all with Android geofences triggering.  If you
killed the app, did you first enable stopOnTerminate: true?  You can build
the SampleApp for Android.  The npm version contains a fairly recent
version of Android.  The SampleApp contains a key to unlock it.

On Tue, Jul 5, 2016 at 5:35 AM, Henrik Mohr <notifications@github.com>
wrote:

> Hi there!
>
> Seems like great work you're doing here.
>
> I'm considering migrating from
> https://github.com/mauron85/cordova-plugin-background-geolocation to your
> premium plugin for an app I'm working on requiring region monitoring even
> when app is killed.
>
>    1. This is one of the use cases where my life will be easier with your
>    plugin, right?
>    2. I tried your SampleApp (downloaded from Google Play). I created a
>    geofence, enabled background location and killed the app. I walked the
>    couple of hundred meters into the geofence, but nothing happened. If this
>    doesn't work I won't pay a premium for your plugin - can you please explain
>    me how to demo this?
>
> Thanks!
>
> Best,
> Henrik
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/145>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l0cBtLF_-ddNCbVAbSEyb-6HvfRvks5qSiVpgaJpZM4JE8Bz>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by luposlip** [comment]
I know (about mauron85's fork) ;)

1. alright, check.
2. Yes, the stopOnTerminate is set to true. But nothing happened on my phone, before I actually opened/started the app again?

Best,
Henrik

**Comment by christocracy** [comment]
You should hear sound "boop-boop-boop" when Geofence fires.  The version on
Google Play hasn't been updated since November.

Try building the SampleApp for Android with npm version.

On Tue, Jul 5, 2016 at 8:48 AM, Henrik Mohr <notifications@github.com>
wrote:

> I know (about mauron85's fork) ;)
>
>    1. alright, check.
>    2. Yes, the stopOnTerminate is set to true. But nothing happened on my
>    phone, before I actually opened/started the app again?
>
> Best,
> Henrik
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/145#issuecomment-230468477>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l_LcUws10fSdQXxaZGexAAsD407Vks5qSlKTgaJpZM4JE8Bz>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by luposlip** [comment]
OK, I'll try that. Getting back to you when I know how it went.

**Comment by luposlip** [comment]
I guess I can build it directly from github, when installing on iOS, right?
https://github.com/transistorsoft/cordova-background-geolocation-SampleApp

**Comment by luposlip** [comment]
I've tried to build and run it on iOS. It still doesn't seem to work for me.

1. Should the BgLocation switch be turned on or off?
2. Better yet, could you send me a sample of all properties as they should be set to test the region monitoring/geoFence entry/exit for a killed app?

Thanks.

**Comment by luposlip** [comment]
Hi @christocracy 
Tested the iOS app again today. It actually works fine.
If you say the Android version works in the same way - and just as good - I'll buy it :)

Best,
Henrik

**Comment by christocracy** [comment]
Android works better in some ways.

On Wednesday, July 6, 2016, Henrik Mohr <notifications@github.com> wrote:

> Hi @christocracy <https://github.com/christocracy>
> Tested the iOS app again today. It actually works fine.
> If you say the Android version works in the same way - and just as good -
> I'll buy it :)
>
> Best,
> Henrik
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/145#issuecomment-230741014>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lyJevXRowch4FwvoXxJsJ0sGWUQNks5qS4mygaJpZM4JE8Bz>
> .
>


-- 
Snet form Gmail Mobile

**Comment by luposlip** [comment]
Cool. Closing. Can you disclose in which ways it works better (or direct me to some docs explaining it)?
