### ISSUE TITLE
Hear Beat Interval Follows Random Interval

### ISSUE THREAD

**Issue by kmanikandan8122** [transistorsoft/cordova-background-geolocation-lt#1451]
## Your Environment
* Plugin version:4.16.5
* Platform: :Android
* OS version:Android 14
* Device manufacturer / model:Vivo
* Cordova version (`cordova -v`):12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (`cordova platform ls`):
* Installed platforms:
  android 10.1.2
  ios 6.3.0
Available platforms:
  browser
  electron
* Plugin config provided to `#ready`:
 BackgroundGeolocation.ready({
      distanceFilter: 0,
      stopOnTerminate: false,
heartbeatInterval:60,
     // triggerActivities:"in_vehicle,on_foot, walking, running",

      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      debug: true
    }

## Expected Behavior
Heart beat event expected to trigger 60 seconds interval

## Actual Behavior
Heart beat event triggers random interval even i specified as 60 seconds,any thing i need to add in configuration?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Due to historical abuse of Android APIs (as evidenced by https://dontkillmyapp.com), Android is “turning the screws” on certain APIs.
