### ISSUE TITLE
Failed to build targeting android 34 with new release android 13 of cordova

### ISSUE THREAD

**Issue by ParisMichael** [transistorsoft/cordova-background-geolocation-lt#1454]
## Your Environment
* Plugin version: cordova-background-geolocation-lt 4.16.5
* Platform: Android
* OS version: Windows 10
* Device manufacturer / model: 
* Cordova version (`cordova -v`): 12.0.0
* Cordova platform version (`cordova platform ls`): android 13.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

Build should complete

## Actual Behavior

> Task :app:processDebugMainManifest FAILED
C:\Users\paris\workspace\daybookpro\platforms\android\app\src\main\AndroidManifest.xml:21:18-58 Error:
        Attribute service#com.transistorsoft.locationmanager.service.LocationRequestService@foregroundServiceType value=(location) from AndroidManifest.xml:21:18-58
        is also present at [com.transistorsoft:tslocationmanager:3.5.4] AndroidManifest.xml:57:13-87 value=(@integer/foregroundServiceTypeShortService).
        Suggestion: add 'tools:replace="android:foregroundServiceType"' to <service> element at AndroidManifest.xml:21:9-142 to override.

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute service#com.transistorsoft.locationmanager.service.LocationRequestService@foregroundServiceType value=(location) from AndroidManifest.xml:21:18-58
        is also present at [com.transistorsoft:tslocationmanager:3.5.4] AndroidManifest.xml:57:13-87 value=(@integer/foregroundServiceTypeShortService).
        Suggestion: add 'tools:replace="android:foregroundServiceType"' to <service> element at AndroidManifest.xml:21:9-142 to override.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Post your Config.xml

**Comment by ParisMichael** [comment]
<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="301680" id="uk.co.daybookpro.mobile" version="3.0.168" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>DayBookPro Mobile Companion</name>
    <description>
        The DayBookPro mobile companion for proof of delivery, tracking and driver support.
    </description>
    <icon src="res/icon/daybookpro.png" />
    <author email="paris.marinakis@daybookpro.co.uk" href="www.daybookpro.co.uk">
        Paris Marinakis
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
	
    <platform name="android">
        <allow-intent href="market:*" />
		<preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/screen/android/daybookpro.9.png" />
		<preference name="AndroidWindowSplashScreenBackground" value="#000000" />
		<preference name="AndroidXEnabled" value="true" />  
        <preference name="android-minSdkVersion" value="24" />
        <preference name="android-targetSdkVersion" value="34" />
		<preference name="AndroidInsecureFileModeEnabled" value="true" />
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="res/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
		
		<config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
		  <meta-data
			android:name="com.transistorsoft.locationmanager.license_key"
			android:value="35d21a5f7bcc979940641d07dceb989e1aa4abf11379c3682006a9b256c0a869" />
			<service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />
			<service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />
		</config-file>
		
		 <resource-file 
			 src="res/headless/android/BackgroundGeolocationHeadlessTask.java" 
			 target="app/src/main/java/com/transistorsoft/cordova/bggeo/BackgroundGeolocationHeadlessTask.java" />
		 
		
	 </platform>
	<platform name="ios">
		<splash src="res/screen/ios/daybookpro.9.png" />
		<allow-intent href="itms:*" />
		<allow-intent href="itms-apps:*" />
    
    <config-file parent="NSLocationAlwaysAndWhenInUseUsageDescription" target="*-Info.plist">
        <string>It is essential to collect location data not only when the app is in foreground but also during phone calls, when using navigation apps, capturing signatures and even in the case the app is accidentally closed. This way headquarters can update shippers and airlines with ETA and can provide help in case of an incident even when the app is closed or in the background. To stop the location service before exiting the app please press 'Stop location tracking after exiting the app' under Device Settings.</string>
    </config-file>
    <config-file parent="NSLocationAlwaysUsageDescription" target="*-Info.plist">
        <string>It is essential to collect location data not only when the app is in foreground but also during phone calls, when using navigation apps, capturing signatures and even in the case the app is accidentally closed. This way headquarters can update shippers and airlines with ETA and can provide help in case of an incident even when the app is closed or in the background. To stop the location service before exiting the app please press 'Stop location tracking after exiting the app' under Device Settings.</string>
    </config-file>
    <config-file parent="NSLocationWhenInUseUsageDescription" target="*-Info.plist">
        <string>It is essential to collect location data not only when the app is in foreground but also during phone calls, when using navigation apps, capturing signatures and even in the case the app is accidentally closed. This way headquarters can update shippers and airlines with ETA and can provide help in case of an incident even when the app is closed or in the background. To stop the location service before exiting the app please press 'Stop location tracking after exiting the app' under Device Settings.</string>
    </config-file>
    <config-file parent="NSMotionUsageDescription" target="*-Info.plist">
        <string>It is essential to collect motion data to enhance battery life when recording location changes. When a location has been recorded as long as the device does not move we can put the location services and GPS search to sleep' under Device Settings.</string>
    </config-file>
    

	</platform>
</widget>

**Comment by ParisMichael** [comment]
[config.xml.txt](https://github.com/user-attachments/files/16398999/config.xml.txt)

**Comment by christocracy** [comment]
See the CHANGELOG from over a year ago where you were instructed to remove these elements from your Config.xml

https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#4141--2023-08-24

**Comment by ParisMichael** [comment]
Thanks a million !

All seems to be working now
