### ISSUE TITLE
LICENSE VALIDATION FAILURE Invalid license key

### ISSUE THREAD

**Issue by billelHachemi** [transistorsoft/cordova-background-geolocation-lt#1457]
I have followed the installation instructions on this repo and purshased the license key and my support is updated but i have error in production LICENSE VALIDATION FAILURE Invalid license key

**Comment by christocracy** [comment]
Licensing issues are handled by email.

see https://www.transistorsoft.com
Email your Order # and config.xml

**Comment by billelHachemi** [comment]
Im using flutter  , i sent message on your website chat and i receive this eemail : 'Tech support is handled by posting an issue at the GitHub repo.  See wiki “Debugging” too.'

**Comment by christocracy** [comment]
> 'Tech support is handled by posting an issue at the GitHub repo. See wiki “Debugging” too.'

You didn’t explain anything about your problem in that email.

also, you’re not even posting at the right repo.  This is the **Cordova** version’s repo, not Flutter.

there are 4 different versions of this plug-in.
1.  Cordova
2. Capacitor
3. React Native
4. Flutter

email your Order #, AndroidManifest, build.gradle and app/build.gradle

**Comment by billelHachemi** [comment]
okay i will send them to this email :  info@transistorsoft.com right ?

**Comment by billelHachemi** [comment]
done
