### ISSUE TITLE
How to get param or extra data in headless events

### ISSUE THREAD

**Issue by codingwithashu** [transistorsoft/cordova-background-geolocation-lt#1458]
I want to get userid for identifying which user have started tracking ?

**Comment by codingwithashu** [comment]
yes

`package com.transistorsoft.cordova.bggeo;

import org.apache.cordova.CordovaPlugin;
import org.greenrobot.eventbus.Subscribe;
import org.greenrobot.eventbus.ThreadMode;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;

import com.transistorsoft.locationmanager.adapter.BackgroundGeolocation;
import com.transistorsoft.locationmanager.adapter.TSConfig;
import com.transistorsoft.locationmanager.adapter.callback.TSLocationCallback;
import com.transistorsoft.locationmanager.event.ActivityChangeEvent;
import com.transistorsoft.locationmanager.event.ConnectivityChangeEvent;
import com.transistorsoft.locationmanager.event.GeofenceEvent;
import com.transistorsoft.locationmanager.event.HeadlessEvent;
import com.transistorsoft.locationmanager.event.HeartbeatEvent;
import com.transistorsoft.locationmanager.event.MotionChangeEvent;
import com.transistorsoft.locationmanager.event.LocationProviderChangeEvent;
import com.transistorsoft.locationmanager.http.HttpResponse;
import com.transistorsoft.locationmanager.location.TSLocation;
import com.transistorsoft.locationmanager.logger.TSLog;
import com.transistorsoft.locationmanager.http.HttpService;

/**
 * BackgroundGeolocationHeadlessTask
 * This component allows you to receive events from the BackgroundGeolocation plugin in the native Android environment while your app has been *terminated*,
 * where the plugin is configured for stopOnTerminate: false.  In this context, only the plugin's service is running.  This component will receive all the same
 * events you'd listen to in the Javascript API.
 *
 * You might use this component to:
 * - fetch / post information to your server (eg: request new API key)
 * - execute BackgroundGeolocation API methods (eg: #getCurrentPosition, #setConfig, #addGeofence, #stop, etc -- you can execute ANY method of the Javascript API)
 */

public class BackgroundGeolocationHeadlessTask {

    @Subscribe(threadMode=ThreadMode.MAIN)
    public void onHeadlessTask(HeadlessEvent event) throws JSONException {
        String name = event.getName();
        TSLog.logger.debug("\uD83D\uDC80  event: " + event.getName());
        TSLog.logger.debug("- event: " + event.getEvent());
        JSONObject jsonData = new JSONObject();
        Object objEvent = event.getEvent();

        try {
            jsonData.put("name", name);
            jsonData.put("Event", objEvent.toString());

            if (BackgroundGeolocation.EVENT_TERMINATE.equals(name)) {
                JSONObject state = event.getTerminateEvent();
                jsonData.put("state", state);
            } else if (BackgroundGeolocation.EVENT_LOCATION.equals(name)) {
                TSLocation location = event.getLocationEvent();
                jsonData.put("state", location.json);
            } else if (BackgroundGeolocation.EVENT_MOTIONCHANGE.equals(name)) {
                MotionChangeEvent motionChangeEvent = event.getMotionChangeEvent();
                TSLocation location = motionChangeEvent.getLocation();
                jsonData.put("state", location);
            } else if (BackgroundGeolocation.EVENT_HTTP.equals(name)) {
                HttpResponse response = event.getHttpEvent();
                jsonData.put("state", response.responseText);  // Convert response to string or desired format
            } else if (BackgroundGeolocation.EVENT_PROVIDERCHANGE.equals(name)) {
                LocationProviderChangeEvent providerChange = event.getProviderChangeEvent();
                jsonData.put("state", providerChange.getStatus());  // Convert providerChange to string or desired format
            } else if (BackgroundGeolocation.EVENT_ACTIVITYCHANGE.equals(name)) {
                ActivityChangeEvent activityChange = event.getActivityChangeEvent();
                jsonData.put("state", activityChange.getActivityName());  // Convert activityChange to string or desired format
            } else if (BackgroundGeolocation.EVENT_SCHEDULE.equals(name)) {
                JSONObject state = event.getScheduleEvent();
                jsonData.put("state", state);
            } else if (BackgroundGeolocation.EVENT_BOOT.equals(name)) {
                JSONObject state = event.getBootEvent();
                jsonData.put("state", state);
            } else if (BackgroundGeolocation.EVENT_GEOFENCE.equals(name)) {
                GeofenceEvent geofenceEvent = event.getGeofenceEvent();
                jsonData.put("state", geofenceEvent.toString());  // Convert geofenceEvent to string or desired format
            } else if (BackgroundGeolocation.EVENT_HEARTBEAT.equals(name)) {
                HeartbeatEvent heartbeatEvent = event.getHeartbeatEvent();
                jsonData.put("state", heartbeatEvent.toString());  // Convert heartbeatEvent to string or desired format
            } else if (BackgroundGeolocation.EVENT_ENABLEDCHANGE.equals(name)) {
                boolean enabled = event.getEnabledChangeEvent();
                //jsonData.put("state", enabled);
            } else if (BackgroundGeolocation.EVENT_CONNECTIVITYCHANGE.equals(name)) {
                ConnectivityChangeEvent connectivityChangeEvent = event.getConnectivityChangeEvent();
                jsonData.put("state", connectivityChangeEvent.hasConnection());  // Convert connectivityChangeEvent to string or desired format
            } else if (BackgroundGeolocation.EVENT_POWERSAVECHANGE.equals(name)) {
                boolean powerSaveEnabled = event.getPowerSaveChangeEvent().isPowerSaveMode();
                jsonData.put("state", powerSaveEnabled);
            }
             else {
                TSLog.logger.warn("Unknown Headless Event: " + name);
            }
            //jsonData.put("DEFAULT_URL", tsLocation.toJson());

        } catch (Exception e) {
            TSLog.logger.error("Failed to create JSON data: " + e.getMessage());
            jsonData.put("Failed", e.getMessage());
        }
        postToApi(jsonData); // Assuming postToApi needs JSON string representation
    }



    private void postToApi(JSONObject jsonData) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {

                    URL url = new URL("https://webhook.site/1275ff7d-e6eb-4a64-836a-1acbc72d9545");
                    HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                    conn.setRequestMethod("POST");
                    conn.setRequestProperty("Content-Type", "application/json; utf-8");
                    conn.setRequestProperty("Accept", "application/json");
                    conn.setDoOutput(true);

                    try (OutputStream os = conn.getOutputStream()) {
                        byte[] input = jsonData.toString().getBytes("utf-8");
                        os.write(input, 0, input.length);
                    }

                    int responseCode = conn.getResponseCode();
                    TSLog.logger.debug("POST Response Code :: " + responseCode);

                    if (responseCode == HttpURLConnection.HTTP_OK) { // success
                        try (BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
                            String inputLine;
                            StringBuilder response = new StringBuilder();

                            while ((inputLine = in.readLine()) != null) {
                                response.append(inputLine);
                            }

                            // Print result
                            TSLog.logger.debug("POST Response: " + response.toString());
                        }
                    } else {
                        TSLog.logger.warn("POST request not worked");
                    }
                } catch (Exception e) {
                    TSLog.logger.error("Failed to POST data: " + e.getMessage());
                }
            }
        }).start();
    }
}`

**Comment by christocracy** [comment]
Please learn how to syntax highlight code-blocks:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by codingwithashu** [comment]
coment updated

**Comment by christocracy** [comment]
```java
// Get reference to TSConfig object which contains getter-methods for each BackgroundGeolocation Config option.
TSConfig config = TSConfig.getInstance(event.getContext());

String url = config.getUrl();
JSONObject params = config.getParams();
JSONObject extras = config.getExtras();
```

**Comment by codingwithashu** [comment]
thanks 👍

**Comment by christocracy** [comment]
BTW, the plugin already imports [OkHttp](https://square.github.io/okhttp/#post-to-a-server), which is a far superior way of doing HTTP than `java.net.HttpURLConnection`.

The OKHttp symbols should already be available for you to use.

**Comment by codingwithashu** [comment]
```
private void postToApi(JSONObject jsonData) {
        OkHttpClient client = new OkHttpClient();

        MediaType JSON = MediaType.get("application/json; charset=utf-8");
        RequestBody body = RequestBody.create(JSON, jsonData.toString());
        Request request = new Request.Builder()
                .url("https://webhook.site/1234456-f27f-4fc9-841b-512dcae92494")
                .post(body)
                .build();

        new Thread(() -> {
            try (Response response = client.newCall(request).execute()) {
                int responseCode = response.code();
                TSLog.logger.debug("POST Response Code :: " + responseCode);

                if (response.isSuccessful()) {
                    String responseData = response.body().string();
                    TSLog.logger.debug("POST Response: " + responseData);
                } else {
                    TSLog.logger.warn("POST request not worked");
                }
            } catch (Exception e) {
                TSLog.logger.error("Failed to POST data: " + e.getMessage());
            }
        }).start();
    }
