### ISSUE TITLE
Marcaciones saltadas o sin registro

### ISSUE THREAD

**Issue by ydarwin** [transistorsoft/cordova-background-geolocation-lt#1459]
## Your Environment
* Plugin version: Latest
* Platform: Android
* OS version: 12
* Device manufacturer / model: Any
* Cordova version (`cordova -v`): 12
* Cordova platform version (`cordova platform ls`): android
* Plugin config provided to `#ready`: 
bgGeo.ready({
        notification: {
            channelName: APP_TITLE,
            title: APP_TITLE,
            text: 'Tracking activo'
        },        
        debug: false,
        logLevel: bgGeo.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        url: APP_PATH_SET_LOCATION,
        autoSync: true,
        autoSyncThreshold: 5,
        batchSync: true,
        maxBatchSize: 50,
        stopOnTerminate: true,
        startOnBoot: false,
        params: {
            user_id: userData.id,
            client_id: userData.client,
            token: app_userData.get('token'),
            group_id: APP_LOCATION_GROUP
        },
        locationsOrderDirection: 'DESC',
        maxDaysToPersist: 10
    }

```javascript <!-- syntax-highlighting:  paste your code below -->
La informacion la envia el plugin al servidor para guardar la ubicacion segun $config arriba especificada
```

## Expected Behavior

Tengo un reporte donde veo el mapa y debe estar marcando cada 10 metros, pero no se esta realizando, hay lugar que se salta mas de 1 KM y luego vuleve a marcar normal.

## Actual Behavior

En el reporte de la app hay distancias que no marcan o no registran la ubicacion, o sea ubicaciones saltadas.

## Steps to Reproduce

No se va a poder reproducir, adjunto capturas de pantalla del problema.

## Context

Quiero que la app registre cada 10 metros la ubicacion

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Sin logs
![Captura](https://github.com/user-attachments/assets/7481991e-d656-4e11-9e6e-58f8066c9381)

```

</details>

**Comment by christocracy** [comment]
Please translate to English.

**Comment by christocracy** [comment]
> Plugin version: Latest

entire the *exact* version used.

>Device manufacturer / model: Any

Enter the *exact* device and model tested on.
