### ISSUE TITLE
Question: overwrite NSLocationAlwaysUsageDescription?

### ISSUE THREAD

**Issue by luposlip** [transistorsoft/cordova-background-geolocation-lt#146]
Hi @christocracy,

Is it possible to overwrite the default `NSLocationAlwaysUsageDescription` in some way, preferably in code (JavaScript), alternatively from `config.xml`?

This is the text I'm referring to, from `plugin.xml`:
```
<config-file target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
            <string>TSLocationManager requires background location tracking</string>
 </config-file>
```

Best,
Henrik

**Comment by christocracy** [comment]
If I could have made this easier already, I would have.

Google "Cordova plist manager"

On Wednesday, July 6, 2016, Henrik Mohr <notifications@github.com> wrote:

> Hi @christocracy <https://github.com/christocracy>,
>
> Is it possible to overwrite the default NSLocationAlwaysUsageDescription
> in some way, preferably in code (JavaScript), alternatively from
> config.xml?
>
> This is the text I'm referring to, from plugin.xml:
>
> <config-file target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
>             <string>TSLocationManager requires background location tracking</string>
>  </config-file>
>
> Best,
> Henrik
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/146>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lyCqRCjgV2V6m_eqLaw9ewoo8AKIks5qS5A2gaJpZM4JF_Hw>
> .
>


-- 
Snet form Gmail Mobile

**Comment by luposlip** [comment]
Alrightythen. Closing.
