### ISSUE TITLE
watchPosition has old age on iOS (up to 60 seconds). is_moving=false while driving?

### ISSUE THREAD

**Issue by caleb87** [transistorsoft/cordova-background-geolocation-lt#1460]
## Your Environment
* Plugin version: 4.17.0
* Platform: iOS
* OS version: 17.6
* Device manufacturer / model: (Multiple iPhones, iPhone XS MAX, iPhone 13, others)
* Cordova version (`cordova -v`): 12
* Cordova platform version (`cordova platform ls`): 7.1.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.watchPosition(function(location) {
	diagnosticValues.location = location;
	gps.setGpsAlt(location);
}, function(err) {
	console.log(err);
}, {
	interval: 1000
});

## OUTPUT:

location":{
        "uuid":"D57BB2CD-02D7-45D0-A326-59FE04380617",
        "odometer":0,
        "extras":{
        },
        "age":59469,
        "timestamp":"2024-09-08T16:50:57.357Z",
        "battery":{
            "level":0.8500000238418579,
            "is_charging":false
        },
        "coords":{
            "speed_accuracy":0.2,
            "speed":29.89,
            "longitude":-103.07507325,
            "ellipsoidal_altitude":0,
            "floor":null,
            "heading_accuracy":1,
            "latitude":47.9768486,
            "accuracy":5,
            "altitude_accuracy":9.5,
            "altitude":651.7,
            "heading":59.6
        },
        "is_moving":false,
        "activity":{
            "type":"unknown",
            "confidence":100
        }
    }

```

## Expected Behavior
Coordinate updates every 1 second with max age of under 1 second.

## Actual Behavior
The GPS will return the same coordinate with age up to 1 minute. 

## Steps to Reproduce
1. this has been reported by multiple users, but I'm unable to reproduced it.

## Context
This code is used for navigation. It works for most people and my own test devices, but for some users, the GPS keeps providing the same coordinates. The users are saying the app is in the foreground while it happens, and they have also tried to set the location permission to Always. 

The location output says **is_moving=false**, but it even returned a speed of 29.89 in the coords. 

Could it because the activity type is "**unknown**"? The location result shows activity as "type": [still|on_foot|walking|running|in_vehicle|on_bicycle], however, their location keeps showing {\"type\":\"unknown\",\"confidence\":100} 

Is my best option to set **changePace(true)** ? I haven't tested this, as it requires a published update to the app store. 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Why are you using .watchPosition?  That method is not designed for use in the background.  It’s to be used only for short periods of time while your app is in the foreground.

are you not telling the plug-in to .start()?

**Comment by caleb87** [comment]
The plugin .starts() with the .read() callback. 

One of the users called me and explained more, and I think the app is open, but set to background due to him playing pandora or taking phone calls. He has the location permission set to Always.

I'm using watchPosition, so that's clearly the issue. What is the correct way to pull coordinates in background?

Do I do startBackgroundTask, and then use getCurrentPosition?

**Comment by christocracy** [comment]
>I'm using watchPosition, so that's clearly the issue. What is the correct way to pull coordinates in background?

Just call `.start()`.  The plugin **automatically** records location when the device is detected to be moving.  Read the Wiki ["Philosophy of Operation"](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

>Do I do startBackgroundTask, and then use getCurrentPosition?

**NO**.  You only need to call `.start()` -- that's **ALL** you need to do.  nothing else.

**Comment by christocracy** [comment]
And if you want to manually engage location-tracking, you call .changePace(true) (after calling .start()).

read the wiki [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

**Comment by christocracy** [comment]
> I am wondering what is the purpose of watchPosition 

For short-periods of time in the foreground.  Updating the current location "blue dot" marker on a map, for example.

>and getCurrentPosition?

For retrieving a location at any time you wish.

>One thing that was happening was motionchange event was going into onLocation callback, so I had to check for it and ignore it. Is this normal?

Yes.  Every single location recorded by the location is fired to the `.onLocation` event.
