### ISSUE TITLE
java.lang.IllegalStateException from com.transistorsoft.locationmanager.logger

### ISSUE THREAD

**Issue by JohnCastle4** [transistorsoft/cordova-background-geolocation-lt#1461]
## Your Environment
* Plugin version: 4.16.4
* Platform: Android
* OS version: 14
* Device manufacturer / model: samsung b0s (Galaxy S22 Ultra) (as reported by Google Play Store)
* Cordova version (`cordova -v`):  "cordova": "^11.1.0",
* Cordova platform version (`cordova platform ls`): "cordova-android": "^13.0.0",
* Plugin config provided to `#ready`:
Following exception reported as a crash on Google Play Store, I don't have enough context to attempt replication, seems to work fine on our owned devices:

## Expected Behavior
Plugin doesn't crash.
Apologies if this is already known and fixed, I could not see an existing issue covering this crash report.

## Actual Behavior
Google Play Store reporting a crash.

## Steps to Reproduce
Unclear how this exception is generated.

## Context
N/A

## Debug logs
I only have the crash log in Google Play Store currently.

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Exception java.lang.IllegalStateException:
  at android.database.sqlite.SQLiteClosable.acquireReference (SQLiteClosable.java:58)
  at android.database.sqlite.SQLiteDatabase.executeSql (SQLiteDatabase.java:2635)
  at android.database.sqlite.SQLiteDatabase.execSQL (SQLiteDatabase.java:2574)
  at com.transistorsoft.locationmanager.logger.TSSQLiteAppender.a
  at com.transistorsoft.locationmanager.logger.TSSQLiteAppender.start
  at com.transistorsoft.locationmanager.logger.TSLog.a
  at com.transistorsoft.locationmanager.logger.TSLog.$r8$lambda$XkIkRZm15zAYrbHnB-eoy9IAVL0
  at com.transistorsoft.locationmanager.logger.TSLog$$ExternalSyntheticLambda0.run (D8$$SyntheticClass)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)
```

</details>

**Comment by christocracy** [comment]
How often have you seen this?

**Comment by JohnCastle4** [comment]
Sorry for the delay responding.

It's rare, 2 events in total so far. We have over 1.6k installs and it's used pretty extensively in the field, although not all of our customers turn on background location tracking:
Devices:
motorola ocean
samsung b0s

Android version:
Android 10 (SDK 29)
Android 14 (SDK 34)

Same call stack both times.
