### ISSUE TITLE
I hope this message finds you well. I am currently facing issues with the geofence functionality in my project, and I would appreciate your assistance.

### ISSUE THREAD

**Issue by yunhoa** [transistorsoft/cordova-background-geolocation-lt#1463]
I hope this message finds you well. I am currently facing issues with the geofence functionality in my project, and I would appreciate your assistance.

Logs
Here are some logs from my application:

[INFO:CONSOLE(126)] "### Updating location: {"latitude":37.4769265,"longitude":126.8798495,"accuracy":100,"speed":-1,"speed_accuracy":-1,"heading":-1,"heading_accuracy":-1,"altitude":76.9,"ellipsoidal_altitude":76.9,"altitude_accuracy":100,"age":187419}"
[INFO:CONSOLE(130)] "### Current location is outside the geofence. (Latitude: 37.4769265, Longitude: 126.8798495)"
[INFO:CONSOLE(141)] "### Location has been updated."
[INFO:CONSOLE(126)] "### Updating location: {"latitude":37.4769439,"longitude":126.8798543,"accuracy":15.08,"speed":-1,"speed_accuracy":1.5,"heading":-1,"heading_accuracy":45,"altitude":76.9,"ellipsoidal_altitude":76.9,"altitude_accuracy":1,"age":122}"
[INFO:CONSOLE(130)] "### Current location is outside the geofence. (Latitude: 37.4769439, Longitude: 126.8798543)"
[INFO:CONSOLE(141)] "### Location has been updated."
Source Code
Here is the relevant source code for creating the geofence, updating the location, and fetching the current location:

javascript
const polygonGeofence = [
    { lat: 37.47723635589942859, lng: 126.87888902028659288 },
    { lat: 37.47754695732687225, lng: 126.87999260064633233 },
    { lat: 37.47644711695644304, lng: 126.88046098068269885 },
    { lat: 37.47615942455919225, lng: 126.8793670245702998 }
];

// BackgroundGeolocation configuration
BackgroundGeolocation.ready({
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 0,
    locationUpdateInterval: 5000,
    stopTimeout: 1,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    notification: {
        title: "App is running",
        text: "Running in background",
    },
    geofenceModeHighAccuracy: true,
}).then(state => {
    // Adding geofence
    BackgroundGeolocation.addGeofence({
        identifier: 'PolygonGeofence',
        notifyOnEntry: true,
        notifyOnExit: true,
        vertices: polygonGeofence.map(vertex => [vertex.lat, vertex.lng]),
        extras: { type: 'polygon' }
    }).then(() => {
        console.log("### Polygon geofence has been added.");
    }).catch(error => {
        console.error("### Error adding polygon geofence: ", error);
    });
});

// Handling geofence events
BackgroundGeolocation.onGeofence(geofenceEvent => {
    console.log("### Geofence event: ", JSON.stringify(geofenceEvent));

    if (geofenceEvent.action === 'ENTER') {
        isInsideGeofence = true;
        enableAppFeatures();
        console.log("### Entered the geofence.");
    } else if (geofenceEvent.action === 'EXIT') {
        isInsideGeofence = false;
        disableAppFeatures();
        console.log("### Exited the geofence.");
    }

    let action = (geofenceEvent.action === 'ENTER') ? 'entered' : 'exited';
    let message = `${geofenceEvent.identifier} has been ${action}`;

    // Trigger local notification
    cordova.plugins.notification.local.schedule({
        title: "MySafety",
        text: message,
        foreground: true
    });

    console.log(`### Notification: ${message}`);
});

// Updating location
BackgroundGeolocation.onLocation(updateLocation, error => {
    console.error("### [Location] error: ", error);
});

function updateLocation(location) {
    console.log("### Updating location: ", JSON.stringify(location.coords));

    // Check if the current location is within the geofence
    const inside = isInsideGeofence ? "inside" : "outside";
    console.log(`### Current location is ${inside} the geofence. (Latitude: ${location.coords.latitude}, Longitude: ${location.coords.longitude})`);

    // Show notification if inside geofence
    if (isInsideGeofence) {
        cordova.plugins.notification.local.schedule({
            title: "Location Info",
            text: `Current location is inside the geofence. (Latitude: ${location.coords.latitude}, Longitude: ${location.coords.longitude})`,
            foreground: true
        });
    }

    console.log("### Location has been updated.");
}
I believe the current location should be recognized as inside the geofence based on the coordinates provided. However, the logs indicate otherwise.

Thank you for your assistance. Looking forward to your insights.

**Comment by christocracy** [comment]
See wiki “Debugging”.  Learn to fetch logs from the plug-in using .emailLog method.
