### ISSUE TITLE
can I see remaining time after stopAfterElapsedMinutes

### ISSUE THREAD

**Issue by malmator** [transistorsoft/cordova-background-geolocation-lt#1464]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
I would like to be able to access the remaining time when using stopAfterElapsedMinutes
this way I can display a progress bar (seconds woud be nice)
I want the app to stop location reporting after a stopAfterElapsedMinutes has elapsed (for privacy reasons). It would be nice if I could access the remaining time. It could be returned in onLocation handler and also by some other function that returns state

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> It would be nice if I could access the remaining time

You can’t.
