### ISSUE TITLE
(Android) Google Play rejected app for FOREGROUND_SERVICE_HEALTH permission

### ISSUE THREAD

**Issue by dpa99c** [transistorsoft/cordova-background-geolocation-lt#1467]
## Your Environment
* Plugin version: 4.14.2
* Platform: Android
* OS version: 14
* Device manufacturer / model: Google Pixel 6
* Cordova version (`cordova -v`): 12.0.0
* Cordova platform version (`cordova platform ls`): cordova-android@13.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
    desiredAccuracy: "DESIRED_ACCURACY_NAVIGATION",
    distanceFilter: 1,
    stopDetectionDelay: 5,
    //Android Only
    notification:{
        title: "My App",
        text: 'Tracking location',
        smallIcon: 'drawable/background_geolocation_tracking',
        largeIcon: 'drawable/background_geolocation_tracking',
        channelName: 'Tracking location'
    },
    foregroundService: true,
    disableLocationAuthorizationAlert: true,
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: {
	    title: "Allow access to this device's location in the background?",
	    message: "My App requires access to your location when \"not using the app\" (the screen is off or another app is on the screen) in order to track your position around the walk. Please enable {backgroundPermissionOptionLabel} location permission",
	    positiveAction: "Change to {backgroundPermissionOptionLabel}",
	    negativeAction: "Cancel"
	}
}
```

## Expected Behavior

Google should not reject the app because of the `FOREGROUND_SERVICE_HEALTH` permission this plugin adds.

## Actual Behavior

Google rejected my app update because of the `FOREGROUND_SERVICE_HEALTH` permission this plugin adds.

## Steps to Reproduce
N/A

## Context

Google rejected my app update on the basis that the declared use case for `FOREGROUND_SERVICE_HEALTH` permission is not compliant with how it's allowed to be used:

![policy_status](https://github.com/user-attachments/assets/0bc47b1a-a83e-4f71-8781-473bc88be4d6)

![permissions_details](https://github.com/user-attachments/assets/1d81a71c-d195-47a1-abeb-7ba56c658f4c)

- The `FOREGROUND_SERVICE_HEALTH` permission is added by this plugin.
- The are 2 options in the Play Store Console for declaring use of this permission:
    - "Health data sync, step counter, exercise tracker"
    - "Other", which asks "Describe your app's use of this permission, including why the task must start immediately and cannot be paused or restarted"
- I need to know why this plugin requires this permission and for what use case, so that I can provide this information to Google
    - Or whether this permission can be removed using `tools:node="remove"` without affecting plugin functionality for my use case:
- My app is a hiking route navigation app:
	- Users purchase routes and the app uses background location tracking via this plugin to track the user so it can notify them when they reach the next location that requires instructions. 
	- Since the walk duration can be several hours, it's essential that the app optimises its use of battery in order to last for the duration of the walk. 
    - However, it's not directly a health app: there is not step counter or exercise tracker
- The video demonstrating how my app uses `BACKGROUND_LOCATION` permission for Google's review purposes is here: https://youtube.com/shorts/ZiJZojrtTjY
    - Google is happy with this video as a use case for `BACKGROUND_LOCATION` permission but not for `FOREGROUND_SERVICE_HEALTH` permission
- Here's my declaration of usage `FOREGROUND_SERVICE_HEALTH` as "Health - Other" which Google says is non-compliant:

![foreground_service_permissions](https://github.com/user-attachments/assets/46ae4db8-2a05-4efd-8782-f73201a37431)
    - Google says this declared use case does not justify usage of `FOREGROUND_SERVICE_HEALTH`

- I read your blog posts [here](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353) and [here](https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a) but could not find any justification for usage of `FOREGROUND_SERVICE_HEALTH`

## Debug logs
N/A

**Comment by christocracy** [comment]
>Plugin version: 4.14.2

That permission was removed [last june](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#4165--2024-06-12)
