### ISSUE TITLE
After reseting the device locations are not updating

### ISSUE THREAD

**Issue by mahmed-ntd** [transistorsoft/cordova-background-geolocation-lt#147]
Once we reset the device then plugin is not generating the locations, neither it is asking for any permissions.

Current work around: Need to uninstall the app and reinstall the app.

Device type: iPhone
Device model: iPhone 6s Plus
OS version: iOS 9.3.2

**Comment by christocracy** [comment]
There are several kinds of reset, from only "content and settings" to
complete wipe.

Specific steps please

On Thursday, July 7, 2016, mahmed-ntd <notifications@github.com> wrote:

> Once we reset the device then plugin is not generating the locations,
> neither it is asking for any permissions.
>
> Current work around: Need to uninstall the app and reinstall the app.
>
> Device type: iPhone
> Device model: iPhone 6s Plus
> OS version: iOS 9.3.2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/147>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l-n2wRrVfBK_bKT4QfBo_ddDOJaLks5qTal7gaJpZM4JHpq7>
> .
>


-- 
Snet form Gmail Mobile

**Comment by mahmed-ntd** [comment]
Settings -> General -> Reset -> Reset Location & Privacy
