### ISSUE TITLE
Playstore android app not recording location after the application is killed

### ISSUE THREAD

**Issue by shyamal890** [transistorsoft/cordova-background-geolocation-lt#149]
I installed the app on Xiaomi Mi4i and restarted the mobile there were no locations recorded when I opened the app after a few hours.

**Comment by christocracy** [comment]
Adb logs please

On Sunday, July 10, 2016, Shyamal Parikh <notifications@github.com> wrote:

> I installed the app on Xiaomi Mi4i and restarted the mobile there were no
> locations recorded after I opened the app after a few hours.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/149>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l5LGCMobfJKV478Gbou4_CTlzpdRks5qUJVAgaJpZM4JIxwC>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
And os version

On Sunday, July 10, 2016, Chris Scott <christocracy@gmail.com> wrote:

> Adb logs please
>
> On Sunday, July 10, 2016, Shyamal Parikh <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I installed the app on Xiaomi Mi4i and restarted the mobile there were no
>> locations recorded after I opened the app after a few hours.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/149>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAA6l5LGCMobfJKV478Gbou4_CTlzpdRks5qUJVAgaJpZM4JIxwC>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile
