### ISSUE TITLE
New version 0.6.2 - requires Motion/Fitness access

### ISSUE THREAD

**Issue by garrettlangley** [transistorsoft/cordova-background-geolocation-lt#15]
Seems strange that a Location plugin needs access to "Fitness" data?

**Comment by christocracy** [comment]
How so?

On Wednesday, October 7, 2015, Garrett Langley <notifications@github.com>
wrote:

> Seems strange that a Location plugin needs access to "Fitness" data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/15>
> .
>


-- 
Snet form Gmail Mobile

**Comment by garrettlangley** [comment]
I am just trying to think through how User's will react when asked for these permissions

**Comment by christocracy** [comment]
Determing the "activity type" (stationary, biking, vehicle, walking) is
perfectly valid information for a tracking plugin.

If Apple deems the user must grant access to this "fitness" data, so be it.

I already make valuable use of this data in Android for the stop/start
switching mechanism.  I know exactly what I'm doing.

On Wednesday, October 7, 2015, Garrett Langley <notifications@github.com>
wrote:

> I am just trying to think through how User's will react when asked for
> these permissions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/15#issuecomment-146180998>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
And Is easily switched off via #disableMotionDetection which I plan to add

On Wednesday, October 7, 2015, Chris Scott <christocracy@gmail.com> wrote:

> Determing the "activity type" (stationary, biking, vehicle, walking) is
> perfectly valid information for a tracking plugin.
>
> If Apple deems the user must grant access to this "fitness" data, so be it.
>
> I already make valuable use of this data in Android for the stop/start
> switching mechanism.  I know exactly what I'm doing.
>
> On Wednesday, October 7, 2015, Garrett Langley <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I am just trying to think through how User's will react when asked for
>> these permissions
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/15#issuecomment-146180998>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
`disableMotionDetection: true` is now possible.

**Comment by aks0020** [comment]
I have passed `disableMotionDetection: true` in `bgGeo.configure` but it still asks for Motion & Fitness activity permission (iOS 9.2).

**Comment by christocracy** [comment]
See docs for #disableStopDetection & #disableMotionActivityUpdates.

It's disableMotionActivityUpdates which controls the "health & fitness"
permission

On Tuesday, March 15, 2016, Akash <notifications@github.com> wrote:

> I have passed disableMotionDetection: true in bgGeo.configure but it
> still asks for Motion & Fitness activity permission (iOS 9.2).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/15#issuecomment-196682208
>


-- 
Snet form Gmail Mobile

**Comment by aks0020** [comment]
ok thanks I will try this. I have not read api doc properly. :smile:
