### ISSUE TITLE
Burst of location events fired when bgGeo.start() is triggered

### ISSUE THREAD

**Issue by Luke-Tan** [transistorsoft/cordova-background-geolocation-lt#150]
I'm not sure if this is intended or not, but my app records a burst of about 5 or so location events when bgGeo.start() is triggered, regardless of whether my device is stationary or not. Is there a way around this  if possible?

**Comment by christocracy** [comment]
This burst is by design.  The plugin fetches a series of "samples" when
changing state.

Check for locations.sample === true


On Monday, July 11, 2016, Luke-Tan <notifications@github.com> wrote:

> I'm not sure if this is intended or not, but my app records a burst of
> about 5 or so location events when bgGeo.start() is triggered, regardless
> of whether my device is stationary or not. Is there a way around this if
> possible?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/150>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l5iVUIH9ZNIJ7gJtSL728W-IGNgdks5qUflMgaJpZM4JJHut>
> .
>


-- 
Snet form Gmail Mobile

**Comment by Luke-Tan** [comment]
So with that being said, there is no way for me to change this?

**Comment by christocracy** [comment]
No, why would you *want* to?  If you're not interested in these helpful *sample* locations, simply *ignore* them.

It can take some time before the *best* location arrives.  You can use these samples to quickly update the user's current position on the map *progressively* as the locations arrive.

You can see this on native map apps as the accuracy slowly improves.

**Comment by Luke-Tan** [comment]
The thing is I would like to plot points on a map for where the user is/was, and this means that the burst of locations will plot a bunch of relatively seemingly inaccurate points on the map. Can this be fixed by first checking if location.sample == false in the success callback function?

**Comment by christocracy** [comment]
The concept is simple and completely up to your application code.

If (location.sample) {
  // do this
} else (
  // do that
}

**Comment by Luke-Tan** [comment]
Is there a way to select the most accurate sample out of the set of samples that have been recorded?
