### ISSUE TITLE
For Android Location Manager is deprecate 

### ISSUE THREAD

**Issue by sachinchoudhary** [transistorsoft/cordova-background-geolocation-lt#151]
In this plugin you using location manager.it is depricated.so that it is not showing exact location.
You need to use GoogleApiClient & LocationRequest.

**Comment by christocracy** [comment]
What are you talking about?  I use nothing deprecated.  This is very
advanced.

Android uses play-services FusedLocationProvider.

On Monday, July 11, 2016, sachin <notifications@github.com> wrote:

> In this plugin you using location manager.it is depricated.so that it is
> not showing exact location.
> You need to use GoogleApiClient & LocationRequest.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/151>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l6MjpzfbjqRP1EjYRw-p3LUvKqbAks5qUjipgaJpZM4JJUWw>
> .
>


-- 
Snet form Gmail Mobile
