### ISSUE TITLE
iOS prompt for motion & fitness activity access?

### ISSUE THREAD

**Issue by dgobaud** [transistorsoft/cordova-background-geolocation-lt#152]
Hi, On some phones we sometimes see the prompt for motion & fitness activity access. We have no idea why. We think it is this plugin. Does this plugin ever prompt for that type of access and if so what causes it? Thank you

![image](https://cloud.githubusercontent.com/assets/240811/16748815/358512d8-477b-11e6-8503-77d78c3006e6.png)

**Comment by christocracy** [comment]
the plugin attaches activity data to each location (see Location Data
Schema in wiki), eg "on_foot", "in_vehicle", etc.  if this data is not
valuable to you, disableMotionActivityUpdates: true.

On Monday, July 11, 2016, David Gobaud <notifications@github.com> wrote:

> Hi, On some phones we sometimes see the prompt for motion & fitness
> activity access. We have no idea why. We think it is this plugin. Does this
> plugin ever prompt for that type of access and if so what causes it? Thank
> you
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/240811/16748815/358512d8-477b-11e6-8503-77d78c3006e6.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/152>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l_0LrHmE0dU5aOkSCGAMGcLW6UAaks5qUsIugaJpZM4JJ3BG>
> .
>


-- 
Snet form Gmail Mobile

**Comment by dgobaud** [comment]
Got it thanks - do you know why this would only happen sometimes on some phones...? I've never seen it on my iPhone 6s+ but other users do see it...

**Comment by christocracy** [comment]
No idea.
