### ISSUE TITLE
Is there a way to disable the notifications when the device is moving or for every background fetch

### ISSUE THREAD

**Issue by brahmanp** [transistorsoft/cordova-background-geolocation-lt#155]
When I drive with the background location tracking enabled, I get a of notifications every time the location is updated.. Is there a way to disable this? 

Please note that I do not want to disable the push notifications, but only disable the notifications generated by the plugin. 

Kiran

**Comment by christocracy** [comment]
[debug: false](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-boolean-debug-false)

These notification are provided for assistance while developing.  If you set `debug: false`, you also won't get any logging either.

**Comment by brahmanp** [comment]
Thank you!! BTW -- Your plugin is awesome!!

**Comment by keithdmoore** [comment]
It would be nice if you could still get logging but no notifications.
