### ISSUE TITLE
force isMoving to always be true

### ISSUE THREAD

**Issue by Luke-Tan** [transistorsoft/cordova-background-geolocation-lt#156]
Hi,
I understand that this plugin has two states: stationary and moving. I assume that when the phone GPS is disconnected i.e. when underground in a subway, the plugin is automatically forced into the stationary state. However, when resurfacing and reconnecting, I understand that it will monitor for about 100m+(iOS) before reactivating.  My app automatically forces isMoving to be true upon bgGeo.start(). Hence, is it possible to always have isMoving to be true, and if not, is it possible to automatically set isMoving to be true once the device has resurfaced and GPS is working properly again?

**Comment by christocracy** [comment]
I'll see what I can do.  traditionally, when the plugin receives a location-error from iOS, it's simply turned off location-updates, allowing the app to suspend.

Perhaps instead I can try initiating the stop-detection system, which will initiate the `stopTimeout` timer.

When location-services *are* re-acquired, the plugin *will* re-engage the last known state.

**Comment by jbfrequence** [comment]
Hi,

I faced the same behaviour with my app on IOS when running in a tunnel.. I used an old version of the plugin (2.3.0). Does the last version of the plugin (2.6.0) enhanced something about this issue ? If yes, is there a specific configuration to handle this ?
Otherwise,, what do you recommand to keep the isMoving state even when location errors occur ?

Thanks

**Comment by christocracy** [comment]
No, there has been nothing changed to address this.  I *do* suggest you upgrade to latest version though (2.6.1).  See the [CHANGELOG](https://github.com/transistorsoft/cordova-background-geolocation/blob/master/CHANGELOG.md#change-log).

Also, please document the problem in your case.  What is the behaviour you observe when you drive into a tunnel?  Can you show me map-data describing the issue?

**Comment by jbfrequence** [comment]
Hi Chris,

Thanks for your reply. Since we customized "distanceFilter" property config for IOS config (it was not used before) , we have not observed the problem again. 

You may consider my request as closed

Best regards
