### ISSUE TITLE
How to disable the notification? And how to check if it uploads successfully onto a server?

### ISSUE THREAD

**Issue by DuoL** [transistorsoft/cordova-background-geolocation-lt#157]
I didn't find the option for disabling the notification.
And is there a way of checking if I can successfully upload my geolocation onto the server? 
I've used the example server but there is no result.
What if my server is made of Node.js? Is it the same way as 'http'?

**Comment by christocracy** [comment]
[debug: false](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-boolean-debug-false).  These notifications are there to assist you during development.

You should be watching the logs.  The plugin is very verbose about HTTP responses, logging the response status as well as error-text.

You can also listen to the plugin's [http event](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#onhttpsuccessfn-failurefn)

Watch your logs!
