### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by KproApps2** [transistorsoft/cordova-background-geolocation-lt#158]
KproApps2 commented 13 minutes ago
Where should the license appear because it has been changed I think from about 3 months ago

It is crashing my app
 @christocracy
 Transistor Software member
 christocracy commented 10 minutes ago
I don't understand why you're commenting at the SampleApp repo.  Are you a
customer?
…
@KproApps2
     
KproApps2 commented 41 seconds ago
Yeah, seems this is the problem

Warning: The method signature for BackgroundGeolocation#configure has changed! Instead of providing the location-callback, error-callback to this method, you should now use the dedicated #onLocation method to provide these callabcks. The #success, #failure callbacks provided to #configure will now fire to signal when the plugin is ready or failed to configure. Please see the new documentation for #configure method and modify your code to respect the new signature ASAP.

**Comment by christocracy** [comment]
Are you a customer?

**Comment by KproApps2** [comment]
Yeah , SurviveDrive

**Comment by christocracy** [comment]
Why are you commenting on the **free** repo?

Use the private member only repo you purchased access to.  It doesn't make sense to talk about license on the free version
