### ISSUE TITLE
IOS doesn't fire onLocation event and not measure the tracking 

### ISSUE THREAD

**Issue by idanperlmutter** [transistorsoft/cordova-background-geolocation-lt#161]
This is the config:
```
bgGeo.configure({
           
            // Geolocation config
            desiredAccuracy: 0, 
            distanceFilter: 10,
            stopAfterElapsedMinutes: 300, 
            
            locationUpdateInterval: 1000,
            fastestLocationUpdateInterval: 2000,
            minimumActivityRecognitionConfidence: 30,
         
            stationaryRadius: 10, 
            activityType: 'Other',

            
            activityRecognitionInterval: 0, 
            stopTimeout: 5,
            heartbeatInterval: 5,

           
            stopOnTerminate: false,
            startOnBoot: false,

            // HTTP / SQLite config
            url: HTTPManager.EndPoint,
            
            method: 'POST',
            autoSync: false,
            batchSync: true,
            maxDaysToPersist: 1,
            headers: {
                "Content-Type": "application/x-www-form-urlencoded"
            },
            
             schedule: ['1-7 15:27-15:30']
            
            
        }, function (state) {
            // This callback is executed when the plugin is ready to use.
            console.log('BackgroundGeolocation ready: ', state);
            bgGeo.startSchedule(function() {
                console.info('- Scheduler started');
            }, function(y){console.log(y)});

        });

```

**Comment by christocracy** [comment]
Are you watching the iOS logs?
Have you set debug: true?

**Comment by christocracy** [comment]
Test in sim

**Comment by idanperlmutter** [comment]
I have tested it with sim and nothing happened.

**Comment by christocracy** [comment]
Are you specifically trying to test scheduling?

**Comment by idanperlmutter** [comment]
no the schedule is another test
The ios log is:
Apache Cordova native platform version 4.1.1 is starting.
Multi-tasking -> Device: YES, App: YES


Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
Using UIWebView
[CDVTimer][handleopenurl] 0.253022ms
[CDVTimer][intentandnavigationfilter] 4.417002ms
[CDVTimer][gesturehandler] 0.173032ms
[CDVTimer][backgroundfetch] 0.165045ms
[CDVTimer][file] 222.314000ms
[CDVTimer][splashscreen] 21.622002ms
[CDVTimer][TotalPluginStartup] 250.815988ms
Resetting plugins due to page load.
Finished load of: file:///var/containers/Bundle/Application/3332CB0B-3B4A-4BB9-8F0E-248BA49D6195/Track2Go.app/www/index.html
-[SQLitePlugin pluginInitialize] [Line 33] Initializing SQLitePlugin
-[SQLitePlugin pluginInitialize] [Line 44] Detected docs path: /var/mobile/Containers/Data/Application/B58B1AA2-573C-4E79-BF41-E5BCAE2416D9/Documents
-[SQLitePlugin pluginInitialize] [Line 48] Detected Library path: /var/mobile/Containers/Data/Application/B58B1AA2-573C-4E79-BF41-E5BCAE2416D9/Library
-[SQLitePlugin pluginInitialize] [Line 55] no cloud sync at path: /var/mobile/Containers/Data/Application/B58B1AA2-573C-4E79-BF41-E5BCAE2416D9/Library/LocalDatabase
-[SQLitePlugin openNow:] [Line 137] open full db path: /var/mobile/Containers/Data/Application/B58B1AA2-573C-4E79-BF41-E5BCAE2416D9/Documents/ok2go.db
-[SQLitePlugin openNow:] [Line 163] Good news: SQLite is thread safe!
THREAD WARNING: ['Geolocation'] took '19.010010' ms. Plugin should use a background thread.
╔═════════════════════════════════════════════════
║TSLocationManager ► Settings: initialize
╠═════════════════════════════════════════════════
╔═════════════════════════════════════════════════
║TSLocationManager ► SQLite init
╠═════════════════════════════════════════════════
✓ Opened database
✓ Unlocked all records
ERROR: Method 'addProviderChangeListener:' not defined in Plugin 'BackgroundGeolocation'
-[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["BackgroundGeolocation798538408","BackgroundGeolocation","addProviderChangeListener",[]]
THREAD WARNING: ['BackgroundGeolocation'] took '39.869873' ms. Plugin should use a background thread.
- CDVBackgroundFetch configure
 - CDVBackgroundGeolocation captured Schedule event: TSSchedule[triggered: 0, 15:27 - 15:30, Days:1,2,3,4,5,6,7]
THREAD WARNING: ['Geolocation'] took '10.814209' ms. Plugin should use a background thread.
THREAD WARNING: ['Geolocation'] took '10.968994' ms. Plugin should use a background thread.
THREAD WARNING: ['Geolocation'] took '98.202148' ms. Plugin should use a background thread.
THREAD WARNING: ['Geolocation'] took '12.128174' ms. Plugin should use a background thread.

**Comment by christocracy** [comment]
Yes `providerchange` event is new.  What version of the plugin are you using?

**Comment by idanperlmutter** [comment]
2.0.0

**Comment by christocracy** [comment]
uninstall & re-install the plugin.

**Comment by idanperlmutter** [comment]
I did it and nothing occurs

**Comment by christocracy** [comment]
Ok, my bad.  I forgot to add that method to `CDVBackgroundGeolocation.h`.  Merged to master.  Re-install; should be good.
