### ISSUE TITLE
IOS doesn't fire onLocation event

### ISSUE THREAD

**Issue by idanperlmutter** [transistorsoft/cordova-background-geolocation-lt#169]
I attached an event to onLocation event and nothing. The device tracks the way but doesn't fire any event for it.

**Comment by Jpsankaran** [comment]
Yes..In my case also, OnLocation event is not firing after getting `isMoving : false`

**Comment by christocracy** [comment]
Xcode logs please.  And config you're using

**Comment by jschwarz0** [comment]
my app is working fine with the latest version of this plugin on iOS 9/10 on 5 different phones.

**Comment by christocracy** [comment]
@Jpsankaran Why should `location` event fire when `isMoving: false`.  The whole philosophy of this plugin is be as battery-efficient as possible by detecting when the device is **moving** vs **stationary**.

When the device is **stationary**, the plugin turns off location-services and let iOS put your app to sleep.
