### ISSUE TITLE
what's the uuid in location data for?

### ISSUE THREAD

**Issue by m-menon** [transistorsoft/cordova-background-geolocation-lt#179]
Is there any specific use for the uuid in the location data that's posted from the device. Earlier I thought that it was to identify the device but that doesn't seem to be the case. I surely can pass other identification params thru the extra headers but just curious whats the use for uuid? thnks

**Comment by christocracy** [comment]
This UUID has nothing to do with the device -- it's a UUID for the *location*.

This is for rare cases where the plugin could potentially post the same location twice.  With the UUID stored in your database, the server will know if a location was posted twice.
