### ISSUE TITLE
iOS Plugin should use a background thread reg.. 

### ISSUE THREAD

**Issue by chansdad** [transistorsoft/cordova-background-geolocation-lt#180]
So in xcode when i run the app i see the messages similar to below . My question is -
1.Is there any configuration that i would have to set to get rid of these messages?
2. Will there be any issues getting the app approved to be included in app store with these messages ?

THREAD WARNING: ['BackgroundGeolocation'] took '17.423828' ms. Plugin should use a background thread.

Thanks

**Comment by christocracy** [comment]
You don't need to worry about this.  This is merely Cordova barking that one of my plugin's API methods has blocked the main-thread for a mere `17ms`.  It would be a problem if it were blocking for "hundreds" of milliseconds.

This has nothing at all to do with Apple's review process.
