### ISSUE TITLE
Persistent Notification does not show Icon in Android 6.0

### ISSUE THREAD

**Issue by razam217** [transistorsoft/cordova-background-geolocation-lt#182]
Hi, 
**Location Service Activated** persistent notification while the **foreground:true** is not showing icon in Android 6.0. It shows nicely in Android 5.0. 
Is there a configuration option for icon?

**Comment by christocracy** [comment]
The config is not `foreground`, it's [`foregroundService`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-boolean-foregroundservice-false)

Are you a customer or using the SampleApp demo key?

**Comment by Frumba** [comment]
I have the same issue on android 7.0 and it's working well on android 5.0.

Any idea?

Thanks!
