### ISSUE TITLE
POST empty

### ISSUE THREAD

**Issue by taufpate** [transistorsoft/cordova-background-geolocation-lt#185]

**Comment by taufpate** [comment]
sorry my mistake:

if any one have this question in PHP the answer is:

$data = json_decode(file_get_contents('php://input'), true);
error_log(print_r($data,true));

**Comment by christocracy** [comment]
Yes, this issue has been referenced many times before.

It's the first question I ask when I see this issue:  "are you using php?".

Search the closed issues for "php"
