### ISSUE TITLE
App not sending location in IOS Background mode

### ISSUE THREAD

**Issue by bacemtabikh** [transistorsoft/cordova-background-geolocation-lt#186]
Hi,

I'm trying the free version on IOS, the plugin is saving location in background mode but it's sending those locations to our server only when starting the app or when going into foreground mode.
But in case I leave the app 4 hours in background, it doesn't send any location to our server unless I go into foreground mode.
Shouldn't it send also in background mode?

Thanks.

**Comment by christocracy** [comment]
- Configuration?
- Plugin version?

**Comment by bacemtabikh** [comment]
Plugin Version: 2.0.9

Configuration:

bgGeo.configure({
       // Geolocation config
       desiredAccuracy: 0,
       distanceFilter: 10,
       stationaryRadius: 50,
       locationUpdateInterval: 1000,
       fastestLocationUpdateInterval: 5000,

       // Activity Recognition config
       activityType: 'AutomotiveNavigation',
       activityRecognitionInterval: 5000,
       stopTimeout: 5,

       // Application config
       debug: true,
       stopOnTerminate: false,
       startOnBoot: true,

   }, function(state) {
       // This callback is executed when the plugin is ready to use.
       console.log('BackgroundGeolocation ready: ', state);
       if (!state.enabled) {
           bgGeo.start();
       }
   });

Thank you.

**Comment by christocracy** [comment]
The plugin doesn't turn on location-services unless you move.  If you're sitting in the same place for hours, your app is sleeping.

You need to move about 100-200 meters before iOS awakens your app.  Only then will the plugin begin recording a location each `distanceFilter` meters.

**Comment by jschwarz0** [comment]
I had this problem too. I was using angular http and then jquery. It seems that in "deep sleep" the geo callback was getting fired but the network call was not completing. 

Once I changed to use the plugin to make the network call, everything has been working well.

**Comment by christocracy** [comment]
Show me the code you're using to sync to your server.  You're probably calling `bgGeo.finish(taskId)` too early, causing iOS to suspend your app before your HTTP requests are complete.

But, yea...as @jschwarz0 said, you really should let the plugin do your HTTP for you.  It's much better at it than Ajax.  It also has automatic retry on failure.

**Comment by christocracy** [comment]
Closed due to lack of input.
