### ISSUE TITLE
App not running in background in Android 6 MI5 device

### ISSUE THREAD

**Issue by sureshway** [transistorsoft/cordova-background-geolocation-lt#187]
Dear sir,

The app is not running in Android 6 version MI5 device as background service. Kindly suggest the solution to overcome it.

**Comment by christocracy** [comment]
This is the free "Lite" repository.  Customers are not supposed to use this repo at all (nor the npm version `cordova-background-geolocation-lt`.  Use the Premium repo only.

**Comment by sureshway** [comment]
How can i add premium version plugin in config.xml?. I am uing phonegap build for building the app.

**Comment by christocracy** [comment]
You are a customer.  Please post issues at the **private repo**
