### ISSUE TITLE
heartbeatInterval always 60 seconds

### ISSUE THREAD

**Issue by rodrigodvp** [transistorsoft/cordova-background-geolocation-lt#188]
Hi,

I am trying to include the on heartbeat event, but when I set the interval with 30 seconds and test the app, the getState function said that is always 60.

I put the log of getState function.

{"distanceFilter":10, "pausesLocationUpdatesAutomatically":false, "debug":false, "startOnBoot":true, "headers":false, "maxRecordsToPersist":-1, "disableStopDetection":false, "maxBatchSize":-1, "extras":false, "url":"http://.....", "disableElasticity":false, "stopTimeout":120, "locationAuthorizationRequest":"Always", "params":{}, "schedule":false, "activityRecognitionInterval":10000, "preventSuspend":true," useSignificantChangesOnly":false, "locationTimeout":60, "activityType":1, "stationaryRadius":25, "method":"POST", "disableMotionActivityUpdates":false, "batchSync":false, "stopAfterElapsedMinutes":-1, "stopOnTerminate":false, "desiredAccuracy":-1, "isMoving":false, "stopDetectionDelay":0, "heartbeatInterval":60, "autoSync":true, "enabled":true, "maxDaysToPersist":1, "schedulerEnabled":false 
}

Thanks.

**Comment by christocracy** [comment]
Minimum is 60.
