### ISSUE TITLE
[iOS 10] Breaking change to CoreMotion with Fix

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/cordova-background-geolocation-lt#189]
>Important: To protect user privacy, an iOS app linked on or after iOS 10.0, and which accesses the device’s accelerometer, must statically declare the intent to do so. Include the NSMotionUsageDescription key in your app’s Info.plist file and provide a purpose string for this key. If your app attempts to access the device’s accelerometer without a corresponding purpose string, your app exits.
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html

**tl;dr** You must add the key `NSMotionUsageDescription` key in your app’s `Info.plist`.  Same idea as `NSLocationAlwaysUsageDescription`.

Example:  "The app uses accelerometer to increase battery efficiency by intelligently toggling location-tracking"

I will add this key to the plugin's `config.xml` but in the meantime, you have to add it to your `.plist` manually.

**Comment by Grandt** [comment]
So, until the next release we just have to add this to the config.xml in your plugin root dir under `<platform name="ios">`?

```
        <config-file target="*-Info.plist" parent="NSMotionUsageDescription">
            <string>The app uses accelerometer to increase battery efficiency by intelligently toggling location-tracking</string>
        </config-file>
```

**Comment by christocracy** [comment]
Key added in version `2.0.11`.
