### ISSUE TITLE
No background location update after airplane is switched off in stationary mode.

### ISSUE THREAD

**Issue by egoossens** [transistorsoft/cordova-background-geolocation-lt#191]
Hello and thanks for this awesome plugin.

This might be an iOS intended behaviour instead of an issue with the plugin. Typical use for my app would be:
- User is stationary
- Switches airplane mode on (and flies)
- Switches airplane mode off
- User is stationary in the new location - No location update is received
- Switches airplane mode on (and flies)
- Switches airplane mode off
- etc.

Is there any way to get a location update even though the user probably won't exit stationary mode between switching airplane mode off then back on?

Thanks!

Edouard

**Comment by christocracy** [comment]
Manually, via `#getCurrentPosition`.

**Comment by egoossens** [comment]
Thanks for getting back.

Ok, but then how can I detect the airplane mode switch off while in the background?

**Comment by egoossens** [comment]
Is there any way to wire a listener to the event that triggers the following log outputs?

TSLocationManager ► Network: No Connection
TSLocationManager ► Network: Cellular

Maybe I need another plugin for that?

**Comment by christocracy** [comment]
You might try listening to the `providerchange` event.  See the docs.

**Comment by egoossens** [comment]
Yes I tried that, but it doesn't seem to be triggered for that kind of event.

**Comment by christocracy** [comment]
I will have to create a new event to provide that info

**Comment by egoossens** [comment]
That would be awesome. I'll stay tuned for more.

I tried using the cordova-plugin-network-information plugin but it doesn't trigger events in the background.

**Comment by christocracy** [comment]
This issue is very old.  `connectivitychange` event has been implemented since.
