### ISSUE TITLE
UUIDs in the records saved in my db are all different from the UUIDs of the same records in sqLite

### ISSUE THREAD

**Issue by mwarren2** [transistorsoft/cordova-background-geolocation-lt#192]
Ok, I don't use the http possibility that you offer to save records in my database. That's because of the nature of Meteor, which is my framework. I prefer to do it my way.

I wait for onLocation to fire, then save the location object in my db, exactly as was passed by onLocation(), using my own code, and wrapped in a location object and saved with a walk name.

So my records look like this:

`{
    walkName: 'myWalk',
    location: recordPassedToMeByOnLocation
}`

Works fine.

I'd like to be in a position to check that every record in sqLite has reached my db safely. Maybe I strayed into an area where communications are bad (it happens around here) and my server was unreachable, or whatever.

The UUID would be a useful way of checking. I go to my db, get all the UUIDs for that walk, and then check against sqLite.
Problem is: none of the UUIDs match.

Is this by design? 
I may well have missed something, in which case any help or advice would be greatly appreciated.

**Comment by christocracy** [comment]
Currently, the UUID sent to your Javascript is not the same as the one stored in the plugin's db.

I have this fixed in the Premium version.  I might be pushed around the end of week.

If you care about Android and `stopOnTerminate: false`, you should really let the plugin handle the HTTP.

**Comment by mwarren2** [comment]
Ok, understood.
And thankyou for the blazing fast support.
