### ISSUE TITLE
Removing listeners?

### ISSUE THREAD

**Issue by susco-sean** [transistorsoft/cordova-background-geolocation-lt#195]
Does the plugin respond to .remove or have some other method for removing listeners? The use case is that we're setting two location listeners and need to be able to stop one.

Edit: Perhaps another approach: Is there a good way to _reset_ the plugin (removing all listeners, reconfigure, etc)? Can I just call bgGeo.configure(configObject) again?

**Comment by christocracy** [comment]
No.  Someone else asked for this a while back too.  I'll probably implement it in the future.

**Comment by susco-sean** [comment]
Okay, so once we've started the plugin and added listeners, we can start/stop, but there's no way to remove listeners or reset the plugin? Good to know, I'm thinking the way around that for the immediate application is to have the callback functions check a status marker.

**Comment by christocracy** [comment]
You cannot remove listeners, no.  You can only `#start` / `#stop` tracking.

What do you mean by "reset" the plugin?

You always add your own simple event-listener mechanism with a simple js array (pulling this code out-of-my-ass right now).  You could probably find some existing `Event` lib that would work for you.

```Javascript
var locationListeners = [];
function on(event, success, failure) {
  var listener = {success: success, failure: failure};
  switch(event) {
    case 'location':
      locationListeners.push(listener);
      break;
  }
  return listener;
}
function un(event, listener) {
  var listeners;
  switch(event) {
    case 'location':
      listeners = locationListeners;
      break;
  }
  for (var i = listeners.length - 1; i >= 0; i--) {
    if (listeners[i] === listener) { 
      listeners.splice(i, 1);
    }
  }
}

var listener = on('location', function(location) {}, function(error) {});
un(listener);

```

**Comment by ryanagler** [comment]
This is something that is causing me problems as well.  In the app a user logs in, and then a controller does a configureBackgroundGeolocation() with values based on the user's profile and starts tracking.

If the user logs out, the controller's $destroy gets called and does a bgGeo.stop.  If the user logs back in, the listeners are getting called twice (heartbeat, etc).  There needs to be a way to not only stop tracking, but also clearing out all of the listeners.

**Comment by christocracy** [comment]
Ensure you `#configure` and add-listeners **once** for the life time of your app.

Just keep track of a flag in `localStorage` if you have to.
```Javascript
window.localStorage.setItem('configured_bg_geo', 1);
```

Use the plugin's `setConfig` method to apply settings per user.

**Comment by ryanagler** [comment]
I am still running into problems with this.  I have two states in my app, loggedout (no geo should be running) and loggedin (geo initialized/running).  The listener function I want to use needs to be able to work with $scope.  For example:

bgGeo.onHttp(function(response) {
   $timeout(function() {
      $scope.lastResponse = response.status;
   });
}, function(response) {});
<div>{{lastResponse}}</div>

It works fine the first time, the response status appears in the div.   But if the user logs out, and the loggedin state/scope is destroyed, the next time the user logs in, the listener function has no knowledge of the new $scope.   The response statuses will no longer appear in the div.

There really needs to be a way to reset or reinitialize onHttp (and other listeners)

**Comment by christocracy** [comment]
Why are you commenting on this **Free** repo (`-lt` means "Lite"; Free).  Are you not a customer?

**Comment by ryanagler** [comment]
Sorry, I am a customer, but searched for the topic on both and this one was relevant so i replied to it.

**Comment by christocracy** [comment]
It's not possible to remove a Cordova callback function.  It would cause a memory leak if the plugin were to remove the callback functions you registered with the plugins `#on` method.

When the user logs out, you could do a window.reload.  This will reset all the plugins.

**Comment by ryanagler** [comment]
Ok, I wasnt aware Cordova wouldn't let you do that.  It might be ugly, but this seems to be a workaround:

`bgGeo.onHttp(function(response) {
   var elem = angular.element(document);
   var rootScope = elem.injector().get('$rootScope');
   rootScope.$broadcast('gotStatus', response.status);
 }, 
function(response) {});

$scope.$on('gotStatus', function(event, e) {
   $timeout(function() 
      $scope.lastResponse = e;
   });
});
`

**Comment by christocracy** [comment]
I can add a `removeListeners` method only.  You will only be able to remove **all** listeners.

Here's where `cordova` stores its callbacks in Javascript Land:
![](https://www.dropbox.com/s/bcq4jlgxqk2nnah/Screenshot%202016-11-16%2010.57.03.png?dl=1)

Here's what will happen when you do `#removeListeners`:
![](https://www.dropbox.com/s/i0z4zrvh6ike1kv/Screenshot%202016-11-16%2010.58.19.png?dl=1)

```Javascript
removeListeners: function(success, failure) {
        success = success || function(){};
        failure = failure || function(){};
        var re = /^BackgroundGeolocation.*/;
        var mySuccess = function(response) {
            var callbacks = window.cordova.callbacks;
            for (var callbackId in callbacks) {
                if (callbacks.hasOwnProperty(callbackId) && callbackId.match(re)) {
                    delete callbacks[callbackId];
                }
            }
            success(response);
        }
        exec(mySuccess,
             failure,
             'BackgroundGeolocation',
             'removeListeners',
             []
        );
    },
```

It will be posted to the private Premium repo today.

**Comment by ryanagler** [comment]
Thank you.  So what will happen if you call #removeListeners, then do like bgGeo.onHttp?  Will that add a listener, or have no effect?

**Comment by christocracy** [comment]
`#removeListeners` wipes the chalkboard.
If you decide to start drawing on the chalkboard again by adding new listeners, that's fine.

**Comment by christocracy** [comment]
Merged to master in Premium repo.
