### ISSUE TITLE
could not update notificationText value

### ISSUE THREAD

**Issue by locsim** [transistorsoft/cordova-background-geolocation-lt#196]
Hello,
Value of notificationtext is correctly setup during .configure.
But I was not able to change it afterwards using .setConfig.

Is it possible?
Thank you,
Philippe

**Comment by christocracy** [comment]
The new `notificationText` will not apply until the background Service is restarted.  If you want the new `notificationText` applied immediately, do this:

eg: 
```Javascript
// First stop the service.
bgGeo.stop();
// Change the config
bgGeo.setConfig({
  notificationText: "New notification text"
}, function() {
  // Restart the service
  bgGeo.start();
});
```
