### ISSUE TITLE
iOS 10 Fitness Sensor permission

### ISSUE THREAD

**Issue by AlexK01** [transistorsoft/cordova-background-geolocation-lt#197]
Hi, thereis an issue with iOS 10 Fitness permission. Regardless of 'disableMotionActivityUpdates' flag it requests for Fitness Sensor in .start() method, while iOS 9 works as expected and when the flag is set to 'false' - no permission needed,

**Comment by christocracy** [comment]
What version of the plugin are you using?

I just deleted the SampleApp from my device and re-installed with `disableMotionActivityUpdates: true` and I'm not asked for permission.

**NOTE:** The plugin is **highly** optimized when you don't `disableMotionActivityUpdates`.  It has **much** improved triggering when user is moving / stationary, in addition to *much* more accurate activity meta-data (eg: "on_foot", "in_vehicle").

**Comment by AlexK01** [comment]
i'm using the latest npm version. According to the docs:  'If you do not wish to ask the user for the "Health updates", set this option to false; However, you will no longer recieve activity data in the recorded locations.' So i set it to 'false', it was working with 'false' on iOS 9 too

**Comment by AlexK01** [comment]
version 2.0.7

**Comment by christocracy** [comment]
iOS 10 did add the requirement of adding the new key to your plist [`NSMotionUsageDescription`](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW21) (which the latest version of the plugin does automatically add).

This key does clearly state:
>Important: To protect user privacy, an iOS app linked on or after iOS 10.0, and which accesses the **device’s accelerometer**, must statically declare the intent to do so. Include the NSMotionUsageDescription key in your app’s Info.plist file and provide a purpose string for this key. If your app attempts to access the device’s accelerometer without a corresponding purpose string, your app exits

The plugin does access the accelerometer, regardless of whether you `disableMotionActivityUpdates`.  However, I do not get this permission request when I do this.

The latest version on [npm](https://www.npmjs.com/package/cordova-background-geolocation-lt) is `2.0.13`

**Comment by AlexK01** [comment]
thanks this helped
