### ISSUE TITLE
 unable to use this in Moto G 2nd gen

### ISSUE THREAD

**Issue by 38ajay** [transistorsoft/cordova-background-geolocation-lt#198]
I came across a very strange output after installing the App([download](https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic)) while using it on Moto G 2nd Gen. 
I changed the location mode in settings to Device only. GPS is turned on but the app is unable to sense the location. I tried to test this with another 3 handsets of Moto G 2nd gen but same result.

**Comment by christocracy** [comment]
Are you indoors?

**Comment by 38ajay** [comment]
I am in an open ground

**Comment by christocracy** [comment]
Does google maps work when you do this?

**Comment by 38ajay** [comment]
Yes Google maps is able to sense my location. But I need to switch on my mobile internet for that.

**Comment by christocracy** [comment]
No you don't.  It just won't show map tiles.  It will still show a location.

**Comment by 38ajay** [comment]
Did you mean this by referring google maps ([Playstore](https://play.google.com/store/apps/details?id=com.google.android.apps.maps)) ?

**Comment by christocracy** [comment]
yes.  I want you to compare the behaviour of native Google Maps app with that of the plugin

**Comment by 38ajay** [comment]
No map tiles are visible in native google maps but a location pointer of blue color is shown.
Also no tiles are visible In Cordova background app.
But I installed GPS TEST app([link](https://play.google.com/store/apps/details?id=com.chartcross.gpstest))
to fetch my GPS coords and it is working absolutely fine

**Comment by christocracy** [comment]
The version on play store is very old.  Try build the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp).

You can build the SampleApp for Android.  Follow the steps.

**Comment by 38ajay** [comment]
Thanks Chris for prompt reply. I will soon build this SampleApp and provide the test results

**Comment by 38ajay** [comment]
Test results after installing the SampleApp.
**Test case 1)**
Location mode selected High accuracy and Mobile internet switched on.
--Perfectly working fine . Able to see map tiles and location is accurate.

**Test case 2)**
Location mode selected Battery saving and Mobile internet switched on.
--Perfectly working fine . Able to see map tiles and location is accurate.

**Test case 3)**
Location mode selected Device only, Mobile internet switched on and standing in an open ground .
--Map tiles are seen but it shows location of Wisonsin wheras I m in India. I here the sound of doodly-doo.

**Test case 4)**
Location mode selected Device only, Mobile internet switched off and standing in an open ground .
--Map tiles are not seen.

**Comment by christocracy** [comment]
If you hear sounds, that's all that matters.  the plugin is working

**Comment by 38ajay** [comment]
The plugin is unrealistic as it gives wrong location in test case 3(mentioned in above comment).
Also there is no sound heard in test case 4.
