### ISSUE TITLE
Use of coords/accuracy

### ISSUE THREAD

**Issue by flytzen** [transistorsoft/cordova-background-geolocation-lt#199]
According to https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema there is a cords/accuracy field when getting the coordinates.
I have been unable to find any further documentation on this field. I presume it gives an indication of how precise the coordinates are, i.e. whether they were from GPS or WiFi etc. Are you able to clarify what we should expect to see in this field and how to use it?

Thanks for a great library btw!

Frans

**Comment by christocracy** [comment]
You can read specific details about coords in apple docs:
https://developer.apple.com/reference/corelocation/cllocation

**Comment by flytzen** [comment]
Nice, thank you! Do we get the same on Android?

**Comment by christocracy** [comment]
Yes, same schema.
https://developer.android.com/reference/android/location/Location.html

**Comment by flytzen** [comment]
Fantastic, thank you for your help!

**Comment by oliviercherrier** [comment]
Thank you for your help.
