### ISSUE TITLE
Params Nor Locations Are Getting Passed with the url.

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [transistorsoft/cordova-background-geolocation-lt#2]
I have configure set to this....
```
    bgGeo.configure( function(location, taskId){ callbackFn(location, taskId);},
    				 function(error){failureFn(error);}, 
    				 {
						locationUpdateInterval: localStorage.getItem('location_update_interval'),
						fastestLocationUpdateInterval: localStorage.getItem('location_update_interval'),
						desiredAccuracy: localStorage.getItem('desired_accuracy'),
						stationaryRadius: localStorage.getItem('stationary_radius'),
						distanceFilter: localStorage.getItem('distance_filter'),
						disableElasticity : localStorage.getItem('disable_elasticity') == 'on',                    
						autoSync: true,
						batchSync: localStorage.getItem('batch_sync') == 'on',
						debug: localStorage.getItem('debug_mode') == 'on',
						url: localStorage.getItem('ims_url')+'/webSrvRequests/AVL/avlMobilePush.php?unitid='+localStorage.getItem('truck'),
						params:{"my_param": "is coming through now?"},
						headers:{"X-FOO": "bar"},
						//params: [thiscoord],
						/* params: {rcdid:new Date().getTime(), unitid:localStorage.getItem('truck'), network_state:defaultNetwork, platform:platform, version:device.version, uuid:device.uuid, device_name:device.name, collection_type:"linemanapp"},*/
						method: 'GET',
						maxDaysToPersist: 3
    				}

```
But in the apache access.log I see this..

64.183.192.222 - - [17/Sep/2015:14:21:55 -0500] "GET /webSrvRequests/AVL/avlMobilePush.php?unitid=NBT1 HTTP/1.1" 200 196

**Comment by christocracy** [comment]
The data is there, in the JSON body of the HTTP request.  PHP is a bit dumb about this.

```
<?php
    $data = file_get_contents('php://input');
    echo $data;
?>
```

**Comment by KimberleeDArmstrong** [comment]
Awesome!  Got it!  Thanks!

**Comment by IAmDragon** [comment]
@christocracy We just talked on live chat. Laravel's Request feature pulls data from the body with Request::post, so it should still work

**Comment by christocracy** [comment]
The plugin logging http requests.  Are you observing the plugin logs?

**Comment by Muralilive** [comment]
startBackgroundGeolocation() {
    this.device = (<any>window).device;
    console.log("device information",this.device);
    BackgroundGeolocation.onLocation(this.onLocation.bind(this));
    BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
    BackgroundGeolocation.onHeartbeat(this.onHeartbeat.bind(this));
    BackgroundGeolocation.onGeofence(this.onGeofence);
    BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
    BackgroundGeolocation.onProviderChange(this.onProviderChange.bind(this));
    BackgroundGeolocation.onGeofencesChange(this.onGeofencesChange);
    BackgroundGeolocation.onSchedule(this.onSchedule);
    BackgroundGeolocation.onPowerSaveChange(this.onPowerSaveChange.bind(this));
    BackgroundGeolocation.onConnectivityChange(this.onConnectivityChange.bind(this));
    BackgroundGeolocation.onNotificationAction(this.onNotificationAction);
    BackgroundGeolocation.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this))
    let location:any;
    BackgroundGeolocation.ready({
      // Geolocation config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,  // <-- highest possible accuracy
      distanceFilter: this.distanceFilter,
      // ActivityRecognition config
      stopTimeout: this.stopTimeout,
      // Application config
      foregroundService: true,
      stopOnTerminate: this.stopOnTerminate,
      enableHeadless: true,
      heartbeatInterval: 60,
      // HTTP / Persistence config
      url: config.SERVICE_API + config.UPD_LOC, 
      headers: {
        'authorization': 'Bearer ' + this.user.access_token,
      },
      httpTimeout : 10000,
      method : 'POST',  
      httpRootProperty: '.',
      locationTemplate: '{"u_lat":<%= latitude %>,"u_lng":<%= longitude %>}',
      params: {
        'u_id':this.user.userid,
        'u_radius':this.radius
      },
      autoSync: this.autoSync,
      batchSync : true,
      forceReloadOnGeofence: true,
      geofenceModeHighAccuracy: true,
      geofenceProximityRadius: 500,
      autoSyncThreshold: 0,
      notification: {
        title: 'cordova-background-geolocation',
        text: 'Tracking engaged'
      },
      // Logging / Debug config
      debug: this.debug,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      schedule: [this.scheduleTime],
      scheduleUseAlarmManager: true
    }, (state) => {
      console.log('- BackgroundGeolocation ready: ', state);
      // Set current plugin state upon our view.
      BackgroundGeolocation.startGeofences().then(() => {
        BackgroundGeolocation.startSchedule();
      });
      BackgroundGeolocation.getLog((log) => {
        console.log('[log] success: ', log);
      });
      this._ngZone.run(() => {
        this.enabled = state.enabled;
        this.isMoving = state.isMoving;
        this.autoSync = state.autoSync;
        this.distanceFilter = state.distanceFilter;
        this.stopTimeout = state.stopTimeout;
        this.stopOnTerminate = state.stopOnTerminate;
        this.startOnBoot = state.startOnBoot;
        this.debug = state.debug;
       
        

      });
    })

  }

Invalid request Error
How to include this format ?
{
  'u_id' : 1
  'u_radius':200,
'u_lat':12.234,
'u_lng':50.23423
}
Please advice..
