### ISSUE TITLE
Support for while using mode

### ISSUE THREAD

**Issue by wedgybo** [transistorsoft/cordova-background-geolocation-lt#20]
I'm just wondering if there is a mode where you can enable the tracker to only function while the app is in use. For some apps always is a bit overkill. I read through the docs but couldn't see anything.

**Comment by christocracy** [comment]
This plugin is called background geolocation for a reason :)

If you want to do fg geolocation, use the standard
Cordova-plugin-geolocation plugin.

On Wednesday, October 14, 2015, Jamie Sutherland <notifications@github.com>
wrote:

> I'm just wondering if there is a mode where you can enable the tracker to
> only function while the app is in use. For some apps always is a bit
> overkill. I read through the docs but couldn't see anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/20>
> .
>


-- 
Snet form Gmail Mobile

**Comment by wedgybo** [comment]
Fair play :D
