### ISSUE TITLE
config.xml

### ISSUE THREAD

**Issue by cissemy** [transistorsoft/cordova-background-geolocation-lt#200]
Hi,
 I added 
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="my id here" version="1.0" versionCode="1">
 <preference name="cordova-background-geolocation-license" value="my key here" />
 <gap:plugin name="https://github.com/transistorsoft/cordova-background-geolocation.git" source="npm" />
 to my config.xml.
When i submit the  app  to build.phonegap.com i get an error  .
I had to replace  <gap:plugin name="https://github.com/transistorsoft/cordova-background-geolocation.git" source="npm" /> by  <gap:plugin name="https://github.com/transistorsoft/cordova-background-geolocation-lt.git" source="npm" /> for it to work .
Why ?

**Comment by christocracy** [comment]
See [markdown guide](https://guides.github.com/features/mastering-markdown/) to learn how to highlight code.

**Comment by christocracy** [comment]
You are a customer.  Post issues in premium repo.
