### ISSUE TITLE
Application stop for the first launch

### ISSUE THREAD

**Issue by cissemy** [transistorsoft/cordova-background-geolocation-lt#201]
Hi,
I made a test app.For some reason it stop working the first time i launch the app.
Only works in the second launch.
Here the code :

window.Application3 = window.Application3 || {};

$(function() {
    // Uncomment the line below to disable platform-specific look and feel and to use the Generic theme for all devices
    // DevExpress.devices.current({ platform: "generic" });
    // To customize the Generic theme, use the DevExtreme Theme Builder (http://js.devexpress.com/ThemeBuilder)
    // For details on how to use themes and the Theme Builder, refer to the http://js.devexpress.com/Documentation/Guide/#themes article

   
    function onDeviceReady() {
            navigator.splashscreen.hide();
        if(window.devextremeaddon) {
            window.devextremeaddon.setup();
        }
        $(document).on("backbutton", function () {
            DevExpress.processHardwareBackButton();
        });

        var bgGeo = window.BackgroundGeolocation;
        bgGeo.configure({
            // Geolocation config
            desiredAccuracy: 0,
            stationaryRadius: 50,
            distanceFilter: 50,
            disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
            locationUpdateInterval: 5000,
            minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change 
            fastestLocationUpdateInterval: 5000,
            activityRecognitionInterval: 10000,
            stopDetectionDelay: 1,   // [iOS] delay x minutes before entering stop-detection mode
            stopTimeout: 2,  // Stop-detection timeout minutes (wait x minutes to turn off tracking)
            activityType: 'AutomotiveNavigation',

            // Application config
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user) 
            forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user) 
            forceReloadOnGeofence: true,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user) 
            stopOnTerminate: false,              // <-- Don't stop tracking when user closes app.
            startOnBoot: true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.

        }, function (state) {
            // Plugin is configured and ready to use.
            if (!state.enabled) {
                bgGeo.start();  // <-- start-tracking
              
            }
        });
        var callbackFn = function (location, taskId) {
            var coords = location.coords;
            var lat = coords.latitude;
            var lng = coords.longitude;
            var msg = 'lat :' + lat + "  lng : " + lng;
            // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
            // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
           
            setTimeout(function () {
                bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
            }, 1000);
        };

        var failureFn = function (error) {
            showToast('toast', 'failurFn : BackgroundGeoLocation error', 'error'); 
        }
        bgGeo.watchPosition(function (location) {
            showToast('toast', '- Watching position: ', 'success');
        }, function (error) {
            showToast('toast', '- Watching position: ', 'error'); 
        }, {
            interval: 60000,      // Get a location every 30s
            persist: true,        // default is true
            extras: {  }  // optional meta-data applied to each location
        });
        // Listen to location event
        bgGeo.on('location', callbackFn, failureFn);
        
        
    }
    document.addEventListener("deviceready", onDeviceReady, false);
    function onNavigatingBack(e) {
        if (e.isHardwareButton && !Application3.app.canBack()) {
            e.cancel = true;
            exitApp();
        }
    }
    window.onerror = function (errorMsg, url, lineNumber) {
        alert('Error: ' + errorMsg + ' Script: ' + url + ' Line: ' + lineNumber);
    }
    function exitApp() {
        switch (DevExpress.devices.real().platform) {
            case "android":
                navigator.app.exitApp();
                break;
            case "win":
                window.external.Notify("DevExpress.ExitApp");
                break;
        }
        bgGeo.stopWatchPosition();
        if (state.enabled) {
            bgGeo.stop();

        }
    }
    var showToast = function (id, msg, type) {
        $("#" + id).empty();
        var instance = $("#" + id).dxToast({
            message: msg,
            type: type,
            displayTime: 5000
        }).dxToast('instance');
        if (instance != 'undefined' && instance != null) { instance.show(); }

    }
    //DevExpress.ui.notify('ERROR -> MSG:' + e.msg, 'error', 1000);
    Application3.app = new DevExpress.framework.html.HtmlApplication({
        namespace: Application3,
        layoutSet: DevExpress.framework.html.layoutSets[Application3.config.layoutSet],
        navigation: Application3.config.navigation,
        commandMapping: Application3.config.commandMapping
    });
    Application3.app.router.register(":view/:id", { view: "home", id: undefined });
    Application3.app.on("navigatingBack", onNavigatingBack);
    Application3.app.navigate();
});

Thanks

**Comment by christocracy** [comment]
You are a customer.  You don't use this *free* repo anymore.  You use the premium repo now.
