### ISSUE TITLE
iOS plugin running forever

### ISSUE THREAD

**Issue by cincaw** [transistorsoft/cordova-background-geolocation-lt#204]
Hi, is it possible for this plugin to run forever even the app has been swiped away from task manager?
How to make javascript always run even the app has been closed from task manager?
Thanks

**Comment by christocracy** [comment]
When the user terminates the app, your app (and your javascript) will terminate.

However, if you've configured `stopOnTerminate: false`, the plugin continues to monitor a "stationary geofence" around the device's last known position.  iOS **does** persist geofence monitoring *in spite of app termination*.  When the device travels out of that "stationary geofence", iOS re-awakens the app **in the background** and your Javascript app re-boots.  The user is not aware of your app rebooting in the background.

In addition, the plugin also engages the "background-fetch" API.  This api typically fires about every 15min (typically).  Just like geofences, iOS also persists background-fetch listeners.  If the user terminates the app with `stopOnTerminate: false`, eventually a background-fetch event will reboot your app in the background.
