### ISSUE TITLE
about localization 

### ISSUE THREAD

**Issue by 99226369** [transistorsoft/cordova-background-geolocation-lt#205]
Hi,How can I display  "Background location is not enabled ......" in Chinese?
![c28b5a45-7ddb-4097-96f8-3822b8c1281e](https://cloud.githubusercontent.com/assets/22812124/19430334/73482260-9486-11e6-98e7-bdfc7a7a2fcd.png)

**Comment by christocracy** [comment]
https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#param-object-locationauthorizationalert

**Comment by 99226369** [comment]
@christocracy thanks a lot.I do as you suggest,and my app works well.
