### ISSUE TITLE
is the plugin legal and accepted with apple rules for production the app ? 

### ISSUE THREAD

**Issue by int3rnet** [transistorsoft/cordova-background-geolocation-lt#207]
Hello 

i tried to find an answer for this question before i purchase the plugin but i couldn't find any thing 

i loved the plugin so much but my concerns is the following 

apple team very restricted with locations and the plugin work all the time in background , is it against their rules ?!

i don't wanna pay for the plugin then use it in my app and the apple team refused to upload it in the market (app store )

is there any guarantee about apple rules ? 

thank you

**Comment by christocracy** [comment]
The plugin completely operates within the Apple guidelines.  It is 100% acceptable, assuming Apple deems your app *deserves* background location updates.  

If you're making an Alarm clock app, you'll be denied.  If you're making any kind of fleet tracking app, youre 100% ok

**Comment by int3rnet** [comment]
thank you sir for the fast response 👍 

the three two question is :

1 - to stop tracking the phone just use #stop ?! and that will stop the plugin to work ?!

2 - if i quit the application , the tracking will still working ? what about if i sent the data to server , can i capture everything even if it's quite ? 

3 - is there any less price for the plugin ? i am an start up and the cost is bit expensive for me

**Comment by christocracy** [comment]
1. yes.  `#start` / `#stop` are like the power button of the plugin.
2. If you configure `stopOnTerminate: false`, the plugin will continue to track.  You should provide an `#url` to the plugin and let it take care of HTTP requests for you.
3. Sorry, no.  The price is firm.
