### ISSUE TITLE
Update Location after Moving from place after stopTimeout has been reached.

### ISSUE THREAD

**Issue by micho777** [transistorsoft/cordova-background-geolocation-lt#209]
some devices(android marshmallow and iOS 10.0.2) are taking much longer time (sometimes doesn’t at all) to update location after moving from a place (after the stopTimeout is reached).

i tried :
```
bgGeo.onHeartbeat(function (params) {
           bgGeo.getCurrentPosition(function (location, taskId) {
               bgGeo.finish(taskId);
               num_geolocation_latitude = location.coords.latitude;
               num_geolocation_longitude = location.coords.longitude;
           });
       });
```
but still after the stopTimeout is reached, am not receiving any url post (since the url is configurable) 

is there a better way to get location after leaving a specific place when reaching stopTimeout ?

**Comment by christocracy** [comment]
Have you read the [Behaviour]https://github.com/transistorsoft/cordova-background-geolocation-lt#behaviour) section in README?

Post logs.

**Comment by micho777** [comment]
there was an error blocking the app in the background. nothing related to the plugin. thank you.
