### ISSUE TITLE
Too many Permission

### ISSUE THREAD

**Issue by Loda** [transistorsoft/cordova-background-geolocation-lt#212]
Hi ,

Before all, thanks for this very nice plugin. It is a nice project.

We try to use only **useSignificantChangesOnly** to avoid the UIbackgroundMode-location apple store policy issue.

but when we compile the ipa, the info.plist contain the UiBackgroundMode location and fetch.

**How can I remove these permission ?**

info.plist extract:

`<key>UIBackgroundModes</key>
    <array>
      <string>fetch</string>
      <string>location</string>
    </array>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>App requires background location tracking</string>
    <key>NSMotionUsageDescription</key>
    <string>Accelerometer use increases battery efficiency by intelligently toggling location-tracking</string>`

plugin config:

 bgGeo.configure({
         // Geolocation config
            locationAuthorizationAlert: {
              titleWhenNotEnabled: "Hi, location-services not enabled",
              titleWhenOff: "Hi, location-services OFF",
              instructions: "You must enable 'Always' in location-services, buddy",
              cancelButton: "Cancel",
              settingsButton: "Settings"
            },
          desiredAccuracy: 0,
          distanceFilter: 10,
          stationaryRadius: 50,
          locationUpdateInterval: 1000,
          fastestLocationUpdateInterval: 5000,
          useSignificantChangesOnly: true,
          //heartbeatInterval: 60,
          foregroundService: false,
          preventSuspend: false,
          // Activity Recognition config
          activityType: "OtherNavigation",
          activityRecognitionInterval: 5000,
          stopTimeout: 5,
          // Application config
          debug: false, //switch to false in pro and remove sound capabilities
          stopOnTerminate: false,
          startOnBoot: true,
          // HTTP / SQLite config
          url: "http://192.168.1.23:8080/locations",
          method: 'POST',
          autoSync: true,
          maxDaysToPersist: 1,
          headers: {
              "type": "local"
          },
          params: {
              "auth_token": "maybe_your_server_authenticates_via_token_YES?"
          }
      }, function(state) {
          // This callback is executed when the plugin is ready to use.
          console.log('BackgroundGeolocation ready: ', state);
          if (!state.enabled) {
              bgGeo.start();
          }
      });

`"name": "cordova-plugin-geolocation",
 "version": "2.1.0",`

see also #210

**Comment by christocracy** [comment]
When you:
```
cordova plugin add cordova-background-geolocation-lt
```
The plugin automatically add [`UIBackgroundMode location`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L34) to your `.plist`.  You have to manually remove it.

In XCode, you can do this simply by disabling:
[x]Location Updates
![](https://www.dropbox.com/s/eb3yptkuaz41h7w/Screenshot%202016-11-09%2011.37.22.png?dl=1)

**Comment by Loda** [comment]
thanks man for the quick answer.

with my setup, the info.plist is overwritten at each compilation. 

do you experience the same behavior ?


so, to manually remove the permission, I would need to : 
-  compile the ipa
- manually edit the info.plist
- open the generated xcode project
- manually compile the xcode project

also, the plugin seem to not work when we removed manually the permission.
 Maybe I need to walk more. (i will try again tomorrow.)

**Comment by christocracy** [comment]
I'm not sure the specific steps you have to take but you need to ensure that you **don't** submit your `.plist` containing the key `UIBackgroundMode location`.

Obviously, you're going to receive fewer location updates.  You probably have to travel up to `1000` meters before a location is recorded.  `distanceFilter` and `desiredAccuracy` are ignored with `useSignificantChangesOnly`.

**Comment by Loda** [comment]
ok.

so i need to do it manually.

thanks for your help.

I will give you more feedback tomorrow.

**Comment by Loda** [comment]
at the end, we keep the permission, because it seem that without it, we don't receive event when the app is killed.

thanks for your help.
