### ISSUE TITLE
How to change NSLocationAlwaysUsageDescription value?

### ISSUE THREAD

**Issue by chris087** [transistorsoft/cordova-background-geolocation-lt#214]
How to change the plist value  " NSLocationAlwaysUsageDescription " 

Its evertime overwritten when I do: cordova prepare with the default one from plugin.xml

When I change the value in in plugin.xml and save, and do again : cordova prepare. still the old values become in plist!

Please help.

**Comment by chris087** [comment]
this is also not working:

    

>     <platform name="ios">
>         <config-file platform="ios" parent="NSLocationAlwaysUsageDescription">
>             <array>
>                 <string>test</string>
>             </array>
>         </config-file>
> ...

**Comment by chris087** [comment]
no answer in 14 hours. OMG! this is maybe the simplest thing there is.

**Comment by christocracy** [comment]
You'll have to manage your post on your own.  Make a hooks script
