### ISSUE TITLE
tracking stopped on Android Marshmallow, while app is in the background

### ISSUE THREAD

**Issue by micho777** [transistorsoft/cordova-background-geolocation-lt#215]
Geotracking is stopped after being in background for more than 1 hr, (Android Marshmallow). logs are attached. 
PS: the datetime of the log entries are the same on most of the records within the same second any reason why?!
the tracker has stopped from 2016-11-11 13:31:57.770 till 2016-11-11 12:03:03.697
where the device was on the move.
[logs.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/585868/logs.txt)

**Comment by micho777** [comment]
tested another scenario, 
am getting a lot of:
11-11 15:37:15.158 24683 24747 I TSLocationManager: ? LocationService: location
11-11 15:37:15.188 24683 24747 W TSLocationManager: ? LocationService found nobody to talk to.  Stopping...
11-11 15:37:17.278 24683 24777 D EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
11-11 15:37:17.278 24683 24777 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
11-11 15:37:25.938 24683 24888 D EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
11-11 15:37:25.938 24683 24888 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
11-11 15:37:31.138 24683 24940 D EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
11-11 15:37:31.138 24683 24940 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
11-11 15:37:36.338 24683 24993 D EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
11-11 15:37:36.338 24683 24993 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
11-11 15:37:44.948 24683 25040 D EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
11-11 15:37:44.948 24683 25040 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
11-11 15:37:46.218 24683 25051 I TSLocationManager: ? LocationService: location
11-11 15:37:46.228 24683 25051 W TSLocationManager: ? LocationService found nobody to talk to.  Stopping...
11-11 15:37:50.178 24683 25069 D EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
11-11 15:37:50.178 24683 25069 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent

and some:
11-11 15:40:03.498 24683 26069 I TSLocationManager: HttpService is busy

**Comment by christocracy** [comment]
@see [`foregroundService`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-boolean-foregroundservice-false).

these log-entries are unimportant:
```
11-11 15:37:25.938 24683 24888 D EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
```

They will be happy again once Android reboots the service (which was killed by the OS due to memory pressure).  Android automatically reboots services it killed.

If you want to avoid the OS interrupting the plugin's tracking service, simply configure `foregroundService: true`.

**Comment by micho777** [comment]
what if i don't want to show notifications to the user?? "supplying the ongoing notification to be shown to the user while in this state"
and i don't want the app to stop even if its in the background for a long time? any configuration for that?

**Comment by christocracy** [comment]
You have **no choice**.  If you want uninterrupted tracking as an Android ["Foreground Service"](https://developer.android.com/reference/android/app/Service.html#startForeground(int, android.app.Notification)), the OS *requires* the notification.

>Make this service run in the foreground, supplying the ongoing notification to be shown to the user while in this state. By default services are background, meaning that if the system needs to kill them to reclaim more memory (such as to display a large page in a web browser), they can be killed without too much harm. You can set this flag if killing your service would be disruptive to the user, such as if your service is performing background music playback, so the user would notice if their music stopped playing.

There is **no** alternative.
