### ISSUE TITLE
How to pause geotracking for X seconds

### ISSUE THREAD

**Issue by chris087** [transistorsoft/cordova-background-geolocation-lt#216]
Is there a possiblitly to pause the geotracking for x seconds. then auto reenable.

**Comment by christocracy** [comment]
Once you call `#stop`, iOS will automatically put your app to sleep once it enters the background.  Only a stationary-exit or background-fetch (typically every 15min) will re-awaken it.

What is your use-case?

**Comment by christocracy** [comment]
Closed for lack of feedback.
