### ISSUE TITLE
Do not getting same response of location

### ISSUE THREAD

**Issue by manojmeshram** [transistorsoft/cordova-background-geolocation-lt#218]
## Your Environment
* Plugin version:2.1.6.pre
* Platform: iOS or Android
* OS version: IOS 9.3 and above and Android 5 and above
* Device manufacturer / model: IPhone 6 and Samsung s6
* Cordova version (`cordova -v`): 6
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior

Location response should be same. 
## Actual Behavior

as per my observation , after configuring plugin first time we receive location on server. But  response from android and and IOS are different.
In android response we are getting location array but in IOS response we got location object. As per expectation we should get same response. please see the response in below line. 

 
Response from IOS
 
{
                "location": {
                                "odometer": 0,
                                "is_moving": false,
                                "battery": {
                                                "level": 0.79,
                                                "is_charging": true
                                },
                                "coords": {
                                                "altitude": 301.469482421875,
                                                "speed": -1,
                                                "heading": -1,
                                                "altitudeAccuracy": 10,
                                                "accuracy": 65,
                                                "latitude": 21.08429124289254,
                                                "longitude": 79.08442954246971
                                },
                                "extras": {
                                                "customerid": "20",
                                                "employeeid": 851,
                                                "uuid": "FC63545C-7399-4ED3-A086-FE911DDC30DC"
                                },
                                "is_heartbeat": false,
                                "timestamp": "2016-11-17T06:17:51.431Z",
                                "event": "motionchange",
                                "activity": {
                                                "type": "unknown",
                                                "confidence": 100
                                },
                                "uuid": "9A2198DF-6478-442F-992F-99BA3CCFB3AC"
                }
}
 
Response From ANDROID
 
{
                "location": [ {
                                "odometer": 0,
                                "is_moving": false,
                                "battery": {
                                                "level": 0.79,
                                                "is_charging": true
                                },
                                "coords": {
                                                "altitude": 301.469482421875,
                                                "speed": -1,
                                                "heading": -1,
                                                "altitudeAccuracy": 10,
                                                "accuracy": 65,
                                                "latitude": 21.08429124289254,
                                                "longitude": 79.08442954246971
                                },
                                "extras": {
                                                "customerid": "20",
                                                "employeeid": 851,
                                                "uuid": "FC63545C-7399-4ED3-A086-FE911DDC30DC"
                                },
                                "is_heartbeat": false,
                                "timestamp": "2016-11-17T06:17:51.431Z",
                                "event": "motionchange",
                                "activity": {
                                                "type": "unknown",
                                                "confidence": 100
                                },
                                "uuid": "9A2198DF-6478-442F-992F-99BA3CCFB3AC"
                } ]
}

## Steps to Reproduce

I am using below code 
	configObj={
	url: this.generalConstant.applicationUrl+this.generalConstant.addLocations,
	desiredAccuracy: -1,
	stopDetectionDelay: 0,
	activityRecognitionInterval: 0,
	distanceFilter: 0,
	activityType: 'OtherNavigation',
	useSignificantChangesOnly: false,
	autoSync: true,
	maxDaysToPersist: 7,
	stopTimeout: 0,
	batchSync: true,
	maxBatchSize: 10,
	disableElasticity: true,
	stationaryRadius: 20,
	stopOnTerminate: false,
	deferTime: 0,
	heartbeatInterval: 10,
	preventSuspend: false,
	pausesLocationUpdatesAutomatically: false,
	//autoSyncThreshold: 0,
	//debug: true,
	//locationTimeout: 60,
	logLevel: 5,
	//disableMotionActivityUpdates: false,
	locationUpdateInterval: (180000),
	fastestLocationUpdateInterval: (180000),
	extras: {
		employeeid: 1,
		customerid: 7,
		uuid: 123456
	},
	schedule: scheduleArray
};
try{
	this.bgService.configure(this.configObj,
	function(state){
		console.log('Before');//StarttheSchedulerif(!state.enabled){
			console.log('after');self.startScheduler();
		}
	});
}catch(e){
	console.log('Errorfromtrycatchis'+e);
}

**Comment by christocracy** [comment]
This Free version repo does not contain version 2.1.16.pre.  If you're a customer, do not use the free repo
