### ISSUE TITLE
Problem with license

### ISSUE THREAD

**Issue by alexandreafc** [transistorsoft/cordova-background-geolocation-lt#219]
* Plugin version: 2.1.0
* Platform: iOS or Android
* OS version: Android 6.0 and 6.1 / iOS 9 and iOS 10

Actual Behavior
Hi I'm trying to use plugin but I receive the message bellow: License Validation Failure 

Can you help me? I thought I was using the free version of the component.

**Comment by christocracy** [comment]
Free version is for use with iOS only.  Use of Android requires [purchasing a license](http://www.transistorsoft.com/shop/products/cordova-background-geolocation).

You may try Android by building the Sample App
