### ISSUE TITLE
how to get BG service to execute callbacks when app is closed?

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#222]
When app is closed no callbacks are executed. Is there a hook for code(native?) to be executed for the various #on events?

For example, say I want to add an extra parameter to each HTTP POST such as the user's local time when location was obtained, or do some basic data processing etc.

**Comment by christocracy** [comment]
Your Cordova app *will* be terminated when the user wants to close the app.  You cannot prevent that.

The key with `stopOnTerminate: false` is that iOS will *reboot* your app in the background when the device moves out of the `stationaryRadius` (or a background-fetch event occurs, typically every 15min).

Watch [this video](https://www.youtube.com/watch?v=rFNDIQLEouo&t=32s) where I demonstrate `stopOnTerminate` behaviour in the sim.

Why would you care about "user's local time"??  You have the `timestamp`, just set the timezone in the `#params`.  Presumably, your server would already know something about your users' timezone/locale when you register them to your app.

**Comment by christocracy** [comment]
And btw, the `iSSUE_TEMPLATE` is there for a reason, not to be ignored.  You should post your config and platform information **at least**

**Comment by christocracy** [comment]
![](https://www.dropbox.com/s/3c8o8l49lb8cpad/Screenshot%202016-11-26%2011.50.13.png?dl=1)

**Comment by JohnyBoy1234** [comment]
the timestamp is UTC, but the user may be travelling across timezones and the schedule is in the user's local timezone no? so one day it may run at 8pm UTC, the next day at 9pm UTC right?

**Comment by christocracy** [comment]
Your question is "how to get BG service to execute callbacks when app is closed".  That has been answered.  If you have un-related questions, post a detailed question in a new issue.
