### ISSUE TITLE
What timezone is the schedule in?

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#224]
If I configure a schedule that runs everyday between 10:00-17:00 but then the user travels to another timezone, does the schedule keep running 10:00-17:00 in the user's new local time or will it keep running on the old timezone time?

    Plugin version: 2.2.0
    Platform: Android
    OS version: 5.1.1
    Device manufacturer / model: Nexus 4
    Cordova version (cordova -v): 6.4.0
    Cordova platform version (cordova platform ls): android 6.0.0
    Plugin config
    startOnBoot: true
    stopOnTerminate: false
    foregroundService: true

**Comment by christocracy** [comment]
The Scheduler schedules items one-at-time, selecting the most recent schedule found.  The schedule time is based upon the current time of the device.

A time-zone change on the device should properly cause the currently schedule Alarm to fire correctly.
