### ISSUE TITLE
"BgGeo.finish (taskId)" missing in various functions.

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#225]
CallbackFn must be terminated with bgGeo.finish(taskId). And the failureFn ??
&nbsp; Because failureFn are also running in the background, and can also have a long runtime because they have scripts added by us.
Strangely I also realized that successful functions in "onHeartbeat" (in the docs) are also without "bgGeo.finish(taskId)", which leads me to believe that they can also be unexpectedly interrupted by the operating system, especially being added scripts with long Runtime, even in these functions of success.

**Comment by christocracy** [comment]
Heartbeat doesn't  require a `bgTask` since the core mechanism of iOS `preventSuspend` operates by requesting a background-task, which is managed internally and "refreshed" as necessary.

Not strange at all.

I will add a method to the Javascript API `#startBackgroundTask`, `#stopBackgroundTask` so you can manually manage your own at will.

**Comment by christocracy** [comment]
In fact, I may just remove `bgTask` from all iOS callbacks and simply leave it up to developers to:

```Javascript
bgGeo.startBackgroundTask(function(taskId) {
  doLongRunningOperation(function() {
    bgGeo.finish(taskId);
  });
});
```

**Comment by dbessa1** [comment]
These issues came to my mind because in my app, I need to periodically get an update of some geofences change variables. This update comes from my web server that takes some time to deliver me the update. So I planned to create "onHeartbeat" events to periodically request the update. And to force iOS to expect such an update, I thought about creating a "window.setTimeout" of about 15 seconds before sending the "bgGeo.finish (taskId)" statement. This way I could force iOS to wait for the update before going back to sleep until the next "onHeartbeat" event or other events. But since the "onHeartbeat" event does not have "bgGeo.finish (taskId)", then I was thinking: "I understood that iOS might go back to sleep before I get the update from the server."

**Comment by christocracy** [comment]
When you use iOS `preventSuspend: true` (the only way to enabled `heartbeat` events), iOS will **not** suspend your app **at all**.

There's no need for background-tasks in this mode -- the plugin itself has registered a background-task in this mode.

While in `preventSuspend` mode, your javascript is running 24/7.

```
bgGeo.on('heartbeat', function(params) {
  console.log('- heartbeat');
});
bgGeo.configure({preventSuspend: true}, function(state) {
   // This is going to run every second forever.  It will never stop or be suspended while preventSuspend: true
  setInterval(function() {
    console.log('- tick');
  }, 1000);
});
```

**Comment by dbessa1** [comment]
Many thanks for the clarification!
Would it be possible to do the same on Android, have the javacript run 24/7 with the screen off / without bringing the app to the foreground?

**Comment by christocracy** [comment]
You should keep your processing limited to the `heartbeat` callback.

There's no guarantee that Android won't put your Javascript to sleep while the plugin is in **stationary** mode.

The `heartbeat` event is guaranteed to fire according to your configured `heartbeatInterval`.  Android uses `AlarmManager` for this, basically a repeating alarm that will always wake up your app.

The iOS example above, where I put a `setInterval` within the `#configure` callback was just an example.  Don't do that.  Keep all your background processing limited to the `heartbeat` event callback.

**Comment by dbessa1** [comment]
My app is useful to my users for a critical function that can not fail. Would it be that if I turn on the aggressive mode, would there be a guarantee that OS (android / iOS) will not interrupt my app?

**Comment by dbessa1** [comment]
... even when the user is standing (estacionay).

**Comment by christocracy** [comment]
>Would it be that if I turn on the aggressive mode, would there be a guarantee that OS (android / iOS) will not interrupt my app?

iOS and Android will **never** suspend your app when location-services are engaged.

**Comment by christocracy** [comment]
Btw, I've implemented `startBackgroundTask` for iOS in the Premium Version.  I plan to completely remove `taskId` from all callbacks, leaving it up to the developer to manage their own background-tasks.

I'm not sure when I'll merge it to the free version here.

```Javascript
bgGeo.on('location', function(location) {
  bgGeo.startBackgroundTask(function(taskId) {
    performLongRunningTask(function() {
      bgGeo.finish(taskId);
    });
  });
});
```

**Comment by jbfrequence** [comment]
Ok thanks. I will use LOG_LEVEL_OFF in my production config and keep them in development phase
