### ISSUE TITLE
The documentation for disableMotionActivityUpdates is backward

### ISSUE THREAD

**Issue by vijayb** [transistorsoft/cordova-background-geolocation-lt#226]
To turn off the permission alert it should be set to true, not false. Also this attribute should have documentation saying how important it is to battery saving so it's only turned off in critical circumstances.

**Comment by christocracy** [comment]
Fixed in [premium version](http://www.transistorsoft.com/shop/products/cordova-background-geolocation)

**Comment by vijayb** [comment]
Doesn't look like this is fixed. It's still wrong in the table. Also, you
misspelled "disable" as isable. I think a note about the importance of this
would also be useful since you've emphasized that to me in chat

**Comment by christocracy** [comment]
LIke I said, fixed in **Premium Version**.  This repo where we're talking now is the **Free Version**.

If you're a customer, you should not be using this repo **at all**.

![](https://www.dropbox.com/s/vxtdr6ru56apfj5/Screenshot%202016-12-05%2016.37.26.png?dl=1)
