### ISSUE TITLE
Schedule is broken/unreliable

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#227]
When defining multiple schedules, it seems that their order matters. For example ["2,3,4,5,6 01:39-10:39", "2,3,4,5,6 11:59-21:53"] works but the reverse order ["2,3,4,5,6 11:59-21:53", "2,3,4,5,6 01:39-10:39"] does not. It seems they have to be in some sort of chronological order or plugin does not work.

## Your Environment
Plugin version: 2.2.0
Platform: Android
OS version: 5.1.1
Device manufacturer / model: Nexus 4
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): android 6.0.0
Plugin config
startOnBoot: true
stopOnTerminate: false
foregroundService: true

**Comment by christocracy** [comment]
Do you have some logs.  The scheduler is very verbose about what it's doing.

**Comment by christocracy** [comment]
"Broken / unreliable" seems a bit dramatic.

**Comment by christocracy** [comment]
But yes, the Schedule parser will pick out the first matching schedule it finds but doesn't order the times.  That is easily fixed.

**Comment by christocracy** [comment]
Fixed in premium repo.

**Comment by christocracy** [comment]
**Configured**
```
'1-7 11:44-11:45',
'1-7 11:42-11:43',
'1-7 11:40-11:41'
```
**Parsed**
11-29 11:38:37.035  6940  7012 I TSLocationManager: ╔═════════════════════════════════════════════
11-29 11:38:37.035  6940  7012 I TSLocationManager: ║ 🎾  Scheduler ON
11-29 11:38:37.035  6940  7012 I TSLocationManager: ╠═════════════════════════════════════════════
11-29 11:38:37.035  6940  7012 I TSLocationManager: ╟─ Schedule[11:40-11:41, Days: [1, 2, 3, 4, 5, 6, 7]]
11-29 11:38:37.035  6940  7012 I TSLocationManager: ╟─ Schedule[11:42-11:43, Days: [1, 2, 3, 4, 5, 6, 7]]
11-29 11:38:37.035  6940  7012 I TSLocationManager: ╟─ Schedule[11:44-11:45, Days: [1, 2, 3, 4, 5, 6, 7]]
11-29 11:38:37.035  6940  7012 I TSLocationManager: ╚═════════════════════════════════════════════
```

**Comment by JohnyBoy1234** [comment]
For example at current time 11:36, the scheduler should (be started) or at least schedule to start at 11:38 but instead it schedules 13:51

D/TSLocationManager(30332): $ startSchedule()
I/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
I/TSLocationManager(30332): ╔═════════════════════════════════════════════
I/TSLocationManager(30332): ║ ������  Scheduler ON
I/TSLocationManager(30332): ╠═════════════════════════════════════════════
I/TSLocationManager(30332): ╟─ Schedule[13:51-22:29, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╟─ Schedule[03:50-09:22, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╟─ Schedule[02:26-14:00, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╟─ Schedule[11:38-17:52, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╚═════════════════════════════════════════════
D/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
D/TSLocationManager(30332):   ������  Day #3: Searching schedule for alarms...
I/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
I/TSLocationManager(30332):   ������  Scheduled Alarm: ON at 13:51 on Tuesday



In this example at 11:41 it schedules to start at 18:16 but it should be started now according to the 3rd schedule

D/TSLocationManager(30332): $ startSchedule()
I/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
I/TSLocationManager(30332): ╔═════════════════════════════════════════════
I/TSLocationManager(30332): ║ ������  Scheduler ON
I/TSLocationManager(30332): ╠═════════════════════════════════════════════
I/TSLocationManager(30332): ╟─ Schedule[03:50-09:22, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╟─ Schedule[18:16-22:29, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╟─ Schedule[10:23-17:52, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╚═════════════════════════════════════════════
D/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
D/TSLocationManager(30332):   ������  Day #3: Searching schedule for alarms...
I/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
I/TSLocationManager(30332):   ������  Scheduled Alarm: ON at 18:16 on Tuesday



If I modify the first schedule, then it correctly detects it should be started now

D/TSLocationManager(30332): $ startSchedule()
I/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
I/TSLocationManager(30332): ╔═════════════════════════════════════════════
I/TSLocationManager(30332): ║ ������  Scheduler ON
I/TSLocationManager(30332): ╠═════════════════════════════════════════════
I/TSLocationManager(30332): ╟─ Schedule[03:50-13:59, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╟─ Schedule[18:16-22:29, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╟─ Schedule[10:23-17:52, Days: [2, 3, 4, 5, 6]]
I/TSLocationManager(30332): ╚═════════════════════════════════════════════
D/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
D/TSLocationManager(30332):   ������  Day #3: Searching schedule for alarms...
D/TSLocationManager(30332): [c.t.l.s.TSScheduleManager a]
D/TSLocationManager(30332):   ������  Scheduler says we should be ENABLED but we are NOT

**Comment by JohnyBoy1234** [comment]
I said 'broken/unreliable' because depending on how a user sets up an initial schedule, it may not work and if he adds another schedule to start in a minute(to test it) it may also not work...
