### ISSUE TITLE
Disable local push notifications in app?

### ISSUE THREAD

**Issue by Kestanous** [transistorsoft/cordova-background-geolocation-lt#23]
Trying this out with iOS. In a case where a user says they want notifications, we would like to give them the option to disable them in app. Is that possible? Alternatively can we disable them outright?

**Comment by christocracy** [comment]
The notification are purely for you, the developer.  They only appear when
debug:true

On Wednesday, October 21, 2015, Sivli Kestanous <notifications@github.com>
wrote:

> Trying this out with iOS. In a case where a user says they want
> notifications, we would like to give them the option to disable them in
> app. Is that possible? Alternatively can we disable them outright?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/23>
> .
>


-- 
Snet form Gmail Mobile

**Comment by Kestanous** [comment]
Doh! Awesome, thank you.
