### ISSUE TITLE
Licence error on Android?

### ISSUE THREAD

**Issue by chris087** [transistorsoft/cordova-background-geolocation-lt#232]
Hello,

On iOS its working fine, but on android when i start the app i get a short message with "licence error".
Does it means that i cannot use the plugin for free on Android? (its not really clear explained on the doc page).

**Comment by christocracy** [comment]
Correct.

**Comment by christocracy** [comment]
If you wish to build the **Free Version** for **Android** in your *own* app, modify your `config.xml` as follows (your app **must** be named `com.transistorsoft.backgroundgeolocation.ionic`:

```xml
<widget id="com.transistorsoft.backgroundgeolocation.ionic" version="2.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <preference name="cordova-background-geolocation-license" value="4bbb513c013111eae951647fd4f9e79f127fce6f7a00e9d327db9ea2a053a0df" />
```

**Comment by chris087** [comment]
// BackgroundGeoLocation is highly configurable.
        bgGeo.configure({
            // Geolocation config
            desiredAccuracy: 10,
            distanceFilter: 20,
            stationaryRadius: 40,
            locationUpdateInterval: 1000,
            fastestLocationUpdateInterval: 5000,

            // Activity Recognition config
            activityType: 'Fitness',
            activityRecognitionInterval: 25000,
            stopTimeout: 2,
            useSignificantChangesOnly: true,

            // Application config
            debug: false,
            stopOnTerminate: false,
            startOnBoot: true

            }, function(state) {
                // This callback is executed when the plugin is ready to use.
                console.log('BackgroundGeolocation ready: ', state);

                if (!state.enabled) {
                    bgGeo.start();
                }
        });

**Comment by christocracy** [comment]
Yes, but `useSignificantChangesOnly` is iOS-only.  Android ignores this option.

**Comment by chris087** [comment]
<widget id="com.transistorsoft.backgroundgeolocation.ionic" version="2.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <preference name="cordova-background-geolocation-license" value="4bbb513c013111eae951647fd4f9e79f127fce6f7a00e9d327db9ea2a053a0df" />

changed... worked in test build. when I upload it to google play store, following error:

**Your APK needs to have the package name com.yorbody.easyfysio**

**Comment by christocracy** [comment]
Obviously you can't submit your app to the play with with *my* app id `com.transistorsoft.backgroundgeolocation.ionic`.

[I own that app id for my Sample App](https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic&hl=en)

You can only deploy it to your device from your local machine.

**Comment by christocracy** [comment]
If you want to publish your app with the Android plugin, you must [purchase a license](http://www.transistorsoft.com/shop/products/cordova-background-geolocation#plans) so you can generate your own key.

**Comment by chris087** [comment]
I know, but why you make it so unclear... You have to say: FOR TESTING PURPOSES you can use "com.transistorsoft.backgroundgeolocation.ionic"  in your config.

**Comment by christocracy** [comment]
I don't know...seems obvious if you change your `<widget id />` in `config.xml` that you won't be able to submit that to the play store unless you've first created that app id.
