### ISSUE TITLE
Is this plugin works when iOS app is killed? (background service remains open or not?)

### ISSUE THREAD

**Issue by ShahnawazAli93** [transistorsoft/cordova-background-geolocation-lt#234]
## Your Environment
* Plugin version: latest
* Platform: iOS
* OS version: latest

I only have one question does this plugin works in background (as background service) in iOS after the app is killed?

I have tried this other plugin
https://github.com/mauron85/cordova-plugin-background-geolocation

but its not giving this feature.

If yes then I would definitely buy your premium version.

**Comment by christocracy** [comment]
Yes, with `stopOnTerminate: false`.  While the your app certainly *will* die for a short period of time, iOS *will* reboot your app once the device breaks out of the `stationaryRadius` (typically takes ~200 meters of movement) or a background-fetch event occurs (typically every 15min).

You can see me demonstrate this behaviour in the iOS simulator [in this video](https://youtu.be/rFNDIQLEouo?t=70)

**Comment by christocracy** [comment]
It's actually a harder problem to keep the plugin from rebooting after terminate when you *don't* want it to (ie: `stopOnTerminate: true`.

**Comment by ShahnawazAli93** [comment]
Great, so it means even after rebooting the plugin it will hit the server API with all the geolocation data?

**Comment by christocracy** [comment]
You can see that in the video.  That terminal screen on the right is my [Node-based Test Server](https://github.com/transistorsoft/background-geolocation-console).
