### ISSUE TITLE
locationAuthorizationAlert & listen for permission not granted errors

### ISSUE THREAD

**Issue by grundmanise** [transistorsoft/cordova-background-geolocation-lt#235]
Hi,

`locationAuthorizationAlert` - Is there something similar for the Android version.
Is it possible to receive `error` or listen for `onError` / `onPermissionNotGranted` event? I want to show custom screen when: `Location services are off` or `Background location is not enabled` errors happen.

Btw thanks for this amazing plugin!

**Comment by christocracy** [comment]
Android automatically shows a popup when you ask the plugin fetch a location (either from calling `#start`, `#configure`, `#getCurrentPosition`, `#watchPosition`.

![](https://3.bp.blogspot.com/-G6JbDQ22P6k/VtV-PY_BVoI/AAAAAAAABHE/BBvGrk-0qfk/s1600/device-2016-03-01-165818.png)
