### ISSUE TITLE
Can the startSchedule have an optional parameter to not force start immediately?

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#236]
In case we set a schedule and then startSchedule() in the middle of a schedule item can this be optionally turned off:
D/TSLocationManager(30332): ������ Scheduler says we should be ENABLED but we are NOT

and the plugin will instead start at the beginning of the next schedule item?
Something like ignoreCurrent=true or ignoreInProgress=true

## Your Environment
Plugin version: 2.2.0
Platform: Android
OS version: 5.1.1
Device manufacturer / model: Nexus 4
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): android 6.0.0
Plugin config
startOnBoot: true
stopOnTerminate: false
foregroundService: true

**Comment by christocracy** [comment]
What is your reasoning?  Why would you provide a particular `schedule` if you don't want the Scheduler to respect it?  Doesn't make sense.

**Comment by JohnyBoy1234** [comment]
I do want the scheduler to respect it. But let's say I want to track someone going to work every day. Once he gets to work, I want to stop tracking until the next day to save battery life. So I could stop the scheduler and start it again with ignoreInProgress=true

**Comment by christocracy** [comment]
Why not just listen to the `schedule` event and make your own decision to `#stop`?

```Javascript
bgGeo.on('schedule', function(state) {
  var now = new Date();
  if (<some logic>) {
    bgGeo.stop();
  }
});
```

**Comment by JohnyBoy1234** [comment]
The generic concept would be, I want scheduled tracking sessions, but once an event occurs, I want to end the current tracking session early as my goal has been achieved

**Comment by JohnyBoy1234** [comment]
but if I stop() then there's no more scheduling running for the next day

**Comment by christocracy** [comment]
That's not true.  The Scheduler doesn't stop until you `#stopSchedule`.

**Comment by JohnyBoy1234** [comment]
the docs say stop() This is the plugin's power OFF button.

I've tried it and the scheduler did not restart

**Comment by JohnyBoy1234** [comment]
basically I had a schedule in progress and another that starts in a couple of minutes. I stop() and getState did show schedulerEnabled:true but after a few minutes the next schedule wasn't started...

**Comment by christocracy** [comment]
`#stop` does not stop the Scheduler.  The Scheduler will evaluate on each background-fetch event (typically every 15 min) and on `pause` / `resume` events.

**Comment by christocracy** [comment]
When your app is in background, with location services *OFF*, due either to being in stationary-mode or `#stop`ped, iOS has **suspend** your app.  There is no code running.  The Scheduler cannot evaluate until its awakened by some event, as mentioned above.  The Scheduler can be 15 min (or more) late.

**Comment by JohnyBoy1234** [comment]
okay, so you're saying my test scenario is bad based on the plugin's internals. I'll keep trying
Thanks

**Comment by christocracy** [comment]
With the Scheduler enabled and the plugin `#stop`ped, you can force a Schedule evaluation just by bringing your app to the foreground.  You'll see the Schedule evaluation in the logs, so watch the logs.

**Comment by christocracy** [comment]
Or by simulating a background-fetch event with XCode.

**Comment by JohnyBoy1234** [comment]
I was trying Android currently with app in the foreground. I'll set the next schedule to be at least 15 minutes after my stop() to see if it works.

**Comment by christocracy** [comment]
Android is much more exact with its scheduling.  What I said above applies only to iOS, which is *much* more strict with background operation.

**Comment by christocracy** [comment]
You can test Android with Schedule intervals of 1 min.

I made a [Schedule-generator](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/tests.js#L152) in the SampleApp.  It spits out an `[]` of schedules you can provide to the plugin

```Javascript
config.schedule = Tests.generateSchedule(10, 0, 1, 1);
```

**Comment by JohnyBoy1234** [comment]
Yes I saw that. Thanks
