### ISSUE TITLE
Use socket.io instead of http request

### ISSUE THREAD

**Issue by int3rnet** [transistorsoft/cordova-background-geolocation-lt#241]
Hello , i checked the plugin and saw that i can call a http request so i can save the point.
that is so nice but what about if i wanna send socket.io instead of http request all the time.

that will make my server performance better.

i didn't try it to be honest , but where can i put the socket.io init code so the plugin call it all the time even if it's in backlground or terminted.

thank you

**Comment by christocracy** [comment]
There's no support for using Sockets.  If you don't want to use the plugin's built-in HTTP layer, simply don't provide an url.  It's up to you to sync your locations as you wish.

However, for Android, your foreground Activity (where you Javascript lives) does not exist if the user terminates the app -- only the plugin's native Android service with its built-in HTTP layer are capable of sending locations to your server.  You'll have no sockets when the user terminates the Android app.

**Comment by int3rnet** [comment]
so can i use socket.io while the app in background ? 

and once the app is terminated i will use http request ???

if yes , please guide me howto set my socket.io while the status is (on_movment)


thnx

**Comment by christocracy** [comment]
It's not about foreground vs background, it's about awake vs suspended.

The plugin has 2 states:  **moving** and **stationary**.  When the plugin is **stationary** in the background (signalled by the `motionchange` event), iOS is going to **suspend** your app.  Your socket will die in this case.

On Android, when user terminates the app, only the plugin's background-service continues to live.  Your Javascript (and your socket) will die.

You might as well just set up a standard HTTP endpoint and let the plugin manage this for you.

I have no experience with Socket.io.
