### ISSUE TITLE
Background location reading is not working

### ISSUE THREAD

**Issue by hiteshthakor** [transistorsoft/cordova-background-geolocation-lt#243]
function onDeviceReady() {
        // Get a reference to the plugin.
        var bgGeo = window.BackgroundGeolocation;

        //This callback will be executed every time a geolocation is recorded in the background.
        var callbackFn = function (location, taskId) {
            var coords = location.coords;
            var lat = coords.latitude;
            var lng = coords.longitude;

            var addVisitUrl = 'myapiURL';
            var item = {
                "UserName": localStorage.getItem('username'),
                "Lat": location.latitude,
                "Long": location.longitude,
                "Token": localStorage.getItem('accessKey')
            };

            $http({
                method: 'POST',
                url: addVisitUrl + 'Location/UpdateLocation',
                data: item
            });

            alert("Location Updating")
            console.log('- Location: ', JSON.stringify(location));

            // Must signal completion of your callbackFn.
            bgGeo.finish(taskId);
        };

        // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
        var failureFn = function (errorCode) {
            console.warn('- BackgroundGeoLocation error: ', errorCode);
        }

        // Listen to location events & errors.
        bgGeo.on('location', callbackFn, failureFn);

        // Fired whenever state changes from moving->stationary or vice-versa.
        bgGeo.on('motionchange', function (isMoving) {
            console.log('- onMotionChange: ', isMoving);
        });

        // BackgroundGeoLocation is highly configurable.
        bgGeo.configure({
            // Geolocation config
            desiredAccuracy: 0,
            distanceFilter: 10,
            stationaryRadius: 50,
            locationUpdateInterval: 1000,
            fastestLocationUpdateInterval: 5000,

            // Activity Recognition config
            activityType: 'AutomotiveNavigation',
            activityRecognitionInterval: 5000,
            stopTimeout: 5,

            // Application config
            debug: true,
            stopOnTerminate: false,
            startOnBoot: true,

         
        }, function (state) {
            // This callback is executed when the plugin is ready to use.
            console.log('BackgroundGeolocation ready: ', state);
            if (!state.enabled) {
                bgGeo.start();
            }
        });

        // The plugin is typically toggled with some button on your UI.
        function onToggleEnabled(value) {
            if (value) {
                bgGeo.start();
            } else {
                bgGeo.stop();
            }
        }
        navigator.splashscreen.hide();
    }

**Comment by hiteshthakor** [comment]
please help me, I have  tried lots of time but still not working

**Comment by hiteshthakor** [comment]
@christocracy

**Comment by christocracy** [comment]
Do **NOT** spam issues.  Do you **want** to make me angry?

Also, you ignored the issue-template.  You'll get no help until you provide this information.



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
Closing for lack of feedback.
