### ISSUE TITLE
Adding extras object to a geofence?

### ISSUE THREAD

**Issue by chrisle** [transistorsoft/cordova-background-geolocation-lt#244]
I would like to persist geofences instead of locations. Is there a way to add `extras` to Geofences? Is there a way to upload to a server just the Geofences?

## Your Environment
* Plugin version: 2.2.0
* Platform: iOS
* OS version: 10.x
* Device manufacturer / model: Apple
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): ios 4.3.1
* Plugin config

```
com.googlemaps.ios 2.1.1 "Google Maps SDK for iOS"
com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.6.5 "BackgroundMode"
cordova-plugin-ble-central 1.1.3 "BLE"
cordova-plugin-browsersync 0.1.1 "cordova-plugin-browsersync"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-insomnia 4.2.0 "Insomnia (prevent screen sleep)"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-sqlite-storage 2.0.0 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
```

## Expected Behavior
```js
bgGeo.addGeofence({
    identifier: "Home",
    radius: 150,
    latitude: 45.51921926,
    longitude: -73.61678581,
    notifyOnEntry: true,
    notifyOnExit: false,
    notifyOnDwell: true,
    loiteringDelay: 30000,
    extras { 'foo': 'bar' } // <-- this could be nice.
}, function() {
    console.log("Successfully added geofence");
}, function(error) {
    console.warn("Failed to add geofence", error);
});
```

## Actual Behavior
Extras is not persisted

## Steps to Reproduce
(Feature request)

## Context
My app interfaces with external hardware connected via Bluetooth. When the hardware sends a detection signal, I would like to create a geofence that includes data from the hardware. Then at some point, batch send all the geofences create to a server.

## Debug logs
n/a

**Comment by christocracy** [comment]
I foresaw this need.  I believe I built-in some hooks to allow for this, just needs to be finished.

**Comment by christocracy** [comment]
Ok, I've got `extras` implemented for both iOS and Android.  However, it'll only be available in the [Premium Version](http://www.transistorsoft.com/shop/products/cordova-background-geolocation) until I release a new stable version to this public repo here.

There won't be a new stable release here until the new year.

**Comment by chrisle** [comment]
Does the addition to the Premium version also include the ability to send just the Geofences to a server?

**Comment by christocracy** [comment]
The plugin has a "geofences only" tracking mode.  @see [`#startGeofences`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#startgeofencescallbackfn)
