### ISSUE TITLE
Location Authorization popup is fired even if it's already authorized

### ISSUE THREAD

**Issue by ludooo** [transistorsoft/cordova-background-geolocation-lt#245]
## Your Environment
* Plugin version: 2.2.0
* Platform: iOS (tested on Simulator + Device)
* OS version: 10.1
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): 4.3.1
* Plugin config

```
bgGeo.configure({
	// Geolocation config
	desiredAccuracy: 0,
	distanceFilter: 10,
	stationaryRadius: 25,
	locationUpdateInterval: 1000,
	fastestLocationUpdateInterval: 5000,

	// Activity Recognition config
	activityType: 'AutomotiveNavigation',
	activityRecognitionInterval: 5000,
	stopTimeout: 5,
	locationAuthorizationRequest: 'Always',
	disableMotionActivityUpdates: true,

	// Application config
	debug: false,
	stopOnTerminate: true,
	startOnBoot: false,
	persist: false,
	notificationText: 'Location service activated',// TODO
	notificationColor: '#ff9012'
}, function(state) {
	// This callback is executed when the plugin is ready to use.
	console.log('BackgroundGeolocation ready: ', state);
	if (!state.enabled) {
		bgGeo.start();
		// First call
		bgGeo.getCurrentPosition(function(position, taskId){
			geoSuccess(position, taskId);
		}, function(){
			if (error) {
				error();
			}
		}, {
			desiredAccuracy: 0,
			persist: false
		});
	}
}, function(err){
	console.log('bgGeo error', err);
	if (error) {
		error();
	}
});
```

## Expected Behavior
Location Authorization popup should not be fired, right ?

## Actual Behavior
The Location Authorization popup is fired even if it's already authorized in device Settings.

![capture d ecran 2016-12-21 a 14 15 05](https://cloud.githubusercontent.com/assets/4241119/21402860/78c38060-c788-11e6-83da-eeb485c30a58.png)

![capture d ecran 2016-12-21 a 14 17 55](https://cloud.githubusercontent.com/assets/4241119/21402859/78bf2f92-c788-11e6-9717-bf7642f8575b.png)

**Comment by christocracy** [comment]
What other plugin have you installed?

**Comment by christocracy** [comment]
Btw, it's unnecessary to do a getCurrentPosition in the configure callback if you're always calling #start.  The first thing #start does is get the current position.

**Comment by ludooo** [comment]
@christocracy Ok for getCurrentPosition() !

My plugins list : 

com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
com.vliesaputra.deviceinformation 1.0.1 "DeviceInformation"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.6.6-dev "BackgroundMode"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-customurlscheme 4.2.0 "Custom URL scheme"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-device-motion 1.2.3 "Device Motion"
cordova-plugin-device-orientation 1.0.5 "Device Orientation"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-google-analytics 1.7.4 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-insomnia 4.2.0 "Insomnia (prevent screen sleep)"
cordova-plugin-media 2.4.1 "Media"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
cordova.plugins.diagnostic 2.3.11 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.4+ledControl+spk0611iOS10Changes "LocalNotification"
es6-promise-plugin 3.0.2 "Promise"
io.branch.sdk 2.4.0 "branch-cordova-sdk"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.0.10 "OneSignal Push Notifications"

**Comment by christocracy** [comment]
Get rid of Cordova-plugin-geolocation.  That's your problem.

Also, if you care about not having Apple rejecting your app (100% guaranteed), get rid background-mode.  Apple **will** reject you (unless you're making an Audio player)

**Comment by christocracy** [comment]
Closing for lack of feedback.  I assume my previous comment fixed the issue.
