### ISSUE TITLE
How to check whether GPS is On or not?

### ISSUE THREAD

**Issue by mohanchalla** [transistorsoft/cordova-background-geolocation-lt#246]
If the user is disabled the GPS, Then How to alert the user with a popup message to turn on the GPS. The pop-up should navigate the user to the Settings screen.

**Comment by christocracy** [comment]
Listen to providerchange event

**Comment by mohanchalla** [comment]
Any configuration is there to show settings page from the app?

**Comment by mohanchalla** [comment]
providerchange event is not triggered even after turn off the GPS.
