### ISSUE TITLE
speed: -1, heading: -1, altitude -1

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#247]
The sample app is reporting some parameters as -1. What is the value -1 supposed to indicate and why is it showing up at all?

For example "activity": "still" with "confidence": 100 and "is_moving": false which means speed should be 0. But it's showing as -1. Same when it's actually moving in a car.
It's probably a phone or setup issue... but what?

 A different GPS tracking app is properly showing values for speed, heading etc. 

## Your Environment
Plugin version: 2.2.0
Platform: Android
OS version: 5.1.1
Device manufacturer / model: Nexus 4
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): android 6.0.0
Plugin config
startOnBoot: true
stopOnTerminate: false
foregroundService: true

**Comment by christocracy** [comment]
A value of -1 means undetermined.  Speed comes only from when gps is available.  The plugin does not massage these values at all.  It merely passes them directly as reported from the native api.

**Comment by Renzo04** [comment]
Hi, i have the same problem with speed in some devices, i'm working on a running app, do you know some alternative to calculate this value?

Thanks a lot!

**Comment by christocracy** [comment]
No alternative.  The only thing you can do is ensure `desiredAccuracy: 0`.  If the location comes from GPS, there will be `speed` / `heading`.

**Comment by Renzo04** [comment]
And if i use the distance between coords from geosamples (latitude and longitude) with the difference between the timestamp attribute, it would be a trustable value?

**Comment by christocracy** [comment]
Depends on the accuracy.  Obviously if you use a location with poor accuracy in your calculation, your `speed` calculation is going to junk.

**Comment by Renzo04** [comment]
Yes... i don't know if the best choice is bad speed sometimes or none speed haha.

Thank you!
