### ISSUE TITLE
How to navigate the user to the settings page to enable the GPS

### ISSUE THREAD

**Issue by mohanchalla** [transistorsoft/cordova-background-geolocation-lt#248]
_If the GPS is turned off then I want show a popup which will enable the GPS. If he says OK then I will open the app Otherwise I will close the app. Is there any method to show the settings page from the app through Background GeoLocation Plugin or Should I need to use third party plugin for this?_

**Comment by christocracy** [comment]
There's no automatic mechanism to navigate the user directly to *your App's* Setting's -- only to the Settings` main screen.

The plugin has no mechanism to perform this.

**Comment by mohanchalla** [comment]
So I have to use third party plugin to do this right?

**Comment by christocracy** [comment]
If there's a 3rd party plugin that will allow you to do this, yes.
