### ISSUE TITLE
Is there the ability to query/update the database directly?

### ISSUE THREAD

**Issue by chrisle** [transistorsoft/cordova-background-geolocation-lt#249]
Is there any ability to query / update database records directly?

* I would like the ability to query the database directly.
* I would also like the ability to update the extra data that goes with each geofence.

Is this functionality available (or can be made available) in the premium version?

## Your Environment
* Plugin version: 2.2.0
* Platform: iOS
* OS version: 10.x
* Device manufacturer / model: Apple
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): ios 4.3.1
* Plugin config

```
com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-ble-central 1.1.3 "BLE"
cordova-plugin-browsersync 0.1.1 "cordova-plugin-browsersync"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-insomnia 4.2.0 "Insomnia (prevent screen sleep)"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
```

## Expected Behavior
```javascript
db.transaction(function(tx) {
  db.executeSql('SELECT * FROM geofenceDb ' +
                'WHERE ' +
                'latitude BETWEEN 37.335 AND 37.339 ' +
                'AND longitude BETWEEN -122.032 AND -122.035',
    [], function(result) {
      console.log('Result:', result);
    });
}, function(err) {
  console.log('Bad things happened:', err);
});
```
## Actual Behavior
N/A

## Steps to Reproduce
N/A

## Context
Hardware radar communicates with an app. As the user drives along a road the radar reports signals it picks up to the app. I want to create geofences for each radar signal. If the user drives along the same road a second time I do not want another to create another geofence. Instead, I would like to update data associated with the geofence that is already there.

## Debug logs
N/A

**Comment by christocracy** [comment]
This is not possible currently.  If you want to update the `extras` on a geofence, just recreate it.  You don't have to first delete it -- the code will automatically destroy an existing geofence with identical `identifier`.
