### ISSUE TITLE
Question: Calling config multiple times

### ISSUE THREAD

**Issue by mattgrande** [transistorsoft/cordova-background-geolocation-lt#25]
Hi Chris,

A quick question for you: Are there any known issues / problems if the config gets called multiple times?

Thanks,
- Matt.

**Comment by christocracy** [comment]
You mean #configure method?  I wouldn’t do that.

On Fri, Oct 23, 2015 at 11:02 AM, Matt Grande <notifications@github.com>
wrote:

> Hi Chris,
>
> A quick question for you: Are there any known issues / problems if the
> config gets called multiple times?
>
> Thanks,
>
>    - Matt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/25>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
If you need to update the config of the plugin, use the method #setConfig

On Fri, Oct 23, 2015 at 11:03 AM, Chris Scott <christocracy@gmail.com>
wrote:

> You mean #configure method?  I wouldn’t do that.
>
> On Fri, Oct 23, 2015 at 11:02 AM, Matt Grande <notifications@github.com>
> wrote:
>
>> Hi Chris,
>>
>> A quick question for you: Are there any known issues / problems if the
>> config gets called multiple times?
>>
>> Thanks,
>>
>>    - Matt.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/25>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by mattgrande** [comment]
Yes, I meant #configure. I'll try and avoid it. Thanks for the prompt response!

**Comment by mattgrande** [comment]
Hey, sorry, follow-up question, if you don't mind.

What's the difference between `configure` and `setConfig`? Should we just always use `setConfig` in that case?

**Comment by christocracy** [comment]
Do #configure just one, to provide initial config and location callback.

Use #setConfig to change config thereafter.

On Monday, October 26, 2015, Matt Grande <notifications@github.com> wrote:

> Hey, sorry, follow-up question, if you don't mind.
>
> What's the difference between configure and setConfig? Should we just
> always use setConfig in that case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/25#issuecomment-151122169>
> .
>


-- 
Snet form Gmail Mobile
