### ISSUE TITLE
Is it possible to detect walking vs driving?

### ISSUE THREAD

**Issue by EGreg** [transistorsoft/cordova-background-geolocation-lt#252]
Love the continuous background updates of location. Is there a way to use the acceleromoter in the background detect when the user has parked their car and began walking? They were sitting in the car and moving fast from time to time, then started walking. And vice versa, from walking to driving? If not, how hard would it be to add this feature? It would be extremely useful on top of your already excellent library!

**Comment by christocracy** [comment]
Listen to [`activitychange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#onactivitychangecallbackfn-failurefn) event.

```Javascript
bgGeo.on('activitychange', function(activityName) {
  console.log('- activitychange fired: ', activityName);  // <-- 'still', 'on_foot', 'in_vehicle', etc
});
```

**Comment by christocracy** [comment]
The icon on bottom toolbar of SampleApp is rendered using the `activitychange` event:

![](https://camo.githubusercontent.com/057b63f80467c6064f262b82a2b0f20837b9f771/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f323331393735352f636f72646f76612d6261636b67726f756e642d67656f6c6f636169746f6e2f73637265656e73686f742d6970686f6e65352d67656f66656e6365732d6672616d65642d524541444d452e706e67)
