### ISSUE TITLE
Post only on entering / leaving a geofence

### ISSUE THREAD

**Issue by lukeisontheroad** [transistorsoft/cordova-background-geolocation-lt#254]
Hi,

Your plugin is awesome, I consider buying the premium edition. There is just one thing I can't see at the moment. Is there a way to just fire a POST requests on entering / leaving a geofence? Currently it fires on each motionchange. I wasn't able to find something related to this in the documentation.

**Comment by christocracy** [comment]
There's a relatively new "geofences-only" mode.

Use [`#startGeofences`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#startgeofencescallbackfn) instead of `#start`.
