### ISSUE TITLE
Background-fetch not fires when app is killed 

### ISSUE THREAD

**Issue by dimitrisTheof** [transistorsoft/cordova-background-geolocation-lt#255]
## MyEnvironment
* Plugin version: 2.2.0
* Platform: iOS
* OS version: Sierra 10.12.1
* Cordova version: 6.2.0
* Cordova platform version (`cordova platform ls`): IOS 4.1.1
* Plugin config
                desiredAccuracy: 0,
                distanceFilter: 10,
                stationaryRadius: 50,
                locationUpdateInterval: 1000,
                fastestLocationUpdateInterval: 5000,
                // Activity Recognition config
                activityType: 'AutomotiveNavigation',
                activityRecognitionInterval: 5000,
                stopTimeout: 5,
                // Application config
                debug: true,
                stopOnTerminate: false,
                startOnBoot: true,
                // HTTP / SQLite config
                url: 'http://141.237.36.18/Test',
                method: 'GET',
                autoSync: true,
                maxDaysToPersist: 1,
                headers: {
                    "X-FOO": "bar"
                },
                params: {
                    "auth_token": "maybe_your_server_authenticates_via_token_YES?"
                }

##Questions
1. When the app is in background my server receives the request('http://141.237.36.18/Test') every 20 minutes(avg time) or more. In documentation is mentions that the fetch is fired every 15 min. 
Have something wrong?

2. As you can see I set stopOnTerminate: false. 
When I am killing the app I am waiting for a request in my server every 15 min. But nothing is received. (Max waiting time is 2 hours)
Can you understand what is wrong?
I checked your video -> https://www.youtube.com/watch?v=rFNDIQLEouo&feature=youtu.be&t=70
and I cannot understand what is wrong. 
Have something wrong?

The question No2 is the most important.

**Comment by christocracy** [comment]
There's no *guarantee* that fetch will fire *every* 15 min.  It's totally up to Apple's secret algorithm when fetch is fired but is most *likely* based upon frequency of usage of the app.  If you open the app frequently for a long period of time, fetch will fire frequently.

If you don't open the app for a few days, fetch will *likely* fire *less* frequently.

This isn't an issue for this repo, it's an issue for [background-fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch)

**Comment by christocracy** [comment]
Also, i find a fetch event often coincides with notifications from other apps, when I receive a GMail notification, for example.

**Comment by dimitrisTheof** [comment]
Your answer is really useful about question1. Thank you!!

What about question2? When the app is killed fetch never happens. Have something wrong?

**Comment by christocracy** [comment]
Fetch is not a topic for this plugin.

It's totally up to Apple to fire fetch.  There's nothing to be done.

**Comment by christocracy** [comment]
I just returned from a field-test, where I terminated the app before staring out.  

Here a "Background fetch Received", where the app was "Booted in background".  However, it also coincided with an "Exit stationary region".

![](https://www.dropbox.com/s/crazzfoq0wqmgav/Screenshot%202017-01-11%2015.37.59.png?dl=1)

**Comment by christocracy** [comment]
The plugin will **always** boot in background when stationary-exit occurs, 100% guaranteed, typically 200 meters movement away from stationary-location.

**Comment by christocracy** [comment]
It seems that background-fetch monitoring is terminated [if user *manually* terminates the app](http://stackoverflow.com/questions/22823788/why-does-my-iphone-app-not-receive-background-fetch-events-after-being-terminate).  If the OS itself terminates an app (due to memory pressure), background-fetch *will* re-launch your app.  

This does not apply to the plugin in general.  The plugin will *still* be rebooted **no matter what** when the user travels about 200 meters beyond the last known location.  This is purely a *background fetch* issue.  It has nothing to do with this plugin.
