### ISSUE TITLE
useSignificantChangesOnly does not set app Background Location to 'Always' with stopOnTerminate set to false

### ISSUE THREAD

**Issue by mherb63** [transistorsoft/cordova-background-geolocation-lt#256]
## Your Environment
* Plugin version: 2.3.0
* Platform: iOS or Android:  IOS
* OS version: 10.2
* Device manufacturer / model: IPhone 6
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): ios 4.3.1
* Plugin config

```
    bgGeo.configure({
        desiredAccuracy: 0,
        distanceFilter:50,
        stationaryRadius: 50,
        locationUpdateInterval: 300000,
        fastestLocationUpdateInterval: 60000,

        // Activity Recognition config
        useSignificantChangesOnly: true,
        activityType: 'AutomotiveNavigation',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,

        // Application config
        debug: false,
        stopOnTerminate: false,
        startOnBoot: true,
        maxDaysToPersist: 0,
        maxRecordsToPersist: 0,
        logMaxDays: 0

    }...
```

## Expected Behavior
When App ask user for permission to use background location, it should ask like below.  And if the user approves that, the permissions should be set appropriately in Settings:

![image](https://cloud.githubusercontent.com/assets/1205814/22128931/293d43be-de71-11e6-8810-51f8ee05e99e.png)

## Actual Behavior
App only ask for background permission for when the app is in use:

![image](https://cloud.githubusercontent.com/assets/1205814/22129143/40d854ea-de72-11e6-8c50-443e8060d106.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
I made some changes to locationAuthorization recently.  I'll check it out.

**Comment by christocracy** [comment]
I just booted the SampleApp using version `2.3.0`.  I see no issue here.

There is perhaps some confusion with this, however.

At first boot, when the plugin's `#start` method is called for the first time, you'll see **Alert 2** above.

Next, [`locationAuthorizationRequest`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-string-locationauthorizationrequest-always) (default `Always`).  This is the authorization-mode that you *expect* your app to be in.  If the user sets it to anything *other than* that (eg: `Always`), the plugin will complain and show **Alert 1** above (whose dialog contents are configured with [`locationAuthorizationAlert`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-object-locationauthorizationalert)

Finally, the plugin adds both [`NSLocationAlwaysUsageDescription`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L33) as well as `NSLocationWhenInUseUsageDescription` to your app's `.plist`.  Generally, you should require one or the other.  In the future, I'd like to make that configurable in your app's `config.xml`, where you'd select which one (or both) you'd like to use, as well as the associated `UsageDescription` text.
