### ISSUE TITLE
Is there an API call to generate a local Notification in the manner that debug: true does?

### ISSUE THREAD

**Issue by mherb63** [transistorsoft/cordova-background-geolocation-lt#257]
I would like to generate my own local notification.  Is there way to do this with your API to get a notification similar to the below?

![image](https://cloud.githubusercontent.com/assets/1205814/22152276/07a1f72a-def0-11e6-91f8-7d8879a00901.png)

**Comment by christocracy** [comment]
No.  You a third party plugin.
