### ISSUE TITLE
Location not working when i terminate the App

### ISSUE THREAD

**Issue by turkialarjani** [transistorsoft/cordova-background-geolocation-lt#259]
## Your Environment
* Plugin version:
* Platform: iOS 
* OS version: 10.2
* Device manufacturer / model:
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`):ios 4.3.1 - 
* Plugin config

```
bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 50,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 5000,

        // Activity Recognition config
        activityType: 'AutomotiveNavigation',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,

        // Application config
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true,

        // HTTP / SQLite config
        url: server_url+'users/location/',
        method: 'POST',
        autoSync: true,
        maxDaysToPersist: 1,
        }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log('BackgroundGeolocation ready: ', state);
        if (!state.enabled) {
            bgGeo.start();
        }
    });
```
## Expected Behavior
-Send the location to server when the app is terminated. 

## Actual Behavior
-No thing happen when app terminated. 
-The plugin stop when the app terminated.

**Comment by christocracy** [comment]
After app termination with `stopOnTerminate: false`, the plugin must exit the "stationary-geofence" before iOS will reboot the app.  Typically, you must move 200 meters before this occurs.

- Terminate app
- Travel at least 200 meters.

**Comment by christocracy** [comment]
You can a demo of `stopOnTerminate: false` in [this video](https://youtu.be/rFNDIQLEouo?t=68)

**Comment by turkialarjani** [comment]
I travel about 40 Km and nothing happened.

**Comment by christocracy** [comment]
Logs please.  
- Wifi on?
- Not in Airplane mode?

**Comment by christocracy** [comment]
The plugin stores 3 days worth of logs by default.  Fetch them with [`getLog`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getlogcallbackfn)

**Comment by turkialarjani** [comment]
Yes, and I use cellular data.

**Comment by christocracy** [comment]
And don't post the **entire** log to this thread.  Link it to a text file or gist.

**Comment by turkialarjani** [comment]
loggggggggggggggggg2017-01-21 20:05:35.027 🔵-[Settings init] Settings loaded Form Xcode

**Comment by christocracy** [comment]
You're giving me 1 single row of log??

I want hours worth.  Use the getLog method

**Comment by turkialarjani** [comment]
Sorry but how to link log to text file.

**Comment by christocracy** [comment]
post it to a gist: https://gist.github.com/

**Comment by turkialarjani** [comment]
After i terminate the app Xcode display this:

2017-01-21  - TSBackgroundFetch onAppTerminate
🔵-[TSLocationManager onAppTerminate] stopOnTerminate? 0
⋯-[TSDBLogger db_save] Log committed

**Comment by christocracy** [comment]
Is there something you don't understand about [getLog](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getlogcallbackfn)

**Comment by turkialarjani** [comment]
Yes how to post getlog to gist.

**Comment by christocracy** [comment]
Open the Safari Javascript Console and execute the method directly in the console:
![](https://www.dropbox.com/s/lseiulnsrx2onmi/Screenshot%202017-01-21%2012.54.14.png?dl=1)

```Javacript
>bg = window.BackgroundGeolocation;
>bg.getLog(function(log) { console.log(log); });
```

Copy / paste to Gist.

**Comment by turkialarjani** [comment]
![screen shot 1438-04-23 at 11 34 26 pm](https://cloud.githubusercontent.com/assets/15672452/22177611/76f5723a-e032-11e6-8fa7-dafc773dd1f7.png)

**Comment by christocracy** [comment]
Well, well.  You have just learned the importance of monitoring the web console during mobile development.

You have a JavaScript error in **your** code.  The plugin not responsible for syntax errors in your code.

This is most certainly the cause of your problem.

**Comment by christocracy** [comment]
When you see me using the var `bgGeo` in example code *it's assumed* you've first declared that variable in your code, eg:

```
var bgGeo = window.BackgroundGeolocation;
```

Read the README:
https://github.com/transistorsoft/cordova-background-geolocation-lt#using-the-plugin

**Comment by turkialarjani** [comment]
I already use it :

var bgGeo = window.BackgroundGeolocation;

    //This callback will be executed every time a geolocation is recorded in the background.
    var callbackFn = function(location, taskId) {
        var coords = location.coords;
         lat    = coords.latitude;
         lng    = coords.longitude;
        console.log('- Location: ', JSON.stringify(location));
        // Must signal completion of your callbackFn.
        bgGeo.finish(taskId);
    };

    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
    var failureFn = function(errorCode) {
        console.warn('- BackgroundGeoLocation error: ', errorCode);
    }

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);

    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function(isMoving) {
      console.log('- onMotionChange: ', isMoving);
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 50,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 5000,

        // Activity Recognition config
        activityType: 'AutomotiveNavigation',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,

        // Application config
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true,

        // HTTP / SQLite config
        url: server_url+'users/location/',
        method: 'POST',
        autoSync: true,
        maxDaysToPersist: 1,
        headers: {
            'token': '4kkuKkpSZuJ1efExodtWSCbcn7fDM7MN'
        },
        params: {
            actualLat: lat,
            actualLng: lng
        }
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log('BackgroundGeolocation ready: ', state);
        if (!state.enabled) {
            bgGeo.start();
        }
    });

    // The plugin is typically toggled with some button on your UI.
    function onToggleEnabled(value) {
        if (value) {
            bgGeo.start();
        } else {
            bgGeo.stop();
        }
    }

**Comment by christocracy** [comment]
And are you accessing the plugin in the `deviceready` event?

You're not trying to access the plugin by booting your app in the browser, are you?  Cordova plugins are not available in the browser.

**Comment by turkialarjani** [comment]
Yes,
every thing in plugin work fine when i build it in my phone using Xcode but when i terminate the app it doesn't work.
Note: my app is hybrid - jQuery Mobile.

**Comment by christocracy** [comment]
The js error screenshot:  was that the web console of the app running on your **device** or the **browser**?

**Comment by turkialarjani** [comment]
browser

**Comment by turkialarjani** [comment]
It's working now thank you.

**Comment by turkialarjani** [comment]
Another question, how I can post the location using HTTP request every movement?

**Comment by christocracy** [comment]
Yes
https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#http--persistence-options

**Comment by tarunsharpdeveloper** [comment]
in android app is not tracking location when exit , i used this to start in background,
BackgroundGeolocation.start();

even i also check in your hello-world example

**Comment by christocracy** [comment]
> Plugin version
> OS version:
>Device manufacturer / model:
