### ISSUE TITLE
Testing Android with free license failed on simulator

### ISSUE THREAD

**Issue by mherb63** [transistorsoft/cordova-background-geolocation-lt#260]
my config.xml:

```
<widget id="com.transistorsoft.backgroundgeolocation.ionic" version="2.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <preference name="cordova-background-geolocation-license" value="4bbb513c013111eae951647fd4f9e79f127fce6f7a00e9d327db9ea2a053a0df" />
```

Android Developer Console output

```

$ adb shell am start -n "com.increditek.punchapp/com.transistorsoft.backgroundgeolocation.ionic.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.increditek.punchapp/com.transistorsoft.backgroundgeolocation.ionic.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.increditek.punchapp/com.transistorsoft.backgroundgeolocation.ionic.MainActivity }
Error type 3
Error: Activity class {com.increditek.punchapp/com.transistorsoft.backgroundgeolocation.ionic.MainActivity} does not exist.

Error while Launching activity
```

**Comment by christocracy** [comment]
Why don't you just:

```
$ cordova run android
```
?

**Comment by mherb63** [comment]
I think its working.  I must have forgotten to do a 

```
cordova build android
```

I deleted all versions of the app from the sim device and did the build and I'm not seeing the error now.  I need to get a real Android device.  The Android is all new to me.  Thanks for your reply.

**Comment by christocracy** [comment]
I always dev on devices.  Nexus 5 is a nice dev device.   Nexus are best since they're the flagship Android device.  The APIs operate as advertised.

I develop on a pixel primarily, using latest os.

**Comment by mherb63** [comment]
Just to let you know, it does work on the Nexus 5 simulator.

**Comment by christocracy** [comment]
Thanks ;)

**Comment by mherb63** [comment]
you’re welcome and thanks for the great plugin.

I tried generating a license after I purchased, but it didn’t work:  may app id will be “com.increditek.punchapp”

Thanks,

Mike

**Comment by christocracy** [comment]
I see you created that key.

**Comment by mherb63** [comment]
yea but I never got to see it.  after I created it the website timed out.  So, how can I access it to include in my config.xml.

Thanks,

Mike

**Comment by christocracy** [comment]
Just hit the dashboard again:  http://www.transistorsoft.com/shop/customers

**Comment by mherb63** [comment]
got it…thanks
