### ISSUE TITLE
HTTP request with customize configuration of distance

### ISSUE THREAD

**Issue by turkialarjani** [transistorsoft/cordova-background-geolocation-lt#261]
Plugin version:
Platform: iOS
OS version: 10.2
Device manufacturer / model:
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls) :ios 4.3.1 -
Plugin config

`var bgGeo = window.BackgroundGeolocation;
        
    //This callback will be executed every time a geolocation is recorded in the background.
    var callbackFn = function(location, taskId) {
        var coords = location.coords;
        var lat1    = coords.latitude;
        var lng1    = coords.longitude;
        console.log('- Location: ', JSON.stringify(location));

        // Must signal completion of your callbackFn.
        bgGeo.finish(taskId);
    };

    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
    var failureFn = function(errorCode) {
        console.warn('- BackgroundGeoLocation error: ', errorCode);
    }

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);

    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function(isMoving) {
      console.log('- onMotionChange: ', isMoving);
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 50,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 5000,

        // Activity Recognition config
        activityType: 'AutomotiveNavigation',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,

        // Application config
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true,

        // HTTP / SQLite config
        url: server_url+'users/location/',
        method: 'POST',
        autoSync: true,
        batchSync:true,
        maxDaysToPersist: 1,
        headers: {
            'token': '4kkuKkpSZuJ1efExodtWSCbcn7fDM7MN'
        },
        params: {
             actualLat: lat,
             actualLng: lng
        }
    }, function(state) {
        
        
        // This callback is executed when the plugin is ready to use.
        console.log('BackgroundGeolocation ready: ', state);
        if (!state.enabled) {
            bgGeo.start();
        }
    });

    // The plugin is typically toggled with some button on your UI.
    function onToggleEnabled(value) {
        if (value) {
            bgGeo.start();
        } else {
            bgGeo.stop();
        }
    }`

Expected Behaviors

- Send the location **each 1km** only , otherwise don't use the http request at all.
- send the actual lat , lng instead of sending undefined sometimes .

Actual Behaviors

- using the http request even if the phone idle.
- send lat , lng undefined sometimes

**Comment by christocracy** [comment]
Read [`distanceFilter`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-integer-distancefilter).

You're configuring `distanceFilter: 10`, which means "record a location every 10 meters".

Show me evidence of `latitude` / `longitude` "undefined sometimes" from the **plugin's** log.

**Comment by turkialarjani** [comment]
Ok, how to send the location each 30 minutes only , otherwise don't use the http request at all ?

**Comment by christocracy** [comment]
You cannot think in terms of *time* with iOS.  iOS Location API is strictly *distance* based.

You try implementing my [background-fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch) plugin.  **NOTE:** `background-fetch` is **already** included as a dependency of `background-geolocation`.  The Javascript API `window.BackgroundFetch` is already available to you -- you simply need to implement the callback function as documented in that plugin's [`README`](https://github.com/transistorsoft/cordova-plugin-background-fetch#example)

That API will *typically* fire about every 15 min.  You can do whatever you want in the `callback` (eg: `getCurrentPosition`).  You are provided *exactly* 30 seconds of background-time.
