### ISSUE TITLE
getCurrentPosition() Works first time.  Then all subsequent calls go the the error callback function.

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [transistorsoft/cordova-background-geolocation-lt#266]
I can call getCurrentPostion() and the success callback is called, all is good.  If I call getCurrentPosition again within 60 seconds of the first call, then all subsequent calls go to the error callback function with "Unknown Location" error.  However the cordova geolocation can get a location during that time.  

## Your Environment
* Plugin version: 2.3.0
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: iPad Air
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): 4.2.1
* Plugin config

## Expected Behavior
I would expect the current position since the cordova geolocation plugin can find my location.

## Actual Behavior
If I call getCurrentPosition again within 60 seconds of the first call, then all subsequent calls go to the error callback function with "Unknown Location" error. 

## Steps to Reproduce
call getCurrentPosition().  Then call it again within 60 seconds of first call.

## Context
The customer is walking the electric lines and gathering pole locations using getCurrentPosition()

## Debug logs
🔵-[Settings init] Settings loaded
🔵-[DatabaseQueue migrateDatabase:] Migrating database: /var/mobile/Containers/Data/Application/6B1FDF60-4470-4B2A-A5BB-636A6597EE8F/Documents/locations.db
ℹ️__21-[LocationDAO unlock]_block_invoke UNLOCKED ALL RECORDS
ℹ️-[GeofenceDAO init] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, extras TEXT)
ℹ️-[GeofenceDAO init] CREATE index IF NOT EXISTS identifier ON geofences (identifier);CREATE index IF NOT EXISTS latitude ON geofences (latitude);CREATE index IF NOT EXISTS longitude ON geofences (longitude);CREATE index IF NOT EXISTS sin_latitude ON geofences (sin_latitude);CREATE index IF NOT EXISTS cos_latitude ON geofences (cos_latitude);CREATE index IF NOT EXISTS sin_longitude ON geofences (sin_longitude);CREATE index IF NOT EXISTS cos_longitude ON geofences (cos_longitude);
⚠️-[Settings load:] Minimum stationaryRadius is 25

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager setConfig:] 
{
    activityRecognitionInterval = 10000;
    activityType = 2;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = 10;
    disableElasticity = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    enabled = 1;
    extras = 0;
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    headers = 0;
    heartbeatInterval = 180;
    isMoving = 0;
    locationAuthorizationRequest = Always;
    locationTimeout = 60;
    logLevel = 18446744073709551615;
    maxBatchSize = "-1";
    maxDaysToPersist = 3;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    params =     {
        "collection_type" = CollectInspect;
        "network_state" = wifi;
        platform = I;
        rcdid = 1485806790781;
        unitid = e81c28e5b3a9f9de2b823acc8b4e4957c5a056ee9b6123381ba3c5ea13b3502c;
        uuid = "DAAB18E2-57AF-4618-9E5F-91603496711D";
        version = "10.2";
    };
    pausesLocationUpdatesAutomatically = 0;
    preventSuspend = 1;
    schedule = 0;
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnTerminate = 0;
    stopTimeout = 300;
    trackingMode = location;
    url = "http://10.59.23.21/webSrvRequests/AVL/avlMobilePush.php";
    useSignificantChangesOnly = 0;
}
╚═══════════════════════════════════════════════════════════
ℹ️-[LocationDAO purge:] maxDaysToPersist: 3

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush] 
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:] Success: 1
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager start] 
╚═══════════════════════════════════════════════════════════
🎾-[SOMotionDetector startDetection] 
2017-01-30 14:06:30.881447 Collect-Inspect[4301:4561300] - TSBackgroundFetch addListener: TSLocationManager

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush] 
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:] Success: 1
╚═══════════════════════════════════════════════════════════
🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2017-01-30 14:06:30.893030 Collect-Inspect[4301:4561300] - TSBackgroundFetch started
2017-01-30 14:06:30.961812 Collect-Inspect[4301:4561300] THREAD WARNING: ['BackgroundGeolocation'] took '115.687988' ms. Plugin should use a background thread.
🔵-[TSLocationManager start] Already started (ignored)
2017-01-30 14:06:30.964730 Collect-Inspect[4301:4561387] Push Plugin register called
2017-01-30 14:06:30.964883 Collect-Inspect[4301:4561387] PushPlugin.register: setting badge to false
2017-01-30 14:06:30.964983 Collect-Inspect[4301:4561387] PushPlugin.register: clear badge is set to 0
2017-01-30 14:06:30.965030 Collect-Inspect[4301:4561387] PushPlugin.register: better button setup
2017-01-30 14:06:30.972387 Collect-Inspect[4301:4561387] GCM Sender ID (null)
2017-01-30 14:06:30.972485 Collect-Inspect[4301:4561387] Using APNS Notification
🔵-[TSLocationManager locationManager:didChangeAuthorizationStatus:] status 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[BackgroundTaskManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
✅ Enabled M7 MotionActivity updates

<+33.16998397,-96.64593432> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/30/17, 14:06:24 Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | distanceFilter: -1.0
╚═══════════════════════════════════════════════════════════
- Acquiring stationary location (1 / 5)
✅ [BackgroundTaskManager createBackgroundTask]: 2

<+33.16998397,-96.64593432> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/30/17, 14:06:15 Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | distanceFilter: -1.0
╚═══════════════════════════════════════════════════════════
- Acquiring stationary location (2 / 5)
2017-01-30 14:06:31.030689 Collect-Inspect[4301:4561300] Push Plugin register success: <e81c28e5 b3a9f9de 2b823acc 8b4e4957 c5a056ee 9b612338 1ba3c5ea 13b3502c>
✅ [BackgroundTaskManager createBackgroundTask]: 3

╔═══════════════════════════════════════════════════════════
║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

<+33.16998397,-96.64593432> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/30/17, 14:06:24 Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | distanceFilter: -1.0
╚═══════════════════════════════════════════════════════════
- Acquiring stationary location (3 / 5)
✅ [BackgroundTaskManager createBackgroundTask]: 4

<+33.16998181,-96.64593457> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/30/17, 14:06:31 Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | distanceFilter: -1.0
╚═══════════════════════════════════════════════════════════
- Acquiring stationary location (4 / 5)
✅ [BackgroundTaskManager createBackgroundTask]: 5
2017-01-30 14:06:36.085561 Collect-Inspect[4301:4561300] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-01-30 14:06:36.087806 Collect-Inspect[4301:4561300] [MC] Reading from public effective user settings.

╔═══════════════════════════════════════════════════════════
║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/66 | isMoving: 0
╚═══════════════════════════════════════════════════════════

<+33.16998268,-96.64593447> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/30/17, 14:06:38 Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | distanceFilter: -1.0
╚═══════════════════════════════════════════════════════════
- Acquiring stationary location (5 / 5)
- Median location accuracy: 65.0
✅ [BackgroundTaskManager createBackgroundTask]: 6
🔵-[TSLocationManager beginHeartbeat] 
✅ [BackgroundTaskManager createBackgroundTask]: 7
🔴-[TSLocationManager stopUpdatingLocation] 
✅ INSERT: 63CB7104-E696-42CF-920C-C171B5A85529

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush] 
╚═══════════════════════════════════════════════════════════
✅ LOCKED: 63CB7104-E696-42CF-920C-C171B5A85529
🔵-[TSHttpService doPost:] HTTP Response: 200
✅ DESTROY: 63CB7104-E696-42CF-920C-C171B5A85529

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:] Success: 1
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════
2017-01-30 14:06:47.132077 Collect-Inspect[4301:4561343] 0x17414f6d0 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x17414f6d0> { count = 1, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x174229d40>: 29
}
2017-01-30 14:06:47.136806 Collect-Inspect[4301:4561343] 0x17414eb20 Daemon configuration query reply: XPC_TYPE_DICTIONARY  <dictionary: 0x17414eb20> { count = 2, transaction: 0, voucher = 0x0, contents =
	"Dictionary" => <dictionary: 0x17414e9c0> { count = 1, transaction: 0, voucher = 0x0, contents =
		"ServerURL" => <dictionary: 0x17414f200> { count = 3, transaction: 0, voucher = 0x0, contents =
			"com.apple.CFURL.magic" => <uuid: 0x17424ae90> C3853DCC-9776-4114-B6C1-FD9F51944A6D
			"com.apple.CFURL.string" => <string: 0x174254040> { length = 30, contents = "https://mesu.apple.com/assets/" }
			"com.apple.CFURL.base" => <null: 0x1af29be80>: null-object
		}
	}
	"Result" => <int64: 0x174229d60>: 0
}
2017-01-30 14:06:47.138192 Collect-Inspect[4301:4561343] [MobileAssetError:29] Unable to copy asset information from https://mesu.apple.com/assets/ for asset type com.apple.MobileAsset.TextInput.SpellChecker
- updateCurrentPosition: {
}
🎾-[LocationManager startUpdatingLocation] ON

<+33.16998039,-96.64593474> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/30/17, 14:07:01 Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 3
╚═══════════════════════════════════════════════════════════
✅ [BackgroundTaskManager createBackgroundTask]: 8

<+33.16998039,-96.64593474> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/30/17, 14:06:52 Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 2 of 3
╚═══════════════════════════════════════════════════════════
✅ [BackgroundTaskManager createBackgroundTask]: 9
2017-01-30 14:07:16.020972 Collect-Inspect[4301:4561300] locationManager::didFailWithError (null)
⚠️-[LocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=0 "(null)"
- Median location accuracy: 65.0
✅ [BackgroundTaskManager createBackgroundTask]: 10
🔴-[LocationManager stopUpdatingLocation] OFF
✅ INSERT: B1A16F32-C4E9-494F-9B73-2DF5356B9C49

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush] 
╚═══════════════════════════════════════════════════════════
✅ LOCKED: B1A16F32-C4E9-494F-9B73-2DF5356B9C49
🔵-[TSHttpService doPost:] HTTP Response: 200
✅ DESTROY: B1A16F32-C4E9-494F-9B73-2DF5356B9C49

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:] Success: 1
╚═══════════════════════════════════════════════════════════
2017-01-30 14:07:29.543931 Collect-Inspect[4301:4561300] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
⋯-[TSDBLogger db_save] Log committed
- updateCurrentPosition: {
}
🎾-[LocationManager startUpdatingLocation] ON
⚠️-[LocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=0 "(null)"
🔴-[LocationManager stopUpdatingLocation] OFF
2017-01-30 14:07:34.180938 Collect-Inspect[4301:4561300]  - onLocationManagerError: Error Domain=kCLErrorDomain Code=0 "(null)"
⋯-[TSDBLogger db_save] Log committed

## Code
/*********************Lineman App Uses This for Close ticket and upload picture*****************/
var gpsCallbackFunc;
function getBgGps(callback) {
	if (callback == undefined) {
		callback='doCloseTicket';
	}
	gpsCallbackFunc = callback;
	$("#waiting").show();
	if (bgGeo == null) {
		alert("GPS has been turned off in the settings.  You must turn GPS back on to close this ticket.");
		$("#waiting").hide();
		return;
	}
	bgGeo.getCurrentPosition(gotBgGps,errorBgGps,{ });
}
function gotBgGps(position, taskId) {
	console.log("gotBgGps() = getCurrentPostition success callback function");
	$("#waiting").hide();
	bgGeo.finish(taskId);
	bgGeo.finish(taskId);
	search_value=position;
    searchlat=search_value.coords.latitude;
    searchlon=search_value.coords.longitude;
    searchaccuracy=search_value.coords.accuracy;
    $("#accuracy_acceptance_accuracy").html(searchaccuracy+"<br>Latitude/Longitude:"+searchlat +"/"+searchlon);
    setTimeout(function() {$("#accuracy_acceptance_dialog").popup('open');},800);
    
}
function errorBgGps(err) {
	console.log("errorBgGps() = getCurrentPostition error callback function");
	$('#waiting').hide();
	$("#accuracy_acceptance_accuracy").html("<br>Failed to get GPS:"+GPSError[err]+'<br>');
    setTimeout(function() {$("#accuracy_acceptance_dialog").popup('open');},800);
}

**Comment by srsarcasmo** [comment]
What happens if I do not declare in the config, a web address to send my data? .. because I can use that data to be sent via ajax in javascript for example in a separate way

Plugin = latitude, longitude;

My ajax upload
Ajax ({{
Url: "my_web_service";
Date: "plugin";


)

**Comment by KimberleeDArmstrong** [comment]
Is that comment for this issue?  I am afraid I do not follow.

**Comment by christocracy** [comment]
If you're using this for a Lineman app, I wonder why you've configured `desiredAccuracy: 10`.  Don't you want the best possible accuracy?

Only `desiredAccuracy: 0` uses GPS.

**Comment by KimberleeDArmstrong** [comment]
LinemanApp?  You remember me. :-)  This is actually for CollectInspect, so yes you are right even more important we get excellent accuracy as they are collecting the positions of electric assets on their grid.

It gets that value based on what the user puts into their settings.  I am running a wifi only ipad deep inside a building with a metal roof.  I think I tried setting it higher because it was taking a really long time to get a reading ( 30 seconds or more ).  That is good to know though I will add a note to that setting that only a desiredAccuracy of 0 will use GPS.  I will change my setting as well and see what happens.

I noticed you had an issue earlier today where you mentioned we should not have the cordova geolocation plugin installed and only this one.  I do have that plugin installed.  Could that be my issue?  Should I remove it?

**Comment by christocracy** [comment]
You should **not** use `cordova-plugin-geolocation` in conjunction with this one.  There can be a "permission tug-of-war" between `Always` and `WhenInUse`.

GPS is only available outdoors.  However, Wifi-only iPads do **not** have GPS.

I'm not surprised you have trouble fetching locations:
```
⚠️-[LocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=0 "(null)"
```

This error comes directly from the iOS Location-Services API.

**Comment by christocracy** [comment]
[Location code: 0 means](https://developer.apple.com/reference/corelocation/clerror/kclerrorlocationunknown?language=objc)

>The location manager was unable to obtain a location value right now.

**Comment by KimberleeDArmstrong** [comment]
I tried to upload a video, but it didn't work.  It just seems weird because the first attempt to get my GPS always works with 65m accuracy and all immediate requests after that fail until I force kill the app and reopen and then it work once and never again.  And it is repeatable over and over again.

That being said I did it in the simulator and outside with a Mobile iPad and it worked perfectly.   Sorry we had a client reporting it was happening in the field so I just assumed it was a problem regardless of inside building or not.  Should have checked outside myself. Thank you.

**Comment by KimberleeDArmstrong** [comment]
Hey Chris! Quick question... You mentioned Desired Accuracy 0 uses GPS satellites. Most of our clients are in rural locations so the satellites are most definitely preferred to triangulation estimates. We have one utility that is a city utility with lots of trees but also lots of towers. If we set Desired Accuracy to 0 would it use the triangulation as back up if the satellites were having a hard time? They are getting a lot of missed readings and incorrect direction readings when driving through the city, and I was just wondering. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by christocracy** [comment]
Native location-services "fuse" all available location-providers together and return the most accurate location it found.
