### ISSUE TITLE
onHeartbeat event always fires

### ISSUE THREAD

**Issue by grundmanise** [transistorsoft/cordova-background-geolocation-lt#268]
## Your Environment
* Plugin version: 2.2.0
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: iPhone 5s
* Plugin config
```
    options: {
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 25,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 10000,

        // Activity Recognition config
        activityType: 'Other',
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        disableMotionActivityUpdates: true,

        // Application config
        debug: false,
        stopOnTerminate: false,
        startOnBoot: true,
        preventSuspend: false,
        heartbeatInterval: 7200, //seconds 7200 = every 2h.

        locationAuthorizationAlert: {
            titleWhenNotEnabled: 'Background location is not enabled',
            titleWhenOff: 'Location services are off',
            instructions: `Before you continue, need access to your location. Please enable 'Always' in the Location Services settings.`,
            cancelButton: 'Cancel',
            settingsButton: 'Settings',
        },

        // HTTP / SQLite config
        autoSync: true,
        method: 'POST',
        autoSyncThreshold: 0,
        batchSync: false,
        maxDaysToPersist: 60,
        url: `${Api.domain}/api/save-location?access_token=${localStorage.accessToken}`,
    },
    onHeartBeatReceived(params) {
        geolocation.getCurrentPosition();
    },
    init() {
    .....
       plugin.on('heartbeat', this.onHeartBeatReceived, this.onHeartBeatError);
    .....
       plugin.configure(this.options, this.onConfigureSuccess, this.onConfigureError);
    .....
   }
```

## Expected Behavior
With `preventSuspend: false` I expect that `onHeartbeat` event won't ever fire. 
With `preventSuspend: true` I expect that `onHeartbeat` will fire every ` heartbeatInterval: 7200`.

## Actual Behavior
Despite the `preventSuspend` settings (true/false) `onHeartbeat` event fires every 30 seconds.

## Debug logs
Jan 31 23:14:44 Mac-Admin [12470]: 🔵-[TSLocationManager onHeartbeat] Heartbeat
Jan 31 23:14:44 Mac-Admin [12470]: - updateCurrentPosition: {
	}
Jan 31 23:14:44 Mac-Admin [12470]: 🎾-[LocationManager startUpdatingLocation] ON
Jan 31 23:14:44 Mac-Admin [12470]: 🔴-[LocationManager stopUpdatingLocation] OFF
Jan 31 23:14:44 Mac-Admin [12470]: 
	<+26.foo ,-81.bar> +/- 5.00m (speed -1.00 mps / course -1.00) @ 1/31/17, 11:14:44 PM Eastern European Standard Time
Jan 31 23:14:44 Mac-Admin [12470]: 
	╔═══════════════════════════════════════════════════════════
	║ -[LocationManager locationManager:didUpdateLocations:] Sample 3 of 3
	╚═══════════════════════════════════════════════════════════
Jan 31 23:14:44 Mac-Admin [12470]: - Median location accuracy: 5.0
Jan 31 23:14:44 Mac-Admin [12470]: ✅ [BackgroundTaskManager createBackgroundTask]: 2467
Jan 31 23:14:44 Mac-Admin [12470]: ✅ [BackgroundTaskManager createBackgroundTask]: 2468
Jan 31 23:14:44 Mac-Admin [12470]: ✅ INSERT: 4302AB0A-485A-476A-81AA-850F52ED2B5D
Jan 31 23:14:44 Mac-Admin [12470]: 
	╔═══════════════════════════════════════════════════════════
	║ -[TSHttpService flush] 
	╚═══════════════════════════════════════════════════════════
Jan 31 23:14:44 Mac-Admin [12470]: ✅ LOCKED: 4302AB0A-485A-476A-81AA-850F52ED2B5D
Jan 31 23:14:45 Mac-Admin [12470]: 🔵-[TSHttpService doPost:] HTTP Response: 200
Jan 31 23:14:45 Mac-Admin [12470]: ✅ DESTROY: 4302AB0A-485A-476A-81AA-850F52ED2B5D
Jan 31 23:14:45 Mac-Admin [12470]: 
	╔═══════════════════════════════════════════════════════════
	║ -[TSHttpService finish:] Success: 1
	╚═══════════════════════════════════════════════════════════
Jan 31 23:14:45 Mac-Admin [12470]: ✅ [BackgroundTaskManager stopBackgroundTask] 2467 OF (
	    2,
	    2468
	)
Jan 31 23:14:45 Mac-Admin [12470]: ✅ [BackgroundTaskManager stopBackgroundTask] 2468 OF (
	    2
	)
Jan 31 23:14:54 Mac-Admin [12470]: ⋯-[TSDBLogger db_save] Log committed

and every 30 seconds this log repeats...

**Comment by christocracy** [comment]
I'll look into this when I return from vacation next week.

**Comment by grundmanise** [comment]
Sorry. This was due my mistake.
