### ISSUE TITLE
getCurrentLocation function doesnot call success callback with location coordinates if user turn off the location services and then turn On location services

### ISSUE THREAD

**Issue by amritmatharu** [transistorsoft/cordova-background-geolocation-lt#269]
## Android
* Plugin version: com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"
* Platform: iOS or Android
* OS version:
* Device manufacturer / model: Samsung S5
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): android 6.0.0
* Plugin config
backgroundGeolocation.configure({
				desiredAccuracy: 0,
				distanceFilter: 50,
				stationaryRadius: 25,
				locationUpdateInterval: 1000,
				foregroundService: false,
				autosync: true,
				debug: true,
				preventSuspend: true,
				heartbeatInterval: 60 // <-- every minute
			}
## Expected Behavior

It should detect if location services are turned on from off and provide the user current location
## Actual Behavior

It does not give user current location if I turned off the location services and then turn it on.
## Steps to Reproduce

1. I turn on the location service and open my app
2. I configured the plugin and start tracking
3. I called getCurrentLocation function and I got user current location in its success callback
4. Now, I turned off the location service and called getCurrentLocation function and now its error callback function is called with error code 1
5. Now, I turned on the location service but now its not calling its success callback with user's current location and going in error callback with same error

## Context

I need to check if location services are off and prompt user to turn it on. As soon as user turn the location services, it should give user current location if I call getCurrentLocation method.

**Comment by christocracy** [comment]
The plugin is far more adavanced than you're aware of.

See the the [providerchange](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#onproviderchangecallbackfn-failurefn) event.

**Comment by christocracy** [comment]
Btw, are you watching the plugin's logs in XCode?

**Comment by christocracy** [comment]
Also see [locationAuthorizationAlert](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-object-locationauthorizationalert)

**Comment by amritmatharu** [comment]
@christocracy , I have used the providerchange event but it is called once when location services are already turned ON but afterwards if I turned OFF or ON the location Services, it is not called. 

This is the reason I am not able to check if location services are ON or OFF.

Once I turned it OFF and again turned it ON, it never gives the user's current location but rather throws the errorcode 1.

Also, I tried to look for Java source files of this plugin for Android but I didn't get them.

Please suggest how can I resolve the above problem.

**Comment by christocracy** [comment]
The purpose of the providerchange event is to let you know when the state of location-services (i.e.  "Provider") *changes*.  I will attempt to verify this issue in the public version next week when I return from vacation.  It may have been fixed in the Premium Version (I did fix something with providerchange last week before I went on vacation)

Have you discovered what errorCode 1 means?

There is no point in attempting to determine the state of location-services in any other manner:  this is precisely what providerchange is for.

**Comment by christocracy** [comment]
And yes, providerchange is designed to fire at boot to let you know the *current* state of the location provider.

**Comment by amritmatharu** [comment]
@christocracy , do we have its free version to use since premium version is paid?

**Comment by christocracy** [comment]
Customers do not use this public Github repository, which contains only the **latest stable release**, updated typically every several months.

Customers are instructed to use the private Premium repository, which provides access to all the latest updates.

Talk to your product manager about getting granted access.
