### ISSUE TITLE
taskId is NULL

### ISSUE THREAD

**Issue by gogcam** [transistorsoft/cordova-background-geolocation-lt#27]
Hello

I'm using your background geolocation and it works but I have one problem with parameter taskId in success callback from getting position.
I've got the following code (relevant to this topic):

        function OnBackgroundPositionSuccess(position, taskId) {
            LE.log('OnBackgroundPositionSuccess: ' + taskId);
            
            var request: any = {};
            request.SerialNumber = _SerialNumber;
            request.Time = position.timestamp;
            request.Latitude = position.latitude;
            request.Longitude = position.longitude;
            request.Speed = position.speed;

            sendToWebservice(request, taskId);
        }

        function OnBackgroundPositionError(error) {
            LE.log('OnBackgroundPositionError');
        }

        bgGeo.configure(OnBackgroundPositionSuccess, OnBackgroundPositionError, {
            desiredAccuracy: 1,
            distanceFilter: 1,
            activityRecognitionInterval: 0,
            autoSync: false //,
            //useSignificantChangesOnly: true,
            //debug: true,
        });

My problem is that taskId is always NULL in function OnBackgroundPositionSuccess(). Parameter position on the other hand has the correct values. As you can see I send my requests manual to the webservice but I don't think this should affect taskId. Is there anything wrong in my configuration?

Any help would be great.
Thank you very much.

Best Regards,
gogcam

**Comment by christocracy** [comment]
Are you testing in the simulator?  Is it it null for the first location
only?

Btw, why do not let the plugin handle the http?

On Monday, October 26, 2015, gogcam <notifications@github.com> wrote:

> Hello
>
> I'm using your background geolocation and it works but I have one problem
> with parameter taskId in success callback from getting position.
> I've got the following code (relevant to this topic):
>
>     function OnBackgroundPositionSuccess(position, taskId) {
>         LE.log('OnBackgroundPositionSuccess: ' + taskId);
>
>         var request: any = {};
>         request.SerialNumber = _SerialNumber;
>         request.Time = position.timestamp;
>         request.Latitude = position.latitude;
>         request.Longitude = position.longitude;
>         request.Speed = position.speed;
>
>         sendToWebservice(request, taskId);
>     }
>
>     function OnBackgroundPositionError(error) {
>         LE.log('OnBackgroundPositionError');
>     }
>
>     bgGeo.configure(OnBackgroundPositionSuccess, OnBackgroundPositionError, {
>         desiredAccuracy: 1,
>         distanceFilter: 1,
>         activityRecognitionInterval: 0,
>         autoSync: false //,
>         //useSignificantChangesOnly: true,
>         //debug: true,
>     });
>
> My problem is that taskId is always NULL in function
> OnBackgroundPositionSuccess(). Parameter position on the other hand has the
> correct values. As you can see I send my requests manual to the webservice
> but I don't think this should affect taskId. Is there anything wrong in my
> configuration?
>
> Any help would be great.
> Thank you very much.
>
> Best Regards,
> gogcam
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/27>
> .
>


-- 
Snet form Gmail Mobile

**Comment by gogcam** [comment]
No, on different real devices (iOS 8 & 9). It's null everytime the event is fired.

I already had the implementation of a foreground geolocation service and with this also a stable function to call my webservice. So I didn't need to change a lot when using your plugin.

**Comment by christocracy** [comment]
I'll investigate null taskId

So, in case of no network, you're caching location yourself in localStorage
(or you're not interested in location history)?

Be aware that setting autoSync: false, and not manually executing #sync
method, the plugin is storing each recorded location to its own SQLite db
(which it automatically purges after #maxDaysToPersist expires.

Read the docs on #sync--when you execute that method without configuring an
#url, it will clear the db (as well as return the locations it deleted to
your callback)

On Monday, October 26, 2015, gogcam <notifications@github.com> wrote:

> No, on different real devices (iOS 8 & 9). It's null everytime the event
> is fired.
>
> I already had the implementation of a foreground geolocation service and
> with this also a stable function to call my webservice. So I didn't need to
> change a lot when using your plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/27#issuecomment-151068240>
> .
>


-- 
Snet form Gmail Mobile

**Comment by gogcam** [comment]
Thank you very much.

No, it's not important to me right now. Maybe I'll change it later to your http-handling if it's getting important.

I call sync() on another place, so SQLite db get's empty. Thank you for your hints!

**Comment by christocracy** [comment]
I see nothing wrong after booting a fresh clone of [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp).

I always see a valid `taskId` in the [location-callback](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/services.js#L108)

![](https://www.dropbox.com/s/02gb0fbulm1iwps/Screenshot%202015-10-26%2005.50.05.png?dl=1)

**Comment by gogcam** [comment]
Thank you for your investigation.
Did you use the same configuration as I use?
Do you have any other idea what could cause this problem?

Is it possible to count up taskId by myself and call #finish with it (like starting from 1 and increase it by 1 everytime location-callback is called)? I know this would be a hack.

I'm using Cordova 3.7.0 along with DevExtreme (DevExpress).

**Comment by christocracy** [comment]
Your config is suspect:
```
{
        desiredAccuracy: 1,  // <-- INVALID
        distanceFilter: 1,      
        activityRecognitionInterval: 0,  // <-- BAD IDEA
        autoSync: false //,
        //useSignificantChangesOnly: true,
        //debug: true,
    }
```

1.  `desiredAccuracy: 1` is invalid.  This is how my code decodes your [desiredAccuracy](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#param-integer-desiredaccuracy-0-10-100-1000-in-meters)
```
switch (accuracy) {
        case 1000:
            accuracy = kCLLocationAccuracyKilometer;
            break;
        case 100:
            accuracy = kCLLocationAccuracyHundredMeters;
            break;
        case 10:
            accuracy = kCLLocationAccuracyNearestTenMeters;
            break;
        case 0:
            accuracy = kCLLocationAccuracyBest;
            break;
        case -1:
            accuracy = kCLLocationAccuracyBestForNavigation;
            break;
        default:
            accuracy = kCLLocationAccuracyBest;
    }```

2.  `activityRecognitionInterval: 1`  This is a **really** bad idea.  I never considered anyone would actually set that so low.  You shouldn't set that any lower than `1000`ms.  Setting that to `1`ms is impossible for the code to handle.  `10000`ms is **fine**.  I'm going to enforce a minimum within my code to not allow anything < 1000.

**Comment by christocracy** [comment]
>Is it possible to count up taskId by myself and call #finish with it 

No.  You have no control over `taskId`

**Comment by christocracy** [comment]
re: `activityRecognitionInterval: 0`.  I see [in the docs](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#param-integer-millis-10000-activityrecognitioninterval) that it states "A value of 0 will result in activity detections at the fastest possible rate".

However, that comment applies to **Android** -- not iOS.  iOS uses a complete different activity-recognition system than Android.  I have to update my docs.

Use the value `activityRecognitionInterval: 10000`.

**Comment by gogcam** [comment]
I've changed my settings to what you have recommanded, but taskId still remains null.

It will be hard for me to provide you an example without DevExtreme. I could provide you my source code (for Visual Studio and DevExtreme), or an APK file if this would help in any way.

Could you see any other reason why taskId could be null? 

Thank you very much again!

**Comment by christocracy** [comment]
Show me your installed plugins

**Comment by gogcam** [comment]
<gap:plugin name="org.apache.cordova.splashscreen" version="0.3.4" onload="true" />
<gap:plugin name="com.phonegap.plugin.statusbar" version="1.1.0" onload="true" />
<gap:plugin name="com.devexpress.plugins.devextremeaddon" version="1.0.1" />
<gap:plugin name="org.transistorsoft.cordova.background-geolocation" />
<gap:plugin name="org.apache.cordova.geolocation" version="0.3.10" />

**Comment by christocracy** [comment]
?

**Comment by gogcam** [comment]
Edited my answer.

**Comment by christocracy** [comment]
Just as I suspected.  You have my **OLD**, [deprecated, unsupported version](https://github.com/christocracy/cordova-plugin-background-geolocation) installed `org.transistorsoft.cordova.background-geolocation`.  The repo where we're talking now is `com.transistorsoft.cordova.background.geolocation`.

- Remove the old version.
- Install the plugin from **THIS** repo.

**Comment by christocracy** [comment]
I see you're using my old plugin as a "Phonegap" plugin.

`gap:plugin name="org.apache.cordova.splashscreen" version="0.3.4" onload="true" />`

I no longer provide plugin updates to PhoneGap.  You won't find the new version of my plugin from this repo on Phonegap.  What people on PhoneGap do is submit my plugin as a "Private Plugin".

I don't know what support this DevExpress provides for uploading "private plugins" from a github repo, but that's what you require.

**Comment by gogcam** [comment]
Thank you very much. This seems to be the solution.
I will have a look with DevExpress how to add your github repo to my project, but I hope I will get this running. There won't be a chance that you add this again to PhoneGap? ;-)

Thanks again!

**Comment by christocracy** [comment]
No chance.  PhoneGap now requires a paid account to upload plugins.  Since
users can now add their own private plugins, it’s no longer required.

On Mon, Oct 26, 2015 at 10:29 AM, gogcam <notifications@github.com> wrote:

> Thank you very much. This seems to be the solution.
> I will have a look with DevExpress how to add your github repo to my
> project, but I hope I will get this running. There won't be a chance that
> you add this again to PhoneGap? ;-)
>
> Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/27#issuecomment-151156218>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by gogcam** [comment]
I'm now also able to add own private plugins to PhoneGap. When I try to add this git repo to private plugins, it says: "The Plugin ID specified is already being used by another user".

Do you know how other user handle this?
I know it's not directly related to this topic but maybe you can help here again?

Thank you very much.

**Comment by christocracy** [comment]
this is correct.  PhoneGap plugin IDs must be globally unique.

You must fork the repo and modify the plugin’s ID here
<https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L5>
and
submit your fork as a private plugin.

Set the plugin id to something like “com.*yourcompany*
.cordova.background-geolocation"

On Mon, Oct 26, 2015 at 11:47 AM, gogcam <notifications@github.com> wrote:

> I'm now also able to add own private plugins to PhoneGap. When I try to
> add this git repo to private plugins, it says: "The Plugin ID specified is
> already being used by another user".
>
> Do you know how other user handle this?
> I know it's not directly related to this topic but maybe you can help here
> again?
>
> Thank you very much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/27#issuecomment-151179945>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by gogcam** [comment]
Thank you for your great support. Work's perfect now and also taskId is now valid.
We will have a look if we are also going for Android.
