### ISSUE TITLE
On iOS, plugin reads location all the time when no schedule is active

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#270]
Even though there is no active schedule, the plugin with startSchedule() keeps reading the location from iOS for some reason (internal purposes?). The location active icon is shown in the header by iOS all the time.

## Your Environment
* Plugin version: 2.3.0
* Platform: iOS
* OS version: SE 10.2 sim and device
* Device manufacturer / model: Apple
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): 4.3.1

* Plugin config
║ -[TSScheduler parse:] 
(
    "TSSchedule[triggered: 0, 8:0 - 13:10, Days:4]"
)
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager setConfig:] 
{
    activityRecognitionInterval = 5000;
    activityType = 2;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    disableElasticity = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    enabled = 0;
    extras = 0;
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    headers =     {
      
    };
    heartbeatInterval = 60;
    isMoving = 0;
    locationAuthorizationRequest = Always;
    locationTimeout = 60;
    logLevel = 18446744073709551615;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 80;
    params =     {
    };
    pausesLocationUpdatesAutomatically = 0;
    preventSuspend = 0;
    schedule =     (
        "4 08:00-13:10"
    );
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnTerminate = 0;
    stopTimeout = 300;
    trackingMode = location;
    url = "http://127.0.0.1";
    useSignificantChangesOnly = 0;
}
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager stop] 
╚═══════════════════════════════════════════════════════════
🔴-[TSGeofenceManager stopMonitoringGeofences] 
🔴-[TSLocationManager stopUpdatingLocation] 
🔴-[TSLocationManager stopMonitoringBackgroundFetch] BackgroundFetch: OFF
🔴-[TSLocationManager stop] Stop monitoring significant-changes
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2017-02-04 16:58:23.778[30877:717402] - TSBackgroundFetch addListener: TSLocationManager
2017-02-04 16:58:23.781[30877:717402] - TSBackgroundFetch started
🎾-[TSScheduler start] ON

╔═══════════════════════════════════════════════════════════
║ -[TSScheduler findNextSchedule:] Day #7
╚═══════════════════════════════════════════════════════════
- Failed to find alarms on this day.  Trying tomorrow...

╔═══════════════════════════════════════════════════════════
║ -[TSScheduler findNextSchedule:] Day #1
╚═══════════════════════════════════════════════════════════
- Failed to find alarms on this day.  Trying tomorrow...

╔═══════════════════════════════════════════════════════════
║ -[TSScheduler findNextSchedule:] Day #2
╚═══════════════════════════════════════════════════════════
2017-02-04 16:58:23.790[30877:717402] THREAD WARNING: ['BackgroundGeolocation'] took '11.958984' ms. Plugin should use a background thread.
- Failed to find alarms on this day.  Trying tomorrow...

╔═══════════════════════════════════════════════════════════
║ -[TSScheduler findNextSchedule:] Day #3
╚═══════════════════════════════════════════════════════════
- Failed to find alarms on this day.  Trying tomorrow...

╔═══════════════════════════════════════════════════════════
║ -[TSScheduler findNextSchedule:] Day #4
╚═══════════════════════════════════════════════════════════
✅ Found schedule: TSSchedule[triggered: 0, 8:0 - 13:10, Days:4]
ℹ️__25-[GeofenceDAO destroyAll]_block_invoke 
🔵-[TSLocationManager addGeofences:success:error:] 
ℹ️-[GeofenceDAO doInsert:params:] 13
🔵-[TSScheduler evaluate] TSSchedule[triggered: 0, 8:0 - 13:10, Days:4]
🔵-[TSScheduler evaluate] TSSchedule[triggered: 0, 8:0 - 13:10, Days:4]
⋯-[TSDBLogger db_save] Log committed
🔵-[TSScheduler evaluate] TSSchedule[triggered: 0, 8:0 - 13:10, Days:4]

## Expected Behavior
No background location fetch until a schedule is active.

## Actual Behavior
Background location fetch all the time.

**Comment by christocracy** [comment]
Location is not fetched while scheduler is activated.  What makes you think this is so?

Your logs clearly show location-services being turned off.

**Comment by JohnyBoy1234** [comment]
That's why this is a bug.

iOS shows that the app is requesting location constantly. For example if I stop the plugin, iOS stops indicating the app is requesting the location.

But as you can see in the logs:

[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2017-02-04 16:58:23.778[30877:717402] - TSBackgroundFetch addListener: TSLocationManager
2017-02-04 16:58:23.781[30877:717402] - TSBackgroundFetch started

so for some reason it's actually fetching locations. It's not actually doing anything with it as far as I can tell ie. it's not POSTing it to a server.


Maybe it's this change that you did?

[Changed] When iOS Scheduler is engaged and a scheduled OFF event occurs, the plugin will continue to monitor significant-changes, since background-fetch events alone cannot be counted on. This will guarantee the plugin evaluates the schedule each time the device moves ~ 1km. This will have little impact on power consumption, since these sig.change events will not be persisted or POSTed, nor will they even be provided to Javascript.

**Comment by christocracy** [comment]
[Background-fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch) does **not** fetch *locations*.  It's an iOS API that will simply awakens your app in the background, about every 15min, providing *exactly* 30s of bg time before putting your app to sleep again.

Fetch events are **crucial** -- the plugin uses the events to **evaluate the schedule**.
