### ISSUE TITLE
locationAuthorizationAlert add option to disable this alert

### ISSUE THREAD

**Issue by grundmanise** [transistorsoft/cordova-background-geolocation-lt#271]
Hi,

could you please add an option (pass false?) to disable `locationAuthorizationAlert`. I need this because I am displaying a custom locationAuthorizationAlert screen with a custom design.

**Comment by christocracy** [comment]
In the Premium Version, I've a new `status` param to the `providerchange` method.

When `AUTHORIZATION_STATUS_DENIED` is detected, you can execute `#stop`:  this will prevent alert from showing and you can show your own there.

```Javascript
bgGeo.on('providerchange', function(provider) {
    console.log('  status: ', provider.status);

    switch(provider.status) {
        case bgGeo.AUTHORIZATION_STATUS_DENIED:
            // Android & iOS
            console.log('- Location authorization denied');
            bgGeo.stop();  // <----------- Call stop and plugin won't show Alert
            alert("My Custom Alert message here");  
            break;
        case bgGeo.AUTHORIZATION_STATUS_ALWAYS:
            // Android & iOS
            console.log('- Location always granted');
            break;
        case bgGeo.AUTHORIZATION_STATUS_WHEN_IN_USE:
            // iOS only
            console.log('- Location WhenInUse granted');
           bgGeo.start();    // <------------- call start again.
            break;
    }
});
```

**Comment by christocracy** [comment]
`status` param mentioned above is now available in latest release `2.4.0`.

**Comment by dimitriscsd** [comment]
Hello.

I am trying the above solution on the latest version 2.14.0 with calling bgGeo.stop() but it's not working. The dialog still comes up.

The fact is that when I'm calling this, the background automated geolocation is already turned off. So I'm guessing stop doesn't do anything.

Is there any other way to stop the default alert?

**Comment by christocracy** [comment]
Searching the docs for "locationAuthorizationAlert", you would find:

[`disableLocationAuthorizationAlert`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#disablelocationauthorizationalert)

**Comment by dimitriscsd** [comment]
Wow. I searched numerous times. I'm not sure how I missed that. Only managed to find this issue.

Thank you very much for the help. I'll check it out.
