### ISSUE TITLE
my app is sending to server an empty array! Help me, please!

### ISSUE THREAD

**Issue by kent2011981** [transistorsoft/cordova-background-geolocation-lt#272]
## Expected Behavior

your sampleApp is working in background, but it's sending to my php server an empty arrays.

my php code : 

mysql_query("INSERT INTO os_test (`postdata`) VALUES ('".json_encode($_POST)."')");

I'm activated 'backgroung geolocation', configured for fastest intervals, AND (0.0)
![screenshot_285](https://cloud.githubusercontent.com/assets/18715452/22733765/202ff592-ee2e-11e6-8eec-ffabd7abd2e3.png)

**Comment by christocracy** [comment]
The data is there.  [PHP is dumb](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/2)
