### ISSUE TITLE
On iOS, plugin reads location all the time when no schedule is active

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#278]
This is still an issue. Even though there is no active schedule, the plugin with startSchedule() keeps reading the location from iOS for some reason (internal purposes?)
**The location active icon is shown in the header by iOS all the time.**
**Settings -> Privacy -> Location Services -> App is shown with purple icon indicating location is being used**

## Your Environment

    Plugin version: 2.3.0

    Platform: iOS

    OS version: SE 10.2 sim and device

    Device manufacturer / model: Apple

    Cordova version (cordova -v): 6.4.0

    Cordova platform version (cordova platform ls): 4.3.1

    Plugin config
    ║ -[TSScheduler parse:]
    (
    "TSSchedule[triggered: 0, 8:0 - 13:10, Days:4]"
    )
    ╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager setConfig:]
{
activityRecognitionInterval = 5000;
activityType = 2;
autoSync = 1;
autoSyncThreshold = 0;
batchSync = 0;
debug = 0;
desiredAccuracy = "-1";
disableElasticity = 0;
disableMotionActivityUpdates = 0;
disableStopDetection = 0;
distanceFilter = 10;
enabled = 0;
extras = 0;
geofenceInitialTriggerEntry = 1;
geofenceProximityRadius = 1000;
headers = {

};
heartbeatInterval = 60;
isMoving = 0;
locationAuthorizationRequest = Always;
locationTimeout = 60;
logLevel = 18446744073709551615;
maxBatchSize = "-1";
maxDaysToPersist = 1;
maxRecordsToPersist = "-1";
method = POST;
minimumActivityRecognitionConfidence = 80;
params =     {
};
pausesLocationUpdatesAutomatically = 0;
preventSuspend = 0;
schedule =     (
    "4 08:00-13:10"
);
schedulerEnabled = 0;
startOnBoot = 1;
stationaryRadius = 25;
stopAfterElapsedMinutes = "-1";
stopDetectionDelay = 0;
stopOnTerminate = 0;
stopTimeout = 300;
trackingMode = location;
url = "http://127.0.0.1";
useSignificantChangesOnly = 0;

}
## Expected Behavior
No background location fetch until a schedule is active.

## Actual Behavior
Background location fetch all the time.

**Comment by christocracy** [comment]
It's not fetching location *all the time*.  While the scheduler is enabled, the plugin registers a listener to the low-power ["significant changes API"](https://developer.apple.com/reference/corelocation/cllocationmanager/1423531-startmonitoringsignificantlocati?language=objc).  This is another mechanism the plugin uses to evaluate the schedule periodically.

```Obj-c
- (void) stop
{
    .
    .
    .
    // Stop monitoring BackgroundFetch if Scheduler isn't active.
    TSScheduler *scheduler = [TSScheduler sharedInstance];
    if (!scheduler.enabled) {   
        [self stopMonitoringBackgroundFetch];
        // Stop monitoring Significant changes
        [locationManager stopMonitoringSignificantLocationChanges];
        DDLogOff(@"Stop monitoring significant-changes");
    }
}
```
And when a significant-location *is* recorded:
```Obj-c
-(void) locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray *)locations
{
    .
    .
    .
    // significantChange handler when plugin is disabled and scheduler is activated.  This provides an additional mechanism to evaluate schedules in addition to background-fetch.
    if (settings.schedulerEnabled) {
        if (!settings.enabled) {
            if (settings.debug) {
                TSLog *log = [TSLog sharedInstance];
                [log playSound:backgroundFetchSound];
                [log notify:@"📅 Evaluate schedule in SLC event."];
            }
        }
        [[TSScheduler sharedInstance] evaluate];
    }
    
    if (!isUpdatingLocation && !settings.useSignificantChangesOnly) {
        // If this location was recorded during a schedule OFF event, bail out.  do not persist the location.
        return;
    }
```

You'll see the schedule being evaluated in the "significant location change" events like so:
![](https://www.dropbox.com/s/1wdkzy276bs0vu2/Screenshot%202017-02-09%2018.29.26.png?dl=1)

"SLC" = "**S**ignificant **L**ocation **C**hange"

**Comment by JohnyBoy1234** [comment]
but from a user + privacy + battery perspective this doesn't make any sense. 
If tracking should be enabled (scheduled) between 1-2 pm on Monday only... then why would the plugin/app be listening (IOS showing the user that it is) for location all 7 days a week non-stop.
It should not be listening even for significant location changes while no schedule is activated.
To me this is a big problem. If you're saying scheduling on IOS can only work with this happening 24/7 because of technical reasons then I think that it's a major limitation and should be warned in the docs.

**Comment by christocracy** [comment]
The significant-changes API is *extremely* low-power.  The increased power usage is *negligible*.

If the plugin didn't do this, you'd be writing issues about "The schedule is not activating".

I suggest you educate yourself on ["iOS significant changes"](https://www.google.ca/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=ios%20significant%20changes&oq=ios%20significant%20changes&aqs=chrome..69i57j0.4499j0j4).

There is **no** way I'm going to disable this.  It's a crucial mechanism to the schedule.  This issue is closed.

**Comment by JohnyBoy1234** [comment]
I'm saying the user knows and sees when an app uses his location. IOS makes it obvious. That's why I'm saying this is a big limitation. Users believe when IOS shows an app using their location, they would never understand technical details and that it's tracking them 'but not really'...
So your scheduling on IOS is actually driven by the location not the other way around.
You're saying: have we moved? No. have we moved? No. have we moved? Yes. Should a schedule be active? No. Have we moved? No. Have we moved? No. Have We moved? Yes. Should a schedule be active? Yes.

Instead of actually scheduling a date/time to start monitoring for significant changes, then tracking and a date/time to end monitoring/tracking.

**Comment by JohnyBoy1234** [comment]
On Android for example it's must better as it shows the app using the user's location only during an active schedule, not 24/7.

**Comment by christocracy** [comment]
If iOS would allow me to schedule an Alarm like Android's `AlarmManager`, that'd be great.

It doesn't.  This case is closed.

**Comment by JohnyBoy1234** [comment]
but why does the significant changes need to be monitored when no schedule is active? isn't the background fetch enough to check the time and then it should enable the SLC once a schedule is active or close enough even -1 hour or something?

**Comment by JohnyBoy1234** [comment]
ie. keep doing what you're doing background fetch + SLC but only from a certain amount of time prior to a schedule starting and up until a schedule end time. the rest of the time background fetch only...

**Comment by christocracy** [comment]
>but why does the significant changes need to be monitored when no schedule is active? 

To determine when to activate the *next* schedule.

>isn't the background fetch enough

It's not.  The timing of background-fetch events can vary widely based upon the user's pattern of usage with your app.  They might fire every 15min, they might fire every hour or every 5 hours.

>then it should enable the SLC once a schedule is active or close enough even -1 hour or something?

I will research this.

**Comment by christocracy** [comment]
SLC is **not** powering any radios or *actively* listening.  It's a passive mechanism.  When the user's device changes cell-towers iOS checks to see if *any* app on the user's device is listening for SLC events, and *presumably* fetch a location from GPS (since the location from a cell-tower typically have accuracy ~1000).  This single location will be provided to *all* apps.

**Comment by JohnyBoy1234** [comment]
I understand the technical reasons now. All I'm saying is from an average user's *perspective*, he will believe (with IOS 'confirming') that the app is using his location all the time. He will believe IOS, he will not believe 'me' that the app is not 'really' using his location all the time.

**Comment by christocracy** [comment]
Background-fetch listeners are ceased if user *manually* terminates the app but  SLC listeners are **not**.

If the user terminates the app while its in the background (ie: double-tap [home] and swipe away), the app receives no `onAppTerminate` signal (ie: no last-breath SLC listening).

Constant SLC is the only thing capable of keeping the Scheduler alive.

Starting up SLC in a fetch event when next schedule time is approaching (eg: within next 1 or 2 hours) would be like driving without a seat belt.

The *only* other option would be to create a geofence (eg: 500m) around the current position and evaluate the schedule whenever the geofence triggers.  If no schedule is active, a new stationary-geofence would be created.  Like a frog hopping between lily pads.  This is effectively the same as using SLC.

**Comment by JohnyBoy1234** [comment]
That is just brutal...

Thanks for looking into this

**Comment by christocracy** [comment]
I've spent nearly 4 years of my career dealing with the intricacies of [iOS Background Execution](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html).

`background-geolocation` [began with iOS 6](https://github.com/christocracy/cordova-plugin-background-geolocation/commit/6b1410b26cd6e8c5ecbe3b27029d26a0fe4a4e74) on Sept 25 2013 and `background-fetch` [soon after](https://github.com/transistorsoft/cordova-plugin-background-fetch/commit/fab5f4293e0c3e9663aba1efd6c6bf44bad157f7) on Oct 17, 2013.

Much of this stuff is not well documented.  I've learned it through hundreds hours of field-testing.
