### ISSUE TITLE
Not sending onLocation event when moving

### ISSUE THREAD

**Issue by Frumba** [transistorsoft/cordova-background-geolocation-lt#279]
## Your Environment
* Plugin version: master
* Platform: Android
* OS version: 7.0
* Ionic 1

Hello,

I'm actually trying to use the plugin with the free version.

I use the following config to configure the plugin:

```
// Geolocation config
        desiredAccuracy              : 0,
        distanceFilter               : 5,
        stationaryRadius             : 25,
        locationUpdateInterval       : 5000,
        fastestLocationUpdateInterval: 1000,
        disableElasticity            : true,
        locationAuthorizationRequest : "WhenInUse",

        // Activity Recognition config
        activityType               : 'AutomotiveNavigation',
        activityRecognitionInterval: 2000,
        stopTimeout                : 5,
        foregroundService          : false,

        // Application config
        debug          : true,
        stopOnTerminate: true,
        startOnBoot    : true
```

The problem is when i move i never receive onlocation event do you have any idea why?

I may have missed some configuration to make it work?

Thank you in advance!

Paul-louis

**Comment by christocracy** [comment]
You closed this.  What was it?

**Comment by Frumba** [comment]
It finally worked so I didn't want to bother you for nothing.

Thank you!
