### ISSUE TITLE
The plugin is not going to install in project.

### ISSUE THREAD

**Issue by ssharmass** [transistorsoft/cordova-background-geolocation-lt#28]
Hi, 
  Is this now paid plugin , not going to install until we pay.

Regards
Shivam

**Comment by christocracy** [comment]
iOS is free.  Pay for Android.

On Tuesday, October 27, 2015, ssharmass <notifications@github.com> wrote:

> Hi,
> Is this now paid plugin , not going to install until we pay.
>
> Regards
> Shivam
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/28>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
As stated in [README](https://github.com/transistorsoft/cordova-background-geolocation-lt#premium-version-ios)

>This repo hosts the iOS platform available in the Premium Version. Android functionality is available 
>only in the Premium Version.
