### ISSUE TITLE
Android app killed even when put in background

### ISSUE THREAD

**Issue by Frumba** [transistorsoft/cordova-background-geolocation-lt#281]
Hello,

I'm currently having a problem with the application in foreground on android being killed 2/3 min after being put in background on a phone that has 4 gb of ram (One plus 3). Do you have any idea why it's killing itself?

Here is the configuration:

```
// Geolocation config
        desiredAccuracy              : 0,
        distanceFilter               : 5,
        stationaryRadius             : 25,
        locationUpdateInterval       : 5000,
        fastestLocationUpdateInterval: 1000,
        disableElasticity            : true,

        // iOs options
        locationAuthorizationRequest      : Always,
        locationAuthorizationAlert        : If you change location permission the app may not work anymore,
        pausesLocationUpdatesAutomatically: false,

        // Android options
        foregroundService: false,
        notificationText : Shyft location service is running,
        notificationIcon : drawable/icon,

        // Activity Recognition config
        activityType               : 'AutomotiveNavigation',
        activityRecognitionInterval: 2000,
        stopTimeout                : 5,

        // Application config
        debug          : false,
        stopOnTerminate: true,
        startOnBoot    : true
```

Thank you very much!

**Comment by christocracy** [comment]
Show me logs of this happening while watching 
```
$ adb logcat
```

**Comment by Frumba** [comment]
I had some log given by the app via the library but i don't have them anymore and i don't reproduce this bug every time so it's very difficult to identify the root cause.

One thing is sure, it's only happening when i'm moving while the app is running in background.

I had a log once showing a log 'Mainactivity was destroyed' when the app crash and after that one the logs was just stopping when the app was killed.

I'm trying to reproduce the bug but it's not easy..

**Comment by christocracy** [comment]
When you keep observing, you'll find that Android is killing your app due to memory pressure due to other apps.

The **only** way to prevent the OS from terminating your app is by signalling [`foregroundService: true`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#param-boolean-foregroundservice-false).  Yes, the notification is required.  **No** there's no way to remove it.

**Comment by Frumba** [comment]
Ok sorry the foregroundservice value you're seeing in the config is not what i'm using because depending on some configuration i enable or not.

So when i'm testing the app take into account that it's enable.

That's the reason i don't know why the app is being killed with this configuration enabled.

**Comment by christocracy** [comment]
Without logs, I cannot speculate upon anything.

**Comment by srsarcasmo** [comment]
Friend, this eplugin can put your app in the background; Even when you lock the phone; Just start it after DeviceReady; This plugin returns you locations too ... but it is only available on android;


> https://github.com/louisbl/cordova-plugin-gpslocation

**Comment by christocracy** [comment]
My plugin is about 100* more complex and feature-packed than that.

**Comment by christocracy** [comment]
I've been working on this plugin for nearly 4 years.

**Comment by christocracy** [comment]
And hasn't been touched in 2 years.  It's garbage.  The best tracking plugin for both iOS and Android is mine.

**Comment by Frumba** [comment]
I could never reproduced the bug so i'll close the issue.
