### ISSUE TITLE
OS platform plugin operation doubts

### ISSUE THREAD

**Issue by srsarcasmo** [transistorsoft/cordova-background-geolocation-lt#282]
## Your Environment
* what is it for:
StationaryRadius: 50 ?, locationUpdateInterval: 1000?
FastestLocationUpdateInterval: 5000?

Because I want to set a callback execution time in 5 minutes while being in the background;

**Comment by christocracy** [comment]
https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation

**Comment by christocracy** [comment]
for iOS you **cannot** do time-based geolocation.  it's strictly *distance-based* (eg: `distanceFilter`).

`locationUpdateInterval` and `fastestLocationUpdateInterval` are Android-only.
