### ISSUE TITLE
 Doubts of operation

### ISSUE THREAD

**Issue by srsarcasmo** [transistorsoft/cordova-background-geolocation-lt#283]
## Your Environment
* Plugin version: 2.0
* Platform: iOS
* OS version: 6
* Device manufacturer / model: at&t
* Cordova version (`cordova -v`):4.03
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
![ios debug](https://cloud.githubusercontent.com/assets/20671621/22992427/4e1723b6-f385-11e6-96f7-3e1f48da9b21.png)

**Comment by christocracy** [comment]
I have no idea what you're trying to tell me.

**Comment by srsarcasmo** [comment]
I'm using your friend plugin; Is working in the background but is not respecting the time interval I have set for each answer / callback .. for example I want to receive a callback every 10 minutes but I do not know how to configure the plugin

**Comment by srsarcasmo** [comment]
![screenshot_2017-02-15-13-58-29 1](https://cloud.githubusercontent.com/assets/20671621/22992957/e211ed52-f386-11e6-975d-e67311fa7f4b.png)

**Comment by christocracy** [comment]
iOS is *strictly* distance-based.  You don't get to say "I want a location every x minutes".  You say "I want a location every 500 meters" (ie: `distanceFilter`).

**Comment by srsarcasmo** [comment]
Now I understand, very well thank you friend .. but give me an idea to solve my problem or if you know in some way that your plugin can help me in this

**Comment by srsarcasmo** [comment]
And these configuration options so that they work? 
*locationUpdateInterval: 1000,
 *fastestLocationUpdateInterval: 5000,

**Comment by christocracy** [comment]
Are you going to purchase Android?  Those are *android-only* configs.

**Comment by srsarcasmo** [comment]
![android debug](https://cloud.githubusercontent.com/assets/20671621/22993152/90f70ec4-f387-11e6-9d43-b18f0c8d5cb1.png)

**Comment by christocracy** [comment]
Stop sending meaningless images.

**Comment by srsarcasmo** [comment]
Look in android I already have it working and it returns the times with locations to as I want it

**Comment by christocracy** [comment]
If you're not going to purchase Android, I have **no motivation** to offer you such prompt support.
