### ISSUE TITLE
PlugIn returns diferent UUIDs every time

### ISSUE THREAD

**Issue by lmchacon** [transistorsoft/cordova-background-geolocation-lt#284]
## Your Environment
* Plugin version:2.4.0
* Platform: iOS or Android Android
* OS version:5.1
* Device manufacturer / model:Motorola Model G
* Cordova version (`cordova -v`):PhoneGap cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)
* Cordova platform version (`cordova platform ls`): Sorry do not know how to get that info from Adobe Web Phone Gap
* Plugin config
bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 50,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 5000,

        // Activity Recognition config
        activityType: 'AutomotiveNavigation',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,

        // Application config
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true,

        // HTTP / SQLite config
        url: 'http://www.itlabs.com.mx/geoloc/geoecho.php?device=1234',
        method: 'POST',
        autoSync: true,
        maxDaysToPersist: 1,
        headers: {
            "X-FOO": "bar"
        },
        params: {
            "auth_token": "maybe_your_server_authenticates_via_token_YES?"
        }

## Expected Behavior

UUID should be unique to the phone

## Actual Behavior

UUID is diferent every time we get a new location (HTTP)
## Steps to Reproduce

1.
2.
3.
4.

## Context

Get the plug inn in background to keep the location updated via HTTP. It works fine.

**Comment by christocracy** [comment]
This `uuid` has nothing to do with the *device*.  The plugin attaches a `uuid` to *each* location for your convenience, so you have the option of detecting if the plugin ever sends the same location twice.

It's a way for the client and the server to share a common "id".  The plugin references this `uuid` in its logs:

```
✅ LOCKED: 5BC5FC4C-DE7A-411E-A8AE-7324DEBD8264
🔵-[TSHttpService doPost:] HTTP Response: 200
✅ DESTROY: 5BC5FC4C-DE7A-411E-A8AE-7324DEBD8264
```

This show the plugin "locking" a particular record, `POST`ing that to your server, your server responding "200 OK", and the plugin removing its copy.

It's very useful in debugging.

In the **[Premium Version](http://www.transistorsoft.com/shop/products/cordova-background-geolocation)**, I've introduced new HTTP JSON template feature where you can define your own HTTP schema, and choose to ignore any particular attribute, such as `uuid`, if you wish:

eg:

```javascript
bgGeo.configure({
  url: 'http://my-url/locations',
  httpRootProperty: 'data',
  locationTemplate: '{ "lat":{{latitude}}, "lng":{{longitude}} }'
});
```

| Tag | Type | Description |
|-----|------|-------------|
| `{{latitude}}` | `Float` ||
| `{{longitude}}` | `Float` ||
| `{{speed}}` | `Float` | Meters|
| `{{heading}}` | `Float` | Degress|
| `{{accuracy}}` | `Float` | Meters|
| `{{altitude}}` | `Float` | Meters|
| `{{altitude_accuracy}}` | `Float` | Meters|
| `{{timestamp}}` | `String` |ISO-8601|
| `{{uuid}}` | `String` |Unique ID|
| `{{event}}` | `String` |`motionchange|geofenee|heartbeat`
| `{{odometer}}` | `Float` | Meters|
| `{{activity.type}}` | `String` | `still|on_foot|running|on_bicycle|in_vehicle|unknown`|
| `{{activity.confidence}}` | `Integer` | 0-100%|
| `{{battery.level}}` | `Float` | 0-100%|
| `{{battery.is_charging}}` | `Boolean` | Is device plugged in?|

**Comment by lmchacon** [comment]
Chris:

Sorry, my mistake.
Thank you for your help.
Will get the Premium Version as soon as we decide hoy many app will be needed.

Best regards,

Luis
