### ISSUE TITLE
onSchedule incorrectly called after onGeofence

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#288]
When a schedule starts and then immediately detects that a geofence has been entered, it then calls onGeofence callback and 20sec to a minute later the onSchedule callback. This is wrong since the sequence is actually reversed to what happened chronologically.

For example, I'm waiting for a geofence to be hit any time during a schedule, so I stop() tracking in the onGeofence callback but 30 seconds later the plugin starts tracking again by itself and calls the onSchedule callback ...

Plugin version: 2.3.0
Platform: Android
OS version: 5.1.1
Device manufacturer / model: Nexus 4
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): android 6.0.0

**Comment by christocracy** [comment]
Logs please.

**Comment by JohnyBoy1234** [comment]
logs??? you go get some sleep first
