### ISSUE TITLE
can not stop() schedule auto-start from .configure() success callback

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#289]
Given a configuration with a schedule in progress, plugin will start tracking automatically some time after configure() is called.
But the success callback seems to be called before the actual start() so if I try to stop() tracking in the configure() callback, it doesn't work.

Plugin version: 2.3.0
Platform: Android
OS version: 5.1.1
Device manufacturer / model: Nexus 4
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): android 6.0.0

**Comment by christocracy** [comment]
Can you provide a simple test-case please?

**Comment by sweebee** [comment]
Somehow the console.log messages don't show up in the xcode log.

This is the geolocation log file:

```
2017-03-11 12:42:14.546 🔵-[Settings init] Settings loaded

2017-03-11 12:42:14.556 🔵-[Settings setOdometer:] 0

2017-03-11 14:22:44.908 🔵-[Settings init] Settings loaded

2017-03-11 14:22:44.910 🔵-[Settings setOdometer:] 46

```

**Comment by christocracy** [comment]
Closed for lack of response.
