### ISSUE TITLE
GPS taking some time to "warm up"?

### ISSUE THREAD

**Issue by mattgrande** [transistorsoft/cordova-background-geolocation-lt#29]
I've been noticing that some of the results I'm getting back show a bit of a "warm up" time.

[See here for example](http://i.imgur.com/Hnoz8SA.jpg): The car was travelling Westward, and you can see there's a "gap" near the start of about 15 minutes. I've seen it as long as 30 minutes before I start getting reliable data on some devices.

Since this is intermittent, I'm guessing it's a iOS issue, but have you (or anyone else) seen this before? Is there anything I can do to prevent it?

**Comment by christocracy** [comment]
This is the nature of iOS.  It needs a cell-tower switch event to initially trigger its stationary geofence.  Nothing can be done.

**Comment by christocracy** [comment]
Android performs far better in this regard, needing only a few meters of
movement.

On Tuesday, October 27, 2015, Matt Grande <notifications@github.com> wrote:

> I've been noticing that some of the results I'm getting back show a bit of
> a "warm up" time.
>
> See here for example <http://i.imgur.com/Hnoz8SA.jpg>: The car was
> travelling Westward, and you can see there's a "gap" near the start of
> about 15 minutes. I've seen it as long as 30 minutes before I start getting
> reliable data on some devices.
>
> Since this is intermittent, I'm guessing it's a iOS issue, but have you
> (or anyone else) seen this before? Is there anything I can do to prevent it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/29>
> .
>


-- 
Snet form Gmail Mobile

**Comment by mattgrande** [comment]
Ahh, that explains the variable time in switching. Thanks.

PS - If I get the pro version for Android, will I need to make code changes to my configure/start/finish code?

**Comment by christocracy** [comment]
You won't need to change anything in `#config, #start, #finish`.  You'll have to add a few Android-specific configs is all.
