### ISSUE TITLE
Is it possibel to set the selectable privacy options on ios8+?

### ISSUE THREAD

**Issue by Twois** [transistorsoft/cordova-background-geolocation-lt#291]
* Platform: iOS
* OS version: 8+
* Device manufacturer / model:
* Cordova version (`cordova -v`): 6.5

Hi, it is possible to remove "while using the app" option at location privacy setting?

**Comment by christocracy** [comment]
You'll have to remove the description from your `.plist` in XCode.

![](https://www.dropbox.com/s/gsplulz14j921f5/Screenshot%202017-02-27%2009.37.40.png?dl=1)

**Comment by Twois** [comment]
I mean, not just the description i would like to remove even the the option, so i want to only never and always option be selecteble. What you suggested will do this?

Other hand it will be possible to set this from config.xml or as parameter from js?

**Comment by Twois** [comment]
Okey, this is solved, but i have to remove manually after every changes, because that field automatically generated into the plist file when i run cordova platfrom ios or cordova emulator ios... only work if i build from xcode.

**Comment by christocracy** [comment]
Yes, you'll have to manually manage your `.plist` on your own.  It's not possible to configure this at the plugin level.

You can your own custom `/hooks/` script to automate your `.plist` management.
