### ISSUE TITLE
Not able to merge with latest code

### ISSUE THREAD

**Issue by farrukhsubhani** [transistorsoft/cordova-background-geolocation-lt#292]
We have a repository forked at https://github.com/SoftwareStudio/cordova-background-geolocation
I am new developer added to this company and wanted to update my branch with latest code. I am not able to compare from Transistorsoft master branch. I can see commits on master under network tab and can see that it has moved forward.
![june2016_network graph softwarestudio cordova background geolocation](https://cloud.githubusercontent.com/assets/2126566/23370198/dba3495a-fd0b-11e6-8ad4-77901b70711b.png)
As I understand you now have public repository and we can use our license to compile plugin from there so is that the way forward or should we keep a fork of private repo to get access to latest code in future.

**Comment by christocracy** [comment]
You only get access to private repo for 1 year.  If you don't you pay the yearly maintenance fee, you're remove from the private repo and you must now use *this* public repo.
