### ISSUE TITLE
Plugin not making any sounds on start with debug is true

### ISSUE THREAD

**Issue by aliexalter** [transistorsoft/cordova-background-geolocation-lt#293]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 5.0
* Device manufacturer / model: Samsung Note 3
* Cordova version (`cordova -v`): cli-6.5.0
* Cordova platform version (`cordova platform ls`): 6.1.2
* Plugin config

## Expected Behavior
Application should produce debug sound.

## Actual Behavior
Application is not producing any sounds. while debug=true;

## Context
Just trying to start the plugin. With debug true to hear the sounds.
`var bgGeoOptions = {
    desiredAccuracy: 0,
    stationaryRadius:0,
    distanceFilter: 0,
    locationUpdateInterval: 1000, 
    fastestLocationUpdateInterval: 1000,
    activityRecognitionInterval: 1000,
    heartbeatInterval: 60,
    stopDetectionDelay: 5,  // Wait x minutes to engage stop-detection system
    stopTimeout: 10,  // Wait x miutes to turn off location system after stop-detection
    pausesLocationUpdatesAutomatically: false,
    minimumActivityRecognitionConfidence: 80, 
    stopOnTerminate: false,              // <-- [Android] Allow the background-service to run headless when user closes the app.
    startOnBoot: false,
    batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
    autoSync: false,
    debug: true,
    disableStopDetection: true,
    foregroundService: true  
};`
`bgGeo.on('location', callbackFn, failureFn);

      bgGeo.on('motionchange', function(isMoving, location, taskId) {
        if (isMoving) {
          console.log("Device has just started MOVING at @ "+(new Date).toLocaleTimeString());
        } else {
          console.log("Device has just STOPPED at @ "+(new Date).toLocaleTimeString());
        }
      });

      // BackgroundGeoLocation is highly configurable.
      bgGeo.configure(bgGeoOptions, function(state) {
          // This callback is executed when the plugin is ready to use.
          console.log("BackgroundGeolocation ready");
          if (!state.enabled) {
              bgGeo.start(function(state){
                console.log("BackgroundGeolocation started");
              });
          }
      });`

## Debug logs
- Android: $ adb logcat
D/LocationManagerService(  933): getProviders()=[passive, gps, network]
D/LocationManagerService(  933): request 296f19cb fused Request[ACCURACY_BLOCK fused requested=0 fastest=0] from com.apploft.xxxxx(10257)
D/LocationManagerService(  933): provider request: fused ProviderRequest[ON interval=0]
I/LocationManagerService(  933): remove 296f19cb by com.apploft.xxxxx
D/LocationManagerService(  933): provider request: fused ProviderRequest[OFF]
D/LocationManagerService(  933): getProviders()=[passive, gps, network]
D/LocationManagerService(  933): request 1067c8c1 fused Request[ACCURACY_FINE fused requested=0 fastest=0] from com.apploft.xxxxx(10257)
D/LocationManagerService(  933): provider request: fused ProviderRequest[ON interval=0]
I/LocationManagerService(  933): remove 1067c8c1 by com.apploft.xxxxx
D/LocationManagerService(  933): provider request: fused ProviderRequest[OFF]
D/LocationManagerService(  933): getProviders()=[passive, gps, network]
D/ActivityManager(  933): caller:null, r.packageName :com.google.android.gms
D/LocationManagerService(  933): request 95387a7 fused Request[ACCURACY_FINE fused requested=0 fastest=0] from com.apploft.xxxxx(10257)
D/LocationManagerService(  933): provider request: fused ProviderRequest[ON interval=0]
D/ActivityManager(  933): caller:null, r.packageName :com.google.android.gms

**Comment by christocracy** [comment]
As you can see in the logs, the plugin is not even referenced.  No wonder it's not making any sounds.  You're not even talking to it.

**Comment by aliexalter** [comment]
I see this before in log I don't have SQLlite table called geofences it must be the plugin

I/TSLocationManager( 2889): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager( 2889): ╔═════════════════════════════════════════════
I/TSLocationManager( 2889): ║ BackgroundGeolocation adapter
I/TSLocationManager( 2889): ╠═════════════════════════════════════════════
D/TSLocationManager( 2889): [c.t.l.d.s.SQLiteLocationDAO prune] 
D/TSLocationManager( 2889):   ℹ️  PRUNE -1 days
E/SQLiteLog( 2889): (1) no such table: geofences
W/System.err( 2889): android.database.sqlite.SQLiteException: no such table: geofences (code 1): , while compiling: SELECT count(*) AS count FROM geofences
W/System.err( 2889): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
W/System.err( 2889): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
W/System.err( 2889): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:670)
W/System.err( 2889): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
W/System.err( 2889): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
W/System.err( 2889): 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
W/System.err( 2889): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
W/System.err( 2889): 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1440)
W/System.err( 2889): 	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1379)
W/System.err( 2889): 	at com.transistorsoft.locationmanager.data.sqlite.GeofenceDAO.count(Unknown Source)
W/System.err( 2889): 	at com.transistorsoft.locationmanager.geofence.a.<init>(Unknown Source)
W/System.err( 2889): 	at com.transistorsoft.locationmanager.geofence.a.a(Unknown Source)
W/System.err( 2889): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
W/System.err( 2889): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
W/System.err( 2889): 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:1021)
W/System.err( 2889): 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:108)
W/System.err( 2889): 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:99)
W/System.err( 2889): 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
W/System.err( 2889): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
W/System.err( 2889): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err( 2889): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err( 2889): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err( 2889): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 2889): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
W/System.err( 2889): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 2889): 	at android.os.Looper.loop(Looper.java:145)
W/System.err( 2889): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by aliexalter** [comment]
Before that it does this

I/TSLocationManager( 2889): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager( 2889): ╔═════════════════════════════════════════════
I/TSLocationManager( 2889): ║ BackgroundGeolocation adapter
I/TSLocationManager( 2889): ╠═════════════════════════════════════════════
D/TSLocationManager( 2889): [c.t.l.settings.Settings load] 
D/TSLocationManager( 2889):   ℹ️  Settings loaded
D/TSLocationManager( 2889): [c.t.l.d.s.SQLiteLocationDAO dbh] 
D/TSLocationManager( 2889):   ✅  Opened database
D/TSLocationManager( 2889): [c.t.l.d.s.SQLiteLocationDAO prune] 
D/TSLocationManager( 2889):   ℹ️  PRUNE -1 days
D/TSLocationManager( 2889): [c.t.l.data.sqlite.GeofenceDAO dbh] 
D/TSLocationManager( 2889):   ✅  Opened database
E/SQLiteLog( 2889): (1) no such table: geofences 

and then it gives system.err

**Comment by christocracy** [comment]
Yes, there is a bug (fixed in premium version) where upgrading from a **very** old version to latest fails to generate the new "geofences" table.

First install version `2.0.13` before upgrading to latest.

**Comment by aliexalter** [comment]
like this <plugin name="cordova-background-geolocation-lt" source="npm" version="2.0.13" />

**Comment by aliexalter** [comment]
Now plugin is at version 2.0.13 and it made sound and also show console.log BackgroundGeolocation ready.
Can I upgrade to latest now?

**Comment by christocracy** [comment]
yes

**Comment by aliexalter** [comment]
I update to latest and its giving me the same errors again.

**Comment by aliexalter** [comment]
How Can I disable SQLite? I don't need geofencing stored in sqlite. Will that fix it?

**Comment by christocracy** [comment]
You don't disable SQLite.  The plugin requires its expected schema, regardless if you *use* geofences or not.

Install then uninstall all previous version starting at [2.2.0](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#220---2016-11-21)

**Comment by aliexalter** [comment]
You mean uninstall the app from device completely or only remove plugin from the config.xml.

**Comment by christocracy** [comment]
the plugin.  pretend you're installing / uninstalling each version of the plugin starting from `2.0.13`

**Comment by aliexalter** [comment]
Web it works till 2.3.0 after that it gives message license validity failure. I renewed license last Friday.

**Comment by christocracy** [comment]
See the new [Configure the Plugin](https://github.com/transistorsoft/cordova-background-geolocation-lt#configuring-the-plugin) section.

Add 
```
<variable name="LICENSE" value="YOUR_LICENSE_KEY" />
```
Uninstall / re-install plugin for variables to take-effect.

**Comment by aliexalter** [comment]
```
<plugin name="cordova-background-geolocation-lt" source="npm">
        <variable name="LICENSE" value="014xxxxxxx7faxxxxxx" />
    </plugin>
```

**Comment by aliexalter** [comment]
It worked.  Thanks.
