### ISSUE TITLE
Documentation typo: [Application] Common Options "stopOnTerminate"

### ISSUE THREAD

**Issue by minessis** [transistorsoft/cordova-background-geolocation-lt#296]
See: https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#application-common-options

## Currently
* stopOnTerminate Boolean	true	Set **true to continue tracking** after user teminates the app.

## Fix
(as per https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-boolean-stoponterminate-true)
* stopOnTerminate Boolean	true	Set **false to continue tracking** after user teminates the app.

**Comment by christocracy** [comment]
Thanks.

**Comment by christocracy** [comment]
Fixed in premium plugin.
