### ISSUE TITLE
Remove listeners issue

### ISSUE THREAD

**Issue by stosiarz** [transistorsoft/cordova-background-geolocation-lt#298]
## Your Environment
* Plugin version: 2.2.0
* Platform: iOS 
* OS version: 10.2.1
* Device manufacturer / model: iphone 7
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): ios 4.1.1

I've got a problem implementing this 

BackgroundGeolocation.on('location', ...)
BackgroundGeolocation.removeListeners();
BackgroundGeolocation.on('location', ...)

Plugin works and reports correctly but after removing it and adding listener again, it won't report any 
new locations. I can't get output from any of the listeners. I can provide more information if necessary.

**Comment by christocracy** [comment]
I'll check it out

**Comment by christocracy** [comment]
I attempted to reproduce this in the Safari Web Console:
![](https://www.dropbox.com/s/uwkugb4n6leexrp/Screenshot%202017-03-13%2010.03.12.png?dl=1)

```javascript
bg = window.BackgroundGeolocation
bg.removeListeners();
bg.on('location', function(location, taskId) { console.log('- Location: ', location); bg.finish(taskId); })
```

- As you can see, listeners stopped when I execute `#removeListeners`.
- When I add a new listener, my callback is fired.

**Comment by christocracy** [comment]
Closed for lack of feedback
