### ISSUE TITLE
IOS App terminates while on background

### ISSUE THREAD

**Issue by bicimapas** [transistorsoft/cordova-background-geolocation-lt#299]
Hello Chris, I am using your plug in in an IOS app for  mountain bike rides using phonegap build. It is a fitness app that tracks the user’s location and stores the information for future use and reference. I have added your plug in and  all works very well except for one fact. After about  an hour or hour and a half in the background, the app shuts down and all information is lost. Mountain bike rides maybe of up to 5 or 6 hours in length so continuous background operation is needed.  I think there is something I may have to change in the configuration to allow for continuous background operation but have not figured out what is causing this.

In the config.xml  file I have these calls that to my understanding are needed for IOS background apps:

```xml
<gap:config-file platform="ios" parent="UIBackgroundModes" overwrite="false"><array><string>location</string></array></gap:config-file>
<gap:config-file platform="ios" parent="NSLocationAlwaysUsageDescription" overwrite="false"><string></string></gap:config-file>
```

The plug in is added like this

```xml
<plugin name="cordova-background-geolocation-lt" source="npm" />
```

The app uses  getCurrentPosition to get the user’s initial position (Locate() function below)  and then a watchPosition to track the user’s movements. The plugin is called this way

```javascript
function onDeviceReady() {
         bgGeo = window.BackgroundGeolocation; // Get a reference to the background geolocation plugin.
			   Locate();
			}
```

These are the options for watch position

```javascript
 var optionswatch = {interval: 1000, desiredAccuracy: 10};
```

This is the plug in configuration:

```javascript
bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 10,
        distanceFilter: 10,
        stationaryRadius: 30,
        disableElasticity: true, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity            
        // Activity Recognition config
        activityType: 'Fitness',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,
        preventSuspend: true,
        heartbeatInterval: 60,

        // Application config
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true
        } 
   );
```

Watch position is started this way

```javascript
bgGeo.watchPosition(showTrack, showError, optionswatch)
```

and stopped this way

```javascript
bgGeo.stopWatchPosition();
```

My questions are:

1.	Am I missing something in the configuration file to allow continuous background operation?
2.	The watchPosition is turned on/off by buttons. Shall  bgGeo.start(); and bgGeo.stop(); be used with watchposition before starting and after stopping? (I have tested both ways and cannot find a difference in performance.

Thank you in advance for any help you may provide.

**Comment by christocracy** [comment]
**Please learn to use markdown markup.  Edit your comment to see what I did.**

You do **NOT** need to use `#watchPosition`.  `#watchPosition` is designed for use in the foreground.

Just call `#start`.  Read the plugin's [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

I feel like remove the `#watchPosition` method because people abuse it.

**Comment by bicimapas** [comment]
Thanks,  my first time writing  in Github so need to learn the markup, thanks for fixing it. I have read all your documents and I understand the philosophy. 
So what you mean is that using watch position is causing the app to terminate while on the background?

If so, then using 

`bgGeo.on(´location', callbackFn, failureFn);`

method shall fix this?

**Comment by christocracy** [comment]
You're not using the plugin correctly.  When you want to track a device, call `#start`.  When you wish to cease tracking, call `#stop`.  If you wish to manuall trigger a motion-state change, `#changePace`.  Simple as that.  

I'm not going to speculate on anything until you get rid of watchPosition.

**Comment by bicimapas** [comment]
I am working on it, I will let you know on the results.

Thanks for the help

**Comment by bicimapas** [comment]
I have modified the code to remove watchPosition as follows:

Configuration 

```
bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 10,
        distanceFilter: 10,
        stationaryRadius: 30,
        disableElasticity: true,
        
// Activity Recognition config
        activityType: 'Fitness',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,
        preventSuspend: true,
        heartbeatInterval: 60,
 
        // Application config
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true
        } 
   );

```
Then this

```
bgGeo.changePace(true); // Setting pace to fast to enable aggresive tracking as soon as the plugin is started
                          // Comment it to enable default behaviour
                          
bgGeo.on('heartbeat', function(params) {
  console.log('- heartbeat event received');
});
```

The tracking start button triggers a function called Track() that contains

```
function Track() {
		  navigator.notification.beep(1);
		  bgGeo.start();
		  //Some coce to be executed   
      	bgGeo.on('location', showTrack, failureFn);
		}	
```
where showTrack() gets the position information to plot it on a map and store the position object in a javascript array.

The tracking stop button triggers this function

```
function stopTrack() {
			navigator.notification.beep(1);
			// Some code to be executed
			bgGeo.stop();
			}	
```

Please let me know whether:

1. This configuration is correct for continuous background operation. 
2. Is the heartbeat value of 60 appropiate for the app scope?
3. Is the bgGeo.on(heartbeat....  function appropiate for the app scope?

Thank you

**Comment by christocracy** [comment]
- Make sure you only add event-listeners **once**.  If your `#Track` method is called twice, you're going to add **2** `location` event-listeners.
- Do not execute **any** plugin API method (aside from adding event-listeners with `#on`) until the callback to `#configure` executes.  See [README](https://github.com/transistorsoft/cordova-background-geolocation-lt#configure-the-plugin)
- If you call `#start`, the plugin is running "continuously".  That does **not** mean that location-services are on "continuously" -- it means the plugin is listening to the ActivityRecognition API for movement.  If the device is moving, the plugin will turn **on** location-services.  If the device is **stationary**, the plugin will turn **off** location-services, as noted in the "Philosophy of Operation" docs.
- I have no opinion on whether a `hearrtbeatInterval: 60` is appropriate for you.
- The `callback` you provide to *any* plugin event is owned by *your* app.  Scope it as you wish.  The plugin has nothing to do with this.

**Comment by bicimapas** [comment]
I have modified the code following your guidelines and performed 2 short term tests (less than half an hour in the background ) that worked well. During one of them, phone calls and emails were received as well and the app kept running as expected. Long term tests (more than 2 hours in the background) will be performed shortly.

I tried to use the emailLog() function but it is not working. A button was added to the UI to send the email like this

`<button id ='log' class ='btn' onclick = 'sendLog()'>Send Log</button>`

and the sendLog() function is this

```
var sendlLog = function() {
    	bgGeo.emailLog("myemail@myemail.com");
    	}
```

but no email is send.  What am I missing?

**Comment by christocracy** [comment]
what version of plugin are you using?

**Comment by bicimapas** [comment]
Should be the last one. This is the call in config.xml

`<plugin name="cordova-background-geolocation-lt" source="npm" />`

**Comment by bicimapas** [comment]
Chris,

The email issue has been fixed. The sendLog function was written in a js file we have for all functions and some how it was not being recognized by the html UI. I moved the function to the html page just after the background geolocation definition calls and it now works.

I am attaching the file I got (renamed it from *.log to *.txt to be able to upload it)

[background-geolocation.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/834776/background-geolocation.txt)

Thanks for your support. I will report back the long term tests performance.

**Comment by christocracy** [comment]
Note that the `<plugin>` [config now accepts `<variable />` elements](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)

**Comment by bicimapas** [comment]
I am aware of that option, thanks.

**Comment by christocracy** [comment]
Whenever you see this:
```
2017-03-06 13:15:21.948 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 1, remaining time: 4.024932

2017-03-06 13:15:21.949 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 2, remaining time: 4.024174

2017-03-06 13:15:21.949 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 3, remaining time: 4.023637

2017-03-06 13:15:21.950 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 5, remaining time: 4.023120

2017-03-06 13:15:21.950 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 6, remaining time: 4.022615

2017-03-06 13:15:21.951 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 7, remaining time: 4.022105

2017-03-06 13:15:21.951 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 8, remaining time: 4.021537

2017-03-06 13:15:21.952 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 9, remaining time: 4.021037

2017-03-06 13:15:21.952 ⚠️__45-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 10, remaining time: 4.020539
```
and this:
```
2017-03-06 13:09:03.914 ✅ [BackgroundTaskManager stopBackgroundTask] 4 OF (
    1,
    2,
    3,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    28
)
```
You're failing to execute `bgGeo.finish(taskId)` in one of your callbacks.  Double check the signature of event callbacks where you're provided a `taskId` and **be sure** to `bgGeo.finish(taskId)`.

**Comment by christocracy** [comment]
You have **HUNDREDS** of unfinished `bgTask` not being finished.  Do you not test your app in the iOS simulator and watch the logs in XCode?

[FORCE KILL.log](https://gist.github.com/christocracy/40586f33ad2b0ce838cbc5f590284e01)

**Comment by christocracy** [comment]
And stop **abusing** `#watchPosition`.  I'm not going to support 24/7 usage of `watchPosition`.  It's meant for short *managed* periods.

**Comment by bicimapas** [comment]
Thanks for the feedback on the log data. Several of those logs were generated before we removed watchPosition  and improved the code as I mentioned in my first post of today. The changes were made yesterday so the relevant data is that from March 9th after 18:36 Central time when the updated app was built.

**Comment by bicimapas** [comment]
I have cleared the log data base so that we get new fresh data from our long term testing.  Are there any guidelines for log data interpretation?

**Comment by christocracy** [comment]
I think the logs are quite self-explanatory.
-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Closed for lack of feedback
