### ISSUE TITLE
Stop geolocation

### ISSUE THREAD

**Issue by ReemaBegum** [transistorsoft/cordova-background-geolocation-lt#300]
After giving BackgroundGeolocation.stop(); 
call of background geolocation is not stopping

**Comment by christocracy** [comment]
Logs please.

**Comment by ReemaBegum** [comment]
no logs....after giving BackgroundGeolocation.stop();
watchposition callback function is executing

**Comment by christocracy** [comment]
The plugin save logs to its database.  *Yes* there *are* logs.  See [`getLog`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getlogcallbackfn) method.

**Comment by christocracy** [comment]
Closed for failing to provide logs.
