### ISSUE TITLE
Foreground service killed

### ISSUE THREAD

**Issue by idanperlmutter** [transistorsoft/cordova-background-geolocation-lt#301]
## Your Environment
* 2.0.9 
* Android
* OS version: reported from different users, we reproduced on 6.0.1
* Device manufacturer / model: many, for ex GalaxyS6
* Cordova version (`cordova -v`): 6.2.0
* Cordova platform version (`cordova platform ls`): android 5.1.1
* Plugin config:
  desiredAccuracy: 1000,  
distanceFilter: 30,  
stopAfterElapsedMinutes: 0,  
//android
foregroundService: true,
minimumActivityRecognitionConfidence: 30,
//ios
stationaryRadius: 10 activityType: 'Other',
activityRecognitionInterval: 45000,
stopTimeout: 5,  

debug: false,
stopOnTerminate: false, 
url: HTTPManager.EndPoint,
method: 'POST',
autoSync: false,
batchSync: true,
maxDaysToPersist: 1,
headers: {
"Content-Type": "application/x-www-form-urlencoded"
}
 

## Expected Behavior
Supposed to run all the time without user intervention once user opens the app and allows his location tracking, that is sent to our server. We use a schedule so it is supposed to run usually at work hours and it usualy does. Also in order it to be more stable we use Foreground service as you pointed to be more safe from the OS killing..

## Actual Behavior
 But  we still have very serious problem –sometimes the service killed by Android OS anyway..  after few hours or next day. And it says "Ok2Track terminated"..

## Steps to Reproduce
Just keep it run as FG service for few hours/days..

## Debug logs
It's hard to catch because it happens in different hours - today i got it at night, but can try later if must..

We have customers complaints - up to 10% of users – so it’s very urgent to solve please!

**Comment by christocracy** [comment]
Logs please.

**Comment by christocracy** [comment]
Also, you're a customer should you should not be using the free repo.  You should be using the [private repo](https://github.com/transistorsoft/cordova-background-geolocation)
