### ISSUE TITLE
[New] Android Now Available for Free Evaluation

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/cordova-background-geolocation-lt#303]
Android is now available for **free evaluation** in **`DEBUG`** builds.

[Purchasing a license](http://www.transistorsoft.com/shop/products/cordova-background-geolocation) is required for **`RELEASE`** builds.

**Comment by andreapazi** [comment]
cool! One question, for Android the plugin is able to call JS when running in the background?

**Comment by christocracy** [comment]
For as long as the `MainActivity`(where your Cordova javascript app lives) is alive.

If the user terminates the app, your Javascript is terminated.  Only the plugin's background service stays alive.  This is why the plugin has its own HTTP service:  so the background service can continue posting locations to your server in spite of the `MainActivity` being terminated.

**Comment by christocracy** [comment]
The plugin's background-service will remain alive only if you configure `stopOnTerminate: false`.

**Comment by christocracy** [comment]
However, the plugin's background service has a mechanism which can re-launch the your Javascript app (if it was terminated).  See the [`forceReloadOn*`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-forcereloadon-false) config options.

**Comment by morganabel** [comment]
Is there a way to disable the toast notification that the license is not valid on android? I use the same codebase right now and I would prefer to not have to uninstall the plugin just to build a release for android. I actually plan on buying a license in the future but for now it's just a nice to have, but the toast is of course a non-starter for a production app.

**Comment by christocracy** [comment]
Sorry, No.

**Comment by YadrovSergey** [comment]
How in PhonaGap set  that is DEBUG build?

**Comment by christocracy** [comment]
No idea.  I don't use PhoneGap

**Comment by dhrytsenko** [comment]
Can this plugin work in evaluation mode in iOS for testing?

**Comment by christocracy** [comment]
iOS is free.  Only Android requires a key to unlock it.

**Comment by dhrytsenko** [comment]
@christocracy Thanks!
