### ISSUE TITLE
App abruptly Closing First time

### ISSUE THREAD

**Issue by testvicoast** [transistorsoft/cordova-background-geolocation-lt#305]
Once install this Plugin to my app, App is  abrupt Closing first time and i will Work Correctly from next time.Please help   
## 
[Output-Build.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/838099/Output-Build.txt)
Your Environment
* Plugin version:  2.5.1
* Platform: iOS and  Android
* Device manufacturer / model: Iphone 4s and  Micromax
* Cordova version (`cordova -v`): 6.1.1
* Cordova platform version (`cordova platform ls`): 6.1.1

**Comment by christocracy** [comment]
>Platform: iOS and Android
>Device manufacturer / model: Iphone 4s and Micromax

You're saying you get the same build error on "iOS **and** Android"??

**Comment by testvicoast** [comment]
Yes..
I have implemented like this
cordova.plugins.backgroundMode.enable();                                                                                                cordova.plugins.backgroundMode.moveToBackground();
then i am Calling Bgcordova Plugin
bgGeo.configure({
            desiredAccuracy: 0,
            distanceFilter: 0,
            stationaryRadius: 0,
            locationUpdateInterval: Pullfrequency,
            fastestLocationUpdateInterval: PullfrequencyLess,
            debug: false,
            stopOnTerminate: false,
            startOnBoot: false,
            disableMotionActivityUpdates: false
        }, function (state) {
            if (!state.enabled) {
                bgGeo.start(function () {
                });
            }
        });
......
......

**Comment by testvicoast** [comment]
**cordova.plugins.backgroundMode.enable(); 
cordova.plugins.backgroundMode.moveToBackground();**

//then i am Calling Bgcordova Plugin

**bgGeo.configure({
desiredAccuracy: 0,
distanceFilter: 0,
stationaryRadius: 0,
locationUpdateInterval: Pullfrequency,
fastestLocationUpdateInterval: PullfrequencyLess,
debug: false,
stopOnTerminate: false,
startOnBoot: false,
disableMotionActivityUpdates: false
}, function (state) {
if (!state.enabled) {
bgGeo.start(function () {
});
}
});
......
......**

**Comment by christocracy** [comment]
Don't **spam** the issue thread -- edit your original message.

Learn to use markdown.  There's a link to it right on this very page:
https://guides.github.com/features/mastering-markdown/

**Comment by christocracy** [comment]
Why are you showing me the build log which shows
```
1>  BUILD SUCCESSFUL
```
You should be showing me the `$ adb logcat` of the crash.

**Comment by christocracy** [comment]
Closed for failing to provide logs..
