### ISSUE TITLE
Plugin not work when killed app  (iOS)

### ISSUE THREAD

**Issue by N0madzx** [transistorsoft/cordova-background-geolocation-lt#307]
Hello Chris , I used this plugin for iOS . It work when I test my application on simulator . Plugin still active when I killed app. But when I tested on my Ipad and Iphone . It not work when I killed app.
Please help. Thank you. 

Plugin version: 2.5.3
Platform: iOS 
Device manufacturer / model: Iphone 6plus and ipad Air 2
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): ios 4.2.1

**Comment by christocracy** [comment]
Your app *does* terminate.  However, iOS will reboot it when you move about 200 meters.  It will not reboot until you move.

**Comment by christocracy** [comment]
Closed for lack of feedback
