### ISSUE TITLE
HeartBeat sent the old position (ios) 

### ISSUE THREAD

**Issue by hatvott** [transistorsoft/cordova-background-geolocation-lt#308]
Hi Chris,
I have a problem with iOS background location. I configured the heartbeat is 60 seconds.
When the device stay at position A, move to B, move to C.
The server received position A --> B  --> **A** --> C --> **A** (A is the position by heartbeat (interval 60s).
Please help me.
Thanks.
## Your Environment
* Plugin version: 2.1.0
* Platform: iOS  
* OS version: 10
* Device manufacturer / model: Iphone
* Cordova version: 6.4.0
* Cordova platform version: 4.3.0
* Plugin config

**Comment by christocracy** [comment]
You can't trust the location provided to the heartbeat callback.  It's only the last known location.  The plugin does **NOT** request new locations during heartbeat events.  It's completely up to you to request a location on your own with `#getCurrentPosition`.

```javascript
bgGeo.on('heartbeat', function(params) {
  bgGeo.getCurrentPosition(function(location, taskId) {
    console.log('- current location: ', location);
    bgGeo.finish(taskId);
  });
});
```

**Comment by hatvott** [comment]
Thanks Chris 👍
