### ISSUE TITLE
What does "maximumAge": 0 mean?

### ISSUE THREAD

**Issue by juanscolari** [transistorsoft/cordova-background-geolocation-lt#309]
I would like to have no cache, but i don't know if a 0 value for maximumAge means that or it means infinite cache

**Comment by christocracy** [comment]
So, you're talking about `#getCurrentPosition`?

The plugin's default behaviour is to **never** return a cached location.  If you don't want a cached location, you need not even think about `maximumAge`.  Do not provide it to the `config`.
