### ISSUE TITLE
Can't build the project on Xcode

### ISSUE THREAD

**Issue by gabfr** [transistorsoft/cordova-background-geolocation-lt#31]
Hi,

I'm trying to run some tests with your plugin on iOS, but I can't build it. It prompt this error:

    duplicate symbol _llvm.cmdline in:
        EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.embedded.module in:
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.cmdline in:
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.embedded.module in:
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.cmdline in:
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
duplicate symbol _llvm.embedded.module in:
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
    ld: 6 duplicate symbols for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is a bug? Or I did something wrong?

Thanks

**Comment by christocracy** [comment]
Upgrade to Xcode 7.x.  I guess your using 6.x

On Wednesday, October 28, 2015, Gabriel Ferreira Rosalino <
notifications@github.com> wrote:

> Hi,
>
> I'm trying to run some tests with your plugin on iOS, but I can't build
> it. It prompt this error:
>
> duplicate symbol _llvm.cmdline in:
>     EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>  EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
>
> duplicate symbol _llvm.embedded.module in:
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
> duplicate symbol _llvm.cmdline in:
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
> duplicate symbol _llvm.embedded.module in:
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
> duplicate symbol _llvm.cmdline in:
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
> duplicate symbol _llvm.embedded.module in:
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>
> EarthlyExplorer/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
> ld: 6 duplicate symbols for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> This is a bug? Or I did something wrong?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/31>
> .
>


-- 
Snet form Gmail Mobile
