### ISSUE TITLE
Plugin stops after X amount of time (days... even weeks)

### ISSUE THREAD

**Issue by nschurmann** [transistorsoft/cordova-background-geolocation-lt#310]
Hello!, this plugins works but randomly stops working after certain amount of time, this can be days or weeks. Is there a way to prevent this?

# Environment
Plugin version: 2.5.3
Platform: iOS
OS Version: 10.2
Device: iPhone 6
Cordova version: 6.4.0
Cordova platform version: ios 4.3.1

# Expected behaviour:
Keep tracking all the time with no missing tracks

# Actual behaviour
Randomly stops tracking, image attached
![screen shot 2017-03-30 at 1 02 16 pm](https://cloud.githubusercontent.com/assets/5099344/24514176/b8e5eac0-1549-11e7-8929-01cab948e989.png)
Steps to reproduce:
Configuration:
```javascript
bgGeo.configure({
                // Geolocation config
                desiredAccuracy: 10,
                distanceFilter: 40,
                stationaryRadius: 40,

                // Activity Recognition config
                activityType: 'Fitness',
                activityRecognitionInterval: 10000,
                stopTimeout: 5,

                // Application config
                debug: false,
                logLevel: 'LOG_LEVEL_OFF',
                stopOnTerminate: false,
                startOnBoot: true,
                preventSuspend: true,
                heartbeatInterval: 5000,

                // HTTP / SQLite config
                url: URL_SERVICES + 'yu-track/api/v1/users/trackV2',
                method: 'POST',
                autoSync: true,
                batchSync: true,
                maxBatchSize: 50,
                maxDaysToPersist: 100,
                headers: {
                    'authorization': session.token
                }
            }, function(state) {
                if (!state.enabled) {
                    bgGeo.start()
                }
            })
```
Run the app, start tracking, eventually will miss track.

The context is that the app must keep tracking always, except for the known issues (waiting up to 15 minutes after a reboot).

# Logs
No logs can be provided because this happens randomly

**Comment by christocracy** [comment]
**If you ignore the issue template, I ignore your issue**.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
Closed for failing to provide issue template.

**Comment by nschurmann** [comment]
@christocracy updated the issue :)

**Comment by christocracy** [comment]
You're using `desiredAccuracy: 10`, which doesn't include GPS.  You're relying upon Wifi / Cell tower triangulation only.

Without logs, there's little to say.  I'm sure there's no issue with the plugin.

**Comment by nschurmann** [comment]
With `desiredAccuracy: 0` will rely also on GPS?

**Comment by christocracy** [comment]
See docs:  [`desiredAccuracy`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-desiredaccuracy-0-10-100-1000-in-meters)

**Comment by nschurmann** [comment]
@christocracy thanks!, we will try with desiredAccuracy 0 and see the results

**Comment by christocracy** [comment]
Update?

**Comment by nschurmann** [comment]
Works a lot better! thanks :)
