### ISSUE TITLE
Geofence ENTRY only fires 50% of the time when adding new geofence despite location being clearly within geofence. 

### ISSUE THREAD

**Issue by jordanmsllvn** [transistorsoft/cordova-background-geolocation-lt#311]
Hi Chris,
First off let me tell you that I am indeed planning on purchasing your plugin.

Currently having trouble getting a consistent geofence ENTRY when my application first initializes. I think part of the problem is I don't have an understanding of how this is working under the hood.

When I init my app, I configure bgGeo and hit the server for a collection of entities that need to have geofences, when the server responds I add the geofences using `bgGeo.addGeofences()`.

I am expecting, based on what I can find in the docs, that after adding these geofences, I should be getting a geofence ENTRY event if current location is within one of the newly added geofences (I have VERY wide geofences for testing so location accuracy shouldn't be the issue here). However, this expected behavior only happens about 50% of the time.

This on and off behavior, especially given the asynchronous nature of fetching the geofence entities from the server, lead me to believe theres a race condition of some sort. However, after refactoring my code to ensure geofences are only added after the BackgroundGeolocation.config success callback, the geofence ENTRY fires 0% of the time. I have also tried adding geofences before `bgGeo.config()` to similar dismay.

Looking at the logs, it seems that when it works, a `-[TSGeofenceManager startMonitoringGeofence:] 2` shows in the log immediately after the `-[GeofenceDAO doInsert:params:]`.

When it doesn't work, this never shows up in the logs. 

As a test, I even tried adding the geofences up to 10 seconds after bgGeo init success. No luck.

I've attached two logs, one when it works, and one when it doesn't. The app has identical code for both of these logs.

[Log when it works](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/863645/working.txt)

[Log when it fails](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/863646/not-working.txt)

I am testing on an iPhone 5s device. No access yet to an android device for testing.

Thanks Chris.

**Comment by jordanmsllvn** [comment]
One other note... Ive noticed that in the logs, when it works as expected, 
`ℹ️__25-[GeofenceDAO destroyAll]_block_invoke` is called near the beginning of the init process...

when it doesn't work... this happens near the end of the init process right before the ENTRY event would be expected to happen.

**Comment by christocracy** [comment]
Since you're using `stopOnTerminate: false`, when you terminate the app, geofence monitoring is persisted.

Imagine this scenario:
1. boot app.  destroy all geofences.
2. Add a new geofence `foo` around the current position:  it fires immediately.
3. Terminate the app and reboot.
4. Reboot the app.  Geofence `foo` will **NOT** fire again.

Why won't geofence `foo` fire again?  Because geofence monitoring is persisted.  You never left that geofence.

**Comment by christocracy** [comment]
Geofences are persisted in the database.  You do not have to re-add them each time your app boots.

**Comment by christocracy** [comment]
If I put a geofence `HOME` with `notifyOnEntry: true` around my current location then **never** destroy it, it's going to fire immediately the first time I create it.  Thereafter, it's going to fire every time a *exit and re-enter* `HOME`.

If I terminate the app 10 days later while I'm *inside* `HOME` and reboot, it will *not* fire.  I have to *exit and re-enter* before it will fire again.

**Comment by jordanmsllvn** [comment]
Great! fully understood. Thanks for your quick answer. 

Is it safe to assume then that I can depend on the plugin to fire an EXIT event when the app is booted up 10 days later outside of the geofence, or in a different geofence?

**Comment by christocracy** [comment]
iOS monitors geofences at the OS level.  With stopOnTerminate: false, iOS will automatically reboot your app to service any triggered geofence.  Even if you reboot your device without booting your app, those geofences *are* being monitored.
