### ISSUE TITLE
Change the config when the Plugin working

### ISSUE THREAD

**Issue by turkialarjani** [transistorsoft/cordova-background-geolocation-lt#313]
Your Environment

Plugin version:
Platform: iOS
OS version: 10.2
Device manufacturer / model:
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls):ios 4.3.1 -
Plugin config

function configBackgroundLocation(distanceFilter,serviceUrl,token,orderId) {
    var bgGeo = window.BackgroundGeolocation;
    
    //This callback will be executed every time a geolocation is recorded in the background.
    var callbackFn = function(location, taskId) {
        var coords = location.coords;
        var lat    = coords.latitude;
        var lng    = coords.longitude;
       
        console.log('- Location: ', JSON.stringify(location));

        // Must signal completion of your callbackFn.
        bgGeo.finish(taskId);
    };

    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
    var failureFn = function(errorCode) {
        console.warn('- BackgroundGeoLocation error: ', errorCode);
    }

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);

    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function(isMoving) {
      console.log('- onMotionChange: ', isMoving);
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: distanceFilter,
        stationaryRadius: 50,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 5000,

        // Activity Recognition config
        activityType: 'AutomotiveNavigation',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,

        // Application config
        debug: true,
        stopOnTerminate: false,
        startOnBoot: true,

        // HTTP / SQLite config
        url: server_url+serviceUrl,
        method: 'POST',
        autoSync: true,
        batchSync:true,
        maxDaysToPersist: 1,
        headers: {
            'token': token
        },
        data : {
            'orderId' : orderId
        }
//        
    }, function(state) {
        
        
        // This callback is executed when the plugin is ready to use.
        console.log('BackgroundGeolocation ready: ', state);
        if (!state.enabled) {
            bgGeo.start();
        }
    });

    function onToggleEnabled(value) {
        if (value) {
            bgGeo.start();
        } else {
            bgGeo.stop();
        }
    }
    
    }

Expected Behavior

-I use this plugin two times with different config so I create a global method to call it in different pages and change the config.   
-Change the config when the plugin working.

Actual Behavior

-App terminat when I change the configuration.
-The plugin stop when the I change the config.

Debug logs

**Comment by christocracy** [comment]
You must **never** call the `#configure` method twice.

If you need to change the config *after* the initial `#configure`, use `#setConfig`

**Comment by christocracy** [comment]
If you have a crash, show me logs or stacktrace.

**Comment by christocracy** [comment]
Update?

**Comment by christocracy** [comment]
Closing for lack of feedback
