### ISSUE TITLE
Question: Is it possible to tell if app is booted headless or not?

### ISSUE THREAD

**Issue by mikkelsjolin** [transistorsoft/cordova-background-geolocation-lt#315]
I wan't to use different configurations when my app is running in the foreground versus the background.

Is there a state somewhere that can tell me if the plugin has booted in the background only or if it is running in the foreground?

Thank you!

**Comment by christocracy** [comment]
[`cordova-plugin-applicationstate`](https://github.com/leomylonas/cordova-plugin-applicationstate)

**Comment by mikkelsjolin** [comment]
Thank you :)

I'm using another cordova plugin to monitor the application state. Just wanted to know if it was built into your plugin already.
