### ISSUE TITLE
Location Permissions / Location settings updated callbacks

### ISSUE THREAD

**Issue by harshabonthu** [transistorsoft/cordova-background-geolocation-lt#317]
## Your Environment
* Plugin version: 2.6.0
* Platform: iOS and Android

## Expected Behavior
We want to track a user in background / foreground at a scheduled time. IF the location tracking has been started then the plugin should handle location permissions i.e on calling the .start method and when the location authorization permission popup is shown - if the user clicks on deny or if the user clicks on allow and has GPS turned off or later disabled GPS

## Actual Behavior
Right now after calling the .start() method plugin shows the permission popup and if the user clicks on allow and has GPS enabled everything works fine.

If the user clicks on deny at the permission popup, we don't get any callback? Not sure if anyway we can identify the tracking has not started?

IF the user clicks on allow and has GPS turned off on android -> Plugin gets initialized but location tracking is not yet started until GPS is turned on -> Same do we have any callback to identify / watch for location setting changes ?

## Steps to Reproduce
1. Configure the plugin
2. Call .start() method
3. Click deny for permission popup or click allow and later change the permissions / location settings

## Context
If location tracking has been enabled and later user denies permission or changes location settings, I'm looking for anyway to detect or notify the user to enable the location settings / grant permissions.

**Comment by christocracy** [comment]
Listen to [`providerchange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#providerchange) event.
