### ISSUE TITLE
Started getting Licence Validation Error.

### ISSUE THREAD

**Issue by dimitriscsd** [transistorsoft/cordova-background-geolocation-lt#318]
Hello.

I've been using the paid version of the plugin for a while. Everything was working great. Then I got a message saying that the subscription is about to end and I should copy the contents of the repo locally. I did that, made sure it gets installed from the local folder and everything ran fine for a few days.

Last week I randomly started getting an error about License Validation, saying that the plugin is now running in Evaluation Mode.

My config.xml hasn't changed, the licence key is the same as it always was so I'm confused about what's going on. It could be me doing something wrong, however I haven't changed any configuration files compared to when it was working just fine.

I believe I updated my cordova CLI at some point if that makes any difference.

## Your Environment
* Plugin version: 2.6.0
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Oneplus 3T
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): android 6.1.2
* Plugin config

```
bgGeo.configure({
                desiredAccuracy: 0,
                distanceFilter: 20, // Minimum distance before update
                locationUpdateInterval: 10000,
                stationaryRadius: 30,
                activityType: 'AutomotiveNavigation',
                fastestLocationUpdateInterval: 5000,
                activityRecognitionInterval: 5000,
                minimumActivityRecognitionConfidence: 65,
                stopTimeout: 1,  // Stop-detection timeout minutes (wait x minutes to turn off tracking)

                // Application config
                debug: false,
                stopOnTerminate: true
            }, function(state) {
                console.log("BgGeolocation plugin configured.  Current state: ", state.enabled);
            }, function(error) {
                console.error("BgGeolocation plugin failed to configure.");
            });
```

## Debug logs
https://pastebin.com/N7jSWBRZ

## config.xml

```
<plugin name="cordova-background-geolocation" spec="local_plugins/cordova-background-geolocation">
        <variable name="LICENSE" value="KEY_IS_LOCATED_HERE" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
        <variable name="BACKGROUND_MODE_LOCATION" value="location" />
        <variable name="BACKGROUND_MODE_AUDIO" value="" />
    </plugin>
```

**Comment by christocracy** [comment]
You no longer need to copy the private repo.  You can simply use this free repo for latest stable release (it contains Android and your existing keys will unlock it).

Follow the directions in the README (**NOTE** the plugin id is `cordova-background-geolocation-lt` -- not `cordova-background-geolocation`.

**Comment by dimitriscsd** [comment]
That worked - Thanks for the help. Problem solved.

**Comment by kushal-ost** [comment]
We have purchased the plugin, and using command 'cordova plugin add cordova-background-geolocation-lt' to install plugin, But it still shows 'Licence Validation Error'. How to remove this error ? From where we can get licence key ?

**Comment by christocracy** [comment]
See Wiki [License Validation Failure](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/License-Validation-Failure)

**Comment by kushal-ost** [comment]
Thanks,
For the second point, I have created a new issue, Please check

**Comment by ManishMittal** [comment]
Hi,
We have purchased this plugin.
I am  editing in config.xml
 <variable name="LICENSE" value="YOUR_LICENSE_KEY" />
Do we need to replace YOUR_LICENSE_KEY with license number or just above code is fine ?
If we need to replace YOUR_LICENSE_KEY with license number then from where we can get license number ?
This is not mentionen in this wiki <a href="https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/License-Validation-Failure">License Validation Failure</a>

**Comment by kushal-ost** [comment]
Hi, We have purchased your plugin.
and editing in config.xml
<variable name="LICENSE" value="YOUR_LICENSE_KEY" />
So do we need to replace YOUR_LICENSE_KEY with license number or above code is fine ?

If we ned to replace then from where we can get license number ? Please suggest.

This is not mentioned in <a href="https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/License-Validation-Failure">License Validation Failure</a>

Waiting for your respnse !!

**Comment by christocracy** [comment]
Yes, you need to replace `YOUR_LICENSE_KEY` with...*your license key*.  You generate your own license key in the product dashboard.  Talk to the person who registered the product and ask them for the license key.

**Comment by kushal-ost** [comment]
I trying as you suggested, but its showing error as :  
I am using same license key and bundle key when purchased.

code 1 Error output:
/home/ost/ionic/v1/child/platforms/android/app/src/main/AndroidManifest.xml:35:9-113 Error:
	Element meta-data#com.transistorsoft.locationmanager.license at AndroidManifest.xml:35:9-113 duplicated with element declared at AndroidManifest.xml:18:9-161
/home/ost/ionic/v1/child/platforms/android/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

**Comment by christocracy** [comment]
Show me your entire `AndroidManifest.xml`

**Comment by kushal-ost** [comment]
I m using license key also.. Do you need to check license key also ?

**Comment by christocracy** [comment]
@kushal-ost You're not *manually* adding the `license` to your `AndroidManifest.xml`, are you?

**Comment by kushal-ost** [comment]
Yes .. after installing this plugin, I am manually adding my license key in config.xml and AndroidManifest.xml. If I will not manually add license key then "YOUR_LICENSE_KEY" is written by default. 

Please suggest

**Comment by kushal-ost** [comment]
So if I don't touch the file then "YOUR_LICENSE_KEY" is not replaced by my licence key and "License Failure" message still comes

**Comment by kushal-ost** [comment]
Do this plugin support android version 6.2.3 and cordova version 8.0.0 ?

**Comment by christocracy** [comment]
Destroy your Android platform.  Re-add it.

Follow the directions in wiki.

**Comment by christocracy** [comment]
You need min cordova-android @ 6.3.0

**Comment by kushal-ost** [comment]
Ok, I will try this by removing platform and then adding

**Comment by shrashwin** [comment]
@kushal-ost  hello, I am having the same problem. The location are geting fetched in version 2.11.0 but the problem is even with license key, i am geting this:

07-13 16:16:22.884 12953-13028/com.docandtrack.app I/TSLocationManager: ╔═════════════════════════════════════════════
                                                                        ║ License Validation Failure
                                                                        ╠═════════════════════════════════════════════
                                                                        ╟─ BackgroundGeolocation is running in evaluation mode.


in my logcat.

In some issue, i see repo owner writing, post question relating to license in private repo.. where as in some its written, this cordova-background-geolocation-lt can be used with correct license key. 

Do you have any insight on this.

Also, with this version, my ios is crashing.
