### ISSUE TITLE
location service disabled when in background

### ISSUE THREAD

**Issue by sandeep-agarwal** [transistorsoft/cordova-background-geolocation-lt#319]
Is it possible to know, and send update to server, if a user has disabled location service from phone settings while the app is terminated / in background ?

**Comment by christocracy** [comment]
Yes, listen to [`providerchange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#providerchange) event.

Android automatically records a location with `provider` info attached and sends it to your server.

**Comment by sandeep-agarwal** [comment]
Thanks for the quick response. I am working on an ios only app. 

I tried with the event listener on ios. Works perfectly with the app is in background but fails to send any update on server when the app is terminated and then the location service is disabled / app permission revoked. Atleast in my setup. I did not tried the SampleApp. 

A config setting, similar to http url setup in config, which send the providerchange details to a remote server even when the app is terminated ?

**Comment by christocracy** [comment]
If iOS app is terminated in background, there's no way to tell.

With stopOnTerminate: false, the app *is* terminated.  It's just that it'll
*reboot* when the device moves beyond the stationary geofence (typicall 200
meters of movement).


-- 
Snet form Gmail Mobile
