### ISSUE TITLE
Plugin not working in Android 

### ISSUE THREAD

**Issue by turkialarjani** [transistorsoft/cordova-background-geolocation-lt#321]
Your Environment

Plugin version:
Platform: android
Device manufacturer / model:
Cordova version (cordova -v): 6.4.0

Plugin config

function configBackgroundLocation(distanceFilter,serviceUrl,token,orderId) {
var bgGeo = window.BackgroundGeolocation;

//This callback will be executed every time a geolocation is recorded in the background.
var callbackFn = function(location, taskId) {
    var coords = location.coords;
    var lat    = coords.latitude;
    var lng    = coords.longitude;
   
    console.log('- Location: ', JSON.stringify(location));

    // Must signal completion of your callbackFn.
    bgGeo.finish(taskId);
};

// This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
var failureFn = function(errorCode) {
    console.warn('- BackgroundGeoLocation error: ', errorCode);
}

// Listen to location events & errors.
bgGeo.on('location', callbackFn, failureFn);

// Fired whenever state changes from moving->stationary or vice-versa.
bgGeo.on('motionchange', function(isMoving) {
  console.log('- onMotionChange: ', isMoving);
});

// BackgroundGeoLocation is highly configurable.
bgGeo.configure({
    // Geolocation config
    desiredAccuracy: 0,
    distanceFilter: distanceFilter,
    stationaryRadius: 50,
    locationUpdateInterval: 1000,
    fastestLocationUpdateInterval: 5000,

    // Activity Recognition config
    activityType: 'AutomotiveNavigation',
    activityRecognitionInterval: 5000,
    stopTimeout: 5,

    // Application config
    debug: true,
    stopOnTerminate: false,
    startOnBoot: true,

    // HTTP / SQLite config
    url: server_url+serviceUrl,
    method: 'POST',
    autoSync: true,
    batchSync:true,
    maxDaysToPersist: 1,
    headers: {
        'token': token
    },
    data : {
        'orderId' : orderId
    }
//
}, function(state) {

    // This callback is executed when the plugin is ready to use.
    console.log('BackgroundGeolocation ready: ', state);
    if (!state.enabled) {
        bgGeo.start();
    }
});

function onToggleEnabled(value) {
    if (value) {
        bgGeo.start();
    } else {
        bgGeo.stop();
    }
}

}

Expected Behavior

- The plugin working on android.
 

Actual Behavior

-The plugin working fine on ios but it's not working in android and it's giving me the below error.
Note that I already buy the plugin.
Debug logs
![whatsapp image 2017-04-14 at 5 07 58 pm](https://cloud.githubusercontent.com/assets/15672452/25064878/e943f93a-220c-11e7-922b-5956b1e4edde.jpeg)

**Comment by christocracy** [comment]
This is correct.  The plugin is running "evaluation mode" until you purchase a license key.

**Comment by christocracy** [comment]
See the [README](https://github.com/transistorsoft/cordova-background-geolocation-lt#cordova-background-geolocation)

**Comment by turkialarjani** [comment]
we already purchased the license key.

**Comment by christocracy** [comment]
Then you shouldn't be using the free repo.  You use the [Premium repo](https://github.com/transistorsoft/cordova-background-geolocation) and follow the installation instructions in the README there.
