### ISSUE TITLE
NSGenericException when calling setConfig 

### ISSUE THREAD

**Issue by matthiasdv** [transistorsoft/cordova-background-geolocation-lt#322]
When compiling my application to ios I am sometimes faced with the following exception: 

```
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x60000005e4b0> was mutated while being enumerated.'
```

Stack trace: 

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001024a3b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000101edf141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010250c2ec __NSFastEnumerationMutationHandler + 124
	3   CoreFoundation                      0x00000001024400df -[NSDictionary isEqualToDictionary:] + 319
	4   CoreFoundation                      0x0000000102440260 -[NSDictionary isEqual:] + 64
	5   CoreFoundation                      0x00000001023cb9c9 CFEqual + 457
	6   CoreFoundation                      0x000000010250df64 -[CFPrefsPlistSource alreadylocked_setValues:forKeys:count:] + 1236
	7   CoreFoundation                      0x00000001024cac58 -[CFPrefsSource setValues:forKeys:count:removeValuesForKeys:count:] + 264
	8   CoreFoundation                      0x00000001023f6680 -[CFPrefsSource setValues:forKeys:count:] + 32
	9   CoreFoundation                      0x0000000102504af6 -[CFPrefsSearchListSource alreadylocked_setValues:forKeys:count:] + 454
	10  CoreFoundation                      0x00000001024cac58 -[CFPrefsSource setValues:forKeys:count:removeValuesForKeys:count:] + 264
	11  CoreFoundation                      0x00000001023f6680 -[CFPrefsSource setValues:forKeys:count:] + 32
	12  CoreFoundation                      0x0000000102439fe9 -[CFPrefsSource setValue:forKey:] + 57
	13  CoreFoundation                      0x0000000102506a4f __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 319
	14  CoreFoundation                      0x000000010250624d normalizeQuintuplet + 317
	15  CoreFoundation                      0x0000000102506909 -[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 105
	16  CoreFoundation                      0x00000001024f0c15 -[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:] + 261
	17  CoreFoundation                      0x0000000102439f34 _CFPreferencesSetAppValueWithContainer + 68
	18  Foundation                          0x00000001019de610 -[NSUserDefaults(NSUserDefaults) setObject:forKey:] + 55
	19  MYAPPLICATION                      0x000000010017ef0e -[Settings load:] + 1251
	20  MYAPPLICATION                      0x0000000100190a57 -[TSLocationManager setConfig:] + 68
	21  MYAPPLICATION                      0x00000001000881d9 __38-[CDVBackgroundGeolocation setConfig:]_block_invoke + 57
	22  libdispatch.dylib                   0x00000001047834a6 _dispatch_call_block_and_release + 12
	23  libdispatch.dylib                   0x00000001047ac05c _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x000000010478bdcd _dispatch_queue_override_invoke + 1321
	25  libdispatch.dylib                   0x000000010478dec4 _dispatch_root_queue_drain + 634
	26  libdispatch.dylib                   0x000000010478dbef _dispatch_worker_thread3 + 123
	27  libsystem_pthread.dylib             0x0000000104cac712 _pthread_wqthread + 1299
	28  libsystem_pthread.dylib             0x0000000104cac1ed start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 


```

## Your Environment
* Plugin version: 2.6.0
* Platform: iOS
* OS version: 10.3
* Device manufacturer / model: iPhone 6 simulator (xCode)
* Cordova version 6.5.0
* Cordova platform version  ios 4.3.1
* Plugin config

```
          {
            debug: true,
            stationaryRadius: 25,
            stopTimeout: 5,
            minimumActivityRecognitionConfidence: 80,
            stopDetectionDelay: 10,
            // triggerActivities: 'on_foot, walking, running, in_vehicle, on_bicycle',
            desiredAccuracy: 0,
            distanceFilter: 10,
            autoSync: true
          }
```
## Expected Behavior
This behaviour occurs when I call  `setConfig(...)` multiple times on the plugin. I listen for the callback function of the original `.configure()` call and only process any .setConfig calls after this has completed. Is it possible that calling `setConfig(...)` multiple times in rapid succession is causing this behaviour? 

## Context
I'm attempting to modify the configuration of a _running_ plugin instance. I'm calling setConfig once for each property I want to change. As I'm typing this I realise this might not be a good idea.

**Comment by christocracy** [comment]
That is not a good idea.  Think of the plugin as a server.  Calls to the server are expensive.  They should be minimized.  Gather multiple property changes into one `#setConfig` request.

**Comment by matthiasdv** [comment]
Could I potentially fix this issue by listening to the `#setConfig` callback, and chaining requests instead of sending them in parallel? 

I understand making one call instead of multiple ones would be the preferred solution. When doing this I assume I'd still have to listen for the `#setConfig` callback before passing in any new requests?

**Comment by christocracy** [comment]
what are you doing that you need to call `#setConfig` so rapidly?

**Comment by matthiasdv** [comment]
I wrote a wrapper for the plugin, which allows individual config properties to be switched on or off; Sometimes this causes `#setConfig` to fire twice or thrice

**Comment by matthiasdv** [comment]
That was probably not a good idea and created unneeded complexity. I rewrote the wrapper so I can just pass in properties to one `#setConfig` call. 

Case close.

**Comment by christocracy** [comment]
class SettingsService {
  public constructor() {
    this.changes = [];
    this.buffer = null;
    this.bufferDelay = 500;
  }
  public set(name, value) {
    if (this.buffer) {
      this.buffer = clearTimeout(this.buffer);
    }
    this.changes.push({name: name, value: value});
    this.buffer = setTimeout(this.handleChange.bind(this), this.bufferDelay);
  }
  public handleChange() {
    if (!this.changes.length) { return; }
    let config = {};
    this.changes.forEach((item) => {
      config[item.name] = item.value;
    });
    YOUR_BG_GEO_REF.setConfig(config);
  }
}

**Comment by matthiasdv** [comment]
That seems like a very good idea, thanks for the insight!
