### ISSUE TITLE
Cant compile the app

### ISSUE THREAD

**Issue by nonamez** [transistorsoft/cordova-background-geolocation-lt#323]
## Your Environment
* Plugin version: latest
* Platform: Android
* OS version: Linux 4.4 Mint 18 Sarah
* Device manufacturer / model: Some sort of cheap Huavei
* Cordova version (`cordova -v`): 6.5.0

## Actual Behavior
Cant compile when plugin added. If plugin removed everything work fine

![screenshot_2017-04-20_16-51-34](https://cloud.githubusercontent.com/assets/1894964/25234057/a21967bc-25e9-11e7-9a24-333f02b60e1e.png)

## Context
Add/Remove plugin

## Debug logs
![screenshot_2017-04-20_16-53-18](https://cloud.githubusercontent.com/assets/1894964/25234147/e427d36e-25e9-11e7-83e6-d46e958e42cb.png)

**Comment by christocracy** [comment]
Show me your plugins.  Are you using `cordova-plugin-googlemaps'?
```
$ cordova plugins
```

**Comment by nonamez** [comment]
>   "cordovaPlugins": [
>     "cordova-plugin-console",
>     "cordova-plugin-device",
>     "cordova-plugin-geolocation",
>     "cordova-plugin-compat",
>     "cordova-plugin-splashscreen",
>     "cordova-plugin-statusbar",
>     "cordova-plugin-whitelist",
>     "cordova-sqlite-storage",
>     "ionic-plugin-keyboard",
>     "cordova-plugin-datepicker",
>     "cordova-plugin-googlemaps"
>   ],

**Comment by christocracy** [comment]
Just as I suspected:  `cordova-plugin-googlemaps`.

Go add another complaint to [this issue](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1208)

**Comment by nonamez** [comment]
Um, but my program lives for six months already and the google maps worked just fine until I added yours plugin...

**Comment by christocracy** [comment]
yes, read the issue.  I've seen this a million times.  Those goofs pin their [`play-services dependency`](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L49) forcing every other 3rd party plugin (including mine) to use their desired version (`9.8.0`).

The latest version of play-services is [10.2.1](https://developers.google.com/android/guides/releases).  Why must they use `9.8.0`??

**Comment by christocracy** [comment]
You would have the same issue if you were to attempts to use *any* plugin which uses play-services, like [`phonegap-plugin-push`](https://github.com/phonegap/phonegap-plugin-push/blob/master/plugin.xml#L63), for example.  They're a little more sane there, where they *at least* pin to `10.2:+`

**Comment by nonamez** [comment]
Thanks you for the explanation.

**Comment by jelluz** [comment]
any way to solve this?

**Comment by christocracy** [comment]
@jelluz you fork this plugin or that plugin an pin play-services dependency accordingly

**Comment by jelluz** [comment]
Thnx for your reply. The solution listed at the bottom of [https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1208 ](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1208) seems to work :)
