### ISSUE TITLE
License validation failure

### ISSUE THREAD

**Issue by locsim** [transistorsoft/cordova-background-geolocation-lt#325]
## Your Environment
* Plugin version: 2.6.0
* Platform: Android
* OS version: 5.1.1
* Device manufacturer / model: Oneplus ONE E1001
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): android 6.1.2
* Plugin config
bgGeo.configure({
			desiredAccuracy: 0,
			distanceFilter: 40,
			locationUpdateInterval: 60000,
			fastestLocationUpdateInterval: 10000,
			stopAfterElapsedMinutes: 0,
			stationaryRadius: 30,
			disableElasticity: false,
			deferTime:0,
					
			activityRecognitionInterval: 10000,
			stopTimeout: 0,
			minimumActivityRecognitionConfidence: 80,
			
			url: 'https:---------------',
			method: 'POST',
			autoSync: true,
			maxDaysToPersist: 1,
			
			// Application config
			debug: false,
			stopOnTerminate: true,
			startOnBoot: false,
			heartbeatInterval: heartbeat_delai,
			
			//geofencig
			geofenceInitialTriggerEntry: false,			
					
			foregroundService: true 
			},
			function(state) {
				if (!state.enabled) {bgGeo.start();}
				
				}
			);

Hi everyone,

I'm not sure of where I should post this issue. I hope this is the right place.
I have a license for a unlimited number of apps, bought in 2015 (so more than one year ago). This license was not renewed, so I'm now using transistorsoft/cordova-background-geolocation-lt repo. 

My app worked okay untill few days ago with Bgg 2.6.0, but for some reason I had to re create the cordova project from scratch (no bgg plugin change, it was 2.6.0 already before this rebuild). Since, I get LICENSE VALIDATION FAILURE at application startup.

As far as I remember, no change was made in the config.xml file which contains the <variable name="LICENSE" value="YOUR_LICENSE_KEY" /> line within the as explained in the readme file.

<plugin name="cordova-background-geolocation-lt">
<variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
<variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
<variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />

<variable name="LICENSE" value="my license key generated using http://www.transistorsoft.com/shop/customers" />
</plugin>

I certainly did something wrong, but no idea of what...any help appreciated!
Philippe

**Comment by locsim** [comment]
Hi!
I removed the plugin, and re-added it.
The license failure message appeared once...and that's all.
No very clear to me, but I guess this can be closed. Apologies.

**Comment by christocracy** [comment]
You saw the warning in the [installation Instructions](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)?

❗️ To apply changes to these <variable />, you must remove/re-add the plugin.

**Comment by dtruel** [comment]
Also if you just add the key the new way but dont get rid of the old way to add the key it won't work.
