### ISSUE TITLE
providerchange event never fired

### ISSUE THREAD

**Issue by Ko-Boy** [transistorsoft/cordova-background-geolocation-lt#326]
* Plugin version: latest
* Platform: iOS
* OS version: 10.2.1
* Device manufacturer / model: SE
* Cordova version: 6.3.1 
* Cordova platform version: ios 4.2.1
* Plugin config : 
{
    desiredAccuracy: 0,
    distanceFilter: 30,
    stationaryRadius: 20,
    disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
    locationUpdateInterval: 3000, //3000 Debug
    fastestLocationUpdateInterval: 3000, //3000 Debug
    activityRecognitionInterval: 3000, //3000 Debug
    minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change
    stopDetectionDelay: 5,  // Wait x minutes to engage stop-detection system
    stopTimeout: 10,  // Wait x minutes to turn off location system after stop-detection
    activityType: 'AutomotiveNavigation',

    locationAuthorizationAlert: {
    titleWhenNotEnabled: "Yo, location-services not enabled",
    titleWhenOff: "Yo, location-services OFF",
    instructions: "You must enable 'Always' in location-services, buddy",
    cancelButton: "Cancel",
    settingsButton: "Settings"
  },

    debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
    forceReloadOnLocationChange: false, 
    forceReloadOnMotionChange: false,  
    forceReloadOnGeofence: false,    
    stopOnTerminate: true,        
    startOnBoot: false,
    heartbeatInterval: 2,                  
    preventSuspend: true,
    
    url: '/tracking',
    method: 'POST',
    batchSync: true,       
    autoSync: true,         
    maxDaysToPersist: 1   
}

## Expected Behavior
Fired providerchange event after desable Wi-fi and location services.

## Actual Behavior
The event is not fired.

## Steps to Reproduce
1. When the app is running (captain obvious), go to settings and turn off wi-fi and location services.
2. Go back to the app, check the logs (i've add one console.log())

## Context
I'd like to avoid that a user use the app without location services activated.

My code : 
`           window.BackgroundGeolocation.on('geofence', this.onGeofence); // WORKS FINE

             window.BackgroundGeolocation.on('location', function() {
                console.log('YES YES YES !!! 1'); // DOES NOT WORK
            })
             window.BackgroundGeolocation.on('activitychange', function() {
                console.log('YES YES YES !!! 2'); // DOES NOT WORK
            })
             window.BackgroundGeolocation.on('providerchange', function() {
                console.log('YES YES YES !!! 3'); // DOES NOT WORK
            })
             window.BackgroundGeolocation.on('http', function() {
                console.log('YES YES YES !!! 4'); // WORKS
            })
             window.BackgroundGeolocation.on('heartbeat', function() {
                console.log('YES YES YES !!! 5'); // WORKS
            })
         
            window.BackgroundGeolocation.configure((location, taskId) => {
                ...
                ...
`
Thank you in advance :)

**Comment by christocracy** [comment]
Yes, because you're not using the [`#configure`] method properly.  See the docs.

`#configure(config, successFn, failureFn)`

```javascript
bgGeo.configure({  // <-- 1st param is config params
  desiredAccuracy: 0,
  distanceFilter: 10,
  debug: true,
  logLevel: 5
}, (state) => {
  console.log('- Configure success: ', state);
  bgGeo.start();  // <-- start the plugin
});
```
