### ISSUE TITLE
Adquire android version for cordova and for react native

### ISSUE THREAD

**Issue by nschurmann** [transistorsoft/cordova-background-geolocation-lt#327]
Hello, currently we have our version of our app that is built with cordova. But in a short term we are going to migrate to react native. We are using this plugin for the iOS version and would really love to use it in our android version. But our main concern is that we may need to purchase two licences. Is there a way that we can purchase only one licence that will work in cordova version and, later, in react native version??

Thanks,

**Comment by christocracy** [comment]
Sorry, they're two different products, each requiring its own license.
