### ISSUE TITLE
Location tracking not working in Android

### ISSUE THREAD

**Issue by dtruel** [transistorsoft/cordova-background-geolocation-lt#329]
## Your Environment
Platform: Android
Plugin version: cordova-background-geolocation 2.4.0
OS Version: 5.1.1
Cordova version 6.5.0
Cordova platform version: android 6.1.2

## Expected Behavior

It should track location changes

## Actual Behavior

It gives 2 locations immediately the server, but nothing after that.  It doesn't work in the foreground or background.  I will walk around with the app open, plenty of distance, and it won't record any motion changes.

I also ran this in the android simulator and inputted a GPX file with points.  The logs for this were simple - it also wouldn't report anything to the server either
```
05-01 13:50:23.145 5035-7145/com.weathercall.push D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-01 13:50:23.179 5035-7145/com.weathercall.push D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
05-01 13:53:23.685 5035-7148/com.weathercall.push D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-01 13:53:23.711 5035-7148/com.weathercall.push D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
05-01 13:56:24.219 5035-7151/com.weathercall.push D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-01 13:56:24.248 5035-7151/com.weathercall.push D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
05-01 13:59:24.753 5035-8025/com.weathercall.push D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-01 13:59:24.775 5035-8025/com.weathercall.push D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
```

## Steps to Reproduce

```javascript
        BackgroundGeolocation.configure({
            desiredAccuracy:  0,
            distanceFilter:0,
            activityRecognitionInterval: 0,
            url: defaultPostLocation,
            stopOnTerminate:false,
            startOnBoot:true,
            batchSync:false,
            autoSync:true,
            method: "POST",
            forceReloadOnMotionChange: true,
            debug:true,
            params: {
                device: device
            }
        },function(state){
            console.log('BackgroundGeolocation initizalized ', state);
            BackgroundGeolocation.start();
        });

        BackgroundGeolocation.on('location',function(location, taskId){
            console.log("------------Location gotten------------------")
            BackgroundGeolocation.finish(taskId);
        })
```

## Debug logs
The logs 
 http://turbobuilt.com/wc-app/new-log.txt
This log shows the initial location updates right on startup, but I don't get anything after that.

**Comment by christocracy** [comment]
When you simulate location, you must manually execute `changePace(true)` before the plugin will record locations.  The plugin uses accelerometer-based MotionDetection apis to start listening to locations.

Merely pumping locations into your app will not cause the plugin to begin *listening* to those simulated locations.

You can simulate movement by shaking your device vigorously.  You can observe the logs and watch the `onActivityRecognitionResult` change.

**Comment by christocracy** [comment]
Also, keeping the app open has no effect upon the plugin's operation.  There is no difference in behaviour on Android whether you have your app in the foreground vs background.

**Comment by christocracy** [comment]
Also, the latest version of the plugin is `2.6.0`

**Comment by dtruel** [comment]
Ok, I will try these debugging procedures.  Thank you.

**Comment by dtruel** [comment]
All right, I have found that "shaking" the simulator causes it to pick up location changes!  Now the only issue is with my real phone.  I had an earlier version of the plugin working on my phone, and am not sure why it wouldn't be working now.  Also this same configuration works on an iOS device.

-I know location services are working because it sends an initial location when I start the app
-I know accelerometer is working because I downloaded another app that uses accelerometer and it works perfectly

I sent the apk to somebody else to test with their android phone.  Any ideas for further debugging steps?

**Comment by dtruel** [comment]
More info:

I downloaded the sample app, and I have the same problem!  It shows it making the initial geofence, but after driving about a mile away, it still hadn't enabled aggressive background location tracking, and so it hadn't detected any movement.  The plugin switch was on in the top right.  Then, while in the car, I clicked the play button at the bottom right, and it began tracking.  So it seems the problem is with the ActivityRecognition API

{
"isMoving": true,
"enabled": true,
"odometer": 251.6681,
"schedulerEnabled": false,
"trackingMode": "location",
"distanceFilter": 10,
"desiredAccuracy": 0,
"desiredOdometerAccuracy": 100,
"locationUpdateInterval": 1000,
"fastestLocationUpdateInterval": 10000,
"locationTimeout": 60,
"deferTime": 0,
"disableElasticity": false,
"activityRecognitionInterval": 10000,
"minimumActivityRecognitionConfidence": 75,
"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
"disableStopDetection": false,
"stationaryRadius": 25,
"stopTimeout": 0,
"url": "http:\/\/mysite.com\/post-location.php",
"method": "POST",
"autoSync": false,
"autoSyncThreshold": 0,
"batchSync": false,
"maxBatchSize": -1,
"params": {
"device": {
"model": "Coolpad 3320A",
"platform": "Android",
"uuid": "ccf44e044449fba",
"version": "5.1.1",
"manufacturer": "Coolpad",
"framework": "Cordova"
}

**Comment by christocracy** [comment]
Use the Email Logs button in Settings screen to get the logs.

**Comment by christocracy** [comment]
And try testing with a different device (what make/model *are* you using?).

If your device won't respond to the ActivityRecognition API, there's nothing to be done.

**Comment by christocracy** [comment]
Nevermind, I see it's a ["Coolpad 3320A"](http://www.phonearena.com/phones/Coolpad-Rogue_id9784).  This doesn't look like an ideal device to use the plugin with.

It doesn't have a gyroscope.  The Android MotionDetection API is based upon accelerometer **and** gyroscope.

**Comment by dtruel** [comment]
Aha, I was beginning to suspect it was something about the phone.  I will test on another one.

**Comment by dtruel** [comment]
I have tested on a higher end phone, and it is working!   You are so smart and highly knowledgeable.  Thank you for your help.
