### ISSUE TITLE
Invalid Date error while running on iPhone

### ISSUE THREAD

**Issue by neversun** [transistorsoft/cordova-background-geolocation-lt#33]
Hey,

I am using background geolocation plugin (free) for iPhone. While using the simulator it works fine (location is emulated via Debug -> Location -> City Bicyle Ride).

But once deployed on a real iPhone the location callback is not called anymore.

I'm getting an 'Invalid Date' error on calling to BackgroundGeolocationService (taken from your example app) with method GetCurrentPosition():
```
> BackgroundGeolocationService.getCurrentPosition()
< undefined
[Log] ************************************************************************************* (console-via-logger.js, line 173)
[Error] BackgroundGeolocation caught a Javascript Exception in your application code
	(anonyme Funktion)
	_runBackgroundTask
	mySuccess
	callbackFromNative
	(anonyme Funktion)
	nativeEvalAndFetch
	nativeCallback
	(anonyme Funktion)
[Log]  while running in a background thread.  Auto-finishing background-task: – 14 (console-via-logger.js, line 173)
[Log]  to prevent application crash (console-via-logger.js, line 173)
[Log] ************************************************************************************* (console-via-logger.js, line 173)
[Log] STACK: (console-via-logger.js, line 173)
 – "toISOString@[native code]↵toJSON@[native code]↵stringify@[native code]↵fireLocationListeners@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/js/services/backgroundGeolocation.js:109:82↵file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:38:29↵_runBackgroundTask@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:356:26↵mySuccess@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:37:34↵callbackFromNative@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:293:63↵file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:1109:35↵nativeEvalAndFetch@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:1117:13↵nativeCallback@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:1106:38↵global code@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/index.html#/:1:47"
[Error] RangeError: Invalid Date 
	(anonyme Funktion)
	_runBackgroundTask
	mySuccess
	callbackFromNative
	(anonyme Funktion)
	nativeEvalAndFetch
	nativeCallback
	(anonyme Funktion)
[Log] calculateWatt (console-via-logger.js, line 173)
```

**Comment by neversun** [comment]
The line 109
```
console.log('[js] BackgroundGeolocation location received: ' + JSON.stringify(location));
````
from your Angular service (out of example app) is responsible for the crash.

Log of `JSON.stringify(location)` in Safari console 
```
Object = $1
activity: {type: "still", confidence: 100}
battery: {level: 1, is_charging: 1}
coords: {speed: 0, longitude: 8.58015613631213, latitude: 50.14426436745575, accuracy: 30, heading: -1, …}
is_moving: true
timestamp: Invalid Date
Keine Eigenschaften.
Date Prototyp
uuid: "82E06494-62CA-4151-B911-400689DCDBDB"
Object Prototyp

**Comment by christocracy** [comment]
I've never had a problem with that,  I'm not sure I'll be able to easily
duplicate that error.

On Thursday, November 5, 2015, Robert Scheinpflug <notifications@github.com>
wrote:

> Hey,
>
> I am using background geolocation plugin (free) for iPhone. While using
> the simulator it works fine (location is emulated via Debug -> Location ->
> City Bicyle Ride).
>
> But once deployed on a real iPhone the location callback is not called
> anymore.
>
> I'm getting an 'Invalid Date' error on calling to
> BackgroundGeolocationService (taken from your example app) with method
> GetCurrentPosition():
>
> > BackgroundGeolocationService.getCurrentPosition()
> < undefined
> [Log] ************************************************************************************* (console-via-logger.js, line 173)
> [Error] BackgroundGeolocation caught a Javascript Exception in your application code
>     (anonyme Funktion)
>     _runBackgroundTask
>     mySuccess
>     callbackFromNative
>     (anonyme Funktion)
>     nativeEvalAndFetch
>     nativeCallback
>     (anonyme Funktion)
> [Log]  while running in a background thread.  Auto-finishing background-task: – 14 (console-via-logger.js, line 173)
> [Log]  to prevent application crash (console-via-logger.js, line 173)
> [Log] ************************************************************************************* (console-via-logger.js, line 173)
> [Log] STACK: (console-via-logger.js, line 173)
>  – "toISOString@[native code]↵toJSON@[native code]↵stringify@[native code]↵fireLocationListeners@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/js/services/backgroundGeolocation.js:109:82↵file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:38:29↵_runBackgroundTask@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:356:26↵mySuccess@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:37:34↵callbackFromNative@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:293:63↵file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:1109:35↵nativeEvalAndFetch@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:1117:13↵nativeCallback@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/cordova.js:1106:38↵global code@file:///var/mobile/Containers/Bundle/Application/C33D902D-6792-4A23-B40C-112D343BF51C/BG%20Geo.app/www/index.html#/:1:47"
> [Error] RangeError: Invalid Date
>     (anonyme Funktion)
>     _runBackgroundTask
>     mySuccess
>     callbackFromNative
>     (anonyme Funktion)
>     nativeEvalAndFetch
>     nativeCallback
>     (anonyme Funktion)
> [Log] calculateWatt (console-via-logger.js, line 173)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/33>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Confirmed.  The sync-callback is sending back the entire SQLite record, rather than just the `location` JSON *from* that record.

```
{
  "id": 66,
  "timestamp": "Invalid Date",
  "location": {...}  // <-- this is the object which *should* be returned.
}
```

Will be fixed in a few hours.

**Comment by neversun** [comment]
Nice, thank you! :blush:

**Comment by rtholmes** [comment]
Just following up (not sure if it is related), with the latest from head (9f36cd9459c02a8c5c4b76fa41fdde823b5500ad) the timestamp is coming through as a Date formatted object rather than a timestamp (long):

```
{"is_moving":true,"battery":{"level":1,"is_charging":1},"coords":
{"altitude":98.29133605957031,"speed":0,"heading":-1,"altitudeAccuracy":3,"accuracy":10,"latitude":59.26094068684546,"longitude":-113.2493278012827},
"is_heartbeat":false,
"timestamp":"2015-12-03T16:55:15.000Z",
"activity":{"type":"unknown","confidence":100},"uuid":"16575262-9201-4565-9062-CD6D3882DC6C"}
```

**Comment by christocracy** [comment]
This is correct.  my plugin sends back timestamp in ISO-8601 UTC format.

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema


On Thu, Dec 3, 2015 at 12:03 PM, rtholmes <notifications@github.com> wrote:

> Just following up (not sure if it is related), with the latest from head (
> 9f36cd9
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/commit/9f36cd9459c02a8c5c4b76fa41fdde823b5500ad>)
> the timestamp is coming through as a Date formatted object rather than a
> timestamp (long):
>
> {"is_moving":true,"battery":{"level":1,"is_charging":1},"coords":
> {"altitude":98.29133605957031,"speed":0,"heading":-1,"altitudeAccuracy":3,"accuracy":10,"latitude":59.26094068684546,"longitude":-113.2493278012827},
> "is_heartbeat":false,
> "timestamp":"2015-12-03T16:55:15.000Z",
> "activity":{"type":"unknown","confidence":100},"uuid":"16575262-9201-4565-9062-CD6D3882DC6C"}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/33#issuecomment-161717075>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by rtholmes** [comment]
Ok, sorry about that. For some reason I thought the format would be the same as for cordova-plugin-geolocation which formats the ```timestamp``` as a ```DOMTimestamp``` (http://dev.w3.org/geo/api/spec-source.html#position_interface).

Thanks for letting me know.

**Comment by christocracy** [comment]
Nope.  I like ISO-8601 UTC better.

On Thu, Dec 3, 2015 at 12:15 PM, rtholmes <notifications@github.com> wrote:

> Ok, sorry about that. For some reason I thought the format would be the
> same as for cordova-plugin-geolocation which formats the timestamp as a
> DOMTimestamp (
> http://dev.w3.org/geo/api/spec-source.html#position_interface).
>
> Thanks for letting me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/33#issuecomment-161720300>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
