### ISSUE TITLE
Dependency error: with cordova-plugin-cocoalumberjack@^0.0.2

### ISSUE THREAD

**Issue by danfleck** [transistorsoft/cordova-background-geolocation-lt#331]
After upgrading to the latest Cordova version 7.0 and removing platform ios. Get an error when adding the platform back:

```
Failed to install 'cordova-background-geolocation-lt': Error
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:581:33
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Version of installed plugin: "cordova-plugin-cocoalumberjack@0.0.1" does not satisfy dependency plugin requirement "cordova-plugin-cocoalumberjack@^0.0.2". Try --force to use installed plugin as dependency.
```

**Comment by christocracy** [comment]
Show me your plugins:
```
$ cordova plugins
```

**Comment by danfleck** [comment]
call-number 0.0.2 "Cordova Call Number Plugin"
com.instabug.cordova.plugin 1.0.0 "instabug-cordova"
cordova-background-geolocation-lt 2.6.0 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.6.2 "AddSwiftSupport"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-settings-hook 0.2.4 "Cordova Settings Hooks"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
es6-promise-plugin 3.0.2 "Promise"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"
onesignal-cordova-dependencies-compat 1.0.0 "OneSignal Android Dependencies"
onesignal-cordova-plugin-pgb-compat 2.0.10 "OneSignal Push Notifications PGB Compat"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"

**Comment by christocracy** [comment]
Remove / re-add `cordova-background-geolocation-lt`

**Comment by danfleck** [comment]
Same error after remove/re-add.

cordova plugins rm cordova-background-geolocation-lt
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-background-fetch from android
Uninstalling cordova-background-geolocation-lt from android
Subproject Path: CordovaLib
Uninstalling 3 dependent plugins.
Uninstalling cordova-plugin-dialogs from ios
Uninstalling cordova-plugin-background-fetch from ios
Uninstalling cordova-plugin-cocoalumberjack from ios
Uninstalling cordova-background-geolocation-lt from ios
Removing "cordova-background-geolocation-lt"
Removing plugin cordova-background-geolocation-lt from config.xml file...
Removing cordova-background-geolocation-lt from package.json


cordova plugins add cordova-background-geolocation-lt
Installing "cordova-background-geolocation-lt" for android
Plugin dependency "cordova-plugin-dialogs@1.2.1" already fetched, using that version.
Dependent plugin "cordova-plugin-dialogs" already installed on android.
Installing "cordova-plugin-background-fetch" for android
Subproject Path: CordovaLib
Installing "cordova-background-geolocation-lt" for ios
Plugin dependency "cordova-plugin-dialogs@1.2.1" already fetched, using that version.
Installing "cordova-plugin-dialogs" for ios
Plugin dependency "cordova-plugin-background-fetch@4.0.2" already fetched, using that version.
Installing "cordova-plugin-background-fetch" for ios
Failed to install 'cordova-background-geolocation-lt': Error
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:581:33
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Version of installed plugin: "cordova-plugin-cocoalumberjack@0.0.1" does not satisfy dependency plugin requirement "cordova-plugin-cocoalumberjack@^0.0.2". Try --force to use installed plugin as dependency.

**Comment by christocracy** [comment]
I forgot to increment the `plugin.xml` version of `cordova-plugin-cocoalumberjack` to match its `package.json`.  I've bumped it to version `0.0.4` and published.

```
$ cordova plugin remove --force cordova-plugin-cocoalumberjack
$ cordova plugin add cordova-plugin-cocoalumberjack
$ cordova platform remove ios
$ cordova platform add ios

$ cordova plugins
  cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
```

**Comment by danfleck** [comment]
Oddly, now I get this error:

Error: Version of installed plugin: "cordova-plugin-cocoalumberjack@0.0.4" does not satisfy dependency plugin requirement "cordova-plugin-cocoalumberjack@^0.0.2". Try --force to use installed plugin as dependency.

**Comment by christocracy** [comment]
Hmm, seems the dependency should be defined as `~0.0.2` -- not `^0.0.2`.  Crap.

There's really no difference in the underlying code between these versions.  Does it work when you force install it?  I'm due to publish an updated stable release for background-geolocation.  I'll do that next week.

**Comment by danfleck** [comment]
Yes... it seems to work fine with --force so I'm good till you get the stable release out. No problem. Want me to close this or wait till stable?

**Comment by christocracy** [comment]
Yes, this can be closed.  I'll fix it in the premium version first.

**Comment by sergiomartell** [comment]
Hey Chris,

I was also having this problem and tried to --force install the plugin and got this error: 

```
Failed to install 'cordova-background-geolocation': SyntaxError: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "/" found.
    at peg$buildStructuredError (/Users/admin/git/teemRC1/platforms/ios/cordova/node_modules/xcode/lib/parser/pbxproj.js:412:12)
    at Object.peg$parse [as parse] (/Users/admin/git/teemRC1/platforms/ios/cordova/node_modules/xcode/lib/parser/pbxproj.js:1886:11)
    at pbxProject.parseSync (/Users/admin/git/teemRC1/platforms/ios/cordova/node_modules/xcode/lib/pbxProject.js:46:24)
    at Object.parseProjectFile [as parse] (/Users/admin/git/teemRC1/platforms/ios/cordova/lib/projectFile.js:43:15)
    at Api.addPlugin (/Users/admin/git/teemRC1/platforms/ios/cordova/Api.js:224:33)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:619:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:379:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
Error: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "/" found.
```

What can I do to fix this?

Thanks!

**Comment by vijayb** [comment]
I'm having the same issue, Chris. Has the solution changed since May? thanks

**Comment by christocracy** [comment]
Ask yourself:  what is the version of cocoa-lumberjack plugin which is required by the background-geolocation (see background-geolocation plugin.xml for the version you have installed, where master represents latest version 2.8.5)

Do you have that version installed in your app?

If not remove it and make sure your app has the required version.

**Comment by vijayb** [comment]
Hey Chris, thanks for the pointer:

geolocation plugin.xml:
<dependency id="cordova-plugin-cocoalumberjack" version="^0.0.2" />

And:
cordova plugins list:
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"

It's strange though that in my package.json I see under dependencies:
    "cordova-plugin-cocoalumberjack": "0.0.2",

so I'm not sure why it installed the old version. At any rate I'm going to try to upgrade and see if it fixes the problem. Thanks again for the pointer
