### ISSUE TITLE
locationAuthorizationRequest default value

### ISSUE THREAD

**Issue by bacemtabikh** [transistorsoft/cordova-background-geolocation-lt#332]
## Your Environment
* Plugin version: 2.6.0
* Platform: iOS
* OS version: 10.3.1
* Device manufacturer / model:

* Plugin config

## Expected Behavior

locationAuthorizationRequest should have as default value "always".

## Actual Behavior

locationAuthorizationRequest is coming "WhenInUse".

Thanks for your help.

**Comment by christocracy** [comment]
This is most likely because you have a permissions "tug-of-war" with another plugin which is requesting location permission first, such as `cordova-plugin-geolocation`, which is not required when using this plugin.
