### ISSUE TITLE
Assertion failure in -[CLLocationManager setAllowsBackgroundLocationUpdates:]

### ISSUE THREAD

**Issue by riderx** [transistorsoft/cordova-background-geolocation-lt#336]
## Your Environment
* Plugin version: 2.7.0
* Platform: iOS
* OS version: 10.3
* Device manufacturer / model: iphone SE
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):
  android 6.2.3
  ios 4.3.1
* Plugin config
```
    var SETTINGS = {
      common: {
        'url': appConfig.ENV.baseUrl + '/api/positions/',
        'httpRootProperty': '.',
        'params': {
          'userId': -1,
          'version': '0.0.2'
        },
        'headers': {
          'accept-version': ['0.0.1', '0.0.2', '0.0.3', '0.0.4'],
          'appkey': appConfig.appkey
        },
        'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "time":<% timestamp %> }',
        'autoSync': true,
        'autoSyncThreshold': 0,
        'stopOnTerminate': false,
        'startOnBoot': false,
        'stopTimeout': 1,
        'activityRecognitionInterval': 10000,
        'debug': false,
        'deferTime': 0,
        'disableElasticity': false,
        'heartbeatInterval': 60,
        'distanceFilter': 50,
        'stationaryRadius': 1,
        'desiredAccuracy': 100,
        'locationAuthorizationAlert': {
          'titleWhenNotEnabled': 'Le service de Géolocalisation est éteint',
          'titleWhenOff': 'La Géolocalisation est désactivée en arrière plan.',
          'instructions': 'Pour recevoir les livraisons tu dois réactiver la géolocalisation dans Réglages > You2You > Toujours activé',
          'cancelButton': 'Annuler',
          'settingsButton': 'Réglages'
        }
      },
      iOS: {
        // 'desiredAccuracy': 100,
        // 'distanceFilter': 20,
        'stationaryRadius': 20,
        'activityType': 'Other',
        'stopDetectionDelay': 0,
        'preventSuspend': true,
        // 'preventSuspend': false,
        'pausesLocationUpdatesAutomatically': undefined,
        'useSignificantChangesOnly': false,
        'disableMotionActivityUpdates': false
      },
      Android: {
        // 'desiredAccuracy': 100,
        // 'distanceFilter': 20,
        'locationUpdateInterval': 5000,
        'fastestLocationUpdateInterval': 10000,
        'notificationIcon': 'resources/android/icon.png',
        'triggerActivities': 'in_vehicle, on_bicycle, running, walking, on_foot',
        'forceReloadOnBoot': false,
        'forceReloadOnMotionChange': false,
        'forceReloadOnLocationChange': false,
        'forceReloadOnGeofence': false,
        'forceReloadOnHeartbeat': false,
        'foregroundService': true
      }
    };
```
## Expected Behavior

app run 

## Actual Behavior

app provide an exeption at run : 

2017-05-11 16:30:04.776 Youzer[1272:5378381] *** Assertion failure in -[CLLocationManager setAllowsBackgroundLocationUpdates:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreLocationFramework_Sim/CoreLocation-2101.0.62/Framework/CoreLocation/CLLocationManager.m:649
2017-05-11 16:30:04.794 Youzer[1272:5378381] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ff54b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010f990141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ff58cf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010f52a3b6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   CoreLocation                        0x000000010dff995b CLClientGetCapabilities + 10739
	5   Youzer                              0x000000010cdbe237 -[TSGeofenceManager init] + 147
	6   Youzer                              0x000000010cdc3fd3 -[TSLocationManager init] + 1181
	7   Youzer                              0x000000010cdc3b10 __35+[TSLocationManager sharedInstance]_block_invoke + 38
	8   libdispatch.dylib                   0x000000011240b05c _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00000001123f09a1 dispatch_once_f + 503
	10  Youzer                              0x000000010cdc3ae8 +[TSLocationManager sharedInstance] + 102
	11  Youzer                              0x000000010cc74f81 -[CDVBackgroundGeolocation pluginInitialize] + 49
	12  Youzer                              0x000000010cce6ebb -[CDVViewController registerPlugin:withClassName:] + 315
	13  Youzer                              0x000000010cce72aa -[CDVViewController getCommandInstance:] + 410
	14  Youzer                              0x000000010cceb7b4 -[CDVCommandDelegateImpl getCommandInstance:] + 100
	15  Youzer                              0x000000010ccf4e55 -[CDVCommandQueue execute:] + 341
	16  Youzer                              0x000000010ccf48c1 -[CDVCommandQueue executePending] + 833
	17  Youzer                              0x000000010ccf346e -[CDVUIWebViewNavigationDelegate webView:shouldStartLoadWithRequest:navigationType:] + 478
	18  Youzer                              0x000000010cce9a19 -[CDVUIWebViewDelegate webView:shouldStartLoadWithRequest:navigationType:] + 265
	19  UIKit                               0x0000000110e292f0 -[UIWebView webView:decidePolicyForNavigationAction:request:frame:decisionListener:] + 306
	20  CoreFoundation                      0x000000010fedcc6c __invoking___ + 140
	21  CoreFoundation                      0x000000010fedcb40 -[NSInvocation invoke] + 320
	22  CoreFoundation                      0x000000010fef4956 -[NSInvocation invokeWithTarget:] + 54
	23  WebKitLegacy                        0x0000000117ca2444 -[_WebSafeForwarder forwardInvocation:] + 148
	24  CoreFoundation                      0x000000010fedb656 ___forwarding___ + 534
	25  CoreFoundation                      0x000000010fedb3b8 _CF_forwarding_prep_0 + 120
	26  CoreFoundation                      0x000000010fedcc6c __invoking___ + 140
	27  CoreFoundation                      0x000000010fedcb40 -[NSInvocation invoke] + 320
	28  WebCore                             0x00000001197e3e87 _ZL20HandleDelegateSourcePv + 103
	29  CoreFoundation                      0x000000010fefac01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	30  CoreFoundation                      0x000000010fee00cf __CFRunLoopDoSources0 + 527
	31  CoreFoundation                      0x000000010fedf5ff __CFRunLoopRun + 911
	32  CoreFoundation                      0x000000010fedf016 CFRunLoopRunSpecific + 406
	33  GraphicsServices                    0x00000001132b0a24 GSEventRunModal + 62
	34  UIKit                               0x0000000110aa30d4 UIApplicationMain + 159
	35  Youzer                              0x000000010cbd75f1 main + 65
	36  libdyld.dylib                       0x000000011245765d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Somehow, you've managed to disable `[x] Location updates` In XCode **Background Modes**.

The plugin is supposed to automatically set that.  You didn't [do this](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-disabling-background-location), did you?

**Comment by christocracy** [comment]
Also note in [Configuring the Plugin](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)

❗️ To apply changes to these <variable />, you must remove/re-add the plugin.

**Comment by riderx** [comment]
Hi i didn't [x] Location updates In XCode Background Modes,
i just update your plugin and i get this problem, so i just delete my plugin and platform, and add them again but i get the same issue 😢

**Comment by christocracy** [comment]
Show me a screenshot of you XCode **Background Modes**
![](https://www.dropbox.com/s/hv745192tp07lz7/Screenshot%202017-05-11%2011.39.43.png?dl=1)

**Comment by christocracy** [comment]
**NO**.  Where did you see instructions to do this?
```
<variable name="BACKGROUND_MODE_LOCATION" value="location" />
```

**Comment by christocracy** [comment]
Just **delete** this line:
```
<variable name="BACKGROUND_MODE_LOCATION" value="location" />
```

**Comment by christocracy** [comment]
And remember:

❗️ To apply changes to these , you must remove/re-add the plugin.

**Comment by christocracy** [comment]
As the docs say for [`BACKGROUND_MODE_LOCATION`](https://github.com/transistorsoft/cordova-background-geolocation-lt#variable-background_mode_location-ltstringgtlocationltstringgt-ios):

>[iOS] Adds the iOS background-mode location to your iOS .plist file. This is the default behaviour. To disable this, (ie: for those using useSignificantChangesOnly), provide an empty-string:

  <variable name="BACKGROUND_MODE_LOCATION" value="" />
**WARNING If you do want the default behaviour of background-location updates, simply IGNORE this variable -- Do NOT even provide it**. **If you do provide it, you must provide the full escaped XML value of &lt;string&gt;location&lt;/string&gt; (the default value when not provided), not just location.**

**Comment by riderx** [comment]
Yea i just read it thank's for your quick anwser, i don't know why that  apear in my config.xml file.

**Comment by christocracy** [comment]
>thank's for your quick anwser

This is why I charge for the plugin.  Dedicated, rapid support.

**Comment by riderx** [comment]
<img width="657" alt="screen shot 2017-05-11 at 18 46 14" src="https://cloud.githubusercontent.com/assets/4084527/25961327/38adc3bc-367a-11e7-8151-a2a75e463ec4.png">
I still get the same issue ..
I have try to check location updates like in your screenshot but doesn't work 😞

**Comment by riderx** [comment]
Now i have that:
    <plugin name="cordova-background-geolocation-lt" spec="~2.7.0">
        <variable name="LICENSE" value="MYLICENCE" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required to send you notification of delivery on your road" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required to send you notification of delivery on your road" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
        <variable name="BACKGROUND_MODE_AUDIO" value="" />
    </plugin>

<img width="695" alt="screen shot 2017-05-11 at 18 53 29" src="https://cloud.githubusercontent.com/assets/4084527/25961610/25911a58-367b-11e7-9fa8-57b0ac7104df.png">

But i still get the same assertion 😞

**Comment by riderx** [comment]
Okay i just delete the app on the simulator and that work again 😎

**Comment by christocracy** [comment]
Is this issue solved?

**Comment by riderx** [comment]
@christocracy have you any idea of why i don't recieve http post with this config ?

**Comment by christocracy** [comment]
please stay in-topic.  Don't use issues for open-ended support threads.  Please open a new issue for unrelated question.  

Keep an eye on your logs.
