### ISSUE TITLE
http failure:  0 {"status":0,"responseText":""}

### ISSUE THREAD

**Issue by riderx** [transistorsoft/cordova-background-geolocation-lt#337]
## Your Environment
* Plugin version: 2.7.0
* Platform: iOS 
* OS version: 10.3
* Device manufacturer / model: iphone SE
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): 4.4
* Plugin config
    var SETTINGS = {
      common: {
        'url': appConfig.ENV.baseUrl + '/api/positions/ ',
        'httpRootProperty': '.',
        'params': {
          'version': '0.0.2',
          'userId': -1,
        },
        'headers': {
          'accept-version': '[\'0.0.1\', \'0.0.2\', \'0.0.3\', \'0.0.4\']',
          'appkey': appConfig.appkey
        },
        'method': 'POST',
        'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, time":"<% timestamp %>" }',
        'autoSync': true,
        'autoSyncThreshold': 0,
        'stopOnTerminate': false,
        'startOnBoot': false,
        'stopTimeout': 1,
        'activityRecognitionInterval': 10000,
        'debug': false,
        'deferTime': 0,
        'disableElasticity': false,
        'heartbeatInterval': 60,
        'distanceFilter': 50,
        'stationaryRadius': 1,
        'desiredAccuracy': 100,
        'locationAuthorizationAlert': {
          'titleWhenNotEnabled': 'Le service de Géolocalisation est éteint',
          'titleWhenOff': 'La Géolocalisation est désactivée en arrière plan.',
          'instructions': 'Pour recevoir les livraisons tu dois réactiver la géolocalisation dans Réglages > You2You > Toujours activé',
          'cancelButton': 'Annuler',
          'settingsButton': 'Réglages'
        }
      },
      iOS: {
        // 'desiredAccuracy': 100,
        // 'distanceFilter': 20,
        'stationaryRadius': 20,
        'activityType': 'Other',
        'stopDetectionDelay': 0,
        'preventSuspend': true,
        // 'preventSuspend': false,
        'pausesLocationUpdatesAutomatically': undefined,
        'useSignificantChangesOnly': false,
        'disableMotionActivityUpdates': false
      },
      Android: {
        // 'desiredAccuracy': 100,
        // 'distanceFilter': 20,
        'locationUpdateInterval': 5000,
        'fastestLocationUpdateInterval': 10000,
        'notificationIcon': 'resources/android/icon.png',
        'triggerActivities': 'in_vehicle, on_bicycle, running, walking, on_foot',
        'forceReloadOnBoot': false,
        'forceReloadOnMotionChange': false,
        'forceReloadOnLocationChange': false,
        'forceReloadOnGeofence': false,
        'forceReloadOnHeartbeat': false,
        'foregroundService': true
      }
    };

## Expected Behavior

Receive http post on my server 

## Actual Behavior

nothing receive

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Check your url.  What the logs from XCode.  HTTP status 0 means server not found.

**Comment by christocracy** [comment]
This is not a problem with the plugin.  This is networking issue.  Either your url is incorrect or your device has no network connection to that server.

**Comment by riderx** [comment]
i have try to copy the URL and send the same object in postman that work proprely

**Comment by riderx** [comment]
there it's the Url in the conf file: https://app.you2you.fr/api/positions/

**Comment by christocracy** [comment]
When I use your url in my demo app (running on device):
```
⚠️-[TSHttpService doPost:] HTTP ERROR: 400
***
* {"statusCode":400,"title":"Invalid Version","detail":"Supported Versions: [0.0.1, 0.0.2, 0.0.3, 0.0.4]"}
```
I clearly hit your server.  You have a network issue on your device.

**Comment by riderx** [comment]
i don't have network issue have you try with the same configuration as me ?

```
'url': appConfig.ENV.baseUrl + '/api/positions/ ',
'httpRootProperty': '.',
'params': {
'version': '0.0.2',
'userId': -1,
},
'headers': {
'accept-version': '['0.0.1', '0.0.2', '0.0.3', '0.0.4']',
'appkey': appConfig.appkey
},
'method': 'POST',
'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, time":"<% timestamp %>" }',
'autoSync': true,
'autoSyncThreshold': 0,
```

**Comment by christocracy** [comment]
All other config params don't matter.  The point is, I was able to hit your `url` well enough for it to return a response `400`.  You're not even connecting to your server.

**Comment by christocracy** [comment]
Are you sure you've configured your iOS Plist to *allow* your app to hit your server?

![](https://www.dropbox.com/s/09tbu55syzyknz2/Screenshot%202017-05-12%2010.22.38.png?dl=1)

In my case, I've configured `Allow Arbitrary Loads: YES`, allowing my app to hit *any* server.  This is 100% an issue with your application.  It's not an issue with the plugin.

**Comment by riderx** [comment]
how i can get my data ou the same server and can't with your pluging that not logical.
look 
<img width="544" alt="screen shot 2017-05-12 at 16 31 28" src="https://cloud.githubusercontent.com/assets/4084527/26002695/c1c4fc9a-3730-11e7-8fa4-f5ab3e137220.png">

Also the pluging was craching when i put : 
```
'headers': {
'accept-version': ['0.0.1', '0.0.2', '0.0.3', '0.0.4'],
'appkey': appConfig.appkey
},
```
instead of:
```
'headers': {
'accept-version': '[\'0.0.1\', \'0.0.2\', \'0.0.3\', \'0.0.4\']',
'appkey': appConfig.appkey
},
```

**Comment by christocracy** [comment]
I have no idea why you can't hit your server but I can.  The problem is in your app / device.

>Also the pluging was craching when i put:

HTTP headers are expected to be `String` values.  If you want to send `Object` data in your header, convert your Array to JSON.

```
'headers': {
  'accept-version':  JSON.stringify(['0.0.1', '0.0.2', '0.0.3', '0.0.4']),
  'appkey': appConfig.appkey
}
```

**Comment by riderx** [comment]
now i get : 
`http failure:  400 {"status":400,"responseText":"{\"statusCode\":400,\"title\":\"Invalid Version\",\"detail\":\"Supported Versions: [0.0.1, 0.0.2, 0.0.3, 0.0.4]\"}"}`
with this configuration : 
```
        'url': appConfig.ENV.baseUrl + '/api/positions/',
        // 'httpRootProperty': '.',
        'params': {
          'userId': -1,
        },
        'headers': {
          // 'accept-version': '0.0.1',
          'appkey': appConfig.appkey
        },
        'method': 'PUT',
        // 'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, time":"<% timestamp %>" }',
        'autoSync': true,
        'autoSyncThreshold': 0,
```
so something look weird with your plugin, also with : 
        'url': appConfig.ENV.baseUrl + '/api/positions/',
         'httpRootProperty': '.',
        'params': {
          'userId': -1,
        },
        'headers': {
           'accept-version': '0.0.1',
          'appkey': appConfig.appkey
        },
        'method': 'PUT',
         'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, time":"<% timestamp %>" }',
        'autoSync': true,
        'autoSyncThreshold': 0,
```
 that just do nothing i don't get any feedback of this function:
```
      bgGeo.on('http', function (response) {
        console.log('http success: ', response.responseText, JSON.stringify(response));
      }, function (response) {
        console.log('http failure: ', response.status, JSON.stringify(response));
      });
```

**Comment by riderx** [comment]
ok with this conf : 

```
        'url': appConfig.ENV.baseUrl + '/api/positions/?version=0.0.2',
        'httpRootProperty': '.',
        'params': {
          'userId': -1,
        },
        'headers': {
          'accept-version': JSON.stringify(['0.0.1', '0.0.2', '0.0.3', '0.0.4']),
          'appkey': appConfig.appkey
        },
        'method': 'POST',
        'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, time":"<% timestamp %>" }',
        'autoSync': true,
        'autoSyncThreshold': 0,
```
that work propely i think : 
`'accept-version': '[\'0.0.1\', \'0.0.2\', \'0.0.3\', \'0.0.4\']',`
was breaking your pluging

**Comment by christocracy** [comment]
Yes, because you're providing invalid JSON.  Humans aren't meant to compose JSON -- machines are.
![](https://www.dropbox.com/s/iyi3im8fgab5ok8/Screenshot%202017-05-12%2010.54.15.png?dl=1)

**Comment by christocracy** [comment]
And how did you manage to finally successfully hit your url to *at least* return `400`.  I hit it successfully *without* providing *any* `headers` or `params`.

**Comment by riderx** [comment]
Yes probably, but you should trow an error to let us know that :) 
that have work on my remote server that does't work in the local env ... so i continue to test for the moment

**Comment by riderx** [comment]
ok i have delete these args:
```
 'httpRootProperty': '.',
'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, time":"<% timestamp %>" }',
```
now your plugin send propely the data i decide to parse them in your format

**Comment by christocracy** [comment]
Was there a problem with the locationTemplate?

**Comment by riderx** [comment]
Yes with this specific template that don't send the http request

**Comment by christocracy** [comment]
```
'locationTemplate': '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, time":"<% timestamp %>" }',
```

If that's the *exact* template you were using, you should probably be seeing a JSON error in the XCode logs, since you're missing the initial `"` before `time"`.

**Comment by riderx** [comment]
i don't get any explicit error for that, it was my problem. 
Thanks for your help !
