### ISSUE TITLE
Android error in loop getting coordinates

### ISSUE THREAD

**Issue by samukt** [transistorsoft/cordova-background-geolocation-lt#338]
## Your Environment
* Plugin version: 2.7.0
* Platform: Android
* OS version: 6.0
* Device manufacturer / model: LG G4
* Cordova version (`cordova -v`): 7.0.0
* Cordova platform version (`cordova platform ls`): 2.7.0
* Plugin config:

         bgGeo.configure({
                distanceFilter: 25,
                desiredAccuracy: 10,
                stationaryRadius: 25,
                disableElasticity: true,  // [ Keep distance filter locked. Default of it is change by the speed. ]
                locationUpdateInterval: 3600,
                fastestLocationUpdateInterval: 1000,
                useSignificantChangesOnly: false,
                deferTime: 3000,
                logLevel: 0,

        // iOS notification

        locationAuthorizationAlert: {
            titleWhenNotEnabled: "Localização em Background Inativa",
            titleWhenOff: "Serviços de Localização Inativo",
            instructions: "Para o Henry funcionar corretamente você deve habilitar \"Sempre\" nas configuraçōes de localização do iOS.",
            cancelButton: "Cancelar",
            settingsButton: "Configurar Agora"
        },

        // Application config
        debug: false,                           // <-- enable this hear sounds for background-geolocation life-cycle.
        forceReloadOnBoot: true,                // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
        stopOnTerminate: false,                 // <-- [Android] Allow the background-service to run headless when user closes the app.
        startOnBoot: true,                      // <-- [Android] Auto start background-service in headless mode when device is powered-up.
        preventSuspend: true,                   // iOS
        heartbeatInterval: 60,

        foregroundService: true,
        notificationTitle: "Henry",
        notificationText: (decoded_user.enterprise.name || ' - '),
        notificationColor: "#007acc",
        notificationIcon: 'drawable/icon',

        // HTTP / SQLite config
        url: '######'+decoded_user.id_user,
        batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        maxDaysToPersist: 7,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails

## Expected Behavior
It should returns to my server coordinates in short space of time.
25 meters or 3600 ms.

## Actual Behavior
I've noticed that when the plugin can't get the speed correctly and the phone has no internet connection it doesn't sends coordinates like it should.
I've noticed it only in Android until now.

## Context
I was testing sync system. 
So i turned off the 3G and made a travel by car.
When came back... The sync was not the expected.

Look at register_date:

Without Internet:
![captura de tela 2017-05-13 as 17 43 13](https://cloud.githubusercontent.com/assets/12994414/26029170/336d2ff0-3805-11e7-9e09-cfcad9169ee6.png)

The same phone and the same code but with internet:
![captura de tela 2017-05-13 as 18 10 20](https://cloud.githubusercontent.com/assets/12994414/26029280/7a7abef6-3807-11e7-9bf2-fee613572f85.png)
Look that it doesn't reached the speed too but sent coordinates correctly.

## What i'll do
If is speed -1  really impacting in a error to reach the locations:

    bgGeo.on("location"      , function(location, taskId) {
        var
            coords      = location.coords,
            timestamp   = location.timestamp,
            speed       = coords.speed,
            latitude    = coords.latitude,
            longitude   = coords.longitude,
            kmspeed     = parseFloat(speed) * 3.6,
            originalspeed = coords.speed,
            settings = {};

        if(originalspeed <= 0){
            settings = {
                distanceFilter: 0,
                locationUpdateInterval: 3600,
                deferTime: 0,
                desiredAccuracy: 0
            };
        }

        bgGeo.setConfig(
            settings,
            function(){ console.log("- setConfig success" , settings); },
            function(){ console.warn("- Failed to setConfig"); }
        );
     }

It should ignore distanceFilter and send a location each 3600 ms, right?

**Comment by christocracy** [comment]
- speed is only possible from GPS.  GPS is engaged only with desiredAccuracy: 0
- locationUpdateInterval is ignored when distamceFilter > 0

**Comment by samukt** [comment]
The same code (desiredAccuracy: 10) in others Android phones returns speed (in majority more recent phones). Why?

So...
In all cases, will it works, right?

    bgGeo.on("location", function(location, taskId) {
        var
            coords      = location.coords,
            timestamp   = location.timestamp,
            speed       = coords.speed,
            latitude    = coords.latitude,
            longitude   = coords.longitude,
            kmspeed     = parseFloat(speed) * 3.6,
            originalspeed = coords.speed,
            settings = {};

        if(originalspeed <= 0){
            settings = {
                distanceFilter: 0,
                locationUpdateInterval: 3600,
                deferTime: 0,
                desiredAccuracy: 0
            };
        }
    
        bgGeo.setConfig(
            settings,
            function(){ console.log("- setConfig success" , settings); },
            function(){ console.warn("- Failed to setConfig"); }
        );
     }


**Off-Topic**
i would to thank you so much for this plugin.
I'm using it for more than 6 months and it's awesome!!
You're the great!!
If you would like to see... i've made a script to reduce the battery use based on user speed and battery...

    bgGeo.on("location"      , function(location, taskId) {
        var
            coords      = location.coords,
            timestamp   = location.timestamp,
            speed       = coords.speed,
            latitude    = coords.latitude,
            longitude   = coords.longitude,
            kmspeed     = parseFloat(speed) * 3.6,
            originalspeed = coords.speed,
            settings = {};

        sessionStorage.setItem("last_latitude", latitude);
        sessionStorage.setItem("last_longitude", longitude);
        sessionStorage.setItem("last_geosend_date", new Date());
        sessionStorage.setItem("last_coords", JSON.stringify(coords));

        $(document).trigger('location_changed',[latitude,longitude]);
        $.henry.modules.routes.alerts.proximity(latitude,longitude);

        if(speed   <= 0) speed = 10;
        if(kmspeed <= 0) kmspeed = 36;

        var desired_accuracy = 10, desired_distance = kmspeed;

        if(desired_distance < 27)  desired_distance = 27;
        if(desired_distance > 100) desired_distance = 100;

        var time = (parseFloat(desired_distance) / parseFloat(speed)) * 1000;

        if(time < 1000) time = 1000;
        if(kmspeed > 60){ time *= (kmspeed/60); }
        if(time > 10000) time = 10000;


        if(desired_distance > 60){ desired_distance *= (desired_distance/60); }
        if(desired_distance > 300 && kmspeed > 100){ desired_distance = 300; }
        if(desired_distance > 150 && kmspeed < 100){ desired_distance = 100; }

        if(localStorage.getItem('battery_level') !== null){
            var battery = parseFloat(localStorage.getItem('battery_level'));
            var battery_plugged = parseFloat(localStorage.getItem('battery_plugged'));

            if(kmspeed < 25 && battery > 80){ desired_accuracy = 0; }
            if(battery_plugged == true || parseInt(battery_plugged) == 1){ desired_accuracy = 0; }
        }


        if(sessionStorage.getItem('foreground') == 1){
            settings = {
                distanceFilter: 0,
                locationUpdateInterval: 2000,
                deferTime: 0,
                desiredAccuracy: 0
            };
        }else{
            settings = {
                distanceFilter: (desired_distance < 25) ? 25 : desired_distance,
                locationUpdateInterval: Math.round(time),
                deferTime: Math.round(time * 0.9),
                desiredAccuracy: (desired_accuracy > 10) ? 10 : desired_accuracy
            };
        }

        if(originalspeed <= 0){
            settings = {
                distanceFilter: 0,
                locationUpdateInterval: 3600,
                deferTime: 0,
                desiredAccuracy: 0
            };
        }

        bgGeo.setConfig(
            settings,
            function(){ console.log("- setConfig success" , settings); },
            function(){ console.warn("- Failed to setConfig"); }
        );

        if(log.location) console.log("Atualizacao", settings, coords);

        bgGeo.finish(taskId);
    }, function(errorCode) {
        console.error("- Location error: ", errorCode);
    });

I know it's not perfect but in my case i reduced more then 70% of battery use.

**Comment by samukt** [comment]
Still didn't worked.

I think that some Android doesn't store coordinates when have no internet.

**Comment by christocracy** [comment]
I did a test this weekend with `desiredAccuracy: 10`.  

![](https://www.dropbox.com/s/ipqtee0gkbjjpkl/Screenshot%202017-05-15%2010.50.52.png?dl=1)

Yes, you'll see the odd location with a valid speed but those can come from *other* apps or Android itself requesting a high-accuracy location.

![](https://www.dropbox.com/s/83k5o4im7dp4my8/Screenshot%202017-05-15%2010.52.53.png?dl=1)

All locations for all apps come from the same source.  If you open google maps app with your app running in the background, those high-quality locations will be shared to all other apps currently requesting locations (your app will receive no power-blame for those locations; they come free).

**Comment by samukt** [comment]
So the problem is the phone?
LG G4 doesn't work and Moto G4 yes.

How can i retrieve a location each 3 seconds in LG G4?

**Comment by christocracy** [comment]
Logs please

**Comment by christocracy** [comment]
Btw, you're a Premium member.  You should not be using the Free repo anymore.

**Comment by samukt** [comment]
After a lot of test i found it.

THE PLUGIN IS NOT GETTING POSITION WHEN HAS NO 3G.

What can it be?

**Comment by christocracy** [comment]
If you don't use desiredAccuracy: 0 (the only value which uses gps), where do you think a location comes from?

**Comment by samukt** [comment]
Using desiredAccuracy: 0 keeps the error. 
It doesn't get coordinates.

**Comment by christocracy** [comment]
Are you observing the plugin logs?  See #getLog method in docs

**Comment by samukt** [comment]
`{
    "isMoving": true,
    "enabled": true,
    "odometer": 4592.5703,
    "schedulerEnabled": false,
    "trackingMode": "location",
    "distanceFilter": 0,
    "desiredAccuracy": 0,
    "desiredOdometerAccuracy": 100,
    "locationUpdateInterval": 3600,
    "fastestLocationUpdateInterval": 1000,
    "locationTimeout": 60,
    "deferTime": 0,
    "disableElasticity": true,
    "activityRecognitionInterval": 10000,
    "minimumActivityRecognitionConfidence": 75,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "disableStopDetection": false,
    "stationaryRadius": 25,
    "stopTimeout": 0,
    "url": "https:\/\/api.henryprojetos.net\/geoloc.php?user_id=71",
    "method": "POST",
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "maxBatchSize": -1,
    "params": {},
    "headers": {},
    "extras": {},
    "httpRootProperty": "location",
    "locationTemplate": "",
    "geofenceTemplate": "",
    "persist": true,
    "maxDaysToPersist": 7,
    "maxRecordsToPersist": -1,
    "locationsOrderDirection": "ASC",
    "geofenceProximityRadius": 1000,
    "geofenceInitialTriggerEntry": true,
    "stopOnTerminate": false,
    "startOnBoot": true,
    "heartbeatInterval": 60,
    "foregroundService": true,
    "notificationTitle": "Henry",
    "notificationText": "DevNinja",
    "notificationColor": "#007acc",
    "notificationIcon": "drawable\/icon",
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnBoot": true,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnSchedule": false,
    "stopAfterElapsedMinutes": 0,
    "schedule": [],
    "configureUrl": "",
    "configureInterval": -1,
    "debug": false,
    "logLevel": 0,
    "logMaxDays": 3
}
`

Please i need your help.
I need to send it to a client tomorrow.

**Comment by christocracy** [comment]
Those are not logs.  That is a config object.  Did you read the docs for #getLog method?

**Comment by samukt** [comment]
![captura de tela 2017-05-31 as 01 13 05](https://cloud.githubusercontent.com/assets/12994414/26615596/5d369a78-459e-11e7-9609-f7414bafe918.png)
Is this?

**Comment by samukt** [comment]
Wrote again all the code.

Worked.
I think it was a bug in my javascript.

Again, Thank you so much christocracy.
Your plugin is awesome and i'm sure to say that is one of the best things i ever saw in Cordova.

**Comment by christocracy** [comment]
Always, always, always **first observe the Javascript console for errors in your own code**.  

**Always**.
