### ISSUE TITLE
is possible to change the notification title/text on android after configure the plugin?

### ISSUE THREAD

**Issue by seedgabo** [transistorsoft/cordova-background-geolocation-lt#339]
i just wonder if possible change the notification after  plugin is runing, i tried change with setConfig method without results

**Comment by christocracy** [comment]
You would have to `#stop` / `#start` the plugin in order for you `#setConfig` change to take effect.  Not recommended to do that very often.

**Comment by seedgabo** [comment]
so, there is not a possible way to update the notification on the app without stop the plugin?

**Comment by christocracy** [comment]
No.
>You would have to #stop / #start the plugin in order for you #setConfig change to take effect.

**Comment by d34thkn3ll** [comment]
Sorry for being a little bit offtopic, but:

> You would have to #stop / #start the plugin in order for you #setConfig change to take effect. 

Do I have to restart plugin after **any** config updates, or your answer is relates only to notifications? It's not very clear to me. For example, if I reconfigure HTTP params (url, headers), should I restart plugin?

**Comment by christocracy** [comment]
That statement applies **only** to changing notification.
