### ISSUE TITLE
Performance ipad after update to iOS9.1

### ISSUE THREAD

**Issue by lavagu** [transistorsoft/cordova-background-geolocation-lt#34]
I implemented the background geoloc a few months ago.
Users never complained about performance issues on iOS 8.4.

Since 9.1, several users are complaining that other apps become laggy, non responsive when app with backgroundlocation is running. When app is not running, no lags.

I tested this for the last week. 
Sometimes i do have lags, most of the time i don't. Can't find a reason of the irregular behaviour.

Anybody experiencing same problems lately?

**Comment by christocracy** [comment]
There's nothing the plugin does that consumes any great amount of CPU.

**Comment by lavagu** [comment]
Chris,

might the bug that you fixed have caused my lagging issue?

**Comment by christocracy** [comment]
What bug that I fixed?

There is *no* lagging issue caused by my plugin.

On Friday, November 6, 2015, lavagu <notifications@github.com> wrote:

> Chris,
>
> might the bug that you fixed have caused my lagging issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/34#issuecomment-154343782>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
What evidence do you have to single out my plugin as the source of your problem?

**Comment by lavagu** [comment]
Chris
I'm not 'attacking' your plugin. I have no evidence, I was just wondering. 

Our salesrep mainly use 2 cordova apps. 
One of them uses this plugin.  
They can start the background geo with a button. if they're within 1km of a customer some data are fetched from the server automatically.
If they don't start background geo, they can manually search a customer and manually fetch the data from the server.

If the geo location is on, the other app (order registration app) becomes laggy, scrolling is slow.
   Lag is not constant, but occurs often.
If the geo location is off and they only work with the manual option there is no lag.

As i said, i'm not claiming that your plugin is not good. Just wondering if anyone else is experiencing same problems on 9.0 or 9.1. Plugin worked fine in test phase on 8.4. 
So the issues might be rather related to backgroundprocesses, timers on 9.*.

As this is the only backgroundprocesse i'm using, i thought this was the place to check.

**Comment by christocracy** [comment]
On second thought, try adding config `{disableStopDetection: true}`.  See if that changes anything.

**Comment by lavagu** [comment]
thanks for the feedback.
i made a build with the option and keep your updated next week when the users are on the road.

**Comment by lavagu** [comment]
chris

good news for you, bad news for me.
After some extensive testing, i can simulate the problem in the manual scenario as well.
So my problem is not related to the background geo loc.
It seems to me (i'm pretty new to js so i might be wrong again) that multilple http calls are causing the issue.
in the automatic scenario often multiple customers are found with in the geo range.
For every found customer a http call is launched to fetch some data.
In the manual scenario they usually fetch data for only one customer. But if you click multiple customers very fast (multiple http calls) other apps become laggy.
'funny' thing is : if you click home button and reopen the app from homescreen the lag is gone. 

thanks for your effort.
