### ISSUE TITLE
WiFi to WiFi in IOS

### ISSUE THREAD

**Issue by beritsistemas** [transistorsoft/cordova-background-geolocation-lt#340]
We have been testing the plugin in IOS and seems not to update to server in the scenario I will describe next.

We have tested the 2.7 and the last release 2.7.1 of your plugin.

## Your Environment
* Plugin version: 2.7.1
* Platform: iOS
* OS version: 10.3.1
* Device manufacturer / model: Iphone 5S
* Cordova version (`cordova -v`): 7.0.0
* Cordova platform version (`cordova platform ls`): ios 4.4.0
* Plugin config

{
                                                                                   "isMoving": false,
                                                                                   "enabled": true,
                                                                                   "odometer": 90759.2,
                                                                                   "schedulerEnabled": false,
                                                                                   "trackingMode": "location",
                                                                                   "distanceFilter": 1000,
                                                                                   "desiredAccuracy": 1000,
                                                                                   "desiredOdometerAccuracy": 100,
                                                                                   "locationUpdateInterval": 1000,
                                                                                   "fastestLocationUpdateInterval": 5000,
                                                                                   "locationTimeout": 60,
                                                                                   "deferTime": 0,
                                                                                   "disableElasticity": false,
                                                                                   "activityRecognitionInterval": 10000,
                                                                                   "minimumActivityRecognitionConfidence": 75,
                                                                                   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                                   "disableStopDetection": false,
                                                                                   "stationaryRadius": 1000,
                                                                                   "stopTimeout": 5,
                                                                                   "url": "https://server/location",
                                                                                   "method": "POST",
                                                                                   "autoSync": true,
                                                                                   "autoSyncThreshold": 0,
                                                                                   "batchSync": false,
                                                                                   "maxBatchSize": -1,
                                                                                   "params": {},
                                                                                   "headers": {
                                                                                   },
                                                                                   "extras": {},
                                                                                   "httpRootProperty": "location",
                                                                                   "locationTemplate": "",
                                                                                   "geofenceTemplate": "",
                                                                                   "persist": true,
                                                                                   "maxDaysToPersist": 1,
                                                                                   "maxRecordsToPersist": -1,
                                                                                   "locationsOrderDirection": "ASC",
                                                                                   "geofenceProximityRadius": 1000,
                                                                                   "geofenceInitialTriggerEntry": true,
                                                                                   "stopOnTerminate": false,
                                                                                   "startOnBoot": true,
                                                                                   "heartbeatInterval": -1,
                                                                                   "foregroundService": false,
                                                                                   "notificationTitle": "",
                                                                                   "notificationText": "Location Service activated",
                                                                                   "notificationColor": "",
                                                                                   "notificationIcon": "",
                                                                                   "forceReloadOnLocationChange": false,
                                                                                   "forceReloadOnMotionChange": false,
                                                                                   "forceReloadOnGeofence": false,
                                                                                   "forceReloadOnBoot": false,
                                                                                   "forceReloadOnHeartbeat": false,
                                                                                   "forceReloadOnSchedule": false,
                                                                                   "stopAfterElapsedMinutes": 0,
                                                                                   "schedule": [],
                                                                                   "configureUrl": "",
                                                                                   "configureInterval": -1,
                                                                                   "debug": false,
                                                                                   "logLevel": 5,
                                                                                   "logMaxDays": 3
                                                                                 }

## Expected Behavior
Every time the device connect to WiFi we expect to push all record location change stored

## Actual Behavior
Not updating to server when connection to WiFi

## Steps to Reproduce
1)Being in a WiFi zone open our app
2)We receive an update to server
3)Close our app 
4)It’s in background: we see the icon in the tray of our iPhone)
5)We go out to another location (5.5 km)
6)We enter a WiFi zone again
7)See the servers logs and no updates are visible
8)Open our app
9)We see posts to server with two or three location records

The location records show us that the plugin is recording the location changes, but It doesn’t update to server when it detects a Network change.

Our question is if you have tested this scenario and if you are aware de any bug?

## Context
Receive location updates to our server

**Comment by christocracy** [comment]
Is this not a duplicated of #334?

**Comment by beritsistemas** [comment]
Yes.. but we have tested the new version

**Comment by christocracy** [comment]
And is the issue not the same?

**Comment by beritsistemas** [comment]
Do you want me to post in the other issue?

**Comment by christocracy** [comment]
I would appreciate that, yes.
