### ISSUE TITLE
provider info in the DB

### ISSUE THREAD

**Issue by RobertoPirrone** [transistorsoft/cordova-background-geolocation-lt#341]
Hi, 
Would it be possibile to add the provider information (3G/wifi, SSID, BSSID,..) directly in the position that is persisted in the DB and  posted to server?
We do this stuff adding fields to the 'extras' structure, but this can be done only when the JS app is alive. If the app is killed, the position is sent to the server, but lacks the SSID info

## Your Environment
* Plugin version:cordova-background-geolocation-lt 2.6.0
* Platform: iOS and Android
* OS version: any
* Device manufacturer / model: any
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 6.1.2
  browser 4.1.0
  ios 4.3.1
* Plugin config

## Expected Behavior
SSID, BSSID are persisted in the DB and sent to the server, directly by the plugin

**Comment by christocracy** [comment]
Since you're a Premium member, you should be posting at the Premium repo.  This is the public **Free** repo.  `-lt` means "Lite"

**Comment by RobertoPirrone** [comment]
Sorry, You’re right.
Am I supposed to post he questions again on the other repo?

**Comment by christocracy** [comment]
You are not supposed to use the **Free** repo **at all**.  You definitely do **not** install the plugin from this repo.

**Comment by christocracy** [comment]
You need to uninstall the Free plugin and re-install the Premium version.  See the Premium README for setup instructions.
