### ISSUE TITLE
providing positions even in steady state

### ISSUE THREAD

**Issue by RobertoPirrone** [transistorsoft/cordova-background-geolocation-lt#342]
Hi, 
our app is intended to live indefinitely, and to report our server the positions, with a low impact on battery and user experience.
We would like to have a sort of keepalive, sending locations to the server, even when the phone is not moving. Some low frequency event, like background fetch on iOS or heartbeat on Android could be used to trigger a getCurrentPosition.
We already implemented this behaviour in the javascript app, but it would be nice if we can delegate the plugin, because the javascript app can be killed by the system.

## Your Environment
* Plugin version:cordova-background-geolocation-lt 2.6.0
* Platform: iOS and Android
* OS version: any
* Device manufacturer / model: any
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 6.1.2
  browser 4.1.0
  ios 4.3.1
* Plugin config

## Expected Behavior
positions are sent to the server, even in absence of motion

Thank you

**Comment by christocracy** [comment]
>with a low impact on battery and user experience.

>We would like to have a sort of keepalive, sending locations to the server, even when the phone is not moving

These two statements contradict each other.  Querying the location constantly when device is idle necessarily increases battery consumption.  Why must you do this?  The plugin is very good at determining when the device is moving.

**Comment by RobertoPirrone** [comment]
Well, in our experience the added consumption given by a background fetch interrupt is negligible. One callback in 30/90 minutes is peanuts.

We are aware of (and greatly appreciate) the efficiency of the plugin.  
But in our use case (members of a family that track each others) the knowledge that a phone is still alive, and is in a given position is really important. 
Think, for instance, about kids attending their lessons, and parents that are aware of this.
In this kind of usage, a position every ten or thirty minutes is enough, but, as a parent, I feel more relaxed if a receive a periodic update.

**Comment by christocracy** [comment]
If you want to receive events from Android when your MainActivity is destroyed, I created a separate plugin [`cordova-background-geolocation-broadcast-receiver`](https://github.com/transistorsoft/cordova-background-geolocation-broadcast-receiver) where you can listen to broadcasted events from the plugin in the native Android context.

It's not that difficult to interact with the plugin in native Android code to execute a `getCurrentPosition` when the `heartbeat` event is received.

**Comment by RobertoPirrone** [comment]
We were not aware of it, and can be useful, even though Android only.

But we miss the documentation for the Java API interface. I suppose that we could have very similar concepts and function names, but we did not find the correct document.

**Comment by christocracy** [comment]
iOS doesn't require this "Headless" type of mechanism.  

Yes, the docs are scant for this mechanism currently, but it's very easy.

**Comment by christocracy** [comment]
Try installing that plugin and see if you can get it logging.  As far as I know, nobody's actually tried it.

Basically, to use the native Android API, you get a reference to it like this:
```java
BackgroundGeolocation adapter = BackgroundGeolocation.getInstance(context, intent);
```
You can pretty much call any of the Javascript methods upon it.  The cordova plugin [CDVBackgroundGeolocation.java](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/CDVBackgroundGeolocation.java) can be used as a menu of available methods and implementations, [getCurrentPosition](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/CDVBackgroundGeolocation.java#L431), for example (location permission checking is unnecessary in this context).

The `getAdapter()` method in `CDVBackgroundGeolocation.java` is just a helper for `BackgroundGeolocation.getInstance(context, intent)`.

Each method to the Java API generally accepts a `TSCallback` instance with both a `success` and `error` callback.

**Comment by christocracy** [comment]
An example of performing a simple `getCurrentPosition` would look something like this:

```java
onHeartbeat(Context context, Intent intent) {
  // Get reference to API
  BackgroundGeolocation adapter = BackgroundGeolocation.getInstance(context, intent);

  // Create TSCallback instance
  TSCallback callback = new TSCallback() {
    public void success(Object location) {
      TSLog.logger.debug("*** getCurrentPosition success");
    }
    public void error(Object error) {
      TSLog.logger.debug("*** getCurrentPosition failure");
    }
  };

  try {
    // Create options instance
    JSONObject options = new JSONObject();
    options.put("persist", true);
    options.put("samples", 3);
    JSONObject extras = new JSONObject();
    extras.put("user_id", 1234);
    options.put("extras", extras);

    // Run it.
    adapter.getCurrentPosition(callback, options);
  } catch (JSONException e) {
    TSLog.logger.error("Something bad happened: " + e.getMessage();
  }    
}
```

**Comment by RobertoPirrone** [comment]
We get this error:

platforms/android/src/com/transistorsoft/cordova/bggeo/EventReceiver.java:103: error: incompatible types: TSCallback cannot be converted to JSONObject
        adapter.getCurrentPosition(callback, options);
                                   ^

**Comment by christocracy** [comment]
Right, now look closely at the Cordova plugin implementation of getCurrentPosition to see where the problem is.

https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/CDVBackgroundGeolocation.java#L431
