### ISSUE TITLE
Multiple geofence trigger and app suspended state issue when tested with GPX.

### ISSUE THREAD

**Issue by patadv** [transistorsoft/cordova-background-geolocation-lt#344]
## Your Environment
* Plugin version: 2.7.1 
* Platform: iOS 
* OS version: 10.2.1
* Device manufacturer / model: iphone 5s
* Cordova version (`cordova -v`):6.5.0
* Cordova platform version (`cordova platform ls`):6.5.0
* Plugin config 
cordova-background-geolocation-lt 2.7.1 "BackgroundGeolocation"
cordova-plugin-background-fetch 4.0.2 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-dbcopy 2.0.0 "sqlDB"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

## Expected Behavior
We have geo-fence that are fairly close to each other. when the user walks through these fences, the app could go suspended, but it should still trigger because i have enabled preventSuspend to true. 

## Actual Behavior
The first fence works well, even the second works well. Now as soon as the app goes to suspened mode it will stop triggering geofences. heartbeat event start to trigger.
Further details you can see in this video. Please note the way i have emulated this. I have used a GPX file to mimic motion. 
https://youtu.be/7TlKY5uw_vo

## Steps to Reproduce
https://youtu.be/7TlKY5uw_vo
## Context
This is an audio based tour guide. 
https://youtu.be/7TlKY5uw_vo

Setting 

> BackgroundGeolocation
 ```
this.bgGeo.configure({
                desiredAccuracy: 0,
                stationaryRadius: 1,
                distanceFilter:10,
                geofenceInitialTriggerEntry:true,
                activityRecognitionInterval: 10000,
                stopTimeout: 5,
                preventSuspend: true,
                debug: true,  
                stopOnTerminate: true,
                heartbeatInterval:30
                
                }, (state) => {
                    let fences = [];
                    for(let spot of this.spots) {
                      if(!spot.fields.sightGeofence) continue;
                        fences.push({
                            notifyOnEntry:true,
                            radius: spot.fields.sightGeofence.features[0].properties['marker-radius'],
                            identifier:spot.fields.sightId,
                            latitude:  spot.fields.sightGeofence.features[0].geometry.coordinates[1],
                            longitude: spot.fields.sightGeofence.features[0].geometry.coordinates[0]
                        })
                    }
                    this.geoFenceObserver = observer;
                    this.setGeoFence(fences);
                }); 

```

geofence event
```
this.bgGeo.on('geofence', (e) => {
           this.checkIfNextSite(e);
           console.log(e);
        });
```

Thanks

**Comment by christocracy** [comment]
I haven't look at your logs/videos but geofences are handled completely at the os level.

It doesn't matter if the app is suspended in background or even if app is terminated or device rebooted.  When the os detects a geofence transition, iOS will boot your app in the background to service that event.

**Comment by christocracy** [comment]
- minimum `stationaryRadius` is `25`.  Setting `1` is useless
- What are your geofence radius?  Best result are with minimum `150`
- Configure plugin with `logLevel: 5` for verbose plugin logging and send logs to me:
![](https://www.dropbox.com/s/vbp78xhxqnqz9s4/Screenshot%202017-05-18%2015.31.21.png?dl=1)

**Comment by patadv** [comment]
We are creating an application that tracks people when they walk and triggers the playing of audio files when are at a specific location. It's a self-guided audio tour app.

The average distance between two locations is 20-25 meters. We are putting a geofence around the locations so that when people enter the fence we know which location they are in and we trigger the related audio file to that location. 

We have this working in our web application. We constantly monitor the location and check if a fence was crossed or not. This clearly isn't the most battery efficient method but it works very well.

With the Cordova plugin, I'm able to get a fence triggered on the emulator, but in the field is much more difficult.

On the emulator, we set 4 fences (avg distance between them is 20 meters), and the fence will only work if I move out a very far distance and then move back into the fence. If I move directly from one fence to another which is around 20 meters apart it does not trigger. Naturally, this short distance isn't working in the field either. 

I know as per the documentation we you suggest it needs to move at least 200 meters to get the fence to trigger, but that does not help us when we need geolocation updates to happen in lesser distances (15-20 meters). Is there some way in which we can force the geolocation updates to run more frequently, even if that isn't ideal for battery life? I'm ok burning extra battery to have a functional app. 

Attached is a recent log of our use of the plugin. Setting all the configurations to be as aggressive as possible (to my knowledge), it still appears the geolocation event listeners only update about once per minute if I'm reading the log correctly. We would like these to run more frequently at certain times, as the triggers are not going off in a timely manner at the moment.

The current test environment is iOS.  Any help you can provide is greatly appreciated! 

Most recent settings:
{
    activityRecognitionInterval = 1000;
    activityType = Other;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 1;
    desiredAccuracy = 0;
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 1;
    enabled = 0;
    extras =    {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =    {
    };
    heartbeatInterval = 30;
    httpRootProperty = location;
    isHeartbeatEnabled = 0;
    isMoving = 0;
    locationAuthorizationAlert =    {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 7;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 90;
    odometer = "4398.687538829427";
    params =    {
    };
    pausesLocationUpdatesAutomatically = 1;
    preventSuspend = 1;
    schedule =    (
    );
    schedulerEnabled = 0;
    startOnBoot = 0;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnTerminate = 1;
    stopTimeout = 5;
    trackingMode = 0;
    url = "";
    useSignificantChangesOnly = 0;
}
[background-geolocation.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1028060/background-geolocation.zip)

**Comment by christocracy** [comment]
Also, iOS geofences require moving ~200 meters outside before it will trigger the `exit` transition.

With my [Background Geolocation Console]() app that I use for testing, you can see a picture of where transitions occur relative to the geofence:
red = exit
green = enter
![](https://www.dropbox.com/s/topnno4tbt5a32j/Screenshot%202017-06-01%2010.04.33.png?dl=1)

**Comment by christocracy** [comment]
Closed for lack of feedback
