### ISSUE TITLE
Newbie needs help with heartbeat callback

### ISSUE THREAD

**Issue by indianaahmed** [transistorsoft/cordova-background-geolocation-lt#348]
Trying to add a callback method for heartbeat event so that the app that I am trying to support is able to report gps coordinates to a server. Currently not seeing the log message from the call back at all.

Here is the congifuration that I am using:
// Geolocation Common Options
                                                                   desiredAccuracy: 0,
                                                                   distanceFilter: 50,

                                                                   // Geolocation iOS Options
                                                                   stationaryRadius: 25,

                                                                   // Geolocation Android Options
                                                                   //locationUpdateInterval: 1000,

                                                                   // Application Common Options
                                                                   heartbeatInterval: 1, // <-- every minute

                                                                   // Application iOS Options
                                                                   preventSuspend: true,

                                                                   // Application Android Options
                                                                   foregroundService: true,

                                                                   // HTTP & Persistence Options
                                                                   autosync: true,

                                                                   debug: true
                                                                 },

Here is the plugin information in my Windows 10 environment:

com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"
cordova-background-geolocation-lt 2.7.1 "BackgroundGeolocation"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-fastrde-checkgps 1.0.0 "checkGPS"
cordova-plugin-fcm 2.1.1 "FCMPlugin"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-keyboard 1.1.4 "Keyboard"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"

Here is the method that is used to add the heartbeat method:

                      CordovaBgGeoObj.onHeartbeat = function ()
                      {
                        console.info( '[js] onHeartBeat: ' );

                        var deferred = $q.defer();
                        $cordovaBackgroundGeolocation.on( 'heartbeat',
                                                          function ( params )
                                                          {
                                                            console.info( '[js] Heartbeat event: ',
                                                                          JSON.stringify( params ) );
                                                            deferred.resolve( provider );
                                                          } );
                        return deferred.promise;
                      }

Expect to see the [js] Heartbeat event:  every minute but not seeing it

Please help.

**Comment by christocracy** [comment]
Please do **not** ignore the issue template.



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by indianaahmed** [comment]
Your Environment

    Plugin version: com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"

    Platform: iOS or Android
Android 5.0.1
    OS version:
Windows 10
    Device manufacturer / model:
Samsung-SGH-I337
    Cordova version (cordova -v):
7.0.1
    Cordova platform version (cordova platform ls):

Installed platforms:
  android 6.1.2
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0
    Plugin config

Expected Behavior

Expect to see log message "[js] Heartbeat event:"

Actual Behavior

No such log message seen

Steps to Reproduce

Configure and start the associated app.

Context
Debug logs

**Comment by christocracy** [comment]
Have you purchased a license?
Are you watching the ADB logs?

```
$ adb logcat
```

**Comment by christocracy** [comment]
Are you joining a project where some developers have implemented this?

**Comment by indianaahmed** [comment]
Hi Chris,
Yes but the "original" developers are no longer available/accessible. Core problem I'm trying to solve is that it appears the goe location capability seems to have been centered around time based for both iOS and Android whereas instead it amy be better off being distance based to keep iOS "happy". 
I am new to ionic/cordova  so extra challenges there. Thought about using the heartbeat event to add some kind of regular check on position - I understand that there are other more appropriate event handlers and will get to them if I can get past this simple guaranteed callback. Trying to understand and work my way through.

Regards,Shakeel

**Comment by christocracy** [comment]
Well, you're using version a very old version of the plugin:
```
com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"
```
The latest version is `2.7.1`.  The method of configuring the plugin has changed significantly.  See the [README for new setup steps](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)

Are you watching the plugin's logs in XCode?  Also see [getLog](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getlogcallbackfn) and [logLevel](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-loglevel-5)

```
🔵-[TSLocationManager onHeartbeat] Heartbeat
.
.
.
🔵-[TSLocationManager onHeartbeat] Heartbeat
.
.
.
🔵-[TSLocationManager onHeartbeat] Heartbeat

```
