### ISSUE TITLE
addGeofences add lat and lng from json API

### ISSUE THREAD

**Issue by gogs85** [transistorsoft/cordova-background-geolocation-lt#353]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
For using addGeofences  we need to get lat and lng from json api, but if I import
Http, and in constructor app not working on Android. Just get white background.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Obviously there's an error someone in your app code.  Until you discover where that error is being produced and provide some logs, I cannot even begin to speculate.
