### ISSUE TITLE
iOS : JS callback called multiple times (also for same locations)

### ISSUE THREAD

**Issue by uzumakinaruto123** [transistorsoft/cordova-background-geolocation-lt#355]
## Your Environment
* Plugin version: 2.6.0
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: iPhone 6s Plus simulator | iPhone 5s
* Cordova version (`cordova -v`): 6.3.1
* Cordova platform version (`cordova platform ls`): ios 4.1.1
* Plugin config

```
let config = {
          desiredAccuracy: 0,
          distanceFilter: 0,
          stationaryRadius: 5,
          locationUpdateInterval:10000,
          activityType: 'AutomotiveNavigation',
          activityRecognitionInterval: 10000,
          stopTimeout: 10,
          maxRecordsToPersist: 0,
          debug: true,
          stopOnTerminate: false,
          startOnBoot: true,
          locationAuthorizationAlert: {
            titleWhenNotEnabled: "Location Services not enabled",
            titleWhenOff: "Location Services are OFF",
            instructions: "You must enable 'Always' in Location Services, to always get notified.",
            cancelButton: "Cancel",
            settingsButton: "Settings"
          }
        };
```

## Expected Behavior

Get the JS location callback once per location detection.

## Actual Behavior

Whenever plugin starts monitoring (start method), the JS location callback is run multiple times with multiple locations. After that on every custom location I set in simulator, JS callback is run twice for every location.  I have set `maxRecordsToPersist: 0`

## Steps to Reproduce

1. Start Ionic 2 app and install the plugin
2. Configure plugin as per the config mentioned above.
3. Build app.
4. Run on Simulator or device.

## Context

I want to get user location once every 10s irrespective of users movement. I am getting user location but multiple times. Anything wrong with the config?

Thank you.

**Comment by christocracy** [comment]
Are you sure these  "multiple locations" are not samples?  See the docs for [location event](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#location)

ℹ️ When performing a motionchange or getCurrentPosition, the plugin requests multiple location samples in order to record the most accurate location possible. These samples are not persisted to the database but they will be provided to your location listener, for your convenience, since it can take some seconds for the best possible location to arrive. For example, you might use these samples to progressively update the user's position on a map. You can detect these samples in your callbackFn via location.sample === true. If you're manually POSTing location to your server, you should ignore these locations.

**Comment by uzumakinaruto123** [comment]
Thank you, I was not aware of sample locations in callback. So now I did this in callback : 

```
if(location.sample === true){
      console.log('GOT sample location: ', location.coords.latitude+','+location.coords.longitude);
    }else{
      console.log('GOT location: ', location.coords.latitude+','+location.coords.longitude);
    }
```
<br>

**Now, when I start monitoring I do get few sample locations but actual once are also multiple**

![location1](https://cloud.githubusercontent.com/assets/15323421/26503914/3856b71a-4260-11e7-98cc-a95704af503d.png)


<br>

**Later when I debug in Freeway drive mode** 

(Notice how I get callback multiple times for same locations)


![location2](https://cloud.githubusercontent.com/assets/15323421/26503962/60ee096c-4260-11e7-8d0b-e6de8f81293c.png)




<br>

I am trying to test this out of the box as in in your sample application provided at [https://github.com/transistorsoft/cordova-background-geolocation-SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp).

But its throwing `Error: cordovaProject.projectConfig.getFileResources is not a function` when I do `ionic run ios --emulator`

Also web application is not loading : 

![location3](https://cloud.githubusercontent.com/assets/15323421/26504347/e1318206-4261-11e7-9375-168afd8e7b64.png)


Thank you!

**Comment by christocracy** [comment]
Are you sure you're not listening to the `location` event *twice*?

**Comment by christocracy** [comment]
Are you running the SampleApp from master (ie: the Ionic 2 version)?

**Comment by uzumakinaruto123** [comment]
Yes, I am listening to event once. This is pretty much all I am doing : 

```
initGeo() {

    this.platform.ready().then(() => {

        // IMPORTANT: BackgroundGeolocation must be called within app.ts and or before Geolocation. Otherwise the platform will not ask you for background tracking permission.

        // BackgroundGeolocation is highly configurable. See platform specific configuration options
        this.bgGeo = (<any>window).BackgroundGeolocation;

        this.bgGeo.on('location', this.onLocation.bind(this));

        let config = {
          desiredAccuracy: 0,
          distanceFilter: 0,
          stationaryRadius: 5,
          locationUpdateInterval:10000,
          activityType: 'AutomotiveNavigation',
          activityRecognitionInterval: 10000,
          stopTimeout: 10,
          maxRecordsToPersist: 0,
          debug: true,
          stopOnTerminate: false,
          startOnBoot: true,
          locationAuthorizationAlert: {
            titleWhenNotEnabled: "Location Services not enabled",
            titleWhenOff: "Location Services are OFF",
            instructions: "You must enable 'Always' in Location Services, to always get notified.",
            cancelButton: "Cancel",
            settingsButton: "Settings"
          }
        };

        this.bgGeo.configure(config, (state) => {
          // This callback is executed when the plugin is ready to use.
          console.log('BackgroundGeolocation ready: ', state);


          if (!state.enabled) {
            this.bgGeo.start();
          }
        });

    });
  }


onLocation(location, taskId) {
    
    if(location.sample === true){
      console.log('GOT sample location: ', location.coords.latitude+','+location.coords.longitude);
    }else{
      console.log('GOT location: ', location.coords.latitude+','+location.coords.longitude);
    }
    this.bgGeo.finish(taskId);
  }
```


Yes, I did this `git clone https://github.com/transistorsoft/cordova-background-geolocation-SampleApp.git` so it pulled master I guess.

**Comment by christocracy** [comment]
Increase your distanceFilter.  You've set it to 0

**Comment by christocracy** [comment]
What version Ionic are you using?

**Comment by uzumakinaruto123** [comment]
I increased it to 5, now I don't get multiple locations. Thank you. This can be closed since now I know the cause. But I configured it to 0 because I wanted to get immediate location every 10s irrespective of distance traveled and irrespective of motion change.  Is there no way to get location every X amount of time? 
Also can you suggest if the above config will be energy efficient?  Thank you can be closed 👍

**Comment by uzumakinaruto123** [comment]
I am using ionic 2.2.0.

**Comment by christocracy** [comment]
iOS is strictly distanceBased.  

locationUpdateInterval is Android only.  The docs specify this.

**Comment by uzumakinaruto123** [comment]
OK. Nevermind :)  Thank you for your quick responses.

**Comment by christocracy** [comment]
The more locations you record, the more energy you will consume.

Note that http requests consume far more energy/s than GPS.

If you're hoping to upload to your server every location *as they're recorded*, with a distanceFilter: 5, you will consume **a lot** of power.

**Comment by uzumakinaruto123** [comment]
I will try increasing the distance. We will mostly try avoiding http posts, currently we are experimenting with the plugin. Posting locations to Drupal cms backend.

**Comment by christocracy** [comment]
Btw, the error you received `Error: cordovaProject.projectConfig.getFileResources is not a function`

This *may* be caused by a [bug in Cordova](https://stackoverflow.com/questions/43195668/cordova-error-using-cordova-android-6-2-0-getfileresources-is-not-a-function)

I would appreciate if you could try upgrading Cordova and let me know if it solves that issue.

**Comment by uzumakinaruto123** [comment]
@christocracy I upgraded Cordova, it installed `cordova@7.0.0`. App built and run successfully. 👍
