### ISSUE TITLE
Database questions

### ISSUE THREAD

**Issue by skrpc** [transistorsoft/cordova-background-geolocation-lt#356]
General suggestion: All versions

My use case is to store tracks locally on the device and retrieve and display on a map on occasions whilst offline.
The track data (points) are stored in the Sqlite DB but there appears to be is no optimised way to identify individual instances of start/stop sequences (i.e. individual tracks).
My idea is that when starting a track (start()) if a key could be specified that is recorded in the DB against each point then in the getLocations, destroyLocations and getCount methods by specifying the key the subset of points for a single track can be retrieved (i.e. SELECT * from table WHERE key = 'key'").
As it stands it appears as though the extras property could be used but then all points for all tracks will be retrieved by getLocations() and then would have to be manually filtered in the app which I suspect would not be as optimised as could be achieved in Sqlite not to mention the memory required for all the points.
Further the prune function at start up (i.e. the maxDaysToPersist parameter) will clear them down anyway whereas prune could ignore tracks with keys (or set a boolean to indicate whether the key is to be pruned or not).

Excellent plugin though.

**Comment by christocracy** [comment]
Not going to happen.  The plugin stores its data as JSON in a single column.

It's your responsibility to persist locations with your own persistence mechanism.

The plugin's db is merely a short-term cache for its own purposes.
