### ISSUE TITLE
General persistence questions

### ISSUE THREAD

**Issue by skrpc** [transistorsoft/cordova-background-geolocation-lt#357]
All devices and OS's

1. Is it possible to disable database pruning when the app is started by setting maxDaysToPersist to for example -1 ?

2. If using #url are locations removed from the SQLite database as soon as the location is synced with the target #url or do they persist locally for maxDaysToPersist ?

3. Can locations already synchronised with #url subsequently be retrieved using getLocations() ?

4. When calling getLocations() or when the #location event callback is called does the Location Data Schema have a flag to indicate if the location has been synchronised with the target at #url ?

5. If calling insertLocation() with a location sent by the plugin and therefore already in the plugins SQLite database (i.e. same uuid) is the location in the database updated, can this be used to update for example the extras parameter with my own flags (e.g. to indicate now persisted in my apps local storage area) without adding a new location to the plugins SQLite database ?

**Comment by christocracy** [comment]
>Is it possible to disable database pruning when the app is started by setting maxDaysToPersist to for example -1 ?

I've never tried it.

>If using #url are locations removed from the SQLite database as soon as the location is synced with the target #url or do they persist locally for maxDaysToPersist ?

The plugin **strongly** desires and empty database.  When your server returns a `200`-type response, the plugin deletes that record.

>Can locations already synchronised with #url subsequently be retrieved using getLocations() ?

No.

>When calling getLocations() or when the #location event callback is called does the Location Data Schema have a flag to indicate if the location has been synchronised with the target at #url ?

No.  If the location has been sent to your server and your server returned `200`-type response, that record is gone.  Ask  your server for those records.

>If calling insertLocation() with a location sent by the plugin and therefore already in the plugins SQLite database (i.e. same uuid) is the location in the database updated, 

No.  The plugin always tags each inserted location with a new `uuid`.

>can this be used to update for example the extras parameter with my own flags (e.g. to indicate now persisted in my apps local storage area) without adding a new location to the plugins SQLite database ?

No.

The plugin's database is primarily designed for its own purposes.  It's not intended to be your application's long-term storage.  You should either implement your own local persistence layer or simply query your server.
