### ISSUE TITLE
location event callback

### ISSUE THREAD

**Issue by skrpc** [transistorsoft/cordova-background-geolocation-lt#358]
All OS's but only tested so far on Android.

Well I am obviously missing something, here is my scenario.

Using the #location event callback the plugin does seem to call the callback function whilst the app is in the foreground.
I then kill my app as this is the whole point of needing the plugin, my use of the plugin is to continue recording points in the background even if my app is no longer running.
I then start up my app again later and the location event callback does not seem to be called with all the points that were recorded by the plugin whilst in the background.
I cannot use http as this is Search and Rescue so users of the app will be in the back country away from cell service so cannot connect with a http server and may also want to look at their track whilst offline so all points need to be recorded and stored locally anyway; I have no issue with this and my app already has a mechanism for this.
Therefore the only option now seems to be to call getLocations() and get all the points and this is assuming that on restart of my app the plugin does not prune points not yet sent to the #location event callback.
I cannot flag the points I have already persisted in my app in the plugins database plus I cannot just get the points from the plugins database that have not already been submitted to the location event callback.
It seems to me in my apps local persistence store I will have no option but to store the uuid for each point therefore an additional 36 characters per point; assuming a worst case scenario of a team in the field for at least eight hours moving most of that time so with one point every 10 seconds 3,000 points does not seem to be an inconceivable amount resulting in an additional 100k per track just to store the uuids which I have no real need for as I just need an array of points sorted by the time they were recorded.
My app also provides the option to keep the tracks locally for historical purposes in case the user wants to review/retrace their track at a later stage.
To me this up to 100k seems like a waste of memory as there is already a database with all this information and therefore I am assuming there has to be some easier way of synchronising my apps local persistence store with that of the plugin as seems to be the case when using the http #url.

Thanks,
Scottt

**Comment by christocracy** [comment]
If you're concerned about space, you're free to [provide your own JSON schema](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/http.md#locationtemplate--geofencetemplate)

**Comment by christocracy** [comment]
Do you have a question?

**Comment by skrpc** [comment]
But other than the uuid there does not seem to be any other unique parameter that can be specified in the schema, all I need is a flag that I can set to indicate if a point in the plugins database has also been persisted in my apps local store database.

I am also concerned there appears to be no way to control the pruning, I had planned on calling destroyLocations() when the user starts a new track and then if the app ends when it is restarted I would just call getLocations() and just re-insert as a whole into my apps local store but based on a question asked earlier you are indicating that the plugin is very keen to remove points from the database so how do I know that a call to getLocations on a subsequent app start will contain all the points; as I understand it I cannot.

The issue to me seems to be there is no way to synchronise with an apps own local store in the same way and with the same level of control that exist if using http and #url.  I cannot use http as for most cases usage of the app will be offline.

**Comment by christocracy** [comment]
What is your question?

**Comment by skrpc** [comment]
What is the way to synchronise an apps own local store with that of the plugins without using uuids whilst guaranteeing that the plugin will not have pruned the database whilst my app is not running.

**Comment by christocracy** [comment]
If you want to fetch all the locations the plugin current holds, use `#getLocations` then `#destroyLocations`.

If you're not providing the plugin with an `#url`, you can simply execute `#sync`.  This will return old the locations the plugin currently holds and automatically empty the database.

```javascript
bgGeo.sync(function(records) {
  // move locations to your own persistence mechanism.  The plugin's database is now empty.
});
```

If you want prevent the plugin from pruning records, you can simply provide a very large `maxDaysToPersist`.
