### ISSUE TITLE
Works well on IOS simulator, but does not work for real IOS device for me 

### ISSUE THREAD

**Issue by owen-pengtao** [transistorsoft/cordova-background-geolocation-lt#36]
```javascript
function onDeviceReady() {
      var bgGeo = window.BackgroundGeolocation;
      bgGeo.configure(function(location, taskId) {
        var data = {
          saved: false,
          currentData: {
            "time" : $scope.time,
            "position": {
              "lat": location.coords.latitude,
              "lng": location.coords.longitude
            }
          }
        };
        setTimeout(function() {
          $scope._formatLocationData(data);
          bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
        }, 1000);
      }, function(error) {
        console.log('BackgroundGeoLocation error');
      }, {
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        notificationTitle: 'Background tracking', // <-- android only, customize the title of the notification
        notificationText: 'ENABLED', // <-- android only, customize the text of the notification
        activityType: 'AutomotiveNavigation',
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        stopOnTerminate: false
      });

      bgGeo.start();
    }

    var frequencyMin = 1;
    $scope.intervalSend = function () {
      var d = new Date(),
        h = new Date(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), (d.getMinutes() - (d.getMinutes() % frequencyMin)) + frequencyMin, 0, 0),
        e = h - d;
      $timeout($scope.intervalSend, e);
      if (d.getSeconds() === 0) {
        $scope.time = Math.floor(d.getTime() / 1000);
        $scope.syncMyLocation($scope.time, true);
      }
    };
    $scope.intervalSend();
```

My project works for IOS simulator, but does not work for real IOS device.
It works on device if I keep app in front, but it does not work for background.
Is there any suggestion I can get from you? thanks.

Location: Always
Motion & Fitness: Yes
Background App Refresh: Yes
Cellular Data: Yes

**Comment by christocracy** [comment]
Your config is somewhat invalid.  It looks like you're using config from my old, deprecated repo.

These are no longer valid:
```
notificationTitle: 'Background tracking', // <-- android only, customize the title of the notification
notificationText: 'ENABLED', // <-- android only, customize the text of the notification
        activityType: 'AutomotiveNavigation',
```

However, while that will not be causing the problem, you should have a look at this repo's README and modify your config accordingly.

Also, why are you using a `setTimeout`?  That was used in the example code merely to *simulate* an asychronous XHR request -- not to actually wrap your code within it.

```
setTimeout(function() {  // <-- get rid of this
          $scope._formatLocationData(data);
          bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
        }, 1000);
```

Finally, are you moving 2-3 blocks to trigger out of stationary-mode?

**Comment by owen-pengtao** [comment]
I removed those invalid parameters and setTimeout,  those are copied from somewhere.
The issue is still same, works well on simulator but not on IOS device.

I did not moving 2-3 blocks, just work from one building to anther, but if I always stay in same place, can I track the device, let device report where it is in every 10 minutes?

will test it on highway when I drive to home.

**Comment by christocracy** [comment]
Native location APIs are distance-based -- not time-based.  The plugin will not report "every 10 minutes".

For iOS, you could use my free [background-fetch](https://github.com/christocracy/cordova-plugin-background-fetch) plugin.  This plugin will awaken an iOS app ~every 15min, providing exactly 30s of background running-time.  Within the callback, you could execute `bgGeo#getCurrentPosition`.

Android is much better at detecting movement, typically taking just a few meters of movement to trigger tracking.
