### ISSUE TITLE
IOS tracking issues skipping/not working altogether

### ISSUE THREAD

**Issue by TeamAntris** [transistorsoft/cordova-background-geolocation-lt#360]
We're having issues for many weeks now with tracking skipping or just not working altogether on most IPhones. We have 3 IPhones that are acceptably working good (but still not perfect), 5 that are only sometimes working (large skips), and 1 that's not working at all (known issue in other apps like google maps). We have 7 Androids that're working perfectly with the exact same app version.

## Your Environment
* Plugin version: 2.7.1
* Platform: iOS
* OS version: 1 on 9.2.1, 6 on 10.3.2
* Device manufacturer / model: IPhone: 3 on 5, 4 on 5S, and 2 on 6
* Cordova version (`cordova -v`): 6.3.0
* Cordova platform version (`cordova platform ls`): 4.2.0
* Plugin config
	        desiredAccuracy: 0,
	        distanceFilter:30,
	        stationaryRadius:30,
	        notificationTitle: '####', 
	        notificationText: '####',
	        activityType: 'OtherNavigation',
	        debug: false,
	        stopOnTerminate: false,
	        preventSuspend:true,
	        locationAuthorizationRequest: "Always",
	        batchSync:true,
	        url: newServicesAPI+"v1/user/"+memberid+"/save_track",
	        locationAuthorizationAlert: {
			    titleWhenNotEnabled: "Location Services: 'While Using'",
			    titleWhenOff: "Location Services: 'Never'",
			    instructions: "To use ### you must select 'Always' in the Location Services setting.",
			    cancelButton: "Cancel",
			    settingsButton: "Settings"
			},
		foregroundService:true,

## Expected Behavior
For the tracking to always work within acceptable ranges of motion 

## Actual Behavior
The tracking sometimes has large skips while driving, and sometimes it mimics the tracking stopping altogether when the app goes into the background.

## Context
We need accurate track marks for calculating mileage and timesheets with our own geofencing.

## Debug logs
These are production only devices so we cannot turn debug on in production. We have not been able to recreate the issues with testing our own phones.

**Let us know what the next steps are to try and solve this. If that means getting debug logs for one of the users out in the field we can try that.**

**Comment by christocracy** [comment]
Without logs, there's nothing to speculate about.  I test field-test daily with iPhone 5 & 6s.  I have no issues.

**Comment by christocracy** [comment]
Btw, you're posting this issue on the **Free** version.  Customers do not use this repo, they use the [private repo](https://github.com/transistorsoft/cordova-background-geolocation)

**Comment by christocracy** [comment]
Closed for lack of feedback.
