### ISSUE TITLE
Synchronization question

### ISSUE THREAD

**Issue by skrpc** [transistorsoft/cordova-background-geolocation-lt#363]
General enquiry all OS's

Are calls to the #location event handler and the BackgroundGeolocation.sync() method synchronous.
For example if my #location handler looked like the following can I be guaranteed that #location would not be called again whilst already processing a call to sync (note not using HTTP so sync() being called to get all records not yet persisted locally).

```
locationHandler = function(location) {
  BackgroundGeolocation.sync(function(records) {
    <persist records to local store>
  }
}
```

This is so that  I can catch up the apps local store if the app was terminated and the plugin recorded points in the background prior to the app being restarted.

**Comment by skrpc** [comment]
Sorry just realised I emant to ask it the following way
I guess I do not need to add sync to the #location but I am going to include it in the #configure callback (i.e. to get all points recorded whilst app terminated).  But if the state is such that the enabled flag is true and the plugin automatically calls start() I was wondering if #location can be called whilst processing sync() in the #configure success callback.

**Comment by christocracy** [comment]
The plugin performs actions asynchronously.

The plugin performs http requests in a background thread.

The location event will be fired regardless of anything.

**Comment by christocracy** [comment]
I should say more generally, the plugin performs *#sync* in a separate thread.

**Comment by skrpc** [comment]
I see there is no #off method, once an event handler such as #location has been added is there any way to remove it ?

Can #location be added in the #configure() or really at any time or does it have to be added when first initialising and prior to #configure() ?

**Comment by christocracy** [comment]
Add an event-listener at any time.

Only all event-listeners can be removed using #removeListeners.  It's
simply impossible to reference a particular native event callback method
living in a List through a JavaScript function(){} reference alone.
-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
You're free to create your own Proxy "Observable" mechanism to collect
listeners and fire events.

On Thu, Jun 1, 2017 at 12:20 AM Chris Scott <christocracy@gmail.com> wrote:

> Add an event-listener at any time.
>
> Only all event-listeners can be removed using #removeListeners.  It's
> simply impossible to reference a particular native event callback method
> living in a List through a JavaScript function(){} reference alone.
> --
> Snet form Gmail Mobile
>
-- 
Snet form Gmail Mobile
