### ISSUE TITLE
HTTP synchronization

### ISSUE THREAD

**Issue by skrpc** [transistorsoft/cordova-background-geolocation-lt#364]
General question all OS's

Thank you for your time answering my questions to date and I think I am nearly at the point where I fully understand the workings and can start to test my "real" use case to make sure the plugin behaves how I need it to which from my preliminary tests and your responses looks like it will.

Regarding HTTP I understand this is a background task based on #url, but what happens after a #stop and there are points that have not yet been submitted (e.g. #url server unavailable).  Do these just remain in the plugin database and my app would have to manually sync them when it is next started if my app has been terminated.

I realise I can check the database and manually call #sync() before issuing a call to #stop when my app is in the foreground but what happens if the plugin stops automatically as a result of stopAfterMaxMinutes expiring.

I am assuming if this timeout occurs the plugin will try a final sync before stopping but if the sync fails and the plugin is stopped again is it now my app that must manually sync or is there some magic whereby the plugin keeps trying until it can successful send all points and clear its database ?

If my app is in the foreground is there any way to know that stopAfterMaxMinutes has expired (eg. callback and flag setting) and that the plugin has now stopped.

**Comment by christocracy** [comment]
>what happens after a #stop and there are points that have not yet been submitted (e.g. #url server unavailable). Do these just remain in the plugin database and my app would have to manually sync them when it is next started if my app has been terminated.

Yes.  `#stop` means *stop*.  Like powering off your phone.  The plugin will do no work at all after `#stop` is called.  If there's locations in the db, it's up to you.  If you call `#start` the plugin will automatically attempt to flush those to your configured `#url`.

If you explicitly *ask* the plugin to `#sync` after `#stop`, the plugin perform that request and attempt to flush to your configured `#url`.

> but what happens if the plugin stops automatically as a result of stopAfterMaxMinutes expiring.

The config is named [`stopAfterElapsedMinutes`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-integer-stopafterelapsedminutes).  The plugin does **not** perform a `sync` here.  However, the plugin does attempt to `#sync` each [`heartbeatInterval`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-integer-heartbeatinterval-undefined).  If you configure `heartbeatInterval: 60`, the plugin is going to attempt to `#sync` every minute while the device is stationary.

>If my app is in the foreground is there any way to know that stopAfterMaxMinutes has expired (eg. callback and flag setting) and that the plugin has now stopped.

No.  There is no signal for this.
