### ISSUE TITLE
Notification Text won't upgrade while running?

### ISSUE THREAD

**Issue by mb34124** [transistorsoft/cordova-background-geolocation-lt#367]
Please let me know if I missed anything in your template, but I think I got it all.

## Your Environment
* Plugin version: 2.6.0
* Platform: Android
* OS version: Android 6.0.1
* Device manufacturer / model: Samsung Galaxy S5
* Cordova version (`cordova -v`): 4.0.0
* Cordova platform version (`cordova platform ls`): Android 4.4.1
* Plugin config
bgGeo.configure({
            // Geolocation config
            preventSuspend: true,
            desiredAccuracy: 0,
            distanceFilter: 10,
            //stationaryRadius: 25,
            fastestLocationUpdateInterval: 30000,
            stopTimeout: 5,
            // Application config
            debug: true,  // <-- Debug sounds & notifications.
            stopOnTerminate: false,
            startOnBoot: true,            
            autoSync: false,
            maxDaysToPersist: 3,
            foregroundService: true,
        }, bgGeoReady);

## Expected Behavior

Android Banner text should update even after plugin has started. (maybe this isn't supported?)

## Actual Behavior

Android Banner text did not update unless I stopped and restarted the plugin.

## Steps to Reproduce

1.  Configure Plugin with settings above.
2.  Call setConfig and set notificationTitle and notificationText (text shows what I want correctly)
3.  call start();
4.  Call setConfig and set notificationTitle and notificationText with different values from step 2  (old values remain).
5.  If I stop and restart the plugin with a third set of values they show correctly.  It appears the text will not update once the plugin has already started.  

## Context

Whenever users launch my app, I start the plugin if needed and want to show different messages in the notification text.  Like what time we first started tracking them or something like that.  It won't be updated frequently but I would like to occasionally update the text while the plugin is running.  

## Debug logs

I'm going to have to attach the logs in a bit.   My first logcat had so much stuff in it that it was overwhelming.  I'm going to kick off an emulator and gather the logs so it is cleaner.  I'll keep the same Android specs or update the issue.

**Comment by christocracy** [comment]
The service must be `#stop` / `#start`ed before new notification text will appear.

**Comment by mb34124** [comment]
Thanks!  I was about to send you that exact link.

**Comment by christocracy** [comment]
Ok, I've implemented this.  It's available now in the Paid version.  It won't appear here until I next push the latest stable release.

**Comment by mb34124** [comment]
Great!  Thank you!  We should be buying a license this week.
