### ISSUE TITLE
How i can get activity (walk, run,...) from the plugin for save it in location object ?

### ISSUE THREAD

**Issue by Raffaele-LIZE** [transistorsoft/cordova-background-geolocation-lt#369]
## Your Environment

* Plugin version: 2.2.5
* Platform: iOS & Android
* OS version: iOS 10.3.2 / Android 7.0
* Device manufacturer and model: iPhone 5S / Galaxy S6 edge
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): ios 4.4.0 / android 6.2.3
* Plugin configuration options: 
// Background Tracking
		let config = {

			// Both (Android & iOS)  
			desiredAccuracy            : 10,
			stationaryRadius           : 50, // Stationary radius in meters. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
			distanceFilter             : 30, // The minimum distance (measured in meters) a device must move horizontally before an update event is generated. @see Apple docs.
			debug                      : true, //  enable this hear sounds for background-geolocation life-cycle.
			stopOnTerminate            : false, // enable this to clear background location settings when the app terminates
			startOnBoot                : false, // Start background service on device boot. (default false)
			notificationTitle          : 'Background tracking',
			geofenceProximityRadius    : 1000,
			triggerActivities          : 'on_foot, walking, running, on_bicycle, in_vehicle, still',
			// maxLocations            : 10000 // Limit maximum number of locations stored into db (default: 10000)
			
			// Only for Android (Detect activity for Android)
			locationProvider           : this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
			interval                   : 10000, // Rate in milliseconds at which your app prefers to receive location updates. @see android docs
			fastestInterval            : 5000, // Fastest rate in milliseconds at which your app can handle location updates. @see android docs.
			activitiesInterval         : 300000, // Rate in milliseconds at which activity recognition occurs. Larger values will result in fewer activity detections while improving battery life.
			stopOnStillActivity        : true, // stop() is forced, when the STILL activity is detected (default is true)
			
			// Only for iOS (Detect activity for iOS)
			activityType               : 'AutomotiveNavigation',
			activityRecognitionInterval: 5000,
			stopTimeout                : 5,
			locationAuthorizationAlert: {
				titleWhenNotEnabled: "Yo, location-services not enabled",
				titleWhenOff       : "Yo, location-services OFF",
				instructions       : "You must enable 'Always' in location-services, buddy",
				cancelButton       : "Cancel",
				settingsButton     : "Settings"
			}
		};

## Context
When i try to detect the device activity, an alert show the coordinates and the activity but i want catch the activity type for link it in my location object.

like that:

var currentPosition  = {
				'latitude'           : position.latitude,
				'longitude'          : position.longitude,
				'altitude'           : null,
				'accuracy'           : position.accuracy,
				'altitude_accuracy'  : null,
				'heading'            : null,
				'speed'              : null,
				'timestamp'          : position.time,
				'activity'           : position.activity.type || null,
				'activity_confidence': position.activity.confidence || null
			}

If someone can help me ? Thanks a lot =)

**Comment by christocracy** [comment]
Why don't you simply inspect the `location` object in Web Inspector or view the [Location Data Schema](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema) in the Wiki?
![](https://www.dropbox.com/s/ftl7n5mrm9zmleh/Screenshot%202017-06-08%2011.05.33.png?dl=1)

**Comment by Raffaele-LIZE** [comment]
Thank christocracy for your rapidity ! =).

I inspected (with chrome://inspect) but the location return me only object with "coords" children.

I had to make a mistake somewhere ^^".

**Comment by christocracy** [comment]
Then that location did not come from the plugin.  You're probably using `cordova-plugin-geolocation` in addition to this plugin.

**Comment by christocracy** [comment]
And btw, these configs come from Mauron85's old fork.

```
// Only for Android (Detect activity for Android)
  	locationProvider           : this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
  	interval                   : 10000, // Rate in milliseconds at which your app prefers to receive location updates. @see android docs
  	fastestInterval            : 5000, // Fastest rate in milliseconds at which your app can handle location updates. @see android docs.
  	activitiesInterval         : 300000, // Rate in milliseconds at which activity recognition occurs. Larger values will result in fewer activity detections while improving battery life.
  	stopOnStillActivity        : true, // stop() is forced, when the STILL activity is detected (default is true)
```
Are you sure you're in the right place?  Show me your `$ cordova plugins`

**Comment by christocracy** [comment]
This plugin is completely different from Mauron85's old fork of my original open-source project.  They are separated by over 2-and-a-half years.  This plugin has been completely re-written.  They are not compatible in *any* way.

**Comment by Raffaele-LIZE** [comment]
Yes i am really sorry, it was my mistake. Thanks Christocracy
