### ISSUE TITLE
Delay permissions request

### ISSUE THREAD

**Issue by gilesa** [transistorsoft/cordova-background-geolocation-lt#37]
Currently, the plugin prompts for background location tracking permissions as soon as the app loads. Is there a way to delay this until a later point? It would make sense for it to prompt only when the configure method is called.

**Comment by christocracy** [comment]
I could, yes.

**Comment by christocracy** [comment]
Actually, it's already performing the request in the #configure method.

**Comment by gilesa** [comment]
Thank you for the quick response!

Though, I think we've had a mis-communication. If I remove all calls to window.BackgroundGeolocation (so configure is never run), I still get a permissions popup. So even if it's not performing any requests until configure is called, something is still making iOS request background location tracking permission as soon as the app loads.

**Comment by christocracy** [comment]
Is this occurring in the SampleApp?

https://github.com/transistorsoft/cordova-background-geolocation-SampleApp

On Wed, Nov 11, 2015 at 5:46 PM, Andrew Giles <notifications@github.com>
wrote:

> Thank you for the quick response!
>
> Though, I think we've had a mis-communication. If I remove all calls to
> window.BackgroundGeolocation (so configure is never run), I still get a
> permissions popup. So even if it's not performing any requests until
> configure is called, something is still making iOS request background
> location tracking permission as soon as the app loads.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/37#issuecomment-155933433>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by gilesa** [comment]
Very strange, if I comment out the configure method in the sample app, it doesn't prompt me for the permissions. No idea why it does it my app. I'll keep investigating, thanks.

**Comment by christocracy** [comment]
It will be due to one of your other plugins installed in your app.

$ cordova plugins

On Thu, Nov 12, 2015 at 12:06 PM, Andrew Giles <notifications@github.com>
wrote:

> Very strange, if I comment out the configure method in the sample app, it
> doesn't prompt me for the permissions. No idea why it does it my app. I'll
> keep investigating, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/37#issuecomment-156167767>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by gilesa** [comment]
Yup, you are correct! It was another plugin. Thanks again.
