### ISSUE TITLE
geofenceProximityRadius appears not change value.

### ISSUE THREAD

**Issue by jorgemejia** [transistorsoft/cordova-background-geolocation-lt#370]
I guess the geofenceProximityRadius "1000" is not changing on fly, I test all my geofences with the simulator on xcode, the geofences are near about of 50 meters or less. I don´t know if there is a min and max geofenceProximityRadius and geofence radious.

When I set the one of my geofences on xcode, it fires all the geofences on entry event. And the same for exit.

I know that because I set a far geofence for test.

## Your Environment
* Plugin version: 2.7.1
* Platform: iOS 
* OS version: 10.3.2
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):
* Plugin config
```
this.bgGeo.configure({
            // Geolocation config
            desiredAccuracy: 10,
            distanceFilter: 10,
            stationaryRadius: 1,
            locationAuthorizationRequest:"Always",
            // Activity Recognition config
            activityRecognitionInterval: 0,
            stopTimeout: 5,
            // Application config
            debug: true,  // <-- Debug sounds & notifications.
            stopOnTerminate: false,
            startOnBoot: true,
            preventSuspend:true,
            // HTTP / SQLite config
            url: "http://url/gps",
            method: "POST",
            autoSync: true,
            batchSync: true,
            maxDaysToPersist: 3,
            headers: {  // <-- Optional HTTP headers
                "X-FOO": "bar"
            },
            params: {   // <-- Optional HTTP params
                "auth_token": "maybe_your_server_authenticates_via_token_YES?"
            }
        }, function(state) {
            // This callback is executed when the plugin is ready to use.
            console.log("BackgroundGeolocation ready: ", state);
            if (!state.enabled) {
               self.bgGeo.start();
            }
        });

      let geofences = [
                {latitude: x, longitude: -x, identifier:"x1", radius:10 ,notifyOnEntry:true, notifyOnExit:true},
                {latitude: x, longitude: x, identifier:"x2", radius:10, notifyOnEntry:true, notifyOnExit:true},
                {latitude: x, longitude: x, identifier:"x3", radius:10, notifyOnEntry:true, notifyOnExit:true}
          ];

      this.bgGeo.setConfig({geofenceProximityRadius: 25});

      this.bgGeo.addGeofences(geofences);

```

## Expected Behavior
Notification fired when the device is in - out geofence

## Actual Behavior
The plugin fires the notification for all geofences

## Steps to Reproduce
I´m setting the geofences with this method 

```
let geofences = [
                {latitude: x, longitude: -x, identifier:"x1", radius:10 ,notifyOnEntry:true, notifyOnExit:true},
                {latitude: x, longitude: x, identifier:"x2", radius:10, notifyOnEntry:true, notifyOnExit:true},
                {latitude: x, longitude: x, identifier:"x3", radius:10, notifyOnEntry:true, notifyOnExit:true}
          ];

      this.bgGeo.setConfig({geofenceProximityRadius: 25});

      this.bgGeo.addGeofences(geofences);
```

**Comment by christocracy** [comment]
A car at highway speed travels about 27 m/s.  With a geofenceProximityRadius: 25, you would rocket through your geofences before they even had a chance to be activated.

This is why the plugin prevents you from shooting yourself in the foot, by enforcing a *minimum* of 1000 meters.

**Comment by christocracy** [comment]
And anyway, the minimum geofence radius that tends to work reliably is 150 meters.  

How then would it make any sense to attempt a proximityRadius < the minimum reliable geofence radius?

**Comment by christocracy** [comment]
Have you [read this](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/geofencing.md)

**Comment by christocracy** [comment]
And [stare at this for a few minutes](http://www.transistorsoft.com/shop/products/assets/images/background-geolocation-infinite-geofencing.gif) to visualize `geofenceProximityRadius` in action.

**Comment by jorgemejia** [comment]
Thanks for answer.

What I want to do is, when user walks, the app sould be able to alert when cross a geofence, in this case geofences could be near to other one so that´s te reason I´m trying to reduce proximityRadius to prevent on entry of two diferent geofence.

is it possible to do that?

**Comment by christocracy** [comment]
>is it possible to do that?

Impossible.
