### ISSUE TITLE
Query on tracking startup

### ISSUE THREAD

**Issue by joewoodhouse** [transistorsoft/cordova-background-geolocation-lt#371]
On both iOS and Android I am seeing quite a big lag at the start of tracking, where it will not detect movement for maybe 1 to 2km. 

I can see from the documentation (https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Help-it-Doesn't-Work!!) that at least on iOS this is expected behaviour. 

So my questions are 
a) Is there a way to reduce this distance on iOS (using changePace perhaps?)
b) Is there any reason we would see this behaviour on Android?
c) We are almost certainly going to buy the licensed version of this plugin. Does the latest/private repository have any improvements in this area?

# Your Environment
* Plugin version:
* Platform: iOS & Android
* OS version: Latest (10.3.1 & 6.0.1)
* Device manufacturer / model: iPhone4S & Nexus 6P
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):   
  android 6.1.2
  ios 4.3.1

* Plugin config
```
const backgroundGeolocationConfig: any = {
    debug: false,
    desiredAccuracy: 0,
    distanceFilter: 20,
    stationaryRadius: 25,
    fastestLocationUpdateInterval: 5000,
    locationUpdateInterval: 10000,
    minimumActivityRecognitionConfidence: 70,
    preventSuspend: true,
    activityType: 'OtherNavigation',
    foregroundService: true,
    heartbeatInterval: 10
};
```

## Expected Behavior
1) Locations begin tracking immediately in a regular manner.

## Actual Behavior
1) A delay of ~1-2km is seen before tracking kicks in properly.

## Steps to Reproduce

1. Start tracking on iOS & Android, monitor positions

**Comment by joewoodhouse** [comment]
I thought potentially I could use `watchPosition` for the first N seconds of the tracking to get it going? Would it be madness to use both background tracking and `watchPosition` simultaneously, even for a short period?

**Comment by christocracy** [comment]
>a) Is there a way to reduce this distance on iOS (using changePace perhaps?)

If you start out on a trip with the phone in your pocket, iOS has suspended your app in the background.  The only thing that can awaken it is to exit the stationary geofence the plugin has created around the last known position.  This stationary geofence typically requires movement of ~200 meters away from the last-known-position.  There is no way to improve this.  It's a limitation of iOS.

If your app is alive (ie: in the foreground), sure you can execute the `changePace(true)` method to immediately engage tracking.  Once the plugin detects the device is still, it's going to engage the `stopTimeout` timer and the plugin will change state back to `stationary`.

>b) Is there any reason we would see this behaviour on Android?

Android is monitoring the ActivityRecognitionAPI constantly, regardless of foreground / background.  Difficult to speculate without seeing logs.  The plugin stores 3 days of logs.  See the `#getLog` / `#emailLog` methods.

>c) We are almost certainly going to buy the licensed version of this plugin. Does the latest/private repository have any improvements in this area?

No.

**Comment by christocracy** [comment]
Here's a couple of weeks of sample data.  
- The **red** dots are places where the device stopped.
- The **green** polylines are places where the plugin detected device is moving and engaged tracking.

**iOS**
![](https://www.dropbox.com/s/2ioenenf3e76upf/Screenshot%202017-06-13%2010.15.43.png?dl=1)

**Android** (much quicker to engage tracking than iOS)
![](https://www.dropbox.com/s/x5p5pn68ecs3c8m/Screenshot%202017-06-13%2010.17.46.png?dl=1)
