### ISSUE TITLE
Feature Request: Limit location updates (and http sync) to accuracy below a certain value

### ISSUE THREAD

**Issue by mb34124** [transistorsoft/cordova-background-geolocation-lt#373]
## Your Environment
* Plugin version: **Latest**
* Platform: iOS or Android **Both**
* OS version: **Any**
* Device manufacturer / model: **All**
* Cordova version (`cordova -v`):  **4.x and up**
* Cordova platform version (`cordova platform ls`): **4.x and up**
* Plugin config **default example in documentation**

## Expected Behavior

Only trigger location updates (and http sync) if accuracy is below a certain value

## Actual Behavior

We receive all location updates regardless of accuracy

## Steps to Reproduce

1.  Start plugin with default config from documentation
2.  Receive all location updates no matter accuracy level

## Context

We throw out location updates if the accuracy value is 'too high'.   Our use case dictates that we only store location updates if we are "pretty certain" you are where you say you are.  We also post process our data for our own geofencing but only use location data with a certain accuracy.  It would be nice to not even receive those updates from the plugin (through http sync or location update event).  It would help us on the 'chattiness' of our app, battery usage (though probably minimal), and how much data we store/process.  We understand the limitations of using only the 'most accurate' data but it fits our use case to do so.

I was hoping you could add a configuration value for 'max accuracy' and then use that value in the OS event that you are handling.  Then you could only do the http call or trigger our registered event if the accuracy level is below what we configure.

## Debug logs

NA

**Comment by AlphaCreative** [comment]
Do you have an ETA on this enhancement?

**Comment by christocracy** [comment]
No

**Comment by christocracy** [comment]
This issue is very old.

**Comment by AlphaCreative** [comment]
Yes this issue is very old.  Did this feature get implemented?
