### ISSUE TITLE
General Help Question - Keeping App Running in background efficiently with plugin

### ISSUE THREAD

**Issue by stib** [transistorsoft/cordova-background-geolocation-lt#377]
## Your Environment
* Plugin version: 2.2.0
* Platform: iOS or Android
Both
* OS version: n/a
* Device manufacturer / model: n/a
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`):
  android 6.0.0
  ios 4.3.1
* Plugin config: n/a

This is a general help question. My App needs to report back location when it receives a Data Request Notification - I don't need to track location all the time. Which means the App should be able to receive and respond when in background when the Data Request Notification comes in.

Both iOS and Android will eventually kill the App because of memory pressure unless I use preventSuspend for iOS (which is expensive) or foregroundService for Android (which I assume is also expensive battery wise).

My question is what is the most efficient way to ensure the App is able to come back alive after the OS has suspended or terminated it given I am not worried about constant tracking but only when location is requested.

_For Android_: It seems if I use forceReloadOnMotionChange then the App should reload in background (if already terminated) when OS detects motion otherwise I can continue using the old location.

_For iOS_: I am less sure. If I use "UIBackgroundMode" set to "location" in the Capabilities and Apple approves will my App automatically come back alive (after OS terminates) when there is location change? Or do I need to set useSignificantChangesOnly to true in the plugin to enable the App to connect with the Significant Changes API and kick my App back to life when there is a significant location change (as Apple documentation seems to suggest)? 

The plugin documentation for useSignificantChangesOnly says "Set true in order to disable constant background-tracking and use only the iOS Significant Changes API". It sounds like I should set this flag to true because I don't need constant background-tracking.

And how do these options behave when the User terminates the App instead of the OS in terms of bringing the App back to life to respond to data notifications?

Have read a bunch of documentation but not sure if I have it all straight. Appreciate any thoughts/feedback.

Thanks,
-S

**Comment by christocracy** [comment]
If you don't need to track location all the time, this plugin is not for you.

**Comment by christocracy** [comment]
`foregroundService: true` for Android is not a big battery consumer.

>when it receives a Data Request Notification

Are you talking about a push request?  You don't need this plugin for fetching the location from a push request.
