### ISSUE TITLE
A (super) simple question

### ISSUE THREAD

**Issue by m-menon** [transistorsoft/cordova-background-geolocation-lt#379]
If we just need to get the location once ( as accurately as possible ) without starting the background service, can we just execute `bgGeo.getCurrentPosition()` and get done with it? This is because on some devices we just need an occasional lookup at the location, and not continuous. If there's a snippet that would help. Thanks

And also for Android - does this plugin need any other core cordova plugins? For example device motion plugin or something? As it uses the accelerometer

**Comment by christocracy** [comment]
iOS:  No.  without location-services on continuously, the OS suspends your app while in the background.  You would best `useSignificantChangesOnly: true` for iOS and you'll get a location update about every 500-1000 meters.

>And also for Android - does this plugin need any other core cordova plugins? For example device motion plugin or something? As it uses the accelerometer

No.

**Comment by m-menon** [comment]
All righty, thanks for the clarification :+1:
