### ISSUE TITLE
Will it work if the app is closed?

### ISSUE THREAD

**Issue by vasconcelloslf** [transistorsoft/cordova-background-geolocation-lt#38]

**Comment by christocracy** [comment]
Yes, as long as you configure `stopOnTerminate: false`.

iOS will require the device to move 2-3 blocks for tracking to re-engage after user closes the app.

**Comment by Jpsankaran** [comment]
Hi,
I want to send _geo location coordinates_ to my service URL for every 10sec in background(**app is not open**) .In which function i have to call _Ajax_ ?

If possible to use " url , params " option means,where will i get geo location coordinates.

**Comment by christocracy** [comment]
@Jpsankaran you need to forget about time-based Geolocation in background.  Geolocation in background is strictly *distance-based*.  If the device isn't moving, no location events.

Every 10s??  Do you not care about battery life?  Your desire is simply not possible, forget it.
