### ISSUE TITLE
Licence validation failure toast message in release alpha version

### ISSUE THREAD

**Issue by michaelhoepfner** [transistorsoft/cordova-background-geolocation-lt#380]
We've got a licence validation failure toast message in release alpha version in our paid version of the plugin. Maybe something went wrong with our licence key.

Thanks for your help.

## Your Environment
* Plugin version: 2.7.0
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Nexus 6
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): 6.2.3
* Plugin config

<plugin name="cordova-background-geolocation-lt">
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
        <variable name="LICENSE" value="<OUR_LICENCE_KEY>" />
    </plugin>

## Expected Behavior
No licence validation failure toast message in release version

## Actual Behavior
Licence validation failure toast message in release version

## Steps to Reproduce

1. Install alpha release of app from playstore
2. Start app
3. Toast message with licence validation failure message

**Comment by christocracy** [comment]
This is the Free repo.  Customers do not use the free version.
