### ISSUE TITLE
Send more values in emailLog method 

### ISSUE THREAD

**Issue by anurag0707** [transistorsoft/cordova-background-geolocation-lt#382]
Can we send more than configuration properties when we call the emailLog method such as latitude, longitude, current location of user etc

**Comment by christocracy** [comment]
#emailLog already renders the plugin config to the body of the email

![](https://www.dropbox.com/s/nopkfeea12o6zjn/Screenshot%202017-06-26%2011.11.39.png?dl=1)

If you want the current location in the log, simply request `getCurrentPosition` before you call `emailLog`:

```javascript
myEmailLog() {
  BackgroundGeolocation.getCurrentPosition(function(location, taskId) {
    BackgroundGeolocation.emailLog(emailAddress);
  }, function(error) { 
    console.log(error); 
  }, {persist: false});
}
```

**Comment by anurag0707** [comment]
Yeah we can get current location using getCurrentPosition method but is there a way where along with plugin config i can also send latitude and longitude inside email body using emailLog method

**Comment by christocracy** [comment]
The emailLog method is in the open-source portion of the plugin.  You're free to fork the plugin and provide your own implementation of emailLog.
