### ISSUE TITLE
HTTP call provides wrong identifier and action.

### ISSUE THREAD

**Issue by rbetjes** [transistorsoft/cordova-background-geolocation-lt#384]
## Your Environment
* Plugin version: 2.7.3
* Platform: iOS and Android
* OS version: 10.2.1
* Device manufacturer / model: Apple and huawai
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): ios 4.3.1
* Plugin config

{
      url: `${this.config.api}checkinout`,
      httpRootProperty: 'data',
      debug: true,  // <-- Debug sounds & notifications.
      stopOnTerminate: false, //default is true
      startOnBoot: true, //default is false
      geofenceTemplate: '{ "identifier":"<%= geofence.identifier %>", "type": "<%= geofence.action %>", "battery": "<%= battery.level %>", "timestamp": "<%= timestamp %>"}',
      extras: {
        "pnummer": this.pnummer
      }

## Expected Behavior
the plugin should make a call to the http backend with every enter and exit of multiple geofences.

## Actual Behavior
We add 22 geofences at once. when we're doing testing the debug messages from the plugin say that the device is (e.g.) entering fence with identifier 1 but the http call to the backend gets parameters for an exit on identifier 2.

## Context
Is it possible to create fences within fences? 
We've got an inner fence called 1_inner with only notifyOnEntry:true and an outer fence called 1_outer with the same lat/lon as 1_inner but with a radius 100m wider than 1_inner and  only notifyOnExit: true.
Is such a setup even possible?

**Comment by christocracy** [comment]
Show me plugin logs of this.

**Comment by rbetjes** [comment]
Attached is the _verbose_ log of the plugin for 3 geofence actions.
The first two (ENTER 44_inner and EXIT 44_outer) were correct. After that came ENTER 55_inner, but the call to the backend contained EXIT 44_outer.
Every call onwards (enters and exits in any geofence) will show EXIT 44_outer. 


[geofence_problem_log.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1102886/geofence_problem_log.txt)

**Comment by christocracy** [comment]
Are you observing your HTTP response from the server in the logs?
```
⚠️-[TSHttpService doPost:] HTTP ERROR: 202
***
* {"success":true,"message":"Checked out."}
.
.
.
⚠️-[TSHttpService doPost:] HTTP ERROR: 404
***
* {"success":false,"message":"You are not checked in at this location!"}
```

Since the plugin doesn't recognize [HTTP `202`](https://httpstatuses.com/202) as successful, the plugin keep attempting to re-send the failed location/geofence.

The plugin recognizes `200`, `201` and `204` as successful.  

I purposely chose not to allow `202` since this response is "noncommittal"

>The 202 response is intentionally noncommittal. Its purpose is to allow a server to accept a request for some other process (perhaps a batch-oriented process that is only run once per day) without requiring that the user agent's connection to the server persist until the process is completed. The representation sent with this response ought to describe the request's current status and point to (or embed) a status monitor that can provide the user with an estimate of when the request will be fulfilled.

**Comment by rbetjes** [comment]
Crystal clear answer. Changing the response code of the server resolves the issue. 
Thanks.
