### ISSUE TITLE
Turning off BackgroundLocation from server

### ISSUE THREAD

**Issue by awesomeguy3** [transistorsoft/cordova-background-geolocation-lt#385]
Is there a way for the plugin to be stopped via server for a specific device? Something like some push message which will stop it?

**Comment by christocracy** [comment]
Server push is a great way to control the plugin.  You can do whatever you want in your callback, including `BackgroundGeolocation.stop()`

**Comment by awesomeguy3** [comment]
Sorry, but can you please explain a little bit more? Do I need to use some push plugin like https://github.com/phonegap/phonegap-plugin-push for doing that or do you have some other suggestions?

**Comment by christocracy** [comment]
phonegap-plugin-push is fine

**Comment by mlazic** [comment]
Is there a way to stop your plugin remotely without running app manually by the user via clicking push notification ?
Or could it be stopped via response when it send data to server ?

**Comment by christocracy** [comment]
You can send a "silent push" notification (google it).

Push is a great way to control the plugin.

**Comment by mlazic** [comment]
@christocracy 
I am not familiar too much with Android and cordova.
Can you please help me how to send request via server that will kill your background process on specific phone.
I will buy your plugin but I need to be sure to have option to turn off plugin remotely.

Can it be done via phonegap-plugin-push and if yes please help me with example ?

**Comment by christocracy** [comment]
This really has nothing to do with the plugin.  

Have you got server push working yet?  If not, go visit PhoneGap-plugin-push and learn there how to set up push.

**Comment by mlazic** [comment]
I achieved it using this code, but it requires pressing on notification and opening the app in order to stop BackgroundGeolocation. I need it to work like a silent push without showing notification and clicking on it in order to stop the plugin.

var push = PushNotification.init({
   "android": {
      "senderID": "############",
      "icon": "icon",
      "iconColor": "white"
   }
});

push.on('registration', function(data) {
   //console.log(data.registrationId);
   
   app.serverAddress = app.liveMode.serverAddress;
   $.ajax({
      url: 'save_user_device',
      data: {
         device_id: data.registrationId,
         user_id: app.user.id
      },
      method: 'post'
   })/*.done(function(response) {
        alert(response);
       })*/;
});

push.on('notification', function(data) {
   app.serverAddress = app.liveMode.serverAddress;
   $.ajax({
      url: 'read_notification',
      data: {
         //device_id: data.registrationId,
         user_id: app.user.id,
         notification_id: data.additionalData.notification_id
      },
      method: 'post'
   })/*.done(function(response) {
        alert(response);
        })*/;
        
       
   if(parseInt(data.additionalData.stop_tracking) === 1) {
      BackgroundGeolocation.stopSchedule(function() {
         BackgroundGeolocation.stop();
      });
   }
   
   baseView.showAlert(" Message: " + data.additionalData.sent_msg, data.title);
});

push.on('error', function(e) {
   alert(e);
});

Please advice me what to do in order to stop it in background without running app and stopping it from app ?

**Comment by christocracy** [comment]
I instructed `phonegap-plugin-push` to [implement notifications in the background](https://github.com/phonegap/phonegap-plugin-push/issues/93) in 2015.

You need to consult with their API on how to implement a "silent background notification".

**Comment by mlazic** [comment]
In their api there is nowhere any mention of "silent background notification".
I tried to send content-available: 1 and it fires correctly when app is in background but it wont run when app is closed, is there any way with this or any other plugin to stop your plugin when app is closed ?

**Comment by christocracy** [comment]
These are not questions for this plugin.  There are questions you can ask the folks at `phonegap-plugin-push`.

[What is a "silent" push notification](https://stackoverflow.com/questions/36694963/what-is-silent-push-notification-when-does-the-device-receive-it)

**Comment by mlazic** [comment]
I really don't understand how this is not related to your plugin when I need the way to close your plugin. 
Is it possible to change your java code to receive callback action stop when send location to server if response is 'stop background tracking' ?

**Comment by christocracy** [comment]
My plugin is not responsible for receiving a push notification.  *Your* app is.  My plugin is a a passenger of your app.

If you wish to execute methods upon the plugin in your push callback function, that's completely your business.

```javascript
onPush(notification) {
  var extras = notification.extras;
  if (extras.stop_background_geolocation) {
    BackgroundGeolocation.stop();
  }
});
```

If you consult with the folks at `phonegap-plugin-push`, you'll find it has [the ability to `forceStart` a terminated Android app](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/FCMService.java#L335) by supplying `forceStart` in your Push notification.

```
{
  content-available: 1
  forceStart: 1,
  extras: {
    stop_background_geolocation: 1
  }
}
```

This plugin has **nothing at all** to do with Push or receiving push in a terminated app.  It's completely the responsibility of `phonegap-plugin-push`.
