### ISSUE TITLE
Offline location tracking synchronisation information

### ISSUE THREAD

**Issue by dylanvdmerwe** [transistorsoft/cordova-background-geolocation-lt#387]
I would like to find out more information how to track users without network connectivity. I've hunted through the docs, but there is nothing clear about how the plugin handles offline modes. 

As far as I can tell, location events are stored in the SQL database on the device. If there is a network connection and the `url` and `autoSync` is configured, the plugin will try and POST locations to the server. With a network connection, this works as expected.

My questions are as follows for when there is no network connection:
1. Are the locations still stored in the SQL database?
2. When the network is available, will the plugin automatically try and send all stored locations to the server? How many times does it try?
3. If the plugin does not automatically do this, does the app need to manually call the `sync` method to POST all remaining database items to the server and empty the database?
4. Does calling `sync` while the `autoSync` is `true` break anything?
5. For any `autoSync` items that failed (due to timeout, network issue, or some other factor) will these remain in the database and need to be manually synced?

We're trying to build a robust fuel logger that will reliably track users as best as possible, and return all positions logged (eventually & automatically) regardless of connectivity.

I would highly appreciate your feedback and insight. 

## Your Environment
* Plugin version: 2.7.3
* Platform: iOS
* OS version: 10.x
* Device manufacturer / model: iPhone
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): ios 4.4.0
* Plugin config

```
          {
            // Geolocation config
            desiredAccuracy: 0,
            distanceFilter: 5,
            stationaryRadius: 5,
            preventSuspend: true,
            heartbeatInterval: 10,

            // Activity Recognition config
            activityRecognitionInterval: 10000,
            stopTimeout: 5,
            // Application config
            debug: false,  // <-- Debug sounds & notifications.
            stopOnTerminate: true,
            startOnBoot: false,
            // HTTP / SQLite config
            url: this.appInfo.serviceUrl + '/location/background',
            method: "POST",
            autoSync: true,
            maxDaysToPersist: 30,
            headers: {  // <-- Optional HTTP headers
                'ApiKey': apiKey,
                'Accept': 'application/json'
            },
            params: {   // <-- Optional HTTP params
                'userId': userId,
                'utcoffset': this.device.utcOffset
            }
```

```
        var callbackFn = function (location, taskId) {
            let coords = location.coords;
            let lat = coords.latitude;
            let lng = coords.longitude;
            //console.log("BACKGROUND", lat + ' ' + lng);

            try {
                this.appLocation.LastKnownLatitude = coords.latitude;
                this.appLocation.LastKnownLongitude = coords.longitude
            }
            catch (ex) {
                console.error(ex);
            }

            // Must signal completion of your callbackFn.
            bgGeo.finish(taskId);
        };

        var failureFn = function (errorCode) {
            console.warn('- BackgroundGeoLocation error: ', errorCode);
        }
```

**Comment by christocracy** [comment]
The plugin was designed for tracking first-responders in disaster zones, in environments where the network infrastructure is likely destroyed.

It's really very simple:  *Every* location is first persisted to database, **no matter what**.  

- The persistence layer is completely independent of the HTTP layer.  `maxRecordsToPersist` (default infinite) will be enforced when configured, by killing oldest before inserting latest.
- The HTTP layer operates by selecting records from the database.
- As long as there are records in the database, the HTTP layer will continue attempting to sync those to your server until `maxDaysToPersist` expires, when expired records will be deleted.  The HTTP layer **strongly** desires an empty database.  When your server returns a success response, the HTTP layer will delete that record from database.  As long as there are records in the database, the HTTP layer will continue posting until your server returns an error, when it will give up until the next `sync` event
- The `autoSync` system is engaged in a number of scenarios:
  - Location is recorded
  - Background `fetch` event
  - Application `suspend` / `resume` event
  - Application boot

>1. Are the locations still stored in the SQL database?

Yes

>2. When the network is available, will the plugin automatically try and send all stored locations to the server? How many times does it try?

Yes, until `maxDaysToPersist` or `maxRecordsToPersist` causes record(s) to be pruned.

>4. Does calling sync while the autoSync is true break anything?

No.

>5. For any autoSync items that failed (due to timeout, network issue, or some other factor) will these remain in the database and need to be manually synced?

Yes, until `maxDaysToPersist` or `maxRecordsToPersist` causes record(s) to be pruned.

**Comment by christocracy** [comment]
Of your config:
- `stationaryRadius: 5`:  enforced minimum is `25`
- `heartbeatInterval: 10` enforced minimum is `60`
- `stopOnTerminate: true` be careful.  The OS may terminate your app automatically when under memory pressure and tracking will stop even if user didn't explicitly terminate the app.

**Comment by dylanvdmerwe** [comment]
Thanks for the detailed response Chris. That is great to hear about the HTTP layer wanting an empty database. It may be a good idea to use your response above in the docs?

With regards to the HTTP layer retrying to send items to the server, are the timestamps of these items the time of the retry or the time of the item being logged?

**Comment by christocracy** [comment]
>With regards to the HTTP layer retrying to send items to the server, are the timestamps of these items the time of the retry or the time of the item being logged?

When the plugin records and persists a location, it inserts a JSON blob of the location (including `timetamp`) at that time.

When the HTTP layer selects a record to `POST`, it selects that JSON blob and appends it to the HTTP request body.

The `timestamp` corresponds to time the location was *recorded*.  The timestamp  a location is posted is meaningless information that your server can determine if so desired.

**Comment by dylanvdmerwe** [comment]
Thank you for your assistance!
