### ISSUE TITLE
Failed to fetch plugin.....

### ISSUE THREAD

**Issue by khwerhahn** [transistorsoft/cordova-background-geolocation-lt#39]
Fetching plugin "https://github.com/transistorsoft/cordova-background-geolocation.git" via git clone
Error: Failed to fetch plugin https://github.com/transistorsoft/cordova-background-geolocation.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/tmp/git/1448183248166'...
remote: Repository not found.
fatal: repository 'https://github.com/transistorsoft/cordova-background-geolocation.git/' not found

**Comment by christocracy** [comment]
Are you a paid customer?  That's the "premium", private repo.

The free version repo ends with "-lt"

On Sunday, November 22, 2015, Konstantin <notifications@github.com> wrote:

> Fetching plugin "
> https://github.com/transistorsoft/cordova-background-geolocation.git" via
> git clone
> Error: Failed to fetch plugin
> https://github.com/transistorsoft/cordova-background-geolocation.git via
> git.
> Either there is a connection problems, or plugin spec is incorrect:
> Error: git: Command failed with exit code 128 Error output:
> Cloning into '/tmp/git/1448183248166'...
> remote: Repository not found.
> fatal: repository '
> https://github.com/transistorsoft/cordova-background-geolocation.git/'
> not found
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/39>
> .
>


-- 
Snet form Gmail Mobile

**Comment by khwerhahn** [comment]
Thx for the answer. I'm not (yet).

In the docs it says cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git instead of cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git

A little bit confusing.

**Comment by christocracy** [comment]
Ooops.  fixed.  thanks

On Sun, Nov 22, 2015 at 12:01 PM, Konstantin <notifications@github.com>
wrote:

> Thx for the answer. I'm not (yet).
>
> In the docs it says cordova plugin add
> https://github.com/transistorsoft/cordova-background-geolocation.git
> instead of cordova plugin add
> https://github.com/transistorsoft/cordova-background-geolocation-lt.git
>
> A little bit confusing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/39#issuecomment-158778340>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
