### ISSUE TITLE
Success callback only when moving - How to differ between active and inactive device?

### ISSUE THREAD

**Issue by JaneDawson** [transistorsoft/cordova-background-geolocation-lt#390]
As far as I understand, the success-callback-function (at least on iOS) is only executed if the devices position changes. Hence, the success-callback is not called if the device doesn't move and I cannot know if the device is still sending it's location.

How would I then be able to differ between a device that is active but doesn't move and a device that suddenly gets switched off or doesn't allow to track location anymore?

**Comment by christocracy** [comment]
you can determine if user changes the state of location-services (eg: disabled) by listening to the [providerchange](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#zap-events) event.

Other than that, if you're concerned about a particular device, I'd send a "silent" server push request to that device, that is, a Push request with only a JSON payload (no message).

With [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push)

```
{
  content-available: 1,  // <-- iOS: allow push in background
  forceStart: 1,             // <-- Android force-start a terminated android app to receive push
  extras: {                    // <-- JSON payload
    "command": "getCurrentPosition"
  }
```
And in your push callback on app:
```javascript
onPush(notification) {
  if (notification.extras) {
    switch(notification.extras.command) {
      case 'getCurrentPosition':
        BackgroundGeolocation.getCurrentPosition(success, fail, config);
        break;
    }
  }
}
```
