### ISSUE TITLE
Location coords accuracy returning 900

### ISSUE THREAD

**Issue by alexbarnsley** [transistorsoft/cordova-background-geolocation-lt#392]
## Your Environment
Plugin version: 2.7.3
Platform: Android
OS version: 7.1.1
Device manufacturer / model: OnePlus 3
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): 6.0.0
Plugin config:

```js
desiredAccuracy: 0,
distanceFilter: 10,
stationaryRadius: 25,
locationUpdateInterval: 10000,
fastestLocationUpdateInterval: 5000,
activityType: 'AutomotiveNavigation',
activityRecognitionInterval: 10000,
stopTimeout: 5,
stopOnTerminate: false,
startOnBoot: true,
preventSuspend: true,
heartbeatInterval: 60,
foregroundService: true,
forceReloadOnGeofence: true,
forceReloadOnBoot: true,
notificationTitle: "IQ:timecard",
notificationText: "Tracking GPS for Passive clock In/Out",
```

## Expected Behavior
No exit event with bad GPS

## Actual Behavior
Exit event is fired

## Steps to Reproduce
1. Enter geofence (outside)
2. Go indoors, somewhere with a bad signal
3. Exit Event is fired (and GPS has accuracy of 900)

## Context
I know the Geofences are done at OS level. I would ideally like the system, if possible, to not run the Exit event when I have bad GPS. Really I'm after advice or best practice on how best to do this. I already extended the radius to 500 metres, but the accuracy is showing 900 which is quite large (I'm presuming this is metres based on [this](https://developer.android.com/reference/android/location/Location.html#getAccuracy())). What would your suggestion be here, other than extending the radius? Interestingly the latitude and longitude returned are within the geofence radius, but it still fired the event.

Thanks

**Comment by christocracy** [comment]
When you get a location with `accuracy: 900`, that location obviously didn't come from GPS.

Mobile location-services != GPS.

Mobile location services = GPS (accuracy ~5-10 meters) + Wifi geolocation (accuracy ~40-100 meters)+ Cell triangulation (accuracy ~1000 meters).

A location having `accuracy: 900` likely came from Cell tower triangulation.  Do you have Wifi disabled?

**Comment by christocracy** [comment]
Closed for lack of feedback.
