### ISSUE TITLE
Http request on app closed.

### ISSUE THREAD

**Issue by jorgemejia** [transistorsoft/cordova-background-geolocation-lt#397]
## Your Environment
* Plugin version: 2.7.1
* Platform: iOS 
* OS version: 10.3.2
* Device manufacturer / model: iPhone 7
* Cordova version : 6.5.0
* Cordova platform version (`cordova platform ls`): ios 4.3.1
* Plugin config
this.bgGeo.configure({
                      // Geolocation config
                      desiredAccuracy: 0,
                      distanceFilter: 10,
                      stationaryRadius: 12,
                      locationAuthorizationRequest:"Always",
                      // Activity Recognition config
                      activityRecognitionInterval: 0,
                      stopTimeout: 5,
                      // Application config
                      debug: false,  // <-- Debug sounds & notifications.
                      stopOnTerminate: false,
                      startOnBoot: true,
                      preventSuspend:true,
                      // HTTP / SQLite config
                      url: "http://www.server/gps",
                      method: "POST",
                      autoSync: true,
                      batchSync: true,
                      maxDaysToPersist: 3,
                      headers: {  // <-- Optional HTTP headers
                          'Content-Type': 'application/json'
                      },
                      params: {   // <-- Optional HTTP params
                          "par1": par1,
                          "par2" : par2,
                          "par3" : par3
                      }
                  }, function(state) {
                      // This callback is executed when the plugin is ready to use.
                      console.log("BackgroundGeolocation ready: ", state);
                      if (!state.enabled) {
                          self.bgGeo.start();
                      }
                  });
## Expected Behavior
Is it possible to send http request when the app is closed ? 

## Actual Behavior
When the app is completely closed, it doesn't send the information to the server, it only works in background and foreground.

## Context
Send gps information to the server even when the app is completely closed.

**Comment by christocracy** [comment]
When an iOS app is terminated with [stopOnTerminate: false](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-stoponterminate-true), your app *is* terminated.

However, when the device is detected to be moving (iOS typically requires ~200 meters movement beyond last known location), iOS will reboot the app and tracking (and HTTP posts) will resume.

See docs for [stopOnTerminate](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-stoponterminate-true)
