### ISSUE TITLE
Ionic No BackgroundGeolocation on window object

### ISSUE THREAD

**Issue by popcorn245** [transistorsoft/cordova-background-geolocation-lt#4]
I have tried everything and am pulling my hair out here.  I have my code to execute inside of the block below which is supposed to be equivalent to deviceready and even when I try to manually tie to deviceready it doesn't fire. 

```
$ionicPlatform.ready(function() {
```

Even when trying to pull a geolocation first and then initializing the plugin I get cannot read property 'configure' of undefined. The strange thing to me is that there is no DI.  Every other plugin I use I inject first, but I see nowhere documenting that I do this.  Please help I am on a tight deadline..

**Comment by christocracy** [comment]
Have you looked at the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/app.js#L130)

Are you running this in the browser or on the device?

**Comment by popcorn245** [comment]
Android Device and yes. So does the plugin inject itself when the deviceready event fires?

**Comment by popcorn245** [comment]
Hmmmm I dunno how I missed that line. Thanks I will try shortly and close ticket if necessary. Thanks Chris! ^_^

**Comment by hhpom** [comment]
I'm having the same issue with no "BackgroundGeolocation" property on the window object. I've installed the plugin in a vanilla phonegap app via the phonegap cli and waited until device ready to check for window.BackgroundGeolocation and it doesn't exist.

I then tried installing the sample app (https://github.com/transistorsoft/cordova-background-geolocation-SampleApp), which is Ionic based but got the same result.

- Cordova version 5.1.1
- Xcode 6.4
- iOS 8.2 on device and in simulator

@christocracy could this be a compatibility issue or is there something I'm missing?

**Comment by christocracy** [comment]
Upgrade to Xcode 7+

On Thursday, October 8, 2015, hhpom <notifications@github.com> wrote:

> I'm having the same issue with no "BackgroundGeolocation" property on the
> window object. I've installed the plugin in a vanilla phonegap app via the
> phonegap cli and waited until device ready to check for
> window.BackgroundGeolocation and it doesn't exist.
>
> I then tried installing the sample app (
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp),
> which is Ionic based but got the same result.
>
>    - Cordova version 5.1.1
>    - Xcode 6.4
>    - iOS 8.2 on device and in simulator
>
> @christocracy <https://github.com/christocracy> could this be a
> compatibility issue or is there something I'm missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/4#issuecomment-146522146>
> .
>


-- 
Snet form Gmail Mobile

**Comment by hhpom** [comment]
Upgraded Xcode to 7.0.1 and the plugin works smoothly! Thanks
