### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by popcorn245** [transistorsoft/cordova-background-geolocation-lt#40]
I have code that logs a final location before I stop the background geolocation service. It is throwing an error when I run the following because I don't have the taskId variable. How do I get said variable so it doesn't error out, I don't think it effects the functionality but I don't want this thing to error if I can avoid it. Thanks! ^_^

Code I Run

```javascript
this.bgGeo.getCurrentPosition(function(location) {
    this.driver.session.end = {
        lat: location.coords.latitude,
        lng: location.coords.longitude,
        timestamp: new Date().toString()
    };

    this.driver.$save();

    this.bgGeo.stop();
}.bind(this), this.missing);
```

Error
```
BackgroundGeolocation caught a Javascript Exception in your application code(anonymous function) @ console-via-logger.js:173module.exports._runBackgroundTask @ BackgroundGeolocation.js:367mySuccess @ BackgroundGeolocation.js:48cordova.callbackFromNative @ cordova.js:291processMessage @ cordova.js:1079processMessages @ cordova.js:1102pollOnce @ cordova.js:971pollOnceFromOnlineEvent @ cordova.js:958
console-via-logger.js:173  while running in a background thread.  Auto-finishing background-task: task-id-undefined
console-via-logger.js:173  to prevent application crash
console-via-logger.js:173 *************************************************************************************
console-via-logger.js:173 STACK:
 TypeError: Cannot read property 'id' of undefined
    at GeolocationService.located (file:///android_asset/www/js/build.js:81593:96)
    at Object.<anonymous> (file:///android_asset/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:49:25)
    at Object.module.exports._runBackgroundTask (file:///android_asset/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:364:22)
    at mySuccess (file:///android_asset/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:48:16)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:291:58)
    at processMessage (file:///android_asset/www/cordova.js:1079:17)
    at processMessages (file:///android_asset/www/cordova.js:1102:9)
    at pollOnce (file:///android_asset/www/cordova.js:971:9)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:958:5)
console-via-logger.js:173 TypeError: Cannot read property 'id' of undefined(…)
```

**Comment by christocracy** [comment]
See docs for getCurrentPosition.

https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#getcurrentpositionsuccessfn-failurefn-options

And read this:
https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Background-Tasks

On Monday, November 23, 2015, Bobby Johnson <notifications@github.com>
wrote:

> I have code that logs a final location before I stop the background
> geolocation service. It is throwing an error when I run the following
> because I don't have the taskId variable. How do I get said variable so it
> doesn't error out, I don't think it effects the functionality but I don't
> want this thing to error if I can avoid it. Thanks! ^_^
>
> Code I Run
>
> this.bgGeo.getCurrentPosition(function(location) {
>     this.driver.session.end = {
>         lat: location.coords.latitude,
>         lng: location.coords.longitude,
>         timestamp: new Date().toString()
>     };
>
>     this.driver.$save();
>
>     this.bgGeo.stop();
> }.bind(this), this.missing);
>
> Error
>
> BackgroundGeolocation caught a Javascript Exception in your application code(anonymous function) @ console-via-logger.js:173module.exports._runBackgroundTask @ BackgroundGeolocation.js:367mySuccess @ BackgroundGeolocation.js:48cordova.callbackFromNative @ cordova.js:291processMessage @ cordova.js:1079processMessages @ cordova.js:1102pollOnce @ cordova.js:971pollOnceFromOnlineEvent @ cordova.js:958
> console-via-logger.js:173  while running in a background thread.  Auto-finishing background-task: task-id-undefined
> console-via-logger.js:173  to prevent application crash
> console-via-logger.js:173 *************************************************************************************
> console-via-logger.js:173 STACK:
>  TypeError: Cannot read property 'id' of undefined
>     at GeolocationService.located (file:///android_asset/www/js/build.js:81593:96)
>     at Object.<anonymous> (file:///android_asset/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:49:25)
>     at Object.module.exports._runBackgroundTask (file:///android_asset/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:364:22)
>     at mySuccess (file:///android_asset/www/plugins/com.transistorsoft.cordova.background-geolocation/www/BackgroundGeolocation.js:48:16)
>     at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:291:58)
>     at processMessage (file:///android_asset/www/cordova.js:1079:17)
>     at processMessages (file:///android_asset/www/cordova.js:1102:9)
>     at pollOnce (file:///android_asset/www/cordova.js:971:9)
>     at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:958:5)
> console-via-logger.js:173 TypeError: Cannot read property 'id' of undefined(…)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/40>
> .
>


-- 
Snet form Gmail Mobile

**Comment by popcorn245** [comment]
I am manually invoking the bgGeo.getCurrentPosition so I don't need to pass in the task-id?

Also, do I call the this.bgGeo.finish(taskId) before or after bgGeo.stop()? My editing code looks like the following.

```javascript
this.bgGeo.getCurrentPosition(function(location, taskId) {
    this.driver.session.end = {
        lat: location.coords.latitude,
        lng: location.coords.longitude,
        timestamp: new Date().toString()
    };

    this.driver.$save();

    this.bgGeo.stop();
    this.bgGeo.finish(taskId);
}.bind(this), this.missing);
```

**Comment by christocracy** [comment]
You don't provide taskId to getCurrentPosition -- it's provided to you as
2nd arg in callback, after location.

You must signal the end of your callback by executing bgGeo.finish(taskId).

Do it after bgGeo.stop().  Shouldn't matter, but it should always be the
last thing you do

On Monday, November 23, 2015, Bobby Johnson <notifications@github.com>
wrote:

> I am manually invoking the bgGeo.getCurrentPosition so I don't need to
> pass in the task-id?
>
> Also, do I call the this.bgGeo.finish(taskId) before or after
> bgGeo.stop()? My editing code looks like the following.
>
> this.bgGeo.getCurrentPosition(function(location, taskId) {
>     this.driver.session.end = {
>         lat: location.coords.latitude,
>         lng: location.coords.longitude,
>         timestamp: new Date().toString()
>     };
>
>     this.driver.$save();
>
>     this.bgGeo.stop();
>     this.bgGeo.finish(taskId);
> }.bind(this), this.missing);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/40#issuecomment-159090358>
> .
>


-- 
Snet form Gmail Mobile

**Comment by popcorn245** [comment]
That's the thing I am manually calling it and not inside of a bgGeo.config so how can it pass the taskId if it didn't call it...
