### ISSUE TITLE
Unable to show App settings or location settings

### ISSUE THREAD

**Issue by bhargavkonkathi** [transistorsoft/cordova-background-geolocation-lt#400]
Hello Team,
We used plugin in our application and we have plans to take premium membership. Plugin worked nice in android but we have faced some issues in iOS. Issues are mentioned below.

## Your Environment
* Plugin version: 2.7.3
* Platform: Android
* OS version: Android Version 6
* Device manufacturer / model: Nexus
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): 6.2.3
* Plugin config
`<plugin name="cordova-background-geolocation-lt" spec="^2.7.3">
        <variable name="LICENSE" value="4bbb513c013111eae951647fd4f9e79f127fce6f7a00e9d327db9ea2a053a0df" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>`

## Expected Behavior
1.Location permission dialog shown only once for first time, and when user denies location permission there should be way to show App settings or Location settings from application using same plugin 
2. There should be way to use location in IOS based on time interval
## Actual Behavior
1.Location settings dialog shown two times i.e When user deny for location it is asking again for user location permission. Plugin missing feature for showing App settings or location settings when user deny for location access.
2. When tried for accessing location in iOS for certain interval it is not working properly i.e giving continues locations for each second.

## Context
We are trying to track user location based certain interval like for each 1 min or 2 min etc. for tracking race information and use geofence features to show notifications to show users based on restricted location area.

Please give us any suggestions for iOS to track for each certain interval like 1 min or 2 min etc. and is there any way to know if user accept or denied location permission request for app when we try to configure it.

Thank you.

**Comment by christocracy** [comment]
Plugin config is this:
```
{
  desiredAccuracy: 0,
  distanceFilter: 50,
  stopOnTerminate: false,
  .
  .
  .
}
```

**Comment by christocracy** [comment]
>2. There should be way to use location in IOS based on time interval

The iOS native location API is strictly *distance-based*.  A location is recorded each `distanceFilter` meters.  Note:  by default the plugin auto-scales the `distanceFilter` based upon speed (higher speed = higher `distanceFilter`.  Use [disableElasticity](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-disableelasticity-false) to prevent this.

**Comment by bhargavkonkathi** [comment]
Thank you @christocracy for giving valuable information to us.

**Comment by christocracy** [comment]
>1.Location permission dialog shown only once for first time, and when user denies location permission there should be way to show App settings or Location settings from application using same plugin

I've refactored the location-authorization handling to better handle this.  It's not available yet here in the Free version.

**Comment by christocracy** [comment]
For Android, you can listen to the plugin's [providerchange](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#providerchange) event.  This event fires when that user modifies that state of Location Services settings.

If you want to show a dialog directing the user to settings screen, there's [existing 3rd-party plugin's](https://github.com/selahssea/Cordova-open-native-settings) specialized in that sort of thing.

**Comment by bhargavkonkathi** [comment]
Hello,
I followed using heartbeatInterval in configuration settings. But still i have same issue like previously. Config is as below,  

```
var config = {
    desiredAccuracy: 0,
    distanceFilter: 100,
    stopTimeout: 10,
    activityType: 
    heartbeatInterval:120000,
    disableElasticity: true,
    locationUpdateInterval: 120000,
    fastestLocationUpdateInterval: 120000,
    foregroundService: true,
    preventSuspend:true,
}
```
Although is it necessary to include `acitivityType` to AutomotiveNavigation or any other settings.
Thanks.

**Comment by christocracy** [comment]
What is your issue and on which platform?

**Comment by bhargavkonkathi** [comment]
Above configuration which I was using for iOS to fetch location for every interval like 2 min. But I have got more location callbacks in iOS for example continuesoly like for each 2 seconds.  How can I avoid getting multiple callbacks and get location call back like every one minute or two minutes in iOS. Do I need to remove interval or fastestInterval property when we set heartbeat Interval ? Or is there any extra configuration I can add for iOS restrict multiple location callback. Plugin is working nice. But this one small issue I'm facing in iOS

**Comment by christocracy** [comment]
Show me logs from XCode showing what you're talking about.

**Comment by bhargavkonkathi** [comment]
@christocracy 
We are using this plugin in our application, In android it is working nice, But when coming to iOS we are getting multiple locations in iOS for example for . I have used following configuration options for plugin for iOS.

`var bgOptions = {
    desiredAccuracy: 0,
    distanceFilter: 10,
    stopTimeout: 10,
    heartbeatInterval:120,
    pauseLocationUpdates: true,
    activityType: 'AutomotiveNavigation',
    //disable automatic, speed-based #distanceFilter elasticity.
    disableElasticity: true,
    locationUpdateInterval: 120000,
    fastestLocationUpdateInterval: 120000,
    notificationSmallIcon: "drawable/notification_small_icon",
    notificationLargeIcon: "drawable/notification_large_icon",
    foregroundService: true,
    preventSuspend:true
}`

Following screen shot show getting multiple location with in few seconds. 

![img_3426](https://user-images.githubusercontent.com/24550636/28264272-d1ca9e0a-6b07-11e7-9ddc-9957d92720b7.PNG)

Is there any way to restrict or avoid multiple location callbacks in iOS. Please help US to solve this problem i'e  getting location on interval based like 2 min or 1 min using heartBeatInterval in iOS. 
Thanks

**Comment by bhargavkonkathi** [comment]
Hello @christocracy ,
Please find attached log file for further information. I configured heartbeatInterval but following snippet callback never got called in ios. Please help me where I'm doing wrong.

```
backgroundGeolocation.on('heartbeat', function(params) { 
      console.log('- hearbeat'); // You could request a new location if you wish. 
      backgroundGeolocation.getCurrentPosition(function(location, taskId) { 
      console.log('- current location: ', location); 
            backgroundGeolocation.finish(taskId); 
      }); 
});
```

Thanks.
[log.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1156163/log.txt)

**Comment by christocracy** [comment]
Show me all your Javascript you're using to `#configure` and `#start` the plugin.

**Comment by bhargavkonkathi** [comment]
@christocracy ,

Please find attached javascript file for more details.
[javascript.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1156296/javascript.txt)

**Comment by christocracy** [comment]
- Make sure you only call `#configure` once for the lifetime of your app.  Do **NOT** execute `#configure` twice.
- Do not execute any method which would request the location *before* callback to `#configure` has executed:

eg:
```javascript
BackgroundGeolocation.getCurrentPosition(callback);  // <-- NO!
BackgroundGeolocation.start();  // <-- NO!
BackgroundGeolocation.configure(function(state) {
  BackgroundGeolocation.start();  // <-- OK
  BackgroundGeolocation.getCurrentPosition(callback);  // <-- OK
});
// You must wait for callback to #configure to execute!
BackroundGeolocation.start();  // <-- NO!
BackgroundGeolocation.getCurrentPosition(callback)  // <-- NO!
```

**Comment by christocracy** [comment]
if you need to change config *after* `#configure`, use `#setConfig`

**Comment by bhargavkonkathi** [comment]
I have license key but when I try to set key in our application it overwrites application key with other sample key and shows License failure error. Please give suggestion or steps to add license key for project.

**Comment by christocracy** [comment]
This is is titled "Unable to show App settings or location settings".

Github issues are not open-ended support threads for any question you have.
