### ISSUE TITLE
Does the app support Javascript Background Execution?

### ISSUE THREAD

**Issue by lpender** [transistorsoft/cordova-background-geolocation-lt#401]
Hi!

Lovely plugin.

Before I go to the trouble of setting up and testing it extensively, I thought I'd just ask:

Does the app support Javascript Background Execution?

I'm building a Meteor app and looking for a replacement to [this plugin](https://github.com/lpender/cordova-plugin-geofence#javascript-background-execution). 

I can't use it because I need geofence transition to trigger the execution of Javascript in the background, and this plugin simply won't do it.

Does yours?

Thanks!
-Lee

**Comment by christocracy** [comment]
Yes, of course.

**Comment by lpender** [comment]
Thanks!
