### ISSUE TITLE
Failing to Send Log via emailLog

### ISSUE THREAD

**Issue by jimgibbs** [transistorsoft/cordova-background-geolocation-lt#402]
Failing to Send Log via emailLog 
The email is created, but since in my outbox and will not send. 

## Your Environment
* Plugin version: **cordova-background-geolocation-lt: ^2.7.1**
* Platform: **iOS**
* OS version: **10.3.2**
* Device manufacturer / model: **iPhone 6 Plus**
* Cordova version (`cordova -v`): **7.0.1**
* Cordova platform version (`cordova platform ls`): 

```
Installed platforms:
  android 6.2.3
  ios 4.4.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  osx ~4.0.1
  webos ~3.7.0
```

* Plugin config

```
this.bgGeo.configure({
      debug: false, 
      logLevel: this.bgGeo.LOG_LEVEL_VERBOSE, 
      autoSync: false, 
      desiredAccuracy: 0, 
      distanceFilter: 10, 
      stopTimeout: 2, 
      stopOnTerminate: false,
      startOnBoot: true, 
      heartbeatInterval: 60, 
      preventSuspend: true, 
      forceReloadOnBoot: true, 
      logMaxDays: 2, 
      maxDaysToPersist: 2, 
      //maxRecordsToPersist: 20, 
      schedule: [ 
        '2-6 8:00-18:00'  // Mon-Fri: 8:00am to 6:00pm
      ],
      geofenceProximityRadius: 500,
      geofenceInitialTriggerEntry: true, 
      trackingMode: 'location'
    }, (state) => {
      this.bgGeo.start();
    });
```

## Expected Behavior
I would expect the email to be sent. I am not able to determine the file size from my phone.

## Actual Behavior
The email sits in my phone's outbox. I am sending via Gmail.

## Steps to Reproduce
1. Start Application - this initlizes the standard stuff above
2. Click send email which kicks off 
```
var bgGeo = this.bgSvc.getBgGeo();
bgGeo.emailLog(SUPPORT_EMAIL);
```

## Context
N/A

## Debug logs
I would provide these if I knew of a means to gather the logs from my phone. This is the reason I am creating this issue.

**Comment by christocracy** [comment]
Could be the attachment is too large.  I'll have to have the code gzip the log.  Android does this already.

**Comment by jimgibbs** [comment]
Thanks for a quick turn around. Let me know when that change has been released and I will verify.

Thanks!!

**Comment by christocracy** [comment]
This is implemented in the premium version now.  It will appear here when I next push the latest stable release.

Attached is an example log file gzipped by the iOS plugin.

[background-geolocation-test.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1156706/background-geolocation-test.log.gz)

**Comment by jimgibbs** [comment]
Thank you for a quick turn around!

Question - How should I uncompress this file? I am using a Mac and I cannot
uncompress the file.

**Comment by christocracy** [comment]
I initially attached the wrong file.  Try this one:
[background-geolocation-test-3.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1156735/background-geolocation-test-3.log.gz)

**Comment by jimgibbs** [comment]
SWEET! Thank you!
