### ISSUE TITLE
Stop working on application terminate in Android

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [transistorsoft/cordova-background-geolocation-lt#404]
Plugin stop working on application termination, even using setting   stopOnTerminate: false, myurl
 triggers until app is open, when I close it or terminate,  I stop getting the locations logged in my db.

## Your Environment
* Plugin version:
* Platform:   Android
* OS version:7.0
* Device manufacturer / model:One Plus 3 

## Expected Behavior
 Plugin should work even when the application is terminated or closed  

## Actual Behavior
  Application does not work on application terminate 

 
## Context
Here is my config settings
 this.bgGeo.configure({
      debug: true,
      desiredAccuracy: 10,
      distanceFilter: 10,
      stationaryRadius: 2,
      url: 'myurl',
      autoSync: true,
      stopOnTerminate: false,
    }, (state) => {
      // 4. Start the plugin.
      this.bgGeo.start();
    });

**Comment by christocracy** [comment]
Logs please.

**Comment by christocracy** [comment]
Closed for failing to provide logs.
