### ISSUE TITLE
Location updates are not triggered as frequent as they should

### ISSUE THREAD

**Issue by gitstc** [transistorsoft/cordova-background-geolocation-lt#406]
I am trying to implement background Geolocation tracking in my app 

## Your Environment
* Plugin version:  cordova-background-geolocation-lt- 2.7.4
* Platform:  iOS 
* OS version:  10
* Device manufacturer / model:  iphone 6
* Cordova version ('cordova -v'): 4.0.0
* Cordova platform version ('cordova platform ls`): 3.8.0
* Plugin config: default config

## Expected Behavior
The devices  sending location updates automatically to the server.

## Actual Behavior

 The devices are not sending location updates automatically to the server.The devices usually send updates once upon launching the app and once upon killing the app. On iOS, no updates are sent when the user is moving and on Android devices, the plugin would send a couple of updates but the Latitude and Longitude are the same although the device's location is constantly changing.

## Steps to Reproduce
`try {
	bgGeo = window.BackgroundGeolocation;

	if (bgGeo) {
		bgGeo.on('location', function(position) {
			//bgGeo.finish();
		}, function(error) {
		   
		});
		
		bgGeo.on('motionchange', function(isMoving) {
				 console.log'- onMotionChange: ', isMoving);
		});
		
		bgGeo.on('geofence', function(geofence) {
		  console.log('- onGeofence: ', geofence.identifier, geofence.location);
		});
		
		bgGeo.on('http', function(response) {
			 console.log('http success: ', response.responseText);
		}, function(response) {
			console.log('http failure: ', response.status);
		});
		
		bgGeo.configure({
											desiredAccuracy: 1000,
											stationaryRadius: 25,
											distanceFilter: 10,
										   // disableElasticity: true, 
											locationUpdateInterval:1,
										   // minimumActivityRecognitionConfidence: 1,
										   // fastestLocationUpdateInterval:1,
										   // activityType: 'Other',
											activityRecognitionInterval: 1000,
											 stopTimeout: 5,
											startOnBoot: true,
											debug: true, 
											//debug: false, 
											stopOnTerminate: false,
										   // forceReloadOnLocationChange: false, 
											useSignificantChangesOnly: false,
											url: "192.168.1.1:5050/updateLocation2",
											method: "POST",
											autoSync: true,
											httpRootProperty: ".", 
											locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>,"speed":<%= speed %>}',
										}, function(state) {
											if (!state.enabled) {
												bgGeo.start(function() {
												  console.log('- BackgroundGeolocation tracking started');
												});
											}
										});
	}
} catch (ex) {
	console.log("Location Service error " + ex);
}`
## Context
I am trying to implement background geolocation tracking in my app but the devices are not sending location updates automatically to the server.
The devices usually send updates once upon launching the app and once upon killing the app. On iOS, no updates are sent when the user is moving and on Android devices, the plugin would send a couple of updates but the Latitude and Logitude are the same although the device's location is constantly changing.

**Comment by christocracy** [comment]
Please don't ignore the issue template.  Edit your post and provide the following information:



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
Closed for failure to provide issue template.
