### ISSUE TITLE
I use  stopOnTerminate: false, but it can not get  update on server . When app in foreground or background it work like a charm but can not update when app completely close.. 

### ISSUE THREAD

**Issue by Swapniltdatalogy** [transistorsoft/cordova-background-geolocation-lt#407]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Are you aware that your Cordova JavaScript app is completely terminated when the user terminates an Android app?  If you're hoping to run JavaScript code after app terminate, that's not going to happen.

Only the plugin's native Android service remains running.

**Comment by christocracy** [comment]
Closed for lack of feedback.
