### ISSUE TITLE
Artifice to increase precise geofences

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#409]
It is known that the system of both android and ios do not offer high precision in geofences, but with its plugin activated in background with Start in aggressive mode, and "preventSuspend: true", and the app closed; Is that in this case the native location services could take advantage of the requests of continuous location data requests made by its plugin, resulting in a precise geofence event (10 meters for example) and not 200 meters as the ios system says in Documentation. In this case would we have a geofence drive as accurate as if it were a foreground app doing "watchPosition"?

**Comment by christocracy** [comment]
preventSuspend does **not** assist with geofence-triggering.  iOS *always* requires the device move ~200 meters outside geofence before it triggers, regardless if the plugin is currently requesting locations.

**Comment by dbessa1** [comment]
And on android, would this be possible?

**Comment by christocracy** [comment]
Android tends to fire geofence exit soon than iOS.  The following is typical:

(red dots represent geofence exit)
![](https://www.dropbox.com/s/thil9nkgcpapsko/Screenshot%202017-07-21%2017.50.01.png?dl=1)

**Comment by dbessa1** [comment]
Thank you, but it was not clear to me if my continued requests for GPS location queries would help the android system fire a geofence more accurately. In ios I already understood that it does not help.

**Comment by christocracy** [comment]
You will never get a geofence exit at 10 meters.

**Comment by christocracy** [comment]
Try testing with the SampleApp.  It has great features for visualizing geofence hits.

**Comment by christocracy** [comment]
Closed for lack of feedback.
