### ISSUE TITLE
Background geolocation not getting updates

### ISSUE THREAD

**Issue by scrawner** [transistorsoft/cordova-background-geolocation-lt#41]
I set debut to true and changePace(true) on app pause.
It's ok when I put the app in bacgkround I receive the notification saying that agressive monitoring has been engaged. Then I get updates for my location only 10 minutes later or so.
When I get a location update I receive like 8 or more notifications from plugin saying MOVING and LOCATION UPDATE... but it takes like 10 minutes after I put the app in background to get the first location update.

I dont know what I'm doing wrong!

```
var successFn = function(location, taskid){
   //now i removed the post method to my server in order to test in debug mode
    bgGeo.finish(taskid);
}
bgGeo.configure(successFn, function(){
    //does nothing for now
}, {
    desiredAccuracy: 10,
    distanceFilter: 20,
    stationaryRadius: 20,
    debug: true,
    stopOnTerminate: true
});
```

![background_print](https://cloud.githubusercontent.com/assets/16047563/11442661/5aaf03b4-94fe-11e5-9f85-3825f9f77264.png)

**Comment by christocracy** [comment]
When in doubt, use highest power geolocation `desiredAccuracy: 0`.

iOS typically requires 2-3 blocks of movement to engage aggressive monitoring.  This depends upon the GPS / network environment.  Make sure you have Wifi enabled on the device.

[iOS Behaviour](https://github.com/transistorsoft/cordova-background-geolocation-lt#behaviour)

**Comment by scrawner** [comment]
Actually I dont think the accuracy could be the problem.
And I travelled much more than 3 blocks. That was 10 minutes by car like 10 blocks or even more to get the first location update. Then after a long time (10 mins or so again) to get another update...then after a long time another update.
When I began to use the plugin I used to get updates every 30-40-60 secs (not an exact timing as its distance-based)

**Comment by christocracy** [comment]
Does it work in Simulator?

**Comment by scrawner** [comment]
Im not using Simulator to test it. The strange thing is that it was really awesome then suddenly it started acting like this.

**Comment by christocracy** [comment]
are you using the latest version from master?

I'll boot up teh SampleApp from scratch and test it out.

**Comment by scrawner** [comment]
I am using phonegap build so i believe its the latest version

**Comment by christocracy** [comment]
so you've pushed the repo as your own private plugin?

What is the specific plugin ID you're using?  is is
com.transistorsoft.cordova.background-geolocation?

On Fri, Nov 27, 2015 at 11:28 AM, scrawner <notifications@github.com> wrote:

> I am using phonegap build so i believe its the latest version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/41#issuecomment-160170784>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by scrawner** [comment]
cordova-plugin-background-geolocation
from npm

**Comment by scrawner** [comment]
hmmmm.... well thought... 
i used to use com.transistorsoft.cordova.background-geolocation

May they have some difference?

**Comment by christocracy** [comment]
Don't use that.  That's my old [deprecated version](https://github.com/christocracy/cordova-plugin-background-geolocation).  You are not using the superior code from the repo you're commenting on here.

I don't support that old npm version anymore.  I haven't updated that code in over a year.

In order to use the plugin from this repo, you need to follow the steps [here](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/PhoneGap-Build-Installation)

**Comment by christocracy** [comment]
They have immense differences.  Not even close.

On Fri, Nov 27, 2015 at 11:36 AM, scrawner <notifications@github.com> wrote:

> hmmmm.... well thought...
> i used to use com.transistorsoft.cordova.background-geolocation
>
> May they have some difference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/41#issuecomment-160171811>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by scrawner** [comment]
Alright... I will do that.
Thanks for your support. After I test it I come back here to tell if it worked!

**Comment by scrawner** [comment]
Can I still use this?
<plugin name="org.transistorsoft.cordova.background-geolocation" source="pgb" />
are you supporting this?

**Comment by scrawner** [comment]
Can I still use this:
`<plugin name="org.transistorsoft.cordova.background-geolocation" spec="0.3.5" source="pgb" />`
Are you supporting this?

**Comment by christocracy** [comment]
I wouldn't.  I don't support it anymore.  I only support the Premium
version in the repo we're talking on.

com.transistorsoft.cordova.background-geolocation

On Fri, Nov 27, 2015 at 11:57 AM, scrawner <notifications@github.com> wrote:

> Can I still use this?
>
> are you supporting this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/41#issuecomment-160175092>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by scrawner** [comment]
Chris, I tried to use in my config
`<gap:plugin name="com.transistorsoft.cordova.background-geolocation" />`
says plugin unsupported: com.transistorsoft.cordova.background-geolocation 

I also tried 
`<gap:plugin name="cordova-background-geolocation-lt" source="npm" />`
phonegap builds but after installing on iOS my app stops

the only one that works for me is
`<gap:plugin name="org.transistorsoft.cordova.background-geolocation" />`
but the issues keeps the same: long time to get location updates

I made changes to the code but its quite the same as before

```javascript
    if(bgGeo===false){
            bgGeo = window.plugins.backgroundGeoLocation;
            var bgLocationSuccess = function(location){
                /*var jqxhr = $.post(SERVER_URL+'/atualiza_posicao.php?fbid='+FBID, {
                   latitude: location.latitude,
                   longitude: location.longitude,
                   speed: location.speed,
                   accuracy: location.accuracy,
                   tipo: 'background_tracking',
                }, function(){
                    //its ok
                }).always(function(){
                    bgGeo.finish();
                });*/
                bgGeo.finish();
            };
            var bgLocationError = function(error){
                //does nothing for now
            };
            bgGeo.configure(bgLocationSuccess, bgLocationError, {
                desiredAccuracy: 10,
                stationaryRadius: 10,
                distanceFilter: 20,
                debug: true,
                stopOnTerminate: true
            });
            bgGeo.start();
        }
```

I'm starting to wonder if this issue may has something to do with my iOS version which is 9.1

**Comment by christocracy** [comment]
The steps to install my plugin are clearly defined here.  Read them closely
and don't skip anything.  Do it exactly as documented. L

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/PhoneGap-Build-Installation

On Saturday, November 28, 2015, scrawner <notifications@github.com> wrote:

> Chris, I tried to use in my config
> <gap:plugin name="com.transistorsoft.cordova.background-geolocation" />
> says plugin unsupported: com.transistorsoft.cordova.background-geolocation
>
> I also tried
> <gap:plugin name="cordova-background-geolocation-lt" source="npm" />
> phonegap builds but after installing on iOS my app stops
>
> the only one that works for me is
> <gap:plugin name="org.transistorsoft.cordova.background-geolocation" />
> but the issues keeps the same: long time to get location updates
>
> I made changes to the code but its quite the same as before
>
>     if(bgGeo===false){
>             bgGeo = window.plugins.backgroundGeoLocation;
>             var bgLocationSuccess = function(location){
>                 /*var jqxhr = $.post(SERVER_URL+'/atualiza_posicao.php?fbid='+FBID, {                   latitude: location.latitude,                   longitude: location.longitude,                   speed: location.speed,                   accuracy: location.accuracy,                   tipo: 'background_tracking',                }, function(){                    //its ok                }).always(function(){                    bgGeo.finish();                });*/
>                 bgGeo.finish();
>             };
>             var bgLocationError = function(error){
>                 //does nothing for now
>             };
>             bgGeo.configure(bgLocationSuccess, bgLocationError, {
>                 desiredAccuracy: 10,
>                 stationaryRadius: 10,
>                 distanceFilter: 20,
>                 debug: true,
>                 stopOnTerminate: true
>             });
>             bgGeo.start();
>         }
>
> I'm starting to wonder if this issue may has something to do with my iOS
> version which is 9.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/41#issuecomment-160318747>
> .
>


-- 
Snet form Gmail Mobile

**Comment by scrawner** [comment]
Looks like its a paid solution. Was checking on how to add a private plugin on PGB and I would have to pay for it. Am I right?
The strange thing is that everything was working so good. Now its not!
