### ISSUE TITLE
Not getting location when i move more than 3 km in iphone version 10.2 ,its working like charm in android and lowest version of IOS like 9.3.5 .

### ISSUE THREAD

**Issue by Swapniltdatalogy** [transistorsoft/cordova-background-geolocation-lt#412]
## Your Environment
* Plugin version:2.7.4
* Platform: iOS or Android
* OS version:IOS and Android
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config
 {
   activityRecognitionInterval = 10000;
   activityType = Other;
   autoSync = 1;
   autoSyncThreshold = 0;
   batchSync = 0;
   debug = 1;
   desiredAccuracy = 0;
   desiredOdometerAccuracy = 10;
   disableElasticity = 0;
   disableMotionActivityUpdates = 0;
   disableStopDetection = 0;
   distanceFilter = 10;
   enabled = 0;
   extras =    {
   };
   geofenceInitialTriggerEntry = 1;
   geofenceProximityRadius = 1000;
   geofenceTemplate = "";
   headers =    {
   };
   heartbeatInterval = 60;
   httpRootProperty = location;
   httpTimeout = 60000;
   isHeartbeatEnabled = 0;
   isMoving = 0;
   locationAuthorizationAlert =    {
       cancelButton = Cancel;
       instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
       settingsButton = Settings;
       titleWhenNotEnabled = "Background location is not enabled";
       titleWhenOff = "Location services are off";
   };
   locationAuthorizationRequest = Always;
   locationTemplate = "";
   locationTimeout = 60;
   locationsOrderDirection = ASC;
   logLevel = 5;
   logMaxDays = 7;
   maxBatchSize = "-1";
   maxDaysToPersist = 3;
   maxRecordsToPersist = "-1";
   method = POST;
   minimumActivityRecognitionConfidence = 70;
   odometer = 0;
   params =    {
       userid = "<null>";
   };
   pausesLocationUpdatesAutomatically = 1;
   preventSuspend = 0;
   schedule =    (
   );
   schedulerEnabled = 0;
   startOnBoot = 1;
   stationaryRadius = 25;
   stopAfterElapsedMinutes = "-1";
   stopDetectionDelay = 0;
   stopOnStationary = 0;
   stopOnTerminate = 0;
   stopTimeout = 5;
   trackingMode = 1;
   url = "http://www.umbra.org/umbra-app/umbra-api/11umbra-testing-api.php?callback=JSON_CALLBACK¶m=trackUserLocation&user_id=0&lat=0&longni=0";
   useSignificantChangesOnly = 0;
}
[background-geolocation.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1169815/background-geolocation.zip)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Logs please.  See [Debugging wiki](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

**Comment by christocracy** [comment]
Show me the Javascript code you're using.

**Comment by Swapniltdatalogy** [comment]
var bgGeo = window.BackgroundGeolocation;
    //alert('hi');
    //This callback will be executed every time a geolocation is recorded in the background.

    var callbackFn = function(location, taskId) {
        var coords = location.coords;
         lat    = coords.latitude;
         lng    = coords.longitude;
    };

  

    bgGeo.on('heartbeat', function(params) {
        var d = new Date();
        var datetime = d.getFullYear() +"-"+("00" + (d.getMonth() + 1)).slice(-2) + "-" + ("00" + d.getDate()).slice(-2)  + " " + ("00" + d.getHours()).slice(-2) + ":" +("00" + d.getMinutes()).slice(-2) + ":" +("00" + d.getSeconds()).slice(-2);
        window.localStorage.setItem('devicedate',datetime);
       
        bgGeo.getCurrentPosition(function(location, taskId) {
           lat =location.coords.latitude;
           lat =location.coords.longitude;
          // alert(JSON.stringify(location));
            bgGeo.finish(taskId);
        });

    });
    var failureFn = function(errorCode) {
       
    }


    bgGeo.getLog(function(log) {
        bgGeo.emailLog("swapnilt@datalogysoftware.com");
  
        });
    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);
    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function(isMoving) {
    //  alert('- onMotionChange: '+ isMoving);
    });
    // Fired whenever a geofence transition occurs.
    bgGeo.on('geofence', function(geofence) {
      alert('- onGeofence: '+ geofence.identifier + geofence.location);
    });
    // Fired whenever an HTTP response is received from your server.
    bgGeo.on('http', function(response) {
    // alert('http success: '+ response.responseText);

    }, function(response) {
      //alert('http failure: '+ response.status);
    });
    
    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 25,
        disableElasticity: false,
        geofenceProximityRadius:1000,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval:10000,
        deferTime:0,
        stopTimeout: 5,
        //stopOnStationary:true,
        // Activity Recognition config
        activityRecognitionInterval: 10000,
        triggerActivities: 'on_foot,walking,running,in_vehicle,on_bicycle',
       
        // Application config
        debug: true,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        logLevel :5,
        startOnBoot: true,
        //preventSuspend: true,
        // HTTP / SQLite config
        url: "http://www.umbra.org/umbra-app/umbra-api/11umbra-testing-api.php?callback=JSON_CALLBACK&param=trackUserLocation&user_id=0&lat="+lat+"&longni="+lng,
        method: "POST",
        autoSync: true,
        desiredOdometerAccuracy: 10,
        maxDaysToPersist: 3,
       // heartbeatInterval: 60,
        foregroundService:true,
        params: {   
           // "auth_token": "maybe_your_server_authenticates_via_token_YES",
            "userid":window.localStorage.getItem('user_id'),
           // "devicedate":window.localStorage.getItem('devicedate')
        }

    }, function(state) {
       // alert('start one two three'+state.enabled);
        if (!state.enabled) {
              bgGeo.start();
              
        }
    });

**Comment by christocracy** [comment]
Show me your `config.xml` block for the plugin.

**Comment by christocracy** [comment]
This is not  how you do `emailLog`:
```javascript
bgGeo.getLog(function(log) {
    bgGeo.emailLog("swapnilt@datalogysoftware.com");

    });
```

`#emailLog` *automatically* does a `#getLog`.  You just need to:
```javascript
bgGeo.emailLog(yourEmailAddress);
```

**Comment by Swapniltdatalogy** [comment]
<gap:plugin name="cordova-background-geolocation-lt" source="npm" />

**Comment by christocracy** [comment]
See [Phonegap Build Setup](https://github.com/transistorsoft/cordova-background-geolocation-lt#phonegap-build) in addition to [Configuring the Plugin](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)

Your logs show that the plugin is not have **Location Authorization** from user so is not even starting.

**Comment by Swapniltdatalogy** [comment]
Location Authorization is working but i wrote email code  before Authorization that's why  its happening.

**Comment by christocracy** [comment]
show me more logs.  Your attached log is useless.

**Comment by Swapniltdatalogy** [comment]
[background-geolocation.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1170038/background-geolocation.zip)
can you please check this

**Comment by christocracy** [comment]
When you see this in your logs, you're not reading the **important** documentation about event-handlers and the necessity to call `bgGeo.finish(taskId)` to signal completion of your event-handler.

For example, see the [location](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-integer-taskid-the-taskid-used-to-send-to-backgroundgeolocationfinishtaskid-in-order-to-signal-completion-of-your-callbackfn) event.

```javascript
bgGeo.on('location', function(location, taskId) {
  console.log('location: ', location);
  bgGeo.finish(taskId);  // <-- DO NOT NEGLECT THIS
});
```

Whenever an `event` provides you a `taskId`, you **MUST** `bgGeo.finish(taskId)` when your callback is complete.

```
2017-07-24 19:24:56.166 ✅ [BackgroundTaskManager stopBackgroundTask] 611 OF (
    22,
    24,
    25,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    58,
    59,
    60,
    62,
    64,
    66,
    72,
    74,
    76,
    78,
    80,
    82,
    84,
    86,
    88,
    90,
    92,
    94,
    96,
    98,
    100,
    102,
    104,
    106,
    108,
    110,
    112,
    114,
    116,
    118,
    120,
    122,
    124,
    126,
    128,
    130,
    132,
    134,
    136,
    138,
    140,
    142,
    144,
    146,
    148,
    150,
    152,
    154,
    156,
    158,
    160,
    162,
    164,
    166,
    168,
    170,
    172,
    174,
    176,
    178,
    180,
    182,
    184,
    186,
    188,
    190,
    191,
    192,
    193,
    194,
    195,
    196,
    198,
    199,
    200,
    201,
    202,
    203,
    204,
    205,
    206,
    207,
    208,
    210,
    212,
    214,
    216,
    218,
    220,
    222,
    224,
    226,
    228,
    230,
    232,
    234,
    236,
    238,
    240,
    242,
    243,
    244,
    245,
    246,
    247,
    248,
    250,
    252,
    254,
    256,
    258,
    260,
    262,
    264,
    266,
    268,
    270,
    272,
    274,
    276,
    278,
    280,
    282,
    284,
    286,
    288,
    290,
    292,
    294,
    296,
    298,
    300,
    302,
    304,
    306,
    308,
    310,
    312,
    314,
    316,
    319,
    322,
    324,
    326,
    327,
    328,
    330,
    332,
    334,
    336,
    338,
    340,
    342,
    344,
    346,
    348,
    351,
    352,
    354,
    355,
    356,
    358,
    360,
    362,
    364,
    366,
    368,
    370,
    372,
    374,
    376,
    378,
    380,
    382,
    384,
    386,
    387,
    388,
    389,
    390,
    392,
    394,
    396,
    398,
    400,
    402,
    404,
    407,
    408,
    413,
    414,
    416,
    418,
    420,
    422,
    424,
    426,
    428,
    430,
    432,
    434,
    436,
    438,
    440,
    442,
    444,
    446,
    448,
    450,
    452,
    454,
    458,
    460,
    462,
    464,
    466,
    468,
    470,
    472,
    474,
    476,
    478,
    480,
    482,
    484,
    486,
    488,
    490,
    492,
    494,
    496,
    498,
    500,
    502,
    504,
    506,
    508,
    510,
    512,
    514,
    516,
    518,
    520,
    522,
    524,
    526,
    528,
    530,
    532,
    534,
    536,
    538,
    540,
    542,
    544,
    546,
    548,
    550,
    552,
    554,
    556,
    558,
    560,
    562,
    564,
    566,
    568,
    570,
    572,
    574,
    576,
    578,
    580,
    582,
    584,
    586,
    588,
    590,
    592,
    594,
    596,
    598,
    602,
    604,
    606,
    608,
    610,
    611
)
```

**Comment by christocracy** [comment]
Closed for lack of feedback.
