### ISSUE TITLE
Improvement : Allow internationalization of messages

### ISSUE THREAD

**Issue by pvdyck** [transistorsoft/cordova-background-geolocation-lt#419]
<variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
    <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
    <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />

Are not internationalized ... is there any easy way to do it ? Thanks

**Comment by christocracy** [comment]
What messages?

**Comment by pvdyck** [comment]
Sorry ....

=> 
  <variable name="LICENSE" value="9714bf7d289bb9f54f601d1fa629eeeb5f08473a59287150756a1aef27f9f1f5" />
        <variable name="BACKGROUND_MODE_LOCATION" value="&lt;string&gt;location&lt;/string&gt;" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />

**Comment by christocracy** [comment]
That's the whole point of exposing these `<variable />` in your `config.xml`:  *so you can modify them as you wish*.

[Configuring the plugin](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)

**Comment by pvdyck** [comment]
Yes, indeed, thank you but when your application supports multiple langages there is no way to display a internationalized version of the message.

So right now the solution is to display a multilingual and very short message (there is not much space) 

Ideally, it should be possible to specify the language of the message and switch accordingly.

**Comment by christocracy** [comment]
This is not a plugin problem or even a Cordova problem.  This is an iOS problem.

You need to search "ios internationalize plist strings"

The `<variable />` you configure in `LOCATION_ALWAYS_USAGE_DESCRIPTION` is ultimately creating strings in the iOS app's `.plist` file.

![](https://www.dropbox.com/s/fkoyd5plpvyhnwa/Screenshot%202017-07-29%2010.56.38.png?dl=1)
