### ISSUE TITLE
Status available indicating the app restart e.g. after the device reboot?

### ISSUE THREAD

**Issue by ToniKorin** [transistorsoft/cordova-background-geolocation-lt#420]
H Scott,

First of all, thanks for this great plugin!

Is there any way to get information from your plugin (in iOS), if the app has been restarted (e.g. because of a device boot or a memory cleaning)?

I'd just like to avoid unnecessary javascript executions when the app is restarted into the background.

**Comment by christocracy** [comment]
There's a 3rd party plugin you can use to determine if your app is in the background.

https://github.com/leomylonas/cordova-plugin-applicationstate

**Comment by ToniKorin** [comment]
Great, thanks.
