### ISSUE TITLE
Plugin is not working in ios/andriod production build

### ISSUE THREAD

**Issue by vedantterkar** [transistorsoft/cordova-background-geolocation-lt#421]
When I tested this plugin on android and ios (debug build) it works fine:
1. It first asks for location permission, then for motion detection permission and then It triggers .on("location") call back.

But when I do prod android/ios build for testing purpose:
It first asks for location permission, then for motion detection permission and then It  doesn't trigger
.on("location")

## Your Environment
* Plugin version:2.7.3
* Platform: Android/IOS (Ionic app using typescript)
* OS version: Android 4.0/ Ios 10
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):
* Plugin config
```
config = {
      debug: false,
      desiredAccuracy: 0,
      distanceFilter: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      stopDetectionDelay: 3600000,
      heartbeatInterval: 60,
      locationUpdateInterval: 60 * 1000,
      stationaryRadius: 0,
      activityType: "AutomotiveNavigation",
      preventSuspend: true,
      activityRecognitionInterval: 0,
      disableStopDetection: false,
      stopTimeout: 3600000,
      foregroundService: true,
      notificationTitle: "Location Tracking"
    }
```
## Expected Behavior
Plugin should behave in the same way as of debug build.

## Actual Behavior
It looks like .on("location") call back is never executed in prod build.
**Also in IOS: The app is not listed in settings page to allow Location Permissions**

## Steps to Reproduce

1. ionic build ios/android works fine
But app generated using
2. ionic cordova build android/ios --prod --release
Doesn't seems to be working

## Debug logs
Can't get debug logs from prod build

Can you please look into this and let me know on what needs to be done in order to make it work?

**Comment by christocracy** [comment]
Did you purchase a license?

**Comment by vedantterkar** [comment]
No. I was just testing the behavior for prod build.

**Comment by vedantterkar** [comment]
Also Can you please tell why:

In IOS The app is not listed in settings page to allow Location Permissions?

Here is my config xml snippet, If it helps:

```
.....
  <plugin name="cordova-background-geolocation-lt" spec="^2.7.3">
        <variable name="BACKGROUND_MODE_LOCATION" value="location" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="This app requires background tracking to be enabled" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="This app requires background tracking to be enabled" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>
.....
```

**Comment by christocracy** [comment]
See the top of README.

🆕 The Android plugin requires purchasing a license. However, it will work for DEBUG builds. It will not work with RELEASE builds without purchasing a license.

**Comment by christocracy** [comment]
Why did you do this:
```
<variable name="BACKGROUND_MODE_LOCATION" value="location" />
```

You need to go read the docs for [that config](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/README.md) **VERY** carefully.  

Are you reading anything?

**Comment by vedantterkar** [comment]
Thanks. @christocracy , Sorry My bad.

Appreciate the help. Still I wonder why it works on IOS debug build though :).

Thanks a lot :+1: .

**Comment by christocracy** [comment]
I have no idea
