### ISSUE TITLE
notificationSmallIcon doesn't work after license key.

### ISSUE THREAD

**Issue by bhargavkonkathi** [transistorsoft/cordova-background-geolocation-lt#423]
## Your Environment
* Plugin version: 2.7.4
* Platform: Android
* OS version: 6.0 and above
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):  android 6.2.3, ios 4.4.0
* Plugin config

## Expected Behavior
Notification small icon should be displayed in status bar after including license key.

## Actual Behavior
Notification small icon is missing after including license key. But it was working before without license key.

## Steps to Reproduce

1. Set small notification icon without license
2. Set small notification icon with license

So after including is there any way to show notification small icon in status bar. 
Thanks.

**Comment by christocracy** [comment]
Yes, I made a change in 2.7.4 to change the `NOTIFICATION_PRIORITY` to `NOTIFICATION_PRIORITY_MIN`, hiding the icon.  

I've since made it configurable with new `notificationPriority` config.  It will be available in the next latest stable release.

**Comment by christocracy** [comment]
Install latest `2.7.6`.

**Comment by bhargavkonkathi** [comment]
By installing Version 2.7.6 issue got resolved.
Thanks.
