### ISSUE TITLE
Location Updates Firing just after running config?

### ISSUE THREAD

**Issue by dogofpavlov** [transistorsoft/cordova-background-geolocation-lt#425]
Is the plugin suppose to fire off location updates after just running the config? I'm not directly running the "start" method nor am I manually getting a location with "getCurrentPosition".

## Your Environment
* Plugin version: 2.7.4
* Platform: iOS
* OS version: 10.3.3
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): 4.4.0
* Plugin config

## Expected Behavior
Shouldn't I not get location updates until I ask?

## Actual Behavior
after I run the "configure", the .on("location"... handler is firing.

I am not executing the code how the example shows checking if it's not enabled, then starting the service.

**Comment by christocracy** [comment]
Yes, the plugin persists it's enabled state and will auto-start itself after you execute #configure

**Comment by christocracy** [comment]
See state.enabled in callback to #configure
