### ISSUE TITLE
Inconsistent ENTER/EXIT geofence server notifications 

### ISSUE THREAD

**Issue by darrinholst** [transistorsoft/cordova-background-geolocation-lt#426]
## Your Environment
* Plugin version: 2.7.5
* Platform: iOS
* OS version: 10.3.3
* Device manufacturer / model: iPhone 6s
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): ios 4.4.0
* Plugin config
``` js
{
      stopOnTerminate: false,
      logLevel: 5,
      url: `${ENV.rootUrl}/api/timeclock/entries`
}
```

## Expected Behavior

ENTER and EXIT server events should be sent when a geofence is entered or exited.

## Actual Behavior

ENTER and EXIT events are not consistently sent.

## Steps to Reproduce

1. Add a geofence
1. Drive out of the geofence

## Context

`fd5729f1-1c92-4ff1-aec1-2d1aa344ad24` in the log is the geofence in question. For example, I get the following...

    2017-08-08 16:38:31.623 🔴-[TSGeofenceManager locationManager:didExitRegion:] fd5729f1-1c92-4ff1-aec1-2d1aa344ad24

which I would expect the EXIT geofence event to be sent to the server, but I get nothing. I was driving at that time. Walking out of the geofence a few hours earlier worked. Not sure if how fast you exit the geofence matters or not.

When I returned I get...

    2017-08-08 17:09:25.175 🎾 -[TSGeofenceManager startMonitoringGeofence:] fd5729f1-1c92-4ff1-aec1-2d1aa344ad24

but it appears I was already inside that geofence when it got re-enabled.

Are there some settings that I need to adjust to make this work? Possible increasing `geofenceProximityRadius` so the geofences start getting monitored sooner to catch the ENTRY? I'm not sure what's going on with the EXIT though since it did appear to fire at the os level...just didn't get the server notification.

## Debug logs

[background-geolocation.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1209794/background-geolocation.txt)

**Comment by christocracy** [comment]
Are you not field testing with debug: true, so you can *hear* geofence triggers in real time?

In my experience, geofences are very consistent.

**Comment by christocracy** [comment]
I'm on vacation, I'll look at logs when I return

**Comment by darrinholst** [comment]
Yes, running with debug on. I wish I had your consistency. Enjoy the 🏖.

**Comment by christocracy** [comment]
You should try testing with my sample app, which I use for development.  It has great geofence trigger map notifications and syncs data to my server.  Try it.

**Comment by darrinholst** [comment]
Could this be an issue caused by an app update? (testflight in this instance). When I originally reported this I was updating the app pretty frequently to get new changes. Since then development has flattened out and it's been very consistence. I updated it again last night while in the geofence and when I left today I see the same situation...which is the logs indicate that the geofence exit notification was received, but I get no HTTP message. Here are the logs from that time frame...

geofence id - `01f7494d-5186-4a74-9b96-544f0bfa2337`

[background-geolocation.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1235740/background-geolocation.txt)

**Comment by chilimix** [comment]
Hey Darrinholst,

We have the same exact issue. What version of the plugin are you using?
We are using 2.8.5 and we get the events on the phone but the sever doest recieve the information.

We testet with the sample app and it seems to work, but as far as we know the sample app runs version 2.7.1

**Comment by chilimix** [comment]
We found out why it didnt work for us.

We had set maxDaysToPersist=0, for some reason we get positions with this setting but not geofence events. We changed it to 1 and then we started getting the geofence events to the server as well.

**Comment by christocracy** [comment]
This is why jumping into an issue saying “me too”, that you also post your configuration.

To the database, everything is a location.  A geofence is a location with geofence data attached.

**Comment by chilimix** [comment]
Will try to remenber that :)

But that still does not explain why regular locations was inserted into the local SQL Lite DB and not the geofence locations with the maxDaysToPersist=0 setting.
