### ISSUE TITLE
App terminate 10 seconds after background-geolocation services starts.

### ISSUE THREAD

**Issue by mario-berardo** [transistorsoft/cordova-background-geolocation-lt#431]
## Your Environment
* Plugin version:2.7.6
* Platform: Android
* OS version: 4.1.3
* Device manufacturer / model: Samsung Galaxy S3 GT i9300
* Cordova version (`cordova -v`): 6.2.3
* Cordova platform version (`cordova platform ls`):
* Plugin config
* OBS : java jdk1.8.0_112

	BackgroundGeolocation.configure({
		desiredAccuracy: 0,
		distanceFilter: 0,
		locationUpdateInterval:30000,
		url:'http://www.devicecontrols.com.br/rast/services/ws_gravaloc_t.php',
		extras:'OBJETO:3'
	}, function(state) {
	  if (!state.enabled) {  // <-- current state provided to callback
		BackgroundGeolocation.start();
	  }
	});

## Expected Behavior
App continous geolocation monitoring. I think maybe related with issue #430 .

## Actual Behavior
Notification about "Licence failed - Demo Version " and app terminates aproxmately 10 seconds after background geolocation service starts .

## Steps to Reproduce

1. in my app have a start button that only do this 
	BackgroundGeolocation.configure({
		desiredAccuracy: 0,
		distanceFilter: 0,
		locationUpdateInterval:30000,
		url:'http://www.devicecontrols.com.br/rast/services/ws_gravaloc_t.php',
		extras:'OBJETO:3'
	}, function(state) {
	  if (!state.enabled) {  // <-- current state provided to callback
		BackgroundGeolocation.start();
	  }
	});

2.
3.
4.

## Context
My app will get the current geolocation and call a PHP webservice to store LAT and LONG it in a database, each 30s time interval,  and need to run in background for to free th use of another apps in the phone.

## Debug logs
adb logcat 

E/ClockAlarmWidget(26869): [AlarmWidgetIdManager] getListItem() : itemIndex=1, widgetID:1
E/dalvikvm(29130): Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.zzo.zzy
E/dalvikvm(29130): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.internal.zzbgy.zzf
E/Watchdog( 2265): !@Sync 1490
E/AndroidRuntime(29130): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime(29130): java.lang.IllegalArgumentException: invalid value for field
E/AndroidRuntime(29130):        at java.lang.reflect.Field.setField(Native Method)
E/AndroidRuntime(29130):        at java.lang.reflect.Field.set(Field.java:588)
E/AndroidRuntime(29130):        at com.transistorsoft.locationmanager.settings.Settings.b(Unknown Source)
E/AndroidRuntime(29130):        at com.transistorsoft.locationmanager.settings.Settings.load(Unknown Source)
E/AndroidRuntime(29130):        at com.transistorsoft.locationmanager.settings.Settings.configure(Unknown Source)
E/AndroidRuntime(29130):        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$c.run(Unknown Source)
E/AndroidRuntime(29130):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime(29130):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime(29130):        at java.lang.Thread.run(Thread.java:856)
E/android.os.Debug( 2265): !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error
E/Launcher(22945): Error finding setting, default accessibility to not found: accessibility_enabled
E/webview (29130): Error: WebView.destroy() called while still attached!
E/MtpService( 8976): In MTPAPP onReceive:android.intent.action.BATTERY_CHANGED
E/MtpService( 8976): battPlugged Type : 2
E/dalvikvm(30171): Could not find class 'X.AYb', referenced from method com.facebook.messenger.app.MessengerApplication.k
E/dalvikvm(30187): Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.zzo.zzy
E/dalvikvm(30171): Could not find class 'com.facebook.tigon.tigonvideo.TigonVideoConfig', referenced from method com.facebook.video.vps.VideoPlayerService$5.a
E/dalvikvm(30171): Could not find class 'X.43I', referenced from method com.facebook.video.vps.VideoPlayerService$5.b
E/dalvikvm(30171): Could not find class 'X.43I', referenced from method com.facebook.video.vps.VideoPlayerService$5.b
E/dalvikvm(30171): Could not find class 'X.3vT', referenced from method com.facebook.video.vps.VideoPlayerService$5.a
E/dalvikvm(30187): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.internal.zzbgy.zzf
E/WifiHW  ( 2265): ##################### set firmware type 0 #####################
E/WifiHW  ( 2265): ##################### set firmware type 0 #####################
E/WifiHW  ( 2265): ##################### set firmware type 0 #####################

**Comment by christocracy** [comment]
Read the docs for #extras.

It requires an {}.  Not a String

**Comment by mario-berardo** [comment]
Ok, Sorry, its an object.
I need to send the "veichle ID" to my PHP webservice.
Wht is the best way to to this ? Using the "params" options ?

Thanks.

2017-08-11 14:56 GMT-03:00 Chris Scott <notifications@github.com>:

**Comment by christocracy** [comment]
- #params is applied to each http request.
- #extras is applied to each location

**Comment by mario-berardo** [comment]
Im trying compile a new version. Do you if is going something wrong woth
geadle today ? Its giving me a message that "its not possible do start
daemon" and i didnt make any modification at my machine.

Em 11/08/2017 15:47, "Chris Scott" <notifications@github.com> escreveu:

**Comment by christocracy** [comment]
>"its not possible do start daemon"

You have problems in your development environment.  I have no idea.

**Comment by mario-berardo** [comment]
Sorry ... graddle .. im hurting cordova. Each day have a different kind of
error with compiler.

Em 11/08/2017 18:45, "Mario Cesar Berardo" <mario.berardo72@gmail.com>
escreveu:

**Comment by mario-berardo** [comment]
Are you using Linux or windows ? What OS is better to cordova and react
native development ?

Em 11/08/2017 18:48, "Mario Cesar Berardo" <mario.berardo72@gmail.com>
escreveu:

**Comment by christocracy** [comment]
I use Mac.  Cordova works on Mac, Linux and Windows.

That being said, I would personally avoid Windows.

**Comment by mario-berardo** [comment]
Very complicated and detailed enviroment configuration. Its free but lost
so much time. Time is money.
Thanks.

Em 11/08/2017 18:56, "Chris Scott" <notifications@github.com> escreveu:
