### ISSUE TITLE
Getting License Validation Failure - License purchased in Dec

### ISSUE THREAD

**Issue by stib** [transistorsoft/cordova-background-geolocation-lt#434]
## Your Environment
* Plugin version: 2.7.4
* Platform: Android
* OS version: 5.1
* Device manufacturer / model: Motorola (Also tried on old Nexus)
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): android 6.0.0
* Plugin config
```
  <plugin name="cordova-background-geolocation-lt">
    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="XXX"/>
    <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="XXX"/>
    <variable name="MOTION_USAGE_DESCRIPTION" value="XXX"/>
    <variable name="cordova-background-geolocation-license" value="KEY_VALUE HERE"/>
  </plugin>
```

## Expected Behavior
Not get License Validation Failure

Purchased the license in Dec. Doing some Beta testing on PlayStore. Recently moved to plugin version 2.7.4 from earlier 2.2.0. I don't recall seeing this validation failure earlier.

## Actual Behavior
Get License Validation Failure.

## Steps to Reproduce
Deploy the app either directly to a device from my machine or through Playstore

## Debug logs
Can generate the logs if needed but hopefully it's a straightforward answer from the details above

**Comment by christocracy** [comment]
When in doubt, see README for changes:

https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/README.md#large_blue_diamond-configuring-the-plugin

**Comment by christocracy** [comment]
And be careful to closely read the instructions:

⚠️ To apply changes to these <variable />, you must remove/re-add the plugin (append --nosave when removing the plugin)

$ cordova plugin remove cordova-background-geolocation-lt --nosave
$ cordova plugin add cordova-background-geolocation-lt

**Comment by stib** [comment]
For anyone else who may encounter this issue, had to change the key name from "cordova-background-geolocation-license" (in 2.2.0) to "LICENSE" in 2.7.4 and that worked.

Thanks @christocracy

**Comment by christocracy** [comment]
Btw, customers should not use this Public repo.  You should be using the private repo for latest updates.  This repo gets only latest stable release.
