### ISSUE TITLE
Location update delayed

### ISSUE THREAD

**Issue by joe69** [transistorsoft/cordova-background-geolocation-lt#437]
[background-geolocation-18.08.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1234472/background-geolocation-18.08.zip)

## Your Environment
* cordova-background-geolocation-lt": "^2.7.4"
* IOS 
* OS version: 10.3.3
* Device manufacturer / model: Iphone
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): Ionic 3.7.0
* Plugin config

  this.bgGeo = (<any>window).BackgroundGeolocation;

      this.onHeartbeat = this.onHeartbeat.bind(this);
      // 2. Listen to events
      this.bgGeo.on('location', this.onLocation.bind(this));
      this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
      this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
      this.bgGeo.on('geofence', this.onGeofence.bind(this));
      this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));
      this.bgGeo.on('heartbeat', this.onHeartbeat);
    //  this.bgGeo.on('heartbeat', this.onHeartbeat.bind(this));
      // 3. Configure it.
      this.bgGeo.configure({
        debug: true,
        desiredAccuracy: 0,
        distanceFilter: 10,
        locationUpdateInterval: 1000,
        foregroundService: true,
        stationaryRadius: 25,
        logLevel: 5,
        heartbeatInterval: 5,
        preventSuspend: true,
        url: 'http://pr366.webofficeserver.info/api/location',
        params: {
            equusi_id: localStorage.getItem("equusi_id"),
            identifier : localStorage.getItem("identifier"),
            name: localStorage.getItem("track"),
		        user: localStorage.getItem("user"),
		        horse: localStorage.getItem('horse')
        },
        autoSync: true,
        headers: { Authorization: "Bearer "+localStorage.getItem("token") }
      }, (state) => {
        // 4. Start the plugin.
        if (!state.enabled) {
          this.bgGeo.start();
        }
      });

## Expected Behavior

We would need the tracking right from the beginning, means once when the function is called. 

## Actual Behavior

At the  moment it happens, that the first location update is sent after around 400-500 meter (maybe a bit more). Once the first update is sent, we receive location-updates frequently and this is working fine (approx every 10 meters). 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
This is the core [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

**Comment by christocracy** [comment]
What do you think the `heartbeat` event does?

**Comment by joe69** [comment]
i want only execute every 5 seconds:
 BackgroundGeolocation.getCurrentPosition(function(location) {
    console.log('- current location: ', location);
  });

**Comment by christocracy** [comment]
That's your responsibility to execute `#getCurrentPosition` in the `heartbeat` callback.  The plugin itself does **not** turn on location-services during `heartbeat` events.

That's a **very** bad idea to attempt to fetch a location every 5 seconds while the device is stationary.  Why would you do that?  Do you not care about battery life?

On iOS, the operating system *will* pause the `heartbeat` event if the device is unplugged from power and the device is stationary.  If the device is moved even slightly or the user unlocks their phone and begins using it (not necessarily your app), the `heartbeat` will resume.
