### ISSUE TITLE
How to only use Always or Never, remove "In Use"

### ISSUE THREAD

**Issue by jonathanhollander** [transistorsoft/cordova-background-geolocation-lt#438]
In my app I need to set the Location to be Always only, and never "In Use"

I've seen many apps that do this, but I don't know how to do it with this plugin.

For example: https://mackuba.eu/images/posts/ios11-location/ios10-privacy-2.png They only list 2 options (Never/Always) "In use" does not appear. 

Is there any way to do this with this plugin? If I leave the "LOCATION_IN_USE_DESCRIPTION" blank it still shows.

**Comment by christocracy** [comment]
Delete `Privacy - Location When In Use Usage Description` from your `.plist` in XCode.

The plugin automatically adds this key so you'll have to manually delete it each time the plugin is added.

![](https://dl.dropboxusercontent.com/s/qt2wp3s12i0vyb1/Screenshot%202017-08-18%2011.06.00.png?dl=1)

However, iOS 11 has changed everything about this:  Apps will now be **forced** to offer both.

**Comment by jonathanhollander** [comment]
Thank you
