### ISSUE TITLE
Debug Sounds - Won't Stop when set to false

### ISSUE THREAD

**Issue by dan003400** [transistorsoft/cordova-background-geolocation-lt#44]
debug is set to false, but I am still getting the sounds.

Thanks,

Dan

**Comment by christocracy** [comment]
really?

**Comment by christocracy** [comment]
Are you using the latest version?

On Thursday, December 10, 2015, dan003400 <notifications@github.com> wrote:

> debug is set to false, but I am still getting the sounds.
>
> Thanks,
>
> Dan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/44>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Hello?  Can I close this?

**Comment by dan003400** [comment]
Yes I believe I was able to solve this issue. Thanks. The library was not being initialized with the configurations I thought I was setting.
