### ISSUE TITLE
schedule configs

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#441]
When I make a new schedule setting, do the previous settings remain?

**Comment by christocracy** [comment]
Example?

**Comment by dbessa1** [comment]
bgGeo.setConfig({
  schedule: [
    '1-7 17:30-23:00'
  ]
})

bgGeo.setConfig({
  schedule: [
    '1-7 09:10-23:00'
  ]
})

The two schedules followed above would be equivalent to:
bgGeo.setConfig({
  schedule: [
    '1-7 17:30-23:00',
    '1-7 09:10-23:00'
  ]
})

Or does the last erase the first?

**Comment by christocracy** [comment]
When you `#setConfig` *any* param, that param is overwritten.

Just as if you:
```javascript
var schedule = '1-7 17:30-23:00';
.
.
.
schedule = '1-7 09:10-23:00';
```
