### ISSUE TITLE
Advice on usage on Android

### ISSUE THREAD

**Issue by skrpc** [transistorsoft/cordova-background-geolocation-lt#445]
I have a scenario that I am not sure how to handle and it is holding me back from buying the plugin, can you please advise ?

Android device using #url to sync with my central server.

I want to record the full track locally on an android device so I can draw the track on a map (map stored locally on device so no network connection required to show maps).  Equally this is a tracking app so that users centrally can see current location of device in real time assuming the device has a network connection therefore I want to use autoSync = true to submit points to server in real time

1. App starts location services with stopOnTerminate = false
2. Network connection is available and app is in foreground/suspended (i.e. not terminated)
3. Location service captures points and sends to server as well as calling javascript callback in app
4. Javacsript callback records points locally in apps own db for app to draw track
5. Android terminates my app but location services still running (since stopOnTerminate - false) and network connection still available
6. Location service captures points and autoSync sends to server but now does not call javascript callback in my app as it is terminated so points not stored in apps own db
7. Device now moves to where there is no network connection so offline
8. Location service captures points but cannot send to server as no network connection so points stay in location services local db
9. User starts up my app and app asks location services for points in database
10. App wants to draw track on map

What happens to points submitted to server in step 6, as I understand it the autoSync will have deleted them from the location services local db therefore will not be included in the points returned in step 9.  As the device is now in an area with no network connection I cannot check with my server to get those missing points.

How can I draw a full track in step 10 if I am missing the points submitted to the server in step 6 but not sent to my app as it was terminated ?

As I read it this is not an issue with iOS because my app will not be terminated and the javascript callback on sync() will ALWAYS be called regardless of the state of my app.

Thanks,

**Comment by christocracy** [comment]
>What happens to points submitted to server in step 6, as I understand it the autoSync will have deleted them from the location services local db therefore will not be included in the points returned in step 9

Correct.  The plugin *strongly* desires an empty database.  You should not rely on the plugin as your data-store.

Fetch locations from your server.

**Comment by christocracy** [comment]
>As I read it this is not an issue with iOS because my app will not be terminated and the javascript 

False.  iOS can and will terminate idle apps in the background when memory is required.

**Comment by christocracy** [comment]
However, idle apps terminated by the OS will be automatically rebooted if the device is detected to be moving.  Tracking will not suffer due to OS terminating an app in background.

**Comment by christocracy** [comment]
Anyway, if you boot the app with no network connection, you're not even going to be able to render a map, so it's pointless to even care about rending points in that case.

Just fetch positions from your own server.

**Comment by skrpc** [comment]
My apps will display maps whilst offline, one of the apps I am looking to adding tracking to is the British Columbia Search and Rescue Association (BCSARA) Field Guide app and if you wish to download you will see that it has the option to download offline map files in order to display maps when there is no network connection.

As the users are Search and Rescue members in the field it is useful if they can see their full track on the map so they can verify the track they took in order to verify they have completed their search mission whether there is a network connection or not before they return to base.  This does not appear to be possible with the location services plugin because if the Android app was terminated whilst there was a network connection there would be some points on the server only that cannot be retrieved if the user restarts the app to view their track when there is no network connection.

When there is a network connection it is useful for the command team located at the Incident Command Post to be able to track their members locations, I accept when there is no network connection this cannot be done but there are many times when there are network connections or teams are moving in and out of cell service.

Can you explain this response a bit more please

> "However, idle apps terminated by the OS will be automatically rebooted if the device is detected to be moving. Tracking will not suffer due to OS terminating an app in background."

as according to the documentation 

> "It is highly recommended to let the plugin manage uploading locations to your server, particularly for Android when configured with stopOnTerminate: false, since your Cordova app (where your Javascript lives) will terminate — only the plugin's native Android background service will continue to operate, recording locations and uploading to your server. The plugin's native HTTP service is better at this task than Javascript Ajax requests, since the plugin will automatically retry on server failure."

I understand this to mean that my app will not be rebooted as it is not idle it is terminated, the only idle app is the location services plugin which I assume is like a headless app/service and what you are referring to as an idle app and therefore tracking will not suffer.

Thanks again,
Scott
