### ISSUE TITLE
Android app crashes just after installing the plugin

### ISSUE THREAD

**Issue by HamzaLJ** [transistorsoft/cordova-background-geolocation-lt#451]
## Your Environment
* Plugin version: cordova-background-geolocation-lt 2.8.2 "BackgroundGeolocation"
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Motorola (Moto C)
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):   android 6.2.3
* Plugin config

## Expected Behavior

It should run smoothly without crashing the app

## Actual Behavior

After installing the plugin, the app crashes right away after opening, it does not even show the splash screen.

## Steps to Reproduce

1. Install the plugin
2. Run it on Android

## Context

I have an Ionic 3 app where I am trying to get drivers locations on the background

**Comment by christocracy** [comment]
What am I supposed to say without logs?

```
$ adb logcat
```

**Comment by HamzaLJ** [comment]
Here is what I got : 

`08-27 16:21:09.509 234-493/? E/MAL-RDS:  (  rds_ru_3gpp_status_ind, 1638) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8
08-27 16:21:09.516 1204-1472/? E/NetworkController.MobileSignalController(1): mCurrentState.dataConnected = false; mCurrentState.connected = true; mDataState = 2; isIMS = false; mDataConnectionState = 0
08-27 16:21:09.705 1709-7758/? E/ctxmgr: [WorkManager]Ongoing task not found: UserVelocityProducer_receive
08-27 16:21:09.749 1709-1709/? E/ctxmgr: [PlaceFenceHelper]NearbyBuffer is null!
08-27 16:21:09.782 12657-19312/? E/PlaceStateUpdater: Received no places
08-27 16:21:10.194 19316-19316/? E/PQ: [PQ][PQWhiteList] libwlparser.so is absent
08-27 16:21:10.497 265-637/? E/VT: [SRV] [VT THREAD] [VT_Bind] des = volte_imsvt1 Fail to connect . retry count: 105224
08-27 16:21:10.705 19348-19348/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.onadiDriver.app, PID: 19348
                                                   java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbo; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbo' appears in /data/app/com.onadiDriver.app-1/base.apk:classes8.dex)
                                                       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5976)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5545)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5484)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:203)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6253)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
08-27 16:21:12.681 1117-1680/? E/Sensors: handleToDriver handle(0)`

**Comment by christocracy** [comment]
You're using multiple plugins importing different version of `play-services`.  This plugin is one.

```
$ cordova plugins
```

**Comment by HamzaLJ** [comment]
Here they are : 

> cordova-background-geolocation-lt 2.8.2 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-fetch 5.0.0 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova.plugins.diagnostic 3.6.5 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.0.0 "PushPlugin"

**Comment by HamzaLJ** [comment]
I've solved it by setting the version of `play-services` to `11.0.1` to all the other plugins I am importing.
Thanks anyway!

**Comment by christocracy** [comment]
I've forked and expanded upon a plugin which allows you to override every google-api dependency of *every* plugin in your app.

[`cordova-google-api-version`](https://github.com/transistorsoft/cordova-google-api-version).

Don't look at the README, none of it applies.

Forget tweaking individual plugins:  You'll just do this (it's **not on npm yet**):

I have to make a small change to `background-geolocation's `play-services-location` version, making it `11.+`

```
$ cordova plugin add cordova-google-api-version.git --variable GOOGLE_API_VERSION=11.2.0
```
(replace `11.2.0` with *any* desired version)

**Comment by christocracy** [comment]
Ok, try this out:  #453
