### ISSUE TITLE
failure background geolocation is running in evaluation mode

### ISSUE THREAD

**Issue by ArnoMyOnlinePresence** [transistorsoft/cordova-background-geolocation-lt#454]
We are trying to test the plugin before we buy it, but we can't get it to work at all. Every time our app starts we get the following message.:
failure background geolocation is running in evaluation mode

## Your Environment
* Plugin version: latest
* Platform: Android
* OS version: Android O
* Device manufacturer / model: emulator
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): 7.0.1
* Plugin config
this.bgGeo.configure({
      debug: true,
      desiredAccuracy: 0,
      distanceFilter: 10,
      locationUpdateInterval: 1000,
      fastestLocationUpdateInterval: 1000,
      stationaryRadius: 25,
      startOnBoot: false,
      url: this.apiService.BASEAPIURL + "panic/update",
      Headers: this.apiService.getAuthHeaderOptions(),
      autoSync: true,
      foregroundService: true,
      stopOnTerminate: false
    }, (state) => {
      // 4. Start the plugin.
      if (!state.enabled) {
        this.bgGeo.start(function () {
          console.log('- BackgroundGeolocation tracking started');
        });
      }
    });

## Expected Behavior
It should as i understand it work as long as its not a release version

## Actual Behavior
Getting failure background geolocation is running in evaluation mode the moment we open our app

**Comment by christocracy** [comment]
This is normal.  Are you not "evaluating" the product before deciding to purchase?

The plugin is saying:  "you don't have a license key, but we're running in DEBUG build, so I'll let you evaluate the product."
