### ISSUE TITLE
window.BackgroundGeolocation is undefined

### ISSUE THREAD

**Issue by PerryRylance** [transistorsoft/cordova-background-geolocation-lt#456]
## Your Environment
* Plugin version: 2.8.0
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Samsung SM-A520F
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): 

Installed platforms:
  android 6.2.3
  browser 4.1.0
  ios 4.4.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  webos ~3.7.0
  windows ~5.0.0

* Plugin config

## Expected Behavior
window.backgroundGeolocation should be defined

## Actual Behavior
window.backgroundGeolocation is undefined

## Steps to Reproduce
1. Fresh install (or use sample app as a basis)
2. Run phonegap platform add android
3. Run phonegap serve, it installs the plugin
4. Add script in index.html to log all property names in window, there are no property names containing "geolocation"

## Context
Installation

NB: I have omitted this: &lt;variable name="LICENSE" value="YOUR_LICENSE_KEY" /&gt; as I read you can trial the plugin in debug mode. Am I required to get a license key before this plugin will work?

**Comment by PerryRylance** [comment]
I found a similar issue which had been closed where someone else has provided this startup example

https://github.com/rishantagarwal/CordovaBackgroundGeolocationStartingUpExample

window.BackgroundLocation was undefined in this example too

**Comment by christocracy** [comment]
I just created a simple Cordova app and it works.

```bash
$ cordova -v
7.0.1
$ cordova create ./Foo foo.bar
$ cordova plugin add cordova-background-geolocation-lt
$ cordova platform add android
```
*www/index.js*
```javascript
var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },
    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        alert("BackgroundGeolocation?: " + window.BackgroundGeolocation);
    }
}
```

```bash
$ cordova run android
```
![](https://dl.dropboxusercontent.com/s/xgvgcxdt6jwsla4/Screenshot%202017-09-01%2009.05.41.png?dl=1)

**Comment by christocracy** [comment]
You have something wrong on your end.

**Comment by christocracy** [comment]
You know that `phonegap serve` is for booting your app in a browser?

The plugin **doesn't work in the browser**.

**Comment by PerryRylance** [comment]
If that's the case it really should be documented

I used cordova run --device instead and it runs fine

**Comment by christocracy** [comment]
It's no different than trying to use the Camera API in the web browser.  That won't work either.

This plugin is dependant upon a variety of native APIs, including the accelerometer.  Web browsers do not have these APIs.
