### ISSUE TITLE
The plugin is capturing wrong coords

### ISSUE THREAD

**Issue by HamzaLJ** [transistorsoft/cordova-background-geolocation-lt#458]
I am trying to capture the coords, store them in an array, then using this last I draw a polyline over the map.

## Your Environment
* Plugin version: 2.8.3
* Platform: **Android**
* OS version: 7.0.1
* Device manufacturer / model: Motorola Moto C
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):   android 6.2.3

**Config**

```
    this.bgGeo.configure({
     debug: true,
     desiredAccuracy: 0,
     distanceFilter: 0,
     locationUpdateInterval:5000,
     stopOnTerminate:false
   }, (state) => {
     // 4. Start the plugin.
     this.bgGeo.start();
   });
```

## Expected Behavior
It should capture the coords correctly

## Actual Behavior
It seems that it does not capture the coords correctly

## Steps to Reproduce

1. Capture the coords
2. Store them in an array
3. Draw a polyline using the coords stored

You may check the drawn polyline in attachments.

![screen shot 2017-09-03 at 22 35 03](https://user-images.githubusercontent.com/17797937/30006813-4db0d5cc-90f9-11e7-9c7f-555ffd0f52fe.jpg)

**Comment by HamzaLJ** [comment]
Any sign of life here...?

**Comment by christocracy** [comment]
I don't understand what you're trying to show here.  Logs please

**Comment by christocracy** [comment]
you haven't provided all the requested information from the issue template.  Where's your config?

**Comment by HamzaLJ** [comment]
I've updated my post with the config.
I have a driver app where I am capturing coords each 5 seconds, store them in an array, then at the end of the trips that polyline is drawn over the map.

I don't have any logs for that. However, I have the array of generated coords, let me know if you need it.

**Comment by christocracy** [comment]
I still have no idea what your problem is or what you're trying to show here.  Obviously you're simulating location.

**Comment by HamzaLJ** [comment]
I am trying to get the latitude and longitude of the user each 5 seconds, store all of these coordinates in an array, at the end of the trip I represent the coordinates stored in that array with a polyline on Google Maps.

But it seems, somehow that the plugin is not obtaining the right coordinates (P.S. it seems that the issues shows up when being on long routes +10km)

**Comment by christocracy** [comment]
[Here's a ~300km round-trip](http://tracker.transistorsoft.com/a3a231c3?device=Cordova-a76924c11115eb8b&end=2017-9-5&start=2017-9-2) I did this weekend with my Google Pixel running Android 8 beta.

**Comment by christocracy** [comment]
Closed for lack of feedback.
