### ISSUE TITLE
Can't DEBUG while using mock location

### ISSUE THREAD

**Issue by JeremyLaffard** [transistorsoft/cordova-background-geolocation-lt#459]
## Your Environment
* Plugin version: 2.8.3
* Platform: **Android**
* OS version: 7.0
* Device manufacturer / model: Samsung S7
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): Android 6.2.3
* Plugin config : 
`     this.bgGeo.configure({
        debug: true,
        desiredAccuracy: 0,
        distanceFilter: 0,
        locationUpdateInterval:7500,
        stopOnTerminate:false,
        setLogLevel: 4,
        stopTimeout:50000
   }, (state) => {
     // 4. Start the plugin.
          this.bgGeo.start();
   });`

## Expected Behavior
It should update location in background each 7.5 seconds.

## Actual Behavior
Once I start the app, it shows from the logs that it gets the current location, but after that the location gets never updated knowing that I am using "Lockito" to mock the location and update it on the go.

## Steps to Reproduce

1. Using Lockito set a start/end location. 
2. Run the app with the configurations above.

**Comment by christocracy** [comment]
It's important to be aware that the plugin doesn't *listen* to locations until it determines the device is *moving*.

When simulating with Lockito, you have to either execute `BackgroundGeolocation.changePace(true)` or literally shake the device until the plugin thinks the device is moving.

**Comment by JeremyLaffard** [comment]
I've used `BackgroundGeolocation.changePace(true)` it didn't worked, I also shaked the device many times, nothing happened... How can I debug ?

**Comment by christocracy** [comment]
See wiki:
https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging

**Comment by PerryRylance** [comment]
I had the same issue, using changePace made the location update consistantly. However, I have to call getCurrentPosition as well in order for the http requests to fire

**Comment by christocracy** [comment]
@PerryRylance you do not have to call #getCurrrntPosition to "get http requests to fire".

**Comment by christocracy** [comment]
@JeremyLaffard Update?

**Comment by christocracy** [comment]
Closed for lack of feedback.
