### ISSUE TITLE
BackgroundGeoLocation error Class not found

### ISSUE THREAD

**Issue by roysG** [transistorsoft/cordova-background-geolocation-lt#46]
Hi, 
i am using android cordova 5.0, and i get this error message.

why?

code:

 // Get a reference to the plugin.
    var bgGeo = window.BackgroundGeolocation;

    /**
     * This callback will be executed every time a geolocation is recorded in the background.
     */
    var callbackFn = function(location, taskId) {
      console.log('start location');
      var coords = location.coords;
      var lat    = coords.latitude;
      var lng    = coords.longitude;

      // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
      // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
      setTimeout(function() {
        console.log('finished');
        bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
      }, 1000);
    };

    var failureFn = function(error) {
      console.log('BackgroundGeoLocation error', error);
    }

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure(callbackFn, failureFn, {
      // Geolocation config
      desiredAccuracy: 0,
      stationaryRadius: 50,
      distanceFilter: 50,
      disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
      locationUpdateInterval: 5000,
      minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change
      fastestLocationUpdateInterval: 5000,
      activityRecognitionInterval: 10000,
      stopDetectionDelay: 1,  // Wait x minutes to engage stop-detection system
      stopTimeout: 2,  // Wait x miutes to turn off location system after stop-detection
      activityType: 'AutomotiveNavigation',

      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
      forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
      forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
      stopOnTerminate: false,              // <-- [Android] Allow the background-service to run headless when user closes the app.
      startOnBoot: true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.

      // HTTP / SQLite config
      url: globalVars.apiUrl + '/liveLocation',
      method: 'POST',
      batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
      headers: {
        "X-FOO": "bar"
      },
      params: {
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
    });

    // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
    bgGeo.start();

**Comment by christocracy** [comment]
This free version is [iOS-only](https://github.com/transistorsoft/cordova-background-geolocation-lt#premium-version-ios).  You have to [buy a license](http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium) to get access to Android.

**Comment by roysG** [comment]
if i will run it in debug mode, does it work?

**Comment by christocracy** [comment]
Debug mode for Android?  There is no Android code in this repo at all.  This repo is iOS only.

**Comment by roysG** [comment]
yes i saw it now, thanks anyway, the price is a little bit expensive :(

**Comment by roysG** [comment]
maybe if i was some trial version to test, it was good for me.

**Comment by christocracy** [comment]
You can install the SampleApp on your device from play store.

https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic


On Wednesday, December 30, 2015, roysG <notifications@github.com> wrote:

> maybe if i was some trial version to test, it was good for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/46#issuecomment-168047260>
> .
>


-- 
Snet form Gmail Mobile
