### ISSUE TITLE
Tracking seems erratic compared to other apps

### ISSUE THREAD

**Issue by PerryRylance** [transistorsoft/cordova-background-geolocation-lt#461]
Please see this image http://imgur.com/a/u6AHn

The blue line was recorded by my app using this plugin

The red line was recorded on the same phone in the same conditions with the Strava app

Here are my options:

```
url: this.getURL(),
method: "POST",
params: this.getBackgroundGeolocationPOSTParams(),
distanceFilter: 1,
foregroundService: true,
// debug: true,
stopOnTerminate: false,
fastestLocationUpdateInterval: 1000
```

Is this something I can smooth out by tweaking the apps settings?

I've done a bit of reading on the subject and I understand that GPS coordinates are already Kalman filtered and that post processing is unlikely to improve the data, so I don't imagine other apps implement their own smoothing.

**Comment by christocracy** [comment]
Other apps [*certainly are* implementing their own smoothing algorithms](https://www.hypertrack.com/blog/2016/09/11/our-framework-for-real-time-filtering-of-location-streams/), including *on the server*.

**Comment by christocracy** [comment]
>Is this something I can smooth out by tweaking the apps settings?

No.  Check your device settings:
- Location is set to "High Accuracy"
- Battery:  Power Saving is no engaged.
- Wifi is enabled.

**Comment by christocracy** [comment]
For reference, here's a [300km round trip last weekend](http://tracker.transistorsoft.com/a3a231c3?device=Cordova-a76924c11115eb8b&end=2017-9-5&start=2017-9-2) 
- Google Pixel @ 8.0.0

```
desiredAccuracy: 0,
distanceFilter: 50
```
