### ISSUE TITLE
Javascript run in background with only #StartGeofences?

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#464]
In iOS, with stopOnTerminate: false, if I run a #Start, my javascript keeps working even if the user closed the app.
Does javascript also continue working if I run #StartGeofences instead of #Start? If yes, would it be necessary to have a geofence event for the javascript to start?
Thank you!

**Comment by christocracy** [comment]
I'm not sure what you're trying to ask.

"Background" and "terminated" are two completely different states.

When your app is in the background with #startGeofences, iOS has *suspended* your app, just like closing your laptop.  Your JavaScript is asleep until a geofence event occurs, when iOS will awaken your sleeping app (like opening your laptop)  for exactly 30 seconds.

If the user terminated the app with stopOnTerminate: false, iOS will boot your app in the background (including your JavaScript) when a geofence event occurs, automatically putting your app to sleep in the background after 30 seconds.

**Comment by dbessa1** [comment]
Thank you, I get it!
In the second case, with stopOnTerminate: false, after the geofence submission, (where my application starts); when will the app be closed again? Will the plugin wait for me to run a #Stop?

**Comment by dbessa1** [comment]
Some words may be strange because I'm using the Portuguese to English translator...

**Comment by christocracy** [comment]
>In the second case, with stopOnTerminate: false, after the geofence submission, (where my application starts); when will the app be closed again? Will the plugin wait for me to run a #Stop?

- The OS can terminate any app at any time if memory is required by other app running in the foreground.  No, the plugin not wait for you to call `#stop`.

**Comment by christocracy** [comment]
Geofences are managed by OS.  Geofences **never** stop being monitored, in spite of app terminate / device reboot.  When a geofence fires and your app is not running, the OS will reboot your app to service the event.

**Comment by dbessa1** [comment]
It turns out that for energy saver I want my app to be terminated a certain time after it has been opened by an input event in a geofence (when my app has already done the necessary services related to such geofence). This is why I think I'm going to run a #Stop in the output of the same geofence, and then I'm going to run a #StartGeofences so that the geofences are re-monitored with my app closed. Do you think that way I will achieve success in energy saving? (ensuring that my app stays open only within the geofences)

**Comment by christocracy** [comment]
If your app is using `#startGeofences`, its energy-use is not worth worrying about.

The biggest consumer of energy is HTTP requests and constant location-updates.

**Comment by dbessa1** [comment]
it's exactly these two things my app does uninterruptedly while it's open ...
