### ISSUE TITLE
Notification permission request

### ISSUE THREAD

**Issue by zettvs** [transistorsoft/cordova-background-geolocation-lt#466]
My app is only working with user geolocation and is not sending any push/local notifications to the user. However, on first invocation the plugin asks permission to send Notifications. I tried to find where I can disable Notification permission request, but have not been able to do that. Please could you advise?

**Comment by christocracy** [comment]
debug: false.

Obviously you won't submit an app to production with debug: true.

**Comment by zettvs** [comment]
Thanks Chris. 

Of course, `debug` was already set to `false`, and it turned out it was `cordova-plugin-badge` that asked for notification permission – it's invoked in the `cordova-background-geolocation-lt`'s start callback in my app...
