### ISSUE TITLE
Issue when exiting a geofence after a long period of time

### ISSUE THREAD

**Issue by alexbarnsley** [transistorsoft/cordova-background-geolocation-lt#468]
During my testing, I'm entering a geofence when I get home (around 6pm). I then leave my home around 8:20am the next day. The problem I'm having is when I come to leave the geofence (I haven't done so since I got there), there is no exit event being fired. I don't experience the same issues when testing normally (E.g. lost of in/out events during the day). It feels like it's an issue with overnight, or for long periods. I don't believe it's doze because the logs indicate it's still doing stuff in the background around and after that time. I am using the phone during these times.

## Your Environment
* Plugin version: 2.8.3
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: OnePlus 3
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): 6.0.0
* Plugin config:

```
desiredAccuracy: 0,
stationaryRadius: 25,
locationUpdateInterval: 10000,
fastestLocationUpdateInterval: 5000,
activityType: 'AutomotiveNavigation',
activityRecognitionInterval: 10000,
stopTimeout: 5,
stopOnTerminate: false,
startOnBoot: true,
preventSuspend: true,
heartbeatInterval: 60,
foregroundService: true,
forceReloadOnGeofence: true,
forceReloadOnBoot: true,
notificationTitle: "blurb",
notificationText: "blurb",
notificationPriority: -2, 
```

## Expected Behavior
An exit event should be fired when leaving the geofence

## Actual Behavior
An exit event is not fired when leaving the geofence

## Debug logs
I can send details of `BackgroundGeolocation().getLog(console.log)` - let me know where I can send this (private geolocation information inside)

**Comment by christocracy** [comment]
Why are you worried about geolocation data?  Who cares?  Yes, I need logs.  email them to `chris@transistorsoft.com` if you're paranoid.

**Comment by MichaelChopsWood** [comment]
![desktop-notification](https://user-images.githubusercontent.com/15216493/30438651-a7284342-9969-11e7-881d-be4d2abdb3e6.jpg)

**Comment by christocracy** [comment]
Now that I have your logs, what time if of interest to you?

**Comment by alexbarnsley** [comment]
The time I left the geofence was "09-14 08:18" I'd say. There's not really any activity around that time either side of then. I notice there's a location `Location-provider change: false` at roughly 07:02 but I didn't touch any GPS settings. Had plenty of battery too. 

Actually I just noticed an Enter event at `09-13 22:15:25.703` which has no Exit event prior to that, if that's of any relevance?

**Comment by christocracy** [comment]
Is it the geofence: `8008` we're dealing with?
```
09-14 07:19:12.468 DEBUG [a a] 
╔═════════════════════════════════════════════
║ TSGeofenceManager found 1/2 within 1000 meters
╠═════════════════════════════════════════════
╟─ 🎾  8008
╚═════════════════════════════════════════════
```

Yes, for some reason, the OS reacted here in the same manner as if you disabled "Location" in settings screen, detecting a change in "Location Provider", determining it to be disabled:

```
09-14 07:02:16.720 INFO [BackgroundGeolocation$n onReceive] 
╔═════════════════════════════════════════════
║ Location-provider change: false
╠═════════════════════════════════════════════
╟─ GPS: false
╟─ Network: false
.
```
As a result, the `GeofencingAPI` fires the error code `1000` ([`GEOFENCE_NOT_AVAILABLE`](https://developers.google.com/android/reference/com/google/android/gms/location/GeofenceStatusCodes.html#GEOFENCE_NOT_AVAILABLE))

```
09-14 07:02:16.787 WARN [GeofenceService onHandleIntent] 
  ⚠️  Geofencing error1000
```

Just over an hour later, Location-services comes back online:
```
09-14 08:18:04.975 INFO [BackgroundGeolocation$n onReceive] 
╔═════════════════════════════════════════════
║ Location-provider change: true
╠═════════════════════════════════════════════
╟─ GPS: true
╟─ Network: true
```

**Comment by christocracy** [comment]
Curiously, just before Location-services came back online, the activity-recognition-system detected the device was `in_vehicle` where attempted to start tracking:
```
09-14 08:18:01.267 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (82%)
09-14 08:18:01.281 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:18:01.291 INFO [BackgroundGeolocationService a] 
  🔵  setPace: false → true
09-14 08:18:01.299 INFO [BackgroundGeolocationService j] 
  🔴  Stop heartbeat
09-14 08:18:04.975 INFO [BackgroundGeolocation$n onReceive] 
╔═════════════════════════════════════════════
║ Location-provider change: true
╠═════════════════════════════════════════════
╟─ GPS: true
╟─ Network: true
```
However, Location-services didn't re-enable until 3 seconds later.

The logs follow with a series of `onActivityRecognitionResult`.  The plugin should have been recording locations here:
```
09-14 08:18:09.228 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (74%)
09-14 08:18:09.239 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:18:24.000 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (66%)
09-14 08:18:24.014 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:18:34.593 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (82%)
09-14 08:18:34.609 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:18:44.691 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (100%)
09-14 08:18:44.709 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:18:54.836 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (100%)
09-14 08:18:54.852 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:19:05.113 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (100%)
09-14 08:19:05.128 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:19:15.195 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (100%)
09-14 08:19:15.211 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:19:25.299 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (100%)
09-14 08:19:25.314 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:19:35.386 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (89%)
09-14 08:19:35.399 DEBUG [BackgroundGeolocation isMainActivityActive] YES
09-14 08:19:45.476 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (100%)
.
.
.
```
I think there's a bug here.  The plugin needs to have a bit of intelligence in its `providerchange` handler.  However, I don't think that related to your initial issue.

Do you know exactly if you were *inside* or *outside* of geofence `8008` when ` Location-provider change: true` occurred?

**Comment by christocracy** [comment]
Actually, I think there's another way that `Location-provider change: false` could occur:
- In `Settings->Location`:  **Battery saving**
- Wifi disabled

What is your `Settings->Location` set to?
- High Accuracy
- Battery saving
- Device only

**Comment by alexbarnsley** [comment]
Hi @christocracy, apologies for the delay.

The geofence in question is 8008. I believe I was in the geofence at the time of `Location-provider change: true` - 8:18 however, I was just leaving at that time. The "in_vehicle" was probably accurate at that point. Also, I guess my GPS will have been better as I'd have left the house. I don't use WiFi at home as 4G is usually better for me.

My GPS is set to "High Accuracy".

Have I missed any of your questions?

I can try using WiFi overnight to see if that is related due to poor GPS, but I won't be certain until Monday morning about 10am (BST) when I get in the office to check. I just thought it was quite strange how an exit event wasn't fired at all, even after entering a different geofence later on in a completely different location.

**Comment by christocracy** [comment]
Geofence triggering is *highly* degraded when Wifi on your device is *disabled*.

**Comment by alexbarnsley** [comment]
@christocracy apologies, since I reported this issue I've noticed a separate issue adding geofences (our issue, not plugin related), which won't help this situation. Once I have that resolved, I'll re-test and send over the logs again, with Wifi enabled. This should be tomorrow morning (BST time).

Thanks

**Comment by alexbarnsley** [comment]
Just a quick update @christocracy - WiFi enabled this morning and the exit event triggered. I'm going to try over the next week to alternate WiFi on/off and see if it is a scenario of bad GPS / WiFi disabled. In your opinion, let's say it is down to bad GPS, do you think the Exit event should be triggered regardless? It just seemed strange that it effectively disregarded the fact that I've left.

Either way, I'll do my tests and see how I get on. Will keep you updated 👍

**Comment by christocracy** [comment]
Neither IOS nor Android use active gps to evaluate geofences.  They use WiFi or cell-tower Geolocation.

**Comment by alexbarnsley** [comment]
@christocracy on that basis, geofences shouldn't work at all when in Airplane mode (with GPS enabled - which you can do on my phone)? Is that what you're saying?

**Comment by christocracy** [comment]
The keyword here is *active* gps.  If a GPS location is requested from some other app in the background, sure it'll be used.

Put a geofence around your house .  Disable Wifi and exit your house.  Your Geofence exit will likely not fire.

**Comment by alexbarnsley** [comment]
@christocracy while yes, I'm having an issue with my home during the morning. I'm also testing during the day at the office with exact same scenarios. I never have WiFi enabled at all usually and I've not had issues up to this point. If you meant to disable mobile data as well, then that's something I can test at the office.
