### ISSUE TITLE
A strange set of points received

### ISSUE THREAD

**Issue by audio747** [transistorsoft/cordova-background-geolocation-lt#469]
## Your Environment
* Plugin version: 2.8.3
* Platform: iOS
* OS version: 10.2.1
* Device manufacturer / model: iPhone 7
* Cordova version (`cordova -v`): cli-6.5.0 (4.3.1)
* Cordova platform version (`cordova platform ls`): PGB
* Plugin config

_geo.object.configure({
                    desiredAccuracy: 0,
                    distanceFilter: 30,
                    stationaryRadius: 10,
                    activityRecognitionInterval: 10000,
                    stopTimeout: 15,
                    debug: _app.debugMode,
                    stopOnTerminate: false,
                    startOnBoot: true,
                    url: _api.journey,
                    method: "POST",
                    autoSync: true,
                    maxDaysToPersist: 1,
                    params: {
                        "action": "track_driver",
                        "user_id": _profile.user.profile.id,
                        "token": _profile.user.token,
                        "uuid": _app.uuid,
                        "value": {}
                    }
                });

## Expected Behavior

The green line in attach image

## Actual Behavior

The red line in attach image

## Context

![image_example](https://user-images.githubusercontent.com/846718/30479846-4671a6c0-9a17-11e7-84ea-00df88b58f05.png)

Plugin sent a strange set of points... there are methods or settings to mitigate this case?

**Comment by christocracy** [comment]
You can never get perfect results.  Observe the reported `accuracy` of locations and ignore them as desired.

**Comment by christocracy** [comment]
Your signal was affected by those 4 large buildings which blocked the view of some GPS satellites your device was locked onto.

![](https://jdl.dropboxusercontent.com/s/rp2be2yixau1o4z/Screenshot%202017-09-15%2008.23.10.png?dl=1)

**Comment by christocracy** [comment]
(having trouble posting screenshots)
![](https://dl.dropboxusercontent.com/s/hrprpv3poe1dzsg/Screenshot%202017-09-15%2008.26.16.png?dl=1)

**Comment by audio747** [comment]
ok for first example... correct.

but in this case we have receive three, four points distanced kms...

![anomalia_2](https://user-images.githubusercontent.com/846718/30491551-f08a1766-9a3d-11e7-8d4c-b6419883fd66.png)

**Comment by christocracy** [comment]
Show me the corresponding location-data for those locations of that iPhone 7 device.

**Comment by audio747** [comment]
![img_15092017_161903_0](https://user-images.githubusercontent.com/846718/30496045-84587478-9a4e-11e7-801c-0cf95cfed4dd.png)

**Comment by christocracy** [comment]
What is that column, `accuracy`?  There's nothing the plugin can do about that.

"You can't squeeze blood from a stone"
