### ISSUE TITLE
Repo url bad

### ISSUE THREAD

**Issue by vpshonyak** [transistorsoft/cordova-background-geolocation-lt#47]
I bought a license. In email it said repo url is https://github.com/transistorsoft/cordova-background-geolocation which doesn't work. What's the good url? Thanks

**Comment by christocracy** [comment]
https://github.com/transistorsoft/cordova-background-geolocation

Did you register your github username and respond the github request to
join the private repo?

On Friday, January 1, 2016, vpshonyak <notifications@github.com> wrote:

> I bought a license In email it said repo url is
> https://githubcom/transistorsoft/cordova-background-geolocation which
> doesn't work What's the good url? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/47>
> .
>


-- 
Snet form Gmail Mobile

**Comment by vpshonyak** [comment]
Just responded to join private repo. Thank you so much!
