### ISSUE TITLE
location + internet in background 

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#471]
In ios, with the "location" value in "UIBackgroundModes" of the file "info.plist" this plugin can make the GPS requests in the background. But only with the value "location" would it be enough to have internet access permission to run the HTTP post offered by this plugin?
Would not it be necessary to add the values "voip" or "fetch" to ensure the presence of internet in the background, especially after a long period without user interaction with the smartphone?
Thank you

**Comment by christocracy** [comment]
The setup instructions mention none of this, the answer is no.
