### ISSUE TITLE
problem with speed

### ISSUE THREAD

**Issue by aboveo** [transistorsoft/cordova-background-geolocation-lt#473]
there is a large difference in speed ; in driving mode if the car speed is 20 its showing 40

is there any solution for it

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
And now you've *completely ignored* the issue template.  You haven't event specified if you're talking about **iOS** or **Android**, nor have you provided any logs.

**Comment by christocracy** [comment]
Nevertheless, the plugin has nothing to do with `speed`.  It provides this data directly from the native location API.  The plugin is only the messenger.

**Comment by aboveo** [comment]
thank you thats all we need
