### ISSUE TITLE
Can't build app with plugin

### ISSUE THREAD

**Issue by philipkaare** [transistorsoft/cordova-background-geolocation-lt#474]
## Your Environment
* Plugin version: 2.8.4
* Platform: Android
* OS version: Building on Windows 10 in Powershell.
* Device manufacturer / model: -
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): android 6.1.2
* Plugin config

<plugin name="cordova-background-geolocation-lt" spec="~2.8.4">
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
        <variable name="LICENSE" value="YOUR_LICENSE_KEY" />
    </plugin>

## Expected Behavior
The app should build.

## Actual Behavior
The app does not build and fails with: "error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'."

## Steps to Reproduce

1. Install plugin
2. `android cordova build android`
3. ERROR

## Context
I have been trying many, many things over last few days, including:
Different combinations of installed SDKs (with/without 24,25,26 - different versions of android build tools), using the cordova-google-api-version plugin, upgrading cordova, upgrading nodejs, clearing the npm cache, giving arguments to gradle to force it to use specific android SDK versions. 

## Debug logs
```
PS C:\git\app.develop\scaut> ionic cordova build android
[WARN] Not performing Ionic build for project type: ionic1.
> ionic cordova prepare android
> cordova prepare android
Running command: "C:\Program Files\nodejs\node.exe" C:\git\app.develop\scaut\hooks\after_prepare\020_remove_sass_from_pl
atforms.js C:\git\app.develop\scaut

Discovered plugin "cordova-plugin-ios-no-export-compliance" in config.xml. Adding it to the project
Fetching plugin "https://github.com/mikaoelitiana/cordova-plugin-ios-no-export-compliance.git" via git clone

Repository "https://github.com/mikaoelitiana/cordova-plugin-ios-no-export-compliance.git" checked out to git ref "master
".
cp: dest file already exists: C:\git\app.develop\scaut\plugins\cordova-ios-plugin-no-export-compliance\package.json

cp: dest file already exists: C:\git\app.develop\scaut\plugins\cordova-ios-plugin-no-export-compliance\package.json
cp: dest file already exists: C:\git\app.develop\scaut\plugins\cordova-ios-plugin-no-export-compliance\plugin.xml

cp: dest file already exists: C:\git\app.develop\scaut\plugins\cordova-ios-plugin-no-export-compliance\package.json
cp: dest file already exists: C:\git\app.develop\scaut\plugins\cordova-ios-plugin-no-export-compliance\plugin.xml
cp: dest file already exists: C:\git\app.develop\scaut\plugins\cordova-ios-plugin-no-export-compliance\README.md

Plugin "cordova-ios-plugin-no-export-compliance" already installed on android.

> cordova build android
× Running command - failed!
[ERROR] An error occurred while running cordova build android (exit code 1):


        (truncated) ... cesWithMergeJavaResForDebug UP-TO-DATE
        :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
        :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
        :CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
        :CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
        :CordovaLib:bundleDebug UP-TO-DATE
        :CordovaLib:preReleaseBuild UP-TO-DATE
        :CordovaLib:checkReleaseManifest
        :CordovaLib:prepareReleaseDependencies
        :CordovaLib:compileReleaseAidl UP-TO-DATE
        :CordovaLib:compileReleaseNdk UP-TO-DATE
        :CordovaLib:copyReleaseLint UP-TO-DATE
        :CordovaLib:mergeReleaseShaders UP-TO-DATE
        :CordovaLib:compileReleaseShaders UP-TO-DATE
        :CordovaLib:generateReleaseAssets UP-TO-DATE
        :CordovaLib:mergeReleaseAssets UP-TO-DATE
        :CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
        :CordovaLib:packageReleaseRenderscript UP-TO-DATE
        :CordovaLib:compileReleaseRenderscript UP-TO-DATE
        :CordovaLib:generateReleaseResValues UP-TO-DATE
        :CordovaLib:generateReleaseResources UP-TO-DATE
        :CordovaLib:packageReleaseResources UP-TO-DATE
        :CordovaLib:processReleaseManifest UP-TO-DATE
        :CordovaLib:generateReleaseBuildConfig UP-TO-DATE
        :CordovaLib:processReleaseResources UP-TO-DATE
        :CordovaLib:generateReleaseSources UP-TO-DATE
        :CordovaLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
        :CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
        :CordovaLib:processReleaseJavaRes UP-TO-DATE
        :CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
        :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
        :CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
        :CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
        :CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
        :CordovaLib:bundleRelease UP-TO-DATE
        :prepareAndroidArchLifecycleRuntime100Library UP-TO-DATE
        :prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
        :prepareComAndroidSupportAnimatedVectorDrawable2610Library UP-TO-DATE
        :prepareComAndroidSupportAppcompatV72610Library UP-TO-DATE
        :prepareComAndroidSupportSupportCompat2610Library UP-TO-DATE
        :prepareComAndroidSupportSupportCoreUi2610Library UP-TO-DATE
        :prepareComAndroidSupportSupportCoreUtils2610Library UP-TO-DATE
        :prepareComAndroidSupportSupportFragment2610Library UP-TO-DATE
        :prepareComAndroidSupportSupportMediaCompat2610Library UP-TO-DATE
        :prepareComAndroidSupportSupportV132340Library UP-TO-DATE
        :prepareComAndroidSupportSupportV42610Library UP-TO-DATE
        :prepareComAndroidSupportSupportVectorDrawable2610Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesBase1140Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesBasement1140Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesGcm902Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesIid902Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesLocation1140Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesTasks1140Library UP-TO-DATE
        :prepareHockeySDK410Beta1Library UP-TO-DATE
        :prepareMeLeolinShortcutBadger1111Library UP-TO-DATE
        :prepareTslocationmanagerLibrary UP-TO-DATE
        :prepareDebugDependencies
        :compileDebugAidl UP-TO-DATE
        :compileDebugRenderscript UP-TO-DATE
        :generateDebugBuildConfig UP-TO-DATE
        :generateDebugResValues UP-TO-DATE
        :generateDebugResources UP-TO-DATE
        :mergeDebugResources UP-TO-DATE
        :processDebugManifest UP-TO-DATE
        :processDebugResourcesC:\git\app.develop\scaut\platforms\android\build\intermediates\res\merged\debug\values-v26
\values-v26.xml:15:21-54:
        AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

        C:\git\app.develop\scaut\platforms\android\build\intermediates\res\merged\debug\values-v26\values-v26.xml:15:
        error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.


          FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':processDebugResources'.
        > com.android.ide.common.process.ProcessException: Failed to execute aapt

        * Try:

        BUILD FAILED

        Total time: 7.997 secs
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        Error: cmd: Command failed with exit code 1 Error output:
        C:\git\app.develop\scaut\platforms\android\build\intermediates\res\merged\debug\values-v26\values-v26.xml:15:21-
54:
        AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

        C:\git\app.develop\scaut\platforms\android\build\intermediates\res\merged\debug\values-v26\values-v26.xml:15:
        error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.



        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':processDebugResources'.
        > com.android.ide.common.process.ProcessException: Failed to execute aapt

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by christocracy** [comment]
$ cordova plugins

**Comment by christocracy** [comment]
You are having [this issue](https://stackoverflow.com/questions/45301203/no-resource-found-that-matches-the-given-name-attr-androidkeyboardnavigationc)

**Comment by philipkaare** [comment]
@christocracy I figured as much, but I don't exactly know how to solve it. How do I find out which plugin is causing the conflict?

Cordova plugins:

android-camera-permission 1.0.0 "Android Camera Permission"
cordova-background-geolocation-lt 2.8.4 "BackgroundGeolocation"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-background-fetch 5.0.0 "CDVBackgroundFetch"
cordova-plugin-badge 0.7.4 "Badges"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-datepicker 0.9.2 "DatePicker"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-hockeyapp 2.2.3 "HockeyApp"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-indexedDB 0.1.4 "IndexedDB polyfill"
cordova-plugin-indexeddb-async 0.0.1 "cordova-plugin-indexeddb-async"
cordova-plugin-ios-camera-permissions 1.0.3 "iOS Permissions"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-media 2.4.0 "Media"
cordova-plugin-media-capture 1.4.3 "Capture"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.0 "Whitelist"
cordova-sqlite-storage 0.7.14 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.4.2 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.8.3 "PushPlugin"

**Comment by christocracy** [comment]
1.  [`cordova-plugin-compat` is deprecated](https://github.com/apache/cordova-plugin-compat#deprecated).  Get rid of it:
>This plugin is no longer being worked on as the functionality provided by this plugin is now included in cordova-android 6.3.0

2.  You're using a *very* old version of [`phonegap-plugin-push`](https://github.com/phonegap/phonegap-plugin-push).  Latest is `2.0.0`

3.  You might need to use my [cordova-google-api-version](https://github.com/transistorsoft/cordova-google-api-version) plugin to align all plugins using `play-services` to a fixed version (latest version is `11.4.0`.

**Comment by philipkaare** [comment]
@christocracy Thank you. I already tried using  cordova-google-api-version, without much success, but maybe dealing with the other plugins might solve the problem :)

**Comment by donwon** [comment]
@philipkaare did you find a solution to this?  I'm having the exact same problem.

**Comment by christocracy** [comment]
@donwon show me your plugins

**Comment by donwon** [comment]
Hi @christocracy  here they are:
(I've been trying different versions of the plugin from the non "lt" version, including the latest versions and older versions 2.8.X)

cordova-background-geolocation-lt 2.8.3 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-fetch 5.0.0 "CDVBackgroundFetch"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-ext 0.10.5 "Cordova sqlite storage plugin with extra features"
cordova.plugins.diagnostic 3.1.7 "Diagnostic"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.5 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"

**Comment by christocracy** [comment]
Your first task is to determine all those plugins (aside from this one) which include `play-services` or `firebase`.  These dependencies must all be aligned to use the same version.

This plugin requests [`11.+`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/build.gradle#L13)

At a glance:
- `cordova-backround-geolocation-lt`
- `phonegap-plugin-push 1.10.5 "PushPlugin"`

Did you try installing my [`cordova-google-api-version`](https://github.com/transistorsoft/cordova-google-api-version)?

Unrelated: you don't need to use `cordova-plugin-geolocation` with this plugin.  This plugin does everything it does (in fact the two can cause problems with "permissions tug-of-war").

**Comment by christocracy** [comment]
You might also try using the lastest version of `phonegap-plugin-push`
![](https://dl.dropboxusercontent.com/s/0pnntifv4zbhw08/Screenshot%202017-10-09%2022.12.40.png?dl=1) in addition to installing `cordova-google-api-version`

**Comment by christocracy** [comment]
@donwon Since you're a customer, you should not use this `-lt` version.  It's merely the "latest stable release" of the private repo.  Currently, the latest version of both private and `-lt` are identical and even if they weren't, it wouldn't make a difference.

The problem is common and is due to multiple plugins requesting different version `play-services` dependency.

eg:  if one plugin requests `11.0.1`, another `11.+` and another `11.2.0`, a dependency collision will occur.  It has nothing to do with the actual code of in the library.

**Comment by christocracy** [comment]
@donwon I've been participating in [this thread](https://github.com/phonegap/phonegap-plugin-push/issues/1718#issuecomment-325532721) at `phonegap-plugin-push` which is the same problem / other plugins.

In that thread, It's mentioned there's help coming down the pipe in next release of `cordova-android`.

**Comment by donwon** [comment]
Hi Chris, thanks for your help so far, it's been helpful. 
When try to build andorid with cordova-google-api-version I get the follow error when trying to build: 

Error: Cannot find module 'xml2js'

Have you seen that before?

**Comment by christocracy** [comment]
Hmm, the plugin does use that to parse the config.xml.

Try npm install xml2js

**Comment by coolvasanth** [comment]
Even I'm facing the same problem, If I remove PhoneGap-plugin push then everything works fine. Waiting for the next release of phone gap push plugin.

**Comment by christocracy** [comment]
`cordova-google-api-version` will no longer be required when I post the latest update to this repo.  It will now be possible to configure the `GOOGLE_API_VERSION` as a plugin `<variable name="GOOGLE_API_VERSION" />`.  This will require you to use the latest version of Cordova `7.1.0+` (latest android platform in particular `android 6.3.0`.

There will be no more install-script (thus no more `xml2js`).

**Comment by christocracy** [comment]
And you'll want to use `phonegap-plugin-push @ 2.1.0+` which has a similar configuration mechanism with the `<variable name="FCM_VERSION" />`

In your `config.xml`
```xml
 <plugin name="cordova-background-geolocation" spec="file:///Users/chris/workspace/cordova/background-geolocation/cordova-background-geolocation">
        <variable name="LICENSE" value="LICENSE" />
        <variable name="GOOGLE_API_VERSION" value="11.0.1" />
        <variable name="APPCOMPAT_VERSION" value="26.1.0" />
    </plugin>
    <plugin name="phonegap-plugin-push" spec="^2.1.0">
        <variable name="FCM_VERSION" value="11.0.1" />
    </plugin>
```

`FCM_VERSION` and `GOOGLE_API_VERSION` must be **identical**.

In the future, all plugins which require Google dependencies will implement this same mechanism.
