### ISSUE TITLE
Plugin doesn't return location after some time without any warning messages

### ISSUE THREAD

**Issue by dhrytsenko** [transistorsoft/cordova-background-geolocation-lt#475]
## Your Environment
* Plugin version: 2.8.2
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Google Nexus 6
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): android 6.2.3
* Plugin config

  "distanceFilter": 0,
  "desiredAccuracy": 0,
  "locationUpdateInterval": 60000,
  "fastestLocationUpdateInterval": 60000,
  "locationTimeout": 120,
  "disableElasticity": true,
  "disableStopDetection": true,
  "heartbeatInterval": 60,
  "foregroundService": true,
  "forceReloadOnSchedule": true,
  "schedule": [
    "2017-09-20-12:51 2017-09-20-13:29",
    "2017-09-20-13:30 2017-09-20-16:00"
  ]

## Expected Behavior

Plugin should tracking location whole time according to schedule time without motion detection in aggressive way. 

## Actual Behavior

Plugin was stop returning any location for some time without any error. It started to track on time and return location on time and then it stops from 13:52 to 14:47 and then again stop from 14:47 to 15:55. 

## Debug logs

[Logs file](https://drive.google.com/open?id=0By3cDKyjfhCdZ003VVdrYnhGdW8)

**Comment by christocracy** [comment]
The device was stationary at `13:52`.  Android OS could be throttling location updates when it detects the device isn't moving.  Could also be power-management engaging.

```
09-20 13:52:41.175 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
```

It's really **not** a good idea to `disableStopDetection: true, distanceFilter: 0, locationUpdateInterval: 60000`.  You'll kill the battery.  Location-services radios are **ON** constantly with your configuration. 

The plugin is *very* good at determining when the device is moving / stationary.  If the device is stationary, you don't need to keep requesting the same location over and over again -- you'll **kill the battery.**

Read the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

**Comment by dhrytsenko** [comment]
@christocracy Thank you for so quick answer. l used this set of settings cause sometimes plugin doesn't determind motion when phone is on flat surface like on a car or a boat dashboard. I work on track's app for boats and my goal is to get location by some time period like 1 min or so. Do you have any advice in my case how l can improve my app and prevent this problem?

**Comment by christocracy** [comment]
When your app boots, the plugin logs the `DEVICE SENSORS`, show me the result you see:
```
09-21 08:52:32.896 28130 28285 I TSLocationManager: ╔═════════════════════════════════════════════
09-21 08:52:32.896 28130 28285 I TSLocationManager: ║ DEVICE SENSORS
09-21 08:52:32.896 28130 28285 I TSLocationManager: ╠═════════════════════════════════════════════
09-21 08:52:32.896 28130 28285 I TSLocationManager: ╟─ ✅  ACCELEROMETER: {Sensor name="BMI160 accelerometer", vendor="Bosch", version=1, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.001, minDelay=2500}
09-21 08:52:32.896 28130 28285 I TSLocationManager: ╟─ ✅  GYROSCOPE: {Sensor name="BMI160 gyroscope", vendor="Bosch", version=1, type=4, maxRange=17.453293, resolution=5.326322E-4, power=0.001, minDelay=2500}
09-21 08:52:32.896 28130 28285 I TSLocationManager: ╟─ ✅  MAGNETOMETER: {Sensor name="AK09915 magnetometer", vendor="AKM", version=1, type=2, maxRange=1300.0, resolution=0.0, power=0.001, minDelay=20000}
09-21 08:52:32.896 28130 28285 I TSLocationManager: ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant motion", vendor="Google", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.001, minDelay=-1}
09-21 08:52:32.896 28130 28285 I TSLocationManager: ╚═════════════════════════════════════════════
```
You can also query the sensors with method [`#getSensors(callback)`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getsensorscallbackfn-failurefn)

If you're using a low-cost device which is *missing* any of those sensors, Motion-detection performance will be *severely* degraded.  Even my Nexus 4 from 2012 includes all those sensors.

**Comment by dhrytsenko** [comment]
Ok, l'll check it. Thanks!

**Comment by christocracy** [comment]
Closed for lack of feedback.
