### ISSUE TITLE
timestamp with timezone anomaly

### ISSUE THREAD

**Issue by audio747** [transistorsoft/cordova-background-geolocation-lt#477]
## Your Environment
* Plugin version: 2.8.4
* Platform: Android
* OS version: various
* Device manufacturer / model: various
* Cordova version (`cordova -v`): 6.5
* Cordova platform version (`cordova platform ls`): PGB
* Plugin config

_geo.object.configure({
    desiredAccuracy: 10,
    distanceFilter: 30,
    stationaryRadius: 10,
    activityRecognitionInterval: 10000,
    stopTimeout: 15,
    debug: _app.debugMode,
    stopOnTerminate: false,
    url: _api.journey,
    method: "POST",
    batchSync: true,
    autoSync: true,
    maxDaysToPersist: 1,
    params: {
        "action": "track_driver",
        "user_id": _profile.user.profile.id,
        "token": _profile.user.token,
        "uuid": _app.uuid
    }
}, function(state) {
    console.log("_geo.configure - BACKGROUND ready!");
    if (!state.enabled) {
        _geo.object.start(function() {
            _geo.getLocations();
        });
    }
}, function(error) {
    console.log("_geo.configure - BACKGROUND error!");
    console.error(error);
})

## Context

When plug-in start to send data in background-mode we receive a correct sequence of point, but in specific case (from an android of our customer), we receive a sequence with timestamp error (.394Z, .500Z, etc...).

Example:

"location": {
            "is_moving": true,
            "timestamp": "2017-09-22T10:41:09.000Z",  //CORRECT
            "coords": {...
 "location": {
            "is_moving": true,
            "timestamp": "2017-09-22T10:41:27.000Z", //CORRECT
            "coords": {... 
"location": {
            "is_moving": true,
            "timestamp": "2017-09-22T11:41:33.394Z", //ERROR
            "coords": {...
"location": {
            "is_moving": true,
            "timestamp": "2017-09-22T10:41:49.000Z", //CORRECT
            "coords": {...
"location": {
            "is_moving": true,
            "timestamp": "2017-09-22T10:42:19.000Z", //CORRECT
            "coords": {...
"location": {
            "is_moving": true,
            "timestamp": "2017-09-22T11:42:46.500Z", //ERROR
            "coords": {...

## Steps to Reproduce

we can't reproduce it on our test devices... these data was obtained, printing data sent to our service, from the endpoint specified in url param. In this trace step there is not conversions or elaborations.

**Comment by christocracy** [comment]
Let me guess:  you’re in Brazil?

**Comment by audio747** [comment]
Italy

**Comment by christocracy** [comment]
These are perfectly valid timestamps:
- `2017-09-22T11:41:33.394Z`
- `2017-09-22T11:42:46.500Z`

What do you have a problem with?  Those are *milliseconds*.

**Comment by audio747** [comment]
sorry, I explained badly...

"timestamp": "2017-09-22T10:41:27.000Z", //CORRECT time: 10:41:27.000
"timestamp": "2017-09-22T11:41:33.394Z", //ERROR time 11:41:33:394 (instead of 10:41:33:394)
"timestamp": "2017-09-22T10:41:49.000Z", //CORRECT time: 10:41:49.000
"timestamp": "2017-09-22T10:42:19.000Z", //CORRECT time: 10:42:19.000
"timestamp": "2017-09-22T11:42:46.500Z", //ERROR  time 11:42:46.500 (instead of 10:42:46.500)

**Comment by obkdev** [comment]
This seems to be the same issue as recorded in our issue #1333 - we are now seeing the same issue occur on a Sony Xperia XA.  Appreciate this is an OS time-stamp, but we are seeing more instances of it occurring on new Android devices and therefore makes the points unusable.

**Comment by christocracy** [comment]
@audio747 Since you've purchased a license, you should no longer use this *public* repo.  You should post issues to the [private repo](https://github.com/transistorsoft/cordova-background-geolocation/issues/1333)

**Comment by audio747** [comment]
Tnx chris... into this post in private repo I have read interesting info
