### ISSUE TITLE
Location Updates on Stationary 

### ISSUE THREAD

**Issue by tusharaga** [transistorsoft/cordova-background-geolocation-lt#479]
## Your Environment
* Plugin version:2.8.4
* Platform: iOS or Android : Android
* OS version: 6.0.1
* Device manufacturer / model: Oneplus One
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):  android 6.2.3
* Plugin config

      desiredAccuracy: 0,
      distanceFilter: 0,
      locationUpdateInterval: 5000,
      heartbeatInterval: 5,
      headers:{"Content-Type":"application/json", "Authorization":this.authToken},
      debug: true,
      url: this.envVariables.apiEndpoint + '/api/private/location/create',
      startOnBoot: true,
      maxDaysToPersist: 3,
      stopOnTerminate:false,
      foregroundService:true,
      preventSuspend:true,
      batchSync:true,
      httpRootProperty: '.',

## Expected Behavior

Location Heartbeat should trigger at heartbeatInterval: 5 seconds 
## Actual Behavior

Triggering every one minute

**Comment by christocracy** [comment]
Heartbeat was never designed to be run at a fast interval.

Android uses AlarmManager for its heartbeat implementation.  It cannot run faster than one minute.

**Comment by tusharaga** [comment]
Thanks @christocracy
