### ISSUE TITLE
window.BackgroundGeolocation is undefined 

### ISSUE THREAD

**Issue by rishantagarwal** [transistorsoft/cordova-background-geolocation-lt#48]
Plugin.xml 
```
<?xml version="1.0" encoding="UTF-8"?>

<plugin xmlns="http://www.phonegap.com/ns/plugins/1.0"
    xmlns:android="http://schemas.android.com/apk/res/android"
    id="com.transistorsoft.cordova.background-geolocation"
    version="1.2.0">
    <name>BackgroundGeolocation</name>
    <description>Sophisticated, battery-efficient background-geolocation plugin for Cordova</description>
    <license>MIT</license>
    <keywords>cordova, phonegap, background geolocation</keywords>

    <engines>
        <engine name="cordova" version=">=3.0.0" />
    </engines>

    <!-- 
        Pre-Cordova 5, non-npm plugin reference.  Uncomment this if you're not using Cordova 5.
    <dependency id="org.apache.cordova.dialogs" />
    -->

    <!-- Cordova 5 npm-style plugin referernce.  Comment this out if you're not using Cordova 5 -->
    <dependency id="cordova-plugin-dialogs" />

    <js-module src="www/BackgroundGeolocation.js" name="BackgroundGeolocation">
        <clobbers target="window.BackgroundGeolocation" />
    </js-module>

    <!-- android available in Premium Version: http://transistorsoft.github.io/cordova-background-geolocation -->
    
     <platform name="ios">
        <!-- required background modes:  App registers for location updates -->
        
        <config-file target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
            <string>TSLocationManager requires background location tracking</string>
        </config-file>

        <config-file target="*-Info.plist" parent="UIBackgroundModes">
            <array>
                <string>location</string>
            </array>
        </config-file>

        <config-file target="config.xml" parent="/*">
            <feature name="BackgroundGeolocation">
                <param name="ios-package" value="CDVBackgroundGeolocation"/>
            </feature>
        </config-file>
        <framework src="SystemConfiguration.framework" weak="true" />
        <framework src="AudioToolbox.framework" weak="true" />
        <framework src="AVFoundation.framework" weak="true" />
        <framework src="libsqlite3.dylib" weak="true" />
        <framework src="src/ios/TSLocationManager.framework" custom="true" />
        <source-file src="src/ios/CDVBackgroundGeolocation.m" />
        <header-file src="src/ios/CDVBackgroundGeolocation.h" />
     </platform>          

</plugin>
```
app.js 

```
angular.module('starter', ['ionic','ionic.service.core', 'starter.controllers', 'starter.services','ngCordova','ngCordova.plugins.backgroundGeolocation'])

.run(function ($window,$ionicPlatform,  $rootScope, $cordovaGeolocation, $cordovaBackgroundGeolocation, $cordovaDevice, $http) {
   // alert('stop so I can inspect!');
  $ionicPlatform.ready(function() {
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }

   // $location.path('/app');
   /* $rootScope.$digest();

    $rootScope.deviceReady = false; */

  /*  document.addEventListener('deviceready', function () {
        if(window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
          window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
          
          */
         var bgGeo = window.BackgroundGeolocation;
         console.log(bgGeo);
    /**
    * This callback will be executed every time a geolocation is recorded in the background.
    */
    var callbackFn = function(location, taskId) {
        var coords = location.coords;
        var lat    = coords.latitude;
        var lng    = coords.longitude;

        // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
        // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
        setTimeout(function() {
          bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
        }, 1000);
    };

    var failureFn = function(error) {
        console.log('BackgroundGeoLocation error');
    }

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure(callbackFn, failureFn, {
        // Geolocation config
        desiredAccuracy: 0,
        stationaryRadius: 50,
        distanceFilter: 50,
        disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
        locationUpdateInterval: 5000,
        minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change 
        fastestLocationUpdateInterval: 5000,
        activityRecognitionInterval: 10000,
        stopDetectionDelay: 1,  // Wait x minutes to engage stop-detection system
        stopTimeout: 2,  // Wait x miutes to turn off location system after stop-detection
        activityType: 'AutomotiveNavigation',

        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user) 
        forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user) 
        forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user) 
        stopOnTerminate: false,              // <-- [Android] Allow the background-service to run headless when user closes the app.
        startOnBoot: true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.

        // HTTP / SQLite config
        url: 'http://posttestserver.com/post.php?dir=cordova-background-geolocation',
        method: 'POST',
        batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
        headers: {
            "X-FOO": "bar"
        },
        params: {
            "auth_token": "maybe_your_server_authenticates_via_token_YES?"
        }
    });

    // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
    bgGeo.start();
  });
})
```

Pasted above is my code , but every-time I run it in browser I get an error saying that window.BackgroundGeolocation is undefined. I think i am missing something but am unable to figure out. Any help would be really appreciated.

**Comment by christocracy** [comment]
Start with the SampleApp first.

https://github.com/transistorsoft/cordova-background-geolocation-SampleApp


On Monday, January 4, 2016, Rishant Agarwal <notifications@github.com>
wrote:

> Plugin.xml
>
> <?xml version="1.0" encoding="UTF-8"?>
>
> <plugin xmlns="http://www.phonegap.com/ns/plugins/1.0"
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     id="com.transistorsoft.cordova.background-geolocation"
>     version="1.2.0">
>     <name>BackgroundGeolocation</name>
>     <description>Sophisticated, battery-efficient background-geolocation plugin for Cordova</description>
>     <license>MIT</license>
>     <keywords>cordova, phonegap, background geolocation</keywords>
>
>     <engines>
>         <engine name="cordova" version=">=3.0.0" />
>     </engines>
>
>     
>
>     
>     <dependency id="cordova-plugin-dialogs" />
>
>     <js-module src="www/BackgroundGeolocation.js" name="BackgroundGeolocation">
>         <clobbers target="window.BackgroundGeolocation" />
>     </js-module>
>
>     
>
>      <platform name="ios">
>         
>
>         <config-file target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
>             <string>TSLocationManager requires background location tracking</string>
>         </config-file>
>
>         <config-file target="*-Info.plist" parent="UIBackgroundModes">
>             <array>
>                 <string>location</string>
>             </array>
>         </config-file>
>
>         <config-file target="config.xml" parent="/*">
>             <feature name="BackgroundGeolocation">
>                 <param name="ios-package" value="CDVBackgroundGeolocation"/>
>             </feature>
>         </config-file>
>         <framework src="SystemConfiguration.framework" weak="true" />
>         <framework src="AudioToolbox.framework" weak="true" />
>         <framework src="AVFoundation.framework" weak="true" />
>         <framework src="libsqlite3.dylib" weak="true" />
>         <framework src="src/ios/TSLocationManager.framework" custom="true" />
>         <source-file src="src/ios/CDVBackgroundGeolocation.m" />
>         <header-file src="src/ios/CDVBackgroundGeolocation.h" />
>      </platform>
>
> </plugin>
>
> app.js
>
> angular.module('starter', ['ionic','ionic.service.core', 'starter.controllers', 'starter.services','ngCordova','ngCordova.plugins.backgroundGeolocation'])
>
> .run(function ($window,$ionicPlatform,  $rootScope, $cordovaGeolocation, $cordovaBackgroundGeolocation, $cordovaDevice, $http) {
>    // alert('stop so I can inspect!');
>   $ionicPlatform.ready(function() {
>     if(window.StatusBar) {
>       StatusBar.styleDefault();
>     }
>
>    // $location.path('/app');
>    /* $rootScope.$digest();
>
>     $rootScope.deviceReady = false; */
>
>   /*  document.addEventListener('deviceready', function () {
>         if(window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
>           window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
>         }
>
>           */
>          var bgGeo = window.BackgroundGeolocation;
>          console.log(bgGeo);
>     /**
>     * This callback will be executed every time a geolocation is recorded in the background.
>     */
>     var callbackFn = function(location, taskId) {
>         var coords = location.coords;
>         var lat    = coords.latitude;
>         var lng    = coords.longitude;
>
>         // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
>         // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
>         setTimeout(function() {
>           bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
>         }, 1000);
>     };
>
>     var failureFn = function(error) {
>         console.log('BackgroundGeoLocation error');
>     }
>
>     // BackgroundGeoLocation is highly configurable.
>     bgGeo.configure(callbackFn, failureFn, {
>         // Geolocation config
>         desiredAccuracy: 0,
>         stationaryRadius: 50,
>         distanceFilter: 50,
>         disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
>         locationUpdateInterval: 5000,
>         minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change
>         fastestLocationUpdateInterval: 5000,
>         activityRecognitionInterval: 10000,
>         stopDetectionDelay: 1,  // Wait x minutes to engage stop-detection system
>         stopTimeout: 2,  // Wait x miutes to turn off location system after stop-detection
>         activityType: 'AutomotiveNavigation',
>
>         // Application config
>         debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
>         forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
>         forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
>         forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
>         stopOnTerminate: false,              // <-- [Android] Allow the background-service to run headless when user closes the app.
>         startOnBoot: true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.
>
>         // HTTP / SQLite config
>         url: 'http://posttestserver.com/post.php?dir=cordova-background-geolocation',
>         method: 'POST',
>         batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
>         autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
>         maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
>         headers: {
>             "X-FOO": "bar"
>         },
>         params: {
>             "auth_token": "maybe_your_server_authenticates_via_token_YES?"
>         }
>     });
>
>     // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
>     bgGeo.start();
>   });
> })
>
> Pasted above is my code , but every-time I run it in browser I get an
> error saying that window.BackgroundGeolocation is undefined. I think i am
> missing something but am unable to figure out. Any help would be really
> appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/48>
> .
>


-- 
Snet form Gmail Mobile

**Comment by rishantagarwal** [comment]
I tried with the app on the emulator. It works all good. Now how shall i proceed ?

**Comment by christocracy** [comment]
See the README for installation information.  The plugin is very easy to use.

**Comment by rishantagarwal** [comment]
Thanks

**Comment by thim81** [comment]
Hi Rishantargal,

I have the inverse problem. I moved the code to a services but it keeps saying that "window.BackgroundGeolocation is undefined".

Could you share your service example?
That way I can see how you did and where I do it wrong?

Regards,
Tim

**Comment by rishantagarwal** [comment]
Hi @thim81 , you may refer this sample code which i made . Please comment here if you find any more issues. Will be happy to help .

https://github.com/rishantagarwal/CordovaBackgroundGeolocationStartingUpExample
