### ISSUE TITLE
Request Location Authorization

### ISSUE THREAD

**Issue by tusharaga** [transistorsoft/cordova-background-geolocation-lt#480]
## Your Environment
* Plugin version:2.8.4

* Platform: iOS or Android : Android

* OS version: 6.0.1

* Device manufacturer / model: Oneplus One

* Cordova version (cordova -v): 7.0.1

* Cordova platform version (cordova platform ls): android 6.2.3

Can i request Location Authorization , as this can be useful for android 6 / API 23 and above because permissions are not granted at install time. ?

**Comment by christocracy** [comment]
Android will automatically request permission when necessary.

You do not need to think about this.

**Comment by christocracy** [comment]
I don't understand your problem.

**Comment by tusharaga** [comment]
Guess Screen Overlay is restricting authorization  permissions.

**Comment by christocracy** [comment]
If you're talking about this:
![](https://dl.dropboxusercontent.com/s/0s2kvh83d50okaq/Screenshot%202017-09-28%2010.49.25.png?dl=1)

You can capture Location state changes by listening to the [`providerchange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#providerchange) event.  You're free to interact with the user any way you wish in your event-handler.

**Comment by tusharaga** [comment]
ok , Thanks
