### ISSUE TITLE
plugin stops on terminating app in iOS

### ISSUE THREAD

**Issue by Jeet0027** [transistorsoft/cordova-background-geolocation-lt#481]
Hi, I am using this plugin in my application in which I draw the route with distance travel by user. My application is little similar to Uber app.
Plugin is working fine when the application is foreground or in background mode. It keeps sending locations to server. But when I terminate the app it stops. The location icon of device disappear from the top of phone. Same plugin working fine in android even when I kill the app it keep sending request to server and location icon remains on the screen. But in iOS it fails even I crossed 1 mile but plugin didn't wake.
Settings I using in my app
stop on terminate is false
stationary radius is 25

in info plist I have set UIBackgroundmode to location

Can you please tell me that what settings I am missing which it making fail to work on application termination in iOS. If its possible please give me some suggestions with this much information.
Thanks and regards

**Comment by christocracy** [comment]
This is normal and documented Behaviour of the iOS operating system.  See [this Video](https://youtu.be/aR6r8qV1TI8) (3:35 “Terminating the App”).

Also read the docs for #stopOnTerminate.
