### ISSUE TITLE
No "always" setting (in Location Services) in iOS 11

### ISSUE THREAD

**Issue by sideshow-systems** [transistorsoft/cordova-background-geolocation-lt#483]
When I have this setting here in my code (specific for iOS)

`locationAuthorizationRequest: 'Always',`

and run this in the simulator (or device) on os 9.3, I have the three options "Never", "While Using the App" and "Always".

When I run the app on iOS 11, I just see the options "Never" and "While Using the App".

Can anybody tell me why the option is missing in iOS 11?

**Comment by christocracy** [comment]
iOS has removed the permissions `Always` and `WhenInUse` and replaced it with `AlwaysAndWhenInUse`.  A new release is coming today.

In the meantime, you can manually add this permission in your XCode `.plist`:
![](https://dl.dropboxusercontent.com/s/mnopfx6d8kljh7d/Screenshot%202017-09-25%2010.36.57.png?dl=1)

**Comment by sideshow-systems** [comment]
WOW! Thank you for the fast answer. Workaround is working great. Thank you Chris!

**Comment by christocracy** [comment]
This is why I charge for the plugin:  prompt support.

**Comment by christocracy** [comment]
This is now fixed in version `2.8.5`

**Comment by chilimix** [comment]
Does this mean that LocationAuthorizationRequest has deprecated and your plugin by default always request AlwaysAndWhenInUse?

**Comment by christocracy** [comment]
>Does this mean that LocationAuthorizationRequest has deprecated 

No.  Nothing changed here.

iOS 11 made a change *forcing* apps to offer both *Always* and *When in Use* on the authorization popup.

In the end, there are still only 3 possible states for the user to select:
- Denied
- Always
- When in Use

`locationAuthorizationRequest` is simply telling the plugin which selection it should *EXPECT* the user to have chosen.  If the user selects anything other than `locationAuthorizationRequest`, the plugin will complain.

**Comment by chilimix** [comment]
Thank you Chris :)
