### ISSUE TITLE
Error in new version 2.8.5

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#486]
Your new version 2.8.5 did not compile in the phonegap build, which I use. I'm sending my generated log file to phonegap.
[log error ios phonegap.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1330682/log.error.ios.phonegap.txt)

**Comment by christocracy** [comment]
I’m now using XCode 9 to compile the library for iOS 11.

You’ll need to go ask PhoneGap Build when they’ll start building with XCode 9.
