### ISSUE TITLE
Accuracy problem

### ISSUE THREAD

**Issue by PrismaSG** [transistorsoft/cordova-background-geolocation-lt#488]
## Your Environment
* Plugin version: cordova-background-geolocation-lt 2.8.3 "BackgroundGeolocation"
* Platform: Android
* OS version: 4.3
* Device manufacturer / model: Samsung S3
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 6.0.0
  ios 4.3.1

* Plugin config

`
                       
                    desiredAccuracy: 0, 
                    distanceFilter: 45, 
                    stationaryRadius: 45,
                    
                    stopOnStationary:true,
                    stopTimeout:5, 
                    activityRecognitionInterval:30000, 

                    url: serverApi.host+"geotrack",
                    method: "POST",
                    params: { "transportId":activeJob[0].id },
                    headers: {"Token": token},
                    httpTimeout:25000,
                    autoSync: false, 
                    autoSyncThreshold:20,  
                        
                    
                    maxDaysToPersist: 2,
                    batchSync: true,
                    maxBatchSize:500,
                    startOnBoot:true,
                    stopOnTerminate:false,
                    foregroundService:true,
                    logLevel:0,
                    //debug:true,
                    
                   
                    geofenceProximityRadius:500,

                    
                    notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
                        
                   
                    locationAuthorizationRequest:"Always",

                    locationTemplate: '{"lat":<%=latitude%>, "lng":<%=longitude%>,"moving":<%=is_moving%>, "speed":<%=speed%>,"timestamp":"<%=timestamp%>"}',
                        
                    geofenceTemplate: '{"lat":<%=latitude%>, "lng":<%=longitude%>,"moving":<%=is_moving%>, "speed":<%=speed%>,"timestamp":"<%=timestamp%>","geofence":"<%= geofence.identifier %>","action":"<%= geofence.action %>" }',
                    `

## Expected Behavior
Accurated positions

## Actual Behavior
Sometimes points not very accurated( in that place there are no buildings, it was long time taking displaced points, parallel to real road,about 20 meters parallel),even when was using gps. 

<img src="http://labs.encolate.es/controlcad/img/screen2.png"/>
And some times takes positions with previous lat and lng. The plugin is remembering previous positions?. 
<img src="http://labs.encolate.es/controlcad/img/screen1.png"/>

I have observed that walking is enough precise, but this geopositions errors happens with speed.

## Steps to Reproduce

1. Install plugin
2. Start it
3.
4.

## Context
Tracking vehicles

**Comment by christocracy** [comment]
Logs.  See [Debugging](wiki/Debugging)

**Comment by PrismaSG** [comment]
Ok, you can close it. I don't have logs.
