### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dtruel** [transistorsoft/cordova-background-geolocation-lt#49]
Hello,

I'm very interested in this, but have 3 questions before buying:

1. If this thing is closed completely (not just suspended) can it restart itself in the background on significant changes in positioning?
2. Does it work with iOS 6,7, 8, and 9? What is compatibility like?
3. What kind of updates do we get if we buy?  If IOS 10 is different will we get a free fix, or will we have to pay more?

Thank you!

**Comment by christocracy** [comment]
On Thursday, January 7, 2016, dtruel <notifications@github.com> wrote:

> Hello,
>
> I'm very interested in this, but have 3 questions before buying:
>
>    1. If this thing is closed completely (not just suspended) can it
>    restart itself in the background on significant changes in positioning?
>
> Yes

>
>    1. Does it work with iOS 6,7, 8, and 9? What is compatibility like?
>
> I created it initially using ios7.

>
>    1. What kind of updates do we get if we buy? If IOS 10 is different
>    will we get a free fix, or will we have to pay more?
>
> Purchasing license provides 1 year access to private repo (i.e. Constant
updates).  $199/yr maintemce fee.

>
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/49>
> .
>


-- 
Snet form Gmail Mobile
