### ISSUE TITLE
Build problem xcode: .... 'TSBackgroundFetch/TSBackgroundFetch.h' file not found

### ISSUE THREAD

**Issue by PrismaSG** [transistorsoft/cordova-background-geolocation-lt#491]
I am not sure if I am in the right place, please if there is other git for client let me know and I will post this issue there..

* Plugin version:2.8.3
* Platform: iOS 
* OS version:  10.11.6
* Device manufacturer / model: Mac
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  ios 4.3.1
* Plugin config

`locationAuthorizationAlert: {
                            titleWhenNotEnabled: languageTexts[currentLanguage]["LANG_titleWhenNotEnabled"],
                            titleWhenOff: languageTexts[currentLanguage]["LANG_titleWhenOff"],
                            instructions: languageTexts[currentLanguage]["LANG_instructions"],
                            cancelButton: languageTexts[currentLanguage]["LANG_cancelButton"],
                            settingsButton: languageTexts[currentLanguage]["LANG_settingsButton"]
                        },

                    notificationText:languageTexts[currentLanguage]["LANG_notificationText"],
                    desiredAccuracy: 0, //La mejor
                    distanceFilter: 35, //Elastico
                    stationaryRadius: 45,
                    
                    stopOnStationary:false, // False deshabilita el modo stationery, por lo que siempre mandando
                    stopTimeout:5, //Detiene el servicio 3 minutos despues de entrar en modo stationery
                    activityRecognitionInterval:30000, //Reconoce cambio de actividad cada 30 segundos

                    url: serverApi.host+"geotrack",
                    method: "POST",
                    params: { "transportId":activeJob[0].id },
                    headers: {"Token": token},
                    httpTimeout:25000,
                    autoSync: true, //Original mente a true con autoSyncThreshold a 2
                    autoSyncThreshold:15,  //Original 16
                        
                    //Cuando se alcancen 2 registros locales se fuerza un post con todos los registros
                    maxDaysToPersist: 2,
                    batchSync: true,
                    maxBatchSize:500,
                    startOnBoot:true,
                    stopOnTerminate:false,
                    foregroundService:true,
                    logLevel:0,
                    //debug:true,
                    
                    //geofences
                    geofenceProximityRadius:500, //Metros, preguntar por geofences cercanas,

                    //android
                    notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN, //Oculta el icono del servicio
                        
                    //ios
                    //preventSuspend:true ,
                    locationAuthorizationRequest:"Always",

                    //Template de Json enviado
                    locationTemplate: '{"lat":<%=latitude%>, "lng":<%=longitude%>,"moving":<%=is_moving%>, "speed":<%=speed%>,"timestamp":"<%=timestamp%>"}',
                        
                    geofenceTemplate: '{"lat":<%=latitude%>, "lng":<%=longitude%>,"moving":<%=is_moving%>, "speed":<%=speed%>,"timestamp":"<%=timestamp%>","geofence":"<%= geofence.identifier %>","action":"<%= geofence.action %>" }',
                    `

## Expected Behavior
Build right

## Actual Behavior

I can run the app on emulator but when I try to build I get this error:

Lexical or Preprocessor error
....../Plugins/cordova-plugin-background-fetch/CDVBackgroundFetch.m:9:9: 'TSBackgroundFetch/TSBackgroundFetch.h' file not found

How can I fix it? In Android is working great with license.

## Steps to Reproduce

1.
2.
3.
4.

## Context

Build the app for production in xcode

## Debug logs
Not necessary

**Comment by christocracy** [comment]
```
$ cordova plugin remove --force cordova-plugin-background-fetch
$ cordova plugin add cordova-plugin-background-fetch@5.0.0
```

**Comment by PrismaSG** [comment]
Now I have this error: /Users/xxxxx/Desktop/<project>/platforms/ios/<project>/Plugins/cordova-background-geolocation-lt/CDVBackgroundGeolocation.h:8:9: 'TSLocationManager/TSLocationManager.h' file not found

**Comment by christocracy** [comment]
You have something corrupt in your project.  Remove / re-add background-geolocation.

**Comment by PrismaSG** [comment]
ok i will try. I will tell you later.

**Comment by christocracy** [comment]
Update?

**Comment by PrismaSG** [comment]
Just close the post, i was trying to archive with a debug scheme...
