### ISSUE TITLE
Unable to display speed, while using plugin on mobile device

### ISSUE THREAD

**Issue by Johan144** [transistorsoft/cordova-background-geolocation-lt#492]
Hi , im having trouble displaying the speed while using the plugin for one of our mobile applications. I've managed to play around with the settings and got the speed to display, but unfortunately the gps tracking interval was messed up. The gps coordinate intervals needs to be tracked regularly. Please look at my configuration settings, which im currently using works fine though except for the speed not displaying on the coordinates. I would appreciate it if you can point out any faulty property settings that might cause the plugin not to track the speed. Also see the attached screenshot for a graphical representation of the coordinates.

// 2. Compose your configuration.
    var simpleConfig = {
        // Geolocation Options
        trackingMode: 'location',//***** Additional Parameter
        //stopAfterElapsedMinutes: 0, *** Additional Parameter        
        triggerActivities: 'in_vehicle, on_bicycle, on_foot, running, walking',
        geofenceInitialTriggerEntry: true,
        desiredAccuracy: 10,//todo was 0
        distanceFilter: 5,//todo was 10
        disableElasticity: true,
        deferTime: 0,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 700,
        persist: true,//Additional Parameter
        desiredOdometerAccuracy: 1,  
        //geofenceInitialTriggerEntry: true, Additional Parameter
        //locationsOrderDirection: 'ASC',
        isMoving: true,            
        // Activity Recognition Options
        stationaryRadius: 25, //todo 100 default 25
        activityRecognitionInterval: 0, //todo default 10000
        stopTimeout: 5, //todo was 1 default 5
        heartbeatInterval: 10, //todo default 60
        interval: 500, //todo uncomment?
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        forceReloadOnLocationChange:
            true, // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)  //todo was false
        forceReloadOnMotionChange:
            true, // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)  //todo was false
        forceReloadOnGeofence:
            false, // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)  //todo was false
        stopOnTerminate:
            true, // <-- [Android] Allow the background-service to run headless when user closes the app. //todo was true
        startOnBoot: true, //todo was false
        license: '', //purchased license key 
        notificationTitle: 'Background tracking', // <-- android only, customize the title of the notification
        notificationText: 'ENABLED', // <-- android only, customize the text of the notification
        activityType: "AutomotiveNavigation", // <-- iOS-only
        // HTTP / SQLite config
        url: '',
        method: 'POST',
        batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        maxDaysToPersist: 1, // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails,
        autoSyncThreshold: 1,
        headers: {
            "X-FOO": "bar"
        },
        params: {
            "auth_token": "",
            "Imei": ""
        }
    };
![trackingcoordinates](https://user-images.githubusercontent.com/32546967/31233955-008ece3a-a9ee-11e7-984d-6b03c373a929.PNG)

**Comment by christocracy** [comment]
Please edit your post and **format your code** by wrapping in 3 back-tick characters.

![](https://dl.dropboxusercontent.com/s/9ssu4zdygkproty/Screenshot%202017-10-05%2010.57.37.png?dl=1)

**Comment by christocracy** [comment]
You don’t get `speed` unless location comes from GPS.

[`desiredAccuracy: 10`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-integer-desiredaccuracy-0-10-100-1000-in-meters) does not use GPS.  See the docs.

Lower battery usage comes by sacrificing accuracy.
