### ISSUE TITLE
Dependency error: with cordova-plugin-cocoalumberjack@^0.0.2

### ISSUE THREAD

**Issue by vijayb** [transistorsoft/cordova-background-geolocation-lt#493]
Hey Chris, I'm having the same issue as here:
https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/331

My plugin version from config.xml: 
<plugin name="cordova-background-geolocation" spec="git+https://github.com/transistorsoft/cordova-background-geolocation.git#2.6.0">

I was wondering what the best way to handle this is today. Back in May you suggested just using --force but I was wondering if that is still the right thing? Should I upgrade the plugin? I hadn't come across this previously because I was building for platform android, but now I'm going through the steps for ios.

Thank you

**Comment by christocracy** [comment]
If you’re having the problem as a previously posted issue, why are you opening a new one?  Post your question there.

Duplicate #331

**Comment by vijayb** [comment]
Sorry, Chris, will do. I thought because it was closed I should open a new issue. I'll move over there.
