### ISSUE TITLE
iOS build error - framework not found FileProvider for architecture x86_64

### ISSUE THREAD

**Issue by tomstreet** [transistorsoft/cordova-background-geolocation-lt#495]
## Environment
* Plugin version: 2.8.5
* Platform: iOS
* OS version: OS X 10.11.5
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): ios 4.4.0
* Plugin config

## Expected Behavior
Successful build

## Actual Behavior
The following commands failed:
   Ld build/emulator/HelloCordova.app/HelloCordova normal x86_64
framework not found FileProvider for architecture x86_64
linker command failed with exit code 1

## Steps to Reproduce
$ cordova create testapp
$ cordova plugin add cordova-background-geolocation-lt
$ cordova platform add ios
$ cordova build ios

## Context
Simply install the plugin. Created a fresh cordova project from scratch and added the plugin to eliminate as much as possible.

**Comment by christocracy** [comment]
Install latest XCode 9.  Always install latest XCode ASAP.

**Comment by tomstreet** [comment]
Thanks that sorted it
