### ISSUE TITLE
IOS 11 on app kill it's not calling http url for location update

### ISSUE THREAD

**Issue by laddhadhiraj** [transistorsoft/cordova-background-geolocation-lt#496]
I am just confirming is this plugin support in IOS 11 and is it able to update location after app kill? 

Currently when I start the app and set it in the background then I am getting the notification for any location change and also API getting called but As I close the app it just stops notification and updating URL at the server.

Please let me know How can we call api after killing app.

My configuration code is:

` this.bgGeo.configure({
	      debug: true,
	      desiredAccuracy: 0,
	      distanceFilter: 5,
	      stationaryRadius:10,
	      maxRecordsToPersist:2,
	      stopOnTerminate:false,
	      startOnBoot:true,
	      preventSuspend:true,
	      url	:'https://xxxx.com/api/v1/xxxx.json?type=url',
	      headers:headers,
	      method:'POST',
	      autoSync: true
	    }, (state) => {
	      // 4. Start the plugin.
	      this.bgGeo.start(function(e,s){
	      	console.log("this.bgGeo.start",e,s)
	      });
	    });`

Also in IONIC config.xml  added this 

`<plugin name="cordova-background-geolocation-lt" spec="^2.8.4">
    <variable name="LICENSE" value="YOUR_LICENSE_KEY"/>
    <variable name="BACKGROUND_MODE_LOCATION" value="&lt;string>location&lt;/string>"/>
    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required"/>
    <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required"/>
    <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving"/>
  </plugin>
  <engine name="android" spec="^6.2.3"/>
  <engine name="ios" spec="^4.4.0"/>`

**Comment by christocracy** [comment]
Yes, it works with iOS 11.  iOS 11 changed nothing in the operation of the plugin (only the authorization, with the new key `NSLocationAlwaysAndWhenInUseUsageDescription`).

Yes, iOS apps *are* completely terminated when user terminates the app.  This has always been the case.  However, once the device moves about 200 meters from the last known position, the OS will re-awaken the app *in the background*, where it will resume tracking.

- See docs for [`distanceFilter`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-stoponterminate-true)
- See [Demo Video](https://youtu.be/aR6r8qV1TI8?t=213)

**Comment by christocracy** [comment]
And you'll want to use version `2.8.5` for iOS 11, which includes the new `<variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" />`

**Comment by laddhadhiraj** [comment]
I tried this way and my app also has location permission as Always, but
when I kill the app, this not work.

**Comment by christocracy** [comment]
- Did you see the docs for `distanceFilter` and watch the Video? 
- Are you simulating location?  If not, try it.

The device must move *at least* 200 meters beyond the location where you terminated the app *before* the OS will reboot the app and resume tracking.

**Comment by laddhadhiraj** [comment]
Yes, I tried as your given video and changing location after killing as the
custom location but It's not sending any notification after app kill and no
updates at the server.

I have set "distanceFilter:5 " and I tried with changing location so far
but still after killing the app it's not working.

plz, let me know if anything required or I am doing something wrong.

**Comment by christocracy** [comment]
With plugin configured with `debug: true`:

- Boot your app in iOS Simulator
- Simulate location in Simulator:  **Debug -> Location -> Freeway Drive**.
- Terminate app.
- Wait.  Plugin will show debug local notifications when rebooted (as well as debug sounds)
