### ISSUE TITLE
Is it possible to have batched syncs occur based on a time interval?

### ISSUE THREAD

**Issue by troygilbert** [transistorsoft/cordova-background-geolocation-lt#497]
Ideally what I want is to be able to send batched location updates at a time-based interval, such as every 30 or 60 seconds. It seems like my options are:

* Do it myself. Set a timer in my code and when it's called manually call `sync()`. Drawback: if my app gets killed then I stop getting updates.
* Set `autoSyncThreshold` to a value that approximates how often I want. On my phone, I tend to get a location update every second or so, so I'd probably set the threshold at 30 or 60, but I don't think this is dependable because it seems some users, when they have bad tracking, may only produce a few dozen updates over the course of 30 minutes, which would leave a bunch of updates sitting and waiting on their device waiting for the threshold to be hit.

It feels like I should be able to configure the app to do this through a combination of `locationUpdateInterval` and `fastestLocationUpdateInterval`, but they don't seem to have any predictable impact. I think I'm misunderstanding how to use them.

Bottom-line, I'd love a "autosync batches no more often than X seconds" option, but I don't think that exists, right?

**Comment by christocracy** [comment]
There’s no way to autoSync based upon time.

Use autoSyncThreshold.  The plugin will always upload the remaining records in queue when a motionchange occurs.

**Comment by troygilbert** [comment]
Ah, that's very useful info about clearing the queue on a `motionchange` event. I didn't see that in the docs anywhere, did I miss it?

**Comment by christocracy** [comment]
It’s not documented but that’s certainly what it does.

**Comment by troygilbert** [comment]
Awesome, great to know, I think that fixes things. (Thanks for the very, very quick response!)

**Comment by K1N5L4Y3R** [comment]
I also tried looking for this in the docs, so IMHO it would be really helpful to add a quick note about it  in the docs/README.md when you have some time (or let me know if a PR for this would be welcome).
