### ISSUE TITLE
unable to upload to DB

### ISSUE THREAD

**Issue by itsupportvspl** [transistorsoft/cordova-background-geolocation-lt#498]
i am unable to upload the locations to db, it is returning http failure:  but am not getting any code .

below is the log 

 ╔═════════════════════════════════════════════
                                                                            ║ BackgroundGeolocation Settings
                                                                            ╠═════════════════════════════════════════════
                                                                            {
                                                                              "isMoving": false,
                                                                              "enabled": true,
                                                                              "odometer": 117.27817,
                                                                              "schedulerEnabled": false,
                                                                              "trackingMode": "location",
                                                                              "distanceFilter": 10,
                                                                              "desiredAccuracy": 0,
                                                                              "desiredOdometerAccuracy": 100,
                                                                              "locationUpdateInterval": 1000,
                                                                              "fastestLocationUpdateInterval": 10000,
                                                                              "locationTimeout": 60,
                                                                              "deferTime": 0,
                                                                              "disableElasticity": false,
                                                                              "elasticityMultiplier": 1,
                                                                              "activityRecognitionInterval": 30000,
                                                                              "minimumActivityRecognitionConfidence": 75,
                                                                              "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                              "disableStopDetection": false,
                                                                              "stationaryRadius": 25,
                                                                              "stopTimeout": 5,
                                                                              "stopOnStationary": false,
                                                                              "url": "http:\/\/myip\/Service\/Service.svc\/RunStoredProcedureReturnsDataset?ConnectionString_Encrypted=FAICTranDBConnection&ProcedureName_Encrypted=Gpstrack&ParametersList_Encrypted=aswin|1.0.8(DEV)|FAiC|12.22222|70.77777",
                                                                              "method": "POST",
                                                                              "autoSync": true,
                                                                              "autoSyncThreshold": 0,
                                                                              "batchSync": false,
                                                                              "maxBatchSize": -1,
                                                                              "params": {},
                                                                              "headers": {
                                                                                "ContentType": "application\/json",
                                                                                "DataType": "json",
                                                                                "ProcessData": "true"
                                                                              },
                                                                              "extras": {},
                                                                              "httpRootProperty": "location",
                                                                              "locationTemplate": "",
                                                                              "geofenceTemplate": "",
                                                                              "persist": true,
                                                                              "maxDaysToPersist": 3,
                                                                              "maxRecordsToPersist": -1,
                                                                              "locationsOrderDirection": "ASC",
                                                                              "httpTimeout": 60000,
                                                                              "geofenceProximityRadius": 1000,
                                                                              "geofenceInitialTriggerEntry": true,
                                                                              "stopOnTerminate": false,
                                                                              "startOnBoot": true,
                                                                              "heartbeatInterval": -1,
                                                                              "foregroundService": false,
                                                                              "notificationPriority": 0,
                                                                              "notificationTitle": "",
                                                                              "notificationText": "Location Service activated",
                                                                              "notificationColor": "",
                                                                              "notificationIcon": "",
                                                                              "notificationSmallIcon": "",
                                                                              "notificationLargeIcon": "",
                                                                              "forceReloadOnLocationChange": false,
                                                                              "forceReloadOnMotionChange": false,
                                                                              "forceReloadOnGeofence": false,
                                                                              "forceReloadOnBoot": false,
                                                                              "forceReloadOnHeartbeat": false,
                                                                              "forceReloadOnSchedule": false,
                                                                              "stopAfterElapsedMinutes": 0,
                                                                              "schedule": [],
                                                                              "configureUrl": "",
                                                                              "configureInterval": -1,
                                                                              "debug": true,
                                                                              "logLevel": 5,
                                                                              "logMaxDays": 3
                                                                            }╚═════════════════════════════════════════════

**Comment by christocracy** [comment]
You have ignored the **issue template**.



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
