### ISSUE TITLE
unable to upload coordinates to DB

### ISSUE THREAD

**Issue by itsupportvspl** [transistorsoft/cordova-background-geolocation-lt#499]
## Your Environment
* Plugin version:2.8.5
* Platform: Android
* OS version:5.1
* Device manufacturer / model:Lenovo A2010-a
* Cordova version (`cordova -v`):7.0.1
* Cordova platform version (`cordova platform ls`):android 6.2.2
* Plugin config

## Expected Behavior
Capture location and upload it to DB on background

## Actual Behavior
It is capturing the location but uploding was failed.
it is returning http failure:  with blank there is no code or message

## Context
var callbackFn = function(location) {
                var coords = location.coords;
                var lat    = coords.latitude;
                var lng    = coords.longitude;
                console.log('- Location: ', JSON.stringify(location));
                console.log('- CustomLocation: '+ lat + lng);
            };
alert("CALL");
            // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
            var failureFn = function(errorCode) {
                console.warn('- BackgroundGeoLocation error: ', errorCode);
            }

            // Listen to location events & errors.
            bgGeo.on('location', callbackFn, failureFn);
            // Fired whenever state changes from moving->stationary or vice-versa.
            bgGeo.on('motionchange', function(isMoving) {
              console.log('- onMotionChange: ', isMoving);
            });
            // Fired whenever a geofence transition occurs.
            bgGeo.on('geofence', function(geofence) {
              console.log('- onGeofence: ', geofence.identifier, geofence.location);
            });
            // Fired whenever an HTTP response is received from your server.
            bgGeo.on('http', function(response) {
              console.log('http success: ', response.responseText);
            }, function(response) {
              console.log('http failure: ', response.status);
            });

            // BackgroundGeoLocation is highly configurable.
            bgGeo.configure({
                // Geolocation config
                desiredAccuracy: 0,
                distanceFilter: 10,
                stationaryRadius: 25,
                // Activity Recognition config
                activityRecognitionInterval: 30000,
                stopTimeout: 5,
                // Application config
                debug: true,  // <-- Debug sounds & notifications.
                stopOnTerminate: false,
                startOnBoot: true,
                // HTTP / SQLite config
                url: SAVE_GPS_URL+"aswin|1.0.8(DEV)|FAiC|"+lat+"|"+lng,
                method: "POST",
                autoSync: true,
                maxDaysToPersist: 3,
                headers: {  // <-- Optional HTTP headers
                    "ContentType" : "application/json",
                    "DataType" : "json",
                    "ProcessData" : "true"
                },
                params: {   // <-- Optional HTTP params

                }
            }, function(state) {
                // This callback is executed when the plugin is ready to use.
                console.log("BackgroundGeolocation ready: ", state);
                if (!state.enabled) {
                    bgGeo.start();
                }
            });

**Comment by christocracy** [comment]
You couldn't just **edit** the existing issue?

Are you not watching the plugin logs?  See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging#android)

**Comment by christocracy** [comment]
>it is returning http failure: with blank there is no code or message

The *plugin* is not returning "http failure" -- **YOUR SERVER** is.  Ask your server what the problem is.

**Comment by itsupportvspl** [comment]
yes this "http failure" is the printable statement here i am not getting any code ,below is my log

 ╔═════════════════════════════════════════════
                                                                            ║ BackgroundGeolocation Settings
                                                                            ╠═════════════════════════════════════════════
                                                                            {
                                                                              "isMoving": false,
                                                                              "enabled": true,
                                                                              "odometer": 117.27817,
                                                                              "schedulerEnabled": false,
                                                                              "trackingMode": "location",
                                                                              "distanceFilter": 10,
                                                                              "desiredAccuracy": 0,
                                                                              "desiredOdometerAccuracy": 100,
                                                                              "locationUpdateInterval": 1000,
                                                                              "fastestLocationUpdateInterval": 10000,
                                                                              "locationTimeout": 60,
                                                                              "deferTime": 0,
                                                                              "disableElasticity": false,
                                                                              "elasticityMultiplier": 1,
                                                                              "activityRecognitionInterval": 30000,
                                                                              "minimumActivityRecognitionConfidence": 75,
                                                                              "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                              "disableStopDetection": false,
                                                                              "stationaryRadius": 25,
                                                                              "stopTimeout": 5,
                                                                              "stopOnStationary": false,
                                                                              "url": "http:\/\/106.51.100.16:1170\/Service\/Service.svc\/RunStoredProcedureReturnsDataset?ConnectionString_Encrypted=FAICTranDBConnection&ProcedureName_Encrypted=Gpstrack&ParametersList_Encrypted=aswin|1.0.8(DEV)|FAiC|12.22222|70.77777",
                                                                              "method": "POST",
                                                                              "autoSync": true,
                                                                              "autoSyncThreshold": 0,
                                                                              "batchSync": false,
                                                                              "maxBatchSize": -1,
                                                                              "params": {},
                                                                              "headers": {
                                                                                "ContentType": "application\/json",
                                                                                "DataType": "json",
                                                                                "ProcessData": "true"
                                                                              },
                                                                              "extras": {},
                                                                              "httpRootProperty": "location",
                                                                              "locationTemplate": "",
                                                                              "geofenceTemplate": "",
                                                                              "persist": true,
                                                                              "maxDaysToPersist": 3,
                                                                              "maxRecordsToPersist": -1,
                                                                              "locationsOrderDirection": "ASC",
                                                                              "httpTimeout": 60000,
                                                                              "geofenceProximityRadius": 1000,
                                                                              "geofenceInitialTriggerEntry": true,
                                                                              "stopOnTerminate": false,
                                                                              "startOnBoot": true,
                                                                              "heartbeatInterval": -1,
                                                                              "foregroundService": false,
                                                                              "notificationPriority": 0,
                                                                              "notificationTitle": "",
                                                                              "notificationText": "Location Service activated",
                                                                              "notificationColor": "",
                                                                              "notificationIcon": "",
                                                                              "notificationSmallIcon": "",
                                                                              "notificationLargeIcon": "",
                                                                              "forceReloadOnLocationChange": false,
                                                                              "forceReloadOnMotionChange": false,
                                                                              "forceReloadOnGeofence": false,
                                                                              "forceReloadOnBoot": false,
                                                                              "forceReloadOnHeartbeat": false,
                                                                              "forceReloadOnSchedule": false,
                                                                              "stopAfterElapsedMinutes": 0,
                                                                              "schedule": [],
                                                                              "configureUrl": "",
                                                                              "configureInterval": -1,
                                                                              "debug": true,
                                                                              "logLevel": 5,
                                                                              "logMaxDays": 3
                                                                            }╚═════════════════════════════════════════════

**Comment by christocracy** [comment]
That is **not** your log.  Those are settings *from* the log.  Logs look like *this*:
```
10-12 09:21:11.036 29646 17572 D TSLocationManager: ╔═════════════════════════════════════════════
10-12 09:21:11.036 29646 17572 D TSLocationManager: ║ HTTP Service
10-12 09:21:11.036 29646 17572 D TSLocationManager: ╠═════════════════════════════════════════════
10-12 09:21:11.064 29646 17572 D TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO first]
10-12 09:21:11.064 29646 17572 D TSLocationManager:   ✅  Locked 1 records
10-12 09:21:11.070 29646 17637 D TSLocationManager: [c.t.l.LocationService onLocation]
10-12 09:21:11.070 29646 17637 D TSLocationManager: ╔═════════════════════════════════════════════
10-12 09:21:11.070 29646 17637 D TSLocationManager: ║ LocationService: location
10-12 09:21:11.070 29646 17637 D TSLocationManager: ╠═════════════════════════════════════════════
10-12 09:21:11.070 29646 17637 D TSLocationManager: ╟─ 📍  Location[fused 45.519287,-73.616991 hAcc=20 et=+8d17h42m12s840ms vAcc=??? sAcc=??? bAcc=???], age: 55ms
10-12 09:21:11.072 29646 17572 I TSLocationManager: [c.t.l.http.HttpService createRequest]
10-12 09:21:11.072 29646 17572 I TSLocationManager:   🔵  HTTP POST: 159614cd-a2f5-4fcc-b00b-b3152394af05
10-12 09:21:11.104 29646 17637 D TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult]
10-12 09:21:11.104 29646 17637 D TSLocationManager: ╔═════════════════════════════════════════════
10-12 09:21:11.104 29646 17637 D TSLocationManager: ║ Process LocationResult
10-12 09:21:11.104 29646 17637 D TSLocationManager: ╠═════════════════════════════════════════════
10-12 09:21:11.325 29646 17640 I TSLocationManager: [c.t.l.http.HttpService$a onResponse]
10-12 09:21:11.325 29646 17640 I TSLocationManager:   🔵  Response: 200
```

**Comment by itsupportvspl** [comment]
hi ,  i am getting "bad request" but i requested by  all required parameter and headers and so ,  below is my log ,  

10-13 11:41:41.036 17870-18924/com.verifact.faiconnect D/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                                            ╔═════════════════════════════════════════════
                                                                            ║ LocationService: location
                                                                            ╠═════════════════════════════════════════════
                                                                            ╟─ ��  Location[fused 12.960468,77.645650 acc=96 et=+1h56m43s282ms alt=194.2 vel=3.3060608 bear=320.0], age: 18ms
10-13 11:41:41.077 17870-18924/com.verifact.faiconnect D/TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
                                                                            ╔═════════════════════════════════════════════
                                                                            ║ Process LocationResult
                                                                            ╠═════════════════════════════════════════════
10-13 11:41:41.103 17870-18924/com.verifact.faiconnect I/TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
                                                                              ��  Re-scaled distanceFilter: 10.0->20.0)
10-13 11:41:41.132 17870-18924/com.verifact.faiconnect D/TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 52.4
10-13 11:41:41.157 17870-18924/com.verifact.faiconnect D/TSLocationManager: [c.t.l.l.TSLocationManager incrementOdometer] 76620.414
10-13 11:41:41.223 17870-18924/com.verifact.faiconnect D/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                                            ╔═════════════════════════════════════════════
                                                                            ║ LocationService: location
                                                                            ╠═════════════════════════════════════════════
                                                                            ╟─ ��  Location[fused 12.960468,77.645650 acc=96 et=+1h56m43s282ms alt=194.2 vel=3.3060608 bear=320.0], age: 220ms
10-13 11:41:41.230 17870-18192/com.verifact.faiconnect I/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO persist] 
                                                                              ✅  INSERT: 353a4650-90cb-4619-9113-5dbea4c2477b
10-13 11:41:41.256 17870-18924/com.verifact.faiconnect D/TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
                                                                            ╔═════════════════════════════════════════════
                                                                            ║ Process LocationResult
                                                                            ╠═════════════════════════════════════════════
10-13 11:41:41.308 17870-18192/com.verifact.faiconnect D/TSLocationManager: [c.t.l.http.HttpService flush] 
                                                                            ╔═════════════════════════════════════════════
                                                                            ║ HTTP Service
                                                                            ╠═════════════════════════════════════════════
10-13 11:41:41.321 17870-18924/com.verifact.faiconnect D/TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
                                                                              ℹ️  IGNORED: same as last location
10-13 11:41:41.383 17870-18924/com.verifact.faiconnect I/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                                              ℹ️  Location availability: true
10-13 11:41:41.386 17870-18192/com.verifact.faiconnect D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO first] 
                                                                              ✅  Locked 1 records
10-13 11:41:41.425 17870-18192/com.verifact.faiconnect I/TSLocationManager: [c.t.l.http.HttpService createRequest] 
                                                                              ��  HTTP POST: 2af94a46-6d7b-4704-b358-216592aa28d5
10-13 11:41:41.504 17870-18193/com.verifact.faiconnect W/TSLocationManager: [c.t.l.http.HttpService$a onResponse] 
                                                                              ⚠️  Response: 400, Bad Request
10-13 11:41:41.551 17870-18193/com.verifact.faiconnect D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO unlock] 
                                                                              ✅  UNLOCKED: 2af94a46-6d7b-4704-b358-216592aa28d5
10-13 11:41:53.869 17870-19055/com.verifact.faiconnect I/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                                              ℹ️  Location availability: false
10-13 11:41:54.879 17870-19068/com.verifact.faiconnect I/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                                              ℹ️  Location availability: true

**Comment by christocracy** [comment]
You're responsible for encoding your `url` params.  Your url params contain special characters (eg `|`) **which need to be encoded**.

```javascript
var params =encodeURI('ConnectionString_Encrypted=FAICTranDBConnection&ProcedureName_Encrypted=Gpstrack&ParametersList_Encrypted=aswin|1.0.8(DEV)|FAiC|12.22222|70.77777');

var url = 'http://myip/Service/Service.svc/RunStoredProcedureReturnsDataset?' + params;
```

- See [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)
- See [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding)
