### ISSUE TITLE
Leaving stationary state on IOS

### ISSUE THREAD

**Issue by PauloBronfox** [transistorsoft/cordova-background-geolocation-lt#50]
It seems that the plugin can take a long time to leave the stationary state. It is possible to configure it without the power optimisation based on motion detection ? 
I mean getting data at the rate configured for motion even when the phone is stationary ?

**Comment by christocracy** [comment]
This limitation is imposed by iOS.  It requires a cell-tower change event to awaken and interrogate the stationary geofence.  In my extensive experience, it takes 2-3 city blocks of movement.  This is clearly documented in the "iOS Behaviouer" section of the docs.
