### ISSUE TITLE
Not working on iOS, but works in Simulator

### ISSUE THREAD

**Issue by ChronoSheets** [transistorsoft/cordova-background-geolocation-lt#500]
## Your Environment
* Plugin version: 2.8.5
* Platform: iOS  
* OS version: 10.2.1
* Device manufacturer / model: iPhone 5C and iPhone 6 plus
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):  ios 4.3.1
* Plugin config
            desiredAccuracy: 0,
            stationaryRadius: 10,
            distanceFilter: 10,
            stopTimeout: 20,
            activityRecognitionInterval: 3000,
            stopOnStationary: true,
            debug: false,
            preventSuspend: true,
            heartbeatInterval: 30,
            stopOnTerminate: false,
            startOnBoot: false,

(I've also tried other variations of the plugin config).

## Expected Behavior
It should start tracking location after 250 meters in the vehicle (I've read about this in the 'philosophy' docs).

## Actual Behavior
It doesn't appear to be tracking anything.  Sometimes it will start tracking 10 meters but then never gets another coordinate.

## Steps to Reproduce
Download/install the ChronoSheets iOS app from: http://tsheets.xyz/iosapp

- Enter the following test account:
username: testaccount
password: Password02@
- Goto the 'new timesheet' tab
- Choose any job
- Choose any task
- Select 'YES' for GPS tracking

The app should start to track your journey and total distance will show.  This has proven to work on the Android equivalent (http://tsheets.xyz/androidapp) running the same code so I'm sure it's something to do with my configuration or version mismatch but cannot figure it out.  It also works on the iPhone simulator when I'm running it in XCode with the location simulation (highway drive) turned on.

**Comment by christocracy** [comment]
Logs please.

**Comment by christocracy** [comment]
Closed for failure to provide logs.
