### ISSUE TITLE
Build Issues on Phonegap Adobe build

### ISSUE THREAD

**Issue by abdulhamid-alattar** [transistorsoft/cordova-background-geolocation-lt#501]
## Your Environment
* Plugin version: 2.8.5
* Platform: iOS 
* OS version: 10.3
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.1
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
Build on andriod is success and the app works just fine. but build for IOS fails

## Actual Behavior
IOS fails to build on phonegap adobe 

##Config.xml

`<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="5" id="#" ios-CFBundleVersion="undefined" version="0.1.5" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>##</name>
    <description>Universal init code for Intel XDK and Cordova device ready detection, as well as within browser.</description>
    <author>##</author>
    <content src="index.html" />
    <preference name="android-build-tool" value="gradle" />
    <platform name="android">
        <allow-intent href="http://*/*" />
        <allow-intent href="https://*/*" />
        <allow-intent href="tel:*" />
        <allow-intent href="sms:*" />
        <allow-intent href="mailto:*" />
        <allow-intent href="geo:*" />
        <allow-intent href="market:*" />
        <access origin="*" />
    </platform>
    <platform name="ios">
        <allow-intent href="http://*/*" />
        <allow-intent href="https://*/*" />
        <allow-intent href="tel:*" />
        <allow-intent href="sms:*" />
        <allow-intent href="mailto:*" />
        <allow-intent href="geo:*" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <access origin="*" />
    </platform>
  
    <engine name="android" spec="^6.2.3" />
    <engine name="ios" spec="^4.4.0" />
    <preference name="phonegap-version" value="cli-6.5.0" />
    <preference name="xwalkMultipleApk" value="false" />
    <preference name="cordova-background-geolocation-license" value="" />
    <plugin name="cordova-plugin-compat" spec="~1.2.0" />
    <plugin name="com-intel-security-cordova-plugin" spec="~2.0.3" />
    <plugin name="cordova-plugin-background-fetch" spec="5.1.1" />
    <plugin name="cordova-plugin-cocoalumberjack" spec="~0.0.4" />
    <plugin name="cordova-plugin-whitelist" spec="~1.3.2" />
    <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect --ignore-gpu-blacklist " />
    <platform name="android">
        <preference name="SplashMaintainAspectRatio" value="false" />
        <preference name="android-minSdkVersion" value="16" />
        <preference name="android-targetSdkVersion" value="21" />
        <preference name="android-installLocation" value="auto" />
        <preference name="android-signed" value="true" />
        <preference name="Orientation" value="portrait" />
        <preference name="AndroidLaunchMode" value="singleTop" />
    </platform>
    <platform name="ios">
        <preference name="ios-configuration" value="production" />
        <preference name="deployment-target" value="10.3" />
        <preference name="Orientation" value="portrait" />
        <preference name="AutoHideSplashScreen" value="true" />
        <preference name="FadeSplashScreen" value="false" />
        <preference name="FadeSplashScreenDuration" value="2" />
        <preference name="ShowSplashScreenSpinner" value="false" />
        <preference name="StatusBarOverlaysWebView" value="false" />
        <preference name="StatusBarBackgroundColor" value="#000000" />
        <preference name="StatusBarStyle" value="lightcontent" />
    </platform>
    <splash density="mdpi" height="470" orientation="portrait" platform="android" src="package-assets/android-320x470.png" width="320" />
    <splash density="hdpi" height="640" orientation="portrait" platform="android" src="package-assets/android-480x640.png" width="480" />
    <splash density="ldpi" height="426" orientation="portrait" platform="android" src="package-assets/android-320x426.png" width="320" />
    <splash density="xhdpi" height="960" orientation="portrait" platform="android" src="package-assets/android-720x960.png" width="720" />
    <splash height="480" orientation="portrait" platform="ios" src="package-assets/ios-320x480.png" width="320" />
    <splash height="960" orientation="portrait" platform="ios" src="package-assets/ios-640x960.png" width="640" />
    <splash height="1136" orientation="portrait" platform="ios" src="package-assets/ios-640x1136.png" width="640" />
    <splash height="1334" orientation="portrait" platform="ios" src="package-assets/ios-750x1334.png" width="750" />
    <splash height="2208" orientation="portrait" platform="ios" src="package-assets/ios-1242x2208.png" width="1242" />
    <icon density="mdpi" height="48" platform="android" src="package-assets/android-48x48.png" width="48" />
    <icon density="xhdpi" height="96" platform="android" src="package-assets/android-96x96.png" width="96" />
    <icon density="ldpi" height="36" platform="android" src="package-assets/android-36x36.png" width="36" />
    <icon density="hdpi" height="72" platform="android" src="package-assets/android-72x72.png" width="72" />
    <icon height="60" platform="ios" src="package-assets/ios-60x60.png" width="60" />
    <icon height="120" platform="ios" src="package-assets/ios-120x120.png" width="120" />
    <icon height="180" platform="ios" src="package-assets/ios-180x180.png" width="180" />
    <icon height="76" platform="ios" src="package-assets/ios-76x76.png" width="76" />
    <icon height="152" platform="ios" src="package-assets/ios-152x152.png" width="152" />
    <config-file mode="merge" parent="/manifest/application" platform="android">
        <activity android:launchMode="singleTop" />
    </config-file>
    <plugin name="cordova-plugin-crosswalk-webview" spec="~2.3.0" />
    <plugin name="cordova-plugin-statusbar" spec="~2.2.3" />
    <plugin name="cordova-plugin-device" spec="~1.1.6" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.3" />
    <plugin name="cordova-plugin-battery-status" spec="~1.2.4" />
    <plugin name="cordova-plugin-camera" spec="~2.4.1" />
    <plugin name="cordova-plugin-file" spec="~4.3.3" />
    <plugin name="cordova-plugin-media-capture" spec="~1.4.3" />
    <plugin name="cordova-plugin-contacts" spec="~2.3.1" />
    <plugin name="cordova-plugin-wkwebview-engine" spec="~1.1.3" />
    <plugin name="cordova-plugin-device-motion" spec="~2.0.0" />
    <plugin name="cordova-plugin-device-orientation" spec="~2.0.0" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.6.3" />
    <plugin name="cordova-plugin-geolocation" spec="~2.4.3" />
    <plugin name="cordova-plugin-globalization" spec="~1.0.7" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.7.1" />
    <plugin name="cordova-plugin-media" spec="~3.0.1" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.3" />
    <plugin name="cordova-plugin-dialogs" spec="~1.3.3" />
    <plugin name="cordova-plugin-screen-orientation" spec="~2.0.1" />
    <plugin name="cordova-plugin-vibration" spec="~2.1.5" />
    <plugin name="cordova-plugin-background-mode" spec="~0.7.2" />
    <plugin name="cordova-background-geolocation-lt" spec="~2.8.5">
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
        <variable name="LICENSE" value="" />
    </plugin>
</widget>
`

## Debug logs

The following build commands failed:
	Ld /Users/phonegap/Library/Developer/Xcode/DerivedData/FDMobileApp-gzrfwcuplviwrkgeinolhigtlbfe/Build/Intermediates/ArchiveIntermediates/FDMobileApp/IntermediateBuildFilesPath/FDMobileApp.build/Release-iphoneos/FDMobileApp.build/Objects-normal/armv7/FDMobileApp normal armv7
	Ld /Users/phonegap/Library/Developer/Xcode/DerivedData/FDMobileApp-gzrfwcuplviwrkgeinolhigtlbfe/Build/Intermediates/ArchiveIntermediates/FDMobileApp/IntermediateBuildFilesPath/FDMobileApp.build/Release-iphoneos/FDMobileApp.build/Objects-normal/arm64/FDMobileApp normal arm64
(2 failures)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/tmp/gimlet/2836012/project/cordova/build-release.xcconfig,-workspace,FDMobileApp.xcworkspace,-scheme,FDMobileApp,-configuration,Release,-destination,generic/platform=iOS,-archivePath,FDMobileApp.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/tmp/gimlet/2836012/project/build/device,SHARED_PRECOMPS_DIR=/private/tmp/gimlet/2836012/project/build/sharedpch
/Users/phonegap/gimlet/bin/system_ruby: line 22: shell_session_update: command not found

similar issue been reported by others also  https://forums.adobe.com/thread/2390472

**Comment by christocracy** [comment]
Duplicate #490.  You need to ask PGB: “when will you support iOS 11 and build with XCode 9?!”
