### ISSUE TITLE
Battery level not updating on IOS

### ISSUE THREAD

**Issue by chilimix** [transistorsoft/cordova-background-geolocation-lt#502]
## Your Environment
* Plugin version: From master about 1 months ago
* Platform: iOS
* OS version: 10.3.3
* Device manufacturer / model: Apple iPhone
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`): IOS 4.4.0
* Plugin config
stationaryRadius: 25,
      distanceFilter: 40,
      activityRecognitionInterval: 10000,
      fastestLocationUpdateInterval: 5000,
      minimumActivityRecognitionConfidence: 70,
      stopOnTerminate: false,
      startOnBoot: true,
      forceReloadOnBoot: true,
      batchSync: true,
      autoSync: true,
      debug: false,
      maxDaysToPersist: 0,
      preventSuspend: true,
      heartbeatInterval: 60,
      geofenceProximityRadius: 1000,
      activityType: "Other",
      deferTime: 0,
      elasticityMultiplier: 20,
      forceReloadOnMotionChange: true,
      forceReloadOnLocationChange: true,
      forceReloadOnHeartbeat: true,
      foregroundService: true,
      locationUpdateInterval: 10000

## Expected Behavior
We expect to get the current battery level every time we get a location.

## Actual Behavior
It seems like the battery level from the first location persists. The state as well, so if the phone is pluged in, every location afterwards gets the same state even if the phone is not in the charger
It works perfectly on Android. On androoid we get the current level on every location.

**Comment by christocracy** [comment]
Check your plugins.  You’re using some other plugin which turns off battery monitoring.  There’s one global battery api for your entire app.  When some plugin turns it off, it’s off globally.

**Comment by chilimix** [comment]
thanks, we will look into it

**Comment by christocracy** [comment]
For reference, show me your `$ cordova plugins`

**Comment by chilimix** [comment]
cordova-background-geolocation-lt 2.8.3 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.0.0 "CDVBackgroundFetch"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-statusbar 2.2.4-dev "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
es6-promise-plugin 4.1.0 "Promise"

**Comment by chilimix** [comment]
We still havent had any success finding out what causes IOS to not deliver battery level.

We only get battery level at the get current position, but not with the background location tracking http request. We have been through the plugins and cant find anything that would close the battery monitoring. Could it be a permission that we need to ask for?

**Comment by christocracy** [comment]
Battery does not require permission.

When the plugin's `#start` method is called:
```obj-c
// Start monitoring battery status.
[[UIDevice currentDevice] setBatteryMonitoringEnabled:YES];
```
When the plugin's `#stop` method is called:
```obj-c
// Stop monitoring battery status.
[[UIDevice currentDevice] setBatteryMonitoringEnabled:NO];
```

These are the only 2 references in the entire plugin to `setBatteryMonitoringEnabled`

Apple docs: [`UIDevice setBatteryMonitoringEnabled:BOOL`](https://developer.apple.com/documentation/uikit/uidevice/1620045-batterymonitoringenabled?language=objc)

**Comment by chilimix** [comment]
We will see if we can figure out what plugin stops the monitoring then.

Thank you Chris
