### ISSUE TITLE
Override the Service Request Body

### ISSUE THREAD

**Issue by itsupportvspl** [transistorsoft/cordova-background-geolocation-lt#503]
## Your Environment
* Plugin version:2.8.5
* Platform: Android
* OS version:5.1
* Device manufacturer / model:Lenovo A2010-a
* Cordova version (`cordova -v`):7.0.1
* Cordova platform version (`cordova platform ls`):android 6.2.2
* Plugin config

## Expected Behavior
While requesting service ,need to send our own body.

## Actual Behavior
While requesting service , some default Body is getting.

## Steps to Reproduce

1.
2.
3.
4.

## Context
bgGeo.configure({
                // Geolocation config
                desiredAccuracy: 0,
                distanceFilter: 10,
                stationaryRadius: 25,
                // Activity Recognition config
                activityRecognitionInterval: 30000,
                stopTimeout: 5,
                // Application config
                debug: true,  // <-- Debug sounds & notifications.
                stopOnTerminate: false,
                startOnBoot: true,
                // HTTP / SQLite config
                url: SAVE_GPS_URL+"aswin|1.0.8(DEV)|FAiC|132.22222|7330.77777",
                method: "POST",
                autoSync: true,
                maxDaysToPersist: 3,
                // data:Data,
                headers: {  // <-- Optional HTTP headers
                    "contentType" : "application/json; charset=utf-8",
                    "dataType" : "json",
                    "processData" : true
                }
                params: {   // <-- Optional HTTP params
                    "data":Data
                }
            }, function(state) {
                // This callback is executed when the plugin is ready to use.
                console.log("BackgroundGeolocation ready: ", state);
                if (!state.enabled) {
                    bgGeo.start();
                }
            });

## Debug logs
We are getting this in our service log.

<root type="object" xmlns="">
<location type="object">
<event type="string">motionchange</event>
<is_moving type="boolean">false</is_moving>
<uuid type="string">2af94a46-6d7b-4704-b358-216592aa28d5</uuid>
<timestamp type="string">2017-10-12T08:43:47.669Z</timestamp>
<odometer type="number">0</odometer>
<coords type="object">
<latitude type="number">12.9561803</latitude>
<longitude type="number">77.6363034</longitude>
<accuracy type="number">20</accuracy>
<speed type="number">-1</speed>
<heading type="number">-1</heading>
<altitude type="number">-1</altitude>
</coords>
<activity type="object">
<type type="string">still</type>
<confidence type="number">100</confidence>
</activity>
<battery type="object">
<is_charging type="boolean">true</is_charging>
<level type="number">0.95</level>
</battery>
<extras type="object"></extras>
</location>
</root>

**Comment by christocracy** [comment]
I have no idea what you're talking about.

**Comment by itsupportvspl** [comment]
here i am requesting 
params: { // <-- Optional HTTP params
"data":Data
}

but in our server i am getting the params and below xml also iam getting i think this is from plugin i dont need , because of this it is returning "bad request".


```xml
<root type="object" xmlns="">
<location type="object">
<event type="string">motionchange</event>
<is_moving type="boolean">false</is_moving>
<uuid type="string">2af94a46-6d7b-4704-b358-216592aa28d5</uuid>
<timestamp type="string">2017-10-12T08:43:47.669Z</timestamp>
<odometer type="number">0</odometer>
<coords type="object">
<latitude type="number">12.9561803</latitude>
<longitude type="number">77.6363034</longitude>
<accuracy type="number">20</accuracy>
<speed type="number">-1</speed>
<heading type="number">-1</heading>
<altitude type="number">-1</altitude>
</coords>
<activity type="object">
<type type="string">still</type>
<confidence type="number">100</confidence>
</activity>
<battery type="object">
<is_charging type="boolean">true</is_charging>
<level type="number">0.95</level>
</battery>
<extras type="object"></extras>
</location>
</root>
```

**Comment by christocracy** [comment]
The plugin isn’t concerned with what goes on behind the curtains at your server.  The data got there.  The plugin’s part of the deal is fulfilled.

It’s up to you to view the published Location Data Schema (see wiki) and determine how to transform that into your own data model.

**Comment by itsupportvspl** [comment]
hi ,

i want to send the lat and lng in URL itself here i am sending URL but it received as null .
below is the URL , why it is going as null.

SERVER_URL_PREFIX+"/Service/Service.svc/RunStoredProcedureNonQuery?ConnectionString_Encrypted=FAICTranDBConnection&ProcedureName_Encrypted=Gpstrack&ParametersList_Encrypted="+userName+"|"+APP_VER+"|"+APP_CODE+"|"+lat+"|"+lng

**Comment by christocracy** [comment]
This is impossible.

**Comment by christocracy** [comment]
Think about it:  you’d have to change the url every time a new location is recorded.

**Comment by itsupportvspl** [comment]
yes .

then how to capture the lat and lng server side

**Comment by christocracy** [comment]
The plugin **IS ALREADY SENDING IT TO YOUR SERVER**.  Your server code is too dumb to figure it out.

**Comment by christocracy** [comment]
There is the [Location Data Schema](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema#http-post-schema).

The data exists in the **BODY** of the HTTP Request.

**Comment by itsupportvspl** [comment]
In BODY we don't need that's what i asked earlier in this issue .

Thanks.

**Comment by christocracy** [comment]
In the BODY of the http request is where you’ll find the data.

The plugin isn’t going to post the data in the url.  That would be incredibly stupid.
