### ISSUE TITLE
Can't install plugin - Could not find :tslocationmanager: and Failed to install 'cordova-plugin-background-fetch'

### ISSUE THREAD

**Issue by dudunegrinhu** [transistorsoft/cordova-background-geolocation-lt#504]
ionic/cli-utils  : 1.14.0
ionic (Ionic CLI) : 3.14.0
cordova (Cordova CLI) : 7.1.0 

local packages:

@ionic/app-scripts : 1.3.7
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.4.0

System:

    ios-sim : 5.0.13 
    Node    : v6.11.4
    npm     : 3.10.10 
    OS      : macOS Sierra
    Xcode   : Xcode 9.0.1 Build version 9A1004 

I'm having the license failure error so I removed the plugin and tried to add again but when I try to add I receive this error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find :tslocationmanager:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.288 secs
Failed to install 'cordova-plugin-background-fetch': Error: /platforms/android/gradlew: Command failed with exit code 1

So I tried to install cordova-plugin-background-fetch separate and I get the same error.

**Comment by christocracy** [comment]
Customers aren’t supposed to use the public repo.  This repo only gets updated every few months.

Nevertheless, if you really want to use this version:  when in doubt, remove / re-add the platform.

**Comment by dudunegrinhu** [comment]
My license is still valid but I can't access private repo anymore. Do I need to pay again to access?

**Comment by christocracy** [comment]
IF your subscription expired, login to dashboard and click [Renew] button.

**Comment by christocracy** [comment]
Is this still an issue?

**Comment by dudunegrinhu** [comment]
Yes. I installed from Private repo and still the same issue. Do you want me to post on the private git?

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find :tslocationmanager:.

**Comment by christocracy** [comment]
Yes, post to private repo.
