### ISSUE TITLE
Failed to install 'cordova-background-geolocation-lt'

### ISSUE THREAD

**Issue by psonawane-servicetitan** [transistorsoft/cordova-background-geolocation-lt#505]
Hi,
I am working on cordova version 7.1.0
I am trying to build the cordova project for ios platform but I keep getting this error. Despite of adding this in package.json:

"cordova-plugin-background-fetch": "~5.1.0",
    "cordova-plugin-background-mode": "~0.7.2",
    "cordova-plugin-camera": "git+https://github.com/apache/cordova-plugin-camera.git",
    "cordova-plugin-cocoalumberjack": "0.0.4",
    "cordova-plugin-compat": "^1.1.0",

Failed to install 'cordova-background-geolocation-lt': CordovaError: Version of installed plugin: "cordova-plugin-background-fetch@4.0.0" does not satisfy dependency plugin requirement "cordova-plugin-background-fetch@~5.1.1". Try --force to use installed plugin as dependency.
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Failed to restore plugin "com.transistorsoft.cordova.background-geolocation" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "cordova-plugin-background-fetch@4.0.0" does not satisfy dependency plugin requirement "cordova-plugin-background-fetch@~5.1.1". Try --force to use installed plugin as dependency.

Can you please suggest something?

**Comment by christocracy** [comment]
It’s true, background-fetch 5.1.1 is required by the current version of background-geolocation.

When in doubt, remove the plugin and re-install

**Comment by psonawane-servicetitan** [comment]
I removed and reinstalled the plugin. Then removed and added the ios platform again. But still the project doesn't build successfully.

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by christocracy** [comment]
Hello, feedback please.

**Comment by psonawane-servicetitan** [comment]
Hello, after removing and adding back, it worked fine. Thanks for your prompt help!

**Comment by Fdgroups** [comment]
i am also getting same error 
$ ionic cordova plugin add cordova-background-geolocation-lt
> cordova.cmd plugin add cordova-background-geolocation-lt
Cannot find plugin.xml for plugin "cordova-background-geolocation-lt". Please try adding it again.
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd plugin add cordova-background-geolocation-lt exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

 cordova plugins
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 3.0.1 "CDVBackgroundGeolocation"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"

**Comment by christocracy** [comment]
Get rid of this:

cordova-plugin-mauron85-background-geolocation 3.0.1

**Comment by dapchanvabatquat** [comment]
I am having the same problem when building ios
```
khoanait@MacBook-Air TRACKING_HM_RL % sudo  cordova platform add ios    
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.trungviet.HMSales
	Name: Vicem Hoang Mai Sales
iOS project created with cordova-ios@5.1.1
Installing "cordova-background-geolocation-lt" for ios
Plugin dependency "cordova-plugin-background-fetch@6.1.1" already fetched, using that version.
Installing "cordova-plugin-background-fetch" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Failed to install 'cordova-background-geolocation-lt': undefined
CordovaError: Promise rejected with non-error: '/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/khoanait/Documents/IONIC in PATH, mode 040777\n/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:439:in `help!\': \u001b[31m[!] You cannot run CocoaPods as root.\u001b[39m (CLAide::Help)\n\n\u001b[4mUsage:\u001b[24m\n\n    $ \u001b[32mpod\u001b[39m \u001b[32mCOMMAND\u001b[39m\n\n      CocoaPods, the Cocoa library package manager.\n\n\u001b[4mCommands:\u001b[24m\n\n    \u001b[32m+ cache\u001b[39m      Manipulate the CocoaPods cache\n    \u001b[32m+ env\u001b[39m        Display pod environment\n    \u001b[32m+ init\u001b[39m       Generate a Podfile for the current directory\n    \u001b[32m+ install\u001b[39m    Install project dependencies according to versions from a\n                 Podfile.lock\n    \u001b[32m+ ipc\u001b[39m        Inter-process communication\n    \u001b[32m+ lib\u001b[39m        Develop pods\n    \u001b[32m+ list\u001b[39m       List pods\n    \u001b[32m+ outdated\u001b[39m   Show outdated project dependencies\n    \u001b[32m+ repo\u001b[39m       Manage spec-repositories\n    \u001b[32m+ setup\u001b[39m      Setup the CocoaPods environment\n    \u001b[32m+ spec\u001b[39m       Manage pod specs\n    \u001b[32m+ update\u001b[39m     Update outdated project dependencies and create new Podfile.lock\n\n\u001b[4mOptions:\u001b[24m\n\n    \u001b[34m--silent\u001b[39m     Show nothing\n    \u001b[34m--version\u001b[39m    Show the version of the tool\n    \u001b[34m--verbose\u001b[39m    Show more debugging information\n    \u001b[34m--no-ansi\u001b[39m    Show output without ANSI codes\n    \u001b[34m--help\u001b[39m       Show help banner of specified command\n\tfrom /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:47:in `run\'\n\tfrom /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>\'\n\tfrom /usr/local/bin/pod:23:in `load\'\n\tfrom /usr/local/bin/pod:23:in `<main>\'\n'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I removed the ios platform and reinstalled but nothing has changed

**Comment by christocracy** [comment]
Are you reading the error message?  None of that has anything to do with this plugin.

You have a problem with your dev environment setup.  Google your errors.

**Comment by christocracy** [comment]
>sudo  cordova platform add ios 

You should never be using `sudo` with the Cordova CLI.  If you *have* to, it's a sign that your development environment is not set up correctly.

**Comment by shahdeep1989** [comment]
@christocracy 

Facing same issue. Failed to install plugin for iOS.

cordova platforms add ios
Using cordova-fetch for cordova-ios@^6.2.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.mysmartjarvis.com
	Name: mySmartJarvis
iOS project created with cordova-ios@6.2.0
config file *.entitlements requested for changes not found at Project/platforms/ios/*.entitlements, ignoring
Installing "cordova-background-geolocation-lt" for ios
Plugin dependency "cordova-plugin-background-fetch@7.1.1" already fetched, using that version.
Installing "cordova-plugin-background-fetch" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Failed to install 'cordova-background-geolocation-lt': Error: pod: Command failed with exit code 1 Error output:
Ignoring ffi-1.15.5 because its extensions are not built.  Try: gem pristine ffi --version 1.15.5
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
/Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflector/inflections.rb:145:in `plural': undefined method `prepend' for []:Array (NoMethodError)
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflections.rb:13:in `block in <module:ActiveSupport>'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflector/inflections.rb:249:in `inflections'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflections.rb:12:in `<module:ActiveSupport>'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflections.rb:11:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/core_ext/string/inflections.rb:3:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/cocoapods-1.11.3/lib/cocoapods.rb:8:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/cocoapods-1.11.3/bin/pod:36:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/bin/pod:23:in `load'
	from /Users/deepshah/.rbenv/versions/2.3.0/bin/pod:23:in `<main>'
    at ChildProcess.whenDone (*********/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
pod: Command failed with exit code 1 Error output:
Ignoring ffi-1.15.5 because its extensions are not built.  Try: gem pristine ffi --version 1.15.5
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
/Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflector/inflections.rb:145:in `plural': undefined method `prepend' for []:Array (NoMethodError)
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflections.rb:13:in `block in <module:ActiveSupport>'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflector/inflections.rb:249:in `inflections'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflections.rb:12:in `<module:ActiveSupport>'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflections.rb:11:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/core_ext/string/inflections.rb:3:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/cocoapods-1.11.3/lib/cocoapods.rb:8:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/cocoapods-1.11.3/bin/pod:36:in `<top (required)>'
	from /Users/deepshah/.rbenv/versions/2.3.0/bin/pod:23:in `load'
	from /Users/deepshah/.rbenv/versions/2.3.0/bin/pod:23:in `<main>'

**Comment by christocracy** [comment]
The original error of this *closed* issue is:

> CordovaError: Version of installed plugin: "cordova-plugin-background-fetch@4.0.0" does not satisfy dependency plugin requirement "cordova-plugin-background-fetch@~5.1.1"

Your error is *not* the same.  Post a new issue.

```
Failed to install 'cordova-background-geolocation-lt': Error: pod: Command failed with exit code 1 Error output:
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
/Users/deepshah/.rvm/gems/ruby-2.6.6@global/gems/activesupport-6.1.4.6/lib/active_support/inflector/inflections.rb:145:in plural': undefined method prepend' for []:Array (NoMethodError)
```

**Comment by shahdeep1989** [comment]
@christocracy 
[Posted new issue.](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1359)
