### ISSUE TITLE
Missing background-fetch event, as seen in Debug-Mode,

### ISSUE THREAD

**Issue by mcdroemmel** [transistorsoft/cordova-background-geolocation-lt#508]
Hello,

first of all: this is a great plugin and it solves nearly all the things a developer needs to work with gps enabled apps.
But one thing could be enhanced from my point of view. When enabling debugging (which is also great implemented for testing the apps gps functionality in background) i get popup-notification about almost every event the plugin fires. I also see, that a debug-notifications shows that a background-fetch was received. But for receiving a background-fetch (which the plugin seems to receive because of the debug message), there is no event-handler implemented for the plugin-user in javascript.
That would be very helpfull because my app needs to do some additional background work (synchronize data, in addition to gps-data, to a backend-system). Using another plugin for background-fetch (i found an additional background-fetch plugin from transistorsoft) seems to influence each other. A background-fetch then only is fired once. 
I think i can do a workaround at the moment using location events and, when in stationary using hear-beat events), but the background-fetch event would be better, even because i don't have to use the heartbeat-events and it would be enough from the aspect of timing to use the background-fetch event.

kind regards
Matthias

**Comment by christocracy** [comment]
background-fetch was designed as *a dependency of* this plugin.  It’s *already* included.  You don’t need to install it.

It’s already available to you at window.BackgroundFetch.

See the docs for that plugin and simply use it as documented.
