### ISSUE TITLE
I need a help to get Locations in background using HTTP.

### ISSUE THREAD

**Issue by brunoheringer** [transistorsoft/cordova-background-geolocation-lt#509]
## Your Environment
* Plugin version: version="2.7.4"
* Platform: iOS and Android
* OS version: all
* Cordova version: 7.0.1
* Cordova platform version: Installed platforms: 6.1.0
* Plugin config
bgGeo.configure({
                desiredAccuracy: 0, 
                distanceFilter: 0, 
                locationUpdateInterval: 10000, 
                stationaryRadius: 25, 
                
                activityType: 'AutomotiveNavigation', 
                activityRecognitionInterval: 2000,  

                stopOnTerminate: false, 
                startOnBoot: true, 
                debug: true,
                foregroundService: true,
                schedule: agendamentos,
                logLevel: bgGeo.LOG_LEVEL_VERBOSE,  

                // HTTP (RUNNING WHEN APP IS CLOSED)
                url: constantes.URL_WS + "/evento/AlterarLocalizacaoConvidadosHttp",
                autoSync: true,
                httpTimeout: 3000,
                logMaxDays: 1,
                method: 'POST',
                httpRootProperty: 'data',
                locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>}',
                extras: {
                    "idUsuario": util.getUsuarioLogado().id,
                },
                headers: {
                    'Access-Control-Allow-Credentials': 'true',
                    'Access-Control-Allow-Origin': '*',
                    'Accept': 'application/json',
                    'x-app-u': util.getUUIDLocal(),
                    'x-app-k': util.getUsuarioLogado().id,
                }
            });

## Expected Behavior
I would like to receive mobile's locations in my Server.

## Context
I'm using HTTP for send Locations to my server. 

## Debug logs
10-30 14:48:09.066 INFO [Settings print] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Settings
╠═════════════════════════════════════════════
{
  "isMoving": false,
  "enabled": false,
  "odometer": 0,
  "schedulerEnabled": false,
  "trackingMode": "location",
  "distanceFilter": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "locationUpdateInterval": 10000,
  "fastestLocationUpdateInterval": 10000,
  "locationTimeout": 60,
  "deferTime": 0,
  "disableElasticity": false,
  "activityRecognitionInterval": 2000,
  "minimumActivityRecognitionConfidence": 75,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "disableStopDetection": false,
  "stationaryRadius": 25,
  "stopTimeout": 5,
  "stopOnStationary": false,
  "url": "MyURL",
  "method": "POST",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "maxBatchSize": -1,
  "params": {},
  "headers": {
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Origin": "*",
    "Accept": "application\/json",
    "x-app-k": 66
  },
  "extras": {
    "idUsuario": 66
  },
  "httpRootProperty": "data",
  "locationTemplate": "{\"lat\":<%= latitude %>,\"lng\":<%= longitude %>}",
  "geofenceTemplate": "",
  "persist": true,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "httpTimeout": 3000,
  "geofenceProximityRadius": 1000,
  "geofenceInitialTriggerEntry": true,
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": -1,
  "foregroundService": true,
  "notificationTitle": "",
  "notificationText": "Location Service activated",
  "notificationColor": "",
  "notificationIcon": "",
  "notificationSmallIcon": "",
  "notificationLargeIcon": "",
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnBoot": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnSchedule": false,
  "stopAfterElapsedMinutes": 0,
  "schedule": [
    "2 14:50-18:00"
  ],
  "configureUrl": "",
  "configureInterval": -1,
  "debug": true,
  "logLevel": 5,
  "logMaxDays": 3
}╚═════════════════════════════════════════════
10-30 14:48:09.086 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

**Comment by brunoheringer** [comment]
I can't to receive locations in my server.

**Comment by christocracy** [comment]
That's not very many logs you're showing.  The plugin stores 3 days worth of logs.

**Comment by christocracy** [comment]
and *please* use a more descriptive subject than "I Need help".

**Comment by christocracy** [comment]
There's nothing to say until you post more logs.

**Comment by brunoheringer** [comment]
My last log. 
I don't have more logs. I starter use this now. 

10-30 14:46:59.633 INFO [Settings print] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Settings
╠═════════════════════════════════════════════
{
  "isMoving": false,
  "enabled": false,
  "odometer": 0,
  "schedulerEnabled": false,
  "trackingMode": "location",
  "distanceFilter": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "locationUpdateInterval": 10000,
  "fastestLocationUpdateInterval": 10000,
  "locationTimeout": 60,
  "deferTime": 0,
  "disableElasticity": false,
  "activityRecognitionInterval": 2000,
  "minimumActivityRecognitionConfidence": 75,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "disableStopDetection": false,
  "stationaryRadius": 25,
  "stopTimeout": 5,
  "stopOnStationary": false,
  "url": "http:\/\/des.qwti.com.br:8989\/Gofree\/dev\/ws\/evento\/AlterarLocalizacaoConvidadosHttp",
  "method": "POST",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "maxBatchSize": -1,
  "params": {},
  "headers": {
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Origin": "*",
    "Accept": "application\/json",
    "x-app-k": 66
  },
  "extras": {
    "idUsuario": 66
  },
  "httpRootProperty": "data",
  "locationTemplate": "{\"lat\":<%= latitude %>,\"lng\":<%= longitude %>}",
  "geofenceTemplate": "",
  "persist": true,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "httpTimeout": 3000,
  "geofenceProximityRadius": 1000,
  "geofenceInitialTriggerEntry": true,
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": -1,
  "foregroundService": true,
  "notificationTitle": "",
  "notificationText": "Location Service activated",
  "notificationColor": "",
  "notificationIcon": "",
  "notificationSmallIcon": "",
  "notificationLargeIcon": "",
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnBoot": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnSchedule": false,
  "stopAfterElapsedMinutes": 0,
  "schedule": [
    "2 13:00-18:00"
  ],
  "configureUrl": "",
  "configureInterval": -1,
  "debug": true,
  "logLevel": 5,
  "logMaxDays": 3
}╚═════════════════════════════════════════════
10-30 14:46:59.659 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

10-30 14:48:09.066 INFO [Settings print] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Settings
╠═════════════════════════════════════════════
{
  "isMoving": false,
  "enabled": false,
  "odometer": 0,
  "schedulerEnabled": false,
  "trackingMode": "location",
  "distanceFilter": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "locationUpdateInterval": 10000,
  "fastestLocationUpdateInterval": 10000,
  "locationTimeout": 60,
  "deferTime": 0,
  "disableElasticity": false,
  "activityRecognitionInterval": 2000,
  "minimumActivityRecognitionConfidence": 75,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "disableStopDetection": false,
  "stationaryRadius": 25,
  "stopTimeout": 5,
  "stopOnStationary": false,
  "url": "http:\/\/des.qwti.com.br:8989\/Gofree\/dev\/ws\/evento\/AlterarLocalizacaoConvidadosHttp",
  "method": "POST",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "maxBatchSize": -1,
  "params": {},
  "headers": {
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Origin": "*",
    "Accept": "application\/json",
    "x-app-k": 66
  },
  "extras": {
    "idUsuario": 66
  },
  "httpRootProperty": "data",
  "locationTemplate": "{\"lat\":<%= latitude %>,\"lng\":<%= longitude %>}",
  "geofenceTemplate": "",
  "persist": true,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "httpTimeout": 3000,
  "geofenceProximityRadius": 1000,
  "geofenceInitialTriggerEntry": true,
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": -1,
  "foregroundService": true,
  "notificationTitle": "",
  "notificationText": "Location Service activated",
  "notificationColor": "",
  "notificationIcon": "",
  "notificationSmallIcon": "",
  "notificationLargeIcon": "",
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnBoot": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnSchedule": false,
  "stopAfterElapsedMinutes": 0,
  "schedule": [
    "2 14:50-18:00"
  ],
  "configureUrl": "",
  "configureInterval": -1,
  "debug": true,
  "logLevel": 5,
  "logMaxDays": 3
}╚═════════════════════════════════════════════
10-30 14:48:09.086 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

10-30 15:29:45.692 INFO [a a] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="BOSCH BMC150 Acceleration Sensor", vendor="Bosch Sensortec, GmbH", version=1, type=1, maxRange=156.88, resolution=0.019150391, power=0.13, minDelay=10000}
╟─ ✅  GYROSCOPE: {Sensor name="BOSCH Gyroscope Sensor", vendor="Bosch Sensortec, GmbH", version=1, type=4, maxRange=2000.0, resolution=0.0030517578, power=5.0, minDelay=10000}
╟─ ✅  MAGNETOMETER: {Sensor name="BOSCH BMC150 Magnetic Field Sensor", vendor="Bosch Sensortec, GmbH", version=1, type=2, maxRange=1600.0, resolution=0.3, power=0.5, minDelay=50000}
╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
╚═════════════════════════════════════════════
10-30 15:29:45.732 INFO [BackgroundGeolocation <init>] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation adapter
╠═════════════════════════════════════════════

10-30 15:29:45.756 DEBUG [SQLiteLocationDAO dbh] 
  ✅  Opened database
10-30 15:29:45.763 DEBUG [SQLiteLocationDAO prune] 
  ℹ️  PRUNE -1 days
10-30 15:29:45.837 DEBUG [GeofenceDAO dbh] 
  ✅  Opened database
10-30 15:29:45.852 INFO [BackgroundGeolocation <init>] 
  🔵  Connecting to GooglePlayServices...
10-30 15:29:45.892 INFO [BackgroundGeolocation onConnected] 
  ✅  Google Play Services: connected (version code:9256000)
10-30 15:29:45.908 INFO [Settings print] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Settings
╠═════════════════════════════════════════════
{
  "isMoving": false,
  "enabled": false,
  "odometer": 0,
  "schedulerEnabled": false,
  "trackingMode": "location",
  "distanceFilter": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "locationUpdateInterval": 10000,
  "fastestLocationUpdateInterval": 10000,
  "locationTimeout": 60,
  "deferTime": 0,
  "disableElasticity": false,
  "activityRecognitionInterval": 2000,
  "minimumActivityRecognitionConfidence": 75,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "disableStopDetection": false,
  "stationaryRadius": 25,
  "stopTimeout": 5,
  "stopOnStationary": false,
  "url": "http:\/\/des.qwti.com.br:8989\/Gofree\/dev\/ws\/evento\/AlterarLocalizacaoConvidadosHttp",
  "method": "POST",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "maxBatchSize": -1,
  "params": {},
  "headers": {
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Origin": "*",
    "Accept": "application\/json",
    "x-app-k": 66
  },
  "extras": {
    "idUsuario": 66
  },
  "httpRootProperty": "data",
  "locationTemplate": "{\"lat\":<%= latitude %>,\"lng\":<%= longitude %>}",
  "geofenceTemplate": "",
  "persist": true,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "httpTimeout": 3000,
  "geofenceProximityRadius": 1000,
  "geofenceInitialTriggerEntry": true,
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": -1,
  "foregroundService": true,
  "notificationTitle": "",
  "notificationText": "Location Service activated",
  "notificationColor": "",
  "notificationIcon": "",
  "notificationSmallIcon": "",
  "notificationLargeIcon": "",
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnBoot": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnSchedule": false,
  "stopAfterElapsedMinutes": 0,
  "schedule": [
    "2 14:50-18:00"
  ],
  "configureUrl": "",
  "configureInterval": -1,
  "debug": true,
  "logLevel": 5,
  "logMaxDays": 3
}╚═════════════════════════════════════════════
10-30 15:29:45.935 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

**Comment by christocracy** [comment]
Show me your JavaScript

**Comment by brunoheringer** [comment]
My field "agendamentos" is: "2 14:50-18:00"

function configurarBackgroundLocation(agendamentos, logSistema) {
    try {
        if (!bgGeo) {
            bgGeo = window.BackgroundGeolocation;
        }
        if (bgGeo) {
            bgGeo.configure({
                desiredAccuracy: 0, //100 // 0, 10, 100, 1000 where 0 means HIGHEST POWER, HIGHEST ACCURACY and 1000 means LOWEST POWER, LOWEST ACCURACY
                distanceFilter: 0, //25 // The minimum distance (measured in meters) a device must move horizontally before an update event is generated.
                locationUpdateInterval: 10000, // 10000 With distanceFilter: 0, Sets the desired interval for location updates, in milliseconds. Set the desired interval for active location updates, in milliseconds. The location client will actively try to obtain location updates for your application at this interval, so it has a direct influence on the amount of power used by your application. Choose your interval wisely.
                stationaryRadius: 25, // 25 Minimo
                
                activityType: 'AutomotiveNavigation', // Produção setar para 'AutomotiveNavigation',
                activityRecognitionInterval: 2000,  //10000

                stopOnTerminate: false, //Falso para rodar em background
                startOnBoot: true, // True para iniciar ao iniciar o boot do celular
                //stopOnStationary: true, //Produção setar para falso
                debug: true,
                foregroundService: true,
                schedule: agendamentos,
                logLevel: bgGeo.LOG_LEVEL_VERBOSE,  //LOG_LEVEL_OFF -> LOG_LEVEL_VERBOSE

                // HTTP (RUNNING WHEN APP IS CLOSED)
                url: constantes.URL_WS + "/evento/AlterarLocalizacaoConvidadosHttp",
                autoSync: true,
                httpTimeout: 3000,
                logMaxDays: 1,
                method: 'POST',
                httpRootProperty: 'data',
                locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>}',
                extras: {
                    "idUsuario": util.getUsuarioLogado().id,
                },
                headers: {
                    'Access-Control-Allow-Credentials': 'true',
                    'Access-Control-Allow-Origin': '*',
                    'Accept': 'application/json',
                    'x-app-u': util.getUUIDLocal(),
                    'x-app-k': util.getUsuarioLogado().id,
                }
            });
            logSistema.cadastrar("GeoLocalização", "ConfigurarBackGroundLocation | Passou pela config: " + util.getUsuarioLogado().id + " | " + agendamentos);
            
            //bgGeo.on('providerchange', function (provider) {
            //    switch (provider.status) {
            //        case bgGeo.AUTHORIZATION_STATUS_DENIED:
            //            // Android & iOS
            //            alert('- Location authorization denied');
            //            break;
            //        case bgGeo.AUTHORIZATION_STATUS_ALWAYS:
            //            // Android & iOS
            //            alert('- Location always granted');
            //            break;
            //        case bgGeo.AUTHORIZATION_STATUS_WHEN_IN_USE:
            //            // iOS only
            //            alert('- Location WhenInUse granted');
            //            break;
            //    }
            //});
        }
    }
    catch (e) {
        logSistema.cadastrar("GeoLocalização", "ConfigurarBackGroundLocation | Erro: " + e.message + e.stack);
    }
}

**Comment by christocracy** [comment]
You aren’t *starting* the plugin.

See docs for #configure and #startSchedule.

**Comment by brunoheringer** [comment]
Thank you
