### ISSUE TITLE
runtine crash on android

### ISSUE THREAD

**Issue by PauloBronfox** [transistorsoft/cordova-background-geolocation-lt#51]
When I run the app on android:
cordova app run native

the build goes fine but I get a runtime error (the app crashes):
01-10 17:59:53.826: E/AndroidRuntime(18721): java.lang.VerifyError: com/transistorsoft/locationmanager/a
01-10 17:59:53.826: E/AndroidRuntime(18721): 	at com.transistorsoft.locationmanager.BackgroundGeolocationService.onStartCommand(Unknown Source)

Do you have an idea ?

**Comment by christocracy** [comment]
There is no Android in this "lite" version.  It's [iOS only](https://github.com/transistorsoft/cordova-background-geolocation-lt#premium-version-ios)

You need to purchase a [Premium Version License](http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium) to get Android.

There's a link on the page above to install the [Sample app](https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic) from google play store.
