### ISSUE TITLE
Example post request

### ISSUE THREAD

**Issue by alexcroox** [transistorsoft/cordova-background-geolocation-lt#511]
I'm trying to work out what post data is sent to the http url. I've created a simple php endpoint with the following in order to work it out:

```
file_put_contents( 'debug' . time() . '.log', var_export( $_POST, true));
```

however the contents of $_POST are always empty, despite `bgGeo.on('http', function(response) {` triggering successfully. 

Is the layout of the posted data sent to the endpoint documented anywhere?

**Comment by christocracy** [comment]
You can see the [Location Data Schema](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema) in Wiki.

However, you won't find the data in PHP's `$_POST` (that's for web-forms.  The plugin doesn't post a web-form).

See #2

**Comment by alexcroox** [comment]
Perfect, thank you!!

**Comment by christocracy** [comment]
Btw, the plugin http handler returns success when your server returns a 200 response.

To signal a failure, send a non-200 response from server.
