### ISSUE TITLE
Android, regular location updates regardless of movement

### ISSUE THREAD

**Issue by alexcroox** [transistorsoft/cordova-background-geolocation-lt#512]
I would like for my app to report a location position to the endpoint every x seconds (10 seconds during testing). I would like this to happen regardless of motion or any other factor that the plugin might prevent it being sent for battery saving reasons.

## Your Environment
* Plugin version: 2.8.5
* Platform: Android
* OS version: 5.0.2
* Device manufacturer / model: HTC One
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config

```
bgGeo.configure({
    desiredAccuracy: 20,
    distanceFilter: 0,
    disableElasticity: true,
    disableStopDetection: true,
    stationaryRadius: 25,
    activityRecognitionInterval: 10000,
    locationUpdateInterval: 10000,
    stopTimeout: 60, 
    debug: true,
    stopOnTerminate: false,
    startOnBoot: true,
    url: "https://xxxx.xx/location-test/index.php",
    method: "POST",
    autoSync: true,
    maxDaysToPersist: 3,
    headers: { 
        "X-FOO": "bar"
    },
    params: { 
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
    }
}, function(state) {
    // This callback is executed when the plugin is ready to use.
    log("BackgroundGeolocation ready: ", state);
    if (!state.enabled) {
        log('Tracking auto started');
        bgGeo.start();
    }
}
```

## Expected Behavior
I'm sat indoors with the phone plugged in. I have therefore reduced accuracy to 20m (gps accuracy at my desk comes in at 10-20).

I expect location events to be sent to my http endpoint every 10 seconds.

I have only tested this with the app active, no background testing yet.

## Actual Behavior
I should get a location event sent to the endpoint every 10 seconds, however all that I receive is 2 `motionchange` events, and zero location http calls.

I have even tried a button that fires `bgGeo.changePace(true);` to see if that forces it to start sending, it does not, I simply get another motionchange http call with is_moving changed to 1.

## Steps to Reproduce
index.js -> https://pastebin.com/u1QFucvG

**Comment by alexcroox** [comment]
I've just been looking into getting the debug logs, and there I found my answer :)

ℹ️  IGNORED: same as last location

I would still like to send duplicate gps coords every x seconds, what is recommended for this?

**Comment by christocracy** [comment]
Why?

**Comment by alexcroox** [comment]
Not sure if you saw my ninja edit above, it's for a fleet tracking app and I will need to show "updated x minutes ago" in the HQ web app, even if they leave the phone in the car during a lunch break.

**Comment by christocracy** [comment]
If they leave their phone in the car "during lunch break", the plugin will enter stationary-mode (firing the `motionchange` event) and the `heartbeat` event will begin firing.  You're free to perform your own `#getCurrentPosition` within the `heartbeat` callback.  (`heartbeat` fires with minimum 60s frequency).

```javascript
bgGeo.on('heartbeat', function(event) {
  bgGeo.getCurrentPosition(success, error);
});
```

**Comment by alexcroox** [comment]
If I set a high value e.g `stopTimeout: 120` would that prevent it entering stationary-mode?

**Comment by christocracy** [comment]
`stopTimeout: 120` would be a very **bad** idea.  You shouldn't set this any higher than `15` minutes.

Android is *very* good at detecting motion within a few meters of movement.

**Comment by alexcroox** [comment]
Could you explain why it would be a bad idea if my goal is to send location updates every x seconds regardless of what the driver is doing or not doing?

**Comment by christocracy** [comment]
And yes, `stopTimeout` will prevent the `heartbeat` event firing until the device is completely still for **2 hours**.  Don't do that.

**Comment by alexcroox** [comment]
Not sure if you noticed my edit above but would `disableStopDetection: true` mean the plugin will continue sending location updates every x seconds even if the user has stopped for an hour?

**Comment by christocracy** [comment]
Just let the plugin enter stationary-mode and take advantage of the `heartbeat` event.

**Comment by alexcroox** [comment]
I could definitely utilise heartbeat, since my updates will be probably be every 1 minute regardless. However if I don't need to write additional http calls myself I'd rather not. Especially if heartbeat would be doing effectively the same thing as `locationUpdateInterval: 60000, disableStopDetection: true`

**Comment by christocracy** [comment]
`disableStopDetection: true` will prevent the plugin ever entering `stationary` mode once in `moving` mode.  You will never see `heartbeat` events until you explicitly `changePace(false)`

**Comment by alexcroox** [comment]
OK so I think the root of the issue here is that if the GPS doesn't change no amount of configuration will overcome that to send an event, so I will definitely have to use heartbeat to make my own http call.

Not a problem, just wanted to avoid writing additional code if it wasn't needed through some configuration combination :)

Thanks for your quick help!

**Comment by christocracy** [comment]
>However if I don't need to write additional http calls myself I'd rather not.

`#getCurrentPosition` will insert a location into the plugin's database and the plugin's HTTP Service will sync it just like any other recorded location.

**Comment by alexcroox** [comment]
Ah even better, thanks!
