### ISSUE TITLE
HTTP POST to server with a minimum interval

### ISSUE THREAD

**Issue by Alienspacecow** [transistorsoft/cordova-background-geolocation-lt#514]
## Your Environment
* Plugin version: 2.8.5
* Cordova version: 7.1.0
* Cordova platform version: Android 6.3.0, IOS 4.5.3
* Plugin config:
bgGeo.configure({
	url: "https://api.domain.com",
	autoSync: true,
	httpTimeout: 3000,
	locationTemplate: '{"lat":<%= latitude %>, "lng":<%= longitude %>}',
	method: 'POST',
	desiredAccuracy: 0,
	distanceFilter: 20,
	stationaryRadius: 25,
	activityRecognitionInterval: 60000,
	stopTimeout: 5,
	stopOnTerminate: false,
	startOnBoot: true,
	locationUpdateInterval: 60000,
	preventSuspend: true,
	schedule: [
		'1,2,3,4,5,6,7 8:00-21:00'
	  ]
});

## Expected Behavior
I want to send a POST to the server on the background with a minimum of 60 seconds between the posts.

## Actual Behavior
It seems not to be possible to manipulate the http interval so I changed the activityRecognitionInterval and locationUpdateInterval to 60000 in the hope they prevent flooding the server. Not helping at all, in some cases I receive 5 requests per minute (usually iPhones).

## Context
I want to configure the app in the way that it:
- runs quite on iPhone and Android in the background 
- only send GPS coordinates to the server when it is not on "in_vehicle" activity and is moving
- with a minimum of 60 seconds between posts

Thank you

**Comment by christocracy** [comment]
`activityRecognitionInterval` has nothing to do with this.  You will affect the sensitivity of motion-triggering (particularly with Android) if you set that too high.

You cannot specify a time but you *can* specify an [`autoSyncThreshold`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#wrench-http--persistence-options)

Have you tried reading *all* the available [HTTP & Persistence Options](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#wrench-http--persistence-options)

**Comment by christocracy** [comment]
And on Android, you can specify a [`deferTime`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-defertime).

This will throttle locations being sent to your Javascript callbacks as well.  This setting can save energy and improve accuracy on Android too.

**Comment by Alienspacecow** [comment]
I understand.

When the app is running in the background the callback functions won't work offcourse. Is there another possibility to prevent HTTP Posts when the activity is in_vehicle?

**Comment by christocracy** [comment]
>When the app is running in the background the callback functions won't work

False.  Do you mean **terminated**?  *background* and *terminated* are two completely different states.

See [`triggerActivities`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-string-triggeractivities)

Are you reading the docs?

**Comment by Alienspacecow** [comment]
Yes, i'm sorry. I'm reading the docs but when English is not your main language and the docs are that big and contain all kind of new terms it's easy to read over some (for other clear) possiblities and functions.

Thank you for your help.
