### ISSUE TITLE
How to proactively determine Location Authorization status on iOS?

### ISSUE THREAD

**Issue by stib** [transistorsoft/cordova-background-geolocation-lt#515]
Hello,

I have been using the `locationAuthorizationAlert` parameter to inform the user when Location is not authorized to 'Always' to enable background location. The related dialog comes up with the message in the `instructions` section of `locationAuthorizationAlert` when I try to get currentLocation using the plugin. That's working as expected.

However, I would like to proactively detect the status of Location authorization and show that to the User on the home/landing page and also before the User takes certain actions that require such authorization. Monitoring `providerChange` gives information on Location changes after the User makes them.

Is there a way to proactively determine the current Location Authorization status in iOS?

Thanks,
Sanjay.

**Comment by christocracy** [comment]
You don’t need to explicitly ask for them.  Just listen to providerchange and store that information in your own app (eg localStorage).

**Comment by stib** [comment]
Thanks @christocracy. Didn't realize that the providerchange monitoring code gets invoked when the App is brought back up even when the Location change is made while App is not running. On testing it seems to do that. Will save that info in localStorage as you suggest. 

When I do detect a change when the User modified the Location permission to something other than 'Always' and I want to show an Alert to the User at an appropriate time, as is shown with `locationAuthorizationAlert` with the `Settings` tab to enable the User to go change the Location permissions, can I trigger that Alert to show up through code with custom message at different points with the Settings tab?

**Comment by christocracy** [comment]
The alert popup is handled automatically.  If you want to force it to show, you could call the `#start` method.  If you want to hide the alert, call the `#stop` method.

**Comment by stib** [comment]
Thank you @christocracy. It seems it would be helpful to provide a better User experience by enabling - 

1. Control of content of the alert shown (please let me know if it is already there and I missed it)
2. More control over whether/when to show the alert. Because if the User has ignored the alert in the past and the App can function in a limited way with "While In Use" then no point showing the alert pop up every time (if the User has chosen 'When In Use') which will degrade the User experience. Instead I would like to have a colored indication on the screen that the Location is not being tracked when App is in background and a button to click on that will bring up the Settings to go change that if User wants to.

With iOS 11 where I understand Users get to pick 'When In Use' or 'Always' on one screen it is likely more Users may initially choose to go with 'When In Use' and this capability will help provide a better User experience if they have ignored it in the past.

Please let me know whether this is something that is worth considering adding or if you have a different perspective/workaround that I may be missing.

Thanks,
Sanjay.

**Comment by stib** [comment]
@christocracy per your suggestion I used providerChange to capture Location changes by the User, save it in localStorage and use that to manage and warn the User where appropriate.

However, while providerChange works fine in debug mode on iPhone (and Android), when I created a release version with XCode (Archive, Export and install that on the iPhone) and tested that before deploying, I found the providerChange is not triggered when the App starts or when I make any Location changes for the App. To make sure, I added Alerts to show up when providerChange is triggered but none show up in the Release version while they show up in the debug version - exact same code.

Here is my environment summary

## Your Environment
* Plugin version: 2.7.4
* Platform: iOS
* OS version: 10.2.1
* Device manufacturer / model: iPhone 6+
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`):
  android 6.0.0
  ios 4.3.1

## Expected Behavior

providerChange should trigger when Location permission is changed between Never, Always or When In Use
## Actual Behavior
providerChange is not triggered for Release code - it is triggered for code deployed directly from XCode to iPhone

## Context
As described earlier in the thread I am trying to capture Location changes so I can inform/warn the User accordingly as appropriate

## Debug logs
The issue is in the Release version of the code deployed - can't attach Safari debugger to it and can't get anything in XCode. If there is some way to capture something for Release version that may be helpful then please let me know.

I believe I am seeing a similar issue on Android side as well where a Release version doesn't trigger the providerChange while a command line deployment using `ionic run --device --target=<target id> android` triggers that.

Not quite sure what is going on here or if I am missing something. Please let me know if I can provide any additional insight. Let me know if I should open another ticket for this to help track this better and I will do that.

Thanks,
Sanjay.

**Comment by christocracy** [comment]
I really doubt this has anything to do with the plugin running in *release* mode.  Particularly if both platforms are affected since there's no correlation between the Android and iOS implementations of `providerchange`.

Sounds more likely an issue with your Javascript.

Are you listening the `providerchange` *before* you execute `#configure`?

```javascript
bgGeo.on('providerchange', onProviderChange);
.
.
.
bgGeo.configure(config, (state) => {

});
// If you listen to providerchange *after* calling #configure, a timing issue could cause you to "miss" the initial event.
```

**Comment by christocracy** [comment]
It's actually the execution of the `#configure` method which fires the initial `providerchange` event.

**Comment by christocracy** [comment]
And I always test the plugin built for *Release*
![](https://dl.dropboxusercontent.com/s/hiu88vilaqdzpx3/Screenshot%202017-11-08%2008.38.59.png?dl=1)

**Comment by stib** [comment]
@christocracy I didn't mean to imply that you didn't test on Release - apologies if it came across that way. Only trying to report what I am seeing.

I do call the `bgGeo.configure` after calling `bgGeo.on('providerchange', onProviderChange);` as you indicate.

I also tried executing directly from XCode by setting the Build Configuration to Release as you show in your screenshot - and that works fine i.e. providerChange is triggered.

Same code, that was used with Build Configuration set to Release, when I Archive, Export and load on my device through Window->Devices in XCode it doesn't seem to fire the providerChange event.

Please let me know if I may be missing anything else or if I can do anything to help debug.

PS: You may already know this but in case it is useful, I learnt in using phonegap-plugin-push plugin that using Build Configuration as Release apparently doesn't exactly represent the actual Release build through the Archive process. There is some difference there that I saw in the behavior of how Push notifications were going out and received.

**Comment by stib** [comment]
To potentially help with reproduction and to be more precise in what I am doing, in exporting the Archived build from XCode I am picking the options shown in screenshots below. Once I have exported the build I use Window -> Devices in XCode to open up my iPhone 6+ device. I then delete the existing App on my device, deployed directly through XCode (that works), and install the newly exported archived version where the `providerChange` is not triggered.

![image](https://user-images.githubusercontent.com/310258/32568832-47933a0a-c474-11e7-97d0-9405de4ed067.png)
![image](https://user-images.githubusercontent.com/310258/32568845-51d7cdb4-c474-11e7-9eaa-98c29467239f.png)

**Comment by stib** [comment]
To test it out further I went ahead and deployed the iOS App in TestFlight. The strange thing is that providerchange triggers when App is in TestFlight but not with the "Release" deployment on iPhone through XCode as described above. Not sure how to explain that but I can move forward.

I will close this out. If I find anything else I will update and if needed reopen or open another ticket.
