### ISSUE TITLE
Ability to execute Javascript code on Persistent Notification click

### ISSUE THREAD

**Issue by valgen** [transistorsoft/cordova-background-geolocation-lt#516]
Let me say that you have built a great plugin and I'll buy a license as soon as I finish testing.

I'd like to know if it is possible to execute Javascript code on "Persistent Notification" click, right after the app receives the focus.

If yes, please could you point me in the right direction? Even a workaround would be acceptable.

If no, is there any plan to add this feature to the plugin?

Thank you in advance.

**Comment by christocracy** [comment]
No, not possible.

I have no current plan to do so.

**Comment by cairinmichie** [comment]
@valgen you can use [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) to achieve this.

**Comment by valgen** [comment]
@cairinmichie As I said I need to execute Javascript code on "Persistent Notification" click. I'm aware of the plugin you suggested and this has nothing to do with the "Persistent Notification" generated by cordova-background-geolocation-lt. Thank you anyway.

**Comment by cairinmichie** [comment]
@valgen I meant you could use that plugin instead of the cordova-background-geolocation-lt notification, and just manually toggle the notification when the service is running. Because as far as I'm aware you can disable the persistent notification setting the foreground services config option to false.

**Comment by meisterm** [comment]
I'm currently testing your Plugin and I think I will buy it these days.
My last question: It isn't possible to run the Geofence Detection in Background and post Geofence Changes to a webserver without showing up a persistent notfication? That's insufficient to me cause I need that the app is running 24/7 without annoying the user.

**Comment by christocracy** [comment]
The notification is required by the os.

**Comment by valgen** [comment]
It would be nice to have this feature. Please leave it open as a discussion.

**Comment by christocracy** [comment]
Should be possible now with [Android Custom Notification Layout](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Custom-Notification-Layout).
