### ISSUE TITLE
The tracking data posted by the plugin is weird and shows lat long far away from the pervious one 

### ISSUE THREAD

**Issue by techmanha** [transistorsoft/cordova-background-geolocation-lt#517]
## Your Environment
* Plugin version: 2.8.5
* Platform: iOS 
* OS version: 11.0.3
* Device manufacturer / model: iPhone 5s
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):  ios 4.5.3 installed
* Plugin config
platform.ready().then(() => {
        this.bgGeo = (<any>window).BackgroundGeolocation;
        this.startBackgroundTracking();
});

startBackgroundTracking() {
    console.log("[LocationService] SatartBackgroundTracking ", this.backgroundGeolocationURL);
    if (!this.platform.is('cordova')) return;

    this.backgroundGeolocationURL = "<url to post the lat long data>";
      
    //minimum config option required to track user in background
    let bglConfig = {
        desiredAccuracy: 0,
        batchSync: true,
        debug: true,
        startOnBoot: true,
        stationaryRadius: 0,
        stopOnTerminate: false,
        maxBatchSize: 15,
        stopTimeout: 5,
        triggerActivities: "in_vehicle, on_bicycle, running, walking, on_foot",
        distanceFilter: 10,
        url: this.backgroundGeolocationURL,
        params: {
            "device_id": "123456789"
        }
    };

    this.applyListeners();
    
    this.bgGeo.configure(bglConfig, (state) => {
      console.log("[LocationService] tracking plugin configured");
      this.bgGeo.start();
      this.isBgPluginConfigured = true;
    });
  }

## Expected Behavior
The plugin should track the user in background even when app is terminated and once it detects user is moving it should continuously fetch the lat long on user and post it server

## Actual Behavior
At this point the plugin start tracking user in background but there is huge gap between the tracked location. No matter whether user is continuously walking or driving it doesn't tracks the user very effectively. If user is walking it should track him even in more sensitive manner but I don't see it happening. When I run the app in debug mode I and travel some distance I noticed that the after detecting user is moving it grabs location after every 6 to 8 minutes no matter how much distance the user has walked. 
And it also start tracking after travelling more than 1 kilometre of distance. 

## Steps to Reproduce
this is the whole code that I have written in a service
```
import { Injectable, ChangeDetectorRef } from '@angular/core';
import { Platform } from 'ionic-angular';
import { SharedData } from './SharedData';
import 'rxjs/add/operator/map';

declare var window: any;
@Injectable()

export class LocationService {
  bgGeo: any;
  platform: any;
  backgroundGeolocationURL: string;

  isBgPluginConfigured: boolean = false;
  isDebugMode: boolean = false;

  constructor(
    platform: Platform,
    public sharedData: SharedData,
    private chDetectRef: ChangeDetectorRef
  ) {
    console.log("[LocationService]");
    this.platform = platform;
    platform.ready().then(() => {
      if (sharedData.isCordovaApp) {
        //this.bgGeo = (<any>window).BackgroundGeolocation;
        this.bgGeo = (<any>window).BackgroundGeolocation;
        console.log("[LocationService] initialized bgGeo variable");
        this.startBackgroundTracking();
      }
      else {
        this.bgGeo = null;
      }
    });
  }

  startBackgroundTracking() {
    console.log("[LocationService] SatartBackgroundTracking ", this.backgroundGeolocationURL);
    if (!this.platform.is('cordova')) return;

    this.backgroundGeolocationURL = "<url to post the lat long data>";
      
    //minimum config option required to track user in background
    let bglConfig = {
        desiredAccuracy: 0,
        batchSync: true,
        debug: true,
        startOnBoot: true,
        stationaryRadius: 0,
        stopOnTerminate: false,
        maxBatchSize: 15,
        stopTimeout: 5,
        triggerActivities: "in_vehicle, on_bicycle, running, walking, on_foot",
        distanceFilter: 10,
        url: this.backgroundGeolocationURL,
        params: {
            "device_id": "123456789"
        }
    };

    this.applyListeners();
    
    this.bgGeo.configure(bglConfig, (state) => {
      console.log("[LocationService] tracking plugin configured");
      this.bgGeo.start();
      this.isBgPluginConfigured = true;
    });
  }

  getCurrentPosition() {
    return new Promise((resolve, reject) => {
      console.log("[LocationService] getCurrentPosition isBgPluginConfigured: ",this.isBgPluginConfigured);
      if (this.platform.is('cordova')) {
        if(this.isBgPluginConfigured){
          this.bgGeo.getCurrentPosition((pos, taskId) => {
            console.log("[LocationService] getCurrentPosition: ", pos);
            this.bgGeo.finish(taskId);
            resolve({
                lat: pos["coords"]["latitude"],
                long: pos["coords"]["longitude"]
            });
          }, (err) => {
            reject(err);
          }, { 
            maximumAge: 3000, 
            timeout: 30, 
            desiredAccuracy: 10, 
            samples: 1,
            persist: false
          });
        }
        else{
          reject(null);
        }
      }
      else {
        console.log("[LocationService] not cordova app hence, returning hardcoded location");
        resolve(null);
      }
    });
  }

  applyListeners(){
    // 2. Listen to events
    this.bgGeo.on('location', this.onLocation.bind(this));
    this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
    this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
    this.bgGeo.on('geofence', this.onGeofence.bind(this));
    this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));
  }

  onLocation(location, taskId) {
    console.log('[LocationService] location: ', location);
    this.bgGeo.finish(taskId);
  }
  onMotionChange(isMoving, location, taskId) {
    console.log('[LocationService] motionchange: ', isMoving, location);
    this.bgGeo.finish(taskId);
  }
  onActivityChange(activity) {
    console.log('[LocationService] activitychange: ', activity);
  }
  onGeofence(params, taskId) {
    console.log('[LocationService] geofence: ', params);
    this.bgGeo.finish(taskId);
  }
  onHttpSuccess(response) {
    console.log('[LocationService] http success: ', response);
  }
  onHttpFailure(response) {
    console.log('[LocationService] http failure: ', response);
  }

  getNotSyncCount() {
    console.log("[LocationService] getNotSyncCount");
    this.bgGeo.getCount((count) => {
      console.log('[LocationService] - BackgroundGeolocation Not Synced Count: ', count);
    });
  }
}
```

## Context
I have purchased the plugin and paid user of the plugin. I am trying to track user's activity in online as well as in offline mode

## Debug logs
Here is the lat long data on map which is generated by the plugin 
https://www.darrinward.com/lat-long/?id=59fe99d35f0285.78992514
You can clearly see the distance between tow locations. This is data from a single trip where I was continuously driving

**Comment by christocracy** [comment]
Plugin logs please.

**Comment by techmanha** [comment]
The issue is fixed now.
I just replaced this line 
` "BACKGROUND_MODE_LOCATION": "true" `
with this
`"BACKGROUND_MODE_LOCATION": "<string>location</string>"`

Now it's working fine.

**Comment by christocracy** [comment]
You do not even need to provide this variable.

[See the docs](https://github.com/transistorsoft/cordova-background-geolocation-lt#variable-background_mode_location-ltstringgtlocationltstringgt-ios)

>**WARNING** If you do want the default behaviour of background-location updates, simply IGNORE this variable -- Do NOT even provide it. If you do provide it, you must provide the full escaped XML value of &lt;string&gt;location&lt;/string&gt; (the default value when not provided), not just location.

[The default value is `<string>location</string>`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L24)
