### ISSUE TITLE
Battery draining very fast

### ISSUE THREAD

**Issue by harsh-ds** [transistorsoft/cordova-background-geolocation-lt#519]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

```
 var bgGeo = window.BackgroundGeolocation;
      bgGeo.configure({
                desiredAccuracy: 0,
                distanceFilter: 10,
                 disableElasticity: false,
                 geofenceProximityRadius:1000,
                stationaryRadius: 25,
                activityType:'Other',//new
                useSignificantChangesOnly :false,//new
                locationUpdateInterval: 60000,
                stopTimeout:5,//new
                activityRecognitionInterval:10000,//new
                stopDetectionDelay:0,//new
                disableStopDetection:false,//new
                disableMotionActivityUpdates:false,//new
                autoSync:true,
                autoSyncThreshold:0,//new
                maxBatchSize:-1,//new
                batchSync:false,//new
                maxRecordsToPersist:-1,//new
                stopOnTerminate: false,
                startOnBoot: true,
                heartbeatInterval:60,//new
                preventSuspend:false,
                url: resturl,
                method: "POST",
        params: {   
            "userid":26
        }

    }, function(state) {
        if (!state.enabled) {
              bgGeo.start();
              
        }
    });
```
Above are my configuration option . Tracking user is working fine but  battery is draining very fast is any help?

**Comment by christocracy** [comment]
HTTP requests consume *far* more energy / second than GPS.

The best way to save battery energy is to execute fewer HTTP requests.

With a `distanceFilter: 10` and `autoSync: true`, you're executing *a lot* of HTTP requests.

- increase `distanceFilter` to record fewer locations
- Use `autoSyncThreshold` to allow locations to accumulate before performing an HTTP sync.
- Use `batchSync: true` to combine accumulated locations into a single HTTP request (rather than 1 request per location)

**Comment by harsh-ds** [comment]
heartbeatInterval:60 is it ok or need to increase?

**Comment by christocracy** [comment]
Are you listening to the `heartbeat` event?

**Comment by harsh-ds** [comment]
Yes we are sending location to sever (http request) on every heartbeat interval.

**Comment by christocracy** [comment]
>Yes we are sending location to sever (http request) on every heartbeat interval.

If you want to improve battery efficiency, **don't do that.**.  This is completely unnecessary and wasteful.  What's the point recording the same location over and over again when the plugin told your the device is *stationary*?.  When the plugin detects the device is moving, it will resume recording locations.

This is the primary philosophy of this plugin -- to track location only when the device is detected to be *moving* and conserve energy by turning off location-services when device is *stationary*.

**Comment by harsh-ds** [comment]
ohk thanks if we have the ability to turn on and off? like by sending push notification we stop the tracking of particular user and again sent notification to start.

**Comment by christocracy** [comment]
You're free to execute any API method upon the plugin at any time, including during a server Push callback.

Push is a great way to control the plugin and is completely independent of the plugin.

**Comment by harsh-ds** [comment]
ohk thanks first let me go with  improve battery efficiency. Thanks for your help.
