### ISSUE TITLE
Battery enhancement

### ISSUE THREAD

**Issue by smamet** [transistorsoft/cordova-background-geolocation-lt#521]
## Your Environment
* Plugin version: 2.4.3
* Plugin config

We would need some advices on the best configuration for little battery usage.

Here is our needs :
-> We need to track people moving in a city, but when in a vehicle there is no real need to track, we can track very few. 
-> When he stops then we should track
-> When someone is still we don't need to send another call to our API (only one is ok).

We used the settings below, it works fine when not in a vehicle. An alert of battery consumption is triggered on every android once in a vehicle.

            desiredAccuracy: 0,
            distanceFilter: 200,
            stationaryRadius: 25,
            activityRecognitionInterval: 10000,
            stopTimeout: 5,
            stopOnTerminate: false,
            startOnBoot: true,
            heartbeatInterval: 60,
            logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
            method: "POST",
            autoSync: true,

What would you suggest us to change ? Maybe an elasticityMultiplier set to 2 ? Or increase the activityRecognitionInterval ?

I tried activityRecognitionInterval: 30000 and elasticityMultiplier:2 but I am having big delays in position update (2 - 5 min)

Thanks

Samuel

**Comment by christocracy** [comment]
Duplicate #519

**Comment by christocracy** [comment]
>We need to track people moving in a city, but when in a vehicle there is no real need to track, we can track very few.

If you don't want to track when `in_vehicle`, remove that from [`triggerActivities`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-string-triggeractivities)

- The greatest way to save energy is by reducing HTTP requests.  Use `autoSyncThreshold`
- If you're doing work in a `heartbeat` event, particularly if you're executing `#getCurrentPosition`, that's going to drain a lot of energy.  Either stop doing that or increase your `heartbeatInterval`

**Comment by christocracy** [comment]
- `activityRecognitionInterval: 30000`:  This will delay the time it takes to detect `motionchange` and start / stop tracking

- `elasticityMultiplier:2`:  you already have a high `distanceFilter: 200`.  Scaling that by `2` will significantly reduce the number of recorded locations.

**Comment by smamet** [comment]
Thanks for your help. 

I have one more question. I saw that plugins sends a lot of requests (at least 2 per second) when in movement, how can I reduce that with a certain threshold. autoSyncThreshold seems to pile up different locations before sending all, so this might create a problem when the movement is small. The risk is that for example the movement hasn't caught enough location points to trigger HTTP before he stops moving.

I'd like something more like a time threshold : when motion detected, do not send a HTTP Request before $x seconds (and only 1 coordinate, not a list of points)

Thanks

**Comment by smamet** [comment]
Example : 

autoSyncThreshold = 10
distanceFilter = 200

User takes his car on 600m (600/200 => 3 coordinates) and stops at a café to have a drink. Will I have him tracked at that café or not ?

**Comment by christocracy** [comment]
motionchange events always flush the queued locations, regardless of autoSyncThreshold.

I’ve already thought of this.

**Comment by smamet** [comment]
Thank a lot :)

**Comment by smamet** [comment]
Hi,

I tried this config (with autoSyncThreshold: 10) but nothing changed. Did I do something wrong ?

```
this.bgGeo.configure({
            desiredAccuracy: 0,
            distanceFilter: 200,
            stationaryRadius: 25,
            activityRecognitionInterval: 15000,
            autoSyncThreshold: 10,
            debug: false,  // <-- Debug sounds & notifications.
            stopTimeout: 5,
            stopOnTerminate: false,
            startOnBoot: true,
            heartbeatInterval: 60,
            logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
            method: "POST",
            autoSync: true,
            url: `${environment.api_endpoint}/users/track/background`,
            httpRootProperty:".",
            locationTemplate: '{ "longitude":<%= longitude %>, "latitude":<%= latitude %> }',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/prs.app.v1+json',
                'Authorization': `Bearer ${token}`
            },
        }, (state) => {
            this.bgGeo.start();
        });
```

Result is this (2 request per second, every second) : 
![image](https://user-images.githubusercontent.com/1436778/32690913-b0b8bd56-c718-11e7-839b-7c594dc19438.png)

Thanks

**Comment by christocracy** [comment]
Try latest version `2.9.1`

**Comment by smamet** [comment]
Hi,

Using : 

```
 "name": "cordova-background-geolocation",
  "version": "2.9.1",
```

I've got same result with this config. Do you see something wrong ?

```
this.bgGeo.getState((config) => {
                config.logLevel = this.bgGeo.LOG_LEVEL_VERBOSE;
                config.distanceFilter = 200;
                config.activityRecognitionInterval = 15000;
                config.locationTemplate = '{ "longitude":<%= longitude %>, "latitude":<%= latitude %> }';
                config.stopTimeout = 5;
                config.autoSyncThreshold = 10;
                config.stopOnTerminate = false;
                config.startOnBoot = true;
                config.heartbeatInterval = 60;
                config.locationAuthorizationAlert = {
                    titleWhenNotEnabled: this.translatedText.titleWhenNotEnabled,
                    titleWhenOff: this.translatedText.titleWhenOff,
                    instructions: this.translatedText.instructions,
                    cancelButton: this.translatedText.cancelButton,
                    settingsButton: this.translatedText.settingsButton
                },
                config.method = "POST";
                config.autoSync = true;
                config.url = `${environment.api_endpoint}/users/track/background`;
                config.httpRootProperty =".";
                config.stationaryRadius = 25;
                config.desiredAccuracy = 0,
                config.debug = false;  // <-- Debug sounds & notifications.
                config.headers = {
                    'Content-Type': 'application/json',
                    'Accept': 'application/prs.app.v1+json',
                    'Authorization': `Bearer ${token}`
                };
                this.bgGeo.configure(config, (state) => {
                    resolve(state);
                });
            });
```

**Comment by smamet** [comment]
![image](https://user-images.githubusercontent.com/1436778/33004046-ed2ddbd4-cdd7-11e7-990e-4034a6d74b45.png)
