### ISSUE TITLE
no DWELL events fired while within geofence

### ISSUE THREAD

**Issue by jsuiker** [transistorsoft/cordova-background-geolocation-lt#526]
## Your Environment
* Plugin version: 2.8.5
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: SAMSUNG-SM-G890A
* Cordova version: 7.1.0
* Cordova platform version: 6.3.0
* Plugin config

```
{
  "isMoving": false,
  "enabled": true,
  "odometer": 630289.3,
  "schedulerEnabled": false,
  "trackingMode": "location",
  "distanceFilter": 10,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "locationUpdateInterval": 1000,
  "fastestLocationUpdateInterval": 10000,
  "locationTimeout": 60,
  "deferTime": 0,
  "disableElasticity": false,
  "elasticityMultiplier": 1,
  "activityRecognitionInterval": 10000,
  "minimumActivityRecognitionConfidence": 75,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "disableStopDetection": false,
  "stationaryRadius": 25,
  "stopTimeout": 5,
  "stopOnStationary": false,
  "url": "http:\/\/api.XXXXX.dev\/checkin\/christocracy",
  "method": "POST",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "maxBatchSize": -1,
  "params": {
    "device": {
      "available": true,
      "platform": "Android",
      "version": "7.0",
      "uuid": "4aaae1f025199d4e",
      "cordova": "6.3.0",
      "model": "SAMSUNG-SM-G890A",
      "manufacturer": "samsung",
      "isVirtual": false,
      "serial": "0815f88565d52b04"
    },
    "user": 4
  },
  "headers": {},
  "extras": {},
  "httpRootProperty": "location",
  "locationTemplate": "",
  "geofenceTemplate": "",
  "persist": true,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "httpTimeout": 60000,
  "geofenceProximityRadius": 1000,
  "geofenceInitialTriggerEntry": true,
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": 60,
  "foregroundService": false,
  "notificationPriority": 0,
  "notificationTitle": "Your App Name",
  "notificationText": "Location service activated",
  "notificationColor": "",
  "notificationIcon": "",
  "notificationSmallIcon": "Your App Icon",
  "notificationLargeIcon": "",
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnBoot": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnSchedule": false,
  "stopAfterElapsedMinutes": 0,
  "schedule": [],
  "configureUrl": "",
  "configureInterval": -1,
  "debug": true,
  "logLevel": 5,
  "logMaxDays": 3
}
```
* Geofence Config
```
{
  "identifier":"Loudoun Logistics LLC",
  "radius":200,
  "latitude":39.2611,
  "longitude":-77.631,
  "notifyOnEntry":true,
  "notifyOnExit":true,
  "notifyOnDwell":true,
  "loiteringDelay":600,
  "extras":{}
}
```

## Expected Behavior
DWELL events should fire and POST from the background while inside of a geofence.

## Actual Behavior
I only get motionchange events, no DWELL events. Restarting the phone or app simply fires a new ENTER event.

| event_type   | provider | is_moving | uuid                                 | coords                                                                                             | activity                            | geofence                                                            | timestamp                | id | createdAt         |
|--------------|----------|-----------|--------------------------------------|----------------------------------------------------------------------------------------------------|-------------------------------------|---------------------------------------------------------------------|--------------------------|----|-------------------|
| motionchange |          | FALSE     | 2e0fc452-94cc-432d-bf5d-550f81a8ec39 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"unknown","confidence":100} |                                                                     | 2017-11-12T18:43:12.565Z | 1  | 11/12/17 01:43 PM |
| geofence     |          | FALSE     | 41d7a9e9-ed8b-4009-8eed-dff734029227 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"unknown","confidence":100} | {"identifier":"Loudoun Logistics LLC","action":"ENTER","extras":{}} | 2017-11-12T18:43:12.565Z | 2  | 11/12/17 01:43 PM |
| motionchange |          | FALSE     | 9589db4e-d795-4ad7-98ea-4df556443e72 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"unknown","confidence":100} |                                                                     | 2017-11-12T18:43:48.481Z | 3  | 11/12/17 01:43 PM |
| motionchange |          | FALSE     | 0c53d33b-d3da-4e94-b3c2-28537484946b | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"unknown","confidence":100} |                                                                     | 2017-11-12T18:43:48.566Z | 4  | 11/12/17 01:43 PM |
| motionchange |          | FALSE     | d887a9d1-199b-4e6c-973b-20b89025c5fb | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"unknown","confidence":100} |                                                                     | 2017-11-12T18:43:49.135Z | 5  | 11/12/17 01:43 PM |
| geofence     |          | FALSE     | 991f6f20-bd96-4bc1-8e8e-444dec476a02 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"unknown","confidence":100} | {"identifier":"Loudoun Logistics LLC","action":"ENTER","extras":{}} | 2017-11-12T18:43:49.047Z | 6  | 11/12/17 01:43 PM |
| motionchange |          | FALSE     | 4532d268-a507-4794-98b6-82cb91a9e7c8 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   |                                                                     | 2017-11-12T19:06:41.293Z | 7  | 11/12/17 02:06 PM |
| geofence     |          | FALSE     | 839c0dd2-9cb7-4658-9542-2bc71483859a | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   | {"identifier":"Loudoun Logistics LLC","action":"ENTER","extras":{}} | 2017-11-12T19:06:41.293Z | 8  | 11/12/17 02:06 PM |
| motionchange |          | FALSE     | 33cac303-de1e-439c-9e2e-475c2655e281 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   |                                                                     | 2017-11-12T19:06:42.988Z | 9  | 11/12/17 02:06 PM |
| geofence     |          | FALSE     | b32dc337-8d22-4b2c-8f21-61365a90367d | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   | {"identifier":"Loudoun Logistics LLC","action":"ENTER","extras":{}} | 2017-11-12T19:06:41.508Z | 10 | 11/12/17 02:06 PM |
| motionchange |          | FALSE     | fc0b300a-c252-443b-b2b1-d1651f068a66 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   |                                                                     | 2017-11-12T19:06:44.065Z | 11 | 11/12/17 02:06 PM |
| motionchange |          | FALSE     | d82636bb-ca91-47e4-a3a7-8bcdf06069a1 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   |                                                                     | 2017-11-12T19:06:44.102Z | 12 | 11/12/17 02:06 PM |
| motionchange |          | FALSE     | 2b3cbff1-a3c8-40d7-96e5-26a0b8332d86 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   |                                                                     | 2017-11-12T19:06:44.938Z | 13 | 11/12/17 02:06 PM |
| geofence     |          | FALSE     | f9362258-bf59-47f9-9350-d6c2a0b0e6c2 | {"latitude":39.2609758,"longitude":-77.631078,"accuracy":20,"speed":-1,"heading":-1,"altitude":-1} | {"type":"still","confidence":100}   | {"identifier":"Loudoun Logistics LLC","action":"ENTER","extras":{}} | 2017-11-12T19:06:44.646Z | 14 | 11/12/17 02:06 PM |

## Context
build my client's API ...OMGWTFHAX!

## Debug logs
[bggeo_debug.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1465010/bggeo_debug.txt)

**Comment by christocracy** [comment]
I think I see the issue.  I was not providing [`INITIAL_TRIGGER_DWELL`](https://developers.google.com/android/reference/com/google/android/gms/location/GeofencingRequest.html#INITIAL_TRIGGER_DWELL).

Were you adding this geofence around your current location?  If you instead create a geofence that you're not *already inside* then walk into it, `DWELL` should fire.

I will default `INITIAL_TRIGGER_DWELL`.

**Comment by christocracy** [comment]
Try version `2.9.1`

**Comment by jsuiker** [comment]
I'm not seeing any difference in 2.9.1

it seems like the debug sounds are no longer working...

FWIW, 2.8.x did work if in motion, ENTER and DWELL fired sequentially. Reboots and startups did not and still do not work.

Also, is the DWELL event supposed to fire only once or does it recur at a certain interval?
