### ISSUE TITLE
Is it possible to do a pause (4-24h) of permanent tracking?

### ISSUE THREAD

**Issue by bezkel** [transistorsoft/cordova-background-geolocation-lt#529]
## Your Environment
* Plugin version: 2.9.0
* Platform: Android and IOS
* OS version: Windows 10
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config

## Expected Behavior
how could I implement a pause of tracking in an app, which is permantent tracking and most of the time in background or terminated? 
The important thing for our app is to make sure that our server doesn't get the locations in this timeslot. It shoud be possible for the user to pause the permanent tracking for 4-24h. 

Could the scheduler do something like this? 

## Actual Behavior
NA

## Steps to Reproduce
NA

## Context
My first solution in the mauron85-version was, if i do a pause, i set the url to "" and ask every time i get an location, if the pause-enddatetime is reached. If not, I delete this location out of the sqldb. So the server didn't get a location and the location is not in the sqldb. After the pause, I reset the config, so all new locations will be send and stored again.
I did that, because the backgroundservice runs allways and so it starts to send the locations after the pause without I have to restart or go into the app.

But how could I do this with your plugin and is there a better way?

## Debug logs
NA

**Comment by christocracy** [comment]
Since you're a customer, you should be using the private repo for latest updates.

Are you still using this public version?

**Comment by christocracy** [comment]
And yes, the `#scheduler` could do this.

**Comment by bezkel** [comment]
Cool, that makes it a lot easier for me :)
ohm, yepp - I have to update it. At the moment I use the public one because I build my app with ionic pro and that build failed because ionic has no access to the private git. I should figure it out, but I have a lot of other problems right now :(

**Comment by christocracy** [comment]
For Ionic pro, you just need to generate a Github access-token and follow the same instructions for [PhoneGap Build](https://github.com/transistorsoft/cordova-background-geolocation/wiki/PhoneGap-Build-Installation#add-the-plugin-to-configxml)

**Comment by bezkel** [comment]
Thanks, that did the job and I can use the private one 👍

**Comment by bezkel** [comment]
Back to the mainquestion ;-)
How could I do that? The scheduler starts and stops at the given dates, or am I wrong?
I thought about to do it like this: I start the scheduler from now to a year and if someone wants a break it reconfig it with a new one from the end of the break to a year away. 
But that sounds a little bit more complicated as to use the scheduler only reverse(stop and start then the otherway). 
What do you think?

**Comment by christocracy** [comment]
Did you read the docs for [`#schedule`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-array-schedule-undefined)

`2-6 09:00-17:00` // <-- Tracking enabled: mon-friday, 9am -> 5pm
