### ISSUE TITLE
Getting "Location error: 0" in simulator while running

### ISSUE THREAD

**Issue by SinoBoeckmann** [transistorsoft/cordova-background-geolocation-lt#53]
Hi!

Great Plugin so far, thanks!
I'm getting a "Location error: 0" while running the demo app in iOS Simulator (iPhone 6, iOS 9.2). Do you know what this causes? It ran about 5-10 minutes.

![bildschirmfoto 2016-01-13 um 18 01 20](https://cloud.githubusercontent.com/assets/4194929/12301363/dbfd43b8-ba1f-11e5-924b-7923d3d64ffd.png)

**Comment by christocracy** [comment]
This is fine.  This error will fire if you walk into a subway station or drive through a tunnel.  Just means the native location-manager failed to retrieve a location.

[Error Codes](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Error-Codes)

**Comment by SinoBoeckmann** [comment]
Thank you! :)

**Comment by christocracy** [comment]
The iOS location simulator fires `error: 0` when it loops back to the start.  It's as if the device went into the subway to travel back to its start position.
