### ISSUE TITLE
iOS location 'Always'

### ISSUE THREAD

**Issue by juancafe4** [transistorsoft/cordova-background-geolocation-lt#530]
Hi,
I am using iOS 11.1 and iOS 10.3 when I start background geolocation it asks me to use location 'While using the App.' And I wanted to have location as 'Always' How do you set up location to always?

Thank you

**Comment by christocracy** [comment]
I recognize you from the Mauron85 repo thread.

Are you asking about *my* plugin or *mauron85's*?

**Comment by juancafe4** [comment]
Your plugin. mauron85 does not support iOS 11 yet

**Comment by christocracy** [comment]
[`locationAuthorizationRequest`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-string-locationauthorizationrequest-always)

This specifies the plugin's *expectation* of what the user *should* have selected.

**Comment by christocracy** [comment]
See [Configuration Variables](https://github.com/transistorsoft/cordova-background-geolocation-lt#configuration-variables)

```
$ cordova plugin add cordova-background-geolocation-lt \
  --variable LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION="Always please for iOS 11+" \
  --variable LOCATION_ALWAYS_USAGE_DESCRIPTION="Always please for < iOS 11" \
  --variable LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION="When in  use for all"
```

**Comment by christocracy** [comment]
And [`providerchange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#providerchange) event will be executed when the state of location-authorization changes.

You will know what the user has selected in this event callback.

**Comment by juancafe4** [comment]
I have this from the example
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="[CHANGEME] Always use is required for constant background location-tracking" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="[CHANGEME] Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="[CHANGEME] Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />

**Comment by juancafe4** [comment]
<variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="[CHANGEME] Always use is required for constant background location-tracking" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="[CHANGEME] Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="[CHANGEME] Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />

**Comment by christocracy** [comment]
The defaults are fine for now.

```javascript
bgGeo.configure({
  locationAuthorizationRequest: 'Always',
  debug: true
}, (state) => {
  // Location Auth popup will appear as soon as you #start the plugin
  bgGeo.start();
});
```

**Comment by juancafe4** [comment]
Thank I ll give it a try

**Comment by juancafe4** [comment]
It id not work it keeps saying while using the app

**Comment by christocracy** [comment]
Show me a screenshot of what you mean.

**Comment by juancafe4** [comment]
https://imgur.com/a/vIApH

my config

    let config = {
      locationAuthorizationRequest: 'Always',
      desiredAccuracy: 0,
      distanceFilter: 10,
      stationaryRadius: 25,
      debug: true,
      activityRecognitionInterval: 10000,
      activityType: 'AutomotiveNavigation',
      pauseLocationUpdates: false,
      url: "http://192.168.52.52:3000/background",
      method: "POST",
      httpHeaders: {"Content-Type": "application/json"},
      params: {   // <-- Optional HTTP params
            "uId": globalData.uId
      }
    };

**Comment by christocracy** [comment]
cordova plugin

**Comment by christocracy** [comment]
You’re prob using cordova-plugin-geolocation

Whichever plugin requests location auth first is the one who wins.

A permissions tug-of-war.

Cordova-plugin-geolocation is not required with my plugin.

My plugin has its own #get urrentPosition method.

Disable Cordova-plugin-geolocation from requesting location.

**Comment by juancafe4** [comment]
oh I understand now thank you I ll disable geolocation

**Comment by dfibuch** [comment]
Sorry to jump on this topic (I'll open another if required) but is there any way to tell what the user has currently set as a location permission for the iOS app?

My scenario is: 

User goes to the map and clicks a START button, which will start up bgGeo, however if the user has set "While In Use" permissions I don't want to proceed with the code and not start bgGeo. Problem is, getCurrentPosition() will return a location in both "While In Use" and "Always" so I can't tell the difference but internally it will pop up a message saying "Always is needed". 

Hope this makes sense.

**Comment by christocracy** [comment]
```javascript
bgGeo.on('providerchange', function(provider) {
  // This callback is executed whenever the state of location-services changes.
  // You're free to save the current state on some application object of your own
  yourApp.setProvider(provider);
});
```

**Comment by dfibuch** [comment]
Thank you, I will try that, but I didn't think that would work seeing as the user hasn't changed the state of location services. They have just set it to "While in Use" completely outside of the app without it running. Or are you saying this will run once as we try to get the location?

**Comment by christocracy** [comment]
As soon as you execute `#configure`, the plugin automatically fires a `providerchange` event with the current state of location-services.

```javascript
bgGeo.on('providerchange', function() {
  console.log('- providerchange: ', provider);
});
bgGeo.configure(yourConfig, function(state) {
  // providerchange has just fired.
});
```

**Comment by dfibuch** [comment]
Perfect! That's the piece of the puzzle I was missing. Thank you for the swift response, I will try this.

**Comment by dfibuch** [comment]
I have set this up and I can get the "providerchange" to fire when I make a change to the settings of the devices Location services but it doesn't fire when I call "configure". The problem might be that our version of your plugin is a bit outdated (2.2.4). Not quite sure when this functionality was introduced, also looks like the data you get out of "providerchange" is the old style, namely {enabled, gps, network}.

Looks like we're going to need to upgrade in order to use the functionality you speak of.
