### ISSUE TITLE
Limit location update frequency for iOS

### ISSUE THREAD

**Issue by MaratFaskhiev** [transistorsoft/cordova-background-geolocation-lt#532]
Hi,

We need an ability to limit update frequency for iOS application. As I can see it is allowed for Android version by using fastestLocationUpdateInterval. Is there a way to achieve the same behavior at iOS application?

**Comment by christocracy** [comment]
iOS is strictly distance-based with distanceFilter.

Don’t provide distanceFilter: 0 to iOS.

You’re advised to let android operate with distanceFilter > 0, as well — it’s more battery-efficient.

**Comment by MaratFaskhiev** [comment]
@christocracy Thank you.

We already using distanceFilter. Current value is 10. But we still receive updates too often. It can be more frequent than several times per second.

**Comment by christocracy** [comment]
Do you have plugin logs showing this?

**Comment by christocracy** [comment]
You’ve ignored the issue template which asked you for some highly relevant information, including:
- Plugin version
- Plugin config
- plugin logs

**Comment by MaratFaskhiev** [comment]
Plugin version:
2.8.5
Plugin config:
```
            var commonOptions = {
                // Geolocation config
                desiredAccuracy: 0,
                distanceFilter: 10,
                stationaryRadius: 20,
                locationUpdateInterval: 5000,
                fastestLocationUpdateInterval: 1000,

                // Activity Recognition config
                activityRecognitionInterval: 5000,
                stopTimeout: 5

                // Activity Recognition config
                activityType: 'AutomotiveNavigation',

                // Application config
                debug: false,
                stopOnTerminate: false,
                startOnBoot: false,

                // HTTP / SQLite config
                method: 'POST',
                autoSync: true,
                maxDaysToPersist: 1,
                url: '...',
                headers: {
                    ...
                }
            };
```

We have no plugin logs. I'm operating by monitoring tools at server side.

**Comment by christocracy** [comment]
Well, 10 meters is an aggressive distanceFilter.

Obviously you’ll record a lot of data at vehicle speeds.

increase distanceFilter and/or provide autoSyncThreshold.  Perhaps batchSync: true.

**Comment by MaratFaskhiev** [comment]
> Obviously you’ll record a lot of data at vehicle speeds.

Yes. I understand this. At the same time we want to receive updates when device is moving slowly. 

It doesn't look that increasing of distanceFilter or providing autoSyncThreshold resolves our issue. It doesn't guarantee that we will receive updates not often that once per second 5 seconds for example. At the same time if technician moving slowly it is possible that we will not receive desired updates.

**Comment by christocracy** [comment]
Without plugin logs, there’s little else to say.

You must reproduce this yourself in debug mode.

**Comment by MaratFaskhiev** [comment]
Is it possible that fastestLocationUpdateInterval support will be implemented for iOS?

**Comment by christocracy** [comment]
No.  iOS is strictly distance-based.

**Comment by flashfm** [comment]
@christocracy hello
why it's not possible to limit frequency of triggering the "url" ?
we don't want to receive update of device coordinates on our server more often than once per N seconds

**Comment by christocracy** [comment]
@flashfm You *can* limit the frequency of updates to server.  Simply provide [`autoSyncThreshold > 0`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-autosyncthreshold-0)

**Comment by flashfm** [comment]
As far as I understand from the doc, it just allows to collect more positions on client before sending them to server, i.e. still one POST per collected position?
If so, it's not throttling frequency of server posts, it just delays them.

If batchSync enabled and maxBatchSize is 100 but you collected only 50 positions in client buffer, then when the post will happen?

From the other hand if maxBatchSize is small and plugin is collecting lots of position quickly - may we have more frequent POSTs than we want?

What we need is to receive current position on server not more than once per N seconds, and we don't care about all positions between two consecutive server posts.

**Comment by christocracy** [comment]
>If batchSync enabled and maxBatchSize is 100 but you collected only 50 positions in client buffer, then when the post will happen?

50 will be posted.

>From the other hand if maxBatchSize is small and plugin is collecting lots of position quickly

The plugin will execute http requests of `maxBatchSize` until the `count < maxBatchSize`

**Comment by flashfm** [comment]
>50 will be posted.
but when? how often will it post it ?

>The plugin will execute http requests of maxBatchSize until the count < maxBatchSize
that's the point, we need those POSTs with some specified frequency only

**Comment by christocracy** [comment]
>but when? how often will it post it ?

When the plugin has queued `>= autoSyncThreshold` records in its database, it will begin uploading to your server.

I'm not going to run a timer to do this.

What is your purpose?  To throttle HTTP server load?

**Comment by flashfm** [comment]
Yes, throttle server loads, decrease energy consumptions on devices

**Comment by christocracy** [comment]
Have you tried using `autoSyncThreshold` yet?

**Comment by christocracy** [comment]
Closed for lack of feedback.
