### ISSUE TITLE
[Changeme] text please to be removed

### ISSUE THREAD

**Issue by dylanvdmerwe** [transistorsoft/cordova-background-geolocation-lt#534]
## Your Environment
* Plugin version: 2.9.1
* Platform: iOS
* OS version: 11.1

## Expected Behavior
I completely understand why the `[Changeme]` text has been included to force users of the plugin to put appropriate permission descriptions in. However this becomes extremely tedious because 1) the change me text ends up in production even if the descriptions are removed and 2) updating the plugin reverts any changes made to these descriptions meaning change me gets to production again. The default messages you have included are perfect and I am imploring you to remove the `[Changeme]`'s.

## Actual Behavior
Changing the `MOTION_USAGE_DESCRIPTION` and other descriptions in `package.json` and `config.xml` that have default `[Changeme]` text in them does not update the iOS project even when removing and readding the platform.

**Comment by christocracy** [comment]
The trick is to remove with **`--nosave`** flag.  This tells cordova to remove with plugin and **do not save** changes to `config.xml`.  Normally it would remove the `<plugin name="cordova-background-geolocation-lt"> element from `config.xml` and save the change.

```
$ cordova plugin remove cordova-background-geolocation-lt --nosave
$ cordova plugin add cordova-background-geolocation-lt
```
