### ISSUE TITLE
geofenceschange vs geofence EH

### ISSUE THREAD

**Issue by alexcroox** [transistorsoft/cordova-background-geolocation-lt#535]
If I'm looking to report to my remote DB whenever a user enters or leaves the geofences I setup.

I'm confused if I should use `geofenceschange` or `geofence` event handler. They both appear to do the same thing for my use case; trigger when a user enters or exits a geofence. What is the advantage or use case of using one over the other?

**Comment by christocracy** [comment]
In the [docs](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs) is a section called *Guides*, which includes a *Geofencing* page.
![](https://dl.dropboxusercontent.com/s/33q5k9l4un8o2mx/Screenshot%202017-11-15%2009.26.14.png?dl=1), where this is explained.

**Comment by alexcroox** [comment]
I had a good read of that, but it doesn't mention the `geofence` and when I saw them both together in the documentation I wasn't sure which to use (the `geofence` looks simpler to use).

**Comment by christocracy** [comment]
`geofenceschange` fires when the list of *monitored* geofences changes.  iOS can only monitor `20` geofences at-a-time (Android: 100).

The plugin is periodically querying for the closest geofences within `geofenceProximityRadius` (default 1km).  When the list of *monitored* geofences *changes*, the `geofenceschange` event fires to let you know exactly which geofences are currently being monitored (as well as those which *stopped* being monitored.

The `geofence` event fires when a geofence **transition** occurs (`ENTER`, `EXIT`, `DWELL`).

**Comment by alexcroox** [comment]
Ah I understand now, `geofenceschange` has nothing to do with when the geofences are triggered, just when the list of them changes.

I think it was this line in the documentation that made me think it was called when they were triggered.

![ss](https://cl.ly/niKY/Screen%20Shot%202017-11-15%20at%2015.42.32.png)

triggered != activated

Thanks for explaining :)

**Comment by christocracy** [comment]
[This is an animation of geofenceschange](https://www.transistorsoft.com/shop/products/assets/images/background-geolocation-infinite-geofencing.gif)

- You can see new new geofences being activated (`event.on`) as the device moves (with out-of-range geofences disappearing (`event.off`)
- Geofences are turn grey when `geofence` are triggered, firing the `geofence` event.

`geofencechange` is probably not useful for most cases.

**Comment by alexcroox** [comment]
Makes sense thank you. I think as well because that EH featured so heavily on the dedicated guide wiki I assumed it was the main one to use (especially since `geofence` isn't mentioned once in the guide page). Just some general feedback on the docs that might help others :)
