### ISSUE TITLE
More than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by manish2535** [transistorsoft/cordova-background-geolocation-lt#536]
Spent a whole day trying to figure out this issue. Really want to use your plugin in our next App. Cant figure out which other app is using the package that its complaining about.

Attached build.gradle and build-extras.gradle.

[build-gradle.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1484121/build-gradle.zip)

Would really appreciate your help.

## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: Building on Windows 10
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config - havent gotten to that part yet

Installed Plugins
code-push 1.9.0-beta "CodePushAcquisition"
com.google.playservices 21.0.0 "Google Play Services for Android"
cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
cordova-fabric-plugin 1.0.8 "cordova-fabric-plugin"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-code-push 1.9.3-beta "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-crosswalk-webview 2.2.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-dialogs 1.3.2 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-opener2 2.0.2 "File Opener2"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-insomnia 4.2.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-evcore-extbuild-free 0.8.0 "Cordova sqlite storage - free enterprise version with Android performance/memory improvements for PhoneGap Build"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"

## Expected Behavior
Build should be successful

## Actual Behavior
Build Fails

## Steps to Reproduce
cordova build android

## Context
Trying to build the project. Cant run cordova android build. I get this error:

:processArmv7DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.
> Error: more than one library with package name 'com.google.android.gms'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 3.209 secs
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.
> Error: more than one library with package name 'com.google.android.gms'

**Comment by manish2535** [comment]
OK found out it was com.google.playservices. Removing this makes the build successful.

**Comment by christocracy** [comment]
Removing what?

It's a very common issue to have gradle conflicts between plugin's that import `play-services`.

The trick with play-services is that **all** plugins must be aligned to use the same version.

If one plugin requests version `10.2.1` and another `11.2.0`, your build will fail.

This is why this plugin now supports a config [`<variable name="GOOGLE_API_VERSION" />`](https://github.com/transistorsoft/cordova-background-geolocation-lt#configuration-variables) (and requires `cordova >= 7.1.0`)

**Comment by manish2535** [comment]
I removed the plugin com.google.playservices. I am not sure if my application is even making use of it as it did not complain about dependency while I was removing it.  

I  have started playing with the plugin now. I am pretty sure I will be contacting soon for a licence.

**Comment by christocracy** [comment]
You definitely don't want to use the plugin `com.google.playservices`.  That plugin includes play-services as a static jar.  We don't do that sort of thing anymore.

That plugin is a fork of [this](https://github.com/MobileChromeApps/google-play-services).  Look what the README says:

> THIS PLUGIN IS DEPRECATED!!! Plugins should use framework tags instead.

A `<framework />` is *exactly* how background-geolocation includes play-services.
