### ISSUE TITLE
iOs 10.3 stop and do not start again

### ISSUE THREAD

**Issue by robaraujo** [transistorsoft/cordova-background-geolocation-lt#537]
## Your Environment
* Plugin version: 2.9.1
* Platform: iOS
* OS version: 10.3
* Device manufacturer / model: Apple / iPhone 5c
* Cordova version: 7.1.0
* Cordova platform version: 4.5.3
* Plugin config
    ` {
            url: api,
            headers: headers,
            desiredAccuracy: 10,
            stationaryRadius: 30,
            distanceFilter: 50,
            interval: 60000*2,
            debug: true,
            logLevel: 5,
            pausesLocationUpdatesAutomatically: false,
        }`

## Expected Behavior
Keep calling the api with smartphone blocked

## Actual Behavior
Stop call the API after a few hours with the phone locked, it will only call again when you reopen the application.

**Comment by christocracy** [comment]
With that config, that's expected.

You need to `stopOnTerminate: false`.

Also, you need to be **VERY** careful setting `pausesLocationUpdatesAutomatically: false`.  If you don't explicitly `#stop` the plugin, location-services will be turned on permanently and kill the battery.

**Comment by robaraujo** [comment]
stopOnTerminate already setted to false, just omit, cause I think it's android specific config. I use `pausesLocationUpdatesAutomatically: false` to keep tracking even if device is locked, thats the right usage?

**Comment by christocracy** [comment]
> I use pausesLocationUpdatesAutomatically: false to keep tracking even if device is locked, thats the right usage?

**No**

The plugin doesn't care if the app is in foreground or background.  It only cares if the device is moving or stationary.  When the device is detected to be moving, it turns on location-services and begins tracking.

When the device is detected to be stationary, it turns off location services and conserves power.

[`stopOnTerminate`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#wrench-application-options) is clearly documented as a *Common Option*, not Android-specific.

**Comment by robaraujo** [comment]
Thanks for the explanation, the problem must be related to a long period in stationary state without opening the app, after that, even moving, the api is not called.
Android works perfectly.

**Comment by christocracy** [comment]
iOS can take 200 meters or more to reboot and resume tracking.
