### ISSUE TITLE
How do I identify, that the GeoLocation plugin is engaged for tracking?

### ISSUE THREAD

**Issue by kevinreynolds** [transistorsoft/cordova-background-geolocation-lt#54]
We use this plugin to track our fruit collectors. Due to the warm up delay we sometime misses to capture their tracks. Is there is a way to identify when the GeoLocation plugin is engaged for tracking?

**Comment by christocracy** [comment]
Yes, it fires motionchange event.  See docs

On Sunday, January 17, 2016, Kevin Reynolds <notifications@github.com>
wrote:

> We use this plugin to track our fruit collectors. Due to the warm up delay
> we sometime misses to capture their tracks. Is there is a way to identify
> when the GeoLocation plugin is engaged for tracking?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/54>
> .
>


-- 
Snet form Gmail Mobile
