### ISSUE TITLE
Update extras Don't work

### ISSUE THREAD

**Issue by younessAgouzzal** [transistorsoft/cordova-background-geolocation-lt#545]
## Your Environment
* Plugin version: 2.8.5
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Samsung Note 4
* Cordova version : 7.1.0
* Cordova platform version : 6.0.0
* Plugin config:
```
desiredAccuracy: 100,
            distanceFilter: 1800, //10
            desiredOdometerAccuracy: 100,
            stationaryRadius: 3,
            locationUpdateInterval: 60000,
            fastestLocationUpdateInterval: 60000,
            deferTime: 0,
            activityRecognitionInterval: 1000,
            stopTimeout: 30,
            url: "my-server-url",
            httpTimeout: 60000,
            method: 'POST',
            autoSync: true,
            batchSync: true,
            maxBatchSize: 1,
            maxDaysToPersist: 90,
            maxRecordsToPersist: 5000,
            stopOnTerminate: true,
            startOnBoot: false,//true
            heartbeatInterval: 60,
            preventSuspend: true,
            foregroundService: true,
            notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,

            forceReloadOnMotionChange: false,
            forceReloadOnLocationChange: true,
            forceReloadOnGeofence: false,
            forceReloadOnHeartbeat: true,//true
            forceReloadOnBoot: false,//true

            debug: true
```
## Expected Behavior
update the extras in the next heartbeat

## Actual Behavior
extras param don't change after a setConfig call

**Comment by christocracy** [comment]
Show me your Javascript code where you're executing `#setConfig`

**Comment by younessAgouzzal** [comment]
bgGeo.start(function() {
            bgGeo.setConfig({
                extras: {
                    'id': userData.id_eqp,
                    'journey': 'start'
                }
            });
        });

**Comment by christocracy** [comment]
Please learn to use syntax highlighting.
![](https://dl.dropboxusercontent.com/s/135et27x544ncvb/Screenshot%202017-11-23%2009.15.26.png?dl=1)

**Comment by younessAgouzzal** [comment]
done

**Comment by younessAgouzzal** [comment]
what is the correct way to update config after the start of the plugin

**Comment by christocracy** [comment]
>what is the correct way to update config after the start of the plugin

`#setConfig`

I see no issue with changing `#extras` with `#setConfig`.

What you probably *will* see in your case is the *first* location recorded has the *previous* extras, since the first thing `#start` does is request a location.  By the time the `callback` to `#start` has executed, where you change the `extras`, that first location has already been inserted into the database.

Set your `#extras` *before* you `#start`

```javascript
bgGeo.setConfig({
  extras: {foo: 'bar'}
});
bgGeo.start();
```

**Comment by christocracy** [comment]
And *be sure* you're not calling `#start` *before* `#configure` callback has executed.

```javascript
bgGeo.start();  // <---------- NO!
.
.
.
bgGeo.configure(config, function(state) {
  bgGeo.start();  // <--- YES
});
.
.
.
bgGeo.start();  // <---------- NO!
```

**Comment by younessAgouzzal** [comment]
I did that but in the server i get allways the first config
```
BackgroundGeolocation.setConfig({
  extras: {
      'id': userData.id_eqp,
      'journey': 'start'
  }
},function(){
    BackgroundGeolocation.start();
});

---or---

BackgroundGeolocation.setConfig({
  extras: {
      'id': userData.id_eqp,
      'journey': 'start'
  }
});
BackgroundGeolocation.start();
```

**Comment by christocracy** [comment]
in the code where you `#configure` the plugin add a `console.log`
```javascript
BackgroundGeolocation.configure(yourConfig, function(state) {
  console.log('*** configure callback');
});
```

In the code where you execute `#setConfig`, add 2 more `console.log`:
```javascript
console.log('*** before setConfig callback');
BackgroundGeolocation.setConfig(function(state) {
  console.log('*** after setConfig');
});
```

What are the order of the log messages?

**Comment by younessAgouzzal** [comment]
I have this order 

*** configure callback
*** before setConfig callback
*** after setConfig

I see in the log the extras param is updated but the probleme is that the extras i receive in server side is not correct

**Comment by christocracy** [comment]
You probably already have recorded locations in the plugin's database with the previous extras.

I cannot reproduce your issue.  When I change `#extras`, I see the new data at my server immediately.

**Comment by younessAgouzzal** [comment]
I used `BackgroundGeolocation.destroyLocations()` now i get the correct extras in server side
