### ISSUE TITLE
Basic error in recent versions

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#546]
Version 2.8.4 works without problems.
Versions 2.9.0 and 2.9.1 compile successfully, but when I run some script from the plugin, I get the error message "BackgroundGeolocation variable has not been defined".
Already version 2.8.5 of the error in compilation.
In all versions I used phonegap buil cli-7.0.1

**Comment by christocracy** [comment]
`2.9.x` requires [minimum Cordova 7.1.0](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L14)

**Comment by dbessa1** [comment]
but version 7.1.0 does not exist, see https://build.phonegap.com/current-support

**Comment by christocracy** [comment]
Then you cannot use `2.9.x` until PGB supports Cordova `7.1.0`.

**Comment by dbessa1** [comment]
Thank you for the clarifications.
