### ISSUE TITLE
Polylines are not making curves in the streets

### ISSUE THREAD

**Issue by manuvalentim** [transistorsoft/cordova-background-geolocation-lt#549]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* Cordova version (`7.0.1`):

## Actual Behavior
I'm having trouble representing polyline on the map when I need to do "curves" on the streets.
![screenshot_1](https://user-images.githubusercontent.com/20819292/33331943-19ff0296-d44a-11e7-84dc-db8ecafb5dab.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20819292/33331958-20358fae-d44a-11e7-9868-fa40f0617ef1.gif)

## Expected Behavior

![8a8041e3-c0c2-4058-86f0-7c6c2c2f1dcf 0](https://user-images.githubusercontent.com/20819292/33331983-33973d9a-d44a-11e7-95a9-8ab9bfdd9c88.png)

**Comment by christocracy** [comment]
This plugin isn't involved with map components (ie: Polylines).  It outputs location coordinates.  It's up to you to draw polylines.
