### ISSUE TITLE
Do you have an android Version

### ISSUE THREAD

**Issue by netbitsolutions** [transistorsoft/cordova-background-geolocation-lt#55]
Is there an android version?

**Comment by christocracy** [comment]
Not in this repo.  This is the free iOS only version.

Android is available for purchase here, as well as Android demo app in play store.
http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium

**Comment by netbitsolutions** [comment]
Ok, i will love to purchase the Premium Support for android for a client, but i need  documentation on what each plugin Api  does and it's effect if not assigned a value in the configure section( for optional options)

**Comment by christocracy** [comment]
Have you tried it yet?  What are you concerned about?

On Wednesday, January 20, 2016, netbitsolutions <notifications@github.com>
wrote:

> Ok, i will love to purchase the Premium Support for android for a client,
> but i need documentation on what each plugin Api does and it's effect if
> not assigned a value in the configure section( for optional options)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/55#issuecomment-173123591>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Have you tried the SampleApp?

https://github.com/transistorsoft/cordova-background-geolocation-SampleApp

On Wednesday, January 20, 2016, Chris Scott <christocracy@gmail.com> wrote:

> Have you tried it yet?  What are you concerned about?
>
> On Wednesday, January 20, 2016, netbitsolutions <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Ok, i will love to purchase the Premium Support for android for a client,
>> but i need documentation on what each plugin Api does and it's effect if
>> not assigned a value in the configure section( for optional options)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/55#issuecomment-173123591>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile
