### ISSUE TITLE
watchPosition not delivering locations to configured #url

### ISSUE THREAD

**Issue by chilimix** [transistorsoft/cordova-background-geolocation-lt#550]
## Your Environment
* Plugin version: 2.9.1
* Platform: iOS
* OS version: 10.3.3
* Device manufacturer / model: iPhone5C
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.2
* Plugin config :
```
{
      stationaryRadius: 0,
      distanceFilter: 0,
      activityRecognitionInterval: 10000,
      fastestLocationUpdateInterval: 1000,
      minimumActivityRecognitionConfidence: 50,
      stopOnTerminate: false,
      startOnBoot: true,
      forceReloadOnBoot: true,
      batchSync: true,
      autoSync: true,
      debug: false,
      maxDaysToPersist: 1,
      preventSuspend: true,
      heartbeatInterval: 60,
      geofenceProximityRadius: 1000,
      activityType: "Other",
      forceReloadOnMotionChange: true,
      forceReloadOnLocationChange: true,
      forceReloadOnHeartbeat: true,
      foregroundService: true,
      locationUpdateInterval: 30000,
      debug: true,
      batchSync: true,
      autoSyncThreshold: 1,
      desiredAccuracy: 0,
      url: "http://some_url"
}

```
## Expected Behavior
Locations delivered to the configured `#url` every 30 second.

## Actual Behavior
No location are delivered.

## Steps to Reproduce
```
app.bgGeo.watchPosition(function(location) { }, function(errorCode) { }, {
  interval: 30000,
  persist: true,
  desiredAccuracy: 0
});
```

## Notes
When starting the plugin first with `#start`, the locations are delivered as expected with start, plus every 30 second.
```
app.bgGeo.start(function () {
    app.bgGeo.watchPosition(function(location) { }, function(errorCode) { }, {
        interval: 30000,
        persist: true,
        desiredAccuracy: 0
    });
    app.bgGeo.changePace(true);
});
```

How can we recieve the locations on the configured `#url` without calling `#start`?

**Comment by christocracy** [comment]
Confirmed.  Fix applied to master in private repo.

**Comment by mikkelsjolin** [comment]
@chilimix Has the fix worked for you?

I'm on the master branch of the private repo and it still looks like the locations aren't getting through.

**Comment by mikkelsjolin** [comment]
Solved: I didn't supply options to watchPosition at first. After doing so, it started working.
