### ISSUE TITLE
Mock Location

### ISSUE THREAD

**Issue by hemantgogna** [transistorsoft/cordova-background-geolocation-lt#551]
Hi,
I am building a hybrid application and i want to know if the user is using spoof location or fake gps.
Is there any function/variable or anything else in this plugin that returns the same (basically a boolean stating if the given location is fake or spoofed). PS- i will be using it on android
Regards

**Comment by christocracy** [comment]
Yes, you find presence of `location.mock` on Android.

**Comment by hemantgogna** [comment]
Hi,
There is so such boolean in the return parameter of the successcallback of " bgGeo.on('location', onLocation, onError);". Is this "location.mock" available in the free version as well ? or am i looking in the wrong place ?.
Thanks again

**Comment by christocracy** [comment]
It is not present until the location is being mocked.

You will never see “mock”: false
