### ISSUE TITLE
Provider Status Check

### ISSUE THREAD

**Issue by DavidBriglio** [transistorsoft/cordova-background-geolocation-lt#552]
After some digging in the documentation I can't seem to find a way to obtain the providers on starting the plugin. I can use the 'providerchange' event to see when they change, but there is no way to know which are active before then.

My scenario is that I only want to use data when GPS is enabled. After attaching my handlers, configuring, and starting: it will work, but I will not know if GPS is enabled until a provider changes state.

Is this information obtainable outside of the 'providerchange' event?

**Comment by christocracy** [comment]
The `#configure` method automatically fires a `providerchange` event with the current state.  Make sure you listen to `providerchange` *before* calling configure or you'll miss the event.

```javascript
bgGeo.on('providerchange', this.onProviderChange.bind(this));

bgGeo.configure(config, (state) => {  // providerchange has just fired.
  console.log('- configure succcess: ', state);
});
```

**Comment by christocracy** [comment]
It's always best to listen to events *before* `#configure`.

**Comment by DavidBriglio** [comment]
Thank you!
