### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method zzagc()Lcom/google/android/gms/common/api/GoogleApiClient

### ISSUE THREAD

**Issue by pvdyck** [transistorsoft/cordova-background-geolocation-lt#554]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: 5.1.1
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):   android 6.4.0

* Plugin config

<?xml version='1.0' encoding='utf-8'?>
<widget defaultlocale="en" id="com.wimfi.parrotcity" version="0.98.0" xmlns="http://www.w3.org/ns/widgets">
    <name>Parrot.City</name>
    <description>Parrot.City civic network</description>
    <author email="dev@parrot.city" href="http://parrot.city/" />
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <preference name="BackupWebStorage" value="local" />
    <preference name="Orientation" value="portrait" />
    <preference name="webviewbounce" value="false" />
    <preference name="LoadingDialog" value="Title LoadingDialog, Message LoadingDialog" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="EnableWebGL" value="true" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="2000" />
    <preference name="SplashScreenBackgroundColor" value="transparent" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <allow-navigation href="*" />
    <engine name="android" spec="6.4.0" />
    <engine name="ios" spec="4.5.4" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="ionic-plugin-deeplinks" spec="1.0.15">
        <variable name="URL_SCHEME" value="parrotcity" />
        <variable name="DEEPLINK_SCHEME" value="https" />
        <variable name="DEEPLINK_HOST" value="parrotcity-tets.firebaseapp.com" />
        <variable name="ANDROID_PATH_PREFIX" value="/" />
        <variable name="DEEPLINK_2_SCHEME" value=" " />
        <variable name="DEEPLINK_2_HOST" value=" " />
        <variable name="ANDROID_2_PATH_PREFIX" value="/" />
        <variable name="ANDROID_3_PATH_PREFIX" value="/" />
        <variable name="ANDROID_4_PATH_PREFIX" value="/" />
        <variable name="ANDROID_5_PATH_PREFIX" value="/" />
        <variable name="DEEPLINK_3_SCHEME" value=" " />
        <variable name="DEEPLINK_3_HOST" value=" " />
        <variable name="DEEPLINK_4_SCHEME" value=" " />
        <variable name="DEEPLINK_4_HOST" value=" " />
        <variable name="DEEPLINK_5_SCHEME" value=" " />
        <variable name="DEEPLINK_5_HOST" value=" " />
    </plugin>
    <plugin name="ionic-plugin-keyboard" spec="2.2.1" />
    <plugin name="cordova-plugin-splashscreen" spec="4.1.0" />
    <plugin name="cordova-plugin-device" spec="1.1.7" />
    <plugin name="cordova-plugin-camera" spec="3.0.0">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="This app needs access to your camera to take photos and publish those on the social network" />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="This app needs access to your Photo Library to publish photos on the social network" />
    </plugin>
    <plugin name="cordova-plugin-statusbar" spec="2.3.0" />
    <plugin name="cordova-plugin-compat" spec="1.2.0" />
    <plugin name="cordova-plugin-network-information" spec="1.3.4" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="2.3.0">
        <variable name="XWALK_VERSION" value="23+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MULTIPLEAPK" value="true" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_MODE" value="embedded" />
    </plugin>
    <plugin name="cordova-plugin-vibration" spec="2.1.6" />
    <plugin name="cordova-plugin-x-socialsharing" spec="5.2.1" />
    <plugin name="cordova-background-geolocation-lt" spec="2.9.1">
        <variable name="LICENSE" value="xxxx" />
        <variable name="BACKGROUND_MODE_LOCATION" value="" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="[CHANGEME] Always use is required for constant background location-tracking" />
        <variable name="GOOGLE_API_VERSION" value="11.2.0" />
        <variable name="APPCOMPAT_VERSION" value="26.1.0" />
    </plugin>
    <plugin name="cordova-plugin-firebase" spec="0.1.24" />
    <plugin name="cordova-plugin-code-push" spec="1.10.0-beta" />
    <plugin name="cordova-plugin-actionsheet" spec="2.3.3" />
    <plugin name="cordova-plugin-file" spec="5.0.0" />
    <plugin name="cordova-plugin-file-transfer" spec="1.7.0" />
    <plugin name="cordova-plugin-x-toast" spec="2.6.0" />
    <plugin name="cordova-plugin-multidex" spec="0.1.4" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.16" />
</widget>

## Steps to Reproduce
start the app

## Context
start the app ... 
## Debug logs

12-06 17:02:54.546 8721-8721/? I/art: Late-enabling -Xcheck:jni
12-06 17:02:54.566 8721-8733/? I/art: Debugger is no longer active
12-06 17:02:55.016 8721-8721/? I/MultiDex: VM with version 2.1.0 has multidex support
12-06 17:02:55.016 8721-8721/? I/MultiDex: Installing application
12-06 17:02:55.016 8721-8721/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
12-06 17:02:55.056 8721-8721/? W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
12-06 17:02:55.066 8721-8721/? W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
12-06 17:02:55.086 8721-8721/? I/BiChannelGoogleApi: [FirebaseAuth: ] No Fallback module; NOT setting up for lazy initialization
12-06 17:02:55.126 8721-8748/? I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
12-06 17:02:55.126 8721-8748/? I/DynamiteModule: Selected local version of com.google.android.gms.flags
12-06 17:02:55.126 8721-8745/? W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
12-06 17:02:55.136 8721-8748/? W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
12-06 17:02:55.136 8721-8748/? W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
12-06 17:02:55.136 8721-8748/? W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
12-06 17:02:55.146 8721-8745/? I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
12-06 17:02:55.146 8721-8745/? I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
12-06 17:02:55.146 8721-8748/? I/DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:10
12-06 17:02:55.146 8721-8748/? I/DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 10
12-06 17:02:55.246 8721-8721/? V/FA: Registered activity lifecycle callback
12-06 17:02:55.246 8721-8721/? I/FirebaseInitProvider: FirebaseApp initialization successful
12-06 17:02:55.256 8721-8721/? I/InstantRun: starting instant run server: is main process
12-06 17:02:55.276 8721-8752/? V/FA: Collection enabled
12-06 17:02:55.276 8721-8752/? V/FA: App package, google app id: com.wimfi.parrotcity, 1:610934719955:android:28ab28526762b159
12-06 17:02:55.276 8721-8752/? I/FA: App measurement is starting up, version: 11720
12-06 17:02:55.276 8721-8752/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-06 17:02:55.276 8721-8752/? I/FA: To enable faster debug mode event logging run:
                                       adb shell setprop debug.firebase.analytics.app com.wimfi.parrotcity
12-06 17:02:55.276 8721-8752/? D/FA: Debug-level message logging enabled
12-06 17:02:55.286 8721-8748/? I/FirebaseCrashApiImpl: FirebaseCrashApiImpl created by ClassLoader t[DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/00000041/DynamiteModulesC_GmsCore_prodlmp_xxhdpi_release.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
12-06 17:02:55.286 8721-8748/? I/FirebaseCrash: FirebaseCrash reporting loaded - com.google.android.gms.internal.zzdxv@1bde92e5
12-06 17:02:55.296 8721-8752/? V/FA: Connecting to remote service
12-06 17:02:55.316 8721-8752/? V/FA: Connection attempt already in progress
12-06 17:02:55.326 8721-8749/? I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
12-06 17:02:55.326 8721-8749/? I/DynamiteModule: Selected local version of com.google.android.gms.flags
12-06 17:02:55.336 8721-8749/? W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
12-06 17:02:55.366 8721-8749/? I/FirebaseCrashApiImpl: FirebaseCrash reporting API initialized
12-06 17:02:55.366 8721-8749/? I/FirebaseCrash: FirebaseCrash reporting initialized com.google.android.gms.internal.zzdxv@1bde92e5
12-06 17:02:55.366 8721-8749/? D/FirebaseCrash: Firebase Analytics Listener for Firebase Crash is initialized
12-06 17:02:55.536 8721-8721/? I/TSLocationManager: [c.t.l.util.Sensors print] 
                                                    ╔═════════════════════════════════════════════
                                                    ║ DEVICE SENSORS
                                                    ╠═════════════════════════════════════════════
                                                    ╟─ ✅  ACCELEROMETER: {Sensor name="BMI160 Accelerometer", vendor="BOSCH", version=1173700, type=1, maxRange=39.22661, resolution=0.0011901855, power=0.18, minDelay=5000}
                                                    ╟─ ✅  GYROSCOPE: {Sensor name="BMI160 Gyroscope", vendor="BOSCH", version=1173700, type=4, maxRange=34.906586, resolution=0.0010681152, power=0.9, minDelay=5000}
                                                    ╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetometer", vendor="Yamaha", version=35193090, type=2, maxRange=2000.0, resolution=0.30059814, power=0.28, minDelay=10000}
                                                    ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.17999268, minDelay=-1}
                                                    ╚═════════════════════════════════════════════
12-06 17:02:55.686 8721-8721/com.wimfi.parrotcity D/AndroidRuntime: Shutting down VM
12-06 17:02:55.686 8721-8721/com.wimfi.parrotcity E/UncaughtException: java.lang.NoSuchMethodError: No virtual method zzagc()Lcom/google/android/gms/common/api/GoogleApiClient; in class Lcom/google/android/gms/common/api/GoogleApi; or its super classes (declaration of 'com.google.android.gms.common.api.GoogleApi' appears in /data/app/com.wimfi.parrotcity-1/split_lib_dependencies_apk.apk)
                                                                           at com.google.android.gms.location.ActivityRecognitionClient.requestActivityUpdates(Unknown Source)
                                                                           at com.transistorsoft.locationmanager.BackgroundGeolocationService.b(Unknown Source)
                                                                           at com.transistorsoft.locationmanager.BackgroundGeolocationService.onStartCommand(Unknown Source)
                                                                           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2899)
                                                                           at android.app.ActivityThread.access$2100(ActivityThread.java:154)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5269)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
12-06 17:02:55.706 8721-8752/com.wimfi.parrotcity I/DynamiteModule: Considering local module com.google.android.gms.tagmanager:12 and remote module com.google.android.gms.tagmanager:12
12-06 17:02:55.706 8721-8752/com.wimfi.parrotcity I/DynamiteModule: Selected remote version of com.google.android.gms.tagmanager, version >= 12
12-06 17:02:55.766 8721-8752/com.wimfi.parrotcity W/GoogleTagManager: No container asset found in /assets/containers. Checking top level /assets directory for container assets.
12-06 17:02:55.786 8721-8752/com.wimfi.parrotcity W/GoogleTagManager: Tag Manager's event handler WILL NOT be installed (no container loaded)
12-06 17:02:55.786 8721-8752/com.wimfi.parrotcity I/GoogleTagManager: Tag Manager initilization took 46ms
12-06 17:02:55.796 8721-8752/com.wimfi.parrotcity D/FA: Logging event (FE): app_exception(_ae), Bundle[{firebase_event_origin(_o)=crash, timestamp=1512576175696, fatal=1}]
12-06 17:02:55.806 8721-8752/com.wimfi.parrotcity V/FA: Connection attempt already in progress
12-06 17:02:55.976 8721-8721/com.wimfi.parrotcity E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.wimfi.parrotcity, PID: 8721
                                                                    java.lang.NoSuchMethodError: No virtual method zzagc()Lcom/google/android/gms/common/api/GoogleApiClient; in class Lcom/google/android/gms/common/api/GoogleApi; or its super classes (declaration of 'com.google.android.gms.common.api.GoogleApi' appears in /data/app/com.wimfi.parrotcity-1/split_lib_dependencies_apk.apk)
                                                                        at com.google.android.gms.location.ActivityRecognitionClient.requestActivityUpdates(Unknown Source)
                                                                        at com.transistorsoft.locationmanager.BackgroundGeolocationService.b(Unknown Source)
                                                                        at com.transistorsoft.locationmanager.BackgroundGeolocationService.onStartCommand(Unknown Source)
                                                                        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2899)
                                                                        at android.app.ActivityThread.access$2100(ActivityThread.java:154)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5269)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
12-06 17:02:55.976 8721-8721/com.wimfi.parrotcity I/Process: Sending signal. PID: 8721 SIG: 9

**Comment by christocracy** [comment]
I changed the plugin to use more modern play-services APIs because they're much easier and less error-prone to use than old ones (which are now deprecated).

However, the plugin now requires `play-services >= 11.2.0`.

Paste your `platforms/android/project.properties`.  You'll find some of your other plugins are importing `play-services < 11.2.0`.

**Comment by pvdyck** [comment]
cat platforms/android/project.properties | grep -i play

cordova.system.library.3=com.google.android.gms:play-services-location:11.6.0
cordova.system.library.6=com.google.android.gms:play-services-tagmanager:+


P.S.: you are providing the fastest support in the galaxy !

**Comment by pvdyck** [comment]
full project.properties 👍 
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.system.library.2=com.android.support:support-v4:24.1.1+
cordova.system.library.3=com.google.android.gms:play-services-location:11.6.0
cordova.system.library.4=com.android.support:appcompat-v7:26.1.0
cordova.gradle.include.1=cordova-background-geolocation-lt/parrotcity-build.gradle
cordova.gradle.include.2=cordova-plugin-firebase/parrotcity-build.gradle
cordova.system.library.5=com.google.gms:google-services:+
cordova.system.library.6=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.7=com.google.firebase:firebase-core:+
cordova.system.library.8=com.google.firebase:firebase-messaging:+
cordova.system.library.9=com.google.firebase:firebase-crash:+
cordova.system.library.10=com.google.firebase:firebase-config:+
cordova.gradle.include.3=cordova-plugin-code-push/parrotcity-build-extras.gradle
cordova.gradle.include.4=cordova-plugin-multidex/parrotcity-build.gradle
cordova.gradle.include.5=cordova-plugin-crosswalk-webview/parrotcity-xwalk.gradle

**Comment by christocracy** [comment]
>P.S.: you are providing the fastest support in the galaxy !

That's what you pay for:  dedicated support.

As a hack, change all `com.google.*` dependencies from `:+` to `:11.6.0` and it will work.

You need to find all your other plugins requiring those dependencies and coax them to align to the same version of `play-services`

**Comment by pvdyck** [comment]
I didn't have the problem before ... can I downgrade in the meantime and if yes, to what version ?

**Comment by christocracy** [comment]
[`2.8.5`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#285---2017-09-25)

Scroll up to see everything you're missing.  Do **NOT** get stuck behind just because of poor behaviour of *other* plugins.

If you care about Android 8, you need to use `2.9.1` ASAP.

**Comment by pvdyck** [comment]
Thank you for your help.

Trying to upgrade to the latest version I faced a couple of issues.

The upgrade to the latest version of gradle forces me to define "flavors" of binaries (arm & intel) when I use xwalk and it does not build anymore.

I'll wait for all those issues to be solved and all the plugins to be aligned on using the new mechanism... is there a common agreement regarding that ?

**Comment by pvdyck** [comment]
I mean, is Telerik or another plugin aggregator planning to do something ?

**Comment by christocracy** [comment]
- common agreement is not necessary.
- it’s not *all* plugins, only those which require play-services / firebase dependencies.
- this is not a concern of app aggregators, other than supporting Cordova 7.1.0
- you will help your situation by posting requests at the offending plugins’ repo, rather than quietly waiting and hoping.
