### ISSUE TITLE
Feature request: On IOS, option to actively poll for localisation when background tracking is not active

### ISSUE THREAD

**Issue by hypersolution1** [transistorsoft/cordova-background-geolocation-lt#555]
With this plugin, on IOS, the device must move for 200 meters before getting any tracking. This make sense for the car use case. We all know that Apple knows best when designing and would never think of any other tracking usage (such as pedestrian or bicycle).

Right now, my plan is to combine your plugin, for keeping the app running in background, and cordova-plugin-geolocation to actively poll while your plugin stays silent.

Would it be possible, on IOS, to have an option for your plugin to actively poll the position, offering a unique data source for localisation, during the 200 meters while the background tracking is not active?

**Comment by christocracy** [comment]
> my plan is to combine your plugin, for keeping the app running in background, and cordova-plugin-geolocation

Bad idea.  My plugin does *everything* `cordova-plugin-geolocation` does.  See 

>We all know that Apple knows best when designing and would never think of any other tracking usage

There's a reason Apple is strict about suspending apps in the background:  Google: ["iphone battery sucks"](https://www.google.ca/search?q=iphone+battery+sucks&oq=iphone+battery+sucks&aqs=chrome..69i57j0l5.2451j0j4&sourceid=chrome&ie=UTF-8).  They receive this bad press often due to poor behaviour of App developers.

What is the purpose of your app that you feel you need to "actively poll" even when device is not active?  Are your users aware of this behaviour, that you're destroying their battery life?  Do you own these devices?

**Comment by hypersolution1** [comment]
You're right, I forgot to recheck your API.

Consider this use case as an example, (I prefer to keep our real use case confidential):  An app to guide blind people in the streets. Once the directions defined, this app is put in background and communicate in audio with a bluetooth device. Does this blind people need to walk 200 meters in any directions before getting instructions?

For our use case, our users are aware, and it is not always active (most of the time inactive, we anticipate about 1 hour usage per day as an estimate). We need to be power efficient too to gives a good users experience.

**Comment by christocracy** [comment]
See [`preventSuspend`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-preventsuspend-false)

**Comment by christocracy** [comment]
```javascript
bgGeo.on('heartbeat', (event) {
  // You're free to do whatever you want here, including #getCurrentPosition
});
```

Note that with `preventSuspend: true`, the plugin is listening to the [`CMMotionActivityManager`](https://developer.apple.com/documentation/coremotion/cmmotionactivitymanager) API.  The plugin will quickly detect when the device is moving / stationary and automatically trigger tracking.  You don't necessarily need to constantly `#getCurrentPosition`.

Note also, that iOS will suspend the `heartbeat` events when device is unplugged from power and off.  As soon as device movement is detected or the user lights up their screen, the heartbeat timer will start running again.

It is *impossible* to get `heartbeat` events when device is off and lying still.

**Comment by hypersolution1** [comment]
That is great! I'll test this but it seems that will do the trick. Thanks!
