### ISSUE TITLE
Licence validation failure toast showing even when the plugin is not started

### ISSUE THREAD

**Issue by N0ps32** [transistorsoft/cordova-background-geolocation-lt#557]
After I updated the plugin to the latest version I have a popup in my Android app about my licence key being invalid. This did not happen before I upgraded. 

I only want to run the plugin in my iOS app, which according to the documentation doesn't need a licence. **The code that initializes the plugin is only run on iOS and not on Android**.

```
init() {
        navigator.geolocation.getCurrentPosition(() => {
            let config = this._getConfig();

            this.bgGeo.configure(config, state => {
                if (!state.enabled) {
                    this.bgGeo.start();
                }
            });

            this.bgGeo.onLocation(location => {
                this.log.info('called background location callback');
                if (this.pedometerType === 'geo') {
                    GPSPedometer.evaluateGeodata(location.coords.latitude, location.coords.longitude, location.timestamp, location.accuracy);
                }
            }, error => this.log.error(error));
        }, err => {
            this.log.error(err);
            GPSPedometer.showNoGPSBadge();
        }, {});
    }
```

How can I make sure the plugin is not initialized on Android?

## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Samsung Galaxy Note 8
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0, ios 4.5.4
* Plugin config

## Expected Behavior
No Licence validation failure toast should be shown on Android since the plugin is only used on iOS to keep the app alive in the background.

## Actual Behavior
Licence validation failure toast is shown on Android.

## Steps to Reproduce
1. Install Plugin

**Comment by christocracy** [comment]
Customers should use the private repo.  This public version is only the latest stable release, typically updated every few *months*.

Latest updates / features / fixes always first appear in the private repo.

See [Wiki](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/License-Validation-Failure)

When you:
```
$ cordova plugin remove cordova-background-geolocation
```
Cordova **DELETES YOU `LICENSE`** from `config.xml`.

use `--nosave` option, to prevent Cordova from *saving* changes to your `config.xml` when it removes the plugin

```
$ cordova plugin remove --nosave cordova-background-geolocation
```

**Comment by N0ps32** [comment]
But that was not the question, I don't have a licence key. I only need the plugin for iOS not for Android which doesn't need a licence. But cordova AFAIK doesn't give you an option to only install a plugin for one platform.

I don't understand why I get the licence popup even though the plugin is **not initialized on Android**.
The only solution I see to this from my side is to fork this repository and remove Android support from the plugin manually. But that's not really a good option.

**Comment by christocracy** [comment]
Why don't you need it for Android?

**Comment by N0ps32** [comment]
This whole App is a legacy application with a step-counting function in it.

If no native step-counter sensor is available in the device (iPhone 5 and older) the App will fall back on using GPS to estimate the amount of walked steps in the background. On iOS the best and easiest solution was this plugin.

On Android we have developed our own in-house solution to overcome some of the problems we had.
This setup has worked fine for the last 3+ years and now after updating the plugin I get the licence popup on Android even though I'm not using the plugin on that platform.

Granted this is probably somewhat of an edge-case but it's still a valid issue imo.

**Comment by christocracy** [comment]
You'll have to fork it and remove Android.
