### ISSUE TITLE
Execution error while building android phone gap build

### ISSUE THREAD

**Issue by asifmehmood91** [transistorsoft/cordova-background-geolocation-lt#558]
when i Run the command phonegap build android it gives me the the `error execution failed for task 'mergeDebugResources'` I am implementing the plugin `cordova-background-geolocation-lt` and following the same as explained there and install the same SDK's.
complete error 
![jmtoq](https://user-images.githubusercontent.com/14163289/33678860-eac392e4-dade-11e7-9cf9-c42e5ae365a7.png)

Here is some more info about DEBUG after running the command `gradlew.bat --info build clean`

![ktnyy](https://user-images.githubusercontent.com/14163289/33678939-20af67f2-dadf-11e7-8a1b-fe0e8a326bf9.png)

**Comment by christocracy** [comment]
Don't know.  Nothing points to the plugin here.

**Comment by christocracy** [comment]
Have you [searched this error](https://www.google.ca/search?q=java.util.concurrent.executionexception+com.android.ide.common.process.processexception&oq=java.util.concurrent.Executionexception+com.android.ide.common.&aqs=chrome.0.0j69i57.27482j0j4&sourceid=chrome&ie=UTF-8)

This seems to be an **ide** exception.

```
com.android.ide.common.process.processexception
```
