### ISSUE TITLE
heartbeatInterval config ignored in Android

### ISSUE THREAD

**Issue by hypersolution1** [transistorsoft/cordova-background-geolocation-lt#559]
During my test, I compared the heartbeat behavior between IOS and android. I set the heartbeatInterval to 3 seconds. This is working as expected in IOS but not in Android. I get a 60 seconds heartbeat interval in Android.  (Although I don't need and don't plan to use the heartbeat event in Android, it doesn't work as expected)

## Your Environment
* Plugin version: 2.9.1 
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Galaxy S6, SM-G920W8
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 
  android 6.3.0
  ios 4.5.4
* Plugin config

## Expected Behavior

In config, `heartbeatInterval: 3` would give me a `heartbeat` event every 3 seconds

## Actual Behavior

The event is triggered ~60 seconds

**Comment by christocracy** [comment]
Android minimum `heartbeatInterval` is 60 seconds.  This is an [`AlarmManager`](https://developer.android.com/reference/android/app/AlarmManager.html) API limitation.

In practice, a 3 second heartbeat is going to make the CPU spin like crazy.  Might be good if you're trying to fry eggs, if the battery lasts long enough.

**Comment by hypersolution1** [comment]
That is fine by me. Is it documented somewhere in your plugin docs?

**Comment by christocracy** [comment]
If it's not documented, it doesn't matter.  The Android minimum is 60s.  It's impossible to have anything quicker.

I wouldn't count on iOS interval < 60.  I may enforce that to 60s in the future.

**Comment by hypersolution1** [comment]
I'm not sure why you would do that since I find it a better idea to rely on your heartbeat (that shut of when still) instead of an active polling. Remember I'm doing this to circumvent that 200 meters "radio silence" of IOS tracking. I do want to rely on the `location` event and I would even want to disable the heartbeat (or polling if the 3 second heartbeat wouldn't be possible in the future) if I detect the `location` event.

Would it be possible to fire events to signal when we are in and out the 200 meters IOS "limbo" state?

**Comment by christocracy** [comment]
`heartbeat` / `heartbeatInterval` is unimportant for "circumventing the 200 meters radio silence".

a 3s vs 3000000000s `heartbeatInterval` affects nothing.

The plugin is monitoring events from `CMMotionActivityManager` in real time.  `CMMotionActivityManager` fires events asynchronously and unrelated to `heartbeatInterval`.

When `CMMotionActivityManager` tells the plugin that the device is moving, the plugin will engage location-services.  `heartbeatInterval` has nothing to do with this.

**Comment by christocracy** [comment]
You can capture the `CMMotionActivityManager` events in real-time by listening to the `activitychange` event.

**Comment by hypersolution1** [comment]
I was referring to your answer in: https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/555 about the behavior of `heartbeat` events.

I'm aware that the heartbeat settings/mechanism has nothing to do with `CMMotionActivityManager`

But, during that 200 meters when there is no `location` events, the `heartbeat` event callback gives me a location that makes this plugin useful for us, and it is a crucial step to replace our current native app to a new app that integrate your plugin (and of course purchasing a license).

**Comment by christocracy** [comment]
While the plugin is stationary in `preventSuspend` mode, that location you see in the `heartbeat` event is the *last known location*.  It's the same *old* location sent to every heartbeat event.  It is *not* the current location.

You need to be aware that the plugin has a lot of intelligence baked-into `preventSuspend` mode.  Don't re-invent the wheel.  The plugin is always asking "am I moving?  Should I start tracking?" when motion-activity events are received.

`activitychange` is going to be far more interesting to you than `heartbeat` event.

**Comment by christocracy** [comment]
Are you field-testing this with `debug: true`?

Just do so and go walk.  The plugin will tell you exactly what's happening with debug sounds and notifications.

**Comment by hypersolution1** [comment]
I don't know what to say. From your documentation about `heartbeat` callback:

[here](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#param-object-location--when-the-plugin-detects-movement-ios-only-it-will-always-request-a-new-high-accuracy-location-in-order-to-determine-if-the-device-has-moved-beyond-stationaryradius-and-if-the-location-has-speed--0--this-fresh-location-will-be-provided-to-your-callbackfn--android-will-simply-return-the-last-known-location)

> When the plugin detects movement (iOS only), it will always request a new high-accuracy location in order to determine if the device has moved beyond stationaryRadius and if the location has speed > 0. This fresh location will be provided to your callbackFn. Android will simply return the "last known location"

I just tested it and it works, it gives me an "accurate" location for our use.

Yes, I compiled your example app and tested it partially with the debug sounds on.

**Comment by hypersolution1** [comment]
I found that I didn't need to call `getCurrentPosition` since the heartbeat callback seemed to already have the right info.

**Comment by christocracy** [comment]
That *last known location* isn't going to change if you leave the device still for 8 hours.  Yes, if you walk around the house, the plugin is going to sense that and say "Hey, I'm moving!  Where am I?  Am I `stationaryRadius` meters distance away from my stationary-location?

As soon as the device detects it has moved `stationaryRadius` meters beyond the stationary-location, it's going to turn on location-services and begin recording locations every `distanceFilter` meters.

If you're attempting to use the location provided to you in the `heartbeat` event to do some calculation about whether the device is moving, you're re-inventing the wheel.  This is already being done for you.

**Comment by hypersolution1** [comment]
I'm using it to know where I am in respect to a given coordinate in order to indicate some sort of real-time progression, not to figure out if I'm moving.

**Comment by christocracy** [comment]
>I'm using it to know where I am in respect to a given coordinate in order to indicate some sort of real-time progression

And you hope to perform this while they're walking from the living room to the kitchen where indoor location accuracy is 40-60 meters (if you're lucky)?

The most important data for you will come when they walk outdoors and the plugin is quickly going to detect that and start firing the `location` event.

**Comment by hypersolution1** [comment]
It is not for indoor use. I know the limitations of GPS. If you want more information, we could discuss this privately by email.
