### ISSUE TITLE
Cordova "deviceready" event is not firing

### ISSUE THREAD

**Issue by blargism** [transistorsoft/cordova-background-geolocation-lt#56]
I'm doing a very simple `window.addEventListener('deviceready', initFunction);`  The event never fires. I'm using an angular stack, but this event listener is outside of angular.  I've brought it down to be as simple as an alert in event listener callback.  No dice.  Note that this is the only plugin I'm using.

**Comment by christocracy** [comment]
I'm not responsible for deviceready event not firing.

If my plugin were a car stereo, I'm not the guy to ask if your Cordova car
doesn't start.

Try my SampleApp first.  It'll work.

https://github.com/transistorsoft/cordova-background-geolocation-SampleApp


On Thursday, January 21, 2016, Joe Mills <notifications@github.com> wrote:

> I'm doing a very simple window.addEventListener('deviceready',
> initFunction); The event never fires. I'm using an angular stack, but
> this event listener is outside of angular. I've brought it down to be as
> simple as an alert in event listener callback. No dice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/56>
> .
>


-- 
Snet form Gmail Mobile
