### ISSUE TITLE
Is it legal to fork this repository publicly on Github?

### ISSUE THREAD

**Issue by N0ps32** [transistorsoft/cordova-background-geolocation-lt#560]
I want to fork this Repository to remove a couple of features from the publicly visible code of the plugin. The licence agreement on the bottom of the page states that:

> License Grant: Licensor hereby grants Licensee a Personal, Non-assignable & non-transferable, Commercial, Royalty free, Including the rights **to create but not distribute derivative works**, Non-exclusive license, all with accordance with the terms set forth and other legal restrictions set forth in 3rd party software used while running Software.

Does that mean that I have to fork the plugin into a private repository? Otherwise I'd be distributing  derivative work.

Wikitude, another commercial plugin has solved this by keeping the public code under Apache 2.0 and having a special licence for their binary blobs.

**Comment by christocracy** [comment]
What features do you hope to remove?

**Comment by N0ps32** [comment]
The Android platform

**Comment by christocracy** [comment]
Oh, now I remember you.  Go ahead.

**Comment by N0ps32** [comment]
Okay thank you!
