### ISSUE TITLE
POST activity when app killed

### ISSUE THREAD

**Issue by everettglovier** [transistorsoft/cordova-background-geolocation-lt#561]
Is this supposed to POST to the url even if the app is killed? It works perfectly when opened and in the background, but it does nothing when the app is killed, even if I move for miles. I am wondering if my config is incorrect.

Running the sample Ionic + TypeScript code.

**Your Environment**

Plugin version: 2.8.5
Platform: iOS
OS version: 11.1
Cordova version (cordova -v): 7.0.1
Cordova platform version (cordova platform ls): 4.4.0
Plugin config

`{ desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 1,
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        debug: true, 
        stopOnTerminate: false,
        startOnBoot: true,
        url: "XXXX",
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 365 }`

**Expected Behavior**
POST to url even when app is killed

**Actual Behavior**
No POST

**Steps to Reproduce**
Run app. Receive POST. Kill app and drive for a few miles. No POST until app is reopened.

**Comment by christocracy** [comment]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by everettglovier** [comment]
@christocracy Updated! Sorry. I know that it's incredibly annoying when people don't follow the template. I just didn't think this was a "bug" as much as user error.

**Comment by christocracy** [comment]
Android and iOS are *completely* different animals and the version matters.

**Comment by christocracy** [comment]
I just killed my sample app and walked 200 meters.  Apps booted in bg and started tracking.

Your device has a provisioned sim with WiFi enabled?

Always authorization?

**Comment by christocracy** [comment]
You can expect your iPhone to operate just as in the simulator, like [this video](https://youtu.be/aR6r8qV1TI8?t=213)

**Comment by everettglovier** [comment]
I have the simulator working! But, no go on the actual phone. Have tested on two devices, wifi on and off.

**Comment by everettglovier** [comment]
```
constructor(public zone: NgZone, public platform: Platform, public afDb: AngularFireDatabase, public server: Server, public navCtrl: NavController, private toastCtrl: ToastController) {		
		platform.ready().then(this.configureBackgroundGeolocation.bind(this));		
  }

	configureBackgroundGeolocation(){

		var that = this;
		
		this.bgGeo = (<any>window).BackgroundGeolocation;

    // 2. Listen to events
    /*this.bgGeo.on('location', this.onLocation.bind(this));
    this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
    this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
    this.bgGeo.on('geofence', this.onGeofence.bind(this));
    this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));*/

    // BackgroundGeoLocation is highly configurable.
    this.bgGeo.configure({
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 1,
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        stopOnTerminate: false,
        startOnBoot: true,
        url: "https://us-central1-now-1-1.cloudfunctions.net/geolocation",
        method: "POST",
				params: { user: this.server.user.uid },
        autoSync: true,
        maxDaysToPersist: 1
    }, (state) => {
    	this.bgGeo.start();
    });
	}

```

**Comment by christocracy** [comment]
You’re developing blind.  Set debug: true and enable Audio/AirPlay background mode in XCode (so plugin can play debug sound fx in background.

See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

**Comment by christocracy** [comment]
Update please.

**Comment by everettglovier** [comment]
Hi! Sorry for the delay. The issue was related to trying to load an async function. You can close! So sorry for the runaround.
