### ISSUE TITLE
What's the best way to mock new locations in Android?

### ISSUE THREAD

**Issue by adsonvinicius** [transistorsoft/cordova-background-geolocation-lt#562]
Hi, I tried to emulate an app using this plugin in Xcode through location (Freeway drive) and everything worked fine. However in Android tests i tried apps to mock locations and the locations' updates are rare. I don't know whether is this apps or the plugin that is not working as expected in Android. So what the best way to mock a city drive for example in Android using this plugin?

**Comment by christocracy** [comment]
The key for mocking Android location is to understand the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

When your device is sitting still on your desk, the plugin is in stationary mode.  It doesn't matter that you're simulating location.  The MotionActivity api (which aggregates accelerometer, gyroscope and magnetometer) says the device is `still`.

The plugin only opens its ears and *listens * for those mocked locations until the motion API says `on_foot`, `in_vehicle`, `running`, etc.

Or you manually tell the plugin to enter the *moving* state by executing `changePace(true)`.

Also see the [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging#android-1) Wiki.
