### ISSUE TITLE
Unable to find attribute android:font

### ISSUE THREAD

**Issue by mushishi78** [transistorsoft/cordova-background-geolocation-lt#563]
## Your Environment
* Plugin version: 2.8.5
* Platform: Android
* OS version: N/a
* Device manufacturer / model: N/a
* Cordova version:  7.0.2
* Cordova platform version: 6.2.3 ([source](https://blog.phonegap.com/phonegap-7-0-1-now-on-build-and-it-includes-some-important-changes-89087fe465f5)
* Plugin config:

```
<plugin name="cordova-background-geolocation-lt" source="npm" version="2.8.5" />
```

## Expected Behavior
It should build.

## Actual Behavior
It does not build.

## Steps to Reproduce
1. Run a build with PhoneGap Build

I have not tried a minimum reproduction project yet, so will come back and edit steps if I need to.

## Context
This is my first installation of plugin, so I'm just prototyping it. Our project is using the PhoneGap Build cloud service to build our application. I could probably make a local build, but it is helpful for our team who don't own macs to have one config that works with the cloud service.

I originally tried the latest version 2.9.1, but this relies on Cordova 2.1 and PhoneGap Build seems to run Cordova 2.0. So I dropped back to version 2.8.5 and this successfully builds on iOS, but not Android.

A similar error has occurred to other people:

* https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/507
* https://forum.ionicframework.com/t/android-build-broken-after-gradle-dependencies-update-execution-failed-for-task-processdebugresources-com-android-ide-common-process-processexception-failed-to-execute-aapt/109982/2
* https://stackoverflow.com/questions/47062650/unable-to-find-attribute-androidfont-for-v7-support
* https://github.com/mauron85/react-native-background-geolocation/issues/116
* https://forums.adobe.com/thread/2405676

The generally accepted advice is that `com.android.support:support-v4:27` is causing the problem, so if you have `com.android.support:support-v4:+`, then you should specify `com.android.support:support-v4:23.+`.

However, I haven't got this to work as of yet. I am fairly new to Cordova development, so I've just been making fairly arbitrary guesses at what changes are needed to make it work.

I've tried to adding this line:

```
<framework src="com.android.support:support-v4:23+" value="gradle" />
```

To my `config.xml` (both in and outside the android platform) . I also tried forking your plugin and adding it to your `plugin.xml` file in the android platform section.

I've tried setting `android-compileSdkVersion`, `android-minSdkVersion`, `android-targetSdkVersion` incase they helped.

I saw somewhere that setting `com.android.support:appcompat-v7:23+` might help, but that did nothing me.

I tried various edits of your `build.gradle` but to no avail. For instance somewhere seem to imply that adding:

```
{
    exclude group: 'com.android.support'
}
```

To the dependency compiles lines might help. However it did nothing.

## Debug logs
```
:processArmv7DebugResourcesERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.171 secs
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

I can appreciate that this problem may seem unrelated to your plugin, as PhoneGap Build and Android support are outside of your control. However, as it only happens to me when installing your plugin, it seems reasonable to post here in case other users are having the similar difficulties.

For my part I will cross post this on other forums, then make a local build so I can run with verbose and then try to make a minimal reproduction setup.

Any help in the meantime would be appreciated.

**Comment by christocracy** [comment]
It’s a problem with app-support dependency problem.

Post your platforms/android/project.properties

**Comment by mushishi78** [comment]
Thanks for quick reply. As I'm currently building on a cloud service, I believe that files on their computer not mine. But when if I recreate problem with a local build then I will post the contents of that file :)

**Comment by christocracy** [comment]
Cloud build services, like PhoneGap Build are *deployment* services -- not *development* builds.

Learn to **build locally**.  You know you can't use this plugin booting your app in the browser?  You need to develop on a device or simulator.

**Comment by mushishi78** [comment]
I have cross-posted this issue on the [PhoneGap Build](https://forums.adobe.com/message/10028062) forum and [stackoverflow](https://stackoverflow.com/questions/47716727/unable-to-find-attribute-androidfont).

A *deployment* service would be actually delivering the application to the customer. PhoneGap Build just assembles it into a package. It's useful because you need a mac to build for iOS and not everyone on the team wants to use a mac as their development machine. The upload time to the cloud service doesn't take a significant amount of time compared to the actual build, so I can't imagine it would improve development iteration time significantly to build the packages locally. Given that I have to use a cloud service, maintaining a local build to try to match it's output is not a trade off that particularly makes sense for me. If it continues to cause me problems, I will have to replace it with my own continuous deployment pipeline, provisioning a mac on the cloud myself. Then I could probably replicate the build on my local machine easily enough that using it for dev would make sense. But as I say, I'm new to cordova development so perhaps this appraisal isn't representative of other developers experience.

I will try to make a local build on monday and get back to you with the project.properties file. Have a good weekend.

**Comment by christocracy** [comment]
You may not have a Mac for building with XCode, but you certainly *can* install the Android SDK and build Android locally and this is precisely where you're having an issue.

[Setup your local environment for building Android](https://cordova.apache.org/docs/en/latest/guide/platforms/android/)

**Comment by mushishi78** [comment]
Local build runs fine on my machine. Tempted to say that the problem is on PhoneGap Build's end and they need to update their Android SDK, or something. Feel free to close.

**Comment by christocracy** [comment]
Now post your `platforms/android/project.properties`

**Comment by mushishi78** [comment]
Sure thing:

```
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.gradle.include.1=phonegap-plugin-barcodescanner/myprojdebug-barcodescanner.gradle
cordova.system.library.2=com.squareup.okhttp3:okhttp:3+
cordova.gradle.include.2=cordova-plugin-crosswalk-webview/myprojdebug-xwalk.gradle
cordova.system.library.3=com.android.support:support-v4:24.1.1+
cordova.gradle.include.3=cordova-background-geolocation-lt/myprojdebug-build.gradle
```
