### ISSUE TITLE
'providerchange' event not triggered when location services is turned off (iOS)

### ISSUE THREAD

**Issue by DavidBriglio** [transistorsoft/cordova-background-geolocation-lt#564]
When location services is toggled on, the 'providerchange' event is fired, but not when it is toggled off. 

## Your Environment
* Plugin version: 2.9.1
* Platform: iOS
* OS version: 11.1.2
* Device manufacturer / model: iPhone 6
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.4

## Expected Behavior
'providerchange' event fired when location services is turned off.

## Actual Behavior
No event is fired, it will only be fired when you navigate to your app.

## Steps to Reproduce
1. Navigate to Settings>Privacy>Location Services
2. Toggle location services off

## Log Output (Coming back into the app)
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════
⚠️-[TSLocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=1 "(null)"
�-[TSLocationManager stopUpdatingLocation] 
⚠️-[TSGeofenceManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=1 "(null)"

**Comment by christocracy** [comment]
>When location services is toggled on, the 'providerchanged' event is fired

There's no such event as **`providerchanged`**.  It's [`providerchange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#providerchange)

**Comment by DavidBriglio** [comment]
My apologies, I just wrote it wrong. I have corrected the details, but the issue still stands.

**Comment by christocracy** [comment]
You're doing something wrong.  Show me your code.  `providerchange` certainly is **not** broken.

**Comment by DavidBriglio** [comment]
I don't think the code would be of benefit since the callback method is not invoked at all (from the background) until you bring the app back into the foreground:
```
static init() {
    MyClass.bgGeo = window.BackgroundGeolocation;
    MyClass.bgGeo.on('location', MyClass.onLocation, (error)=>{console.log(error);});
    MyClass.bgGeo.on('providerchange', MyClass.onProviderChange, (error) => {console.log(error);});
    
    let config = {
        desiredAccuracy: MyClass.bgGeo.DESIRED_ACCURACY_HIGH,
        distanceFilter: 15,
        startOnBoot: true,
        logLevel: MyClass.bgGeo.LOG_LEVEL_VERBOSE
    };
    
    MyClass.bgGeo.configure(config,
        (state) => {
            if(!state.enabled) {
                MyClass.bgGeo.start();
            }
        },
        (error) => {console.log(error);}
    );
}

static onProviderChange(provider) {
    MyClass.status = (provider.gps && provider.enabled);
}
```

**Comment by christocracy** [comment]
> since the callback method is not invoked at all (from the background) until you bring the app back into the foreground:

Correct.  It's completely up to iOS to awaken an app in the background.  It doesn't do so when you *disable* location-services.

Enabling location-services *will* cause iOS to awaken your app in the background.

**Comment by DavidBriglio** [comment]
Thank you, this is an iOS issue than, not an issue with the plugin.

**Comment by christocracy** [comment]
It's not an *issue*, this is *expected* behaviour.
