### ISSUE TITLE
Popup occurs when first app runs. 'License Validation Failure, BackgroundGeolocation is running in evaluation mode'

### ISSUE THREAD

**Issue by JoohyoungPark** [transistorsoft/cordova-background-geolocation-lt#565]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: 4.4.4
* Device manufacturer / model: Samsung / Galaxy Grand Max (SM-G720NO)
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config
```
    <plugin name="cordova-background-geolocation-lt" spec="git+https://github.com/transistorsoft/cordova-background-geolocation-lt.git">
        <variable name="LICENSE" value="my app license" />
        <variable name="GOOGLE_API_VERSION" value="11.6.0" />
        <variable name="APPCOMPAT_VERSION" value="26.1.0" />
        <variable name="BACKGROUND_MODE_LOCATION" value="<string>location</string>" />
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="[CHANGEME] Always use is required for constant background location-tracking" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="[CHANGEME] Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="[CHANGEME] Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>
```

## Expected Behavior
I buy the license and insert code in config.xml and package.json.
The license error popup does not appear.

## Actual Behavior
A license error popup appears.

![gps](https://user-images.githubusercontent.com/8871625/33836277-4d77a420-decc-11e7-9a95-338bb14acba0.jpg)

## Steps to Reproduce
1. run my gps-app.
2. then occurs

## Context

1. check license is right. but it is right value.
1. What the error message means?

## Debug logs

[logcat.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1548158/logcat.txt)

**Comment by christocracy** [comment]
Customers do not use the public repo `cordova-background-geolocation-lt`.  This public repo gets updates only every *few months*.

The private "customers only" repo gets latest updates.  Use the private repo.
