### ISSUE TITLE
device comptbale issue if app is terminated beckground geolocation not show mi and lenovo but afterterminated app loction show in moto mobile plesesolve my problem

### ISSUE THREAD

**Issue by AnkitaChoudharyGitHub** [transistorsoft/cordova-background-geolocation-lt#567]
## Your Environment
* Plugin version: 0.01
* Platform: iOS or Android
* OS version: androide version 5.1.1
* Device manufacturer / model:mi redmi 2 androide version 5.0
* Cordova version (`cordova -v`):7.1.0
* Cordova platform version (`cordova platform ls`):ionicv1
* Plugin config :  <plugin name="cordova-plugin-geolocation" spec="^2.4.3" />
    <plugin name="cordova.plugins.diagnostic" spec="^2.3.17" />

## Expected Behavior

background geolocation afterterminated app

## Actual Behavior

app is work but afterterminated app location show only moto g device not show all devices so solve my devicecomptable problem

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
## Your Environment
* Plugin version: 
* Platform: iOS or Android
* OS version:
* Plugin config

## Debug logs
