### ISSUE TITLE
Unable to change "Background location is not enabled" message

### ISSUE THREAD

**Issue by N0ps32** [transistorsoft/cordova-background-geolocation-lt#568]
## Your Environment
* Plugin version: 2.9.1
* Platform: iOS
* OS version: 11.2
* Device manufacturer / model: iPhone X
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.4
* Plugin config:
```
<plugin name="cordova-background-geolocation-lt" >
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="My custom translated message" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="My custom translated message" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="My custom translated message" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="My custom translated message" />
</plugin>
```
## Expected Behavior

"Background location is not enabled" popup should also be translated.

## Actual Behavior

"Background location is not enabled" popup is not translated and the hard-coded English message is shown. "To use background location, you must enable 'always'' in the Location Services settings"

## Context
People in my country only speak limited English, also it looks dumb to have 99% of your app translated except one popup.

**Comment by christocracy** [comment]
See [`locationAuthorizationAlert`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-object-locationauthorizationalert)

**Comment by shokry055** [comment]
bgGeo.configure({
      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Yo, location-services not enabled",
        titleWhenOff: "Yo, location-services OFF",
        instructions: "You must enable 'Always' in location-services, buddy",
        cancelButton: "Cancel",
        settingsButton: "Settings"
      }
    });

did not work for me !!
