### ISSUE TITLE
 Problems saving locations in sqlite

### ISSUE THREAD

**Issue by renanmoraes** [transistorsoft/cordova-background-geolocation-lt#569]
## My Environment
* Plugin version:
* Platform: Android
* OS version: 5.0
* Device manufacturer / model: ASUS ZENFONE 2
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0

## Expected Behavior
I need to disable location saving in sqlite due to an error when I finish a trip and need to clear it all. My phone hangs on this action making it impossible for me to finish this trip.

## Actual Behavior

The current behavior is that when I end my trip it is crashing preventing it from proceeding with the flow
The code below is what is running with the activity and the problem happens in the function  this.finisGeolocationPlugin();

```   
finishTripPassOne(){
      this.loopActive = false;
       this.state.isMoving = false;
       this.trip.finishAt = new Date();
       this.trip.conclusion = {
       success: true,
       description: 'Sim, foi concluído'
     };
     this.tripService
       .updateTrip(this.trip._id, this.trip)
       .subscribe(res => {
         this.finisGeolocationPlugin();
         this.navCtrl.popToRoot();
       });
   }

  finisGeolocationPlugin() {
    this.isMoving = false;
    this.bgGeo.stop((state) => {
    });
    this.ioDisconnectDevice();
    this.resetMarkers();
    this.destroyLocations();
    this.map.remove();
    this.onStop();
  }
```

Being more specific I think the problem is in this.destroyLocations (); because when there are several locations that the problem happens. A possivel solution for my problem is not to save these items in sqlite, so I need to know how to do this?

How can I not save the locations, and what can this cause in the plugin, does any function need them?

**Comment by christocracy** [comment]
Observe the plugin logs while you perform this action:
```
$ adb logcat -s TSLocationManager
```

**Comment by renanmoraes** [comment]
I'm doing tests on a real device how to check the running log?

**Comment by christocracy** [comment]
- plug device into USB

```
$ adb logcat
```

**Comment by christocracy** [comment]
If you've never used [`adb`](https://developer.android.com/studio/command-line/adb.html) before, stop whatever you're doing and learn about it.

**Comment by renanmoraes** [comment]
kkkkkkkkkkkk could you send me study material?

**Comment by christocracy** [comment]
Step 1:  [Enable USB Debugging on your device](https://www.youtube.com/watch?v=Ucs34BkfPB0)
Step 2: In console:
```
$ adb logcat
```

**Comment by renanmoraes** [comment]
As soon as I pass the lunch hour I give you an opinion.

**Comment by christocracy** [comment]
The plugin is *very* verbose with logging.   It's probably trying to tell you something.  You need to *listen* to it.
![](https://dl.dropboxusercontent.com/s/uqwzmj7grgqle0o/Screenshot%202017-12-18%2009.31.52.png?dl=1)

**Comment by renanmoraes** [comment]
How do you disable the saving of locations in sqlite automatically?

Because I visualized the logs and nothing strange happened, no mistake or anything.

**Comment by christocracy** [comment]
Show me your logs, particularly where the plugin is "hanging".  I really doubt there's an issue with the plugin here.

Are you observing the Javascript console when this "hanging" occurs, that you don't have a Javascript error?

**Comment by christocracy** [comment]
Explanation please.

**Comment by renanmoraes** [comment]
In fact I gave up what needed to be done, and I do not remember what the solution was. So he decides to close the topic since it would not be able to continue and would not be useful for a child
