### ISSUE TITLE
Problem when deploying in Production iOS/Android

### ISSUE THREAD

**Issue by adsonvinicius** [transistorsoft/cordova-background-geolocation-lt#572]
Hi, I created an Ionic app, basically a copy of the Simple-Map demo project, without the map stuff. It works fine in Android / iOS if in debug mode, but not in --prod on real devices (Having a license). There are any configuration for production mode?

In Xcode Simulator (Freeway drive) or Android Emulator (Using Lockito + Setting pace to true manually) it works fine building as --prod

Versions:

"cordova-android": "^6.3.0",
"cordova-background-geolocation-lt": "^2.9.1",
"cordova-ios": "^4.4.0",

## Here is the main page (routed by an ion-tabs component)

**Home.ts**

import { Component, NgZone } from '@angular/core';
import { Platform, NavController, NavParams } from 'ionic-angular';
import { AngularFireAuth } from 'angularfire2/auth';
import { Device } from '@ionic-native/device';
 
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

export class HomePage  { 

  // BackgroundGeolocation API
  bgGeo: any;

  // Background Geolocation State
  state: any;
  enabled: boolean;  
  isMoving: boolean;
  distanceFilter: number;
  stopTimeout: number;
  autoSync: boolean;
  stopOnTerminate: boolean;
  startOnBoot: boolean;
  debug: boolean;
  provider: any;

  // UI State
  menuActive: boolean;
  motionActivity: string;
  odometer: string;
  
  //App variables
  deviceID: any; 
  dSpeed: number;
  dimension: number;
  afToken: any;

  constructor(
    private platform: Platform,
    //private bgService:BGService,
    public navCtrl: NavController,
    public navParams: NavParams,
    private zone:NgZone,
    private device:Device,
    private afAuth: AngularFireAuth) {

    this.platform.ready().then(this.onDeviceReady.bind(this));

    this.state = {};
    // BackgroundGeolocation initial config.
    this.isMoving = false;
    this.enabled = false;
    this.autoSync = true;
    this.distanceFilter = 10;
    this.stopTimeout = 1;
    this.stopOnTerminate = false;
    this.startOnBoot = true;
    this.debug = false;

    // UI members.
    this.motionActivity = 'Activity';
    this.menuActive = false;

    this.dSpeed = 0;
    this.dimension = this.getGaugeDimension();
  }

  ionViewDidLoad() {}

  onDeviceReady() {
    this.configureBackgroundGeolocation();
    this.renewAuthenticationFirebase();
  }

  configureBackgroundGeolocation() {
    
    this.deviceID = this.device.uuid;
    this.bgGeo = (<any>window).BackgroundGeolocation;

    // Listen to events
    this.onLocation = this.onLocation.bind(this);
    this.onLocationError = this.onLocationError.bind(this);
    this.onHttpSuccess = this.onHttpSuccess.bind(this);
    this.onHttpFailure = this.onHttpFailure.bind(this);

    this.bgGeo.on('location', this.onLocation, this.onLocationError);
    this.bgGeo.on('http', this.onHttpSuccess, this.onHttpFailure);
    
    this.bgGeo.getState((state) => {
      this.state = state;

      if (!this.isFirstBoot()) {
        // Set current plugin state upon our view.
        this.enabled         = state.enabled;
        this.isMoving        = state.isMoving;
        this.autoSync        = state.autoSync;
        this.distanceFilter  = state.distanceFilter;
        this.stopTimeout     = state.stopTimeout;
        this.stopOnTerminate = state.stopOnTerminate;
        this.startOnBoot     = state.startOnBoot;
        this.debug           = state.debug;
      }

      this.bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,  // <-- highest possible accuracy
        distanceFilter: this.distanceFilter,
        // ActivityRecognition config
        stopTimeout: this.stopTimeout,
        locationAuthorizationRequest : 'Always',
        // Application config
        foregroundService: true,
        stopOnTerminate: this.stopOnTerminate,
        heartbeatInterval: 60,
        // HTTP / Persistence config
        method : 'POST',
        httpRootProperty : '.',
        autoSync: this.autoSync,
        autoSyncThreshold: 0,
        params : { deviceID : this.device.uuid },
        locationTemplate : '{"latitude" : <%= latitude %>, "longitude" : <%= longitude %>, "speed" : <%= speed %>, "timestamp" : "<%= timestamp %>"}',
        // Logging / Debug config
        debug: this.debug,
        logLevel: this.bgGeo.LOG_LEVEL_VERBOSE
      }, (state) => {
        console.log('- Configure success: ', state);        
      });      
    });  
  }

  onToggleEnabled() {
    console.log('- enabled: ', this.enabled);

    if (this.enabled) {
      this.bgGeo.start((state) => {
        console.log('- Start success: ', state);        
      });
    } else {
      this.isMoving = false;
      this.bgGeo.stop((state) => {
        console.log('- Stop success: ', state);        
      });
    }    
  }

  onLocation(location:any, taskId:any) {
    if (!location.sample) {
        this.zone.run(() => {
          this.dSpeed = this.convertToKMh(location.coords.speed);
        });
    }else{
      console.log('Sample: ', JSON.stringify(location));
    }
  }

  onLocationError(error:any) {
    console.warn('[js] Location error: ', error);
  }
  
  onMotionChange(isMoving, location) {
    console.log('[event] motionchange, isMoving: ', isMoving, location);
    this.zone.run(() => {
      this.isMoving = isMoving;
    });
  }

  onHttpSuccess(response) {
    console.log('[event] http: ', response);
  }

  onHttpFailure(response) {
    console.log('[js] http failure: ', JSON.stringify(response));
    if(response.status == 401)
      this.renewAuthenticationFirebase();
  }

  private isFirstBoot() {
    let localStorage = (<any>window).localStorage;
    let isFirstBoot = true;
    if (localStorage.getItem('device.uuid')) {
      isFirstBoot = false;
    } else {
      localStorage.setItem('device.uuid', this.device.uuid);
    }
    return isFirstBoot;
  }

  private renewAuthenticationFirebase(){
    this.afAuth.auth.signInAnonymously().then((user) => {
       this.afAuth.auth.currentUser.getIdToken(true)
          .then((idToken) => {
            this.afToken = idToken;
            this.bgGeo.setConfig({
              url : 'https://myproject.firebaseio.com/.json?auth=' + this.afToken         
            });
          })
     }).catch(function(error) {
        console.log(error);
    });
  }

  private convertToKMh(velocidade: any): number {    
    if(velocidade != null && velocidade > 0)
      return (velocidade * 3.6);
    else
      return 0;
  }

  private getGaugeDimension(){
    var dim = this.platform.width() > this.platform.height() ? this.platform.height() : this.platform.width();
    var ratio = dim *  0.2;
    return dim < 400 ? Math.round(dim - ratio) : Math.round(400 - ratio);
  }
}

**Comment by christocracy** [comment]
What are the symptoms?

**Comment by adsonvinicius** [comment]
The locations are not gathered from device even in foreground on production mode.  On this part:

_this.dSpeed = this.convertToKMh(location.coords.speed);_

And this variable has no value changed. I tried this morning driving in streets. I will create a new page just to see the logs on real device.

**Comment by christocracy** [comment]
Are you observing the plugin logs?  Paste them here.

See Wiki for “Debugging”

**Comment by adsonvinicius** [comment]
Hi, here is the logs from android (Driving with a laptop plugged)

I/TSLocationManager(19031): [c.t.l.util.Sensors print] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ DEVICE SENSORS
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): ╟─ ✅  ACCELEROMETER: {Sensor name="K2HH Accelerometer Sensor", vendor="STM", version=1, type=1, maxRange=19.6133, resolution=0.038307227, power=0.13, minDelay=10000}
I/TSLocationManager(19031): ╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
I/TSLocationManager(19031): ╟─ ⚠️  MAGNETOMETER:  none.  Motion-detection system performance will be degraded
I/TSLocationManager(19031): ╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
I/TSLocationManager(19031): ╚═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BackgroundGeolocation adapter
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
D/TSLocationManager(19031): [c.t.l.d.s.SQLiteLocationDAO dbh] 
D/TSLocationManager(19031):   ✅  Opened database
D/TSLocationManager(19031): [c.t.l.d.s.SQLiteLocationDAO prune] 
D/TSLocationManager(19031):   ℹ️  PRUNE -1 days
D/TSLocationManager(19031): [c.t.l.data.sqlite.GeofenceDAO dbh] 
D/TSLocationManager(19031):   ✅  Opened database
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(19031):   ??????  Connecting to GooglePlayServices...
D/TSLocationManager(19031): $ addLocationListener()
D/TSLocationManager(19031): $ addHttpListener()
D/TSLocationManager(19031): $ getState()
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation onConnected] 
I/TSLocationManager(19031):   ✅  Google Play Services: connected (version code:11910000)
D/TSLocationManager(19031): $ configure()
I/TSLocationManager(19031): [c.t.l.settings.Settings print] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BackgroundGeolocation Settings
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): {
I/TSLocationManager(19031):   "headers": {},
I/TSLocationManager(19031):   "deferTime": 0,
I/TSLocationManager(19031):   "httpTimeout": 60000,
I/TSLocationManager(19031):   "fastestLocationUpdateInterval": 10000,
I/TSLocationManager(19031):   "notificationPriority": 0,
I/TSLocationManager(19031):   "notificationSmallIcon": "",
I/TSLocationManager(19031):   "desiredOdometerAccuracy": 100,
I/TSLocationManager(19031):   "persist": true,
I/TSLocationManager(19031):   "logMaxDays": 3,
I/TSLocationManager(19031):   "desiredAccuracy": 0,
I/TSLocationManager(19031):   "notificationLargeIcon": "",
I/TSLocationManager(19031):   "geofenceProximityRadius": 1000,
I/TSLocationManager(19031):   "geofenceInitialTriggerEntry": true,
I/TSLocationManager(19031):   "stationaryRadius": 25,
I/TSLocationManager(19031):   "batchSync": false,
I/TSLocationManager(19031):   "minimumActivityRecognitionConfidence": 75,
I/TSLocationManager(19031):   "stopOnStationary": false,
I/TSLocationManager(19031):   "logLevel": 5,
I/TSLocationManager(19031):   "maxDaysToPersist": 1,
I/TSLocationManager(19031):   "elasticityMultiplier": 1,
I/TSLocationManager(19031):   "forceReloadOnLocationChange": false,
I/TSLocationManager(19031):   "forceReloadOnHeartbeat": false,
I/TSLocationManager(19031):   "forceReloadOnBoot": false,
I/TSLocationManager(19031):   "configureUrl": "",
I/TSLocationManager(19031):   "enabled": true,
I/TSLocationManager(19031):   "forceReloadOnGeofence": false,
I/TSLocationManager(19031):   "locationTemplate": "{\"latitude\" : <%= latitude %>, \"longitude\" : <%= longitude %>, \"speed\" : <%= speed %>, \"timestamp\" : \"<%= timestamp %>\"}",
I/TSLocationManager(19031):   "forceReloadOnSchedule": false,
I/TSLocationManager(19031):   "autoSync": true,
I/TSLocationManager(19031):   "odometer": 0,
I/TSLocationManager(19031):   "httpRootProperty": ".",
I/TSLocationManager(19031):   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
I/TSLocationManager(19031):   "url": "",
I/TSLocationManager(19031):   "extras": {},
I/TSLocationManager(19031):   "locationsOrderDirection": "ASC",
I/TSLocationManager(19031):   "geofenceTemplate": "",
I/TSLocationManager(19031):   "notificationIcon": "",
I/TSLocationManager(19031):   "schedulerEnabled": false,
I/TSLocationManager(19031):   "configureInterval": -1,
I/TSLocationManager(19031):   "locationTimeout": 60,
I/TSLocationManager(19031):   "activityRecognitionInterval": 10000,
I/TSLocationManager(19031):   "notificationTitle": "",
I/TSLocationManager(19031):   "disableElasticity": false,
I/TSLocationManager(19031):   "debug": false,
I/TSLocationManager(19031):   "trackingMode": "location",
I/TSLocationManager(19031):   "stopTimeout": 1,
I/TSLocationManager(19031):   "maxBatchSize": -1,
I/TSLocationManager(19031):   "heartbeatInterval": 60,
I/TSLocationManager(19031):   "locationUpdateInterval": 1000,
I/TSLocationManager(19031):   "disableStopDetection": false,
I/TSLocationManager(19031):   "maxRecordsToPersist": -1,
I/TSLocationManager(19031):   "startOnBoot": false,
I/TSLocationManager(19031):   "forceReloadOnMotionChange": false,
I/TSLocationManager(19031):   "notificationText": "Location Service activated",
I/TSLocationManager(19031):   "stopOnTerminate": false,
I/TSLocationManager(19031):   "autoSyncThreshold": 0,
I/TSLocationManager(19031):   "isMoving": false,
I/TSLocationManager(19031):   "params": {
I/TSLocationManager(19031):     "deviceID": "a1b0b89b9bd20cfa"
I/TSLocationManager(19031):   },
I/TSLocationManager(19031):   "notificationColor": "",
I/TSLocationManager(19031):   "schedule": [],
I/TSLocationManager(19031):   "foregroundService": true,
I/TSLocationManager(19031):   "stopAfterElapsedMinutes": 0,
I/TSLocationManager(19031):   "method": "POST",
I/TSLocationManager(19031):   "distanceFilter": 10
I/TSLocationManager(19031): }╚═════════════════════════════════════════════
I/TSLocationManager(19031): - Enable: true → true, trackingMode: location
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onStartCommand] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BackgroundGeolocation Service started
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService c] 
I/TSLocationManager(19031):   ✅  Started in foreground
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation requestActivityUpdates] 
I/TSLocationManager(19031):   ??????  Start activity updates: 10000
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  setPace: null → false
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  Start heartbeat (60)
I/TSLocationManager(19031): - onResume
D/TSLocationManager(19031): $ stop()
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onDestroy] 
D/TSLocationManager(19031): ╔═════════════════════════════════════════════
D/TSLocationManager(19031): ║ BackgroundGeolocationService destroyed
D/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation removeActivityUpdates] 
I/TSLocationManager(19031):   ??????  Stop activity updates
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
D/TSLocationManager(19031): $ start()
I/TSLocationManager(19031): - Enable: false → true, trackingMode: location
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onStartCommand] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BackgroundGeolocation Service started
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService c] 
I/TSLocationManager(19031):   ✅  Started in foreground
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation requestActivityUpdates] 
I/TSLocationManager(19031):   ??????  Start activity updates: 10000
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  setPace: null → false
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  Start heartbeat (60)
I/TSLocationManager(19031): [c.t.l.BootReceiver onReceive] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BootReceiver: br.com.cityspeed
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): ╟─ android.intent.action.MY_PACKAGE_REPLACED
D/TSLocationManager(19031): $ stop()
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onDestroy] 
D/TSLocationManager(19031): ╔═════════════════════════════════════════════
D/TSLocationManager(19031): ║ BackgroundGeolocationService destroyed
D/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation removeActivityUpdates] 
I/TSLocationManager(19031):   ??????  Stop activity updates
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
D/TSLocationManager(19031): $ start()
I/TSLocationManager(19031): - Enable: false → true, trackingMode: location
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onStartCommand] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BackgroundGeolocation Service started
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService c] 
I/TSLocationManager(19031):   ✅  Started in foreground
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation requestActivityUpdates] 
I/TSLocationManager(19031):   ??????  Start activity updates: 10000
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  setPace: null → false
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  Start heartbeat (60)
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (48%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] 
I/TSLocationManager(19031):   ⚠️  Triggered moving due to insufficient device capabilities.
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  setPace: false → true
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (85%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (67%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
D/TSLocationManager(19031): $ stop()
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onDestroy] 
D/TSLocationManager(19031): ╔═════════════════════════════════════════════
D/TSLocationManager(19031): ║ BackgroundGeolocationService destroyed
D/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation removeActivityUpdates] 
I/TSLocationManager(19031):   ??????  Stop activity updates
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
D/TSLocationManager(19031): $ start()
I/TSLocationManager(19031): - Enable: false → true, trackingMode: location
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onStartCommand] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BackgroundGeolocation Service started
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService c] 
I/TSLocationManager(19031):   ✅  Started in foreground
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation requestActivityUpdates] 
I/TSLocationManager(19031):   ??????  Start activity updates: 10000
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  setPace: null → false
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  Start heartbeat (60)
I/TSLocationManager(19031): - onPause
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] on_bicycle (39%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] 
I/TSLocationManager(19031):   ⚠️  Triggered moving due to insufficient device capabilities.
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService a] 
I/TSLocationManager(19031):   ??????  setPace: false → true
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService j] 
I/TSLocationManager(19031):   ??????  Stop heartbeat
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] on_bicycle (98%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
I/TSLocationManager(19031): - onResume
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (38%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
I/TSLocationManager(19031): - onPause
I/TSLocationManager(19031): CDVBackgroundGeolocation#onDestoy
I/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation onActivityDestroy] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ MainActivity was destroyed
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): ╟─ stopOnTerminate: false
I/TSLocationManager(19031): ╟─ enabled: true
I/TSLocationManager(19031): [c.t.l.l.TSLocationManager stopWatchPosition] 
I/TSLocationManager(19031):   ??????  watchPosition: OFF
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation e] 
D/TSLocationManager(19031):   ??????  Cleared callbacks
D/TSLocationManager(19031): $ addLocationListener()
D/TSLocationManager(19031): $ addHttpListener()
D/TSLocationManager(19031): $ getState()
D/TSLocationManager(19031): $ configure()
I/TSLocationManager(19031): [c.t.l.settings.Settings print] 
I/TSLocationManager(19031): ╔═════════════════════════════════════════════
I/TSLocationManager(19031): ║ BackgroundGeolocation Settings
I/TSLocationManager(19031): ╠═════════════════════════════════════════════
I/TSLocationManager(19031): {
I/TSLocationManager(19031):   "headers": {},
I/TSLocationManager(19031):   "deferTime": 0,
I/TSLocationManager(19031):   "httpTimeout": 60000,
I/TSLocationManager(19031):   "fastestLocationUpdateInterval": 10000,
I/TSLocationManager(19031):   "notificationPriority": 0,
I/TSLocationManager(19031):   "notificationSmallIcon": "",
I/TSLocationManager(19031):   "desiredOdometerAccuracy": 100,
I/TSLocationManager(19031):   "persist": true,
I/TSLocationManager(19031):   "logMaxDays": 3,
I/TSLocationManager(19031):   "desiredAccuracy": 0,
I/TSLocationManager(19031):   "notificationLargeIcon": "",
I/TSLocationManager(19031):   "geofenceProximityRadius": 1000,
I/TSLocationManager(19031):   "geofenceInitialTriggerEntry": true,
I/TSLocationManager(19031):   "stationaryRadius": 25,
I/TSLocationManager(19031):   "batchSync": false,
I/TSLocationManager(19031):   "minimumActivityRecognitionConfidence": 75,
I/TSLocationManager(19031):   "stopOnStationary": false,
I/TSLocationManager(19031):   "logLevel": 5,
I/TSLocationManager(19031):   "maxDaysToPersist": 1,
I/TSLocationManager(19031):   "elasticityMultiplier": 1,
I/TSLocationManager(19031):   "forceReloadOnLocationChange": false,
I/TSLocationManager(19031):   "forceReloadOnHeartbeat": false,
I/TSLocationManager(19031):   "forceReloadOnBoot": false,
I/TSLocationManager(19031):   "configureUrl": "",
I/TSLocationManager(19031):   "enabled": true,
I/TSLocationManager(19031):   "forceReloadOnGeofence": false,
I/TSLocationManager(19031):   "locationTemplate": "{\"latitude\" : <%= latitude %>, \"longitude\" : <%= longitude %>, \"speed\" : <%= speed %>, \"timestamp\" : \"<%= timestamp %>\"}",
I/TSLocationManager(19031):   "forceReloadOnSchedule": false,
I/TSLocationManager(19031):   "autoSync": true,
I/TSLocationManager(19031):   "odometer": 0,
I/TSLocationManager(19031):   "httpRootProperty": ".",
I/TSLocationManager(19031):   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
I/TSLocationManager(19031):   "url": "",
I/TSLocationManager(19031):   "extras": {},
I/TSLocationManager(19031):   "locationsOrderDirection": "ASC",
I/TSLocationManager(19031):   "geofenceTemplate": "",
I/TSLocationManager(19031):   "notificationIcon": "",
I/TSLocationManager(19031):   "schedulerEnabled": false,
I/TSLocationManager(19031):   "configureInterval": -1,
I/TSLocationManager(19031):   "locationTimeout": 60,
I/TSLocationManager(19031):   "activityRecognitionInterval": 10000,
I/TSLocationManager(19031):   "notificationTitle": "",
I/TSLocationManager(19031):   "disableElasticity": false,
I/TSLocationManager(19031):   "debug": false,
I/TSLocationManager(19031):   "trackingMode": "location",
I/TSLocationManager(19031):   "stopTimeout": 1,
I/TSLocationManager(19031):   "maxBatchSize": -1,
I/TSLocationManager(19031):   "heartbeatInterval": 60,
I/TSLocationManager(19031):   "locationUpdateInterval": 1000,
I/TSLocationManager(19031):   "disableStopDetection": false,
I/TSLocationManager(19031):   "maxRecordsToPersist": -1,
I/TSLocationManager(19031):   "startOnBoot": false,
I/TSLocationManager(19031):   "forceReloadOnMotionChange": false,
I/TSLocationManager(19031):   "notificationText": "Location Service activated",
I/TSLocationManager(19031):   "stopOnTerminate": false,
I/TSLocationManager(19031):   "autoSyncThreshold": 0,
I/TSLocationManager(19031):   "isMoving": true,
I/TSLocationManager(19031):   "params": {
I/TSLocationManager(19031):     "deviceID": "a1b0b89b9bd20cfa"
I/TSLocationManager(19031):   },
I/TSLocationManager(19031):   "notificationColor": "",
I/TSLocationManager(19031):   "schedule": [],
I/TSLocationManager(19031):   "foregroundService": true,
I/TSLocationManager(19031):   "stopAfterElapsedMinutes": 0,
I/TSLocationManager(19031):   "method": "POST",
I/TSLocationManager(19031):   "distanceFilter": 10
I/TSLocationManager(19031): }╚═════════════════════════════════════════════
I/TSLocationManager(19031): - Enable: true → true, trackingMode: location
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (37%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (75%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (42%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] 
I/TSLocationManager(19031):   ??????  Stop-timeout timer initiated (1 min)...
I/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService g] 
I/TSLocationManager(19031):   ??????  Begin stop timer
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (28%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService h] 
D/TSLocationManager(19031): [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (67%)
D/TSLocationManager(19031): [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES

**Comment by christocracy** [comment]
I see nothing in unusual in your logs but you haven't post much logs.  The plugin will hold 3 days of logs (by default).  You can fetch them with `#getLog` method.

**Comment by christocracy** [comment]
Closed for failing to provide plugin logs.
