### ISSUE TITLE
Can't find tests anywhere

### ISSUE THREAD

**Issue by bf4** [transistorsoft/cordova-background-geolocation-lt#573]
I was looking for tests to see examples of some of the raw data I can expect, and haven't found any, yet.  Are there tests in one of the dependencies and I just haven't found them yet?

## Expected Behavior

Behavior should be verified somehow against regression

## Actual Behavior

Haven't found a place where behavior is tested, if at all.

**Comment by christocracy** [comment]
All the testing occurs within a private repo hosting the core libraries, which are common to all projects using the library (ie: native, cordova, react-native and nativescript).  There are no public tests exposed unfortunately.

**Comment by christocracy** [comment]
(sorry so late, was away for xmas vacation)

**Comment by bf4** [comment]
@christocracy Thanks for getting back

> I was looking for tests to see examples of some of the raw data I can expect, and haven't found any, yet.

Any chance you can include some example data?  I saw one of your files referenced a data csv which was not in the repo.

> All the testing occurs within a private repo

Any way any tests can be made public?  Or least have the test result published somewhere?

**Comment by bf4** [comment]
Oh well
