### ISSUE TITLE
Http service plugin's send only the first location toward back-office when tracking started

### ISSUE THREAD

**Issue by Raffaele-LIZE** [transistorsoft/cordova-background-geolocation-lt#576]
Hello, i need help for understand the right way to use Http service.

I think make a mistake from configuration or the link between plugin and SQLite...

## Your Environment
* Plugin version: ~2.8.5
* Platform: iOS
* OS version: 11.2.1
* Device manufacturer / model: iPhone 5S
* Cordova version (`cordova -v`): 8.0.0
* Ionic version: 3.19.0
* Cordova platform version (`cordova platform ls`):
```
Installed platforms:
  android 6.3.0
  ios 4.5.3
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```

* Plugin config

```
// BackgroundGeoLocation is highly configurable.
			this.bgGeo.configure({
				desiredAccuracy             : 0,
				distanceFilter              : 10, // old value 100
				disableElasticity           : false,
				// iOS config only
				stationaryRadius            : 25, // old value 100
				locationAuthorizationRequest: 'Always',
				// Android config only
				locationUpdateInterval      : 1000, // old value 6000
				// Activity Recognition config
				activityRecognitionInterval : 600000, // 10 minutes 
				stopTimeout                 : 5,
				// Application config
				debug                       : true,  // <-- Debug sounds & notifications.
				stopOnTerminate             : false,
				startOnBoot                 : false,
				// HTTP auto request
				// url                         : 'XXX/locations',
				// method                      : 'POST',
				// autoSync                    : true,
				// httpRootProperty            : '.',
				params : {
					id_user: 'id_user',
					time: 'test time'
				}
			}, (state) => {
				// 4. Start the plugin.
				// this.bgGeo.start();
			});
```

## Expected Behavior
Should happen detect new locations when http config option are uncomment and send it to back office.

## Actual Behavior
When http config option are uncomment, the plugin detect and send only the first location, it no detected another location et send nothing. It never enter 'http' event for test requests.

## Steps to Reproduce
1. Set my config
2. Start the tracking
3. Go for a jaunt ^^

## Context
I try to track my trips

**Comment by christocracy** [comment]
The plugin is very verbose with logging.  It saves 3 days of logs (by default) in its database.  The answer is always in the logs.  See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging) wiki.

**Comment by Raffaele-LIZE** [comment]
Ok i will see thanks christocracy
