### ISSUE TITLE
Android App Cannot read property 'bgGeo' of null

### ISSUE THREAD

**Issue by RonaldVanAken** [transistorsoft/cordova-background-geolocation-lt#577]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: 7.0 Android
* Device manufacturer / model: Samsung s7
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):android 6.3.0
* Plugin configcod

## Expected Behavior

I am not seeing any of the callbacks being activated and see the following error:

[16:16:24]  console.log: bgGeo =         {"LOG_LEVEL_OFF":0,"LOG_LEVEL_ERROR":1,"LOG_LEVEL_WARNING":2,"LOG_LEVEL_INFO":3,"LOG_LEVEL_DEBUG":4,"LOG_LEVEL_VERBOSE":5,"DESIRED_ACCURACY_HIGH":0,"DESIRED_ACCURACY_MEDIUM":10,"DESIRED_ACCURACY_LOW":100,"DESIRED_ACCURACY_VERY_LOW":1000,"AUTHORIZATION_STATUS_NOT_DETERMINED":0,"AUTHORIZATION_STATUS_RESTRICTED":1,"AUTHORIZATION_STATUS_DENIED":2,"AUTHORIZATION_STATUS_ALWAYS":3,"AUTHORIZATION_STATUS_WHEN_IN_USE":4,"NOTIFICATION_PRIORITY_DEFAULT":0,"NOTIFICATION_PRIORITY_HIGH":1,"NOTIFICATION_PRIORITY_LOW":-1,"NOTIFICATION_PRIORITY_MAX":2,"NOTIFICATION_PRIORITY_MIN":-2,"stationaryLocation":null,"config":{},"cordovaCallbacks":[],"logger":{}}
[16:16:24]  console.log: BackgroundGeolocation is configured and ready to use
**[16:16:24]  console.log: Error in Success callbackId: BackgroundGeolocation771970977 : TypeError: Cannot read property**

Currently just testing the plugin and using the following initialization code:

constructor(private events: Events, private platform: Platform) {
        platform.ready().then(
          this.configureBackgroundGeolocation();

             // this statement does not work
            //this.configureBackgroundGeolocation.bind(this)

        );

    }

    configureBackgroundGeolocation() {
        // 1. Get a reference to the plugin
            this.bgGeo = (<any>window).BackgroundGeolocation;

        // 2. Listen to events
       this.bgGeo.on('location', this.onLocation.bind(this));
        this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
        this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
        this.bgGeo.on('geofence', this.onGeofence.bind(this));
        this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));

       // this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));
    
        // 3. Configure it.
        this.bgGeo.configure({
            debug: true,

            desiredAccuracy: 1,   // <-- Config params
            distanceFilter: 1
          }, function(state) {    // <-- Current state provided to #configure callback
            // 3.  Start tracking
            console.log('BackgroundGeolocation is configured and ready to use');
            if (!state.enabled) {
              this.bgGeo.start(function() {
                console.log('- BackgroundGeolocation tracking started');
              });
            }
        });
    }

    onLocation(location, taskId) {
        console.log('- location: ', location);
        this.bgGeo.finish(taskId);
      }
      onMotionChange(isMoving, location, taskId) {
        console.log('- motionchange: ', isMoving, location);
        this.bgGeo.finish(taskId);
      }
      onActivityChange(activity) {
        console.log('- activitychange: ', activity);
      }
      onGeofence(params, taskId) {
        console.log('- geofence: ', params);
        this.bgGeo.finish(taskId);
      }

      onHttpSuccess(response) {
        console.log('- http success: ', response);
      }
      onHttpFailure(response) {
        console.log('- http failure: ', response);
      }

**Comment by RonaldVanAken** [comment]
Been puzzling on this and looking at the error message its trying to reach a callback which i do not register but is mandatory. Appreciate your help on this!

**Comment by christocracy** [comment]
It means the plugin is not installed or you’re attempting to access the plugin before Cordova deviceready event has fired.

Remove / re-install the plugin.

**Comment by RonaldVanAken** [comment]
Hi Chris,

Thanks for the response. I removed and added the plugin through the following commands:
ionic cordova plugin remove cordova-background-geolocation-lt
ionic cordova plugin add cordova-background-geolocation-lt

However when i deploy the app i still see the same error. Though it looks like the plugin is initialized.

12-30 14:13:26.002 8825-9066/com.toqey I/TSLocationManager: ╔═════════════════════════════════════════════
                                                            ║ License Validation Failure
                                                            ╠═════════════════════════════════════════════
                                                            ╟─ BackgroundGeolocation is running in evaluation mode.
12-30 14:13:26.114 8825-9066/com.toqey I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                            ╔═════════════════════════════════════════════
                                                            ║ BackgroundGeolocation adapter
                                                            ╠═════════════════════════════════════════════
12-30 14:13:26.154 8825-9066/com.toqey I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                              ✅  Google Play Services: connected (version code:11910000)
12-30 14:13:26.337 8825-9066/com.toqey I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                              🔵  Connecting to GooglePlayServices...
12-30 14:13:26.374 8825-8825/com.toqey D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 1137 : bgGeo = {"LOG_LEVEL_OFF":0,"LOG_LEVEL_ERROR":1,"LOG_LEVEL_WARNING":2,"LOG_LEVEL_INFO":3,"LOG_LEVEL_DEBUG":4,"LOG_LEVEL_VERBOSE":5,"DESIRED_ACCURACY_HIGH":0,"DESIRED_ACCURACY_MEDIUM":10,"DESIRED_ACCURACY_LOW":100,"DESIRED_ACCURACY_VERY_LOW":1000,"AUTHORIZATION_STATUS_NOT_DETERMINED":0,"AUTHORIZATION_STATUS_RESTRICTED":1,"AUTHORIZATION_STATUS_DENIED":2,"AUTHORIZATION_STATUS_ALWAYS":3,"AUTHORIZATION_STATUS_WHEN_IN_USE":4,"NOTIFICATION_PRIORITY_DEFAULT":0,"NOTIFICATION_PRIORITY_HIGH":1,"NOTIFICATION_PRIORITY_LOW":-1,"NOTIFICATION_PRIORITY_MAX":2,"NOTIFICATION_PRIORITY_MIN":-2,"stationaryLocation":null,"config":{},"cordovaCallbacks":[{"callbackId":"BackgroundGeolocation1957541470"},{"callbackId":"BackgroundGeolocation1957541471"},{"callbackId":"BackgroundGeolocation1957541472"},{"callbackId":"BackgroundGeolocation1957541473"},{"callbackId":"BackgroundGeolocation1957541474"}],"logger":{}}
12-30 14:13:26.374 8825-8825/com.toqey I/chromium: [INFO:CONSOLE(1137)] "bgGeo = {"LOG_LEVEL_OFF":0,"LOG_LEVEL_ERROR":1,"LOG_LEVEL_WARNING":2,"LOG_LEVEL_INFO":3,"LOG_LEVEL_DEBUG":4,"LOG_LEVEL_VERBOSE":5,"DESIRED_ACCURACY_HIGH":0,"DESIRED_ACCURACY_MEDIUM":10,"DESIRED_ACCURACY_LOW":100,"DESIRED_ACCURACY_VERY_LOW":1000,"AUTHORIZATION_STATUS_NOT_DETERMINED":0,"AUTHORIZATION_STATUS_RESTRICTED":1,"AUTHORIZATION_STATUS_DENIED":2,"AUTHORIZATION_STATUS_ALWAYS":3,"AUTHORIZATION_STATUS_WHEN_IN_USE":4,"NOTIFICATION_PRIORITY_DEFAULT":0,"NOTIFICATION_PRIORITY_HIGH":1,"NOTIFICATION_PRIORITY_LOW":-1,"NOTIFICATION_PRIORITY_MAX":2,"NOTIFICATION_PRIORITY_MIN":-2,"stationaryLocation":null,"config":{},"cordovaCallbacks":[{"callbackId":"BackgroundGeolocation1957541470"},{"callbackId":"BackgroundGeolocation1957541471"},{"callbackId":"BackgroundGeolocation1957541472"},{"callbackId":"BackgroundGeolocation1957541473"},{"callbackId":"BackgroundGeolocation1957541474"}],"logger":{}}", source: file:///android_asset/www/build/main.js (1137)
12-30 14:13:26.391 8825-9066/com.toqey W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.configure blocked the main thread for 17ms. Plugin should use CordovaInterface.getThreadPool().
12-30 14:13:26.402 8825-9524/com.toqey I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                            ╔═════════════════════════════════════════════
                                                            ║ BackgroundGeolocation Settings
                                                            ╠═════════════════════════════════════════════
                                                            {
                                                              "isMoving": false,
                                                              "enabled": false,
                                                              "odometer": 0,
                                                              "schedulerEnabled": false,
                                                              "trackingMode": "location",
                                                              "distanceFilter": 1,
                                                              "desiredAccuracy": 1,
                                                              "desiredOdometerAccuracy": 100,
                                                              "locationUpdateInterval": 1000,
                                                              "fastestLocationUpdateInterval": 10000,
                                                              "locationTimeout": 60,
                                                              "deferTime": 0,
                                                              "disableElasticity": false,
                                                              "elasticityMultiplier": 1,
                                                              "activityRecognitionInterval": 10000,
                                                              "minimumActivityRecognitionConfidence": 75,
                                                              "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                              "disableStopDetection": false,
                                                              "stationaryRadius": 25,
                                                              "stopTimeout": 5,
                                                              "stopOnStationary": false,
                                                              "url": "",
                                                              "method": "POST",
                                                              "autoSync": true,
                                                              "autoSyncThreshold": 0,
                                                              "batchSync": false,
                                                              "maxBatchSize": -1,
                                                              "params": {},
                                                              "headers": {},
                                                              "extras": {},
                                                              "httpRootProperty": "location",
                                                              "locationTemplate": "",
                                                              "geofenceTemplate": "",
                                                              "persist": true,
                                                              "maxDaysToPersist": 1,
                                                              "maxRecordsToPersist": -1,
                                                              "locationsOrderDirection": "ASC",
                                                              "httpTimeout": 60000,
                                                              "geofenceProximityRadius": 1000,
                                                              "geofenceInitialTriggerEntry": true,
                                                              "stopOnTerminate": true,
                                                              "startOnBoot": true,
                                                              "heartbeatInterval": -1,
                                                              "foregroundService": false,
                                                              "notificationPriority": 0,
                                                              "notificationTitle": "",
                                                              "notificationText": "Location Service activated",
                                                              "notificationColor": "",
                                                              "notificationIcon": "",
                                                              "notificationSmallIcon": "",
                                                              "notificationLargeIcon": "",
                                                              "forceReloadOnLocationChange": false,
                                                              "forceReloadOnMotionChange": false,
                                                              "forceReloadOnGeofence": false,
                                                              "forceReloadOnBoot": false,
                                                              "forceReloadOnHeartbeat": false,
                                                              "forceReloadOnSchedule": false,
                                                              "stopAfterElapsedMinutes": 0,
                                                              "schedule": [],
                                                              "configureUrl": "",
                                                              "configureInterval": -1,
                                                              "debug": true,
                                                              "logLevel": 5,
                                                              "logMaxDays": 3
                                                            }╚═════════════════════════════════════════════
12-30 14:13:26.672 8825-8825/com.toqey D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 1147 : BackgroundGeolocation is configured and ready to use
12-30 14:13:26.673 8825-8825/com.toqey I/chromium: [INFO:CONSOLE(1147)] "BackgroundGeolocation is configured and ready to use", source: file:///android_asset/www/build/main.js (1147)
12-30 14:13:26.675 8825-8825/com.toqey D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 309 : Error in Success callbackId: BackgroundGeolocation1957541475 : TypeError: Cannot read property 'bgGeo' of null
12-30 14:13:26.675 8825-8825/com.toqey I/chromium: [INFO:CONSOLE(309)] "Error in Success callbackId: BackgroundGeolocation1957541475 : TypeError: Cannot read property 'bgGeo' of null", source: file:///android_asset/www/cordova.js (309)
12-30 14:13:30.200 8825-8825/com.toqey W/TSLocationManager: [c.t.l.BootReceiver a] Plugin is configured to stopOnTerminate: true.  Refusing to start BackgroundGeolocation on boot

**Comment by christocracy** [comment]
You have a JavaScript scoping issue in your own app code.  The plugin is configured and ready to use.
