### ISSUE TITLE
Low accuracy on Android

### ISSUE THREAD

**Issue by deceadmin** [transistorsoft/cordova-background-geolocation-lt#58]
Hi,
We have an isssue about the accurracy of the locations on Android devices (for iOS it seems OK). 
There are big jumps on the locations (I mean hundreds of meters). 
We have tried with many combinations of settings to achieve better result. 
We also tested other apps (mainly Strava) on same device and get good results. If both Strava and our app is running in the background our locations are very close to Strava’s and the accurracy is acceptable. But, when our app is running alone the number of locations decreases and some locations are far away from actual path.
We also tried your sample app (on Google Play), results are similar.
 
Our app is mainly used by “walking”. 
 
What are the best settings for accuracy? Do you have any suggestion? This issue is very critical for us. 

Thanks,

**Comment by christocracy** [comment]
Wrong repo.  This is the iOS only free version.  This is not the place for Android issues.

Go here:
https://github.com/transistorsoft/cordova-background-geolocation
