### ISSUE TITLE
ios when forced close for the first time plugin stops working

### ISSUE THREAD

**Issue by novakgio** [transistorsoft/cordova-background-geolocation-lt#581]
## Your Environment
* Plugin version: cordova-background-geolocation-it
* Platform: iOS
* OS version:10.2.1
* Device manufacturer / model:
* Cordova version (`cordova -v`):7.1.0
* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin config

## Expected Behavior
hello . the plugin is awesome and i am very thankful to you for creating it. 
it should work when user force close the app for the first time and opens again after some time, it should continue tracking,but it doesn't. when app is turned off, which means it's not in background ,plugin must be working and keep tracking. and it must be working without plugin-cordova geolocation.

## Actual Behavior
here is what happens: when i first time open the app, all works fine. there is a button and after clicking that button ,i start tracking. when i fold the app and but not force close it, it works fine too.but if i force close the app after it has started tracking, and then open it, tracking doesn't continue. is it something that i should do like(everytime user opens the app ,i have to call bggeo.start() ?  ) and when app is closed and isn't in background, it's not working.so it's working when app is in background or open. 
and i saw your comments about your plugin that only your plugin must be installed ,and not other plugins that have the same service as you.but with your plugin,i have also cordova-plugin-geolocation and without it it's not working at all,because permissions never show up in settings like wheninuse,always never
## Steps to Reproduce

1.
```
this.bgGeo.configure({
        // Geolocation config
        locationAuthorizationRequest: 'Always',
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 10,
        activityRecognitionInterval:10000,
        
        debug: true,  // <-- Debug sounds & notifications.
      }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log(state.enabled,"state what");
        
        this.bgGeo_enabled = true;
        alert(self.bgGeo_enabled+ " dadada");
      });
when user clicks start button, i have this line of code for that

if(this.bgGeo_enabled){
      self.bgGeo.start();
}
```
so it started tracking,now i force closed it, then opened it and plugin is frozen nothing happens,even though i fold it,there comes no notification at all. and why is it not working when app is closed at all?

## Context
thank you christocracy for your work. i have these questions remaining and after that,i am going to buy the license for android,but i don't want to move on until i know these steps are solved. 
it's kind of urgent and i'd be so happy to know you care for my help ;) 

do you think it's a bug that it's not working when moving slowly on foot ?

**Comment by christocracy** [comment]
This makes no sense:
```javascript
this.bgGeo.configure({
        // Geolocation config
        locationAuthorizationRequest: 'Always',
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 10,
        activityRecognitionInterval:10000,
        
        debug: true,  // <-- Debug sounds & notifications.
      }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log(state.enabled,"state what");
        
        this.bgGeo_enabled = true;  // <-- How do you know it's enabled ?????????????
        alert(self.bgGeo_enabled+ " dadada");
      });

.
.
.
if(this.bgGeo_enabled){
      self.bgGeo.start();
}

```

The plugin *persists* its enabled state between reboots.  Once you `#configure` the plugin, it will have automatically called `#start` upon itself.

```javascript
var me = this;
this.bgGeo.configure(config, function(state) {
  console.log('- Configure success.  Am I enabled already?', state.enabled);
});
```

Also, it sure looks like you're having **scope issues** in the `#configure` callback using:
```javascript
}, function(state) {
  this.bgGeo_enabled = true;   // <-- this callback is likely running in the scope of bgGeo
  // Shouldn't you be doing this instead?
  self.bgGeo_enabled = state.enabled;   // <-- state.enabled -- not hard-coded true!!!
});
```

**Comment by christocracy** [comment]
Also, don't use `window.alert` method while debugging.  This is a **blocking** method.

**Comment by novakgio** [comment]
}, function(state) {
  this.bgGeo_enabled = true;   // <-- this callback is likely running in the scope of bgGeo
  // Shouldn't you be doing this instead?
  self.bgGeo_enabled = state.enabled;   // <-- state.enabled -- not hard-coded true!!!
});

i have self in there,i showed typed this because to show you . i have var self=this before configure and in callback,i have self

**Comment by novakgio** [comment]
i will explain my code. imagine i opened app for the first time and when user clicked on button,i have function which says self.bggeo.start(); then user forced close it and when he opens it again, self.bggeo.start() doesn't run because i want that way and it should already be started. then why it stops working?

**Comment by christocracy** [comment]
Logs please.  See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

**Comment by christocracy** [comment]
Are you *sure* you're executing `#configure` *every time the app boots*?  You **must**.

The plugin will not work until `#configure` is executed.

**Comment by novakgio** [comment]
yes i am doing that.everytime it boots, #configure is called. so for the first time when user opened the app,let's say we called this: bggeo.start(),when user reboots it,we don't need to call bggeo.start() right? it happens automatically, because it was started the last time user visited the app.

**Comment by christocracy** [comment]
the plugin persists the `enabled` state in permanent storage.  Once `#start` is called, the plugin is *permanently* enabled, regardless of app terminate or device reboot.

Once `#configure` is executed, the plugin asks itself "Am I enabled?" and calls `#start` upon itself if so.

Provide logs.  The answer is in the logs.

**Comment by novakgio** [comment]
hm, look what i did, 
}, function(state) {
        // This callback is executed when the plugin is ready to use.
        alert(state.enabled);
       
        
      });
i opened the app and when clicked on button,i called bggeo.start(), it started tracking,the i rebooted the app and when came in configure callback,it alerted false . alert(state.enabled); i think it should have alerted true but why false ? i will try the logs but maybe you can guess before i started it

**Comment by christocracy** [comment]
[`stopOnTerminate`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-stoponterminate-true).  Default is `true`.  You need to set it `false`.

**Comment by christocracy** [comment]
You would have seen this in the logs.  Watch the logs!  The plugin is *incredibly* verbose:
```
🔵-[TSLocationManager onAppTerminate] stopOnTerminate? 1   // <-------------- 
🔴-[SOMotionDetector stopShakeDetection] OFF
🔵-[TSLocationManager onAppTerminate] Stopping on terminate  // <---------------

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager stop] 
╚═══════════════════════════════════════════════════════════
🔴-[TSGeofenceManager stopMonitoringGeofences] 
🔴-[TSLocationManager stopUpdatingLocation] 
🔴-[TSLocationManager stopMonitoringBackgroundFetch] BackgroundFetch: OFF
2018-01-08 12:56:05.603350-0500 BG Geo[42170:13982343] [TSBackgroundFetch removeListener]: TSLocationManager
🔴-[TSLocationManager stopMonitoringSignificantLocationChanges] 
2018-01-08 12:56:05.605018-0500 BG Geo[42170:13982343] [TSBackgroundFetch onAppTerminate]
2018-01-08 12:56:05.605111-0500 BG Geo[42170:13982343] [TSBackgroundFetch stop]
```

**Comment by christocracy** [comment]
also, learn to use markdown-syntax highlighting with 3-backticks.

```
var foo = 'bar';
```

Theres a **Styling with Markdown is supported** link right below the `textarea`.

![](https://dl.dropboxusercontent.com/s/he2k0ss1uz4ryzd/Screenshot%202018-01-08%2012.59.53.png?dl=1)

**Comment by christocracy** [comment]
And see [`logLevel`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-loglevel-5).  You want to set that to `logLevel: this.bgGeo.LOG_LEVEL_VERBOSE` during development.

**Comment by novakgio** [comment]
it made it happen and it's working. thank you so much. i have 3 more questions remaining and is not worth creating new thread. and i swear i won't take any of your time. because i value your work.by the way i am gonna buy it and i also like your 1 hour help.

my questions are:
1) when app is forced close, should it continue tracking? i opened it , then i forced closed it and it stops working. maybe that's how it should happen
2) when moving on foot, it's kind of so slow what i mean is i had distancefilter : 50, stationaryradius:25, and it was not working even though i moved 50 meters but i was in the building maybe that's the case.but when i used car it worked like fantastic
3) and withouth cordova-plugin-geolocation your plugin won't work,because i can't change permission in app settings. is it good to have both ? will they get along?

**Comment by christocracy** [comment]
>when app is forced close, should it continue tracking? i opened it , then i forced closed it and it stops working. maybe that's how it should happen

Read all **iOS** section in [`stopOnTerminate`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-stoponterminate-true) docs.

>Before an iOS app terminates, the plugin will ensure that a stationary geofence is created around the last known position. When the user moves beyond the stationary geofence (typically ~200 meters), iOS will completely reboot your application in the background, including your Javascript application and the plugin will resume tracking. iOS maintains geofence monitoring at the OS level, in spite of application terminate / device reboot.

>when moving on foot, it's kind of so slow what i mean is i had distancefilter : 50, stationaryradius:25, and it was not working even though i moved 50 meters but i was in the building maybe that's the case.but when i used car it worked like fantastic

iOS device needs to move *at least* 200 meters before tracking engages.

>and withouth cordova-plugin-geolocation your plugin won't work,because i can't change permission in app settings. is it good to have both ? will they get along?

No, don't use both.  Use only mine.  Using both can cause a "permissions tug-of-war".  Get rid of `cordova-plugin-geolocation`.  My plugin does everything an more.

**Comment by novakgio** [comment]
i understand all. thank you for your help and availability. i never saw anyone help me that quickly when i used other plugins than you. 
you may close the issue ;)

**Comment by christocracy** [comment]
>i never saw anyone help me that quickly 

This is why I charge $.  Full time support.

**Comment by novakgio** [comment]
if i bought a lisense for android,you will help me whenever i need? you're my NO.1

**Comment by christocracy** [comment]
I respond to all posted issues.  Paying customers get #1 priority over issues posted in this public repo (purchasing provides access to a private repo with latest updates / features / fixes).  This public repo gets updated only every few months.
