### ISSUE TITLE
Android configure failure

### ISSUE THREAD

**Issue by oshek14** [transistorsoft/cordova-background-geolocation-lt#584]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 8.1
* Device manufacturer / model: Nexus 5x
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):
* Plugin config

Everything works fine on emulator, but on real device bgGeo fails to configure and returns error  function : "configure failure". what can be the reason?

**Comment by christocracy** [comment]
Show me logs from `adb logcat`

**Comment by oshek14** [comment]
I made it happen and no need for you to worry about that. 

by the way, i was curious about permissions.
1) on iphone, when user launches the app for the first time, it doesn't ask permission, then user changes the page where i have written `bggeo.getcurrentposition()` and as soon as this happens, permission is like **"allow" or don't allow**, but on simulator permission is like : **allow,don't allow, when in use .** i am sure i don't have other geolocation plugins.i have only you. if it shows the right permission message on simulator,why not on device?

2) on android, as soon as user launches the app for the first time, it asks permission immediatelly and not as it was on iphone when it asked when user entered page where i had  `bggeo.getcurrentposition()`

That's all . It works so good on android .

**Comment by christocracy** [comment]
Your sim is running iOS 11.  Your device is not.  iOS 11 forces you to offer both *Always* and *When in Use* permission.  See [here](https://www.plotprojects.com/ios-11-update-location-services-rationale/)

>on android, as soon as user launches the app for the first time, it asks permission immediatelly and not as it was on iphone when it asked when user entered page where i had

Android asks permission as soon as `#configure` is executed.  iOS waits until location is requested.
