### ISSUE TITLE
check before http call

### ISSUE THREAD

**Issue by oshek14** [transistorsoft/cordova-background-geolocation-lt#586]
before http call is made, i want to check something. i am using http params calls in your `#configure` . but how do i check something before call is made? some days ago, I was using
```
 bggeo.on('location,function(){
if(isId == true){
this.$http.post('myurl',data);
}


})
```
 this is how i was doing,but in this case , when app was in background,it wouldn't make calls. that's why i changed it and used your http params call in` #configure.`but this way i can't check something before call made. how do i achieve this?

**Comment by christocracy** [comment]
You can’t.  What does this “isId” *mean*?

**Comment by oshek14** [comment]
It's just my variable and in case it's true, then I'd want to make http request.

then,It's no way possible? I am dependent on storage and if on the way,  tracking is going on and if user deletes the storage, then I don't want any api calls to continue . do you think, after deleting storage, it would also go to provider change event? that way i'd call bggeo.stop()

**Comment by christocracy** [comment]
When the location event fires, the http request has already been sent.

If you want to stop recording locations, execute the #stop method.

**Comment by oshek14** [comment]
the thing is something else.
this is from your docs.are you sure,this doesn't work when app is booted in background,because i tried and it didn't 👍  that's why i am using your http params in `#configure ` 
```
BackgroundGeolocation.on('location', function(location) {
  var coords    = location.coords,
    timestamp   = location.timestamp
    latitude    = coords.latitude,
    longitude   = coords.longitude,
    speed       = coords.speed;
this.$http.post('my-server',longitude);
  console.log("- Location: ", timestamp, latitude, longitude, speed);
}, function(errorCode) {
  console.warn("- Location error: ", errorCode);
});
```

**Comment by christocracy** [comment]
It depends on iOS vs Android.
