### ISSUE TITLE
How do you get logs?

### ISSUE THREAD

**Issue by jenniewerner** [transistorsoft/cordova-background-geolocation-lt#587]
Hi, 

I've seen the section on debugging, but I'm quite confused on how to access logs. It says logs stored in a database and you can use the`getLog` function to see logs in the console. Where am I supposed to call the `getLog` function? I'm not sure what I'm missing here... 

Thanks for the help!

**Comment by christocracy** [comment]
#getLog returns a string.

Boot the JavaScript web console and interact with the plugin directly from the console.

Copy the result.  Paste into a file.

**Comment by jenniewerner** [comment]
By the JavaScript web console, do you mean load my app in a web browser, inspect the web page and then use the console??

**Comment by christocracy** [comment]
Loading the Javascript Web Console for your app running on your *device* is a fundamental part of application development.  It's assumed you know how to do this.

For iOS, from Safari:
![](https://dl.dropboxusercontent.com/s/2zp3vcj024k4npm/Screenshot%202018-01-14%2019.19.23.png?dl=1 )

Android, from Chrome:  chrome://inspect/#devices
![](https://dl.dropboxusercontent.com/s/i02413mewf6ds2q/Screenshot%202018-01-14%2019.23.36.png?dl=1)

**Comment by jenniewerner** [comment]
Thanks for the pointer! My app signing didn't allow me to inspect it with Safari, but finally got that sorted out...

When I try and get the logs in the Safari console, I get the error: `Error invoking Method ‘locations.updateUser’: Method ‘locations.updateUser’ not found [404]`

**Comment by christocracy** [comment]
That looks like an error in *your own* application code.

**Comment by jenniewerner** [comment]
That function doesn't exist on our end, so I assumed it was from your package. I still haven't been able to get the logs. When I use the emailLog function all I see is the configuration information for your package. We have loglevel set to verbose. I assumed since location tracking is working there would be logs to look at.

**Comment by christocracy** [comment]
The plugin has no concept of "users" or `updateUser`.

`#emailLog` adds a `background-geolocation.log.gz` *file-attachment* to the email.

**Comment by jenniewerner** [comment]
There is no attached file in the email — the body of the email has the configuration information and that is the _only_ contents of the email.

**Comment by bewithjatin** [comment]
how to get this logs on my server via api tell me the parameter used in app for api
