### ISSUE TITLE
Plugin asks for extra permissions on Android 4.4.2

### ISSUE THREAD

**Issue by id4coding** [transistorsoft/cordova-background-geolocation-lt#588]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: Android 4.4.2
* Device manufacturer / model: Micromax A350
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config

## Expected Behavior

An app using the background geolocation plugin doesn't ask for extra permissions while installing on Android 6.0.1 on a Nexus 5 phone. 
![android6_screenshot](https://user-images.githubusercontent.com/26519811/34930679-af245eea-f9f0-11e7-8e50-3a78a7ee22ff.png)

## Actual Behavior

An app without the background geolocation plugin asks for the following permissions:

![android442_wo_bg_plugin](https://user-images.githubusercontent.com/26519811/34930863-b53182a8-f9f1-11e7-96b8-a02accb2553a.png)

However, on an Android 4.4.2 Micromax A350 phone, the app using the background geolocation plugin asks for extra permissions. The screenshot is below:

![android4_4_2_screenshot](https://user-images.githubusercontent.com/26519811/34930745-0ed0c31a-f9f1-11e7-93ab-e96051fc2445.png)

## Steps to Reproduce

1. Build an app with the background geolocation plugin and try to install the app.

## Context

Install an app built with the background geolocation plugin on Android 6 and Android 4.4.2 phones.

**Comment by id4coding** [comment]
Is there any way to turn off the prompt for extra permissions?

**Comment by christocracy** [comment]
I see nothing unusual here.  What specific permission would you have removed?

**Comment by id4coding** [comment]
Wondering why there is difference in permissions asked for newer version of Android versus older? And is there a plugin option to configure the different permissions/access that are prompted, for example, "retrieve running apps", "run at startup"?

**Comment by christocracy** [comment]
>Why there is difference

Obviously Android is becoming more strict with telling the user what’s going on with the apps running on the device they paid for.

“Retrieve running apps”: used for detecting if app was terminated.

“Run at startup”:  used for determining if plugin needs to `startAtBoot`.  Very common permission.

**Comment by id4coding** [comment]
Thanks, Chris, for clarifying that. I've one unrelated question. Would like to know whether there is any difference in performance between the debug build and the production build? Specifically, I would like to know whether in production mode the plugin gets location info faster than in debug mode?

**Comment by christocracy** [comment]
>any difference in performance

No.  The battery will drain faster, of course, while playing sounds, showing notifications, logging.

**Comment by id4coding** [comment]
Thanks for your clarification.
