### ISSUE TITLE
getCurrentPosition is failing silently

### ISSUE THREAD

**Issue by kiwicreation** [transistorsoft/cordova-background-geolocation-lt#59]
On Android, I have an app using the following code
```js
window.BackgroundGeolocation.configure(
	function (location, taskid) {
		console.debug('Configure cb', taskid);
		window.BackgroundGeolocation.finish(taskid);
	},
	function (err) {
		console.debug('Configure error', err);
	},
	{
		desiredAccuracy: 10, // 0, 10, 100, 1000 : 0 is accurate as hell, 1000 is lazy
		distanceFilter: 20, // 10,
		stopTimeout: 5,

		// iOS
		activityType: 'OtherNavigation',
		disableElasticity: true, // try to have an constant update or else update interval will depends on speed
		stationaryRadius: 20,

		// Android
		locationUpdateInterval: 1000,
		fastestLocationUpdateInterval: 1000,
		activityRecognitionInterval: 0, // 10000,
	}
);

setInterval(function () {
	console.debug('Interval start');
	try {
		window.BackgroundGeolocation.getCurrentPosition(
			function (location, taskid) {
				console.debug('Interval yay', taskid);
				window.BackgroundGeolocation.finish(taskid);
			},
			function (err) {
				console.debug('Interval error', err);
			},
			{
				//timeout: 30,
				maximumAge: 1000,
				//minimumAccuracy: 10
			}
		);
	} catch (e) {
		console.debug('Interval catch', e);
	}
}, 1000);
```
The following code does :
1. Configure plugin.
2. Begin an interval loop.
3. Try to getCurrentPosition every second or so.

First time the app is *newly installed* (or after *Clear Data* was done in the App setting), everything is fine. The code print every second or so :
```
Interval start
Interval yay
Interval start
Interval yay
Interval start
Interval yay
Interval start
Interval yay
```

But after a few runs (opening App, and closing it), it never get to `Interval yay` and never trigger any error callback or catch an error :
```
Interval start
Interval start
Interval start
Interval start
```

Am I doing something wrong?

_P.S. I want foreground maximum power Position. Never tried the `start()` approach as it seems to only work when app is in background_

**Comment by mgrenier** [comment]
Same thing happens when I replace the whole `setInterval(...)` block with `window.BackgroundGeolocation.start();`. On a fresh install (or _Clear Data_) it work as expected but after 1 or 2 run, `Configure cb` is never reached.

**Comment by kiwicreation** [comment]
Same thing happens when I replace the whole `setInterval(...)` block with `window.BackgroundGeolocation.start();`. On a fresh install (or _Clear Data_) it work as expected but after 1 or 2 run, `Configure cb` is never reached.

**Comment by christocracy** [comment]
This repo hosts only the iOS plugin.  There is no Android in this repo.

**Comment by kiwicreation** [comment]
Moved the issue to the correct repo, [issue 413](https://github.com/transistorsoft/cordova-background-geolocation/issues/413)
