### ISSUE TITLE
window.BackgroundGeolocation undefined

### ISSUE THREAD

**Issue by 85willie** [transistorsoft/cordova-background-geolocation-lt#591]
Hi,

i realize that all the samples are single .js file to call the "window.BackgroundGeolocation" which is called after device ready is called. But in my application the next page "after index.js" i called/use window.BackgroundGeolocation it shows that the variable is undefined. How can i solve this issue?

**Comment by christocracy** [comment]
Provide a general summary of the issue in the Title above

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by alessandroame** [comment]
Plugin version: ~2.9.1
Platform: Android
OS version: 5.1.1
Device manufacturer / model: Samsung sm-t335
Cordova version (cordova -v): 6.3.1
Cordova platform version (cordova platform ls):   android 5.2.2
Plugin config: I leave all variable empty (should use default values right?)

from the chrome developer tools in console window.BackgroundGeolocation return undefined
I've also trid with this js in my index page with same result: 
document.addEventListener("deviceready", locationHelper.init, false);

**Comment by christocracy** [comment]
With `2.9.1`, minimum required cordova is `7.1.0` (particularly `cordova-android@6.3.0`).

Check your `$ adb logcat`

**Comment by apistraining** [comment]
I have cordova 8.0 version.. installed plugin and initialised it in platform ready event as it is ionic app.
Still I am getting 'window.BackgroundGeolocation' is undefined. tried in android device as well.
return {    
          init: function () {
            $ionicPlatform.ready(function() {
              var bgGeo = window.BackgroundGeolocation;
              alert("BackgroundGeolocation?: " + bgGeo); 
          });
        }
    };
I am calling this init method from some other js file.
please help

Plugin version: 2.12.2
Platform: Android
OS version: 
Device manufacturer / model: Google pixel2 XL
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): android 7.0.0

**Comment by christocracy** [comment]
When in doubt, remove plugin and platforms.  Re-add

**Comment by apistraining** [comment]
yes..done everything.. removed plugins, added back; removed platforms and added back;
still same issue :(

**Comment by christocracy** [comment]
Don’t know.  I suggest you modify your `engine=“6.3.0”` to something more appropriate.

**Comment by apistraining** [comment]
Can you please elaborate ? You mean to upgrade  Cordova -android version?

**Comment by christocracy** [comment]
>Can you please elaborate ?

As you said:

>Note: in my config.xml, it shows this:

```xml
<engine name="android" spec="6.3.0" />
```

**Comment by apistraining** [comment]
updated engine="7.0.0", still same issue !
for a new ionic app, it is working.. but if I include plugin in my application, it gives undefined.
please advice how can I debug this situation (I am a newbee to ionic application development)

**Comment by apistraining** [comment]
@85willie : are you able to solve your issue ?

**Comment by christocracy** [comment]
In your own app, try installing plugin version `2.11.0`.  If that works, you have an Android platform issue.

- 2.11.0 only works with cordova-android <= 6.4.0.
- 2.12.0 only works with cordova-android >= 7.0.0
