### ISSUE TITLE
Build fails after adding plugins to Ionic cordova project

### ISSUE THREAD

**Issue by bavithranmahendran** [transistorsoft/cordova-background-geolocation-lt#593]
Before adding the background-geolocation plugin I able to build my app, but after installing a native plugin ( ionic plugin add cordova-plugin-mauron85-background-geolocation ).

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:javaPreCompileDebug
 UP-TO-DATE

:app:compileDebugJavaWithJavac
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:563: error: cannot find symbol

    @TargetApi(Build.VERSION_CODES.KITKAT)

                                  ^
  symbol:   variable KITKAT
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:189: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR2

  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:190: error: cannot find symbol
            handlerThread.quitSafely();
                         ^
  symbol:   method quitSafely()
  location: variable handlerThread of type HandlerThread
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:198: error: method does not override or implement a method from a supertype
    @Override
    ^
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:207: error: cannot find symbol
        super.onTaskRemoved(rootIntent);
             ^
  symbol: method onTaskRemoved(Intent)
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:421: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
                                                        ^
  symbol:   variable HONEYCOMB
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:422: error: cannot find symbol
            task.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, location);
                                            ^
  symbol:   variable THREAD_POOL_EXECUTOR
  location: class AsyncTask

/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:55: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR1
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:56: error: cannot find symbol
            elapsedRealtimeNanos = location.getElapsedRealtimeNanos();
                                           ^

  symbol:   method getElapsedRealtimeNanos()
  location: variable location of type Location
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:58: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR2
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:59: error: cannot find symbol

            isFromMockProvider = location.isFromMockProvider();
                                         ^
  symbol:   method isFromMockProvider()
  location: variable location of type Location
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:567: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR1
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:568: error: cannot find symbol
            l.setElapsedRealtimeNanos(elapsedRealtimeNanos);
             ^
  symbol:   method setElapsedRealtimeNanos(long)
  location: variable l of type Location
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:592: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR1
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteOpenHelper.java:118: error: cannot find symbol
        Log.d(TAG, "Creating db: " + this.getDatabaseName());
                                         ^
  symbol: method getDatabaseName()
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteOpenHelper.java:172: error: method does not override or implement a method from a supertype

    @Override
    ^
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteLocationDAO.java:113: error: method queryNumEntries in class DatabaseUtils cannot be applied to given types;

    return DatabaseUtils.queryNumEntries(db, LocationEntry.TABLE_NAME, whereClause, whereArgs);
                        ^
  required: SQLiteDatabase,String
  found: SQLiteDatabase,String,String,String[]
  reason: actual and formal argument lists differ in length
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteLocationDAO.java:154: error: cannot find symbol
    db.beginTransactionNonExclusive();
      ^
  symbol:   method beginTransactionNonExclusive()
  location: variable db of type SQLiteDatabase
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/sync/SyncAdapter.java:71: error: constructor AbstractThreadedSyncAdapter in class AbstractThreadedSyncAdapter cannot be applied to given types;
        super(context, autoInitialize, allowParallelSyncs);
        ^
  required: Context,boolean
  found: Context,boolean,boolean
  reason: actual and formal argument lists differ in length
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/sync/BatchManager.java:70: error: cannot find symbol
            db.beginTransactionNonExclusive();
              ^
  symbol:   method beginTransactionNonExclusive()
  location: variable db of type SQLiteDatabase
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/sync/SyncService.java:60: error: cannot find symbol

        settingsBundle.putBoolean(ContentResolver.SYNC_EXTRAS_DO_NOT_RETRY, false);
                                                 ^
  symbol:   variable SYNC_EXTRAS_DO_NOT_RETRY
  location: class ContentResolver
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/HttpPostService.java:59: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                                                        ^
  symbol:   variable KITKAT
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:535: error: cannot find symbol
            activity.bindService(locationServiceIntent, mConnection, Context.BIND_IMPORTANT);
                                                                            ^
  symbol:   variable BIND_IMPORTANT
  location: class Context
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:569: error: cannot find symbol

        return getContext().registerReceiver(locationModeChangeReceiver, new IntentFilter(LocationManager.MODE_CHANGED_ACTION));
                                                                                                         ^
  symbol:   variable MODE_CHANGED_ACTION
  location: class LocationManager

/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:585: error: cannot find symbol
        Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
                                           ^
  symbol:   variable ACTION_APPLICATION_DETAILS_SETTINGS
  location: class Settings
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:598: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                                                        ^
  symbol:   variable KITKAT
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:599: error: cannot find symbol
            locationMode = Settings.Secure.getInt(context.getContentResolver(), Settings.Secure.LOCATION_MODE);
                                                                                               ^
  symbol:   variable LOCATION_MODE
  location: class Secure
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:600: error: cannot find symbol
            return locationMode != Settings.Secure.LOCATION_MODE_OFF;
                                                  ^
  symbol:   variable LOCATION_MODE_OFF
  location: class Secure
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:148: error: cannot find symbol

            criteria.setHorizontalAccuracy(translateDesiredAccuracy(config.getDesiredAccuracy()));

                    ^

  symbol:   method setHorizontalAccuracy(Integer)

  location: variable criteria of type Criteria

/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:166: error: cannot find symbol

                    if (provider != LocationManager.PASSIVE_PROVIDER) {
                                                   ^
  symbol:   variable PASSIVE_PROVIDER
  location: class LocationManager
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:187: error: cannot find symbol
                accuracy = Criteria.ACCURACY_LOW;
                                   ^
  symbol:   variable ACCURACY_LOW
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:190: error: cannot find symbol
                accuracy = Criteria.ACCURACY_MEDIUM;

                                   ^

  symbol:   variable ACCURACY_MEDIUM
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:193: error: cannot find symbol
                accuracy = Criteria.ACCURACY_HIGH;
                                   ^
  symbol:   variable ACCURACY_HIGH
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:196: error: cannot find symbol
                accuracy = Criteria.ACCURACY_HIGH;
                                   ^
  symbol:   variable ACCURACY_HIGH
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:199: error: cannot find symbol

                accuracy = Criteria.ACCURACY_MEDIUM;

                                   ^
  symbol:   variable ACCURACY_MEDIUM
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:463: error: cannot find symbol
             criteria.setHorizontalAccuracy(Criteria.ACCURACY_HIGH);
                                                    ^
  symbol:   variable ACCURACY_HIGH
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:467: error: cannot find symbol
                 locationManager.requestSingleUpdate(criteria, singleUpdatePI);
                                ^
  symbol:   method requestSingleUpdate(Criteria,PendingIntent)
  location: variable locationManager of type LocationManager
/kepler/cloudo/platforms/android/app/src/main/java/io/ionic/keyboard/IonicKeyboard.java:91: error: cannot find symbol
                                display.getSize(size);
                                       ^
  symbol:   method getSize(Point)
  location: variable display of type Display
/kepler/cloudo/platforms/android/app/src/main/java/io/ionic/keyboard/IonicKeyboard.java:131: error: cannot find symbol
        rootView.getViewTreeObserver().removeOnGlobalLayoutListener(list);
                                      ^
  symbol:   method removeOnGlobalLayoutListener(OnGlobalLayoutListener)
  location: class ViewTreeObserver
/kepler/cloudo/platforms/android/app/src/main/java/org/apache/cordova/splashscreen/SplashScreen.java:290: error: cannot find symbol
                LayoutParams layoutParams = new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
                                                                                      ^
  symbol:   variable MATCH_PARENT
  location: class LayoutParams
/kepler/cloudo/platforms/android/app/src/main/java/org/apache/cordova/splashscreen/SplashScreen.java:290: error: cannot find symbol
                LayoutParams layoutParams = new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
                                                                                                                 ^
  symbol:   variable MATCH_PARENT
  location: class LayoutParams
/kepler/cloudo/platforms/android/app/src/main/java/org/apache/cordova/device/Device.java:132: error: cannot find symbol
        String serial = android.os.Build.SERIAL;
                                        ^
  symbol:   variable SERIAL
  location: class Build
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.
42 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
27 actionable tasks: 1 executed, 26 up-to-date
(node:16444) UnhandledPromiseRejectionWarning: Error: /kepler/cloudo/platforms/android/gradlew: Command failed with exit code 1 Error output:
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:563: error: cannot find symbol
    @TargetApi(Build.VERSION_CODES.KITKAT)
                                  ^
  symbol:   variable KITKAT
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:189: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR2
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:190: error: cannot find symbol
            handlerThread.quitSafely();
                         ^
  symbol:   method quitSafely()
  location: variable handlerThread of type HandlerThread
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:198: error: method does not override or implement a method from a supertype
    @Override
    ^
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:207: error: cannot find symbol
        super.onTaskRemoved(rootIntent);
             ^
  symbol: method onTaskRemoved(Intent)
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:421: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
                                                        ^
  symbol:   variable HONEYCOMB
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/LocationService.java:422: error: cannot find symbol
            task.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, location);
                                            ^
  symbol:   variable THREAD_POOL_EXECUTOR
  location: class AsyncTask
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:55: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR1
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:56: error: cannot find symbol
            elapsedRealtimeNanos = location.getElapsedRealtimeNanos();
                                           ^
  symbol:   method getElapsedRealtimeNanos()
  location: variable location of type Location
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:58: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR2
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:59: error: cannot find symbol
            isFromMockProvider = location.isFromMockProvider();
                                         ^
  symbol:   method isFromMockProvider()
  location: variable location of type Location
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:567: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR1
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:568: error: cannot find symbol
            l.setElapsedRealtimeNanos(elapsedRealtimeNanos);
             ^
  symbol:   method setElapsedRealtimeNanos(long)
  location: variable l of type Location
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundLocation.java:592: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                                                        ^
  symbol:   variable JELLY_BEAN_MR1
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteOpenHelper.java:118: error: cannot find symbol
        Log.d(TAG, "Creating db: " + this.getDatabaseName());
                                         ^
  symbol: method getDatabaseName()
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteOpenHelper.java:172: error: method does not override or implement a method from a supertype
    @Override
    ^
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteLocationDAO.java:113: error: method queryNumEntries in class DatabaseUtils cannot be applied to given types;
    return DatabaseUtils.queryNumEntries(db, LocationEntry.TABLE_NAME, whereClause, whereArgs);
                        ^
  required: SQLiteDatabase,String
  found: SQLiteDatabase,String,String,String[]
  reason: actual and formal argument lists differ in length
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteLocationDAO.java:154: error: cannot find symbol
    db.beginTransactionNonExclusive();
      ^
  symbol:   method beginTransactionNonExclusive()
  location: variable db of type SQLiteDatabase
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/sync/SyncAdapter.java:71: error: constructor AbstractThreadedSyncAdapter in class AbstractThreadedSyncAdapter cannot be applied to given types;
        super(context, autoInitialize, allowParallelSyncs);
        ^
  required: Context,boolean
  found: Context,boolean,boolean
  reason: actual and formal argument lists differ in length
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/sync/BatchManager.java:70: error: cannot find symbol
            db.beginTransactionNonExclusive();
              ^
  symbol:   method beginTransactionNonExclusive()
  location: variable db of type SQLiteDatabase
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/sync/SyncService.java:60: error: cannot find symbol
        settingsBundle.putBoolean(ContentResolver.SYNC_EXTRAS_DO_NOT_RETRY, false);
                                                 ^
  symbol:   variable SYNC_EXTRAS_DO_NOT_RETRY
  location: class ContentResolver
/kepler/cloudo/platforms/android/app/src/main/java/com/marianhello/bgloc/HttpPostService.java:59: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                                                        ^
  symbol:   variable KITKAT
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:535: error: cannot find symbol
            activity.bindService(locationServiceIntent, mConnection, Context.BIND_IMPORTANT);
                                                                            ^
  symbol:   variable BIND_IMPORTANT
  location: class Context
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:569: error: cannot find symbol
        return getContext().registerReceiver(locationModeChangeReceiver, new IntentFilter(LocationManager.MODE_CHANGED_ACTION));
                                                                                                         ^
  symbol:   variable MODE_CHANGED_ACTION
  location: class LocationManager
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:585: error: cannot find symbol
        Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
                                           ^
  symbol:   variable ACTION_APPLICATION_DETAILS_SETTINGS
  location: class Settings
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:598: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                                                        ^
  symbol:   variable KITKAT
  location: class VERSION_CODES
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:599: error: cannot find symbol
            locationMode = Settings.Secure.getInt(context.getContentResolver(), Settings.Secure.LOCATION_MODE);
                                                                                               ^
  symbol:   variable LOCATION_MODE
  location: class Secure
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java:600: error: cannot find symbol
            return locationMode != Settings.Secure.LOCATION_MODE_OFF;
                                                  ^
  symbol:   variable LOCATION_MODE_OFF
  location: class Secure
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:148: error: cannot find symbol
            criteria.setHorizontalAccuracy(translateDesiredAccuracy(config.getDesiredAccuracy()));
                    ^
  symbol:   method setHorizontalAccuracy(Integer)
  location: variable criteria of type Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:166: error: cannot find symbol
                    if (provider != LocationManager.PASSIVE_PROVIDER) {
                                                   ^
  symbol:   variable PASSIVE_PROVIDER
  location: class LocationManager
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:187: error: cannot find symbol
                accuracy = Criteria.ACCURACY_LOW;
                                   ^
  symbol:   variable ACCURACY_LOW
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:190: error: cannot find symbol
                accuracy = Criteria.ACCURACY_MEDIUM;
                                   ^
  symbol:   variable ACCURACY_MEDIUM
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:193: error: cannot find symbol
                accuracy = Criteria.ACCURACY_HIGH;
                                   ^
  symbol:   variable ACCURACY_HIGH
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:196: error: cannot find symbol
                accuracy = Criteria.ACCURACY_HIGH;
                                   ^
  symbol:   variable ACCURACY_HIGH
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:199: error: cannot find symbol
                accuracy = Criteria.ACCURACY_MEDIUM;
                                   ^
  symbol:   variable ACCURACY_MEDIUM
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:463: error: cannot find symbol
             criteria.setHorizontalAccuracy(Criteria.ACCURACY_HIGH);
                                                    ^
  symbol:   variable ACCURACY_HIGH
  location: class Criteria
/kepler/cloudo/platforms/android/app/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java:467: error: cannot find symbol
                 locationManager.requestSingleUpdate(criteria, singleUpdatePI);
                                ^
  symbol:   method requestSingleUpdate(Criteria,PendingIntent)
  location: variable locationManager of type LocationManager
/kepler/cloudo/platforms/android/app/src/main/java/io/ionic/keyboard/IonicKeyboard.java:91: error: cannot find symbol
                                display.getSize(size);
                                       ^
  symbol:   method getSize(Point)
  location: variable display of type Display
/kepler/cloudo/platforms/android/app/src/main/java/io/ionic/keyboard/IonicKeyboard.java:131: error: cannot find symbol
        rootView.getViewTreeObserver().removeOnGlobalLayoutListener(list);
                                      ^
  symbol:   method removeOnGlobalLayoutListener(OnGlobalLayoutListener)
  location: class ViewTreeObserver
/kepler/cloudo/platforms/android/app/src/main/java/org/apache/cordova/splashscreen/SplashScreen.java:290: error: cannot find symbol
                LayoutParams layoutParams = new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
                                                                                      ^
  symbol:   variable MATCH_PARENT
  location: class LayoutParams
/kepler/cloudo/platforms/android/app/src/main/java/org/apache/cordova/splashscreen/SplashScreen.java:290: error: cannot find symbol
                LayoutParams layoutParams = new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
                                                                                                                 ^
  symbol:   variable MATCH_PARENT
  location: class LayoutParams
/kepler/cloudo/platforms/android/app/src/main/java/org/apache/cordova/device/Device.java:132: error: cannot find symbol

**Comment by christocracy** [comment]
`cordova-plugin-mauron85-background-geolocation` is a fork of my original project.  You're commenting at the wrong repo.

This repo is [`cordova-background-geolocation-lt`](https://github.com/transistorsoft/cordova-background-geolocation-lt)
