### ISSUE TITLE
Visual Studio Environment friendly Config

### ISSUE THREAD

**Issue by wpmanoj** [transistorsoft/cordova-background-geolocation-lt#594]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: 6 and above
* Device manufacturer / model: 
* Cordova version (`cordova -v`): 6.3.1
* Cordova platform version (`cordova platform ls`): cordova android 5.2.1
* Plugin config

* using to build app - Visual studio environment

**# Please help to find out to fill this form inputs.**

![untitled-1](https://user-images.githubusercontent.com/8339938/35568450-084cb6e8-05ef-11e8-954d-59729aeac30e.jpg)

**Comment by christocracy** [comment]
The plugin provides default values for all those variables.

See [README](https://github.com/transistorsoft/cordova-background-geolocation-lt#configuration-variables)

**Comment by wpmanoj** [comment]
Plugin added to the Solution. but seems like plugin not working 

`var bgGeo = window.BackgroundGeolocation;`

return undefined. is there have any thing to do other than install the plugin.

**Comment by christocracy** [comment]
For plugin version `2.9.1`, minimum required Cordova is `7.1.0` (`cordova-android@6.3.0`).

Check your `$ adb logcat` for errors.

**Comment by wpmanoj** [comment]
updating cordova version in Visual Studio is too painful.  please suggest me proper plugin version to my  working environment.

**Comment by christocracy** [comment]
I have no sympathy for Visual Studio.  You **must** use Cordova 7.1.0.

If VS can’t handle this, throw VS in the garbage and use the Cordova CLI manually, like most everyone else.
