### ISSUE TITLE
Config for highest precision and continuously flow of locations

### ISSUE THREAD

**Issue by lbhifi** [transistorsoft/cordova-background-geolocation-lt#595]
Targeting Android and iOS devices in general.

When battery power efficiency is no issue, and you want max precision and at least 1 location per second continuously, both in foreground and background and preferable also at stationary.
(Also it is important to return locations as quickly as possible after stationary).
What would be the most optimal configuration?

Is this a good configuration, or could it be fine tuned even more?

var config = {
desiredAccuracy: 0,
distanceFilter: 0,
disableElasticity: true,
stationaryRadius: 1,
locationAuthorizationRequest: "Always",
locationAuthorizationAlert: {
titleWhenNotEnabled: "Lokalitetstjenester er ikke aktiveret",
titleWhenOff: "Lokalitetstjenester er slået fra",
instructions: "Denne app kræver at 'Altid' er valgt i lokalitetstjenester",
cancelButton: "Fortryd",
settingsButton: "Indtillinger"
},
locationUpdateInterval: 900,
fastestLocationUpdateInterval: 900,
activityRecognitionInterval: 500,
heartbeatInterval: 30,
preventSuspend: true,
foregroundService: true,
stopTimeout: 60
}

**Comment by christocracy** [comment]
Yes, it’s fine
