### ISSUE TITLE
Plugin doesn't restart after reboot or after closing app

### ISSUE THREAD

**Issue by Smartronic2017** [transistorsoft/cordova-background-geolocation-lt#597]
I use the plugin in geofence mode.
It seems working.
But when i close my app from the recent list, the plugin stops. Also when i reboot my device, app doesn't start automatically. Even if i add startOnBoot:true and stopOnTerminate:false.

## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: Android 7.0
* Device manufacturer / model: all the devices (real testing on Huawei Mediapad T3 10)
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config:

 var bgGeo = window.BackgroundGeolocation;

        bgGeo.on('geofence', function(params) {
          console.log(params);

          $("#allNotifications").append("<li class='list-group-item' style='font-size: large;background-color: aliceblue;'><b>"
           + params.identifier + "</b><br>" + params.action + "</li>");

          bgGeo.finish();
        });

      bgGeo.configure({
        stopOnTerminate:false,
        startOnBoot:true,
        geofenceProximityRadius:300,
        geofenceInitialTriggerEntry:true,
        debug: false  // <-- Debug sounds & notifications.
      }, function(state) {
        // Add some geofences.
        bgGeo.addGeofences([{......},{...}], function() {
          console.log("Successfully added geofence");
        }, function(error) {
          console.warn("Failed to add geofence", error);
        });

          bgGeo.startGeofences(function(state) {
            console.log('- Geofence-only monitoring started', state.trackingMode);
          //  bgGeo.changePace(true);
            bgGeo.getGeofences(function(geofences) {
             console.log(geofences);
            }, function(error) {
              console.warn("Failed to fetch geofences from server");
            });
          });
      });
      

## Expected Behavior
When i close my app or reboot device, the geofecing start automatically.

## Actual Behavior
When i close my app or reboot device, the geofecing doesn't start automatically.

## Steps to Reproduce
Use the code above written in the Plugin confif node

**Comment by christocracy** [comment]
How do you know your geofences aren't working?
- set `debug: true` so you can *hear* them (*beep-beep-beep*)
- Observe the logs.  See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)
- If you're thinking your Javascript is going to execute after terminating or rebooting an Android device, that's not going to happen.  Only the native Android service is running.  That's why the plugin hosts its own HTTP service:  so the native code can continue to post events to your server while your Javascript app is dead.
