### ISSUE TITLE
Does this work with MeteorJS?

### ISSUE THREAD

**Issue by ianpogi5** [transistorsoft/cordova-background-geolocation-lt#60]
As per title, does this work with MeteorJS?

**Comment by christocracy** [comment]
I have a few customers using Meteor

On Friday, January 29, 2016, Ian dela Cruz <notifications@github.com> wrote:

> As per title, does this work with MeteorJS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/60>
> .
>


-- 
Snet form Gmail Mobile
