### ISSUE TITLE
[New Feature] "Headless Mode" for Android

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/cordova-background-geolocation-lt#600]
On Android, when you terminate your app with the **`BackgroundGeolocation`** plugin configured with **`stopOnTerminate: false`**, your Javascript code *is completely terminated* &mdash; only the plugin's native Android background service continues running.  If you've configured the plugin with an **`#url`**, its Android background Service will continue posting locations to your server.

But what if you need to implement some custom business logic in this "headless" state, such as posting a local-notification or executing **`#getCurrentPosition`** in a **`heartbeat`** event?

The **`BackgroundGeolocation`** plugin for now provides a mechanism for you to implement your own custom code to handle all the plugin's events while in the "Headless" state (`heartbeat, location, motionchange, geofence`, etc).

For more information, see the Wiki [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode).

**Comment by christocracy** [comment]
Simply listen to “geofence” event.  You’re free to do whatever you want there.  Yes, it works in background.

**Comment by ejordana** [comment]
I got it! Thanks!
