### ISSUE TITLE
After closing the app location keeps on being received but HTTP Service times out

### ISSUE THREAD

**Issue by samplez** [transistorsoft/cordova-background-geolocation-lt#601]
## Your Environment
* Plugin version: 2.9.1
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung Galaxy S7
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config
debug: true
distanceFilter: 10
extras: {deviceToken: "xyz..."}
headers: {Authorization: "Bearer abc..."}
httpRootProperty: "."
locationTemplate: "{"latitude":<%= latitude %>, "longitude":<%= longitude %>}"
maxRecordsToPersist: 10
startOnBoot: true
stopOnTerminate: false
url: "https://example.org/api/consumer/location"

## Expected Behavior
The location should keep on being posted via HTTP after the app has been closed.

## Actual Behavior
The HTTP Service starts timing out after the app has been closed (backend keeps on running). HTTP Service resumes successful HTTP posts after the app is running again.

## Steps to Reproduce

1. Initiate the plugin and configure automatic location HTTP posting. -> OK
2. Notice (for example via debug sounds) that the location is being received. -> OK
3. Check your backend that the location is being submitted. -> OK
4. Turn off the app. -> OK
5. Notice (for example via debug sounds) that the location keeps on being received. -> OK
6. Check your backend - the location does not get posted anymore -> WRONG

## Context
This happens each time the app gets closed. 

## Debug logs
See that the location was posted successfully on 16:24:04.510
After that the app was closed and HTTP posts result in timeout, although the backend keeps on running.

╔═════════════════════════════════════════════
║ LocationService: location
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 52,366784,4,928003 acc=6 et=+31m4s249ms alt=30.95287698293448 vel=0.6975132 bear=7.0 {Bundle[{battery_level=0.73, uuid=b0533fcd-5f00-424b-b871-27e682f60164, is_charging=false, verticalAccuracy=12.0}]}], age: 82ms

02-06 16:24:04.106 DEBUG [TSLocationManager onLocationResult] 
╔═════════════════════════════════════════════
║ Process LocationResult
╠═════════════════════════════════════════════

02-06 16:24:04.121 DEBUG [TSLocationManager calculateMedianAccuracy] 16.0
02-06 16:24:04.146 DEBUG [TSLocationManager incrementOdometer] 8713.137
02-06 16:24:04.184 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: b0533fcd-5f00-424b-b871-27e682f60164
02-06 16:24:04.202 DEBUG [SQLiteLocationDAO shrink] 
  ℹ️  SHRINK: 10
02-06 16:24:04.215 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

02-06 16:24:04.241 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
02-06 16:24:04.252 INFO [HttpService createRequest] 
  🔵  HTTP POST: b0533fcd-5f00-424b-b871-27e682f60164
02-06 16:24:04.510 INFO [HttpService$a onResponse] 
  🔵  Response: 200
02-06 16:24:04.537 DEBUG [SQLiteLocationDAO destroy] 
  ✅  DESTROY: b0533fcd-5f00-424b-b871-27e682f60164
02-06 16:24:10.718 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (95%)
02-06 16:24:10.756 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:24:21.010 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (51%)
02-06 16:24:21.041 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:24:22.145 INFO [LocationService onLocation] 
  ℹ️  Location availability: false
02-06 16:24:23.241 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
02-06 16:24:28.370 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (55%)
02-06 16:24:28.395 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:24:36.240 INFO [LocationService onLocation] 
  ℹ️  Location availability: false
02-06 16:24:37.973 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 52,367052,4,927563 acc=20 et=+31m37s946ms alt=49.20000076293945 {Bundle[{battery_level=0.73, uuid=9213b45d-f4da-4fee-bd2c-8b5c7fc7991f, is_charging=false, verticalAccuracy=2.0}]}], age: 228ms

02-06 16:24:38.006 DEBUG [TSLocationManager onLocationResult] 
╔═════════════════════════════════════════════
║ Process LocationResult
╠═════════════════════════════════════════════

02-06 16:24:38.032 DEBUG [TSLocationManager calculateMedianAccuracy] 16.0
02-06 16:24:38.045 DEBUG [TSLocationManager incrementOdometer] 8755.455
02-06 16:24:38.073 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
02-06 16:24:38.110 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 9213b45d-f4da-4fee-bd2c-8b5c7fc7991f
02-06 16:24:38.130 DEBUG [SQLiteLocationDAO shrink] 
  ℹ️  SHRINK: 10
02-06 16:24:38.143 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

02-06 16:24:38.164 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
02-06 16:24:38.173 INFO [HttpService createRequest] 
  🔵  HTTP POST: 9213b45d-f4da-4fee-bd2c-8b5c7fc7991f
02-06 16:24:38.375 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-06 16:24:38.411 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:24:38.421 INFO [BackgroundGeolocationService onActivityRecognitionResult] 
  🔵  Stop-timeout timer initiated (5 min)...
02-06 16:24:38.425 INFO [HttpService$a onResponse] 
  🔵  Response: 200
02-06 16:24:38.430 INFO [BackgroundGeolocationService h] 
  🔵  Begin stop timer
02-06 16:24:38.446 DEBUG [SQLiteLocationDAO destroy] 
  ✅  DESTROY: 9213b45d-f4da-4fee-bd2c-8b5c7fc7991f
02-06 16:24:48.609 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-06 16:24:48.632 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:24:48.644 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
02-06 16:24:58.650 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-06 16:24:58.758 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:24:58.833 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
02-06 16:25:08.835 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-06 16:25:08.857 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:25:08.870 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
02-06 16:25:19.058 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-06 16:25:19.080 DEBUG [BackgroundGeolocation isMainActivityActive] YES
02-06 16:25:19.096 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
02-06 16:25:27.566 INFO [BackgroundGeolocation onActivityDestroy] 
╔═════════════════════════════════════════════
║ MainActivity was destroyed
╠═════════════════════════════════════════════
╟─ stopOnTerminate: false
╟─ enabled: true

02-06 16:25:27.590 INFO [TSLocationManager stopWatchPosition] 
  🔴  watchPosition: OFF
02-06 16:25:27.602 DEBUG [BackgroundGeolocation e] 
  🔴  Cleared callbacks
02-06 16:25:27.648 DEBUG [BackgroundGeolocationService onActivityDestroyed] 
╔═════════════════════════════════════════════
║ BackgroundGeolocationService Rx ActivityDestroyed
╠═════════════════════════════════════════════

02-06 16:25:27.670 DEBUG [BackgroundGeolocationService i] 
02-06 16:25:27.706 INFO [BackgroundGeolocationService k] 
  🔴  Stop heartbeat
02-06 16:25:29.649 INFO [Sensors print] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="K6DS3TR Acceleration Sensor", vendor="STM", version=1, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.25, minDelay=2000}
╟─ ✅  GYROSCOPE: {Sensor name="K6DS3TR Gyroscope Sensor", vendor="STM", version=2, type=4, maxRange=34.906586, resolution=0.0012217305, power=6.1, minDelay=2000}
╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetic Sensor", vendor="Yamaha Corporation", version=1, type=2, maxRange=1200.0, resolution=0.1, power=6.0, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="SAMSUNG Significant Motion Sensor", vendor="Samsung Inc.", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=0}
╚═════════════════════════════════════════════
02-06 16:25:29.671 INFO [BackgroundGeolocation &lt;init&gt;] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation adapter
╠═════════════════════════════════════════════

02-06 16:25:29.698 INFO [BackgroundGeolocation &lt;init&gt;] 
  ✅  Google Play Services: connected (version code:11220000)
02-06 16:25:29.722 DEBUG [SQLiteLocationDAO dbh] 
  ✅  Opened database
02-06 16:25:29.733 DEBUG [SQLiteLocationDAO prune] 
  ℹ️  PRUNE -1 days
02-06 16:25:29.770 DEBUG [GeofenceDAO dbh] 
  ✅  Opened database
02-06 16:25:29.841 INFO [BackgroundGeolocation &lt;init&gt;] 
  🔵  Connecting to GooglePlayServices...
02-06 16:25:29.862 INFO [BackgroundGeolocationService onStartCommand] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Service started
╠═════════════════════════════════════════════

02-06 16:25:29.883 INFO [BackgroundGeolocationService b] 
  🎾  Start activity updates: 10000
02-06 16:25:29.914 INFO [BackgroundGeolocationService a] 
  🔵  setPace: null → true
02-06 16:25:29.933 INFO [BackgroundGeolocationService k] 
  🔴  Stop heartbeat
02-06 16:25:29.985 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-06 16:25:30.005 DEBUG [BackgroundGeolocation isMainActivityActive] NO
02-06 16:25:30.028 INFO [BackgroundGeolocationService onActivityRecognitionResult] 
  🔵  Stop-timeout timer initiated (5 min)...
02-06 16:25:30.039 INFO [BackgroundGeolocationService h] 
  🔵  Begin stop timer
02-06 16:25:30.107 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location:1001
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 52,367048,4,927577 acc=14 et=+32m30s251ms alt=49.20000076293945 {Bundle[{battery_level=0.73, uuid=10f791d2-42a6-4048-8a4c-1ce0a2a950f2, requestId=1001, is_charging=false, verticalAccuracy=2.0}]}], age: 54ms

02-06 16:25:30.168 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: true
02-06 16:25:30.183 DEBUG [TSLocationManager calculateMedianAccuracy] 14.099
02-06 16:25:30.196 DEBUG [TSLocationManager incrementOdometer] 8755.455
02-06 16:25:30.464 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
02-06 16:25:30.509 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-06 16:25:30.535 DEBUG [BackgroundGeolocation isMainActivityActive] NO
02-06 16:25:30.578 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
02-06 16:25:30.662 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 10f791d2-42a6-4048-8a4c-1ce0a2a950f2
02-06 16:25:30.677 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
02-06 16:25:30.697 DEBUG [SQLiteLocationDAO shrink] 
  ℹ️  SHRINK: 10
02-06 16:25:30.757 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

02-06 16:25:30.806 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 52,367048,4,927577 acc=14 et=+32m30s838ms alt=49.20000076293945 {Bundle[{battery_level=0.73, uuid=08598cc1-65ad-4263-b6fb-3812a6429790, is_charging=false, verticalAccuracy=2.0}]}], age: 158ms

02-06 16:25:30.866 DEBUG [TSLocationManager onLocationResult] 
╔═════════════════════════════════════════════
║ Process LocationResult
╠═════════════════════════════════════════════

02-06 16:25:30.871 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
02-06 16:25:30.894 DEBUG [TSLocationManager onLocationResult] 
  ℹ️  IGNORED: same as last location
02-06 16:25:30.909 INFO [HttpService createRequest] 
  🔵  HTTP POST: 10f791d2-42a6-4048-8a4c-1ce0a2a950f2
02-06 16:25:40.992 WARN [HttpService$a onFailure] 
  ⚠️  Response: 0, connect timed out
02-06 16:25:41.050 DEBUG [SQLiteLocationDAO unlock] 
  ✅  UNLOCKED: 10f791d2-42a6-4048-8a4c-1ce0a2a950f2
02-06 16:25:42.512 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
02-06 16:25:42.676 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (92%)
02-06 16:25:42.700 DEBUG [BackgroundGeolocation isMainActivityActive] NO
02-06 16:25:42.749 DEBUG [BackgroundGeolocationService i] 
02-06 16:25:52.957 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (95%)
02-06 16:25:52.988 DEBUG [BackgroundGeolocation isMainActivityActive] NO
02-06 16:26:03.014 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (92%)
02-06 16:26:03.061 DEBUG [BackgroundGeolocation isMainActivityActive] NO
02-06 16:26:14.119 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (93%)
02-06 16:26:14.147 DEBUG [BackgroundGeolocation isMainActivityActive] NO
02-06 16:26:14.362 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 52,366605,4,927629 acc=12 et=+33m14s515ms alt=43.37310914326096 vel=0.0 {Bundle[{battery_level=0.73, uuid=1939b512-a936-4442-ad92-91eba06a25e0, is_charging=false, verticalAccuracy=24.0}]}], age: 2ms

02-06 16:26:14.407 DEBUG [TSLocationManager onLocationResult] 
╔═════════════════════════════════════════════
║ Process LocationResult
╠═════════════════════════════════════════════

02-06 16:26:14.424 DEBUG [TSLocationManager calculateMedianAccuracy] 13.0494995
02-06 16:26:14.444 DEBUG [TSLocationManager incrementOdometer] 8804.958
02-06 16:26:14.486 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 1939b512-a936-4442-ad92-91eba06a25e0
02-06 16:26:14.505 DEBUG [SQLiteLocationDAO shrink] 
  ℹ️  SHRINK: 10
02-06 16:26:14.516 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

02-06 16:26:14.532 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
02-06 16:26:14.542 INFO [HttpService createRequest] 
  🔵  HTTP POST: 10f791d2-42a6-4048-8a4c-1ce0a2a950f2
02-06 16:26:20.361 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] on_foot (97%)
02-06 16:26:20.383 DEBUG [BackgroundGeolocation isMainActivityActive] NO
02-06 16:26:24.573 WARN [HttpService$a onFailure] 
  ⚠️  Response: 0, connect timed out
02-06 16:26:24.635 DEBUG [SQLiteLocationDAO unlock] 
  ✅  UNLOCKED: 10f791d2-42a6-4048-8a4c-1ce0a2a950f2
02-06 16:26:25.088 DEBUG [LocationService onLocation]

**Comment by christocracy** [comment]
Yes, you terminated the app while the plugin had initiated a location request.   This request will timeout and location-services will turn off.

**Comment by samplez** [comment]
Yes, isn't that the idea that the plugin keeps on working after the app is terminated? Note that in the configuration stopOnTerminate is false.

Also according to your documentation (https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode):
"BackgroundGeolocation Android "Headless" mode is the state where your app has been terminated with the plugin configured for stopOnTerminate: false. (...) Only the plugin's native Android service continues to run, tracking and posting locations to your server through your configured #url."

**Comment by christocracy** [comment]
I misunderstood your question.  I assumed you had `stopOnTerminate: true`.

These log warnings are from the HTTP service.  You have no HTTP connection to the server.
```
⚠️ Response: 0, connect timed out
```

**Comment by samplez** [comment]
Yup, I double checked that - the server was up and my phone was connected to internet. This happens each time I terminate the app, so doesn't look like problem with internet or server - rather a problem of the plugin to initiate the connection. Can you verify that?

**Comment by christocracy** [comment]
The plugin uses a well-known 3rd-party lib [OkHttp](http://square.github.io/okhttp/) for its HTTP Service.  If OkHttp cannot connect, you have an issue on your device.

**Comment by samplez** [comment]
Dear Chris,

Does your plugin not support all devices? My Samsung Galaxy 7 is quite a
common one.

Maciej

Op 7 feb. 2018 16:06 schreef "Chris Scott" <notifications@github.com>:

**Comment by christocracy** [comment]
I test on a wide range of devices from Nexus 4 @4.4.4 to Pixel @8.1.0.  I regularly field-test with an S7.
