### ISSUE TITLE
Popup that warns the app is in eval mode

### ISSUE THREAD

**Issue by mvr-devs** [transistorsoft/cordova-background-geolocation-lt#603]
## Your Environment
* Plugin version: 
* Platform: Android
* OS version: Windows  7
* Device manufacturer / model:   Samsung S5
* Cordova version (`cordova -v`):  7.0.1
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 6.3.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0

* Plugin config
```
<plugin name="cordova-background-geolocation" spec="git+https://github.com/transistorsoft/cordova-background-geolocation.git">
        <variable name="LICENSE" value="8c6560fe04c4e19b07d71---The Rest of My Licsense---1c70759e32e311834c81e49" />
        <variable name="GOOGLE_API_VERSION" value="11.6.0" />
        <variable name="APPCOMPAT_VERSION" value="27.0.0" />
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Always use is required for background location tracking" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>
```

## Expected Behavior

No Popup

## Actual Behavior

Pops up after launch and states:

License Validation Failure
BackgroundGeolocation is running in evaluation mode

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Customer should post in private repo.  [See Wiki](https://github.com/transistorsoft/cordova-background-geolocation/wiki/License-Validation-Failure)

**Comment by mvr-devs** [comment]
oh crap sorry
