### ISSUE TITLE
OnGeofence() event not generated for Android 7

### ISSUE THREAD

**Issue by pmalhotra1** [transistorsoft/cordova-background-geolocation-lt#605]
## Your Environment
* Plugin version: "cordova-background-geolocation-lt": "2.9.1",
* Platform: Android
* OS version: 7
* Device manufacturer / model: Samsung
* Cordova version (`cordova -v`): 7
* Cordova platform version (`cordova platform ls`):7.1.0
* Plugin config

## Expected Behavior

OnGeofence() event should occur when fences are configured

## Actual Behavior

OnGeofence event is not getting generated

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

02-16 12:20:27.770 9665-32140/? I/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO persist] 
                                                       ✅  INSERT: 9ac6cca3-f2f8-46a8-8d46-e351de29ac1b
02-16 12:20:27.786 9665-32140/? D/TSLocationManager: [c.t.l.http.HttpService flush] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ HTTP Service
                                                     ╠═════════════════════════════════════════════
02-16 12:20:27.804 9665-32140/? D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO first] 
                                                       ✅  Locked 1 records
02-16 12:20:27.812 9665-32140/? I/TSLocationManager: [c.t.l.http.HttpService createRequest] 
                                                       🔵  HTTP POST: 9ac6cca3-f2f8-46a8-8d46-e351de29ac1b
02-16 12:20:27.829 9665-31386/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 12:20:27.844 9665-31386/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
02-16 12:20:27.876 9665-32149/? I/TSLocationManager: [c.t.l.http.HttpService$a onResponse] 
                                                       🔵  Response: 200
02-16 12:20:27.886 9665-32149/? D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO destroy] 
                                                       ✅  DESTROY: 9ac6cca3-f2f8-46a8-8d46-e351de29ac1b
02-16 12:20:32.007 708-708/? I/TSLocationManager: - onResume
02-16 12:20:33.083 708-947/? D/TSLocationManager: $ configure()
02-16 12:20:33.088 708-32336/? I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                    ╔═════════════════════════════════════════════
                                                    ║ BackgroundGeolocation Settings
                                                    ╠═════════════════════════════════════════════
                                                    {
                                                      "isMoving": false,
                                                      "enabled": false,
                                                      "odometer": 56380.496,
                                                      "schedulerEnabled": false,
                                                      "trackingMode": "geofence",
                                                      "distanceFilter": 10,
                                                      "desiredAccuracy": 0,
                                                      "desiredOdometerAccuracy": 100,
                                                      "locationUpdateInterval": 900000,
                                                      "fastestLocationUpdateInterval": 10000,
                                                      "locationTimeout": 60,
                                                      "deferTime": 0,
                                                      "disableElasticity": false,
                                                      "elasticityMultiplier": 1,
                                                      "activityRecognitionInterval": 1000,
                                                      "minimumActivityRecognitionConfidence": 75,
                                                      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                      "disableStopDetection": false,
                                                      "stationaryRadius": 25,
                                                      "stopTimeout": 5,
                                                      "stopOnStationary": false,
                                                      "url": "",
                                                      "method": "POST",
                                                      "autoSync": true,
                                                      "autoSyncThreshold": 0,
                                                      "batchSync": false,
                                                      "maxBatchSize": -1,
                                                      "params": {},
                                                      "headers": {},
                                                      "extras": {},
                                                      "httpRootProperty": "location",
                                                      "locationTemplate": "",
                                                      "geofenceTemplate": "",
                                                      "persist": true,
                                                      "maxDaysToPersist": 1,
                                                      "maxRecordsToPersist": -1,
                                                      "locationsOrderDirection": "ASC",
                                                      "httpTimeout": 60000,
                                                      "geofenceProximityRadius": 3000000,
                                                      "geofenceInitialTriggerEntry": true,
                                                      "stopOnTerminate": true,
                                                      "startOnBoot": true,
                                                      "heartbeatInterval": 900,
                                                      "foregroundService": true,
                                                      "notificationPriority": 0,
                                                      "notificationTitle": "",
                                                      "notificationText": "Location Service activated",
                                                      "notificationColor": "",
                                                      "notificationIcon": "",
                                                      "notificationSmallIcon": "",
                                                      "notificationLargeIcon": "",
                                                      "forceReloadOnLocationChange": false,
                                                      "forceReloadOnMotionChange": false,
                                                      "forceReloadOnGeofence": false,
                                                      "forceReloadOnBoot": false,
                                                      "forceReloadOnHeartbeat": false,
                                                      "forceReloadOnSchedule": false,
                                                      "stopAfterElapsedMinutes": 0,
                                                      "schedule": [],
                                                      "configureUrl": "",
                                                      "configureInterval": -1,
                                                      "debug": false,
                                                      "logLevel": 5,
                                                      "logMaxDays": 3
                                                    }╚═════════════════════════════════════════════
02-16 12:20:33.123 708-947/? D/TSLocationManager: $ removeGeofences()
02-16 12:20:33.129 708-32336/? I/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO destroyAll] ✅  
02-16 12:20:33.138 708-947/? D/TSLocationManager: $ setConfig()
02-16 12:20:33.140 708-32336/? I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                    ╔═════════════════════════════════════════════
                                                    ║ BackgroundGeolocation Settings
                                                    ╠═════════════════════════════════════════════
                                                    {
                                                      "isMoving": false,
                                                      "enabled": false,
                                                      "odometer": 56380.496,
                                                      "schedulerEnabled": false,
                                                      "trackingMode": "geofence",
                                                      "distanceFilter": 10,
                                                      "desiredAccuracy": 0,
                                                      "desiredOdometerAccuracy": 100,
                                                      "locationUpdateInterval": 900000,
                                                      "fastestLocationUpdateInterval": 10000,
                                                      "locationTimeout": 60,
                                                      "deferTime": 0,
                                                      "disableElasticity": false,
                                                      "elasticityMultiplier": 1,
                                                      "activityRecognitionInterval": 1000,
                                                      "minimumActivityRecognitionConfidence": 75,
                                                      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                      "disableStopDetection": false,
                                                      "stationaryRadius": 25,
                                                      "stopTimeout": 5,
                                                      "stopOnStationary": false,
                                                      "url": "",
                                                      "method": "POST",
                                                      "autoSync": true,
                                                      "autoSyncThreshold": 0,
                                                      "batchSync": false,
                                                      "maxBatchSize": -1,
                                                      "params": {},
                                                      "headers": {},
                                                      "extras": {},
                                                      "httpRootProperty": "location",
                                                      "locationTemplate": "",
                                                      "geofenceTemplate": "",
                                                      "persist": true,
                                                      "maxDaysToPersist": 1,
                                                      "maxRecordsToPersist": -1,
                                                      "locationsOrderDirection": "ASC",
                                                      "httpTimeout": 60000,
                                                      "geofenceProximityRadius": 3000000,
                                                      "geofenceInitialTriggerEntry": true,
                                                      "stopOnTerminate": true,
                                                      "startOnBoot": true,
                                                      "heartbeatInterval": 900,
                                                      "foregroundService": true,
                                                      "notificationPriority": 0,
                                                      "notificationTitle": "",
                                                      "notificationText": "Location Service activated",
                                                      "notificationColor": "",
                                                      "notificationIcon": "",
                                                      "notificationSmallIcon": "",
                                                      "notificationLargeIcon": "",
                                                      "forceReloadOnLocationChange": false,
                                                      "forceReloadOnMotionChange": false,
                                                      "forceReloadOnGeofence": false,
                                                      "forceReloadOnBoot": false,
                                                      "forceReloadOnHeartbeat": false,
                                                      "forceReloadOnSchedule": false,
                                                      "stopAfterElapsedMinutes": 0,
                                                      "schedule": [],
                                                      "configureUrl": "",
                                                      "configureInterval": -1,
                                                      "debug": false,
                                                      "logLevel": 5,
                                                      "logMaxDays": 3
                                                    }╚═════════════════════════════════════════════
02-16 12:20:33.146 708-32336/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation$p run] 
                                                      ✅  Updated config
02-16 12:20:33.148 708-947/? D/TSLocationManager: $ addGeofences()
02-16 12:20:33.153 708-420/? I/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
                                                    ✅  0
02-16 12:20:33.165 708-420/? I/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
                                                    ✅  1
02-16 12:20:33.175 708-947/? D/TSLocationManager: $ startGeofences()
02-16 12:20:33.177 708-32336/? I/TSLocationManager: - Enable: false → true, trackingMode: geofence
02-16 12:20:33.185 708-708/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService onStartCommand] 
                                                  ╔═════════════════════════════════════════════
                                                  ║ BackgroundGeolocation Service started
                                                  ╠═════════════════════════════════════════════
02-16 12:20:33.190 708-708/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService d] 
                                                    ✅  Started in foreground
02-16 12:20:33.202 708-708/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService b] 
                                                    🎾  Start activity updates: 1000
02-16 12:20:33.208 708-708/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService a] 
                                                    🔵  setPace: null → false
02-16 12:20:33.214 708-708/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService k] 
                                                    🔴  Stop heartbeat
02-16 12:20:33.220 708-708/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService a] 
                                                    🎾  Start heartbeat (900)
02-16 12:20:33.251 708-31461/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 12:20:33.260 708-31461/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
02-16 12:20:33.266 9665-31386/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 12:20:33.273 9665-31386/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
02-16 12:20:33.338 708-425/? I/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                    ℹ️  Location availability: true
02-16 12:20:33.907 708-435/? D/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                  ╔═════════════════════════════════════════════
                                                  ║ LocationService: location:1041
                                                  ╠═════════════════════════════════════════════
                                                  ╟─ 📍  Location[fused 33.905954,-84.459185 acc=7 et=+2d1h25m22s224ms alt=110.0 vel=0.0 bear=197.0 mock {Bundle[{mockLocation=true, battery_level=0.47, uuid=2b25ec55-2c80-419b-a797-20f990b976ae, requestId=1041, is_charging=true, verticalAccuracy=14.0}]}], age: 60ms
02-16 12:20:33.916 708-435/? I/TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
                                                    🔵  Acquired motionchange position, isMoving: false
02-16 12:20:33.922 708-435/? D/TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 4.9
02-16 12:20:33.938 708-435/? D/TSLocationManager: [c.t.locationmanager.geofence.a a] 
                                                  ╔═════════════════════════════════════════════
                                                  ║ TSGeofenceManager found 2/2 within 3000000 meters
                                                  ╠═════════════════════════════════════════════
                                                  ╟─ 🎾  0
                                                  ╟─ 🎾  1
                                                  ╚═════════════════════════════════════════════
02-16 12:20:33.982 708-31461/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 12:20:33.987 708-31461/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
02-16 12:20:33.999 9665-31386/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 12:20:34.005 9665-31386/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
02-16 12:20:47.395 9665-633/? D/TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️

**Comment by christocracy** [comment]
What is the radius of your geofences?

**Comment by pmalhotra1** [comment]
i have 3 fences , having radius 2 miles, 1 mile and 1 mile.
I started inside the first fence with 2 miles radius.

**Comment by pmalhotra1** [comment]
geofence works fine on Android 5.1.1.
Below are the logs showing the ENTER event 👍 
02-16 13:25:08.670 5157-5157/? I/TSLocationManager: - onResume
02-16 13:25:49.390 5157-5157/? I/TSLocationManager: - onPause
02-16 13:26:13.538 5157-5157/? I/TSLocationManager: - onResume
02-16 13:28:05.508 5157-5157/? I/TSLocationManager: - onPause
02-16 13:28:22.278 5157-5157/? I/TSLocationManager: [c.t.l.a.BackgroundGeolocation$n onReceive] 
                                                    ╔═════════════════════════════════════════════
                                                    ║ Location-provider change: true
                                                    ╠═════════════════════════════════════════════
                                                    ╟─ GPS: true
                                                    ╟─ Network: true
02-16 13:28:22.378 5157-5157/? I/TSLocationManager: [c.t.l.a.BackgroundGeolocation$n onReceive] 
                                                    ╔═════════════════════════════════════════════
                                                    ║ Location-provider change: true
                                                    ╠═════════════════════════════════════════════
                                                    ╟─ GPS: true
                                                    ╟─ Network: true
02-16 13:28:29.698 5157-5157/? I/TSLocationManager: - onResume
02-16 13:28:32.278 5157-5157/? I/TSLocationManager: - onPause
02-16 13:28:32.558 5157-5157/? I/TSLocationManager: - onResume
02-16 13:28:34.108 5157-5223/? D/TSLocationManager: $ configure()
02-16 13:28:34.158 5157-14100/? I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ BackgroundGeolocation Settings
                                                     ╠═════════════════════════════════════════════
                                                     {
                                                       "isMoving": false,
                                                       "enabled": false,
                                                       "odometer": 17607.35,
                                                       "schedulerEnabled": false,
                                                       "trackingMode": "geofence",
                                                       "distanceFilter": 10,
                                                       "desiredAccuracy": 0,
                                                       "desiredOdometerAccuracy": 100,
                                                       "locationUpdateInterval": 900000,
                                                       "fastestLocationUpdateInterval": 10000,
                                                       "locationTimeout": 60,
                                                       "deferTime": 0,
                                                       "disableElasticity": false,
                                                       "elasticityMultiplier": 1,
                                                       "activityRecognitionInterval": 1000,
                                                       "minimumActivityRecognitionConfidence": 75,
                                                       "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                       "disableStopDetection": false,
                                                       "stationaryRadius": 25,
                                                       "stopTimeout": 5,
                                                       "stopOnStationary": false,
                                                       "url": "",
                                                       "method": "POST",
                                                       "autoSync": true,
                                                       "autoSyncThreshold": 0,
                                                       "batchSync": false,
                                                       "maxBatchSize": -1,
                                                       "params": {},
                                                       "headers": {},
                                                       "extras": {},
                                                       "httpRootProperty": "location",
                                                       "locationTemplate": "",
                                                       "geofenceTemplate": "",
                                                       "persist": true,
                                                       "maxDaysToPersist": 1,
                                                       "maxRecordsToPersist": -1,
                                                       "locationsOrderDirection": "ASC",
                                                       "httpTimeout": 60000,
                                                       "geofenceProximityRadius": 3000000,
                                                       "geofenceInitialTriggerEntry": true,
                                                       "stopOnTerminate": true,
                                                       "startOnBoot": true,
                                                       "heartbeatInterval": 900,
                                                       "foregroundService": true,
                                                       "notificationPriority": 0,
                                                       "notificationTitle": "",
                                                       "notificationText": "Location Service activated",
                                                       "notificationColor": "",
                                                       "notificationIcon": "",
                                                       "notificationSmallIcon": "",
                                                       "notificationLargeIcon": "",
                                                       "forceReloadOnLocationChange": false,
                                                       "forceReloadOnMotionChange": false,
                                                       "forceReloadOnGeofence": false,
                                                       "forceReloadOnBoot": false,
                                                       "forceReloadOnHeartbeat": false,
                                                       "forceReloadOnSchedule": false,
                                                       "stopAfterElapsedMinutes": 0,
                                                       "schedule": [],
                                                       "configureUrl": "",
                                                       "configureInterval": -1,
                                                       "debug": false,
                                                       "logLevel": 5,
                                                       "logMaxDays": 3
                                                     }╚═════════════════════════════════════════════
02-16 13:28:34.238 5157-5223/? D/TSLocationManager: $ setConfig()
02-16 13:28:34.238 5157-5223/? D/TSLocationManager: $ removeGeofences()
02-16 13:28:34.248 5157-14100/? I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ BackgroundGeolocation Settings
                                                     ╠═════════════════════════════════════════════
                                                     {
                                                       "isMoving": false,
                                                       "enabled": false,
                                                       "odometer": 17607.35,
                                                       "schedulerEnabled": false,
                                                       "trackingMode": "geofence",
                                                       "distanceFilter": 10,
                                                       "desiredAccuracy": 0,
                                                       "desiredOdometerAccuracy": 100,
                                                       "locationUpdateInterval": 900000,
                                                       "fastestLocationUpdateInterval": 10000,
                                                       "locationTimeout": 60,
                                                       "deferTime": 0,
                                                       "disableElasticity": false,
                                                       "elasticityMultiplier": 1,
                                                       "activityRecognitionInterval": 1000,
                                                       "minimumActivityRecognitionConfidence": 75,
                                                       "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                       "disableStopDetection": false,
                                                       "stationaryRadius": 25,
                                                       "stopTimeout": 5,
                                                       "stopOnStationary": false,
                                                       "url": "",
                                                       "method": "POST",
                                                       "autoSync": true,
                                                       "autoSyncThreshold": 0,
                                                       "batchSync": false,
                                                       "maxBatchSize": -1,
                                                       "params": {},
                                                       "headers": {},
                                                       "extras": {},
                                                       "httpRootProperty": "location",
                                                       "locationTemplate": "",
                                                       "geofenceTemplate": "",
                                                       "persist": true,
                                                       "maxDaysToPersist": 1,
                                                       "maxRecordsToPersist": -1,
                                                       "locationsOrderDirection": "ASC",
                                                       "httpTimeout": 60000,
                                                       "geofenceProximityRadius": 3000000,
                                                       "geofenceInitialTriggerEntry": true,
                                                       "stopOnTerminate": true,
                                                       "startOnBoot": true,
                                                       "heartbeatInterval": 900,
                                                       "foregroundService": true,
                                                       "notificationPriority": 0,
                                                       "notificationTitle": "",
                                                       "notificationText": "Location Service activated",
                                                       "notificationColor": "",
                                                       "notificationIcon": "",
                                                       "notificationSmallIcon": "",
                                                       "notificationLargeIcon": "",
                                                       "forceReloadOnLocationChange": false,
                                                       "forceReloadOnMotionChange": false,
                                                       "forceReloadOnGeofence": false,
                                                       "forceReloadOnBoot": false,
                                                       "forceReloadOnHeartbeat": false,
                                                       "forceReloadOnSchedule": false,
                                                       "stopAfterElapsedMinutes": 0,
                                                       "schedule": [],
                                                       "configureUrl": "",
                                                       "configureInterval": -1,
                                                       "debug": false,
                                                       "logLevel": 5,
                                                       "logMaxDays": 3
                                                     }╚═════════════════════════════════════════════
02-16 13:28:34.258 5157-14100/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation$p run] 
                                                       ✅  Updated config
02-16 13:28:34.268 5157-14104/? I/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO destroyAll] ✅  
02-16 13:28:34.318 5157-5223/? D/TSLocationManager: $ addGeofences()
02-16 13:28:34.338 5157-5220/? I/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
                                                      ✅  0
02-16 13:28:34.358 5157-5220/? I/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
                                                      ✅  1
02-16 13:28:34.388 5157-5223/? D/TSLocationManager: $ setConfig()
02-16 13:28:34.388 5157-14104/? I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ BackgroundGeolocation Settings
                                                     ╠═════════════════════════════════════════════
                                                     {
                                                       "isMoving": false,
                                                       "enabled": false,
                                                       "odometer": 17607.35,
                                                       "schedulerEnabled": false,
                                                       "trackingMode": "geofence",
                                                       "distanceFilter": 10,
                                                       "desiredAccuracy": 0,
                                                       "desiredOdometerAccuracy": 100,
                                                       "locationUpdateInterval": 900000,
                                                       "fastestLocationUpdateInterval": 10000,
                                                       "locationTimeout": 60,
                                                       "deferTime": 0,
                                                       "disableElasticity": false,
                                                       "elasticityMultiplier": 1,
                                                       "activityRecognitionInterval": 1000,
                                                       "minimumActivityRecognitionConfidence": 75,
                                                       "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                       "disableStopDetection": false,
                                                       "stationaryRadius": 25,
                                                       "stopTimeout": 5,
                                                       "stopOnStationary": false,
                                                       "url": "",
                                                       "method": "POST",
                                                       "autoSync": true,
                                                       "autoSyncThreshold": 0,
                                                       "batchSync": false,
                                                       "maxBatchSize": -1,
                                                       "params": {},
                                                       "headers": {},
                                                       "extras": {},
                                                       "httpRootProperty": "location",
                                                       "locationTemplate": "",
                                                       "geofenceTemplate": "",
                                                       "persist": true,
                                                       "maxDaysToPersist": 1,
                                                       "maxRecordsToPersist": -1,
                                                       "locationsOrderDirection": "ASC",
                                                       "httpTimeout": 60000,
                                                       "geofenceProximityRadius": 3000000,
                                                       "geofenceInitialTriggerEntry": true,
                                                       "stopOnTerminate": true,
                                                       "startOnBoot": true,
                                                       "heartbeatInterval": 900,
                                                       "foregroundService": true,
                                                       "notificationPriority": 0,
                                                       "notificationTitle": "",
                                                       "notificationText": "Location Service activated",
                                                       "notificationColor": "",
                                                       "notificationIcon": "",
                                                       "notificationSmallIcon": "",
                                                       "notificationLargeIcon": "",
                                                       "forceReloadOnLocationChange": false,
                                                       "forceReloadOnMotionChange": false,
                                                       "forceReloadOnGeofence": false,
                                                       "forceReloadOnBoot": false,
                                                       "forceReloadOnHeartbeat": false,
                                                       "forceReloadOnSchedule": false,
                                                       "stopAfterElapsedMinutes": 0,
                                                       "schedule": [],
                                                       "configureUrl": "",
                                                       "configureInterval": -1,
                                                       "debug": false,
                                                       "logLevel": 5,
                                                       "logMaxDays": 3
                                                     }╚═════════════════════════════════════════════
02-16 13:28:34.398 5157-5223/? D/TSLocationManager: $ startGeofences()
02-16 13:28:34.408 5157-14104/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation$p run] 
                                                       ✅  Updated config
02-16 13:28:34.418 5157-14100/? I/TSLocationManager: - Enable: false → true, trackingMode: geofence
02-16 13:28:34.438 5157-5157/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService onStartCommand] 
                                                    ╔═════════════════════════════════════════════
                                                    ║ BackgroundGeolocation Service started
                                                    ╠═════════════════════════════════════════════
02-16 13:28:34.448 5157-5157/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService d] 
                                                      ✅  Started in foreground
02-16 13:28:34.468 5157-5157/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService b] 
                                                      ��  Start activity updates: 1000
02-16 13:28:34.518 5157-5157/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService a] 
                                                      ��  setPace: null → false
02-16 13:28:34.538 5157-5157/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService k] 
                                                      ��  Stop heartbeat
02-16 13:28:34.558 5157-5157/? I/TSLocationManager: [c.t.l.BackgroundGeolocationService a] 
                                                      ��  Start heartbeat (900)
02-16 13:28:34.658 5157-14108/? D/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ LocationService: location:1031
                                                     ╠═════════════════════════════════════════════
                                                     ╟─ ��  Location[fused 33.905695,-84.458850 acc=14 et=+1d22h13m8s249ms alt=123.99140876 vel=0.0 bear=214.0 mock {Bundle[{mockLocation=true, battery_level=0.84, uuid=957c8b6f-4e6c-4ff3-bf3b-3960f7ae868c, requestId=1031, is_charging=true, verticalAccuracy=28.0}]}], age: 27ms
02-16 13:28:34.688 5157-14108/? I/TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
                                                       ��  Acquired motionchange position, isMoving: false
02-16 13:28:34.698 5157-14108/? D/TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 26.832815
02-16 13:28:34.738 5157-14108/? D/TSLocationManager: [c.t.locationmanager.geofence.a a] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ TSGeofenceManager found 2/2 within 3000000 meters
                                                     ╠═════════════════════════════════════════════
                                                     ╟─ ��  0
                                                     ╟─ ��  1
                                                     ╚═════════════════════════════════════════════
02-16 13:28:34.818 5157-14108/? D/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ LocationService: location:1031
                                                     ╠═════════════════════════════════════════════
                                                     ╟─ ��  Location[fused 33.905695,-84.458850 acc=8 et=+1d22h13m8s287ms alt=123.99140876 vel=0.0 bear=83.0 mock {Bundle[{mockLocation=true, battery_level=0.84, uuid=19d9c7d9-6bbf-4d0c-8b78-7c58bf15d3dc, requestId=1031, is_charging=true, verticalAccuracy=16.0}]}], age: 149ms
02-16 13:28:34.848 5157-14108/? W/TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
                                                       ⚠️  Failed to find SingleLocationRequest
02-16 13:28:34.888 5157-14108/? I/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                       ℹ️  Location availability: true
02-16 13:28:34.898 5157-14110/? I/TSLocationManager: [c.t.l.geofence.GeofenceService onHandleIntent] 
                                                     ╔═════════════════════════════════════════════
                                                     ║ Geofencing Event: ENTER
                                                     ╠═════════════════════════════════════════════
                                                     ╟─ 0
                                                     ╚═════════════════════════════════════════════
02-16 13:28:34.908 5157-14110/? D/TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 25.0
02-16 13:28:34.948 5157-14104/? I/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO persist] 
                                                       ✅  INSERT: efc41862-16e9-4216-ac17-91a75b20e727
02-16 13:28:34.958 5157-5223/? D/TSLocationManager: $ startGeofences()
02-16 13:28:34.968 5157-5223/? W/TSLocationManager: [c.t.l.a.BackgroundGeolocation startGeofences] 
                                                      ⚠️  Already started geofences.  Ignored
02-16 13:28:38.298 5157-14103/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 13:28:38.338 5157-14103/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
02-16 13:28:44.318 5157-14103/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 13:28:44.328 5157-14103/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
02-16 13:28:48.908 5157-14103/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 13:28:48.928 5157-14103/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
02-16 13:28:53.478 5157-14103/? D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
02-16 13:28:53.488 5157-14103/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES

**Comment by pmalhotra1** [comment]
I see a difference in the heartbeat interval in both the logs
Android 7 has a heartbeat of 900 and for Android 5.1.1 the heartbeat is 60 .

My config also has a heartbeat of 60.
this.config = {
      //trackingMode: 'geofence',
      desiredAccuracy: 0,
      distanceFilter: 10,
      disableElasticity: false,
      geofenceProximityRadius: 3000000,
      locationTimeout: 60,
      locationUpdateInterval: 1000,
      fastestLocationUpdateInterval: 10000,
      deferTime: 0,
      activityRecognitionInterval: 1000,
      stopTimeout: 5,
      heartbeatInterval: 60,
      preventSuspend: true,
      startOnBoot: true,
      foregroundService: true,
      notifyOnEntry: true,
      notifyOnExit: true,
      debug: false,
      geofenceInitialTriggerEntry: 1
    };

**Comment by christocracy** [comment]
There is no difference in Geofence behaviour between Android 4.3.3 -> 8.1.0.  I test every day on my Pixel @ 8.1.0.  

`heartbeatInterval` does not changed based upon Android version.  Are you *sure* you didn't actually configure `900`?

**Comment by christocracy** [comment]
Try testing with 200 meter geofences.

**Comment by pmalhotra1** [comment]
Pixel 8.1 is also working fine. Its only on Android 7, its not working.
Let me check the heartbeat config again, but is there anything else you can see as a problem on Android 7. The geofence ENTER/EXIT event does not get generated.

**Comment by christocracy** [comment]
I know of nothing that would be a problem for Android 7.

Check your build SDK, make sure you're building with latest `play-services` version (`11.8.0`)
