### ISSUE TITLE
Does not work. When you turn on the application on multiple devices at once

### ISSUE THREAD

**Issue by IgnatevAnton** [transistorsoft/cordova-background-geolocation-lt#606]
Does not work. When you turn on the application on multiple devices at once

## Your Environment
* Plugin version: 2.10.1
* Platform:Android 
* OS version:  6.0, 7.0
* Device manufacturer / model: 
* Cordova version (`cordova -v`): 
* Cordova platform version (`cordova platform ls`):
* Plugin config

**Comment by christocracy** [comment]
I don’t understand your problem.

**Comment by IgnatevAnton** [comment]
1. I install the application with a plug-in on one device.
Plugin work.
2. I take another phone and install the same application on the second phone.
The plug-in stops working on both devices

**Comment by christocracy** [comment]
That doesn’t make any sense.  There is no quantum entanglement between instances of the plugin on multiple devices.

I regularly have the plugin running on 7 Android devices for both React Native and Cordova sample apps.

Are you observing your adb logcat?

**Comment by IgnatevAnton** [comment]
Thanks for the answer. I looked at the logs and found the problem
