### ISSUE TITLE
ios permission

### ISSUE THREAD

**Issue by Abaddon-88** [transistorsoft/cordova-background-geolocation-lt#609]
If i follow the Instructions i add this variables:
variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION"
variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" 
variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" 
to my config.

If i start the app and background-geolocation ist used i got the message for permission with:
- always
- in use
- not allowed.

How do i get only the 2 options:
- alway
- not allowed?

**Comment by christocracy** [comment]
As of iOS 11, you don't.  iOS now forces you to offer all:
[When in Use]
[Always]
[Never]
