### ISSUE TITLE
Posting by https does not appear to be supported

### ISSUE THREAD

**Issue by aabdelsh** [transistorsoft/cordova-background-geolocation-lt#61]
Can you please add support for posting the location to the server by https for both iOS and Android?

Thanks

**Comment by christocracy** [comment]
The plugin does support https.  Make sure your cert is not self-signed.
Watch the logs.

On Sunday, January 31, 2016, aabdelsh <notifications@github.com> wrote:

> Can you please add support for posting the location to the server by https
> for both iOS and Android?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/61>
> .
>


-- 
Snet form Gmail Mobile

**Comment by aabdelsh** [comment]
I am using self-signed for my lower environments. I suppose will need to use a signed certificate or continue to use http for lower environments...

**Comment by christocracy** [comment]
The plugin was designed for use in military, government (USA FEMA) and power utility applications where ssl is required.

**Comment by christocracy** [comment]
There's actually nothing specific the plugin needs to do wrt ssl.  It's all taken care of by the native http libs.  Provide a valid ssl cert and you're good.
