### ISSUE TITLE
heartbeat event not firing in IOS

### ISSUE THREAD

**Issue by vchatzigiannakis** [transistorsoft/cordova-background-geolocation-lt#610]
## Your Environment
* Plugin version:2.9.1
* Platform: iOS 
* OS version:11
* Device manufacturer / model: iphone 5S
* Cordova version (`cordova -v`):8.0.0
* Cordova platform version (`cordova platform ls`): cli-7.1.0 (4.5.4 / 6.3.0 / 5.0.0) (phonegap build)
* Plugin config

  // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 40,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 10000,
        //stopTimeout: 5,
        debug: false,  // <-- Debug sounds & notifications.
        stopOnTerminate: true,
        startOnBoot: true,
		heartbeatInterval: 120,   //seconds between heartbeat events
        
		
		// HTTP / SQLite config
        autoSync: false,
		batchSync: true,
		httpRootProperty: '.',
        maxDaysToPersist: 3,
		locationTemplate: '{"recorded_at": "<%= timestamp %>","latitude": "<%= latitude %>","longitude": "<%= longitude %>","accuracy":"<%= accuracy %>","speed":"<%= speed %>","status": "<%= activity.type %>"}',
		

## Expected Behavior

Heartbeat  event should fire in stationary mode (It does in android with the same conf/code.)
## Actual Behavior

Heartbeat  event does not fire

**Comment by christocracy** [comment]
Unfortunately, iOS will throttle the heartbeat events when the device is **unplugged from power and sitting completely still**.

You'll find that if you shake the device a bit or light up the screen, heartbeats will resume.  As long as the user is using the device (not necessarily your app) or physically *moving*, heartbeats will fire normally.

**Comment by christocracy** [comment]
Also, iOS requires `preventSuspend: true` for `heartbeat` event to fire.  I don't see you've provided that.

**Comment by vchatzigiannakis** [comment]
Thanx for the input!
