### ISSUE TITLE
License validation error and app crash after plugin update

### ISSUE THREAD

**Issue by Salcci** [transistorsoft/cordova-background-geolocation-lt#613]
I upgraded background geolocation plugin from version 2.1.6 to 2.8.5.
At startup I see 'License validation failure' message and later on application crashes.
NoSuchMethodError: checkSelfPermission

## Your Environment
* Plugin version: 2.8.5
* Platform: Android
* OS version: 5.0 & 7.0
* Device manufacturer / model: Samsung Xcover 3, Xcover 4
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): android 6.0.0
* Plugin config

## Expected Behavior
License is valid and it should be accepted.

## Actual Behavior
License validation fais and application crashes.

## Context
Updated plugin from 2.1.6-pre to 2.8.5.
Launch application.
Start locating.

## Debug logs
<pre>
03-01 10:40:12.185 19411-19579/? W/System.err: java.lang.NoSuchMethodError: No static method checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/<my-app>-1/base.apk)
03-01 10:40:12.185 19411-19579/? W/System.err:     at com.transistorsoft.locationmanager.event.LocationProviderChangeEvent.<init>(Unknown Source)
03-01 10:40:12.185 19411-19579/? W/System.err:     at com.transistorsoft.locationmanager.location.TSLocationManager.isLocationServicesEnabled(Unknown Source)
03-01 10:40:12.185 19411-19579/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$h.a(Unknown Source)
03-01 10:40:12.185 19411-19579/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$h.run(Unknown Source)
03-01 10:40:13.439 3146-3146/? I/SapService: Unexpected error!
</pre>

**Comment by Salcci** [comment]
Update:
I added following lines to build.gradle:
<pre>
    compile 'com.google.android.gms:play-services:+'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile "com.android.support:support-v13:24.2.1"
</pre>

Now application wont crash and license validation error not shown at startup BUT it is shown when closing or restarting app if background locating is on.

**Comment by christocracy** [comment]
Did you follow the [README](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin)?
