### ISSUE TITLE
Could not find :tsbackgroundfetch,Could not find :tslocationmanager:.

### ISSUE THREAD

**Issue by keerthivasan12** [transistorsoft/cordova-background-geolocation-lt#614]
BUILD FAILED in 24s
11 actionable tasks: 11 executed
Error: /home/developer/Documents/myNewProject/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :tsbackgroundfetch:.
  Searched in the following locations:
      file:/home/developer/Android/Sdk/extras/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
      file:/home/developer/Android/Sdk/extras/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
      file:/home/developer/Android/Sdk/extras/google/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
      file:/home/developer/Android/Sdk/extras/google/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
      file:/home/developer/Android/Sdk/extras/android/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
      file:/home/developer/Android/Sdk/extras/android/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
      https://jcenter.bintray.com//tsbackgroundfetch//tsbackgroundfetch-.pom
      https://jcenter.bintray.com//tsbackgroundfetch//tsbackgroundfetch-.aar
      https://maven.google.com//tsbackgroundfetch//tsbackgroundfetch-.pom
      https://maven.google.com//tsbackgroundfetch//tsbackgroundfetch-.aar
      https://repo1.maven.org/maven2//tsbackgroundfetch//tsbackgroundfetch-.pom
      https://repo1.maven.org/maven2//tsbackgroundfetch//tsbackgroundfetch-.aar
      file:/home/developer/Documents/myNewProject/platforms/android/app/src/android/libs/tsbackgroundfetch-.aar
      file:/home/developer/Documents/myNewProject/platforms/android/app/src/android/libs/tsbackgroundfetch.aar
  Required by:
      project :app
> Could not find :tslocationmanager:.
  Searched in the following locations:
      file:/home/developer/Android/Sdk/extras/m2repository//tslocationmanager//tslocationmanager-.pom
      file:/home/developer/Android/Sdk/extras/m2repository//tslocationmanager//tslocationmanager-.aar
      file:/home/developer/Android/Sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.pom
      file:/home/developer/Android/Sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.aar
      file:/home/developer/Android/Sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.pom
      file:/home/developer/Android/Sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.aar
      https://jcenter.bintray.com//tslocationmanager//tslocationmanager-.pom
      https://jcenter.bintray.com//tslocationmanager//tslocationmanager-.aar
      https://maven.google.com//tslocationmanager//tslocationmanager-.pom
      https://maven.google.com//tslocationmanager//tslocationmanager-.aar
      https://repo1.maven.org/maven2//tslocationmanager//tslocationmanager-.pom
      https://repo1.maven.org/maven2//tslocationmanager//tslocationmanager-.aar
      file:/home/developer/Documents/myNewProject/platforms/android/app/src/android/libs/tslocationmanager-.aar
      file:/home/developer/Documents/myNewProject/platforms/android/app/src/android/libs/tslocationmanager.aar
  Required by:
      project :app

**Comment by keerthivasan12** [comment]
global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

**Comment by rajasj08** [comment]
@keerthivasan12 the plugin is compatible for  6.3.0 and it'll work well in that. In order to make the plugin background-geolocation-lt compatible to work with android 7.+ do the following changes

1. Open your plugin.xml file and look out for the Androidmanifest.xml and do the below change
// from 
<config-file target="AndroidManifest.xml" parent="/manifest/application">
// To 
<config-file target="app/src/main/AndroidManifest.xml" parent="/manifest/application">

2. Change attr target from "src/android/libs/tslocationmanager.aar" to "libs/tslocationmanager.aar"

3. Similarly for attr target-dir from "src/com/transistorsoft/" to "app/src/main/com/transistorsoft/"

4. on plugin/src/android/build.gradle file
// from 
flatDir{
    dirs 'src/android/libs'
  }

// to

flatDir{
    dirs 'src/main/libs'
  }

5. Do the above changes to the plugin dependency cordova-plugin-background-fetch too.
6. cordova platform remove android
7. cordova platform add android@7.1.0 for android version 7.1.0
8. Happy coding

**Comment by christocracy** [comment]
It *is* a simple task to update the plugin's `config.xml` to support the new structure of a `cordova-android@7.x` and it will be updated in the near future.  And of course once I do, *everyone* will be forced to use `cordova-android@7.x` and the ones left behind will be posting issues:
```
Could not find :tsbackgroundfetch,Could not find :tslocationmanager
```

But beware:  the next version of `background-geolocation` (available now in the premium version) no longer uses `flatDirs`.

**Comment by keerthivasan12** [comment]
@rajasj08 thank you for your reply, your my day saver :) - i followed your steps and now the tsbackgroundfetch issue gone and the app builded successfully for android, but the background service is not working! Any idea will be helpful.

@christocracy can you guide me on that why the bgGeo.start() is starting!

Thanks in advance

**Comment by rajasj08** [comment]
can you share me your plugin list

**Comment by christocracy** [comment]
If something is not working, the first thing to do is:
```
$ adb logcat -s TSLocationManager
```

**Comment by keerthivasan12** [comment]
@rajasj08   my plugin list
cordova-background-geolocation-lt 2.10.1 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.2.1 "PushPlugin"

**Comment by keerthivasan12** [comment]
@christocracy 
adb logcat -s TSLocationManager
when i run this above command i am getting 

--------- beginning of crash
--------- beginning of main
--------- beginning of system

**Comment by keerthivasan12** [comment]
@rajasj08 @christocracy 

adb logcat -s TSLocationManager
when i run this above command i am getting
--------- beginning of crash
--------- beginning of system
--------- beginning of main
I/TSLocationManager(23534): 
I/TSLocationManager(23534): ╔═════════════════════════════════════════════
I/TSLocationManager(23534): ║ License Validation Failure
I/TSLocationManager(23534): ╠═════════════════════════════════════════════
I/TSLocationManager(23534): ╟─ BackgroundGeolocation is running in evaluation mode.
I/TSLocationManager(23534): [c.t.l.util.Sensors print] 
I/TSLocationManager(23534): ╔═════════════════════════════════════════════
I/TSLocationManager(23534): ║ DEVICE SENSORS
I/TSLocationManager(23534): ╠═════════════════════════════════════════════
I/TSLocationManager(23534): ╟─ ✅  ACCELEROMETER: {Sensor name="MPU6050-accel", vendor="Invensense", version=1, type=1, maxRange=156.8, resolution=5.98144E-4, power=0.5, minDelay=10000}
I/TSLocationManager(23534): ╟─ ✅  GYROSCOPE: {Sensor name="MPU6050-gyro", vendor="Invensense", version=1, type=4, maxRange=34.906586, resolution=0.0010681152, power=3.6, minDelay=10000}
I/TSLocationManager(23534): ╟─ ✅  MAGNETOMETER: {Sensor name="st480", vendor="Senodia", version=1, type=2, maxRange=3200.0, resolution=0.1, power=0.4, minDelay=10000}
I/TSLocationManager(23534): ╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
I/TSLocationManager(23534): ╚═════════════════════════════════════════════
I/TSLocationManager(23534): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(23534): ╔═════════════════════════════════════════════
I/TSLocationManager(23534): ║ TSLocationManager version: 2.11.2
I/TSLocationManager(23534): ╠═════════════════════════════════════════════
I/TSLocationManager(23534): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(23534):   ✅  Google Play Services: connected (version code:11910000)
I/TSLocationManager(23534): 
I/TSLocationManager(23534): ╔═════════════════════════════════════════════
I/TSLocationManager(23534): ║ License Validation Failure
I/TSLocationManager(23534): ╠═════════════════════════════════════════════
I/TSLocationManager(23534): ╟─ BackgroundGeolocation is running in evaluation mode.
D/TSLocationManager(23534): [c.t.l.d.s.SQLiteLocationDAO dbh] 
D/TSLocationManager(23534):   ✅  Opened database
D/TSLocationManager(23534): [c.t.l.d.s.SQLiteLocationDAO prune] 
D/TSLocationManager(23534):   ℹ️  PRUNE -1 days
I/TSLocationManager(23534): 
I/TSLocationManager(23534): ╔═════════════════════════════════════════════
I/TSLocationManager(23534): ║ License Validation Failure
I/TSLocationManager(23534): ╠═════════════════════════════════════════════
I/TSLocationManager(23534): ╟─ BackgroundGeolocation is running in evaluation mode.
I/TSLocationManager(23534): 
I/TSLocationManager(23534): ╔═════════════════════════════════════════════
I/TSLocationManager(23534): ║ License Validation Failure
I/TSLocationManager(23534): ╠═════════════════════════════════════════════
I/TSLocationManager(23534): ╟─ BackgroundGeolocation is running in evaluation mode.
D/TSLocationManager(23534): [c.t.l.data.sqlite.GeofenceDAO dbh] 
D/TSLocationManager(23534):   ✅  Opened database
I/TSLocationManager(23534): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(23534):   ������  Connecting to GooglePlayServices...
I/TSLocationManager(23534): [c.t.l.BootReceiver onReceive] 
I/TSLocationManager(23534): ╔═════════════════════════════════════════════
I/TSLocationManager(23534): ║ BootReceiver: com.inpre.android
I/TSLocationManager(23534): ╠═════════════════════════════════════════════
I/TSLocationManager(23534): ╟─ android.intent.action.MY_PACKAGE_REPLACED
W/TSLocationManager(23534): [c.t.l.BootReceiver a] Plugin is configured to stopOnTerminate: true.  Refusing to start BackgroundGeolocation on boot

**Comment by christocracy** [comment]
- logcat is a stream of logs from all apps on device.
- `-s` is a filter for all messages from plugin
- if a crash occurs, remove the -s filter to see stacktrace

**Comment by ckirksey3** [comment]
I put the changes that @rajasj08 suggested in a PR if anyone wants to review it: https://github.com/transistorsoft/cordova-background-geolocation-lt/pull/623

**Comment by MrXyfir** [comment]
> Open your plugin.xml file and look out for the Androidmanifest.xml and do the below change ...

I'm getting this same issue, but how would I implement these solutions on PhoneGap Build?

```
Build Date: 2018-04-09 18:15:36 +0000
--------------------------------------------------------------------------------
PREPARE OUTPUT
--------------------------------------------------------------------------------
Android Studio project detected
Generating platform-specific config.xml from defaults for android at /app/src/main/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
Merging and updating files from [www, ../platform_www] to ../app/src/main/assets/www
  copy  www/app.js ../app/src/main/assets/www/app.js (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src
  mkdir ../app/src/main/assets/www/cordova-js-src/android
  copy  ../platform_www/cordova-js-src/android/nativeapiprovider.js ../app/src/main/assets/www/cordova-js-src/android/nativeapiprovider.js (new file)
  copy  ../platform_www/cordova-js-src/android/promptbasednativeapi.js ../app/src/main/assets/www/cordova-js-src/android/promptbasednativeapi.js (new file)
  copy  ../platform_www/cordova-js-src/exec.js ../app/src/main/assets/www/cordova-js-src/exec.js (new file)
  copy  ../platform_www/cordova-js-src/platform.js ../app/src/main/assets/www/cordova-js-src/platform.js (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin/android
  copy  ../platform_www/cordova-js-src/plugin/android/app.js ../app/src/main/assets/www/cordova-js-src/plugin/android/app.js (new file)
  copy  ../platform_www/cordova.js ../app/src/main/assets/www/cordova.js (updated file)
  rmdir  ../app/src/main/assets/www/css (no source)
  delete ../app/src/main/assets/www/css/index.css (no source)
  rmdir  ../app/src/main/assets/www/img (no source)
  delete ../app/src/main/assets/www/img/cordova.png (no source)
  delete ../app/src/main/assets/www/img/logo.png (no source)
  copy  www/index.html ../app/src/main/assets/www/index.html (updated file)
  rmdir  ../app/src/main/assets/www/js (no source)
  delete ../app/src/main/assets/www/js/index.js (no source)
Wrote out android application name "Test" to /app/src/main/res/values/strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (0.0.4): 4
Wrote out Android package name "com.xyfir.test" to /app/src/main/java/com/xyfir/test/Test.java
Updating icons at ../app/src/main/res
  copy  res/icons/android/icon-72-hdpi.png ../app/src/main/res/mipmap-hdpi/icon.png (updated file)
  copy  res/icons/android/icon-36-ldpi.png ../app/src/main/res/mipmap-ldpi/icon.png (updated file)
  copy  res/icons/android/icon-48-mdpi.png ../app/src/main/res/mipmap-mdpi/icon.png (updated file)
  copy  res/icons/android/icon-96-xhdpi.png ../app/src/main/res/mipmap-xhdpi/icon.png (updated file)
  copy  res/icons/android/icon-144-xxhdpi.png ../app/src/main/res/mipmap-xxhdpi/icon.png (updated file)
  copy  res/icons/android/icon-192-xxxhdpi.png ../app/src/main/res/mipmap-xxxhdpi/icon.png (updated file)
Updating splash screens at ../app/src/main/res
  copy  res/screens/android/screen-hdpi-landscape.png ../app/src/main/res/drawable-land-hdpi/screen.png (updated file)
  copy  res/screens/android/screen-ldpi-landscape.png ../app/src/main/res/drawable-land-ldpi/screen.png (updated file)
  copy  res/screens/android/screen-mdpi-landscape.png ../app/src/main/res/drawable-land-mdpi/screen.png (updated file)
  copy  res/screens/android/screen-xhdpi-landscape.png ../app/src/main/res/drawable-land-xhdpi/screen.png (updated file)
  copy  res/screens/android/screen-xxhdpi-landscape.png ../app/src/main/res/drawable-land-xxhdpi/screen.png (updated file)
  copy  res/screens/android/screen-xxxhdpi-landscape.png ../app/src/main/res/drawable-land-xxxhdpi/screen.png (updated file)
  copy  splash.png ../app/src/main/res/drawable-mdpi/screen.png (new file)
  copy  res/screens/android/screen-hdpi-portrait.png ../app/src/main/res/drawable-port-hdpi/screen.png (updated file)
  copy  res/screens/android/screen-ldpi-portrait.png ../app/src/main/res/drawable-port-ldpi/screen.png (updated file)
  copy  res/screens/android/screen-mdpi-portrait.png ../app/src/main/res/drawable-port-mdpi/screen.png (updated file)
  copy  res/screens/android/screen-xhdpi-portrait.png ../app/src/main/res/drawable-port-xhdpi/screen.png (updated file)
  copy  res/screens/android/screen-xxhdpi-portrait.png ../app/src/main/res/drawable-port-xxhdpi/screen.png (updated file)
  copy  res/screens/android/screen-xxxhdpi-portrait.png ../app/src/main/res/drawable-port-xxxhdpi/screen.png (updated file)
This app does not have additional resource files defined
Prepared android project successfully
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-console" via npm
Installing "cordova-plugin-console" at "1.1.0" for android
Android Studio project detected
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "2.0.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "2.0.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-file" via npm
Installing "cordova-plugin-file" at "6.0.1" for android
Android Studio project detected

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "4.0.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-globalization" via npm
Installing "cordova-plugin-globalization" at "1.0.9" for android
Android Studio project detected
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "2.0.2" for android
Android Studio project detected
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media" at "5.0.2" for android
Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Android Studio project detected
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "2.0.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-splashscreen" via npm
Installing "cordova-plugin-splashscreen" at "5.0.2" for android
Android Studio project detected
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android
Android Studio project detected

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-statusbar" via npm
Installing "cordova-plugin-statusbar" at "2.4.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-remote-injection" via npm
Installing "cordova-plugin-remote-injection" at "0.5.2" for android
Android Studio project detected
Fetching plugin "cc.fovea.cordova.purchase" via npm
Installing "cc.fovea.cordova.purchase" at "7.1.3" for android
Android Studio project detected
Fetching plugin "cordova-background-geolocation-lt" via npm
Installing "cordova-background-geolocation-lt" at "2.11.0-beta.2" for android
Fetching plugin "cordova-plugin-background-fetch@~5.3.0" via npm
Installing "cordova-plugin-background-fetch" at "5.3.0" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
Android Studio project detected
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Android Studio project detected
studio
:wrapper

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Exception while marshalling /opt/android-sdk/extras/google/google_play_services/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-P/package.xml. Probably the SDK is read-only
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_31nkmutlm81sptgh5eniirg8q.run(/app/build.gradle:145)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:checkReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:prepareLintJar
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:platformAttrExtractor
:CordovaLib:processReleaseManifest
:CordovaLib:javaPreCompileRelease
:CordovaLib:processReleaseJavaRes NO-SOURCE
:app:preBuild UP-TO-DATE
:app:preReleaseBuild
Download https://maven.google.com/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.pom
Download https://jcenter.bintray.com/com/intentfilter/android-permissions/0.1.6/android-permissions-0.1.6.pom
Download https://maven.google.com/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-tasks/11.6.0/play-services-tasks-11.6.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-location-license/11.6.0/play-services-location-license-11.6.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-base/11.6.0/play-services-base-11.6.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-basement/11.6.0/play-services-basement-11.6.0.pom
Download https://maven.google.com/com/android/support/support-vector-drawable/27.1.0/support-vector-drawable-27.1.0.pom
Download https://maven.google.com/com/android/support/animated-vector-drawable/27.1.0/animated-vector-drawable-27.1.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-base-license/11.6.0/play-services-base-license-11.6.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-basement-license/11.6.0/play-services-basement-license-11.6.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-tasks-license/11.6.0/play-services-tasks-license-11.6.0.pom
:app:preReleaseBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
  Searched in the following locations:
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/
      https://repo1.maven.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://repo1.maven.org/maven2/com/transistorsoft/tsbackgroundfetch/
      file:/app/src/android/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/app/src/android/libs/com/transistorsoft/tsbackgroundfetch/
  Required by:
      project :app
> Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
  Searched in the following locations:
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tslocationmanager/
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/
      https://maven.google.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tslocationmanager/
      https://repo1.maven.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://repo1.maven.org/maven2/com/transistorsoft/tslocationmanager/
      file:/app/src/android/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/app/src/android/libs/com/transistorsoft/tslocationmanager/
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
11 actionable tasks: 11 executed
Error: /gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
  Searched in the following locations:
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/
      https://repo1.maven.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://repo1.maven.org/maven2/com/transistorsoft/tsbackgroundfetch/
      file:/app/src/android/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/app/src/android/libs/com/transistorsoft/tsbackgroundfetch/
  Required by:
      project :app
> Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
  Searched in the following locations:
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/opt/android-sdk/extras/m2repository/com/transistorsoft/tslocationmanager/
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/opt/android-sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/opt/android-sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/
      https://maven.google.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tslocationmanager/
      https://repo1.maven.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://repo1.maven.org/maven2/com/transistorsoft/tslocationmanager/
      file:/app/src/android/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/app/src/android/libs/com/transistorsoft/tslocationmanager/
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by christocracy** [comment]
@MrXyfir Just use `cordova-android@6.4.0` for now.

**Comment by christocracy** [comment]
That PR #623 is obsolete with latest version of the plugin `2.11.0`.

**Comment by gregor-srdic** [comment]
Can you please describe how to make this compatible with cordova-android 7.1.0?

**Comment by christocracy** [comment]
@gregor-srdic Just use cordova-android@6.4.0 for now.  I'll update the plugin for cordova-android@7 compatibility in the next few weeks.

**Comment by christocracy** [comment]
`cordova-android@7` support is now released in `2.12.1`

The native libraries in `2.11.x` are *identical* to those in `2.12.x`.  The only difference is in the plugin's `plugin.xml` file making it compatible with `cordova-android@7`.   There is no difference in plugin *behaviour* between `2.11.x` and `2.12.x`.

**Comment by gregor-srdic** [comment]
I have tried to use this plugin with [Ionic Capacitor ](https://capacitor.ionicframework.com/) but it produces a similar error when trying to build - any idea?

Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
Searched in the following locations:
    file:/C:/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
    file:/C:/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/
    file:/C:/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
    file:/C:/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/
    file:/C:/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
    file:/C:/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/
    https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
    https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/
    https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
    https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/
    https://dl.bintray.com/ionic-team/capacitor/com/transistorsoft/tslocationmanager/maven-metadata.xml
    https://dl.bintray.com/ionic-team/capacitor/com/transistorsoft/tslocationmanager/
    file:/C:/Nomnio/Sandbox/Capacitor/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/libs/
    file:/C:/Nomnio/Sandbox/Capacitor/android/app/libs/
    https://maven.google.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
    https://maven.google.com/com/transistorsoft/tslocationmanager/
    file:/C:/Nomnio/Sandbox/Capacitor/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
    file:/C:/Nomnio/Sandbox/Capacitor/android/app/libs/com/transistorsoft/tslocationmanager/
Required by:
    project :app
    project :app > project :capacitor-android-plugins

**Comment by christocracy** [comment]
Show me your 
```
$ cordova -v
$ cordova platforms
$ cordova plugins
```

**Comment by gregor-srdic** [comment]
cordova -v: 8.0.0
I believe none of those apply though because capacitor works without cordova (it is a replacement) - never mind though, I do not have enough experience with it to know what the problem is
perhaps you can take a look at it if you have some spare time sometime
it is also just in alpha though for now I believe ...

**Comment by christocracy** [comment]
Yea, I know little of Capacitor.
