### ISSUE TITLE
Plugin doesn't work consistently on background mode

### ISSUE THREAD

**Issue by mihristov** [transistorsoft/cordova-background-geolocation-lt#617]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: HTC Desire 820
* Cordova version (`cordova -v`): / phonegap build cli-7.1.0 (android 6.3.0)
* Cordova platform version (`cordova platform ls`):
* Plugin config
          desiredAccuracy: 0,
          stopTimeout: 0,
          fastestLocationUpdateInterval: 5000,
          locationUpdateInterval: 1000,
          heartbeatInterval: 60,
          foregroundService: true

## Expected Behavior

To run in background mode as it is running in foreground (which is pretty good).
## Actual Behavior

The plugin gives me coordinates regularly for some time then stops.
You can see the points on the map here https://imgur.com/a/2WQHX (the trip starts from east). I think I unlocked my phone in the middle of the trip (where the three points are).
## Steps to Reproduce

1. Start the plugin
2. Lock the phone
3. Drive for 15mins
4. Stop the plugin

## Context

Do you have any suggestions on why the background service stops after some time?
## Debug logs

debug logs: https://pastebin.com/Jm5wL8DT

**Comment by christocracy** [comment]
Your OS engaged PowerSaveMode here:
```
03-05 19:36:19.712 INFO [BackgroundGeolocationService a]
  🎾  PowerSaveMode
```

**Comment by christocracy** [comment]
you can capture these `PowerSaveMode` events via the plugin's [`powersavechange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#powersavechange) event.

**Comment by christocracy** [comment]
One thing the OS is going to do when it engages Power Save Mode is disable GPS.  The plugin itself does **nothing** other than inform you via the `powersavechange` event.
