### ISSUE TITLE
iOS adding distance when not moving and tracking more distance then real distance

### ISSUE THREAD

**Issue by maswa** [transistorsoft/cordova-background-geolocation-lt#618]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS 
* OS version: 11.2
* Device manufacturer / model: Apple iPhone SE
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):4.5.4
* Plugin config     // BackgroundGeoLocation is highly configurable.
        bgGeo.configure({
            // Geolocation config
		desiredAccuracy: 0,
	  	distanceFilter: 10,
	  	stationaryRadius: 25,
		stopTimeout: 5,         // Change state to stationary after 5 min with device "still"
                //stopOnTerminate: false, // Don't stop tracking when app is terminated.
	  	foregroundService: true,
            debug: false  // <-- Debug sounds & notifications.
        
        }, function(state) {
            // This callback is executed when the plugin is ready to use.
            //alert("BackgroundGeolocation ready: "+ state);
        if (!state.enabled) {
            bgGeo.start();

        }
    });
 

## Expected Behavior

App should track accurate distance and should not add distance while not moving. 

## Actual Behavior

iOS version tracks more distrance then the real distance and it adds distance while not even moving.. but standing still. Android version with the same code does track accurate and does not add distance when not moving. 

## Steps to Reproduce

This is the complete code that is used for the GPS monitor. 

    <!DOCTYPE html>
    <html lang="en">
    <head>
	<meta charset="UTF-8">
	<title>THC</title>
	<meta name="viewport" content="width=device-width, initial-scale=1  maximum-scale=1 user-
    scalable=no">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="HandheldFriendly" content="True">
	
	<link rel="shortcut icon" href="img/favicon.png">
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="css/materialize.min.css">
	<link rel="stylesheet" href="css/slick.css">
	<link rel="stylesheet" href="css/slick-theme.css">
	<link rel="stylesheet" href="css/owl.carousel.css">
	<link rel="stylesheet" href="css/owl.theme.css">
	<link rel="stylesheet" href="css/owl.transitions.css">
	<link rel="stylesheet" href="css/style.css">	
    </head>
    <body onLoad="load_left_bar();">

	
      <div class="navbar">
		<div class="container">
			
			<div class="site-title">
				<a href="javascript:voide();" class="logo">
				<h1 tkey="gps-title">Activiteiten</h1></a>
			</div>
			
		</div>
	</div>
	

	
	<div class="panel-control-left" >
		<ul id="slide-out-left" class="side-nav collapsible"  data-collapsible="accordion">
        </ul>
	</div>
	

	
	
	
	<div class="login app-pages app-section">
		<div class="container" id="content" style="width:100%; margin-top:-25px;">
        <div id="map_canvas" style="width:100%;height:350px; background-color:#999;"></div>
        <p align="center" style="font-weight:bold"><span tkey="lbl-distance">Afgelegde Afstand:
    </span> <span id="distance">0</span> KM</p>
        
    	<div style="text-align:center; width:100%"><input type="button" value="Pause" 
     onClick="load_activity_page();" class="button2" style="width:50%;"></div>
        
        
       
        
       
        <p id="err"></p>
        
            
          
      
             
             
             
	  </div>
	</div>
	
	
	
	<script src="js/jquery.min.js"></script>
	<script src="js/materialize.min.js"></script>
	<script src="js/slick.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/custom.js"></script>
       <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnQ-
    vuYb2n_GbT8KPLyHXiKmZtqwBsCi0&force=canvas"></script>
    <script src="cordova.js"></script>
    <script src="lang/translations_alerts.js"></script>
    <script src="js/main.js"></script>

    <script language="javascript">

    document.addEventListener("deviceready", onDeviceReady, false);
    // PhoneGap is loaded and it is now safe to make calls PhoneGap methods
    function onDeviceReady() {
    var lat1=0;
    var lon1=0;
    if(Number(localStorage.distance)>0){
    }else{
	localStorage.distance=0;	
    }

	var options = {
		timeout: Infinity,
		enableHighAccuracy: true,
		maximumAge: 0
	};
	var mapCanvas = document.getElementById("map_canvas");
	
	var mapOptions = {
			//center: current_location,
			zoom: 17,
			clickableIcons: true,
			mapTypeControl: false
		};
	map = new google.maps.Map(mapCanvas, mapOptions);
	
	var marker = new google.maps.Marker({
			//position:current_location,
			map:map,
			title: 'My Location',
			icon:'img/green-dot.png'
		});
	
    
      $("#distance").html(localStorage.distance);
    
      // Get a reference to the plugin.
      var bgGeo = window.BackgroundGeolocation;
   
      //This callback will be executed every time a geolocation is recorded in the background.
     var callbackFn = function(location) {
        var coords = location.coords;
        var lat2    = coords.latitude;
        var lon2   = coords.longitude;
	var speed = (coords.speed*60*60)/1000;
	//alert (lat2+" : "+lon2);
	var current_location = new google.maps.LatLng(lat2 ,lon2);
	
	map.setCenter(current_location);
	marker.setPosition(current_location);
		if(speed>40){
		 show_alert(lbl_activity[langCode],lbl_gps_speed[langCode],'OK');
		 save_distance();
		}
		if(lat1!=0){
			var 
    
    distance=Number(localStorage.distance)+Number(getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2));
			localStorage.distance=distance.toFixed(2);
			$("#distance").html(localStorage.distance);
		}
		lat1=lat2;
		lon1=lon2;
		//$('#location').append("<br>Lat: "+lat1+", Lng: "+lon1);
       // alert('- Location: ', JSON.stringify(location));        
    };
	
 
    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables 
    location-services.
    var failureFn = function(errorCode) {
        //alert('- BackgroundGeoLocation error: '+ errorCode);
    }
 
    // Listen to location events & errors.
   bgGeo.on('location', callbackFn, failureFn);
    // Fired whenever state changes from moving->stationary or vice-versa.
   
    bgGeo.on('motionchange', function(isMoving) {
		//localStorage.loc_data=localStorage.loc_data+'motionchange <br>';
		//alert('- onMotionChange: '+ isMoving);
      //alert('- onMotionChange: ', isMoving);
    });
   
    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
		desiredAccuracy: 0,
	  	distanceFilter: 10,
	  	stationaryRadius: 25,
		stopTimeout: 5,         // Change state to stationary after 5 min with device "still"
                //stopOnTerminate: false, // Don't stop tracking when app is terminated.
	  	foregroundService: true,
        debug: false  // <-- Debug sounds & notifications.
        
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        //alert("BackgroundGeolocation ready: "+ state);
        if (!state.enabled) {
            bgGeo.start();

        }
    });
 
    // The plugin is typically toggled with some button on your UI.
	/*function onToggleEnabled(value) {
        if (value) {
            bgGeo.start();
			$("#content").append('start1 <br>');
        } else {
            bgGeo.stop();
			$("#content").append('stop1 <br>');
        }
    }*/

    }//end of device ready

    function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
  var R = 6371; // Radius of the earth in km
  var dLat = deg2rad(lat2-lat1);  // deg2rad below
  var dLon = deg2rad(lon2-lon1); 
  var a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * 
    Math.sin(dLon/2) * Math.sin(dLon/2)
    ; 
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
  var d = R * c; // Distance in meters
  //d=Math.round(d*1000);
  return d;
   }

   function deg2rad(deg) {
  return deg * (Math.PI/180)
   }

   function speed_limit(){
	show_alert(lbl_activity[langCode],lbl_gps_speed[langCode],'OK');
	save_distance();	
   }

   </script>
   </body>
   </html>

   ## Context

This app should track distance for walking, running or cycling activities

**Comment by christocracy** [comment]
Are you aware the plugin already calculates distance travelled via the `odometer` attribute appended to each recorded location?

See [`resetOdometer`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#resetodometercallbackfn-failurefn) and [`desiredOdometerAccuracy`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-desiredodometeraccuracy-100)

If you're calculating your own distance, I really don't understand your problem "iOS adding distance when not moving and tracking more distance then real distance".

**Comment by christocracy** [comment]
The plugin's odometer is only incremented when the plugin is in `moving` state.

**Comment by maswa** [comment]
Thanks.. we have used the odometer attribute now and that seems to work better. There is only one difference we notice between iOS end Android behaviour. Android is updating distance faster then iOS after a pause..  is that normal behaviour?

**Comment by christocracy** [comment]
Yes, iOS requires movement of *at least* 200 meters before tracking will engage.  See [`stationaryRadius`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-stationaryradius-meters)
