### ISSUE TITLE
Created a sample ionic App with this plugin

### ISSUE THREAD

**Issue by rishantagarwal** [transistorsoft/cordova-background-geolocation-lt#62]
I have created a sample app so that people can get started easily with the plugin. 

[Sample App](https://github.com/rishantagarwal/CordovaBackgroundGeolocationStartingUpExample)

I don't know where to put it so i am creating an issue with the link. Let me know if this could be useful or  any feedback @christocracy

**Comment by sadortun** [comment]
:+1:

**Comment by christocracy** [comment]
Thanks.  Sorry so late, I just discovered I wasn't getting notifications on my own repo!
