### ISSUE TITLE
Framework not found

### ISSUE THREAD

**Issue by Jeyavijay** [transistorsoft/cordova-background-geolocation-lt#620]
Hi,
I have added the TSLocationManager SDK and TSBackgroundFetch SDK while building the app showing the error No framework found .
I tried by adding in the framework search paths too but the error was not solving.

Can you please help me this out.

Thanks in Advance

**Comment by christocracy** [comment]
Is this for a native app implementation?

**Comment by Jeyavijay** [comment]
Yeah for native iOS app

**Comment by christocracy** [comment]
This is the repo for Cordova framework.  Use the repo [background-geolocation-lt](https://github.com/transistorsoft/background-geolocation-lt)
