### ISSUE TITLE
Plugin doesn't start tracking immediately after being still

### ISSUE THREAD

**Issue by mihristov** [transistorsoft/cordova-background-geolocation-lt#621]
I stop getting locations for some period after I've stopped moving for a while. Aggressive tracking doesn't launch right after I start moving again. Tested in background mode.
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: HTC Desire 820
* Cordova version (`cordova -v`): phonegap build cli-7.1.0 (android 6.3.0)
* Cordova platform version (`cordova platform ls`):
* Plugin config

- desiredAccuracy: 0,
- stopTimeout: 0,
- fastestLocationUpdateInterval: 5000,
- locationUpdateInterval: 1000,
- heartbeatInterval: 60,
- foregroundService: true

## Expected Behavior

Location tracking should start right after I start moving again.
## Actual Behavior

It starts 10 mins later. https://imgur.com/a/FRKDq You can see that big chunk of missing points. It happened right after I spent some time waiting at the traffic light.
## Steps to Reproduce

1. Start the plugin
2. Put it in background and lock the phone
3. Stop at the traffic light
4. Continue to drive

## Context

I'm trying to get the full set of coordinates out of my trip.
Do you think the issue is related to `stopTimeout: 0` ? I set that in order to start receiving heartbeat updates right after I stop moving (because I need some location update at least once per minute).
Or do you think this is because of my phone? I'm missing 2 out of 4 sensors.
Thanks.
## Debug logs

https://pastebin.com/xgg9L6Fs

**Comment by christocracy** [comment]
I would **never** use `stopTimeout: 0`.  That's going to cause the plugin to enter stationary-state at traffic lights.

There are other ways to get a location "every minute", like using `#watchPosition` when `motionchange: true` fires.  **BE SURE** to `#stopWatchPosition` when `motionchange: false` fires or location-services will stay on **forever**.

Your **Device Sensors** report 2 missing sensors, so the ActivityRecognition API is handicapped:
```
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="BOSCH BMA250 3-axis Accelerometer", vendor="BOSCH", version=1, type=1, maxRange=39.2266, resolution=0.038307227, power=0.2, minDelay=10000}
╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
╟─ ✅  MAGNETOMETER: {Sensor name="AK8963 3-axis Magnetic field sensor", vendor="Asahi Kasei Microdevices", version=1, type=2, maxRange=4915.2, resolution=0.06, power=0.28, minDelay=10000}
╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
╚═════════════════════════════════════════════
```
Even my Nexus 4 @ 4.4.4 from 2012 contains all these sensors and tracks wonderfully.

As for your logs, I assume you're talking about the 10 min gap here:
- The plugin successfully trigger *moving* state on the first `ActivityRecognitionResult` it receives.  You are simply being far too eager to trigger *stationary* state with `stopTimeout: 0`.  This is a particularly **bad idea** on a device with handicapped MotionApi due to missing sensors.

```
03-06 19:10:20.524 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (98%)
03-06 19:10:20.544 INFO [TSLocationManager removeLocationUpdates]
  🔴  Location-services: OFF
03-06 19:10:20.549 INFO [BackgroundGeolocationService k]
  🔴  Stop heartbeat
03-06 19:10:20.559 INFO [BackgroundGeolocationService a]
  🎾  Start heartbeat (60)
03-06 19:10:20.575 INFO [BackgroundGeolocationService a]
  🔵  setPace: true → false
03-06 19:10:20.654 INFO [LocationService onLocation]
  ℹ️  Location availability: true
03-06 19:10:21.853 DEBUG [LocationService onLocation]
╔═════════════════════════════════════════════
║ LocationService: location:1004
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 42.674177,23.337690 acc=96 et=+20d16h47m23s343ms alt=642.0 vel=0.15 bear=220.0 {Bundle[{requestId=1004, verticalAccuracy=192.0}]}], age: 40ms, time: 1520356221721
 
03-06 19:10:21.863 DEBUG [TSLocationManager calculateMedianAccuracy] 3.9
03-06 19:10:22.619 DEBUG [LocationService onLocation]
╔═════════════════════════════════════════════
║ LocationService: location:1004
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 42.674174,23.337693 acc=4 et=+20d16h47m24s115ms alt=643.0 vel=0.0 {Bundle[{requestId=1004, verticalAccuracy=7.8}]}], age: 35ms, time: 1520356223000
 
03-06 19:10:22.629 INFO [TSLocationManager onSingleLocationResult]
  🔵  Acquired motionchange position, isMoving: false
.
.
.
03-06 19:20:31.078 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (65%)
03-06 19:20:31.085 INFO [BackgroundGeolocationService onActivityRecognitionResult]
  ⚠️  Triggered moving due to insufficient device capabilities.
03-06 19:20:31.091 INFO [BackgroundGeolocationService k]
  🔴  Stop heartbeat
03-06 19:20:31.106 INFO [BackgroundGeolocationService a]
  🔵  setPace: false → true
03-06 19:20:31.345 INFO [LocationService onLocation]
  ℹ️  Location availability: true
03-06 19:20:33.808 DEBUG [LocationService onLocation]
╔═════════════════════════════════════════════
║ LocationService: location:1005
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 42.643033,23.334392 acc=96 et=+20d16h57m35s269ms alt=712.0 vel=1.13 bear=13.0 {Bundle[{requestId=1005, verticalAccuracy=192.0}]}], age: 66ms, time: 1520356834162
 
03-06 19:20:33.829 DEBUG [TSLocationManager calculateMedianAccuracy] 3.9
03-06 19:20:33.836 DEBUG [TSLocationManager incrementOdometer] 12333.522
03-06 19:20:34.798 DEBUG [LocationService onLocation]
╔═════════════════════════════════════════════
║ LocationService: location:1005
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 42.642950,23.334129 acc=25 et=+20d16h57m36s291ms alt=698.0 vel=0.0 {Bundle[{requestId=1005, verticalAccuracy=50.0}]}], age: 38ms, time: 1520356835000
 
03-06 19:20:34.809 INFO [TSLocationManager onSingleLocationResult]
  🔵  Acquired motionchange position, isMoving: true
```

**Comment by mihristov** [comment]
Thanks for the fast reply. I'll try what you're suggesting.
Cheers
