### ISSUE TITLE
How does the 'is_moving' property works?

### ISSUE THREAD

**Issue by mihristov** [transistorsoft/cordova-background-geolocation-lt#624]
First - the problem. I need to push locations to my server no matter if the device is moving or not. I need at least one location per minute. Of course, when the device is moving, it works great. Not moving is the tricky part. I tried using the heartbeat event but it didn't fit my needs because it needed 5mins to start working. Now I'm using the motionchange event to keep pushing the last known location to my server (every 5 secs) when the 'is_moving' property is false. It kind of works when you start the plugin, but when you change your activity to 'on_foot' and hold it back to 'still' the motionchange event doesn't seem to reflect the movement (or the lack of it). The 'is_moving' property goes back to false 5-6 mins after that.
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: HTC Desire 820
* Cordova version (`cordova -v`): phonegap build cli-7.1.0 (android 6.3.0)
* Cordova platform version (`cordova platform ls`):
* Plugin config

-    desiredAccuracy: 0,
-    fastestLocationUpdateInterval: 1000,
-    locationUpdateInterval: 1000,
-    foregroundService: true

## Expected Behavior

'is_moving' property go back to false when the activity goes to 'still'
## Actual Behavior

the two doesn't correlate when it comes to not moving 
## Steps to Reproduce

1. start the plugin - it goes to activity 'still', is_moving - false
2. shake the phone - it goes 'on_foot' , 'is_moving' - true
3. hold the phone  still - it goes to activity 'still' - motionchange event is not fired
4. motionchange is fired with 'is_moving' - false after >5mins (after stop-timeout elapsed I guess)

Which puts me in the same situation as if I'm using the heartbeat event. Using watchPosition is not doable as well because I need it to work in background.

Any suggestions?
Thanks
## Debug logs

https://pastebin.com/pwYm2r94

**Comment by christocracy** [comment]
I think you misunderstand with `motionchange` event is.  I suggest you read the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

> I need to push locations to my server no matter if the device is moving or not.

I suggest you abandon attempting to push locations to your server when device is not moving.  This is a *bad* idea.  Why do you think you need this?  The plugin *knows* when the device is moving / stationary.  If the device is stationary, what's the point in sending the same location over and over again?  The device's battery is a precious resource.  What good is your app if you've killed the battery?

**Comment by mihristov** [comment]
I need it because I want to know when a user is active and stopped or just closed the app. I don't think an [interval](https://nodejs.org/api/timers.html#timers_setinterval_callback_delay_args) has anything to do with battery life, but still you're right about that I can simulate the user activity in other ways, not using this plugin.
Thanks.
