### ISSUE TITLE
Location reporting didn't resume after killed & travel exceeded >200m of geofence (but launching Map would kickstart)

### ISSUE THREAD

**Issue by 604abbky** [transistorsoft/cordova-background-geolocation-lt#627]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS 
* OS version: 11.2.1 (15C153)
* Device manufacturer / model: Apple iPad Air 2 MGH72CL/A 
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): ios 4.4.0
* Plugin config
            desiredAccuracy: 0, 
            distanceFilter: 0, 
            stationaryRadius: 25,
            stopOnTerminate: false,
            preventSuspend: true,
            heartbeatInterval: 60, 
            geofenceProximityRadius: 10,
            startOnBoot: true, 
            stopOnStationary: false, 
            debug: false 

## Expected Behavior
Location reporting should resume after killing the app, traveled > 200m

## Actual Behavior
Location reporting didn't resume

## Steps to Reproduce
1. Start the app
2. Check the server side if it got location(moving)/heartbeat(stationary)
3. Killed the app
4. Drove 3.2km (around 20 minutes)
5. Check the server side if there is any update
6.  No new updated since app was killed
7.  **BUT, once I launch the iPad Maps app, then the plugin resumed reporting location**

## Context
Is there any dependency(i.e. Maps, or any other application that uses Location service?) for the geo-fence to wake up cordova-background-geolocation-lt plugin?

**Comment by christocracy** [comment]
Is this the Cellular model of iPad or Wifi only?  If it's the Wifi-only version, yes it won't work as well as a cellular device.

You don't need to "check your server side" to see if it works, just enable `debug: true` and the plugin will *tell you* it's working with sound Fx / local notifications.

>Is there any dependency(i.e. Maps, or any other application that uses Location service?)

No.

You will need Wifi enabled.

**Comment by 604abbky** [comment]
it supports both cellular & wifi, I don't recall if wifi was on/off, will try again with wifi-on.

Previously I had the debug:true, then wondered if that has any effect on any other sensors that would keep it alive.   
I'll also try debug:true to keep my ears to the beeps.

**Comment by christocracy** [comment]
`debug: true` has no effect upon triggering.

**Comment by 604abbky** [comment]
Have tried quite a bit of driving tests with the wifi enabled, seems like it works most of the time.

Came across a few instances that, when driving in rural area that has no wifi hotspots, it didn't seem to wake up based on geofence+200meters, then it would wake up as soon as driving back to urban with wifi hotspots.  Just wondering does geofence+200meters require wifi hotspots?

**Comment by christocracy** [comment]
A cell tower change should cause os to evaluate geofences. 

I drove all [around Iceland](http://www.transistorsoft/lab/iceland) with little problem (largely rural).

**Comment by 604abbky** [comment]
No wonder, there is only 1 tower for the whole city of the Bell network... 

https://www.ertyu.org/steven_nikkel/cancellsites.html?lat=49.171004&lng=-123.114028&zoom=12&type=roadmap&layers=b&pid=0
