### ISSUE TITLE
Tracking stopping while driving (iOS)

### ISSUE THREAD

**Issue by rdantonio** [transistorsoft/cordova-background-geolocation-lt#629]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS
* OS version: 11.2.x (seen on .1, .5, .6)
* Device manufacturer / model: iPhone 6s, iPhone 7, iPhone 6 Plus
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.4
* Plugin config

    activityRecognitionInterval = 10000;
    activityType = Other;
    autoSync = 1;
    autoSyncThreshold = 5;
    batchSync = 1;
    debug = 0;
    desiredAccuracy = 0;
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 100;
    elasticityMultiplier = "0.5";
    enabled = 1;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    isHeartbeatEnabled = 0;
    isMoving = 0;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 2;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 60;
    odometer = 0;
    params = removed;
    pausesLocationUpdatesAutomatically = 1;
    preventSuspend = 1;
    schedule =     (
    );
    schedulerEnabled = 0;
    startOnBoot = 0;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 3;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 5;
    trackingMode = 1;
    url = removed;
    useSignificantChangesOnly = 0;

## Expected Behavior

While driving location tracking should constantly be on

## Actual Behavior

Device seems to be reporting "still" instead of in_vehicle, causing the stop detection to trigger and turn off tracking

## Context

This specific case was using an iPhone 6s, iOS 11.2.5.

The user was driving home. The tracking starts off fine (detecting that they are walking to the car, around 17:42:56) but as soon as they get into their car and start driving, it seems like the activity detection gets stuck in a still state which engages the stop detection system (the delay starts at 17:44:59, then the 5 minute timeout starts 3 minutes later at 17:48:00). During this time the user is driving and points are being tracked, but since in_vehicle never triggers the stopTimeout never gets cancelled.

At 18:01:42 in_vehicle is finally triggered and tracking works as expected from there, but this is nearly 10 miles of highway driving later, which is much more than the 25m-200m stationaryRadius (not sure if stationaryRadius even comes into play here but throwing it out there)

I realize the activity events are provided by iOS, but is there something I'm missing with configurations or otherwise that would help prevent this (besides turning off stop detection altogether)?

As far as the user providing the logs can remember, he was not in any sort of slow traffic. I confirmed that Motion and Fitness and on and allowed, Location is set to Always.

I use the same configuration settings for Android and no similar issues have been reported, this seems isolated to iOS and is not limited to this one user.

Thanks!

## Debug logs

https://pastebin.com/gt2CMMDh

**Comment by christocracy** [comment]
Not much to be here if the MotionActivity API is not reporting `in_vehicle` when the device *is* `in_vehicle`.

Your only option is to disable the motion-activity system.

```
disableMotionActivityUpdates: true
```

`stopTimeout` will no longer be respected and the iOS default system will be used (typically 15min).

**Comment by christocracy** [comment]
Actually, `stopTimeout` will still be respected unless you `disableStopDetection: true`.

The plugin will use pure accelerometer-based stop-detection system, which may not perform any better if the iOS MotionActivity API isn't performing well in your case.

**Comment by rdantonio** [comment]
Thank you for confirming. I will try these options to see if they improve things.

As an alternative, is there a way to manually force the stopTimeout to reset through code? Perhaps if I bind to the location event I can call something like changePace(true) if the location.is_moving is true? For example right before the stopTimeout starts in the logs there's this:


2018-03-22 17:47:19.906 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2018-03-22 17:47:23.070 
📍<+40.16633468,-75.13337256> +/- 30.00m (speed -1.00 mps / course -1.00) @ 3/22/18, 5:47:23 PM Eastern Daylight Time

2018-03-22 17:47:23.071 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: 100.0m | age: 0.0s
╚═══════════════════════════════════════════════════════════

2018-03-22 17:47:23.071 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 65.0

2018-03-22 17:47:23.073 🔵-[Settings incrementOdometer:] 1356.4

2018-03-22 17:47:23.095 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 10203B32-B351-4059-AFD9-1975FBFCA271

2018-03-22 17:47:24.360 ℹ️-[TSDBLogger db_save] Log committed

2018-03-22 17:47:30.082 
📍<+40.16558996,-75.13410722> +/- 10.00m (speed 14.92 mps / course 218.26) @ 3/22/18, 5:47:30 PM Eastern Daylight Time

2018-03-22 17:47:30.082 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: 100.0m | age: 0.0s
╚═══════════════════════════════════════════════════════════

2018-03-22 17:47:30.082 🔵-[TSLocationManager locationManager:didUpdateLocations:] Updated distanceFilter, new: 250.000000, old: 100.000000

2018-03-22 17:47:30.083 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 65.0

2018-03-22 17:47:30.085 🔵-[Settings incrementOdometer:] 1460.1

2018-03-22 17:47:30.112 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 5A86AFE9-165F-4619-BD56-C13B645B059D

2018-03-22 17:47:37.996 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2018-03-22 17:47:45.762 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2018-03-22 17:47:48.870 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2018-03-22 17:47:50.455 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2018-03-22 17:48:00.085 🔵-[TSLocationManager beginStopDetection] ⏲Stop-timeout engaged: 300 s...

2018-03-22 17:48:00.089 ✅-[BackgroundTaskManager createBackgroundTask] 103

2018-03-22 17:48:00.089 ℹ️-[BackgroundTaskManager startKeepAlive] 

2018-03-22 17:48:00.096 🔴-[TSLocationManager stopUpdatingLocation] 

2018-03-22 17:48:24.450 ℹ️-[TSDBLogger db_save] Log committed

It got 2 locations before the activity system decided to stop updating locations, but if changePace forces it back to a moving state it might help avoid this?

**Comment by rdantonio** [comment]
Sorry, I meant reset the stopDetectionDelay, not stopTimeout

**Comment by christocracy** [comment]
>As an alternative, is there a way to manually force the stopTimeout to reset through code? 

No.

>Perhaps if I bind to the location event I can call something like changePace(true) if the location.is_moving is true? For example right before the stopTimeout starts in the logs there's this:

if you execute `changePace(true)` while the plugin is already `is_moving == true`, it will be ignored.

However, there is *something* I could do.  On Android, in order to compensate for inferior devices with missing sensors (typically gyroscope / magnetometer), the plugin *does* analyze incoming locations during stop-detection.  This would only work during `stopDetectionDelay`, since the iOS turns **off** location-services during the `stopTimeout` timer.

This Android code from the plugin should speak for itself:
```java
public void onLocationResult(LocationResult result) {
        if (shouldStopAfterElapsedMinutes()) {
            stopAfterElapsedMinutes();
            return;
        }

        // Analyze recorded locations for movement while stop-detection is engaged.

        // If we're not stopped, nothing to do here.
        if (stoppedAtLocation == null) { return; }

        Location location = result.getLastLocation();
        float pointDistance = location.distanceTo(stoppedAtLocation);
        float uncertainDistance = pointDistance - stoppedAtLocation.getAccuracy() - location.getAccuracy();

        TSLog.logger.info(TSLog.info("Distance from stoppedAtLocation: " + uncertainDistance));
        // How far have we moved from stopedAtLocation?
        if (uncertainDistance > TSConfig.getInstance(this).getStationaryRadius()) {
            resetStopTimer();
        }
    }
```

**Comment by rdantonio** [comment]
This sounds good as well. I believe it would cover my scenario at least since between the stopDetectionDelay starting and stopTimeout starting there were about 6 or 7 points that likely would have triggered the reset in the code you provided.

**Comment by rdantonio** [comment]
@christocracy was just wondering if this is something that might be available either here or in the private repo at some point soon (don't currently have access to private but if it's there would be willing to upgrade for another year). Thanks!

**Comment by christocracy** [comment]
It will be implemented in the private repo some time soon.  It won't appear here in the free repo for at least 6 months.
