### ISSUE TITLE
Interval Settings

### ISSUE THREAD

**Issue by danielstrickland** [transistorsoft/cordova-background-geolocation-lt#63]
I've purchased a solo license, but have just been testing so far with this repo (the free iOS version). I'm using an iPhone 6S running 9.2.1.

I'm trying to reduce the frequency with which the app POSTs to my server.

Here are my config settings:
{
desiredAccuracy: 0
stationaryRadius: 50,
distanceFilter: 50,
disableElasticity: false, 
locationUpdateInterval: 60000,
minimumActivityRecognitionConfidence: 80,  
fastestLocationUpdateInterval: 60000,
activityRecognitionInterval: 60000, 
url: [myserver],
method: 'POST',
batchSync: true,
autoSync: true,   
}

My expectation was that the app would only POST to my server once every 60 seconds (since all the intervals were set to 60000). Instead, the app posted about every 7-15 seconds.  The output below shows the distance and time between points logged by the server - this was in a test drive across town for a few miles using an actual device (not the simulator).

Distance: 2.895mi Time: 151sec
Distance: 11.059mi Time: 557sec
Distance: 0.161mi Time: 7sec
Distance: 0.198mi Time: 10sec
Distance: 0.202mi Time: 10sec
Distance: 0.233mi Time: 11sec
Distance: 0.065mi Time: 10sec
Distance: 1.401mi Time: 62sec
Distance: 0.166mi Time: 7sec
Distance: 0.062mi Time: 14sec
Distance: 0.432mi Time: 10sec
Distance: 0.25mi Time: 12sec
Distance: 0.231mi Time: 11sec
Distance: 0.169mi Time: 8sec
Distance: 0.021mi Time: 14sec
Distance: 0.499mi Time: 11sec
Distance: 0.227mi Time: 11sec

Am I missing something?

**Comment by christocracy** [comment]
Native location APIs are ultimately distance-based, not time-based;
throttled by distanceFilter.

Your distanceFilter: 50 means you're recording a location every 50 meters

On Monday, February 1, 2016, danielstrickland <notifications@github.com>
wrote:

> I've purchased a solo license, but have just been testing so far with this
> repo (the free iOS version). I'm using an iPhone 6S running 9.2.1.
>
> I'm trying to reduce the frequency with which the app POSTs to my server.
>
> Here are my config settings:
> {
> desiredAccuracy: 0
> stationaryRadius: 50,
> distanceFilter: 50,
> disableElasticity: false,
> locationUpdateInterval: 60000,
> minimumActivityRecognitionConfidence: 80,
>
> fastestLocationUpdateInterval: 60000,
> activityRecognitionInterval: 60000,
> url: [myserver],
> method: 'POST',
> batchSync: true,
> autoSync: true,
>
> }
>
> My expectation was that the app would only POST to my server once every 60
> seconds (since all the intervals were set to 60000). Instead, the app
> posted about every 7-15 seconds. The output below shows the distance and
> time between points logged by the server - this was in a test drive across
> town for a few miles using an actual device (not the simulator).
>
> Distance: 2.895mi Time: 151sec
> Distance: 11.059mi Time: 557sec
> Distance: 0.161mi Time: 7sec
> Distance: 0.198mi Time: 10sec
> Distance: 0.202mi Time: 10sec
> Distance: 0.233mi Time: 11sec
> Distance: 0.065mi Time: 10sec
> Distance: 1.401mi Time: 62sec
> Distance: 0.166mi Time: 7sec
> Distance: 0.062mi Time: 14sec
> Distance: 0.432mi Time: 10sec
> Distance: 0.25mi Time: 12sec
> Distance: 0.231mi Time: 11sec
> Distance: 0.169mi Time: 8sec
> Distance: 0.021mi Time: 14sec
> Distance: 0.499mi Time: 11sec
> Distance: 0.227mi Time: 11sec
>
> Am I missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/63>
> .
>


-- 
Snet form Gmail Mobile

**Comment by danielstrickland** [comment]
Thanks for the reply.

So my only option is to change distanceFilter to something larger?

What does locationUpdateInterval do?

**Comment by christocracy** [comment]
Well, speaking of Android only, distanceFilter takes precedence over
locationUpdateInterval.  If you set distanceFilter: 0,
locationUpdateInterval should be respected (roughly; Android docs state
that locationUpdateInterval may not be exactly respected; could be faster
or slower).

However, iOS is strictly distance-based.  It only understands
distanceFilter.  It does not understand locationUpdateInterval.


On Monday, February 1, 2016, danielstrickland <notifications@github.com>
wrote:

> Thanks for the reply.
>
> So my only option is to change distanceFilter to something larger?
>
> What does locationUpdateInterval do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/63#issuecomment-178220155>
> .
>


-- 
Snet form Gmail Mobile

**Comment by danielstrickland** [comment]
Got it. Thanks.
