### ISSUE TITLE
Can I change the message LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION ?

### ISSUE THREAD

**Issue by Chopstickswide** [transistorsoft/cordova-background-geolocation-lt#633]
Could I change this msg as i18n?

**Comment by christocracy** [comment]
Edit the string in your `config.xml`.  Remove(with `--nosave`) / re-add the plugin

```
$ cordova plugin remove cordova-background-geolocation-lt --nosave
$ cordova plugin add cordova-background-geolocation
```

**Comment by Chopstickswide** [comment]
Could I add multiple text msgs like English, Korean and Japanese?
and display as the setting of the phone?
