### ISSUE TITLE
[QUESTION] Detect user all day with minimum battery and location service usage

### ISSUE THREAD

**Issue by matheusdavidson** [transistorsoft/cordova-background-geolocation-lt#634]
Hi There, just got your plugin and i have a question.

I need to track the user all day, even with the app closed/killed, but i really don't need to get precise results. Testing the sample app provided by you, on ios, with many different configurations i could see that the location service icon would show even while i'm not moving(tested in freedrive and no moving mode), so i want to know:

- What is the best configuration to get location even with the app closed/killed without showing location service icon(IOS) or the notification(Android) all day long?

**Comment by christocracy** [comment]
On iOS, you’ll see a “hollow” icon while in stationary state meaning gps is not on.

The plugin is only monitoring a geofence around the last known position.  The exit of this “stationary geofence” will trigger aggressive location tracking.  It’s the monitoring of this geofence responsible for the “hollow location icon”

If you only need location periodically (ie every 500-1000 meters), configure useSignificantChangesOnly: true.

**Comment by matheusdavidson** [comment]
Lets say i only want to track the user every 3000 meters, if i set useSignificantChangesOnly and put stationary config, but still want the app to get location when the app is killed, will android still show the notification bar always/every time?

**Comment by christocracy** [comment]
`useSignificantChangesOnly` is iOS only.  

I suggest you have a look at my [cordova-plugin-background-fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch) (included as a dependency of this plugin).  You're free to execute `BackgroundGeolocation#getCurrentPosition` in the fetch callback.

As long as the Android plugin is not enabled (ie: `#start`), the service and corresponding notifications will be inactive.

**Comment by matheusdavidson** [comment]
What about the schedule feature, wouldn't it be better to schedule some time during the day rather then using background-fetch? Will schedule feature work when app is killed?

**Comment by christocracy** [comment]
on iOS, the scheduler *uses* background-fetch to periodically evaluate the schedule.

on iOS, the scheduler maintains a listener on Significant Location Changes (SLC) API.  When the app is terminated, the plugin SLC listener is persisted by the OS.  If the device moves 500-1000 meters while the app is terminated, an SLC event will cause your app to reboot to service that event.  The plugin will evaluate the schedule at that time.

If an iOS app is configured with a schedule then terminated, your app will never re-awaken until the device moves 500-1000 meters.  If the device sits in same location for a week, the scheduler will never trigger.

**Comment by matheusdavidson** [comment]
Very good, thats exactly what i was looking for!!

Thank you for answering me and for the fast support, i appreciate!
