### ISSUE TITLE
Plugin usage after the first year

### ISSUE THREAD

**Issue by mihristov** [transistorsoft/cordova-background-geolocation-lt#635]
Given that I have purchased the cordova plugin's starter plan and it expires after the first year, can I continue to use it as a private plugin? Will I be able to build it and is the 'License validation failure' thing going to pop?
Thanks

**Comment by christocracy** [comment]
- License keys **never** fail to unlock the plugin
- What you lose access to is the private repo where latest updates land first and attention to support issues is given *priority*.
- The public version in this repo (and corresponding [version on npm](https://www.npmjs.com/package/cordova-background-geolocation-lt) is *mirrored* from the private version about every 3 months.
