### ISSUE TITLE
Can't make it work on Ionic

### ISSUE THREAD

**Issue by HamzaLJ** [transistorsoft/cordova-background-geolocation-lt#636]
## Your Environment
* Plugin version: Just downloaded it "2.10.1"
* Platform: **Android**
* OS version: 7.0.1
* Device manufacturer / model: Motorola
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 6.3.0
* Plugin config
`
      debug: true,
     desiredAccuracy: 0,
     distanceFilter: 3,
     mock:true,
     stopOnTerminate: false,
`

## Expected Behavior
Should at least make some sounds, show messages

## Actual Behavior
Does not show any message/make any sound, like the plugin is not installed at all.

## Steps to Reproduce
my current file is the same one as the GIST provided on the documentation.

## Context
Just started using the plugin, initial tests.

## Debug logs
When runing `adb logcat` nothing is being generated, here is what I see : 

--------- beginning of main
--------- beginning of system

**Comment by HamzaLJ** [comment]
Here is the code :  

  
       ionViewDidLoad(){
         this.platform.ready().then(this.configureBackgroundGeolocation.bind(this));
         }     

         configureBackgroundGeolocation() {

        // 1. Get a reference to the plugin
        this.bgGeo = (<any>window).BackgroundGeolocation;

        // 2. Listen to events
        this.bgGeo.on('location', this.onLocation.bind(this));
        this.bgGeo.on('motionchange', this.onMotionChange.bind(this));

        // 3. Configure it.
        this.bgGeo.configure({
          debug: true,
          desiredAccuracy: 0,
          distanceFilter: 3,
          mock:true,
          stopOnTerminate: false,
        }, (state) => {
          this.bgGeo.start();
        });

      }

     onLocation(location, taskId) {
     console.log('############ ON LOCATION ###########')
      }

**Comment by christocracy** [comment]
Looks fine.  There must be logs from `$ adb logcat` when you boot your app.

Are you observing JavaScript console for JavaScript errors?

**Comment by HamzaLJ** [comment]
I see only this when running `adb logcat` :

--------- beginning of main
--------- beginning of system

No errors reported on the JS console

**Comment by christocracy** [comment]
Did you configure your Android device for debug mode and enabled `[x] USB Debugging`?

There should be a constant stream of logs, not just from *your* app but *all* apps on the device.

**Comment by HamzaLJ** [comment]
Of course already enabled USB debugging, I can see the logs of my apps, but no logs of BackgroundGeolocation plugin

**Comment by christocracy** [comment]
And close all Javascript consoles in browser.  Those Browser debugger instances can take over adb connection.

**Comment by HamzaLJ** [comment]
Seems to be working fine now, I have mauron85 fork installed on the same time too. I had to delete it and now it works, fine.
