### ISSUE TITLE
Can't get coords after terminating the app

### ISSUE THREAD

**Issue by HamzaLJ** [transistorsoft/cordova-background-geolocation-lt#637]
## Your Environment
* Plugin version: 2.1.0
* Platform: Android 
* OS version: 7.0.1
* Device manufacturer / model: Motorola
* Cordova version (`cordova -v`): 7.1.0
* Plugin config
  
          debug: true,
          desiredAccuracy: 0,
          distanceFilter: 3,
          mock:true,
          stopOnTerminate: false,

## Expected Behavior
Should get coords even after terminating the app.

## Actual Behavior
After terminating the app, the app does seems to get coords anymore.

## Debug logs
- Android: $ adb logcat

04-01 15:54:50.588  5583  6561 D TSLocationManager: ║ LocationService: location:1007
04-01 15:54:50.588  5583  6561 D TSLocationManager: ╠═════════════════════════════════════════════
04-01 15:54:50.588  5583  6561 D TSLocationManager: ╟─ 📍  Location[fused 35.778828,-5.819935 acc=31 et=+19h50m22s534ms alt=0.0 vel=13.89 bear=164.0 mock {Bundle[{mockLocation=true, requestId=1007, verticalAccuracy=62.616}]}], age: 115ms, time: 1522594490456
04-01 15:54:50.611  5583  6561 I TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
04-01 15:54:50.611  5583  6561 I TSLocationManager:   🔵  Acquired providerchange position
04-01 15:54:50.636  5583  6561 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 45.863
04-01 15:54:50.672  5583  5636 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
04-01 15:54:50.689  5583  6563 I TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO persist] 
04-01 15:54:50.689  5583  6563 I TSLocationManager:   ✅  INSERT: 953fe474-1f21-4e4c-aca6-c79e31fcdfdd
04-01 15:55:29.995  5583  6862 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
04-01 15:55:30.030  5583  5636 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (48%)
04-01 15:55:30.048  5583  5636 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO

**Comment by christocracy** [comment]
You have to *move*.  The plugin records *only* when the device is moving.  When the device is completely stationary, location-services are off.

If you're simulating location, shake the device *vigorously* to simulate walking while observing `$ adb logcat -s TSLocationManager`.

**Comment by HamzaLJ** [comment]
@christocracy got you, thanks for the clarification.

**Comment by christocracy** [comment]
Btw, you can easily configure the plugin to post to my test-server so you can quickly visualize your tracking.  See [this blog entry](https://shop.transistorsoft.com/blogs/news/background-geolocation-console)
