### ISSUE TITLE
Question - How to get current coords inside ".configure" ?

### ISSUE THREAD

**Issue by HamzaLJ** [transistorsoft/cordova-background-geolocation-lt#638]
I would like to update the DB with the new coords even if the app is closed and only when the user is moving, for that I have the below:

## Your Environment
* Plugin version: 2.1.0
* Platform: Android 
* OS version: 7.0.1
* Device manufacturer / model: Motorola
* Cordova version (`cordova -v`): 7.1.0
* Plugin config
  
          debug: true,
          desiredAccuracy: 0,
          distanceFilter: 3,
          mock:true,
          stopOnTerminate: false,
          url: posrURL,
           method: "POST",
           autoSync: true,
           maxDaysToPersist: 3,
           headers: {  // <-- Optional HTTP headers
              'Application-Id': 'DiPbYHVlTPmk',
              'REST-API-Key', 'vphdgoCNYQm4V'
           },
           params: {   // <-- How to get latitude and longitude here so I can post it to the DB even when the app is terminated ?
                "currentLocation": { "__type": "GeoPoint", "latitude": currentLatLng.lat, "longitude": currentLatLng.lng }, 
                "bearing": bearing, 
                  "speed": speed 
           }

As I know I can get the coords inside 'onLocation', but the the above case I don't have a clue

**Comment by christocracy** [comment]
When the plugin first boots and is enabled, it will *always* record a location and fire the `location` event.

You're always free to use the `#getCurrentPosition` method.

```javascript
bgGeo.configure(config, (state) => {
  bgGeo.getCurrentPosition((location) => {
    console.log('- current position: ', location);
  }, (error) => {
    console.log('- current position error: ', error);
  });
});

**Comment by HamzaLJ** [comment]
What happens if the app is terminated and the user is moving, will it get always new coords ?

**Comment by christocracy** [comment]
Yes.  The plugin’s Android service remains running.

Try it yourself.  Terminate your app then shake the device vigorously for about 10s while observing logcat.

**Comment by HamzaLJ** [comment]
Okay, sounds good. 
However I didn't figure out where to put `bgGeo.getCurrentPosition((location) => {})`

    this.bgGeo.configure({    debug: true,
          desiredAccuracy: 0,
          distanceFilter: 3,
          mock:true,
          stopOnTerminate: false,
          url: posrURL,
           method: "POST",
           autoSync: true,
           maxDaysToPersist: 3,
           headers: {  // <-- Optional HTTP headers
              'Application-Id': 'DiPbYHVlTPmk',
              'REST-API-Key', 'vphdgoCNYQm4V'
           },
           params: {   
                "currentLocation": { "__type": "GeoPoint", "latitude": currentLatLng.lat, "longitude": currentLatLng.lng }, 
                "bearing": bearing, 
                  "speed": speed 
           }}, (state) => {
          this.bgGeo.start();
        });

**Comment by christocracy** [comment]
In the callback to `#configure`
As in my [comment above](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/638#issuecomment-377798535).

And get rid of those `params` you’re providing to `#configure`.

If you want to provide extra data to your `#getCurrentPosition` request, provide `extras` to the getCurrentPosition request arguments.  See docs for `#getCurrentPosition`.

**Comment by HamzaLJ** [comment]
I couldn't find anything related to `getCurrentPosition`, can you please provide a direct link?

**Comment by christocracy** [comment]
The README is not the API docs.  The [API docs](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/README.md#books-api-documentation) are *linked to* in the README.
