### ISSUE TITLE
Any Example code for C# Wcf web service to get data pushed by the plugin to server ?

### ISSUE THREAD

**Issue by thomas550i** [transistorsoft/cordova-background-geolocation-lt#640]
Any Example code for C# Wcf web service to get data pushed by the plugin to server ?

**Comment by christocracy** [comment]
Sorry, I don't know anything about C#.  The plugin posts its JSON in the **body** of the HTTP Request.  It doesn't post like a web-form.

You'll want to retrieve the "body content" of the HTTP request.  That will be a JSON string.  You should parse this JSON and turn it into an Object.

**Comment by thomas550i** [comment]
is there any way we have to follow for HTTPS web url ? working fine in HTTP but not working in HTTPS ?

**Comment by christocracy** [comment]
There's nothing special involved with HTTPS as long as you're not using a self-signed certificate.
