### ISSUE TITLE
Question: how to configure the plugin to send the user's location even if the user is not moving

### ISSUE THREAD

**Issue by PITG-support** [transistorsoft/cordova-background-geolocation-lt#641]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 6.0.0
* Device manufacturer / model: Samsung Galaxy S5
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config

## Expected Behavior
The app should always send their location even if its always the same (if possible every 10-15 minutes if the user is not moving)

## Actual Behavior
The app stops sending the locations if the user is still on the same position

## Steps to Reproduce
Our plugin configuration:

```
private pluginConfig = {
        //Common options
        desiredAccuracy: 10,
        //distanceFilter: 10,
        distanceFilter: 0,
        disableElasticity: false,
        stopOnStationary: false,
        
        //IOS only options
        stationaryRadius: 25,
        locationAuthorizationAlert: {
            titleWhenNotEnabled: 'Le service de Géolocalisation est éteint',
            titleWhenOff: 'La Géolocalisation est désactivée en arrière plan.',
            instructions: 'Pour recevoir les notifications tu dois réactiver la géolocalisation dans Réglages > App Name > Toujours activé',
            cancelButton: 'Annuler',
            settingsButton: 'Réglages'
        },
        //Android only options
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 1000,
        allowIdenticalLocations: true,

        //Activity Recognition Common Options
        activityRecognitionInterval: 10000,
        stopTimeout: 12*60,

        //HTTP & Persist options
        autoSync: true,
        url: ENV.API_ENDPOINT + "/geoloc",
        headers: {
            "Authorization": ""
        },
        
        //Application common options
        stopOnTerminate: true,
        startOnBoot: false,
        heartbeatInterval: 60,
        debug: false,
        
        //Application android options
        foregroundService: true,
        notificationColor: "#00A7F7",
        notificationTitle: "App Name",
        notificationText: "Location Service activated",
        notificationSmallIcon: "icon",
        notificationLargeIcon: "icon",
        
        deferTime: 0,
        
    };
```

## Context
Im trying to make an app to send the positions of the users even if they are always in the same position (if possible every 10-15 minutes)

**Comment by christocracy** [comment]
The plugin includes [`cordova-plugin-background-fetch`](https://github.com/transistorsoft/cordova-plugin-background-fetch) as a dependency.  It's already available to you at `window.BackgroundFetch`.

Simply perform a `BackgroundGeolocation#getCurrentPosition` in your `BackgroundFetch` callback.

**Comment by iamjoyce** [comment]
Alternatively, can we use `changePace` to set the movement as `moving`? Will `BackgroundGeolocation` initiate a call + sync data to server?

**Comment by christocracy** [comment]
That would not be a good idea.  When you `changePace(true)`, the plugin turns on location-services and begins consuming battery.  The `stopTimeout` timer will engage and the plugin will automatically `changePace(false)` when the `stopTimeout` timer expires.
