### ISSUE TITLE
Locations not posting to url

### ISSUE THREAD

**Issue by MrXyfir** [transistorsoft/cordova-background-geolocation-lt#642]
## Your Environment
* Plugin version: Latest
* Platform: iOS
* OS version: 11.2.2
* Device manufacturer / model: iPhone 6s
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.3.1
* Plugin config

```xml
  <plugin name="cordova-background-geolocation-lt">
    <variable name="LICENSE" value="YOUR_LICENSE_KEY" />
    <variable name="GOOGLE_API_VERSION" value="11.6.0" />
    <variable name="APPCOMPAT_VERSION" value="26.1.0" />
    <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Always use is required for background location tracking" />
    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location tracking is required" />
    <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location tracking is required" />
    <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location tracking only when the device is detected to be moving" />
  </plugin>
```

## Expected Behavior
Locations are posted to url

## Actual Behavior
Locations are not posted to url

---

```js
// Values set low on purpose for testing
// Yes, this is in an async function
// No errors are given, just the location updates are never sent to the url
if (window.BackgroundGeolocation) {
  await window.BackgroundGeolocation.ready({
    // Geolocation config
    desiredAccuracy: 0,
    distanceFilter: 1,
    stationaryRadius: 1,
    // iOS
    useSignificantChangesOnly: true,
    locationAuthorizationRequest: 'Always',
    // Android
    locationUpdateInterval: 6 * 1000,
    allowIdenticalLocations: false,
    fastestLocationUpdateInterval : 6 * 1000,
    // Activity Recognition config
    activityRecognitionInterval: 1 * 1000,
    stopTimeout: 5,
    // Application config
    debug: true,
    stopOnTerminate: false,
    startOnBoot: true,
    // HTTP / SQLite config
    autoSync: true,
    url: 'http://postb.in/G8XGnHoD',
    method: 'POST',
    params: {
      timezone: moment().utcOffset() / 60,
      authToken: localStorage.authToken
    }
  });
  window.BackgroundGeolocation.start();
}
```

**Comment by christocracy** [comment]
Are you using php?  Are you observing the plugin logs in XCode?

**Comment by MrXyfir** [comment]
Locations are being sent to postb.in so I can view the entire request. They're not showing up.

Using PhoneGap Build so no XCode.

**Comment by MrXyfir** [comment]
Yes, but it can accept a JSON request body. We've tested that.

**Comment by christocracy** [comment]
For php, see https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/2

**Comment by christocracy** [comment]
The plugin login every http request and response from your server in its logs.

See [Debugging Wiki](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

The best dev experience is to observe the plugin logs in real time in XCode.  If you don’t have a Mac, get one.  Your development experience will explode in a good way.

PhoneGap build is a *deployment* service, not a *development* service.

**Comment by MrXyfir** [comment]
Sending to your server. Nothing.

http://tracker.transistorsoft.com/locations/MrXyfir

I see the spinner going around in the top left when I close the app.

**Comment by christocracy** [comment]
Fetch the plugin logs (see wiki linked above).  The answer is in the logs.

**Comment by MrXyfir** [comment]
Logs were empty last I checked but I'll check again and report back.

**Comment by christocracy** [comment]
You need to provide a logLevel (default is NONE).

Also read the docs carefully for #ready method.

Your config is applied ONLY AT FIRST BOOT.

During development, provide config `reset: true` and the plugin will apply the supplied defaultConfig with each launch.

**Comment by MrXyfir** [comment]
Logs were indeed empty.

> Your config is applied ONLY AT FIRST BOOT.

**That** is probably my issue... I don't know how I missed that in the docs. Read through it for like 2 hours.

**Comment by MrXyfir** [comment]
Yep. I'm an idiot. My apologies.

**Comment by christocracy** [comment]
To view your locations at `tracker.transistorsoft.com`, in browser, don't use `/locations/username`.  It's just `/username`

![](https://dl.dropboxusercontent.com/s/08bebf1pdtxvcyo/Screenshot%202018-04-09%2017.44.36.png?dl=1)

**Comment by christocracy** [comment]
You *POST* to `/locations/username`.  In browser, you `GET /username`.

I've been meaning to add a redirect.

**Comment by MrXyfir** [comment]
Thanks for your help Chris, I got iOS working.

Is there any way I can get a one-day license key so I can test that Android works with our current setup? If it worked we'd purchase an actual license.

**Comment by christocracy** [comment]
There is no ability to provide temp license.

Simply build your app for DEBUG.  License is enforced in RELEASE build only.

If you’re not building Android locally, stop messing around and do so now.  You’re wasting valuable time and money using PhoneGap as a dev service.

**Comment by MrXyfir** [comment]
I understand, I'll see what I can do. I've been trying to avoid it given how little I need to mess with the Cordova API but I guess it's unavoidable.

**Comment by christocracy** [comment]
How long does it take you to make a simple change to your Javascript app and see the result on a device with PGB?  60s?

Running your app with `--livereload`, you can see the result in a couple of *seconds*.  Get the Android SDK installed on your machine.
