### ISSUE TITLE
Time-sensitive geofences

### ISSUE THREAD

**Issue by CaffeinatedAndroid** [transistorsoft/cordova-background-geolocation-lt#644]
Question/Feature request:
I'm looking to have geofences only trigger-able within a specific date-time window, and also have them expire (by default at the end of a date-time window, if specified).

Is this already possible, and if not, is this something that could be implemented?

Other people who may use/benefit from this feature could filter HTTP requests server-side, but I'm working with a contextually decoupled service. I could also do manual client-side adding and removing of geofences with a bespoke scheduler, but this cannot be done whilst the app is in the background (leading to data loss, in my instance).

## Expected Behavior
When adding a geofence, be able to configure a date-time window (start and end datetime objects) that the geofence HTTP request should be fired within, otherwise a geofence trigger should be ignored.

**Comment by CaffeinatedAndroid** [comment]
I note the existence of the `schedule`:
https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#schedule
https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-array-schedule-undefined

This does not work for my context, as it is an all-or-nothing schedule. Though it may be sufficient for someone else that stumbles across this issue.

**Comment by CaffeinatedAndroid** [comment]
Another configure option (perhaps I should create a separate issue) would be to only fire a geofence event once, auto-removing that geofence after it fires e.g after an on-enter event.

**Comment by christocracy** [comment]
Sorry, missed this.  Sounds like a good idea.
