### ISSUE TITLE
update plugin after app crash: onLocation is not a function

### ISSUE THREAD

**Issue by helpynet** [transistorsoft/cordova-background-geolocation-lt#647]
## Your Environment
* Plugin version: latest
* Platform:  Android
* OS version: Android 7.
* Device manufacturer / model: Samsung Galaxy S7
* Cordova version (`cordova -v`):  7.1.0
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config 

## Expected Behavior

The app constantly crash on start. After we update the cordova-background-geolocation-lt plug-in (remove  - add android platform again), the app sould be work properly

## Actual Behavior

Error on console:
cordova.js:313 Error in Success callbackId: File1039486570 : TypeError: o.onLocation is not a function

## Steps to Reproduce

1. config.xml: GOOGLE_API_VERSION: 11.6, APPCOMPAT_VERSION: 26.1.0 - constant crash at appstart
2. Update the  cordova-background-geolocation-lt plug-in from git
3.  config.xml: GOOGLE_API_VERSION: 11.8, APPCOMPAT_VERSION: 27.0.0 - onLocation is not function

## Context

Fix the app crash at start.

**Comment by christocracy** [comment]
It's correct.  There's no longer a method `onLocation` (or `on{Anything}`).  These methods were never documented.

The way to listen to events is with method [`#on(eventName, callback)`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#adding-event-listeners-on)

**Comment by helpynet** [comment]
We fix the onLocation issue.
The app crash at the start again.

**Comment by christocracy** [comment]
If you have a "crash", there must be a stack-trace in `$ adb logcat`.  Post it here.

**Comment by helpynet** [comment]
Sorry, we find the solution. The problem was the push plugin started immediately after the geolocation.
