### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by t2wu** [transistorsoft/cordova-background-geolocation-lt#648]
Crashes when running the app

## Your Environment
* Plugin version: The latest from github. (2.11.0-beta.2?)
* Platform: Android
* OS version: Android 8.0.0
* Device manufacturer / model: Samsung Galaxy S9
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.4.0
* Plugin config

## Expected Behavior
Run without crash.

## Actual Behavior
Crashed, and if I read the log correctly, it may be related to the plugin. However, I don't know if I have read it correctly.

## Steps to Reproduce
I have no idea. Just happened.

## Context
Nothing in particular, just launch and run.

## Debug logs

> --------- beginning of crash
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: FATAL EXCEPTION: main
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: Process: com.bxxxxxxxxx.xxxxxxxxxxx, PID: 10045
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at java.lang.reflect.Method.getParameterTypes(Method.java:179)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:151)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:12)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:959)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:100)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/com.bxxxxxxxxx.xxxxxxxxxxx-jytWDnpvXT0EVOJfTYxeCw==/base.apk"],nativeLibraryDirectories=[/data/app/com.bxxxxxxxxx.xxxxxxxxxxx-jytWDnpvXT0EVOJfTYxeCw==/lib/arm, /data/app/com.bxxxxxxxxx.xxxxxxxxxxx-jytWDnpvXT0EVOJfTYxeCw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 04-17 14:31:34.201 10045 10045 E AndroidRuntime: 	... 22 more

**Comment by christocracy** [comment]
Paste your platforms/android/project.properties

**Comment by t2wu** [comment]
Here it is:

> # This file is automatically generated by Android Tools.
> # Do not modify this file -- YOUR CHANGES WILL BE ERASED!
> #
> # This file must be checked in Version Control Systems.
> #
> # To customize properties used by the Ant build system edit
> # "ant.properties", and override values to adapt the script to your
> # project structure.
> #
> # To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
> #proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
> # Project target.
> target=android-26
> android.library.reference.1=CordovaLib
> cordova.gradle.include.1=cordova-plugin-badge/brilonglock-badge.gradle
> cordova.gradle.include.2=cordova-plugin-bluenet-dfu/brilonglock-build-extras.gradle
> cordova.gradle.include.3=cordova-plugin-firebase/brilonglock-build.gradle
> cordova.system.library.1=com.android.support:support-v4:24.1.1+
> cordova.gradle.include.4=cordova-plugin-local-notification/brilonglock-localnotification.gradle
> cordova.system.library.2=com.google.gms:google-services:+
> cordova.system.library.3=com.google.android.gms:play-services-tagmanager:+
> cordova.system.library.4=com.google.firebase:firebase-core:+
> cordova.system.library.5=com.google.firebase:firebase-messaging:+
> cordova.system.library.6=com.google.firebase:firebase-crash:+
> cordova.system.library.7=com.google.firebase:firebase-config:+
> cordova.system.library.8=com.google.firebase:firebase-perf:+
> cordova.system.library.9=com.android.support:support-v4:26.+
> cordova.gradle.include.5=phonegap-plugin-barcodescanner/brilonglock-barcodescanner.gradle
> cordova.gradle.include.6=cordova-plugin-buildinfo/brilonglock-BuildInfo.gradle
> cordova.gradle.include.7=cordova-plugin-background-fetch/brilonglock-build.gradle
> cordova.system.library.10=com.google.android.gms:play-services-location:11.8.0
> cordova.gradle.include.8=cordova-background-geolocation-lt/brilonglock-build.gradle
> cordova.system.library.11=com.google.android.gms:play-services-location:11.8.0
> cordova.system.library.12=com.android.support:appcompat-v7:27.0.0

**Comment by christocracy** [comment]
- All `com.google.gms` / `com.google.firebase` dependencies must import the same version.  Avoid `:+`.  Align them all to `11.8.0`.
- All `com.android.support` dependencies must be aligned to the same version.  Set them all to `27.0.0`.

**Comment by t2wu** [comment]
I see. Got it.

Right now these just appear when install the plugins. How do I peg them all to the same version though? Do I do config them in config.xml?

**Comment by christocracy** [comment]
Each plugin is responsible for providing configuration variables to allow you to do this.  You'll have to consult with each plugin which imports play-services / firebase.  

background-geolocation provides the following:
- [`GOOGLE_API_VERSION`](https://github.com/transistorsoft/cordova-background-geolocation-lt#variable-google_api_version-1160)
- [`APP_COMPAT_VERSION`](https://github.com/transistorsoft/cordova-background-geolocation-lt#variable-appcompat_version-2700)

`phonegap-plugin-push` supports similar variables.  I have no idea about other plugins.

Firebase and Google Play Services version **must** be aligned to the same version.

**Comment by christocracy** [comment]
When you see plugins importing Firebase / Google Play Services version using wildcard `+`, you will have problems.

When you see multiple version of `com.android.support` libraries, you will have problems.

**Comment by t2wu** [comment]
I decided just to mess with plugin.xml from the plugins to solve these issues.

By all com.google.gms / com.google.firebase dependencies, do you mean like both com.google.gms:google-services and com.google.android.gms:play-services-location?

The reason I asked is that it seems to have trouble fetching `com.google.gms:google-services:11.8.0`. It seems like the latest is 3.1.1? https://mvnrepository.com/artifact/com.google.gms/google-services.

And set all `com.google.firebase` such as `com.google.firebase:firebase-core` and `com.google.firebase:firebase-crash` and to 11.8.0? Currently they are "+".

**Comment by t2wu** [comment]
I have now changed all `com.google.firebase:*` stuff to 11.8.0 but it now won't build:

```
platforms/android/src/org/apache/cordova/firebase/FirebasePluginMessagingService.java:47: error: cannot access zzbfm
        if (remoteMessage.getNotification() != null) {
                         ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

platforms/android/project.properties is now:

```
target=android-26
android.library.reference.1=CordovaLib
cordova.gradle.include.1=cordova-android-support-gradle-release/brilonglock-cordova-android-support-gradle-release.gradle
cordova.gradle.include.2=cordova-plugin-background-fetch/brilonglock-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/brilonglock-build.gradle
cordova.gradle.include.4=cordova-plugin-badge/brilonglock-badge.gradle
cordova.gradle.include.5=cordova-plugin-bluenet-dfu/brilonglock-build-extras.gradle
cordova.gradle.include.6=cordova-plugin-buildinfo/brilonglock-BuildInfo.gradle
cordova.system.library.3=com.android.support:support-v4:27.0.0
cordova.gradle.include.7=cordova-plugin-firebase/brilonglock-build.gradle
cordova.system.library.4=com.google.gms:google-services:3.1.1
cordova.system.library.5=com.google.android.gms:play-services-tagmanager:11.8.0
cordova.system.library.6=com.google.firebase:firebase-core:11.8.0
cordova.system.library.7=com.google.firebase:firebase-messaging:11.8.0
cordova.system.library.8=com.google.firebase:firebase-crash:11.8.0
cordova.system.library.9=com.google.firebase:firebase-config:11.8.0
cordova.system.library.10=com.google.firebase:firebase-perf:11.8.0
cordova.system.library.11=com.android.support:support-v4:27.0.0
cordova.gradle.include.8=cordova-plugin-local-notification/brilonglock-localnotification.gradle
cordova.gradle.include.9=phonegap-plugin-barcodescanner/brilonglock-barcodescanner.gradle
```

**Comment by christocracy** [comment]
`cordova-plugin-firebase` is horrible.

**Comment by t2wu** [comment]
Lol. I don't know if I am just get bitten frequently, but I felt somehow the whole Cordova ecosystem is horrible. I mean there are various plugins that don't play nicely and you have to tweak. I really hope I can just migrate out of this mess. Though I don't know if React native is any better.

**Comment by t2wu** [comment]
OK I used an old version of cordova-plugin-firebase (hash 79dbf49) and and consulted this [thread](https://stackoverflow.com/questions/49208772/error-resource-androidattr-fontvariationsettings-not-found) and managed to get it to compile.
