### ISSUE TITLE
error when build android after installing this plugin

### ISSUE THREAD

**Issue by okkypt** [transistorsoft/cordova-background-geolocation-lt#649]
## Your Environment
* Plugin version: 
cordova-background-geolocation-lt 2.10.1 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-whitelist 1.3.3 "Whitelist"

* Platform: Android
* OS version: Android 6.0
* Device manufacturer / model: Xiaomi redmi4x
* Cordova version (`cordova -v`):  8.0.0
* Cordova platform version (`cordova platform ls`):android 7.0.0

## Expected Behavior
fail build APK for android when install this plugin

## Actual Behavior
before i install this plugin, i can succesfully build APK for android. i dont know why i cant build APK (always error) after i install this plugin.

## Debug logs
![capture4](https://user-images.githubusercontent.com/38503051/38944096-31387032-435d-11e8-9415-d64fce3d4d5b.JPG)
![capture1](https://user-images.githubusercontent.com/38503051/38944097-318ebf82-435d-11e8-9764-a73387be9937.JPG)
![capture2](https://user-images.githubusercontent.com/38503051/38944098-31c3e23e-435d-11e8-8656-ce8629b8dd25.JPG)
![capture3](https://user-images.githubusercontent.com/38503051/38944099-31f960da-435d-11e8-8478-e67558a247d9.JPG)

Thankyou for your help

**Comment by christocracy** [comment]
yes

**Comment by okkypt** [comment]
ok, i need to read it first need some minute

**Comment by okkypt** [comment]
how do i know my plugin version ?

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by okkypt** [comment]
i fill with all my plugins or only your plugins chris ?

**Comment by christocracy** [comment]
I don't care what you post, as long as it includes the version of background-geolocation

**Comment by okkypt** [comment]
oke chris thankyou

**Comment by okkypt** [comment]
@christocracy Chris, SO THANKYOU! now i can build my apk succesfully, you save my day bro, once again THANKYOU!
