### ISSUE TITLE
"Error - The plugin in your app does not support the compulsory arm64"

### ISSUE THREAD

**Issue by ivanssa** [transistorsoft/cordova-background-geolocation-lt#65]
Could help in this matter, I added the plugin correctly but when you build the Phonegap site only android version is compiled and get the following error in the ios platform, "Error - The plugin in your app does not support the compulsory arm64 (64- bit support) architecture. "how do I solve? other questions in this version ios plugin enables the native option monitoring gps background defined as ever? as well as the new role of facebook friends nearby? which enables the GPS function always as seen in the image below?

![aways1](https://cloud.githubusercontent.com/assets/3166174/12740373/4bc38a00-c951-11e5-95ef-d72369cb236f.png)

/-------------------------------------/

![aways](https://cloud.githubusercontent.com/assets/3166174/12740374/4bc60118-c951-11e5-8c75-83ddde45f398.png)

**Comment by christocracy** [comment]
iOS version?
Cordova version?

I don't know what you're trying to ask related to facebook but this plugin,
in order to operate in the background, does of course request "always
usage" permission instead of "when using" permission.

https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/doc/uid/TP40007125-CH3-SW72

On Tuesday, February 2, 2016, ivanssa <notifications@github.com> wrote:

> Could help in this matter, I added the plugin correctly but when you build
> the Phonegap site only android version is compiled and get the following
> error in the ios platform, "Error - The plugin in your app does not support
> the compulsory arm64 (64- bit support) architecture "how do I solve? other
> questions in this version ios plugin enables the native option monitoring
> gps background defined as ever? as well as the new role of facebook friends
> nearby? which enables the GPS function always as seen in the image below?
>
> [image: aways1]
> <https://camo.githubusercontent.com/880b7d0d25e06a0da3019789e23e0c36acb7c013/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f333136363137342f31323734303337332f34626333386130302d633935312d313165352d393565662d643732333639636232333666706e67>
> [image: aways]
> <https://camo.githubusercontent.com/70ed531d1ffc48dfe1362109ddb12a5c985c1739/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f333136363137342f31323734303337342f34626336303131382d633935312d313165352d386337352d383364646465343566333938706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/65>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ivanssa** [comment]
Hello thanks for the reply, I am using build.phonegap.com to compile my app made with ionic, in android seems to work but I get an error when compiling the version ios like the image below:

![erro](https://cloud.githubusercontent.com/assets/3166174/12752569/ea6dc21a-c9a1-11e5-9334-1aec285eb8ee.jpg)

follows the error log excerpt below:

```
_kCLLocationAccuracyBest ", referenced from:
      - [CDVLocation StartLocation:] in CDVLocation.o
      - [CDVBackgroundGeoLocation translateDesiredAccuracy:] in CDVBackgroundGeoLocation.o
      - [CDVBackgroundGeoLocation setPace:] in CDVBackgroundGeoLocation.o
  "_kCLLocationAccuracyNearestTenMeters", referenced from:
      - [CDVLocation StartLocation:] in CDVLocation.o
      - [CDVBackgroundGeoLocation translateDesiredAccuracy:] in CDVBackgroundGeoLocation.o
ld: symbol (s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

On facebook is that it is the only app I have to request activation of GPS no app que através de um alert vc pode habilitar a opção gps sempre, as usual so I asked that only with this plugin ios will disponibilizar this option or do I have to do any more configuration to use this option in my phonegap app?

![facebook](https://cloud.githubusercontent.com/assets/3166174/12752582/f67c812c-c9a1-11e5-9b9e-63d0c71595df.jpg)

**Comment by ivanssa** [comment]
@christocracy some solution for this error?

**Comment by christocracy** [comment]
I return from vacation tomorrow night

On Wednesday, February 3, 2016, ivanssa <notifications@github.com> wrote:

> @christocracy <https://github.com/christocracy> some solution for this
> error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/65#issuecomment-179288411>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ivanssa** [comment]
Thank you, I'll be awaiting ...

**Comment by ivanssa** [comment]
Hello @christocracy I discovered the error reason, changed the version of the plugin repository par 0.3.5 and the problem was solved, I now have the option to set the app as GPS always as well as the use of facebook friends nearby.

<Plugin name = "org.transistorsoft.cordova.background-geolocation" spec = "0.3.5" source = "pgb" />

Congratulations for this great plugin,
I just have one more question, how can I create an alert requesting the approval of the location of the access to change aways within my app?

**Comment by christocracy** [comment]
There is no version 0.3.5.  Do you have a link to this 0.3.5?  What is the
plugin ID?  If it begins with "org.transistorsoft.*", that's the old junk
version which hasn't been supported in over a year.

You're not quite understanding how this plugin works.  It's smarter than
you think.  The plugin automatically adds NSLocationAlwaysUsage permission
and sets a default NSLocationAlwaysUsageDescription in you .plist.

If you're not seeing the plugin automatically ask for that permission,
you're doing something wrong.

On Thursday, February 4, 2016, ivanssa <notifications@github.com> wrote:

> Hello @christocracy <https://github.com/christocracy> I discovered the
> error reason, changed the version of the plugin repository par 0.3.5 and
> the problem was solved, I now have the option to set the app as GPS always
> as well as the use of facebook friends nearby.
>
> Congratulations for this great plugin,
> I just have one more question, how can I create an alert requesting the
> approval of the location of the access to change aways within my app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/65#issuecomment-179751620>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ivanssa** [comment]
@christocracy  Yes I can see now the plugin work with background now and the option has always been available on the repository you could then move the line of code <plugin ... with the correct version to add in my config.xml that does not occur error build.phonegap.com the site? the other question was as it is possible to make the ios settings change request to activate the GPS as always in as app approved notifications, GPS etc .. when we opened the first app ...

**Comment by christocracy** [comment]
The *only* way to use the plugin with PGB is to follow these steps exactly:

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/PhoneGap-Build-Installation

If you're installing the plugin in *any other manner*, you're doing it
wrong.

On Thursday, February 4, 2016, ivanssa <notifications@github.com> wrote:

> @christocracy <https://github.com/christocracy> Yes I can see now the
> plugin work with background now and the option has always been available on
> the repository you could then move the line of code <plugin ... with the
> correct version to add in my config.xml that does not occur error
> build.phonegap.com the site? the other question was as it is possible to
> make the ios settings change request to activate the GPS as always in as
> app approved notifications, GPS etc .. when we opened the first app ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/65#issuecomment-179931431>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
The plugin has always requested "always" authorization.  This is central to
the plugin's theory of operation, to run "always" in the background.

If you're not seeing the plugin request "always" authorization, you have
some issue where another plugin has already requested "when in use"
authorization, such as the std cordova-plugin-geolocation.

Try removing Cordova-plugin-geolocation (if you're using it), delete the
app from your phone, then reinstall.

You'll see that my plugin certainly does request "always" authorization.

On Thursday, February 4, 2016, ivanssa <notifications@github.com> wrote:

> @christocracy <https://github.com/christocracy> Yes I can see now the
> plugin work with background now and the option has always been available on
> the repository you could then move the line of code <plugin ... with the
> correct version to add in my config.xml that does not occur error
> build.phonegap.com the site? the other question was as it is possible to
> make the ios settings change request to activate the GPS as always in as
> app approved notifications, GPS etc .. when we opened the first app ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/65#issuecomment-179931431>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ivanssa** [comment]
Hello again to try to include the plugin on my config.xml through the code <plugin name = "org.transistorsoft.cordova.background-geolocation" /> I receive an error in build.phonegap stating "Error - The Following plugin, plugin version or the dependancy of this plugin is not on npm: org.transistorsoft.cordova.background-geolocation "so I opted for this entry <plugin name =" org.transistorsoft.cordova.background-geolocation "spec =" 0.3.5 "source = "pgb" /> this link >> https://build.phonegap.com/plugins/513 who managed to compile, is that correct? if not what input should add in my config.xml?

**Comment by christocracy** [comment]
You don't understand.  You're trying to install the old fee version
"org.transistorsoft.*". Delete that from your app.  The new version begins
"com.transistorsoft.*".

Follow the Gradle instructions here.

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/PhoneGap-Build-Installation

On Friday, February 5, 2016, ivanssa <notifications@github.com> wrote:

> Hello again to try to include the plugin on my config.xml through the code
> I receive an error in build.phonegap stating "Error - The Following plugin,
> plugin version or the dependancy of this plugin is not on npm:
> org.transistorsoft.cordova.background-geolocation "so I opted for this
> entry this link >> https://build.phonegap.com/plugins/513 who managed to
> compile, is that correct? if not what input should add in my config.xml?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/65#issuecomment-180218571>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ivanssa** [comment]
Sorry if I was not clear, I followed all the instructions but still get errors when adding the plugin with id "com.transistorsoft.cordova.background-geolocation" adding liha` <plugin name = "com.transistorsoft.cordova.background-geolocation" /> `I'm using phonegap plugins list in this https://build.phonegap.com/plugins and so can only add to the success the old version through the config.xml entry `<plugin name = "org.transistorsoft.cordova .background-geolocation "spec =" 0.3.5 "source =" pgb "/>`

**Comment by christocracy** [comment]
You're still doing it wrong.  you need to fork this repo and change the plugin
ID
<https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L5>to
*your own a unique name.
<https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/PhoneGap-Build-Installation#make-your-pluginxml-pgb-compatible>*

eg:  com.*yourcompany*.cordova.background-geolocation

You will *NOT* install com.*transistorsoft*.cordova.background-geolocation

On Fri, Feb 5, 2016 at 2:47 PM, ivanssa <notifications@github.com> wrote:

> Sorry if I was not clear, I followed all the instructions but still get
> errors "plugin version or a dependancy of this plugin is not on npm:" when
> adding the plugin with id
> "com.transistorsoft.cordova.background-geolocation" adding liha<plugin
> name = "com.transistorsoft.cordova.background-geolocation" />I'm using
> phonegap plugins list in this https://build.phonegap.com/plugins and so
> can only add to the success the old version through the config.xml entry <plugin
> name = "org.transistorsoft.cordova .background-geolocation "spec =" 0.3.5
> "source =" pgb "/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/65#issuecomment-180519053>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by ivanssa** [comment]
Hello I thought there was any official public plugin on npm to direct install the build phonegap, I have not used any more private plugin will follow the recommendations, thank you once again for your help.
