### ISSUE TITLE
Question: is maxRecordsToPersist only for Offline Mode ?

### ISSUE THREAD

**Issue by ugenlik** [transistorsoft/cordova-background-geolocation-lt#650]
I am fine most values being default. I did an iOS build with following configuration values, it worked fine the first day and after a day I dont see anydata being sent to the server.  I just drove 2 miles then stopped while the app started then put on the background, nothing 

```
                desiredAccuracy: 10,
                distanceFilter: 250,
                elasticityMultiplier:2,
                //Android Geolocation Options
                fastestLocationUpdateInterval: 10000,

                maxRecordsToPersist:50,
            
                // Application config
                debug: false,
                startOnBoot: true,
                logLevel: global.environment === 'production' ? 3 : 5,
                stopOnTerminate: true,

                // HTTP Feature
                autoSync: true,
                locationsOrderDirection: 'DESC',
```

I just want to record the location every 250 meters and I don't want plugin to clog the server if a user becomes online after a while. 

Currently, we can't handle the `batchSync` option on the server side.

**Comment by christocracy** [comment]
`stopOnTerminate: true`

The OS *will* terminate an app in the background when memory is required by other apps.  When it does, tracking will cease.

Also, are you aware that `desiredAccuracy: 10` doesn't use GPS?

>is maxRecordsToPersist only for Offline Mode

No.  *Every* location is first persisted to database.  The HTTP service operates by selecting records from the database and posting to server.  When your server says `200`, the plugin deletes its copy.

I suggest you have a look at the plugin looks.  See [Debugging Wiki](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)
