### ISSUE TITLE
Question: Trigger local notification on moving

### ISSUE THREAD

**Issue by ishaq-bhojani** [transistorsoft/cordova-background-geolocation-lt#651]
I want to show notifications on specific times like sunrise or sunset
If a user changes it's city or country the notifications time change.
Can i register local notifications inside "motionchange" event in Ionic 3 even when the app is closed (by swiping or back button)
I want to implement this feature in both iOS and Android Apps
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS or Android Both
* OS version: 7.0 Android
* Device manufacturer / model: Samsung
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.4.0

**Comment by christocracy** [comment]
For the Android terminated case, you’ll have to implement your own custom HeadlessTask
https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode

For all other cases, use a third party module
