### ISSUE TITLE
window.plugins.backgroundgeolocation or window.BAckgroundGeolocation isn't works

### ISSUE THREAD

**Issue by Trauck** [transistorsoft/cordova-background-geolocation-lt#653]
I tryed to put a background geolocation on my app like a sport app. 
Then i download this plugins and wanna try it on my browser. But this error append : 
"Uncaught TypeError: Cannot read property 'backgroundGeoLocation' of undefined" on Chrome and 
"TypeError: window.plugins is undefined[En savoir plus] index.js:229:13" on firefox..

Then i tryed to fix it with using window.Backgroudgeolocation but nothing works. I really don't know what to do.. 

In addition I looked a lot of forum dealing with this type of problem and nothing works so please do not redirect me.

(Sorry if my statement is not clear, or not very well written)

**Comment by christocracy** [comment]
The plugin is available at `window.BackgroundGeolocation` as documented in README.

Show me your:
```
$ cordova plugins
```

**Comment by Trauck** [comment]
Yes, i read that then i wanna change it but it doesn't work.. I can't instal the right version in the bash.

![image](https://user-images.githubusercontent.com/38696298/39195305-d8c70ba2-47df-11e8-8b60-1bdae37746f4.png)

**Comment by christocracy** [comment]
You are using the [**wrong** plugin](https://github.com/christocracy/cordova-plugin-background-geolocation).

```
$ cordova plugin remove cordova-plugin-background-geolocation
$ cordova plugin add cordova-background-geolocation-lt
```

**Comment by Trauck** [comment]
Oh yes sorry, i didn't see there is a new version of this plugin. I'll try it.

Thank you.

**Comment by Trauck** [comment]
Well, after doing all the required installations, i end up with the same problem: bgGeo is undefined.

![image](https://user-images.githubusercontent.com/38696298/39235130-5dba0ebe-4875-11e8-9df5-9f47041c3534.png)
 Said , bgGeo is undefined line 147.

I must have forgotten to put a variable in the right function or not called a necessary script ..

**Comment by christocracy** [comment]
Remove / re-add platforms

Remove / re-add plugin.

**Comment by christocracy** [comment]
```
$ cordova platforms
```

**Comment by Trauck** [comment]
Done, but now should i make someting else or i could add the previous code in my map.js (javascript file linked to my html) ?
![image](https://user-images.githubusercontent.com/38696298/39247836-c0cac2ee-489a-11e8-856d-5a1c2954e352.png)

**Comment by christocracy** [comment]
I don't understand your question.  I asked you to show me the following information:
```
$ cordova platforms
```

**Comment by Trauck** [comment]
This is my platforms : 

![image](https://user-images.githubusercontent.com/38696298/39249032-f7a2fc5c-489d-11e8-813b-dc9a8247f35d.png)

**Comment by christocracy** [comment]
The plugin is not yet ready for `cordova-android@7.0.0`
```
$ cordova platform remove android
$ cordova platform add android@6.4.0
```

**Comment by Trauck** [comment]
And it only works on device or we can test it on browser like the last version of background geolocation ?

**Comment by christocracy** [comment]
The plugin does not exist in browser.  The plugin implements native location and motion apis (accelerometer, gyroscope, compass).

The browser does not have these apis.  Just like the browser doesn't have a Camera API.

You must test on device or sim.

**Comment by Trauck** [comment]
So, i am trying on my device and at launch, this message appears: "Licence Validation Failure BackgroundGeolocation is running in evaluation mode." 

Is this the key license in the config.xml file. If that's it I do not have an android key, and I'm a student, so this is not a commercial application and I do not intend to pay for a license.

**Comment by christocracy** [comment]
You cannot use Android without purchasing a license key.

**Comment by christocracy** [comment]
Android will work only in DEBUG builds, so that you can evaluate the plugin before purchase.

Android will not work in RELEASE builds without purchase.

**Comment by Trauck** [comment]
The problem here is that I test my application on my phone that is connected to my pc .. So I can not even test without a license.
Otherwise, the problem seems solved, I will see what I will do with the android license.
Thank you.

**Comment by christocracy** [comment]
The message "Licence Validation Failure BackgroundGeolocation is running in evaluation mode." is fine.

This means the plugin is running in DEBUG build and is *fully operational*.  It's running in **evaluation mode** so that you can *evaluate* the performance of the plugin before purchase.

**Comment by Trauck** [comment]
Yes that's what I'm doing, and just then the message appears.

**Comment by christocracy** [comment]
**IT IS SUPPOSED TO APPEAR**.

**Comment by Trauck** [comment]
Yes I understand that but so I can not test this plugin without license.

**Comment by Trauck** [comment]
Thank you for all these tips and still sorry for the time used.

**Comment by christocracy** [comment]
**YES YOU CAN**.

Just **IGNORE** the message and pretend you have a license.

**Comment by Trauck** [comment]
Well when I come to my page map, nothing happens, like when there is an error in the js.

**Comment by christocracy** [comment]
See [Debugging Wiki](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging#android)

**Comment by Trauck** [comment]
There is a lot of information, but the last one is pretty clear.

![image](https://user-images.githubusercontent.com/38696298/39295110-d9f9aaac-493d-11e8-9d16-0af8d8b06f38.png)

**Comment by christocracy** [comment]
Do not post *screenshots* of logs.  Post the *text*.

I know nothing of your `map.js`.

See docs for `stopOnTerminate`

**Comment by umasankarm** [comment]
Hi i tried to integrate with in my hybrid mobile using ReactJS(not react native), i defined plugin in the config.xml as version below
 
plugin name="cordova-background-geolocation-lt" spec="^2.11.0-beta.1"></plugin

when i tried to run my application it found the below error on console

> Uncaught TypeError: Cannot read property 'on' of undefined
>     at Channel.c (myfileName.js:1921)
>     at Channel.fire (cordova.js:846)
>     at cordova.js:231

**Comment by christocracy** [comment]
@umasankarm 

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

**Comment by christocracy** [comment]
[Using the Plugin](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-using-the-plugin)

>The plugin creates the object window.BackgroundGeolocation. See API Documentation for details

The plugin has nothing to do with `window.plugins`.  It's `window.BackgroundGeolocation`

>in pom.xml and import into my main file as

I know nothing of `pom.xml`.

>import BackgroundGeolocation from 'cordova-background-geolocation-lt/2.10.1/cordova-background-geolocation-lt';

Where did you get the idea to do this??

If you're [using typescript](https://github.com/transistorsoft/cordova-background-geolocation-lt#ionic-2-and-typescript):

```javascript
let bgGeo = (<any>window).BackgroundGeolocation;
```

**Comment by umasankarm** [comment]
Even i changed my code based on your suggestion but still i got the error 

> Uncaught TypeError: Cannot read property 'on' of undefined
>     at Channel.c (xxxx.js:1921)
>     at Channel.fire (cordova.js:846)
>     at cordova.js:231

whether i need to add any key in the variable tag at config.xml file under <plugin> tag for development mode ?
> <variable name="LICENSE" value="YOUR_LICENSE_KEY" />

**Comment by christocracy** [comment]
>whether i need to add any key in the variable tag at config.xml file under plugin tag for development mode ?

No.  The plugin will work in DEBUG builds without a license.  Even if you built for RELEASE, the Javascript API is still available at `window.BackgroundGeolocation`.

If there is no Javascript API available at `window.BackgroundGeolocation`, you do not have the plugin installed.

**Comment by umasankarm** [comment]
ok.. then what may be the problem ?

**Comment by christocracy** [comment]
I do not know.

**Comment by umasankarm** [comment]
We can't use the plugin with ReactJs ? for build hybrid application

**Comment by christocracy** [comment]
This is a pure Cordova plugin.  It doesn't care about what Javascript framework you use.

The plugin installs its Javascript API at `window.BackgroundGeolocation`.

You're not attempting to use the plugin in the browser, are you?  The plugin API is only available on Device or Simulator.

**Comment by christocracy** [comment]
In Javascript console
```
>bg = window.BackgroundGeolocation
```

**Comment by umasankarm** [comment]
![bg](https://user-images.githubusercontent.com/15336535/39627901-f0422ce8-4fc4-11e8-9a0d-b75e20cc50fb.png)

**Comment by christocracy** [comment]
Install [`cordova-plugin-device`](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-device/) and attempt to access it from the Javascript console.

**Comment by umasankarm** [comment]
in browser ? or in a application ?

**Comment by christocracy** [comment]
You can't install a Cordova plugin "in the browser".  

```
$ cordova plugin add cordova-plugin-device
```

**Comment by umasankarm** [comment]
ok, i am not using cordova CLI, i will do by adding webjars and will back with good results may be. Thank you

**Comment by christocracy** [comment]
I have never heard of “webjars”.

**Comment by umasankarm** [comment]
`<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>cordova-plugin-device</artifactId>
    <version>1.1.4</version>
</dependency>`

i get in the site [https://www.webjars.org/](url)

**Comment by christocracy** [comment]
What makes you think that my plugin is magically available on this “webjars”?
