### ISSUE TITLE
How to get location data when users turn off the gps setting?

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#656]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
I want to get location  data when users turn off the gps setting.

**Comment by christocracy** [comment]
What do you mean by “GPS Setting”?

**Comment by pyeonjaesik** [comment]
The gps sensor which I can see when I drag  down the statusbar

**Comment by christocracy** [comment]
That is “location-services”, not specifically GPS.

If the user turns off location-services, it is *impossible* to know the location.

If the user wants to hide from your app, there’s nothing you can do to stop them.  This is a good thing.

You can listen to the `providerchange` event to know when location-services has been disabled.  You could show an alert to the user and ask them to “please turn location-services on”.

**Comment by pyeonjaesik** [comment]
OK! Thank you!
