### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#657]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Actual Behavior
When I change the bgeo configuration and build my app, the configuration do not change as I expected. 
It does not change. So former configuration and later configuration is same.
SO I remove plugin and install it again.
And then I remove android and install it again. But   after that time, I got error code :build failed

**Comment by christocracy** [comment]
The purpose of the template is to provide crucial information to assist you.

You’re giving me nothing.  You’ll get no help until you do.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

**Comment by pyeonjaesik** [comment]
Platform: android
OS: Windows
Cordova version:8.0.0

**Comment by pyeonjaesik** [comment]
Do yo need more information?

**Comment by christocracy** [comment]
I need **ALL** the info.  I can’t read your mind and I can’t see your screen.

**Comment by pyeonjaesik** [comment]
Plugin version: don' know(maybe latest)
Platform: android
OS: windows
Device manufacturer: samsung/galaxy a7
Cordova version: 8.0.0

In my situation, i set the configuration
Param:{id:'1111'} and build my app. It does work well. After I change the configuration param:{id:'2222'} and build my app again. But my app still send param which contains {id:'1111'}  to server

**Comment by pyeonjaesik** [comment]
Plugin version: don' know(maybe latest)
Platform: android
OS: windows
Device manufacturer: samsung/galaxy a7
Cordova version: 8.0.0

In my situation, I set the configuration
Param:{id:'1111'} and built my app. It did work well. After I changed the configuration param from {id:'1111'} to {id:'2222'} and built my app again. But my app still send param which contains {id:'1111'} to server

**Comment by christocracy** [comment]
How do you expect to help yourself if you can’t determine the version of plugins you have installed?

```
$ cordova plugins
```
You were asked to provide the platform versions as well, including the *exact* command required to get that information:

### Cordova platform version (`$ cordova platform ls`):
