### ISSUE TITLE
Geofence callback doesn't get called on Android 8 when crossing out

### ISSUE THREAD

**Issue by t2wu** [transistorsoft/cordova-background-geolocation-lt#658]
## Your Environment
* Plugin version:
* Platform: Android 
* OS version: Android 8.0.0
* Device manufacturer / model: Samsung Galaxy S9
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.4.0
* Plugin config

```
    window.BackgroundGeolocation.configure({
      desiredAccuracy: 1000, // <-- Config params // 0, 10, 100, 1000, where 1000 is the lowest accuracy
      distanceFilter: 50,
      timeout: 40000, // 40 seconds for every location fetch
      activityRecognitionInterval: 10000, // android
      // locationUpdateInterval: 1000,// With distanceFilter: 0, Sets the desired interval for location updates, in milliseconds.
      timeout: 3000,
      geofenceInitialTriggerEntry: true,
      fastestLocationUpdateInterval: 10000,
      forceReloadOnGeofence: true,
    }, ...
```

## Expected Behavior
Crossing event should be received for geofence when testing by physically moving in and out of the geofence boundary

## Actual Behavior
No crossing event

## Steps to Reproduce

1. Run app on Android 8. Samsung Galaxy S9 is what I have.
2. Walk out of the geofence zone.

## Context
Just want the event for crossing out of geofence region.

## Debug logs
Nothing to show for now.

**Comment by christocracy** [comment]
- What is the radius of you geofence?
- Show me corresponding logs from device.

**Comment by t2wu** [comment]
1. Radius 200 meter
2. I turned on verbosity and I hope this contains what you're looking for.
[S9_verbose.txt.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/1959812/S9_verbose.txt.zip)

**Comment by christocracy** [comment]
Test geofencing on your device using the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp)

- Use "Advanced" app.
- Long-press on map to add geofence.

**Comment by t2wu** [comment]
Tried it with NotifyOnExit. There are red dot on the geofence so it works on Samsung Galaxy S9.
Is there anything I need to do for Android 8 in particular? I search for Geofence Android 8 and there are pages talking about foreground service but I don't really understand Android.

**Comment by christocracy** [comment]
I primarily develop upon a Pixel @ 8.1.0 and I have no problems with geofences, ever.  No, there's nothing special that needs to be done.  `foregroundService: true` is automatically enforced for Android 8.  Setting it to `false` has no effect.

**Comment by t2wu** [comment]
Now what could I do to find the problem? Your stuff works on Samsung Galaxy S9. My app works on other Androids we have but not the Samsung Galaxy S9.

**Comment by t2wu** [comment]
You know what, that `foregroundService: true` worked! Will do further testing.
