### ISSUE TITLE
setConfig error

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#659]
## Your Environment
* Plugin version: 2.11.0 -beta3
* Platform: Android
* OS version: windows
* Device manufacturer / model: samsung /galaxy a5
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
When I call the setConfig functions, It works only at first.
but after that my app can't send location data to server.

And following is code which I write.
```javascript
               bgGeo.stop();
                BackgroundGeolocation.setConfig({
                    desiredAccuracy: 0,
                    distanceFilter: 10,
                    stationaryRadius: 25,
                    // Activity Recognition config
                    activityRecognitionInterval: 10000,
                    stopTimeout: 5,
                    // Application config
                    debug: true,  // <-- Debug sounds & notifications.
                    stopOnTerminate: false,
                    startOnBoot: true,
                    // HTTP / SQLite config
                    url: url+"/sendlocal",
                    method: "POST",
                    autoSync: true,
                    maxDaysToPersist: 3,
                    params: {   // <-- Optional HTTP params
                        _id:'2222'
                    }                   
                }, function() {
                  console.log('set config success');
                }, function() {
                  console.log('failed to setConfig');
                });
               bgGeo.start();
```

**Comment by christocracy** [comment]
The plugin's methods are *asynchronous*.  There's no guarantee they're going to run in the same order you execute them from Javascript.  Do **not** do this:
```javascript
bgGeo.stop();
bgGeo.setConfig(config);
bgGeo.start();
```
You have to *chain* them together in their callbacks:
```javascript
bgGeo.stop(function() {
  bgGeo.setConfig(config, function(state) {
    bgGeo.start();
  });
});
```

**Comment by christocracy** [comment]
and keep and eye on your Android logs.  The plugin is logging everything it does.  See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging) Wiki.

You should be *always* tailing the plugin logs in a terminal session with:
```
$ adb logcat -s TSLocationManager
```
![](https://dl.dropboxusercontent.com/s/j2i5vtmsfhqqysa/Screenshot%202018-04-27%2010.30.08.png?dl=1)

**Comment by pyeonjaesik** [comment]
I changed my code as yo advice. But It still do not work well. 
When my devce battery level is lower than 0.15, my app can not send location to server?
document.addEventListener('deviceready',onDeviceReady_fc, false);
function onDeviceReady_fc() {
    // Get a reference to the plugin.
    var bgGeo = window.BackgroundGeolocation;

    //This callback will be executed every time a geolocation is recorded in the background.
    var callbackFn = function(location) {
        var coords = location.coords;
        var lat    = coords.latitude;
        var lng    = coords.longitude;
        console.log('- Location: ', JSON.stringify(location));  
    };

    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
    var failureFn = function(errorCode) {
        console.warn('- BackgroundGeoLocation error: ', errorCode);
    }

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);
    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function(isMoving) {
      console.log('- onMotionChange: ', isMoving);
    });
    // Fired whenever a geofence transition occurs.
    bgGeo.on('geofence', function(geofence) {
      console.log('- onGeofence: ', geofence.identifier, geofence.location);
    });
    // Fired whenever an HTTP response is received from your server.
    bgGeo.on('http', function(response) {
      console.log('http success: ', response.responseText);
    }, function(response) {
      console.log('http failure: ', response.status);
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.ready({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        // Application config
        debug: true,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        // HTTP / SQLite config
        url: url+"/sendlocal",
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3,
        params: {   // <-- Optional HTTP params
            _id:'0000'
        }
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        if (!state.enabled) {
            bgGeo.start();
            var myFunction = function(){
                bgGeo.stop(function(){
                    BackgroundGeolocation.setConfig({
                        desiredAccuracy: 0,
                        distanceFilter: 10,
                        stationaryRadius: 25,
                        // Activity Recognition config
                        activityRecognitionInterval: 10000,
                        stopTimeout: 5,
                        // Application config
                        debug: true,  // <-- Debug sounds & notifications.
                        stopOnTerminate: false,
                        startOnBoot: true,
                        // HTTP / SQLite config
                        url: url+"/sendlocal",
                        method: "POST",
                        autoSync: true,
                        maxDaysToPersist: 3,
                        params: {   // <-- Optional HTTP params
                            _id:'1111'
                        }                   
                    }, function() {
                      console.log('set config success');
                      bgGeo.start();    
                    }, function() {
                      console.log('failed to setConfig');
                    });                    
                });
                
            }
            var myFunction2 = function(){
                bgGeo.stop(function(){
                    BackgroundGeolocation.setConfig({
                        desiredAccuracy: 0,
                        distanceFilter: 10,
                        stationaryRadius: 25,
                        // Activity Recognition config
                        activityRecognitionInterval: 10000,
                        stopTimeout: 5,
                        // Application config
                        debug: true,  // <-- Debug sounds & notifications.
                        stopOnTerminate: false,
                        startOnBoot: true,
                        // HTTP / SQLite config
                        url: url+"/sendlocal",
                        method: "POST",
                        autoSync: true,
                        maxDaysToPersist: 3,
                        params: {   // <-- Optional HTTP params
                            _id:'2222'
                        }                   
                    }, function() {
                      console.log('set config success');
                      bgGeo.start();    
                    }, function() {
                      console.log('failed to setConfig');
                    });                    
                });
                
            }       
            document.getElementById("bgtestbtn").addEventListener("click", myFunction);
            document.getElementById("bgtestbtn2").addEventListener("click", myFunction2);
        }
    });

    // The plugin is typically toggled with some button on your UI.
//    function onToggleEnabled(value) {
//        if (value) {
//            bgGeo.start();
//        } else {
//            bgGeo.stop();
//        }
//    }
}

**Comment by christocracy** [comment]
Show me logs.
