### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'

### ISSUE THREAD

**Issue by SinoBoeckmann** [transistorsoft/cordova-background-geolocation-lt#66]
Hi!
Just started to implement this cool plugin into our product, but unfortunately it's not working.

When trying to start your small demo script as shown in the [README](https://github.com/transistorsoft/cordova-background-geolocation-lt#example), the following error occurs:

> 2016-02-02 11:38:18.429 GEOApp[3164:1323163] [ts-locationmanager] - start
> 2016-02-02 11:38:18.430 GEOApp[3164:1323163] [ts-locationmanager] - setPace 0, stationaryRegion? 0
> 2016-02-02 11:38:18.430 GEOApp[3164:1323163] [ts-locationmanager] - stop prevent-suspend timer
> 2016-02-02 11:38:18.431 GEOApp[3164:1323163] [ts-locationmanager] - stopShakeDetection
> 2016-02-02 11:38:18.431 GEOApp[3164:1323163] [ts-locationmanager] - start location updates
> 2016-02-02 11:38:18.436 GEOApp[3164:1323163] [ts-locationmanager] - MotionDetector starting
> 2016-02-02 11:38:18.538 GEOApp[3164:1323134] [ts-locationmanager] - start
> 2016-02-02 11:38:18.643 GEOApp[3164:1323098] [ts-locationmanager] - didChangeAuthorizationStatus 3
> 2016-02-02 11:38:18.644 GEOApp[3164:1323098] [ts-locationmanager] - setPace 0, stationaryRegion? 0
> 2016-02-02 11:38:18.644 GEOApp[3164:1323098] [ts-locationmanager] - stop prevent-suspend timer
> 2016-02-02 11:38:18.644 GEOApp[3164:1323098] [ts-locationmanager] - stopShakeDetection
> 2016-02-02 11:38:18.645 GEOApp[3164:1323098] [ts-locationmanager] - LocationManager didChangeAuthorizationStatus -- NO IMPL 3
> 2016-02-02 11:38:18.647 GEOApp[3164:1323098] [ts-locationmanager] --------------------------------------------------------
> 2016-02-02 11:38:18.647 GEOApp[3164:1323098] [ts-locationmanager] - didUpdateLocations (enabled: 1, isMoving: 0, df: -1.0, spd: -1.0)
> 2016-02-02 11:38:18.647 GEOApp[3164:1323098] [ts-locationmanager]   updatingLocation: 1
> 2016-02-02 11:38:18.649 GEOApp[3164:1323098] [ts-locationmanager]   isAcquiringStationaryLocation: 1
> 2016-02-02 11:38:18.673 GEOApp[3164:1323098] [ts-locationmanager]   isAcquringSpeed: 0
> 2016-02-02 11:38:18.673 GEOApp[3164:1323098] [ts-locationmanager]   stoppedAt: (null)
> 2016-02-02 11:38:18.673 GEOApp[3164:1323098] [ts-locationmanager] - LocationManager didChangeAuthorizationStatus -- NO IMPL 3
> 2016-02-02 11:38:18.675 GEOApp[3164:1323098] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'
> *** First throw call stack:
> (0x181819900 0x180e87f80 0x181819848 0x182253760 0x1000d3bb0 0x1000d0398 0x1000cfb78 0x1817befc4 0x1817be7e4 0x1817be564 0x181823de4 0x1816ff0f4 0x1820eed2c 0x1000bf794 0x1867c3830 0x1867b1de0 0x182dcf790 0x182dcfb10 0x1817d0efc 0x1817d0990 0x1817ce690 0x1816fd680 0x182c0c088 0x186574d90 0x1000bf0e4 0x18129e8b8) libc++abi.dylib: terminating with uncaught exception of type NSException

I've the following Cordova Version
> sinoboeckmann$ cordova -v
> 5.4.1

And of course the following plugins installed
> sinoboeckmann$ cordova plugin list
> com.synconset.imagepicker 1.0.6 "ImagePicker"
> cordova-plugin-app-preferences 0.7.5 "AppPreferences"
> cordova-plugin-calendar 4.4.5 "Calendar"
> cordova-plugin-camera 1.2.0 "Camera"
> cordova-plugin-console 1.0.2 "Console"
> cordova-plugin-dialogs 1.2.0 "Notification"
> cordova-plugin-file 3.0.0 "File"
> cordova-plugin-splashscreen 3.0.0 "Splashscreen"
> cordova-plugin-statusbar 2.0.0 "StatusBar"
> cordova-plugin-vibration 2.1.0 "Vibration"
> cordova-plugin-whitelist 1.2.0 "Whitelist"
> de.appplant.cordova.plugin.background-mode 0.6.4 "BackgroundMode"
> de.appplant.cordova.plugin.local-notification 0.8.1 "LocalNotification"
> ionic-plugin-keyboard 1.0.8 "Keyboard"
> org.apache.cordova.device 0.3.0 "Device"
> phonegap-facebook-plugin 0.12.0 "Facebook Connect"

Both Simulator (iOS 9.2, Iphone 6) and Device (iPhone 5s 9.2.1) are crashing with the same issue.

If we will get fixed this error and everything is going to work, we're definitely in to buy a license!
Thanks! :)

**Comment by christocracy** [comment]
1.  Get rid of background-mode plugin.  iOS will reject your app 100%
guaranteed

2.  The json exception is not my problem, it's local-notification.  My
plugin emits its own debug notifications which local-notification
dumbly assumes are json-encoded.  Get rid of that plugin and problem goes
away.  Go complain to him.  You'll also find the exceptions stop by setting
debug: false on my plugin but that impedes the development experience.  The
real problem is a false and flawed assumption by local-notification author
that all native notifications recieved in an app are using his arbitrary
json schema.  My notifications are simple text messages, which his json
deserializer pukes on.

On Tuesday, February 2, 2016, Sino <notifications@github.com> wrote:

> Hi!
> Just started to implement this cool plugin into our product, but
> unfortunately it's not working
>
> When trying to start your small demo script as shown in the README
> <https://githubcom/transistorsoft/cordova-background-geolocation-lt#example>,
> the following error occurs:
>
> 2016-02-02 11:38:18429 GEOApp[3164:1323163] [ts-locationmanager] - start
> 2016-02-02 11:38:18430 GEOApp[3164:1323163] [ts-locationmanager] - setPace
> 0, stationaryRegion? 0
> 2016-02-02 11:38:18430 GEOApp[3164:1323163] [ts-locationmanager] - stop
> prevent-suspend timer
> 2016-02-02 11:38:18431 GEOApp[3164:1323163] [ts-locationmanager] -
> stopShakeDetection
> 2016-02-02 11:38:18431 GEOApp[3164:1323163] [ts-locationmanager] - start
> location updates
> 2016-02-02 11:38:18436 GEOApp[3164:1323163] [ts-locationmanager] -
> MotionDetector starting
> 2016-02-02 11:38:18538 GEOApp[3164:1323134] [ts-locationmanager] - start
> 2016-02-02 11:38:18643 GEOApp[3164:1323098] [ts-locationmanager] -
> didChangeAuthorizationStatus 3
> 2016-02-02 11:38:18644 GEOApp[3164:1323098] [ts-locationmanager] - setPace
> 0, stationaryRegion? 0
> 2016-02-02 11:38:18644 GEOApp[3164:1323098] [ts-locationmanager] - stop
> prevent-suspend timer
> 2016-02-02 11:38:18644 GEOApp[3164:1323098] [ts-locationmanager] -
> stopShakeDetection
> 2016-02-02 11:38:18645 GEOApp[3164:1323098] [ts-locationmanager] -
> LocationManager didChangeAuthorizationStatus -- NO IMPL 3
> 2016-02-02 11:38:18647 GEOApp[3164:1323098] [ts-locationmanager]
> --------------------------------------------------------
> 2016-02-02 11:38:18647 GEOApp[3164:1323098] [ts-locationmanager] -
> didUpdateLocations (enabled: 1, isMoving: 0, df: -10, spd: -10)
> 2016-02-02 11:38:18647 GEOApp[3164:1323098] [ts-locationmanager]
> updatingLocation: 1
> 2016-02-02 11:38:18649 GEOApp[3164:1323098] [ts-locationmanager]
> isAcquiringStationaryLocation: 1
> 2016-02-02 11:38:18673 GEOApp[3164:1323098] [ts-locationmanager]
> isAcquringSpeed: 0
> 2016-02-02 11:38:18673 GEOApp[3164:1323098] [ts-locationmanager]
> stoppedAt: (null)
> 2016-02-02 11:38:18673 GEOApp[3164:1323098] [ts-locationmanager] -
> LocationManager didChangeAuthorizationStatus -- NO IMPL 3
> 2016-02-02 11:38:18675 GEOApp[3164:1323098] *** Terminating app due to
> uncaught exception 'NSInvalidArgumentException', reason: '***
> +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter
> is nil'
> *** First throw call stack:
> (0x181819900 0x180e87f80 0x181819848 0x182253760 0x1000d3bb0 0x1000d0398
> 0x1000cfb78 0x1817befc4 0x1817be7e4 0x1817be564 0x181823de4 0x1816ff0f4
> 0x1820eed2c 0x1000bf794 0x1867c3830 0x1867b1de0 0x182dcf790 0x182dcfb10
> 0x1817d0efc 0x1817d0990 0x1817ce690 0x1816fd680 0x182c0c088 0x186574d90
> 0x1000bf0e4 0x18129e8b8) libc++abidylib: terminating with uncaught
> exception of type NSException
>
> I've the following Cordova Version
>
> sinoboeckmann$ cordova -v
> 541
>
> And of course the following plugins installed
>
> sinoboeckmann$ cordova plugin list
> comsynconsetimagepicker 106 "ImagePicker"
> cordova-plugin-app-preferences 075 "AppPreferences"
> cordova-plugin-calendar 445 "Calendar"
> cordova-plugin-camera 120 "Camera"
> cordova-plugin-console 102 "Console"
> cordova-plugin-dialogs 120 "Notification"
> cordova-plugin-file 300 "File"
> cordova-plugin-splashscreen 300 "Splashscreen"
> cordova-plugin-statusbar 200 "StatusBar"
> cordova-plugin-vibration 210 "Vibration"
> cordova-plugin-whitelist 120 "Whitelist"
> deappplantcordovapluginbackground-mode 064 "BackgroundMode"
> deappplantcordovapluginlocal-notification 081 "LocalNotification"
> ionic-plugin-keyboard 108 "Keyboard"
> orgapachecordovadevice 030 "Device"
> phonegap-facebook-plugin 0120 "Facebook Connect"
>
> Both Simulator (iOS 92, Iphone 6) and Device (iPhone 5s 921) are crashing
> with the same issue
>
> If we will get fixed this error and everything is going to work, we're
> definitely in to buy a license!
> Thanks! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/66>
> .
>


-- 
Snet form Gmail Mobile

**Comment by SinoBoeckmann** [comment]
Thanks! That helped! :( Sorry for that. 
Is there a way to use your local notification service? Haven't found something in your Docs?

**Comment by christocracy** [comment]
No, I have no interest in this.  I'm sending notifications purely for my
own debug msgs.

On Tuesday, February 2, 2016, Sino <notifications@github.com> wrote:

> Thanks! That helped! :( Sorry for that.
> Is there a way to use your local notification service? Haven't found
> something in your Docs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/66#issuecomment-178566450>
> .
>


-- 
Snet form Gmail Mobile
