### ISSUE TITLE
about options...

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#660]
## Your Environment
* Plugin version: latest
* Platform:  Android
* OS version: 
* Device manufacturer / model: samsung/ galaxy a7
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
I want know options - activityRecognitionInterval
 'activityRecognitionInterval: 2000 ' means my device detect location every 20 seconds?
When I set the activityRecognitionInterval 5000, my device detects location almost every 10~11 seconds.
And when I set the activityRecognitionInterval 1000000, my device can not detect location.

**Comment by pyeonjaesik** [comment]
And  I want to know desiredAccuracy too...
When I set the desiredAccuracy 100, does my device detect location when I move mores than 100m?
along the same lines when I set the desiredAccuracy 1000, does my device detect location when I move mores than 1000m?

**Comment by pyeonjaesik** [comment]
In my opinion,,,
document.addEventListener('deviceready',onDeviceReady_fc, false);
function onDeviceReady_fc() {
    // Get a reference to the plugin.
    var bgGeo = window.BackgroundGeolocation;

    //This callback will be executed every time a geolocation is recorded in the background.
    var callbackFn = function(location) {
        var coords = location.coords;
        var lat    = coords.latitude;
        var lng    = coords.longitude;
        console.log('- Location: ', JSON.stringify(location));        
    };

    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
    var failureFn = function(errorCode) {
        console.warn('- BackgroundGeoLocation error: ', errorCode);
    }

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);
    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function(isMoving) {
      console.log('- onMotionChange: ', isMoving);
    });
    // Fired whenever a geofence transition occurs.
    bgGeo.on('geofence', function(geofence) {
      console.log('- onGeofence: ', geofence.identifier, geofence.location);
    });
    // Fired whenever an HTTP response is received from your server.
    bgGeo.on('http', function(response) {
      console.log('http success: ', response.responseText);
    }, function(response) {
      console.log('http failure: ', response.status);
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.ready({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        // Application config
        debug: true,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        // HTTP / SQLite config
        url: url+'/sendlocal',
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3,
        params: {   // <-- Optional HTTP params
            _id:'0'
        }
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        if (!state.enabled) {
            bgGeo.start();
            var setcofig_fc1 = function(){
                BackgroundGeolocation.setConfig({
                    activityRecognitionInterval: 5000,
                    params: {   // <-- Optional HTTP params
                        _id:window.localStorage['_id']
                    }                
                }, function() {
                  console.log('set config success');
                }, function() {
                  console.log('failed to setConfig');
                });
            };
            var setcofig_fc2 = function(){
                BackgroundGeolocation.setConfig({
                    activityRecognitionInterval: 10000,
                    params: {   // <-- Optional HTTP params
                        _id:'0'
                    }                
                }, function() {
                  console.log('set config success');
                }, function() {
                  console.log('failed to setConfig');
                });
            };            
            document.getElementById("Pg_start_btn").addEventListener("click", setcofig_fc1);
            document.getElementById("Pg5_setting_main_logout").addEventListener("click", setcofig_fc2);
        }
    });
}

Only  when this setting, my device works well.
when I change the desiredAccuracy to 10 or 100  and activityRecognitionInterval to 10000 or 100000, my device can not work well. because my device does not detect location even though I moves 30m.

**Comment by christocracy** [comment]
>I want know options - activityRecognitionInterval
 'activityRecognitionInterval: 2000 ' means my device detect location every 20 seconds?

See docs [`activityRecognitionInterval`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-integer-millis-10000-activityrecognitioninterval).  This is the sample-rate of the "Motion Activity Detection System".  It has nothing to do with geolocation specifically.

`activityRecognitionInterval` is more important for Android, since Android *triggers* tracking purely based upon Motion APIs (accelerometer, gyroscope, compass).  If you set Android to a *very* high value, it means it won't sample the accelerometer/gyroscope/compass very often thus won't trigger tracking for a long period of time.

Read the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

The Android plugin is constantly sampling the accelerometer/gyroscope/compass asking the question:

```
"am I moving?"
.
"am I moving?"
.
"am I moving?"
```

If you set a *very* high value:
```
"am I moving?"
.
.
.
.
.
.
.
.
"am I moving?"
.
.
.
.
.
.
.
.
"am I moving?"
```

When the answer to "am I moving?" evaluates to `yes` (ie: `on_foot`, `in_vehicle`, `on_bicycle`, `running`), the plugin will turn on location-services and begin recording a location every `distanceFilter` meters.

**Comment by christocracy** [comment]
And when you *don't* use `desiredAccuracy: 0`, you are **NOT** using GPS.  Only Wifi / Cell tower triangulation.

Unless your environment is urban (ie: surrounded by Wifi radios), you will have difficulty getter locations.
