### ISSUE TITLE
ask location permission before background -location -service

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#663]
## Your Environment
* Plugin version: latest
* Platform:Android
* OS version:
* Device manufacturer / model: samsung / galaxy
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
I wonder whether I can ask location permission before cordova- background -geoloaction work or not.
So I tried testing it. and It works well.  Is that ok? I worry If my app can not work later.

**Comment by christocracy** [comment]
The plugin will ask permission as soon as you call `#start`.

**Comment by pyeonjaesik** [comment]
No... I mean...
Can I ask permission before bgeo.start()?
In my case, I ask permission before execute bgeo.start(). 
When I ask permission before bgeo.start(), after bgeo.start() my app does not ask permission any more.

**Comment by christocracy** [comment]
>Can I ask permission before bgeo.start()?

No.  It's the `#start` method which asks permission.
