### ISSUE TITLE
Use the location actively when the app in not in foreground - with the blue location banner.

### ISSUE THREAD

**Issue by transfinderdev** [transistorsoft/cordova-background-geolocation-lt#665]
## Your Environment
* Plugin version: 2.11.0
* Platform: iOS
* OS version: 11.3.1
* Device manufacturer / model: Apple iPhone 7
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 4.5.4

## Expected Behavior
Trying to access the location actively without needing the always authorization on iOS. An example of this is seen in the app "Waze". When the navigation is started on waze and the app goes to background, a blue banner is seen on the iOS satus bar with the name of the app "waze" in this case. Click on the banner opens the app.

## Actual Behavior
The location updates are happening in background but the always permission is required.

## Steps to Reproduce
1. Open the app with this plugin
2. Select Only While Using the App permission when asked
3. The background location does not work

## Context
We are trying to reproduce this:
![image](https://user-images.githubusercontent.com/38570961/39445638-b63d58c6-4c89-11e8-9b02-855e100c0754.png)

**Comment by christocracy** [comment]
See [`locationAuthorizationRequest`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-string-locationauthorizationrequest-always)

**btw**:  customers should use [private repo](https://github.com/transistorsoft/cordova-background-geolocation/)

**Comment by transfinderdev** [comment]
Awesome, thank you this helps with my concern.
