### ISSUE TITLE
Heartbeat Interval on Android

### ISSUE THREAD

**Issue by mino922** [transistorsoft/cordova-background-geolocation-lt#668]
How can I increase the interval at which Android post coords to a server?

## Your Environment
* Plugin version: **2.10.1**
* Platform: iOS or **Android**
* OS version: **All**
* Device manufacturer / model: **All**
* Cordova version (`cordova -v`): **6.4.0**
* Cordova platform version (`cordova platform ls`): 
**Installed platforms:
  android 6.3.0
  ios 4.5.4**
* Plugin config

```
     debug: false,
      desiredAccuracy: 0,
      distanceFilter: 10,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': this.******.getAuthToken()
      },
      httpRootProperty: 'data',
      locationTemplate: '{"lat":<%= latitude %>,"long":<%= longitude %>}',
      url: this.updateLocURL,
      autoSync: true,
      preventSuspend: true,
      heartbeatInterval: 2
    }, (state) => {
      // 4. Start the plugin.
      this.bgGeo.start();
      // setTimeout(() => {
      this.bgGeo.stop();
      // }, 2000);
    });
```

## Expected Behavior
I need to post coords to a server in nearish real time (~2 seconds). I am able to do this on iOS and it is working great! However, I am having trouble doing so on Android. 

I see that the documentation says that the Android heartbeat interval cannot be less than 60 seconds. Are there any ways to speed this up?

**Comment by christocracy** [comment]
>Are there any ways to speed this up?

No, it’s a limitation of the API used to generate heartbeat events (`AlarmManager`).

What are you doIng that you have the need to update location so aggressively while the device is in the stationary state?

Is your device assumed to be plugged into power because if it’s not, you’re going to kill the battery in a couple of hours.

**Comment by christocracy** [comment]
You’re aware of the plugin’s [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation), that the plugin *knows* when the device is **moving** vs **stationary**?

What’s the point constantly sending the same position to the server over and over again?  Your HTTP requests to server are consuming more energy than location-services, btw.. 

When the device begins moving, the plugin tell you by firing the `motionchange` event.  Feel free to aggressively track at that time.

**Comment by mino922** [comment]
Sorry, I should not have said updating coords. I am doing that when the coords change based on the distance filter. 

I need to poll a backend server for a response  I am using this plugins background mode capabilities to do so. On iOS I can use the heartbeat interval to call the API ~2 seconds, but on Android I cannot achieve that same performance.

Is there a way to achieve this?

**Comment by christocracy** [comment]
Like I said:

>No, it’s a limitation of the API used to generate heartbeat events (AlarmManager).

You will *never* have heartbeat faster than 60s.  It’s **impossible**.

What are you doing that you need to poll the server at such an *insane* frequency on a mobile device?

**is your device assumed to be plugged into power**?

**Comment by christocracy** [comment]
And be aware that the ios heartbeat will be throttled by the os after a few minutes when the device is unplugged from power with screen off.  Your `heartbeat` events *will* stop until movement is detected or the user lights up the screen / unlocks device.

**Comment by christocracy** [comment]
Instead of polling a server, you probably want to be using server *Push* requests, “silent” ones with only a JSON payload (so the user sees no notification).

Server push requests are capable of awakening a suspended app in the background too (so you don’t need `preventSuspend`).  They can even cause a terminated app to be booted to service the request.
