### ISSUE TITLE
Sufficient Geolocation Permissions Problem

### ISSUE THREAD

**Issue by yecicen** [transistorsoft/cordova-background-geolocation-lt#669]
* Plugin version: 2.10.1
* Platform: Android 
* OS version: -
* Device manufacturer / model: Nexus 6P API 26 (Emulator)
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.4.0
* Plugin config

## Expected Behavior
Our expected behavior is to get user's current location info.

## Actual Behavior
I get an error says that "Caught security exception while registering for location updates from the system. The application does not have sufficient geolocation permissions."

## Debug logs
E/cr_LocationProvider: Caught security exception while registering for location updates from the system. The application does not have sufficient geolocation permissions.

**Comment by christocracy** [comment]
`E/cr_LocationProvider` is not related to the plugin.  I guess you figured this out?
