### ISSUE TITLE
 Invalid callback id received by sendPluginResult

### ISSUE THREAD

**Issue by raskri** [transistorsoft/cordova-background-geolocation-lt#67]
window.BackgroundGeolocation.setConfig(function() {
 console.log('BackgroundGeolocation - set config success');
}, function(){
 console.log('BackgroundGeolocation - failed to setConfig');
},{
 desiredAccuracy: 0, 
 distanceFilter: 50 
});
					
window.BackgroundGeolocation.getCurrentPosition(
 onUpdate,
onError, {
 preventSuspend: true,
 stopOnTerminate: true
});

I'm getting this error: Invalid callback id received by sendPluginResult... any clues

**Comment by christocracy** [comment]
Are you executing #configure before you do anything with the plugin?

On Tuesday, February 2, 2016, Kristian Rasmussen <notifications@github.com>
wrote:

> window.BackgroundGeolocation.setConfig(function() {
> console.log('BackgroundGeolocation - set config success');
> }, function(){
> console.log('BackgroundGeolocation - failed to setConfig');
> },{
> desiredAccuracy: 0,
> distanceFilter: 50
> });
>
> window.BackgroundGeolocation.getCurrentPosition(
> onUpdate,
> onError, {
> preventSuspend: true,
> stopOnTerminate: true
> }
>
> I'm getting this error: Invalid callback id received by
> sendPluginResult... any clues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/67>
> .
>


-- 
Snet form Gmail Mobile

**Comment by raskri** [comment]
Yes, setConfig is ran first, then getCurrentPosition. Just in the order in the example... Thanks

**Comment by raskri** [comment]
I get coords and all... I just didn't like the message  :)

**Comment by christocracy** [comment]
No.  You must first run #configure.  If you wish to change the config
*after* you've first configured the plugin, *then* you use #setConfig.

On Tuesday, February 2, 2016, Kristian Rasmussen <notifications@github.com>
wrote:

> Yes, setConfig is ran first, then getCurrentPosition. Just in the order in
> the example... Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/67#issuecomment-178765445>
> .
>


-- 
Snet form Gmail Mobile

**Comment by raskri** [comment]
Aha! Yes I changed it. And the message is gone. 

But I can still see console.log('BackgroundGeolocation - set config success'); output every time I call getCurrentPosition... But it's maybe intended?

Thanks again!

**Comment by christocracy** [comment]
You don't quite understand the purpose of #configure.

Please see the docs for the #configure method and understand that the 1st
param is the *locationCallback* executed whenever a location is recorded.
This is NOT a success-callback for the #configure method itself.

With #configure, you are saying to the plugin "here is my JavaScript
callback function that I want called whenever a location is recorded".  The
2nd param is the errorCallback, executed whenever the plugin *fails* to
fetch a location.  The 3rd param is the config-params.

Please glance through the entire API docs.

On Tuesday, February 2, 2016, Kristian Rasmussen <notifications@github.com>
wrote:

> Aha! Yes I changed it. And the message is gone.
>
> But I can still see console.log('BackgroundGeolocation - set config
> success'); output every time I call getCurrentPosition... But it's maybe
> intended?
>
> Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/67#issuecomment-178776548>
> .
>


-- 
Snet form Gmail Mobile

**Comment by raskri** [comment]
I will thanks!
