### ISSUE TITLE
Heartbeat only triggered for a few minutes, then it stopped triggering

### ISSUE THREAD

**Issue by 604abbky** [transistorsoft/cordova-background-geolocation-lt#670]
After the iPad (isn't plugged with anything) went into stationary state, heartbeat triggered for a few minutes, then it stopped triggering.

Heartbeat seems to always triggers when it is plugged in laptop or charging

## Your Environment
* Plugin version: 2.11.0
* Platform: iOS
* OS version: 11.2.1 (15C153)
* Device manufacturer / model: Apple iPad Air 2 MGH72CL/A
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): ios 4.4.0
* Plugin config
{
        minimumActivityRecognitionConfidence: 50,
        stopOnTerminate: false,
        startOnBoot: true,
        preventSuspend: true
}
## Expected Behavior
Heartbeat always triggers at the default rate, 60 (if not specified) when preventSuspend is true

## Actual Behavior
When the device isn't plugged with anything, heartbeat triggers only for a few minutes, then it stopped.

When the device is plugged with laptop or charging, it always triggers heartbeats continuously. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
This is correct.  When iOS device is unplugged from power with screen off, the OS throttles the process.

When motion is detected or the screen is activated, `heartbeat` will resume.  `heartbeat` will fire for as long as the user has their device unlocked.
