### ISSUE TITLE
window.BackgroundGeolocation === undefined

### ISSUE THREAD

**Issue by StijnAvdL** [transistorsoft/cordova-background-geolocation-lt#673]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: ^6.4.0
* Device manufacturer / model: 1 PLUS 2
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):
![image](https://user-images.githubusercontent.com/3808655/40049835-089256dc-5836-11e8-86b6-45a89c044aad.png)
* Plugin config: 
![image](https://user-images.githubusercontent.com/3808655/40049905-401af2bc-5836-11e8-8831-d26268af8a9c.png)

## Expected Behavior
I expected that ``window.BackgroundGeolocation`` returns an Object

## Actual Behavior
But its ``undefined``

## Context

![image](https://user-images.githubusercontent.com/3808655/40050103-cbad982a-5836-11e8-9b3d-a34574702916.png)

## Debug logs
``$ adb logcat -s TSLocationManager`` doesnt give anything back

**Comment by StijnAvdL** [comment]
🤦‍♂️  I fixed it but it was to stupid to share here ... 

awesome plugin btw!

**Comment by christocracy** [comment]
good, thanks
