### ISSUE TITLE
Do geofences work without the map?

### ISSUE THREAD

**Issue by renanmoraes** [transistorsoft/cordova-background-geolocation-lt#674]
## Your Environment
* Plugin version:  ^2.11.0
* Platform: Android
* OS version: 5.1
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0

## Expected Behavior
I need to get the geofence functions but I do not use the map. I need the event of entrance, exit and dwell. I also need it to run even if I did not have access to the internet, or locally.

## Actual Behavior
I tried to do but it does not work well, it informs the console that was added but there is not the event, to try to decrease the distanceFilter but does not actually display the console.log nor the alert placed in the function.

## Context
```
  configureBackgroundGeolocation() {
    this.bgGeo = this.bgService.getPlugin();
    this.addGeolocations();

    // Listen to events
    this.onLocation = this.onLocation.bind(this);
    this.onMotionChange = this.onMotionChange.bind(this);
    this.onMotionChange = this.onMotionChange.bind(this);
    this.onGeofence = this.onGeofence.bind(this);

    this.bgGeo.on('location', this.onLocation);
    this.bgGeo.on('motionchange', this.onMotionChange);
    this.bgGeo.on('geofence', this.onGeofence);

    //Resetar o odometro toda vez que entrar na configuracoes
    this.resetOdometer();

    // Obtendo as configurações atuais do bgService
    this.bgService.getState((config) => {
      const settingsEdit = [].concat(this.SETTINGS.Common).concat(this.SETTINGS[this.device.platform || 'iOS']);

      for (let key in settingsEdit[0]) {
        config[key] = settingsEdit[0][key];
      }

      for (let key in settingsEdit[1]) {
        if (key !== 'triggerActivities') {
          config[key] = settingsEdit[1][key];
        } else {
          config[key] = '';
          settingsEdit[1][key].forEach((element, index) => {
            (index === settingsEdit[1][key].length - 1) ? config[key] += element : config[key] += element + ', ';
          });
        }
      }

      // config.triggerActivities = 'in_vehicle';
      this.configPlugin = config;


      this.bgGeo.configure(config, (state) => {
        this.zone.run(() => {
          this.state.enabled = config.enabled;
          this.state.isMoving = config.isMoving;
          this.state.geofenceProximityRadius = config.geofenceProximityRadius;
          this.state.trackingMode = (state.trackingMode === 1 || state.trackingMode === 'location') ? 'location' : 'geofence';
          if (!this.isFirstBoot()) {
            // Set current plugin state upon our view.
            this.enabled = state.enabled;
            this.isMoving = state.isMoving;
          }
        });
        if (state.schedule.length > 0) {
          this.bgGeo.startSchedule();
        }
        this.onEnabled();
      });
    });
  }

  onGeofence(event: any) {
    console.log('[event] - geofence: ', event);
    alert('chegou geofence')
  }

  addGeolocations() {
    this.bgGeo.addGeofence({
      identifier: "ZONE_OF_INTEREST",
      radius: 15,
      latitude: -19.5513635,
      longitude: -42.6392057,
      notifyOnEntry: true,
      notifyOnExit: true,
      notifyOnDwell: true,
      loiteringDelay: 30000,  // 30 seconds
      extras: {               // Optional arbitrary meta-data
        zone_id: 1234
      }
    }, function () {
      console.log("Successfully added geofence");
    }, function (error) {
      console.warn("Failed to add geofence", error);
    });
  }
```

**Comment by renanmoraes** [comment]
I'm not going out to field, according to my code you can let me know if I'm missing something, I'm trying to see the log, but I'm not getting it, I'm going to run one more time and check.

**Comment by christocracy** [comment]
Ensure you're configuring `{logLevel: this.bgGeo.LOG_LEVEL_VERBOSE, debug: true}`

**Comment by christocracy** [comment]
Here's my [account on test server](http://tracker.transistorsoft.com/transistor-ionic?device=Cordova-cd4ce2e5d0447f8a&end=2018-5-13&start=2018-5-12) with fired geofences.

Are you syncing to `tracker.transistorsoft.com`?  If so, what's your username?

**Comment by christocracy** [comment]
Oh, btw:  the minimum reliable geofence radius is `150` meters.  `radius: 15` won't work.

**Comment by renanmoraes** [comment]
I'm not on the transistor soft yet, I'm in the test of the plugin to check if it meets me, so far this is fine, missing this part of geofence, wait for me a few minutes because I'm going to field and I'll test again.

**Comment by christocracy** [comment]
You can easily configure the plugin to post to `tracker.transistorsoft.com` by getting a reference to `cordova-plugin-device` and [following the directions here](https://shop.transistorsoft.com/blogs/news/background-geolocation-console)

**Comment by renanmoraes** [comment]
Well we go to the results, I think the problem really was in the beam, because when I put 150 worked perfectly.

Regarding the post for api, it did not work as expected, but life follows kkkk.

Now I have a cruel doubt, because of the demand of the 150 meters? If I had a prerequisite for a geofence less than this number, what are the possible errors that I can face besides not working?

**Comment by christocracy** [comment]
> If I had a prerequisite for a geofence less than this number, what are the possible errors that I can face besides not working?

The geofence will not fire.  Do not *ever* configure `< 150` meters.

**Comment by renanmoraes** [comment]
To close the inssue. Does the geofence event have relation to distanceFilter, for example if it had a distanceFilter of 200m and my geofence is of 150m all events will be executed in a natural way? That is, exit, enter, dwell

**Comment by christocracy** [comment]
`distanceFilter` has nothing to do with geofences.  You can configure `distanceFilter: 10000000000`:  it won't affect the behaviour of geofences *at all*.

**Comment by renanmoraes** [comment]
Thank you for the great work so far.
