### ISSUE TITLE
in cordova 8 BUILD FAILED

### ISSUE THREAD

**Issue by areswonghrh** [transistorsoft/cordova-background-geolocation-lt#677]
## Your Environment
* Plugin version:2.11.0
* Platform: Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):8.0.0
* Cordova platform version (`cordova platform ls`):7.0.0
* Plugin config
  plugin name="cordova-background-geolocation-lt" spec="^2.11.0" 
       variable name="LICENSE" value="XXXXXX" 
      variable name="GOOGLE_API_VERSION" value="11.8.0" 
      variable name="APPCOMPAT_VERSION" value="27.0.0" 
   plugin

## Expected Behavior

Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
`2.11.0` is not compatible with `cordova-android@7`.

I've released `2.12.0` just now which *is* compatible with `cordova-android@7`.

Installed `2.12.0`
