### ISSUE TITLE
Last still / stationary position not coming

### ISSUE THREAD

**Issue by paulatrockhill** [transistorsoft/cordova-background-geolocation-lt#678]
Hi Chris...we have distanceFilter: 100m and we travelled 250m, we will be getting only first 100m position and second 100m position. We have stopTimeout: 3 min. How we will get 250th meter position after 3 min of still / stationary?

Also what should be given in elasticityMultiplier in order to receive one position for 1 miles when we drive at 90miles per hour and every 100m position when we drive less than 20 mph?  For your information, we have already given distanceFilter: 100m.  

Thanks in advance. 

Have a great day

**Comment by christocracy** [comment]
When `stopTimeout` expires, the plugin will fire the [`motionchange`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#motionchange) event, where it has recorded the current position where the device is stationary.

>Also what should be given in elasticityMultiplier in order to receive one position for 1 miles

I have no idea.  See the docs for [`distanceFilter`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-integer-distancefilter) where the formula is documented:
```
rounded_speed = round(7.7, 5)
  => 10
  multiplier = rounded_speed / 5
  => 10 / 5 = 2
  adjusted_distance_filter = multiplier * distanceFilter
  => 2 * 30 = 60 meters
```
