### ISSUE TITLE
getCurrentPosition callbacks not called when finish() triggered in configure(successFn)

### ISSUE THREAD

**Issue by kylethielk** [transistorsoft/cordova-background-geolocation-lt#68]
Hi There!

Thanks for the excellent plugin.

I have an issue where getCurrentPosition callbacks (both success and failure) are not being triggered when successFn from configure(successFn) calls finish(taskId).

So for example this will never trigger getCurrentPosition callbacks:

    BackgroundGeolocationService.configure(function(location, taskId)
    {
        console.log('Received location.');
        BackgroundGeolocationService.finish(taskId);
    });

    BackgroundGeolocationService.getCurrentPosition(function(location, taskId){
          console.log('current position received');
    },function(){},{});

However if we comment out the `finish(taskId)` in successFn like so the getCurrentPosition callbacks are triggered as expected:

    BackgroundGeolocationService.configure(function(location, taskId)
    {
        console.log('Received location.');
        //BackgroundGeolocationService.finish(taskId);
    });

    BackgroundGeolocationService.getCurrentPosition(function(location, taskId){
          console.log('current position received');
    },function(){},{});

Is this expected behavior? 

Thank you.

**Comment by kylethielk** [comment]
A quick update. 

This seems to only be an issue when setting breakpoints and debugging using the Simulator and Safari Debug Tools. I'm not sure if perhaps it is a threading/timing issue but I will investigate further and update if I find anything else out.

Any suggestions or ideas why this is happening only when stepping through code would be greatly appreciated.

Thanks!

**Comment by christocracy** [comment]
First-of-all, have you tried the SampleApp?



On Wednesday, February 3, 2016, Kyle Thielk <notifications@github.com>
wrote:

> Hi There!
>
> Thanks for the excellent plugin.
>
> I have an issue where getCurrentPosition callbacks (both success and
> failure) are not being triggered when successFn from configure(successFn)
> calls finish(taskId).
>
> So for example this will never trigger getCurrentPosition callbacks:
>
> BackgroundGeolocationService.configure(function(location, taskId)
> {
>     console.log('Received location.');
>     BackgroundGeolocationService.finish(taskId);
> });
>
> BackgroundGeolocationService.getCurrentPosition(function(location, taskId){
>       console.log('current position received');
> },function(){},{});
>
> However if we comment out the finish(taskId) in successFn like so the
> getCurrentPosition callbacks are triggered as expected:
>
> BackgroundGeolocationService.configure(function(location, taskId)
> {
>     console.log('Received location.');
>     //BackgroundGeolocationService.finish(taskId);
> });
>
> BackgroundGeolocationService.getCurrentPosition(function(location, taskId){
>       console.log('current position received');
> },function(){},{});
>
> Is this expected behavior?
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/68>
> .
>


-- 
Snet form Gmail Mobile

**Comment by kylethielk** [comment]
Hi Chris,

Thank you for the response. I have and this same issue is present in the SampleApp. 

Here is a recording I just made of it in action: https://www.dropbox.com/s/c8a3rf2chr1iyn8/cordova-bg-error.mov?dl=0 (the quality sucks viewing through Dropbox's browser player, probably need to download to see details)

First go through there is no breakpoint in fireLocationListeners and everything works as expected. Our getCurrentPosition callback is triggered.

Second time around I set a breakpoint in fireLocationListeners and the getCurrentPosition callback is never triggered.

Thanks!

**Comment by christocracy** [comment]
I'll be back in the office Friday

On Wednesday, February 3, 2016, Kyle Thielk <notifications@github.com>
wrote:

> Hi Chris,
>
> Thank you for the response. I have and this same issue is present in the
> SampleApp.
>
> Here is a recording I just made of it in action:
> https://www.dropbox.com/s/c8a3rf2chr1iyn8/cordova-bg-error.mov?dl=0 (the
> quality sucks viewing through Dropbox's browser player, probably need to
> download to see details)
>
> First go through there is no breakpoint in fireLocationListeners and
> everything works as expected. Our getCurrentPosition callback is triggered.
>
> Second time around I set a breakpoint in fireLocationListeners and the
> getCurrentPosition callback is never triggered.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/68#issuecomment-179370590>
> .
>


-- 
Snet form Gmail Mobile

**Comment by kylethielk** [comment]
Thanks Chris. No rush as I have not been able to reproduce in any other circumstance.
