### ISSUE TITLE
how to work without  google play ?

### ISSUE THREAD

**Issue by areswonghrh** [transistorsoft/cordova-background-geolocation-lt#680]
## Your Environment
* Plugin version:2.12.0
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):8.0.0
* Cordova platform version (`cordova platform ls`):7.0.0
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Google Play Services is *required*.

The plugin requires the [`FusedLocationProviderClient`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient) and more importantly, the [`ActivityRecognitionClient`](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient) (motion API for detecting when device is moving to toggle location updates on / off)
