### ISSUE TITLE
Can google play-related plug-ins be integrated into the android project?

### ISSUE THREAD

**Issue by areswonghrh** [transistorsoft/cordova-background-geolocation-lt#681]
## Your Environment
Plugin version:2.12.0
Platform: iOS or Android
OS version:
Device manufacturer / model:
Cordova version (cordova -v):8.0.0
Cordova platform version (cordova platform ls):7.0.0
Plugin config

## Expected Behavior

Can google play-related plug-ins be integrated into the android project? 		
Because Android phones in China by default donundefinedt have googl play or google server framework installed.
If there is no other way, can I have a refund.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
There is no way.  Email me for refund.
