### ISSUE TITLE
Motion and fitness Prompt in Ios App

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/cordova-background-geolocation-lt#686]
Using the plugin for continous tracking of user location updates to my server.

## Expected Behavior
Ios device give prompt of Location access from user

## Actual Behavior
Ios device is giving prompt of "Motion and Fitness Access"

## Context
I went through the app docs and also issues, where i came across similar issue, where it has been said to "disableMotionActivityUpdates": true.

But still i am getting the prompt. How do i disable that prompt and instead ask for location access. 
Is this even possible?

**Comment by christocracy** [comment]
Show me the code you're using to initialize the plugin.

**Comment by shrashwin** [comment]
Here attached are my files for this:



Thanks in advance.

With regards,
Ashwin Shrestha

**Comment by christocracy** [comment]
attachments don't work when replying to a Github thread via email client.
