### ISSUE TITLE
Command failed with exit code 1 Error output: ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font

### ISSUE THREAD

**Issue by devil82426** [transistorsoft/cordova-background-geolocation-lt#687]
## Your Environment
Plugin version: 2.8.5
Platform: Android 6.2.3
OS version: Mac OSX 10.11.16
Cordova version (cordova -v): 8.0.0

## Expected Behavior
cordova run android --device

## Actual Behavior
Crash when running into the device

## Steps to Reproduce
1.
2.
3.
4.

## Context
I'm trying to update the android studio's Android SDK.
and I edit the build.gradle to add this line
configurations.all { resolutionStrategy { force com.android.support:support-v4:27.0.0}}
Nothing gonna change.

## Debug logs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.679 secs
(node:50219) UnhandledPromiseRejectionWarning: Error: /Users/devilmax/Desktop/專案/android/phonegapApp_two/platforms/android/gradlew: Command failed with exit code 1 Error output:
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/Users/devilmax/Desktop/專案/android/phonegapApp_two/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
(node:50219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:50219) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by christocracy** [comment]
You have a gradle dependency conflict with multiple plugin requesting different versions of android support libs.

Post your platforms/android/project.properties

**Comment by devil82426** [comment]
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-location:+
cordova.gradle.include.1=phonegap-plugin-barcodescanner/helloworld-barcodescanner.gradle
cordova.gradle.include.2=phonegap-plugin-push/helloworld-push.gradle
cordova.system.library.2=com.android.support:support-v13:23+
cordova.system.library.3=com.google.android.gms:play-services-gcm:11+
cordova.system.library.4=me.leolin:ShortcutBadger:1.1.14@aar

**Comment by christocracy** [comment]
You're using a very old version of the plugin `2.8.5`.  Latest is `2.12.2`.

Your problem is all those google dependencies pinned to versions with `+` wildcard.

eg:
```
play-services-gcm:11+
```

**Comment by devil82426** [comment]
@christocracy Thanks you! I know that. when I build this project I never update their version.
So I need to remove that and reinstall back. After that, I need to edit the [com.android.support:support-v13:23+ ] ?

**Comment by devil82426** [comment]
Ok, thank you very much, I remain the old project and build the new cordova project.
I will remove the wildcard and setting the specific support.
