### ISSUE TITLE
Google-services version conflict with phonegap-plugin-push

### ISSUE THREAD

**Issue by JeffCODEblum** [transistorsoft/cordova-background-geolocation-lt#688]
I'm trying to use cordova-background-geolocation-lt in a project with phonegap-plugin push but I'm getting the build error:

Execution failed for task ':app:processDebugGoogleServices'

## Your Environment

node v 8.9.4
npm v 5.6.0
ionic v 3.20.0
cordova v 8.0.0
android platform v 7.1.0
Windows 10 Enterprise
Samsung Galaxy S8 Android 8.0.0
Zuk Android 5.1.1

Plugins:
cordova-background-geolocation-lt 2.12.2 "BackgroundGeolocation"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"

## Expected Behavior
App should build and run

## Actual Behavior
Build error is thrown and build fails

(node:6380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:6380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to Reproduce
Create an ionic 1 app. Add cordova-background-geolocation-lt and phonegap-plugin-push and try to build for android

## Context
Making an app which requires the plugins phonegap-plugin-push and cordova-background-geolocation-lt

## Debug logs
λ ionic cordova build android --stacktrace --debug --info
[WARN] Not performing Ionic build for project type: ionic1.
> cordova build android --debug
Android Studio project detected

Running command: "C:\Program Files\nodejs\node.exe" F:\dev\OutdoorFloridaEsri\hooks\after_prepare\010_add_platform_class.js F:\dev\OutdoorFloridaEsri

ANDROID_HOME=C:\Users\Morris\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_161
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_erijc79elmnfzotwin87aiouy.run(F:\dev\OutdoorFloridaEsri\platforms\android\app\build.gradle:147)
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]

registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

:CordovaLib:preBuild
 UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl
 UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources
 UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac
 UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild

UP-TO-DATE
:app:compileDebugAidl

UP-TO-DATE
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript
 UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig

UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:processDebugGoogleServices
Found play-services-location:11.8.0, but version 11.6.2 is needed for the google-services plugin. :app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
21 actionable tasks: 1 executed, 20 up-to-date
(node:13280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:13280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JeffCODEblum** [comment]
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android Studio Gradle projects

# Project target.
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/outdoorflorida-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/outdoorflorida-build.gradle
cordova.system.library.3=com.android.support:support-v4:24.1.1+
cordova.gradle.include.3=cordova-support-google-services/outdoorflorida-build.gradle
cordova.system.library.4=com.android.support:support-v4:26.+
cordova.system.library.5=com.android.support:appcompat-v7:26.+
cordova.gradle.include.4=phonegap-plugin-multidex/outdoorflorida-multidex.gradle
cordova.system.library.6=com.android.support:support-v13:27.+
cordova.system.library.7=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.8=com.google.firebase:firebase-messaging:11.6.2

**Comment by christocracy** [comment]
What a mess.

For every `com.android.support` dependency, set the version to `27.0.0`

Run it

**Comment by JeffCODEblum** [comment]
Thanks, Chris. I just changed firebase-messaging to v 11.8.0 and it worked. I will also change those versions to 27.0.0. I did not even think to edit this file. Thanks again!

**Comment by christocracy** [comment]
It’s not ideal to edit this file directly since it’s auto-generated.  Your changes will be lost when you `cordova platform remove android`

**Comment by JeffCODEblum** [comment]
Is there a way to manually set these settings in ionic so that they will persist? Sorry if this is out of scope for this issue, I know it is more of an Ionic question. I'm still somewhat of a noob when it comes to Ionic.
