### ISSUE TITLE
Plugin doesn't work during turning application.

### ISSUE THREAD

**Issue by vadim22** [transistorsoft/cordova-background-geolocation-lt#69]
I tested this plugin on the street in the app but Background Geolocation doesn't work, I didn't get any GPS coordinates. What can be the problem? I launch this plugin in controller on Ionic Framework with such code:

```
var bgGeo = window.BackgroundGeolocation;
var options = {
        disableElasticity: false,
        locationUpdateInterval: 10000,
        fastestLocationUpdateInterval: 5000,
        activityRecognitionInterval: 10000,
        activityType: 'AutomotiveNavigation',
        debug: false
      };
      bgGeo.configure(function(location, taskId) {
          console.log('BackgroundGeolocationConfig');
          console.log(location.coords);
          $scope.getColorStatus(location.coords.accuracy);
          console.log($scope.transfer.location_gps_status);
          $scope.sendLocation(location);


        $timeout(function () {
          bgGeo.finish(taskId);
        }, 1000);
      }, function(error) {
        console.error('BackgroundGeolocationConfig',error);
      }, options);

  $ionicPlatform.on('pause', function(event) {
bgGeo.start();
});

 $ionicPlatform.on('resume', function(event) {
  bgGeo.stop();
});
```

**Comment by christocracy** [comment]
Are you still having issues?  Sorry, I just discovered I wasn't getting notifications on issues from own plugin.

**Comment by Inwinder** [comment]
Hi Chris,
I am also kind of facing the same issue. If the app is in the background or not running, it is not updating the server, though its was working for iOS 9, currently in iOS 9.2 / 9.3 it is not updating. Under the settings I found for the Location, that by default it selects location access for "While Using the App" rather than, "Always". Please you please help me in this?

Thanks,
Inwinder

**Comment by christocracy** [comment]
- There were not changes by Apple in location-services between ios9, 9.2, 9.3.
- The plugin's default setting for `locationAuthorizationRequest` is 'Always`.

I suggest you delete the app from your device and re-install.  There is no issue with the plugin.
