### ISSUE TITLE
 Error after installation of the android ionic plugin 3

### ISSUE THREAD

**Issue by renanmoraes** [transistorsoft/cordova-background-geolocation-lt#691]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: 5.0.1
* Device manufacturer / model: Motorola G1
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin config

## Expected Behavior
The expectation is to build the application, everything worked before the installation.

## Actual Behavior
````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
37 actionable tasks: 1 executed, 36 up-to-date
(node:24793) UnhandledPromiseRejectionWarning: Error: /home/renan/projects/tv-driver/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
    at ChildProcess.whenDone (/home/renan/projects/tv-driver/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
(node:24793) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24793) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
# Project target.
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.system.library.2=com.android.support:support-v4:24.1.1+
cordova.gradle.include.1=cordova-plugin-googlemaps/topvans-tbxml-android.gradle
cordova.system.library.3=com.google.android.gms:play-services-maps:15.0.1
cordova.system.library.4=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.5=com.android.support:support-core-utils:26.1.0
cordova.gradle.include.2=cordova-plugin-background-fetch/topvans-build.gradle
cordova.system.library.6=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.7=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/topvans-build.gradle
```

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1. Create new project ionic
2. run cordova plugin add cordova-background-geolocation-lt
3. run npm i cordova-background-geolocation-lt
4. run ionic cordova run android

## Debug logs

`  "dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@ionic-native/camera": "^4.7.0",
    "@ionic-native/core": "^4.7.0",
    "@ionic-native/google-maps": "^4.8.2",
    "@ionic-native/social-sharing": "^4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/pro": "1.0.20",
    "@ionic/storage": "2.1.3",
    "cordova-android": "7.0.0",
    "cordova-background-geolocation-lt": "^2.12.2",
    "cordova-plugin-background-fetch": "^5.4.1",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-googlemaps": "^2.3.5",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.4.0",
    "es6-promise-plugin": "^4.2.2",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "minimist": "^1.2.0",
    "rxjs": "5.5.10",
    "sw-toolbox": "3.6.0",
    "xml2js": "^0.4.19",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.9",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-googlemaps": {
        "API_KEY_FOR_ANDROID": "MYAPI",
        "PLAY_SERVICES_VERSION": "15.0.1",
        "ANDROID_SUPPORT_V4_VERSION": "26.1.0"
      },
      "cordova-background-geolocation-lt": {
        "LICENSE": "YOUR_LICENSE_KEY",
        "GOOGLE_API_VERSION": "11.8.0",
        "APPCOMPAT_VERSION": "27.0.0"
      }
    },
    "platforms": [
      "android"
    ]
  }`

**Comment by christocracy** [comment]
Please don't specify "Last Version".  That's meaningless in the future.

**Comment by christocracy** [comment]
Post your `platforms/android/project.properties`

**Comment by renanmoraes** [comment]
Did you see anything?

**Comment by christocracy** [comment]
See any what?  I asked you to post your `platforms/android/project.properties`

**Comment by renanmoraes** [comment]
# Project target.
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.system.library.2=com.android.support:support-v4:24.1.1+
cordova.gradle.include.1=cordova-plugin-googlemaps/topvans-tbxml-android.gradle
cordova.system.library.3=com.google.android.gms:play-services-maps:15.0.1
cordova.system.library.4=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.5=com.android.support:support-core-utils:26.1.0
cordova.gradle.include.2=cordova-plugin-background-fetch/topvans-build.gradle
cordova.system.library.6=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.7=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/topvans-build.gradle


kkkkk, I added the question

**Comment by renanmoraes** [comment]
Cordova Plugins:

cordova-background-geolocation-lt 2.12.2 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

**Comment by christocracy** [comment]
When you see mixed versions of `com.android.support` and `play-services`, your screwed.  All these dependency version must be aligned to the same version.

BackgroundGeolocation exposes [`GOOGLE_API_VERSION, APP_COMPAT_V7_VERSION`](https://github.com/transistorsoft/cordova-background-geolocation-lt#variable-google_api_version-1160).

It's up to each plugin to provide you a mechanism to align google dependencies.  You'll have to consult with your other plugins to see if they have something similar (eg: `cordova-plugin-googlemaps`, `cordova-plugin-x-socialsharing`).

In the meantime, hack it:
```diff
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
+cordova.system.library.1=com.android.support:support-v4:27.0.0
cordova.system.library.2=com.android.support:support-v4:27.0.0
cordova.gradle.include.1=cordova-plugin-googlemaps/topvans-tbxml-android.gradle
cordova.system.library.3=com.google.android.gms:play-services-maps:15.0.1
cordova.system.library.4=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.5=com.android.support:support-core-utils:27..0
cordova.gradle.include.2=cordova-plugin-background-fetch/topvans-build.gradle
cordova.system.library.6=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.7=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/topvans-build.gradle
```

**Comment by renanmoraes** [comment]
I'm trying to replace it to see if it works, but it was not.

**Comment by renanmoraes** [comment]
But the error has changed. 

FAILURE: Build failed with an exception.

* What went wrong:
Task 'cdvBuildDebug' not found in root project 'android'.


* Try:

Run 
gradlew tasks to get a list of available tasks. Run with 
--stacktrace
 option to get the stack trace. Run with 
--info
 or 
--debug
 option to get more log output.


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:26874) UnhandledPromiseRejectionWarning: Error: /home/renan/projects/tv-driver/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Task 'cdvBuildDebug' not found in root project 'android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (/home/renan/projects/tv-driver/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
(node:26874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by christocracy** [comment]
[Let me google that for you](https://www.google.ca/search?q=Task+%27cdvBuildDebug%27+not+found+in+root+project+%27android%27.&oq=Task+%27cdvBuildDebug%27+not+found+in+root+project+%27android%27.&aqs=chrome..69i57j0.470j0j4&sourceid=chrome&ie=UTF-8)

**Comment by renanmoraes** [comment]
Incredibly just remove and add the platform again and it worked. Thank you so far.
