### ISSUE TITLE
Posting data to server

### ISSUE THREAD

**Issue by srikanth15794** [transistorsoft/cordova-background-geolocation-lt#692]
Background Geolocation plugin is able to hit an url, but the data like params are not posting. Just an empty array is posting to the server even if I included the headers also. Is there any way to achieve it ?

**Comment by christocracy** [comment]
The data is there.  You’re not looking for it in the right place.

This question typically is asked by php users.  Are you using php?

**Comment by srikanth15794** [comment]
Yes im using php  Yii2 with oauth2 authentication

**Comment by christocracy** [comment]
Duplicate #2
