### ISSUE TITLE
can't get value from method POST using file_get_contents()

### ISSUE THREAD

**Issue by okkypt** [transistorsoft/cordova-background-geolocation-lt#695]
Hello i am a newbie, this plugin already run in my device, but i cant get the value from that params (latitude,longitude)

## Expected Behavior
get longitude and latitude as parameter from bgGeo.ready

## Actual Behavior
this plugin request to my server .php, but i cant get the value from the param

## Context
i already set this
```javascript
bgGeo.ready({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 1,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 1000,
        stopTimeout: 5,
        // Application config
        debug: true,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        // HTTP / SQLite config
        url: "http://testing.com/fake.php",
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3,
        headers: {  // <-- Optional HTTP headers
            "X-FOO": "bar"
        },
        params: {   // <-- Optional HTTP params
            latitude: "321",
            longitude : "321"
        }
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        if (!state.enabled) {
            bgGeo.start();
        }
    });
```

and this is my php code (already sync with my db)
$data = file_get_contents("php://input");
$array = json_decode($data,true);

$sql = "INSERT INTO tested (latitude,longitude,jam) values('".$array['0']['latitude']."','".$array[0]['longitude']."',now())";
$result = mysqli_query($conn,$sql);

why my $array['0]['latitude'] still 0 in database ? i need help, Thankyou!

**Comment by christocracy** [comment]
I have no idea why you expect the data to look like an `$array`.  Why don't you try `echo $data` and see what the raw data *actually* looks like.

**Comment by okkypt** [comment]
sorry chris im a newbie, how to see echo $data? 
i just see echo $data in my browser with javascript request post. but if i use javascript post reques with param, and run it to browser, it will give me latitude=321&longitude=321
what must i do then ?

**Comment by christocracy** [comment]
Look at your server logs.  PHP prints echo to the server log.  You *are* watching your server logs, right??

**Comment by christocracy** [comment]
If you’re developing server code, it’s crucial to be able to log feedback from http requests.

If you’re not watching your server logs, you might as well be blindfolded.

I can’t help you if you can’t help *yourself*.  Stop what you’re doing and figure out how to observe servernlogs.

**Comment by okkypt** [comment]
oh sorry chris, i can see this echo $data.
like this right ?
{"location":{"event":"providerchange","provider":{"network":true,"gps":true,"enabled":true,"status":3},"is_moving":false,"uuid":"b73a1033-7b08-47c0-b6f8-ffa42b00ca89","timestamp":"2018-06-07T19:29:36.376Z","odometer":414.4,"coords":{"latitude":-7.1499661,"longitude":111.8839461,"accuracy":17.6,"speed":-1,"heading":-1,"altitude":-1},"activity":{"type":"still","confidence":100},"battery":{"is_charging":false,"level":0.5},"extras":{}}}

**Comment by christocracy** [comment]
Correct, now modify your server code accordingly to consume *that* data structure.

**Comment by okkypt** [comment]
chris is it object right ? why i cant get the value like $data->location->coords->latitude ?
or i am wrong ?

**Comment by christocracy** [comment]
I haven’t used php since 2006, but it’s probably:

```
$data[“location”][“coords”]
```

**Comment by okkypt** [comment]
its not corret, illegal string log said chris.

**Comment by christocracy** [comment]
It’s up to you to figure out how to iterate your data object.  This is not in the scope of the plugin.

The JSON is clearly there.  My job is done.  Google is your friend.

**Comment by okkypt** [comment]
Oke, Thankyou Chris for your help! awesome

**Comment by okkypt** [comment]
Chris, i already get the lat long. but i need to parse the params like userId maybe. i put it on params but it doesnt show when i use file_get_contents(). hope you can help. @christocracy

**Comment by christocracy** [comment]
#params are appended into the same JSON data fetched from ` file_get_contents("php://input");`, into the root of the data-structure.

You might want to have a *careful* read of the docs for #ready method if you’re *changing* #params while developing and expecting to see those changes.

**Comment by okkypt** [comment]
THANKYOU @christocracy i already give `reset:true` in the #ready . but would it be a problem when i give `reset:true` ?

**Comment by christocracy** [comment]
It’s not a problem.  The plugin stores its state in permanent storage.  When you use #setConfig at runtime, those changes will be persisted.

If you reset: true at each boot, those runtime changes with #setConfig will be lost.

reset: true simply resets the plugin to documented defaults before applying the config supplied to #ready.

**Comment by okkypt** [comment]
@christocracy sorry for late reply after a vacation. oke chris, thanks for your support, btw awesome plugin!
