### ISSUE TITLE
Blue line in header when app use location

### ISSUE THREAD

**Issue by webquali** [transistorsoft/cordova-background-geolocation-lt#70]
Hello, can you help understand. It is possible have the same in your plugin?
http://9to5mac.com/2014/06/04/apple-improves-location-services-in-ios-8-with-when-in-use-mode-visit-monitoring/

**Comment by christocracy** [comment]
What, visit monitoring?  Not currently.  I did some testing with it once,
it worked.

On Monday, February 8, 2016, webquali <notifications@github.com> wrote:

> Hello, can you help understand. It is possible have the same in your
> plugin?
>
> http://9to5mac.com/2014/06/04/apple-improves-location-services-in-ios-8-with-when-in-use-mode-visit-monitoring/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/70>
> .
>


-- 
Snet form Gmail Mobile

**Comment by calummoore** [comment]
This would be a really useful feature. 

The blue bar represents a difference in the permissions that are being requested from the user for location. The `requestAlwaysAuthorization` allows the app to use location services at any point, whereas `requestWhenInUseAuthorization` only allows the app to continue using location if it is started within the app.

I believe this can't be done at present (as the code that needs to be modified is within the `TSLocationManager.framework`). It would be great to have this as an option that could be configured.

_(As discussed over e-mail)_

**Comment by christocracy** [comment]
Implemented this in Premium repo.
