### ISSUE TITLE
How to view Log

### ISSUE THREAD

**Issue by paulatrockhill** [transistorsoft/cordova-background-geolocation-lt#701]
## Your Environment
* Plugin version: 2.11.0 beta 9
* Platform: iOS 
* OS version: iOS 10.13.4
* Device manufacturer / model: simulator iPhoneX 11.4
* Cordova version (`cordova -v`): 8.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
  browser 5.0.3
  ios 4.5.4
* Plugin config 
cordova-android-support-gradle-release 1.2.1 "cordova-android-support-gradle-release"
cordova-background-geolocation 2.11.0-beta.9 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.3.0 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-ios-keychain 3.0.1 "KeyChain Plugin for Cordova iOS"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-whitelist 1.3.3 "Whitelist"

## Expected Behavior
How to find the log file in my machine in order to share you to ask few doubts? Please explain in details.

we are running our app from terminal cordova build ios & cordova emulate ios (not from Xcode)

**Comment by christocracy** [comment]
See Wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)
