### ISSUE TITLE
ios - plugin does not work after app is terminated

### ISSUE THREAD

**Issue by Hector52mrs** [transistorsoft/cordova-background-geolocation-lt#704]
I am not provide any url to config of plugin but i am using 
`this.bgGeo.getLocations().then((locations)=> {});` method to track.
this plugin is worked fine when app is running but after app is terminated plugin does not work.
i.e. plugin does not store location when app is not running.

when am i used simulator to test plugin with Freeway Drive then `getLocation()` method is worked after app is terminated but when i am used real device then app is not worked after app is terminated.

When i test this plugin with real device then i put `distanceFilter: 50, stationaryRadius:50` and i am going around 3 km for testing but after app is terminated , plugin does not work.

## Your Environment
* Plugin version: 2.12.2
* Platform: iOS
* OS version: 10.2.1
* Device manufacturer / model: iPhone 5s
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 4.5.4
* Plugin config
`this.bgGeo.ready({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 50,
        stationaryRadius: 50,
        // Activity Recognition config
        stopTimeout: 5,
        // Application config
        debug: true,  // <-- Debug sounds & notifications.
        reset: true,
        logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3

    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        // this.bgGeo.start();
    });`

please see my whole code for better understand.

`this.platform.ready().then(() => {
                  this.bgGeo = (<any>window).BackgroundGeolocation;
                  this.onDeviceReady();
                });`

`onDeviceReady() {

    this.bgGeo.on('location', this.onLocation.bind(this));
    this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
    this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
    this.bgGeo.on('geofence', this.onGeofence.bind(this));
    this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));

    // BackgroundGeoLocation is highly configurable.
    this.bgGeo.ready({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 50,
        stationaryRadius: 50,
        // Activity Recognition config
        stopTimeout: 5,
        // Application config
        debug: true,  // <-- Debug sounds & notifications.
        reset: true,
        logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3

    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        this.bgGeo.start();
    });

  }`

`  
onLocation(location, taskId) {
    console.log('- location: ', location);
      if(location.sample === true) {

        this.bgGeo.getLocations().then((locations)=> {
          this.arrLocations = [];
          console.log("stored locations: ", locations);
                for(let i=0; i<locations.length; i++) {
                    var millisec = new Date(locations[i].timestamp);
                    var milliInDate = moment(millisec).format('YYYY-MM-DDTHH:mm:ss');

                    this.arrLocations.push({
                        Lat: locations[i].coords.latitude,
                        Long: locations[i].coords.longitude,
                        Date: milliInDate,
                        BatteryPerc: locations[i].battery.level
                    });
                }

                setTimeout(()=> {
                     // push data to server
                 },3000);
        }).catch((err)=> {
          console.log('error: ', err);
        });

      }

    this.bgGeo.finish(taskId);
  }
`

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Hector52mrs** [comment]
hello sir, please update me asap

**Comment by christocracy** [comment]
See [`#stopOnTerminate`](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-iOS.md#config-bool-stoponterminate-yes)

Yes, your iOS app *does* terminate.  It will reboot after you move by at least 200 metres and resume tracking.  It's completely in iOS' hands to reboot your app and depends upon the local network environment and requires Wifi enabled.

**Comment by Hector52mrs** [comment]
i already enable stopOnTerminate to false and also after i terminated the app i ride the bike around 2 km but plugin does not resume the tracking.
Why plugin is not stored the locations after app is terminated ?

**Comment by Hector52mrs** [comment]
i am calling `getLocations ()` method in `onLocation ()` method

**Comment by christocracy** [comment]
with `debug: true`, the plugin will tell you and notify you when iOS reboots your app in the background.  If you don't *see* and *hear* iOS re-awakening your app, then your app is not rebooting, thus no locations recorded.

The plugin is at the mercy of iOS and your local network environment (and wifi enabled).  All you can do is `stopOnTerminate: false` and keep testing in other directions.

**Comment by Hector52mrs** [comment]
if i am moving around 2-3 km and after that app also not rebooted then what should i do ?

**Comment by christocracy** [comment]
I do not know.  It it works in the sim, your problem is the network environment (eg: spacing of cell towers, lack of wifi signals).

**Comment by Hector52mrs** [comment]
no man, i am giving 4g network and network speed is not slow.

**Comment by christocracy** [comment]
If it works in sim, that's all you can do.

**Comment by Hector52mrs** [comment]
i tested in both sim and wifi but at both time plugin is not worked after app is terminated.

**Comment by Hector52mrs** [comment]
I already saw your video man, i am not telling that problem is in your plugin but i am telling that your problem is not work in my project and i am just telling you please find how ?

**Comment by Hector52mrs** [comment]
And i am calling http URL custom not from plugin

**Comment by Hector52mrs** [comment]
And also i want to ask that is this plugin store the location when device is offline ?

**Comment by christocracy** [comment]
>is this plugin store the location when device is offline ?

Yes

**Comment by Hector52mrs** [comment]
Hello Man,
onLocation method is also call after app is terminated but only when i am testing in the simulator.
But when i am testing the app in real device then onLocation method does not call after app is terminated. and also after app terminated, i moved around 2-3 km but no any get update.
Why man ?

**Comment by christocracy** [comment]
It’s completley up to iOS to reboot your app after termination.  If it works in the sim, that’s all you can do.  Everything else depends upon your network environment and device settings (eg spacing of cell towers, WiFi enabled on device, “Always” location authorized.)

**Comment by aaronharper123** [comment]
ok let me check

**Comment by christocracy** [comment]
Closed for lack of feedback.

**Comment by yomencity** [comment]
@christocracy What do yo mean " If it works in the sim, that’s all you can do. Everything else depends upon your network environment and device settings (eg spacing of cell towers, WiFi enabled on device, “Always” location authorized.)"?
I have same issue. And I can not still solve that problem. and I tested your plugin with real device(IPhone 6) which I can not call someone with. Then in my device background location service doesn't work? because of lack of sim?

**Comment by christocracy** [comment]
@yomencity  I test will iOS devices with no sim all the time (iPhone 6s, iPhone 5).  They have no trouble at all with tracking.  Obviously they can't upload locations until I return to my office Wifi network.

**Comment by yomencity** [comment]
Then, what is the problem in my case?
I made stopOnTerminate be false already and walked more than 2 miles.

**Comment by yomencity** [comment]
And I don't have any trouble in android

**Comment by yomencity** [comment]
@christocracy Would you show me your code especially about setconfig?

**Comment by christocracy** [comment]
setConfig is irrelevant.

Show me *your* logs.

**Comment by yomencity** [comment]
logs which I get with adb logcat?

**Comment by yomencity** [comment]
In IOS I only get the message "waiting deice" after I command adb logcat.

**Comment by christocracy** [comment]
There’s no such thing as adb logcat with iOS.  See wiki Debugging.

**Comment by yomencity** [comment]
Then, What should I show you? my code?

**Comment by christocracy** [comment]
Read the wiki Debugging.

**Comment by yomencity** [comment]
[logcat.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2522359/logcat.txt)

**Comment by yomencity** [comment]
Sorry I don't know which part I should show you. It's very looooong

**Comment by christocracy** [comment]
Why are you sending me **Android logs** for an iOS issue??

Do you know what “adb” means?  **A**ndroid **D**evelopment **B**ridge.

If you can’t figure out the difference between Android logs vs iOS logs, no wonder you have issues.

**Comment by yomencity** [comment]
Which one you install first? cordova-background-geolocation-lt plugin or platform?

**Comment by yomencity** [comment]
I showed you the log using IOS console app.  ignore the file name

**Comment by christocracy** [comment]
Your logs are useless.  The instructions to fetch plugin logs are in the Wiki Debugging.

I’m ready to give up on you.

**Comment by christocracy** [comment]
It’s all explained In Wiki Debugging.  This is your last chance.

**Comment by yomencity** [comment]
Thanks for your chance.
But I want to ask you a question.
step1) 
bgGeo.getLog(function(log) {
  console.log(log);
});
step2 ) When testing at your work-station, you can observe the plugin logs in XCode: 

Is this way right?

**Comment by yomencity** [comment]
knock knock...
