### ISSUE TITLE
In android, #getGeoFences() returns an empty list.

### ISSUE THREAD

**Issue by efhilton** [transistorsoft/cordova-background-geolocation-lt#706]
On an android machine and/or emulator, #getGeofences() returns an empty list.

## Your Environment
* Plugin version: 2.11.0
* Platform: iOS or Android -- Android
* OS version: 
* Device manufacturer / model: Pixel 2
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config
 "cordova-background-geolocation-lt": {
        "LICENSE": "YOUR_LICENSE_KEY",
        "GOOGLE_API_VERSION": "11.8.0",
        "APPCOMPAT_VERSION": "27.0.0"
      }
## Expected Behavior

I should get a list of all the configured geofences.

## Actual Behavior

I get an empty array []

## Steps to Reproduce

1. Call #getGeofences() on an Android machine
2.
3.
4.

## Context

Get a list of all the geofences that have been stored in the geofences module.

**Comment by christocracy** [comment]
I cannot reproduce this in Console now in either `2.11.0` or `2.12.2`:

![](https://dl.dropboxusercontent.com/s/mrfc9jdq9j2ymxm/Screenshot%202018-06-20%2011.45.29.png?dl=1)

**Comment by efhilton** [comment]
Found the solution: my list refresh was being called before the geofence tracker was ready. Hence the empty list. I now trigger the list refresh from geofenceschanged callback. It's been working every time.
