### ISSUE TITLE
Android not fetching current location and updating it to server

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/cordova-background-geolocation-lt#707]
## Your Environment
* Plugin version: 1.3.0 
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung j7 Prime
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config 

`this.BackgroundGeolocation.setConfig({
            desiredAccuracy: 0,
            distanceFilter: 2000,
            disableElasticity: true,
            stopOnTerminate: false,
            url: Variables.api_url + "loads/" + this.currentLoad.id + "/tracking.json",
            batchSync: true,
            maxDaysToPersist: 30,
            headers: {
                "Authorization": "Token " + this.auth.token()
            }
        });
        this.gps.start();`

## Expected Behavior
The plugin needs to track the current location of the user and then update to the api, this is working fine in ios

## Actual Behavior
in android, during my debug
` private void getCurrentPosition(CallbackContext callbackContext, JSONObject options) {
}
`
its failure  

## Debug logs
06-15 09:53:33.143 30458-864/com.docandtrack.app I/TSLocationManager: - reconfigure BackgroundGeolocationService
06-15 09:53:33.143 30458-864/com.docandtrack.app I/TSLocationManager: - applyConfig
06-15 09:53:33.153 30458-864/com.docandtrack.app I/TSLocationManager:   enabled: true
06-15 09:53:33.153 30458-864/com.docandtrack.app I/TSLocationManager:   isMoving: false
06-15 09:53:33.154 30458-864/com.docandtrack.app I/TSLocationManager:   distanceFilter: 2000.0
06-15 09:53:33.156 30458-864/com.docandtrack.app I/TSLocationManager:   desiredAccuracy: 0
06-15 09:53:33.157 30458-864/com.docandtrack.app I/TSLocationManager:   locationUpdateInterval: 0
06-15 09:53:33.158 30458-864/com.docandtrack.app I/TSLocationManager:   fastestLocationUpdateInterval: 0
06-15 09:53:33.160 30458-864/com.docandtrack.app I/TSLocationManager:   locationTimeout: 0
06-15 09:53:33.160 30458-864/com.docandtrack.app I/TSLocationManager:   activityRecognitionInterval: 0
06-15 09:53:33.163 30458-864/com.docandtrack.app I/TSLocationManager:   minimumActivityRecognitionConfidence: 0
06-15 09:53:33.166 30458-864/com.docandtrack.app I/TSLocationManager:   triggerActivities: null
06-15 09:53:33.166 30458-864/com.docandtrack.app I/TSLocationManager:   stopTimeout: 0
06-15 09:53:33.169 30458-864/com.docandtrack.app I/TSLocationManager:   debug: false
06-15 09:53:33.170 30458-864/com.docandtrack.app I/TSLocationManager:   stopAfterElapsedMinutes: 0
06-15 09:53:33.171 30458-864/com.docandtrack.app I/TSLocationManager:   stopOnTerminate: false
06-15 09:53:33.173 30458-864/com.docandtrack.app I/TSLocationManager:   startOnBoot: false
06-15 09:53:33.174 30458-864/com.docandtrack.app I/TSLocationManager:   forceReloadOnLocationChange: false
06-15 09:53:33.175 30458-864/com.docandtrack.app I/TSLocationManager:   forceReloadOnMotionChange: false
06-15 09:53:33.175 30458-864/com.docandtrack.app I/TSLocationManager:   forceReloadOnGeofence: false
06-15 09:53:33.176 30458-864/com.docandtrack.app I/TSLocationManager:   maxDaysToPersist: 30
06-15 09:53:33.177 30458-864/com.docandtrack.app I/TSLocationManager:   url: **************
06-15 09:53:33.186 30458-864/com.docandtrack.app I/TSLocationManager:   method: null
06-15 09:53:33.190 30458-864/com.docandtrack.app I/TSLocationManager:   autoSync: false
06-15 09:53:33.193 30458-864/com.docandtrack.app I/TSLocationManager:   batchSync: true
06-15 09:53:33.194 30458-864/com.docandtrack.app I/TSLocationManager:   params: null
06-15 09:53:33.194 30458-864/com.docandtrack.app I/TSLocationManager:   headers: {"Authorization":"Token ****************************"}
06-15 09:53:33.195 30458-864/com.docandtrack.app I/TSLocationManager:   configureUrl: null
06-15 09:53:33.206 30458-864/com.docandtrack.app I/TSLocationManager:   configureInterval: 0
06-15 09:53:33.215 30458-864/com.docandtrack.app I/TSLocationManager:   maxBatchSize: 0
06-15 09:53:33.216 30458-864/com.docandtrack.app I/TSLocationManager:   extras: null
06-15 09:53:33.217 30458-864/com.docandtrack.app I/TSLocationManager:   foregroundService: false
06-15 09:53:33.217 30458-864/com.docandtrack.app I/TSLocationManager:   notificationTitle: null
06-15 09:53:33.218 30458-864/com.docandtrack.app I/TSLocationManager:   notificationText: null
06-15 09:53:33.218 30458-864/com.docandtrack.app I/TSLocationManager:   notificationColor: null
06-15 09:53:33.218 30458-864/com.docandtrack.app I/TSLocationManager: ----------------------------------------
06-15 09:53:33.219 30458-864/com.docandtrack.app I/TSLocationManager: - requesting activity updates 10000
06-15 09:53:33.250 30458-865/com.docandtrack.app I/TSLocationManager: - Activity received: still, confidence: 100
06-15 09:53:33.256 30458-865/com.docandtrack.app I/TSLocationManager: - setPace:  motionStateChanged? false, isMoving? false, wasMoving? false
06-15 09:53:33.257 30458-865/com.docandtrack.app I/TSLocationManager: - removeLocationUpdates
06-15 09:53:33.257 30458-865/com.docandtrack.app I/TSLocationManager:   PendingIntent is null.  No updates to remove
06-15 09:53:35.011 30458-31055/com.docandtrack.app D/TSLocationManager: execute: getState
06-15 09:53:35.022 30458-31055/com.docandtrack.app W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.getState blocked the main thread for 4538ms. Plugin should use CordovaInterface.getThreadPool().
06-15 09:53:35.065 30458-30458/com.docandtrack.app E/chromium: [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
06-15 09:53:35.067 30458-30458/com.docandtrack.app D/InputMethodManager: HSI from window - flag : 0 Pid : 30458
06-15 09:53:35.089 30458-30458/com.docandtrack.app E/chromium: [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
06-15 09:53:35.116 30458-30458/com.docandtrack.app W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 30458
06-15 09:53:35.119 30458-30458/com.docandtrack.app D/XWalkCordovaUiClient: onPageLoadStopped(file:///android_asset/www/location/91)
06-15 09:53:35.119 30458-30458/com.docandtrack.app D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/location/91)
06-15 09:53:35.129 30458-30458/com.docandtrack.app E/chromium: [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
06-15 09:53:35.131 30458-30458/com.docandtrack.app D/InputMethodManager: HSI from window - flag : 0 Pid : 30458
06-15 09:54:33.324 30458-30458/com.docandtrack.app I/TSLocationManager: - location timeout
06-15 09:56:38.961 30458-863/com.docandtrack.app I/TSLocationManager: - command received: Bundle[{name=getCurrentPosition, request=true}]
06-15 09:56:51.963 30458-30458/com.docandtrack.app I/TSLocationManager: - CDVBackgroundGeolocation onEventMainThread: getCurrentPosition
06-15 09:57:02.906 30458-30458/com.docandtrack.app I/TSLocationManager: - getCurrentPosition timeout, giving up

**Comment by christocracy** [comment]
>06-15 09:54:33.324 30458-30458/com.docandtrack.app I/TSLocationManager: - location timeout

Version `1.3.0` is *very* old.  The latest version is [`2.12.2`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md)

**Comment by shrashwin** [comment]
Yes, i tried with the new version but there were so many dependencies that caused issue in my over all app with android 7.0.0 that, i had to roll back. So it would be very huch helpful, if you could help me with this one.

**Comment by christocracy** [comment]
`2.11.0` supports < cordova-android@7.0.0.  It's the same core library.  the only difference is cordova xml config.

This isn't a problem with the library.  the native location api failed to return a location in the given timeout period (default 60s).  Check your device location settings.  Set it to "High Accuracy"

**Comment by shrashwin** [comment]
I checked in my device setting and the location method is set to "High Accuracy".
Also these are the permission in my manifest file

`
 <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
`

**Comment by christocracy** [comment]
You configured **`locationTimeout: 0`**!!

```
06-15 09:53:33.160 30458-864/com.docandtrack.app I/TSLocationManager: locationTimeout: 0
```

The plugin is waiting `0` seconds for a location to arrive.
