### ISSUE TITLE
Uncaught TypeError: BackgroundGeolocation.on Http is not a function

### ISSUE THREAD

**Issue by kushal-ost** [transistorsoft/cordova-background-geolocation-lt#708]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS or Android: Both
* OS version: Ubunto
* Device manufacturer / model: Any device of android / iOS
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
* IONIC VERSION : IONIC v1

Installed platforms:
  android 7.0.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

* Plugin config:
 ```
  <plugin name="cordova-background-geolocation-lt" spec="^2.12.2">
        <variable name="LICENSE" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" />
        <variable name="GOOGLE_API_VERSION" value="11.8.0" />
        <variable name="APPCOMPAT_VERSION" value="27.0.0" />
    </plugin>
```

## Expected Behavior

I am using this plugin and. After event change, it should run API.

## Actual Behavior

It does not hit API, after event API response. It was working fine earlier. I have changed 2 things-
a) I have added license key to plugin.
b) Updated android version to 7.0.0

## Context

I am trying to hit api after event change like enter or exit

## Debug logs

app.js:115 Uncaught TypeError: BackgroundGeolocation.onHttp is not a function
    at app.js:115
    at Array.<anonymous> (ionic.bundle.js:56238)
    at Channel.onPlatformReady (ionic.bundle.js:2496)
    at Channel.fire (cordova.js:842)
    at cordova.js:229

**Comment by christocracy** [comment]
Correct.  These `onX` methods have been removed.

Use `#on(event, callback, [failure])`

**Comment by kushal-ost** [comment]
Hi Does this plugin support real time tracking  of marker by drawing the geofence places ?

**Comment by christocracy** [comment]
The is not involved with the UI at all.  It’s up to you to listen to events and perform your own drawing.

**Comment by kushal-ost** [comment]
Hi, Now I am using
