### ISSUE TITLE
Plugin callback returns multiple location data on initiate call

### ISSUE THREAD

**Issue by abhijithp** [transistorsoft/cordova-background-geolocation-lt#709]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS / Android
* OS version: 11 above 
* Device manufacturer / model: iphone 5s above
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0 / ios 4.5.4
* Plugin config: // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 10,
        locationUpdateInterval: TrackingSequence*1000,
        fastestLocationUpdateInterval: 4000,
        disableElasticity: true,
        // Activity Recognition config
        activityType: 'AutomotiveNavigation',
        activityRecognitionInterval: 5000,
        stopTimeout: 5,
        // Application config
        debug: false,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true

## Expected Behavior
shouldn't return multiple location data on initiate call.

## Actual Behavior
returns multiple location data on initiate call. the no of location data returning increases after each initiate call.

![screen shot 2018-06-18 at 10 17 53 am](https://user-images.githubusercontent.com/11426641/41518590-f49b067c-72e0-11e8-82f4-1acfe7291a1e.png)

**Comment by christocracy** [comment]
This is correct behaviour.  See docs for [`#location`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#location) event.  You'll notice an attribute `location.sample`.  Those locations have not been persisted to the plugin's database.

These are merely the plugin zeroing in on the most accurate possible location.  The same thing when you boot Google Maps, for example where the  blue "accuracy circle" gets progressively smaller as the device connects to GPS satellites and the location becomes more accurate.
