### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by kingalione** [transistorsoft/cordova-background-geolocation-lt#71]
Hello. I have installed the plugin but when i start my app I get into the failure call back of BackgroundGeolocation which is

var failureFn = function(error) {
console.log('BackgroundGeoLocation error');
}

and the error variable contains "Class not found".. I dont know what this error is all about. I am using cordova 5.2.0 and testing on lollipop(Android API 22). Any help would be much appreciated.

**Comment by christocracy** [comment]
Have you paid for a license?  See the [README](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/README.md)

>This repo hosts the iOS platform available in the Premium Version. Android functionality is available 
>only in the Premium Version.

**Comment by kingalione** [comment]
Oh, I didn't saw that one. So with a license it will work like on iOS?

**Comment by christocracy** [comment]
Yes.
