### ISSUE TITLE
Regarding update places

### ISSUE THREAD

**Issue by kushal-ost** [transistorsoft/cordova-background-geolocation-lt#711]
Does this plugin support edit places ? 
There is inbuilt function of add and delete places

**Comment by christocracy** [comment]
This plugin has nothing to do with Android [Places SDK](https://developers.google.com/places/android-sdk/intro)

**Comment by kushal-ost** [comment]
I am not talking about Android Places SDK. 
I am asking about geofence that to add and delete there are inbuilt methods like addGeofence and removeGeofence , is there any method for update the geofence ?
