### ISSUE TITLE
#configure callback not called on iOS

### ISSUE THREAD

**Issue by iMarti** [transistorsoft/cordova-background-geolocation-lt#712]
The plugin is present (window.BackgroundGeolocation.configure exists) but calling it doesn't trigger a callback (success or error):

The following executes after the deviceready event:

window.BackgroundGeolocation..configure({
    debug: true,
    desiredAccuracy: -1,
    distanceFilter: 50
}, function (state) {
    console.log('BackgroundGeolocation is configured and ready to use');
}, function(error) {
    console.log('BackgroundGeolocation failed to init', error);
});

## Your Environment
* Plugin version: 2.12.2
* Platform: iOS
* OS version: 11.4
* Device manufacturer / model: iPhone SE
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  ios 4.5.4
Available platforms: 
  android ~7.0.0
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
* Plugin config
	<plugin name="cordova-background-geolocation-lt" spec="^2.11.0">
		<variable name="LICENSE" value="YOUR_LICENSE_KEY"/>
		<variable name="GOOGLE_API_VERSION" value="11.8.0"/>
		<variable name="APPCOMPAT_VERSION" value="27.0.0"/>
		<variable name="BACKGROUND_MODE_LOCATION" value="&lt;string>location&lt;/string>"/>
		<variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Always use is required for constant background location-tracking"/>
		<variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required"/>
		<variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required"/>
		<variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving"/>
	</plugin>

## Expected Behavior
success or callback function is called

## Actual Behavior
No callback called

## Debug logs
Getting this in the console, but it doesn't make sense as I trace that your plugin is there:

Appname[15072:6884538] CDVPlugin class CDVBackgroundGeolocation (pluginName: BackgroundGeolocation) does not exist.
Appname[15072:6884538] ERROR: Plugin 'BackgroundGeolocation' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
Appname[15072:6884538] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["BackgroundGeolocation1853331731","BackgroundGeolocation","getCurrentPosition",[{"timeout":15,"maximumAge":30000,"desiredAccuracy":500}]]

**Comment by christocracy** [comment]
`#configure` isn't called because you're not calling `#configure` -- the plugin isn't installed:

```
CDVPlugin class CDVBackgroundGeolocation (pluginName: BackgroundGeolocation) does not exist.
```

```
$ cordova plugins
```

**Comment by iMarti** [comment]
I thought that CDVBackgroundGeolocation was different from your plugin. How is it possible that window.BackgroundGeolocation and window.BackgroundGeolocation.configure are not null? I traced that.

**Comment by iMarti** [comment]
cordova plugins

cordova-background-geolocation-lt 2.12.2 "BackgroundGeolocation"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-hockeyapp 5.1.2 "HockeyApp"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"

**Comment by christocracy** [comment]
>How is it possible that window.BackgroundGeolocation and window.BackgroundGeolocation.configure

Because sometimes Cordova gets confused.  If you open XCode, you will almost certainly see the following files are missing from your `/Plugins` folder:
![](https://dl.dropboxusercontent.com/s/4ybysxj531vcrhg/Screenshot%202018-06-20%2009.47.34.png?dl=1)

**Comment by iMarti** [comment]
Correct. I reinstalled the plugin and those files are present. Let's close this, thank you.

**Comment by christocracy** [comment]
When in doubt.  remove / re-add plugin.  remove / re-add platform.  It *does happen* that Cordova fails to copy the plugin files to `/Plugins`
