### ISSUE TITLE
Geofence notifyOnEntry not working

### ISSUE THREAD

**Issue by mknnaren** [transistorsoft/cordova-background-geolocation-lt#713]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS and Android (Both)
* OS version: Android (8.0.0, 7.1.1), iOS (11.4)
* Device manufacturer / model: Android(Nokia 3[7.1.1], Nokia 5[8.0.0])
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 7.0.0
* Plugin config

{
        desiredAccuracy: 0,
        startOnBoot: false,
        stopOnTerminate: false,
        foregroundService: true,
        enableHeadless: true,
        notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
        notificationTitle: "GUERRINI",
        forceReloadOnGeofence: false,
        geofenceProximityRadius: 100,
        geofenceInitialTriggerEntry: false,
        distanceFilter: 0, // Must be 0 or locationUpdateInterval is ignored!
        locationUpdateInterval: 5000, // Get a location every 5 seconds
        stopAfterElapsedMinutes: 60,
        stopTimeout: 60,
        stopOnStationary: true,
        stationaryRadius: 15,
        activityRecognitionInterval: 1000,
        debug: false
      },
 BackgroundGeolocation.addGeofences(
        [
          {
            identifier: geoFenceData.applianceId,
            radius: 100,
            latitude: geoFenceData.latitude,
            longitude: geoFenceData.longitude,
            notifyOnEntry: true,
            notifyOnExit: true,
            notifyOnDwell: false,
            loiteringDelay: 30000,
            extras: {
              // Optional arbitrary meta-data
              appliance_id: geoFenceData.applianceId,
              appliance_name: geoFenceData.applianceName,
              appliance_nick_name: geoFenceData.applianceNickName,
              activate_time: geoFenceData.activationTime,
              user_id: geoFenceData.userId,
              latitude: geoFenceData.latitude,
              longitude: geoFenceData.longitude,
              popup_icon: geoFenceData.popupIcon
            }
          }
        ],

## Expected Behavior

Geofence event should trigger on entry.

## Actual Behavior

Geofence event trigger happens only on exit. I have configured to notify on both entry and exit.

## Steps to Reproduce

1. After I updated from 2.10.1 to 2.12.2 this issue is happening on both iOS and Android phones for all OS versions.
2. Configure the settings to notify on entry and exit but not dwell for geofence events.
3.
4.

## Context

I was trying to capture the geofence entry and exit events and show appropriate alerts to the user.

## Debug logs

This is pretty much reproducible on the demo app available in Android play store.

**Comment by christocracy** [comment]
The minimum reliable geofence radius is `150` meters.  For iOS, have you tested in the simulator?

**Comment by mknnaren** [comment]
No, I have tested it on real device. I have tested this issue on multiple devices and its the same result.
I get the notification/event trigger for geofence exit event but not for the entry.

I use to get the notification for both on 2.10.1 version. After the latest update I am getting this issue.

**Comment by mknnaren** [comment]
I will change the radius to 150 meters and get back to you on the results after a thorough field testing. Thank you for your quick suggestion. :+1:

**Comment by christocracy** [comment]
Test in simulator.  Set your `radius: 150` I test geofences in my neighbourhood *every* day.  [Here's yesterday](http://tracker.transistorsoft.com/transistor-ionic?device=Cordova-11FC8D2D-5A5E-4CC1-B3F8-D5C810817882&end=2018-6-19&start=2018-6-19)

**Comment by christocracy** [comment]
Update?

**Comment by mknnaren** [comment]
Hey,
After changing the geo-fence radius to 150m, the results were:
iOS > Worked on both entry and exit
Android > Worked only on exit.Still doesn't work for entry event.

I am still debugging on my configs if there is anything I could change and fix it for android.

**Comment by christocracy** [comment]
Increase to 200 meter radius.
Provide logs.

**Comment by mknnaren** [comment]
Hey,

Sorry for the delay in reply. 
Now both entry and exit events work for both platforms Android and iOS.
There was some issue in the app logic where it used to get stuck after events get triggered for some cases which was not being handled.

Thanks for your help. :-)

**Comment by kushal-ost** [comment]
What listener are you using to get notification or tracking event ?
