### ISSUE TITLE
providerchange event isn't fired when i turn location on and off

### ISSUE THREAD

**Issue by terracom2** [transistorsoft/cordova-background-geolocation-lt#714]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: Tested on 7.0 & 8.0
* Device manufacturer / model: Sony, LG, Samsung
* Cordova version (`cordova -v`): 
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config: 
```json
debug: false,
notificationPriority: -2,
notificationText: 'Tap to open',
desiredAccuracy: 0,
distanceFilter: 50,
notificationColor: "#ef3e41",
foregroundService: true,
notificationSmallIcon: "mipmap/notification_small",
stopOnTerminate: true,
startOnBoot: false
```

## Expected Behavior
A providerchange event should fire when i turn location on and off on my phone.

## Actual Behavior
The first time i install my app the plugin works as expected. Every time i turn locaion on and off an event is fired. But when i terminate my app after first install and run it again, the providerchange event doesn't fire.

## Steps to Reproduce
1. Install app
2. Close the location and wait for the providerchange event to occur
3. Terminate app
4. Open app again 
5. Turn location on and off
6. No providerchange event 
**if you open the app with location turned off and after the device ready event you turn the location on, new coordinates are never fetched.

## Context

Users might turn location on and off several times

## Debug logs
No errors thrown

**Comment by christocracy** [comment]
Be sure to listen to `providerchange` event *before* you call `#ready`

**Comment by terracom2** [comment]
The code used to start the plugin is shown below. As you can see, i listen to providerchange event before the ready function.

```javascript
this.bgGeo = (<any>window).BackgroundGeolocation;
    this.bgGeo.on('location', this.onLocation.bind(this));
    this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
    this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
    this.bgGeo.on('providerchange', this.onProviderChange.bind(this));

    this.bgGeo.configure({
      debug: false,
      notificationText: 'Message',
      desiredAccuracy: 10,
      distanceFilter: 50,
      notificationColor: "#ef3e41",
      foregroundService: true,
      notificationSmallIcon: "mipmap/notification_small",
      stopOnTerminate: true,
      startOnBoot: false
    }, (state) => {
      this.logger.Info("Background geolocation started","#9999ff");
      this.bgGeo.start(); / Start the geolocation plugin /
    });
```

**Comment by christocracy** [comment]
Where are you observing the evidence that the `providerchange` event doesn't fire?

**Comment by terracom2** [comment]
As shown in the above comment, the function below is binded to the providerchange event. The debug message is never shown. The providerchange event isn't fired when i terminate and then open my app again after first install.

```javascript
onProviderChange(state){
    this.logger.Debug(`Provider state change ${JSON.stringify(state)}`);
}
```

**Comment by christocracy** [comment]
After performing your steps, here's what I see in Javascript console after rebooting app:
![](https://www.dropbox.com/s/wz0h2ny8j7bubwn/Screenshot%202018-06-22%2009.12.34.png?dl=1)

As you can see:
```
[event] - providerchange
```

The `providerchange` event is fired always by the `#ready` method with the current state of location-provider.  It doesn't need any kind of *change* to occur.  It's fired always at app boot to let you know the current state.

**Comment by terracom2** [comment]
Your documentation states that a providerchange event is fired when a change in the state of the device's Location Services has been detected. eg: "GPS ON", "Wifi only". So when i turn gps off and on on my phone it should fire an event, right? Well the event is never fired.

As you can see below the first time i run my app the providerchange event is fired after #ready and every time i turn gps on and off.

![35a42f18-1ef5-47d8-a991-7f3547ff11cc](https://user-images.githubusercontent.com/39090100/41780261-ea8f3ab8-763c-11e8-9ca2-e83324e69031.png)

![edc02e34-eb62-42e8-822e-305b5edf59ea](https://user-images.githubusercontent.com/39090100/41780380-3d1fbb2c-763d-11e8-914b-ea20dac3eb43.png)

When i run my app for the second time a providerchange event is fired after #ready but then nothing

![97ce0f76-85a3-43ab-8dbe-4d420340b31d](https://user-images.githubusercontent.com/39090100/41780426-5dca8a82-763d-11e8-9955-9bcce35d5d6e.png)

**Comment by christocracy** [comment]
I see the issue.  Fix will be posted to private repo monday.  btw, why are you posting in the free repo if you're a member of the private repo.  This fix won't appear here for weeks/months.
