### ISSUE TITLE
FCM plugin not installed

### ISSUE THREAD

**Issue by Vijay2704** [transistorsoft/cordova-background-geolocation-lt#715]
Hi,

Iam installing FCM plugin but i got Error: Invalid data, chunk must be a string or buffer, not object,

my project properties are...

target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/avra421082-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/avra421082-build.gradle

please clarify my doubt.

**Comment by christocracy** [comment]
This cannot be your entire `project.properties`.  Show me your:
```
$ cordova plugins
```

**Comment by Vijay2704** [comment]
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/avra421082-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:9.0.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/avra421082-build.gradle
cordova.gradle.include.3=cordova-plugin-firebase/avra421082-build.gradle
cordova.system.library.3=com.google.gms:google-services:+
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.5=com.google.firebase:firebase-core:+
cordova.system.library.6=com.google.firebase:firebase-messaging:+
cordova.system.library.7=com.google.firebase:firebase-crash:+
cordova.system.library.8=com.google.firebase:firebase-config:+
cordova.system.library.9=com.google.firebase:firebase-perf:+

**Comment by Vijay2704** [comment]
Hi Sir,

I am using Firebase plugin for getting Token,i am getting token but app is suddenly closing.

target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/avra421082-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:9.0.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/avra421082-build.gradle
cordova.gradle.include.3=cordova-plugin-firebase/avra421082-build.gradle
cordova.system.library.3=com.google.gms:google-services:+
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.5=com.google.firebase:firebase-core:+
cordova.system.library.6=com.google.firebase:firebase-messaging:+
cordova.system.library.7=com.google.firebase:firebase-crash:+
cordova.system.library.8=com.google.firebase:firebase-config:+
cordova.system.library.9=com.google.firebase:firebase-perf:+
above are Project properties and 
below are plugins list

cordova-background-geolocation-lt 2.12.2 "BackgroundGeolocation"
cordova-plugin-appminimize 1.0 "AppMinimize"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by christocracy** [comment]
Make the following changes to your `project.properties` and it will work.

```diff
cordova.gradle.include.1=cordova-plugin-background-fetch/avra421082-build.gradle
+cordova.system.library.1=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/avra421082-build.gradle
cordova.gradle.include.3=cordova-plugin-firebase/avra421082-build.gradle
+cordova.system.library.3=com.google.gms:google-services:15.0.1
+cordova.system.library.4=com.google.android.gms:play-services-tagmanager:15.0.1
+cordova.system.library.5=com.google.firebase:firebase-core:15.0.1
+cordova.system.library.6=com.google.firebase:firebase-messaging:15.0.1
+cordova.system.library.7=com.google.firebase:firebase-crash:15.0.1
+cordova.system.library.8=com.google.firebase:firebase-config:15.0.1
+cordova.system.library.9=com.google.firebase:firebase-perf:15.0.1
```

**Comment by Vijay2704** [comment]
Again i got error,

                             ^
  symbol:   method getResources()
  location: class FirebasePluginMessagingService
D:\Aditya\cordova-background-geolocation-SampleApp-master\platforms\android\app\
src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:18
4: error: cannot find symbol
            NotificationManager notificationManager = (NotificationManager) getS
ystemService(Context.NOTIFICATION_SERVICE);
                                                                            ^
  symbol:   method getSystemService(String)
  location: class FirebasePluginMessagingService
D:\Aditya\cordova-background-geolocation-SampleApp-master\platforms\android\app\
src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:19
7: error: cannot find symbol
            FirebasePlugin.sendNotification(bundle, this.getApplicationContext()
);
                                                        ^
  symbol: method getApplicationContext()
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get
full output
57 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by christocracy** [comment]
`cordova-plugin-firebase` is garbage.

**Comment by christocracy** [comment]
Go raise an issue at `cordova-plugin-firebase`.  Quote [this link](https://stackoverflow.com/questions/6843736/cannot-find-symbol-notification-service)

**Comment by christocracy** [comment]
In the meantime, try changing `15.0.1` in `project.properties` -> `11.8.0`

**Comment by Vijay2704** [comment]
i will try and update you.

Thank You.

**Comment by Vijay2704** [comment]
but not working,

present i am trying to install  ionic cordova plugin add cordova-plugin-fcm for push notifications

**Comment by Vijay2704** [comment]
Hi Sir,
when i am trying to install FCm i got this error ,  
(node:4268) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje
tion id: 1): TypeError: Invalid data, chunk must be a string or buffer, not obj
ct
please solve my error.
Thank you

**Comment by christocracy** [comment]
I have no idea.

**Comment by Scombr0** [comment]
I'm using this firebase plugin: https://github.com/arnesson/cordova-plugin-firebase

And then when installing this backgrouind-geolocation plugin set the play-services version to '+': ``ionic cordova plugin add cordova-background-geolocation-lt --variable GOOGLE_API_VERSION=+``

Removed platform.
Added platform.
Build -> Success.

That's how I made it work.

**Comment by Vijay2704** [comment]
Thanq it is working.
