### ISSUE TITLE
Mobile application reloads on app resume intermittently on iOS. 

### ISSUE THREAD

**Issue by abhijithp** [transistorsoft/cordova-background-geolocation-lt#716]
## Your Environment
Plugin version: 2.12.2
Platform: iOS 
OS version: iOS v 11 above
Device manufacturer / model: iphone 5s above
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): ios 4.5.4
Plugin config: // Geolocation config
    desiredAccuracy: 0,
    distanceFilter: 10,
    stationaryRadius: 10,
    locationUpdateInterval: TrackingSequence*1000,
    fastestLocationUpdateInterval: 4000,
    disableElasticity: true,
    // Activity Recognition config
    activityType: 'AutomotiveNavigation',
    activityRecognitionInterval: 5000,
    stopTimeout: 5,
    // Application config
    debug: false, // <-- Debug sounds & notifications.
    stopOnTerminate: false,
    startOnBoot: true

## Expected Behavior
Resuming the mobile app from background should go to its last active page.

## Actual Behavior
Application reloads on app resume intermittently. 

## Steps to Reproduce
1. Start the background geolocation tracking.
2. Navigate to any page other than the initial landing page.
3. Minimize the app and lock the screen
4. Resume app around after 10 - 15 mins

## Context
Testing the background location logging over a span of time.

**Comment by christocracy** [comment]
This is normal.  iOS periodically terminates apps in the background when memory is required by other apps.  This does not affect the operation of the plugin.  When the device moves ~200 meters from last known location, iOS will re-launch your app in the background and tracking will resume.
