### ISSUE TITLE
This plugin is not working when the app is closed.

### ISSUE THREAD

**Issue by kushal-ost** [transistorsoft/cordova-background-geolocation-lt#718]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS or Android : Both
* OS version: Latest
* Device manufacturer / model:  Any device of android / iOS
* Cordova version (`cordova -v`):  8.0.0
* Cordova platform version (`cordova platform ls`): Andriud- 7.0.0
* IONIC VERSION : IONIC v1

Installed platforms:

android 7.0.0
Available platforms:
browser ~5.0.1
ios ~4.5.4
osx ~4.0.1
windows ~5.0.0
www ^3.12.0

Plugin config:
` <plugin name="cordova-background-geolocation-lt" spec="^2.12.2">
       <variable name="LICENSE" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" />
       <variable name="GOOGLE_API_VERSION" value="11.8.0" />
       <variable name="APPCOMPAT_VERSION" value="27.0.0" />
   </plugin>
`

## Expected Behavior

It should response every 15 minutes when the app is closed

## Actual Behavior

When app gets closed, it does not respond.

**Comment by christocracy** [comment]
What makes you expect the plugin is supposed “respond every 15 minutes”?

Are you observing the logs?  See wiki “Debugging”

You have not posted the config you’re using with the plugin.  The config fron config.xml is not what’s requested.  It’s the config you’re providing to `#ready` method.

**Comment by kushal-ost** [comment]
I am using background fetch plugin to hit api when app is closed.


This is my log


Log 06-22 11:49:37.254 DEBUG [TSConfig c] ℹ️   Persist config
06-22 11:51:52.802 DEBUG [TSConfig c] ℹ️   Persist config
06-22 11:57:27.085 DEBUG [TSConfig c] ℹ️   Persist config
06-22 11:59:36.161 DEBUG [TSConfig c] ℹ️   Persist config
06-22 12:00:07.727 DEBUG [TSConfig c] ℹ️   Persist config
06-22 12:03:05.662 DEBUG [TSConfig c] ℹ️   Persist config
06-22 12:03:46.019 DEBUG [TSConfig c] ℹ️   Persist config
06-22 12:04:39.201 DEBUG [TSConfig c] ℹ️   Persist config
06-22 12:05:09.093 DEBUG [TSConfig c] ℹ️   Persist config
06-22 12:07:59.254 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:07:59.400 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640673,77.113457 acc=18 et=+4d2h37m53s759ms], age: 30ms, time: 1529649479365

06-22 12:07:59.409 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:07:59.475 DEBUG [TSLocationManager a] 17.547
06-22 12:11:19.236 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:11:19.325 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640676,77.113448 acc=17 et=+4d2h41m13s712ms], age: 4ms, time: 1529649679318

06-22 12:11:19.334 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:11:19.361 DEBUG [TSLocationManager a] 17.4375
06-22 12:14:39.238 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:14:39.302 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 3
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640670,77.113451 acc=18 et=+4d2h44m33s674ms], age: 18ms, time: 1529649879280

06-22 12:14:39.308 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:14:39.333 DEBUG [TSLocationManager a] 17.328
06-22 12:17:59.320 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:17:59.396 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 4
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640673,77.113455 acc=17 et=+4d2h47m53s763ms], age: 23ms, time: 1529650079369

06-22 12:17:59.414 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:17:59.452 DEBUG [TSLocationManager a] 17.625
06-22 12:21:19.364 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:21:19.474 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 5
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640673,77.113455 acc=18 et=+4d2h51m13s757ms], age: 13ms, time: 1529650279445

06-22 12:21:19.485 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:21:19.505 DEBUG [TSLocationManager a] 17.922
06-22 12:24:39.320 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:24:39.435 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 6
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640683,77.113456 acc=18 et=+4d2h54m33s742ms], age: 3ms, time: 1529650479430

06-22 12:24:39.439 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:24:39.470 DEBUG [TSLocationManager a] 17.6795
06-22 12:27:59.317 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:27:59.424 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 7
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640698,77.113460 acc=17 et=+4d2h57m53s729ms], age: 4ms, time: 1529650679417

06-22 12:27:59.431 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:27:59.462 DEBUG [TSLocationManager a] 17.437
06-22 12:31:19.362 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:31:19.420 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 8
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640695,77.113457 acc=18 et=+4d3h1m13s725ms], age: 4ms, time: 1529650879413

06-22 12:31:19.426 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:31:19.451 DEBUG [TSLocationManager a] 17.532001
06-22 12:34:39.402 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:34:39.509 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 9
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640675,77.113459 acc=17 et=+4d3h4m33s806ms], age: 11ms, time: 1529651079494

06-22 12:34:39.535 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:34:39.584 DEBUG [TSLocationManager a] 17.627
06-22 12:35:10.135 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 2.12.14 (270)
╠═════════════════════════════════════════════
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "disableElasticity": false,
  "disableStopDetection": false,
  "distanceFilter": 25,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "extras": {},
  "fastestLocationUpdateInterval": 10000,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": true,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": false,
  "geofenceInitialTriggerEntry": true,
  "geofenceProximityRadius": 5000,
  "geofenceTemplate": "",
  "headers": {
    "authorization": "oTSy0omKQgNMdqwXohDwIMyRGNHAasjcDzvRHqM5\/eU="
  },
  "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": false,
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "notificationColor": "",
  "notificationLargeIcon": "",
  "notificationPriority": 0,
  "notificationSmallIcon": "",
  "notificationText": "Location Service activated",
  "notificationTitle": "",
  "params": {
    "user_id": "63"
  },
  "persist": true,
  "schedule": [],
  "startOnBoot": false,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "http:\/\/www.childfinda.com\/process\/geofence.php",
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 0,
  "odometer": 0,
  "isFirstBoot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="BMI160 Accelerometer", vendor="BOSCH", version=2062200, type=1, maxRange=39.22661, resolution=0.0023956299, power=0.18, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="BMI160 Gyroscope", vendor="BOSCH", version=2062200, type=4, maxRange=34.906586, resolution=0.0010681152, power=0.9, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetometer", vendor="Yamaha", version=35193090, type=2, maxRange=2000.0, resolution=0.30059814, power=0.28, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.17999268, minDelay=-1}
╚═════════════════════════════════════════════
06-22 12:35:10.244 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:11910000)
06-22 12:35:10.283 DEBUG [c a] 
  ✅  Opened database
06-22 12:35:10.326 DEBUG [c prune] 
  ℹ️  PRUNE -1 days
06-22 12:35:10.399 DEBUG [a f] 
  ✅  Opened database
06-22 12:35:20.153 INFO [BootReceiver onReceive] 
╔═════════════════════════════════════════════
║ BootReceiver: com.childfinda.childfinda
╠═════════════════════════════════════════════
╟─ android.intent.action.MY_PACKAGE_REPLACED

06-22 12:38:30.492 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:38:30.640 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640686,77.113459 acc=17 et=+4d3h8m24s902ms], age: 39ms, time: 1529651310589

06-22 12:38:30.658 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:38:30.690 DEBUG [TSLocationManager a] 17.421
06-22 12:41:51.504 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:41:51.858 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640674,77.113459 acc=18 et=+4d3h11m46s103ms], age: 60ms, time: 1529651511790

06-22 12:41:52.000 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:41:52.330 DEBUG [TSLocationManager a] 17.5225
06-22 12:45:11.359 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:45:11.488 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 3
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640686,77.113458 acc=18 et=+4d3h15m5s762ms], age: 29ms, time: 1529651711450

06-22 12:45:11.510 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:45:11.596 DEBUG [TSLocationManager a] 17.624
06-22 12:48:31.401 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
06-22 12:48:31.511 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 4
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 28.640674,77.113458 acc=17 et=+4d3h18m25s795ms], age: 23ms, time: 1529651911483

06-22 12:48:31.550 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-22 12:48:31.646 DEBUG [TSLocationManager a] 17.657501
06-22 12:49:03.060 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 2.12.14 (270)
╠═════════════════════════════════════════════
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "disableElasticity": false,
  "disableStopDetection": false,
  "distanceFilter": 25,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "extras": {},
  "fastestLocationUpdateInterval": 10000,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": true,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": false,
  "geofenceInitialTriggerEntry": true,
  "geofenceProximityRadius": 5000,
  "geofenceTemplate": "",
  "headers": {
    "authorization": "oTSy0omKQgNMdqwXohDwIMyRGNHAasjcDzvRHqM5\/eU="
  },
  "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": false,
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "notificationColor": "",
  "notificationLargeIcon": "",
  "notificationPriority": 0,
  "notificationSmallIcon": "",
  "notificationText": "Location Service activated",
  "notificationTitle": "",
  "params": {
    "user_id": "63"
  },
  "persist": true,
  "schedule": [],
  "startOnBoot": false,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "http:\/\/www.childfinda.com\/process\/geofence.php",
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 0,
  "odometer": 0,
  "isFirstBoot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="BMI160 Accelerometer", vendor="BOSCH", version=2062200, type=1, maxRange=39.22661, resolution=0.0023956299, power=0.18, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="BMI160 Gyroscope", vendor="BOSCH", version=2062200, type=4, maxRange=34.906586, resolution=0.0010681152, power=0.9, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetometer", vendor="Yamaha", version=35193090, type=2, maxRange=2000.0, resolution=0.30059814, power=0.28, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.17999268, minDelay=-1}
╚═════════════════════════════════════════════
06-22 12:49:03.221 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:11910000)
06-22 12:49:03.250 DEBUG [c a] 
  ✅  Opened database
06-22 12:49:03.267 DEBUG [c prune] 
  ℹ️  PRUNE -1 days
06-22 12:49:03.341 DEBUG [a f] 
  ✅  Opened database
06-25 11:23:15.625 DEBUG [TSConfig c] ℹ️   Persist config
06-25 11:30:02.120 DEBUG [TSConfig c] ℹ️   Persist config
06-25 11:36:31.957 DEBUG [TSConfig c] ℹ️   Persist config
06-25 11:42:34.196 DEBUG [TSConfig c] ℹ️   Persist config
06-25 11:43:09.455 DEBUG [TSConfig c] ℹ️   Persist config
06-25 11:43:09.774 INFO [BootReceiver onReceive] 
╔═════════════════════════════════════════════
║ BootReceiver: com.childfinda.childfinda
╠═════════════════════════════════════════════
╟─ android.intent.action.MY_PACKAGE_REPLACED

06-25 11:45:15.875 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 2.12.14 (270)
╠═════════════════════════════════════════════
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "disableElasticity": false,
  "disableStopDetection": false,
  "distanceFilter": 25,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "extras": {},
  "fastestLocationUpdateInterval": 10000,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": true,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": false,
  "geofenceInitialTriggerEntry": true,
  "geofenceProximityRadius": 5000,
  "geofenceTemplate": "",
  "headers": {
    "authorization": "oTSy0omKQgNMdqwXohDwIMyRGNHAasjcDzvRHqM5\/eU="
  },
  "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": false,
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "notificationColor": "",
  "notificationLargeIcon": "",
  "notificationPriority": 0,
  "notificationSmallIcon": "",
  "notificationText": "Location Service activated",
  "notificationTitle": "",
  "params": {
    "user_id": 63
  },
  "persist": true,
  "schedule": [],
  "startOnBoot": false,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "http:\/\/www.childfinda.com\/process\/geofence.php",
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 0,
  "odometer": 0,
  "isFirstBoot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="BMI160 Accelerometer", vendor="BOSCH", version=2062200, type=1, maxRange=39.22661, resolution=0.0023956299, power=0.18, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="BMI160 Gyroscope", vendor="BOSCH", version=2062200, type=4, maxRange=34.906586, resolution=0.0010681152, power=0.9, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetometer", vendor="Yamaha", version=35193090, type=2, maxRange=2000.0, resolution=0.30059814, power=0.28, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.17999268, minDelay=-1}
╚═════════════════════════════════════════════
06-25 11:45:16.087 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:11910000)
06-25 11:45:16.126 DEBUG [c a] 
  ✅  Opened database
06-25 11:45:16.153 DEBUG [c prune] 
  ℹ️  PRUNE -1 days
06-25 11:45:16.240 DEBUG [a f] 
  ✅  Opened database

**Comment by kushal-ost** [comment]
I want that when the app is closed then then it should hit api like as it does when app is open.

To perform action when app is closed , I am writing code as ,

`var BackgroundFetch = window.BackgroundFetch;
 
        // Your background-fetch handler.
        var fetchCallback = function() {
            console.log('[js] BackgroundFetch event received');
            alert('after 1 min');
            // Required: Signal completion of your task to native code
            // If you fail to do this, the OS can terminate your app
            // or assign battery-blame for consuming too much background-time
            BackgroundFetch.finish();
        };
        
        var failureCallback = function(error) {
            console.log('- BackgroundFetch failed', error);
        };


        BackgroundFetch.configure(fetchCallback, failureCallback, {
            minimumFetchInterval: 1, // <-- default is 15
            stopOnTerminate: false,   // <-- Android only
            startOnBoot: true,        // <-- Android only
            forceReload: true         // <-- Android only
        });`

**Comment by kushal-ost** [comment]
Ok, So I need to just copied down the java code as explained in document or do we need to change also ?

But here how to declare that which api to call again after 15 mins when app is closed ?

Do we need to add 'build-extras.gradle' file for this ? 

Please suggest

**Comment by christocracy** [comment]
That Java code provides a sandbox for you to interact with `BackgroundFetch` / `BackgroundGeolocation` in native Android context.

No, you do not need to do anything with `build-extras.gradle`.  What do you want to do in the native `BackgroundFetchHeadlessTask`?  `BackgroundGeolocation#getCurrentPosition`?

**Comment by kushal-ost** [comment]
When my app is opened then I can get geofences API hit at interval... But when app closes , it stopped hitting API .

Also when app is closed then it does not give response of background http request.

What to do ? Please suggest

**Comment by christocracy** [comment]
iOS and Android are as different as Mars and Venus.  There's no correlation between the behaviour of the two.  Which are you talking about?

**Comment by kushal-ost** [comment]
I want this to be working first on Android.
I need that when app is closed then also it would send background geolocation http request

**Comment by christocracy** [comment]
All you need to do is `stopOnTerminate: false`.  If you've provided an `#url` to the plugin, the plugin will *not* cease tracking.

Show me *all* the Javascript you're using with the plugin.  You're doing something wrong.

**Comment by kushal-ost** [comment]
My app have something functionality like this---
Suppose there are two devices A and B.
If both app is open then if device A add any geofence place then it's get reflected in device B and I get response.

But if device A is opened and device B is closed then if I add any geofence place from device A then nothing happened to device B. There is no response.

Means it is working when app is open but not when app is closed.

I m already using stopOnTerminate to false in geolocation config

**Comment by christocracy** [comment]
Show me **all your Javascript**.  You are doing something *fundamentally wrong* in it.

**Comment by kushal-ost** [comment]
` BackgroundGeolocation.setLogLevel(BackgroundGeolocation.LOG_LEVEL_VERBOSE,function() {
      console.log("Changed logLevel success");
    });
    var config ={
      debug :true,
      geofenceProximityRadius :5000,
      geofenceInitialTriggerEntry : true,
      stopOnTerminate: false,
      distanceFilter: 25,
      forceReloadOnGeofence: true,
      url:"http://xxxxxxxxxxxxxxxxxxxxxxxxxxx.xxx",
      params: {
          user_id: $localStorage.userMaster.id,
        },
      headers: {
          authorization: $localStorage.apiAccessToken
        }
    }


    BackgroundGeolocation.getState(function(state) {
     //   alert(JSON.stringify(state));
        console.log('state data',JSON.stringify(state));
      });

    BackgroundGeolocation.configure(config, function(state) {
      if (!state.enabled) {
        BackgroundGeolocation.startGeofences(function(state) {
          console.log('- Geofence-only monitoring started', state.trackingMode);
        });
      }
    });

    // response from server
      BackgroundGeolocation.onHttp(function(response) {
       var resText = JSON.parse(response.responseText);
        window.plugins.OneSignal.getIds(function(ids) {
            self.deviceToken    =   ids.pushToken;
            self.userId         =   ids.userId;
        });


        if(resText.responseCode == 1 && typeof(resText.action) != "undefined" ){
            $rootScope.notifyEvent(resText.action, resText.placeName,  self.userId);
        }
      }, function(response) {
        var status = response.status;
        var responseText = response.responseText;
        console.log("- HTTP failure: ", status, responseText);
      })

      $rootScope.notifyEvent = function(action, place, oneSignalId) {
    
            var notify_data = {
             circleToken:$localStorage.userMaster.circleToken, 
             placeName:place, 
             action:action, 
             userId : oneSignalId
            }

        usersService.onesignotify(notify_data)
        .then(function(response){
            console.log('Response console', response);

        }, function(error) {
          alertmsgService.tostMessage('An error occurred. Please try again..');
        });
 }

    // Listen to geofences
    BackgroundGeolocation.on('geofence', function(params) {
        BackgroundGeolocation.start();
    });
    BackgroundGeolocation.on('geofenceschange', function(event) {
      console.log("geofenceschange fired! ", event);
    });


    BackgroundGeolocation.on('geofence', function(geofence) {
        var location    = geofence.location;
        var identifier  = geofence.identifier;
        var action      = geofence.action;
      });`

**Comment by christocracy** [comment]
1.  [minor] What are you executing `#getState` before `#configure`?  The callback to `#configure` provides you current state.
2.  [minor] `#configure` is deprecated in favour of new `#ready`
3.  [minor] Why `#setLogLevel` before `#configure`?  Just provide `logLevel` to your config `{}`.
4.  [major] Where do you get the idea to use `#onHttp` method?  there's no such method.  You *must* be seeing a Javascript error.  It's `BackgroundGeolocation.on('http', success, failure)`, just like *every other* event.
5.  [minor[ Listen to events *before* `#configure` / `#ready`.

When the plugin's `#startGeofence` method is executed, you'll see this in the logs:
```
06-25 22:56:38.775 31889 32008 D TSLocationManager: $ startGeofences()
06-25 22:56:38.784 31889 32008 D TSLocationManager: [c.t.locationmanager.util.b a]
06-25 22:56:38.784 31889 32008 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-25 22:56:38.828 31889 29743 I TSLocationManager: - Enable: false → true, trackingMode: 0
06-25 22:56:38.855 31889 31889 I TSLocationManager: [c.t.l.BackgroundGeolocationService onStartCommand]
06-25 22:56:38.855 31889 31889 I TSLocationManager: ╔═════════════════════════════════════════════
06-25 22:56:38.855 31889 31889 I TSLocationManager: ║ BackgroundGeolocation Service started
06-25 22:56:38.855 31889 31889 I TSLocationManager: ╠═════════════════════════════════════════════
06-25 22:56:38.883 31889 31889 I TSLocationManager: [c.t.l.BackgroundGeolocationService d]
06-25 22:56:38.883 31889 31889 I TSLocationManager:   ✅  Started in foreground
06-25 22:56:38.922 31889 31889 I TSLocationManager: [c.t.l.ActivityRecognitionService a]
06-25 22:56:38.922 31889 31889 I TSLocationManager:   🎾  Start activity updates: 10000
06-25 22:56:38.962 31889 31889 I TSLocationManager: [c.t.l.BackgroundGeolocationService a]
06-25 22:56:38.962 31889 31889 I TSLocationManager:   🔵  setPace: null → false
06-25 22:56:38.984 31889 31889 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
06-25 22:56:38.998 31889 31889 D TSLocationManager: [c.t.locationmanager.util.b a]
06-25 22:56:38.998 31889 31889 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-25 22:56:39.020 31889 29746 D TSLocationManager: [c.t.l.http.HttpService flush]
06-25 22:56:39.020 31889 29746 D TSLocationManager: ╔═════════════════════════════════════════════
06-25 22:56:39.020 31889 29746 D TSLocationManager: ║ HTTP Service
06-25 22:56:39.020 31889 29746 D TSLocationManager: ╠═════════════════════════════════════════════
06-25 22:56:39.030 32199 29679 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
06-25 22:56:39.056 31889 29746 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
06-25 22:56:39.133 20862 29682 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
06-25 22:56:46.526 31889 31889 D TSLocationManager: [c.t.l.l.SingleLocationRequest$2 onLocationResult]
06-25 22:56:46.526 31889 31889 D TSLocationManager: ╔═════════════════════════════════════════════
06-25 22:56:46.526 31889 31889 D TSLocationManager: ║ SingleLocationRequest: 10
06-25 22:56:46.526 31889 31889 D TSLocationManager: ╠═════════════════════════════════════════════
06-25 22:56:46.526 31889 31889 D TSLocationManager: ╟─ 📍  Location[fused 45.519240,-73.616980 hAcc=16 et=+27d3h56m40s417ms alt=44.099998474121094 vAcc=2 sAcc=??? bAcc=??? {Bundle[{requestId=10, verticalAccuracy=2.0}]}], age: 2101ms, time: 1529981804423
06-25 22:56:46.527 31889 29746 I TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult]
06-25 22:56:46.527 31889 29746 I TSLocationManager:   🔵  Acquired motionchange position, isMoving: false
06-25 22:56:46.547 31889 29746 D TSLocationManager: [c.t.l.l.TSLocationManager a] 16.183
06-25 22:56:46.577 31889 29746 D TSLocationManager: [c.t.l.g.TSGeofenceManager a]
06-25 22:56:46.577 31889 29746 D TSLocationManager: ╔═════════════════════════════════════════════
06-25 22:56:46.577 31889 29746 D TSLocationManager: ║ TSGeofenceManager found 3/4 within 1000 meters
06-25 22:56:46.577 31889 29746 D TSLocationManager: ╠═════════════════════════════════════════════
06-25 22:56:46.577 31889 29746 D TSLocationManager: ╟─ 🎾  Jfk
06-25 22:56:46.577 31889 29746 D TSLocationManager: ╟─ 🎾  Laj
06-25 22:56:46.577 31889 29746 D TSLocationManager: ╟─ 🎾  Bernard
06-25 22:56:46.577 31889 29746 D TSLocationManager: ╚═════════════════════════════════════════════
```

If you do not see the following, your code is not executing `#startGeofences`:
```
╔═════════════════════════════════════════════
06-25 22:56:38.855 31889 31889 I TSLocationManager: ║ BackgroundGeolocation Service started
06-25 22:56:38.855 31889 31889 I TSLocationManager: ╠═════════════════════════════════════════════
```

Are you launching the Javascript Web Console in Chrome to observe your app code for Javascript errors?  Do so.  Run `window.location.reload()` in Console to observe your app booting from scratch.

**Comment by kushal-ost** [comment]
You have mentioned 5 points out of which 4th point I have already corrected. Rest other minor point I will correct.
Yes I am consoling on chrome browser. 
Is there any way to check console when the app is closed. ?

Thanks in advance

**Comment by christocracy** [comment]
I want you to do the following and send me result from `$ adb logcat -s TSLocationManager`

- call `#stop` (perform directly from js console if you have no UI button to do this)
- terminate app.
- boot app
- terminate app.

Show me these logs.

No you can’t view web console when app is terminated.  There’s no JavaScript app running to observe.  You *do* realize your Cordova app *is* terminated when Android app is terminated, right?

**Comment by kushal-ost** [comment]
Thanks , I will update you in 2 hours..
