### ISSUE TITLE
My app is synchronizing the location but the deviceID and deviceModal is missing

### ISSUE THREAD

**Issue by razam217** [transistorsoft/cordova-background-geolocation-lt#72]
Hi, I am using this plugin. In sample app your plugin works fine, it synchronizes all the locations along with the device information. but in my app it is not sending the device model and device ID, even I've added cordova-device-plugin... I'm not sure what is the problem... although the device plugin version is same...

**Comment by christocracy** [comment]
My plugin has **nothing** to do with "device ID".

My SampleAp *arbitrarily* added that as an example of *extra data* that you can *optionally* append to the plugins `params` config.

It's completely up to you.
