### ISSUE TITLE
Unable to build android after updating to cordova 7.1.0

### ISSUE THREAD

**Issue by anurag0707** [transistorsoft/cordova-background-geolocation-lt#720]
## Your Environment
* Plugin version: 2.12.3-beta.1 
* Platform: Android
* OS version: windows
* Device manufacturer / model: Moto E3
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):7.1.0
* IONIC VERSION: IONIC v1

Plugin config:

          <plugin name="cordova-background-geolocation"> <variable name="LICENSE" 
          value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" />  </plugin>

## Expected Behavior
Should build with 6.4.0 cordova-android version and bgGeo object should get initialized.

## Actual Behavior
bgGeo is getting initialized only with cordova-android 7.1.0

## Context
With recent release of cordova 7.1.0 some of the cordova plugin are unable to find path for androidMainfest.xml as there is change in folder structure of android build and the plugin is not supporting cordova-android 6.4.0. So please provide a provision so that i can use the plugin with cordova-android 6.4.0

**Comment by christocracy** [comment]
See CHANGELOG.  2.11.0 supports Cordova-android < 7.

To use 2.12.x, you must use cordova-android >= 7.x

**Comment by anurag0707** [comment]
so what version of the plugin should I use if I want to go with Cordova-android 6.4.0

**Comment by christocracy** [comment]
As I said:

>”2.11.0 supports Cordova-android < 7.”
