### ISSUE TITLE
Geolocation prompt duplicate

### ISSUE THREAD

**Issue by kirstenfrager** [transistorsoft/cordova-background-geolocation-lt#722]
- Plugin version: 2.11.0
- Platform: Android
- OS version: 8.0
- Device manufacturer / model: Samsung Galaxy S9
- Cordova version (cordova -v): 7.1.0
- Cordova platform version (cordova platform ls): 6.4.0
- Plugin config

```
{
    reset: true,
    stopOnTerminate: false,
    startOnBoot: true
}
```

When we call `navigator.geolocation.getCurrentPosition(onSuccess, onFailure, config)`, immediately before `bgGeolocationPlugin.ready(config)`, android displays the following prompt twice: 

> Allow XXXX to access this device's location

This does not happen in android 7.0.
Ideally we just want the prompt to happen the one time, as changing the code is not trivial.

**Comment by christocracy** [comment]
You do not require `cordova-plugin-geolocation` in addition to background-geolocation plugin.

background-geolocation has its own `#getCurrentPosition` method.

If want to continue using `cordova-plugin-geolocation`, don't execute `#ready` until the callback of your `navigator.geolocation.getCurrentPosition onSuccess` callback fires.
