### ISSUE TITLE
App freeze on splashscreen after reload when pass background to foreground (tracking active)

### ISSUE THREAD

**Issue by Raffaele-LIZE** [transistorsoft/cordova-background-geolocation-lt#723]
I try to find why when my app which use your plugin (good plugin ^^), freeze on splashscreen.

## Your Environment
* Plugin version: ^2.12.0
* Platform: iOS
* OS version: 11.4
* Device manufacturer / model: iPhone 5S and more
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin config
`// Geolocation common
		this.desiredAccuracy             = 0; 
		this.distanceFilter              = 800;
		this.disableElasticity           = true;
		// Geolocation iOS
		// this.stationaryRadius            = 500;
		// Activity Recognition common
		this.activityRecognitionInterval = 60000;
		this.stopTimeout                 = 5;
		// HTTP & Persistence Options
		this.autoSync                    = true;
		// Application common
		this.stopOnTerminate             = true;
		this.startOnBoot                 = false;
		this.heartbeatInterval           = 120;
		// Application iOS options
		this.preventSuspend              = true;
		// Debug options
		this.debug                       = false;
		
		// UI members.
		this.motionActivity              = 'Activity';
`

## Expected Behavior
No freezing on splashscreen when app reload

## Actual Behavior

When i start the tracking and it running. I pass my app in background... i think, when i am stationary mode (the night for exemple), my application falls asleep and the morning i re open my background app to foreground.

One in two the app reload. Whereas i use the "preventSuspend" with the "heartbeatInterval" for lock the reload. 

## Steps to Reproduce

1. Start the tracking
2. Pass app in background mode
3. Go to sleep ^^
4. Pass app in foreground mode
5. Why often app reload ?

I have no valide step for reproduce 100%... i can't do it.

## Context
i have try the "preventSuspend" with the "heartbeatInterval".

## Debug logs

Nothing =s. Because i need disconnect my from my mac and i need long time (a night generaly) for reproduce =s

How i can debug app during the splash screen ?
Do you think, i have to create a native logger ?

**Comment by christocracy** [comment]
You’re probably using the cordova-webview or Ionic-webview plugin.

That plugin is buggy with apps which may be rebooted in the background.

Don’t use it.

**Comment by Raffaele-LIZE** [comment]
I don't remember if i have install this plugin manually, maybe it's was by default.

I will try to remove it, but I'm going to experience side effects ?

I will come back said you if it's good when i had tested.

Thx christocracy

**Comment by fripp0971** [comment]
Chris - I have the same issue more or less where I get the freeze when I reboot my phone after starting your plugin and going into the background. You mention not using ionic-webview or cordova-webview. I assume I am doing this since this doesn't work and I've tried Ionic 3 and 4(beta). What webview plugin are we supposed to use?

**Comment by christocracy** [comment]
@fripp0971 it's very easy to see the plugins you have installed.

```
$ cordova plugins
```

**Comment by fripp0971** [comment]
Yeah, i see it in my list, I thought it was just part of ionic. Am I supposed to have "some" form of webview installed?

**Comment by christocracy** [comment]
If you some some sort of `*-webview` plugin, uninstall it.  Do not use *any* kind of `webview` plugin.  They have bugs when an iOS app is booted in the background.

**Comment by fripp0971** [comment]
Great advice. You may have just saved me from the 25 hours I have been in debug hell. Thanks fellow Canuck!

**Comment by fripp0971** [comment]
worked! wish i had talked to you 2 days ago! Anyway, amazing, thanks!
