### ISSUE TITLE
Timestamp based on device clock and other on GPS clock

### ISSUE THREAD

**Issue by coveateam** [transistorsoft/cordova-background-geolocation-lt#724]
## Your Environment
* Plugin version: 2.8.5
* Platform: iOS and Android
* OS version: 7.1.1 and other
* Device manufacturer / model: Samsung Galaxy J5 (2016)
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.2.3 and iOS 4.5.4
* Plugin config : 
------
        <variable name="GOOGLE_API_VERSION" value="11.6.0" />
        <variable name="APPCOMPAT_VERSION" value="27.0.0" />
------
this.bgGeo.configure({
          debug: false,
          desiredAccuracy: this.bgGeo.DESIRED_ACCURACY_HIGH,
          distanceFilter: 0, 
          stopDetectionDelay : 3, 
          locationUpdateInterval : 1000, 
          stopAfterElapsedMinutes : 0,
          desiredOdometerAccuracy : 100,
          fastestLocationUpdateInterval : 1000, 
          stationaryRadius : 2,
          foregroundService: true,
          notificationTitle : "CoachAAC",
          notificationText : "Trajet en cours",
          activityRecognitionInterval : 0, 
          disableStopDetection : false, 
          heartbeatInterval : 2,
          preventSuspend : true,
          disableElasticity : true,
          allowIdenticalLocations : true, 
          locationAuthorizationRequest : "Always",
          locationTimeout : 10, 
          notificationLargeIcon : 'drawable/notification_large_icon', 
          notificationSmallIcon : 'drawable/notification_large_icon' 
        }

## Expected Behavior
I'm using the watchPosition() method to retrieve positions every seconds. 

## Actual Behavior
Most of the measures seem to be based on the gps timestamp but some of them are bases on my device clock (they are maybe generated from the accelerometer or something like that).
My device clock is ahead by almost one minute and it causes some issues and i'm forced to reject most of the gps measures because they have an inferior timestamp.

## Context
I would like to ignore the measures which are based on the device clock. For my case, the clock is ahead of the 'gps' one but for some users it could be the opposite, so I guess I can't just do a basic condition that looks for specifics timestamps. I would like to see if I can ignore the measures with the 'device' timestamp (Accelerometer measures I guess?) with configuration options or something else.

## Debug logs
- Measure with device based timestamp : 
We got a BG Update Location{"is_moving":true,"uuid":"37e8e66a-3cc0-441c-ae8f-0acfab4204ae","timestamp":"2018-07-09T11:39:27.693Z","odometer":1901,"coords":{"latitude":47.9944255,"longitude":0.1910056,"accuracy":10,"speed":0,"heading":-1,"altitude":118.9},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":0.59},"extras":{}}
BG timestamp :  1531136367693
Device timestamp :  1531136367904
timeFromLastSave 24811

- Next measure is based on "gps" timestamp
We got a BG Update Location{"is_moving":true,"uuid":"7d269d6a-1fd1-40af-bb44-2104cf51619b","timestamp":"2018-07-09T11:38:24.000Z","odometer":1901.1,"coords":{"latitude":47.9944263,"longitude":0.1910047,"accuracy":10,"speed":0,"heading":-1,"altitude":118.9},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":0.59},"extras":{}}
BG timestamp :  1531136304000
Device timestamp :  1531136369387
timeFromLastSave -38882   <-- duration (in ms) from the last position

**Comment by christocracy** [comment]
Sorry, missed this while on vacation.  Is this still an issue?

**Comment by coveateam** [comment]
Hi, no problem. 
Yes, we found a solution which consist to set the current device date to all measures (not a perfect solution). 
But it seems that measures which are from wi-fi or data (or accelerometer ?) are based on the device time and measures from the GPS cheap are based on the GPS clock. It's not a problem in most of cases, but for devices which haven't set their clock automaticaly, it can be an issue (for example we are re-calculating the speed by comparing each measure to the previous one, so if we have measures based on two different clock, it cause some big problems). 


I make suppositions about the reason for these different timestamp bases and it's maybe not about wifi, data or GPS based measures.

**Comment by christocracy** [comment]
When you're indoors, location will likely come from Wifi.  When you're outdoors, location likely comes from GPS.

> we are re-calculating the speed by comparing each measure to the previous one

Why not just use `speed` provided by the location (obviously `speed` is only available when location came from GPS).

I wouldn't attempt calculate speed with a location that came from Wifi since the accuracy will be typically 40-60 meters so the measurement error will be useless anyway.

**Comment by coveateam** [comment]
So do you think that the different bases of timestamp are linked to wifi, data or GPS measures ?
We calculates the speed this way because we realized that sometimes, a lot of measures are retrieved with a speed of 0. When we are re-calculating with our method we find that it's not the case and when we look the trip on a map, it clearly show that the speed wasn't at 0 and that the vehicle was driving on a road. So we decided to make it like that (we take measures with accuracy <= 30 m). 
I understand that when we are outside, we are getting measures from GPS, but for some device which are not in time, only one measure retrieved from wifi or data can be a real problem (I still make the supposition that it's the cause of the different timestamp).
Do you know if we have another way, other than the speed of 0, to distinguish GPS measures from the other ones?

**Comment by christocracy** [comment]
>that the different bases of timestamp are linked to wifi, data or GPS measures 

Probably.  Locations come from 3 possible sources:  GPS, Wifi, Cell-tower.

>because we realized that sometimes, a lot of measures are retrieved with a speed of 0.

What is the corresponding `accuracy`?  If you have a location having `accuracy > 10`, the location is too inaccurate to use for `speed` calculation.

>Do you know if we have another way, other than the speed of 0, to distinguish GPS measures from the other ones?

GPS locations will have accuracy typically `<= 10 meters`.

**Comment by coveateam** [comment]
Thanks for your answer. I just have two last questions.
- Have GPS locations a speed at 0 when they have an accuracy > 10m or are they retrieved with a speed (even if it not usable due to the bad accuracy) ?
- How the source of location is choosen : GPS in priority and wifi / cell in last ressort if GPS can't give any location or the source with best accuracy first (even if GPS is most of the time the best one) ?

Thanks for your time.

**Comment by christocracy** [comment]
>Have GPS locations a speed at 0 when they have an accuracy > 10m or are they retrieved with a speed (even if it not usable due to the bad accuracy) ?

I don't know.  The plugin provides the `speed` directly from the native API.  If the native API says speed is unavailable, the value is `-1`.

>How the source of location is choosen

This is not known.  The native API encapsulates all 3 providers and simply provides the best available location.
