### ISSUE TITLE
Odometer doesn't calculate distance

### ISSUE THREAD

**Issue by mf222** [transistorsoft/cordova-background-geolocation-lt#726]
Hi, I'm trying to implement the plugin, overall it works amazing! but I can't get the odometer distance calculation. I'm expecting that the odometer to give the distance in meters, but it value never changes from 0. I caught the events without problem, the pacing changes, the speed, the points, everything but the odometer distance.

## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Xiao Mi A1
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
```
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
* Plugin config

```
this.bgGeo.ready(
      {
        desiredAccuracy: 0,
        distanceFilter:  10,
        stopTimeout: 1,
        foregroundService: true,
        stopOnTerminate: false,
        heartbeatInterval: 60,
      },
        (state) => {
        if (!state.enabled) {
          this.bgGeo.start(this.bgStatus = `- Start success: ${state}`);
        }
      });
```

## Expected Behavior

```
private onLocation(location: any) {
    this.zone.run (() => {
      console.log(location.odometer);
    });
  }
```
To have output different than 0.

I've also tried with
```
private onLocation(location: any) {
    this.bgGeo.getOdometer(distance => console.log(distance));
  }
```
## Actual Behavior
Never changes from 0. Although it captures other information like coords and change in pacing like changes from `still` to `on_foot` to `on_vehicle`.

## Steps to Reproduce

1. Same config from SampleApp: 
In the constructor of the view
```
 this.bgGeo.on(
      'location',
      this.onLocation.bind(this),
      this.onLocationFailure.bind(this),
    );

    this.bgGeo.on(
      'motionchange',
      this.onMotionChange.bind(this),
    );

    this.bgGeo.on(
      'providerchange',
      this.onProviderChange.bind(this),
    );

    this.bgGeo.ready(
      {
        desiredAccuracy: 0,
        distanceFilter:  10,
        stopTimeout: 1,
        foregroundService: true,
        stopOnTerminate: false,
        heartbeatInterval: 60,
      },
      (state) => {
        this.zone.run(() => {
          this.enabled = state.enabled;
        });
    });
```
And the method I put in the expected behaviour.

## Context

Count meters that I walked.

## Debug logs

Not error shown.

**Comment by christocracy** [comment]
Sorry, missed this while on vacation.  Is this still an issue?

**Comment by mf222** [comment]
Hi, it was an issue, but lately I updated the plugin to the `cordova-background-geolocation` version (without the `lt`). It doesn't seem to be an issue there.

**Comment by groupmwt** [comment]
I, am getting the value of getOdometer = 0 . Please help me.
