### ISSUE TITLE
Adding paid plugin failed to fetch plugin via registry error

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/cordova-background-geolocation-lt#727]
## Expected Behavior
-> cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git
Plugin be added

## Actual Behavior
error:

`(node:37800) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/transistorsoft/cordova-background-geolocation.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/transistorsoft/cordova-background-geolocation.git
npm ERR! 
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/transistorsoft/cordova-background-geolocation.git/'
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/insightworkshop/.npm/_logs/2018-07-11T07_32_40_778Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:37800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

## Steps to Reproduce
1. Add plugin

**Comment by christocracy** [comment]
Customer should post issues to private repo for priority support.

https://help.github.com/articles/caching-your-github-password-in-git/
