### ISSUE TITLE
License Validation Failure

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/cordova-background-geolocation-lt#729]
## Your Environment
* Plugin version: cordova-background-geolocation-lt 2.8.4 "BackgroundGeolocation" 
* Platform: Android
* OS version: any 
* Device manufacturer / model: any
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):  android 6.3.0

## Expected Behavior
Did everything as mentioned in the plugin doc to add license key, but still geting license validation failure 

## Actual Behavior
have added license key, so there must not be any license issue

## Steps to Reproduce
As mentioned in pluin's setup doc

## Debug logs
07-17 09:17:30.442 562-846/com.docandtrack.app I/TSLocationManager: ╔═════════════════════════════════════════════
                                                                    ║ License Validation Failure
                                                                    ╠═════════════════════════════════════════════
                                                                    ╟─ BackgroundGeolocation is running in evaluation mode.
07-17 09:17:30.469 562-846/com.docandtrack.app I/TSLocationManager: [c.t.l.util.Sensors print] 
                                                                    ╔═════════════════════════════════════════════
                                                                    ║ DEVICE SENSORS
                                                                    ╠═════════════════════════════════════════════
                                                                    ╟─ ✅  ACCELEROMETER: {Sensor name="K6DS3TR Accelerometer", vendor="STM", version=1, type=1, maxRange=39.2266, resolution=0.0011971008, power=0.13, minDelay=10000}
                                                                    ╟─ ✅  GYROSCOPE: {Sensor name="K6DS3TR Gyroscope", vendor="STM", version=1, type=4, maxRange=17.453293, resolution=6.1086525E-4, power=6.1, minDelay=10000}
                                                                    ╟─ ✅  MAGNETOMETER: {Sensor name="AK09916C Magnetometer", vendor="Asahi Kasei Microdevices", version=1, type=2, maxRange=2000.0, resolution=0.06, power=6.0, minDelay=10000}
                                                                    ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="K6DS3TR Significant Motion Detector", vendor="STM", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.75, minDelay=0}
                                                                    ╚═════════════════════════════════════════════
07-17 09:17:30.501 562-846/com.docandtrack.app I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                    ╔═════════════════════════════════════════════
                                                                    ║ BackgroundGeolocation adapter
                                                                    ╠═════════════════════════════════════════════
07-17 09:17:30.554 562-846/com.docandtrack.app D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO dbh] 
                                                                      ✅  Opened database
07-17 09:17:30.570 562-846/com.docandtrack.app D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO prune] 
                                                                      ℹ️  PRUNE -30 days
07-17 09:17:30.629 562-846/com.docandtrack.app D/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO dbh] 
                                                                      ✅  Opened database
07-17 09:17:30.692 562-846/com.docandtrack.app I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                      🔵  Connecting to GooglePlayServices...
07-17 09:17:30.709 562-846/com.docandtrack.app D/TSLocationManager: $ addLocationListener()
07-17 09:17:30.714 562-846/com.docandtrack.app D/TSLocationManager: $ configure()
07-17 09:17:30.719 562-846/com.docandtrack.app D/TSLocationManager: $ getState()
07-17 09:17:30.742 562-1526/com.docandtrack.app I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                                     ╔═════════════════════════════════════════════
                                                                     ║ BackgroundGeolocation Settings
                                                                     ╠═════════════════════════════════════════════
                                                                     {
                                                                       "isMoving": false,
                                                                       "enabled": true,
                                                                       "odometer": 0,
                                                                       "schedulerEnabled": false,
                                                                       "trackingMode": "location",
                                                                       "distanceFilter": 200,
                                                                       "desiredAccuracy": 0,
                                                                       "desiredOdometerAccuracy": 100,
                                                                       "locationUpdateInterval": 1000,
                                                                       "fastestLocationUpdateInterval": 10000,
                                                                       "locationTimeout": 60,
                                                                       "deferTime": 0,
                                                                       "disableElasticity": true,
                                                                       "activityRecognitionInterval": 10000,
                                                                       "minimumActivityRecognitionConfidence": 75,
                                                                       "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                       "disableStopDetection": false,
                                                                       "stationaryRadius": 25,
                                                                       "stopTimeout": 5,
                                                                       "stopOnStationary": false,
                                                                       "url": "http:\/\/api.docandtrack.com\/loads\/162\/tracking.json",
                                                                       "method": "POST",
                                                                       "autoSync": true,
                                                                       "autoSyncThreshold": 0,
                                                                       "batchSync": true,
                                                                       "maxBatchSize": -1,
                                                                       "params": {},
                                                                       "headers": {
                                                                         "Authorization": "Token auth key here"
                                                                       },
                                                                       "extras": {},
                                                                       "httpRootProperty": "location",
                                                                       "locationTemplate": "",
                                                                       "geofenceTemplate": "",
                                                                       "persist": true,
                                                                       "maxDaysToPersist": 30,
                                                                       "maxRecordsToPersist": -1,
                                                                       "locationsOrderDirection": "ASC",
                                                                       "httpTimeout": 60000,
                                                                       "geofenceProximityRadius": 1000,
                                                                       "geofenceInitialTriggerEntry": true,
                                                                       "stopOnTerminate": false,
                                                                       "startOnBoot": false,
                                                                       "heartbeatInterval": -1,
                                                                       "foregroundService": false,
                                                                       "notificationPriority": 0,
                                                                       "notificationTitle": "",
                                                                       "notificationText": "Location Service activated",
                                                                       "notificationColor": "",
                                                                       "notificationIcon": "",
                                                                       "notificationSmallIcon": "",
                                                                       "notificationLargeIcon": "",
                                                                       "forceReloadOnLocationChange": false,
                                                                       "forceReloadOnMotionChange": false,
                                                                       "forceReloadOnGeofence": false,
                                                                       "forceReloadOnBoot": false,
                                                                       "forceReloadOnHeartbeat": false,
                                                                       "forceReloadOnSchedule": false,
                                                                       "stopAfterElapsedMinutes": 0,
                                                                       "schedule": [],
                                                                       "configureUrl": "",
                                                                       "configureInterval": -1,
                                                                       "debug": false,
                                                                       "logLevel": 5,
                                                                       "logMaxDays": 3
                                                                     }╚═════════════════════════════════════════════

My config file 

<plugin name="cordova-background-geolocation-lt" spec="^2.8.4">
        <variable name="LICENSE" value="key here was set my cordova add plugin .... terminal command" />
        <variable name="BACKGROUND_MODE_LOCATION" value="&lt;string&gt;location&lt;/string&gt;" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>

my package.json file:

 "cordova-background-geolocation-lt": {
        "LICENSE": "auto update license here",
        "BACKGROUND_MODE_LOCATION": "<string>location</string>",
        "LOCATION_ALWAYS_USAGE_DESCRIPTION": "Background location-tracking is required",
        "LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION": "Background location-tracking is required",
        "MOTION_USAGE_DESCRIPTION": "Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving"
      }

And android manifest file content auto generated : 

`<manifest android:hardwareAccelerated="true" android:versionCode="20102" android:versionName="2.1.2" package="com.docandtrack.app" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="auto generated key was here" />
        <activity android:label="@string/app_name" android:name="com.docandtrack.docandtrackandroid.CordovaBridge" android:theme="@style/AppTheme" />
        <activity android:launchMode="singleTop" android:name="com.scanlibrary.ScanActivity" android:screenOrientation="portrait" android:theme="@style/AppTheme" android:windowSoftInputMode="adjustPan" />
    </application>
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="26" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
</manifest>`

This issue is really giving me pain. 

Initially I had another version of plugin as was not showing the license issue and i even updated it in playstore, but the problem with that version was when i called bgGEO.getcurrentLocation, it was always never fetching location and was location time out even when timeout provided 60 sec.

Now with this version of plugin, geting license validation issue but location ping working file.

Additionally, is there seperate repo of customers with license and order id? I emailed to your contact email but no reponse was given. In some thread, i see written that now there is no seperate private repo and this -lt repo works fine with license key and and in another i see written to check for issue in private repo. Can you clarify on this one. :)

**Comment by christocracy** [comment]
https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/License-Validation-Failure
