### ISSUE TITLE
Does not sync my every location

### ISSUE THREAD

**Issue by razam217** [transistorsoft/cordova-background-geolocation-lt#73]
Hi Chris, I want to sync my each change in location with the Background Geolocation Console app. But it do not sync all the location changes. For location changes I'm using Android Mock Location functionality by Fake Location App. But each location change has is_moving: false, because I'm not moving, but I only change the location suddenly.

**Comment by christocracy** [comment]
Android is_moving flag is toggled by an accelerometer based API.  Mocking
your location doesn't change make the device physically move.

On Thursday, February 11, 2016, Muhammad Mehdi Raza <
notifications@github.com> wrote:

> Hi Chris, I want to sync my each change in location with the Background
> Geolocation Console app. But it do not sync all the location changes. For
> location changes I'm using Android Mock Location functionality by Fake
> Location App. But each location change has is_moving: false, because I'm
> not moving, but I only change the location suddenly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/73>
> .
>


-- 
Snet form Gmail Mobile

**Comment by razam217** [comment]
Yep, right, Thanks... :)
