### ISSUE TITLE
Weird battery level

### ISSUE THREAD

**Issue by staskuban** [transistorsoft/cordova-background-geolocation-lt#731]
Hello,  have bug with a battery level on real iphone 7

## Your Environment
* Plugin version: latest from master branch
* Platform: iOS
* OS version: ios 11.4
* Device manufacturer / model: iphone 7
* Cordova version (`cordova -v`):     Cordova Platforms  : ios 4.5.4 Ionic Framework    : ionic-angular 3.9.2

* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin config
{
        debug: true,
        desiredAccuracy: 0,
        distanceFilter: 10,
        startOnBoot:true,
        url: 'https://example.com/update',
        httpRootProperty: '.',
        locationTemplate:'{"geo": {"lat": "<%= latitude %>", "long": "<%= longitude %>", "gtype": 0},"device": {"scr": 1, "bat": "<%=battery.level%>", "psav": 0}}',
        params: {
some_params {...some_params}
        }
        ,
        autoSync: true
      }

## Expected Behavior

Battery level in range of 0-100

## Actual Behavior
Battery level is -1

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

Also i want ask: can i use (without declare url and data in plugin config) custom sync handler for posting coordinates to my server?

**Comment by christocracy** [comment]
It's useless to specify version "latest from master branch".  This is completely meaningless the next time I post a commit.

You'll see battery-level `-1` when running on a simulator.  Simulators don't have batteries.
