### ISSUE TITLE
Using timestamp in the locationTemplate throws error

### ISSUE THREAD

**Issue by manish2535** [transistorsoft/cordova-background-geolocation-lt#732]
## Your Environment
* Plugin version: 2.11.0
* Platform: iOS or Android
* OS version:  iPhone 8 Plus simulator
* Device manufacturer / model:
* Cordova version (`cordova -v`):  7.1.0
* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin config: Default

## Expected Behavior
No error and continues to send http request

## Actual Behavior
When using certain fields like '{ "Timestamp":<%= timestamp %>, "Activity":<%= activity.type %> }'
I get an error saying "you have an error in your locationTemplate. I am following the documentation in HTTP features guide where it clearly says timestamp and activity.type are valid inputs.

## Steps to Reproduce

1. Include this '{ "Timestamp":<%= timestamp %>, "Activity":<%= activity.type %> }' in your locationTemplate property of .ready() and try to make a request.
2.
3.
4.

**Comment by Steffaan** [comment]
Both `timestamp` and `activity.type` are strings, which makes your JSON invalid.

See [documentation ](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/http.md#quoting-string-values)

You are not quoting the values. Change your template to this:
`'{ "Timestamp":"<%= timestamp %>", "Activity":"<%= activity.type %>" }'`

**Comment by christocracy** [comment]
@manish2535 you should be seeing error messages in the logs related to invalid JSON.

**Comment by manish2535** [comment]
Thanks guys. My bad, I should have read that page more carefully.
