### ISSUE TITLE
smoothing gps data

### ISSUE THREAD

**Issue by jamesdixon** [transistorsoft/cordova-background-geolocation-lt#733]
This isn't anything specific about the library itself, but I was wondering if you have any recommendations on smoothing data to remove noise/outliers? Techniques or libraries that you use often? I've found a couple of articles but given this is your forte, I figured I'd ask 👍 

Thanks!

**Comment by christocracy** [comment]
outliers should have unusually high accuracy compared to its sibling records (before / after).

**Comment by jamesdixon** [comment]
@christocracy thanks. is there a canonical example for settings that you find produces the best results?

**Comment by christocracy** [comment]
There’s not many options that affect geolocation.  Most of the plugins options are related to HTTP config.

The most important are `desiredAccuracy` and `distanceFilter`.

If you want to enable GPS, your only option is `DESIRED_ACCURACY_HIGH`
