### ISSUE TITLE
Ping location every x minutes and send it to server

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/cordova-background-geolocation-lt#734]
## Your Environment
* Plugin version: 2.11.0
* Platform: iOS and  Android
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios: 4.5.4 and android: 6.3.0

## Expected Behavior
Location should be fetched every x minutes

## Actual Behavior
location is not geting fetched every x minutes

## Context
I saw that there is Android Option of locationUpdateInterval when distanceFilter == 0, does this apply to ios as well. How can i fetch the location every 15 minutes irrespective of platform, i.e in both ios and android.

**Comment by christocracy** [comment]
- iOS is distance-based only (`distanceFilter`)
- To receive an event about every 15 min, implement [cordova-plugin-background-fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch).  This plugin is already installed for you as a dependency of background-geolocation.  It's waiting for you to use right now at `window.BackgroundFetch`.

**Comment by christocracy** [comment]
You are free to do whatever you want in the BackgroundFetch event-handler, including `BackgroundGeolocation#getCurrentPosition`.
