### ISSUE TITLE
Background for IOS and Android when app closed 

### ISSUE THREAD

**Issue by blgsyrmhnds** [transistorsoft/cordova-background-geolocation-lt#735]
Hi
I try to many background plugin but I get failed
Is that plugin support both android and IOS when app closed?If yes can I remove background tracking enable text and Icon in anyway such as disabled notifacation?I want to track user coordinates every x second

https://stackoverflow.com/questions/51044602/how-can-i-remove-the-notification-from-the-plugin-cordova-plugin-mauron85-backg#comment89816183_51044602

thanks

**Comment by Steffaan** [comment]
Your posting in the wrong repo, head over to https://github.com/mauron85/cordova-plugin-background-geolocation/issues and post your issue there.

You can't remove the notification in Android if you want to use the background service, the OS doesn't allow you to.

**Comment by christocracy** [comment]
@Steffaan what makes you think he's using the Mauron85 fork?

**Comment by blgsyrmhnds** [comment]
I am not wrong epo @Steffaan 
For detail I give stackoverflow question

so If I use cordova-background-geolocation-lt
 If user close app it still send coordinates to my server but I can not remove background enabled information text on notification.Is this true?If yes
I can see some app such as swarn which continue track even if you close it but without notification
how they do that?Have you any suggestions?Thanks

**Comment by christocracy** [comment]
On Android 8+, the notification is **required** by the operating system.  It **cannot** be removed.

For < Android 8, foregroundService: false.

**Comment by christocracy** [comment]
This plugin is designed for aggressive tracking of location for “fleet-tracking” use-cases (eg taxi app, delivery service app).

If you’re making a social-type app, this is not the plugin for you.
