### ISSUE TITLE
Background for IOS and Android when app closed

### ISSUE THREAD

**Issue by blgsyrmhnds** [transistorsoft/cordova-background-geolocation-lt#736]
Hi
I try to many background plugin but I get failed
Is that plugin support both android and IOS when app closed?If yes can I remove background tracking enable text and Icon in anyway such as disabled notifacation?I want to track user coordinates every x second

**Comment by christocracy** [comment]
>Is that plugin support both android and IOS when app closed

Yes.  `stopOnTerminate: false`

>can I remove background tracking enable text and Icon in anyway such as disabled notifacation?

On Android 8+, no.  For < Android 8, `foregroundService: false`.

>I want to track user coordinates every x second

See docs for `#locationUpdateInterval`.  This is only possible on Android.  iOS is strictly distance-based (`#distanceFilter`)
