### ISSUE TITLE
Plugin doesn't wake up after stopping itself

### ISSUE THREAD

**Issue by Osmanakdemir** [transistorsoft/cordova-background-geolocation-lt#738]
* Plugin version: 2.10.1
* Platform: both iOS and Android
* OS version: Android => 6.4.0 iOS => 4.5.4
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 6.4.0
  browser 5.0.3
Available platforms: 
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
* Plugin config
                       fastestLocationUpdateInterval: 30000, //180000,
                        stopAfterElapsedMinutes: 120,
                        minimumActivityRecognitionConfidence: 75,
                        stopDetectionDelay: 0,
                        schedule: null,
                        desiredAccuracy: 0,
                        disableElasticity: false,
                        distanceFilter: 5,
                        stationaryRadius: 1,
                        //stopOnStationary: true,
                        // Activity Recognition config
                        activityRecognitionInterval: 5000, //120000, //activity recognition in 1 minute
                        locationUpdateInterval: 30000, //180000, //update every 180 second...
                        //stopTimeout: 5,
                        batchSync: true,
                        maxBatchSize: 10,
                        //preventSuspend: true,
                        //foregroundService: true,
                        // Application config
                        debug: false,  // <-- Debug sounds & notifications.
                        stopOnTerminate: false,
                        startOnBoot: false,
                        //deferTime: 300000, //5 minutes
                        url:  'https://xxxxxx/tracker/sendlocation/',
                        method: 'PUT',
                        locationAuthorizationRequest: "Always",
                        geofenceInitialTriggerEntry: false,
                        locationAuthorizationAlert: {
                        titleWhenNotEnabled: apex.lang.getMessage("GEOLOCATION_TITLEWHENNOTENABLED"), //"Location services not enabled",
                        titleWhenOff: apex.lang.getMessage("GEOLOCATION_TITLEWHENOFF"), //"Location services are off",
                        instructions: apex.lang.getMessage("GEOLOCATION_INSTRUCTIONS"), //"To use this app, you must enable 'Always' in the location service settings.",
                        cancelButton: apex.lang.getMessage("GEOLOCATION_CANCEL"), //"Cancel",
                        settingsButton: apex.lang.getMessage("GEOLOCATION_SETTINGS")//"Settings"
## Expected Behavior
Plugin should continue to track the location of the user after it stops it self. We have this setting in the config as //stopTimeout: 5 but we are not using it right now. I think the default stopTimeOut value is 10 minutes because it stops the service after 10 minutes and I got this with hearing the sounds that comes from the device while the debug mode is on !
## Actual Behavior
Plugin stops itself after 10 minutes and it DOES NOT wake up when user starts to move with the device !
## Context
We are try to log the drivers locations via using your plugin.

## Debug logs
I'll share if it is neccessary...

**Comment by christocracy** [comment]
Do you know what this does?

```
stopAfterElapsedMinutes: 120,
```
