### ISSUE TITLE
iOS and Android Geofence notification issues

### ISSUE THREAD

**Issue by flfruitios** [transistorsoft/cordova-background-geolocation-lt#739]
## Your Environment
* Plugin version: 2.11.0
* Platform: iOS and Android
* OS version: iOS 11.4 and Android 9.0 
* Device manufacturer / model: Apple 6s plus, Essential PH-1
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 6.3.0
  ios 4.5.4
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0 

* Plugin config
bgGeo.ready(
          {
            reset: true,
            desiredAccuracy: 0,
            enableHeadless:true,
            distanceFilter: 50,
            stopOnTerminate: false,
            startOnBoot: true,
            foregroundService: false
          }
## Expected Behavior

ionic1 application
1. When I enter into geofence I need to get notification popup. When I leave the geofence and come back again into geofence I need to get notification popup. It should work both in iOS and Android.
2. When I closed the application, still I need to get the notification whenever I entered the geofence.
3. **if (!state.enabled)** it should be true, if I have allowed the location service 
## Actual Behavior

1.  iOS application is giving only one time notification for geofence. When I entered the geofence again, I am not getting any notifications. 
2. I am not getting the notification When I closed the application. It is not working in iOS and Android.
                bgGeo.on("geofences", function(geofences) {
                  console.log(geofences);
                  var notification = geofenceNotifications[geofences.identifier];
                  $ionicPopup.alert({
                    title: notification.title,
                    template: notification.body
                  });
3. It is sometimes being true and sometimes being false. Please let me know in detail of what it is meant. 
## Steps to Reproduce

1. Tried to change the configuration with multiple ways. Still it the same
2. Changed distanceFilter value
3. Changed radius from 100 to 200
4. Reopened the iOS application multiple times. But it is a one time process.

## Context

I am trying make an application which tracks our location and give notification if we entered the geofence location. If we entered the geofence multiple times, I should get multiple notifications. I want test at the edge of the fence, going in and out, and check the notification frequency.

**Comment by christocracy** [comment]
Customers should use the [private repo](https://github.com/transistorsoft/cordova-background-geolocation), not the public repo.  The public repo has no guarantee of support.

**Comment by christocracy** [comment]
See Wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation/wiki/Debugging).  The plugin logs all its geofence events.

Also use `debug: true`.  The plugin emits sound FX when geofence events occur.

**Comment by christocracy** [comment]
And for Android, your Javascript code **will not run** when app is terminated.  Your entire Ionic app is terminated when user terminates an Android app.  You will have to write native Android code to show an notification using the plugin's [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation/wiki/Android-Headless-Mode) mechanism.

**Comment by kushal-ost** [comment]
Hi,
there is an issue that when I add a geofence then I am not getting any notification, Notification comes only when I open the app again .

One thing more,.. How to remove the debug sound ? I already made debug:false.

Please suggest
