### ISSUE TITLE
How to remove the sound on geofence activity

### ISSUE THREAD

**Issue by kushal-ost** [transistorsoft/cordova-background-geolocation-lt#740]
## Your Environment
Plugin version: 2.12.2
Platform: iOS or Android : Both
OS version: Latest
Device manufacturer / model: Any device of android / iOS
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): Andriud- 7.0.0
IONIC VERSION : IONIC v1

## Expected Behavior

If debug:false, then it should not emit sound on geofence activity.

## Actual Behavior

A small time sound is coming out on any activity releted to geofence.

## Steps to Reproduce

1.
2.
3.
4.

Please suggest how to remove the sound.

**Comment by christocracy** [comment]
When developing use `reset: true` with `#ready` or changes to config options will be ignored.  Read the docs for `#ready`.

**Comment by kushal-ost** [comment]
There is nothing written about sound in ready function.  I want to remove the beep sound which is coming after geofence activity.
Please suggest.

**Comment by christocracy** [comment]
Sounds are emitted with `debug: true`

If you change a config option (eg `debug` from `true` -> `false` without setting `reset: true`, the plugin is still running with `debug: true` and debug sound fx will continue to run.

Re-read docs for #ready

**Comment by kushal-ost** [comment]
Thanks Sir..
My this issue gets resolved... 

I need your help in one issue..
When I add a geofence then I don't get any notification of entering into geofence (If using licence key).
With same code , when I am not using licence key, I get notification of adding geofence.

Please suggest.
