### ISSUE TITLE
TSConfig updateDictionary Crash - iOS 11.4.1

### ISSUE THREAD

**Issue by AsteaDevelopment** [transistorsoft/cordova-background-geolocation-lt#744]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS
* OS version: 11.4.1
* Device manufacturer / model: iPhone 6s
* Cordova version (`cordova -v`):8.0.0
* Cordova platform version (`cordova platform ls`): 4.5.5
* Plugin config:
<pre>BackgroundGeolocation.setConfig(
        {
            allowIdenticalLocations: true,
            desiredAccuracy: 0,
            distanceFilter: (Ext.is.Android) ? 0 : 30,
            disableLocationAuthorizationAlert: true,
            pausesLocationUpdatesAutomatically: false,
            activityRecognitionInterval: geoLocationInterval,
            fastestLocationUpdateInterval: geoLocationInterval,
            locationUpdateInterval: geoLocationInterval
        }, function() {})</pre>

## Expected Behavior
When using the app with setConfig and plugin enabled, app should not crash.

## Actual Behavior
It looks like after calling setConfig, the app is crashing. The crash stack trace is below. I was going to investigate it myself, but it is within the TSLocationManager.framework.

## Steps to Reproduce
1. Setup 2.12.2 plugin and enable for iOS.
2. Add setConfig info like above, this is after the app is ready.

## Context
Just use the app, nothing fancy. This issue did not seem to occur before 2.12, we were using 2.11 at one point and never had this crash. Also, the crash only seems to happen with iPhone 6s. I couldn't reproduce the problem on iPhone X or iPhone 5 both running 11.4.1.

## Debug logs
<pre>Fatal Exception: NSInvalidArgumentException
-[NSNull objectForKey:]: unrecognized selector sent to instance 0x1b45cc878
0
CoreFoundation
__exceptionPreprocess
1
libobjc.A.dylib
objc_exception_throw
2
CoreFoundation
__methodDescriptionForSelector
3
CoreFoundation
___forwarding___
4
CoreFoundation
_CF_forwarding_prep_0
5
Astea Mobile
TSConfig.m - Line 531
-[TSConfig updateWithDictionary:]
6
Astea Mobile
CDVBackgroundGeolocation.m - Line 86
__38-[CDVBackgroundGeolocation setConfig:]_block_invoke
7
libdispatch.dylib
_dispatch_call_block_and_release
8
libdispatch.dylib
_dispatch_client_callout
9
libdispatch.dylib
_dispatch_queue_override_invoke$VARIANT$mp
10
libdispatch.dylib
_dispatch_root_queue_drain
11
libdispatch.dylib
_dispatch_worker_thread3
12
libsystem_pthread.dylib
_pthread_wqthread
13
libsystem_pthread.dylib
start_wqthread
</pre>

**Comment by christocracy** [comment]
I wonder if your `geoLocationInterval` is evaluating to something unexpected?
```
            activityRecognitionInterval: geoLocationInterval,
            fastestLocationUpdateInterval: geoLocationInterval,
            locationUpdateInterval: geoLocationInterval
```

**Comment by AsteaDevelopment** [comment]
@christocracy sorry for posting here, we have the premium version. As for geoLocationInterval, the value we are using is:

`var geoLocationInterval = 60000; // How often we should grab location updates in milliseconds.`

**Comment by christocracy** [comment]
Show me more of your code you're using with the plugin.

Where are you executing `#setConfig` relative to `#ready`?

**Comment by AsteaDevelopment** [comment]
@christocracy We are calling setConfig from another function that detects if we are using a native device or not, since we don't want to run this in the browser. Here is some more javascript of our .ready listener check. Also, this works on multiple other versions against multiple devices EXCEPT this device as far as we could tell thus far. (Examples - iPhone X 11.4.1 works fine, iPhone 6 Plus 10.3.3 works fine).

`document.addEventListener('deviceready', configureDefaultBackgroundGeolocation, false);`

<pre>
var configureDefaultBackgroundGeolocation = function() {
  try {
    Ext.ControllerManager.get('gpstracking_controller').useNativeGps = true;
  } catch (e) {}

  BackgroundGeolocation.ready(
    {
      notificationSmallIcon: 'drawable/driving',
      notificationText: 'Location is being shared with Dispatch.',
      notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
      desiredAccuracy: 0,
      distanceFilter: 30
    },
    function() {
      BackgroundGeolocation.on('location', gpsUpdateReceived);
      BackgroundGeolocation.on('geofence', gpsGeofenceTriggered);
      BackgroundGeolocation.stop(function() {}, function() {});
    },
    function() {}
  );
};
</pre>

**Comment by christocracy** [comment]
Your stack-trace shows a crash while executing **`#setConfig`** -- **not `#ready`**.

```
__38-[CDVBackgroundGeolocation setConfig:]_block_invoke

```

Show me where you're executing `#setConfig`.

**Comment by christocracy** [comment]
There's no possible way this affects *only* an iPhone 6s.  You're sending an unexpected `null` value to one of the config-options in `#setConfig`.

**Comment by AsteaDevelopment** [comment]
You are correct, we were able to reproduce the issue on an iPhone 5s on iOS 12. The problem is we are calling setConfig from the native side and on the client side (one of our customers was passing specific config and we didn't get to update our native code to support it). For now, what you are saying sounds correct to me. I will update our code and see what happens. When you say show you what I am executing, do you mean the stacktrace for setConfig or just the process of how we are using it? Sorry for any confusion.

**Comment by christocracy** [comment]
>we are calling setConfig from the native side and on the client side

What do you mean "on the native side"?

I want to see *everywhere* you are using the `#setConfig` method.

**Comment by AsteaDevelopment** [comment]
Sorry, cordova javascript. Here is the other places we are using setConfig:

<pre>
asteaExports.configure = function(success, error, args) {
  var enabled = args[0];
  var frequency = args[1];
  var accuracy = args[2];
  var radius = args[3]; //I'm going to ignore this for now until I understand the quirks of the plugin
  var successWrapper = null;
  var errorWrapper = null;

  if (typeof success === 'string') {
    successWrapper = function() {
      cordova.callbackFromNative(success, true, cordova.callbackStatus.OK, ['true'], false);
    };
    errorWrapper = function() {
      cordova.callbackFromNative(success, false, cordova.callbackStatus.ERROR, [], false);
    };
  } else if (typeof success === 'function') {
    successWrapper = function() {
      success('true');
    };
  }

  BackgroundGeolocation.setConfig(
    {
      desiredAccuracy: accuracy || 0,
      distanceFilter: device.platform === 'iOS' ? radius : 0,
      locationUpdateInterval: frequency,
      fastestLocationUpdateInterval: frequency,
      notificationSmallIcon: 'drawable/driving',
      notificationText: 'Location is being shared with Dispatch.'
    },
    successWrapper,
    errorWrapper
  );
};

asteaExports.enableDebug = function(success, error, enabled) {
  BackgroundGeolocation.setConfig(
    {
      debug: enabled
    },
    success,
    error
  );
};

asteaExports.configureExt = function(options, success, error) {
  options = options || {};
  var config = extend(
    {
      foregroundService: true,
      stopOnTerminate: false
    },
    options
  );
  if (config.accuracy) {
    switch (config.accuracy) {
      case 0:
        //0 is off. if this is the case GPS shouldn't ever be turned on anyway
        config.desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_VERY_LOW;
        break;
      case 1:
        config.desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_HIGH;
        break;
      case 2:
        config.desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM;
        break;
      case 3:
        config.desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_LOW;
        break;
      case 4:
      case 5:
        config.desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_VERY_LOW;
        break;
      default:
        config.desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_HIGH;
        break;
    }
  }

  if (config.postUrl) {
    config.url = config.postUrl;
  }

  if (config.params) {
    config.params = config.params;
  }

  config.distanceFilter = config.distanceFilter || 50;
  BackgroundGeolocation.setConfig(config, success, error);
};
</pre>

**Comment by christocracy** [comment]
When you reproduce your issue, you will see an unexpected `null` value in one of your config options:

```diff
+console.log("************ setConfig: ", JSON.stringify(config, null, 2));
BackgroundGeolocation.setConfig(config, success, error);
```

**Comment by christocracy** [comment]
Check  your config.  Without a doubt, you're sending an unexpected `null` to one of the plugin's config options.

**Comment by AsteaDevelopment** [comment]
Yeah I definitely agree, I will take a look. Thank you for the help!

**Comment by christocracy** [comment]
The plugin could certainly handle this better (eg apply the default value) but then what...you'd place the plugin into a state you're not aware of making it more difficult to discover that you're providing the plugin an unexpected config option.

**Comment by christocracy** [comment]
and what is this?
```javascript
if (config.params) {
    config.params = config.params;
  }
```

put another way:
```javascript
var foo = true;
if (foo)( {
  foo = foo;
}
```
