### ISSUE TITLE
N

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#746]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
??

**Comment by pyeonjaesik** [comment]
sorry I mistake
