### ISSUE TITLE
Distance filter and locationUpdateInterval

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#748]
I want to detect user's location whenever user moves more than 30 meter while detecting user's location every 10 minutes in android and ios. But , if I intend to write code detecting location every 10minutes, I should set distancefilter 0. How to detect  location whenever user moves more than 30m and every 10 min?

**Comment by christocracy** [comment]
You don't save any energy by configuring `locationUpdateInterval` for every 10 min.  Location-services radios will be on constantly, regardless of every 10 min vs every second.

iOS is **strictly** distance-based.  iOS does not do *time-based* geolocation (`locationUpdateInterval` is an Android-only option).  You cannot ask to receive a location "every 10 minutes" on iOS.

If you want infrequent locations (minimum every 15 minutes), use [`cordova-background-fetch`](https://github.com/transistorsoft/cordova-plugin-background-fetch), which is already included as a dependency of `background-geolocation` and is available to you now at `window.BackgroundFetch`.  You're free to do whatever you wish in the `background-fetch` callback, including `BackgroundGeolocation#getCurrentPosition`.

**Comment by pyeonjaesik** [comment]
I should receive 'when' and 'where'. For example when Peter who is a user of my service is in the central park at 3 PM, my server receive location(eg. 30,144) and updated time(eg .2018.8.30.3pm). 
But if my device only detect distance-based location and users don't move, my device cannot detect any information. So, although Peter is still in the central park at 5PM, my server think peter Is still in the central park at 3PM. As a matter of fact the goal which I intend is not detecting location every 15 minutes, but detecting location even though Peter dose not move for time update.
Would you give me advice? please.

---cordova-background-fetch. 
I don't want to use that plugin because my app is awaken every 15 minutes. I think this may be annoying to users...

**Comment by christocracy** [comment]
This plugin was initially designed for aggressively tracking device locations for a disaster-response app where it was required to track devices where life depended on it.

![](https://dl.dropboxusercontent.com/s/ifqyamb0788czun/Screenshot%202018-08-13%2010.05.10.png?dl=1)

The plugin *knows* when the device is *moving* vs *stationary*.  See the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

>I don't want to use that plugin because my app is awaken every 15 minutes. I think this may be annoying to users...

Users are not aware of a background-fetch event.  This is the best option for battery-friendly, periodic location-updates.

**Comment by pyeonjaesik** [comment]
Ok thank you!

2018년 8월 13일 (월) 오후 11:08, Chris Scott <notifications@github.com>님이 작성:
