### ISSUE TITLE
Android Persistent Notification Icon is a grey square

### ISSUE THREAD

**Issue by mdanics** [transistorsoft/cordova-background-geolocation-lt#750]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: 8.0.0
* Cordova version: 8.0.0
* Cordova platform version: 7.1.1

## Expected Behavior
App Icon or Icon located in /drawables should be present. (works in with Push notifications)

## Actual Behavior
A grey square is the icon.

**Comment by christocracy** [comment]
Because you're not using an icon with transparency.  Certain version of Android automatically grey-scale / white-scale your app icon.

Eg:  here's my SampleApp icon:
![](https://dl.dropboxusercontent.com/s/rizkwcqumkv9c2n/Screenshot%202018-08-15%2012.00.38.png?dl=1)

**Comment by mdanics** [comment]
Is it possible to provide a custom icon to the plugin, similar to how phonegap push handles it?

**Comment by christocracy** [comment]
It's very helpful to *at least* read all the available configuration options.   See [[Application] Android Options ](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#application-android-options)

You will find `notificationSmallIcon` and `notifiationLargeIcon` interesting.

**Comment by mdanics** [comment]
Apologies. I read it, but skimmed over that option and thought it was to enable a small icon vs large icon.

**Comment by mdanics** [comment]
Thank you for your time.
