### ISSUE TITLE
Listening for  "BackgroundGeolocation.on('geofence'" without transmission?

### ISSUE THREAD

**Issue by mnutsch** [transistorsoft/cordova-background-geolocation-lt#752]
In my code I want to use "BackgroundGeolocation.on('geofence'," to kick off a recurring "BackgroundGeolocation.sync(function(locations)" inside of "BackgroundGeolocation.watchPosition(function(location)". 

However, "BackgroundGeolocation.on('geofence'," triggers a transmission of data in addition to being an event listener. This causes a problem, because multiple transmissions are rapidly sent when the device is turned on inside of overlapping geofences.

**Is there a way to use "BackgroundGeolocation.on('geofence'" as an event listener to trigger other code, but not have it transmit the location through HTTP?**

## Your Environment
* Plugin version: GOOGLE_API_VERSION 11.8.0; APPCOMPAT_VERSION 27.0.0
* Platform: iOS (also Android)
* OS version: iOS 11.4.1
* Device manufacturer / model: Apple iPad MP2D2LL/A
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios 4.5.5
* Plugin config

## Expected Behavior
The API listening for HTTP posts should only receive transmissions from BackgroundGeolocation.watchPosition(function(location):

req.body == {"location":{"coords":{"speed":0,"longitude":-96.86748395682952,"floor":null,"latitude":32.837440785982494,"accuracy":5,"altitude_accuracy":4,"altitude":135.1,"heading":-1},"extras":{},"is_moving":false,"event":"motionchange","odometer":6.7,"uuid":"0B513E49-65BC-4750-AAB9-61F53CCB177E","activity":{"type":"still","confidence":100},"battery":{"level":1,"is_charging":true},"timestamp":"2018-08-16T17:47:02.000Z"}}

## Actual Behavior
The API listening for HTTP posts receives information during geofence entry in addition to the intended transmissions:

req.body == {"location":{"coords":{"speed":-1,"longitude":-96.86753134497837,"floor":null,"latitude":32.83728375796341,"accuracy":65,"altitude_accuracy":10,"altitude":129.2,"heading":-1},"extras":{},"is_moving":false,"event":"motionchange","odometer":0,"uuid":"0490BA9D-CB23-46E6-929C-389946CEE279","activity":{"type":"unknown","confidence":100},"battery":{"level":1,"is_charging":true},"timestamp":"2018-08-16T17:57:53.913Z"}}

req.body == {"location":{"coords":{"speed":0,"longitude":-96.86737348334572,"floor":null,"latitude":32.83735738604594,"accuracy":10,"altitude_accuracy":4,"altitude":131.8,"heading":-1},"extras":{},"is_moving":false,"event":"geofence","odometer":0,"uuid":"EF9408BD-00FC-4EB2-878B-D3D366794890","geofence":{"action":"ENTER","identifier":"Atlas HQ-0"},"battery":{"level":1,"is_charging":true},"activity":{"type":"still","confidence":100},"timestamp":"2018-08-16T17:57:57.997Z"}}

req.body == {"location":{"coords":{"speed":0,"longitude":-96.86737348334572,"floor":null,"latitude":32.83735738604594,"accuracy":5,"altitude_accuracy":4,"altitude":132.5,"heading":-1},"extras":{},"is_moving":false,"event":"geofence","odometer":0,"uuid":"57BC97D9-EFCE-4991-8FBB-99749ECDAB8E","geofence":{"action":"DWELL","identifier":"Atlas HQ-0"},"battery":{"level":1,"is_charging":true},"activity":{"type":"still","confidence":100},"timestamp":"2018-08-16T17:58:04.000Z"}}

## Steps to Reproduce
//start listening for crossing of geofence boundaries
        BackgroundGeolocation.on('geofence', function(geofence) {
          console.log("Set listener BackgroundGeolocation.on('geofence'...");
          var action = geofence.location.geofence.action;
          console.log('A geofence has been crossed! geofence == ' + JSON.stringify(geofence));
          if(action == "ENTER"){
            //entered a vicinity
            try{
              BackgroundGeolocation.watchPosition(function(location) {
                console.log('Watch position: ' + JSON.stringify(location));                
                if(location.sample == undefined){
                  console.log("This is not a sample, so keeping the data.");
                  var currentTimestamp = new Date();
                  var timeSinceLastTransmission = (currentTimestamp - lastTransmission) / 1000;     
                  console.log("timeSinceLastTransmission == " + timeSinceLastTransmission);        
                  if(timeSinceLastTransmission >= 9){ //make sure the app waited X seconds
                    //transmit user location to the live location API
                    console.log("Transmitting user location to the live location API.");
                    //use the Cordova plugin's HTTP method to transmit
                    //see: https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#syncsuccessfn-failurefn                
                    BackgroundGeolocation.sync(function(locations) {
                      //Here are all the locations from the database.  The database is now EMPTY.
                      console.log('synced locations: ' + JSON.stringify(locations)); //DEV NOTE: this code never runs
                    }, function(errorMessage) {
                      console.log('Sync FAILURE: ' + JSON.stringify(errorMessage));
                    });        
                    lastTransmission = new Date();
                  }
                  else{
                    console.log("Skipping transmission. Only " + timeSinceLastTransmission + " seconds elapse since last transmission.");   
                  }
                }
                else{
                  //console.log("Skipping transmission. This is a sample (low accuracy data).");
                }                                      
              }, function(errorCode) {
                console.log('An location error occurred sharing location: ' + errorCode);
              }, {
                interval: (1000 * intervalTimeInSeconds),    // <-- retrieve a location every intervalTimeInSeconds.             
                persist: true,    // <-- default is true
              });
            }
            catch(error){
              console.log("unable to run BackgroundGeolocation.watchPosition");
            }
          } //action == "ENTER"
          if(action == "EXIT"){
            //left a vicinity
            // Stop watching position when the user leaves a Vicinity
            BackgroundGeolocation.stopWatchPosition();
          } //action == "EXIT"
        }); //Background.geolocation on geofence (Vicinity)

## Context
I want BackgroundGeolocation.sync(function(locations) to transmit at the watchPosition interval only. I want "BackgroundGeolocation.on('geofence'," to act as an event listener, but not transmit.

**Comment by christocracy** [comment]
You cannot.  Simply ignore geofences at the server.

**Comment by christocracy** [comment]
If you’re trying to throttle http requests, see `autoSyncThreshold` and use `autoSync: true`
