### ISSUE TITLE
iOS geofence doesn't work with locationAuthorizationRequest: 'WhenInUse'

### ISSUE THREAD

**Issue by flfruitios** [transistorsoft/cordova-background-geolocation-lt#753]
*Summary:
The geofencing feature does not trigger its callback when we use the config setting locationAuthorizationRequest: 'WhenInUse'. It does work when we use the default configuration setting locationAuthorizationRequest: 'Always'

## Your Environment
*Plugin version: 2.11.0
*Platform: iOS or Android: iOS
*OS version: 11.4
*Device manufacturer / model: iPhone 6+
*Cordova version (cordova -v): 8.0.0
*Cordova platform version (cordova platform **ls):4.5.4**
*Plugin config:
cordova-background-geolocation-lt 2.11.0 "BackgroundGeolocation"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 5.3.0 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.3 "PushPlugin"

## Expected Behavior
Geofence feature should fire its callback upon entry of the geofence radius when the app is in the foreground and the configuration setting locationAuthorizationRequest is set to 'WhenInUse'

## Actual Behavior
Geofence feature does not fire its callback upon entry of geofence radius when app is in foreground with configuration setting locationAuthorizationRequest is set to 'WhenInUse'. If the app is started from within the geofence radius, sometimes the callback is triggered, but not upon entry.

## Steps to Reproduce

1. Configure cordova-background-geolocation-lt with setting locationAuthorizationRequest: 'WhenInUse'
2. Add a geofence and put an ionicPopup alert in the callback for the geofence
3. Run the app and enter the geofence
4. Nothing happens

## Context
Trying to display an ionicPopup upon triggering a geofence by entering its radius using locationAuthorizationRequest = 'WhenInUse'

## Debug logs
https://github.com/VamshiKyra/ExploreFlorida/blob/master/background-geolocationWhenInUse.log

**Comment by christocracy** [comment]
That's correct.  The iOS geofence API *requires* `Always` authorization.

**Comment by joewoodhouse** [comment]
@christocracy this also means, as I understand it, that `preventSuspend` also won't work in `WhenInUse` mode, so your app will eventually die - the documentation should probably make this more clear? And potentially in the logs there should be big warnings about this sort of incompatible configuration?

**Comment by christocracy** [comment]
>this also means, as I understand it, that `preventSuspend` also won't work in `WhenInUse` mode

Correct.  `preventSuspend` uses periodic location-sample in the background to reset the background-time remaining.  If no `Always` authorization, the plugin is not allowed to *periodically request a location to reset the background time remaining*.
