### ISSUE TITLE
NOT WORKING....

### ISSUE THREAD

**Issue by pyeonjaesik** [transistorsoft/cordova-background-geolocation-lt#754]
When I set distnacefilter to 10 and 
activityRecognitionInterval tp to 5000 It works well. 
But I chage any of them, my device can not detect location. 
I think this plugin has many problems...

**Comment by christocracy** [comment]
Closed for failing to use issue template.

**Comment by pyeonjaesik** [comment]
Why did you edit my issue?

**Comment by christocracy** [comment]
You failed to use the issue template.  This issue is deleted.
