### ISSUE TITLE
Android version stops various times

### ISSUE THREAD

**Issue by timpisti** [transistorsoft/cordova-background-geolocation-lt#76]
Hi, 

I use the licenced version of this plugin.

It is required a licenced Google MAPS api and api key to proper using?

The android version of the plugin seems to stop working after a minute if the phone changes no coordinates (no movement) and the application is running in the background. This behaviour, however, occurs randomly so even if two identical phones come from the same manufacturer and same series, they can differ in whether they manifest this issue or not.

**Comment by sctosh** [comment]
Hi,

i have this problem, too.

**Comment by christocracy** [comment]
There is no Android version in the repo.
