### ISSUE TITLE
Android log problem

### ISSUE THREAD

**Issue by LarsBocons** [transistorsoft/cordova-background-geolocation-lt#765]
## Your Environment
* Plugin version: 2.11.0
* Platform: iOS or Android: Android
* OS version: 6.0
* Device manufacturer / model: Huawei Honor 7 lite
Phonegap version 7.1.0
* Cordova version (`cordova -v`): 
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config
{
    "activityRecognitionInterval": 500,
    "allowIdenticalLocations": true,
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": true,
    "deferTime": 0,
    "desiredAccuracy": 0,
    "desiredOdometerAccuracy": 10,
    "disableElasticity": true,
    "disableStopDetection": true,
    "distanceFilter": 0,
    "elasticityMultiplier": 1,
    "enableHeadless": false,
    "extras": {},
    "fastestLocationUpdateInterval": 900,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {},
    "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
    "heartbeatInterval": 30,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": false,
    "locationTemplate": "",
    "locationTimeout": 60,
    "locationUpdateInterval": 900,
    "locationsOrderDirection": "ASC",
    "logLevel": 0,
    "logMaxDays": 3,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": -1,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 20,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "Location Service activated",
    "notificationTitle": "",
    "params": {},
    "persist": true,
    "schedule": [],
    "startOnBoot": false,
    "stationaryRadius": 1,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": true,
    "stopTimeout": 60,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "",
    "enabled": true,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 160.52984619140625,
    "isFirstBoot": true
}

## Expected Behavior
Log background geolocation details

## Actual Behavior
In iOS the logs looks fine, but in Android I get virtually nothing :

08-20 07:35:01.481 DEBUG [TSConfig c] ℹ️   Persist config
08-20 07:40:09.553 DEBUG [TSConfig c] ℹ️   Persist config
08-20 08:09:46.549 DEBUG [TSConfig c] ℹ️   Persist config

This has worked before, so not shure why it stopped working. Maybe some security setting ? (see adb logcat)
[background-geolocation.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2301340/background-geolocation.log).
I should mention that the plugin works in Android. I get the locations I ask for, it's just the loggin that seems to fail.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
-->
C:\Users\lbor\Downloads\platform-tools_r28.0.0-windows\platform-tools>adb logcat -s TSLocationManager
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--------- beginning of main

C:\Users\lbor\Downloads\platform-tools_r28.0.0-windows\platform-tools>adb logcat -s TSLocationManager
- waiting for device -
^C
C:\Users\lbor\Downloads\platform-tools_r28.0.0-windows\platform-tools>adb logcat -s TSLocationManager
- waiting for device -
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--------- beginning of main
08-20 07:57:21.060 17456 17456 I TSLocationManager: - onResume
08-20 07:59:02.147 17456 17456 I TSLocationManager: - onPause

**Comment by christocracy** [comment]
Your logLevel is 0

**Comment by christocracy** [comment]
And be aware:  `#ready` only consumes the supplied config `{}` at first install of your app.  If you change the config after first install (eg:  changing `logLevel`, it is ignored unless you provide `reset: true`.  Or you can use `#setConfig`.

**Comment by christocracy** [comment]
As for you error:

```
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied
```

Never seen this before.  This isn't related to the plugin.

**Comment by LarsBocons** [comment]
Thank. I think it is due to some kind of racing situation. I had my loglevel set in a separate function like this:

function setBackGroundGeolocationLogging(value) {
    try {
        if (value) {
            window.BackgroundGeolocation.setConfig({
                logLevel: window.BackgroundGeolocation.LOG_LEVEL_VERBOSE
            }, function () {
                console.log("Changed logLevel success");
            });
        }
        else {            
            window.BackgroundGeolocation.setConfig({
                logLevel: window.BackgroundGeolocation.LOG_LEVEL_OFF
            }, function () {
                console.log("Switched off log success");
            });
        }
    }
    catch (e) { }
}

It's was called right before the main starting steps (and I verified that it called verbose), which also includes a configure call, but without logLevel. Instead of calling the setBackGroundGeolocationLogging function, I know just calculate the loglevel needed and insert in the main configure options.

That seems to work, but shouldn't the other approach work too? I mean, if I don't provide a logLevel in the options, the logLevel should be verbose, right?

**Comment by christocracy** [comment]
>if I don't provide a logLevel in the options, the logLevel should be verbose, right?

The default logLevel is `NONE`

**Comment by christocracy** [comment]
Correct, thanks
