### ISSUE TITLE
Crash in cordova-background-geolocation-SampleApp

### ISSUE THREAD

**Issue by Yermo** [transistorsoft/cordova-background-geolocation-lt#767]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS 
* OS version: 11.4.1
* Device manufacturer / model: Apple iPhone 7
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios 4.5.5
* Plugin config

Running the sample application: https://github.com/transistorsoft/cordova-background-geolocation-SampleApp

## Expected Behavior

It should not crash.
## Actual Behavior

Running the advanced demo for a random period of time, it crashes with 

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace ASSERTIOND, Code 0x8badf00d
Triggered by Thread:  0
  
## Steps to Reproduce

1. Run the advanced example.
2. click the play button.
3. let run for some hours.
4.

## Context

I'm trying to track down some odd behavior I'm seeing from the plugin in my own app. So my thought was to see if I can reproduce the behavior in the sample app. 

The sample app should be able to run indefinitely, no?  

## Debug logs

[BG Geo-2018-08-23-110441.ips.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2315381/BG.Geo-2018-08-23-110441.ips.log)

**Comment by Yermo** [comment]
Ah. Ok. Thank you for taking the time to look at it.

**Comment by christocracy** [comment]
If the plugin crashes, it’s clear to me.

In spite of an app crashing, iOS will reboot your app and tracking *will* resume.
