### ISSUE TITLE
We’re not getting “extras” information on a consistent basis from android

### ISSUE THREAD

**Issue by kkommuri** [transistorsoft/cordova-background-geolocation-lt#77]
.  Below is a log from the server side, where we’re logging every minute.   Any thoughts?

 stopOnTerminate: true,
                  stopTimeout: 3,
                  //activityRecognitionInterval: 10000,
                  debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                  desiredAccuracy: 0,
                  distanceFilter: 30,

                  //android settings
                  locationUpdateInterval:5000,
                  fastestLocationUpdateInterval: 1000,
                  triggerActivities: 'in_vehicle',
                  forceReloadOnMotionChange: false,
                  forceReloadOnLocationChange: false,
                  forceReloadOnGeofence: false,
                  startOnBoot: false,
                  foregroundService: false

"location":{"timestamp":"2016-02-25T20:15:28.990Z","is_moving":true,"coords":{"longitude":-88.1450489,"latitude":41.7573746,"speed":17.79405975341797,"accuracy":16,"altitude":196,"heading":125},"uuid":"8ac8f9bf-ea8d-4132-a514-570d7abef804","battery":{"is_charging":false,"level":0.6899999976158142}}}
{"location":{"timestamp":"2016-02-25T20:16:29.073Z","is_moving":true,"coords":{"longitude":-88.1355895,"latitude":41.753373,"speed":18.83049774169922,"accuracy":15,"altitude":202,"heading":127},"uuid":"0e8531d9-39b5-4af6-8855-754ee0974e20",**"extras":{"deviceType":"android"}**,"battery":{"is_charging":false,"level":0.6899999976158142}}}
{"location":{"timestamp":"2016-02-25T20:17:29.944Z","is_moving":true,"coords":{"longitude":-88.1286218,"latitude":41.745363,"speed":17.788000106811523,"accuracy":8,"altitude":178,"heading":163},"uuid":"58d821d7-2997-4ee4-adab-c31ff2a2a86a","battery":{"is_charging":false,"level":0.6899999976158142}}}
{"location":{"timestamp":"2016-02-25T20:18:31.989Z","is_moving":true,"coords":{"longitude":-88.1281016,"latitude":41.738315,"speed":16.602487564086914,"accuracy":96,"altitude":172,"heading":183},"uuid":"1ca88d1e-bcd1-4060-9922-9768b0f6c911",**"extras":{"deviceType":"android"}**,"battery":{"is_charging":false,"level":0.6899999976158142}}}
{"location":{"timestamp":"2016-02-25T20:19:35.060Z","is_moving":true,"coords":{"longitude":-88.1305001,"latitude":41.7283854,"speed":19.065845489501953,"accuracy":96,"altitude":182,"heading":205},"uuid":"deffd17b-d1f0-4383-a3e9-a13d7a6e793e","battery":{"is_charging":false,"level":0.6800000071525574}}}
{"location":{"timestamp":"2016-02-25T20:20:34.049Z","is_moving":true,"coords":{"longitude":-88.1342859,"latitude":41.7209692,"speed":7.161787509918213,"accuracy":96,"altitude":172,"heading":232},"uuid":"92790b2a-7905-41c2-b6e0-f0cd7cc26f2c",**"extras":{"deviceType":"android"}**,"battery":{"is_charging":false,"level":0.6800000071525574}}}
{"location":{"timestamp":"2016-02-25T20:21:34.991Z","is_moving":true,"coords":{"longitude":-88.140671,"latitude":41.7152245,"speed":14.081718444824219,"accuracy":7,"altitude":172,"heading":227},"uuid":"8b382f9b-3847-47ba-8be3-47dfb64b7f94","battery":{"is_charging":false,"level":0.6800000071525574}}}
{"location":{"timestamp":"2016-02-25T20:22:38.022Z","is_moving":true,"coords":{"longitude":-88.1495845,"latitude":41.7107694,"speed":14.183998107910156,"accuracy":17,"altitude":204,"heading":262},"uuid":"af0cb4c0-d575-4ad5-99f8-e9cf8adf802f","battery":{"is_charging":false,"level":0.6800000071525574}}}
{"location":{"timestamp":"2016-02-25T20:23:37.117Z","is_moving":true,"coords":{"longitude":-88.1593443,"latitude":41.7103778,"speed":12.078763008117676,"accuracy":14,"altitude":187,"heading":238},"uuid":"a91d7175-a934-43f6-ae38-21646224ec9d","battery":{"is_charging":false,"level":0.6700000166893005}}}
{"location":{"timestamp":"2016-02-25T20:24:39.024Z","is_moving":true,"coords":{"longitude":-88.156437,"latitude":41.7063031,"speed":10.13071060180664,"accuracy":10,"altitude":192,"heading":135},"uuid":"67b98b31-bc66-4d63-a0ad-3ca64b9a180a",**"extras":{"deviceType":"android"}**,"battery":{"is_charging":false,"level":0.6700000166893005}}}
{"location":{"timestamp":"2016-02-25T20:25:45.043Z","is_moving":true,"coords":{"longitude":-88.1560863,"latitude":41.7057649,"speed":1.7066048383712769,"accuracy":20,"altitude":157,"heading":325},"uuid":"7c29380b-141b-456f-8eae-7cb640e67752",**"extras":{"deviceType":"android"}**,"battery":{"is_charging":false,"level":0.6700000166893005}}}

**Comment by christocracy** [comment]
Please post Android issues at the private "premium" repo.
