### ISSUE TITLE
Plugin doesn't works on Android Oreo

### ISSUE THREAD

**Issue by joseiherq** [transistorsoft/cordova-background-geolocation-lt#770]
## Your Environment
* Plugin version: 2.13.0
* Platform: Android
* OS version: 8.0.1
* Device manufacturer / model: Nexus 5X
* Cordova version (`cordova -v`):  8.0.0
* Cordova platform version (`cordova platform ls`): 7.0.1
* Plugin config

## Expected Behavior

The plugin must track the user position on background

## Actual Behavior

The app crashes

## Steps to Reproduce

1. Run code of [https://gist.github.com/christocracy/2abf5587cc12b83e15aa12958de7a7d2#file-backgroundgeolocation-ionic2-js]
2. Press button home on mobile device when background tracking is activated
3. App crashes

## Context

I was trying to track user position on background using a device with Android Oreo

## Debug logs

    --------- beginning of crash
08-24 15:36:09.798 14520-14520/com.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test, PID: 14520
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-24 15:36:09.803 1664-1711/? W/ActivityManager:   Force finishing activity com.test/.MainActivity
08-24 15:36:09.812 6778-6778/? I/OptInState: There is a new client and it does not support opt-in. Dropping request.
08-24 15:36:09.822 1664-1679/? I/ActivityManager: Showing crash dialog for package com.test u0
08-24 15:36:09.891 1664-1675/? I/WifiService: getConnectionInfo uid=10032
08-24 15:36:09.901 2327-2522/? D/EGL_emulation: eglMakeCurrent: 0x9e906680: ver 2 0 (tinfo 0x9e903770)
08-24 15:36:09.912 1427-3958/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
08-24 15:36:09.926 1427-3958/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
08-24 15:36:09.946 1664-2937/? I/WifiService: getWifiEnabledState uid=10032
08-24 15:36:09.947 6778-14537/? W/Settings: Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
08-24 15:36:09.975 1664-1679/? W/Looper: Dispatch took 155ms on android.ui, h=Handler (com.android.server.am.ActivityManagerService$UiHandler) {ccd35a6} cb=null msg=1
08-24 15:36:09.981 6778-13200/? W/LocationOracle: No location history returned by ContextManager
08-24 15:36:10.004 1435-2003/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
08-24 15:36:10.032 6778-6778/? I/MicroDetectionWorker: #updateMicroDetector [detectionMode: [mDetectionMode: [1]]]
08-24 15:36:10.033 6778-6778/? I/MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
08-24 15:36:10.033 6778-6778/? I/AudioController: Using mInputStreamFactoryBuilder
08-24 15:36:10.055 1445-1445/? E/EGL_emulation: tid 1445: eglCreateSyncKHR(1962): error 0x3004 (EGL_BAD_ATTRIBUTE)
08-24 15:36:10.057 6778-14655/? I/MicroRecognitionRunner: Starting detection.
08-24 15:36:10.058 6778-14535/? I/MicrophoneInputStream: mic_starting com.google.android.apps.gsa.staticplugins.aa.c@a16c13e
08-24 15:36:10.108 1791-1989/? D/EGL_emulation: eglMakeCurrent: 0x8d47e800: ver 2 0 (tinfo 0x8d47c860)

**Comment by christocracy** [comment]
Use 2.12.x until I verify this.

**Comment by joseiherq** [comment]
Thanks @christocracy, version 2.12.0 doesn't crash! It doesn't work correct for me now, but i think is an problem on my code because i test your demo app and it works perfect.

**Comment by christocracy** [comment]
I’m keeping this open until in investigate.  I changed something related to notification-channel, making the name configurable rather than hard coded name.

**Comment by christocracy** [comment]
I cannot reproduce this issue.  Can you please install latest version `2.13.1` and let me know if you can reproduce this issue?

**Comment by joseiherq** [comment]
I'm using version 2.13.1 and it's correct. The app crash only when i used at same time the plugin [https://github.com/tushe/cordova-plugin-background-mode](url).

Maybe this two plugins are incompatible.

**Comment by joseiherq** [comment]
I think that [https://github.com/tushe/cordova-plugin-background-mode](url) is not necessary, your plugin stand alive the app @christocracy.

Sorry for wast your time with this innecesary issue... :(

Thanks for helping!

**Comment by christocracy** [comment]
**Never** Use cordova-plugin-background-mode!  That plugin is toxic.  Apple will reject apps using that (unless your app is an audio player) since it requests the background `audio` capability and plays a silent `.wav` file to achieve its “magic”.
