### ISSUE TITLE
It calls only twice callback function.

### ISSUE THREAD

**Issue by AlexTerry1024** [transistorsoft/cordova-background-geolocation-lt#772]
## Your Environment
* Plugin version: 2.13.0
* Platform:Android
* OS version:7.0
* Device manufacturer / model: Hwawei P10 lite/WAS-LX2J
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 7.0
* Plugin config

## Expected Behavior

I hope it works to capture all while stop
## Actual Behavior

It calls only twice callback function.

**Comment by christocracy** [comment]
I have no idea what "it calls only twice callback function" means.

And don't you think the plugin config you're using *might* be *incredibly* relevant to an issue you might be having?

Also, are you observing `$ adb logcat -s TSLocationManager` (See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging).  The plugin is logging a massive amount of information about what it's doing.  You're probably not even watching it.

**Comment by AlexTerry1024** [comment]
Okay, I found a solution myself.

Thanks for your time.
