### ISSUE TITLE
events triggered by accelerometer

### ISSUE THREAD

**Issue by locsim** [transistorsoft/cordova-background-geolocation-lt#773]
Hi everyone,

My app sometimes need to be informed about the phone owner's movements. For example, detect if he is moving, or not. At first sight, the activitychange event could do the job, but for some reason, it can't, mainly because:
-it is not responsive enough, even when activityRecognitionInterval is set to 0. 
-it can report the phone to be 'still' even if it is slightly moving (it is not possible to choose sensitivity).

This is only an example, because of course one could be interested by various situations (freefall, given position, single tap, double tap and so on). So being able to trigger events in given situations would be really great.

The sensors used in phones have this calpability (process data and raise interrupts when asked: freefall, motion detection, pulse detection, orientation, Is this exposed by android to native code?

This could be a great enhancement for this plugin.
Or anyone already successfully read the accelerometer data in the background from a cordova app?

## Expected Behavior
Example:  trigger an event when no movement occured for a period of time.

**Comment by christocracy** [comment]
>detect if he is moving, or not.

This is the core philosophy of the plugin.  To automatically toggle location-services when the device is detected to be moving or not.

>when no movement occured for a period of time.

Just keep a timestamp of the last time you received a `still` event from `activitychange` event.  Use `cordova-plugin-background-fetch` to ask "How old is the last known event from `activitychange`?" with each fetch-event.  You'll get these fetch-events about every 15 min.

**Comment by locsim** [comment]
Hello Chris, thank you for your quick reply.
I understand that motion detection as it is currently performed by your plugin is designed to decide if it is worth switching the GPS on, or not.

What I need is a little bit different: I want to know if the guy is, conscious or not . So I need to know if he moved, even a little bit. And it looks like small movements won't trigger activity change, and so I cant rely on this in situation when somebody watches tv sitting in a chair, eg.

**Comment by christocracy** [comment]
you will have trouble with your use-case on a phone.  Phones are designed to sleep an app when running in background in order to conserve energy.

**Comment by locsim** [comment]
Yes. Phones, and a lot of other devices try to save energy. This is why accelerometers ara capable of doing many things, not only providing a flow af data.
Please have a look at chapter 5.5 of this document (it will be much better explained than if I try to!):
https://www.nxp.com/files-static/sensors/doc/data_sheet/MMA8452Q.pdf
