### ISSUE TITLE
Location not tracking after main activity closed

### ISSUE THREAD

**Issue by thomas550i** [transistorsoft/cordova-background-geolocation-lt#775]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: MOTO G5 plus
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config

{"desiredAccuracy": 0, "distanceFilter": 150, "stationaryRadius": 25, "activityRecognitionInterval": 10000, "stopTimeout": 5, "debug": false, "stopOnTerminate": false, "startOnBoot": true, "disableElasticity": false, "url": "/BackgroundGeoLocation", "method": "POST", "autoSync": true,"autoSyncThreshold":10,"batchSync":true,"maxBatchSize":10,"httpTimeout": 120000, "maxDaysToPersist": 3, "params": "",logLevel : 4 }

## Expected Behavior

Location tracking should work after main activity closed. 

## Actual Behavior

When Main Activity running tracking working fine , but when main activity closed , the location tracking was not working .

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

08-29 13:51:54.660 DEBUG [TSConfig c] ℹ️   Persist config
08-29 13:51:54.674 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
08-29 13:51:54.683 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

08-29 13:51:54.687 INFO [BackgroundGeolocationService a] 
  🔵  setPace: false → false
08-29 13:51:54.687 DEBUG [BackgroundGeolocation ready] LocationPermission :true
08-29 13:51:54.689 DEBUG [c allWithLocking] 
  ✅  Locked 0 records
08-29 13:51:54.693 DEBUG [TSConfig c] ℹ️   Persist config
08-29 13:51:54.700 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
08-29 13:51:54.707 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
08-29 13:51:54.783 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 13.064987,80.257516 acc=16 et=+3d11h5m47s798ms], age: 21ms, time: 1535530914759

08-29 13:51:54.784 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired providerchange position
08-29 13:51:54.795 DEBUG [TSLocationManager a] 16.05
08-29 13:51:54.823 INFO [c persist] 
  ✅  INSERT: 5846d04c-adbb-4969-83ad-b2a8ea21e66b
08-29 13:51:54.823 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 3
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 13.064987,80.257516 acc=16 et=+3d11h5m47s798ms], age: 61ms, time: 1535530914759

08-29 13:51:54.825 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: false
08-29 13:51:54.839 DEBUG [TSLocationManager a] 16.1
08-29 13:51:54.863 INFO [c persist] 
  ✅  INSERT: c4f552c2-7cc3-4cc0-a251-0611cb666d70
08-29 13:51:54.880 DEBUG [BackgroundGeolocation$h$1 onSuccess] StartTask success
08-29 13:51:54.882 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

08-29 13:51:54.895 DEBUG [c allWithLocking] 
  ✅  Locked 2 records
08-29 13:51:54.900 INFO [HttpService a] 
  🔵  HTTP POST batch (2)
08-29 13:51:57.212 INFO [HttpService$a onResponse] 
  🔵  Response: 200
08-29 13:51:57.241 DEBUG [c destroyAll] 
  ✅  DELETED: (2)
08-29 13:51:57.271 DEBUG [c allWithLocking] 
  ✅  Locked 0 records
08-29 13:52:07.334 DEBUG [TSConfig c] ℹ️   Persist config
08-29 13:53:52.475 INFO [BackgroundGeolocation onActivityDestroy] 
╔═════════════════════════════════════════════
║ MainActivity was destroyed
╠═════════════════════════════════════════════
╟─ stopOnTerminate: false
╟─ enabled: true

08-29 13:53:52.515 DEBUG [BackgroundGeolocation c] 
  🔴  Cleared callbacks
08-29 13:53:52.530 DEBUG [BackgroundGeolocation isMainActivityActive] NO
08-29 13:53:52.545 DEBUG [BackgroundGeolocationService onActivityDestroyed] 
╔═════════════════════════════════════════════
║ BackgroundGeolocationService Rx ActivityDestroyed
╠═════════════════════════════════════════════

08-29 13:53:52.552 INFO [BackgroundGeolocationService k] 
  🔴  Stop heartbeat
08-29 14:31:08.253 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 2.12.13 (269)
╠═════════════════════════════════════════════
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "autoSync": true,
  "autoSyncThreshold": 10,
  "batchSync": true,
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "disableElasticity": false,
  "disableStopDetection": false,
  "distanceFilter": 150,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "extras": {},
  "fastestLocationUpdateInterval": 10000,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": false,
  "geofenceInitialTriggerEntry": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 120000,
  "isMoving": false,
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 4,
  "logMaxDays": 3,
  "maxBatchSize": 10,
  "maxDaysToPersist": 3,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "notificationColor": "",
  "notificationLargeIcon": "",
  "notificationPriority": 0,
  "notificationSmallIcon": "",
  "notificationText": "Location Service activated",
  "notificationTitle": "",
  "params": {
    "strUId": "Smp06",
    "strCompcode": "Dem116",
    "strSessID": ""
  },
  "persist": true,
  "schedule": [],
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "https:\/\/staging.talentproindia.com\/TalentHRService.svc\/\/BackgroundGeoLocation",
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 0,
  "isFirstBoot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DS3 Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=78.4532, resolution=0.0023956299, power=0.9, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="LSM6DS3 Gyroscope", vendor="STMicroelectronics", version=1, type=4, maxRange=34.906586, resolution=0.0012207031, power=0.9, minDelay=5000}
╟─ ⚠️  MAGNETOMETER:  none.  Motion-detection system performance will be degraded
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.8999939, minDelay=-1}
╚═════════════════════════════════════════════
08-29 14:31:08.328 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:12451000)
08-29 14:31:08.356 DEBUG [c a] 
  ✅  Opened database
08-29 14:31:08.371 DEBUG [c prune] 
  ℹ️  PRUNE -3 days
08-29 14:31:08.405 DEBUG [a f] 
  ✅  Opened database

**Comment by christocracy** [comment]
When I terminate my app using your config, I see the following logs:

```
08-29 09:14:58.320  9297  9297 I TSLocationManager: CDVBackgroundGeolocation#onDestoy
08-29 09:14:58.330  9297  9297 I TSLocationManager: [c.t.l.a.BackgroundGeolocation onActivityDestroy]
08-29 09:14:58.330  9297  9297 I TSLocationManager: ╔═════════════════════════════════════════════
08-29 09:14:58.330  9297  9297 I TSLocationManager: ║ MainActivity was destroyed
08-29 09:14:58.330  9297  9297 I TSLocationManager: ╠═════════════════════════════════════════════
08-29 09:14:58.330  9297  9297 I TSLocationManager: ╟─ stopOnTerminate: false
08-29 09:14:58.330  9297  9297 I TSLocationManager: ╟─ enabled: true
08-29 09:14:58.350  9297  9297 D TSLocationManager: [c.t.l.a.BackgroundGeolocation c]
08-29 09:14:58.350  9297  9297 D TSLocationManager:   🔴  Cleared callbacks
08-29 09:14:58.350  9297  9297 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
08-29 09:14:58.400  9297  9297 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityDestroyed]
08-29 09:14:58.400  9297  9297 D TSLocationManager: ╔═════════════════════════════════════════════
08-29 09:14:58.400  9297  9297 D TSLocationManager: ║ BackgroundGeolocationService Rx ActivityDestroyed
08-29 09:14:58.400  9297  9297 D TSLocationManager: ╠═════════════════════════════════════════════
08-29 09:14:58.400  9297  9297 I TSLocationManager: [c.t.l.BackgroundGeolocationService k]
08-29 09:14:58.400  9297  9297 I TSLocationManager:   🔴  Stop heartbeat

08-29 09:14:59.700  9471  9471 I TSLocationManager:
08-29 09:14:59.700  9471  9471 I TSLocationManager: ╔═════════════════════════════════════════════
08-29 09:14:59.700  9471  9471 I TSLocationManager: ║ License Validation Failure
08-29 09:14:59.700  9471  9471 I TSLocationManager: ╠═════════════════════════════════════════════
08-29 09:14:59.700  9471  9471 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
08-29 09:14:59.740  9471  9471 I TSLocationManager: [c.t.l.adapter.TSConfig print]
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╔═════════════════════════════════════════════
08-29 09:14:59.740  9471  9471 I TSLocationManager: ║ TSLocationManager version: 2.12.22 (278)
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╠═════════════════════════════════════════════
08-29 09:14:59.740  9471  9471 I TSLocationManager: {
.
.
.
08-29 09:14:59.740  9471  9471 I TSLocationManager:   "foregroundService": false,
08-29 09:14:59.740  9471  9471 I TSLocationManager:   "startOnBoot": true,
08-29 09:14:59.740  9471  9471 I TSLocationManager:   "stopOnTerminate": false,
08-29 09:14:59.740  9471  9471 I TSLocationManager:   "enabled": true,
.
.
.
08-29 09:14:59.740  9471  9471 I TSLocationManager: }
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╔═════════════════════════════════════════════
08-29 09:14:59.740  9471  9471 I TSLocationManager: ║ DEVICE SENSORS
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╠═════════════════════════════════════════════
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DS3 Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=78.4532, resolution=5.950928E-4, power=0.07, minDelay=5000}
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╟─ ✅  GYROSCOPE: {Sensor name="LSM6DS3 Gyroscope", vendor="STMicroelectronics", version=1, type=4, maxRange=34.906586, resolution=1.5258789E-4, power=0.83, minDelay=5000}
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╟─ ✅  MAGNETOMETER: {Sensor name="AK09911 Magnetometer", vendor="AKM", version=1, type=2, maxRange=4911.9995, resolution=0.5996704, power=2.4, minDelay=20000}
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.069992065, minDelay=-1}
08-29 09:14:59.740  9471  9471 I TSLocationManager: ╚═════════════════════════════════════════════
08-29 09:14:59.770  9471  9471 I TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>]
08-29 09:14:59.770  9471  9471 I TSLocationManager:   ✅  Google Play Services: connected (version code:12451000)
08-29 09:14:59.790  9471  9471 D TSLocationManager: [c.t.locationmanager.data.a.c a]
08-29 09:14:59.790  9471  9471 D TSLocationManager:   ✅  Opened database
08-29 09:14:59.800  9471  9471 D TSLocationManager: [c.t.locationmanager.data.a.c prune]
08-29 09:14:59.800  9471  9471 D TSLocationManager:   ℹ️  PRUNE -7 days
08-29 09:14:59.830  9471  9471 D TSLocationManager: [c.t.locationmanager.data.a.a f]
08-29 09:14:59.830  9471  9471 D TSLocationManager:   ✅  Opened database
08-29 09:14:59.860  9471  9471 I TSLocationManager: [c.t.l.BackgroundGeolocationService onStartCommand]
08-29 09:14:59.860  9471  9471 I TSLocationManager: ╔═════════════════════════════════════════════
08-29 09:14:59.860  9471  9471 I TSLocationManager: ║ BackgroundGeolocation Service started
08-29 09:14:59.860  9471  9471 I TSLocationManager: ╠═════════════════════════════════════════════
08-29 09:14:59.870  9471  9471 I TSLocationManager: [c.t.l.ActivityRecognitionService a]
```

**Comment by christocracy** [comment]
The crucial log-entry after terminating with `stopOnTerminate: false` is:
```
4:59.860  9471  9471 I TSLocationManager: ╔═════════════════════════════════════════════
08-29 09:14:59.860  9471  9471 I TSLocationManager: ║ BackgroundGeolocation Service started
08-29 09:14:59.860  9471  9471 I TSLocationManager: ╠═════════════════════════════════════════════
```

**Comment by Cow258** [comment]
Same Issue

**Comment by NaveenBalakrishnan1** [comment]
08-29 09:14:58.330  9297  9297 I TSLocationManager: ║ MainActivity was destroyed ,when i close the app,the location manager does not track the location and no callbacks are fired

**Comment by NaveenBalakrishnan1** [comment]
> ## Your Environment
> * Plugin version: 2.11.0
> * Platform: Android
> * OS version: 7.1.1
> * Device manufacturer / model: MOTO G5 plus
> * Cordova version (`cordova -v`): 8.0.0
> * Cordova platform version (`cordova platform ls`): android 6.3.0
> * Plugin config
> 
> {"desiredAccuracy": 0, "distanceFilter": 150, "stationaryRadius": 25, "activityRecognitionInterval": 10000, "stopTimeout": 5, "debug": false, "stopOnTerminate": false, "startOnBoot": true, "disableElasticity": false, "url": "/BackgroundGeoLocation", "method": "POST", "autoSync": true,"autoSyncThreshold":10,"batchSync":true,"maxBatchSize":10,"httpTimeout": 120000, "maxDaysToPersist": 3, "params": "",logLevel : 4 }
> 
> ## Expected Behavior
> Location tracking should work after main activity closed.
> 
> ## Actual Behavior
> When Main Activity running tracking working fine , but when main activity closed , the location tracking was not working .
> 
> ## Steps to Reproduce
> 
> ## Context
> ## Debug logs
> 08-29 13:51:54.660 DEBUG [TSConfig c] ℹ️ Persist config
> 08-29 13:51:54.674 DEBUG [b a]
> ℹ️ LocationAuthorization: Permission granted
> 08-29 13:51:54.683 DEBUG [HttpService flush]
> ╔═════════════════════════════════════════════
> ║ HTTP Service
> ╠═════════════════════════════════════════════
> 
> 08-29 13:51:54.687 INFO [BackgroundGeolocationService a]
> 🔵 setPace: false → false
> 08-29 13:51:54.687 DEBUG [BackgroundGeolocation ready] LocationPermission :true
> 08-29 13:51:54.689 DEBUG [c allWithLocking]
> ✅ Locked 0 records
> 08-29 13:51:54.693 DEBUG [TSConfig c] ℹ️ Persist config
> 08-29 13:51:54.700 DEBUG [b a]
> ℹ️ LocationAuthorization: Permission granted
> 08-29 13:51:54.707 DEBUG [b a]
> ℹ️ LocationAuthorization: Permission granted
> 08-29 13:51:54.783 DEBUG [SingleLocationRequest$2 onLocationResult]
> ╔═════════════════════════════════════════════
> ║ SingleLocationRequest: 2
> ╠═════════════════════════════════════════════
> ╟─ 📍 Location[fused 13.064987,80.257516 acc=16 et=+3d11h5m47s798ms], age: 21ms, time: 1535530914759
> 
> 08-29 13:51:54.784 INFO [TSLocationManager onSingleLocationResult]
> 🔵 Acquired providerchange position
> 08-29 13:51:54.795 DEBUG [TSLocationManager a] 16.05
> 08-29 13:51:54.823 INFO [c persist]
> ✅ INSERT: 5846d04c-adbb-4969-83ad-b2a8ea21e66b
> 08-29 13:51:54.823 DEBUG [SingleLocationRequest$2 onLocationResult]
> ╔═════════════════════════════════════════════
> ║ SingleLocationRequest: 3
> ╠═════════════════════════════════════════════
> ╟─ 📍 Location[fused 13.064987,80.257516 acc=16 et=+3d11h5m47s798ms], age: 61ms, time: 1535530914759
> 
> 08-29 13:51:54.825 INFO [TSLocationManager onSingleLocationResult]
> 🔵 Acquired motionchange position, isMoving: false
> 08-29 13:51:54.839 DEBUG [TSLocationManager a] 16.1
> 08-29 13:51:54.863 INFO [c persist]
> ✅ INSERT: c4f552c2-7cc3-4cc0-a251-0611cb666d70
> 08-29 13:51:54.880 DEBUG [BackgroundGeolocation$h$1 onSuccess] StartTask success
> 08-29 13:51:54.882 DEBUG [HttpService flush]
> ╔═════════════════════════════════════════════
> ║ HTTP Service
> ╠═════════════════════════════════════════════
> 
> 08-29 13:51:54.895 DEBUG [c allWithLocking]
> ✅ Locked 2 records
> 08-29 13:51:54.900 INFO [HttpService a]
> 🔵 HTTP POST batch (2)
> 08-29 13:51:57.212 INFO [HttpService$a onResponse]
> 🔵 Response: 200
> 08-29 13:51:57.241 DEBUG [c destroyAll]
> ✅ DELETED: (2)
> 08-29 13:51:57.271 DEBUG [c allWithLocking]
> ✅ Locked 0 records
> 08-29 13:52:07.334 DEBUG [TSConfig c] ℹ️ Persist config
> 08-29 13:53:52.475 INFO [BackgroundGeolocation onActivityDestroy]
> ╔═════════════════════════════════════════════
> ║ MainActivity was destroyed
> ╠═════════════════════════════════════════════
> ╟─ stopOnTerminate: false
> ╟─ enabled: true
> 
> 08-29 13:53:52.515 DEBUG [BackgroundGeolocation c]
> 🔴 Cleared callbacks
> 08-29 13:53:52.530 DEBUG [BackgroundGeolocation isMainActivityActive] NO
> 08-29 13:53:52.545 DEBUG [BackgroundGeolocationService onActivityDestroyed]
> ╔═════════════════════════════════════════════
> ║ BackgroundGeolocationService Rx ActivityDestroyed
> ╠═════════════════════════════════════════════
> 
> 08-29 13:53:52.552 INFO [BackgroundGeolocationService k]
> 🔴 Stop heartbeat
> 08-29 14:31:08.253 INFO [TSConfig print]
> ╔═════════════════════════════════════════════
> ║ TSLocationManager version: 2.12.13 (269)
> ╠═════════════════════════════════════════════
> {
> "activityRecognitionInterval": 10000,
> "allowIdenticalLocations": false,
> "autoSync": true,
> "autoSyncThreshold": 10,
> "batchSync": true,
> "debug": false,
> "deferTime": 0,
> "desiredAccuracy": 0,
> "desiredOdometerAccuracy": 100,
> "disableElasticity": false,
> "disableStopDetection": false,
> "distanceFilter": 150,
> "elasticityMultiplier": 1,
> "enableHeadless": false,
> "extras": {},
> "fastestLocationUpdateInterval": 10000,
> "forceReloadOnBoot": false,
> "forceReloadOnGeofence": false,
> "forceReloadOnHeartbeat": false,
> "forceReloadOnLocationChange": false,
> "forceReloadOnMotionChange": false,
> "forceReloadOnSchedule": false,
> "foregroundService": false,
> "geofenceInitialTriggerEntry": true,
> "geofenceProximityRadius": 1000,
> "geofenceTemplate": "",
> "headers": {},
> "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
> "heartbeatInterval": -1,
> "httpRootProperty": "location",
> "httpTimeout": 120000,
> "isMoving": false,
> "locationTemplate": "",
> "locationTimeout": 60,
> "locationUpdateInterval": 1000,
> "locationsOrderDirection": "ASC",
> "logLevel": 4,
> "logMaxDays": 3,
> "maxBatchSize": 10,
> "maxDaysToPersist": 3,
> "maxRecordsToPersist": -1,
> "method": "POST",
> "minimumActivityRecognitionConfidence": 75,
> "notificationColor": "",
> "notificationLargeIcon": "",
> "notificationPriority": 0,
> "notificationSmallIcon": "",
> "notificationText": "Location Service activated",
> "notificationTitle": "",
> "params": {
> "strUId": "Smp06",
> "strCompcode": "Dem116",
> "strSessID": ""
> },
> "persist": true,
> "schedule": [],
> "startOnBoot": true,
> "stationaryRadius": 25,
> "stopAfterElapsedMinutes": 0,
> "stopOnStationary": false,
> "stopOnTerminate": false,
> "stopTimeout": 5,
> "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
> "url": "https://staging.talentproindia.com/TalentHRService.svc//BackgroundGeoLocation",
> "enabled": true,
> "schedulerEnabled": false,
> "trackingMode": 1,
> "odometer": 0,
> "isFirstBoot": false
> }
> ╔═════════════════════════════════════════════
> ║ DEVICE SENSORS
> ╠═════════════════════════════════════════════
> ╟─ ✅ ACCELEROMETER: {Sensor name="LSM6DS3 Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=78.4532, resolution=0.0023956299, power=0.9, minDelay=5000}
> ╟─ ✅ GYROSCOPE: {Sensor name="LSM6DS3 Gyroscope", vendor="STMicroelectronics", version=1, type=4, maxRange=34.906586, resolution=0.0012207031, power=0.9, minDelay=5000}
> ╟─ ⚠️ MAGNETOMETER: none. Motion-detection system performance will be degraded
> ╟─ ✅ SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.8999939, minDelay=-1}
> ╚═════════════════════════════════════════════
> 08-29 14:31:08.328 INFO [BackgroundGeolocation ]
> ✅ Google Play Services: connected (version code:12451000)
> 08-29 14:31:08.356 DEBUG [c a]
> ✅ Opened database
> 08-29 14:31:08.371 DEBUG [c prune]
> ℹ️ PRUNE -3 days
> 08-29 14:31:08.405 DEBUG [a f]
> ✅ Opened database

Any solutions for this issue,it still exists,Need any clarification or sample Application.java and MainActivity.java files,that could help others.
