### ISSUE TITLE
Location Tracking Missing some points 

### ISSUE THREAD

**Issue by thomas550i** [transistorsoft/cordova-background-geolocation-lt#776]
## Your Environment
* Plugin version: 2.11.0
* Platform: iOS or Android
* OS version: 
* Device manufacturer / model: Samsung Galaxy J7
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config

```
{
	"desiredAccuracy": 0,
	"distanceFilter": 150,
	"stationaryRadius": 25,
	"activityRecognitionInterval": 10000,
	"stopTimeout": 5,
	"debug": false,
	"stopOnTerminate": false,
	"startOnBoot": true,
	"disableElasticity": false,
	"url": "/BackgroundGeoLocation",
	"method": "POST",
	"autoSync": true,
	"autoSyncThreshold": 10,
	"batchSync": true,
	"maxBatchSize": 10,
	"httpTimeout": 120000,
	"maxDaysToPersist": 3,
	"params": ""
}
```

## Expected Behavior

User start his travel to a point and come back to the source point , starting and ending path should capture. 

## Actual Behavior

User walk some where and stop on local time 13:05:17 and start again  on_bicycle at 13:40,  but we got data after 14:07.

Have this data for your reference
 
12:32:09 --> is_moving": true->on_foot
13:05:17 --> is_moving": false->still
13:33:53 --> is_moving": false->still
14:07:34 --> is_moving": true->on_bicycle

Missing data between 13:40 to 14:07, Kindly let me know did i have to change any settings ?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
There is nothing wrong with your settings.

Your issue is most likely due to device / environment.  You'll find a wealth of information from the plugin in the native android logs.  It's impossible to even begin to speculate upon your problem without plugin logs.

See Wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)
