### ISSUE TITLE
Not working on cli-8.0.0 adobe phonegap build

### ISSUE THREAD

**Issue by umasankarm** [transistorsoft/cordova-background-geolocation-lt#779]
I added the following in my config.xml
```xml
<plugin name="cordova-background-geolocation-lt" spec="2.12.2" source="npm">
         <variable name="LICENSE" value="YOUR_LICENSE_KEY" />
        <variable name="GOOGLE_API_VERSION" value="11.8.0" />
        <variable name="APPCOMPAT_VERSION" value="27.0.0" />
        <variable name="BACKGROUND_MODE_LOCATION" value="&lt;string&gt;location&lt;/string&gt;" />
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Always use is required for constant background location-tracking" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" /> 
    </plugin> 
```

and my preference is `<preference name='phonegap-version' value='cli-8.0.0' /> ` adobe phonegap build successfully but BackgroundGeolcoation is not initialized inside the project

What is the correct version supports cli-8.0.0 ? or what version of the plugin i need to use with cli-7.0.1/cli-7.1.0 ?

**Comment by umasankarm** [comment]
What is issue template ?

**Comment by christocracy** [comment]
That big check of text you see in the text area that you didn’t read before deleting it all.

https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/new

**Comment by christocracy** [comment]
Copy that chunk of text and **edit** your original post in *tgis* thread.

Do **NOT** create a new issue.

**Comment by umasankarm** [comment]
ok i did it on new issue no 780

**Comment by christocracy** [comment]
You don’t read or follow rules, do you?

**Comment by umasankarm** [comment]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS or Android
* OS version: android 7.1.1
* Device manufacturer / model: lenova k8 plus
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): (Android phonegap : 7.0.0 / iOS : 4.5.5 / windows : 5.0.0)
* Plugin config : default config

## Expected Behavior
window.BackgroundGeolocation object not initialized  

## Actual Behavior
window.BackgroundGeolocation object is undefined

## Steps to Reproduce

1. zipped the source file 
2. upload the zip file to adobe phonegap build site

## Context
Trying to integrate plugin in my application

## Debug logs
Build Date: 2018-08-31 09:38:18 +0000 
above values only available in log

**Comment by christocracy** [comment]
```
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.0.0
Skipping 'cordova-background-geolocation-lt' for android
```

Version `2.12.x` of `background-geolocation` *requires* `cordova-android >= 7.0.0`.  You are clearly using `6.3.0`

You are also having issues with `cordova-plugin-compat` for the same reason.
```
Installing "cordova-plugin-compat" at "1.2.0" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: 
      <6.3.0
```

**Comment by umasankarm** [comment]
Ok what version of your plugin is compatible with cordova-android 6.2.3 and 6.3.0 ? do you have any reference for the compatibility versions with your plugin ?

**Comment by christocracy** [comment]
You are **strongly** advised to upgrade your `cordova-android` to `7.0.0`.    `cordova-android@7.0.0` was released on December 2017.  Phonegap build supports it.

For `cordova-android < 7.0.0`, you must use plugin version `2.11.0`.  That would be a bad idea.
