### ISSUE TITLE
Unfortunately App Stopped working

### ISSUE THREAD

**Issue by kkommuri** [transistorsoft/cordova-background-geolocation-lt#78]
Hi Chris,

We created a sample android app and able to start the service, we set StoponTerminate=true assuming  the background service will be stopped when we kill the app. 
If we relaunch the app without calling stop() api before we kill the app, and try to start the service
it throws out "Unfortunately app stopped working"
Even tried calling Stop() api before calling Start() api still no luck.

    // Get a reference to the plugin.
              var bgGeo = window.BackgroundGeolocation;

              /**
            * This callback will be executed every time a geolocation is recorded in the background.
            */

              //Make sure to get at least one GPS coordinate in the foreground before starting background services
              //to overcome the Unfortunately the app stopeed working when we restart the service without stopping it.
              //window.BackgroundGeolocation.getCurrentPosition();
              window.BackgroundGeolocation.stop(function () { }, function (error) {
                  alert('unable to stop the previous start due to errorCode:' + error)
              });

              // BackgroundGeoLocation is highly configurable. See platform specific configuration options 
              window.BackgroundGeolocation.configure(callbackFn, failureFn, {
                  // Geolocation config
                  //stationaryRadius: 3,
                  //disableElasticity: true, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
             
                  //activityType: 'AutomotiveNavigation',
                  //notificationTitle: 'Chris BG Geolocation',
                  //notificationText: 'done by kkommuri',
                  // Application config
            

                  // Common Settings
                  //url: 'http://54.85.209.125/TransistorsoftPostService/api/GeoLocation/SaveGeoLocation',
                  //method: 'POST',
                  //batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                  //autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
                  //maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
                  //headers: {
                  //    "X-FOO": "bar"
                  //},
                  stopOnTerminate: $scope.StopOnTerminate.checked,// true,
                  stopTimeout:$scope.StopTimeOut,// 3,
                  //activityRecognitionInterval: 10000,
                  debug:$scope.Debug.checked,// true, // <-- enable this hear sounds for background-geolocation life-cycle.
                  desiredAccuracy: $scope.SelectedAccuracy.dial_code,// 0,
                  distanceFilter:$scope.DistanceFilter,// 30,

                  //android settings
                  locationUpdateInterval:$scope.LocationUpdateInterval * 1000,//5000,
                  fastestLocationUpdateInterval:$scope.FatestLocationUpdateInterval *1000,// 1000,
                  //triggerActivities: 'in_vehicle',
                  activityRecognitionInterval:$scope.activityRecognitionInterval *1000,// 0,
                  minimumActivityRecognitionConfidence:$scope.minimumActivityRecognitionConfidence,
                  forceReloadOnMotionChange: false,
                  forceReloadOnLocationChange: false,
                  forceReloadOnGeofence: false,
                  startOnBoot: false,
                  foregroundService: false
              });

         

              // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app. 
              window.BackgroundGeolocation.start(successfn, failureFn);

**Comment by Glenndejaeger** [comment]
We have exactly the same issue. We've set stopOnTerminate to true but when we force close the app (on Android), an error is thrown telling that the app has stopped.
If we manually call the stop() function and then close the app, no error is thrown. So it seems that stopOnTerminate is not working as intended.

@christocracy Could you explain why this issues was closed? Is there a solution?

**Comment by christocracy** [comment]
Because customers like yourself aren't supposed to use the free version of the repo.

This is the "Lite" (ie: `-lt`) repo.  And without logs, there's no way to say this is "exactly the same issue".  However, I did experience something similar a few days ago and posted a fix in the **Premium** repo, which you should be using.

**Comment by christocracy** [comment]
In addition, this issue dates back to February.  Android has been **completely** refactored since then so there's 0% chance this issue is relevant to current behaviour.

**Comment by Glenndejaeger** [comment]
Luckily I am using the Premium version. But I just stumbled upon this issue here, so I added a comment. I'll check the fix in the Premium repo!

**Comment by christocracy** [comment]
Furthermore, the title "Unfortunately App Stopped working" is about as useful as telling the mechanic "My car stopped working".  That could happen from having no gas, starter coil is bured-out, bad spark plugs, battery dead...
