### ISSUE TITLE
Plugin not working with cordova cli-8.0.0 on phonegap build

### ISSUE THREAD

**Issue by umasankarm** [transistorsoft/cordova-background-geolocation-lt#780]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS or Android
* OS version: android 7.1.1
* Device manufacturer / model: lenova k8 plus
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): (Android phonegap : 7.0.0 / iOS : 4.5.5 / windows : 5.0.0)
* Plugin config : default config

## Expected Behavior
window.BackgroundGeolocation object not initialized  

## Actual Behavior
window.BackgroundGeolocation object is undefined

## Steps to Reproduce

1. zipped the source file 
2. upload the zip file to adobe phonegap build site

## Context
Trying to integrate plugin in my application

## Debug logs
Build Date: 2018-08-31 09:38:18 +0000 
above values only available in log

**Comment by christocracy** [comment]
You know, you can *edit* an issue??  Even change the title.  

This all could have been done upon your original issue, now you’ve created 3 issues.
