### ISSUE TITLE
stopOnTermiante:false

### ISSUE THREAD

**Issue by yomencity** [transistorsoft/cordova-background-geolocation-lt#781]
## Your Environment
* Plugin version: 2.13.1
* Platform: Android
* OS version: 8.0.0(Oreo)
* Device manufacturer / model: samsung galaxy s6
* Cordova version (`cordova -v`): 8.0.0

stopOnTerminate does not work well. I expect location background service not to be terminated when I terminate app.
However when I terminate app , the background location service is terminated too.
And Background service is activated again after a while.
And when I press hard my app icon, background location service is activated immediately.
      
  document.addEventListener("deviceready", onDeviceReady);                
function onDeviceReady() {
    // Get a reference to the plugin.
    var bgGeo = window.BackgroundGeolocation;

    //This callback will be executed every time a geolocation is recorded in the background.
    var callbackFn = function(location) {
        var coords = location.coords;
        var lat    = coords.latitude;
        var lng    = coords.longitude;
        console.log('- Location: ', JSON.stringify(location));        
    };

    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
    var failureFn = function(errorCode) {
        alert(JSON.stringify(errorCode));
        console.warn('- BackgroundGeoLocation error: ', errorCode);
    }

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);
    // Fired whenever state changes from moving->stationary or vice-versa.
    // Fired whenever an HTTP response is received from your server.
    bgGeo.on('motionchange', function(isMoving) {
      console.log('- onMotionChange: ', isMoving);
    });
    // Fired whenever a geofence transition occurs.
    bgGeo.on('geofence', function(geofence) {
      console.log('- onGeofence: ', geofence.identifier, geofence.location);
    });    
    bgGeo.on('http', function(response) {
      console.log('http success: ', response.responseText);
    }, function(response) {
      console.log('http failure: ', response.status);
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.ready({
        // Geolocation config
          reset: true,
          logLevel: bgGeo.LOG_LEVEL_VERBOSE,        
        desiredAccuracy: 0,
        distanceFilter: 50,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        foregroundService:true,
        // Application config
        debug: true,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        // HTTP / SQLite config
        url: url+'/localdata',
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3,
        headers: {  // <-- Optional HTTP headers
            "X-FOO": "bar"
        },
        params: {   // <-- Optional HTTP params
             use:'myid'
        }
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        if (!state.enabled) {
            bgGeo.start();
        }        
    });
}

**Comment by laychar** [comment]
I have the similar problem and code except foregroundSevice. I guess it is due to oreo OS version. But I can not ALWAYS get "location service activated" icon which resemple push icon. Sometimes the  icon does not appear after I terminate app

**Comment by laychar** [comment]
But It is very long. Is that Ok?
And can I ask something?
What the words (I develop on a pixel @8.1.0) means?

**Comment by christocracy** [comment]
Github allows you to easily drag/drop file attachments.

>What the words (I develop on a pixel @8.1.0) means?

It means I primarily develop on Oreo (ie Android 8.1 0).

**Comment by laychar** [comment]
Thanks! Please wait for a while. I am going back to my office.

**Comment by laychar** [comment]
[adblogcat.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2344082/adblogcat.txt)
Sorry I am late. Here It is.

**Comment by christocracy** [comment]
The plugin's service is being killed by the system right after a [`lowmemorykiller`](https://stackoverflow.com/questions/45630538/low-memory-killer-error-message-within-cordova-android-app) log:

```
09-03 12:01:54.181   342   342 D CordovaActivity: CordovaActivity.onDestroy()
.
.
.
09-03 12:01:54.269  2981  4392 I WindowManager: WIN DEATH: Window{f1252cb u0 com.example.yomenw/com.example.yomenw.MainActivity}
.
.
.
09-03 12:01:54.270  2981  3707 I ActivityManager: Process com.example.yomenw (pid 342) has died: prcp FGS (95,601)
.
.
.
09-03 12:01:54.273  2462  2462 E lowmemorykiller: Error writing /proc/10363/oom_score_adj; errno=22
.
09-03 12:01:54.276  2981  3707 W ActivityManager: Scheduling restart of crashed service com.example.yomenw/com.transistorsoft.locationmanager.BackgroundGeolocationService in 20510848ms
```

At `12:02:02` (~8 seconds later), the system *does indeed* **restart the service**:

```
09-03 12:02:02.388 10763 10763 I TSLocationManager: 
09-03 12:02:02.388 10763 10763 I TSLocationManager: ╔═════════════════════════════════════════════
09-03 12:02:02.388 10763 10763 I TSLocationManager: ║ License Validation Failure
09-03 12:02:02.388 10763 10763 I TSLocationManager: ╠═════════════════════════════════════════════
09-03 12:02:02.388 10763 10763 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
09-03 12:02:02.451 10763 10769 I zygote64: Do partial code cache collection, code=123KB, data=81KB
09-03 12:02:02.451 10763 10769 I zygote64: After code cache collection, code=123KB, data=81KB
09-03 12:02:02.451 10763 10769 I zygote64: Increasing code cache capacity to 512KB
09-03 12:02:02.465 10763 10763 I TSLocationManager: [c.t.l.adapter.TSConfig print] 
09-03 12:02:02.465 10763 10763 I TSLocationManager: ╔═════════════════════════════════════════════
09-03 12:02:02.465 10763 10763 I TSLocationManager: ║ TSLocationManager version: 2.12.22 (278)
09-03 12:02:02.465 10763 10763 I TSLocationManager: ╠═════════════════════════════════════════════
09-03 12:02:02.465 10763 10763 I TSLocationManager: {
.
.
.
09-03 12:02:02.465 10763 10763 I TSLocationManager: }
```

**Comment by laychar** [comment]
the system does indeed restart the service: 
 Maybe It is because I turn off and on app.
then, my problem occur because of memory deficiency? 
how to be immune to lowmemory killer? I already make foregroundService be true.

**Comment by christocracy** [comment]
>then, my problem occur because of memory deficiency?
 
I have no idea.  

This is most likely a Samsung-specific issue.  However, I test upon 2 Samsung devices and I don't experience this:
- Samsung-SM G930A @ 6.0.1
- Samsung-SM-J320A @ 6.0.1

>how to be immune to lowmemory killer?

I doubt you can.  I have no idea about this.

However, the plugin service *is indeed* being restarted by the System, as promised in the logs.

**Comment by laychar** [comment]
Your plugin works well with my another smartphone. -galaxy J7 @6.0.1.
location service is indeed be restarted as you told. However It is very changeable. 
For example sometimes plugin service is restarted right after I terminate app. At another time plugin service is restarted after a while. And at othertimes plugin service is not restarted.

**Comment by christocracy** [comment]
It is the OS terminating the service.  I cannot do anything about this.  I suggest you google "samsung android foreground service terminated".

**Comment by laychar** [comment]
I got it, thanks. 
then what is the reason that cause this problem?  OS or manufacturer?  or both?

**Comment by christocracy** [comment]
Samsung's custom flavour of Android.

**Comment by laychar** [comment]
I got it ,thank you.
