### ISSUE TITLE
App crashes when built in release mode, ok in debug

### ISSUE THREAD

**Issue by locsim** [transistorsoft/cordova-background-geolocation-lt#783]
<My App crashes immediately after start. The same app build in debug mode runs ok.>

## Your Environment
* Plugin version: 2.13.1
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Oneplus 5T
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin config

{
    "activityRecognitionInterval": 1000,
    "allowIdenticalLocations": false,
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": true,
    "deferTime": 0,
    "desiredAccuracy": 0,
    "desiredOdometerAccuracy": 100,
    "disableElasticity": false,
    "disableStopDetection": false,
    "distanceFilter": 30,
    "elasticityMultiplier": 1,
    "enableHeadless": false,
    "extras": {},
    "fastestLocationUpdateInterval": 1000,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": false,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {},
    "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
    "heartbeatInterval": 60,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": false,
    "locationTemplate": "",
    "locationTimeout": 60,
    "locationUpdateInterval": 30000,
    "locationsOrderDirection": "ASC",
    "logLevel": 5,
    "logMaxDays": 3,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": -1,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 50,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "en service",
    "notificationTitle": "Ootigo",
    "params": {
        "code_emetteur": "XXXXXX",
        "app_version": "2.6.5"
    },
    "persist": true,
    "schedule": [],
    "startOnBoot": false,
    "stationaryRadius": 25,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": true,
    "stopTimeout": 0,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "https:xxxxxxxxxxxxxxx.php",
    "enabled": false,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 0,
    "isFirstBoot": true
}

## Expected Behavior
App behave in release build the same way as in debug build.

## Actual Behavior
App crashes every time it is launched.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
- Android: $ adb logcat
09-07 19:20:54.419 19948 19948 D AndroidRuntime: Shutting down VM
09-07 19:20:54.419 19948 19948 E AndroidRuntime: FATAL EXCEPTION: main
09-07 19:20:54.419 19948 19948 E AndroidRuntime: Process: com.locsim.ootigo2, PID: 19948
09-07 19:20:54.419 19948 19948 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
09-07 19:20:54.419 19948 19948 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1867)
09-07 19:20:54.419 19948 19948 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-07 19:20:54.419 19948 19948 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-07 19:20:54.419 19948 19948 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6753)
09-07 19:20:54.419 19948 19948 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-07 19:20:54.419 19948 19948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
09-07 19:20:54.419 19948 19948 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
-->

App wont crash when bgGeo is not started in the ready method.

**Comment by locsim** [comment]
Hi Chris,
Thank you your quick reply. You are right, it was a license key related issue: config.xml was ok, but android.json contained  "YOUR_LICENSE_KEY" instead of the key. I can't figure out how I could create this situation.
Anyway, once again, THANK YOU!
(btw, your wiki refers to AndroidManifest.xml, sounds like the right name is now android.json).

**Comment by christocracy** [comment]
you create that situation when you do this:
```
$ cordova plugin remove cordova-background-geolocation
```

If you want to avoid this situation, append `--nosave` when you remove the plugin.
