### ISSUE TITLE
debug notification don't disappear

### ISSUE THREAD

**Issue by laychar** [transistorsoft/cordova-background-geolocation-lt#784]
## Your Environment
* Plugin version: 2.13.1
* Platform: Android
* OS version: 6.0.0
* Device manufacturer / model: SAMSUNG/galaxy J7
* Cordova version (`cordova -v`): 8.0.0

## Expected Behavior

I want the debug notification to disappear
## Actual Behavior

But It doesn't disappear.
Following is my configure.
    bgGeo.ready({
        reset: true,
        debug:false,
        desiredAccuracy: 0,
        distanceFilter: 200,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 60000,
        stopTimeout: 5,
        foregroundService:true,
        // Application config
        stopOnTerminate: false,
        startOnBoot: true,
        // HTTP / SQLite config
        url: url+'/updatelocal',
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3,
        headers: {  // <-- Optional HTTP headers
            "X-FOO": "bar"
        },
        params: {   // <-- Optional HTTP params
             id:userid
        }
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        if (!state.enabled) {
            bgGeo.start();
        }        
    });
I don't know what the problem is.

**Comment by christocracy** [comment]
What is an Android “debug notification”.

**Comment by laychar** [comment]
I mean that the debug notification is
the icon which resemble push icon.
I can get the icon when I make debug be true.

2018년 9월 9일 (일) 오전 8:28, Chris Scott <notifications@github.com>님이 작성:

**Comment by christocracy** [comment]
That’s not a “debug” notification, that’s the *required* persistent notification of an Android foreground service, which cannot be disabled on Android 8+.

This is required by the OS.  You cannot hide it.

**Comment by christocracy** [comment]
If you want to disable it on Android < 8.0, configure foregroundService; false.

:warning: this will make your app much more likely to be terminated when device is under memory pressure from other apps.

Tracking is much more consistent if you don’t disable this.  And on Android 8+, you *cannot* disable it.

**Comment by laychar** [comment]
I got it. Thanks!

2018년 9월 9일 (일) 오전 10:15, Chris Scott <notifications@github.com>님이 작성:

**Comment by christocracy** [comment]
Version 3 now only shows foreground-service when in *moving* state.
