### ISSUE TITLE
I found solution about #781

### ISSUE THREAD

**Issue by laychar** [transistorsoft/cordova-background-geolocation-lt#786]
I had the problem that when I terminate app, the location service is terminated too..
I tried to remove cordova-plugin-firebase. After that my problem is solved!!
But I needed  that plugin too. So I changed that plugin version. @1.0.5 -> 1.1.4. 
After that my all-problem is solved.

**Comment by laychar** [comment]
+) I am reaaaaaaally reeeaaaaalllly happy!!

**Comment by christocracy** [comment]
Why are you not commenting at issue #781 then?

**Comment by laychar** [comment]
That is closed.  I think you cannot get mail.  I was very excited. sorry...

**Comment by christocracy** [comment]
I do get mail for every comment posted, regardless.  Go put your comment there for others in the future.  I'm deleting this thread.
