### ISSUE TITLE
bgGeo is undefined

### ISSUE THREAD

**Issue by DigitalMystery** [transistorsoft/cordova-background-geolocation-lt#787]
## Your Environment
* Plugin version: 2.13.1
* Platform: iOS and Android
* OS version: iOS: 11.4.1 - Android 6.0.1
* Device manufacturer / model: Apple 6s & Galaxy s5
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
Android: 7.1.0
iOS: 4.5.5
* Plugin config

## Expected Behavior

Should get a reference to the BackgroundGeolocation

## Actual Behavior

Not getting reference to BackgroundGeolocation and receiving error:
TypeError: undefined is not an object (evaluating 'this.bgGeo')

## Steps to Reproduce

1.   In constructor of a page (several layers deep) I get a reference to the plugin.  Above this I have instantiated bgGeo an any.  Below is in my init.
```
this.platform.ready()
    .then(() => {
      this.bgGeo = (<any>window).BackgroundGeolocation;
     this.setUpMapRoute();
    });
```

2. The call to setUpMapRoute then configures and starts the service, but this.bgGeo is not defined
```
this.bgGeo.configure({
        desiredAccuracy: 0,
        stationaryRadius: 20,
        distanceFilter: 18,
        activityRecognitionInterval: 10000,
        stopTimeout: 10,
        autoSync: false,
        maxDaysToPersist: 2,
        stopOnTerminate: true,
        heartbeatInterval: 60,
        preventSuspend: true,
        locationAuthorizationRequest: "WhenInUse",
        locationAuthorizationAlert: {
          //titleWhenNotEnabled: "Location Services are disabled",
          titleWhenOff: "Location Services are off",
          instructions:
            "You must enable 'When In Use' in location-services, to use certain features in the app.",
          cancelButton: "Cancel",
          settingsButton: "Settings"
        }
        //logLevel: 5
      }, function (state) {
        if (!state.enabled) {
          this.bgGeo.start();
        }
      });
      this.bgGeo.on("location", this.callbackFn.bind(this), this.failureFn.bind(this));
```

## Context

So I have been using this plugin for several years now, but updating all my platforms.  I have been on android 6.4 and a lower iOS which have worked perfectly fine.  However I cannot seem to get this to work with just updating the platform.  Even if I lower it back down everything works again.  I have worked thru all the issues with every plugin to upgrade except this one.  Any advice?

**Comment by christocracy** [comment]
When in doubt:
- remove / re-add plugin
- remove / re-add platforms

```
$ rm -rf node_modules
$ npm install
```

**Comment by christocracy** [comment]
> THREAD WARNING: ['BackgroundGeolocation'] took '103.371826' ms. Plugin should use a 

Ignore.  The  plugin performs most of its operations on a background thread except for a few methods which are executed only once for the lifetime of the app (eg: `#ready`).

This warning is expected.

It also shows the plugin is alive and correctly installed.

**Comment by DigitalMystery** [comment]
Ok, so I uninstalled the app on the device and then did a fresh install last night (which I had also done before just not after removing and adding back the node modules).  Everything was happy after that.  Maybe you should add the following steps to help anybody else.  Unless you have them someplace and I just missed them (only found the add remove plugin part before creating this thread).  I can add them if you are accepting pull requests, but I assume this is an easy enough one lol.  Thanks again!

> $ rm -rf node_modules
> $ npm install

> uninstall app from device
> install app on device

**Comment by christocracy** [comment]
The problem is likely you had an app built pre `cordova-android@7.0.0`.  This is one-time pain for a small subset of people.  This isn't related specifically to the plugin.  This is due to your npm dependencies and cordova.
