### ISSUE TITLE
SOLVED: Custom BackgroundGeolocationHeadlessTask.java

### ISSUE THREAD

**Issue by staryja4** [transistorsoft/cordova-background-geolocation-lt#788]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.4.0
* Plugin config
This in platform
```
<resource-file
src="resources/android/BackgroundGeolocationHeadlessTask.java"
target="app/src/main/java/com/transistorsoft/cordova/bggeo/BackgroundGeolocationHeadlessTask.java" />
```
and
```
<plugin name="cordova-background-geolocation-lt" spec="^2.11.0">
<variable name="LICENSE" value="YOUR_LICENSE_KEY" />
<variable name="GOOGLE_API_VERSION" value="11.8.0" />
<variable name="APPCOMPAT_VERSION" value="27.0.0" />
<variable name="BACKGROUND_MODE_LOCATION" value="&lt;string&gt;location&lt;/string&gt;" />
<variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Always use is required for constant background location-tracking" />
<variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
<variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
<variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
</plugin>
```

## Expected Behavior

Should be able to implement own business logic for Android Headless Mode. 

## Actual Behavior

My BackgroundGeolocationHeadlessTask.java is not part of a build. I can't even find BackgroundGeolocationHeadlessTask.java file even if I don't try to replace it with my custom one.

<img width="1440" alt="screen shot 2018-09-13 at 10 25 26" src="https://user-images.githubusercontent.com/2436794/45477158-3719e000-b741-11e8-9034-7d834bf5b78f.png">

You can see missing BackgroundGeolocationHeadlessTask.java file and Logcat at the bottom of the screen.

## Steps to Reproduce

1. My implementation
```
  startBgLocationIfPlatformReady(locationSharing: LocationSharingDto) {
    this.platform.ready().then(() => {
      this.setBgLocation(locationSharing);
    }).catch(err => this.errorProvider.present(err));
  }

  private setBgLocation(locationSharing: LocationSharingDto) {
    const bgGeo = (window as any).BackgroundGeolocation;

    const callbackFn = (location) => {
      console.log('- Location: ', JSON.stringify(location));
      this.addLocationSharingPoints(locationSharing, [location]).subscribe(
        res => console.log(res),
        err => this.tempAction(location)
      );
    };

    const failureFn = (errorCode) => {
      console.warn('- BackgroundGeoLocation error: ', errorCode);
    };

    bgGeo.on('location', callbackFn, failureFn);
    bgGeo.on('motionchange', (isMoving) => {
      console.log('- onMotionChange: ', isMoving);
    });
    bgGeo.on('heartbeat', (params) => {
      const diff = new Date(locationSharing.finishOn).getTime() - new Date().getTime();
      if (diff <= 60000) {
        bgGeo.stop();
      }
    });

    bgGeo.ready({
      desiredAccuracy: 10,
      distanceFilter: 20,
      stationaryRadius: 20,
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Yo, location-services not enabled',
        titleWhenOff: 'Yo, location-services OFF',
        instructions: 'You must enable "Always" in location-services, buddy',
        cancelButton: 'Cancel',
        settingsButton: 'Settings'
      },
      activityRecognitionInterval: 60000,
      stopTimeout: 5,
      debug: true,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: false,
      autoSync: true,
      maxDaysToPersist: 3,
      heartbeatInterval: 60,
      preventSuspend: true,
      foregroundService: true,
    }, (state) => {
        if (!state.enabled) {
          bgGeo.start();
        }
    });
  }
```
2. I call function startBgLocationIfPlatformReady() after click on a button

**Comment by Steffaan** [comment]
As stated in the [changelog](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#2101---2018-02-04), it's correct that your missing `BackgroundGeolocationHeadlessTask.java` in your project.

Please [follow the guide](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode) which explains all necessary steps very clear. 

Since you already added `enableHeadless: true` follow the following steps:
[Step 2: BackgroundGeolocationHeadlessTask.java](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode#step-2--backgroundgeolocationheadlesstaskjava)
[Step 3: Copying BackgroundGeolocationHeadlessTask.java](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode#step-3--copying-backgroundgeolocationheadlesstaskjava)

**Comment by staryja4** [comment]
> As stated in the [changelog](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#2101---2018-02-04), it's correct that your missing `BackgroundGeolocationHeadlessTask.java` in your project.
> 
> Please [follow the guide](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode) which explains all necessary steps very clear.
> 
> Since you already added `enableHeadless: true` follow the following steps:
> [Step 2: BackgroundGeolocationHeadlessTask.java](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode#step-2--backgroundgeolocationheadlesstaskjava)
> [Step 3: Copying BackgroundGeolocationHeadlessTask.java](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode#step-3--copying-backgroundgeolocationheadlesstaskjava)

Hi Steffaan,

Yeah, that's what I've already done. Created my custom file and then copied it to config:
```
<resource-file
src="resources/android/BackgroundGeolocationHeadlessTask.java"
target="app/src/main/java/com/transistorsoft/cordova/bggeo/BackgroundGeolocationHeadlessTask.java" />
```

**Comment by Steffaan** [comment]
Make sure your `src` path is correct.

Also, did you build / run your app at least 1 time after adding the `resource-file` in your config?

**Comment by staryja4** [comment]
`src` path should be correct as I have there icons and other files too.

This is how my platform tag config looks like:
```
<platform name="android">
        <allow-intent href="market:*" />
        <resource-file src="resources/android/BackgroundGeolocationHeadlessTask.java" target="app/src/main/java/com/transistorsoft/cordova/bggeo/BackgroundGeolocationHeadlessTask.java" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        <resource-file src="google-services.json" target="google-services.json" />
    </platform>
```

And yeah I made build of my app many times.

Do you have any idea what could be wrong? Thanks!

**Comment by christocracy** [comment]
You're using `cordova-android@6.4.0`.  The Wiki instructions are for `cordova-android >= 7.0.0`

`cordova-android@7.0.0` changed the directory structure of the generated Android app to resemble that of a pure native Android app, with `/app` folder.

Simply observe the file structure of your `platforms/android` folder and locate the `com/transistorsoft/bggeo` folder.  Adjust the `<resource-file>` `src` attribute accordingly.

**Comment by staryja4** [comment]
Cool, it helped! Thank you so much Chris!
