### ISSUE TITLE
iOS Background Location Tracking sometimes stops when Aggressive Monitoring is engaged

### ISSUE THREAD

**Issue by skourem** [transistorsoft/cordova-background-geolocation-lt#79]
Hi Chris,

I am currently testing your iOS free version (v.1.2) using the example code. It works great but usually after continuous use (1-2 days) it suddenly stops on Exit Stationary (i.e. when aggressive monitoring is engaged). I have also tested your bump version 1.3 and the same issue was reproduced. I prefer v1.2 because it returns the activity type whereas 1.2 does not (fyi, it returns 'unknown').

Could you pleased advise on the above?

Thanks,
Stelios

**Comment by christocracy** [comment]
Thanks, I'll have a look.

**Comment by christocracy** [comment]
Are you still having issues?

**Comment by skourem** [comment]
I installed your new master version today. I will let you know in 2-3 days. Thanks.

**Comment by skourem** [comment]
The issue re: the activity types is resolved. However, I still have issues with the app being suspended after exit stationary (v. 1.5.1)

**Comment by christocracy** [comment]
Update please.

**Comment by christocracy** [comment]
Closing due to lack of response
