### ISSUE TITLE
How to reset odometer everyday ?

### ISSUE THREAD

**Issue by shubham13jain** [transistorsoft/cordova-background-geolocation-lt#791]
## Your Environment
* Plugin version: 2.13.1
* Platform: iOS or Android
* OS version: 8.1.0
* Device manufacturer / model:
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin config

We are using Scheduler in plugin And Scheduler runs between 10 AM to 10 PM.  So, Basically, I want to reset the odometer everyday event without user's opening the application.  how can we reset the odometer everyday at 10 AM.

**Comment by shubham13jain** [comment]
@christocracy Will the above mentioned work even if the app is closed ??

**Comment by christocracy** [comment]
On Android, no.  You’ll have to make a HeadlessTask and do it with the plugin’s Android native API.

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode

Or use forceReloadInSchedule: true

**Comment by shubham13jain** [comment]
> On Android, no. You’ll have to make a HeadlessTask and do it with the plugin’s Android native API.
> 
> https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode
> 
> Or use forceReloadInSchedule: true

What about the ios ?

**Comment by christocracy** [comment]
>On Android, no

Therefore: “iOS yes”.

**Comment by shubham13jain** [comment]
Thanks @christocracy. I have implemented the above mentioned functionality in Android, But How to reset odometer in ios when app is in terminated state.

**Comment by christocracy** [comment]
>But How to reset odometer in ios when app is in terminated state.

When your app *re-awakens* from termination (due to a schedule event).
