### ISSUE TITLE
Strange behaviour with Headless Task

### ISSUE THREAD

**Issue by nicolagerotto** [transistorsoft/cordova-background-geolocation-lt#792]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: 7.0.0
* Device manufacturer / model: Lenovo K6
* Cordova version (`cordova -v`):  8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin config
`{
     desiredAccuracy: 0,
     distanceFilter: 5,
     debug: false,
     logLevel: 5,
     disableElasticity: true,
     heartbeatInterval: 60,
     enableHeadless: true,
     foregroundService: true,
     notificationColor: "#006633",
     notificationSmallIcon: 'drawable/mappointer_small',
     notificationLargeIcon: "",
     notificationPriority: 2,
     notificationText: "Test",
     notificationTitle: "",
     startOnBoot: true,
     stopOnTerminate: false
}`
## Expected Behavior

When I terminate my app, I expect that Headless Task starts immediatly, as with other devices. 

## Actual Behavior

With Lenovo K6, I terminate the app, I see on the logs the event "on Destroy" but after nothing happens. 
On MotoG5 plus, Huawei Mate 10pro and many other devices, the plugins works great. In others, like Lenovo K6, Honor 8 or OnePlus 6, I have this problem.

So I tried adding heartbeatInterval: 60 on the plugins config, and now every ~60 seconds (more or less) I see that Headless Task starts; you can see the logs which I enclose below (event terminated: 16:26:16.863, headlesstask first entrance: 16:27:34.752). 

The question is: why on some devices I see that headless task starts immediatly and in others don't? Is heartbeat interval necessary for this? 
This is a problem for me, because I can't wait ~60 seconds until the task starts. 

Eventually, is possible to reduce the heartbeatInterval? 

Thank you. 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

09-20 16:26:16.863 27047 27047 I TSLocationManager: CDVBackgroundGeolocation#onDestoy
09-20 16:26:16.873 27047 27047 I TSLocationManager: [c.t.l.a.BackgroundGeolocation onActivityDestroy]
09-20 16:26:16.873 27047 27047 I TSLocationManager: ╔═════════════════════════════════════════════
09-20 16:26:16.873 27047 27047 I TSLocationManager: ║ MainActivity was destroyed
09-20 16:26:16.873 27047 27047 I TSLocationManager: ╠═════════════════════════════════════════════
09-20 16:26:16.873 27047 27047 I TSLocationManager: ╟─ stopOnTerminate: false
09-20 16:26:16.873 27047 27047 I TSLocationManager: ╟─ enabled: true
09-20 16:27:34.752 27189 27446 I TSLocationManager:
09-20 16:27:34.752 27189 27446 I TSLocationManager: ╔═════════════════════════════════════════════
09-20 16:27:34.752 27189 27446 I TSLocationManager: ║ License Validation Failure
09-20 16:27:34.752 27189 27446 I TSLocationManager: ╠═════════════════════════════════════════════
09-20 16:27:34.752 27189 27446 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
09-20 16:27:34.865 27189 27446 I TSLocationManager: [c.t.l.adapter.TSConfig print]
09-20 16:27:34.865 27189 27446 I TSLocationManager: ╔═════════════════════════════════════════════
09-20 16:27:34.865 27189 27446 I TSLocationManager: ║ TSLocationManager version: 2.12.14 (270)
09-20 16:27:34.865 27189 27446 I TSLocationManager: ╠═════════════════════════════════════════════
09-20 16:27:35.192 27189 27446 E TSLocationManager:   ‼️  Failed to get last location: com.google.android.gms.tasks.zzu@a7aad35
09-20 16:27:35.213 27189 27446 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
09-20 16:27:35.319 27189 27189 D TSLocationManager: [c.t.c.bggeo.HeadlessJobService onStartJob] 💀  event: heartbeat

**Comment by nicolagerotto** [comment]
Hi,

any update? We still can't find a solution

**Comment by christocracy** [comment]
On your Lenovo device, test this:
- Start a music player (eg: Play Music).  Start a song.
- Terminate the player.  Does the music keep playing or does it stop?

**Comment by nicolagerotto** [comment]
When I terminate the player, Lenovo stops playing music. 
Instead if I try with my Moto G5plus, even if I terminate the app continues to play.

What can I do?

**Comment by christocracy** [comment]
You can do nothing.  Lenovo's flavour of Android is terminating foreground-services when the MainActivity is terminated.  That's not supposed to happen.

Imagine how annoying that must be for users listening to music / podcast / audio-books.

**Comment by christocracy** [comment]
Try searching "Lenovo music stops".

See [this](https://forums.lenovo.com/t5/P2-P2a42-Smartphones/Online-Radios-does-not-run-correctly-after-Nougat-update-P2a42/m-p/3654107/highlight/true#M3440)
