### ISSUE TITLE
IOS app crashing

### ISSUE THREAD

**Issue by jumamfa** [transistorsoft/cordova-background-geolocation-lt#795]
## Your Environment
* Plugin version: 2.13.1
* Platform: iOS or Android
* OS version: IOS 12 
* Device manufacturer / model:  iPhone 7
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios 4.5.5
config :
            reset: true,
            desiredAccuracy: 0,
            distanceFilter: 10
            stopTimeout:1,
            foregroundService: true,
            stopOnTerminate: false,
            heartbeatInterval: 60,
            autoSync: true,
            autoSyncThreshold: 0,
            debug: false,
            logLevel: window.BackgroundGeolocation.LOG_LEVEL_NONE

## Expected Behavior
App continues to run in the background

## Actual Behavior
Runs for quite a while, tracking correctly but sometimes the app crashes and restarts, no reason for this in device logs in xcode

## Steps to Reproduce
open app put in to the background seems to work correctly for 6-12 hours (sometimes a few days) before eventually crashing

## Context
Building an automatic mileage tracker so our end users can log their mileage without having to do anything other than start the app.

**Comment by jumamfa** [comment]
Found a crash in the device logs

Date/Time:       2018-09-13 17:45:46 +0100
OS Version:      iPhone OS 12.0 (Build 16A366)
Architecture:    arm64
Report Version:  26

Data Source:     KPerf Lightweight PET
Kernel Cache:    0xffffffe000000000 87D017F1-4B23-5B8F-FF31-712EDB58D031
Reason:          UIKit-runloop-MyAccountants: timeout 2105ms

Command:         MyAccountants
Path:            /private/var/containers/Bundle/Application/8F97D6DC-DAFA-469C-8D79-657535243192/MyAccountants.app/MyAccountants
Identifier:      uk.co.myfirmsapp.one.accountants
Version:         4.2.95 (4.2.95)
Parent:          launchd [1]
PID:             352

Duration:        2.10s
Steps:           42 (50ms sampling interval)

Hardware model:  N71mAP
Active cpus:     2

**Comment by christocracy** [comment]
Logs, please.

**Comment by jumamfa** [comment]
{
  "build" : "iPhone OS 12.0 (16A366)",
  "product" : "iPhone8,1",
  "kernel" : "Darwin Kernel Version 18.0.0: Tue Aug 14 22:07:19 PDT 2018; root:xnu-4903.202.2~1\/RELEASE_ARM64_S8000",
  "tuning" : {

  },
  "incident" : "519EECB9-3E1C-40F7-825F-C814AB5343B5",
  "crashReporterKey" : "a891bfa01a13a1deaeb185a047880dd261b9a961",
  "date" : "2018-09-14 08:11:23.04 +0100",
  "reason" : "Power assertion timeout for \"com.apple.locationd.LocationHarvester.106802618(Submit)\".  Simply releasing it now.\nBacktrace for power assertion: pid 59 (0x21fd35ad8 0x104d330b4 0x1047f61fc 0x104d6e094 0x104caf40c 0x1047f0f88 0x1047f6680 0x1047f0dc0 0x104aaac78 0x104aaaaf4 0x21ceb36c8 0x21ceb4484 0x21ce5bc18 0x21ce5c794 0x21ce64f00 0x21d0960f0 0x21d098d00)",
  "frontmostPids" : [
    52
  ],
  "exception" : "0xdeaffeed",
  "absoluteTime" : 162876880424,
  "thermalData" : {"sensors":[0],"thermalLevel":0},
  "memoryStatus" : {"compressorSize":11689,"compressions":73953,"decompressions":35005,"busyBufferCount":0,"pageSize":16384,"memoryPressure":false,"memoryPages":{"active":41789,"throttled":0,"fileBacked":52769,"wired":12777,"purgeable":658,"inactive":37382,"free":13938,"speculative":4631}},
  "processByPid" : {
    "0" : {"pid":0,"residentMemoryBytes":13778944,"timesDidThrottle":0,"systemTimeTask":0,"pageIns":0,"pageFaults":1498,"userTimeTask":12186.270425916,"procname":"kernel_task","copyOnWriteFaults":0,"threadById":{"356":{"continuation":[0,68842532196],"userTime":0.0034999580000000001,"systemTime":0,"id":356,"basePriority":81,"name":"AppleCBTL1610","user_usec":3499,"schedPriority":81,"system_usec":0,"state":["TH_WAIT","TH_UNINT"],"waitEvent":[1,8094287857900426991]},"470":{"continuation":[0,68841307200],"userTime":1.333e-06,"systemTime":0,"id":470,"basePriority":81,"user_usec":1,"system_usec":0,"schedPriority":81,"state":["TH_WAIT","TH_UNINT"],"waitEvent":[0,68843678040]},"259":{"continuation":[0,68842532196],"userTime":0.022564375000000001,"systemTime":0,"id":259,"basePriority":81,"name":"AppleM2ScalerCSCDriver","user_usec":22564,"schedPriority":81,"system_usec":0,"state":["TH_WAIT","TH_UNINT"],"waitEvent":[1,8094287857900550863]},"348":{"continuation":[0,68842532196],"userTime":32.844214915999999,"systemTime":0,"id":348,"basePriority":81,"name":"AppleSN2400Charger","user_usec":32844214,"schedPriority":81,"system_usec":0,"state":["TH_WAIT","TH_UNINT"],"waitEvent":[1,8094287857900425631]},"462":{"continuation":[0,68841550840],"userTime":0.00079737500000000002,"systemTime":0,"id":462,"basePriority":81,"user_usec":797,"system_usec":0,"schedPriority":81,"state":["TH_WAIT","TH_UNINT"],"waitEvent":[0,68843674372]},"1550":{"userTime":4.3329999999999998e-06,"systemTime":0,"name":"skywalk_mit_awdl0_rx_0","id":1550,"basePriority":81,"user_usec":4,"system_usec":0,"schedPriority":81,"kernelFrames":[[0,68837854116],[0,68837848396],[0,68842070888],[0,68837602388]],"state":["TH_WAIT","TH_UNINT"],"waitEvent":[1,8094287857926013103]},"640":{"userTime":1.9999999999999999e-06,"systemTime":0,"name":"skywalk_doorbell_pdp_ip1_tx","id":640,"basePriority":81,"user_usec":2,"system_usec":0,"schedPriority":81,"kernelFrames":[[0,68837854116],[0,68837848396],[0,68837815284],[0,68841306468],[0,68841307908],[0,68839287536],[0,68837602388]],"st

**Comment by jumamfa** [comment]
{
  "crashReporterKey" : "a891bfa01a13a1deaeb185a047880dd261b9a961",
  "kernel" : "Darwin Kernel Version 18.0.0: Tue Aug 14 22:07:19 PDT 2018; root:xnu-4903.202.2~1\/RELEASE_ARM64_S8000",
  "product" : "iPhone8,1",
  "incident" : "4D3B3F84-7606-413F-8901-AB12ED817E7F",
  "date" : "2018-09-24 11:27:03.07 +0100",
  "build" : "iPhone OS 12.0 (16A366)",
  "timeDelta" : 2,
  "memoryStatus" : {
  "compressorSize" : 13265,
  "compressions" : 864381,
  "decompressions" : 677490,
  "zoneMapCap" : 755810304,
  "largestZone" : "APFS_4K_OBJS",
  "largestZoneSize" : 29622272,
  "pageSize" : 16384,
  "uncompressed" : 39934,
  "zoneMapSize" : 104464384,
  "memoryPages" : {
    "active" : 44715,
    "throttled" : 0,

**Comment by christocracy** [comment]
There's nothing related to the plugin in this log.

**Comment by jumamfa** [comment]
What logs could I provide that would be helpful

**Comment by christocracy** [comment]
Even if your app crashes, it will be re-launched and tracking *will* resume.

I have not seen a crash from the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp) since May 9.  I test every day.

>What logs could I provide that would be helpful

Your crash log does not reference the plugin code (`TSLocationManager`).  The plugin is not responsible for your crash.
