### ISSUE TITLE
Hiding push notification alert which is about "location service activated"

### ISSUE THREAD

**Issue by laychar** [transistorsoft/cordova-background-geolocation-lt#797]
Almost of my users complain that the push notification doesn't disappear in android @8.0.0 + .
How to remove push notification?
This is really impossible?

**Comment by christocracy** [comment]
It’s not a “Push” notification, it’s a local notification.

No, it **cannot** be removed.  It’s required by the OS.  If it were removed, the plugin wouldn’t track location.  Perhaps your users would complain about that too?

**Comment by christocracy** [comment]
And if you’re hoping to aggressively tracking users without their knowledge, this is not the plugin for you.  Your users would be right to complain.  

This plugin is designed for fleet tracking use-cases, not social / marketing apps.

**Comment by laychar** [comment]
But GPS is designed for military purpose. But we use it for delivery system, uber ,social /marketing etc.
I think your plugin can be used for various purposes. In my opinion you underestimate your plugin's potentialities.
Do you have an idea to relieve users' complaint? Or  can you tell me what plugin is appropriate for me?
I wanna track users.

**Comment by christocracy** [comment]
>Do you have an idea to relieve users' complaint?

Explain to your users what why you're tracking their location.  configure the `notificationText` / `notificationTitle` as desired.

**Comment by laychar** [comment]
That is good idea. But I already explain to users. But they complain. for example "this notification does not disappear. how to remove it!!? my status bar very precious!"
 I want to know more novel method to relieve complaint.

**Comment by christocracy** [comment]
How you explain the necessity of the notification is between you and your users.  The notification is [required by Android](https://youtu.be/Pumf_4yjTMc?t=181) if you want to use the plugin to track the device in the background.

**Comment by laychar** [comment]
Thank you for your advise. I'll try it.
