### ISSUE TITLE
How to implement the renewal of expired access token (JWT) via refresh token

### ISSUE THREAD

**Issue by thienban** [transistorsoft/cordova-background-geolocation-lt#798]
## Your Environment
* Plugin version: 2.11
* Platform: iOS or Android
* OS version: Window 10 
* Device manufacturer / model: cellphone Xiaomi Redme
* Cordova version (`cordova -v`): 1.1.4
* Cordova platform version (`cordova platform ls`):
* Plugin config
```
                                        desiredAccuracy: 0,
					distanceFilter: 5,
					stationaryRadius: 15,//IOS
					// Activity Recognition config
					activityRecognitionInterval: 10000,
					stopTimeout: 5,
					//locationUpdateInterval: 1000,//Android
					foregroundService: true,//Android
					// Application config
					stopOnTerminate: true, //stop when app terminated
					startOnBoot: true,
					reset: true,  //always apply the supplied config
					//Logging & Debug Options
					debug: true,  //Debug sounds & notifications.
					logLevel: bgGeo.LOG_LEVEL_INFO, //Debub log
					// HTTP / SQLite config
					url: serverURL+"record?token="+token,
					method: "POST",
					autoSync: true,
					maxDaysToPersist: 2,
					maxRecordsToPersist: -1,
					autoSyncThreshold: 5,
					batchSync : true,
					maxBatchSize: 10,
					httpRootProperty: 'positions',
					params: {
						"extRef" : extRef
					},
					locationTemplate: '{ "lat":<%= latitude %>,"lon":<%= longitude %>,"speed":<%= speed %>,"heading":<%= heading %>,"accuracy":<%= accuracy %>,"time":"<%= timestamp %>","batteryLevel":<%= battery.level %> }'
```

## Expected Behavior
-Listen on `http` events. When, `http` error occurs, refresh the token and reconfigure the `url` with `setConfig`
-Positions send with the new `url`

## Actual Behavior
-Listen on `http` events. When, `http` error occurs, refresh the token and reconfigure the `url` with `setConfig`
`-url` is changed in the `getState`. But, there is still an error when sending positions

## Steps to Reproduce

1. Listen on the `http` event
```
bgGeo.on('http', function(response) {
					console.log('http success: ', response.responseText);
				}, function(response) {
					if(!response.success) {
					dispatch(refreshToken());
					console.log("refresh token " + response.responseText);
					}
				});
```
2. Execute refresh function when there is an `http` error
```
export function refreshToken() {
	return function(dispatch, getState) {
		let bgGeo = window.BackgroundGeolocation;
			if(bgGeo) {
				let settings = getState().settings;
				let serverApi = settings.trackingServer;
				let appkey =settings.trackingServerAppKey;
				let appToken = settings.trackingServerAppToken;
				dispatch(fetchGcLocation(serverApi, appkey, appToken))
				.then((token)=> {
						setConfigBglocation(serverApi, token);
						//console.log("- setConfigBglocation");
				});
			}
	};
}
```
3. fetch API to get a new Token
```
export function fetchGcLocation(server, appKey, appToken) {
		return function(dispatch) {
			let serverUrl = server.substring(0,31) + 'token?' + 'appkey='+ appKey + '&apptoken=' + appToken;
			let myHeaders = new Headers();
			myHeaders.append("Content-Type", "application/json");
	      	let options = {
				headers:myHeaders,
				method:'GET'
			};     
	      	return fetch(serverUrl, options)
				.then(response => response.json())
				.then(json => {
					if(json.status === "OK") {
						console.log("OnSuccess & Token: "+ json.result);
						dispatch(gcLocationTokenSave(json.result));
						return json.result
					} else{
						console.error("failed!");
					}
				})
				.catch(error =>console.log(error));
		};
}
```

4. Set the new `url`
```
function setConfigBglocation(serverURL, token) {
	let bgGeo = window.BackgroundGeolocation;
	bgGeo.setConfig({
		url: serverURL+"record?token="+token
	  }, function(){
		//console.log("- setConfig success");
		bgGeo.getState(function(state) {
			//console.log(JSON	.stringify(state));
		  });
	  }, function(){
		//console.warn("- Failed to setConfig");
	  });
}
```

5. The next positions delivery will use the new `url`

## Debug logs
refresh token 400
ot-mobile.js:formatted:29720 OnSuccess & Token: XXXXXXXX
ot-mobile.js:formatted:29736 - setConfigBglocation
ot-mobile.js:formatted:29746 - setConfig success

```
{
	"activityRecognitionInterval": 10000,
	"allowIdenticalLocations": false,
	"autoSync": true,
	"autoSyncThreshold": 5,
	"batchSync": true,
	"debug": true,
	"deferTime": 0,
	"desiredAccuracy": 0,
	"desiredOdometerAccuracy": 100,
	"disableElasticity": false,
	"disableStopDetection": false,
	"distanceFilter": 5,
	"elasticityMultiplier": 1,
	"enableHeadless": false,
	"extras": {},
	"fastestLocationUpdateInterval": 10000,
	"forceReloadOnBoot": false,
	"forceReloadOnGeofence": false,
	"forceReloadOnHeartbeat": false,
	"forceReloadOnLocationChange": false,
	"forceReloadOnMotionChange": false,
	"forceReloadOnSchedule": false,
	"foregroundService": true,
	"geofenceInitialTriggerEntry": true,
	"geofenceProximityRadius": 1000,
	"geofenceTemplate": "",
	"headers": {},
	"headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
	"heartbeatInterval": -1,
	"httpRootProperty": "positions",
	"httpTimeout": 60000,
	"isMoving": false,
	"locationTemplate": "{ \"lat\":<%= latitude %>,\"lon\":<%= longitude %>,\"speed\":<%= speed %>,\"heading\":<%= heading %>,\"accuracy\":<%= accuracy %>,\"time\":\"<%= timestamp %>\",\"batteryLevel\":<%= battery.level %> }",
	"locationTimeout": 60,
	"locationUpdateInterval": 1000,
	"locationsOrderDirection": "ASC",
	"logLevel": 3,
	"logMaxDays": 3,
	"maxBatchSize": 10,
	"maxDaysToPersist": 2,
	"maxRecordsToPersist": -1,
	"method": "POST",
	"minimumActivityRecognitionConfidence": 75,
	"notificationColor": "",
	"notificationLargeIcon": "",
	"notificationPriority": 0,
	"notificationSmallIcon": "",
	"notificationText": "Location Service activated",
	"notificationTitle": "",
	"params": {
		"extRef": "EQPEXP10"
	},
	"persist": true,
	"schedule": [],
	"startOnBoot": true,
	"stationaryRadius": 15,
	"stopAfterElapsedMinutes": 0,
	"stopOnStationary": false,
	"stopOnTerminate": true,
	"stopTimeout": 5,
	"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
	"url": "XXX/record?token=XXXXXX",
	"enabled": true,
	"schedulerEnabled": false,
	"trackingMode": 1,
	"odometer": 51.637176513671875,
	"isFirstBoot": true
}
```

╔═════════════════════════════════════════════
║ Location-provider change: true
╠═════════════════════════════════════════════
╟─ GPS: true
╟─ Network: true
09-27 14:42:07.652 INFO [TSLocationManager onSingleLocationResult] 
Acquired providerchange position
09-27 14:42:07.697 INFO [c persist] 
  ✅  INSERT: c2b1c8f4-8921-447c-93de-6dbcc54fa06e
09-27 15:13:25.389 INFO [BackgroundGeolocationService k] 
  🔴  Stop heartbeat
09-27 15:13:25.410 INFO [BackgroundGeolocationService a] 
  🔵  setPace: false → true
09-27 15:13:26.211 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: true
09-27 15:13:26.266 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
09-27 15:13:26.297 INFO [c persist] 
  ✅  INSERT: 88313a5d-d9da-427c-a064-3b4a10ccb2ae
09-27 15:13:26.310 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
09-27 15:13:26.331 INFO [HttpService a] 
  🔵  HTTP POST batch (2)
09-27 15:13:27.717 WARN [HttpService$a onResponse] 
  ⚠️  Response: 401, Unauthorized
09-27 15:13:29.164 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
09-27 15:13:34.903 INFO [c persist] 
  ✅  INSERT: f99e96c3-03ce-4143-82f7-f045c4e20c53
09-27 15:13:52.933 INFO [BackgroundGeolocationService onActivityRecognitionResult] 
  🔵  Stop-timeout timer initiated (5 min)...
09-27 15:13:52.987 INFO [BackgroundGeolocationService h] 
  🔵  Begin stop timer
09-27 15:14:22.678 INFO [BackgroundGeolocationService onLocationResult] 
  ℹ️  Distance from stoppedAtLocation: -17.315472
09-27 15:14:22.688 INFO [c persist] 
  ✅  INSERT: c6c1ab19-0ba2-49e7-a8c4-401cf613374d
09-27 15:14:40.753 INFO [c persist] 
  ✅  INSERT: 2e216f0b-0a8a-4569-95c3-4e4301126859
09-27 15:14:40.813 INFO [HttpService a] 
  🔵  HTTP POST batch (5)
09-27 15:14:41.921 WARN [HttpService$a onResponse] 
  ⚠️  Response: 400, Bad Request
09-27 15:14:42.181 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
09-27 15:14:47.375 INFO [c persist] 
  ✅  INSERT: 53c97a7f-6f6e-4bf1-9cbe-6d9106c845d8
09-27 15:14:47.407 INFO [HttpService a] 
  🔵  HTTP POST batch (6)
09-27 15:14:47.463 WARN [HttpService$a onResponse] 
  ⚠️  Response: 400, Bad Request
09-27 15:14:47.617 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
09-27 15:15:24.890 INFO [BackgroundGeolocationService onActivityRecognitionResult] 
  🔵  Stop-timeout timer initiated (5 min)...
09-27 15:15:24.913 INFO [BackgroundGeolocationService h] 
  🔵  Begin stop timer
09-27 15:17:47.054 INFO [LocationService onLocation] 
  ℹ️  Location availability: false
09-27 15:17:47.542 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
09-27 15:17:57.542 INFO [BackgroundGeolocationService onLocationResult] 
  ℹ️  Distance from stoppedAtLocation: -18.76081
09-27 15:17:57.562 INFO [c persist] 
  ✅  INSERT: 6297b702-cf7c-4f49-96fe-1ecf71bbe561
09-27 15:17:57.603 INFO [HttpService a] 
  🔵  HTTP POST batch (7)
09-27 15:17:58.845 WARN [HttpService$a onResponse] 
  ⚠️  Response: 400, Bad Request
09-27 15:18:29.903 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
09-27 15:18:30.960 INFO [BackgroundGeolocationService onLocationResult] 
  ℹ️  Distance from stoppedAtLocation: -24.610888
09-27 15:18:30.968 INFO [c persist] 
  ✅  INSERT: cb355a66-9b64-4ae1-9d22-5dedf54bb2ec
09-27 15:18:31.012 INFO [HttpService a] 
  🔵  HTTP POST batch (8)
09-27 15:18:31.069 WARN [HttpService$a onResponse] 
  ⚠️  Response: 400, Bad Request
09-27 15:18:45.497 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
09-27 15:18:46.593 INFO [BackgroundGeolocationService onLocationResult] 
  ℹ️  Distance from stoppedAtLocation: -24.610888
09-27 15:20:24.949 INFO [TSLocationManager d] 
  🔴  Location-services: OFF
09-27 15:20:25.024 INFO [BackgroundGeolocationService a] 
  🔵  setPace: true → false
09-27 15:20:26.231 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: false

**Comment by christocracy** [comment]
This isn't a plugin problem.  This is a problem at your server.  Check your server logs to figure out why it's complaining about a ⚠️ Response: 400, Bad Request

**Comment by thienban** [comment]
I tested in the Background mode. The App is in Background and the phone is in sleep mode. I have error `401,Unauthorized` . After Reopen the phone and the App, positions are sent. 
```
bgGeo.on('http', function(response) {
			dispatch(gcLocatioRespone(response.status));
		}, function(response) {
			console.log('[http] - ', response.status, response.responseText);
			dispatch(gcLocatioRespone(response.status));
			if(!response.success && response.status === 401) {
				console.log("REFRESH on 401")
				dispatch(refreshToken());
			}
		});

export function refreshToken() {
	return function(dispatch, getState) {
		let bgGeo = window.BackgroundGeolocation;
			if(bgGeo) {
				let settings = getState().settings;
				let serverApi = settings.trackingServer;
				let appkey =settings.trackingServerAppKey;
				let appToken = settings.trackingServerAppToken;
				dispatch(fetchGcLocation(serverApi, appkey, appToken))
				.then(()=> {
					let token = getState().settings.gcLocationToken;
					let d = new Date();
					console.log("TOKEN" + token +"  "+ d)
					setConfigBglocation(token);
				});
			}
	};
}
function setConfigBglocation(token) {
	let bgGeo = window.BackgroundGeolocation;
	let time = new Date();
	console.log("RENEW TOKEN" + time);
	bgGeo.setConfig({
		headers: { Authorization:"Bearer "+ token },
	});
}
```
I have the log `REFRESH on 401`. But nothing from `TOKEN`.
In sleep mode, how does the javascript code from the App run ?

**Comment by dbsali** [comment]
@thienban how did you save your json token in gcLocationTokenSave ?

**Comment by christocracy** [comment]
By popular demand later versions of the plugin have implemented a new `Config.Authorization` mechanism for auto-refreshing a JWT.  See the API docs.

**Comment by dbsali** [comment]
@christocracy , Config.Authorization nowhere to be found?

**Comment by dbsali** [comment]
What does getMyAuthorizationToken() signify ?

**Comment by christocracy** [comment]
That’s your own imaginary code to fetch your auth token.
