### ISSUE TITLE
iOS background geofence

### ISSUE THREAD

**Issue by trivector-se** [transistorsoft/cordova-background-geolocation-lt#8]
Hi,

We want to use the onGeofence-event to relaunch the app and start gathering data.
According to the apple developer documentation
https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/doc/uid/TP40007125-CH3-SW32

and specifically the quote:
"The region monitoring service delivers events normally while an app is running in the foreground or background. (You can use this service for both geographic and beacon regions.) For a terminated iOS app, this service relaunches the app to deliver events. Use of this service requires “Always” authorization from the user."

we take it that the app should relaunch from these events. Although when the app runs in background (home button is pressed or screen is locked - applications has NOT been force-quit) we dont seem to get these events.

Example code:
```javascript
bgGeo.onMotionChange(function(isMoving, location, taskId) {
	
    if (!isMoving) { // if not moving, create a geofence on this location
        bgGeo.addGeofence({
			identifier: "test",
			radius: 100,
			latitude: location.coords.latitude,
			longitude:location.coords.longitude,
			notifyOnEntry: false,
			notifyOnExit: true
		}, function() {
			console.log("Successfully added geofence");
			PostToServer('ADD_GEOFENCE');// Log on server that we added a geofence
		}, function(error) {
			console.warn("Failed to add geofence " + error);
		});
    } 
    bgGeo.finish(taskId);
})

bgGeo.onGeofence(function(params, taskId) {
	try {
		if ((params.identifier == 'test') && (params.action == 'EXIT')) {
			bgGeo.changePace(true); // set aggressive logging if we passed a geofence
			PostToServer('EXIT_GEOFENCE');// Log on server that we exited our geofence
		}
	} catch(e) {
		console.error('An error occurred in my application code ' + e);
	}
	bgGeo.finish(taskId);
});
```

We were thinking that we might be calling "bgGeo.finish(taskId)" at the wrong place but we've also tried doing that in the respective callbacks and also "if (isMoving)", like so:

```javascript
bgGeo.onMotionChange(function(isMoving, location, taskId) {
	
    if (!isMoving) { // if not moving, create a geofence on this location
        bgGeo.addGeofence({
			identifier: "test",
			radius: 100,
			latitude: location.coords.latitude,
			longitude:location.coords.longitude,
			notifyOnEntry: false,
			notifyOnExit: true
		}, function() {
			console.log("Successfully added geofence");
			PostToServer('ADD_GEOFENCE');// Log on server that we added a geofence
			bgGeo.finish(taskId);
		}, function(error) {
			console.warn("Failed to add geofence " + error);
			bgGeo.finish(taskId);
		});
    } else {
		bgGeo.finish(taskId);
	}
})
```

When consulting our logs on server we can see that we create new geofences, but we never "EXIT" them.

Thanks in advance

**Comment by christocracy** [comment]
You want to execute `bgGeo.finish(taskId)` within your `PostToServer` response-callback.  This is the purpose of the `taskId`: to request permission from iOS to **not** suspend the app until your server responds.  iOS is very **eager** to suspend an app when it has the change -- you don't want iOS to suspend the app **before** your server has responded.

```
PostToServer('ADD_GEOFENCE, function(response) {
  bgGeo.finish(taskId);  // <-- onMotionChange taskId
});
```

```
PostToServer('EXIT_GEOFENCE', function(response) {
  bgGeo.finish(taskId);  // <-- onGeofence taskId
})
```

As for Geofences not firing, try using a radius of at least 200.

See this [Apple Doc](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html#//apple_ref/doc/uid/TP40009497-CH9-SW11).  Search the word "minimum"

**Comment by trivector-se** [comment]
Hi Chris,

Thank you for your very quick answer,

I will try your suggestions and get back to you with an update soon,

Thanks again.

**Comment by trivector-se** [comment]
After applying your suggested changes, including radius 200 meter, we receive geofence exit. Not always, but often.
