### ISSUE TITLE
"Provider" field is inserted in the body POST request  

### ISSUE THREAD

**Issue by thienban** [transistorsoft/cordova-background-geolocation-lt#801]
## Your Environment
* Plugin version: 2.11
* Platform: iOS or Android
* OS version: Window 10 
* Device manufacturer / model: cellphone Xiaomi Redme
* Cordova version (`cordova -v`): 1.1.4
* Cordova platform version (`cordova platform ls`):
* Framework : React, Redux, Redux-thunk
* Plugin config
```
                                        desiredAccuracy: 0,
					distanceFilter: 5,
					stationaryRadius: 15,//IOS
					// Activity Recognition config
					activityRecognitionInterval: 10000,
					stopTimeout: 5,
					//locationUpdateInterval: 1000,//Android
					foregroundService: true,//Android
					// Application config
					stopOnTerminate: true, //stop when app terminated
					startOnBoot: true,
					reset: true,  //always apply the supplied config
					//Logging & Debug Options
					debug: true,  //Debug sounds & notifications.
					logLevel: bgGeo.LOG_LEVEL_INFO, //Debub log
					// HTTP / SQLite config
					url: serverURL+"record?,
                                        headers: { Authorization:"Bearer "+token },
					method: "POST",
					autoSync: true,
					maxDaysToPersist: 2,
					maxRecordsToPersist: -1,
					autoSyncThreshold: 5,
					batchSync : true,
					maxBatchSize: 10,
					httpRootProperty: 'positions',
					params: {
						"extRef" : extRef
					},
locationTemplate: '{ "lat":<%= latitude %>,"lon":<%= longitude %>,"speed":<%= speed %>,"heading":<%= heading %>,"accuracy":<%= accuracy %>,"time":"<%= timestamp %>","batteryLevel":<%= battery.level %> }'
```

## Expected Behavior
{"positions":[{"lat":48.7966892,"lon":2.3209546,"speed":-1,"heading":-1,"accuracy":13.6,"time":"2018-10-02T14:09:03.302Z","batteryLevel":0.9},
{"lat":48.7966575,"lon":2.3209417,"speed":-1,"heading":-1,"accuracy":15.2,"time":"2018-10-02T16:46:54.085Z","batteryLevel":0.88}

## Actual Behavior
{"positions":[{"lat":48.7966892,"lon":2.3209546,"speed":-1,"heading":-1,"accuracy":13.6,"time":"2018-10-02T14:09:03.302Z","batteryLevel":0.9,"provider":{"network":true,"gps":false,"enabled":true,"status":3}},
{"lat":48.7966575,"lon":2.3209417,"speed":-1,"heading":-1,"accuracy":15.2,"time":"2018-10-02T16:46:54.085Z","batteryLevel":0.88,"provider":{"network":true,"gps":true,"enabled":true,"status":3}},

## Steps to Reproduce
Call the plugin 
```
 dispatch(fetchGcLocation(json.wsconfig.trackingServer, json.wsconfig.trackingServerAppKey, json.wsconfig.trackingServerAppToken))
                    .then((token) => {
                    document.addEventListener("deviceready", () => dispatch(getHighFrequencyCurrentPositionLT(json.wsconfig.trackingServer, token, json.deviceId)), false);
                    });
```

Set up the plugin
```
export function getHighFrequencyCurrentPositionLT(serverURL, token, deviceId){
	return function(dispatch) {
	let agent = navigator.userAgent;
		if(agent.match(/Android/i) || agent.match(/(iPhone|iPad)/i) || agent.match(/Windows Phone/i)) {
			let bgGeo = window.BackgroundGeolocation;
			let extRef = deviceId;
			//This callback will be executed every time a geolocation is recorded in the background.
			let callbackFn = function(location) {
				let coords = location.coords;
				let lat    = coords.latitude;
				let lng    = coords.longitude;
				console.log('- Location: ', JSON.stringify(location));
				//display log
				bgGeo.getLog(function(log) {
					console.log(log);
				});
			};
				// This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
				let failureFn = function(errorCode) {
					console.warn('- BackgroundGeoLocation error: ', errorCode);
				};
			if(bgGeo) {
				// Listen to location events & errors.
				bgGeo.on('location', callbackFn, failureFn);
				// Fired whenever an HTTP response is received from your server.
				bgGeo.on('http', function(response) {
					console.log('http success: ', response.responseText);
				}, function(response) {
					if(!response.success) {
					dispatch(refreshToken());
					console.log("refresh token " + response.responseText);
					}
				});
				bgGeo.ready({
					reset: true,  //always apply the supplied config
					// Geolocation config
					desiredAccuracy: 0,//GPS + Wifi + Cellular
					distanceFilter: 5,//positions recorded after moving 5 meter 
					stationaryRadius: 15,//IOS
					// Activity Recognition config
					activityRecognitionInterval: 10000,//Detect the status of activity (still, on_foot, etc) 
					stopTimeout: 5,
					//locationUpdateInterval: 1000,//Android
					foregroundService: true,//Android
					// Application config
					stopOnTerminate: true, //stop when app terminated
					startOnBoot: true,
					//Logging & Debug Options
					debug: true,  //Debug sounds & notifications.
					logLevel: bgGeo.LOG_LEVEL_INFO, //Debub log
					// HTTP / SQLite config
					url: serverURL+"record",
					headers: { Authorization:"Bearer "+token },
					method: "POST",
					autoSync: true,
					maxDaysToPersist: 2,
					maxRecordsToPersist: -1,
					autoSyncThreshold: 5,
					batchSync : true,
					maxBatchSize: 10,
					httpRootProperty: 'positions',
					params: {
						"extRef" : extRef
					},
					locationTemplate: '{ "lat":<%= latitude %>,"lon":<%= longitude %>,"speed":<%= speed %>,"heading":<%= heading %>,"accuracy":<%= accuracy %>,"time":"<%= timestamp %>","batteryLevel":<%= battery.level %> }'
				}, function(state) {
					if (!state.enabled) {
						bgGeo.start();
					}
				});
			}
		}
	}
}

```
I use the locationTemplate, httpRootProperty, and params.

```
httpRootProperty: 'positions',
params: {
"extRef" : extRef
},
locationTemplate: '{ "lat":<%= latitude %>,"lon":<%= longitude %>,"speed":<%= speed %>,"heading":<%= heading %>,"accuracy":<%= accuracy %>,"time":"<%= timestamp %>","batteryLevel":<%= battery.level %> }'
```

I listen the HTTP response. When there is a `http` error, i refresh the token in header.

```
bgGeo.on('http', function(response) 
       {
	console.log('http success: ', response.responseText);
	}, function(response) {
	if(!response.success) {
	dispatch(refreshToken());
	console.log("refresh token " + response.responseText);
	}
});
```
```
export function refreshToken() {
	return function(dispatch, getState) {
		let bgGeo = window.BackgroundGeolocation;
			if(bgGeo) {
				let settings = getState().settings;
				let serverApi = settings.trackingServer;
				let appkey =settings.trackingServerAppKey;
				let appToken = settings.trackingServerAppToken;
				dispatch(fetchGcLocation(serverApi, appkey, appToken))
				.then((token)=> {
						setConfigBglocation(token);
						//console.log("- setConfigBglocation");
				});
			}
	};
}
```
```
function setConfigBglocation(token) {
	let bgGeo = window.BackgroundGeolocation;
	bgGeo.setConfig({
		headers: { Authorization:"Bearer "+token },
	  }, function(){
		/*console.log("- setConfig success");
		bgGeo.getState(function(state) {
			console.log(JSON.stringify(state));
		  });*/
	  }, function(){
		//console.warn("- Failed to setConfig");
	  });
}

```

## Debug logs

refresh token {"status":"ERROR","message":"Failed to decode: Unrecognized field \"provider\" (class com.geoconcept.location.api.model.GPSPosition), not marked as ignorable (12 known properties: \"heading\", \"privateMode\", \"speed\", \"accuracy\", \"positionMethod\", \"lon\", \"time\", \"lat\", \"status\", \"batteryLevel\", \"event\", \"flags\"])\n at [Source: (String)\"{\"positions\":[{\"lat\":48.7966892,\"lon\":2.3209546,\"speed\":-1,\"heading\":-1,\"accuracy\":13.6,\"time\":\"2018-10-02T14:09:03.302Z\",\"batteryLevel\":0.9,\"provider\":{\"network\":true,\"gps\":false,\"enabled\":true,\"status\":3}},{\"lat\":48.7966575,\"lon\":2.3209417,\"speed\":-1,\"heading\":-1,\"accuracy\":15.2,\"time\":\"2018-10-02T16:46:54.085Z\",\"batteryLevel\":0.88,\"provider\":{\"network\":true,\"gps\":true,\"enabled\":true,\"status\":3}},{\"lat\":48.796591,\"lon\":2.3209255,\"speed\":-1,\"heading\":-1,\"accuracy\":13.8,\"time\":\"2018-10-02T16:47:\"[truncated 952 chars]; line: 1, column: 154] (through reference chain: serverAdress[\"positions\"]->java.lang.Object[][0]->serverAdress[\"provider\"])"}

  ⚠️  Response: 400, Bad Request
10-03 09:20:40.656 INFO [c persist] 
  ✅  INSERT: ec0dbca0-a97f-4141-a62d-cc7c74ef6783
10-03 09:20:40.700 INFO [HttpService a] 
  🔵  HTTP POST batch (10)
10-03 09:20:42.011 WARN [HttpService$a onResponse] 
  ⚠️  Response: 400, Bad Request
10-03 09:25:40.693 INFO [c persist] 
  ✅  INSERT: ba56bca4-9b8a-4a41-80dd-0d3f00d9d851
10-03 09:25:40.733 INFO [HttpService a] 
  🔵  HTTP POST batch (10)
10-03 09:25:40.893 WARN [HttpService$a onResponse] 
  ⚠️  Response: 400, Bad Request
10-03 09:30:48.934 INFO [c persist] 
  ✅  INSERT: efb04c18-48a3-485b-bbef-b9faa7bcdcfa
10-03 09:30:48.976 INFO [HttpService a] 
  🔵  HTTP POST batch (10)
10-03 09:30:50.276 WARN [HttpService$a onResponse] 
  ⚠️  Response: 400, Bad Request

**Comment by thienban** [comment]
Thank you for the answer. It's in the server side.

**Comment by christocracy** [comment]
> Is there a way to disable this key provider ?

No.  Make your server aware of it.  When the `provider` key exists, `location.event == 'providerchange'`
