### ISSUE TITLE
After upgrade to 2.13.1 got a stacktrace in my firebase console

### ISSUE THREAD

**Issue by pdemilly** [transistorsoft/cordova-background-geolocation-lt#802]
## Your Environment
* Plugin version: 2.13.1
* Platform: Android
* OS version: 
* Device manufacturer / model: Pixel 2XL
* Cordova version (`cordova -v`): 8.1.1 (cordova-lib@8.1.0)
* Cordova platform version (`cordova platform ls`):

Installed platforms:
  android 7.1.1
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0

* Plugin config

## Actual Behavior

After upgrading to this new version from 2.11.0-beta.13 I am getting an error in my firebase console. (not sure how it is related). My project is an ionic v3 project using firebase in the backend

Caused by java.lang.ClassNotFoundException
Didn't find class "com.google.android.gms.internal.zzbej" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.agendafleet.mobile2-1Qik3em8cgDGjQoiD8LxHg==/base.apk"],nativeLibraryDirectories=[/data/app/com.agendafleet.mobile2-1Qik3em8cgDGjQoiD8LxHg==/lib/arm64, /system/lib64]]
dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134)
java.lang.ClassLoader.loadClass (ClassLoader.java:379)
java.lang.ClassLoader.loadClass (ClassLoader.java:312)
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance (Unknown Source)
com.transistorsoft.locationmanager.BootReceiver.a (Unknown Source:8)
com.transistorsoft.locationmanager.BootReceiver.onReceive (Unknown Source:109)
android.app.ActivityThread.handleReceiver (ActivityThread.java:3379)
android.app.ActivityThread.access$1200 (ActivityThread.java:199)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1661)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6669)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

**Comment by pdemilly** [comment]
Here is my list of plugins

<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-dialogs" spec="^2.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-keyboard" spec="^1.2.0" />
    <plugin name="cordova-plugin-ionic" spec="^4.1.6">
    </plugin>
    <plugin name="cordova-plugin-android-permissions" spec="^1.0.0" />
    <plugin name="cordova-plugin-fingerprint-aio" spec="^1.3.7" />
    <plugin name="cordova-plugin-nativestorage" spec="^2.3.1" />
    <plugin name="cordova-plugin-background-fetch" spec="5.4.1" />
    <plugin name="cordova-plugin-camera" spec="4.0.3" />
    <plugin name="cordova-plugin-firebase" spec="2.0.3" />
    <plugin name="cordova-clipboard" spec="1.2.1" />
    <plugin name="cordova-background-geolocation" spec="./lib/cordova-background-geolocation-2.13.1">
    <plugin name="cordova-plugin-ionic-webview" spec="^2.1.4">

ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 7.1.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.1
    npm  : 6.4.1
    OS   : Linux 4.15

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by christocracy** [comment]
Makes sense to use `15.0.1`.  Google made a huge change to Firebase and Play-services recently.  The two libraries used to be contained together.  They are now split apart.  When using latest Firebase API, you want to use latest "split" play-services.

**Comment by pdemilly** [comment]
Thanks. I think that did it
