### ISSUE TITLE
http feature is not reporting location

### ISSUE THREAD

**Issue by redolent** [transistorsoft/cordova-background-geolocation-lt#805]
Location is missing when the API is being called. What I did was I took the example config, and programmed BackgroundGeolocation to post to my api. All of the parameters are missing. 

I am posting to a _localhost_ api that records the GET, POST, and headers into a database. The example config is in the section "Example" in https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-example

## My Environment
* Plugin version: 2.13.2
* Platform: iOS
* OS version: High Sierra
* Device: Simulator XS Max
* Cordova version: 8.1.2
* Cordova platform version: ios 4.5.5
* Plugin config: Example config: https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-example

## Expected Behavior
When the HTTP request is made to the server the request must contain the longitude and latitude coordinates and other data if possible such as `isMoving`. 

## Actual Behavior
GET and POST are empty on the request.

## Steps to Reproduce
1. Create a new cordova project (https://cordova.apache.org/docs/en/latest/guide/cli/)
2. Create a new index.html (see below)
3. `$ cordova build`
4. `$ open platforms/ios/*.xcodeproj`
5. Run project
6. Check server logs

**index.html**
```
<script type="text/javascript" charset="utf-8" src="cordova.js"></script>
<script>
function onDeviceReady() {

    // code from https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-example
    // ...

    bgGeo.configure({
        url: "http://localhost/log.php",
        params: {
            myParams: {foo: 'bar'},
        },
    });
}
document.addEventListener('deviceready', onDeviceReady, false);
</script>
```

**log.php**
```
<?php
file_put_contents(
  "request.log"
  , print_r(array(
    "post"=>$_POST,
    "get"=>$_GET,
    "headers"=>getallheaders()
  ,true));
?>
```

## Context
I am trying to record locations in the database. Ultimately, I want to track whether two devices are in close proximity.

## Debug logs
_nothing to show_

**Comment by christocracy** [comment]
Duplicate #2.

**Comment by christocracy** [comment]
$_POST is for a web `<form>`.  The plugin doesn't post web `<form>`s.  It posts pure `JSON`
