### ISSUE TITLE
[New Feature] Typescript API

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/cordova-background-geolocation-lt#807]
The BackgroundGeolocation SDK now includes its own comprehensive **Typescript API**.  This will be great news for Ionic developers.  See [the blog post](https://medium.com/@transistorsoft/new-feature-typescript-api-4a160a2c853b) and the #806 

The is currently a beta version.  To install `2.14.0-beta.1`:
```
$ ionic cordova plugin add cordova-background-geolocation-lt@2.14.0-beta.1
```

**Comment by vandres** [comment]
@christocracy small inconsistency between 

    static onHttp(callback: (response:HttpEvent) => void): void;

and

    onHttp: function(success, failure) {
       this.on('http', success, failure);
    },

**Comment by christocracy** [comment]
Thanks.

**Comment by vandres** [comment]
@christocracy for the `onHttp`, which is the way to go?

```
BackgroundGeolocation.onHttp((response) => {
  console.log('[http] success -', response);
}, (response) => {
  console.log('[http] FAILURE -', response);
})
```
or
```
BackgroundGeolocation.onHttp((response) => {
  if (response.success) {
  	console.log('[http] success -', response);
  } else {
  	console.log('[http] FAILURE -', response);
  }
})
```

**Comment by christocracy** [comment]
Follow [the docs](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#onhttp)
