### ISSUE TITLE
Unable to install plugin on cordova-android: 6.4.0

### ISSUE THREAD

**Issue by madhurakhal** [transistorsoft/cordova-background-geolocation-lt#809]
## Your Environment
Ionic:

   ionic (Ionic CLI) : 4.2.1 
   Ionic Framework   : ionic1 ^1.3.5
   @ionic/v1-toolkit : 1.0.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (21 plugins total)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.8.0
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255

## Expected Behavior
should able to install and work as expected
## Actual Behavior
should work on each android
<img width="964" alt="screen shot 2018-10-22 at 1 48 29 pm" src="https://user-images.githubusercontent.com/839882/47290751-3fe3b880-d601-11e8-9922-cc4e9bd67ac4.png">

I got the same message when trying to install `cordova-background-geolocation-lt` as well.

**Comment by christocracy** [comment]
Don't invent your own issue template.  just fill out mine.  My template asked you for the plugin version, which is **crucial**.

## Your Environment
* Plugin version:

**Comment by christocracy** [comment]
And isn't your error obvious?
>Current project does not satisfy the engine requirements specified by an version...
>Plugin doesn't support this project's cordova-android version.  cordova-android: 6.4.0, failed version requirement:  >= 7.0.0

**Comment by madhurakhal** [comment]
Yes but the app I am working is very old and I am just trying to update some api. My plugin version is 2.12.0

**Comment by madhurakhal** [comment]
Yes But I am only updating some api. My plugin version 2.12.0. and I am using licenced version.

**Comment by christocracy** [comment]
2.12.0+ *requires* cordova-android@7.0.0.

The final version that supports `< cordova-android@7.0.0` is `2.11.0`

**Comment by christocracy** [comment]
When in doubt:
```
$ cordova platform remove android
$ cordova platform add android
```
