### ISSUE TITLE
Class not found error 

### ISSUE THREAD

**Issue by luisalfonsobo** [transistorsoft/cordova-background-geolocation-lt#81]
Hello. I have the premium version and installed the plugin but when i start my app I get into the failure call back of BackgroundGeolocation which is

var failureFn = function(error) {
console.log('BackgroundGeoLocation error');
}

and the error variable contains "Class not found".. I dont know what this error is all about. Also I set the config.xml

**Comment by magnori** [comment]
Having the same issue on android. 
window.BackgroundGeolocation.start(function() {  }, function(err) {   alert(err);   });

i do have the license number in the config.xml.
<preference name="cordova-background-geolocation-license" value="licensenumber" />

**Comment by christocracy** [comment]
For issues with Android, please post at the private repo.
