### ISSUE TITLE
EventBus error

### ISSUE THREAD

**Issue by hnakao** [transistorsoft/cordova-background-geolocation-lt#811]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: 6.0
* Device manufacturer / model: Sony Xperia
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config

I/TSLocationManager: [c.t.l.adapter.TSConfig print] 
                     ╔═════════════════════════════════════════════
                     ║ TSLocationManager version: 2.12.13 (269)
                     ╠═════════════════════════════════════════════
                     {
                       "activityRecognitionInterval": 10000,
                       "allowIdenticalLocations": false,
                       "autoSync": false,
                       "autoSyncThreshold": 0,
                       "batchSync": false,
                       "debug": true,
                       "deferTime": 0,
                       "desiredAccuracy": 0,
                       "desiredOdometerAccuracy": 100,
                       "disableElasticity": false,
                       "disableStopDetection": false,
                       "distanceFilter": 10,
                       "elasticityMultiplier": 1,
                       "enableHeadless": false,
                       "extras": {},
                       "fastestLocationUpdateInterval": 10000,
                       "forceReloadOnBoot": false,
                       "forceReloadOnGeofence": false,
                       "forceReloadOnHeartbeat": false,
                       "forceReloadOnLocationChange": false,
                       "forceReloadOnMotionChange": false,
                       "forceReloadOnSchedule": false,
                       "foregroundService": true,
                       "geofenceInitialTriggerEntry": true,
                       "geofenceProximityRadius": 1000,
                       "geofenceTemplate": "",
                       "headers": {
                         "X-FOO": "bar"
                       },
                       "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
                       "heartbeatInterval": -1,
                       "httpRootProperty": "location",
                       "httpTimeout": 60000,
                       "isMoving": false,
                       "locationTemplate": "",
                       "locationTimeout": 60,
                       "locationUpdateInterval": 1000,
                       "locationsOrderDirection": "ASC",
                       "logLevel": 5,
                       "logMaxDays": 3,
                       "maxBatchSize": -1,
                       "maxDaysToPersist": 3,
                       "maxRecordsToPersist": -1,
                       "method": "POST",
                       "minimumActivityRecognitionConfidence": 75,
                       "notificationColor": "",
                       "notificationLargeIcon": "",
                       "notificationPriority": 0,
                       "notificationSmallIcon": "",
                       "notificationText": "Location Service activated",
                       "notificationTitle": "",
                       "params": {
                         "auth_token": "maybe_your_server_authenticates_via_token_YES?"
                       },
                       "persist": true,
                       "schedule": [],
                       "startOnBoot": true,
                       "stationaryRadius": 25,
                       "stopAfterElapsedMinutes": 0,
                       "stopOnStationary": false,
                       "stopOnTerminate": false,
                       "stopTimeout": 5,
                       "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                       "url": "http:\/\/your.server.com\/locations",
                       "enabled": true,
                       "schedulerEnabled": false,
                       "trackingMode": 1,
                       "odometer": 0,
                       "isFirstBoot": false
                     }
                     ╔═════════════════════════════════════════════
                     ║ DEVICE SENSORS
                     ╠═════════════════════════════════════════════
                     ╟─ ✅  ACCELEROMETER: {Sensor name="ACCELEROMETER", vendor="MTK", version=3, type=1, maxRange=32.0, resolution=0.00390625, power=0.13, minDelay=10000}
                     ╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
                     ╟─ ✅  MAGNETOMETER: {Sensor name="MAGNETOMETER", vendor="MTK", version=3, type=2, maxRange=600.0, resolution=0.0016667, power=0.25, minDelay=100000}
                     ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="significant motion detector", vendor="Sony Mobile Inc", version=104, type=17, maxRange=1.0, resolution=1.0, power=0.5, minDelay=-1}
                     ╚═════════════════════════════════════════════

## Expected Behavior
Update the position

## Actual Behavior
Sometimes he gets the position but sometimes he throws this error:
E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.location.WatchPositionResult to subscribing class class com.transistorsoft.locationmanager.location.TSLocationManager

## Steps to Reproduce
 bgGeo = window.BackgroundGeolocation;

  var failureFn = function (errorCode) {
        alert('- BackgroundGeoLocation error: ' + errorCode);
    };

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);

    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function (isMoving) {
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 25,
        reset: true,
        // Activity Recognition config
        foregroundService: true,
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        // Application config
        debug: true, // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        // HTTP / SQLite config
        url: "http://your.server.com/locations",
        method: "POST",
        autoSync: false,
        maxDaysToPersist: 3,
        logLevel: bgGeo.LOG_LEVEL_ERROR,
        headers: {// <-- Optional HTTP headers
            "X-FOO": "bar"
        },
        params: {// <-- Optional HTTP params
            "auth_token": "maybe_your_server_authenticates_via_token_YES?"
        }
    }, function (state) {
        // This callback is executed when the plugin is ready to use.
        if (!state.enabled) {
            bgGeo.start();
        }
    });

## Debug logs
I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                       ✅  Google Play Services: connected (version code:11220000)
I/TSLocationManager: - Enable: true → true, trackingMode: 1
W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.configure blocked the main thread for 90ms. Plugin should use CordovaInterface.getThreadPool().

E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.location.WatchPositionResult to subscribing class class com.transistorsoft.locationmanager.location.TSLocationManager
            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.containsKey(java.lang.String)' on a null object reference
                at com.transistorsoft.locationmanager.location.TSLocationManager.b(Unknown Source)
                at com.transistorsoft.locationmanager.location.TSLocationManager.buildTSLocation(Unknown Source)
                at com.transistorsoft.locationmanager.location.TSLocationManager.onWatchPositionResult(Unknown Source)
                at java.lang.reflect.Method.invoke(Native Method)
                at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
                at org.greenrobot.eventbus.BackgroundPoster.run(BackgroundPoster.java:64)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)

**Comment by hnakao** [comment]
Any idea?

**Comment by christocracy** [comment]
Show me how you're using `#watchPosition`.

**Comment by hnakao** [comment]
Do you mean after calling the start () function of the plugin?

**Comment by christocracy** [comment]
Under what case is `onToggleEnabled` executed in your app?

Are you aware that `#watchPosition` is designed to be used for short periods while your app is in the foreground?  It's not meant to be used for long periods while your app is in the background.

However, I believe this bug was fixed in `2.12.0`.

**Comment by hnakao** [comment]
I call onToggleEnabled when the user login in the app and twice more when change status from onduty to offduty. Is 2.12.0 compatible with android@6.3.0?

**Comment by christocracy** [comment]
Are you running `#watchPosition` **long term in the background**?  Do **not** do this.  The plugin's core [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation) does **not** require `#watchPosition`.  As I said, `#watchPosition` is designed for short-term usage in the foreground.  For example, rapid updates to the user's current location on a map component for example.

> Is 2.12.0 compatible with android@6.3.0?

No.  You must upgrade to `cordova-android@7.0.0+` . `2.11.0` is the last version which will `cordova-android@6.3.0`.  Cordova Android 7.0.0 was released nearly [a year ago](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html) and well-supported now.

**Comment by hnakao** [comment]
OK, so if I want to send constant requests to the server of the change of position I must use bgGeo.on ('motionchange', function (isMoving) {...}?

**Comment by christocracy** [comment]
>OK, so if I want to send constant requests to the server of the change of position I must use bgGeo.on ('motionchange', function (isMoving) {...}?

No.  *Listening* to events has no effect upon tracking.  If I start playing a song on my stereo then disconnect my speakers, it doesn't make the music stop.  

You initiate tracking with the [`start`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#start) method.  

The plugin doesn't care if you listen to events.  

```
// Start tracking
bgGeo.start();
.
.
// Stop tracking
bgGeo.stop();
```

**Comment by christocracy** [comment]
>OK, so if I want to send constant requests to the server of the change of position

You either provide the plugin an `url` to your server or you implement a `location` event-listener to manually post locations to your server.

`motionchange` event tells you when the device *started* moving or when it became *stationary* (where the `stopTimeout` elapsed).  

The plugin *knows* when a device is *moving* and *stationary*.

**Comment by hnakao** [comment]
I understand, thank you very much for the help!
