### ISSUE TITLE
Automatically stop background location on geofence exit event

### ISSUE THREAD

**Issue by chilimix** [transistorsoft/cordova-background-geolocation-lt#814]
We need the background location to stop when the user leaves the geofence.

We can control a lot of stuff with silent push, however, on IOS when the user manually force closes the app, the silent push cant execute the javascript before the user opens the app, and the user will be tracked until they reopen the app.

Would it be possible to implement an option for the plugin to automatically stop background location on geofence exit event?

Perhaps even with a delay, so that that if an enter event occurs within x minutes after the exit event happened, the process of automatically stopping the background location is canceled (or if the delayed stop process is canceled manually) until it receives another exit event.

**Comment by christocracy** [comment]
> however, on IOS when the user manually force closes the app, the silent push cant execute the javascript before the user opens the app

Even with ["content-available": 1](https://medium.com/posts-from-emmerge/ios-push-notification-background-fetch-demystified-7090358bb66e) and `UIBackgroundModes "notification"`?

**Comment by chilimix** [comment]
We did some testing with what you sugested and it seemed to work. The significant change event was just fluctuating a lot from device to device which was creating some confussion. Thanks Chris
