### ISSUE TITLE
IOS - xcode setting

### ISSUE THREAD

**Issue by laychar** [transistorsoft/cordova-background-geolocation-lt#816]
## Your Environment
* Plugin version: 2.13.1
* Platform: iOS
* OS version: Mac 
* Device manufacturer / model: IPhone 6
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  ios 4.5.5
Available platforms: 
  android ~7.1.1
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0

I want to ask you something. Would you give me a tip?
I have some troubles in using your plugin such as when app is terminated, background location service is closed too. And when I set the one or two  of config value to other value, location service doesn't work at all etc. 
I think this problem occurs because I can't use your plugin in correct way. 
In android there is no problem.
Is there anything I should do in xcode setting?
for example turning on Background modes which is in xcode capablities. or in the apple developer account website there is anything which I should do?

**Comment by yomencity** [comment]
#704
