### ISSUE TITLE
Question: Geofence and batching different behavior for android and IOS

### ISSUE THREAD

**Issue by chilimix** [transistorsoft/cordova-background-geolocation-lt#817]
We are having some issues with geofencing and batching syncronization.

We are using these configs:

```
const config = {
      stationaryRadius: 25,
      distanceFilter: 50,
      desiredOdometerAccuracy: 50,
      activityRecognitionInterval: 10000,
      fastestLocationUpdateInterval: 2000,
      locationUpdateInterval: 2500,
      watchPositionInterval: 1800000,
      minimumActivityRecognitionConfidence: 50,
      stopOnTerminate: false,
      disableStopDetection: false,
      startOnBoot: true,
      batchSync: true,
      autoSync: true,
      autoSyncThreshold: 40,
      debug: false,
      // if set to zero - no geofence event will be sent to the cloud
      maxDaysToPersist: 1,
      maxBatchSize: -1,
      preventSuspend: true,
      heartbeatInterval: 60,
      geofenceProximityRadius: 20000,
      geofenceInitialTriggerEntry: true,
      deferTime: 0,
      elasticityMultiplier: 4,
      disableElasticity: false,
      stopDetectionDelay: 5,

      forceReloadOnMotionChange: true,
      forceReloadOnLocationChange: true,
      forceReloadOnGeofence: true,
      forceReloadOnHeartbeat: true,
      foregroundService: true,
      forceReloadOnBoot: true,
      notificationColor: "#ff9800",
      notificationText: "Clocked in",
      logLevel: 0
```

When we set autoSyncThreshold: 1, android and IOS behaves the same way as expected.
Both devices gets a enter/exit events right away. 

When we set autoSyncThreshold: 40, Android still behaves as we want it to, it sends the enter/exit event to the server right away, regardless of the autosyncthreshold.
IOS however seems to batch the geofencechange event, and doesnt sync it to the server right away?

**Comment by christocracy** [comment]
@chilimix I see you've not renewed your support subscription.

**Comment by christocracy** [comment]
@chilimix you renew your support subscription in the Product Dashboard.  There's a `[Renew Subscription]` button.

**Comment by chilimix** [comment]
Done

**Comment by christocracy** [comment]
I'll investigate.

**Comment by christocracy** [comment]
From now on, post issues to private repo.

**Comment by chilimix** [comment]
Roger Roger

**Comment by chilimix** [comment]
Hey Chris,

Have you been able to reproduce this?

I know I its a little early to ask you, and normally i would wait patiently, as i know you are a busy man. 
However, we are in a complete deadlock situation here because of this, as we cant lunch our next update with some critical updates until we found a solution to this :/

**Comment by christocracy** [comment]
Sorry, no.  Swamped today.  Tomorrow.

**Comment by chilimix** [comment]
Thank you, Chris, much appreciated!

**Comment by chilimix** [comment]
We implemented your example, and it seems to do the trick for us.

Thank you Chris!
