### ISSUE TITLE
Notification icon not working on "Searching for GPS" notification

### ISSUE THREAD

**Issue by MatanYed** [transistorsoft/cordova-background-geolocation-lt#818]
"Searching for GPS" is a temporary notification, i have it only when i'm using getCurrentPosition(), this notification is using the app default icon.
Only the permanent notification "Location service activated" have the `notificationSmallIcon` i configured.

**Comment by christocracy** [comment]
I do not know what you mean.

When the plugin `#start` method is executed, the plugin's foreground-service is launched and the service's required notification is posted.

**Comment by MatanYed** [comment]
You will understand it better by example I guess: https://i.imgur.com/a2D3GyZ.jpg

**Comment by christocracy** [comment]
Who is posting this "Searching for GPS" notification?  Is your own notification or this is the plugin's required notification where you've configured `notificationTitle`, `notificationText`.

I would understand better if you didn't ignore the issue template, which asked you to provide the config you're providing to the plugin.

**Comment by MatanYed** [comment]
I am sorry,
this is my config:

	{
		reset: true,
		distanceFilter: 100,
		maxRecordsToPersist: 1,
		stopOnTerminate: false,
		startOnBoot: true,
		url: `${this.$config.api.baseUrl}store-geo-point`,
		method: 'POST',
		httpRootProperty: '.',
		locationTemplate:  '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}',
		notificationText: 'Available for tour requests',
		notificationSmallIcon: 'drawable/push_icon',
		headers: {
			Accept: 'application/json',
			Authorization: `Bearer ${this.$store.getters["auth/token"]}`
		},
		params: {
			user_id: user.id
		},
		schedule: [
			...
		]
	}

The "Searching for GPS" notification is a notification that I always see when some app trying to catch my current position, it fired because of `BackgroundGeolocation.getCurrentPosition()` method.
I don't have a problem with this notification, I see it only when `getCurrentPosition` is in pending, only for 0.5-2 seconds, my issue is that the icon i configured is not on this notification.
Do you have any suggestion?

**Comment by christocracy** [comment]
The plugin is not responsible for a notification called "Searching for GPS"
