### ISSUE TITLE
Implement auto-sync throttling when server responds HTTP 429 too many requests

### ISSUE THREAD

**Issue by lnagel** [transistorsoft/cordova-background-geolocation-lt#82]
Auto-sync floods server with requests and basically mounts a DDoS service against our APIs when apps need to upload huge amounts of data. Our servers implement throttling of such requests and respond with HTTP 429 too many requests, however the background tracking module does not respect this.

It would simply be enough that the app would stop syncing at that time, wait a few minutes and then start again.

We are paying users of the premium version.

**Comment by Froelund** [comment]
Any news on this?
I'm considering buying the premium version, but it doesn't seem to have proper support?

**Comment by lnagel** [comment]
My workaround so far is to use batch requests with a high number of data points in each batch.
This still doesn't solve the issue of throttling the client if needed..

**Comment by christocracy** [comment]
Sorry so late.  I just noticed I haven't been getting notifications on my own repo!

**Comment by christocracy** [comment]
I'm going to refactor the HTP layer to respect HTTP `429`.

**Comment by silver2k** [comment]
In an unrelated, but probably similar note, I have a client wishing to use your plugin, but they'd also like to throttle the rate at which the data is sent (so client side) to reduce the amount of traffic consumed by the phone.

Ideally - I'd like to be able to pass a reference to a boolean function that would be called before each upload to determine if should upload/skip the record (basically a filter). Looking at the code tho - this might not be trivial.

**Comment by christocracy** [comment]
I've implemented *some* throttling in the Premium version.  If the server returns `427`, the plugin will stop trying to unload its entire queue.

Eg:  if the plugin has 100 locations in its database, the plugin used to initiate an HTTP request for each of the 100 records, regardless if the first request returned `404` or `500` or `427`.

**Now**, the plugin will stop sending if any request returns a non `200`ish response.

If you're using `autoSync: true`, the plugin will **still** attempt to sync each record, but at least it'll stop after the 1st error response.

Throttled servers typically return the number of API calls remaining in the HTTP response headers.  What I'd like to do is make a new config param allowing you to define which header param represents the api calls remaining.  This would be easy to implement.

I once wrote a API throttler for the [Shopify API](https://help.shopify.com/api) (which they integrated into their official version ;)), so I know exactly what's involved with HTTP throttling.

**Comment by christocracy** [comment]
btw, you won't be able to implement this yourself.  The HTTP code is within the compiled binary which you don't have access to.

**Comment by lnagel** [comment]
Great news, thanks! We'll post feedback once we are able to test this out.

**Comment by christocracy** [comment]
Could you all describe your rate-limiting API and headers used.  Do they match any described [here](http://stackoverflow.com/questions/16022624/examples-of-http-api-rate-limiting-http-response-headers)?

**Comment by lnagel** [comment]
We currently don't have the rate limits described in the HTTP response headers, but I intend to add them in Vimeo's style. Over-the-limit responses are rejected with 429 Too Many Requests.

**Comment by christocracy** [comment]
This is really old.  `autoSyncThreshold` has been implemented since this.
