### ISSUE TITLE
Cannot Compile app in ios

### ISSUE THREAD

**Issue by madhurakhal** [transistorsoft/cordova-background-geolocation-lt#820]
It got Build input file cannot found: 
`Plugins/cordova-background-geolocation/CDVBackgroundGeolocation.m` although there is no 'cordova-background-geolation'. I have removed ios platform and re added ios. there is no reference of 'cordova-background-geoloation' in my app but `CDVBackgroundGeolocation.m` and `CDVBackgroundGeolocation.h` file created automatically.

## Your Environment
* Plugin version:2.11.0
* Platform: iOS 
* OS version: 8
* Device manufacturer / model:
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ``` Installed platforms:
  android 6.4.0
  ios 4.5.5
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0```
* Plugin config

Used Plugins
```cordova-android-support-gradle-release 1.4.5 "cordova-android-support-gradle-release"
cordova-background-geolocation-lt 2.11.0 "BackgroundGeolocation"
cordova-custom-config 1.2.6 "cordova-custom-config"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-background-fetch 5.3.0 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.4-dev "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.7.0 "Toast"
cordova.plugins.diagnostic 3.6.8 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
phonegap-plugin-push 1.10.7 "PushPlugin"
```

## Expected Behavior
should not search for `cordova-background-geolocation` and used `cordova-background-geolocation-lt`

## Actual Behavior
Cannot run on build the app

## Debug logs
error: `Build input file cannot be found: 'Plugins/cordova-background-geolocation/CDVBackgroundGeolocation.m'`

**Comment by christocracy** [comment]
```
$ cordova plugin remove cordova-background-geolocation-lt

$ cordova platform remove ios
$ cordova platform add ios
$ cordova build ios
```
After **removing the plugin**, does it build?

**Comment by madhurakhal** [comment]
Failed with the same error. This app was using previous version of the plugin. I changed it to the version you specified previously.

**Comment by christocracy** [comment]
I don't know.  Seems you've confused Cordova.  Check your config files for references:
- `config.xml` 
- `package.json`
- `plugins/fetch.json`, 
- `plugins/ios.json`
- 'package-lock.json`

**Comment by madhurakhal** [comment]
the plugin is not referenced in any of those files.

**Comment by christocracy** [comment]
```
$ ls -al plugins
```

**Comment by madhurakhal** [comment]
![screen shot 2018-10-30 at 3 10 27 pm](https://user-images.githubusercontent.com/839882/47724029-1f95a880-dc56-11e8-8a24-f58358786c20.png)

**Comment by christocracy** [comment]
No idea.

**Comment by madhurakhal** [comment]
this plugin `cordova-background-geolocation` is referenced from here `https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/src/ios/TSLocationManager.framework`

**Comment by christocracy** [comment]
>this plugin cordova-background-geolocation 

No it is **not**.  `TSLocationManager.framework` is a pure Obj-c library that known absolutely *nothing* at all about Cordova.  This same `TSLocationManager.framework` is used in a number of other frameworks:
- React Native
- NativeScript
- Pure Native apps
- Flutter.

**Comment by christocracy** [comment]
I suggest you create a simple Foo app and get the plugin working in isolation of your main app.

I don't know what you've done to your app but you have corrupted something.  This is not a plugin issue.

**Comment by ShafiqShams** [comment]
@madhurakhal did you tried the licensed version or the free one?
Secondly, I want to know if background tracking works perfectly even when the App is killed on both Android and iOS.

I can purchase this plugin, no issues but the thing is if this gonna work or not.
I JUST WANT TO UPDATE MY SERVER WITH THE UPDATED LOCATION POINTS EVEN WHEN THE APP IS KILLED OR IN BACKGROUND MODE.
