### ISSUE TITLE
notificationSmallIcon

### ISSUE THREAD

**Issue by laychar** [transistorsoft/cordova-background-geolocation-lt#821]
I want to change small icon which is on the status bar. Maybe It can be done for me to set notificationSmallIcon, right?
But I can't understand the words
---You must specify the type 
(drawable|mipmap) of resource you wish to use in the following format: {type}/icon_name
And Shoud I set forgroundService  true to change Icon?

**Comment by christocracy** [comment]
>Maybe It can be done for me to set notificationSmallIcon, right?

Yes.

>And Shoud I set forgroundService true to change Icon?

The icon and notification are only shown with `foregroundService: true`.  `foregroundService: true` is enforced with Android 7+.
