### ISSUE TITLE
App freezes on iOS splashscreen when plugin is added

### ISSUE THREAD

**Issue by vv001** [transistorsoft/cordova-background-geolocation-lt#823]
We are facing an issue with iOS. Whenever the plugin is added to our Cordova app and we build and deploy the app on any iPhone (several models), the app occasionally freezes when you start it the first time. Which results in having to kill the iOS app and restarting it again in order for it to run correctly.

## Your Environment
* Plugin version:  2.11.0 (Paid with license)
* Platform: iOS
* OS version: 12.0
* Device manufacturer / model: iPhone X, iPhone 6, iPhone 6S, iPhone 5S, iPhone 7, iPhone 7S (tested on all these devices)
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.1 (iOS) and 4.5.5 (iOS)
* Plugin config
        this.bgGeo.configure({
            debug: true,
            desiredAccuracy: 1, 
            distanceFilter: 1,
            logLevel: 4,
            startOnBoot: false,
            enabled: true,
            url: "linkisprovidedhere",
            method: "POST",
            autoSync: true,
            autoSyncTreshold: 0,
            stopOnTerminate: false,
            params: {
                'id': id
            }

## Expected Behavior
Expecting the overall cordova app to start/load normally, which it doesn't.

## Actual Behavior
Expecting the app to start normally, which it doesn't. If the plugin is added to the app, it causes the app to get stuck/frozen on the splashscreen in iOS. The user has to kill the app on the iOS device, and restart it again for it to run correctly. This happens sporadically. After killing the app and restarting it again, everything seems to be working fine. However, it still happens that the app freezes when the geolocation plugin is included.

This only happens on iOS (previously mentioned iOS devices). We have tested on Android devices, there it doesn't happen somehow.

## Steps to Reproduce

1. Add the plugin through the normal installation instructions.
2. Clean ../plugins/ folder to start with a clean build
2. cordova platform rm ios
3. cordova platform add
4. Start xcode file and deploy to iPhone (5S, 6, 7, 7S, 6S, X)
5. Start the app after any other given moment for the first time, results in the app freezing at Splashscreen.

## Context
Just start the application normally, when the plugin is added.

## Debug logs

When the app freezes, it doesn't even show in the logs that Cordova and Ionic are being started. Missing the 'device ready' output for example in the logs.

**Comment by christocracy** [comment]
You’re probably using some sort of `webview` plugin.  Those are known to have a bug when an iOS app is launched in the background, as this plugin will.

Remove the webview plugin.

**Comment by vv001** [comment]
Thanks for the quick response Chris, much appreciated.

We have the cordova-plugin-ionic-webview installed. I have however removed it and it seems not to freeze anymore, as far as I have tested for now.

When removing that plugin, it does seem that some UI elements are slower in responding to taps on the screen. Perhaps any idea how this might be resolved?

**Comment by christocracy** [comment]
Duplicate #800
