### ISSUE TITLE
Question: How to avoid prompt message that you see after some days in IOS

### ISSUE THREAD

**Issue by beritsistemas** [transistorsoft/cordova-background-geolocation-lt#824]
Hello, I had a question for you.  This is not an issue, however, just a question about the prompt that fires in iOS a couple days after installing the app.
The prompt says: 

"App_Name" has been using your location in the background. Do you want to continue allowing this?

We would like to get rid of that.  But we want to continue tracking in our app but may be with less accuracy.

Our question is:
Is there a configuration or improved our plugin config to avoid iOS from showing that message in the subsequent days after installing the app.

We understand that the first time you install the app its mandatory to ask and we have no issue with asking initially but after the user has already authorized prefer to not have this message show as its an easy opportunity for them to stop sharing location data (for example google maps doesn't do keep asking for location information like that)

## Your Environment
* Plugin version: 2.3.2
* Platform: iOS 
* OS version:12
* Device manufacturer / model: 5S and others
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 
  ios 4.5.5
* Plugin config
{
          debug: false,
          logLevel: 5,
          desiredAccuracy: 1000,
            distanceFilter: 1000,
            stationaryRadius: 1000,
            activityRecognitionInterval: 10000,
            stopTimeout: 5,
            foregroundService:false,
            fastestLocationUpdateInterval:5000,
        
            stopOnTerminate: false,
            startOnBoot: true,
            autoSync: true,
            preventSuspend:false,
            ,url: ‘our-api’,
            maxRecordsToPersist:1,
            method: "POST",
            headers: {
                        "idd”: “id”
                }
## Expected Behavior
I want to get rid of the 'background geolocation prompt after using the app

## Actual Behavior
After some days after installing our app.. I see that prompt message from IOS.. 

## Context
I want to track users of my app but without that prompt message in IOS (expected to loose accuracy to get rid of that message)

**Comment by christocracy** [comment]
You can't.  The plugin is always monitoring *at least* a geofence while in the stationary-state.

If you `#stop` the plugin, you'll never see that message but of course no tracking will occur either.
