### ISSUE TITLE
Geofence is never called

### ISSUE THREAD

**Issue by utiq** [transistorsoft/cordova-background-geolocation-lt#825]
## Your Environment
* Plugin version: 2.14.0
* Platform: iOS
* OS version: 12.1
* Device manufacturer / model:
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): ios 4.5.5

```
import { environment } from '../../environments/environment';
import { GeoCoordinate } from '../home/shared/trip.interface';
import { Injectable, EventEmitter, NgZone } from '@angular/core';

@Injectable()
export class LocationTrackerService {

 private bgGeo: any;
 public locationReached: EventEmitter<Position>;
 public currentLocation: EventEmitter<GeoCoordinate>;

 constructor() {
   this.locationReached = new EventEmitter<Position>();
   this.currentLocation = new EventEmitter<GeoCoordinate>();
 }

 configureBackgroundGeolocation() {
   // 1. Get a reference to the plugin
   this.bgGeo = (<any>window).BackgroundGeolocation;

   // 2. Listen to events
   this.bgGeo.on('location', this.onLocation.bind(this));
   this.bgGeo.on('geofence', this.onGeofence.bind(this));
   this.bgGeo.on('geofenceschange', this.onGeofenceChange.bind(this));
   this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));

   // 3. Configure it.
   this.bgGeo.configure({
     debug: true,
     desiredAccuracy: 0,
     distanceFilter: 10,
     stopOnTerminate: true,
     preventSuspend: true,
     logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
     url: `${environment.apiUrl}/trip_locations`,
     autoSync: true
   }, (state) => {
     // 4. Start the plugin.
     if (!state.enabled) {
       this.bgGeo.start();
     }
   });
 }

 addGeofence(name: string, radius: number, location: GeoCoordinate): void {
   this.bgGeo.addGeofence({
    identifier: name,
    radius: radius, //in meters
    latitude: location.latitude,
    longitude: location.longitude,
    notifyOnEntry: true,
    notifyOnExit: true
  }).then((success) => {
    console.log('[addGeofence] success', success);
  }).catch((error) => {
    console.log('[addGeofence] FAILURE: ', error);
  });
 }

 removeGeofences(): void {
   this.bgGeo.removeGeofences().then(success => {
    console.log('[removeGeofences] all geofences have been destroyed');
  })
 }

 onLocation(location, taskId) {
   console.log('- location: ', location);
   console.log('- taskId: ', taskId);
   this.currentLocation.next({latitude: location.coords.latitude, longitude: location.coords.longitude});
   this.bgGeo.finish(taskId);
 }
 onGeofence(params, taskId) {
   console.log('- geofence: ', params);
   this.bgGeo.finish(taskId);
 }
 onGeofenceChange(params, taskId) {
   console.log('- onGeofenceChange: ', params);
   this.bgGeo.finish(taskId);
 }
 onHttpSuccess(response) {
   console.log('- http success: ', response);
 }
 onHttpFailure(response) {
   console.log('- http failure: ', response);
 }
 stop():void {
   this.bgGeo.stop();
 }

}
```

## Expected Behavior
I'm trying to get a notification from onGeofence, when the user enters in the destination point radius.

## Actual Behavior

Never gets into this part `onGeofence(params, taskId) { }`
or this one `onGeofenceChange`

## Steps to Reproduce

1. Set up the plugin locationTrackerService.configureBackgroundGeolocation()
2. Add a geofence LocationTrackerService.addGeofence('test, 1609, {latitude: xx.xxxx, longitude: yy.yyyy})

## Debug logs
[Console.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2555502/Console.txt)

**Comment by christocracy** [comment]
What’s your radius?

**Comment by utiq** [comment]
1609

**Comment by christocracy** [comment]
See wiki “Debugging” and show me some logs from the plugin.

Btw, you can use new Typescript api for the plugin and `import BackgroundGeolocation`.  See the README for more information.  It has nothing to do with your issue.

**Comment by utiq** [comment]
I already attached the logs in the "Debug logs" section of your template https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2555502/Console.txt

**Comment by christocracy** [comment]
the plugin is not finding any geofences to monitor within 1000 meters of your geofence.
```
2018-11-06 15:23:56.644 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager evaluateProximity:] Found 0 / 1 within 1000 m
╚═══════════════════════════════════════════════════════════
```
Show me all the attributes of your geofence that you're monitoring.

**Comment by utiq** [comment]
All of that is in the code that I pasted in your template.

```
addGeofence(name: string, radius: number, location: GeoCoordinate): void {
   this.bgGeo.addGeofence({
    identifier: name,
    radius: radius, //in meters
    latitude: location.latitude,
    longitude: location.longitude,
    notifyOnEntry: true,
    notifyOnExit: true
  }).then((success) => {
    console.log('[addGeofence] success', success);
  }).catch((error) => {
    console.log('[addGeofence] FAILURE: ', error);
  });
 }
```

**Comment by christocracy** [comment]
I want to the *actual* latitude / longitude you're using.

**Comment by utiq** [comment]
37.794353, -122.398497

**Comment by utiq** [comment]
That works.
I'm allowing my users to customize the geofence between 1 to 15 miles. Should I configure the background position tracking with the maximum miles? or I should initialize it based on the user choice? like the example I sent you, 1609 meters(1 mile)
You know what I mean?

Something else, in your documentation https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.geofence.html
Shouldn't be 'catch(' instead of ... .catchError((error) => { ... ?

**Comment by christocracy** [comment]
You should be configuring the geofenceProximityRadius to be greater than any geofence radius you add.  The plugin will need added intelligence to take this into account.

For the docs, yes.  I ported the examples over from the new Flutter version.  That’s `dart` syntax. It should be `catch`.

**Comment by utiq** [comment]
One question about this, can I reconfigure the geofenceProximityRadius?
For example:
I configured it with a proximity radius of 1000

`
this.bgGeo.configure({ geofenceProximityRadius: 1000 }) ...
`

But later I add a geofence which radius is 1500, can I change the BackgroundGeolocation geofenceProximityRadius to +1600?

**Comment by christocracy** [comment]
You can change it at any time -- the change will be reflected immediately.

Observe this animation where I toggle between `1000` / `5000` in simulator where I've loaded hundreds of geofences along the Freeway Drive route:

![](https://dl.dropboxusercontent.com/s/2383sr3y3fuf3r0/geofenceProximityRadius.gif?dl=1)

**Comment by christocracy** [comment]
Any btw, `#configure` is deprecated.  Use the new `#ready` method.
