### ISSUE TITLE
ERROR in Release Mode.

### ISSUE THREAD

**Issue by laychar** [transistorsoft/cordova-background-geolocation-lt#826]
## Your Environment
* Plugin version:2.14.1
* Platform: Android @8.0
* Device manufacturer / model: galaxy s7
* Cordova version (`cordova -v`): 8.0.0

It works well. But when in release mode, my device can not  get location or send the data to server.

**Comment by christocracy** [comment]
Yes, plugin works and is in use by thousands of paying customers including Fortune 500 companies.

You’re not helping yourself without posting *any* kind of evidence, especially plugin logs.

**Comment by christocracy** [comment]
Have you purchased a license?  You’re posting this to the public repo.

**Comment by christocracy** [comment]
Remove the "-lt" *from the url*.
[](https://dl.dropboxusercontent.com/s/ojj9ajpxv8wewec/Screenshot%202018-11-06%2020.28.54.png?dl=1)

>Btw is there anyone who has same issue which I have?

How can I possibly tell?  You're not posting *any* kind of evidence.  Your report was basically "It doesn't work".
