### ISSUE TITLE
http transfer suspended when app in background

### ISSUE THREAD

**Issue by locsim** [transistorsoft/cordova-background-geolocation-lt#830]
Plugin version: 2.13.1
    Platform: Android
    OS version: 8.1.0
    Device manufacturer / model: Oneplus 5T
    Cordova version (cordova -v): 8.0.0
    Cordova platform version (cordova platform ls): android 7.0.0
    Plugin config

{
"activityRecognitionInterval": 1000,
"allowIdenticalLocations": false,
"autoSync": true,
"autoSyncThreshold": 0,
"batchSync": false,
"debug": true,
"deferTime": 0,
"desiredAccuracy": 0,
"desiredOdometerAccuracy": 100,
"disableElasticity": false,
"disableStopDetection": false,
"distanceFilter": 30,
"elasticityMultiplier": 1,
"enableHeadless": false,
"extras": {},
"fastestLocationUpdateInterval": 1000,
"forceReloadOnBoot": false,
"forceReloadOnGeofence": false,
"forceReloadOnHeartbeat": false,
"forceReloadOnLocationChange": false,
"forceReloadOnMotionChange": false,
"forceReloadOnSchedule": false,
"foregroundService": true,
"geofenceInitialTriggerEntry": false,
"geofenceProximityRadius": 1000,
"geofenceTemplate": "",
"headers": {},
"headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
"heartbeatInterval": 60,
"httpRootProperty": "location",
"httpTimeout": 60000,
"isMoving": false,
"locationTemplate": "",
"locationTimeout": 60,
"locationUpdateInterval": 30000,
"locationsOrderDirection": "ASC",
"logLevel": 5,
"logMaxDays": 3,
"maxBatchSize": -1,
"maxDaysToPersist": 1,
"maxRecordsToPersist": -1,
"method": "POST",
"minimumActivityRecognitionConfidence": 50,
"notificationColor": "",
"notificationLargeIcon": "",
"notificationPriority": 0,
"notificationSmallIcon": "",
"notificationText": "en service",
"notificationTitle": "Ootigo",
"params": {
"code_emetteur": "XXXXXX",
"app_version": "2.6.5"
},
"persist": true,
"schedule": [],
"startOnBoot": false,
"stationaryRadius": 25,
"stopAfterElapsedMinutes": 0,
"stopOnStationary": false,
"stopOnTerminate": true,
"stopTimeout": 0,
"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
"url": "https:xxxxxxxxxxxxxxx.php",
"enabled": false,
"schedulerEnabled": false,
"trackingMode": 1,
"odometer": 0,
"isFirstBoot": true
}

Hi everyone,

I'm facing a really annoying issue: http connections are queued by Android (or Oneplus Oxygen layer) when my app is in the background.
-http connections managed by the plugin work perfectly, even in the background
-http connections managed by the javascript code work for a few minutes after the app is send to background, then stop, obviously queued by Android, and are trigerred when the app comes back to the foreground.

Battery optimization is disabled.
Surprisingly, there is a setup in android 8.1 to prevent/allow an app to transfer data when in background. Looks like this setup is ignored by my phone.

I'm pretty sure this is NOT due to the plugin, but I would like to know if someone else faced this, or has ideas about this.
Thank you!

**Comment by vladimircojuhari** [comment]
Hi. I have something similar. 
I created a new ionic applicaation  and just put this plugin. The app asks me geo permissions and after this imidiatly crashes. 
My phone is android 9. As i understood android doesnt allow background processes. how to avoid this? 
Thx

**Comment by locsim** [comment]
Hi,
Well, it looks quite different: my app will not crash.

**Comment by StevenMapes** [comment]
@vladimircojuhari 
> Hi. I have something similar.
> I created a new ionic applicaation and just put this plugin. The app asks me geo permissions and after this imidiatly crashes.
> My phone is android 9. As i understood android doesnt allow background processes. how to avoid this?
> Thx
> p.s.
> on android 7.1 works ok

Was this on a full build or a development build? It it7s the former do you have a license as, if not, it will cause the app to crash as you've described. This is different to the ops quesiton

**Comment by christocracy** [comment]
@vladimircojuhari 
>and after this imidiatly crashes.

When an Android app crashes, it print the stacktrace to `logcat`.  Show me the stacktrace.  Boot your app and observe `$ adb logcat`

**Comment by locsim** [comment]
Sounds like vladimircojuhari's issue and the one I described are different. It would be much clearer if this could be moved to another thread.

**Comment by locsim** [comment]
I did some new tests. It appears that it works like a charm when the phone is connected with wifi.

**Comment by christocracy** [comment]
@locsim agreed.  @vladimircojuhari, this issue has *nothing to do with an app crash.*.  Open a new issue.

**Comment by locsim** [comment]
A Google Play Service update solved this. No idea how nor why. 
Can you see some logic, Chris?

**Comment by christocracy** [comment]
No idea.  Android has been undergoing a lot of changes with background operation since os version 8.

**Comment by locsim** [comment]
Thank you. Have a nice day.

**Comment by christocracy** [comment]
Btw @locsim, I noticed you hadn’t renewed your yearly-maintenance fee.  I won’t be so quick to respond in the future ;)
