### ISSUE TITLE
GPS occasionally jumping

### ISSUE THREAD

**Issue by SpellCraft** [transistorsoft/cordova-background-geolocation-lt#832]
## Your Environment
* Plugin version: Git head
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Motorola / XT1635-02
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 7.1.1
* Plugin config
```JavaScript
{
  desiredAccuracy: 0,
  distanceFilter: 1,
  disableElasticity: true,
  locationUpdateInterval: 2000,
  fastestLocationUpdateInterval: 1000,
  geofenceInitialTriggerEntry: true,
  activityRecognitionInterval: 0,
  stopTimeout: 180,
  stopOnTerminate: false,
  foregroundService: true,
  notificationTitle: 'GoMap',
  notificationColor: '#0bb752',
  geofenceProximityRadius: 200,
  preventSuspend: true,
  heartbeatInterval: 60,
  debug: false,
  logLevel: bgGeo.LOG_LEVEL_VERBOSE,
  logMaxDays: 3,
},
```

## Expected Behavior
What we're trying to achieve is having the GPS update as often as possible but not later than every couple few seconds (2-5). This is so that we get the best possible tracking in our app as it's used out in the terrain, hiking, etc.

## Actual Behavior
It seems like the GPS sometimes gets stuck and starts spiking hard. See screenshots under for reference:
https://i.imgur.com/6w9TYRY.jpg
https://i.imgur.com/BJYiV1W.jpg
https://i.imgur.com/YXZNemc.jpg
https://i.imgur.com/n2SRx5A.jpg

## Context
What we're trying to do is creating a battery efficient gps tracker app that can be used while hiking, in the mountains etc.

## Debug logs
https://api.gomap.no/gps-logs/4c73be7c-4aaf-44bc-b584-8b5c8b5235d1-1541950430.json

**Comment by christocracy** [comment]
This is not unusual.  When GPS is unavailable due to environmental conditions (in your case, probably blocked by the terrain), the device will fall back to providing a location from the Cellular radio (where accuracy is typically 1000 meters or more.

You'll see a correspondingly poor accuracy in those jumps.

**Comment by christocracy** [comment]
Btw, @SpellCraft  I see your support subscription is expired.

**Comment by SpellCraft** [comment]
@christocracy Ah, crap I hadn't noticed that, thought it would automatically recur on the company card, but I'll fix that once I'm in the office again in the morning.

Simply adding a check for desired accuracy in meters on the *accuracy* property from the location.coords object should fix this, then. I've not really thought about it before.
