### ISSUE TITLE
How to stop Motion usage

### ISSUE THREAD

**Issue by sunnymtl** [transistorsoft/cordova-background-geolocation-lt#833]
* Plugin version: 2.12.2
* Platform: iOS 
* OS version: 10.13

In my application, the only method I use is getCurrentPosition(), which is called when the BLE device is disconnected from the phone in order to get the disconnected location.

In order to submit to App Store, I'm facing this from the App Store: "The app's Info.plist file should contain a NSMotionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. "

Is there a way to not use the NSMotionUsageDescription key in the plugin because I have no reason to use the Motion detection in the app? so the app will not be rejected by the App Store.

Thanks a lot!

**Comment by christocracy** [comment]
See docs for `disableMotionActivityUpdates`.

**Comment by sunnymtl** [comment]
Thank you Chris!

**Comment by christocracy** [comment]
I thought you were using the Mauron85 version.

**Comment by sunnymtl** [comment]
I'm using your plugin : )
I have tried to set disableMotionActivityUpdates: true, I didn't get motion usage permission request but the privacy information is still displayed in info.plist.  Is there a why to remove NSMotionUsageDescription key completely? or maybe I have to try to submit it like this to see if they accept it? Thanks!

**Comment by christocracy** [comment]
>Is there a why to remove NSMotionUsageDescription key completely

No, Cordova doesn't doesn't provide a way to *conditionally add* [elements in the `plugin.xml`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L53-L55) spec.

Try submitting with the `NSMotionUsageDescription`.  If that doesn't work, you'll have to manually remove the key in XCode or make a hook script to manually remove it.

![](https://dl.dropboxusercontent.com/s/m7g4mu2kuddjxsg/Screenshot%202018-11-20%2020.44.23.png?dl=1)

**Comment by sunnymtl** [comment]
I have tried to manually remove the key in XCode but they send me an email saying that info.plist should contain the NSMotionUsageDescription key. So I just submitted the app with the motion key,  let's see if they accept it. Thanks anyways!

**Comment by christocracy** [comment]
Did you also `disableMotionActivityUpdates: true` when you removed the `NSMotionUsageDescriptionKey`?

**Comment by sunnymtl** [comment]
Yes, I did.
