### ISSUE TITLE
URL template object within array results in an appended empty object

### ISSUE THREAD

**Issue by willmero** [transistorsoft/cordova-background-geolocation-lt#834]
## Your Environment
* Plugin version: 2.14.0
* Platform: iOS
* OS version: iOS 12.1
* Device manufacturer / model: iPhone X
* Cordova version (`cordova -v`): 8.1.1
* Cordova platform version (`cordova platform ls`): ios 4.5.5
* Plugin config
```javascript
reset             : true,
						debug             : true,
						logLevel          : bgGeo.LOG_LEVEL_VERBOSE,
						desiredAccuracy   : bgGeo.DESIRED_ACCURACY_HIGH,
						distanceFilter    : 10,
						url               : '/location',
						autoSync          : true,
						stopOnTerminate   : false,
						startOnBoot       : true,
						httpRootProperty  : '.',
						locationTemplate  : '[{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"time":1541980254459}]',
						preventSuspend    : true,
						heartbeatInterval : 60,
						headers           : {
					      Authorization : 'Bearer ${idToken}',
```

## Expected Behavior

When I use the locationTemplate `'[{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"time":1541980254459}]',` I expect to see a resulting body of `[{latitude:'123', Longitude:'123', time:'123'}]`
## Actual Behavior

It would seem that the plugin is adding an extra blank object to the end of the body like so:
[{latitude:'123', Longitude:'123', time:'123'}, {}]
## Steps to Reproduce

1.  Instantiate the plugin with the above config and template
2. Open app and attempt to send location to server
3. Inspect post body and see blank object appended to array

## Context

At some point I would like to sync over an array of location points, but for now I need to send it over as a single object array
## Debug logs
Just some HTTP 400 errors from my server upon getting a blank object inside the array

**Comment by christocracy** [comment]
Your template is weird.  Why are you wrapping your template in an `[ ]`?

If you want an `{}` template:
```
locationTemplate: '{"latitude": <%= latitude %>, "longitude": <%= longitude %>}'
```
If you want an `[ ]` template:
```
locationTemplate: '[<%= latitude %>, <%= longitude %>]`
```
But don't *mix* them together.

The extra `{ }` you're seeing is the optional `#extras`

If I configure: 
```
extras: {foo: "bar"},
locationTemplate: '[<%= latitude %>, <%= longitude %>]'
```

I'll see this at my server:
```
POST /locations_template
{
  "location": [
    37.41652076,
    -122.21132892,
    {
      "foo": "bar"  // <-- extras
    }
  ]  
}
```

**Comment by willmero** [comment]
@christocracy I suppose I can update my API endpoint to accept just a single object instead, but going forward, it would be nice to have the ability to sync location objects over in bulk (in an array) instead of one at a time.

**Comment by christocracy** [comment]
That precisely what [`batchSync: true`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#batchsync) is for.
