### ISSUE TITLE
Android app - No geofence events - java.lang.NoSuchMethodError: No static method getFusedLocationProviderClient(Landroid/content/Context;)Lcom/google/android/gms/location/FusedLocationProviderClient

### ISSUE THREAD

**Issue by RonaldVanAken** [transistorsoft/cordova-background-geolocation-lt#837]
## Your Environment
* Plugin version: 2.11
* Platform:  Android
* OS version: Android 8.0
* Device manufacturer / model: Samsung
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): Android Cordova 6.3.0
* Plugin config

                                                                    ╔═════════════════════════════════════════════
                                                                    ║ TSLocationManager version: 2.12.13 (269)
                                                                    ╠═════════════════════════════════════════════
                                                                    {
                                                                      "activityRecognitionInterval": 10000,
                                                                      "allowIdenticalLocations": false,
                                                                      "autoSync": true,
                                                                      "autoSyncThreshold": 0,
                                                                      "batchSync": false,
                                                                      "debug": true,
                                                                      "deferTime": 0,
                                                                      "desiredAccuracy": 1,
                                                                      "desiredOdometerAccuracy": 100,
                                                                      "disableElasticity": false,
                                                                      "disableStopDetection": false,
                                                                      "distanceFilter": 1,
                                                                      "elasticityMultiplier": 1,
                                                                      "enableHeadless": false,
                                                                      "extras": {},
                                                                      "fastestLocationUpdateInterval": 10000,
                                                                      "forceReloadOnBoot": false,
                                                                      "forceReloadOnGeofence": true,
                                                                      "forceReloadOnHeartbeat": false,
                                                                      "forceReloadOnLocationChange": true,
                                                                      "forceReloadOnMotionChange": true,
                                                                      "forceReloadOnSchedule": false,
                                                                      "foregroundService": false,
                                                                      "geofenceInitialTriggerEntry": true,
                                                                      "geofenceProximityRadius": 1000,
                                                                      "geofenceTemplate": "",
                                                                      "headers": {},
                                                                      "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
                                                                      "heartbeatInterval": -1,
                                                                      "httpRootProperty": "location",
                                                                      "httpTimeout": 60000,
                                                                      "isMoving": false,
                                                                      "locationTemplate": "",
                                                                      "locationTimeout": 60,
                                                                      "locationUpdateInterval": 1000,
                                                                      "locationsOrderDirection": "ASC",
                                                                      "logLevel": 4,
                                                                      "logMaxDays": 3,
                                                                      "maxBatchSize": -1,
                                                                      "maxDaysToPersist": 1,
                                                                      "maxRecordsToPersist": -1,
                                                                      "method": "POST",
                                                                      "minimumActivityRecognitionConfidence": 75,
                                                                      "notificationColor": "",
                                                                      "notificationLargeIcon": "",
                                                                      "notificationPriority": 0,
                                                                      "notificationSmallIcon": "",
                                                                      "notificationText": "Location Service activated",
                                                                      "notificationTitle": "",
                                                                      "params": {
                                                                        "userId": "+"
                                                                      },
                                                                      "persist": true,
                                                                      "schedule": [],
                                                                      "startOnBoot": false,
                                                                      "stationaryRadius": 25,
                                                                      "stopAfterElapsedMinutes": 0,
                                                                      "stopOnStationary": false,
                                                                      "stopOnTerminate": false,
                                                                      "stopTimeout": 5,
                                                                      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                      "url": "<<removed>>",
                                                                      "enabled": true,
                                                                      "schedulerEnabled": false,
                                                                      "trackingMode": 0,
                                                                      "odometer": 0,
                                                                      "isFirstBoot": false
                                                                    }
                                                                    ╔═════════════════════════════════════════════
                                                                    ║ DEVICE SENSORS
                                                                    ╠═════════════════════════════════════════════
                                                                    ╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSL Acceleration Sensor", vendor="STM", version=1, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.25, minDelay=2000}
                                                                    ╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSL Gyroscope Sensor", vendor="STM", version=1, type=4, maxRange=17.453293, resolution=6.1086525E-4, power=6.1, minDelay=2000}
                                                                    ╟─ ✅  MAGNETOMETER: {Sensor name="AK09916C Magnetic field Sensor", vendor="Asahi Kasei Microdevices", version=1, type=2, maxRange=2000.0, resolution=0.06, power=6.0, minDelay=10000}
                                                                    ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="SAMSUNG Significant Motion Sensor", vendor="Samsung Inc.", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=-1}
                                                                    ╚═════════════════════════════════════════════
11-26 07:12:48.553 13470-13747/com.t I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                      ✅  Google Play Services: connected (version code:12451000)
11-26 07:12:48.572 13470-13747/com.t D/TSLocationManager: [c.t.locationmanager.data.a.c a] 
                                                                      ✅  Opened database
11-26 07:12:48.578 13470-13747/com.t D/TSLocationManager: [c.t.locationmanager.data.a.c prune] 
                                                                      ℹ️  PRUNE -1 days
11-26 07:12:48.598 13470-13747/com.t D/TSLocationManager: [c.t.locationmanager.data.a.a f] 
                                                                      ✅  Opened database
11-26 07:12:48.610 13470-13747/com.t D/TSLocationManager: $ addLocationListener()
11-26 07:12:48.612 13470-13747/com.t D/TSLocationManager: $ addMotionChangeListener()
11-26 07:12:48.614 13470-13747/com.t D/TSLocationManager: $ addGeofenceListener()
11-26 07:12:48.616 13470-13747/com.t D/TSLocationManager: $ addHttpListener()
11-26 07:12:48.620 13470-13747/com.t D/TSLocationManager: $ configure()
11-26 07:12:48.645 13470-13747/com.t D/TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-26 07:12:48.661 13470-13747/com.t D/TSLocationManager: [c.t.locationmanager.util.b a] 
                                                                      ℹ️  LocationAuthorization: Permission granted
11-26 07:12:48.667 13470-13747/com.t W/TSLocationManager: [c.t.l.a.BackgroundGeolocation$26 onPermissionGranted] 
                                                                      ⚠️  Already started geofences.  Ignored
11-26 07:12:48.678 13470-13747/com.t D/TSLocationManager: [c.t.l.http.HttpService flush] 
                                                                    ╔═════════════════════════════════════════════
                                                                    ║ HTTP Service
                                                                    ╠═════════════════════════════════════════════
11-26 07:12:48.685 13470-13747/com.t D/TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :true
11-26 07:12:48.697 13470-13747/com.t W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.configure blocked the main thread for 78ms. Plugin should use CordovaInterface.getThreadPool().
11-26 07:12:48.700 13470-13747/com.t D/TSLocationManager: $ startGeofences()
11-26 07:12:48.702 13470-13747/com.t D/TSLocationManager: [c.t.locationmanager.util.b a] 
                                                                      ℹ️  LocationAuthorization: Permission granted
11-26 07:12:48.709 13470-13747/com.t W/TSLocationManager: [c.t.l.a.BackgroundGeolocation$26 onPermissionGranted] 
                                                                      ⚠️  Already started geofences.  Ignored
11-26 07:12:48.718 13470-13747/com.t W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.startGeofences blocked the main thread for 18ms. Plugin should use CordovaInterface.getThreadPool().
11-26 07:12:48.722 13470-13747/com.t D/TSLocationManager: $ addGeofence()
11-26 07:12:48.726 13470-13747/com.t D/TSLocationManager: $ addGeofence()
11-26 07:12:48.727 13470-13747/com.t D/TSLocationManager: $ startGeofences()
11-26 07:12:48.729 13470-14091/com.t I/TSLocationManager: [c.t.locationmanager.data.a.a a] 
                                                                      ✅  8db7cR6Nr5aEgsFwc
11-26 07:12:48.729 13470-13747/com.t D/TSLocationManager: [c.t.locationmanager.util.b a] 
                                                                      ℹ️  LocationAuthorization: Permission granted
11-26 07:12:48.737 13470-14091/com.t I/TSLocationManager: [c.t.locationmanager.data.a.a a] 
                                                                      ✅  8db7cR6Nr5aEgsFwc
11-26 07:12:48.741 13470-13747/com.t W/TSLocationManager: [c.t.l.a.BackgroundGeolocation$26 onPermissionGranted] 
                                                                      ⚠️  Already started geofences.  Ignored
11-26 07:12:48.755 13470-13747/com.t W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.startGeofences blocked the main thread for 28ms. Plugin should use CordovaInterface.getThreadPool().
11-26 07:12:48.756 13470-14092/com.t I/TSLocationManager: [c.t.locationmanager.data.a.a a] 

## Expected Behavior
No crash and geofence should be triggered once we register the available geofences.

## Actual Behavior
GeoFence events do not get triggered. I do notice a stack trace related to the component in the debug logs.

11-26 07:16:36.002 13470-13747/com.t D/TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-26 07:16:36.014 13470-13747/com.t W/System.err: java.lang.NoSuchMethodError: No static method getFusedLocationProviderClient(Landroid/content/Context;)Lcom/google/android/gms/location/FusedLocationProviderClient; in class Lcom/google/android/gms/location/LocationServices; or its super classes (declaration of 'com.google.android.gms.location.LocationServices' appears in /data/app/com.t-hHz3JuKNJnLgHT5A==/base.apk)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:17)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at com.transistorsoft.locationmanager.location.TSCurrentPositionRequest.<init>(Unknown Source:30)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at com.transistorsoft.locationmanager.location.TSCurrentPositionRequest$Builder.build(Unknown Source:2)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.ready(Unknown Source:70)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.configure(CDVBackgroundGeolocation.java:315)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.execute(CDVBackgroundGeolocation.java:152)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:325)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at android.os.Looper.loop(Looper.java:142)
11-26 07:16:36.014 13470-13747/com.t W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

**config.xml (snippet)**
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.1.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="^2.0.2" />
    <plugin name="cordova-plugin-add-swift-support" spec="^1.7.2" />
    <plugin name="cordova-plugin-qrscanner" spec="^2.6.0" />
    <plugin name="cordova-plugin-globalization" spec="^1.11.0" />
    <plugin name="cordova-sqlite-storage" spec="^2.5.1" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="ionic-plugin-deeplinks" spec="^1.0.17">
   
    </plugin>
    <plugin name="cordova-plugin-fcm" spec="^2.1.2" />
    <engine name="android" spec="~6.3.0" />
    <plugin name="cordova-background-geolocation" spec="https://github.com/transistorsoft/cordova-background-geolocation.git#2.11.0">
        <variable name="LICENSE" value="removed" />
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="uses your location to see if you are near or at an event or festival." />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="uses your location to see if you are near or at an event or festival." />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="uses your location when using the app to see if you are near or at an event or festival." />
        <variable name="MOTION_USAGE_DESCRIPTION" value="will collect your motion usage in order to better understand your movements during an event or festival." />
        <variable name="GOOGLE_API_VERSION" value="9.0.0" />
        <variable name="APPCOMPAT_VERSION" value="27.0.0" />
    </plugin>

**package.json:**
"dependencies": {
    "@angular-devkit/build-optimizer": "0.0.36",
    "@angular/common": "^5.1.3",
    "@angular/compiler": "^5.1.3",
    "@angular/compiler-cli": "^5.1.3",
    "@angular/core": "^5.1.3",
    "@angular/forms": "^5.1.3",
    "@angular/http": "^5.1.3",
    "@angular/platform-browser": "^5.1.3",
    "@angular/platform-browser-dynamic": "^5.1.3",
    "@awaitbox/meteor-startup": "^1.0.4",
    "@ionic-native/barcode-scanner": "^4.5.2",
    "@ionic-native/camera": "^4.5.2",
    "@ionic-native/core": "^4.5.2",
    "@ionic-native/fcm": "^4.5.3",
    "@ionic-native/globalization": "^4.5.2",
    "@ionic-native/in-app-browser": "^4.5.2",
    "@ionic-native/network": "^4.5.3",
    "@ionic-native/qr-scanner": "^4.5.2",
    "@ionic-native/splash-screen": "^4.5.2",
    "@ionic-native/status-bar": "^4.5.2",
    "@ionic/storage": "^2.1.3",
    "@types/jasmine": "^2.8.6",
    "@types/jquery": "^3.3.0",
    "@zxing/ngx-scanner": "^1.2.1",
    "android-versions": "^1.2.2",
    "angular2-qrcode": "^2.0.1",
    "angular2-text-mask": "^8.0.4",
    "autoprefixer": "^7.2.4",
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "bluebird": "^3.5.1",
    "chai": "^4.1.2",
    "cordova-android": "6.3.0",
    "cordova-background-geolocation": "git+https://github.com/transistorsoft/cordova-background-geolocation.git#2.11.0",
    "cordova-plugin-add-swift-support": "^1.7.2",
    "cordova-plugin-background-fetch": "^5.3.0",
    "cordova-plugin-cocoalumberjack": "0.0.4",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-fcm": "^2.1.2",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-inappbrowser": "^2.0.2",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-qrscanner": "^2.6.0",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-swift-support": "^3.1.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.5.2",
    "ion-multi-picker": "^2.1.2",
    "ionic-angular": "^3.9.2",
    "ionic-native": "^2.9.0",
    "ionic-plugin-deeplinks": "^1.0.17",
    "ionicons": "^3.0.0",
    "jquery": "^3.3.1",
    "jsencrypt": "^3.0.0-rc.1",
    "lodash": "^4.17.4",
    "meteor-client": "^1.3.1",
    "meteor-client-bundler": "^0.3.0",
    "meteor-node-stubs": "^0.3.2",
    "meteor-rxjs": "^0.4.8",
    "ng2-translate": "^5.0.0",
    "ngx-qrcode2": "0.0.5",
    "node-fetch": "^1.7.3",
    "node-jsencrypt": "^1.0.0",
    "rxjs": "^5.5.6",
    "setimmediate": "^1.0.5",
    "simple-plist": "^0.2.1",
    "tslib": "^1.8.1",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/tsc-wrapped": "^4.4.6",
    "@ionic/app-scripts": "^3.1.7",
    "@types/bluebird": "^3.5.19",
    "@types/lodash": "^4.14.92",
    "@types/meteor": "^1.4.12",
    "@types/meteor-accounts-phone": "0.0.5",
    "@types/meteor-collection-hooks": "^0.8.3",
    "@types/mocha": "^2.2.48",
    "@types/node-fetch": "^1.6.7",
    "tmp": "0.0.33",
    "typescript": "^2.9.2",
    "typescript-extends": "^1.0.1",
    "webpack": "^3.10.0"
  },
  "description": "Client - App",
  "config": {
    "ionic_webpack": "./webpack.config.js",
    "ionic_source_map": "source-map"
  },

**Comment by christocracy** [comment]
You're using an incompatible `play-services:location` version (`GOOGLE_API_VERSION`).

Post the entire contents of file `platforms/android/project.properties`.

**Comment by christocracy** [comment]
Do you know how old `play-services-location:9.0.0` is?  [May 2016](https://developers.google.com/android/guides/releases).  About 2 1/2 years old.

![](https://dl.dropboxusercontent.com/s/8jbnzeelh91v166/Screenshot%202018-11-26%2010.28.53.png?dl=1)

```diff
cordova.system.library.3=com.google.android.gms:play-services-location:16.0.0
```
