### ISSUE TITLE
i have this issue Cannot call method 'configure' of undefined

### ISSUE THREAD

**Issue by mrqaidi** [transistorsoft/cordova-background-geolocation-lt#84]
i  am trying to use this plugin in my  ionic project and i am getting this error

Cannot call method 'configure' of undefined

`        bgGeo = window.plugins.BackgroundGeolocation;

    // BackgroundGeoLocation is highly configurable. See platform specific configuration options
    bgGeo.configure(callbackFn, failureFn, {
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates
    });
`

please help

**Comment by christocracy** [comment]
This plugin's javascript API is available at 
```
window.BackgroundGeolocation
```

**NOT**
```
window.plugins.BackgroundGeolocation
```
