### ISSUE TITLE
Clear or terminated from task manager

### ISSUE THREAD

**Issue by Jitendranagar** [transistorsoft/cordova-background-geolocation-lt#840]
## Your Environment
• Plugin version:2.13.2
• * Platform:  Android
• * OS version: 5.1 above
• * Device manufacturer / model:Vivo,oppo,redmi,xiaomi
• * Cordova version (`cordova -v`):8.0.0
• * Android Platform version:7.0.0
• * hybrid platform: Ionic 3

• Plugin config    
•   isMoving: false,  
•  autoSync: true,   
•  elasticityMultiplier: 1,   
•   stopTimeout: 5,  
•  stopOnStationary: false,     
•  stopOnTerminate: false,    
•  debug: false,    
•  disableElasticity: false,   
• fastestLocationUpdateInterval: 50000,        
• maxDaysToPersist: 3, 
• distanceFilter: 10,        
• desiredAccuracy: 0,      
• motionActivity: 'Activity',     
• menuActive: false,   
• heartbeatInterval: 60,        
• autoSyncThreshold: 0,       
• logLevel: this.bgGeo.LOG_LEVEL_VERBOSE

**Comment by christocracy** [comment]
Chinese devices are the worst.  You generally need to manually "Whitelist" these apps (usually in Settings->Battery) and tell the operating system to let your app run in the background.

On my Huawei P20, it's like this:  
- `Settings->Battery->Launch`
- Find your app.  toggle switch to disable "automatically manage".
![](https://dl.dropboxusercontent.com/s/7t1dmpc95qqgngi/Screenshot%202018-11-30%2011.57.49.png?dl=1)

On my Xiaomi A2 Lite, I didn't have to do anything.  It works without problem.

**Comment by Talentpro** [comment]
Hi we like to give notification when plugin not running due to this battery settings , is there any solution available to handle this ? i hope android handless job will help right ?

**Comment by christocracy** [comment]
@Talentpro I guess you're the one who emailed me via my chat system.  As I said in the email:  No, Android Headless won't help you.  It's the plugin's foreground-service which is being terminated irrationally by the manufacturer's battery-saving mechanism.  Android headless mode is merely a receiver of data *from* the foreground-service.

**Comment by locsim** [comment]
Hi, on my device (Oneplus 5T), there is an option in setup, advanced, recent app management.
The option is: normal cleaning, OR deep cleaning (also kills background process).
(this might not be the exact english words..)
I hope it can help.

**Comment by christocracy** [comment]
>normal cleaning, OR deep cleaning (also kills background process).

Sounds like something printed on a tube of toothpaste ;)

**Comment by Mike1707** [comment]
Hey @christocracy . Did you ever try the settings which can be opened with the [Cordova OpenNativeSettings](https://github.com/guyromb/Cordova-open-native-settings) plugin using the "battery_optimization" setting? I'm struggling with the same issue and it's very hard to explain to my customers how they should change their settings.

**Comment by christocracy** [comment]
@Mike1707 I don't thing "ignore battery optimizations" is generally required.  Have you seen the site http://dontkillmyapp.com

I added a new beta feature called [DeviceSettings](https://transistorsoft.github.io/cordova-background-geolocation/interfaces/_cordova_background_geolocation_.devicesettings.html) for redirecting the user to appropriate screens.

See the [showPowerManager](https://transistorsoft.github.io/cordova-background-geolocation/interfaces/_cordova_background_geolocation_.devicesettings.html#showpowermanager) method.  

You're still responsible for producing a Dialog for the user to explain exactly what to do.  The plugin will keep track if you've shown this screen already so you don't keep spamming them.

I've acquired for myself the following devices and I test upon them extensively.
- Nokia TA-1027 @ 8.0.0 . <-- THE WORST
- Huawei P20 Lite (ANE-LX3) @ 8.0.0  <-- 2nd WORST
- XIAOMI MI A2 Lite @ 9.0.0  <-- works well without settings tweaks.
- OnePlus A5010 @ 8.0.0  <-- works well without settings tweaks.

My full family of test devices:
- Nexus 4 @ 4.4.4
- Lenovo A6000 @ 5.0.2
- Nexus 5 @ 6.0.1
- Nexus 6 @ 6.0.1
- Google Pixel @ 9.0.0
- Samsung S7 @ 6.0.1
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 8.0.0

**Comment by Mike1707** [comment]
Wow this sounds like a pretty amazing feature! I guess you wouldn't recommend to use the beta version in production, would you?

**Comment by christocracy** [comment]
>I guess you wouldn't recommend to use the beta version in production, would you?

I suggest you start developing and field-testing it right now.  I'm working feverishly the last 2 weeks with a backpack full of devices.  But no, I wouldn't push it to production for another few weeks.

I'm gone on vacation for 10 days beginning this Sunday.  I will probably release a `beta.2` before I leave.
