### ISSUE TITLE
background location not tracking when app is terminated

### ISSUE THREAD

**Issue by ketan-nliven** [transistorsoft/cordova-background-geolocation-lt#841]
## Your Environment
* Plugin version:2.13.2
* Platform:  Android
* OS version: 6 above
* Device manufacturer / model: Only working in Samsung
* Cordova version (`cordova -v`):8.0.0
* Android Platform version:7.0.0
* hybrid platform: Ionic 3+
* Plugin config
        isMoving: false,
        autoSync: true,
        elasticityMultiplier: 1,
        stopTimeout: 5,
        stopOnStationary: false,
        stopOnTerminate: false,
        debug: false,
        disableElasticity: false,
        fastestLocationUpdateInterval: 50000, 
        maxDaysToPersist: 3, 
        distanceFilter: 10,
        desiredAccuracy: 0,  
        motionActivity: 'Activity',
        menuActive: false,
        heartbeatInterval: 60,
        autoSyncThreshold: 0,
        logLevel: this.bgGeo.LOG_LEVEL_VERBOSE

## Expected Behavior
background location plugin also working when app is terminated from task manager

## Actual Behavior

I am using buy able plugin but when i cleared app from recent app list they don't track any thing till then app is start again.

**Comment by christocracy** [comment]
Provide logs.  See Wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging).

**Comment by ShafiqShams** [comment]
@ketan-nliven did you tried the licensed version or the free one?
Secondly I want to know if background tracking works perfectly even when the App is killed on both Android and iOS.

I can purchase this plugin, no issues but the thing is if this gonna work or not.
I JUST WANT TO UPDATE MY SERVER WITH THE UPDATED LOCATION POINTS EVEN WHEN THE APP IS KILLED OR IN BACKGROUND MODE.

**Comment by Steffaan** [comment]
@ShafiqShams don't worry and purchase it. Plugin works great and you won't be dissapointed. We are using it for a couple of years now.

**Comment by christocracy** [comment]
Version 3.0.0 is in the oven.  I've found a way to **not** keep the foreground-service running constantly.  When the device is in stationary-state, there be **no** foreground-service running (nor its corresponding persistent notification).  Even after terminate.

**Comment by ketan-nliven** [comment]
I have new issue found onPowerSaveChange not working in some devices like vivo, oppo, xiaomi and its is not working in background also when app is cleared
