### ISSUE TITLE
custon api with params Http call when app i call when app is in open/background/killed

### ISSUE THREAD

**Issue by naitikpatel1990** [transistorsoft/cordova-background-geolocation-lt#842]
Hey,

I have paid version installed in my corodva app. 

I need to do API call with params 'lat' and 'lon' like following:

"http://serverURL.com/api/sendlocation?lat=" + location.coords.latitude +"&lon=" + location.coords.longitude"

SO should i called this method like:

```
bgGeo.onMotionChange(function(event) {
"http://serverURL.com/api/sendlocation?lat=" + event.location.coords.latitude +"&lon=" + event.location.coords.longitude"
})
```

or same API in **bgGeo.onLocation** .

Inshort i need to call api when app every time user changed location wether app is open, in background or killed.

So any code example for call API like above will be appreciated.

I did checked your demo example of code but it direct set URL without params so need to send PARAMS lat and lon of changed location.

**Comment by christocracy** [comment]
you can’t.  Modify your server to decode JSON from the raw http body.

Appending post data to http query params is a bad idea.  Don’t do that.

**Comment by naitikpatel1990** [comment]
@christocracy 

Can you please give snippet JSON what it get in response on backend ?

**Comment by christocracy** [comment]
Its in the docs.  See “Http Guide”.
https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html

**Comment by naitikpatel1990** [comment]
As in your https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema

in json response i just need  "Lat" and "Lon" in response of JSON in backend api function i don't need deviceid, uuid", battery status and all.

So how can i ignore those in response ?

**Comment by christocracy** [comment]
Read the HTTP Guide.  You might be interested in the locationTemplate option.

**Comment by naitikpatel1990** [comment]
Hey @christocracy 

We didn't get any response json body in api function:

Below is my code for cordova app:

`bgGeo.onLocation(function(location) {
    console.log('[location] -', location);
});

bgGeo.onMotionChange(function(event) {
    console.log('[motionchange] -', event.isMoving, event.location);
});

bgGeo.onHttp(function(response) {
    console.log('[http] - ', response.success, response.status, response.responseText);
});

bgGeo.onProviderChange(function(event) {
    console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
});

// 2. Execute #ready method:
bgGeo.ready({
    reset: true,
    debug: false,
    url: "http://myserver.com/api/locationfunction",
    headers: {
        'Authorization': "Basic Token" // goes to header["Authorization"]
    },
    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true,
    locationTemplate: '{"lat":<%= latitude %>,"lon":<%= longitude %>}'
}, function(state) {    // <-- Current state provided to #configure callback
    // 3.  Start tracking
    console.log('BackgroundGeolocation is configured and ready to use');
    if (!state.enabled) {
    bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
    });
    }
});`


and here is server code:

`// Posts a tech's current location to the Locs table
        public HttpResponseMessage Post(float lat, float lon) {
            var response = new HttpResponseMessage();
            lsiPrincipal = (LSIPrincipal)HttpContext.Current.User;
            try {
                string Tech = lsiPrincipal.UserName;
                if (Tech.Length > 24) Tech = Tech.Substring(0, 24);
                string sql = string.Format("Insert Locs(dt, Tech, lat, lon) select convert(SmallDateTime, GetDate()),'{0}',{1},{2}", Tech, lat, lon);
                runsql(sql, lsiPrincipal.DatabaseConnectString);
                response.StatusCode = System.Net.HttpStatusCode.OK;
                response.Headers.Add("DATA", "Location Added");
                return response;
            } catch (Exception ex) {
                var errormess = ex.Message;
                errormess = errormess.Replace("'", "''");
                CatchAll("LocsPOST", errormess, "null");
                response.StatusCode = System.Net.HttpStatusCode.InternalServerError;
                return response;
            }
        }`

can you please let me know how can i get location? and what response json expected as per above cordova code?

**Comment by christocracy** [comment]
You won’t find the data if you’re expecting it to arrive like a web form post.

The data is arrives as raw JSON text in the “body of the http request”.

Search your particular server framework docs for how to retrieve the “http request body”

**Comment by naitikpatel1990** [comment]
Yes. I got lat/lng in service now.

Now i have issue with "locationTemplate"

When i pass: 

`locationTemplate: '{"lat":<%= latitude %>,"lon":<%= longitude %>}'`

Plugin is working good and getting let/lon in response json,

But when i pass:

`locationTemplate: "{\"lat\":<%= latitude %>,\"lon\":<%= longitude %>,\"ts\":<%= timestamp %>,\"spd\":<%= speed %>}"`

as i need timestamp and speed with location, plugin stopped working not getting location in response json. Did i doing something wrong?

**Comment by christocracy** [comment]
Are you not using `debug: true` and observing the logs (`$ adb logcat -s TSLocationManager`)?

If there's an error in your template, the plugin is going to tell you so (and you *do* have an error).

**Comment by naitikpatel1990** [comment]
<img width="1675" alt="screen shot 2018-12-05 at 6 22 06 pm" src="https://user-images.githubusercontent.com/4089997/49514658-b3443f80-f8ba-11e8-95cc-653ae73a2d3e.png">


this is what i am getting i thing something need to set

**Comment by christocracy** [comment]
Yes, it’s a JSON-parsing error.

You need to manually quote your string data.  Look at your timestamp field.

**Comment by naitikpatel1990** [comment]
this what i passed as locationTemplate:

l`ocationTemplate: '{"lat":<%= latitude %>,"lon":<%= longitude %>,"ts":<%= timestamp %>,"spd":<%= speed %>}'`

**Comment by naitikpatel1990** [comment]
ok got working:

need to pass: 

`locationTemplate: '{"lat":<%= latitude %>,"lon":<%= longitude %>,"ts":"<%= timestamp %>","spd":<%= speed %>}'`

**Comment by christocracy** [comment]
This [is documented](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#locationtemplate)

⚠️ quoting String data.
The plugin does not automatically apply double-quotes around String data. The plugin will attempt to JSON encode your template exactly as you're configured.

The following will generate an error:
```javascript
BackgroundGeolocation.ready({
  locationTemplate: '{"timestamp": <%= timestamp %>}'
});
```
