### ISSUE TITLE
Set Always option for use Location services through plugin

### ISSUE THREAD

**Issue by Geoconcept-mobile** [transistorsoft/cordova-background-geolocation-lt#844]
## Your Environment
* Plugin version: 2.14.0
* Platform: iOS
* OS version:12.1
* Device manufacturer / model: iphone
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
I need to set use of Location services to Always, ask the user to select only always

## Actual Behavior
It Shows three options

## Context
I am trying to track locations based on some timing intervals, I need user to select the only option as "Always" or i need to configure it through plugin configuration, how to succeed that

**Comment by christocracy** [comment]
This is purely in the hands of the operating system.  iOS now **forces** all apps to offer **all three** options as of iOS 11.

The only thing you can do is tell the plugin what you *expect* the user to select via `locationAuthorizationRequest: 'Always'`.  

You can listen to the `onProviderChange` event to learn what the user has selected.  The plugin will automatically show a popup warning the user to select `Always`.
