### ISSUE TITLE
new geofence is called multiple times

### ISSUE THREAD

**Issue by utiq** [transistorsoft/cordova-background-geolocation-lt#845]
The problem is in number 4 (take into account number 1). Find attached log file at the end of this message.

Successful Workflow:
1. Open the app
2. Set geofence
3. User get in the radius
4. **Successful message of geofence in radius**
5. Clear geofences using this.bgGeo.removeGeofences() ...
6. Stop service using this.bgGeo.stop();

unsuccessful scenario:
1. With the app still open
2. Set new geofence (same radius)
3. User get in the radius
4. **Successful message of geofence in radius but fired multiple times**
5. Clear geofences using this.bgGeo.removeGeofences() ...
6. Stop service using this.bgGeo.stop();

## Your Environment
Plugin version: 2.14.0
Platform: iOS
OS version: 12.1
Device manufacturer / model: Apple, iPhone 7, iOS 12.1
Cordova version (cordova -v): 8.1.2 (cordova-lib@8.1.1)
Cordova platform version (cordova platform ls): ios 4.5.5

```
this.bgGeo.ready({
     debug: false,
     desiredAccuracy: 0,
     distanceFilter: 10,
     stopOnTerminate: true,
     preventSuspend: true,
     geofenceProximityRadius: 100,
     // foregroundService: true
     logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
     url: `${environment.apiUrl}/trip_trackings`,
     headers:{
       "Authorization": `Bearer ${localStorage.getItem('auth_token')}`,
     },
     params: {
       trip_id: tripId
     },
     autoSync: true
   }, (state) => {
     // 4. Start the plugin.
     if (!state.enabled) {
       this.bgGeo.start();
       console.log(this.bgGeo);
     }
   });
 }
```

[Console.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2646640/Console.txt)

**Comment by christocracy** [comment]
Can this be reproduced in the simulator?

**Comment by utiq** [comment]
Yes, same result, find the log attached.
[Console-simulator.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2650990/Console-simulator.txt)

**Comment by utiq** [comment]
Could you replicate it?

**Comment by christocracy** [comment]
I cannot reproduce your issue.  Your logs simulator logs do not show a geofence being fired multiple times.  Are you sure you're not *listening to `onGeofence` *multiple times*?  Show me the code you're using to `addGeofence` / `onGeofence`.

Your logs show 2 geofence events for two different `identifier`.

1.
```
2018-12-05 14:56:50.178 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: 8zhz8o
╚═══════════════════════════════════════════════════════════

2018-12-05 14:56:50.180 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: CEB49400-CE2E-41DE-B7CD-FE42900D67D8
```

2. 
```
2018-12-05 14:55:23.323 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: jndzwf
╚═══════════════════════════════════════════════════════════

2018-12-05 14:55:23.324 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: ADCFAD12-270A-4163-9C5C-757C7759DA9E
```
