### ISSUE TITLE
Restart functionality for BackgroundGeolocation service

### ISSUE THREAD

**Issue by mknnaren** [transistorsoft/cordova-background-geolocation-lt#847]
## Your Environment
* Plugin version: 2.14.2
* Platform: iOS and Android
* OS version: Latest
* Device manufacturer / model: iPhoneX and Nokia 5
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): android 7.0.0 and ios 4.5.4

## Context

Hi Chris,

I wanted to know if there is any other way to reset "stopAfterElapsedMinutes" timer apart from stopping and restarting the geolocation service. If I want to reset the the timer for **stopAfterElapsedMinutes**, every time I have to call BackgroundGeolocation.stop() and call BackgroundGeolocation.start() with a timeout of 1 or 2 seconds (because if I call stop and start immediately, an error occurs sometimes due to the stop call would be in progress).

Can you please introduce a new functionality called restart.
I am using this logic to increase the longevity of the services running in the background.

Thank you,
Naren

**Comment by christocracy** [comment]
Why are you using `stopAfterElapsedMinutes`?

**Comment by mknnaren** [comment]
I am using it to run geolocation services for max 2 hours and then kill it
as it was consuming battery if the location service was on all the time.

If the geolocation service is off then geofence accuracy goes down. Most of
the time it won't get triggered.

My main purpose is for geofence only.
I am restarting the service when the app goes to background so that the
service will run for 2 hrs after the user goes inactive.

**Comment by christocracy** [comment]
> as it was consuming battery if the location service was on all the time.

The core [philosophy of operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation) of the plugin is to automatically toggle location-services as required.  You're attempting to needlessly optimize something that's *already optimized for you*.

The plugin does *not* keep location-services constantly on.  If the device is sitting still on your desk, location-services are **OFF**.

>If the geolocation service is off then geofence accuracy goes down. Most of
the time it won't get triggered.

If location-services are **OFF**, locations are not recorded.  It's not a matter of "accuracy".

If you're using geofences-only, you should be using [`#startGeofences`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#startgeofences) not `#start`.

I see no reason for you to be using `stopAfterElaspsedMinutes`.

**Comment by christocracy** [comment]
>when i terminates force the app, and open app agin,how i can continue get watch location

If you're talking about the method `#watchPosition`, you can't

**Comment by JianhuisHuang** [comment]
@christocracy  sorry, not #watchPosition,is location not tracking when app is terminated, how I can get the location when app is terminated? thanks.

**Comment by christocracy** [comment]
Yes, the plugin will continue tracking after terminate.  That's what [`stopOnTerminate`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#stoponterminate) is for.  Read the specifics for each platform.  iOS and Android operate differently.  Read the docs.

**Comment by JianhuisHuang** [comment]
@christocracy  Yes , I know, I set stopOnTerminate as false from /help/docs, but I can't get the location

**Comment by christocracy** [comment]
And did you *read* the platform-specific notes about iOS vs Android in the docs?

If you’re expecting your JavaScript callback to fire with a terminated Android app, the docs explain why that’s not going to happen.

**Comment by JianhuisHuang** [comment]
I know ,my platform is ios,form here [https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/help#config-boolean-stoponterminate-true](stoponterminate)

**Comment by JianhuisHuang** [comment]
I know, my platform is ios, form here 
https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#stoponterminate

**Comment by christocracy** [comment]
Yes, and what do the docs tell you about ios after terminating the app?

**Comment by JianhuisHuang** [comment]
racking resumes but I can't get the push alert and I set debug as true when terminated the application

**Comment by JianhuisHuang** [comment]
[](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#stoponterminate)

**Comment by JianhuisHuang** [comment]
[https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#stoponterminate](url)

**Comment by JianhuisHuang** [comment]
_https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#stoponterminate_

**Comment by JianhuisHuang** [comment]
@christocracy  Hi, how to fix this error ? Error Domain=kCLErrorDomain Code=0 "(null)"   thanks.

**Comment by christocracy** [comment]
That’s a normal error to occur when the device fails to deliver a location.  It will happen, for example, when you walk into a subway station, drive into a tunnel, etc.

It’s like turning on your water tap and no water flows.  It’s not the cup’s fault.  Not the sink’s fault.

**Comment by JianhuisHuang** [comment]
Got it, thanks.

**Comment by Suryalg** [comment]
In my case. 
stopOnTerminate: false,
reset: true,
debug: true,

If i open the app for first time the location is sending through http but after closing the app. after some time it stops sending. I have to re launch the then it sends again though for 5-6 times then again stops is something I am missing?

this is the function i am calling one time onDeviceeady.

function initiate_bg_location() {  
  // 1.  Listen to events
  bgGeo = window.BackgroundGeolocation;

  bgGeo.onLocation(function(location) {
    console.log('[location] -', location);
  });

  bgGeo.onMotionChange(function(event) {
    console.log('[motionchange] -', event.isMoving, event.location);
  });

  bgGeo.onHttp(function(response) {
    console.log('[http] - ', response.success, response.status, response.responseText);
  });

  bgGeo.onProviderChange(function(event) {
    console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
  });

  // 2. Execute #ready method:
  bgGeo.ready({
    reset: true,
    debug: true,
    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
    distanceFilter: 15,
    url: 'http://www.system.dineordertest.com/dineordercc/jsonapi/updatedriverlocations', 
	params: {
            user_Id: getStorage('zxc'),
			store_Server_Ip: getStorage('ssip'),
			store_Id: getStorage('str'),
			product_Id: getStorage('ijk'),  
			
            },
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true
  }, function(state) {    // <-- Current state provided to #configure callback
    // 3.  Start tracking
    console.log('BackgroundGeolocation is configured and ready to use');
    if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
  });

  // NOTE:  Do NOT execute any API methods which will access location-services
  // until the callback to #ready executes!
  //
  // For example, DO NOT do this here:
  //
  // bgGeo.getCurrentPosition();   // <-- NO!
  // bgGeo.start();                // <-- NO!
}

**Comment by christocracy** [comment]
This issue from 2018 is closed.  Post a new issue.
