### ISSUE TITLE
Documentation Fix - relationship of app and plugin is not clear. 

### ISSUE THREAD

**Issue by Yermo** [transistorsoft/cordova-background-geolocation-lt#849]
I have carefully read the Philosophy of Operation document and other documentation and there is some clarification I would like to request. One detail that is not clear to me is the relationship between the plugin and the app.

I was under the impression that the Cordova javascript app and the geolocation plugin were separate processes such that the javascript engine "front end app" could be suspended and frozen and that the background geolocation plugin would continue caching locations /without/ waking up the javascript app. (Thus requiring checking the cache on resume for any new locations that might have come in while the app was sleeping.)

The restartOnBoot option left me with this impression because of the wording 'enable background tracking'. (Or does restartOnBoot launch the whole app?) 

However, the #preventSuspend section seems to imply that whenever the background plugin caches a location the javascript code is woken up and the location event published.

My testing seems to imply the app is always woken up but I'm not sure that this is always the case. 

As a documentation fix, a short paragraph clarifying the relationship and the plugin would be very helpful.  Is the javascript app always woken up whenever a location comes in or can locations come in and be stored in the cache without waking up the app? 

What happens if the app is terminated by the OS? Does the plugin exist separately? 

thanks.

## Your Environment
* Plugin version:

2.13.2

* Platform: iOS or Android

both 

* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
These are debug notifications to assist you during development.  They are enabled with `debug: true`.

**Comment by lav-sttl** [comment]
How to turn off all notification in debug mode only ?

**Comment by christocracy** [comment]
That persistent Android notification is not related to debug mode.  It’s a requirement of Android foreground services.  You cannot remove or hide it.

**Comment by lav-sttl** [comment]
But How to turn off all notification in debug mode only in IOS ?

**Comment by christocracy** [comment]
Obviously, debug: false.  If you find that “not applying”, read carefully the docs for the #ready method, paying special attention to the note about reset: true.

**Comment by lav-sttl** [comment]
I see the accuracy value in my API is 5 m. But location is actually 300 m away from actual location.

**Comment by lav-sttl** [comment]
Tested on IOS Example App :
I follows few steps:
App was in background. 
after few minutes App was terminated by users.

I just move around more than 6 kilometers.
I am just uploading all records to my server by getting getLocations method 

**I see the accuracy value in my API is 5 m. But location is actually 300 m away from actual location.**

1) is it being slow to track geolocation ? 

2) Does it mean that Geolocation tracking is not accurately ?

**Comment by christocracy** [comment]
@lav-sttl you are completely polluting this thread with unrelated posts.  This thread is titled “relationship of app and plugin is not clear.”

All your posts in this thread will be deleted to prevent confusion.

Please post your unrelated questions to a new thread.
