### ISSUE TITLE
Background Geolocation issue for Accuracy

### ISSUE THREAD

**Issue by lav-sttl** [transistorsoft/cordova-background-geolocation-lt#852]
## Your Environment

![screen shot 2018-12-21 at 8 46 37 pm](https://user-images.githubusercontent.com/45941718/50349470-edbc0680-0561-11e9-91d5-2fabde40fc78.png)

* Cordova platform version (`cordova platform ls`): 2.14.0 - IOS

* Plugin config

![screen shot 2018-12-21 at 8 50 53 pm](https://user-images.githubusercontent.com/45941718/50349532-2a87fd80-0562-11e9-8cf1-20ff7989b61e.png)

## Expected Behavior
Location Data should be accurate. 

## Actual Behavior
Getting Geolocation inaccurate data

## Steps to Reproduce

1. Installed Example App in IOS 
2. Advance Page and Turn on Background Location 
3. I had set debug:false due to don't want any notification on device.
4. Start moving more than 6 kilo meters.
4. I see the accuracy value in my API is 5 m. But location is actually 300 m away from actual location. 
5. here i didn't get accurate geolocation

## Context

**Is there any issue in the plugin for Accuracy?** 
**Because, I see the accuracy value in my API is 5 m. But location is actually 300 m away from actual location.** 

Kindly share your expert advice on this.

**Comment by lav-sttl** [comment]
Let me know if any updates on this

**Comment by joyaljchurchill** [comment]
@christocracy , please comment on accuracy. I have the same problem of Accuracy.

Thanks.

**Comment by christocracy** [comment]
Native location services api (for both iOS and Android) is like the city water system.  The plugin provides an api for your to turn the taps to moderate the "heat" of the water (ie: `desiredAccuracy`) and rate-of-flow (`distanceFilter`).  The plugin places a cup beneath the tap to capture drops of water and delivers this water directly to you.

The plugin has no control over the "taste" of that water delivered directly from City's water system.

**Comment by lav-sttl** [comment]
@christocracy Could you please let us know which location provider this plugin are 
using ?

**Comment by christocracy** [comment]
Native “Location Services“ is the aggregation of *all* providers.  One doesn’t choose a specific provider.  The OS provides the best possible location automatically.

**Comment by christocracy** [comment]
And for Android, fine vs coarse is selected automatically based upon your configured desiredAccuracy (see the docs for more info).  The Android plugin uses FusedLocation API from play-services, called “fused” because it *fuses* all providers together to provide the best possible location from all providers.

If you see an accuracy <= 10 with a speed >= 0, that location came from GPS.

**Comment by joyaljchurchill** [comment]
@christocracy 
Is there any possibility that we can have location from GPS only? because, We need accurate location.

If yes, please let us know that which configuration we need to make for GPS for Android and iOS both.

**Comment by christocracy** [comment]
>Is there any possibility that we can have location from GPS only?

No, the native APIs **do not let you specify this**.  As I said "If you see an accuracy <= 10 with a speed >= 0, **that location came from GPS**.  If y

If you're indoors, the location will come from Network provider.
If you're indoors with Wifi disabled, the location will come from Cellular provider.

If you're seeing "5 m. But location is actually 300 m away from actual location", **the location DID come from GPS but you're perhaps experiencing a GPS anomaly (eg: signal reflection off a large body of water, tall building, etc).

**Comment by christocracy** [comment]
I've spoken with your client on the phone.  I want you to configure the plugin to post locations to my test-server at `http://tracker.transistorsoft.com`.

The plugin has a helper-method to allow you to do this:  [`transistorTrackerParams`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#transistortrackerparams)

```javascript
// replace "USERNAME" in url with any value with any value you wish.
let url = 'http://tracker.transistorsoft.com/locations/USERNAME';

BackgroundGeolocation.ready({
  reset: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  url: url,
  params: BackgroundGeolocation.transistorTrackerParams(device) // <-- provide ref to cordova-plugin-device
});
```

When you post to my test server, *I'll* be able to view your tracking results.  Let me know the `USERNAME` you've chosen.

Also see the Wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging) to learn how to fetch logs from the plugin.   If you're not observing the logs, you are developing like a blind person hunting for treasure in a dark forest.

And finally, the issue template asked you to provide **Plugin Config**.  The config from your `config.xml` is not what I'm interested in -- It's the **PLUGIN CONFIG** I want, the `{}` provided to `#ready` method.
