### ISSUE TITLE
How to remove Sticky notification on Android

### ISSUE THREAD

**Issue by lav-sttl** [transistorsoft/cordova-background-geolocation-lt#853]
## Your Environment

![screen shot 2018-12-21 at 8 46 37 pm](https://user-images.githubusercontent.com/45941718/50349470-edbc0680-0561-11e9-91d5-2fabde40fc78.png)

* Cordova platform version (`cordova platform ls`): 2.14.0 - IOS

* Plugin config

![screen shot 2018-12-21 at 8 50 53 pm](https://user-images.githubusercontent.com/45941718/50349532-2a87fd80-0562-11e9-8cf1-20ff7989b61e.png)

## Questions
Note: Using your Example Demo App 
1) **How to remove sticky notification ?**
I had set property **notificationPriority: -2**

![screenshot_20190103-171720 - copy](https://user-images.githubusercontent.com/45941718/50639167-784f2d80-0f86-11e9-829d-38b17e71a759.png)

2) **How to set notification icon in below given screen shot ?**
I had set both property
**notificationLargeIcon: "assets/imgs/logo.png"**
**notificationSmallIcon: 'assets/imgs/logo.png'**

![screenshot_20190103-171819 - copy](https://user-images.githubusercontent.com/45941718/50639170-7c7b4b00-0f86-11e9-9ec9-f811bbd7471c.png)

## Context
**I am trying to turn off All notification on Android**
I had set property **debug: false**

**Comment by christocracy** [comment]
You cannot remove that persistent notification.  It's required by the operating-system for the foreground-service.
