### ISSUE TITLE
SQLite Storage security issue

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [transistorsoft/cordova-background-geolocation-lt#854]
SQLite Storage security concern for android application 
 
  IONIC team has raised security concern related to SQLite Storage and I believe this plugin uses SQLite to store the locations locally 
        https://ionic.zendesk.com/hc/en-us/articles/360014143854?utm_campaign=Security%20Alert%20Native%20Plugins&utm_source=hs_email&utm_medium=email&utm_content=68433586&_hsenc=p2ANqtz--bL4PR9y7RGdxSpLhBtib5Gc2ppxTsFKCVi0LbuZK4vmdiYU3HTm9dN-2r3xbQ3k7soFiwnPbQTWEj6d7DAWNw2tYEYQ&_hsmi=68433586
 
  Could you please confirm us if we should worry about this security issue or not. 

Thanks

   
* Cordova platform version (`cordova platform ls`):7.0.0

**Comment by christocracy** [comment]
This plugin does not expose any api for you to arbitrarily execute sql upon its database.

This plugin is not affected by that vulnerability.
