### ISSUE TITLE
How to access geofence identifier in Android Headless Mode

### ISSUE THREAD

**Issue by esol1** [transistorsoft/cordova-background-geolocation-lt#857]
## Your Environment
* PPlugin version: 2.14.2
* Platform: iOS or Android: Android
* Cordova version (cordova -v): 8.1.2
* Cordova platform version (cordova platform ls): Android 7.1.4rm version (`cordova platform ls`):

## Context

When a geofence event is triggered while in Headless Mode, I want to access the identifer of the geofence. I can access the geofence event while in:

```
if (name.equals(BackgroundGeolocation.EVENT_GEOFENCE)) {
            GeofenceEvent geofenceEvent = event.getGeofenceEvent();
        }
```
...but I have no idea how to use geofenceEvent to gain access to the identifer.

**Comment by christocracy** [comment]
Are you developing your HeadlessTask's code in Android Studio?

**Comment by christocracy** [comment]
Because if you are, you can use the code-assist to discover all the available data upon the `GeofenceEvent`

![](https://dl.dropboxusercontent.com/s/mp9g0xgwfnywggz/Screenshot%202019-01-09%2012.40.24.png?dl=1)

**Comment by esol1** [comment]
That was it.  Right there under my nose :-(
