### ISSUE TITLE
Build errors (duplicate symbol) on iOS (xCode 10.1)

### ISSUE THREAD

**Issue by bushev** [transistorsoft/cordova-background-geolocation-lt#859]
## Your Environment
* Plugin version: 2.14.2
* Xcode version: 10.1
* Platform: iOS
* OS version: 11.0 and newer
* Device manufacturer / model: Apple
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): ios 4.5.5
* Plugin config

```
cordova-background-geolocation-lt 2.14.2 "BackgroundGeolocation"
cordova-clipboard 1.2.1 "Clipboard"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-launch-review 3.1.1 "Launch Review"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-filepicker 1.1.5 "File Picker"
cordova-plugin-fingerprint-aio 1.5.0 "FingerprintAllInOne"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-httpd 0.9.3 "CorHttpd"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-ssh-tunnel 1.1.0 "SSHTunnel"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

## Expected Behavior
Success build

## Actual Behavior
```
duplicate symbol _OBJC_CLASS_$_DDASLLogger in:
    /Users/bushev/Library/Developer/Xcode/DerivedData/SSH_Tunnel-dkloiaxphxooqpbdbljrjfchgbbl/Build/Intermediates.noindex/SSH Tunnel.build/Debug-iphoneos/SSH Tunnel.build/Objects-normal/arm64/DDASLLogger.o
    /Users/bushev/IdeaProjects/ssh-tunnel-app/platforms/ios/SSH Tunnel/Plugins/cordova-plugin-cocoalumberjack/libCocoaLumberjack.a(DDASLLogger.o)
duplicate symbol _OBJC_METACLASS_$_DDASLLogger in:
    /Users/bushev/Library/Developer/Xcode/DerivedData/SSH_Tunnel-dkloiaxphxooqpbdbljrjfchgbbl/Build/Intermediates.noindex/SSH Tunnel.build/Debug-iphoneos/SSH Tunnel.build/Objects-normal/arm64/DDASLLogger.o
    /Users/bushev/IdeaProjects/ssh-tunnel-app/platforms/ios/SSH Tunnel/Plugins/cordova-plugin-cocoalumberjack/libCocoaLumberjack.a(DDASLLogger.o)
... And more similar lines
```

## Steps to Reproduce
1. `cordova plugin add cordova-background-geolocation-lt`
2. `ionic cordova build ios`
3. Then, build from Xcode

## Context
I'm trying to add `cordova-background-geolocation-lt` to my app.

**Comment by christocracy** [comment]
One of your other plugins is importing CocoaLumberjack (iOS debug logger) dependency.

Background-Geolocation imports it via plugin Cordova-plugin-CocoaLumberjack.

Let me know which of your other plugins is importing cocoa-lumberjack.

**Comment by bushev** [comment]
Hi Chris!

Thank you a lot! I see, `cordova-plugin-httpd` linked with `CocoaLumberjack` without adding a dependency. This [fork](https://github.com/choongjoey/cordova-httpd) can be used instead.

🎯

**Comment by christocracy** [comment]
Yes, it's **very** poor form to naïvely [hard-copy a 3rd-party external dependency](https://github.com/floatinghotpot/cordova-httpd/tree/master/src/ios/CocoaHttpd/Vendor) to one's own repo, preventing every other library (like mine) from using that same dependency.

**Comment by aless673** [comment]
Same problem with https://github.com/mauron85/cordova-plugin-background-geolocation

Can't use both bg geolocation plugins...
