### ISSUE TITLE
Cordova Plugin is not offically registered with Cordova

### ISSUE THREAD

**Issue by Wade-BuildOtto** [transistorsoft/cordova-background-geolocation-lt#86]
When I search Cordova plugin's all I can find is someone submitting an older version, this would probably help with exposure to have it officially registered. It would also help being able to be able to install from their as well. 

https://cordova.apache.org/plugins/?q=cordova-background-geolocation-lt

**Comment by ivanssa** [comment]
@Wade-BuildOtto  The plugin is really to be congratulated, but falls short in time to use in our apps, I reported it, and the developer seems little to care about the official repositories of Phonegap Cordova and Npmjs allowing thousands of users to create their app with repositories of phonegap using folks of this third-party plugin without any warranty upgrade and security, including this plugin had several problems with the online build phonegap that was solved unfortunately using a folk other user of this plugin, I hope the dev can publish the official plugin, updated and tested for phonegap in www.npmjs.com, and update your repositories and https://build.phonegap.com/plugins cordova.apache.org/plugins/ e http://ngcordova.com/

**Comment by christocracy** [comment]
Sorry, it seems I wasn't signed up for notifications on my own repo.

I'll be submitting to npm soon.

**Comment by christocracy** [comment]
There, it's [on npm now](https://www.npmjs.com/package/cordova-background-geolocation-lt)

**Comment by ivanssa** [comment]
Hello christocracy thanks for finally update the official repository npm, had even created a folk to be able to use it but now, I will update my app straight from your most current repository thanks ...
