### ISSUE TITLE
With server response of 500 the plugin still indicate a success on onHttp responce

### ISSUE THREAD

**Issue by benkarbist** [transistorsoft/cordova-background-geolocation-lt#864]
## Your Environment
* Plugin version:2.14.2
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):7.1.4
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior

onHttp response should give the same status as StatusCode sent by server. 

## Actual Behavior
But regardless of server response the status is always set to 200 and the the success flag is set to true
here is the console log for the response received from onHttp
[http] {"status":200,"responseText":"{\"Version\":{\"Major\":1,\"Minor\":1,\"Build\":-1,\"Revision\":-1,\"MajorRevision\":-1,\"MinorRevision\":-1},\"Content\":null,\"StatusCode\":500,\"ReasonPhrase\":\"Internal Server Error\",\"Headers\":[],\"RequestMessage\":null,\"IsSuccessStatusCode\":false}","success":true}

plugin status set to 200 whereas server response is 500

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
The plugin *does* report same status code from server.

>Platform: iOS or Android

?

Show me logs from the plugin.

**Comment by benkarbist** [comment]
Attached please find the log. Hope I could capture what you are interested to see

Here is what I see when I print the onHttp result on console:
09:16:02 CordovaBackGroundGps - [http] {"status":200,"responseText":"{\"Version\":{\"Major\":1,\"Minor\":1,\"Build\":-1,\"Revision\":-1,\"MajorRevision\":-1,\"MinorRevision\":-1},\"Content\":null,\"StatusCode\":500,\"ReasonPhrase\":\"Internal Server Error\",\"Headers\":[],\"RequestMessage\":null,\"IsSuccessStatusCode\":false}","success":true}


[output.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2779241/output.txt)

**Comment by christocracy** [comment]
See [here](https://stackoverflow.com/questions/37793418/how-to-return-http-500-from-asp-net-core-rc2-web-api)

**Comment by christocracy** [comment]
and [here](http://www.brandonmartinez.com/2012/08/28/return-a-500-error-in-asp-net-mvc/)

**Comment by benkarbist** [comment]
Thank you for your help and prompt response. Much obliged. You solution worked. I close this issue.
