### ISSUE TITLE
cordova-background-geolocation-lt only supports Cordova v7.0+

### ISSUE THREAD

**Issue by brucejo75** [transistorsoft/cordova-background-geolocation-lt#865]
I discovered that `cordova-background-geolocation-lt` only supports Cordova v7.0+.

The documentation that I found on this was buried in #590... [here](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/590#issuecomment-357990484).

I then found the same output buried in my build output:
```
%% Plugin doesn't support this project's cordova-android version. cordova-android: 6.4.0, failed version requirement: >=7.0.0
%% Skipping 'cordova-background-geolocation-lt' for android
```

The currently released version of Meteor has Cordova v6.4, so everyone on Meteor cannot update to the latest version until Meteor v1.8.1 comes out.

**Requests**;
1. Add this constraint to your documentation and make it prominent.
2. Clearly spell out which version support older versions of cordova.  (I tried 2.8.5 with Meteor and it works)

**Comment by christocracy** [comment]
`cordova-android@7.0.0` was [released over a year ago](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html).

If you're using some product which doesn't yet support `cordova-android@7.0.0` after *a year*, that project must have serious problems.

The last version of `background-geolocation` which supports `cordova-android < 7.0.0` is `2.11.x`.

**Comment by brucejo75** [comment]
Hi @christocracy ,

I think it is a little aggressive to make statements like this:

> If you're using some product which doesn't yet support cordova-android@7.0.0 after a year, that project must have serious problems.

I think it is harsh of your product to simply not support older versions (and then to refer to anyone using an older version as having serious problems).  If the work is too much to support multiple versions of Cordova it is a perfectly reasonable response to support older versions of Cordova with downlevel versions of your SW.

There are many reasons to not advance to the latest versions of software.  And there are users out there that may be in this position (like me).  Even though I am in this position, I can see a path to getting on the latest version soon but I need it to work with my older version as I integrate it.  And I am going to say that my project does not have serious problems despite your assertion.

I think all that I asked that was you prominently document the facts that your software is not backward compatible to older versions of Cordova.  And that if a user wants to use your package with an older version they must downlevel to an older version of your software (e.g. 2.11)

If this was prominently documented I may not have spent ~5hrs digging around trying to figure out why my version was not working (Although, the answer was displayed in my build output, it was easy for me to not notice because my project build is quite involved.)  And hopefully, documenting this fact may save other users time.

PS: I think your package looks like it has wonderful features and I am appreciative of your long term support of it.  And I look forward to having it integrated into my project.
