### ISSUE TITLE
auth-token refresh and plugin header configuration

### ISSUE THREAD

**Issue by renato-l-monteiro** [transistorsoft/cordova-background-geolocation-lt#866]
How are auth token refreshes supported?
e.g when running BackgroundGeolocation.ready() function you may pass an headers parameter,
but when the auth token refreshes, (every hour for example), how should i update the config of the plugin?

Thanks

**Comment by christocracy** [comment]
#setConfig

**Comment by christocracy** [comment]
People typically listen to #onHttp event for http 401 and request new token at that point, using #setConfig to update #headers.

**Comment by renato-l-monteiro** [comment]
Though so, thanks, good job on the plugin btw.
