### ISSUE TITLE
Plugin Ignoring Changes to Config

### ISSUE THREAD

**Issue by cosnofski** [transistorsoft/cordova-background-geolocation-lt#867]
## Your Environment
* ionic-angular 3.9.2
* Plugin version: "cordova-background-geolocation-lt": "2.14.2",
* Platform: iOS
* OS version: 12.1.2
* Device manufacturer / model: iPhone 7
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`):  ios 4.5.5
* Plugin config

## Expected Behavior
When I make a change to the config, save, run I expect to see the changes in the app. 

## Actual Behavior

The config doesn't change unless I delete the app from the device, and re-run

## Steps to Reproduce

1. create an ionic app (ionic start myapp --type=ionic-angular)
2. install the plugin, add platform ios (ionic cordova platform add ios), etc..
3. copy and paste the sample ionic code into home.ts
4. `ionic cordova run ios --device` OR `ionic cordova build ios` then run from Xcode
5. check your database to see what the plugin has posted
6.  make a change to the params attribute or add an extras attribute to the config: `extras : { test : 123 }}`
7. repeat step 4,5 above

## Context

Trying to modify the params that are sent to my server, include, for example a user id that changes depending on who has logged into the app

**Comment by christocracy** [comment]
Read carefully the docs for [`#ready`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#ready) method, paying close attention to `reset: true` and why you might want to use that during development.

⚠️ Note:
The #ready method only applies the supplied Config for the first launch of the app — forever after, the plugin is going to remember every configuration change you apply at runtime (eg: setConfig) and reload that same config every time your app boots. Changes to the Config supplied to ready after first launch will not take effect. During development, it's helpful to provide reset true.
