### ISSUE TITLE
Android Content Type not set when using JSON-API

### ISSUE THREAD

**Issue by pollingj** [transistorsoft/cordova-background-geolocation-lt#868]
## Your Environment
* Plugin version: 2.14.2
* Platform: Android
* OS version: 8
* Device manufacturer / model: LG
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 7.0.0
* Plugin config

```
reset: true,
      debug: false,
      logLevel: bgGeo.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bgGeo.DESIRED_ACCURACY_MEDIUM,
      distanceFilter: 500,
      maxRecordsToPersist: 2,
      url: window.getURL('/geolocation-location'),
      headers: {
        "Accept": "application/vnd.api+json",
        "Content-Type": "application/vnd.api+json",
        "Authorization": toeken
      },
      method: "PUT",
      httpRootProperty: ".",
      locationTemplate: '{"format": "json-api", "data": {"type": "geolocation-location", "attributes": { "token": "0e07dccb-5cdf-40c2-bebc-343436c536db", "latitude": <%= latitude %>,"longitude": <%= longitude %>}}}',
      stopOnTerminate: false,
      autoSync: false,
      startOnBoot: true,
      heartbeatInterval: 60,

      locationAuthorizationRequest: 'Always',
      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Location services are not enabled",
        titleWhenOff: "Location services are off",
        instructions: "If you want to be tracked automatically, you must enable 'Always' in location-services.",
        cancelButton: "Cancel",
        settingsButton: "Settings"
      },
```

## Expected Behavior
When using iOS this works fine and the header gets sent and the API responds

## Actual Behavior
The API responds with a 415 (Unsupported Media Type).

**Comment by christocracy** [comment]
Android automatically sets the `Content-Type application/json`

**Comment by pollingj** [comment]
Just been watching the Nginx logs for iOS and Android calls

Here is the info from that
```
iOS Content-Type: application/vnd.api+json Accept: application/vnd.api+json

Android  Content-Type: application/vnd.api+json; Accept: charset=utf-8 application/vnd.api+json
```
Looks like the only difference is the `Accept` header

**Comment by christocracy** [comment]
Your server cannot Accept with charset=utf-8?

**Comment by pollingj** [comment]
Sorry, I had that wrong (reading stuff late at night), it was the Content-Type that had the `charset=utf-8` in it. 

It's tied to this issue: https://github.com/vt-elixir/ja_serializer/pull/200.

I'll close as this isn't an issue here, but might be one day useful for others around Android and JSON-API content negotiation
