### ISSUE TITLE
Android Plugin using a different session than the rest of the App

### ISSUE THREAD

**Issue by FIELDPOINT** [transistorsoft/cordova-background-geolocation-lt#870]
* Plugin version: 2.14.2
* Platform: WIndows
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 8.1.1
* Cordova platform version (`cordova platform ls`): iOS (4.5.4) Android (6.3.0)
* Plugin config

## Expected Behavior
It should use the same session as the rest of the app for the request like it does on iOS and not create a new Session.

## Actual Behavior
When a HTTP call is made to save the locations to the server from Android, a different session is being used. This does not happen on iOS where the same Session is used. This is causing the server to reject the save requests coming from Android.

## Steps to Reproduce

1. Just make a HTTP call from Android and check the session ID. It will be different to the one being used by the rest of the App.
2.
3.
4.

## Context
This is my config

```
bgGeo.ready({
                reset: true,
                // Geolocation config
                desiredAccuracy: 0,
                distanceFilter: 10,
                stationaryRadius: 25,
                // Activity Recognition config
                activityRecognitionInterval: 10000,
                stopTimeout: 5,
                // Application config
                debug: true,  // <-- Debug sounds & notifications.
                stopOnTerminate: false,
                startOnBoot: true,
                schedule: [
                    '2-6 9:00-17:00'
                ],
                url: MYURL + '/RESTServices/RestEndpoint',
                httpRootProperty: '.',
                method:  'PUT',
                params: {
                    "device_id": device.uuid ? device.uuid : ''
                },
                autoSync: true,
                maxDaysToPersist: 3,
                headers: {  // <-- Optional HTTP headers
                    // "X-FOO": "bar"
                }
            }, function(state) {
                // This callback is executed when the plugin is ready to use.
                console.log("BackgroundGeolocation ready: ", state);
               
               //Not sure if we need a timeout here as the blnGPSTrackingEnabled is updated asynchronously
                bgGeo.startSchedule();
            
            });
```

**Comment by FIELDPOINT** [comment]
The Geolocation call made from the iOS app automatically includes this header
**Cookie : ASP.NET_SessionId=o5urs1a1glcyj0apquq5ccssd**
But the call from Android does not. Shouldnt it be consistent? Is there a way I can force this in Android?

**Comment by christocracy** [comment]
The plugin's source doesn't contain the word "Cookie" anywhere.

Why are you using Cookies anyway?  That's a web-browser thing.  You should be using token-based authentication in a mobile app, not Cookies.  Read [this](https://dzone.com/articles/cookies-vs-tokens-the-definitive-guide)

**Comment by FIELDPOINT** [comment]
I get what you mean. Ty. Would have been great if the plugin did the same for Android too as it did in iOS in this matter.

**Comment by christocracy** [comment]
I have no idea how you've managed to set the `Cookie` header for iOS.  You're free to configure the plugin with any `#headers` you wish, of course.

**Comment by FIELDPOINT** [comment]
Thats the thing, I did not set the  Cookie Header on iOS. If I did then I would have done the same on Android.
