### ISSUE TITLE
install plugin on 

### ISSUE THREAD

**Issue by skiperlay** [transistorsoft/cordova-background-geolocation-lt#871]
* Platform: iOS and Android
* OS version: ios 4.5.5 ; android 7.1.4
* Cordova version : 8.1.2 (cordova-lib@8.1.1)
* ionic version: 4.8.0
* Plugin config

## Expected Behavior
The only thing I want at the moment is to include the plugin in the projects

## Actual Behavior
I get issues when i compile on android studio  and  Xcode
I have not included any code yet, just install the plugin

## Debug logs
Xcode:
<img width="565" alt="captura de pantalla 2019-01-31 a las 20 18 55" src="https://user-images.githubusercontent.com/43707162/52081435-88185c80-259a-11e9-9c2b-df8bdcfdc90d.png">
Android Studio
<img width="1246" alt="captura de pantalla 2019-01-31 a las 20 20 11" src="https://user-images.githubusercontent.com/43707162/52081449-8fd80100-259a-11e9-871d-ba9be9726268.png">

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by skiperlay** [comment]
I don’t know what do you mean, its your plugin

El 31 ene 2019, a las 20:56, Chris Scott <notifications@github.com<mailto:notifications@github.com>> escribió:


$ cordova plugins

**Comment by christocracy** [comment]
It's a command.  Execute it in terminal.  I need to see the list of plugins you have installed in your app.

**Comment by skiperlay** [comment]
cordova-background-geolocation-lt 2.14.2 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.2 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"

**Comment by christocracy** [comment]
Now do you see why you have "Duplicate Symbols"?
```
cordova-background-geolocation-lt 2.14.2 "BackgroundGeolocation"
.
.
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
```

```
$ ionic cordova plugin remove cordova-plugin-mauron85-background-geolocation
```

**Comment by skiperlay** [comment]
:S 
serious error.
thank you chris :)
it is solve:
👍

**Comment by christocracy** [comment]
And btw, get rid of this too `cordova-plugin-background-mode`.  Apple and Google [will reject your app](https://github.com/katzer/cordova-plugin-background-mode/issues?utf8=%E2%9C%93&q=rejected) if you attempt to submit with that plugin installed.  It's a toxic plugin.

See [it's README about "Store Compliance"](https://github.com/katzer/cordova-plugin-background-mode#store-compliance)

**Comment by skiperlay** [comment]
then how can I control the code when it enters the background and leaves it

**Comment by christocracy** [comment]
If you're relying on that plugin, you're swimming against the current and not developing in the correct paradigm.  You don't get to develop for mobile like a web app.

You don't need it with my plugin.  I suggest you get to know my plugin first.

**Comment by christocracy** [comment]
>How can I do this now if I remove the plugin?

You can't.  The reason Apple and Google reject usage of this plugin is precisely to prevent you from doing what you're doing and killing the user's battery.  You are **not** supposed to do what you're doing.

Background Geolocation includes a dependency [cordova-plugin-background-fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch) (created by me).  It's available to you now.

This plugin will fire your provided callback about every 15 min (will be throttled based upon device usage; eg: might fire only every hour or more if user isn't interacting with their device).  That's the best you'll get.

**Comment by christocracy** [comment]
Note, that when the device is detected to be moving (where Background Geolocation is in the *moving* state and actively tracking), your app is completely alive in the background.

**Comment by skiperlay** [comment]
thanks for the information, I'll get to work on it
