### ISSUE TITLE
Getting the Request made by the plugin

### ISSUE THREAD

**Issue by FIELDPOINT** [transistorsoft/cordova-background-geolocation-lt#872]
Is there a way I can see whats actually being sent by the plugin somewhere? May be an option to log the Request along with the payload either in the JS code or logCat or iOS Logger? I have set the 
logLevel: bgGeo.LOG_LEVEL_VERBOSE
but i still can not see what exactly is being sent to the server.

## Your Environment
* Plugin version: 2.14.2
* Platform: WIndows
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 8.1.1
* Cordova platform version (`cordova platform ls`): iOS (4.5.4) Android (6.3.0)
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
No.  Observe you HTTP logs.

What are you using on your server?  PHP?  .NET?

You'll find the JSON payload in the "body of the HTTP request".

**Comment by FIELDPOINT** [comment]
Sry about that. Got carried away.. Thanks.
