### ISSUE TITLE
Change desiredAccuracy in headless mode

### ISSUE THREAD

**Issue by KenPeersman** [transistorsoft/cordova-background-geolocation-lt#878]
## Your Environment
* Plugin version: 2.14.2
* Platform: Android (headless)
* Cordova version (`cordova -v`): 8.1.2

## Expected Behavior
I implemented headless state in to the tracking and it works nice.
The goal is to change the desiredAccuracy to high when you come into a geofence, and back to low when you leave the geofence.
I allready found how to change the way of tracking (active/only gelofences) on a geofence event.
`
private void setFullTrackingOn(Boolean toggle, Context context) {
        BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(context);

        if(toggle){
            TSLog.logger.debug("- Geofence in: -------------------------------------");
            bgGeo.start();
        } else {
            TSLog.logger.debug("- Geofence out: -------------------------------------");
            bgGeo.startGeofences();
        }
    }
`

But I can't find how to change the desired accuracy in the headless state.
Can someone help me with it.

Thanks in advance!!

**Comment by christocracy** [comment]
You'll have to provide `int` values as defined in the Javascript API, there are no `CONSTANT`s defined for these in Native API.

```
    DESIRED_ACCURACY_HIGH: 0,
    DESIRED_ACCURACY_MEDIUM: 10,
    DESIRED_ACCURACY_LOW: 100,
    DESIRED_ACCURACY_VERY_LOW: 1000,
```

```java
public class BackgroundGeolocationHeadlessTask  {

    @Subscribe(threadMode=ThreadMode.MAIN)
    public void onHeadlessTask(HeadlessEvent event) {
        // Get ref to plugin's Config singleton.
        TSConfig config = TSConfig.getInstance(event.getContext());
        // Update config.  There are setter methods for every config option.
        config.updateWithBuilder()
                .setDesiredAccuracy(0) // <-- HIGH
                .commit();
    }
}
```

You can set multiple params inline.
```java
config.updateWithBuilder()
                .setDesiredAccuracy(0)
                .setDistanceFilter(50F)
                .setStopTimeout(5L)
                .setUrl("http://foo.bar.com")
                .commit();
```

**Comment by KenPeersman** [comment]
Hi, thanks for the answer.
Maybe a stupid question (but this is the first time I do java) from where do I need to import the TSConfig plugin?

**Comment by christocracy** [comment]
```java
import com.transistorsoft.locationmanager.adapter.TSConfig;
```
If you open your file in Android Studio, Android Studio will automatically handle imports for you.

**Comment by christocracy** [comment]
You can find the Native API docs at the pure-native repo:
https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-Android.md
