### ISSUE TITLE
App closing after calling configure

### ISSUE THREAD

**Issue by agneshoving** [transistorsoft/cordova-background-geolocation-lt#881]
## Your Environment
* Plugin version: **2.9.0**
* Platform: iOS or **Android**
* OS version: 
* Device manufacturer / model: Occurs on every Android device 
* Cordova version (`cordova -v`): **7.1.0**  
* Cordova platform version (`cordova platform ls`): **Android: 6.3.0 **
* Plugin config

` this.bgGeo.configure({
            debug: false,
            desiredAccuracy: 0,
            distanceFilter: 0,
            allowIdenticalLocations: true,
            disableElasticity: true,
            activityRecognitionInterval: 10000,
            stopTimeout: 5,
            disableStopDetection: true,
            locationUpdateInterval: 1000,
            disableLocationAuthorizationAlert: true,
        }, state => {`

## Expected Behavior

The app should ask for permission when configuring the plugin and not close the app. 

## Actual Behavior

When the configure function is called the app won't ask for permission to use the location. Instead the app wil close without an error. If you open the app again you will be prompted to give permission and the plugin works fine. 

## Context

The app i'm working on is quite old and needed some updating. I had problems with the cordova-google-plus plugin and installed cordova-android-play-services-gradle-release. That didn't solve my problem so I uninstalled the play-services plugin again. Since then the app closes once the bgGeo.configure method is called. 

I have tried removing the Android platform and removing the plugin and adding them both again. Still didn't solve my problem.  In logcat it looks like the plugin can't connect to the GooglePlayServices. Right after the "addLocationListener" log the app wil call onPause and move to the background. Do you have any idea how I could solve this issue or where I should look for a solution? I am aware that I should update my app to the latest versions but I wanted to do some quick bug fixes before updating the app. 

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs, 
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat

**Comment by agneshoving** [comment]
```
03-01 14:03:49.165 I/TSLocationManager(13200): [c.t.l.util.Sensors print]
03-01 14:03:49.165 I/TSLocationManager(13200): ╔═════════════════════════════════════════════
03-01 14:03:49.165 I/TSLocationManager(13200): ║ DEVICE SENSORS
03-01 14:03:49.165 I/TSLocationManager(13200): ╠═════════════════════════════════════════════
03-01 14:03:49.165 I/TSLocationManager(13200): ╟─ ✅  ACCELEROMETER: {Sensor name="MPU6500 Acceleration Sensor", vendor="Invensense", version=1, type=1, maxRange=39.2266, resolution=0.0011971008, power=0.25, minDelay=5000}
03-01 14:03:49.165 I/TSLocationManager(13200): ╟─ ✅  GYROSCOPE: {Sensor name="MPU6500 Gyroscope Sensor", vendor="Invensense", version=1, type=4, maxRange=34.906586, resolution=0.0010652645, power=6.1, minDelay=5000}
03-01 14:03:49.165 I/TSLocationManager(13200): ╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetic Sensor", vendor="Yamaha Corporation", version=1, type=2, maxRange=1200.0, resolution=0.1, power=6.0, minDelay=10000}
03-01 14:03:49.165 I/TSLocationManager(13200): ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="SAMSUNG Significant Motion Sensor", vendor="Samsung Inc.", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=0}
03-01 14:03:49.165 I/TSLocationManager(13200): ╚═════════════════════════════════════════════
03-01 14:03:49.194 I/TSLocationManager(13200): [c.t.l.a.BackgroundGeolocation <init>]
03-01 14:03:49.194 I/TSLocationManager(13200): ╔═════════════════════════════════════════════
03-01 14:03:49.194 I/TSLocationManager(13200): ║ BackgroundGeolocation adapter
03-01 14:03:49.194 I/TSLocationManager(13200): ╠═════════════════════════════════════════════
03-01 14:03:49.200 I/TSLocationManager(13200): [c.t.l.a.BackgroundGeolocation <init>]
03-01 14:03:49.200 I/TSLocationManager(13200):   ✅  Google Play Services: connected (version code:12451000)
03-01 14:03:49.239 D/TSLocationManager(13200): [c.t.l.d.s.LocationOpenHelper onCreate] CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL DEFAULT '', timestamp TEXT, json TEXT, locked BOOLEAN);
03-01 14:03:49.246 D/TSLocationManager(13200): [c.t.l.d.s.LocationOpenHelper onCreate] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay INTEGER NOT NULL DEFAULT 0, extras TEXT);
03-01 14:03:49.248 I/art     (13200): Do partial code cache collection, code=58KB, data=60KB
03-01 14:03:49.248 I/art     (13200): After code cache collection, code=58KB, data=60KB
03-01 14:03:49.248 I/art     (13200): Increasing code cache capacity to 256KB
03-01 14:03:49.255 D/TSLocationManager(13200): [c.t.l.d.s.SQLiteLocationDAO dbh]
03-01 14:03:49.255 D/TSLocationManager(13200):   ✅  Opened database
03-01 14:03:49.268 D/TSLocationManager(13200): [c.t.l.d.s.SQLiteLocationDAO prune]
03-01 14:03:49.268 D/TSLocationManager(13200):   ℹ️  PRUNE -1 days
03-01 14:03:49.326 D/TSLocationManager(13200): [c.t.l.data.sqlite.GeofenceDAO dbh]
03-01 14:03:49.326 D/TSLocationManager(13200):   ✅  Opened database
03-01 14:03:49.340 I/TSLocationManager(13200): [c.t.l.a.BackgroundGeolocation <init>]
03-01 14:03:49.340 I/TSLocationManager(13200):   🔵  Connecting to GooglePlayServices...
03-01 14:03:49.346 D/TSLocationManager(13200): $ addLocationListener()
```

**Comment by christocracy** [comment]
If "app closes", there must be a stacktrace in `adb logcat`

**Comment by agneshoving** [comment]
This is a more complete log. The app doesn't crash or anything it just moves to the background. The only thing i noticed is the logs about missing the permissions which is correct because the prompt that asks for permission to use the location didn't trigger. 

When I bring the app to the front again the prompt will trigger and everything works fine. 

`03-01 16:38:01.621 I/chromium(31915): [INFO:CONSOLE(230052)] "%c HomePage  %c HOME DID ENTER ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:01.622 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c GlobalVarsProvider  %c getWalkingRoute()
03-01 16:38:01.622 I/chromium(31915): [INFO:CONSOLE(230052)] "%c GlobalVarsProvider  %c getWalkingRoute() ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:01.646 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c CONFIGURE BACKGROUND TRACKING
03-01 16:38:01.646 I/chromium(31915): [INFO:CONSOLE(230052)] "%c LocationTracker  %c CONFIGURE BACKGROUND TRACKING ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:01.786 W/ServiceManager( 3654): Permission failure: com.samsung.permission.SSENSOR from uid=10752 pid=31915
03-01 16:38:01.789 D/FileTransfer(31915): Saved file: file:///data/user/0/com.ionicframework.msn312163/cache/content-loader-cache/5ad7290be76bb.jpg
03-01 16:38:01.795 W/ServiceManager( 3654): Permission failure: com.samsung.permission.HRM_EXT from uid=10752 pid=31915
03-01 16:38:01.796 W/ServiceManager( 3654): Permission failure: android.permission.BODY_SENSORS from uid=10752 pid=31915
03-01 16:38:01.796 W/ServiceManager( 3654): Permission failure: android.permission.BODY_SENSORS from uid=10752 pid=31915
03-01 16:38:01.796 W/ServiceManager( 3654): Permission failure: android.permission.BODY_SENSORS from uid=10752 pid=31915
03-01 16:38:02.378 I/TSLocationManager(31915): [c.t.l.util.Sensors print]
03-01 16:38:02.378 I/TSLocationManager(31915): ╔═════════════════════════════════════════════
03-01 16:38:02.378 I/TSLocationManager(31915): ║ DEVICE SENSORS
03-01 16:38:02.378 I/TSLocationManager(31915): ╠═════════════════════════════════════════════
03-01 16:38:02.378 I/TSLocationManager(31915): ╟─ ✅  ACCELEROMETER: {Sensor name="MPU6500 Acceleration Sensor", vendor="Invensense", version=1, type=1, maxRange=39.2266, resolution=0.0011971008, power=0.25, minDelay=5000}
03-01 16:38:02.378 I/TSLocationManager(31915): ╟─ ✅  GYROSCOPE: {Sensor name="MPU6500 Gyroscope Sensor", vendor="Invensense", version=1, type=4, maxRange=34.906586, resolution=0.0010652645, power=6.1, minDelay=5000}
03-01 16:38:02.378 I/TSLocationManager(31915): ╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetic Sensor", vendor="Yamaha Corporation", version=1, type=2, maxRange=1200.0, resolution=0.1, power=6.0, minDelay=10000}
03-01 16:38:02.378 I/TSLocationManager(31915): ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="SAMSUNG Significant Motion Sensor", vendor="Samsung Inc.", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=0}
03-01 16:38:02.378 I/TSLocationManager(31915): ╚═════════════════════════════════════════════
03-01 16:38:02.580 I/TSLocationManager(31915): [c.t.l.a.BackgroundGeolocation <init>]
03-01 16:38:02.580 I/TSLocationManager(31915): ╔═════════════════════════════════════════════
03-01 16:38:02.580 I/TSLocationManager(31915): ║ BackgroundGeolocation adapter
03-01 16:38:02.580 I/TSLocationManager(31915): ╠═════════════════════════════════════════════
03-01 16:38:02.611 I/TSLocationManager(31915): [c.t.l.a.BackgroundGeolocation <init>]
03-01 16:38:02.611 I/TSLocationManager(31915):   ✅  Google Play Services: connected (version code:12451000)
03-01 16:38:02.642 I/art     (31915): Do partial code cache collection, code=55KB, data=56KB
03-01 16:38:02.642 I/art     (31915): After code cache collection, code=55KB, data=56KB
03-01 16:38:02.642 I/art     (31915): Increasing code cache capacity to 256KB
03-01 16:38:02.661 D/TSLocationManager(31915): [c.t.l.d.s.LocationOpenHelper onCreate] CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL DEFAULT '', timestamp TEXT, json TEXT, locked BOOLEAN);
03-01 16:38:02.668 D/TSLocationManager(31915): [c.t.l.d.s.LocationOpenHelper onCreate] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay INTEGER NOT NULL DEFAULT 0, extras TEXT);
03-01 16:38:02.679 D/TSLocationManager(31915): [c.t.l.d.s.SQLiteLocationDAO dbh]
03-01 16:38:02.679 D/TSLocationManager(31915):   ✅  Opened database
03-01 16:38:02.687 D/TSLocationManager(31915): [c.t.l.d.s.SQLiteLocationDAO prune]
03-01 16:38:02.687 D/TSLocationManager(31915):   ℹ️  PRUNE -1 days
03-01 16:38:02.753 D/TSLocationManager(31915): [c.t.l.data.sqlite.GeofenceDAO dbh]
03-01 16:38:02.753 D/TSLocationManager(31915):   ✅  Opened database
03-01 16:38:02.777 I/TSLocationManager(31915): [c.t.l.a.BackgroundGeolocation <init>]
03-01 16:38:02.777 I/TSLocationManager(31915):   🔵  Connecting to GooglePlayServices...
03-01 16:38:02.782 D/TSLocationManager(31915): $ addLocationListener()
03-01 16:38:02.786 D/TSLocationManager(31915): $ configure()
03-01 16:38:02.857 D/InputDispatcher( 3654): Focus left window: 31915
03-01 16:38:02.858 D/ViewRootImpl@dcdb7c3[MainActivity](31915): MSG_WINDOW_FOCUS_CHANGED 0
03-01 16:38:02.871 D/CordovaActivity(31915): Paused the activity.
03-01 16:38:02.871 I/TSLocationManager(31915): - onPause
03-01 16:38:02.877 W/PluginManager(31915): THREAD WARNING: exec() call to BackgroundGeolocation.configure blocked the main thread for 91ms. Plugin should use CordovaInterface.getThreadPool().
03-01 16:38:03.130 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c MyApp  %c platform pause
03-01 16:38:03.130 I/chromium(31915): [INFO:CONSOLE(230052)] "%c MyApp  %c platform pause ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.131 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c MyApp  %c onPause()
03-01 16:38:03.131 I/chromium(31915): [INFO:CONSOLE(230052)] "%c MyApp  %c onPause() ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.132 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c CustomGeofencesProvider  %c START BACKGROUND WATCH
03-01 16:38:03.132 I/chromium(31915): [INFO:CONSOLE(230052)] "%c CustomGeofencesProvider  %c START BACKGROUND WATCH ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.223 W/PluginManager(31915): THREAD WARNING: exec() call to BackgroundMode.background blocked the main thread for 225ms. Plugin should use CordovaInterface.getThreadPool().
03-01 16:38:03.258 D/CordovaWebViewImpl(31915): >>> loadUrl(javascript:cordova.plugins.backgroundMode._isActive=true;cordova.plugins.backgroundMode.fireEvent('activate',null);cordova.plugins.backgroundMode.onactivate(null);)
03-01 16:38:03.263 W/PluginManager(31915): THREAD WARNING: exec() call to BackgroundMode.enable blocked the main thread for 37ms. Plugin should use CordovaInterface.getThreadPool().
03-01 16:38:03.269 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c GlobalVarsProvider  %c getWalkingRoute()
03-01 16:38:03.269 I/chromium(31915): [INFO:CONSOLE(230052)] "%c GlobalVarsProvider  %c getWalkingRoute() ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.273 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c MyApp  %c ACTIVATE BACKGROUND MODE
03-01 16:38:03.274 I/chromium(31915): [INFO:CONSOLE(230052)] "%c MyApp  %c ACTIVATE BACKGROUND MODE ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.277 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c STOP FOREGROUND TRACKING
03-01 16:38:03.277 I/chromium(31915): [INFO:CONSOLE(230052)] "%c LocationTracker  %c STOP FOREGROUND TRACKING ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.337 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : ERROR
03-01 16:38:03.337 I/chromium(31915): [INFO:CONSOLE(230052)] "ERROR", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.366 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c MyApp  %c ACTIVATE BACKGROUND MODE
03-01 16:38:03.366 I/chromium(31915): [INFO:CONSOLE(230052)] "%c MyApp  %c ACTIVATE BACKGROUND MODE ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.367 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c STOP FOREGROUND TRACKING
03-01 16:38:03.367 I/chromium(31915): [INFO:CONSOLE(230052)] "%c LocationTracker  %c STOP FOREGROUND TRACKING ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.372 D/FileTransfer(31915): download https://da8qlpoldxnhb.cloudfront.net/1280x720/smart/msn/images/poi/143/5ad7293f7b392.jpg to file:///data/user/0/com.ionicframework.msn312163/cache/content-loader-cache/5ad7293f7b392.jpg
03-01 16:38:03.376 D/FileTransfer(31915): Download file:https://da8qlpoldxnhb.cloudfront.net/1280x720/smart/msn/images/poi/143/5ad7293f7b392.jpg
03-01 16:38:03.382 I/System.out(31915): (HTTPLog)-Static: isSBSettingEnabled false
03-01 16:38:03.382 I/System.out(31915): (HTTPLog)-Static: isSBSettingEnabled false
03-01 16:38:03.395 D/SystemWebChromeClient(31915): file:///android_asset/www/build/vendor.js: Line 230052 : %c HomePage  %c FIRST STARTUP
03-01 16:38:03.396 I/chromium(31915): [INFO:CONSOLE(230052)] "%c HomePage  %c FIRST STARTUP ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:38:03.541 D/InputTransport(31915): Input channel destroyed: fd=99
03-01 16:38:03.644 D/ViewRootImpl@dcdb7c3[MainActivity](31915): mHardwareRenderer.destroy()#1
03-01 16:38:03.652 D/FileTransfer(31915): Saved file: file:///data/user/0/com.ionicframework.msn312163/cache/content-loader-cache/5ad7293f7b392.jpg
03-01 16:38:03.661 D/ViewRootImpl@dcdb7c3[MainActivity](31915): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
03-01 16:38:03.777 D/FileTransfer(31915): download https://da8qlpoldxnhb.cloudfront.net/1280x720/smart/msn/images/poi/144/5ad72a512ae3f.jpg to file:///data/user/0/com.ionicframework.msn312163/cache/content-loader-cache/5ad72a512ae3f.jpg
03-01 16:38:03.779 D/FileTransfer(31915): Download file:https://da8qlpoldxnhb.cloudfront.net/1280x720/smart/msn/images/poi/144/5ad72a512ae3f.jpg
03-01 16:38:03.782 I/System.out(31915): (HTTPLog)-Static: isSBSettingEnabled false
03-01 16:38:03.782 I/System.out(31915): (HTTPLog)-Static: isSBSettingEnabled false
03-01 16:38:04.000 D/CordovaActivity(31915): Stopped the activity.
03-01 16:38:04.080 D/FileTransfer(31915): Saved file: file:///data/user/0/com.ionicframework.msn312163/cache/content-loader-cache/5ad72a512ae3f.jpg
03-01 16:38:04.140 D/FileTransfer(31915): download https://da8qlpoldxnhb.cloudfront.net/1280x720/smart/msn/images/poi/147/5adf002af3f47.jpg to file:///data/user/0/com.ionicframework.msn312163/cache/content-loader-cache/5adf002af3f47.jpg`


This is the log from moving the app to the front again after it closed when the permission prompt gets triggerd: 

`03-01 16:45:53.644 D/CordovaActivity( 7793): Resumed the activity.
03-01 16:45:53.647 D/CordovaWebViewImpl( 7793): >>> loadUrl(javascript:cordova.plugins.backgroundMode._isActive=false;cordova.plugins.backgroundMode.fireEvent('deactivate',null);cordova.plugins.backgroundMode.ondeactivate(null);)
03-01 16:45:53.653 I/TSLocationManager( 7793): - onResume
03-01 16:45:53.653 D/TSLocationManager( 7793): $ stop()
03-01 16:45:53.670 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c MyApp  %c DEACTIVATE BACKGROUND MODE
03-01 16:45:53.670 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c MyApp  %c DEACTIVATE BACKGROUND MODE ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.671 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c STOP BACKGROUND TRACKING
03-01 16:45:53.671 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c LocationTracker  %c STOP BACKGROUND TRACKING ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.672 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c initForegroundTracking
03-01 16:45:53.672 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c LocationTracker  %c initForegroundTracking ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.689 D/GeolocationPlugin( 7793): We are entering execute
03-01 16:45:53.698 D/InputDispatcher( 3654): Focus entered window: 7793
03-01 16:45:53.703 D/ViewRootImpl@8374027[MainActivity]( 7793): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x3 surface={isValid=true 486278638080} surfaceGenerationChanged=true
03-01 16:45:53.703 D/ViewRootImpl@8374027[MainActivity]( 7793): mHardwareRenderer.initialize() mSurface={isValid=true 486278638080} hwInitialized=true
03-01 16:45:53.708 D/mali_winsys( 7793): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
03-01 16:45:53.721 D/InputDispatcher( 3654): Focus left window: 7793
03-01 16:45:53.732 W/PluginManager( 7793): THREAD WARNING: exec() call to Geolocation.getPermission blocked the main thread for 44ms. Plugin should use CordovaInterface.getThreadPool().
03-01 16:45:53.754 D/TSLocationManager( 7793): $ stop()
03-01 16:45:53.761 D/GeolocationPlugin( 7793): We are entering execute
03-01 16:45:53.762 W/Activity( 7793): Can reqeust only one set of permissions at a time
03-01 16:45:53.788 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c MyApp  %c platform resume
03-01 16:45:53.788 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c MyApp  %c platform resume ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.789 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c MyApp  %c onResume()
03-01 16:45:53.790 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c MyApp  %c onResume() ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.791 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c CustomGeofencesProvider  %c END BACKGROUND WATCH
03-01 16:45:53.791 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c CustomGeofencesProvider  %c END BACKGROUND WATCH ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.792 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c STOP BACKGROUND TRACKING
03-01 16:45:53.792 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c LocationTracker  %c STOP BACKGROUND TRACKING ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.793 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c initForegroundTracking
03-01 16:45:53.794 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c LocationTracker  %c initForegroundTracking ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.803 W/Activity( 7793): Can reqeust only one set of permissions at a time
03-01 16:45:53.803 W/CordovaPlugin( 7793): Attempted to send a second callback for ID: Geolocation1727633386
03-01 16:45:53.803 W/CordovaPlugin( 7793): Result was: "OK"
03-01 16:45:53.805 D/CordovaActivity( 7793): Paused the activity.
03-01 16:45:53.806 I/TSLocationManager( 7793): - onPause
03-01 16:45:53.815 D/TSLocationManager( 7793): $ addLocationListener()
03-01 16:45:53.821 D/TSLocationManager( 7793): $ configure()
03-01 16:45:53.823 W/Activity( 7793): Can reqeust only one set of permissions at a time
03-01 16:45:53.823 W/TSLocationManager( 7793): Waiting for location permission result
03-01 16:45:53.844 D/SystemWebChromeClient( 7793): file:///android_asset/www/build/vendor.js: Line 230052 : %c LocationTracker  %c CONFIGURE BACKGROUND TRACKING
03-01 16:45:53.844 I/chromium( 7793): [INFO:CONSOLE(230052)] "%c LocationTracker  %c CONFIGURE BACKGROUND TRACKING ", source: file:///android_asset/www/build/vendor.js (230052)
03-01 16:45:53.884 E/cr_LocationProvider( 7793): Caught security exception while registering for location updates from the system. The application does not have sufficient geolocation permissions.
03-01 16:45:53.891 E/cr_LocationProvider( 7793): newErrorAvailable application does not have sufficient geolocation permissions.
03-01 16:45:53.897 E/cr_LocationProvider( 7793): Caught security exception while registering for location updates from the system. The application does not have sufficient geolocation permissions.
03-01 16:45:53.904 E/cr_LocationProvider( 7793): newErrorAvailable application does not have sufficient geolocation permissions.
03-01 16:45:53.909 E/cr_LocationProvider( 7793): Caught security exception while registering for location updates from the system. The application does not have sufficient geolocation permissions.
03-01 16:45:53.914 E/cr_LocationProvider( 7793): newErrorAvailable application does not have sufficient geolocation permissions.`

**Comment by christocracy** [comment]
What is your Order #?

**Comment by agneshoving** [comment]
What do you mean by order?

**Comment by christocracy** [comment]
Sorry, I thought you were a customer.

**Comment by agneshoving** [comment]
Yeah I am, or at least the company I work for. The order number is #3227.

**Comment by agneshoving** [comment]
@christocracy do you have any idea what could cause this? Do you think the problem will solve itself when I update my project to the newest versions? If that's so I'm not gonna waste any more time on this issue and just take my time on updating everything.

**Comment by christocracy** [comment]
You should **always** use the latest version.  See the README for new usage instructions, as #configure is deprecated in favour of new #ready method.  Read the docs carefully for #ready method

Cordova-android >= 7.0.0 is required.  6.3.0 is over a year old.  Upgrade all your plugins too.
