### ISSUE TITLE
Issue with ProviderChange Event (Android)

### ISSUE THREAD

**Issue by FIELDPOINT** [transistorsoft/cordova-background-geolocation-lt#882]
On Android, the Event.status seems to only care about the App's Location Permission whether it is Granted or Denied and does not look at the Location Services Setting of the Phone itself.

## Your Environment
* Plugin version: 2.14.2
* Platform: WIndows
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 8.1.1
* Cordova platform version (`cordova platform ls`): iOS (4.5.4) Android (6.3.0)
* Plugin config

## Expected Behavior
The Event.status should also take into account whether the Phone's Location Services are turned OFF. 

## Actual Behavior
The Event.status comes back with AUTHORIZATION_STATUS_ALWAYS even when the Phone's Location Services are disabled. Note: The App did have location permissions granted.

## Steps to Reproduce

1. Open App, grant Location Permission
2. When the App is open, slide down Android's Notification Bar and Disable the Location Service
3. The ProviderChange Event triggers but will say AUTHORIZATION_STATUS_ALWAYS
4. Shouldn't this say AUTHORIZATION_STATUS_DENIED instead in this case.

## Context
Trying to figure out when the Location Services are actually enabled and the App has the permission.

**Comment by christocracy** [comment]
No.  `status` purely means only that the user has granted the initial location authorization popup.

When you disable device Location Service.
- `enabled: false`
- No network location
- No GPS location
```
{
  enabled:false, 
  status: 3, 
  network: false, 
  gps: false
}
```

**Comment by FIELDPOINT** [comment]
I see what you mean. Thanks you for the prompt response and an amazing product.

**Comment by christocracy** [comment]
If you're a customer, why are you posting to the public repo?  You have no guarantee of support here.

**Comment by FIELDPOINT** [comment]
Can you send me a link to the Private repo or tell me where I can find it? Thanks again.

**Comment by christocracy** [comment]
Simply remove "-lt" from the url.

**Comment by FIELDPOINT** [comment]
Thank you.
