### ISSUE TITLE
onHttp event fires multiple times for same geofence

### ISSUE THREAD

**Issue by kushal-ost** [transistorsoft/cordova-background-geolocation-lt#884]
Plugin version: 2.12.2
Platform: iOS or Android : Both
OS version: Latest
Device manufacturer / model: Any device of android / iOS
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): Andriud- 7.0.0
IONIC VERSION : IONIC v1

Expected Behavior
onHttp event should fire event 1 time for 1 geofence at a time.

Actual Behavior
onHttp event fires multiple times for same geofence

**Comment by kushal-ost** [comment]
I have some geofence and I am adding some function into bgGeo.on('http')... But instead of getting single notification for 1 geofence, I am getting multiple notification for same geofence. Please find the attached log file.

**Comment by christocracy** [comment]
What makes you think it’s the same geofence responsible for 2 http requests?

**Comment by kushal-ost** [comment]
The console.log 'res' is having same geofence name multiple times

**Comment by christocracy** [comment]
And what do these entire responses from your server look like?

**Comment by kushal-ost** [comment]
I get an json object from server..  In response i get about geofence name/identifier,  action => Enter/Exit,  user id etc

**Comment by christocracy** [comment]
Again:  “And what do these entire responses from your server look like?”

When I say *entire responses”, I mean *entire*.  I’m not interested in your personal description of the responses.  Provide the requested info or close the issue.

**Comment by kushal-ost** [comment]
This is the response I get  

Response :

{"responseText" : "{"responseCode":"1","responseReason":"User ID  150 geolocation updated","event":"geofence detected","action":"ENTER","placeName":"Tm3"}", "status" : 200, "success" : true}

**Comment by kushal-ost** [comment]
I want to hit an API when someone ENTER/EXIT geofence.
So for this do I have to call API in bgGeo.on('geofence')  or inside    bgGeo.on('geofenceschange')   ?  

Please suggest.

**Comment by kushal-ost** [comment]
Any idea regarding this why http event runs multiple time for same geofence.?
