### ISSUE TITLE
Geolocation not working on iOS 

### ISSUE THREAD

**Issue by projjwalg** [transistorsoft/cordova-background-geolocation-lt#885]
## Your Environment
* Plugin version: 3.0.0
* Platform: iOS
* OS version: 11.4
* Device manufacturer / model: iPhone 5S
* Cordova version (`cordova -v`): cli 8.0.0
* Cordova platform version (`cordova platform ls`): 4.5.4
* Plugin config

## Expected Behavior

When the app launches, iOS should ask for permission to access the location. If granted permission, GPS location should turn on. Location icon should be visible on the status bar.
## Actual Behavior

When the app is launched, iOS does not ask for any permission to access the location. Location does not get turned on. Nothing happens. No location icon is visible on the status bar. Neither the app crashes.
## Context

This plugin is working fine on Android. But on iOS, it is not working at all. Is there any specific setting for iOS? Any working example available for iOS ?

**Comment by christocracy** [comment]
Yes it does.  You’re doing it wrong.  Go read the docs.
