### ISSUE TITLE
Not working when app is in background or terminated. 

### ISSUE THREAD

**Issue by kushal-ost** [transistorsoft/cordova-background-geolocation-lt#886]
Plugin version: 2.12.2
Platform: iOS or Android : Both
OS version: Latest
Device manufacturer / model: Any device of android / iOS
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): Andriud- 7.0.0
IONIC VERSION : IONIC v1

Expected Behavior
It should send GPS coordinates even app is terminated or in background. 

Actual Behavior
In Android it is not working even when  app is terminated or in background. 

In ios it is not working when app is terminated.

**Comment by christocracy** [comment]
You are mistaken and you’re not providing logs.

Has worked for 5 years and thousands of paying customers.

**Comment by kushal-ost** [comment]
Please find the logs
[childfindaLog.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2944969/childfindaLog.txt)

**Comment by Steffaan** [comment]
You should set `stopOnTerminate` to `false`. Your configuration is wrong. The plugin does exactly what it's told to do.

**Comment by christocracy** [comment]
Thanks as always @Steffaan.

**Comment by kushal-ost** [comment]
I am doing stopOnTerminate.. Pl see

`// BackgroundGeoLocation is highly configurable.
      bgGeo.ready({
        // Geolocation config
        geofenceProximityRadius :5000,
        geofenceInitialTriggerEntry : true,
        distanceFilter: 10,
        forceReloadOnGeofence: true,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 5000,
        stopTimeout: 5,
        // Application config
        debug: false,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        reset:true,
        // HTTP / SQLite config
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3,
        foregroundService: true,
        logLevel: bgGeo.LOG_LEVEL_WARNING,
        enableHeadless: true,
        url:"http://www.childfinda.com/process/geofence.php",
        params: {
            user_id: $localStorage.userMaster.id,
            },
        headers: {
            'Authorization': $localStorage.apiAccessToken,
            'Content-Type' : 'application/json'
            }
        }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        if (!state.enabled) {
        bgGeo.start();
        }
        });`

**Comment by christocracy** [comment]
Read the docs for #ready, paying close attention to reset: true.

Look at your logs:  the plugin is running with stopOnTerminate: true

**Comment by kushal-ost** [comment]
Should I remove   reset: true ?

reset is true to always apply the supplied config..

**Comment by christocracy** [comment]
The logs you've posted clearly show the plugin configured for `stopOnTerminate: false`.  You must not be executing `#ready` method.  You *think* you are, but you are not.

**Comment by kushal-ost** [comment]
I am executing #ready as I am able to console "BackgroundGeolocation ready: ";

**Comment by kushal-ost** [comment]
Also , I need to know it is working fine with iOS but not in Android background. What may be the reason ? It gives lat, lang at inconsistent time interval
