### ISSUE TITLE
Unable to trigger geocode update every 8046m

### ISSUE THREAD

**Issue by KieranBinning** [transistorsoft/cordova-background-geolocation-lt#887]
* Plugin version: 2.14.2
* Platform: iOS
* OS version: 11.3.1
* Device manufacturer / model: iPhone 6 Plus
* Cordova version (`cordova -v`): 4.5.4
* Cordova platform version (`cordova platform ls`): iOS

## Expected Behavior
Should trigger geocode update every 8046 metres

## Actual Behavior
Geocode consistently triggered below 8046 metres

## Context
Trying to setup the config to trigger a geocode update every 8046 metres. I've attached the config keys I've tried along with the corresponding results. Not sure how to progress from here, any advice would be greatly appreciated.
[GeolocationsTestRunResults.xlsx](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2952944/GeolocationsTestRunResults.xlsx)

**Comment by christocracy** [comment]
You will **never** get the plugin to trigger every x meters.

It’s pointless to use this plugin for such high distanceFilter since you’re consuming the same amount of power as lower distanceFilter.  Location services radios are going to be on the whole time.

**Comment by christocracy** [comment]
If you only want periodic locations, configure useSignificantChangesOnly: true.  You will get a location every 500-1000 meters and save a lot more energy.

**Comment by KieranBinning** [comment]
Is there no way to record locations further than 500-1000 metres apart using this plugin?

I realise it won't be power efficient, but at the moment my main focus is on reducing the quantity of data being returned while keeping a consistent distance between each recorded location. Device battery isn't an issue.

**Comment by christocracy** [comment]
disableElasticity: true.  That’s all you can do.

You will never get an exact distanceFilter.  Sometimes it will be 7000, other times it’ll be 9000.

**Comment by KieranBinning** [comment]
Test 5 has both disableElasticity: true and distanceFilter: 8046, however the average recorded distance was 853m.

Are there any additional config keys I can set to ensure the recorded locations are roughly 7000m to 9000m apart?

**Comment by christocracy** [comment]
>Are there any additional config keys

No

**Comment by KieranBinning** [comment]
Both the config keys are setup as you suggested, but the average recorded locations weren't near 7000m to 9000m apart. Is there any way locations can be captured roughly within these bounds?

**Comment by christocracy** [comment]
>Is there any way locations can be captured roughly within these bounds?

No
