### ISSUE TITLE
bgGeo.on('location' not working on android

### ISSUE THREAD

**Issue by ELECU4TROE** [transistorsoft/cordova-background-geolocation-lt#888]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: macOS High Sierra 10.13.6
* Device manufacturer / model: huawei p8 lite
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0, ios 4.5.5
* Plugin config
                    // Geolocation config
                    desiredAccuracy: 0,
                    distanceFilter: 0,
                    stationaryRadius: 10,
                    // Activity Recognition config
                    activityRecognitionInterval: 10000,
                    //stopTimeout: 5,
                    // Application config
                    debug: false,  // <-- Debug sounds & notifications.
                    stopOnTerminate: true,
                    startOnBoot: true,
                    preventSuspend: true,
                    notificationTitle: "XXX",
                    notificationText: "Location service activated",
## Expected Behavior
App not triggering function 
 	bgGeo.on('location', function(position) {
		XXX.callbackFn(position)
	});
on android, the same code works well on ios device.

## Debug logs
- Android: 
03-13 12:56:06.794 10411 10687 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
03-13 12:56:06.794 10411 10687 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
03-13 12:56:06.794 10411 10687 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
03-13 12:56:06.794 10411 10687 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:962)
03-13 12:56:06.794 10411 10687 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:104)
03-13 12:56:06.794 10411 10687 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)
-->

**Comment by christocracy** [comment]
Did you figure this out?
