### ISSUE TITLE
Locations stop updating for a minute after pause and restart

### ISSUE THREAD

**Issue by maswa** [transistorsoft/cordova-background-geolocation-lt#889]
## Your Environment
* Plugin version: 3.0.0 beta 4
* Platform: iOS 
* OS version: 12.1.4
* Device manufacturer / model: Apple iPhone 7
* Cordova version (`cordova -v`): PGB cli-8.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config
 ```
// BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
		//desiredAccuracy: 0,
		logLevel:bgGeo.LOG_LEVEL_VERBOSE,
	  	desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
		notificationTitle:'Tracking actief',
		notificationText:'',
		distanceFilter: 10,
	  	stationaryRadius: 25,
		stopTimeout: 5,         // Change state to stationary after 1 min with device "still"
                //stopOnTerminate: false, // Don't stop tracking when app is terminated.
	  	foregroundService: true,
		desiredOdometerAccuracy: 10,
        debug: false  // <-- Debug sounds & notifications.
        
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
       // alert("BackgroundGeolocation ready: "+ state);
        if (!state.enabled) {
            bgGeo.start();

        }
    });
```

## Expected Behavior
After pause and restart the activity it should update locations directly 

## Actual Behavior

Immediately after restart off activity it gives new location, but then it takes 2 minutes to get the next location.  It does seem to measure distance correctly but because it doesn't give any locations in these 2 minutes it does not draw the route on my map well.. 

I am trying to understand the logs.. but even from documentation i can't figure out why it seems to stop updating locations for a while after restart.

I put the logs below.. can anyone tell me what happens between :
2019-03-14 23:28:43.865 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager stop] 

Which was when i paused the activity 

and :
2019-03-14 23:30:20.368 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager start] 

Which was when i restarted the activity

and 
2019-03-14 23:32:15.605  which was when i got the first new location again. 

## Context

Tracking a walking activity. My code should do two things , update distance with odometer and draw the tracked route on a map. 

## Debug logs

[background-geolocation.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2970837/background-geolocation.log)

**Comment by christocracy** [comment]
Please don’t post long logs to the issue thread.  Attach them as a file.  It’s annoying to scroll through.

iOS has no concept of “Activity”, that an Android thing.

Do you mean “terminated the app”?

**Comment by maswa** [comment]
Srry, i have removed the log and attached it as file now. 

No app is not terminated, we just pause the activity with our own js function. 

```
function load_activity_page()
{
	if(online()){
		$('#err').html('<img src="img/loader.gif" width="30px">');
		$.post(surl+'update_distance.php',{idu:localStorage.idu,ida:localStorage.idas,distance:localStorage.distance},function(data){
			window.BackgroundGeolocation.stop();
			window.location='activity_detail.html';
		});
	}
	
}
```

and then when we continue we just start the activity again, previous locations are saved and shown on map. What i'm trying to find out is why it is apparently missing locations for 2 minutes after we start the activity again , while odometer seems to give distance correct

**Comment by christocracy** [comment]
Probably because you're executing `#stop`.  Why are you doing that?

**Comment by maswa** [comment]
because we don't want it to continue tracking during a pause.  
This app is for Health related activities..  so walking, running, cycling.. and user can track the route they walk and see the distance and the walked route on a map.  User is able to pause the activity and continue at a later time. We don't want the plugin to keep tracking and adding distance during pause. So we stop it, save the locations and distance and let user restart the same activity later, where it adds locations and distance to previous saved route and distance.

**Comment by christocracy** [comment]
Well that's why.  When you `#start` the plugin once again, it enters the *stationary state* where it requires movement of 200 meters before tracking resumes.

If you want to enter the *moving* state immediately after `#start`, execute `changePace(true)` in the callback to `#start`.

```javascript
BackgroundGeolocation.start().then(function(state) {
  BackgroundGeolocation.changePace(true);
});
```

**Comment by christocracy** [comment]
Read the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation).  Also, customers should be using the (and posting issues to) the private repo.  This public repo has no guarantee of support and is only updated about every 3 months.  Latest updates appear in the private repo.

**Comment by maswa** [comment]
Thank you .. i will implement and test that.

**Comment by maswa** [comment]
Hi Chris,  we have tested it and though we now seem to get faster updates after pause. It also seems to give inaccurate positions after pause. 

**2019-03-18 13:33:51.300**    till here the behaviour looks normal.. plugin is tracking and giving correct locations after start. 

But from here the above date/time we pause our activity ..

At📍<+52.35798767,+6.86377474>  we restart our activity again and then it suddenly picks up two strange locations and odometer also seems to add distance for it. 

The strange locations are around :

**2019-03-18 13:36:18.974** 
📍<+52.35555106,+6.86271186>

And 2019-03-18 13:36:19.031 ✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+52.35405931,+6.86431296> 

Right after these 2 locations it picks up a location that is more accurate and nearby where we really were at that moment. After that is seems to behave normal again and track the right locations. 


Since i was not at the 2 "strange" locations i would like to know how this could have happened.  Because now we get too much distance and a map that is showing wrong locations (in red circle):

![strangelocations](https://user-images.githubusercontent.com/3632005/54534561-e94e9080-498c-11e9-9068-dd7e27e010e6.jpeg)


Below a piece of the complet log around the above mentioned times..

[log.iOS.docx](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/2978417/log.iOS.docx)

**Comment by christocracy** [comment]
When requesting the `motionchange` position, the plugin prefers a more recent location to a more accuracy location.

### Sample 1:
- Age:  142s.
- Accuracy:  4m
```
📍<+52.35798767,+6.86377474> +/- 4.00m (speed 1.15 mps / course 273.91) @ 18/03/2019, 13:33:56 Central European Standard Time

2019-03-18 13:36:18.971 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 142.0s
╚═══════════════════════════════════════════════════════════

2019-03-18 13:36:18.971 ℹ️-[TSLocationManager locationManager:didUpdateLocations:] Received stale motionchange location.  Retrying...
```

### Sample 2:
- Age:  9.7s
- Accuracy: 116.49m
```
2019-03-18 13:36:18.974 
📍<+52.35555106,+6.86271186> +/- 116.49m (speed -1.00 mps / course -1.00) @ 18/03/2019, 13:36:09 Central European Standard Time

2019-03-18 13:36:18.974 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 9.7s
╚═══════════════════════════════════════════════════════════

2019-03-18 13:36:18.974 ℹ️-[TSLocationManager locationManager:didUpdateLocations:] Received stale motionchange location.  Retrying...
```

### Sample 3:
- Age:  0.0s
- Accuracy: 240.16m
```
2019-03-18 13:36:19.031 
📍<+52.35405931,+6.86431296> +/- 240.16m (speed -1.00 mps / course -1.00) @ 18/03/2019, 13:36:19 Central European Standard Time

2019-03-18 13:36:19.031 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: -1.0m | age: 0.0s
╚═══════════════════════════════════════════════════════════
```

At this point, the plugin has settled upon the most recent location and used **Sample 3** as its `motionchange` location.

```
2019-03-18 13:36:19.031 ✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+52.35405931,+6.86431296> +/- 240.16m (speed -1.00 mps / course -1.00) @ 18/03/2019, 13:36:19 Central European Standard Time
```

It takes time to connect to enough GPS satellites.  Were you indoors during this period?  GPS doesn't work indoors.

**Comment by christocracy** [comment]
The plugin is sampling locations for 10s before it gives up and settles upon the most accuracy location having an age of <= 5s ago.

**Comment by maswa** [comment]
No i was completely outdoors.  Question is from where it got locations from sample 2 and sample 3, because i have not been there at all.  If it's not GPS, are these calculated from mobile / 3g / 4g towers?

**Comment by christocracy** [comment]
iOS location-services is black box.  It fetches locations from all 3 sources:  GPS, Wifi and cell towers.  No, these locations are not from cell towers.

These locations are probably returned from GPS with not enough satellites connected yet.

**Comment by christocracy** [comment]
I suggest you try this from the same position, multiple times and make a judgement with a larger set before jumping to conclusions.

**Comment by maswa** [comment]
Ok.. i will do more test but in general:  is there any way to avoid getting ("wrong") locations while not enough sattelites are connected yet? 
We specifically use this plugin for 2 to 10 km walking/ running activities and a deviaton of hundreds of meters on such short tracks are a bit to much.  Maybe you can recommend a setting for the plugin that will help us getting the most accurate results for this purpose?

**Comment by christocracy** [comment]
> is there any way to avoid getting ("wrong") locations while not enough sattelites are connected yet?

These locations are not "wrong", they just happen to have low accuracy.  This location says the device is somewhere within `240.16M` of this lat/lng, which *is* correct.

📍<+52.35405931,+6.86431296> +/- 240.16m

LIke I said:
>The plugin is sampling locations for 10s before it gives up and settles upon the most accurate location having an age of <= 5s ago.

**Comment by maswa** [comment]
Ok.. so there is no way to skip locations with this low accuracy? Because they might be not "wrong" in your definition of wrong. But they do make it difficult for us to use the plugin for the purpose i mentioned. 

 It is happening specifically after a pause and restart of our code .. so when tracking is started again. I don't yet fully understand why this sampling locations for 10s before it gives up and settles upon most accurate location <=5s ago is having this effect after restart.

**Comment by christocracy** [comment]
Please do more testing and gather a larger sample size before jumping to conclusions.  This could be a 1 in 1000 glitch.

**Comment by maswa** [comment]
Ok.. i will

**Comment by christocracy** [comment]
And please use the private repo from now on.  This is the public repo.  There is no guarantee of support here in the public repo.

**Comment by maswa** [comment]
Hi Chris, once more i would like to comment here. This is because my one-year subscription to private repo is over since March.. I might renew my subscription but for now i would like to post my question here because here because this way you can see the history of the issues i faced and the things i have tried already according to your advice before.  It seems that the update of the plugin and executing changePace(true) in the callback to #start has indeed made the tracking resume faster.  But we now have been testing a few weeks on different activities ( driving car, walking, cycling and running ) and we keep getting issues after we paused and restart the activity.  Many times it leads to wrong distances that are measured.  Now i would like to show you this specific example and ask for your advice.  

As said earlier, our app tracks route ( drawing on map ) and distance of health activities.. like walking , running and cycling. Players get  a score for the distance they have done.  To avoid cheating we have build a speed limit in code that pauses the activity when user exeeds the speed limit. Pause means we stop the activity and save the locations in local storage till user starts activity again ( manually) 

The log that i will show you covers a test where i was driving in car a short distance of about 800 metres before i exeeded the speed limit.  This is at:
04-09 16:36:42.976 DEBUG [TrackingService onDestroy] 

Then at:
 04-09 16:50:36.885 DEBUG [TSConfig c] ℹ️   Persist config 
i stepped out of the car and went for a walk and started my walking activity again.  Which means i press the button start in my app again and the activity that was automatically paused by speed limit is starting again and plugin starts 

Then my main question now is , why does the plugin use this very old location:
 📍  Location[fused 52,532278,6,609527 hAcc=436 et=+12d1h50m35s462ms alt=45.0 vAcc=8 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 546282ms, time: 1554820891156

04-09 16:50:37.454 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 10.72
04-09 16:50:42.943 DEBUG [TrackingService b] 

instead of a few much more recent locations to update the odometer?  The problem with this location is that it's still from the location where i was at the time that the plugin stopped because of exeeding speed limit. It should not have used this location because it now adds 7km of distance that should not be added. That is the whole purpose of our pause function. 

You can see around this time in the log which other locations it could have chosen. 
Can you tell us why plugin chose this location for updating odometer and how we can avoid this? 
We could add a time check in our code to exclude locations older then a few seconds, but if i have read well, plugin should already do that? 

[background-geolocation.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3061193/background-geolocation.log.gz)
