### ISSUE TITLE
IOS configuration not working

### ISSUE THREAD

**Issue by BaskaranRamamoorthy** [transistorsoft/cordova-background-geolocation-lt#891]
this is my configuration

```
config: {
    distanceFilter: 0,
    disableElasticity: true,
    activityRecognitionInterval: 5000,
    stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when app terminated.
    startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    batchSync: false,       // <-- Set true to sync locations to server in a single HTTP request.
    autoSync: true,         // <-- Set true to sync each location to server as it arrives.
    method: 'POST',
    url: HttpConfig.url + '/locations',
    httpRootProperty: 'locations',
    locationTemplate: [{latitude: `<%= latitude %>`,
                        longitude: `<%= longitude %>`,
                        speed: `<%= speed %>`,
                        accuracy: `<%= accuracy %>`,
                        heading: `<%= heading %>`,
                        altitude: `<%= altitude %>`,
                        altitudeAccuracy: `<%= accuracy %>`,
                        batteryLevel: 10,
                        batteryCharging: true }],
    headers: { Authorization: 'Bearer ' + '' },
    locationAuthorizationAlert: {
      titleWhenNotEnabled: 'Please enable locations for Tranzport.',
      titleWhenOff: 'Location Services are off.',
      instructions: 'Please enable \'Always\' in location-services.',
      cancelButton: 'Cancel',
      settingsButton: 'Settings'
    },
    allowIdenticalLocations: true,
    locationUpdateInterval: 5000,
    fastestLocationUpdateInterval: 5000
  }
```
![Screen Shot 2019-03-22 at 7 59 35 PM](https://user-images.githubusercontent.com/42064359/54831362-38275d80-4ce0-11e9-810c-0062f079bc54.png)

**Comment by christocracy** [comment]
Why have you **ignored the issue template**??



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by BaskaranRamamoorthy** [comment]
Plugin version: 3.0.0-beta.4
Platform: iOS 
OS version: mojave 10.14.1
Device manufacturer / model: Mac mini (Late 2012)
Cordova version (cordova -v): 8.1.2 (cordova-lib@8.1.1)
Cordova platform version (cordova platform ls): ios 5.0.0
Plugin config

**Comment by christocracy** [comment]
> IOS configuration not working 

I cannot read your mind.  Do you have some *symptoms* of "not working"?

**Comment by BaskaranRamamoorthy** [comment]
please look the top image i already sent 
first one is those all the configuration i sets
ex:
BackgroundGeolocation.ready(configuration);
second one is logs in xcode. 
in logs, url and locationTemplate was empty.
that's the problem i faced. so its not executing any API's

**Comment by christocracy** [comment]
Read the docs for `#ready` method.  Pay particular attention to the note about `reset: true` and why you want to use that during development when modifying config options.
