### ISSUE TITLE
Does the speed in returned  response is accurate when the accuracy is low?

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [transistorsoft/cordova-background-geolocation-lt#892]
Hi, I am using this plugin in ionic 3 app.
I want to know that when the logged accuracy is low of location eg. _accuracy_ :500
Then, do the  _speed_  and _bearing_ parameter values are also wrong in response? 
or it does not depend on the location accuracy. 

Thanks  
 
* Platform: Android
* OS version :7
* Device manufacturer / model:Nokia
* Cordova version (`cordova -v`):7.0

**Comment by christocracy** [comment]
speed / heading come **only** from GPS.  A location from gps has accuracy <= ~10.

A location with accuracy 500 *doesn’t have* speed / heading.

**Comment by Gurjit-ONEBCG** [comment]
> speed / heading come **only** from GPS. A location from gps has accuracy <= ~10.
> 
> A location with accuracy 500 _doesn’t have_ speed / heading.

Thank for replying,
I require to calculate the right location if the accuracy is low, based on the last accurate location logged.
Can you please suggest?

**Comment by christocracy** [comment]
It’s impossible to determinate speed with a location having accuracy 500.

**Comment by Gurjit-ONEBCG** [comment]
Can you please get few mins to read this doc, I am creating to find out the way to figure the right location

https://docs.google.com/document/d/1MrG1kIGd_4GglJtoCVJ4MQwGz6tm6CIm1PcI_qlZ2kA/edit?usp=sharing

**Comment by Gurjit-ONEBCG** [comment]
> It’s impossible to determinate speed with a location having accuracy 500.

Can you please get few mins to read this doc, I am creating to find out the way to figure the right location

https://docs.google.com/document/d/1MrG1kIGd_4GglJtoCVJ4MQwGz6tm6CIm1PcI_qlZ2kA/edit?usp=sharing
