### ISSUE TITLE
Bypass webview entirely using native geolocation plugin

### ISSUE THREAD

**Issue by saoron** [transistorsoft/cordova-background-geolocation-lt#895]
Hi, This plugin is great, the only problem we have with it is the freezing splash screen on boot (iOS), rolling back to UIWebView is not a good solution for us so I was thinking..

Could we use the native plugin and run our logic in Obj-C (similarly to Android headless mode), will this work as expected or will iOS still "half wake" the app in background causing the same issue?

Thanks,

**Comment by christocracy** [comment]
I don't know, probably.  I'm not providing any support for doing this, you're on your own.

- Are you sure you're on the latest version of your `webview` plugin?
- Have you consulted assistance at that plugin repo?

**Comment by saoron** [comment]
Hi,
I'm using the ionic wkwebview and they've recently removed support for background process.
You're probably the most experienced person with this issue so I would love to hear your opinion whether to give it a shot or not.

**Comment by christocracy** [comment]
>they've recently removed support for background process

What??  Link?

**Comment by saoron** [comment]
https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/73b665979e4b49861999d7d2c4a9abf939899af3

**Comment by christocracy** [comment]
I don't think that's necessarily related.
