### ISSUE TITLE
Odometer doesn't calculate distance always giving 0 

### ISSUE THREAD

**Issue by groupmwt** [transistorsoft/cordova-background-geolocation-lt#897]
Hi, I am using the cordova-background-geolocation plugin but I can't get the odometer distance calculation. I'm expecting that the odometer to give the distance in meters, but it is always giving 0.

## Your Environment
* Plugin version:2.14.2
* Platform: Android
* OS version:10.12.6
* Device manufacturer / model: Samsung j7 prime
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`):
* Plugin config

  bgGeo.configure({
          // Geolocation config
          foregroundService: true,
          disableMotionActivityUpdates:true,
          notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
          notificationText: 'Capturando su ubicación',
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, //(value = -1)

          stationaryRadius: 1,

          stopTimeout: 5,
          // Application config
          debug: false,  // <-- Debug sounds & notifications.
          stopOnTerminate: false,
          startOnBoot: true,
          // HTTP / SQLite config
          url: url_base + 'drivers/update_driver_position.json',
          method: "PUT",
          autoSync: true,
          maxDaysToPersist: 3,
          httpRootProperty: 'user',
          locationTemplate: '{ "u_latitude":<%= latitude %>, "u_longitude":<%= longitude %>, "isBackground":true }',
          distanceFilter: 1,
          fastestLocationUpdateInterval: 5000,
          allowIdenticalLocations: true,
          activityRecognitionInterval: 0,
          desiredOdometerAccuracy: 10,
          disableStopDetection: true,
          disableElasticity: true,
          // Set user token
          headers: {  // <-- Optional HTTP headers
            "Authorization": 'Token token=' + AuthService.getApiToken()
          }
        }, function (state) {
          console.log("BackgroundGeolocation ready: ", state);
          bgGeo.start();
        });

## Expected Behavior
 app.bgGeo.getOdometer(function (distance) {

      console.log('distance ======== ', distance);
      $scope.distance_km = distance / 1000;
   $scope.distance_km);
    });
the distance should be different if i am moving anywhere rather then always getting 0

## Actual Behavior

Never changes from 0. 

## Steps to Reproduce

        //BackgroundGeoLocation is highly configurable.
        bgGeo.configure({
          // Geolocation config
          foregroundService: true,
          disableMotionActivityUpdates:true,
          notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
          notificationText: 'Capturando su ubicación',
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, //(value = -1)

          stationaryRadius: 1,

          stopTimeout: 5,
          // Application config
          debug: false,  // <-- Debug sounds & notifications.
          stopOnTerminate: false,
          startOnBoot: true,
          // HTTP / SQLite config
          url: url_base + 'drivers/update_driver_position.json',
          method: "PUT",
          autoSync: true,
          maxDaysToPersist: 3,
          httpRootProperty: 'user',
          locationTemplate: '{ "u_latitude":<%= latitude %>, "u_longitude":<%= longitude %>, "isBackground":true }',
          distanceFilter: 1,
          fastestLocationUpdateInterval: 5000,
          allowIdenticalLocations: true,
          activityRecognitionInterval: 0,
          desiredOdometerAccuracy: 10,
          disableStopDetection: true,
          disableElasticity: true,
          // Set user token
          headers: {  // <-- Optional HTTP headers
            "Authorization": 'Token token=' + AuthService.getApiToken()
          }
        }, function (state) {
          console.log("BackgroundGeolocation ready: ", state);
          bgGeo.start();
        });
## Context

Give distance or the meter which I have walked 

## Debug logs
not getting error

**Comment by christocracy** [comment]
You’re doing something wrong.  Provide logs.

**Comment by groupmwt** [comment]
is above code is correct?
i am not getting any logs

**Comment by christocracy** [comment]
- See wiki debugging.
- read docs for #ready, paying close attention to note about `reset: true`
