### ISSUE TITLE
custom notification cordova 8.1.2

### ISSUE THREAD

**Issue by thibaudsalsa** [transistorsoft/cordova-background-geolocation-lt#898]
Hello,
I'm currently working with the tracker and I would like to know if it's possible to custom the notification ?

When the tracking is on,
the notification need to display a timer and a button. When pressing the button the tracker stop.

thanks a lot.

**Comment by christocracy** [comment]
Only with the current `notification*` config options.  There is no ability to render custom buttons.  This would be very difficult to do in an abstract way.

**Comment by thibaudsalsa** [comment]
Okey thanks,
 But is it possible to put a timer in the notification ?

**Comment by christocracy** [comment]
The only thing you can do with the notification are the [Config](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html) options beginning with the word "notification".

![](https://dl.dropbox.com/s/e2kuoo6kn2flwy8/Screenshot%202019-04-04%2010.06.34.png?dl=1)

**Comment by thibaudsalsa** [comment]
can we disable your notification handler and go with the cordova's notification plugins ?

**Comment by christocracy** [comment]
No.  The plugin's notification is required by its foreground-service.

**Comment by thibaudsalsa** [comment]
okey thanks !
