### ISSUE TITLE
Error on compilation with XCode7

### ISSUE THREAD

**Issue by madubois08** [transistorsoft/cordova-background-geolocation-lt#9]
I'm using Ionic 1.6.5 and Xcode 7.0.1

I'm trying to make an Archive of my App with background geolocation plugin and I have error:

Ld /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/arm64/Lanauco-Mobile normal arm64

    cd /Users/madubois/Projects/lanauco_workbench/lanauco.lanauco_mobile/platforms/ios

    export IPHONEOS_DEPLOYMENT_TARGET=9.0

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos -F/Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos -FLanauco-Mobile/Plugins/com.transistorsoft.cordova.background-geolocation -filelist /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/arm64/Lanauco-Mobile.LinkFileList -miphoneos-version-min=9.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -weak_framework AudioToolbox -framework TSLocationManager -weak_framework AVFoundation -weak-lsqlite3 -weak_framework ImageIO -framework CoreLocation -Xlinker -dependency_info -Xlinker /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/arm64/Lanauco-Mobile_dependency_info.dat -o /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/arm64/Lanauco-Mobile

ld: bitcode bundle could not be generated because 'Lanauco-Mobile/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/armv7/Lanauco-Mobile normal armv7

    cd /Users/madubois/Projects/lanauco_workbench/lanauco.lanauco_mobile/platforms/ios

    export IPHONEOS_DEPLOYMENT_TARGET=9.0

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos -F/Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos -FLanauco-Mobile/Plugins/com.transistorsoft.cordova.background-geolocation -filelist /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/armv7/Lanauco-Mobile.LinkFileList -miphoneos-version-min=9.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/BuildProductsPath/Release-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -weak_framework AudioToolbox -framework TSLocationManager -weak_framework AVFoundation -weak-lsqlite3 -weak_framework ImageIO -framework CoreLocation -Xlinker -dependency_info -Xlinker /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/armv7/Lanauco-Mobile_dependency_info.dat -o /Users/madubois/Library/Developer/Xcode/DerivedData/Lanauco-Mobile-ezkiqbpqposuhngohjxxkxxfowwq/Build/Intermediates/ArchiveIntermediates/Lanauco-Mobile/IntermediateBuildFilesPath/Lanauco-Mobile.build/Release-iphoneos/Lanauco-Mobile.build/Objects-normal/armv7/Lanauco-Mobile

ld: bitcode bundle could not be generated because 'Lanauco-Mobile/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by christocracy** [comment]
Try installing the branch `#ios-motion-detection`.  I have a PR created to merge this to master soon.

https://github.com/transistorsoft/cordova-background-geolocation-lt/pull/11
