### ISSUE TITLE
Geofence Events Never Fire in iOS Simulator

### ISSUE THREAD

**Issue by arcadia168** [transistorsoft/cordova-background-geolocation-lt#90]
Hi,

Thanks for the great plugin, it's incredibly impressive. 

I seem to be having issues getting geofence events to trigger, even though I have registered an event handler in the assigned manner this is never fired.

I managed to get around this issue as I noticed that the callback invoked whenever the location is changed gets given a 'geofence' object as one of its parameters (I think this is undocumented), is this desired behaviour?

For whatever reason however, this too has ceased to work perhaps due to updated to XCode or the iOS Simulator or perhaps even your plugin.

One thing I do however notice is that this break in functionality is preceded (by the iOS simulator) with an alert stating "location error: 0", however, the plugin then correctly updates location and detects a change in location, say when beginning a 'freeway drive' via the debug > location menu.

I find this strange as I am getting the same behaviour using the provided SampleApp, whereby every other aspect of the plugin works other than geofence alerts on events, and the alert for "location error: 0"

Whenever this happens intermittently, the associated error in XCode's console is:

2016-03-24 22:24:06.202 [69314:1505558] [ts-locationmanager] - locationManager failed:  Error Domain=kCLErrorDomain Code=0 "(null)"

Is there some specific version, characteristic or setting for the iOS simulator and XCode to ensure that geofence functionality works?

Below are the ways in which I have attempted to use the plugin and my Ionic project info in case it has a bearing.

https://www.dropbox.com/s/il7p6qouju2gqe8/Screenshot%202016-03-24%2022.44.44.png?dl=0

System information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by christocracy** [comment]
Works fine here.
![](https://www.dropbox.com/s/fj3ypw7xzf0v472/Screenshot%202016-04-08%2010.16.30.png?dl=1)

**Comment by arcadia168** [comment]
Copied everything over to a new project. Seemed to fix the issue. Thanks for the help.

One thing I did notice is that it wasn't an onGeofence event that fired, but detecting a geofence object in the onLocationChange even that allowed me to use this functionality. No onGeofence events seem to fire.

**Comment by christocracy** [comment]
The alert in screenshot above is executed from the `onGeofence` event-handler in the [SampleApp](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/app/home/home.js#L87).
