### ISSUE TITLE
Ionic 4 : Conflict with @ionic-native/http

### ISSUE THREAD

**Issue by AyazBulls** [transistorsoft/cordova-background-geolocation-lt#905]
## Your Environment
* Plugin version: 3.0.0
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Huaweï P20 Light
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 
 android 8.0.0
 browser 6.0.0
* Plugin config

## Expected Behavior
Make normal HTTP request to my server (login, get user info etc..) before using the plugin

## Actual Behavior
App crashes after the first HTTP request (after getting the login result) with a warning message "cordova_not_available". It crashes even if i'm not at all using the plugin (no import nothing...)

## Steps to Reproduce
1. Add HTTP Native
2. Add the plugin
3. Make HTTP request before loading the plugin

## Context
I'm making a HTTP call to log the user, then another one to get the user infos and at last i'm using the plugin.

So when the plugin is removed from my app, it works fine i can make as many HTTP request as i want, but when i add the plugin to the project it crashes with "cordova_not_available" as a warning message. (I'm using `` this.platform.ready().then(()=>{..});``)

## ADB LOGCAT

``04-16 16:30:24.146 12678 12782 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
04-16 16:30:24.146 12678 12782 E AndroidRuntime: Process: io.ionic.starter, PID: 12678
04-16 16:30:24.146 12678 12782 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/io.ionic.starter-pLqx0ZC2jcXrdY2WlW9Yiw==/base.apk)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at okhttp3.internal.huc.OkHttpURLConnection.buildCall(OkHttpURLConnection.java:373)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at okhttp3.internal.huc.OkHttpURLConnection.getResponse(OkHttpURLConnection.java:435)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at okhttp3.internal.huc.OkHttpURLConnection.getResponseCode(OkHttpURLConnection.java:491)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at com.silkimen.http.HttpRequest.code(HttpRequest.java:1447)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at com.silkimen.http.HttpRequest.stream(HttpRequest.java:1740)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at com.silkimen.http.HttpRequest.buffer(HttpRequest.java:1729)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at com.silkimen.http.HttpRequest.receive(HttpRequest.java:1856)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at com.silkimen.cordovahttp.CordovaHttpBase.processResponse(CordovaHttpBase.java:159)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:74)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-16 16:30:24.146 12678 12782 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)``

**Comment by christocracy** [comment]
>Plugin version: master (latest)

Don't do this.  It's meaningless as time goes on.  Update your post.

**Comment by christocracy** [comment]
If your app crashed, where is your stacktrace from `adb logcat`?

**Comment by AyazBulls** [comment]
Done.

**Comment by christocracy** [comment]
Both your http plugin and background-geolocation use the excellent Android HTTP library [`okhttp`](https://square.github.io/okhttp/).

- Background geolocation uses [`okhttp:3.12.1`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/build.gradle#L15)
- `@ionic-native/http` is a wrapper around [`cordova-plugin-advanced-http`](https://github.com/silkimen/cordova-plugin-advanced-http), whose [master branch uses `3.10.0`](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/plugin.xml#L78)

Paste your `platforms/android/project.properties`.

**Comment by AyazBulls** [comment]
Here you go
``target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/starter-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:16.0.0
cordova.system.library.2=com.android.support:appcompat-v7:27.1.1
cordova.gradle.include.2=cordova-background-geolocation-lt/starter-build.gradle
cordova.system.library.3=com.squareup.okhttp3:okhttp-urlconnection:3.10.0
cordova.system.library.4=com.android.support:support-annotations:27.+``

**Comment by christocracy** [comment]
As a test, do this.  Run it.
```diff
target=android-28 android.library.reference.1=CordovaLib android.library.reference.2=app cordova.gradle.include.1=cordova-plugin-background-fetch/starter-build.gradle cordova.system.library.1=com.google.android.gms:play-services-location:16.0.0 cordova.system.library.2=com.android.support:appcompat-v7:27.1.1 cordova.gradle.include.2=cordova-background-geolocation-lt/starter-build.gradle +cordova.system.library.3=com.squareup.okhttp3:okhttp-urlconnection:3.12.1 cordova.system.library.4=com.android.support:support-annotations:27.+
```

**Comment by AyazBulls** [comment]
Yeah just figured out, that it was a problem with the different versions of okhttp. But how can i fix this ?

**Comment by christocracy** [comment]
It seems `cordova-plugin-advanced-http` and `background-geolocation` will have to offer up a config.xml param allowing you to align each plugin to the same version.  In the meantime, you'll have to live with manually hacking your `project.properties` (which is destroyed when you `cordova platform remove android`.

**Comment by christocracy** [comment]
Background Geolocation already offers up [a number of `config.xml` params](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin), eg: `APPCOMPAT_VERSION`

It should have an added `OKHTTP_VERSION` (`cordova-plugin-advanced-http` as well).

**Comment by AyazBulls** [comment]
The hack of project.properties seems to work fine. Thank you.

**Comment by christocracy** [comment]
Added new `OKHTTP_VERSION` (default `3.12.1`) variable in `3.0.1`.

To align with `cordova-plugin-advanced-http`:
```
$ cordova plugin remove cordova-background-geolocation-lt
$ cordova plugin add cordova-background-geolocation-lt --variable OKHTTP_VERSION=3.10.0
```

**Comment by elmbrent** [comment]
Chris I tried to add OKHTTP_VERSION and this did not work 
```
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.+
```

**Comment by christocracy** [comment]
Why do you think you’re having an okhttp version conflict?

The key is to observe your project.properties for conflicting version of *all* dependencies.

**Comment by elmbrent** [comment]
You passed me onto this ticket from the push notification one yesterday https://github.com/fechanique/cordova-plugin-fcm/pull/358 can we skype?

**Comment by andreasaphilo** [comment]
> Added new `OKHTTP_VERSION` (default `3.12.1`) variable in `3.0.1`.
> 
> To align with `cordova-plugin-advanced-http`:
> 
> ```
> $ cordova plugin remove cordova-background-geolocation-lt
> $ cordova plugin add cordova-background-geolocation-lt --variable OKHTTP_VERSION=3.10.0
> ```

Hello, im having an issue with the  cordova-background-geolocation-lt after installing it with capacitor i cannot build it for android getting an error cannot find symbol class OkUrlFactory in file okconnectionfactory.java
