### ISSUE TITLE
getProviderState Not Working Correctly

### ISSUE THREAD

**Issue by juma929** [transistorsoft/cordova-background-geolocation-lt#906]
## Your Environment
* Plugin version: 3.0.0
* Platform: iOS
* OS version: any
* Device manufacturer / model: Apple
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.5
* Plugin config - None yet, trying to check permissions prior to initialisation.

## Expected Behavior

Be able to import BackgroundGeolocation in an angular/typescript/ionic project and call BackgroundGeolocation.getProviderState() successfully.

## Actual Behavior

Error stating 'getProviderState' is not a function. Bearing in mind, I can call a ton of other methods on the same BackgroundGeolocation object, just not this one.

## Steps to Reproduce

1. Setup an ionic project.
2. Install the plugin.
3. Follow the documentation on example usage.
4. Use getProviderState().
5. See the error.

## Context

Get provider state.

## Debug logs

None available.

**Comment by christocracy** [comment]
Thanks @juma929.  Fixed in `3.0.1`
