### ISSUE TITLE
bad positions in power saving mode

### ISSUE THREAD

**Issue by rcauquil** [transistorsoft/cordova-background-geolocation-lt#907]
how to prevent this ?

**Comment by christocracy** [comment]
what do you think the OS does when it engages power-saving mode?  It turns off power-hungry things, like GPS.

How do you avoid it?  You can’t.

You can listen to #onPowerSaveChange to know when it engages.

**Comment by rcauquil** [comment]
Sure, I understand and I know it's the OS that does it and I'm OK with this (hopefully), but you answer my question with the event I can listen to, that's what I was looking for and misspelled my question...
Thank you !
