### ISSUE TITLE
App stuck in open stage

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [transistorsoft/cordova-background-geolocation-lt#909]
When I finished the route of around 10 miles and tried to open the app, it could not load until I killed the app and re opened.  which resulted to log no location on my server.
Kindly see the issue replicate steps.

* Plugin version:3.0.0
* Platform: iOS 
* OS version:12.2
* Device manufacturer / model:iPhone 6 
* Cordova platform version (`cordova platform ls`):7.0
* Plugin config
  debug: true,
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                useSignificantChangesOnly: false,
                maxDaysToPersist: 14,
                stopOnTerminate: false,
                startOnBoot: true,
                foregroundService: true,
                desiredAccuracy: 0,
                enableHeadless: true,
                autoSync: true,
                batchSync: true,
                maxBatchSize: 20,
                heartbeatInterval: 5,
                preventSuspend: true,
                disableElasticity: true,
                distanceFilter: 10,
                stopTimeout: 15,

## Expected Behavior
Locations should sent to server

## Actual Behavior
Locations not post on server and app was not opening on first attempt

## Steps to Reproduce

1. Call the start method 
2. Kill the app
3. turn off the internet
4. drive around 10 miles ( I was able to watch notification of motion change and locations)
5. turn on the internet
6. open the app (which is already in stuck stage (because it was booted by plugin itself in background)

## Context
I wanted to let plugin keep  store all the locations. in sqlite db until I reconnect the internet and call getlocations method of plugin 

Thanks

**Comment by christocracy** [comment]
Are you using some sort of `webview` plugin?

```
$ cordova plugins
```

**Comment by Gurjit-ONEBCG** [comment]
> Are you using some sort of `webview` plugin?
> 
> ```
> $ cordova plugins
> ```

Yes,
"cordova-plugin-ionic-webview": "^1.2.1",

**Comment by christocracy** [comment]
[Search issues for label "Webview plugin"](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues?utf8=%E2%9C%93&q=label%3A%22Webview+plugin%22+)

webview plugins are known to freeze apps that can boot in the background (as `background-geolocation` and `background-fetch` will do)

**Comment by christocracy** [comment]
Duplicate #800

**Comment by Gurjit-ONEBCG** [comment]
> Duplicate #800

Thanks Chris!

I have removed the webview plugin, 
And currently  app is getting reboot properly in background.
And I don't see any lack in app performance after removing webview plugin
