### ISSUE TITLE
TypeError: Cannot read property 'onLocation' of undefined

### ISSUE THREAD

**Issue by miapihl12** [transistorsoft/cordova-background-geolocation-lt#910]
BackgroundGeolaction not working 

## Your Environment
* Plugin version: 3.0.1 
* Platform: Android
* OS version: Windows 10
* Device manufacturer / model: OnePlus 5T
* Cordova version (`cordova -v`): 7.1.0 
* Cordova platform version (`cordova platform ls`): android 6.4.0, browser 5.0.4
* Plugin config 
`configureBackgroundGeolocation() {

    BackgroundGeolocation.onLocation(this.onLocation.bind(this));

    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10
    }, (state) => {
      console.log('BackgroundGeolocation ready ', state);
    });
}`

## Expected Behavior
We have followed the guide for SampleApp updated for ionic 4 in order to implement background geolocation for tracking the position of the user.  We expected it to print the console.log message within the ready block. 

## Actual Behavior
We get the error: TypeError: Cannot read property 'onLocation' of undefined 

## Steps to Reproduce
Imported in the app.module.ts and the .ts file:
`import { Device } from '@ionic-native/device/ngx';`
`import BackgroundGeolocation, { Location } from 'cordova-background-geolocation-lt';`

`backgroundGeolocation: any;`

within startTracking() method in .ts  (we don't want to start background tracking already in the constructor)
`this.platform.ready().then(this.onDeviceReady.bind(this));`

onDeviceReady within ts.
`onDeviceReady(){`
` this.device = (<any>window).device;
  this.configureBackgroundGeolocation();
}`

onLocation within .ts
`onLocation(location: Location) {
    this.testSpeech();
    console.log('[location] -', location);
    console.log(location.coords.latitude);
    console.log(location.coords.latitude);
  }`

## Context
We would like to track users position while the app is running in the background in an ionic 4 app 

Hope you can help

**Comment by christocracy** [comment]
Plugin is not installed.

**Comment by miapihl12** [comment]
I have installed this:
ionic cordova plugin add cordova-background-geolocation-lt

this  is in the package-lock.json file:
`    "cordova-background-geolocation-lt": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/cordova-background-geolocation-lt/-/cordova-background-geolocation-lt-3.0.1.tgz",
      "integrity": "sha512-oL/Q9JSprAeENeyc0xTkuWgTc8xUu2wXjZp3dEuojyGC/0ETwcntHjs1YYGkoLyk8AQZUvrlWJlLPCCuY8zBzw=="
    },`

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by miapihl12** [comment]
Thanks a lot!! 
One question is it true that I have to build the everytime for the plugin to work? 
At the moment it does not work once I have terminated the app and opened it again. But if I rebuild it and run it, it works again.

**Comment by christocracy** [comment]
> that I have to build the app everytime for the plugin to work?

This doesn't make sense to me.

```
BackgroundGeolocation.ready({
  reset: true,
  stopOnTerminate: false
}, ((state) => {
  BackgroundGeolocation.start();
});
```
This will track a device *forever* until you `BackgroundGeolocation.stop()`.

**Comment by christocracy** [comment]
This plugin was designed to track emergency workers in disaster zones (hurricanes, earthquakes).  It had to keep tracking *no matter what*, where life depended on it with no user-interaction at all.

- If device ran out of power, it had to resume tracking when device is recharged (`startOnBoot: true`).
- If user or OS terminated the app, it had to continue tracking (`stopOnTerminate: false`).
- If cell network was destroyed, it had to cache all recorded locations in order to upload all tracking once network connection restored.
