### ISSUE TITLE
onlocation not fired even when moving after some time

### ISSUE THREAD

**Issue by stefanminch** [transistorsoft/cordova-background-geolocation-lt#911]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version:8.1.0
* Device manufacturer / model: Xiaomi Redmi GO
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config: It is part of the attached gzip, see the row at
04-21 12:50:56.106 INFO [TSConfig print] 

Logs:
See the activity AFTER: 04-21 12:50:56.106 INFO [TSConfig print] 
It ends several pages below: 04-21 13:54:46.580 INFO [TSLocationManager removeLocationUpdates] 

[background-geolocation.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3101367/background-geolocation.log.gz)

## Expected Behavior

The plugin works and fires onLocation event for 15 minutes but I expect it to not stop firing the events since the device is moving (changing location on foot and then by car)
Phone is locked with screen off.

## Steps to Reproduce

1.
2.
3.
4.

## Context

Track my company cars while they do travel with clients

**Comment by christocracy** [comment]
Closed for ignoring issue template.

**Comment by stefanminch** [comment]
I am sorry I was still writing :)

**Comment by stefanminch** [comment]
> Closed for ignoring issue template.

Could we

**Comment by christocracy** [comment]
http://dontkillmyapp.com

**Comment by christocracy** [comment]
- Upgrade to latest 3.0.0.
- Upgrade your cordova version.  Cordova-android@6.3.0 is over a year old.

**Comment by stefanminch** [comment]
> http://dontkillmyapp.com

So not much we can do I guess? The app should stay activated, would that work?

**Comment by christocracy** [comment]
Do you know what this means:
```
04-21 01:12:40.105 INFO [BackgroundGeolocation onActivityDestroy] 
╔═════════════════════════════════════════════
║ MainActivity was destroyed
╠═════════════════════════════════════════════
╟─ stopOnTerminate: true  <---------------------------------
╟─ enabled: false
```

**Comment by christocracy** [comment]
Also, your reported plugin version is incorrect (and therefore your reported cordova version is also incorrect).  You *are* using `v3.0.0`.

>Plugin version: 2.10.1

```
04-21 12:50:56.106 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.0.10 (310)
╠═════════════════════════════════════════════
{
```

**Comment by christocracy** [comment]
you will want to provide `reset: true` to `#ready` method during development.

Read docs for `#ready` method, paying particular attention to the note about `reset: true`

**Comment by stefanminch** [comment]
> Also, your reported plugin version is incorrect (and therefore your reported cordova version is also incorrect). You _are_ using `v3.0.0`.
> 
> > Plugin version: 2.10.1
> 
> ```
> 04-21 12:50:56.106 INFO [TSConfig print] 
> ╔═════════════════════════════════════════════
> ║ TSLocationManager version: 3.0.10 (310)
> ╠═════════════════════════════════════════════
> {
> ```

Yes my mistake, the versions were copied from the wrong file :(. 
We have upgraded recently to the latest plugin version: 3.0.0

<plugin name="cordova-background-geolocation" source="git"            spec="https://8f3d50a7cb4142a3e658821d98a6a332c3fd4909@github.com/transistorsoft/cordova-background-geolocation.git#3.0.0">

    <preference name="phonegap-version" value="cli-8.1.1"/>

**Comment by stefanminch** [comment]
> you will want to provide `reset: true` to `#ready` method during development.
> 
> Read docs for `#ready` method, paying particular attention to the note about `reset: true`

Yes the current use case is with reset: true

var androidConfig = {
          reset: true,
          desiredAccuracy: 0,
          distanceFilter: 0,
          allowIdenticalLocations: false,
          fastestLocationUpdateInterval: 1000,
          locationUpdateInterval: 5000,
          foregroundService: true,
          notificationTitle: 'Lucky Driver',
          notificationText: 'Background Location Tracking Enabled',
          heartbeatInterval: 60,
          stopOnTerminate: false,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
        };

**Comment by stefanminch** [comment]
> Do you know what this means:
> 
> ```
> 04-21 01:12:40.105 INFO [BackgroundGeolocation onActivityDestroy] 
> ╔═════════════════════════════════════════════
> ║ MainActivity was destroyed
> ╠═════════════════════════════════════════════
> ╟─ stopOnTerminate: true  <---------------------------------
> ╟─ enabled: false
> ```

Please look at the logs from 04-21 12:50:56.106 INFO [TSConfig print]

**Comment by stefanminch** [comment]
> > Do you know what this means:
> > ```
> > 04-21 01:12:40.105 INFO [BackgroundGeolocation onActivityDestroy] 
> > ╔═════════════════════════════════════════════
> > ║ MainActivity was destroyed
> > ╠═════════════════════════════════════════════
> > ╟─ stopOnTerminate: true  <---------------------------------
> > ╟─ enabled: false
> > ```
> 
> Please look at the logs from 04-21 12:50:56.106 INFO [TSConfig print]

My understanding is that this setting will let the background process still work even after my app gets killed.

**Comment by christocracy** [comment]
stopOnTerminate: true *really means* “stop on terminate”.

**Comment by stefanminch** [comment]
so in my case should be false?

**Comment by christocracy** [comment]
Ask yourself this question:  “do I want to **stop** tracking when the app is **terminated**?”

**Comment by stefanminch** [comment]
Gotcha, thank you very much. Will give it a try!
