### ISSUE TITLE
Geolocation inaccurated on battery saving plan

### ISSUE THREAD

**Issue by samuelfaj** [transistorsoft/cordova-background-geolocation-lt#913]
## Your Environment
* Plugin version: 
* Platform: Android
* OS version: 9
* Device manufacturer / model: Sansumg Galaxy S9
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): android 7.1.4
* Plugin config
```
{
			debug: false,
			logLevel: 0,
			desiredAccuracy: 0,
			// distanceFilter: 10,
			// disableElasticity: false,
			distanceFilter: 0,
			disableElasticity: true,
			stationaryRadius: 5,
			stopOnTerminate: false,
			startOnBoot: true,
			autoSync: true,
			batchSync: true,
			maxBatchSize: 20,
			autoSyncThreshold: 10,
			maxDaysToPersist: 7,
			enableHeadless: true,
			foregroundService: true,
			notificationText: "Aplicativo em monitoramento!",
			notificationColor: color,
			locationUpdateInterval: 5000,
			fastestLocationUpdateInterval: 10000,
			activityRecognitionInterval: 500,
			heartbeatInterval: 30,
			preventSuspend: true, //Enable this to prevent iOS from suspending your app in the background while in the stationary state. Must be used in conjunction with a #heartbeatInterval.
			stopTimeout: 5 //The number of minutes to wait before turning off location- services after the ActivityRecognition System (ARS) detects the device is STILL
		}
```
cordova-background-geolocation-lt 2.14.2 

## Actual Behavior
I've noticed that in battery saving energy plan the plugin gets inaccurate.
Can we solve it somehow?  

## Steps to Reproduce
1. Just apply battery saving energy plan.

![Captura de Tela 2019-04-24 às 17 54 16](https://user-images.githubusercontent.com/12994414/56693401-bcdc1180-66ba-11e9-8ace-1fe7a4fe5827.png)

**Comment by christocracy** [comment]
What do you expect?  Do you know what Android does to "save battery"?  It disables GPS.

**Comment by christocracy** [comment]
You can listen to `#onPowerSaveChange` event to learn when battery-saving is engaged.

**Comment by samuelfaj** [comment]
> You can listen to `#onPowerSaveChange` event to learn when battery-saving is engaged.
I did not know that. Thank you sou much!!!

BTW, in low cost phones distanceFilter may not work perfectly, right?

**Comment by christocracy** [comment]
>BTW, in low cost phones distanceFilter may not work perfectly, right?

Incorrect.
