### ISSUE TITLE
Exactly same configuration produces "holes" in some phones and others work perfectly

### ISSUE THREAD

**Issue by samuelfaj** [transistorsoft/cordova-background-geolocation-lt#914]
## Your Environment
* Plugin version: 
* Platform: Android
* OS version: 9
* Device manufacturer / model: Sansumg Galaxy S9 (working) and Moto G4 Plus (holes)
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): android 7.1.4
* Plugin config
```
{
	debug: false,
	logLevel: 0,
	desiredAccuracy: 0,
	distanceFilter: 0,
	disableElasticity: true,
	stationaryRadius: 5,
	stopOnTerminate: false,
	startOnBoot: true,
	autoSync: true,
	batchSync: true,
	maxBatchSize: 20,
	autoSyncThreshold: 10,
	maxDaysToPersist: 7,
	enableHeadless: true,
	foregroundService: true,
	notificationText: "Aplicativo em monitoramento!",
	notificationColor: color,
	locationUpdateInterval: 5000,
	fastestLocationUpdateInterval: 10000,
	activityRecognitionInterval: 500,
	heartbeatInterval: 30,
	preventSuspend: true,
	stopTimeout: 5
}
```
cordova-background-geolocation-lt 2.14.2 

## Actual Behavior
For you to understand, I have a carrier. I've created an app to track my employees and count the miles they've taken. Currently they use their own cellphones for this.

So I need the plugin to be as accurate as possible, preferably taking every 10 meters.

The point is that in my S9 works perfectly, I can track perfectly. On my collaborators phone, occasionally, holes appear in the trace, as you can see in the screenshots.

What can it be? How can I prevent it?

I need the application to be as accurate as possible and active all the time.

If you can help me ...
I would be very happy.

## Screenshots
S9 Working Fine:
![Captura de Tela 2019-04-24 às 20 49 50](https://user-images.githubusercontent.com/12994414/56700889-ea34b980-66d2-11e9-9d7b-4cc077ae5f65.png)

Holes in G4 (and others):
![Captura de Tela 2019-04-24 às 20 49 07](https://user-images.githubusercontent.com/12994414/56700894-f0c33100-66d2-11e9-8a62-0fe7b83e5c1a.png)

![Captura de Tela 2019-04-24 às 20 48 21](https://user-images.githubusercontent.com/12994414/56700914-0a647880-66d3-11e9-8a3f-191816b48520.png)

![Captura de Tela 2019-04-24 às 20 46 53](https://user-images.githubusercontent.com/12994414/56700915-0d5f6900-66d3-11e9-8acd-3f770ad293e4.png)

**Comment by christocracy** [comment]
your first step is to gather logs for the problem devices.  See wiki Debugging.

**Comment by christocracy** [comment]
Also see http://dontkillmyapp.com

**Comment by christocracy** [comment]
And you’ve neglected to post the **plugin version**.

You will also want to be doing *exhaustive* field-testing no problem devices using `debug: true, logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE` (So you *hear* its behavior in *real time*).

There are no magic solutions.

**Comment by samuelfaj** [comment]
> And you’ve neglected to post the **plugin version**.
> 
> You will also want to be doing _exhaustive_ field-testing no problem devices using `debug: true, logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE` (So you _hear_ its behavior in _real time_).
> 
> There are no magic solutions.

cordova-background-geolocation-lt 2.14.2

Some Days it works with all phones. 
So do you think it is Android killing the app? Or some power optimization?

I've already installed some plugins to avoid it, like:
at.gofg.sportscomputer.powermanagement 1.1.0 "PowerManagement"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"

But they wont work if i'm using enableHeadless, right?

What do you think about this?
https://github.com/snt1017/cordova-plugin-power-optimization

The best is user open app for times in times, right?

**Comment by christocracy** [comment]
- Get rid of background-mode plugin, it’s garbage.
- Upgrade to latest 3.0.x
- Gather and analyze the logs for “hole” periods.

**Comment by samuelfaj** [comment]
I guess that i fixed, using https://github.com/snt1017/cordova-plugin-power-optimization.

If may i suggest to integrate on plugin:
https://developer.android.com/training/monitoring-device-state/doze-standby

**Comment by christocracy** [comment]
See plugin docs [`DeviceSettings`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.devicesettings.html)
