### ISSUE TITLE
Plugin doesn't record location points even though the device is moving

### ISSUE THREAD

**Issue by stefanminch** [transistorsoft/cordova-background-geolocation-lt#915]
## Your Environment
* Plugin version:3.0.10
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Huawei P10 lite
* Cordova version (`cordova -v`): 8.1.1
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config

"activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "disableElasticity": false,
  "disableStopDetection": false,
  "distanceFilter": 15,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": 3000,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask",
  "heartbeatInterval": 60,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 10000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "notificationColor": "",
  "notificationLargeIcon": "",
  "notificationPriority": 0,
  "notificationSmallIcon": "",
  "notificationText": "Background Location Tracking Enabled",
  "notificationTitle": "Lucky Driver",
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "speedJumpFilter": 300,
  "startOnBoot": false,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 119711.9375,
  "isFirstBoot": false

Log:
[background-geolocation.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3119030/background-geolocation.log)

Screenshot locations:
![image](https://user-images.githubusercontent.com/19931102/56771558-abc8f880-67bf-11e9-9550-29c48d3e71a2.png)

## Actual Behavior

In the log files the trip starts at 20:50:44 and ends at 21:25:07, see the screenshot there are obviously missing location points although the device was moving (in a car)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by stefanminch** [comment]
I use the paid version :)

**Comment by christocracy** [comment]
- No such plugin version 3.0.10.  Check your package.json
- Huawei is the worst:  http://dontkillmyapp.com

**Comment by stefanminch** [comment]
3.0.0 sorry.
But shouldn't the new version just trigger on motion detection? Or you can't be actually sure?
Which low end Android phone would you recommend for background tracking purposes?

**Comment by stefanminch** [comment]
Have you tested with Xiaomi Redmi Go (Android stock Go)? I am testing with it now and it looks like it is doing ok.

**Comment by christocracy** [comment]
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Google Pixel @ 9.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0 **(bad)**
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0 **(bad)**
- OnePlus A5010 @ 8.0.0

**Comment by christocracy** [comment]
The Xiaomi Mi A2 consistently performs well.

**Comment by christocracy** [comment]
I’ve found that Huawei will often throttle motion and geofence events, firing them all-at-once when the device is unlocked after returning from a field test, like a constipated person eating a laxative.

**Comment by stefanminch** [comment]
I have noticed the same with the heartbeat events, sometimes these were delayed and stacked for 45 minutes! Is removing the battery optimisation setting actually changing anything like people on dontkillmyapp.com suggest?

**Comment by christocracy** [comment]
In my experience, there’s nothing to be done to solve Huawei or Nokia.

**Comment by stefanminch** [comment]
Lovely :) Thanks!
