### ISSUE TITLE
Invalid license key using debug apk

### ISSUE THREAD

**Issue by antho35** [transistorsoft/cordova-background-geolocation-lt#916]
## Your Environment
* Plugin version: 3.0.1
* Platform: Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 7.1.4
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0

* Plugin config
  `<plugin name="cordova-background-geolocation-lt" spec="^3.0.1">
        <variable name="LICENSE" value="YOUR_LICENSE_KEY" />
        <variable name="GOOGLE_API_VERSION" value="16.+" />
        <variable name="APPCOMPAT_VERSION" value="27.+" />
        <variable name="OKHTTP_VERSION" value="3.12.+" />
        <variable name="EVENTBUS_VERSION" value="3.0.0" />
        <variable name="ANDROID_PERMISSIONS_VERSION" value="0.1.8" />
    </plugin>` 

## Expected Behavior
Using a debug apk, backgroundGeolocation should run in evaluation mode

## Actual Behavior
popup "LICENSE VALIDATION FAILURE Invalid license key : YOUR_LICENSE_KEY" + bgGeo is undefined

## Context
I have already remove/readd plugin and platform but nothing works

**Comment by unugurhamit** [comment]
add this line to your AndroidManifest.xml and replace *** with your licence key.
<meta-data android:name="com.transistorsoft.locationmanager.license" android:value="***" />

**Comment by antho35** [comment]
this line is already added !

I haven't purchased any license, I just want to use evaluation mode.
It worked few weeks ago but since a platform update it doesn't work.

**Comment by christocracy** [comment]
Ignore anything related to license until you purchase one.

Show me your:
```
$ cordova plugins
```

**Comment by christocracy** [comment]
And what do you mean by “platform update”?

**Comment by antho35** [comment]
![cordova_plugins](https://user-images.githubusercontent.com/33059271/56809301-d6549900-6833-11e9-92e8-45800a57a54e.PNG)

**Comment by antho35** [comment]
I think the first build has been made with android 7.1.1 and now I passed to 7.1.4

**Comment by christocracy** [comment]
$ cordova platform remove android 
$ cordova platform add android
$ cordova plugin remove cordova-background-geolocation-lt
$ cordova plugin add cordova-background-geolocation-lt
$ cordova build android

**Comment by antho35** [comment]
Same issue, same popup, bgGeo is still undefined

**Comment by christocracy** [comment]
If it’s undefined, the plugin is not installed.  You should investigate your installed plugins.

**Comment by christocracy** [comment]
**Or**:
- You're attempting to use the plugin in Javascript *before* the `platformready` event has fired.
- You're attempting to use the plugin in a web browser (the plugin only exists on real devices or simulators.

**Comment by yochyG** [comment]
I'm having the same problem.

**Comment by antho35** [comment]
My plugin is installed.
- I'm using the plugin after the platformready event has fired
- I'm using the plugin on real device but debugging with inspect chrome devtools

**Comment by christocracy** [comment]
Create a new Hello World project and test the plugin in isolation.

**Comment by yochyG** [comment]
Created a new hello world project. I still get the "invalid license key" message but it works.

**Comment by yochyG** [comment]
Ok so for me it breaks when I downgrade the version of GOOGLE_API_VERSION. 
I had to that because of another plugin I'm using (phonegap-plugin-push).
I'm still playing around to see how I can make this two plugins work together.
Will keep you updated.
@antho35 did you also downgrade the version?

**Comment by christocracy** [comment]
You need to use play-services version > 12.0.0.  16.0.0 is latest (recommended).

Show me your plugins and platforms/android/project.properties

**Comment by antho35** [comment]
No, I didn't downgrade the version 

![cordova_plugin](https://user-images.githubusercontent.com/33059271/56962400-bdf7bd80-6b56-11e9-80cc-1d103436ce11.PNG)

**Comment by christocracy** [comment]
agains:  **Show me** your `platforms/android/project.properties`

**Comment by antho35** [comment]
![project properties](https://user-images.githubusercontent.com/33059271/56962578-39596f00-6b57-11e9-990c-7937b924aaf9.PNG)

**Comment by christocracy** [comment]
Why are you posting *screenshots* of **text**.  Paste the text (edit your post)

**Comment by yochyG** [comment]
@christocracy I think what's happening is that for some reason the code is not working (one reason or the other) and since people see the error "invalid license key" they think that's the reason.

**Comment by christocracy** [comment]
Are you watching your app boot with `$ adb logcat -s TSLocationManager`, eg:
```
04-30 09:14:49.830 17012 17012 I TSLocationManager: ╟─ android.intent.action.MY_PACKAGE_REPLACED
04-30 09:14:49.843 17012 17012 I TSLocationManager: [c.t.l.service.HeartbeatService b]
04-30 09:14:49.843 17012 17012 I TSLocationManager:   🎾  Start heartbeat (60s)
04-30 09:14:49.852 17012 17012 I TSLocationManager: [c.t.l.s.ActivityRecognitionService a]
04-30 09:14:49.852 17012 17012 I TSLocationManager:   🎾  Start motion-activity updates
04-30 09:14:49.880 17012 17012 I TSLocationManager: [c.t.l.g.TSGeofenceManager start]
04-30 09:14:49.880 17012 17012 I TSLocationManager:   🎾  Start monitoring geofences
04-30 09:14:49.893 17012 17012 D TSLocationManager: [c.t.l.http.HttpService startMonitoringConnectivityChanges]
04-30 09:14:49.893 17012 17012 D TSLocationManager:   🎾  Start monitoring connectivity changes
04-30 09:14:49.900 17012 17012 D TSLocationManager: [c.t.locationmanager.device.a c]
04-30 09:14:49.900 17012 17012 D TSLocationManager:   🎾  Start monitoring powersave changes
⏳ startBackgroundTask: 1
04-30 09:14:51.564 17012 17012 D TSLocationManager: [c.t.locationmanager.util.b a]
04-30 09:14:51.564 17012 17012 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
04-30 09:14:51.785 17012 17012 D TSLocationManager: [c.t.l.s.ActivityRecognitionService a]
04-30 09:14:51.785 17012 17012 D TSLocationManager:   🚘 ️DetectedActivity [type=STILL, confidence=100]
04-30 09:14:51.821 17012 17012 D TSLocationManager: [c.t.l.s.ActivityRecognitionService onDestroy]
04-30 09:14:51.821 17012 17012 D TSLocationManager:   🔴  ActivityRecognitionService destroyed
04-30 09:14:52.093 17012 17012 I TSLocationManager: [c.t.l.s.ActivityRecognitionService a]
04-30 09:14:52.093 17012 17012 I TSLocationManager: ╔═════════════════════════════════════════════
04-30 09:14:52.093 17012 17012 I TSLocationManager: ║ Motion Transition Result
04-30 09:14:52.093 17012 17012 I TSLocationManager: ╠═════════════════════════════════════════════
04-30 09:14:52.093 17012 17012 I TSLocationManager: ╟─ 🎾  ENTER: still
04-30 09:14:52.093 17012 17012 I TSLocationManager: ╚═════════════════════════════════════════════
04-30 09:14:52.197 17012 17012 D TSLocationManager: [c.t.l.s.ActivityRecognitionService onDestroy]
04-30 09:14:52.197 17012 17012 D TSLocationManager:   🔴  ActivityRecognitionService destroyed
04-30 09:14:52.767 17012 17012 D TSLocationManager: [c.t.l.adapter.TSConfig$Builder setNotification] ************ setNotification: {"layout":"","title":"","text":"","smallIcon":"","largeIcon":"","strings":{},"actions":[]}, currentValue: {"layout":"notification_layout","title":"2019-04-30 09:11:32.728636","text":"This is a test","smallIcon":"","largeIcon":"","strings":{},"actions":[]}
04-30 09:14:52.771 17012 17012 D TSLocationManager: [c.t.l.a.TSConfig$Notification a] ********** isDirty: 3, [notification.title, notification.text, notification.layout]
04-30 09:14:52.825 17012 17048 I flutter : [activitychange] - [ActivityChangeEvent still (100%)]
04-30 09:14:52.826 17012 17012 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
04-30 09:14:52.831 17012 17048 I flutter : [activitychange] - [ActivityChangeEvent still (100%)]
04-30 09:14:52.883 17012 17012 I TSLocationManager: [c.t.l.service.HeartbeatService b]
04-30 09:14:52.883 17012 17012 I TSLocationManager:   🎾  Start heartbeat (60s)
04-30 09:14:52.886 17012 17085 I TSLocationManager: [c.t.l.http.HttpService flush]
04-30 09:14:52.886 17012 17085 I TSLocationManager: ╔═════════════════════════════════════════════
04-30 09:14:52.886 17012 17085 I TSLocationManager: ║ HTTP Service (count: 0)
04-30 09:14:52.886 17012 17085 I TSLocationManager: ╠═════════════════════════════════════════════
04-30 09:14:52.893 17012 17012 D TSLocationManager: [c.t.locationmanager.util.b a]
04-30 09:14:52.893 17012 17012 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
04-30 09:14:52.908 17012 17087 I TSLocationManager: - Enable: true → true, trackingMode: 1
04-30 09:14:52.916 17012 17087 I TSLocationManager: [c.t.l.service.HeartbeatService b]
04-30 09:14:52.916 17012 17087 I TSLocationManager:   🎾  Start heartbeat (60s)
04-30 09:14:52.917 17012 17012 I TSLocationManager: [c.t.l.http.HttpService flush]
04-30 09:14:52.917 17012 17012 I TSLocationManager: ╔═════════════════════════════════════════════
04-30 09:14:52.917 17012 17012 I TSLocationManager: ║ HTTP Service (count: 0)
04-30 09:14:52.917 17012 17012 I TSLocationManager: ╠═════════════════════════════════════════════
04-30 09:14:52.921 17012 17012 D TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :true
04-30 09:14:52.923 17012 17087 I TSLocationManager: [c.t.l.s.ActivityRecognitionService a]
04-30 09:14:52.923 17012 17087 I TSLocationManager:   🎾  Start motion-activity updates
04-30 09:14:52.929 17012 17087 I TSLocationManager: [c.t.l.g.TSGeofenceManager start]
04-30 09:14:52.929 17012 17087 I TSLocationManager:   🎾  Start monitoring geofences
04-30 09:14:52.940 17012 17087 D TSLocationManager: [c.t.l.http.HttpService startMonitoringConnectivityChanges]
04-30 09:14:52.940 17012 17087 D TSLocationManager:   🎾  Start monitoring connectivity changes
04-30 09:14:52.942 17012 17087 D TSLocationManager: [c.t.locationmanager.device.a c]
04-30 09:14:52.942 17012 17087 D TSLocationManager:   🎾  Start monitoring powersave changes
```

**Comment by antho35** [comment]
--------- beginning of main
04-30 14:10:55.954  6738  6983 D TSLocationManager: $ addLocationListener()
04-30 14:10:55.958  6738  6983 D TSLocationManager: $ addMotionChangeListener()
04-30 14:10:55.962  6738  6983 D TSLocationManager: $ ready()
--------- beginning of system
04-30 15:30:32.767 22889 23035 E TSLocationManager:
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╔═════════════════════════════════════════════
04-30 15:30:32.767 22889 23035 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.mycarlot.grooom
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╠═════════════════════════════════════════════
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╟─ Invalid license key: YOUR_LICENSE_KEY
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╚═════════════════════════════════════════════
04-30 15:30:32.997 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:30:33.007 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:30:33.015 22889 23035 D TSLocationManager: $ ready()
04-30 15:30:33.034 22889 23035 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
04-30 15:30:33.098 22889 23035 D TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :false
04-30 15:31:25.513 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:31:25.521 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:31:25.528 22889 23035 D TSLocationManager: $ ready()
04-30 15:33:42.230 22889 22889 I TSLocationManager: [c.t.l.a.BackgroundGeolocation$h onReceive]
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╔═════════════════════════════════════════════
04-30 15:33:42.230 22889 22889 I TSLocationManager: ║ Location-provider change: true
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╠═════════════════════════════════════════════
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╟─ GPS: true
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╟─ Network: true
04-30 15:33:42.271 22889 22889 I TSLocationManager: [c.t.l.a.BackgroundGeolocation$h onReceive]
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╔═════════════════════════════════════════════
04-30 15:33:42.271 22889 22889 I TSLocationManager: ║ Location-provider change: true
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╠═════════════════════════════════════════════
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╟─ GPS: true
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╟─ Network: true
04-30 15:34:49.615 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:34:49.618 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:34:49.622 22889 23035 D TSLocationManager: $ ready()
04-30 15:35:19.833 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:35:19.837 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:35:19.840 22889 23035 D TSLocationManager: $ ready()
04-30 15:38:57.103 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:38:57.109 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:38:57.113 22889 23035 D TSLocationManager: $ ready()
04-30 15:39:23.902 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:39:23.906 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:39:23.910 22889 23035 D TSLocationManager: $ ready()

**Comment by antho35** [comment]
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╟─ Invalid license key: YOUR_LICENSE_KEY
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
04-30 15:30:32.767 22889 23035 E TSLocationManager: ╚═════════════════════════════════════════════
04-30 15:30:32.997 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:30:33.007 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:30:33.015 22889 23035 D TSLocationManager: $ ready()
04-30 15:30:33.034 22889 23035 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
04-30 15:30:33.098 22889 23035 D TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :false
04-30 15:31:25.513 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:31:25.521 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:31:25.528 22889 23035 D TSLocationManager: $ ready()
04-30 15:33:42.230 22889 22889 I TSLocationManager: [c.t.l.a.BackgroundGeolocation$h onReceive]
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╔═════════════════════════════════════════════
04-30 15:33:42.230 22889 22889 I TSLocationManager: ║ Location-provider change: true
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╠═════════════════════════════════════════════
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╟─ GPS: true
04-30 15:33:42.230 22889 22889 I TSLocationManager: ╟─ Network: true
04-30 15:33:42.271 22889 22889 I TSLocationManager: [c.t.l.a.BackgroundGeolocation$h onReceive]
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╔═════════════════════════════════════════════
04-30 15:33:42.271 22889 22889 I TSLocationManager: ║ Location-provider change: true
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╠═════════════════════════════════════════════
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╟─ GPS: true
04-30 15:33:42.271 22889 22889 I TSLocationManager: ╟─ Network: true
04-30 15:34:49.615 22889 23035 D TSLocationManager: $ addLocationListener()
04-30 15:34:49.618 22889 23035 D TSLocationManager: $ addMotionChangeListener()
04-30 15:34:49.622 22889 23035 D TSLocationManager: $ ready()

**Comment by christocracy** [comment]
Looks fine, but why are you calling `#ready` *multiple times*?  It's supposed to be called *just once*, each time the app boots.
```
04-30 15:30:33.015 22889 23035 D TSLocationManager: $ ready()
```

The plugin has booted.  It's is in *stopped* state, waiting for you to call `#start`.

**Comment by antho35** [comment]
Everything is ok !
Thanks !!

**Comment by raja-arumugam** [comment]
is there need to pay for license key?

**Comment by christocracy** [comment]
@raja-arumugam iOS is free.  Android requires purchase to unlock for release builds.  The plugin is fully functional in debug builds without a license so you can *try before you buy*.  Yes, you'll see a Toast message "License Validation Failure".  Ignore everything about license in debug builds.
