### ISSUE TITLE
Phone time instead of GPS time

### ISSUE THREAD

**Issue by AirChristophe** [transistorsoft/cordova-background-geolocation-lt#918]
Phone time instead of GPS time

## Your Environment
* Plugin version:
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: HUAWEI P8 Lite 2017 / PRA-LX1
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 7.1.4
* Plugin config

## Expected Behavior
I expected to received GPS time from the plugin instead of the phone time.
Is it possible to received also the GPS time (I guess there the GPS time with the position) ?

## Actual Behavior
I advanced my phone time to 10 minutes and I was surprised to see that the time received from the plugin (position.timestamp) was the phone time.
The time was 10 minutes in the future.

**Comment by christocracy** [comment]
The plugin receives its location from the native location api (CLLocation for iOS; Location for Android).

If you’re indoors, there is no GPS (the location will have come from WiFi).

**Comment by cutechsupport** [comment]
I'm also facing this same issue, getting mobile phone time not GPS time even WiFi turned off 

I don't want phone time, How do i get GPS time, really it is critical for us, because the logic fully based on Time

please assist.

**Comment by christocracy** [comment]
I have no idea what you’re taking about.  The  timestamp comes from CLLocation.timestamp (iOS) and Location.getTime (Android).  There’s no such thing on native api as directly “asking for GPS time vs asking for phone time”

See Config.enableTimestampMeta

**Comment by slava554** [comment]
It looks like getTimeNanos function of android.location.GnssClock do that thing.
The GNSS receiver in device usually gives data in NMEA format, that includes accurate time, received from satellites that have atomic clocks. It allows developers to synchronize clocks on multiple devices and do some awesome things like racing apps. It's sad that there is no way to receive gnss time in web, maybe you can provide it.

**Comment by christocracy** [comment]
I can’t find any docs that demonstrate how to get an instance of `GnssClock` from a `Location` delivered by `FusedLocationProviderClient`.
