### ISSUE TITLE
Location tracking inconsistent and varying on different devices

### ISSUE THREAD

**Issue by cathrinerathje** [transistorsoft/cordova-background-geolocation-lt#919]
## Your Environment
* Plugin version: 3.0.1
* Platform: Android
* OS version: Windows 10
* Device manufacturer / model: OnePlus 5T + OnePlus A0001
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): Android 6.4.0
* Plugin config

`configureBackgroundGeoLocation() {
    BackgroundGeoLocation.onLocation(this.onLocation.bind(this));
    
    BackgroundGeoLocation.ready({
      reset: true,
      desiredAccuracy: BackgroundGeoLocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stopOnTerminate: true
    }, (state) => {
      console.log('Backgroundgeolocation ready', state);
      BackgroundGeoLocation.start();
      console.log('Backgroundgeolocation started');
    });
  }`

## Expected Behavior
We want to be able to track the current position and general movement for the user and drawing the polyline of the route on the map.

## Actual Behavior
Plugin seems to work flawlessly about half the time, but sometimes it does not work until after some minutes has passed, almost like it has to "warm up" first.. Other times it does not work at all and nothing seems to be tracked. When that is the case we can manually deactivate Location on the device and activate it again, and then the plugin continues. This can happen several times during a test route.
We are testing on the two devices mentioned under Environment - OnePlus A0001 seems to work a bit better, but still not very consistent.

We were wondering if there are any device-specific things we need to be aware of or anything we can do to make sure Location services are fully optimized to work on the devices? We have of course enabled all location permissions on the devices.

## Steps to Reproduce
`import { Device } from '@ionic-native/device/ngx';`
`import BackgroundGeoLocation, { Location } from 'cordova-background-geolocation-lt';`

`backgroundGeolocation: any;`

in .ts file once tracking is started by the user:

`this.platform.ready().then(this.onDeviceReady.bind(this));`

`onDeviceReady() {
    this.device = (<any>window).device;
    this.configureBackgroundGeoLocation();
  }`

`configureBackgroundGeoLocation() {
    BackgroundGeoLocation.onLocation(this.onLocation.bind(this));
    
    BackgroundGeoLocation.ready({
      reset: true,
      desiredAccuracy: BackgroundGeoLocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stopOnTerminate: true
    }, (state) => {
      console.log('Backgroundgeolocation ready', state);
      BackgroundGeoLocation.start();
      console.log('Backgroundgeolocation started');
    });
  }`

`onLocation(location: Location) {
    //this.testSpeech(1);
    console.log('[location] -', location);
    console.log(location.coords.latitude);
    console.log(location.coords.longitude);

      this.currentPositionMarker.setPosition({lat: location.coords.latitude, lng: location.coords.longitude});
      this.map.setCenter({lat: location.coords.latitude, lng: location.coords.longitude});

      setTimeout(() => {
        this.trackedRoute.push({lat: location.coords.latitude, lng: location.coords.longitude});
        //for drawing polyline on map
        this.redrawPath(this.trackedRoute);
      }, 0);
  }`

When the user presses 'stop tracking':
`BackgroundGeoLocation.stop();`

**Comment by christocracy** [comment]
http://dontkillmyapp.com

**Comment by cathrinerathje** [comment]
As we understand it, that is mostly in regards to battery optimization. Are OnePlus devices in general also worse at tracking?

**Comment by christocracy** [comment]
My [OnePlus A5010](http://tracker.transistorsoft.com/transistor-ionic?device=Cordova-ONEPLUS-A5010&end=2019-4-30&start=2019-4-22) never fails.

**Comment by davidshieldsaz** [comment]
I've been getting this same feedback from a lot of my users recently too.  About half the devices on most of my accounts work half the time, it's a mix between Android and iOS devices.
