### ISSUE TITLE
Server is getting no  post parameters 

### ISSUE THREAD

**Issue by yugandharyadav** [transistorsoft/cordova-background-geolocation-lt#920]
## Your Environment
* Plugin version: 3.0.1
* Platform:  Android
* OS version: Windows 10
* Device manufacturer / model:
* Cordova version (`cordova -v`):  9.0.0
* Cordova platform version (`cordova platform ls`): 8.0.0
* Plugin config
   
    BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 10,
      stopTimeout: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      url: 'https://accountinggurutest.appspot.com/jobscustomreportsendpoint/v2/updateMobPartyUserLocation',
      autoSync: true,
      params: BackgroundGeolocation.transistorTrackerParams(this.device)
    }, (state) => {
      console.log('- Configure success: ', state);
      // Update UI state (toggle switch, changePace button)
      this.zone.run(() => {
        this.isMoving = state.isMoving;
        this.enabled = state.enabled;
      });
    });

## Expected Behavior
 
Background geolocation should send location parameters to the provided url.

## Actual Behavior
Server is not getting any parameters.

By the way I am not using PHP.

**Comment by christocracy** [comment]
Duplicate #2
