### ISSUE TITLE
Location service stopped logging location after some time in 'whenInUse' mode

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [transistorsoft/cordova-background-geolocation-lt#921]
After changing location authorization permission from 'always' to 'whenInUse', plugin din't
log locations.(Please check steps to reproduce)
 
* Plugin version: 3.0.0
* Platform: iOS 
* OS version:12.2
* Device manufacturer / model: iPhone 6 (iPhone8,1)
* Cordova version (`cordova -v`):7 
* Plugin config
   debug: true,
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                useSignificantChangesOnly: false,
                maxDaysToPersist: 14,
                stopOnTerminate: false,
                startOnBoot: true,
                foregroundService: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                autoSync: true,
                batchSync: true,
                maxBatchSize: 20,
                heartbeatInterval: 5,
                preventSuspend: true,
                disableElasticity: true,
                distanceFilter: 10,
                disableLocationAuthorizationAlert: true,
                locationAuthorizationRequest: "Any"

## Expected Behavior
Plugin should keep working when app is not terminated 

## Actual Behavior
Plugin stopped tracking locations

## Steps to Reproduce 
1.Change location authorization permission from 'always' to 'whenInUse'
2.Call the start method
3.Put app in background and traveled around 25 miles
4.Call the stop method
 
## Debug logs
I expect locations between 18:51 - 19:51
 <details>

2019-04-29 18:47:57.089 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 30.0

2019-04-29 18:47:57.093 ℹ️-[TSConfig persist] 

2019-04-29 18:47:57.098 🔵-[TSConfig incrementOdometer:] 6802.9

2019-04-29 18:47:57.120 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 45E381F7-CA3F-4447-94D6-F0A4B2ED5359

2019-04-29 18:47:57.122 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:error:] 
╚═══════════════════════════════════════════════════════════

2019-04-29 18:47:57.122 ⚠️-[TSHttpService flush:error:] No network connection

2019-04-29 18:47:59.156 ℹ️-[TSDBLogger db_save] Log committed

2019-04-29 18:48:00.611 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:05.044 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:08.227 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:10.758 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/66 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:13.296 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:13.604 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:15.836 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:15.836 🔵-[TSLocationManager startMotionTriggerTimer] Motion-trigger timer engaged: Stop-detection will trigger in 10 seconds...

2019-04-29 18:48:18.993 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:20.237 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:23.712 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:24.976 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:25.851 🔵-[TSLocationManager beginStopDetection] ⏲Stop-timeout engaged: 300 s...

2019-04-29 18:48:25.854 ✅-[BackgroundTaskManager createBackgroundTask] 39

2019-04-29 18:48:25.854 🎾-[BackgroundTaskManager startKeepAlive] 

2019-04-29 18:48:25.855 🔴-[TSLocationManager stopUpdatingLocation] 

2019-04-29 18:48:26.561 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:26.562 🔵-[TSLocationManager detectStopMotion:shakeCount:] Stationary-time: 0/300 s

2019-04-29 18:48:29.732 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:29.733 🔵-[BackgroundTaskManager startPreventSuspendTimer:] BG time remaining: 177 | Total tasks: 1

2019-04-29 18:48:29.733 🔵-[TSLocationManager detectStopMotion:shakeCount:] Stationary-time: 3/300 s

2019-04-29 18:48:31.000 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-29 18:48:31.000 🔵-[TSLocationManager detectStopMotion:shakeCount:] Stationary-time: 5/300 s

2019-04-29 18:51:41.578 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | in_vehicle/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 18:51:41.582 🎾-[TSLocationManager startUpdatingLocation] Location-services: ON

2019-04-29 18:51:41.582 🔴-[BackgroundTaskManager stopKeepAlive] 

2019-04-29 18:51:41.582 ℹ️-[TSLocationManager resetStopTimeoutTimer] 

2019-04-29 18:51:41.593 ℹ️+[LocationAuthorization run:onCancel:] status: 4

2019-04-29 18:51:41.593 ✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 39 OF (
    39
)

2019-04-29 19:51:50.421 🔵-[TSLocationManager onResume:] enabled? 1

2019-04-29 19:51:50.421 ℹ️-[LocationDAO purge:] 14

2019-04-29 19:51:50.440 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:error:] 
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:50.440 ⚠️-[TSHttpService flush:error:] No network connection

2019-04-29 19:51:50.440 ℹ️-[TSDBLogger db_save] Log committed

2019-04-29 19:51:50.440 ℹ️-[TSDBLogger db_delete] maxAge: 604800

2019-04-29 19:51:50.458 ℹ️-[TSDBLogger db_save] Log committed

2019-04-29 19:51:50.481 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/66 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:50.706 
📍<+30.34726474,+76.83659512> +/- 65.00m (speed -1.00 mps / course -1.00) @ 29/4/19, 7:45:08 pm India Standard Time

2019-04-29 19:51:50.707 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: 10.0m | age: 402.3s
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:50.707 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 30.0

2019-04-29 19:51:50.708 ℹ️-[TSConfig persist] 

2019-04-29 19:51:50.709 🔵-[TSConfig incrementOdometer:] 45233.5

2019-04-29 19:51:50.724 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 319FFC40-7F89-423B-99AC-75A3063F91F6

2019-04-29 19:51:50.725 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:error:] 
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:50.725 ⚠️-[TSHttpService flush:error:] No network connection

2019-04-29 19:51:50.763 
📍<+30.35201942,+76.82879315> +/- 4582.32m (speed -1.00 mps / course -1.00) @ 29/4/19, 7:51:50 pm India Standard Time

2019-04-29 19:51:50.763 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: 10.0m | age: 0.1s
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:50.763 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 30.0

2019-04-29 19:51:50.774 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 1DD69436-6901-4126-B060-DB5850D6B20E

2019-04-29 19:51:50.777 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:error:] 
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:50.777 ⚠️-[TSHttpService flush:error:] No network connection

2019-04-29 19:51:51.375 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:53.264 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/100 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:54.851 
📍<+30.34674069,+76.83889989> +/- 165.00m (speed -1.00 mps / course -1.00) @ 29/4/19, 7:51:54 pm India Standard Time

2019-04-29 19:51:54.852 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: 10.0m | age: 0.0s
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:54.852 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 30.0

2019-04-29 19:51:54.870 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 8207A3E5-C914-4C28-ADB4-487011111101

2019-04-29 19:51:54.870 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:error:] 
╚═══════════════════════════════════════════════════════════

2019-04-29 19:51:54.870 ⚠️-[TSHttpService flush:error:] No network connection

2019-04-29 19:51:56.158 🔵-[TSLocationManager onSuspend:] enabled? 1)

2019-04-29 19:51:58.963 ℹ️-[TSLocationManager init] {
    activityRecognitionInterval = 10000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 1;
    debug = 1;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    disableElasticity = 1;
    disableLocationAuthorizationAlert = 1;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    elasticityMultiplier = 1;
    enabled = 1;
    extras =     {
        guid = "9e835a5b-a249-4457-a7ff-8fcf7bc8c7b7";
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 1;
    lastLocationAuthorizationStatus = 4;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Any;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = 20;
    maxDaysToPersist = 14;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "45233.52856448961";
    params =     {
    };
    pausesLocationUpdatesAutomatically = 0;
    persistMode = 2;
    preventSuspend = 1;
    schedule =     (
    );
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 5;
    trackingMode = 1;
    url = "https://dcipreprodapi.onebcg.com//api/Common/LogHttpLocationsData";
    useSignificantChangesOnly = 0;
}

2019-04-29 19:51:58.965 ✅-[LocationDAO unlock]_block_invoke UNLOCKED ALL RECORDS

2019-04-29 19:51:58.967 ℹ️-[GeofenceDAO init] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay DOUBLE NOT NULL DEFAULT 0, extras TEXT)

2019-04-29 19:51:58.967 ℹ️-[GeofenceDAO init] CREATE index IF NOT EXISTS identifier ON geofences (identifier);CREATE index IF NOT EXISTS latitude ON geofences (latitude);CREATE index IF NOT EXISTS longitude ON geofences (longitude);CREATE index IF NOT EXISTS sin_latitude ON geofences (sin_latitude);CREATE index IF NOT EXISTS cos_latitude ON geofences (cos_latitude);CREATE index IF NOT EXISTS sin_longitude ON geofences (sin_longitude);CREATE index IF NOT EXISTS cos_longitude ON geofences (cos_longitude);

2019-04-29 19:51:58.973 ℹ️-[TSLocationManager on:success:failure:] heartbeat

2019-04-29 19:51:58.973 🔵-[TSLocationManager ready] 

2019-04-29 19:51:58.984 ℹ️-[TSLocationManager doStart:] trackingMode: 1

2019-04-29 19:51:58.984 🎾-[TSGeofenceManager start] 

2019-04-29 19:51:58.984 🎾-[SOMotionDetector startDetection] 

2019-04-29 19:51:58.985 🔵-[TSLocationManager setPace:] 1

2019-04-29 19:51:58.985 🎾-[SOMotionDetector startShakeDetection:] sample-rate: 0.2 | M7 DISABLED

2019-04-29 19:51:59.080 🎾-[TSLocationManager startUpdatingLocation] Location-services: ON

</details>

**Comment by christocracy** [comment]
There is, of course, a consequence to using “WhenInUse”, and this is that most iOS apis that the plugin relies upon, including Geofencing and the SLC (significant location changes) apis, no longer work in the background.

With WhenInUse, the user must *manually* engage tracking while the app is in foreground via your UI (eg a button that executes `changePace(true)`).

Have you read the docs for this option?

You may listen to onProviderChange event to learn if user selects this mode, and warn them against it.

**Comment by Gurjit-ONEBCG** [comment]
> Geofencing

Thanks Chris for you reply.

What I understood is that if the app is in foreground then the service will not work(Please correct me if I am wrong)

Yes I always call chagepace(true) immediate after calling start method of plugin

`
                BackgroundGeolocation.start(state => {
                    BackgroundGeolocation.changePace(true);
                }, error => {
                });` 

In my requirement I can not force user to choose 'always' permission.
So in case app is not terminated location should log with 'whenInUse' permission as well.

**Comment by christocracy** [comment]
>So in case app is not terminated location should log with 'whenInUse' permission as well.

Only if you've executed `changePace(true)` while in the foreground.  

Imagine a "Jogging app" authorized for "WhenInUse".  The user clicks a `[Start Workout]` button, which executes `changePace(true)`.  When app goes to background, iOS renders a "Blue Bar" reading "Some App is using your location".  The plugin is alive in the background until `stopTimeout` expires, when the plugin will turn off location-services.  The plugin cannot automatically trigger location services back on while in the background.

`stopOnTerminate: false` / `startOnBoot: true` **cannot** work with `WhenInUse`.

**Comment by Gurjit-ONEBCG** [comment]
> in will turn off location-service

So my problem's will be fixed.
If I call changepace(true) when
1) app goes in stationary position (using onMotionChange event to detect stationary state)
2) when app goes in foreground ( platform resume event)

Please suggest if it will work

**Comment by christocracy** [comment]
Try it, but if you attempt to keep location-services on **all the time** (24h / day) with `WhenInUse`, you're going to fail.

**Comment by Gurjit-ONEBCG** [comment]
> Try it, but if you attempt to keep location-services on **all the time** (24h / day) with `WhenInUse`, you're going to fail.

 Agreed, but my only target is to get location when the app is opened.
Thanks for your help. I will share results after performing your suggestion

**Comment by christocracy** [comment]
> but my only target is to get location when the app is opened.

What's wrong with using `#getCurrentPosition` for that?

**Comment by Gurjit-ONEBCG** [comment]
> > but my only target is to get location when the app is opened.
> 
> What's wrong with using `#getCurrentPosition` for that?

-In my requirement I need to draw route from user starting position to destination or where user ends the service.
-Our client strictly asked to not force user for 'always' permission( But it will be user's wish to choose either 'always' or 'whenInUse'
-If I use getcurrentPosition then users will not take advantage who would have set 'always' permission.
- I will require to write separate logic for iOS

One more question please, 
What max value I can set for stopTimeout (in case iOS)

**Comment by christocracy** [comment]
>What max value I can set for stopTimeout (in case iOS)

Infinity.

**Comment by Gurjit-ONEBCG** [comment]
> > What max value I can set for stopTimeout (in case iOS)
> 
> Infinity.

I think this would be best solution, because I don't need to care about user device's battery

**Comment by Gurjit-ONEBCG** [comment]
I set changepace(true) in the foreground and when app goes in stationary state
` BackgroundGeolocation.onMotionChange((event) => {
                if (!event.isMoving) {
                    BackgroundGeolocation.changePace(true);
                    console.log('- in stationary');
                }

            });`

But locations not logged between 16:11 - 16.21
<details>
 BackgroundGeolocation.onMotionChange((event) => {
                if (!event.isMoving) {
                    BackgroundGeolocation.changePace(true);
                    console.log('- in stationary');
                }

            });
</details>

**Comment by christocracy** [comment]
See [disableStopDetection](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#disablestopdetection)

**Comment by Gurjit-ONEBCG** [comment]
> See [disableStopDetection](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#disablestopdetection)

Thanks Chris, for your reply. 
So with this I don't need stoptimeout property.
I will share the results asap.

**Comment by christocracy** [comment]
>So with this I don't need stoptimeout property.

Not if you configure `pausesLocationUpdatesAutomatically: false`, as well.

Be careful with `pausesLocationUpdatesAutomatically: false`.  If you set that `true`, location-services will **NEVER** turn off, *ever*.  It's also a tri-state parameter:

1.  `false`:  location-services will never turn off once turned on with `changePace(true)`.
2.  `true`:  `stopTimeout` **is ignored**.  iOS will automatically turn off location-services *exactly* 20 minutes after device is detected to be *stationary*.
3.  `null`:  Enable plugin's `stopTimeout` mechanism.

**Comment by Gurjit-ONEBCG** [comment]
> > So with this I don't need stoptimeout property.
> 
> Not if you configure `pausesLocationUpdatesAutomatically: false`, as well.
> 
> Be careful with `pausesLocationUpdatesAutomatically: false`. If you set that `true`, location-services will **NEVER** turn off, _ever_. It's also a tri-state parameter:
> 
> 1. `false`:  location-services will never turn off once turned on with `changePace(true)`.
> 2. `true`:  `stopTimeout` **is ignored**.  iOS will automatically turn off location-services _exactly_ 20 minutes after device is detected to be _stationary_.
> 3. `null`:  Enable plugin's `stopTimeout` mechanism.

Thanks Chris, 
What I understood is that location service will never off until I call the stop method
with following settings.
 
' disableStopDetection: true,
  pausesLocationUpdatesAutomatically: false'

**Comment by christocracy** [comment]
>What I understood is that location service will never off until I call the stop method

Correct.  `#stop` or `changePace(false)`.

**Comment by christocracy** [comment]
Do the same test with `Always` authorization.

**Comment by Gurjit-ONEBCG** [comment]
> Do the same test with `Always` authorization.

Everything was working fine with 'Always'.
But I want my application work with 'WhenInUse'  like 'Runtastic' app.
Assume I am building a fitness app and I want keep tracking until user click stop button

**Comment by christocracy** [comment]
Do the same test with `Always` **and** `pausesLocationUpdatesAutomatically: false`.  Let me know if you see *this* in the logs:
```
2019-05-02 19:41:17.147 🔵-[TSLocationManager locationManagerDidPauseLocationUpdates:] Paused location-updates
```

**Comment by Gurjit-ONEBCG** [comment]
> Do the same test with `Always` **and** `pausesLocationUpdatesAutomatically: false`. Let me know if you see _this_ in the logs:
> 
> ```
> 2019-05-02 19:41:17.147 🔵-[TSLocationManager locationManagerDidPauseLocationUpdates:] Paused location-updates
> ```

Sure, I will test and will share the data. Thanks

**Comment by Gurjit-ONEBCG** [comment]
Did the same test with Always and pausesLocationUpdatesAutomatically: false

- Expected locations logged
- Yes, a  Paused location-updates log logged at 19:20:14.060 

Sorry, uploading the zip file of logs , so that you can see all the information (its only of single test)
[background-geolocation (1).log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3142426/background-geolocation.1.log.gz)

**Comment by christocracy** [comment]
I think there's a bug in the iOS library with `pausesLocationUpdatesAutomatically`.

Try this:

```javascript
await BackgroundGeolocation.setConfig({
  pausesLocationUpdatesAutomatically: true
});

BackgroundGeolocation.ready({
  reset: true,
  pausesLocationUpdatesAutomatically: false,
  .
  . <all your other config>
  .
});
```

**Comment by christocracy** [comment]
Actually, that won't work.  Thinking....

**Comment by christocracy** [comment]
Ok, try that.

**Comment by Gurjit-ONEBCG** [comment]
> Ok, try that.

Thanks Chris, for your valuable response.
Okay I will try that, and will try to bring results during weekend

**Comment by christocracy** [comment]
Are you using Typescript in your project?

**Comment by Gurjit-ONEBCG** [comment]
> Are you using Typescript in your project?

Yes IONIC 3 , Angular 5 with type script

**Comment by Gurjit-ONEBCG** [comment]
> Ok, try that.

Thanks Chris,
It worked. And I don't see 'Paused location-updates'  log.
[background-geolocation.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3148706/background-geolocation.log.gz)

If its a bug, are you planning any release for its fixes.

**Comment by christocracy** [comment]
>If its a bug, are you planning any release for its fixes.

Of course I am.  I can't tell you when.

**Comment by Gurjit-ONEBCG** [comment]
> > If its a bug, are you planning any release for its fixes.
> 
> Of course I am. I can't tell you when.

Cool!  Thanks for your support.
