### ISSUE TITLE
BackgroundGeolocation.removeListeners() disables listeners that are added after the call

### ISSUE THREAD

**Issue by stefanminch** [transistorsoft/cordova-background-geolocation-lt#923]
Plugin version:3.0.10
Platform: Android
OS version: 8.0.0
Device manufacturer / model: Xiaomi Redmi Go
Cordova version (cordova -v): 8.1.1
Cordova platform version (cordova platform ls): 6.3.0
Plugin config

## Expected Behavior
I have the following code:

``` javascript
       try {
            BackgroundGeolocation.removeListeners();
        } catch (e) {
            Logger.addLog("error:"+e);
            alert(JSON.stringify(e));
        }

        var successFn = function (location) {
          geolocationSuccess(location);
        };

        var failureFn = function (error) {
          geolocationError(error);
        };

        BackgroundGeolocation.onLocation(successFn, failureFn);

        BackgroundGeolocation.onHeartbeat(function() {
          sendHeartbeat();
        });

        var userData = localStorage.getObject(config.access_user_data);
        var token=null;
        if (userData && userData.authenticationToken) {
         token = userData.authenticationToken;
        }

        var androidConfig = {
          reset: true,
          desiredAccuracy: 0,
          distanceFilter: 15,
          allowIdenticalLocations: false,
          fastestLocationUpdateInterval: 3000,
          locationUpdateInterval: 10000,
          foregroundService: true,
          notificationTitle: 'Lucky Driver',
          notificationText: 'Background Location Tracking Enabled',
          heartbeatInterval: 60,
          stopOnTerminate: false,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
          /*headers: {
              "Authentication-Token": token
          },
          httpRootProperty: 'data',
          locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>,"time":<%= timestamp %>}'*/
        };


        var iosConfig = {
          reset: true,
          desiredAccuracy: 0, // meters
          stationaryRadius: 5, // meters
          distanceFilter: 10, // meters
          stopOnTerminate: false,

          activityType: 'AutomotiveNavigation',
          preventSuspend: true,
          heartbeatInterval: 60,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
        };

        BackgroundGeolocation.ready(ionic.Platform.isIOS() ? iosConfig : androidConfig, function (state) {
          if (!state.enabled) {
            console.log('[ready] success', state);
            BackgroundGeolocation.start();
          }
        });
```
After I call removeListeners and then add my listeners they never get called, if I remove that line it works and the listeners get called.

## Actual Behavior
remove listeners to remove the listeners but to allow to add new ones later on.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
That's right.  These plugin methods are *asynchronous*, they *take time* to execute.  

Why are you even calling `#removeListeners` before `#ready`, it's pointless.

You're not calling `#ready` *multiple times* are you?  `#ready` is designed to be *just once*.

**Comment by christocracy** [comment]
But if you *really* want to pointlessly `#removeListeners` like that, you should `await` (obviously that requires the containing method to marked `async`.

```
await BackgroundGeolocation.removeListeners();
```

**Comment by stefanminch** [comment]
Got it!
Well the thing is I am stopping the plugin when the user presses a button and the old listeners remain in there. So after it is stopped I call the ready method again in order to start it, is that correct?

**Comment by christocracy** [comment]
- You **DO NOT CALL `#ready` AGAIN!**.  **NEVER CALL `#ready` MORE THAN ONCE!
- You **DO NOT** need to `removeListeners`
- If you want to *stop tracking*, simply `#stop`.  There is no need to `#removeListeners`.

Imagine the plugin is your stereo.  Listeners are speakers.  When you turn your stereo off, do you disconnect the speakers?  No, you simply click the power *OFF* button (ie: `#stop`).  If the plugin is stopped, no signals will be emitted through the event-listeners, **ever**.

**Comment by stefanminch** [comment]
I am reloading the plugin and I need different listeners since on different pages of the app the listeners implement different logic. I can handle it in other way of course, but it looked convinient to add different functions on the different pages of the app.

**Comment by stefanminch** [comment]
But again you provide brilliant support!
Thank you very much for your help.
