### ISSUE TITLE
Server is not getting configured params.

### ISSUE THREAD

**Issue by yugandharyadav** [transistorsoft/cordova-background-geolocation-lt#924]
## Your Environment
* Plugin version: 3.0.1
* Platform:  Android
* OS version: Windows 10
* Device manufacturer / model:
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 8.0.0
* Plugin config

  BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 10,
      stopTimeout: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      url: 'http://bgsample.appspot.com/hello',
      params: {
        tenantId: '1234',
        branchId: 'abc123'
      },
      autoSync: true
    }, (state) => {
      console.log('- Configure success: ', state);
      // Update UI state (toggle switch, changePace button)
      this.zone.run(() => {
        this.isMoving = state.isMoving;
        this.enabled = state.enabled;
      });
    });

## Expected Behavior
The configured params should be appended to the body of the http request.

## Actual Behavior
The configured params are not appending to the body of the http request.

## Context
I was trying to pass authentication tokens by configuring params but it was not happening.

## Debug logs
{"location":{"event":"motionchange","is_moving":false,"uuid":"295a71e9-41b3-4708-bfa4-0ccf92f9ac78","timestamp":"2019-05-02T04:38:53.095Z","odometer":0,"coords":{"latitude":12.955851,"longitude":77.7164525,"accuracy":33.2,"speed":-1,"heading":-1,"altitude":815.2},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}},"device":{"model":"Redmi 6A","platform":"Android","uuid":"Redmi-6A","version":"8.1.0","manufacturer":"Xiaomi","framework":"Cordova"}}

I am using java appengine.

**Comment by christocracy** [comment]
You will find your `#params` 1 level *up* from `"location":{}`.

```
{
  tenantId: '1234',  // <-- params are appended to the root of the data.
  branchId: 'abc123',
  location: {   // <-- You've only logged this
    .
    .
    .
  }
},

**Comment by christocracy** [comment]
Actually, you logged the whole response data.  See docs for [`#ready`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#ready) method, particularly the note about `reset: true`.

⚠️ Note:
The #ready method only applies the supplied Config for the first launch of the app — forever after, the plugin is going to remember every configuration change you apply at runtime (eg: setConfig) and reload that same config every time your app boots. Changes to the Config supplied to ready after first launch will not take effect. During development, it's helpful to provide reset true.




```
{"location":{
  "event":"motionchange",
  "is_moving":false,
  "uuid":"295a71e9-41b3-4708-bfa4-0ccf92f9ac78",
  "timestamp":"2019-05-02T04:38:53.095Z",
  "odometer":0,
  "coords": {"latitude":12.955851,"longitude":77.7164525,"accuracy":33.2,"speed":-1,"heading":-1,"altitude":815.2},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}},
  "device":{   // <-- These are your params.
    "model":"Redmi 6A",
    "platform":"Android",
    "uuid":"Redmi-6A",
    "version":"8.1.0",
    "manufacturer":
    "Xiaomi",
    "framework":"Cordova"}
}
```
