### ISSUE TITLE
Persistent Notification disappears and reappears 

### ISSUE THREAD

**Issue by ajincentfit** [transistorsoft/cordova-background-geolocation-lt#928]
On the new version 3 release, I find the plugin to be overall more reliable on Android.

However, I see the architecture change included starting and stopping the service on movement which has the side effect of causing the persistent notification to continuously disappear and reappear. Our users use currently use this persistent notification (on plugin ver 2) as a way to tell if tracking is active and easily click back to the app from the notifications drawer.

Since the notification exists sometimes and not others, it appears to be a buggy behavior the user and is annoying in general.
Is there any way to make the persistent notification persistent again? Perhaps it could be added as a config switch? We are holding off on releasing the new version of our app with version 3 until this is addressed.

If it makes a difference, we do have a valid license that we use for multiple apps.

**Comment by christocracy** [comment]
>Is there any way to make the persistent notification persistent again?

No.  I got far more complaints about "How do I hide the notification".

It should also conserve power not having a foreground-service running constantly.

**Comment by christocracy** [comment]
And the new 3.0 behaviour is *exactly* what other popular tracking app do, such as *Life 360*.

**Comment by christocracy** [comment]
And one of the primary reasons I refactored the Android service architecture is because of reports the Android 9 was terminating long-running foreground-services after 5 days.

Very difficult to reproduce, waiting 5 days, but I did in fact confirm this on my Pixel.

Android does *not* want you to run a foreground-service for long periods of time.
