### ISSUE TITLE
Background Tracking in Ionic 1        if (!state.enabled) { } condition fails 

### ISSUE THREAD

**Issue by mahesha12345** [transistorsoft/cordova-background-geolocation-lt#929]
First of all i thank you for such a wonderful plugin.
I am writing this mail seeking help.
After implement in one of the ionic 1 project. Main goal is to track location when in minimised state also when the app is killed.

I am using following code given by you in git.

```javascript
// Like any Cordova plugin, you must wait for deviceready before referencing the plugin.
function onDeviceReady() {
  // 1.  Listen to events
  var bgGeo = window.BackgroundGeolocation;

  bgGeo.onLocation(function(location) {
    console.log('[location] -', location);
  });

  bgGeo.onMotionChange(function(event) {
    console.log('[motionchange] -', event.isMoving, event.location);
  });

  bgGeo.onHttp(function(response) {
    console.log('[http] - ', response.success, response.status, response.responseText);
  });

  bgGeo.onProviderChange(function(event) {
    console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
  });

  // 2. Execute #ready method:
  bgGeo.ready({
    reset: true,
    debug: true,
    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    url: 'http://my.server.com/locations',
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true
  }, function(state) {    // <-- Current state provided to #configure callback
    // 3.  Start tracking
    console.log('BackgroundGeolocation is configured and ready to use');
    if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
  });

  // NOTE:  Do NOT execute any API methods which will access location-services
  // until the callback to #ready executes!
  //
  // For example, DO NOT do this here:
  //
  // bgGeo.getCurrentPosition();   // <-- NO!
  // bgGeo.start();                // <-- NO!
}
```

Issue 1:
--------
```
if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
```

following this code only else condition is working in my device. I am not able to get inside if condition. But using else condition i was able to save some raw data into database which later on will be latitude and longitude.

Issue 2:
--------
I am not able to execute this when i terminate the app.
Please explain which part of the code should i focus to get latitude and longitude when app is terminated. Target is to save latitude and longitude into database when app is terminated or when not in use.

**Comment by christocracy** [comment]
Please learn to use syntax-highlighting.  you surround your code with 3-backticks.

**Comment by christocracy** [comment]
See how *pretty* that is now?
![](https://dl.dropbox.com/s/upo3gzddgiato0w/Screenshot%202019-05-10%2018.59.17.png?dl=1)

![](https://dl.dropbox.com/s/sj3m7qf7vz4p3ih/Screenshot%202019-05-10%2018.59.53.png?dl=1)

**Comment by christocracy** [comment]
>following this code only else condition is working in my device. I am not able to get inside if condition. 

The plugin *persists its enabled state* and *automatically* starts itself if it was terminated while `#start`ed.  This is supposed to happen.

Also, in practice, you wouldn't *actually* do this:
```
if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
```
You `#start` the plugin from pressing some UI button.  If it were a jogging app, you'd render a `[Start Workout]` button that the user would click, where you'd execute `#start` and a `[Stop Workout]` button where you'd execute `#stop`.

- `#start` sets `state.enabled = true`
- `#stop` sets `state.enabled = false`.

Once the plugin's `#start` method is called, it's going to track that device forever and each time your reboot your app, the plugin's state is going to be `state.enabled === true` until you `#stop`.

>I am not able to execute this when i terminate the app.

If you're talking about Android, your entire Javascript app is terminated when user terminates the app.  Your Javascript code no longer exists.  Only the plugin's native Android service remains running where it continues to track.  This is why you want to configure the plugin's built-in [HTTP Service](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.httpevent.html) and let the plugin manage uploading locations to your server.

If you need to write your own code in the Android terminated state, you must write native Java in your own custom [Android Headless Task](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode)
