### ISSUE TITLE
how to persist change to plugin settings (related to UIBackgroundModes location and iOS app store rejection)

### ISSUE THREAD

**Issue by jimmont** [transistorsoft/cordova-background-geolocation-lt#93]
related to [the old repo issue around UIBackgroundModes location (and iOS app store rejection)]( https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132)

I see this key value pair inserted into the app automatically and would like to adjust the source of this option, is it best to edit and remove this from [plugin.xml](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L39) or something else? I see the key+value reinserted into `<cordova-project>/platforms/ios/ios.json` (and the app's plist file)  and assume it comes from plugin.xml.

ie remove from `<cordova-project>/plugins/com.transistorsoft.cordova.background-geolocation/plugin.xml`
```
        <config-file target="*-Info.plist" parent="UIBackgroundModes">
            <array>
                <string>location</string>
            </array>
        </config-file>
```

Each time I install the plugin?

**Comment by christocracy** [comment]
Yes, the plugin automatically adds the "location" key.

**Comment by jimmont** [comment]
Thanks very much @christocracy
