### ISSUE TITLE
plugin use

### ISSUE THREAD

**Issue by marking11** [transistorsoft/cordova-background-geolocation-lt#931]
## Your Environment
* Plugin version: last version
* Platform: iOS or Android
* OS version:8.0.0
* Device manufacturer / model:Huawei mate 10
* Cordova version (`cordova -v`):9.0.0
* Cordova platform version (`cordova platform ls`):android 8.0.0
* Plugin config

## Expected Behavior

1.The Client send request to agent.
2.The Agent affect a driver to client.
3.The client show the intenary of the agent in map
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
 --------- beginning of system
--------- beginning of main

**Comment by christocracy** [comment]
- **Plugin version: last version**
What is "last version"?

- **Plugin config**
Missing

Do you have a question?

**Comment by marking11** [comment]
**Plugin version: last version**
cordova-background-geolocation-lt 3.0.3 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"

Do you have a question?
How to use this plugin to do such feature, the client must see the itinerary if affected driver !  where to stock last position , the plugin stock them in this file https://my-server.com/locations ?

**Comment by christocracy** [comment]
>Plugin version: last version

This is why writing "last version" is *completely useless*.  The [latest version](https://github.com/transistorsoft/cordova-background-geolocation-lt/releases) is **`3.0..4`**.

>How to use this plugin to do such feature

Tell the plugin to `#start` as desired.  Configure the plugin with an `#url` to your server.  See [Http Guide](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.httpevent.html)

**Comment by christocracy** [comment]
Also see [Location](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.location.html) and [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

**Comment by marking11** [comment]
thanks for your response what is the use of https://my-server.com/locations ? 
and where the plugin stock the last position?

**Comment by christocracy** [comment]
>what is the use of https://my-server.com/locations ?

You create *your own server* to receive locations from the plugin.  The plugin will post HTTP requests to **YOUR** server.  The plugin has nothing to do with *your* server.  This is *your* job.

**Comment by marking11** [comment]
thanks for your answer
