### ISSUE TITLE
LICENSE VALIDATION FAILURE

### ISSUE THREAD

**Issue by PerryRylance** [transistorsoft/cordova-background-geolocation-lt#935]
I have followed the installation instructions on this repo

I've tried removing the android platform, and removing the plugin, then re-adding the platform, then the plugin.

I've built the app for release, signed it and loaded the APK up and am seeing `LICENSE VALIDATION FAILURE Invalid license key:` followed by our key.

Installed version is `cordova-background-geolocation-lt 3.0.5 "BackgroundGeolocation"`

I recently requested the new format key and added this as per the instructions in this repo's readme.

I don't have access to the private repo, our CEO purchased they key, I'm a technician.

Our key ends `a81b4c4c`

**Comment by christocracy** [comment]
What is your CEO’s github username?

**Comment by christocracy** [comment]
And show me your AndroidManifest.xml (show only last chars of key)

**Comment by PerryRylance** [comment]
@NickDuncanZA is our CEO

This is the contents of `/platforms/android/app/src`:

`
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="20002" android:versionName="2.0.2" package="com.CodeCabin.WPGoogleMapsApp" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.transistorsoft.locationmanager.license_key" android:value="[REDACTED]a81b4c4c" />
        <service android:exported="true" android:name="com.transistorsoft.cordova.backgroundfetch.HeadlessJobService" android:permission="android.permission.BIND_JOB_SERVICE" />
        <receiver android:name="com.transistorsoft.cordova.backgroundfetch.HeadlessBroadcastReceiver">
            <intent-filter>
                <action android:name="${applicationId}.event.BACKGROUND_FETCH" />
            </intent-filter>
        </receiver>
    </application>
    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="27" />
</manifest>
`

**Comment by christocracy** [comment]
Your `package="com.CodeCabin.WPGoogleMapsApp"` doesn't match the package your key was generated for.

Btw, your support subscription is expired.

**Comment by PerryRylance** [comment]
Thank you
