### ISSUE TITLE
Hide indicator on Background Location Services

### ISSUE THREAD

**Issue by billypap1** [transistorsoft/cordova-background-geolocation-lt#938]
I use this plugin to to get user's position in my iOS App.

I use startMonitoringSignificantLocationChanges with Background mode - locations enabled, when my app is terminated/killed I receive the new location update BUT there is an outlined indicator showing a geofence maybe, all the time. So, I want to use startMonitoringSignificantLocationChanges without Background Mode - Location. Is that possible?

So I have 2 options, 1) to have enabled location in background mode, and someway to hide this indicator when is not UpdatingLocation(). or 2) to use startMonitoringSignificantLocationChanges without background mode - location enabled.

Could you help me to hide indicator when startMonitoringSignificantLocationChanges or to make this work without background mode - location enabled?

## Your Environment
* Plugin version: Current
* Platform: iOS
* OS version: 12.2
* Device manufacturer / model: iPhone X
* Cordova version (`cordova -v`): Latest
* Cordova platform version (`cordova platform ls`): Latest
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

```

## Expected Behavior

Hiding indicator when it's on background mode.

## Actual Behavior

Showing indicator when it's on background mode.

</details>

**Comment by christocracy** [comment]
Please don’t specify **Version: Current**, it’s meaningless.

What version are you using?

**Comment by billypap1** [comment]
I use version 3.0.6 . Is it possible to hide outlined indicator, or to make startMonitoringSignificantLocationChanges working without background mode location - enabled? I tried to disable background mode location but then i didn't recieve any location update.

**Comment by christocracy** [comment]
Show me logs of your app booting.

**Comment by billypap1** [comment]
The app is working great. There isn't any problem, all working good. I recieve location updates etc. My question is: Can i hide outlined indicator when my app is terminated? Is that possible with this plugin?

**Comment by billypap1** [comment]
To understand better what I mean, I have seen in many apps which use background mode location that the outlined indicator doesn't show and appears (filled indicator) when gps is in use. Can I do that, with this plugin? startMonitoringSignificantLocationChanges to work in "silence mode" (outlined indicator, hidden), and then when a new location is available (indicator filled)?

**Comment by christocracy** [comment]
No you can’t hide it.  It’s there to warn the user that some app is passively monitoring their location, so they can take action to prevent that if they desire.
