### ISSUE TITLE
Delete a specific location from mysqlite database

### ISSUE THREAD

**Issue by CleatonPais** [transistorsoft/cordova-background-geolocation-lt#939]
I am looking for a function that can delete a specific location from SQLite database
similar to deleteLocation(locationId, success, fail) that is in mauron85/cordova-plugin-background-geolocation 

I have tried using #url in config and it deletes the location once it gets the 200 response from the server. what I want is to deletes once I get acknowledgement when the location is inserted into the database

Thanks in advanced

## Your Environment
* Plugin version:  3.0.6
* Platform: Android
* OS version: 5.1.1
* Device manufacturer / model: Oppo A37
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 7.1.4
* Plugin config provided to `#ready`:

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>what I want is to deletes once I get acknowledgement when the location is inserted into the database

If your goal is to prevent the plugin persisting *any* locations in SQLite, simply configure `maxRecordsToPersist: 0`.

No, there's no API to `deleteLocation`

**Comment by CleatonPais** [comment]
is there any other solution that can be used to delete a specific location?

how is location destroyed for SQLite database once 200 response is received from the server?

**Comment by christocracy** [comment]
What are you doing that’s so specialized that nobody in the last 5 years has required this?

**Comment by CleatonPais** [comment]
I want to be sure that every single location being sent is inserted into the database without any loss

**Comment by christocracy** [comment]
How does being able to #destroyLocation help you achieve that?

Have you read the HTTP Guide in the docs?  It explains how the plugin’s http / persistence operates.

**Comment by CleatonPais** [comment]
Yes I have read the documentation

I have made a function that retrieves the locations from SQLite and then sends the location to the server,
After getting an acknowledgement, I delete that location

**Comment by christocracy** [comment]
Why are you re-inventing in brittle JavaScript what’s already implemented in strong Native Java / Obj-c?

This plugin was originally designed for a disaster response.  It was designed to operate in environments where network may be destroyed.  When network was restored, it had to ensure that all recorded locations were uploaded to server, without missing anything, where life depended on it.

**Comment by CleatonPais** [comment]
How do we ensure that the data which was sent to server was received and inserted in db succesfully,
as 200 response which we get is for the successfull connectivity, but what if the DB is having an error ?

**Comment by christocracy** [comment]
Easy:  if db reports an insert error, that’s a perfect reason to return `500`, *not `200`*.

The plugin will keep trying to upload that location until it sees 200.

**Comment by CleatonPais** [comment]
Will try to create an error on DB side and check the response

Also is there a way to log what data is being sent and what response is received

**Comment by christocracy** [comment]
- Sent: no.  
- Response:  listen to #onHttp event.

**Comment by CleatonPais** [comment]
how do you find out what location data is being sent and if there is an error, which error it is

**Comment by christocracy** [comment]
Just listen to #onHttp and fake an error on your server.
