### ISSUE TITLE
Plugin stops tracking after sometime

### ISSUE THREAD

**Issue by CleatonPais** [transistorsoft/cordova-background-geolocation-lt#941]
The plugin stops tracking after sometime. tested on muntiple android devices with diffrent OS versions near same result

## Your Environment
* Plugin version: 3.0.6
* Platform: Android
* OS version: 9.1
* Device manufacturer / model: Oneplus 6
* Cordova version (`cordova -v`): 9.0.0 
* Cordova platform version (`cordova platform ls`): 7.1.4
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
bgGeo.ready({
        reset: true,    //overide to new plugin configuration 
        debug: false,    // Debug sounds & notifications
        logLevel: bgGeo.LOG_LEVEL_VERBOSE, 
        desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH, // Highest possible accuracy: GPS + Wifi + Cellular
        distanceFilter: 50, // Record a location every 50 meters.
        params: {
            "deviceuid": device.uuid,
            "salesperson_id": window.localStorage.getItem("userid"),
            "salesperson_name": "salesperson_"+window.localStorage.getItem("username")
        },
        autoSync: true, 
        stopOnTerminate: false,
    }
```

## Expected Behavior
Plugin should tracking in forground and background from when the start function is called to when the stop function is called

## Actual Behavior
Plugin stops tracking suddenly. Sometimes the license validation error toast pops up and also the tracking notification pops up but no locations are tracked  

## Steps to Reproduce

1. install platform android 7.1.4
2. install plugin
3. configure plugin to ready settings above 
4. tracking should start and stop on button click

## Context

locations should be tracked and sent to server consistently irrespective of application in foreground or background

## Debug logs

<details>
	<summary>Logs</summary>
In this case tracking started at 12/06/2019 14:28:35 and ended/crashed (without stopping tracking) at 12/06/2019 17:40:56.
 
ADB logcat for the time duration is below

```<!-- Syntax highlighting:  DO NOT REMOVE -->
06-12 13:06:58.281 30409 30545 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-12 16:14:16.220 20677 20801 E AndroidRuntime: FATAL EXCEPTION: Thread-14
06-12 16:14:16.220 20677 20801 E AndroidRuntime: Process: com.lenovo.anyshare.gps, PID: 20677
06-12 16:14:16.220 20677 20801 E AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.lenovo.anyshare.gps/com.ushareit.screenlock.ScreenLockService }: app is in background uid UidRecord{1edf614 u0a443 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
06-12 16:14:16.220 20677 20801 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1595)
06-12 16:14:16.220 20677 20801 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1550)
06-12 16:14:16.220 20677 20801 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
06-12 16:14:16.220 20677 20801 E AndroidRuntime: 	at com.ushareit.screenlock.ScreenLockService$1.run(SourceFile:86)
06-12 16:14:16.220 20677 20801 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: FATAL EXCEPTION: Thread-14
06-12 18:52:20.218 10026 10175 E AndroidRuntime: Process: com.lenovo.anyshare.gps, PID: 10026
06-12 18:52:20.218 10026 10175 E AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.lenovo.anyshare.gps/com.ushareit.screenlock.ScreenLockService }: app is in background uid UidRecord{1e5704d u0a443 RCVR idle change:uncached procs:1 seq(0,0,0)}
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1595)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1550)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at com.ushareit.screenlock.ScreenLockService$1.run(SourceFile:86)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-13 06:00:28.549 30229 30370 E AndroidRuntime: FATAL EXCEPTION: Thread-14android.content.ContextWrapper.startService(ContextWrapper.java:664)
06-12 16:14:16.220 20677 20801 E AndroidRuntime: 	at com.ushareit.screenlock.ScreenLockService$1.run(SourceFile:86)
06-12 16:14:16.220 20677 20801 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: FATAL EXCEPTION: Thread-14
06-12 18:52:20.218 10026 10175 E AndroidRuntime: Process: com.lenovo.anyshare.gps, PID: 10026
06-12 18:52:20.218 10026 10175 E AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.lenovo.anyshare.gps/com.ushareit.screenlock.ScreenLockService }: app is in background uid UidRecord{1e5704d u0a443 RCVR idle change:uncached procs:1 seq(0,0,0)}
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1595)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1550)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at com.ushareit.screenlock.ScreenLockService$1.run(SourceFile:86)
06-12 18:52:20.218 10026 10175 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

</details>

**Comment by Steffaan** [comment]
This is not an issue of this plugin. Check out https://dontkillmyapp.com/oneplus

Also make sure to buy a license key if building your app for production (release), since it won't run without a valid license on Android.

**Comment by CleatonPais** [comment]
Ok fine that is for Oneplus, but I have the same issue that occurs OPPO A37f , Android 5.1.1

I agree with the licence point, It indicates that my application is restarting in the background and the notification for tracking appears, but what is it not picking up locations?

**Comment by Steffaan** [comment]
Well I'm sorry to tell you this, but Oppo is even worse with background services. You can find that brand on the same page as well.

> Background services are being killed (including accessibility services, which then need re-enabling) every time you turn the screen off. 

**Workaround to fix the issue:**
- Pin your app to the recent apps screen
- List your app inside the security app on both sections (Startup manager & Floating app list)
- Turn off battery optimization

Your app will only work if u follow the steps mentioned above. It's already hard enough nowadays to keep the app alive on Android, let alone with the Chinese manufacturers who have the most terrible settings for apps being active in the background.

**Comment by christocracy** [comment]
I'm testing daily upon 10 Android devices in a backpack, left running for weeks at a time.  All perform perfectly except for *Huawei P20* (nothing I can do will make that work).

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Google Pixel @ 9.0.0
- Google Pixel 3 @ 9.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 8.0.0

**Comment by christocracy** [comment]
[](https://dl.dropbox.com/s/3g0kg5euyrcyfv9/Screenshot%202019-06-14%2007.38.46.png?dl=1)

**Comment by christocracy** [comment]
![](https://dl.dropboxusercontent.com/s/3g0kg5euyrcyfv9/Screenshot%202019-06-14%2007.38.46.png?dl=1)

**Comment by Steffaan** [comment]
Just a heads up, OnePlus just announced that they will stop closing background apps in the upcoming updates:

https://forums.oneplus.com/threads/recap-open-ears-forum-developer-community-goa-india.1101974/

So let's hope all other chinese manufacturers will follow :)
