### ISSUE TITLE
Upcoming iOS new location permission 'Just Once'

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [transistorsoft/cordova-background-geolocation-lt#942]
Hi Chris,

Apple is launching a new location permission i.e 'Just Once' in iOS 13.
https://techcrunch.com/2019/06/03/apple-ios-13-location-privacy/
Which may put effect on constant location tracking. So my concern is that will this plugin automatically handle and alert user to choose another required location permission in case user has selected 'Just Once' permission. Or you are planning something related to this.

Thanks!

**Comment by christocracy** [comment]
Yes.
