### ISSUE TITLE
Is Android license is one time paid?

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#945]
Is Android license is one time paid?

**Comment by christocracy** [comment]
Yes.  There's an optional $149 yearly maintenance fee for another year's access to latest updates / priority support.  The public npm version is mirrored from the private version about every 3 months.

Purchased keys will always unlock the npm version forever.

**Comment by Taxi4you** [comment]
So lets sum up:
1. It's 349$ for lifetime for Android license (iOS is free?) 
2. 149$ each year (or also one time), to have support?
3. What is the public npm version?

**Comment by christocracy** [comment]
>It's 349$ for lifetime for Android license (iOS is free?)

Yes.

>149$ each year (or also one time), to have support?

$149 yearly.  Optional.

>What is the public npm version?

When you install the plugin like this, you're installing [from npm version](https://www.npmjs.com/package/cordova-background-geolocation-lt)
```
$ cordova plugin add cordova-background-geolocation-lt
```
