### ISSUE TITLE
Location service stops after some time of closing app.

### ISSUE THREAD

**Issue by Suryalg** [transistorsoft/cordova-background-geolocation-lt#947]
## Your Environment
* Plugin version: 3.0.7
* Platform: Android
* OS version: Android Version 7.0 NRD90M
* Device manufacturer / model: Xiomi Redmi Note 4
* Cordova version : 8.0.0
* Cordova platform version : android 7.0.0
* Plugin config provided to `#ready`: 
this is the function I am calling onDeviceReady
```
var bgGeo;
function initiate_bg_location() {  
  // 1.  Listen to events
  bgGeo = window.BackgroundGeolocation;

  bgGeo.onLocation(function(location) {
    console.log('[location] -', location);
  });

  bgGeo.onMotionChange(function(event) {
    console.log('[motionchange] -', event.isMoving, event.location);
  });

  bgGeo.onHttp(function(response) {
    console.log('[http] - ', response.success, response.status, response.responseText);
  });

  bgGeo.onProviderChange(function(event) {
    console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
  });

  // 2. Execute #ready method:
  bgGeo.ready({
    reset: true,
    debug: true,
    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
    distanceFilter: 15,
    url: 'http://www.myserver.com/jsonapi/updatedriverlocations', 
	params: {
            user_Id: getStorage('zxc'),
			store_Server_Ip: getStorage('ssip'),
			store_Id: getStorage('str'),
			product_Id: getStorage('ijk'),  
			
            },
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true
  }, function(state) {    // <-- Current state provided to #configure callback
    // 3.  Start tracking
    console.log('BackgroundGeolocation is configured and ready to use');
    if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
  });

}
```

## Expected Behavior
App should send location through http continuously

## Actual Behavior
If I launch the app for first time the location is sending through http but after closing the app. after some time it stops sending. I have to re launch the then it sends again though for 5-6 times then again stops is something I am missing?
## Context
No matter the values of http params, i am saving the whole post data in json format in DB

**Comment by christocracy** [comment]
Closed for ignoring issue template.  Did you read what the **top of the issue template says**?


*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Suryalg** [comment]
ok.. open the issue. I will foollow the process and edit the issue

**Comment by christocracy** [comment]
Just click [New issue] button, **copy the template**  then edit *this* issue.  Paste the template and provide all the requested info.

**Comment by Suryalg** [comment]
I have done it

**Comment by christocracy** [comment]
See http://dontkillmyapp.com

**Comment by Suryalg** [comment]
1. I have changed power saving mode to no restriction for my app
2. Turned off battery saver
3. Auto start yes.

A) But still it stops. some times in active mode also
B) I have set distanceFilter: 0.1 for minor distance change to test. is their any sofisticate way?
