### ISSUE TITLE
Offline Only Mode

### ISSUE THREAD

**Issue by bryanrideshark** [transistorsoft/cordova-background-geolocation-lt#948]
Hi Chris

This is a question in the vein of #387, but it doesn't seem like there's a clear answer to what I'm asking for.

We're creating a trip logger - but we want to avoid using the HTTP module to save our users data connection. The desired behavior would be sending stop / start events to the module until the user is finished their behavior (they've finished their workout, etc.) Then, we'd like to be able to query the plugin to get the recorded locations, do processing on the client side, and then send a single object to the server with the recorded trip.

Is that possible with this plugin?

Thanks

Bryan Rayner

**Comment by christocracy** [comment]
Use `batchSync: true, autoSync: false`.  When trip is complete, execute `BackgroundGeolocation.sync()`.

**Comment by bryanrideshark** [comment]
Ah, that's great.

Is there any way to retrieve the data other than HTTP?

**Comment by christocracy** [comment]
You should fetch your application data from your server.  Don’t rely on the plugin to be your data host.
