### ISSUE TITLE
Android background geo service starts, but doesn't update location. Only on once, on app load.

### ISSUE THREAD

**Issue by elmbrent** [transistorsoft/cordova-background-geolocation-lt#950]
## Your Environment
* Plugin version: "cordova-background-geolocation-lt": "3.0.7"
* Platform: Android 
* OS version: 8.1 Api, ver 27
* Device manufacturer / model: Google pixel 1 simulator and real device
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`):   android 7.1.4
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
   bgGeo.ready({
                        reset: true,
                        debug: false,
                        logLevel: bgGeo.LOG_LEVEL_VERBOSE,
                        desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                        distanceFilter: 10,
                        autoSync: true,
                        stopOnTerminate: false,
                        startOnBoot: true
                    }, 
```

## Expected Behavior
App should get multiple location updates

## Actual Behavior
Gets only once on app start

## Steps to Reproduce

1. Run the app and listen onLocation event in js code

**Comment by elmbrent** [comment]
We tested on multiple devices, walked lots of distance and also tested on simulator. All came back with same problem.

Thanks

**Comment by Steffaan** [comment]
Did you watch the logs to see what's happening? Fetch and provide logs in this thread, because it's just guessing without seeing any logs.

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging

**Comment by elmbrent** [comment]
In debug mode i see walking state change `Motion Transition Result` event. But onLocation event seems not always firing. It fired 6 times, but considering logs it should fire much more times
[logs.pdf](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3359009/logs.pdf)

**Comment by Steffaan** [comment]
Your better off posting the logs from the plugin itself or at least clean it up so it's readable.. 

PDF format? Really? :confused:

Anyways, checking the logs is showing me a fully working plugin. Nothing wrong there. 

I do see a lot of "undefined" and "Uncaught expcetion" which indicates you do have errors in your JavaScript which could crash it / stop your events from triggering.

Please check your code and installed plugins. Post logs from the plugin itself so we can actually see if there is anything wrong. As of now I see no issues regarding to the plugin.

**Comment by elmbrent** [comment]
Yes there are some js erros in code, but they have no impact on tracking code. I had state changes from still->running->on_bycicle->running->still, but got only 3 events in js code, and after some period of time I had no events at all

**Comment by elmbrent** [comment]
Here's a plugin log
[logs.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3359232/logs.txt)

**Comment by christocracy** [comment]
Thanks @Steffaan.

**Comment by elmbrent** [comment]
Thanks
