### ISSUE TITLE
Background location plugin doesn't start location tracking when moving

### ISSUE THREAD

**Issue by stefanminch** [transistorsoft/cordova-background-geolocation-lt#951]
## Your Environment
* Plugin version: 3.0.10
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Xiaomi Redmi Go
* Cordova version (`cordova -v`):8.0.0
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config provided to `#ready`:
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "disableElasticity": false,
  "disableStopDetection": false,
  "distanceFilter": 15,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": 3000,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask",
  "heartbeatInterval": 60,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": false,
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 10000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "notificationColor": "",
  "notificationLargeIcon": "",
  "notificationPriority": 0,
  "notificationSmallIcon": "",
  "notificationText": "Background Location Tracking Enabled",
  "notificationTitle": "Lucky Driver",
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "speedJumpFilter": 300,
  "startOnBoot": false,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 982285.125,
  "isFirstBoot": false
}

```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

The plugin doesnt start tracking the phone location. Note that this happens quite rare, in general it is working on the very same type of phones/OS/config. (Our company has 22 identical devices)

## Actual Behavior

Check the logs at 07-02 01:24:00 that is when the trip starts. 
and it ends at 01:50:00 the car is moving during that timeframe. Heartbeat is working but no points were sent to the callback function.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by stefanminch** [comment]
[background-geolocation.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3365646/background-geolocation.log.gz)

**Comment by christocracy** [comment]
It did fine here:
```
07-01 21:56:00.447 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: still
╟─ 🎾  ENTER: walking
╚═════════════════════════════════════════════
.
.
.
07-01 21:58:13.157 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: walking
╟─ 🎾  ENTER: in_vehicle
╚═════════════════════════════════════════════
.
.
.
07-01 22:37:43.692 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: in_vehicle
╟─ 🎾  ENTER: in_vehicle
╚═════════════════════════════════════════════
.
.
.
```

Also, your device is missing crucial sensors so you can expect poor device motion detecction:
```
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LIS3DH Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=39.22661, resolution=0.019607544, power=0.185, minDelay=5000}
╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
╟─ ⚠️  MAGNETOMETER:  none.  Motion-detection system performance will be degraded
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.18499756, minDelay=-1}
╚═════════════════════════════════════════════
```

**Comment by christocracy** [comment]
Also see http://dontkillmyapp.com

**Comment by stefanminch** [comment]
I am aware of dontkillmyapp.com, however please note that the app is not "dead" since it emits the heartbeat event at a regular interval.

**Comment by christocracy** [comment]
http://dontkillmyapp.com still applies to app in the background.

**Comment by stefanminch** [comment]
exactly, but my point is that if it was killed then the heartbeat will stop as well, since it is the same process.

**Comment by christocracy** [comment]
> if it was killed then the heartbeat will stop as well

That's not the point.  I'm not saying your app is being terminated.  There are bad android vendors which disable certain APIs from operating in the background, violating the published Android API.

I regularly field-test almost daily on the following devices stuffed into my backpack.  It doesn't matter if the app is terminated or in background.  The only one that causes me trouble is Huawei and there is no developer solution for that.
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 9.0.0
- Google Pixel 3 @ 9.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0 (**Bad**)
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 8.0.0

**Comment by stefanminch** [comment]
understood, thanks a lot!

Are you aware of a way of modifying the Android distribution so that my app never gets killed? Phones I use are company owned so it is not an issue...

**Comment by christocracy** [comment]
Are you *reading* the descriptions at http://dontkillmyapp.com?

![](https://dl.dropbox.com/s/w40xqval9wpwkys/Screenshot%202019-07-09%2019.41.01.png?dl=1)

**Comment by stefanminch** [comment]
yes I did read them indeed.But my idea is to root the OS and give higher priority to my app on OS level, this will work since, as I said, the devices are owned by my company. The problem is I can't find reliable documentation for Android Go...

**Comment by christocracy** [comment]
I don’t have little experience with rooting.
