### ISSUE TITLE
Background mode doesn't work after updating to iOS 13 Beta 7

### ISSUE THREAD

**Issue by bushev** [transistorsoft/cordova-background-geolocation-lt#952]
## My Environment
* Plugin version: 3.0.7
* Platform: iOS
* OS version: 13.0 (beta 7)
* Device manufacturer / model: Apple iPhone Xs Max
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): ios 5.0.1
* cordova-plugin-ionic-webview: 4.1.1
* Plugin config provided to `#ready`:
```javascript
const config = {
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_WARNING,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    stopOnTerminate: false,
    startOnBoot: false,
    disableMotionActivityUpdates: true,
    preventSuspend: true,
    locationAuthorizationRequest: 'Always',
    locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Location services are disabled',
        titleWhenOff: 'Location services are disabled',
        instructions: 'You should enable "Always" in Location Services, to allow App work properly in the background',
        cancelButton: 'Cancel',
        settingsButton: 'Settings'
    }
}
```

## Expected Behavior
The app runs in the background

## Actual Behavior
The app suspends

## Steps to Reproduce
1. Start app
2. Configure `BackgroundGeolocation` with the config (provided)
3. Call `BackgroundGeolocation.start()`
4. Return to the home screen
5. Wait for ~10 seconds
6. App suspends with logs (provided)

## Context
I'm using this plugin to prevent my app from suspend and tracking location in real-time while the app is working in mode X.

I'm calling `BackgroundGeolocation.start()` when I need to prevent the app from suspend
I'm calling `BackgroundGeolocation.stop()` when the app suspends is ok for the user

## Debug logs
```
2019-07-07 15:39:25.527750+0300 App[2339:808971] [ProcessSuspension] Background task was running for too long so WebKit will end it shortly.
2019-07-07 15:39:25.528149+0300 App[2339:808971] [ProcessSuspension] 0x2825351c0 - WKProcessAssertionBackgroundTaskManager - _backgroundTaskExpired
⚠️-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 10, remaining time: 4.679442
2019-07-07 15:39:30.882814+0300 App[2339:809183] ⚠️-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 10, remaining time: 4.679442
```

/ Yury

**Comment by bushev** [comment]
Just curious, did anyone tested this plugin with iOS 13 beta? 🤔

**Comment by christocracy** [comment]
I have.  iOS 13 support is ready and due to be posted to the private repo tomorrow.

**Comment by christocracy** [comment]
Android Q is already released to the private repo in 3.1.0

**Comment by bushev** [comment]
Hey @christocracy, thanks for your reply. 

Will iOS 13 support be posted to `this` repo as well? My app is iOS only.

If no, should I purchase for the license [here](https://www.transistorsoft.com/shop/products/cordova-background-geolocation#plans)?

**Comment by christocracy** [comment]
For latest updates, purchase a license.

This repo typically lags by 3 months or more.
