### ISSUE TITLE
What happens when user denies GPS permission 

### ISSUE THREAD

**Issue by tbs-arpit** [transistorsoft/cordova-background-geolocation-lt#953]
## Your Environment
* Plugin version:2.15.0
* Platform: iOS and Android
* OS version: android 8.1.0 and ios-12
* Device manufacturer / model: samsung/LG and iphone
* Cordova version (`cordova -v`):8.1.2
* Cordova platform version (`cordova platform ls`): android 7.1.4 and ios 4.5.4
* Plugin config provided to `#ready`:          
```javascript <!-- syntax-highlighting:  paste your code below -->
    config = {
          reset: true,
          debug: false,
          stopOnTerminate: isStopOnTerminate,
          desiredAccuracy: 0,
          stationaryRadius: 1,
          distanceFilter: 1,
          httpRootProperty: '.',
          foregroundService: true,
          startForeground: true,
          locationTemplate: '{ "lat":<%= latitude %>, "lng":<%= longitude %> }',
          extras: data,
          url: url
        };
    this.bgGeo.ready(config, (state) => {
        console.log('- Geolocation plugin is ready : ', state);
        this.startTracking();
        this.storage.set('isAlwaysLocation', !isStopOnTerminate);
      });
```

## Expected Behavior

There should be a method or a callback to determine that user has rejected the GPS permission(or any permission which plugin needs in order to work properly)

## Actual Behavior

Plugin does nothing when user denies GPS permission 

## Details

I checked the docs couldn't found such method(I could have missed something). Please let me know. As a part of the our business logic we need to show/log that user has rejected the plugin's GPS permission.

**Comment by christocracy** [comment]
See event #onProviderChange

**Comment by tbs-arpit** [comment]
Thanks 👍
