### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Haideralee** [transistorsoft/cordova-background-geolocation-lt#954]
## Your Environment
* Plugin version: 3.0
* Platform: iOS or Android: android
* Cordova version (`cordova -v`):9.0
 
 

while adding this in config.xml , builds failed
````
<platform name="android">
      <!-- background-geolocation -->
      <config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
          <meta-data
            android:name="com.transistorsoft.locationmanager.license_key"
            android:value="YOUR_LICENSE_KEY_HERE" />
      </config-file>
      <!-- /background-geolocation -->
</platform>

````
 

 
![image](https://user-images.githubusercontent.com/4715743/60999279-30b1c000-a374-11e9-9562-2bcf489d528a.png)

**Comment by christocracy** [comment]
Your app seems to be complaining about:

```
cordova-plugin-googlemaps/app-apikey.gradle`
```

- Are you sure you followed the [Android Setup](https://github.com/transistorsoft/cordova-background-geolocation-lt#android)?
- Are you *sure* you're using `Version: 3.0`?  The latest version is [3.0.8](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md)

**Comment by Haideralee** [comment]
yes, project was running util i have added 
````
<config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
            <meta-data android:name="com.transistorsoft.locationmanager.license_key" android:value="mykey.." />
        </config-file>
````

it fails now.
err : `The prefix "android" for attribute "android:name" associated with an element type "meta-data" is not bound.`


yes it is `3.0.8`,

**Comment by christocracy** [comment]
And did you add this to your `config.xml`?
```diff
<widget
  id="com.foo.bar"
  version="1.0.0"
  xmlns="http://www.w3.org/ns/widgets"
+ xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:cdv="http://cordova.apache.org/ns/1.0">
```

**Comment by Haideralee** [comment]
ah! that's I missed thanks.
