### ISSUE TITLE
Not getting the "ENTER"/"EXIT" geofence events in Samsung S9 android device

### ISSUE THREAD

**Issue by harsh-iomedia** [transistorsoft/cordova-background-geolocation-lt#958]
## Your Environment
* Plugin version: 3.0.7
* Platform: Android
* OS version: Android 9
* Device manufacturer / model: Samsung S9/ SM-G960F
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): android 7.1.4
* Plugin config provided to `#ready`:
```
BackgroundGeolocation.ready({
	reset: true,
	debug: true,
	logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	distanceFilter: 0.1,
	autoSync: true,
	stopOnTerminate: true,
	startOnBoot: false,
	url: 'someurl',
	headers: {
	'Content-Type': 'application/json'
	}
}, (state) => {
	console.log('[ready] BackgroundGeolocation is ready to use');
	BackgroundGeolocation.startGeofences();
});

/*=========================================
=========  Geofence listen event callback   =========
=========================================*/

BackgroundGeolocation.onGeofence(geofence => {
    console.log('[geofence] ', geofence);
    if (geofence.action == 'ENTER') {
        // Entering the SAFTYZONE, we want to aggressively track location.
        BackgroundGeolocation.start();
    } else if (geofence.action == 'EXIT') {
        // Exiting the SAFTYZONE, we resume geofences-only tracking.
        BackgroundGeolocation.startGeofences();
    }
});
================== END ====================

/*=========================================
=============  Geofence Objects   ==============
=========================================*/
[
  {
    "identifier": "Home",
    "radius": 200,
    "latitude": 28.4296839,
    "longitude": 77.0983314,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
  },
  {
    "identifier": "Office",
    "radius": 200,
    "latitude": 28.451352,
    "longitude": 77.0685103,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
  }
]
==================== END ==================
```

## Expected Behavior
Should have received the geofence "ENTER"/"EXIT" event.

## Actual Behavior
Not received any "ENTER"/"EXIT" geofence event. While the app is in the background. But as i have open the app then I receive on "ENTER" event.

## Steps to Reproduce
1. Start the application
2. Call the 'ready' function.
3. Put the app in background.(NOTE: Already disabled all the battery optimised features)
4. Then move outside the geofence area and didn't receive any event.

## Context
Testing the application geofencing "ENTER/EXIT" events. In the debug logs there are multiple "ENTER"/"EXIT" events but I didn't receive it in the HTTP call. And if you can check the timings of "ENTER"/"EXIT" events then there are happening in every minute. Please plot all the coordinates in google maps side by side along with the 'Geofence Objects' above,  then you will know that I didn't move and still the plugin is giving the "ENTER"/"EXIT" events.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
[LOGS](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3391293/logs-android-s9-bg-it.log)
```

</details>

**Comment by harsh-iomedia** [comment]
Hi Chris,

Can please update the issue and let me know what is happening in case of android here?

**Comment by harsh074** [comment]
Hi Christocracy,

Is there any issue in this ticket. Or you are not able to understand the issue. Can you please update the status on it.

Thanks.

**Comment by christocracy** [comment]
I test geofencing almost every day on 11 Android Devices with the apps running in the background and headless states.  I always receive the events at my server and I always *hear* their debug sound effect.

- *Samsung A5*
![](https://dl.dropbox.com/s/4xgckjhie4enjmt/Screenshot%202019-09-13%2010.31.01.png?dl=1)

- *Samsung J-320*
![](https://dl.dropbox.com/s/p7yr7wr9mzrgioe/Screenshot%202019-09-13%2010.29.48.png?dl=1)

**Comment by christocracy** [comment]
From your logs, here are all the reported Geofence events and their corresponding successful `HTTP POST` to your server:
```
07-11 18:11:43.156 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: EXIT
╠═════════════════════════════════════════════
╟─ Office
╚═════════════════════════════════════════════
07-11 18:11:43.199 INFO [b persist] 
  ✅  INSERT: a7caf29c-48ab-4119-8bf5-c646196a3bdf
07-11 18:11:50.161 INFO [HttpService a] 
  🔵  HTTP POST: a7caf29c-48ab-4119-8bf5-c646196a3bdf
07-11 18:11:51.912 INFO [HttpService$b onResponse] 
  🔵  Response: 200
.
.
.
07-11 18:11:45.151 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER
╠═════════════════════════════════════════════
╟─ Home
╚═════════════════════════════════════════════
07-11 18:11:45.197 INFO [b persist] 
  ✅  INSERT: 24e40651-4f94-4fa7-80cc-fa5d1c99f9c3
07-11 18:11:51.978 INFO [HttpService a] 
  🔵  HTTP POST: 24e40651-4f94-4fa7-80cc-fa5d1c99f9c3
07-11 18:11:53.758 INFO [HttpService$b onResponse] 
  🔵  Response: 200
.
.
.
07-11 18:12:33.810 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: EXIT
╠═════════════════════════════════════════════
╟─ Home
╚═════════════════════════════════════════════
07-11 18:12:33.834 INFO [b persist] 
  ✅  INSERT: c9742bfe-b6bf-4ef0-81fd-99e01ce8f4a7
07-11 18:12:34.581 INFO [HttpService a] 
  🔵  HTTP POST: c9742bfe-b6bf-4ef0-81fd-99e01ce8f4a7
07-11 18:12:35.337 INFO [HttpService$b onResponse] 
  🔵  Response: 200
.
.
.
07-11 18:12:34.704 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER
╠═════════════════════════════════════════════
╟─ Office
╚═════════════════════════════════════════════
07-11 18:12:34.728 INFO [b persist] 
  ✅  INSERT: 4d7783a3-4c23-4bc2-bea2-e786c41323d3  
07-11 18:12:35.385 INFO [HttpService a] 
  🔵  HTTP POST: 4d7783a3-4c23-4bc2-bea2-e786c41323d3
07-11 18:12:37.265 INFO [HttpService$b onResponse] 
  🔵  Response: 200
.
.
.
07-11 18:14:33.826 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: EXIT
╠═════════════════════════════════════════════
╟─ Office
╚═════════════════════════════════════════════
07-11 18:14:33.866 INFO [b persist] 
  ✅  INSERT: d9dbfea2-3482-408e-959d-9b37027d78c6  
07-11 18:14:35.310 INFO [HttpService a] 
  🔵  HTTP POST: d9dbfea2-3482-408e-959d-9b37027d78c6
07-11 18:14:36.380 INFO [HttpService$b onResponse] 
  🔵  Response: 200
.
.
.
07-11 18:14:35.725 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER
╠═════════════════════════════════════════════
╟─ Home
╚═════════════════════════════════════════════
07-11 18:14:35.764 INFO [b persist] 
  ✅  INSERT: c9c76ace-88e5-4752-8b74-4163ed965179
07-11 18:14:36.426 INFO [HttpService a] 
  🔵  HTTP POST: c9c76ace-88e5-4752-8b74-4163ed965179
07-11 18:14:37.099 INFO [HttpService$b onResponse] 
  🔵  Response: 200
```

**Comment by harsh-iomedia** [comment]
Hi Christocracy,

As you see the logs the events are firing in 10-20 seconds interval. With every ENTER/EXIT event my server sends the notification on the basis of the event. It is quit confusing is somebody receives 3-4 notification at a gap of 10-20 seconds. 

And sometimes device fails to know that it had entered in geofence, as soon as i open the app then it knows and run the event. Then at that time the device hit multiple event like you see in logs. 

Thanks.

**Comment by christocracy** [comment]
The plugin has no control over the firing of these geofence events.  It's completely handled by the Android OS.  If that device has a poor network connection or is on the boundary of a geofence, yes it can happen that multiple geofence events might occur in a short period of time.

Totally depends on the device and network environment.  The plugin has no possible way of preventing this.

Either use `notifiyOnDwell` with a suitable `loiteringDelay`, use larger `radius` or add intelligence to buffer geofence events and prevent your app from showing notifications.

**Comment by christocracy** [comment]
The title of this issue is:
>Not getting the "ENTER"/"EXIT" geofence events in Samsung S9 android device

clearly you *are* receiving geofence "ENTER" / "EXIT" events and those events are certainly being `POST`ed to your server.

**Comment by harsh-iomedia** [comment]
Like i said i didnt recieve it until i opens the app. Like i am talking about when app is in the background. Then at that time i didn't recieve it. That is our core functionality to get the location in the background. If it doesn't work then nothing work in the app.

**Comment by christocracy** [comment]
See http://dontkillmyapp.com

**Comment by harsh074** [comment]
I always hear their debug sound that was coming from the device. So that means that the application is background and running. I have read the above article when i started working with the plugin. Because i face the same issue that the app gets kill in the background, so i have re-configured the device according to the link above. Now the device didn't kill my application. but is doesn't give the proper geofencing ENTER/EXIT events sometimes. I just want you to check the logs in case you found something that is not right. Thats all. Nothing more.

**Comment by tafh** [comment]
@harsh074 @christocracy After reading this I have the feeling that it isn't clear that Cordova will not execute any javascript while the app is in the background, so when in the foreground it will trigger all events (i.e. enters and exits) at once (not sure what order). This might be confusing since the plugin is able to run the native code in the background.

**Comment by MasterChef-NL** [comment]
Hi, I am experiencing the same issues on my Samsung S9 device. Already aware that my Ionic app (Cordova) does not work in the background. However, I am using the Firebase Adapter also supplied by Transistor Software that uploads all Geofence events to my Firebase collection.
Many times I do get a Geofence ENTER event, but hardly ever a EXIT event. Sometimes I have to be out of the geofence for at least 5 minutes before it is fired. And also often I do not get the ENTER event, even though GPS tracking data shows my device going straight into the fence.
No clue what is causing this. Have played around with the different parameters, but somehow it just won't work in a stable way. 
@christocracy: You say you test everyday on different devices, but guess you are using apps like Lockito to generate fake gps location updates. I have also used that, but when testing out in the field, the results are way different when passing Radio towers, Wifi zones, etc.

**Comment by christocracy** [comment]
>You say you test everyday on different devices, but guess you are using apps like Lockito

No, I'm stuffing 11 Androids into a backpack and walking through my neighbourhood.  I have all the devices monitoring the same set of geofences.  However, I'm not often testing geofences-only mode `#startGeofences`; mostly the regular location-tracking mode `#start`.

![](https://dl.dropboxusercontent.com/s/x11cykd1hy5zbts/Screenshot%202019-12-19%2010.29.59.png?dl=1)

See [Troubleshoot the geofence entrance event](https://developer.android.com/training/location/geofencing#Troubleshooting)
![](https://dl.dropboxusercontent.com/s/55858h8jg1iuulw/Screenshot%202019-12-19%2010.33.00.png?dl=1)

If you're using `#startGeofences`, geofence triggers don't work as well.  This is why I added [`Config.goefenceModeHighAccuracy`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#geofencemodehighaccuracy)

**Comment by MasterChef-NL** [comment]
@christocracy: I have been doing some more field testing. What really stands out is that when I am only running my app with the plugin, I get irregular location updates. Sometimes after a minute, sometimes 2x per minute. And looking at the location coordinates, they are all over the place. To me it seems that it is only changing when the phone connects to a different telecom radio tower. I don't have the impression that it uses raw GPS data at all.
But as soon as I turn on Google Maps, or an other app that uses GPS (like the app "GPS Status"), I get location updates almost every 5 seconds and then the geofences also get triggered because I go straight in and out of them.

Do you have any idea what might be causing this? In my phone (Samsung Galaxy S9 with Android Pie) I have the "Improve precision" turned on under "Location" settings. Also the "Google location accuracy" is turned on including Wifi and Bluetooth scanning. This should give me the best location at all times I would expect. But somehow, the OS does not seem to understand that my app, with the plugin running wants to get a precise location.

Hope you have some hints that can help me.

**Comment by christocracy** [comment]
@MasterChef-NL see the original post above and provide all the same information (Plugin version, device model, Config, etc.).  All of that info.
