### ISSUE TITLE
Using Oauth 2.0 with cordova Background Geolocation 

### ISSUE THREAD

**Issue by EdiFirst** [transistorsoft/cordova-background-geolocation-lt#962]
How Can'I to protected and use the Plugin with Oauth 2.0 security to consume an API? 
Because seems it doesn't permit make two Call request when my app is working in background and I need make two url request( one passing parameters to get token) and another passing token to finally post or get resources.

**Comment by christocracy** [comment]
Please do not ignore the issue template:

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by EdiFirst** [comment]
@christocracy I didn't put detailed text on template because it's a question. I don't have alot details.
