### ISSUE TITLE
Check if permissions have been granted without asking for them

### ISSUE THREAD

**Issue by Spacarar** [transistorsoft/cordova-background-geolocation-lt#964]
* Plugin version: 3.0.8
* Platform: iOS 
* OS version: 12.4
* Device manufacturer / model: Iphone 8
* Cordova version: 8.1.2
* Cordova platform version: ios 4.5.5
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
  reset: true, //always use this config even after reset
  distanceFilter: 10,
  desiredAccuracy: 10
}
```

## Expected Behavior
Reading through the documentation I see very clearly listed is a `requestPermission` method, as well as several methods asking for permissions without even needing to call this function. In the documentation for this code it is listed that `start`, `startGeofences` and `getCurrentPosition` will ask for permissions if not already available. I have a section of code that will use the `getLocations`, firstly this method also appears to be asking for location permissions if not already available even though it is not listed as asking for permissions in the documentation.. 

Next to my question, is there some way to check if the location permissions have already been granted WITHOUT asking for it? the section of code that uses `getLocations` will run on an interval and I would like to simply skip over that section if permissions have not yet been granted as there would be no locations anyway.

## Actual Behavior
the `getLocations` function is asking for location permissions which unexpected behavior compared to what is listed in the documentation. 

## Steps to Reproduce

1. have a fresh installation of a cordova app with this plugin
2. call BackgroundGeolocation.ready({config})
3. call BackgroundGeolocation.getLocations()
4. the application will ask for location permissions

## Context
If `getLocations` doesn't require location permissions, then it would be nice if this function did not ask for location permissions. If it does indeed require location permissions. It would be helpful to have a function that would check if you have already been granted permission WITHOUT asking for them.

The app I'm building would require multiple permissions and having this one pop up when the interval code runs can be obnoxious. I would like to control when I ask for permissions the first time if possible.

**Comment by Spacarar** [comment]
I didn't even realize that requestPermissions pops up an alert if you don't have permissions? Is there some way to not have this happen? I just want to check if you have permissions, if you don't just ignore the section of code. if you do then run the section...

**Comment by Spacarar** [comment]
I had closed the issue thinking I had found a workaround by using `BackgroundGeolocation.getProviderStatus()`. This helps me get around the section of code in the interval. Nonetheless, the `ready` function is still creating an alert telling me that location services are off when I launch the app. This occurs even after adding `locationAuthorizationRequest: "Any"` to the configuration as recommended by this documentation https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#locationauthorizationrequest.
```

If you configure Any, the plugin allow the user to choose either Always or WhenInUse. 
The plugin will not show the locationAuthorizationAlert dialog when the user changes the selection in Privacy->Location Services.
```


To reproduce this, you can launch a blank app with
```javascript
BackgroundGeolocation.ready({
      reset: true, //always use this config even after reset
      distanceFilter: 10,
      desiredAccuracy: 10,
      locationAuthorizationRequest: "Any"
    })
```
Deny the permissions the first time, and relaunch the app.
A notification will still appear telling me `Location services are off: To use background location, you must enable 'Any' in the location services settings.` I want these permissions to be optional and not loud about it. Having this alert pop up every time you open the application is quite a bother.

**Comment by christocracy** [comment]
disableLocationAuthorizationAlert: true
