### ISSUE TITLE
SQLite corruption - possible?

### ISSUE THREAD

**Issue by matejkramny** [transistorsoft/cordova-background-geolocation-lt#965]
## Your Environment
* Plugin version: 3.0.8
* Platform: iOS
* OS version: ios 12
* Device manufacturer / model: iphone
* Cordova version (`cordova -v`): / irrelevant
* Cordova platform version (`cordova platform ls`): using https://github.com/xpbrew/cordova-sqlite-storage

Hi Chris,

We're running an app and using SQLite to persist settings. On occasion we get these settings lost - this is pretty much the opposite of what usage of SQLite should be guaranteeing.

Trying to get to the bottom of the issue (which isn't easy) - **would it be possible that this plugin's sqlite usage would cause corruption?** [whilst using another sqlite database]

It's described with big warnings in the repo:
"This plugin version also uses a fixed version of sqlite3 on iOS, macOS, and Windows. In case the application accesses the SAME database using multiple plugins there is a risk of data corruption as described in https://www.sqlite.org/howtocorrupt.html (similar to the multiple sqlite problem for Android as described in http://ericsink.com/entries/multiple_sqlite_problem.html)."

Many thanks!

**Comment by christocracy** [comment]
It's doubtful.  This plugin stores its iOS SQLite file in its own database file named `ts_location_manager.sqlite`.
![](https://dl.dropbox.com/s/wb29mmhun9t1wln/Screenshot%202019-07-26%2011.01.51.png?dl=1)

**Comment by matejkramny** [comment]
Thanks for quick reply; perhaps looking in the wrong direction

Matej
