### ISSUE TITLE
android ask me for auth prompt

### ISSUE THREAD

**Issue by bhandaribhumin** [transistorsoft/cordova-background-geolocation-lt#969]
I have used paid service but I'm getting an prompt like a sign in username and password.

![Screen Shot 2019-07-31 at 10 54 19 AM](https://user-images.githubusercontent.com/3336047/62300405-5e31eb00-b494-11e9-906a-2d42d3e011aa.png)

config.xml

```
<plugin name="cordova-background-geolocation-lt" spec="^3.0.4">
        <variable name="LICENSE" value="5xxxxxxxxxb" />
        <variable name="GOOGLE_API_VERSION" value="16.+" />
        <variable name="APPCOMPAT_VERSION" value="27.+" />
        <variable name="OKHTTP_VERSION" value="3.12.+" />
        <variable name="EVENTBUS_VERSION" value="3.0.0" />
        <variable name="BACKGROUND_MODE_LOCATION" value="&lt;string&gt;location&lt;/string&gt;" />
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Always use is required for constant background location-tracking" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>
<platform name="android">
        <config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
            <meta-data android:name="com.trxxxxxft.locxxxxxxer.license_key" android:value="5xxxxxxxxxxxxxxxxcb" />
        </config-file>
    </platform>

```

**Comment by christocracy** [comment]
Did you read that little note in ALL CAPS at the top of issue template before you deleted it all?

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

```

**Comment by christocracy** [comment]
And that *Sign in* dialog has nothing to do with the plugin.
