### ISSUE TITLE
How to get it working on iOS

### ISSUE THREAD

**Issue by tanjentman** [transistorsoft/cordova-background-geolocation-lt#97]
Hi I am trying to get it working on iOS, but don't have much experience making the necessary modifications to make it work.  I am wondering if someone can help me. I am using PhoneGap Build and the only modifications I have made are to the config.xml file.  Any help would be greatly appreciated.  Thanks.

```
<plugin name="org.apache.cordova.dialogs" source="npm"/>
<plugin name="org.apache.cordova.geolocation" source="npm"/>
<plugin name="cordova-background-geolocation-lt"/>
```

**Comment by christocracy** [comment]
See [PhoneGap Build Guide](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/PhoneGap-Build-Installation) in Wiki
