### ISSUE TITLE
License Add Error

### ISSUE THREAD

**Issue by swartjie** [transistorsoft/cordova-background-geolocation-lt#971]
## Your Environment
* Plugin version: Newest
* Platform: Android
* OS version: N/A
* Device manufacturer / model: N/a
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
<platform name="android">
      <config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
          <meta-data
            android:name="com.transistorsoft.locationmanager.license_key"
            android:value="mykey" />
      </config-file>
</platform>
```

## Expected Behavior

Adding the above should be activating the Geolocation plugin
## Actual Behavior

My Cordova stops compiling all together with the below error
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\User\Documents\App\platforms\android\app\src\main\res\xml\config.xml:117: error: unbound prefix.

## Steps to Reproduce

Not suire, I added the plugin into the app. Compiled, it worked, when I add teh licensing it breaks the compiling...

## Context

Compile the app

**Comment by christocracy** [comment]
Follow the [directions carefully](https://github.com/transistorsoft/cordova-background-geolocation-lt#android).

Yes, this bit is *required*:
![](https://dl.dropbox.com/s/xg6ybcpykxfjijl/Screenshot%202019-08-03%2014.07.52.png?dl=1)

**Comment by swartjie** [comment]
Hey Christocracy, Thanks for the fast response... One question though, I use IMA Builder to build the app. When I blatantly change the config file it overrides that change, Any idea how I can implement it?

**Comment by christocracy** [comment]
What is “IMA Builder”?

**Comment by swartjie** [comment]
a lekker web interface to build with ionic :) https://codecanyon.net/item/ionic-mobile-app-builder/15716727

**Comment by christocracy** [comment]
I suggest you ask that service why they’re over-writing your config.xml

**Comment by swartjie** [comment]
They made the needed changes to the config setup thank you :)

**Comment by christocracy** [comment]
Lucky you
