### ISSUE TITLE
Timed Location Updates Not Working

### ISSUE THREAD

**Issue by swartjie** [transistorsoft/cordova-background-geolocation-lt#972]
## Your Environment
* Plugin version: Newest
* Platform: Android
* OS version: Nougat
* Device manufacturer / model: Samsung Note 9
* Cordova version (`cordova -v`): 9
* Cordova platform version (`cordova platform ls`): Android 8.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
bgGeo.ready({
                reset: true,
                debug: true,
                logLevel: bgGeo.LOG_LEVEL_VERBOSE,
                desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                distanceFilter: 0,
  				stationaryRadius: 5,
                locationUpdateInterval: 5000,
              	allowIdenticalLocations: true,
                url: 'https://oursite.co.za/api/UpdateLocation',
                params: {
                  api_key: window.localStorage.getItem('api_key'),
                  employer_api_key: window.localStorage.getItem('employer_api_key')
                },
                autoSync: true,
                stopOnTerminate: false,
                startOnBoot: true
              }, function(state) {    // <-- Current state provided to #configure callback
                // 3.  Start tracking
                console.log('BackgroundGeolocation is configured and ready to use');
                bgGeo.start();
              });
```

## Expected Behavior

Based on the above config the location should be updating every 5 seconds.

## Actual Behavior

It does check location the first time, I added an alert to the on('location') event, and it did alert the first time. but not after that again...

## Steps to Reproduce

I added the following code to my on run event.
         	var bgGeo = window.BackgroundGeolocation;
         	
         	bgGeo.onLocation(function(location) {
              console.log('[location] -', location);
              alert('Location Updated'+location.coords.longitude+', '+location.coords.latitude);
            });
         
           bgGeo.onMotionChange(function(event) {
              console.log('[motionchange] -', event.isMoving, event.location);
           });

           bgGeo.onHttp(function(response) {
              console.log('[http] - ', response.success, response.status, response.responseText);
           });

           bgGeo.onProviderChange(function(event) {
              console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
           });
           
           bgGeo.on('heartbeat', function(params) {
            console.log('- hearbeat');

            // You could request a new location if you wish.
            bgGeo.getCurrentPosition(function(location) {
              console.log('- current location: ', location);
            });
          });
         
         	bgGeo.ready({
                reset: true,
                debug: true,
                logLevel: bgGeo.LOG_LEVEL_VERBOSE,
                desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                distanceFilter: 0,
  				stationaryRadius: 5,
                locationUpdateInterval: 5000,
              	allowIdenticalLocations: true,
                url: 'https://mysite.co.za/api/UpdateLocation',
                params: {
                  api_key: window.localStorage.getItem('api_key'),
                  employer_api_key: window.localStorage.getItem('employer_api_key')
                },
                autoSync: true,
                stopOnTerminate: false,
                startOnBoot: true
              }, function(state) {    // <-- Current state provided to #configure callback
                // 3.  Start tracking
                console.log('BackgroundGeolocation is configured and ready to use');
                bgGeo.start();
              });

## Context

I would like to send the location info every 5 seconds to a server

**Comment by christocracy** [comment]
Don’t do this, it’s meaningless tomorrow:

Plugin version: Newest

**Comment by swartjie** [comment]
Sorry bud. Wasn't sure where to get the version :(. What's the best way to get the version installed?

**Comment by swartjie** [comment]
Hey Guys,

Do you have any advise for me? I am receiving notifications about the GPS plugin doing something (random sounds) but it's not submitting it to the server at all...

**Comment by christocracy** [comment]
See wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

**Comment by christocracy** [comment]
Have you read the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)

**Comment by iprimaek** [comment]
Christ, based on the philosophy: [https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation](url) does it mean that it's impossible to do what is intended by 'swartjie' - 'I would like to send the location info every 5 seconds to a server'? If so, then what's the point of having this config "locationUpdateInterval"?

**Comment by christocracy** [comment]
Read the docs for locationUpdateInterval.

If you set distanceFilter: 0, Android will *attempt* to deliver location at desired locationUpdateInterval **while the device is in-motion**.  The plugin delivers **no** locations while the device is *stationary*.

**Comment by iprimaek** [comment]
That means, no matter how, a device must be in-motion so the plugin can deliver the locations?

**Comment by christocracy** [comment]
What’s the point in the plugin delivering locations while sitting stationary?

**Comment by ranma42** [comment]
Delivering locations while sitting stationary makes it possible to distinguish between a device which is not able to send updates (turned off or disconnected) vs a device whose location did not change.

**Comment by christocracy** [comment]
On mobile, *”you can’t always get what you want”*, particularly for iOS.

You don’t own the user’s device and battery power is a precious resource.  Apple is particularly protective of their customers’ devices after years of customer complaints about poor battery performance due to abuse by poorly designed apps running in the background.

You can’t develop for mobile ad you would a web app running on a desktop plugged into AC power.

**Comment by ranma42** [comment]
Yup, I do understand that. In my case the user explicitly started the tracking and it only happens for a limited time so I am not that worried about battery usage. On the other hand, it is definitely possible for the user to wait in the same location for several minutes and the backend should be informed about that (ideally in real-time, not when the user start moving again).

There seems to be some support for same-position "updates" at least on Android through [allowidenticallocations](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#allowidenticallocations), but this flag does not seem sufficient to enable time-based location updated (not even when combined with `locationUpdateInterval=30000` and `distanceFilter=0`).

This is somewhat expected, as explicitly stated in the documentation for `distanceFilter`:
> This interval is inexact. You may not receive updates at all (if no location sources are available), or you may receive them slower than requested. You may also receive them faster than requested (if other applications are requesting location at a faster interval).

What is your recommendation for time-based location updates (besides choosing a sufficiently long update interval)?
I did not yet try it, but I'm leaning towards experimenting with the heartbeat event.
Would that make sense?
(the sad thing about relying on the heartbeat event is that it would make it impossible to re-use the same machinery for POSTing locations)

**Comment by christocracy** [comment]
If you want to use `onHeartbeat` with Android, simply call `#getCurrentPosition` in the your event-handler.  The plugin will record a location and upload it to your configured `#url`.
