### ISSUE TITLE
How to set variables pre URL Submit

### ISSUE THREAD

**Issue by swartjie** [transistorsoft/cordova-background-geolocation-lt#973]
## Your Environment
* Plugin version: 3.0.8
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung
* Cordova version (`cordova -v`):  9.0.0
* Cordova platform version (`cordova platform ls`): android 8.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
 bgGeo.ready({
                reset: true,
                debug: true,
                logLevel: bgGeo.LOG_LEVEL_VERBOSE,
                desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                distanceFilter: 7,
  		stationaryRadius: 1,
              	allowIdenticalLocations: false,
              	forceReloadOnLocationChange: true,
              	forceReloadOnHeartbeat: true,
              	forceReloadOnBoot: true,
              	forceReloadOnMotionChange: true,
                url: 'https://mysite.co.za/api/UpdateLocation',
                params: {
                  api_key: window.localStorage.getItem('api_key'),
                  employer_api_key: window.localStorage.getItem('employer_api_key')
                },
              	heartbeatInterval: 70,
                autoSync: true,
                stopOnTerminate: false,
                startOnBoot: true,
                
              	locationAuthorizationAlert: {
                  titleWhenNotEnabled: "Location services disabled",
                  titleWhenOff: "Location services OFF",
                  instructions: "Please enable 'Always' in location services",
                  cancelButton: "Cancel",
                  settingsButton: "Settings"
                }
              }, function(state) {    // <-- Current state provided to #configure callback
                // 3.  Start tracking
                console.log('BackgroundGeolocation is configured and ready to use');
                bgGeo.start();
              });
```

## Expected Behavior

I would expect that the params would update with each GPS update sent to the server (url) depending on the variables set at that point in time.
## Actual Behavior

It looks like it sets on config set and does not update.
How can we update the variables per request (just before it should submit)?
Also, is it possible to have a "Check" function run just before the URL submits and stop it should the 2 variables be empty or NULL?
## Context

I would like to check the 2 variables before the GPS coordinates are submitted. If they need to be submitted then, allow it. Else stop it.
Also with each GPS url submit, it needs to update the api variables first?

**Comment by christocracy** [comment]
>How can we update the variables per request (just before it should submit)?

You can't.  By the time the `onLocation` event fires, the HTTP request has already been executed.
