### ISSUE TITLE
Headless Mode in Android not activating

### ISSUE THREAD

**Issue by adamalexander** [transistorsoft/cordova-background-geolocation-lt#977]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Moto e5 play
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
```Installed platforms:
  android 6.4.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0```

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

    var bgGeo = window.BackgroundGeolocation;
    bgGeo.configure({
      enableHeadless: true,    // <-- enable Headless mode
      stopOnTerminate: false  // <-- required for Headless JS
    }, (state) => {
      console.log('- Configure success');
    });
```

## Expected Behavior
****
Taken from the article: "Boot your app, then terminate it. Observe $adb logcat -s TSLocationManager. The first event you'll see is the **terminate** event:"
 
## Actual Behavior
**terminate** event not showing in logcat

## Context
I'm trying to get Headless Mode to work. Testing it out by looking for the terminate event in the logcat. But to no avail.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
$ adb logcat -s TSLocationManager
--------- beginning of crash
--------- beginning of system
--------- beginning of main
08-07 13:36:41.111  3810  3991 I TSLocationManager: 
08-07 13:36:41.111  3810  3991 I TSLocationManager: ╔═════════════════════════════════════════════
08-07 13:36:41.111  3810  3991 I TSLocationManager: ║ License Validation Failure
08-07 13:36:41.111  3810  3991 I TSLocationManager: ╠═════════════════════════════════════════════
08-07 13:36:41.111  3810  3991 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
08-07 13:36:41.521  3810  3991 D TSLocationManager: $ addEventListener()
08-07 13:36:57.817  3810  3991 D TSLocationManager: $ configure()
08-07 13:37:19.705  3810  3991 D TSLocationManager: $ addGeofence()
08-07 13:37:24.250  3810  3991 D TSLocationManager: $ configure()
08-07 13:37:34.465  3810  3810 I TSLocationManager: - onPause
```

</details>

**Comment by christocracy** [comment]
Maybe you're app is crashing?  View the *unfiltered* logcat:

```
$ adb logcat
```

**Comment by christocracy** [comment]
Btw, `2.11.0` is *very old*.  Latest is [`3.0.8`](https://github.com/transistorsoft/cordova-background-geolocation-lt/releases).

All the documentation in README and Wiki assumes you're using 3.x

**Comment by christocracy** [comment]
The Cordova android platform `android 6.4.0` is nearly 2 years old.  Upgrade your cordova to lastest.

```
$ cordova -v
9.0.0 (cordova-lib@9.0.1)

$ cordova platforms
Installed platforms:
  android 8.0.0
  ios 5.0.1
```

**Comment by MSILGITHUB** [comment]
My application was crashing after integrating the license key using the method suggested in README and was using 2.14.2. I used the older method in config file and application stopped crashing.

**Comment by christocracy** [comment]
When there’s a crash, the *first* thing you do is get the stacktrace from adb logcat.
