### ISSUE TITLE
Message to allow location not show and location not enabled

### ISSUE THREAD

**Issue by mcherubin** [transistorsoft/cordova-background-geolocation-lt#978]
## Your Environment
* Plugin version: 3.0.8
* Platform: iOS
* OS version: Mojave
* Device manufacturer / model: iphone 7 / Simulator
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): ios 5.0.1
* Plugin config provided to `#ready`:
```javascript
	bgGeo.ready({
		// Geolocation config
		desiredAccuracy: 0,
		distanceFilter: 10,
		stationaryRadius: 25,
		locationUpdateInterval: 1000,
		fastestLocationUpdateInterval: 1000,

		// Activity Recognition config
		activityType: 'AutomotiveNavigation',
		activityRecognitionInterval: 1000,
		stopTimeout: 1,

		// Application config
		debug: false,
		stopOnTerminate: false,
		startOnBoot: true,
		locationAuthorizationAlert: {
			titleWhenNotEnabled: "I servizi di localizzazione non sono attivi",
			titleWhenOff: "I servizi di localizzazione sono spenti",
			instructions: "E' necessario abilitare 'Sempre' nei servizi di localizzazione di DYNGO",
			cancelButton: "Annulla",
			settingsButton: "Imposta"
		},
		
  		preventSuspend: true,
		heartbeatInterval: 60
		
		/*
		// HTTP / SQLite config
		url: 'http://posttestserver.com/post.php?dir=cordova-background-geolocation',
		method: 'POST',
		autoSync: true,
		maxDaysToPersist: 1,
		headers: {
			"X-FOO": "bar"
		},
		params: {
			"auth_token": "maybe_your_server_authenticates_via_token_YES?"
		}
		*/
	}, function(state) {
		// This callback is executed when the plugin is ready to use.
		console.log('BackgroundGeolocation ready: ');
			
	});
```

## Expected Behavior
BackgroundGeolocation ready fired

Application never ask me Location Authorization if I go to iphone configuration->MyApp I don't see position capabilities, and the location not working

**Comment by christocracy** [comment]
>Plugin version: Latest

This is meaningless.  Enter the **exact version**

**Comment by mcherubin** [comment]
cordova-background-geolocation-lt@3.0.8

**Comment by christocracy** [comment]
**Edit** your original post.
![](https://dl.dropbox.com/s/fx0le6jfep34hew/Screenshot%202019-08-08%2011.05.31.png?dl=1)

**Comment by mcherubin** [comment]
done

**Comment by christocracy** [comment]
You need to tell the plugin to `#start` to start tracking.

**Comment by christocracy** [comment]
```javascript
BackgroundGeolocation.ready(config, function(state) {
  console.log('[ready] success.  Am I enabled?: ', state.enabled);
  if (!state.enabled) {
    // Maybe you want to #start here?
    BackgroundGeolocation.start();
  }
});
```

**Comment by mcherubin** [comment]
Thanks but in other version it ask to me the 'Allow Location' after the .ready function.

**Comment by christocracy** [comment]
The SDK does not ask for location until the location is requested.
- `#start`
- `#getCurrentPosition`

Perhaps you're interested in the [`#requestPermission`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#requestpermission) method.

**Comment by mcherubin** [comment]
thanks a lot, you are really kind and efficient

**Comment by christocracy** [comment]
In the future, since you're a customer, please post support requests to the private repo.
