### ISSUE TITLE
Recording jump after a short motion stop

### ISSUE THREAD

**Issue by HarelM** [transistorsoft/cordova-background-geolocation-lt#980]
# Your Environment
See issue #957 
## Expected Behavior
GPS recording shouldn't have jumps

## Actual Behavior
There are jumps in the recording

## Steps to Reproduce
1. I took the car for a drive
2. Stopped somewhere with the app in the background
3. Traveled a short distance by foot
4. Went back to driving

## Context
Record a route in the background

## Debug logs
Me again, I hope you didn't miss me :-)
I took the debug version for a ride in my car.
It mostly performed well except for a short  period of time.
The route can be seen here:
https://israelhiking.osm.org.il/share/VDxpcSV5iQ
The jump can be seen here (this was after I stopped driving for a few minutes):
![image](https://user-images.githubusercontent.com/3269297/63075579-e0152000-bf3a-11e9-99cd-7bd960af6787.png)
The following are the log I'm writing:
```
2019-08-15T04:58:04.952Z | DEBUG | Valid position, updating: (31.8585636, 34.8171014)
2019-08-15T04:58:07.542Z | DEBUG | State was updated
2019-08-15T05:02:47.035Z | DEBUG | geo-location received, bg: false p: {"lat":31.8585835,"lng":34.8171489,"alt":70,"timestamp":"2019-08-15T05:02:47.000Z"}
2019-08-15T05:02:47.044Z | DEBUG | Rejecting position: {"lat":31.8585835,"lng":34.8171489,"alt":70,"timestamp":"2019-08-15T05:02:47.000Z"} reason:Time difference too high: 282
2019-08-15T05:04:52.114Z | DEBUG | geo-location received, bg: false p: {"lat":31.861777,"lng":34.81084,"alt":-1,"timestamp":"2019-08-15T05:04:51.122Z"}
2019-08-15T05:04:52.168Z | DEBUG | Rejecting position for rejected: {"coords":{"accuracy":1000,"altitude":-1,"latitude":31.861777,"longitude":34.81084,"speed":-1,"heading":-1},"timestamp":1565845491122} reason: Time difference too high: 124.122
2019-08-15T05:04:57.276Z | DEBUG | geo-location received, bg: false p: {"lat":31.8626962,"lng":34.8158754,"alt":72,"timestamp":"2019-08-15T05:04:57.188Z"}
2019-08-15T05:04:57.282Z | DEBUG | Rejecting position for rejected: {"coords":{"accuracy":13.7,"altitude":72,"latitude":31.8626962,"longitude":34.8158754,"speed":14.61,"heading":4},"timestamp":1565845497188} reason: Speed too high: 80.18535031720613
2019-08-15T05:05:03.202Z | DEBUG | geo-location received, bg: false p: {"lat":31.8626962,"lng":34.8158754,"alt":72,"timestamp":"2019-08-15T05:04:58.031Z"}
2019-08-15T05:05:03.208Z | DEBUG | Validating a rejected position: {"lat":31.8626962,"lng":34.8158754,"alt":72,"timestamp":"2019-08-15T05:04:58.031Z"}
2019-08-15T05:05:03.495Z | DEBUG | Adding a new point to the recording route.
```
It can be seen that there's no location received for about 4 minutes (which is probably where I stopped) and then another gap of two minutes...
This is my app's log (it write time in ISO format so you'll need to add 3 hours to get the actual time):
[log_2019-08-15_05-28-00.357Z.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3504491/log_2019-08-15_05-28-00.357Z.txt)
The following is the logcat of the same time the app wokred:
[logcat.txt](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3504493/logcat.txt)

Any help would be appreciated - if there's a configuration I need change please let me know.

**Comment by HarelM** [comment]
I was able to reproduce it again when driving back home today:
![image](https://user-images.githubusercontent.com/3269297/63096401-829ec480-bf76-11e9-9268-ca37521e5ac9.png)
Route can be seen here:
https://israelhiking.osm.org.il/share/Z0DwafRRna

Let me know if you need more logs.
I have decided to open this as a new issue since the other issue is not related and was properly resolved.

**Comment by christocracy** [comment]
I have no idea how to correlate your times in the `logcat`.  You need to tell me the *exact* start/end time in the logcat that you're interested in.

Also, don't show me your raw `logcat`, it's too noisy with unrelated stuff.  See Wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging) and use `BackgroundGeolocation.emailLog`.

**Comment by HarelM** [comment]
The time in my logs is ISO time so just add 3 hours to get to the logcat time.
Running `adb logcat -s TSLocationManager` returned nothing, I have no idea why, the logging layer is at verbose.
The following screenshot is when using the demo app - it's more subtle but exists - after a walk I stopped and sat down for about 15 minutes and when I started walking again it manifested.
![Screenshot_2019-08-15-19-04-35-422_com transistorsoft backgroundgeolocation ionic2](https://user-images.githubusercontent.com/3269297/63117073-bba15e00-bfa3-11e9-8e83-f21a3c10c163.png)

Here's the emaillog from the app:
[background-geolocation.log](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3506780/background-geolocation.log)

Check out the following two lines - there's a gap of more than a minute after I started moving again as far as I can see from the logs
18:15 stopped walking
18:29 started walking again
```
08-15 18:29:40.813 DEBUG [BackgroundTaskService onDestroy] 
08-15 18:30:54.560 DEBUG [TrackingService a] 
```

email log also added this:
```
{
"activityRecognitionInterval": 10000,
"allowIdenticalLocations": false,
"autoSync": true,
"autoSyncThreshold": 0,
"batchSync": false,
"debug": true,
"deferTime": 0,
"desiredAccuracy": -1,
"desiredOdometerAccuracy": 100,
"disableElasticity": false,
"disableStopDetection": false,
"distanceFilter": 10,
"elasticityMultiplier": 1,
"enableHeadless": false,
"enableTimestampMeta": false,
"extras": {},
"fastestLocationUpdateInterval": -1,
"forceReloadOnBoot": false,
"forceReloadOnGeofence": false,
"forceReloadOnHeartbeat": false,
"forceReloadOnLocationChange": false,
"forceReloadOnMotionChange": false,
"forceReloadOnSchedule": false,
"foregroundService": true,
"geofenceInitialTriggerEntry": true,
"geofenceModeHighAccuracy": false,
"geofenceProximityRadius": 1000,
"geofenceTemplate": "",
"headers": {},
"headlessJobService": "com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask",
"heartbeatInterval": 60,
"httpRootProperty": "location",
"httpTimeout": 60000,
"isMoving": false,
"locationTemplate": "",
"locationTimeout": 60,
"locationUpdateInterval": 1000,
"locationsOrderDirection": "ASC",
"logLevel": 5,
"logMaxDays": 3,
"maxBatchSize": -1,
"maxDaysToPersist": 1,
"maxRecordsToPersist": -1,
"method": "POST",
"minimumActivityRecognitionConfidence": 75,
"notification": {
"layout": "",
"title": "",
"text": "Location Service activated",
"color": "",
"channelName": "TSLocationManager",
"smallIcon": "",
"largeIcon": "",
"priority": 0,
"strings": {},
"actions": []
},
"params": {
"device": {
"model": "Redmi 4X",
"platform": "Android",
"uuid": "Redmi-4X",
"version": "7.1.2",
"manufacturer": "Xiaomi",
"framework": "Cordova"
}
},
"persist": true,
"persistMode": 2,
"schedule": [],
"speedJumpFilter": 300,
"startOnBoot": false,
"stationaryRadius": 25,
"stopAfterElapsedMinutes": 0,
"stopOnStationary": false,
"stopOnTerminate": false,
"stopTimeout": 1,
"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
"url": "http:\/\/tracker.transistorsoft.com\/locations\/HarelM",
"useSignificantChangesOnly": false,
"enabled": false,
"schedulerEnabled": false,
"trackingMode": 1,
"odometer": 3378.508056640625,
"isFirstBoot": false
}
```

**Comment by christocracy** [comment]
I’m not going to calculate your time by adding offsets.  You need to tell me exact timestamps to look for.

There’s nothing wrong with your tracking.  The plugin operating as expected.

See docs Config.stopTimeout

**Comment by HarelM** [comment]
@christocracy it's really feels that you're not trying to help out here.
I'm reporting what I believe is a serious issue with how the plugin behaves and you dismiss it for technicalities?
I'm talking about the behavior **after** I resume moving.
In all three cases above there's a gap and some bad recordings after a long period of being still.
If the solution is to set the timeout to infinity in order to avoid this, that's what I'll do, but it feels like a hack and not a solution.

The last log I attached is from the `emaillog` of the demo app.
It is clear from the image that the recording that was made after I resumed movement (around 18:30) are problematic - what you are saying is that this is the expected behaior of this plugin and that it works good?!?
There's no need to calculate time differences in order to look at your app's logs.
Do you need the logcat of that relevant time as well or are your logs enough to understand what went wrong?

**Comment by christocracy** [comment]
When the plugin enters the stationary-state after stopTimeout minutes expires, *yes* it’s going to take movement of some meters before the Motion API determines you’re moving again.  Depending on the device and its quality of sensors (accelerometer, gyroscope, magnetometer) this is going to happen quicker or slower.

This is normal and expected.  Read the wiki “Philosophy of Operation”

If you set an insanely high stopTimeout, you’re going to post a future issue “[BUG] plugin consumes too much battery”.

**Comment by HarelM** [comment]
Thanks you very much for the detailed response.
I believe recording accuracy in my case is more important than battery life, having said that, I don't want the app to kill the battery.
What value do you think is a good balanced value for outdoors activity? I'm tending towards 20 minutes to keep recording on short breaks but stop for long breaks, does it sound reasonable?
Thanks again for your prompt response.
