### ISSUE TITLE
Works inside the app but not outside (in the background)

### ISSUE THREAD

**Issue by globcluster** [transistorsoft/cordova-background-geolocation-lt#983]
This is how I start the tracking in my location-tracker.service.ts file. Then I push the latitude and longitude coordinates in an array that's used to plot the polyline on top of google maps. It will only work when inside the app but not in the background. I am not seeing the tracker icon either. I follow many tutorials online but none of them seemed to work.

startTracking() {

    // Background Tracking

    const config: BackgroundGeolocationConfig = {desiredAccuracy: 0, stationaryRadius: 0, distanceFilter: 0, debug: true, stopOnTerminate: false, startForeground: true, startOnBoot: true, interval: 2000};

    this.backgroundGeolocation.configure(config).then(() => {
 
    this.backgroundGeolocation.on(BackgroundGeolocationEvents.location).subscribe((location: BackgroundGeolocationResponse) => {

      // Run update inside of Angular's zone
      this.zone.run(() => {
        this.lat = location.latitude;
        this.lng = location.longitude;
        this.alt = location.altitude;
        this.spd = location.speed;
        this.tme = location.time; 
      });

      this.trackingArray.push({ latitude: this.lat, longitude: this.lng, altitude: this.alt, speed: this.spd, time: this.tme });
        this.geolocationArray.push({ lat: this.lat, lng: this.lng });

      
    }, (err) => {

      console.log(err);

    });
  });

    // Turn ON the background-geolocation system.
    this.backgroundGeolocation.start();

**Comment by christocracy** [comment]
There is **zero tolerance** for **ignoring** the issue template.  Edit your issue to provide the *required* info and it will be re-opened.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
