### ISSUE TITLE
How to feed Lat & Long as Params for URL configured for Android Headless mode implementation?

### ISSUE THREAD

**Issue by expjes** [transistorsoft/cordova-background-geolocation-lt#984]
Hello Chris

This is not an issue but a question regarding implementing Android Headless mode as we need to get background Geolocation even when app is terminated. For that, I have gone through your solution at https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode
But I am not able to understand, how can I pass Lat & Long to my REST API URL. My REST api url is a rest web service which accepts latitude and longitude as input parameter.

Thanks!

**Comment by christocracy** [comment]
See “HTTP Guide” in the Guides section of [API docs](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html)

**Comment by expjes** [comment]
url: 'https://my-server.com/locations' what type of URL we should provide here? Can't I use my existing REST web service url? As HTTP Guide says "The BackgroundGeolocation SDK hosts its own flexible and robust native HTTP & SQLite persistence services".

**Comment by expjes** [comment]
the URL https://my-server.com/locations, you configure for URL parameter, is https://my-server.com/ the path and locations an object being passed as query param? or https://my-server.com/locations is the complete path?

**Comment by christocracy** [comment]
You’re over-thinking this.  You can *any* url you want.  Use http://foo.bar.com/banana.xyz if you want.

The plugin attaches the JSON data to the *body* of the request.  The plugin does not attach any query-params.

**Comment by christocracy** [comment]
Google “http request JSON body”, eg https://stackoverflow.com/questions/16920291/post-request-with-json-body

**Comment by christocracy** [comment]
See the Wiki [Location Data Schema](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema#http-post-schema) for the JSON payload in the http body.

**Comment by christocracy** [comment]
and you **cannot** "feed Lat & Lng" at http params, like this:
```
http://foo.bar.com/endpoint?lat=lat&lng=lng
```

query-params are for GET requests.  That's not how you send data to a server to insert into a database.  It's insecure, for one thing, since that data won't be encrypted with ssl.

If that's what your server expects, you need to modify your server to accept POST requests with the data located in the HTTP request body.

**Comment by expjes** [comment]
Thanks for all your answer. That helps.
