### ISSUE TITLE
Detect X number of positions within a radius as stationary

### ISSUE THREAD

**Issue by dawndharm** [transistorsoft/cordova-background-geolocation-lt#985]
## Your Environment
* Plugin version: 3.2.0
* Platform: Android
* OS version: 7.0 
* Device manufacturer / model: Redmi note 4
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
            reset: true,
            debug: false,
            logLevel: bgGeo.LOG_LEVEL_OFF,
            desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
            distanceFilter: 3,
            allowIdenticalLocations: true,
            url: 'https://trackdata.domain.com/track/record',
            autoSync: true,
            stopOnTerminate: false,
            enableHeadless: true,
            foregroundService: true,
            notification: { title: "AppName is tracking.", text: "Your locations is being tracked by AppName." },
            heartbeatInterval: 60,
            elasticityMultiplier: 1.5,
            startOnBoot: true,
            preventSuspend: true,
            headers: {
                "X-MODULE": "tracking",
                "X-OPERATION": "track",
                "Authorization": `Bearer ${loginToken}`,
            },
            extras: {
                "cordova": device.cordova,
                "model": device.model,
                "platform": device.platform,
                "uuid": device.uuid,
                "version": device.version
            },
            schedule: [
                '1-7 0:00-23:59'
            ]
}
```

## Expected Behavior

Is it possible to add a feature so that multiple similar location (ie within a radius) be detected as stationary and a state change event is fired.
## Actual Behavior

only still event from google services are fired as still event

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Not Relevant 
```

</details>

**Comment by christocracy** [comment]
Please describe your reasoning for this.

**Comment by dawndharm** [comment]
While implementing it seems many times that the state is not changing to even still after stopped for an hour. that is why I checked this possibility

**Comment by christocracy** [comment]
This likely due to the vendor’s os throttling events in the background.  I’ve witnessed only on my Huawei P20 (1 of 12 of my test devices).

I witness all these events fire at once once I unlock the device back at the office.

See http://dontkillmyapp.com
