### ISSUE TITLE
Need More Control On HTTP Posting

### ISSUE THREAD

**Issue by dawndharm** [transistorsoft/cordova-background-geolocation-lt#986]
## Your Environment
* Plugin version: 3.2.0
* Platform: Android
* OS version: 7.0 
* Device manufacturer / model: Redmi note 4
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
            reset: true,
            debug: false,
            logLevel: bgGeo.LOG_LEVEL_OFF,
            desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
            distanceFilter: 3,
            allowIdenticalLocations: true,
            url: 'https://trackdata.domain.com/track/record',
            autoSync: true,
            stopOnTerminate: false,
            enableHeadless: true,
            foregroundService: true,
            notification: { title: "AppName is tracking.", text: "Your locations is being tracked by AppName." },
            heartbeatInterval: 60,
            elasticityMultiplier: 1.5,
            startOnBoot: true,
            preventSuspend: true,
            headers: {
                "X-MODULE": "tracking",
                "X-OPERATION": "track",
                "Authorization": `Bearer ${loginToken}`,
            },
            extras: {
                "cordova": device.cordova,
                "model": device.model,
                "platform": device.platform,
                "uuid": device.uuid,
                "version": device.version
            },
            schedule: [
                '1-7 0:00-23:59'
            ]
}
```

## Expected Behavior

While working with the plugin. it requires me to to just get the location on the app more frequently than it needs the location synced to the server. it would be great if you could add three parameters 
1) HTTP Post ratio Which posts/logs only one in X entries. You may just buffer X number of positions before adding one to the database.
2) And option to stop logging position to db but still trigger location events.
3) Any variable in the posted data to differentiate if the data was received while app is running or in the headless mode.

## Actual Behavior

No options available
## Context

I am trying to implement a location logging system where the user can have location updated in the app and only log when he wants to be seen by others
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>1. HTTP Post ratio Which posts/logs only one in X entries.

See the [HTTP Guide](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html) in the 📚 **Help** section in the API docs.

The guide references [`Config.autoSyncThreshold`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#autosyncthreshold), which you may be interested in.

>2. And option to stop logging position to db but still trigger location events.

See [`Config.persistMode`](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#persistmode)

```javascript
BackgroundGeolocation.setConfig({
  persistMode: BackgroundGeolocation.PERSIST_MODE_NONE
});
```

>3.  Any variable in the posted data to differentiate if the data was received while app is running or in the headless mode.

In your custom [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode) extension:

```java
// In headless 
public class BackgroundGeolocationHeadlessTask  {

    @Subscribe(threadMode=ThreadMode.MAIN)
    public void onHeadlessTask(HeadlessEvent event) {
        String name = event.getName();
        TSLog.logger.debug("\uD83D\uDC80  event: " + event.getName());
        TSLog.logger.debug("- event: " + event.getEvent());

        if (name.equals(BackgroundGeolocation.EVENT_TERMINATE)) {
            TSConfig config = TSConfig.getInstance(event.getContext());
            JSONObject params = config.getParams();
            try {
                params.put("is_headless", true);
            } catch (JSONException e) {}                       
        }
    }
}
```

**Comment by dawndharm** [comment]
Thanks for the update. But i still think the first feature would be great to reduce post size even though I can handle it at server side with the option you suggested

**Comment by christocracy** [comment]
You *could* do that yourself with your own counter incremented in `location` event, using #setConfig to adjust `persistMode` as desired.  In headless-mode `EVENT_TERMINATE`, you would take care to adjust the `distanceFilter` to a higher level your server is comfortable with (since there’s no UI to worry about).

**Comment by christocracy** [comment]
In which case, you wouldn’t use `autoSyncThreshold`

**Comment by dawndharm** [comment]
On ios there are a lot of notifications coming. can we restrict it?

**Comment by christocracy** [comment]
Maybe you’re talking about the “Debug Notifications”.  See docs `Config.debug`
