### ISSUE TITLE
Typo in API Description

### ISSUE THREAD

**Issue by bloigge** [transistorsoft/cordova-background-geolocation-lt#988]
Hi,

Not really a problem with the plugin - just a notice on your API Description:
The method is called `getState()` not `state()`

![image](https://user-images.githubusercontent.com/7089726/64008266-0e3b5800-cb16-11e9-8a2f-8bce2931082c.png)

**Comment by christocracy** [comment]
Docs can be fixed by editing [`src/ionic/declarations/BackgroundGeolocation.d.ts`](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/ionic/declarations/BackgroundGeolocation.d.ts#L812) and submitting PR.  However, I've fixed this one on my local copy already.
