### ISSUE TITLE
Wrong Interface Definition of property in MotionActivityEvent

### ISSUE THREAD

**Issue by bloigge** [transistorsoft/cordova-background-geolocation-lt#989]
In your interface definition of the `MotionActivityEvent` there is a property called `activity` - which should be named `type`

![image](https://user-images.githubusercontent.com/7089726/64028071-43f63600-cb42-11e9-8c83-1e785791b8e8.png)

**Comment by christocracy** [comment]
The mistake was specifying that `location.activity` implements the `MotionActivityEvent` interface, it doesn't, unfortunately.
