### ISSUE TITLE
Not working after app terminate on iPhone 5 simulator

### ISSUE THREAD

**Issue by aks0020** [transistorsoft/cordova-background-geolocation-lt#99]
Here are some settings:
```
desiredAccuracy: 0,
stationaryRadius: 50,
distanceFilter: 500,
activityType: 'AutomotiveNavigation',
disableMotionActivityUpdates: true
```
However It works on iPhone 5s/6/6 plus (iOS 9.2).

**Comment by christocracy** [comment]
With latest version from master, set

startOnBoot: true

iPhone 5 shouldn't matter

On Saturday, April 9, 2016, Akash <notifications@github.com> wrote:

> Here are some settings:
>
> desiredAccuracy: 0,
> stationaryRadius: 50,
> distanceFilter: 500,
> activityType: 'AutomotiveNavigation',
> disableMotionActivityUpdates: true
>
> However It works in iPhone 5s/6/6 plus.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/99>
>


-- 
Snet form Gmail Mobile

**Comment by aks0020** [comment]
is it required even if I just kill the app & not restart the phone ?

**Comment by christocracy** [comment]
If you don't want tracking to stop when user kills app, then you must set:

stopOnTerminate: false

On Saturday, April 9, 2016, Akash <notifications@github.com> wrote:

> is it required even if I just kill the app & not restart the phone ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/99#issuecomment-207776781>
>


-- 
Snet form Gmail Mobile

**Comment by aks0020** [comment]
I forgot to mention that property but I have added that `stopOnTerminate: false`

**Comment by christocracy** [comment]
Then everything is fine and it will work.

The device will of course require a significant change event to resume
tracking after reboot / app close; it cannot resume immediately.  The
device must move typically 2-3 city blocks

On Saturday, April 9, 2016, Akash <notifications@github.com> wrote:

> I forgot to mention that property but I have added that stopOnTerminate:
> false
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/99#issuecomment-207776877>
>


-- 
Snet form Gmail Mobile

**Comment by aks0020** [comment]
It might be temporary issue but after adding/removing `startOnBoot` it works now in iPhone 5 simulator even if `startOnBoot` is `false`.

**Comment by christocracy** [comment]
StartOnBoot is 2 days old.  Are you using latest version from master?

On Saturday, April 9, 2016, Akash <notifications@github.com> wrote:

> It might be temporary issue but after adding/removing startOnBoot it
> works now in iPhone 5 simulator even if startOnBoot is false.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/99#issuecomment-207782387>
>


-- 
Snet form Gmail Mobile

**Comment by aks0020** [comment]
No I have added from master on 5th Apr, but it might be temporary issue now it works at least on simulator.
