### ISSUE TITLE
Location is not received after initial location

### ISSUE THREAD

**Issue by HarelM** [transistorsoft/cordova-background-geolocation-lt#991]
## Your Environment
* Plugin version: 3.0.8
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung galaxy S8
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): android 7.1.4
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
reset: true,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            allowIdenticalLocations: false,
            distanceFilter: 5,
            notification: {
                text: this.resources.runningInBackground,
                title: this.resources.israelHikingMap
            },
            debug: !this.runningContextService.isProduction,
            stopOnTerminate: true,
            foregroundService: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
```

## Expected Behavior
Location should update while moving

## Actual Behavior
Updates have started only about 5 minutes after the initial location was received

## Steps to Reproduce
1. Download and in stall https://ci.appveyor.com/project/IsraelHikingHost/site/builds/27131558/job/eian4yotodemhx8b/artifacts
2. Click the cross arrows on the left side
3. Move around

## Context
Show where the user went

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
{
"activityRecognitionInterval": 10000,
"allowIdenticalLocations": false,
"autoSync": true,
"autoSyncThreshold": 0,
"batchSync": false,
"debug": false,
"deferTime": 0,
"desiredAccuracy": -1,
"desiredOdometerAccuracy": 100,
"disableElasticity": false,
"disableLocationAuthorizationAlert": false,
"disableStopDetection": false,
"distanceFilter": 5,
"elasticityMultiplier": 1,
"enableHeadless": false,
"enableTimestampMeta": false,
"extras": {},
"fastestLocationUpdateInterval": -1,
"forceReloadOnBoot": false,
"forceReloadOnGeofence": false,
"forceReloadOnHeartbeat": false,
"forceReloadOnLocationChange": false,
"forceReloadOnMotionChange": false,
"forceReloadOnSchedule": false,
"foregroundService": true,
"geofenceInitialTriggerEntry": true,
"geofenceModeHighAccuracy": false,
"geofenceProximityRadius": 1000,
"geofenceTemplate": "",
"headers": {},
"headlessJobService": "com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask",
"heartbeatInterval": -1,
"httpRootProperty": "location",
"httpTimeout": 60000,
"isMoving": true,
"locationTemplate": "",
"locationTimeout": 60,
"locationUpdateInterval": 1000,
"locationsOrderDirection": "ASC",
"logLevel": 5,
"logMaxDays": 3,
"maxBatchSize": -1,
"maxDaysToPersist": 1,
"maxRecordsToPersist": -1,
"method": "POST",
"minimumActivityRecognitionConfidence": 75,
"notification": {
"layout": "",
"title": "מפת הטיולים הפתוחה",
"text": "רצה ברקע",
"color": "",
"channelName": "TSLocationManager",
"smallIcon": "",
"largeIcon": "",
"priority": 0,
"strings": {},
"actions": []
},
"params": {},
"persist": true,
"persistMode": 2,
"schedule": [],
"scheduleUseAlarmManager": false,
"speedJumpFilter": 300,
"startOnBoot": false,
"stationaryRadius": 25,
"stopAfterElapsedMinutes": 0,
"stopOnStationary": false,
"stopOnTerminate": true,
"stopTimeout": 5,
"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
"url": "",
"useSignificantChangesOnly": false,
"enabled": true,
"schedulerEnabled": false,
"trackingMode": 1,
"odometer": 615.7450561523438,
"isFirstBoot": false
}
```
Time: 17:49-17:55
[background-geolocation.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3575641/background-geolocation.log.gz)

</details>

![image](https://user-images.githubusercontent.com/3269297/64275172-aa69c280-cf4d-11e9-9d87-185fd010024f.png)

P.S: I was trying to use the `BackgroundGeolocation.logger` but it doesn't seem to report the logging I'm adding when using `emailLog`. is the logger available before I start BackgroundGeolocation?

**Comment by HarelM** [comment]
I have tested this morning the bg geolocation app instead of my own and I get the red circle again.
I have recently replaced my phone.
The following is the image:
![image](https://user-images.githubusercontent.com/3269297/64314749-c0f93380-cfb8-11e9-8d62-b168be03d420.png)
I have looked at issue #957 and verified that all my HW is working as expected.
Bare in mind that this is a new phone, If this will happen to every user that will use my app they will not trust my app which is bad...
Below is the emailog of this incident.
[background-geolocation.log.gz](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3577594/background-geolocation.log.gz)
Is there a configuration I can change to resolve this?

**Comment by christocracy** [comment]
What's so unusual about the red circle to you?  Do you know what that is?

**Comment by HarelM** [comment]
As far as I understood, it's a ststionary geofence, which means the motion API wont let me know of a change in the location until I leave this circle. I would like to avoid this behavior in order to accurately record the user position.

**Comment by christocracy** [comment]
Android uses Motion API to determine when the device is moving.  When the motion API says the device is moving, the plugin will begin tracking.

The circle means nothing on Android.  It's just a visual cue that the plugin is in the *stationary* state.

**Comment by HarelM** [comment]
So, how can I improve this behavior? This is the second phone I have that is suffering from this. And I only tested this plugging on two phones... I'm guessing other user will probably experience this too...

**Comment by christocracy** [comment]
As I’ve told you, I test regularly on 11 devices with great success.  This plugin has thousands of users paying customers over the last 4 years, some with deployed user-bases of millions of users.

Let me know if you want a refund.

**Comment by christocracy** [comment]
And see http://dontkillmyapp.com for your device
