### ISSUE TITLE
Access to the product dashboard

### ISSUE THREAD

**Issue by sc0ttdav3y** [transistorsoft/cordova-background-geolocation-lt#992]
Hi,

I've just taken over a project using this plugin from a previous developer at the company, and I cannot access the product dashboard to manage our licence keys (http://www.transistorsoft.com/shop/customers).

Can you please provide access?  Contact me directly at sdavey@datalink.com.au if you prefer.

Thanks, Scott

**Comment by christocracy** [comment]
Please contact me about this.  See the chat widget at https://transistorsoft.com
