### ISSUE TITLE
relaunch app when terminated by User 

### ISSUE THREAD

**Issue by Buddies2019** [transistorsoft/cordova-background-geolocation-lt#993]
How I can relaunch my app when it will terminate by user through background Location Plugin?

**Comment by Buddies2019** [comment]
Hi Chris Kindly Help Me here

**Comment by christocracy** [comment]
First of all **NO NOT IGNORE THE ISSUE TEMPLATE**.  Did notice the warning at the top before you just deleted the template?
![](https://dl.dropbox.com/s/drx1unn8ivs7j75/Screenshot%202019-09-16%2010.06.25.png?dl=1)

>How I can relaunch my app when it will terminate by user through background Location Plugin?

Why?  Do you know that [Android Q now forbids](https://developer.android.com/guide/components/activities/background-starts) this?

**Comment by christocracy** [comment]
And since you've purchased a license, you should use the [private repo](https://github.com/transistorsoft/cordova-background-geolocation), not this public one.

**Comment by Buddies2019** [comment]
background Plugin working fine , my concern is how relaunch app when user terminates the app ?

**Comment by christocracy** [comment]
Why do you want to “relaunch” the app?

**Comment by Buddies2019** [comment]
our app is online taxi booking , when app open we received a request from the particular app regard vehicle available so accordingly we assign the trip to the  particular vehicle

**Comment by Buddies2019** [comment]
if unfortunately, user terminate the app we don't the vehicle status.

**Comment by christocracy** [comment]
You cannot relaunch the Android app.  If you have business logic to perform in the terminated state, that’s what “Android Headless Mode” is for.

https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode

**Comment by Buddies2019** [comment]
we tried this but it will work if any one of event happened, its take long time to launch we need real time status

**Comment by christocracy** [comment]
Your only option to implement custom logic in terminated state is “Android Headless Mode”.  That’s it, that’s all.  Period.

> its take long time to launch

There’s nothing to launch.  The plugin’s services remain running.  When events occur, they’re fired *immediately* into your custom headless class.  Now go get your hands dirty and start writing some Android Java in your custom headless class

**Comment by Buddies2019** [comment]
thanks we will try the same .
