### ISSUE TITLE
motionchange event not firing on stationary

### ISSUE THREAD

**Issue by aggsmart** [transistorsoft/cordova-background-geolocation-lt#997]
## Your Environment
* Plugin version: 3.2.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy Active Tab 2
* Cordova version (`cordova -v`): 7.1
* Cordova platform version (`cordova platform ls`): 9
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
reset: true,
        desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        debug: false,  // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        url: endpoint,
		extras: {type: 'tracking', userID: getVariable('userID'), vehicleID: getVariable('vehicleID'), driverName: getVariable('driverName'), driverNo: getVariable('driverNo'), activeJob: getVariable('activeJob'), serial: IMEI},
        method: 'POST',
        autoSync: true,
        maxDaysToPersist: 2,
```

## Expected Behavior
When the device is stationary, the motionchange event should fire to moving=false after 5 minutes. 

## Actual Behavior

When stationary, no motionchange event is fired. And no GPS update position is sent as the travelled distance is less than 50m.

## Context
The tablets are being used in HGV Cement Trucks. When the truck is stationary the engine is still running. I am wondering if the vibration of the engine running is stopping the motionchange event. But, I would have thought modern Android devices would use lateral G sensors, not just motion sensors. Can anyone offer advice on how to detect the stationary vehicle accurately?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki Debugging and observe your logs.
