### ISSUE TITLE
Is it necessary to turn off battery optimization to get location updates continuously ? 

### ISSUE THREAD

**Issue by Venkatesh-Veersoftsolutions** [transistorsoft/cordova-background-geolocation-lt#998]
Geo location is not sending events while the app is running in background, after some time the app is coming back to application main page.Thank you.
-->
## Your Environment
* Plugin version:3.0.8
* Platform:  Android
* OS version:8.1.0
* Device manufacturer / model: Mi
* Cordova version (`cordova -v`):  9.0.0 
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config provided to `#ready`:
BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 0,
      locationUpdateInterval: 300000,
      startOnBoot: true,
      foregroundService: true,
      url: url,
      autoSync: true,
      params: {
        tenantId: tenantId,
        branchId: branchId,
        vsLoginToken: vsLoginToken,
      },
      allowIdenticalLocations: true,
      heartbeatInterval: 300,
      stopOnStationary: false,
      reset: true
    }, (state) => {
      console.log('- Configure success: ', state);
      this.zone.run(() => {
      });
    });

## Expected Behavior
Application should alive for long time in background and have to send location updates continuously.

## Actual Behavior
Suddenly stopping sending updates of location, and application is closing in background

## Debug logs

- Android: $ adb logcat:"Uncaught Error: Failed to execute 'construct' on 'CustomElementConstructor': The provided callback is no longer runnable.", source: http://localhost/vendor.js (70156)

 Received unexpected kModeProcessNoContext
-->

**Comment by christocracy** [comment]
See wiki Debugging.
